### ISSUE TITLE
not getting location in the response upon CompleteMultipartUpload using the seaweed s3

### ISSUE THREAD

**Issue by dorsany** [chrislusf/seaweedfs#1002]
**Describe the bug**
We are using AWS_SDK (node js) in order to use the S3 REST API that the Seaweed is implementing.
The AWS_SDK by default breaks down any file over 5mb into ```multipart``` upload.
When the S3 REST API completes a multipart upload it should return a ```location``` in the result. however, it fails to do so in the Seaweed implementation.

its seems that the seaweed implement the ```CompleteMultipartUpload``` here:
https://github.com/chrislusf/seaweedfs/wiki/Amazon-S3-API

**Expected behavior**
return ```Location``` when using ```Complete Multipart Upload``` 
like here:
![image](https://user-images.githubusercontent.com/36127093/60812889-31dbc500-a19b-11e9-80de-7733eac69b4b.png)

ref:
https://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadComplete.html (see sample response)

**Screenshots**
initiate:
![image](https://user-images.githubusercontent.com/36127093/60813064-9139d500-a19b-11e9-8a7d-6f95778f9b6f.png)

upload part 1:
![image](https://user-images.githubusercontent.com/36127093/60813070-98f97980-a19b-11e9-83c4-092586c74f5c.png)

upload part 2:
![image](https://user-images.githubusercontent.com/36127093/60813091-9f87f100-a19b-11e9-8618-c12827eccec4.png)

CompleteMultipartUpload:
![image](https://user-images.githubusercontent.com/36127093/60813129-b1699400-a19b-11e9-96ee-4b002144681c.png)

**Additional context**
version: 1.30

**Comment by chrislusf** [comment]
Thanks for the detailed issue report! Very helpful!
