### ISSUE TITLE
Vacuuming causes requests to take a long time

### ISSUE THREAD

**Issue by Minikloon** [chrislusf/seaweedfs#1003]
We're running Seaweed 30GB 1.34 with 2 replicated volume servers on Linux.

A few times an hour Seaweed requests time out on our clients (they do reply correctly after 8+ seconds). These events coincide with "Commiting volume X vacuuming..." messages.

On both volume servers there are errors when it happens:

**Volume 1**
> I0709 00:01:02 79201 volume_vacuum.go:43] Committing volume 5 vacuuming...
I0709 00:01:03 79201 volume_server_handlers_read.go:71] read /5,030ce3f155663d error: invalid argument
I0709 00:01:03 79201 volume_loading.go:82] loading index data/5.idx to memory readonly false
I0709 00:02:28 79201 volume_vacuum.go:43] Committing volume 1 vacuuming...
I0709 00:02:28 79201 volume_server_handlers_read.go:71] read /1,10c2b6b2e64295 error: invalid argument
I0709 00:02:28 79201 volume_server_handlers_read.go:71] read /1,0aacc504a9c08f error: invalid argument
I0709 00:02:28 79201 volume_server_handlers_read.go:71] read /1,0679ab493ac835 error: invalid argument
I0709 00:02:29 79201 volume_loading.go:82] loading index data/1.idx to memory readonly false
I0709 00:28:38 79201 volume_vacuum.go:43] Committing volume 3 vacuuming...
I0709 00:28:39 79201 volume_server_handlers_read.go:71] read /3,0cd787fdf4627e error: invalid argument
I0709 00:28:39 79201 volume_loading.go:82] loading index data/3.idx to memory readonly false
I0709 00:28:39 79201 volume_server_handlers_read.go:71] read /3,fd211ca82a5c error: EOF

**Volume 2**
> I0709 00:01:20 31082 volume_loading.go:82] loading index data/5.idx to memory readonly false
I0709 00:02:44 31082 volume_vacuum.go:43] Committing volume 1 vacuuming...
I0709 00:02:44 31082 volume_server_handlers_read.go:71] read /1,311a8cf3d5f9 error: invalid argument
I0709 00:02:44 31082 volume_server_handlers_read.go:71] read /1,0e3deb1e82acaf error: invalid argument
I0709 00:02:45 31082 volume_server_handlers_read.go:71] read /1,04db172bb74c68 error: invalid argument
I0709 00:02:45 31082 volume_server_handlers_read.go:71] read /1,2b286d50c65c error: invalid argument
I0709 00:02:45 31082 volume_server_handlers_read.go:71] read /1,0a1cbf347846ec error: invalid argument
I0709 00:02:46 31082 volume_server_handlers_read.go:71] read /1,10a519d5013499 error: invalid argument
I0709 00:02:46 31082 volume_server_handlers_read.go:71] read /1,03a6c44d7bee9d error: invalid argument
I0709 00:02:47 31082 volume_server_handlers_read.go:71] read /1,0abe2d4dc0df46 error: invalid argument
I0709 00:02:47 31082 volume_loading.go:82] loading index data/1.idx to memory readonly false
I0709 00:02:47 31082 volume_server_handlers_read.go:71] read /1,1125c6d5f0bc9a error: EOF
I0709 00:02:48 31082 volume_server_handlers_read.go:71] read /1,10a33d623923e0 error: File Entry Not Found. offset 3161502640, Needle id 6097913394784596521 expected size 538059729 Memory 38935
I0709 00:02:48 31082 volume_server_handlers_read.go:71] read /1,0b67f9285cb44a error: EOF
I0709 00:02:49 31082 volume_server_handlers_read.go:71] read /1,02767001f3abc2 error: File Entry Not Found. offset 3718582776, Needle id 18277468614684896305 expected size 690246809 Memory 80877
I0709 00:28:52 31082 volume_vacuum.go:43] Committing volume 3 vacuuming...
I0709 00:28:52 31082 volume_server_handlers_read.go:71] read /3,0e527df7feb29d error: invalid argument
I0709 00:28:52 31082 volume_server_handlers_read.go:71] read /3,0a8c8826f83c93 error: invalid argument
I0709 00:28:52 31082 volume_server_handlers_read.go:71] read /3,116b10f2d1cff1 error: invalid argument
I0709 00:28:52 31082 volume_server_handlers_read.go:71] read /3,030c94630da3f5 error: invalid argument
I0709 00:28:52 31082 volume_server_handlers_read.go:71] read /3,0e6338b246588b error: invalid argument
I0709 00:28:53 31082 volume_server_handlers_read.go:71] read /3,04f29e57ed8249 error: invalid argument
I0709 00:28:54 31082 volume_server_handlers_read.go:71] read /3,0f74ccf38a067b error: invalid argument
I0709 00:28:55 31082 volume_loading.go:82] loading index data/3.idx to memory readonly false

**Master**
> I0709 00:00:12 76758 topology_vacuum.go:95] Complete Committing vacuum 4 on chi-hp-goliath3:8883
I0709 00:00:12 76758 volume_layout.go:237] Volume 5 becomes unwritable
I0709 00:00:12 76758 topology_vacuum.go:53] 1 Start vacuuming 5 on chi-hp-goliath3:8883
I0709 00:00:12 76758 topology_vacuum.go:53] 0 Start vacuuming 5 on chi-hp-goliath4:8883
I0709 00:00:52 76758 topology_vacuum.go:64] Complete vacuuming 5 on chi-hp-goliath4:8883
I0709 00:01:02 76758 topology_vacuum.go:64] Complete vacuuming 5 on chi-hp-goliath3:8883
I0709 00:01:02 76758 topology_vacuum.go:84] Start Committing vacuum 5 on chi-hp-goliath4:8883
I0709 00:01:18 76758 topology_vacuum.go:95] Complete Committing vacuum 5 on chi-hp-goliath4:8883
I0709 00:01:18 76758 volume_layout.go:249] Volume 5 becomes writable
I0709 00:01:18 76758 topology_vacuum.go:84] Start Committing vacuum 5 on chi-hp-goliath3:8883
I0709 00:01:33 76758 topology_vacuum.go:95] Complete Committing vacuum 5 on chi-hp-goliath3:8883
I0709 00:01:34 76758 volume_layout.go:237] Volume 1 becomes unwritable
I0709 00:01:34 76758 topology_vacuum.go:53] 1 Start vacuuming 1 on chi-hp-goliath3:8883
I0709 00:01:34 76758 topology_vacuum.go:53] 0 Start vacuuming 1 on chi-hp-goliath4:8883
I0709 00:02:13 76758 topology_vacuum.go:64] Complete vacuuming 1 on chi-hp-goliath4:8883
I0709 00:02:28 76758 topology_vacuum.go:64] Complete vacuuming 1 on chi-hp-goliath3:8883
I0709 00:02:28 76758 topology_vacuum.go:84] Start Committing vacuum 1 on chi-hp-goliath4:8883
I0709 00:02:44 76758 topology_vacuum.go:95] Complete Committing vacuum 1 on chi-hp-goliath4:8883
I0709 00:02:44 76758 volume_layout.go:249] Volume 1 becomes writable
I0709 00:02:44 76758 topology_vacuum.go:84] Start Committing vacuum 1 on chi-hp-goliath3:8883
I0709 00:02:59 76758 topology_vacuum.go:95] Complete Committing vacuum 1 on chi-hp-goliath3:8883
I0709 00:27:38 76758 volume_layout.go:237] Volume 3 becomes unwritable
I0709 00:27:38 76758 topology_vacuum.go:53] 1 Start vacuuming 3 on chi-hp-goliath3:8883
I0709 00:27:38 76758 topology_vacuum.go:53] 0 Start vacuuming 3 on chi-hp-goliath4:8883
I0709 00:28:18 76758 topology_vacuum.go:64] Complete vacuuming 3 on chi-hp-goliath4:8883
I0709 00:28:38 76758 topology_vacuum.go:64] Complete vacuuming 3 on chi-hp-goliath3:8883
I0709 00:28:38 76758 topology_vacuum.go:84] Start Committing vacuum 3 on chi-hp-goliath4:8883
I0709 00:28:52 76758 topology_vacuum.go:95] Complete Committing vacuum 3 on chi-hp-goliath4:8883
I0709 00:28:52 76758 volume_layout.go:249] Volume 3 becomes writable
I0709 00:28:52 76758 topology_vacuum.go:84] Start Committing vacuum 3 on chi-hp-goliath3:8883
I0709 00:29:07 76758 topology_vacuum.go:95] Complete Committing vacuum 3 on chi-hp-goliath3:8883

Here is a view into the frequency of these events:
![image](https://user-images.githubusercontent.com/979743/60859918-44c5b800-a1e2-11e9-87a7-0e7511427e65.png)

The spikes all match logging outputs from vacuum and volume_server_handlers_read errors.

Any help would be greatly appreciated.

**Comment by chrislusf** [comment]
Please follow the issue template. What're your startup commands?

**Comment by Minikloon** [comment]
./weed master -ip=chi-hp-goliath3 -defaultReplication=001
./weed volume -dir="data" -max=5 -mserver="chi-hp-goliath3:9333" -ip="chi-hp-goliath3"  -port=8883
./weed volume -dir="data" -max=5 -mserver="chi-hp-goliath3:9333" -ip=chi-hp-goliath4 -port=8883

The names are defined in the hostfiles.

Just upgraded to 1.41, will report if problems show again.

**Comment by Minikloon** [comment]
The issue is still ongoing with 1.41.

Here are the console outputs for master and volume1:

**Master**
> 0709 04:19:27 45571 volume_layout.go:237] Volume 4 becomes unwritable
I0709 04:19:27 45571 topology_vacuum.go:53] 1 Start vacuuming 4 on chi-hp-goliath3:8883
I0709 04:19:27 45571 topology_vacuum.go:53] 0 Start vacuuming 4 on chi-hp-goliath4:8883
I0709 04:19:59 45571 topology_vacuum.go:64] Complete vacuuming 4 on chi-hp-goliath4:8883
I0709 04:20:16 45571 topology_vacuum.go:64] Complete vacuuming 4 on chi-hp-goliath3:8883
I0709 04:20:16 45571 topology_vacuum.go:84] Start Committing vacuum 4 on chi-hp-goliath4:8883
I0709 04:20:31 45571 topology_vacuum.go:95] Complete Committing vacuum 4 on chi-hp-goliath4:8883
I0709 04:20:31 45571 volume_layout.go:249] Volume 4 becomes writable
I0709 04:20:31 45571 topology_vacuum.go:84] Start Committing vacuum 4 on chi-hp-goliath3:8883
I0709 04:20:46 45571 topology_vacuum.go:95] Complete Committing vacuum 4 on chi-hp-goliath3:8883

**Volume 1**
> I0709 04:20:31 43843 volume_vacuum.go:45] Committing volume 4 vacuuming...
I0709 04:20:31 43843 volume_server_handlers_read.go:92] read /4,0278c81d6649fc isNormalVolume true error: invalid argument
I0709 04:20:31 43843 volume_server_handlers_read.go:92] read /4,4ba148e3b982 isNormalVolume true error: invalid argument
I0709 04:20:31 43843 volume_server_handlers_read.go:92] read /4,044148e1ca3b83 isNormalVolume true error: invalid argument
I0709 04:20:31 43843 volume_server_handlers_read.go:92] read /4,0fe27febee793a isNormalVolume true error: invalid argument
I0709 04:20:31 43843 volume_server_handlers_read.go:92] read /4,114d42121afdfb isNormalVolume true error: invalid argument
I0709 04:20:32 43843 volume_server_handlers_read.go:92] read /4,0fa0330b13cc1f isNormalVolume true error: invalid argument
I0709 04:20:32 43843 volume_server_handlers_read.go:92] read /4,108e6105fe5b69 isNormalVolume true error: invalid argument
I0709 04:20:32 43843 volume_server_handlers_read.go:92] read /4,0e579aa3cc6d20 isNormalVolume true error: invalid argument
I0709 04:20:32 43843 volume_server_handlers_read.go:92] read /4,0fc1f82a9ae4d1 isNormalVolume true error: invalid argument
I0709 04:20:33 43843 volume_loading.go:83] loading index data/4.idx to memory readonly false
I0709 04:20:33 43843 volume_server_handlers_read.go:92] read /4,0f71df478eae96 isNormalVolume true error: EOF
I0709 04:22:21 43843 volume_server_handlers_read.go:92] read /5,1183049eb3f414 isNormalVolume true error: not found
I0709 04:22:33 43843 volume_server_handlers_read.go:92] read /4,118300c7be02d1 isNormalVolume true error: not found

**Comment by chrislusf** [comment]
for volume servers, use "-index=leveldb"

**Comment by Minikloon** [comment]
Okay with -index=leveldb there are still spikes in response time matching with vacuuming, but they are much smaller and do not exceed our time out threshold anymore.

**Volume 2 startup logs**
> [hypixel@chi-hp-goliath4 ~/weed_volume2]$ ./weed volume -dir="data" -max=5 -mserver="chi-hp-goliath3:9333" -ip=chi-hp-goliath4 -port=8883 -index=leveldb
I0709 09:14:31 48163 config.go:28] Reading : Config File "security" Not Found in "[/home/hypixel/weed_volume2 /home/hypixel/.seaweedfs /etc/seaweedfs]"
I0709 09:14:31 48163 file_util.go:19] Folder data Permission: -rwxrwxr-x
I0709 09:14:31 48163 volume_loading.go:88] loading leveldb data/2.ldb
I0709 09:14:31 48163 volume_loading.go:88] loading leveldb data/3.ldb
I0709 09:14:31 48163 volume_loading.go:88] loading leveldb data/1.ldb
I0709 09:14:31 48163 volume_loading.go:88] loading leveldb data/4.ldb
I0709 09:14:31 48163 needle_map_leveldb.go:28] Start to Generate data/3.ldb from data/3.idx
I0709 09:14:31 48163 needle_map_leveldb.go:28] Start to Generate data/4.ldb from data/4.idx
I0709 09:14:31 48163 needle_map_leveldb.go:28] Start to Generate data/2.ldb from data/2.idx
I0709 09:14:31 48163 volume_loading.go:88] loading leveldb data/5.ldb
I0709 09:14:31 48163 needle_map_leveldb.go:28] Start to Generate data/5.ldb from data/5.idx
I0709 09:14:31 48163 needle_map_leveldb.go:28] Start to Generate data/1.ldb from data/1.idx
I0709 09:14:34 48163 needle_map_leveldb.go:30] Finished Generating data/4.ldb from data/4.idx
I0709 09:14:34 48163 needle_map_leveldb.go:30] Finished Generating data/2.ldb from data/2.idx
I0709 09:14:34 48163 needle_map_leveldb.go:30] Finished Generating data/3.ldb from data/3.idx
I0709 09:14:34 48163 needle_map_leveldb.go:30] Finished Generating data/1.ldb from data/1.idx
I0709 09:14:34 48163 needle_map_leveldb.go:30] Finished Generating data/5.ldb from data/5.idx
I0709 09:14:34 48163 disk_location.go:68] data file data/4.dat, replicaPlacement=001 v=3 size=4661392272 ttl=
I0709 09:14:34 48163 disk_location.go:68] data file data/1.dat, replicaPlacement=001 v=3 size=4525412744 ttl=
I0709 09:14:34 48163 disk_location.go:68] data file data/3.dat, replicaPlacement=001 v=3 size=4441438872 ttl=
I0709 09:14:34 48163 disk_location.go:68] data file data/2.dat, replicaPlacement=001 v=3 size=4550975280 ttl=
I0709 09:14:34 48163 disk_location.go:68] data file data/5.dat, replicaPlacement=001 v=3 size=4546324608 ttl=
I0709 09:14:34 48163 disk_location.go:109] Store started on dir: data with 5 volumes max 5
I0709 09:14:34 48163 disk_location.go:112] Store started on dir: data with 0 ec shards
I0709 09:14:34 48163 volume.go:162] Start Seaweed volume server 30GB 1.41 at 0.0.0.0:8883
I0709 09:14:34 48163 volume_grpc_client_to_master.go:24] Volume server start with seed master nodes: [chi-hp-goliath3:9333]
I0709 09:14:34 48163 volume_grpc_client_to_master.go:68] Heartbeat to: chi-hp-goliath3:9333

**Volume 2 vacuuming events**
> I0709 10:02:22 48163 volume_vacuum.go:45] Committing volume 4 vacuuming...
I0709 10:02:23 48163 volume_loading.go:88] loading leveldb data/4.ldb
I0709 10:02:23 48163 needle_map_leveldb.go:28] Start to Generate data/4.ldb from data/4.idx
I0709 10:02:24 48163 needle_map_leveldb.go:30] Finished Generating data/4.ldb from data/4.idx
I0709 10:03:20 48163 volume_vacuum.go:45] Committing volume 2 vacuuming...
I0709 10:03:21 48163 volume_loading.go:88] loading leveldb data/2.ldb
I0709 10:03:21 48163 needle_map_leveldb.go:28] Start to Generate data/2.ldb from data/2.idx
I0709 10:03:22 48163 needle_map_leveldb.go:30] Finished Generating data/2.ldb from data/2.idx
I0709 10:04:22 48163 volume_vacuum.go:45] Committing volume 1 vacuuming...
I0709 10:04:22 48163 volume_loading.go:88] loading leveldb data/1.ldb
I0709 10:04:22 48163 needle_map_leveldb.go:28] Start to Generate data/1.ldb from data/1.idx
I0709 10:04:24 48163 needle_map_leveldb.go:30] Finished Generating data/1.ldb from data/1.idx
I0709 10:05:20 48163 volume_vacuum.go:45] Committing volume 5 vacuuming...
I0709 10:05:21 48163 volume_loading.go:88] loading leveldb data/5.ldb
I0709 10:05:21 48163 needle_map_leveldb.go:28] Start to Generate data/5.ldb from data/5.idx
I0709 10:05:22 48163 needle_map_leveldb.go:30] Finished Generating data/5.ldb from data/5.idx
I0709 10:06:21 48163 volume_vacuum.go:45] Committing volume 3 vacuuming...
I0709 10:06:22 48163 volume_loading.go:88] loading leveldb data/3.ldb
I0709 10:06:22 48163 needle_map_leveldb.go:28] Start to Generate data/3.ldb from data/3.idx
I0709 10:06:23 48163 needle_map_leveldb.go:30] Finished Generating data/3.ldb from data/3.idx

Observed corresponding spikes:
![image](https://user-images.githubusercontent.com/979743/60895176-2a1b2f80-a232-11e9-8afc-1b3f27d8386c.png)

At this point is it just normal behavior?
Can we reduce these events by adding volume servers or some other solution?

**Comment by Minikloon** [comment]
Here is the view of the Prometheus panel:
![image](https://user-images.githubusercontent.com/979743/60901695-618ed980-a23c-11e9-87b1-0b0b5cbbf4dd.png)

**Comment by chrislusf** [comment]
Are you doing some sort of benchmarking? Seems all your volumes are compacting at the same time.

Seems your traffic has lots of updates. You can:
1. reduce the volume size, to reduce the compaction cost.
2. allocate a lot more volumes, to make up for the volume size reduction, and improve concurrency.
