### ISSUE TITLE
How to check if a key is a file or a folder in filer api?

### ISSUE THREAD

**Issue by divinerapier** [chrislusf/seaweedfs#1004]
请问，使用filer api，如何判断一个 key 是文件还是目录?

**Comment by chrislusf** [comment]
what is "a key"?

**Comment by divinerapier** [comment]
eg: http://host/path/to/something. How to check if `/path/to/something` is a file or a foler?

**Comment by chrislusf** [comment]
Suppose by filer API you mean filer http API. Maybe send a HEAD request to `http://host/path/to/something/`. If the status code is 404, it is not a folder.

**Comment by chrislusf** [comment]
added a fix so that you can check `http://host/path/to/something/` http status code. If it is 404, it is not a folder.

**Comment by divinerapier** [comment]
that's pretty good. thank you very much.
