### ISSUE TITLE
Unobvious loading behavior via filer

### ISSUE THREAD

**Issue by aseev-xx** [chrislusf/seaweedfs#1005]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**
When load a file through filer if you do not explicitly specify the file name - the file is loaded, but there is no file metadata in the cassandra

**System Setup**
In the empty storage we load two files in a subdirectory:

first file load correctly because we set t1.txt obviously:

![Screen Shot 2019-07-11 at 11 37 16](https://user-images.githubusercontent.com/1444747/61036349-9f713680-a3d1-11e9-90ed-5a0b85994230.png)
```
# curl -v -F "filename=@test.txt" "http://localhost:8888/t11/t11/t1.txt"
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8888 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
> POST /t11/t11/t1.txt HTTP/1.1
> Host: localhost:8888
> User-Agent: curl/7.46.0
> Accept: */*
> Content-Length: 196
> Expect: 100-continue
> Content-Type: multipart/form-data; boundary=------------------------e0d1985ed0fd4ffa
> 
< HTTP/1.1 100 Continue
< HTTP/1.1 201 Created
< Content-Type: application/json
< Etag: "353dd8be"
< Date: Thu, 11 Jul 2019 08:29:17 GMT
< Content-Length: 110
< 
* Connection #0 to host localhost left intact
{"name":"test.txt","size":6,"fid":"1,678fd51d89","url":"http://localhost:8081/1,678fd51d89"}
```

second file load correctly but no metadata write in cassandra because we not set t1.txt obviously

![Screen Shot 2019-07-11 at 11 37 27](https://user-images.githubusercontent.com/1444747/61036374-aa2bcb80-a3d1-11e9-9da6-b17fa44da8d0.png)
![Screen Shot 2019-07-11 at 11 36 49](https://user-images.githubusercontent.com/1444747/61036384-adbf5280-a3d1-11e9-999a-85d140192fba.png)

```
# curl -v -F "filename=@test.txt" "http://localhost:8888/t22/t22/"
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8888 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
> POST /t22/t22/ HTTP/1.1
> Host: localhost:8888
> User-Agent: curl/7.46.0
> Accept: */*
> Content-Length: 196
> Expect: 100-continue
> Content-Type: multipart/form-data; boundary=------------------------65a9ac8adf41099b
> 
< HTTP/1.1 100 Continue
< HTTP/1.1 201 Created
< Content-Type: application/json
< Etag: "353dd8be"
< Date: Thu, 11 Jul 2019 08:34:11 GMT
< Content-Length: 110
< 
* Connection #0 to host localhost left intact
{"name":"test.txt","size":6,"fid":"2,682cfc7bc3","url":"localhost:8081/2,682cfc7bc3"}
```

Now remove all:
```
# curl -X DELETE http://localhost:8888/?recursive=true
```
but in cassandra:
![Screen Shot 2019-07-11 at 11 45 41](https://user-images.githubusercontent.com/1444747/61036267-72bd1f00-a3d1-11e9-9ea0-0b5c3a0d41a0.png)

**Expected behavior**
Thus, even if you do not explicitly specify a file, it is loaded, but there is no meta information. At the same time, if you completely try to clear the directory recursively - some records will remain

**Additional context**
```
# cassandra -v
3.11.4
# weed version
version 8000GB 1.41 linux amd64
```

**Comment by chrislusf** [comment]
thanks for the details! I am able to quickly reproduce it.

adding a fix now.

**Comment by aseev-xx** [comment]
It work, thank you.
