### ISSUE TITLE
filer do not update after re-create collection

### ISSUE THREAD

**Issue by qszxnp** [chrislusf/seaweedfs#1006]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**
reproduce step：
1、create collection abc
2、upload a file（use filer api）to collection abc use filer api，name file_abc
3、delete collection abc，and then create it with the same name
4、upload a file use p previous path，and filer will return 404 not found

**System Setup**
List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
weed master
weed volume
weed filer

**Expected behavior**
it seems filer record the wrong vid and can not overwrite it

**Screenshots**

**Additional context**

**Comment by qszxnp** [comment]
我怕我英语不好，用中午复述一下：就是先上传一个文件到filer指定collection，然后在后台把collection删除再重建。这个时候用同样的文件路径就无法上传了，一只返回404，感觉像是filer再做覆盖的时候 查了一个老的vid

**Comment by chrislusf** [comment]
can not reproduce. please show your exact steps.
