### ISSUE TITLE
Could not vacuum volumes

### ISSUE THREAD

**Issue by Hansonnnn** [chrislusf/seaweedfs#1008]
I use the version 1.33 of seaweedfs. My operation has many deletions, but the deleted file's disk space is not empty. According to your wiki, I run the command `curl "http://localhost:9333/vol/vacuum` to forced vacuum volumes.  My cluster have 14 volumes, each volume that use 30GB on disk approximately has 100,000 files and 50,000 trash files. Sometimes the vacuum operation cause the volume condition to readonly,  and stuck to this condition all the time.
I try to restart the master and volume server, or run weed fix command, but the problem is not resolved.

**Comment by ijunaid8989** [comment]
how have you started your seaweedfs instance? i.e commands?

**Comment by Hansonnnn** [comment]
weed master -port=*** -mdir=***  -ip=***  -defaultReplication=000
weed volume -port=***  -dir=***  -ip=***  -max=100 -mserver=***

**Comment by chrislusf** [comment]
@Hansonnnn please create a new issue following the issue template and add some meaningful logs and screenshots.
