### ISSUE TITLE
win2003下的问题和如何通过文件名称找到地址

### ISSUE THREAD

**Issue by redmangame** [chrislusf/seaweedfs#1009]
你好win2003下出现这样的错误：panic: Failed to find CreateSymbolicLinkW procedure in kernel32.dll: The specified procedure could not be found.
用的是windows_386.zip

另外再请教下各位：
1、怎么通过文件名称找到文件
举例：
curl -F file=@C:\Users\admin\Desktop\0.jpg localhost:8080/3,0208929369
{"name":"0.jpg","size":74257,"eTag":"ebf10487"}
 localhost:8080/3,0208929369 就是这个文件，可不可通过0.jpg这个名称检索找出可用的地址

2.每个Volume默认限定是30GB吗

英文不好，在线翻译又不准确所以来问问。感谢作者  感谢大家。

**Comment by chrislusf** [comment]
try windows_amd64.zip

1. you need filer
2. there is an CLI option to adjust it.
