### ISSUE TITLE
Getting error during vaccuming volume

### ISSUE THREAD

**Issue by Hansonnnn** [chrislusf/seaweedfs#1011]
**Describe the bug**
Seaweed 30GB 1.33 on CentOS 7.
I often run the vacuum comand after a lof of deletions. One volume can not work. Other volumes are not empty, there is still 30GB on each volume's data file.
 
**System Setup**
```
weed master -port=9333  -ip=192.168.56.10 -defaultReplication=000
weed volume -port=19334 -dir=/data4/seaweedfs_1.33/data -ip=192.168.56.10 -max=100 -mserver="192.168.56.10:9333"
```
**Log**
On volume server there are errors when I run the command
`curl "http://localhost:9333/vol/vacuum"`
```
I0706 15:33:13 80437 master_server_handlers_admin.go:59] garbageThreshold = 0.3
I0706 15:33:13 80437 volume_layout.go:237] Volume 11 becomes unwritable
I0706 15:33:13 80437 topology_vacuum.go:53] 0 Start vacuuming 11 on 192.168.56.10:19334
I0706 15:33:13 80437 topology_vacuum.go:53] 0 Start vacuuming 11 on 192.168.56.10:19334
I0706 15:33:13 80437 topology_vacuum.go:53] 0 Start vacuuming 11 on 192.168.56.10:19334
I0706 15:33:29 80437 topology_vacuum.go:64] Complete vacuuming 11 on 192.168.56.10:19334
I0706 15:33:29 80437 topology_vacuum.go:84] Start Committing vacuum 11 on 192.168.56.10:19334
I0706 15:33:29 80468 volume_vacuum.go:43] Committing volume 11 vacuuming...
I0706 15:33:32 80468 volume_loading.go:78] volumeDataIntegrityChecking failed verifyNeedleIntegrity /data4/seaweedfs_1.33/data/11.idx failed: File Entry Not Found. offset 2484227080, Needle id 17431427978364841011 expected size 3379477726 Memory 122956
I0706 15:33:32 80468 volume_loading.go:82] loading index /data4/seaweedfs_1.33/data/11.idx to memory readonly true
I0706 15:33:32 80437 topology_vacuum.go:95] Complete Committing vacuum 11 on 192.168.56.10:19334
I0706 15:33:32 80437 volume_layout.go:249] Volume 11 becomes writable
I0706 15:33:32 80437 topology_vacuum.go:64] Complete vacuuming 11 on 192.168.56.10:19334
I0706 15:33:32 80437 topology_vacuum.go:84] Start Committing vacuum 11 on 192.168.56.10:19334
I0706 15:33:32 80468 volume_vacuum.go:43] Committing volume 11 vacuuming...
I0706 15:33:32 80468 volume_vacuum.go:57] makeupDiff in CommitCompact volume 11 failed current old dat file's compact revision 2 is not the expected one 1
E0706 15:33:32 80468 volume_grpc_vacuum.go:50] commit volume 11: remove /data4/seaweedfs_1.33/data/11.cpd: no such file or directory
E0706 15:33:32 80437 topology_vacuum.go:92] Error when committing vacuum 11 on 192.168.56.10:19334: rpc error: code = Unknown desc = remove /data4/seaweedfs_1.33/data/11.cpd: no such file or directory
I0706 15:33:33 80437 topology_vacuum.go:64] Complete vacuuming 11 on 192.168.56.10:19334
I0706 15:33:33 80437 topology_vacuum.go:84] Start Committing vacuum 11 on 192.168.56.10:19334
I0706 15:33:33 80468 volume_vacuum.go:43] Committing volume 11 vacuuming...
I0706 15:33:33 80468 volume_vacuum.go:51] fail to close volume 11
I0706 15:33:33 80468 volume_vacuum.go:57] makeupDiff in CommitCompact volume 11 failed current old dat file's compact revision 2 is not the expected one 1
E0706 15:33:33 80468 volume_grpc_vacuum.go:50] commit volume 11: remove /data4/seaweedfs_1.33/data/11.cpd: no such file or directory
E0706 15:33:33 80437 topology_vacuum.go:92] Error when committing vacuum 11 on 192.168.56.10:19334: rpc error: code = Unknown desc = remove /data4/seaweedfs_1.33/data/11.cpd: no such file or directory
I0706 15:33:55 80437 master_server_handlers_admin.go:59] garbageThreshold = 0.3
I0706 15:33:55 80437 volume_layout.go:237] Volume 11 becomes unwritable
I0706 15:33:55 80437 topology_vacuum.go:53] 0 Start vacuuming 11 on 192.168.56.10:19334
I0706 15:33:55 80468 volume_read_write.go:211] cannot read needle body: index out of range 7
I0706 15:33:55 80468 volume_read_write.go:211] cannot read needle body: index out of range 1
I0706 15:33:56 80468 volume_read_write.go:211] cannot read needle body: index out of range 1
I0706 15:33:59 80468 volume_read_write.go:211] cannot read needle body: EOF
I0706 15:33:59 80437 topology_vacuum.go:64] Complete vacuuming 11 on 192.168.56.10:19334
I0706 15:33:59 80437 topology_vacuum.go:84] Start Committing vacuum 11 on 192.168.56.10:19334
I0706 15:33:59 80468 volume_vacuum.go:43] Committing volume 11 vacuuming...
I0706 15:33:59 80468 volume_vacuum.go:51] fail to close volume 11
I0706 15:33:59 80468 volume_vacuum.go:57] makeupDiff in CommitCompact volume 11 failed readIndexEntry /data4/seaweedfs_1.33/data/11.idx at offset -16 failed: offset -16 for index file is invalid
I0706 15:33:59 80468 volume_loading.go:78] volumeDataIntegrityChecking failed verifyNeedleIntegrity /data4/seaweedfs_1.33/data/11.idx failed: File Entry Not Found. offset 2486874032, Needle id 289488699801070697 expected size 3794296969 Memory 19796
I0706 15:33:59 80468 volume_loading.go:82] loading index /data4/seaweedfs_1.33/data/11.idx to memory readonly true
I0706 15:33:59 80437 topology_vacuum.go:95] Complete Committing vacuum 11 on 192.168.56.10:19334
I0706 15:33:59 80437 volume_layout.go:249] Volume 11 becomes writable
I0706 15:37:11 80437 volume_layout.go:237] Volume 11 becomes unwritable
I0706 15:37:11 80437 topology_vacuum.go:53] 0 Start vacuuming 11 on 192.168.56.10:19334
I0706 15:37:11 80468 volume_read_write.go:211] cannot read needle body: index out of range 7
I0706 15:37:12 80468 volume_read_write.go:211] cannot read needle body: index out of range 1
I0706 15:37:13 80468 volume_read_write.go:211] cannot read needle body: index out of range 1
I0706 15:37:19 80468 volume_read_write.go:211] cannot read needle body: EOF
I0706 15:37:19 80437 topology_vacuum.go:64] Complete vacuuming 11 on 192.168.56.10:19334
I0706 15:37:19 80437 topology_vacuum.go:84] Start Committing vacuum 11 on 192.168.56.10:19334
I0706 15:37:19 80468 volume_vacuum.go:43] Committing volume 11 vacuuming...
I0706 15:37:19 80468 volume_loading.go:78] volumeDataIntegrityChecking failed verifyNeedleIntegrity /data4/seaweedfs_1.33/data/11.idx failed: EOF
I0706 15:37:19 80468 volume_loading.go:82] loading index /data4/seaweedfs_1.33/data/11.idx to memory readonly true
I0706 15:37:19 80437 topology_vacuum.go:95] Complete Committing vacuum 11 on 192.168.56.10:19334
I0706 15:37:19 80437 volume_layout.go:249] Volume 11 becomes writable
I0706 15:58:35 80437 master_server_handlers_admin.go:59] garbageThreshold = 0.3
I0706 15:58:51 80437 master_server_handlers_admin.go:59] garbageThreshold = 0.3
```
**Screenshots**
![image](https://user-images.githubusercontent.com/18455973/61269855-66223780-a7d2-11e9-8a88-80c2fe35a9ac.png)

**Comment by chrislusf** [comment]
* Please use latest version to test.
* Is there any other volume server running on 192.168.56.10?
* What process is writing to the system? Please show some source code. Seems it is not respecting the "readonly" mode for the volume.

**Comment by Hansonnnn** [comment]
> * Please use latest version to test.
> * Is there any other volume server running on 192.168.56.10?
> * What process is writing to the system? Please show some source code. Seems it is not respecting the "readonly" mode for the volume.

Thanks for your prompt reply!
1. Could I replace the weed command to update to the latest version 
2. Just one master and one volume.
3. I use java http client to request the weed master. After every 1000 delete requests, I  run the vaccum request, and post file requests are not stop on the same time.

**Comment by chrislusf** [comment]
I cannot debug by your words，please share your code.

**Comment by Hansonnnn** [comment]
This is my pseudocode of processing the deletions.
```java
    @Test
    public void testWeedFS() {
        cleanWeedfs();
    }

    private void cleanWeedfs() {
        for (int i = 0; i < 1000; i++) {
            int count = delete();
            if (count < 1)
                break;
        }
        try {
            String url = "http://192.168.56.10:9333/vol/vacuum";
            HttpClientService.doGet(url);//this is a brief method to call http url
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private int delete() {
        int count = 0;
        try {
            String sql = "select fid from LOG_SYN_REC limit 0,500";
            Vector<String> fids = DBUtils.executeSQL(sql);//this is a customized method to select fids from mysql
            if (fids.size() > 0) {
                for (String fid : fids) {
                    try {
                        String url = "http://192.168.56.10:19334/" + fid;
                        HttpClientService.doDelete(url);//this is a brief method to call http url
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                    count++;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return count;
    }
```

**Comment by chrislusf** [comment]
I need to create some stress test code simulate your test case.

**Comment by Hansonnnn** [comment]
I use seaweedfs as a file transfer station. My business is that many producers upload files to weedfs and consumers deal with them. Once the consumer handles it successfully it mark a condition in database.  One task that find all marked fids sending delete request and vacuum volumes every one hour in order to release space for new upload files.

**Comment by chrislusf** [comment]
seems you can use TTL for this.

**Comment by chrislusf** [comment]
This is caused by multiple concurrent vacuum process. Fixing it by one exclusive lock.

**Comment by BenBenBenny** [comment]
我用了最新版本，在下载多次文件后，还是出现这个错误
下面是报错日志：

I1202 14:35:54 13348 volume_layout.go:340] Volume 7 becomes unwritable
I1202 14:35:54 13348 topology_vacuum.go:70] 0 Start vacuuming 7 on 192.168.1.2:9081
I1202 14:35:54 13348 topology_vacuum.go:82] Complete vacuuming 7 on 192.168.1.2:9081
I1202 14:35:54 13348 topology_vacuum.go:106] Start Committing vacuum 7 on 192.168.1.2:9081
I1202 14:35:55 13348 volume_vacuum.go:93] Committing volume 7 vacuuming...
E1202 14:35:55 13348 volume_grpc_vacuum.go:50] commit volume 7: remove P:\weed\Volume2/7.dat: The process cannot access the file because it is being used by ano
ther process.
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0x18444f2]

goroutine 58 [running]:
github.com/chrislusf/seaweedfs/weed/topology.batchVacuumVolumeCommit.func1(0x249be00, 0xc00080ab60, 0xc0007dfad0, 0x3284080)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/topology/topology_vacuum.go:111 +0xb2
github.com/chrislusf/seaweedfs/weed/operation.WithVolumeServerClient.func1(0xc00074ae00, 0x11, 0xc0007dfb30)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/operation/grpc_client.go:26 +0x82
github.com/chrislusf/seaweedfs/weed/pb.WithCachedGrpcClient(0xc0007dfb40, 0xc00255ed40, 0x11, 0xc0007dfb30, 0x1, 0x1, 0xc00197c96c, 0xc0007dfba8)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/pb/grpc_client_server.go:106 +0x15b
github.com/chrislusf/seaweedfs/weed/operation.WithVolumeServerClient(0xc00197c960, 0x10, 0x2434f60, 0xc000006b08, 0xc0007dfc40, 0xc00197c958, 0x4)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/operation/grpc_client.go:24 +0x1b5
github.com/chrislusf/seaweedfs/weed/topology.batchVacuumVolumeCommit(0x2434f60, 0xc000006b08, 0xc000409490, 0xc000000007, 0xc001a84720, 0x0)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/topology/topology_vacuum.go:107 +0x32b
github.com/chrislusf/seaweedfs/weed/topology.vacuumOneVolumeLayout(0x2434f60, 0xc000006b08, 0xc000409490, 0xc00053f500, 0x3fd3333333333333, 0x0)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/topology/topology_vacuum.go:193 +0x4f4
github.com/chrislusf/seaweedfs/weed/topology.(*Topology).Vacuum(0xc0005978c0, 0x2434f60, 0xc000006b08, 0x3fd3333333333333, 0x0)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/topology/topology_vacuum.go:164 +0x245
github.com/chrislusf/seaweedfs/weed/topology.(*Topology).StartRefreshWritableVolumes.func2(0xc0005978c0, 0x2434f60, 0xc000006b08, 0x0, 0x3fd3333333333333)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/topology/topology_event_handling.go:26 +0x117
created by github.com/chrislusf/seaweedfs/weed/topology.(*Topology).StartRefreshWritableVolumes
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/topology/topology_event_handling.go:22 +0x96
