### ISSUE TITLE
Replication 200 ,but data is not strong consistency

### ISSUE THREAD

**Issue by doufighting** [chrislusf/seaweedfs#1012]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

example of a good issue report:
https://github.com/chrislusf/seaweedfs/issues/1005
example of a bad issue report:
https://github.com/chrislusf/seaweedfs/issues/1008

**Describe the bug**
replication 200,but some data has not been stored on two other data center. and the md5 for the dat file in three data center is not exactly same. 

**System Setup**
use seaweedfs 0.77,replication is 200.
machine1 ip:ip1:
./weed master -mdir=/data/master -port = 9333 -defaultReplication=200 -ip=ip1 -peers=ip1:9333,ip2:9334,ip3:9335
./weed volume -dir=/data/vs_1 -max=30 -mserver=ip1:9333 -dataCenter=dc1 -rack=rack1 -port=9060 -ip=ip1
./weed volume -dir=/data/vs_2 -max=30 -mserver=ip1:9333 -dataCenter=dc1 -rack=rack2 -port=9061 -ip=ip1
./weed volume -dir=/data/vs_3 -max=30 -mserver=ip1:9333 -dataCenter=dc1 -rack=rack3 -port=9062 -ip=ip1
machine 2 ip:ip2:
./weed master -mdir=/data/master -port = 9334 -defaultReplication=200 -ip=ip2 -peers=ip1:9333,ip2:9334,ip3:9335
./weed volume -dir=/data/vs_1 -max=30 -mserver=ip2:9334 -dataCenter=dc2 -rack=rack1 -port=9060 -ip=ip2
./weed volume -dir=/data/vs_2 -max=30 -mserver=ip2:9334 -dataCenter=dc2 -rack=rack2 -port=9061 -ip=ip2
./weed volume -dir=/data/vs_3 -max=30 -mserver=ip2:9334 -dataCenter=dc2 -rack=rack3 -port=9062 -ip=ip2
machine 3 ip:ip3:
./weed master -mdir=/data/master -port = 9335 -defaultReplication=200 -ip=ip3 -peers=ip1:9333,ip2:9334,ip3:9335
./weed volume -dir=/data/vs_1 -max=30 -mserver=ip3:9335 -dataCenter=dc3 -rack=rack1 -port=9060 -ip=ip3
./weed volume -dir=/data/vs_2 -max=30 -mserver=ip3:9335 -dataCenter=dc3 -rack=rack2 -port=9061 -ip=ip3
./weed volume -dir=/data/vs_3 -max=30 -mserver=ip3:9335 -dataCenter=dc3 -rack=rack3 -port=9062 -ip=ip3

**Expected behavior**
when i get a file with fileId such as 27,0326*********, i think weither i use http://ip1:9333/fileid, or http://ip2:9334/fileid or http://ip3:9335/fileid , i could get same answer.but actually there has some fileid , i could get right answer when i use http://ip1:9333/fileid, but when i use http://ip2:9334/fileid , there is nothing return, and the volume log : read error: Not Found /fileid

**Comment by chrislusf** [comment]
Run this to find the locations
`curl http://localhost:9334/dir/lookup?fileId=27,0326*********`

And when starting volume servers, try to set -mserver to the full list of master servers.

**Comment by doufighting** [comment]
1、when i run : http://ip2:9334/dir/lookup?fileId=121,03d3327e45e9d8e5
    i got a error message : {"error":"Unknown volumeId format: "},dont known weither its due to my weed version
    when i run : http://ip2:9334/dir/lookup?volumeId=121
    i got message: {"volumeId":"121","locations":[{"url":"ip3:9060","publicUrl":"ip3:9060"},{"url":"ip1:9060","publicUrl":"ip1:9060"},{"url":"ip2:9060","publicUrl":"ip2:9060"}]}
    i check the size of the dat file on the three data node, and i find,
    on machine 1:
![image](https://user-images.githubusercontent.com/9191377/61357948-d8b31600-a8ab-11e9-87b2-83a818a0352d.png)
    on machine 2:
![image](https://user-images.githubusercontent.com/9191377/61357967-e23c7e00-a8ab-11e9-9692-c52c8fbb6a49.png)
    on machine 3:
![image](https://user-images.githubusercontent.com/9191377/61357978-ebc5e600-a8ab-11e9-8614-4eb5dd4b40c7.png)
    as you can see, the size of three dat file is different,and one has trash, is that the reason cause the problem? and why there is trash? i have not send delete request before.

2、 do you mean i should run volume server like:
./weed volume -dir=/data/vs_1 -max=30 -mserver=ip1:9333,ip2:9334,ip3:9335 -dataCenter=dc2 -rack=rack1 -port=9060 -ip=ip2

**Comment by chrislusf** [comment]
.dat files are not always exactly the same due to write errors, different orderings. If errors happen, the clients are expected to clean up and retry a new upload.

2. yes.

**Comment by doufighting** [comment]
thanks! i also want to make sure one thing, is seaweed strongly consistency? which means if i set replication 200 , when i send a upload request,  client receive fileid only when the file stored successfully in three datacenter. otherwise there won't have fileid return.
