### ISSUE TITLE
Could not get 1 of 2 files with same key. 

### ISSUE THREAD

**Issue by horllion** [chrislusf/seaweedfs#1014]
myversion is 30GB 1.31 linux amd64.
I get a error when getting fid 82,4cae725bbd3e21.
"request /82,4cae725bbd3e21 with cookie:5bbd3e21 expected:4aba18f3 from 10.64.1.52:52478 agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36"
Changed cookie of fid, I can get the file 82,4cae724aba18f3. But it's not the file I wanted.I searched for filer to find both.
![image](https://user-images.githubusercontent.com/42425728/61372015-a49a1e00-a8c8-11e9-925b-f95c218aa747.png)
![image](https://user-images.githubusercontent.com/42425728/61372211-1a9e8500-a8c9-11e9-80c5-eaf8160302d5.png)
is that bug? exist two same index key but different cookie fid.

**Comment by chrislusf** [comment]
I wonder whether you restart the master server or servers often, especially between 2019-05-24 and 2019-07-02.

Please show how you start the servers, how many volumes, etc.

**Comment by horllion** [comment]
> I wonder whether you restart the master server or servers often, especially between 2019-05-24 and 2019-07-02.
> 
> Please show how you start the servers, how many volumes, etc.

I restart the master server and volumes together a few times. 
I have 1 master server and 6 volume servers. every volume server have 20-40 volumes.
sometimes, defore restarting, I changed the  -max of one volume server.

**Comment by chrislusf** [comment]
The only possible case is that when the master is restarted, before the volume server reconnects with the master, a write request comes in.

Try not to restart master servers often.

I will also add some code to protect against this case, and fail early if the cookie does not match.

**Comment by chrislusf** [comment]
This case should be fairly rare. Added a fix to fail fast if this ever happens.

**Comment by horllion** [comment]
> This case should be fairly rare. Added a fix to fail fast if this ever happens.

fixed the volume doesn't work. the old fid was overwritten.

**Comment by horllion** [comment]
> The only possible case is that when the master is restarted, before the volume server reconnects with the master, a write request comes in.
> 
> Try not to restart master servers often.

before the volume server reconnects with the master，the volume is not available. I can;t find the bug after checking code.

**Comment by chrislusf** [comment]
> > This case should be fairly rare. Added a fix to fail fast if this ever happens.
> 
> fixed the volume doesn't work. the old fid was overwritten.

The fix https://github.com/chrislusf/seaweedfs/commit/c54d9221b90676b499830f27064cc7ef8f6cfdfd is to avoid overwrite the old fid.

**Comment by horllion** [comment]
thank you for supportting.
