### ISSUE TITLE
failed to upgrade from 0.76 to 1.41 

### ISSUE THREAD

**Issue by doufighting** [chrislusf/seaweedfs#1017]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

example of a good issue report:
https://github.com/chrislusf/seaweedfs/issues/1005
example of a bad issue report:
https://github.com/chrislusf/seaweedfs/issues/1008

**Describe the bug**

when i upgrade from 0.76 to 1.41, three master can not elect a leader, and some volume lost

**System Setup**
i replace the weed binary file(currently use 1.41 version), then do nothing to the master file and data file, run command like this :
machine1 ip:ip1:
./weed master -mdir=/data/master -port = 9333 -defaultReplication=200 -ip=ip1 -peers=ip1:9333,ip2:9334,ip3:9335
./weed volume -dir=/data/vs_1 -max=30 -mserver=ip1:9333,ip2:9334,ip3:9335 -dataCenter=dc1 -rack=rack1 -port=9060 -ip=ip1
./weed volume -dir=/data/vs_2 -max=30 -mserver=ip1:9333,ip2:9334,ip3:9335 -dataCenter=dc1 -rack=rack2 -port=9061 -ip=ip1
./weed volume -dir=/data/vs_3 -max=30 -mserver=ip1:9333,ip2:9334,ip3:9335 -dataCenter=dc1 -rack=rack3 -port=9062 -ip=ip1
machine 2 ip:ip2:
./weed master -mdir=/data/master -port = 9334 -defaultReplication=200 -ip=ip2 -peers=ip1:9333,ip2:9334,ip3:9335
./weed volume -dir=/data/vs_1 -max=30 -mserver=ip1:9333,ip2:9334,ip3:9335 -dataCenter=dc2 -rack=rack1 -port=9060 -ip=ip2
./weed volume -dir=/data/vs_2 -max=30 -mserver=ip1:9333,ip2:9334,ip3:9335 -dataCenter=dc2 -rack=rack2 -port=9061 -ip=ip2
./weed volume -dir=/data/vs_3 -max=30 -mserver=ip1:9333,ip2:9334,ip3:9335 -dataCenter=dc2 -rack=rack3 -port=9062 -ip=ip2
machine 3 ip:ip3:
./weed master -mdir=/data/master -port = 9335 -defaultReplication=200 -ip=ip3 -peers=ip1:9333,ip2:9334,ip3:9335
./weed volume -dir=/data/vs_1 -max=30 -mserver=ip1:9333,ip2:9334,ip3:9335 -dataCenter=dc3 -rack=rack1 -port=9060 -ip=ip3
./weed volume -dir=/data/vs_2 -max=30 -mserver=ip1:9333,ip2:9334,ip3:9335 -dataCenter=dc3 -rack=rack2 -port=9061 -ip=ip3
./weed volume -dir=/data/vs_3 -max=30 -mserver=ip1:9333,ip2:9334,ip3:9335 -dataCenter=dc3 -rack=rack3 -port=9062 -ip=ip3 

**Expected behavior**
after start up several hours, there is no leader elected. i run:
http://ip1:9333/cluster/status?pretty=y http://ip2:9334/cluster/status?pretty=y http://ip3:9335/cluster/status?pretty=y
i got same result like : {"Peers":[ip:9333,ip:9334]}, there is no leader information.
and when i run http://ip1:9333 on browser, i got nothing . 
some file which i can read in 0.76 version but get nothing from 1.41 version.

is there any step uncorrect during my upgrading ?

**Comment by chrislusf** [comment]
Clean your /data/master on the master servers, and restart the masters.

**Comment by chrislusf** [comment]
And when creating issues, add the master output logs.

**Comment by doufighting** [comment]
thanks ~ i will try agin

**Comment by doufighting** [comment]
it works well after clean up the master folder, thanks a lot
