### ISSUE TITLE
upgrade from 0.92 to 1.42 fail

### ISSUE THREAD

**Issue by qszxnp** [chrislusf/seaweedfs#1018]
**Describe the bug**
    after killall weed (master volume filer) and replace weed binary 
then clean master's meta and restart weed (master volume filer) 
i try curl http://127.0.0.1:9333/dir/status?pretty=y
all of the collection i create before(in version 0.9.2)'s writables is null

change weed binary back can recovery

**System Setup**
List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by qszxnp** [comment]
![10_48_22__07_23_2019](https://user-images.githubusercontent.com/6102619/61679062-881e3b80-ad37-11e9-8b49-8a0ea3729cea.jpg)

**Comment by chrislusf** [comment]
can not reproduce

**Comment by qszxnp** [comment]
i check  the source code 0.92's storage.CurrentVersion is Version2 and 1.42's  storage.CurrentVersion is Version3 ,so when RegisterVolume the vl.isWritable is always false and writables is empty

**Comment by chrislusf** [comment]
I see. You can just allocate new volumes.

**Comment by qszxnp** [comment]
and the file in the old collection(old volumes) can be access?

**Comment by chrislusf** [comment]
yes

**Comment by qszxnp** [comment]
cool ,
 maybe show all vol with different version(1,2,3) and vol status such as writable and read-only after upgread would be better.
