### ISSUE TITLE
Easier migration from leveldb to leveldb2

### ISSUE THREAD

**Issue by LazyDBA247-Anyvision** [chrislusf/seaweedfs#1019]
Hi,
can you please provide a better way to upgrade between these close related filer DB's.
using ```fs.meta.save``` & ```fs.meta.load``` without a specific export name and the unavoidable downtime is cumbersome and problematic.
when upgrading the system we need to follow these steps:

1. check if this is a new system (no data exist) or exists leveldb files(upgrade)
2. if new need to create folder filerldb2 like in the ```Dockerfile``` (can you please  add automatic mkdir?)
3. if old data exists, we need to upgrade, make sure no filer & s3 are not accessible so no new files are been written:
  -  start weed filer with leveldb config
  - open the weed shell (in the folder you want the export to occur)  and do export ```fs.meta.save /```
  - move files on success (so migration happen once, or use a FLAG) and find the dynamic export filename 
  - close weed filer with the leveldb config
  - open weed filer with leveldb2 config
  - open the weed shell and do import ```fs.meta.load DYNAMIC_EXPORT_FILENAME```

Can you please suggest me a better or a simple flow to do the upgrade (migrate from leveldb to leveldb2)?, or even support a backward-compatible in leveldb2 that can READ ONLY old leveldb files and new writes to leveldb2, which will enable a seamless migration.

Thanks a lot for your hard work, we LOVE seaweedfs, it RULES!

**Comment by chrislusf** [comment]
thanks for your suggestion! 

"leveldb" should still work fine. You can leave it running on old deployments. Migration is not a must-have.

Trying to support auto migration is tricky and can lead to hard-to-maintain legacy code. It's better to avoid that and keep things simple and fast.

Downtime is needed. Otherwise, hard to ensure metadata correctness during the transition.

**Comment by LazyDBA247-Anyvision** [comment]
Thanks for the quick response, but when we use leveldb and the full-stack side is bombarding seaweedfs with 10k+ concurrent deletes, the filer works slow (freeze?) with 500-600% cpu utilization for hours, when using leveldb2 we can't reproduce it and manage to delete all keys...
so we MUST upgrade to leveldb2...

**Comment by LazyDBA247-Anyvision** [comment]
Hi,
managed to write a simple python3 script to migrate directly on the leveldb side:
script output:
Done export, time to export_sec: 1.33
items: 526239, import_time_sec: 0.389, total_time_sec: 1.719

so 0.5 million keys in 1.7 seconds on i7-7700HQ

```
import plyvel
import hashlib
import os
import time

current_milli_time = lambda: int(round(time.time() * 1000))

SOURCE_LDB1 = '/ssd/seaweed-filer'
DEST_LDB2 = '/ssd/seaweed-filer/filerldb2'
DB_COUNT = 8
lvlDB = dict()

# check for new filerldb2 folder existence
if not os.path.exists(DEST_LDB2):
    os.mkdir(DEST_LDB2)
# create each sharded leveldb2 folder
for i in range(0, DB_COUNT):
    folder = os.path.join(DEST_LDB2, '{0:02d}'.format(i))
    if not os.path.exists(folder):
        os.mkdir(folder)
    # create db connector for each folder.
    lvlDB[i] = plyvel.DB(folder, create_if_missing=True)

db = plyvel.DB(SOURCE_LDB1, create_if_missing=False)
start_time = current_milli_time()
data = dict()
i = 0
with db.iterator() as it:
    for k, v in it:
        i += 1
        # split old leveldb key on 0x00
        dirPath, Key = k.split(b'\x00')
        # create md5 from dirPath
        md5 = hashlib.md5(dirPath).digest()
        # use last byte to generate the partition (shard)
        p = md5[-1] % 8
        # create new leveldb2 key
        newK = md5+Key
        # save each partition in it own list
        if str(p) in data:
            data[str(p)] += [(newK, v)]
        else:
            data[str(p)] = [(newK, v)]
print(f"Done export, time to export_sec: {(current_milli_time()-start_time) /1000}")
import_time = current_milli_time()
for part in data:
    with lvlDB[int(part)].write_batch() as b:
        for kv in data[part]:
            b.put(kv[0], kv[1])
for d in lvlDB:
    lvlDB[d].close()
print(f"items: {i}, import_time_sec: {(current_milli_time()-import_time) /1000}, total_time_sec: {(current_milli_time()-start_time) /1000}")
```

the only issue is: if I create the databases I need to restart master to get the data working but if I let the filer to create the databases and then import on existing folders, all ok.
anyway thought maybe someone can use my script.

**Comment by chrislusf** [comment]
Impressive!

**Comment by chrislusf** [comment]
Could you please share your old leveldb data in '/ssd/seaweed-filer'. I want to make the `fs.meta.save` and `fs.meta.load` faster and benchmark with your data.

**Comment by chrislusf** [comment]
The steps still need the down time. Does the major benefit come from the speed?

btw: For a one-time job on a small filer store, the script is totally fine. The script would be more efficient on memory if the two loops are combined into one, avoiding the large map object `data`.

**Comment by LazyDBA247-Anyvision** [comment]
> The steps still need the down time. Does the major benefit come from the speed?
> 
> btw: For a one-time job on a small filer store, the script is totally fine. The script would be more efficient on memory if the two loops are combined into one, avoiding the large map object `data`.

the major benefit comes from not needing to start filer with "old" config export then close then stat with new config and import, to many steps while needing to block access to the filer.... with the external script, i can just do it when ALL the k8s pods are down (maintenance) and next start start all without any changes to the "production/regular"  config.

yes my first version i wrote was without the map object:
```
import plyvel
import hashlib
import os
import time

current_milli_time = lambda: int(round(time.time() * 1000))

SOURCE_LDB1 = '/ssd/seaweed-filer'
DEST_LDB2 = '/ssd/seaweed-filer/filerldb2'
DB_COUNT = 8
lvlDB = dict()

# check for new filerldb2 folder existence
if not os.path.exists(DEST_LDB2):
    os.mkdir(DEST_LDB2)
# create each sharded leveldb2 folder
for i in range(0, DB_COUNT):
    folder = os.path.join(DEST_LDB2, '{0:02d}'.format(i))
    if not os.path.exists(folder):
        os.mkdir(folder)
    # create db connector for each folder.
    lvlDB[i] = plyvel.DB(folder, create_if_missing=True)

db = plyvel.DB(SOURCE_LDB1, create_if_missing=False)
start_time = current_milli_time()
i = 0
with db.iterator() as it:
    for k, v in it:
        i += 1
        # split old leveldb key on 0x00
        dirPath, Key = k.split(b'\x00')
        # create md5 from dirPath
        md5 = hashlib.md5(dirPath).digest()
        # use last byte to generate the partition (shard)
        p = md5[-1] % 8
        # create new leveldb2 key
        newK = md5+Key
        # save each shared/partition key in it own list
        lvlDB[p].put(newK, v)
for d in lvlDB:
    lvlDB[d].close()
print(f"items: {i}, total_time_sec: {(current_milli_time()-start_time) /1000}")
```

**Comment by LazyDBA247-Anyvision** [comment]
> Could you please share your old leveldb data in '/ssd/seaweed-filer'? I want to make the `fs.meta.save` and `fs.meta.load` faster and benchmark with your data.

includes old & new (script output)
https://drive.google.com/file/d/17JeUCc-5sQ6tuP4XUGPJJx9m9sT7TODw/view?usp=sharing

around 164K "folders" with 4 files in each.
without map (python dictionary) = items: 817175, total_time_sec: 3.845
with map (python dictionary) + leveldb batch write = Done export, time to export_sec: 2.289
items: 817175, import_time_sec: 0.654, total_time_sec: 2.943 

example folder.
![image](https://user-images.githubusercontent.com/45972051/61830082-ffa4b580-ae72-11e9-8327-8a2ebc0a9843.png)

**Comment by LazyDBA247-Anyvision** [comment]
> Could you please share your old leveldb data in '/ssd/seaweed-filer'? I want to make the `fs.meta.save` and `fs.meta.load` faster and benchmark with your data.

I think if you can provide `fs.meta.sync SOURCE_CONFIG_FILER_TOML DEST_CONFIG_FILER_TOML` which will do like fs.meta.save & fs.meta.load from another/old config in the filer.toml, we can have no downtime for new data, and old will be loaded online. I think that will make seaweedfs much better in terms of migration between filer backends & even can enable a cron job for backup filer data to Postgres/Cassandra every night while using leveldb for performance, online?

**Comment by chrislusf** [comment]
Added minor changes to `fs.meta.save`
* added an option to set the output file name
* added an option to see verbose output, default to non-verbose mode

**Comment by bash99** [comment]
@LazyDBA247-Anyvision a little off-topic question, does you use leveldb/leveldb2 in production, how do you achieve HA as it's a local storage?

**Comment by LazyDBA247-Anyvision** [comment]
Only on aio...
We are testing memsql/postgres as the filer backend in cluster/ha mode...
