### ISSUE TITLE
data backup failed,seaweedfs version is 1.42

### ISSUE THREAD

**Issue by doufighting** [chrislusf/seaweedfs#1022]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

example of a good issue report:
https://github.com/chrislusf/seaweedfs/issues/1005
example of a bad issue report:
https://github.com/chrislusf/seaweedfs/issues/1008

**Describe the bug**

i use weed backup to backup the data file,but failed

**System Setup**

seaweedfs version is 1.42,i have run a seaweedfs on one machine:
    weed master -mdir=''/data/master" -ip=ip1 
    weed volume -dir="/data/vs_1"  -max=30 -mserver=ip1:9333 -ip=ip1 -port=9060
then i run weed backup on machine2 ,use :
    weed backup -server=ip1:9333 -dir=/data -volumeId=1
i got the message below:
    I0727 09:34:05 12536 config.go:28] Reading : Config File "security" Not Found    in "[/home/dd /root/.seaweedfs /etc/seaweedfs]"
    I0727 09:34:05 12536 volume_loading.go:83] loading index /data/1.idx to memory readonly false
then i check the folder /data in mechine2, i found:
    -rw-r--r--  1 root root    8 Jul 27 09:34 1.dat
    -rw-r--r--  1 root root    0 Jul 27 09:34 1.idx
but the size of 1.dat in machine1 is 31457840640, obviously the backup failed. i wonder is there anything wrong i have done?

**Comment by chrislusf** [comment]
could not reproduce. was the volume created using 1.42, or from some older version?

**Comment by doufighting** [comment]
the volume is created by version 0.76,  i have cleared the master folder, but do nothing to data folder,upgrade seaweedfs to version 1.42 from 0.76

**Comment by chrislusf** [comment]
need to use latest volume version for incremental backup.

**Comment by doufighting** [comment]
how can i change the old version volume to latest volume? is there any command to do this?

**Comment by chrislusf** [comment]
change volume version is not necessary. they are considered readonly and should not cause any problem.
