### ISSUE TITLE
001模式下，发生单台volumeserver宕机，如何保障文件的可读性？

### ISSUE THREAD

**Issue by SachChen** [chrislusf/seaweedfs#1025]
你好，我创建了一个三节点的master集群和一个rack，001模式，里面有三台volumeserver,如果其中一台volumeserver宕机，master不会更新注册状态，依旧会重定向到这个volumeserver,请问有没有方法让master不去重定向到已宕机的volumeserver上，感谢！

**Comment by chrislusf** [comment]
Please follow the issue template and add logs.
