### ISSUE TITLE
Disk space release issue after deleting files

### ISSUE THREAD

**Issue by xiangshibo** [chrislusf/seaweedfs#1027]
After deleting the file under Linux, the disk space is not released, so I executed "http://localhost:9333/vol/vacuum", but when I executed it, the whole process was very time consuming (my file is about again 3000G), and the file cannot be written in the whole process, the business will be affected. Is there any way to solve this problem? Thank you.

**Comment by chrislusf** [comment]
Smaller volume size, more volumes.

**Comment by xiangshibo** [comment]
It’s too scary, it’s not finished in six hours.

**Comment by chrislusf** [comment]
It is not good to use large volume size for frequent updates.

The compaction is copy on write. If the compaction fail, the original data volume is still safe.
