### ISSUE TITLE
jwt 设计的问题

### ISSUE THREAD

**Issue by cocosip** [chrislusf/seaweedfs#1028]
- > 看了作者关于 `jwt` 这块的设计,并且自己也实践了之后，有些疑问。按照作者目前的思路是只要获取了 `fid`,在文件修改跟删除的时候,直接能根据 `fid` 获取 `jwt token`,然后再根据 `jwt token` 能直接修改或者删除该文件。那是否意味着 `jwt token` 并没有起到安全保障的作用? 在很多时候,我们的服务器端可能是直接返回文件的 `url` 给客户端的, 类似 `http://127.0.0.1:9333/15,27a6f20d92eb`,客户端在这个时候是能直接拿到 `fid`的。这样服务器端的修改,删除操作还是暴露在客户端下的

**Comment by chrislusf** [comment]
JWT is from the master server. Just separate the master server from the clients.
