### ISSUE TITLE
[future] Add "enableAuditLog" option to master and volume server

### ISSUE THREAD

**Issue by yourchanges** [chrislusf/seaweedfs#103]
The default value of "enableAuditLog" option is false. when it set to true, it will produce the audit log files.

Because  some critical operations,  such as: '/delete', PUT/POST actions,  need be record in same format for audit use case.

There are the import fields should be record:
time(ms);clientIP;ACTION;FID

Any other suggestions?

**Comment by chrislusf** [comment]
If fronted by nginx, this log can be generated with nginx logs?
