### ISSUE TITLE
 losing production data

### ISSUE THREAD

**Issue by xiangshibo** [chrislusf/seaweedfs#1030]
When I executed the "http://localhost:9333/vol/vacuum" command, a lot of data was lost.
Is there a way to retrieve lost data? I am losing production data.

**Comment by chrislusf** [comment]
how to help you without any details?

**Comment by xiangshibo** [comment]
![image](https://user-images.githubusercontent.com/11767971/62407158-6863fe80-b5e6-11e9-977f-c18aa4451a80.png)
The volume related to port 8083 has no way to access it.
When I execute vacuum, my disks are full.

**Comment by chrislusf** [comment]
please follow the issue template.

**Comment by xiangshibo** [comment]
what issue template?

**Comment by chrislusf** [comment]
when creating an issue, you should be able to see the option.

**Comment by chrislusf** [comment]
not actionable.
