### ISSUE TITLE
fs.meta.save lost data

### ISSUE THREAD

**Issue by chen2aaron** [chrislusf/seaweedfs#1032]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**
I want to change a new filer storage.
so i use `fs.meta.save` to dump data.
but it lost many data.

**System Setup**
List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
```
/data/seaweedfs/weed master -port 19333 -ip 192.168.140.111 -ip.bind 192.168.140.111
/data/seaweedfs/weed filer -master=192.168.140.111:19333 -port=9998 -port.readonly=9999
/data/seaweedfs/weed volume -dir=/data/seaweedfs/vol1 -max=15 -mserver="192.168.140.111:19333" -port=18080 -ip=192.168.140.111 -ip.bind=192.168.140.111
```
use shell command
```
./weed shell -master 192.168.140.111:19333
> fs.cd http://192.168.140.111:9998/
> fs.meta.save
...
...
/images/666kb.com/i/e3l7c2udy8y7q49og.jpg
/images/666kb.com/i/e3l7cjwpdknks77y8.jpg
/images/666kb.com/i/e3l7d8luxemvrvaww.jpg

total 56695 directories, 94760 files
meta data for http://192.168.140.111:9998/ is saved to 192.168.140.111-9998-20190806-064321.meta
> 
```

**Expected behavior**
There should actually be 8.4 million files.

```
➜  ~ redis-cli
127.0.0.1:6379> DBSIZE
(integer) 8409980
```

**Screenshots**

**Additional context**

**Comment by chrislusf** [comment]
Can not debug unless you have a dump of your redis database.

**Comment by chrislusf** [comment]
make sure your redis do not evict keys.

**Comment by chen2aaron** [comment]
redis info
```
# Stats
evicted_keys:0
```
I'm sure there no evicted keys

**Comment by chrislusf** [comment]
fine. need to have a reproducible case.

**Comment by chen2aaron** [comment]
I just sliced the data in the interrupted position, tried to reproduce it.  But it run ok.
So I guess the reason for the lack of memory,
Now I try to increase the memory to reproduce

**Comment by chen2aaron** [comment]
Not a memory problem.
It seems that it can only be reproduced when the amount of redis data is particularly large.
May be a recursion problem in `command_fs_meta_save.go`
The `dump.rdb` is 1.2G.
I'm trying to reproduce in my local redis.

**Comment by chrislusf** [comment]
If you can upload the dump to somewhere, I can try to reproduce it locally also.

**Comment by chen2aaron** [comment]
Ok, thank you. I will send dump.rdb to your email.

**Comment by chen2aaron** [comment]
....I forgot. I don't have your email yet.

**Comment by chrislusf** [comment]
fixed in https://github.com/chrislusf/seaweedfs/commit/fb3c9ed80d37a08dcf9f8f6a926e7734816a2a63

**Comment by zhutongcloud** [comment]
Excuse me？How can I transfer the metadata in redis to MySQL?
