### ISSUE TITLE
failing to connect to volume server /buckets/testp3/myobjects56588?collection=testp3: Put http://xxx.xxx.x.x:xxxx/19,0570ec2df0615c: net/http:  request canceled (Client.Timeout exceeded while awaiting headers), PUT

### ISSUE THREAD

**Issue by ahnselina** [chrislusf/seaweedfs#1033]
3 master servers and 6 volume servers

Leader | 192.168.2.1:9333
-- | --
Other Masters: | 192.168.2.2:9333, 192.168.2.3:9333

Concurrent Connections | 70
-- | --
Version | 30GB 1.42

Data Center | Rack | RemoteAddr | #Volumes | #ErasureCodingShards | Max
-- | -- | -- | -- | -- | --
DefaultDataCenter | DefaultRack | 192.168.2.4:11011 | 1 | 0 | 7
DefaultDataCenter | DefaultRack | 192.168.2.4:11111 | 3 | 0 | 7
DefaultDataCenter | DefaultRack | 192.168.2.5:11111 | 2 | 0 | 7
DefaultDataCenter | DefaultRack | 192.168.2.5:11011 | 2 | 0 | 7
DefaultDataCenter | DefaultRack | 192.168.2.6:11111 | 3 | 0 | 7
DefaultDataCenter | DefaultRack | 192.168.2.6:11011 | 1 | 0 | 7

on  192.168.2.1，start a filer and s3 api server.

then I use COSBench tool to test the s3 api performance.
the COSBench config as follows:
<?xml version="1.0" encoding="UTF-8" ?>
<workload name="S3Test" description="Performance">
    <storage type="s3" config="accesskey=any;secretkey=any;endpoint=http://192.168.2.1:8333" /> 
    <workflow>
    
        <workstage name="init">
            <work type="init" workers="1" config="cprefix=testp;containers=r(1,2)" /> 
        </workstage>
    
    
        <workstage name="sequential_WO_8W_4MB">
            <work name="sequential_WO_8W_4MB" workers="200" totalOps="60000">
                <operation type="write" ratio="100" config="cprefix=testp;containers=c(1);objects=s(1,60000);sizes=c(4)MB" /> 
            </work>
        </workstage>
    
        <workstage name="random_WO_8W_4MB">
            <work name="random_WO_8W_4MB" workers="200" totalOps="60000">
                <operation type="write" ratio="100" config="cprefix=testp;containers=c(2);objects=u(1,60000);sizes=c(4)MB" /> 
            </work>
        </workstage>
    
        <workstage name="cleanup">
            <work type="cleanup" workers="1" config="cprefix=testp;containers=r(1,2);objects=r(1,60000)" />
        </workstage>
    
        <workstage name="dispose">
            <work type="dispose" workers="1" config="cprefix=testp;containers=r(1,2)" />
        </workstage>
    
        <workstage name="init">
            <work type="init" workers="1" config="cprefix=testp;containers=r(1,2)" /> 
        </workstage>
    
    
        <workstage name="sequential_WO_32w_64KB">
            <work name="sequential_WO_32w_64KB" workers="200" totalOps="60000">
                <operation type="write" ratio="100" config="cprefix=testp;containers=c(1);objects=s(1,60000);sizes=c(64)KB" /> 
            </work>
        </workstage>
    
        <workstage name="random_WO_32W_64KB">
            <work name="random_WO_32W_64KB" workers="200" totalOps="60000">
                <operation type="write" ratio="100" config="cprefix=testp;containers=c(2);objects=u(1,60000);sizes=c(64)KB" /> 
            </work>
        </workstage>
    
        <workstage name="cleanup">
            <work type="cleanup" workers="1" config="cprefix=testp;containers=r(1,2);objects=r(1,60000)" />
        </workstage>
    
        <workstage name="dispose">
            <work type="dispose" workers="1" config="cprefix=testp;containers=r(1,2)" />
        </workstage>
    </workflow>
</workload>

then I start the test, but there are a lot of errors about Client.Timeout 

S3 SERVER：
s3api_object_handlers.go:203] upload to filer error: Put http://192.168.2.6:11111/33,066ed1ccbedba4: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

FILER SERVER:
failing to connect to volume server /buckets/testp3/myobjects56588?collection=testp3: Put http://xxx.xxx.x.x:xxxx/19,0570ec2df0615c: net/http:  request canceled (Client.Timeout exceeded while awaiting headers), PUT

When the data size is 4MB, always ocurr this error, and the performance is slow:

Op-Type | Op-Count | Byte-Count | Avg-ResTime | Avg-ProcTime | Throughput | Bandwidth | Succ-Ratio
-- | -- | -- | -- | -- | -- | -- | --
write | 60 kops | 240 GB | 3013.68 ms | 2985.7 ms | 66.38 op/s | 265.52 MB/S | 100%

when the data size  is 64KB, it seams right and the performace is reasonable

Op-Type | Op-Count | Byte-Count | Avg-ResTime | Avg-ProcTime | Throughput | Bandwidth | Succ-Ratio
-- | -- | -- | -- | -- | -- | -- | --
op1: init -write | 0 ops | 0 B | N/A | N/A | 0 op/s | 0 B/S | N/A
op1: write | 300 kops | 19.2 GB | 63.3 ms | 62.76 ms | 3133.62 op/s | 200.55 MB/S | 100%

**Comment by chrislusf** [comment]
What's the command line to start master, volume server, filer, s3 servers? And how to run COSBench?

**Comment by ahnselina** [comment]
start master command:
./weed -logdir=/var/log/seaweedfs master -ip=192.168.2.1 -port=9333 -mdir=/data2/seaweedfs -peers=192.168.2.1:9333,192.168.2.2:9333,192.168.2.3:9333 
./weed -logdir=/var/log/seaweedfs master -ip=192.168.2.2 -port=9333 -mdir=/data2/seaweedfs -peers=192.168.2.1:9333,192.168.2.2:9333,192.168.2.3:9333 
./weed -logdir=/var/log/seaweedfs master -ip=192.168.2.52 -port=9333 -mdir=/data2/seaweedfs -peers=192.168.2.1:9333,192.168.2.2:9333,192.168.2.3:9333

start volume server command:
./weed -logdir=/var/log/seaweedfs volume -ip=192.168.2.4 -dir=/data1/seaweedfs -port=11011 -mserver=192.168.2.1:9333,192.168.2.2:9333,192.168.2.3:9333 
....

start filer command:
./weed -logdir=/var/log/seaweedfs filer -ip=192.168.2.1 -port=8888 -master=192.168.2.1:9333,192.168.2.2:9333,192.168.2.3:9333 -defaultReplicaPlacement=001

start s3 server:
./weed -logdir=/var/log/seaweedfs s3 -filer=192.168.2.1:8888

You can refer to this address to run COSBench:
https://www.cnblogs.com/landhu/p/5843282.html
Simply，
1. download the COSBench tool：https://github.com/intel-cloud/cosbench/releases/download/v0.4.2/0.4.2.zip

2. Unzip and extract

3. sh start-all.sh to start the tool

4. run "sh cli.sh submit conf/config_xxx.xml" to submit your task

**Comment by chrislusf** [comment]
success rate is 100%, and bandwidth is around 200MB/s. This seems reasonable.

**Comment by ahnselina** [comment]
network speed:
iperf -c 192.168.2.1 -i 1
------------------------------------------------------------
Client connecting to 192.168.2.1, TCP port 5001
TCP window size: 19.3 KByte (default)
------------------------------------------------------------
[  3] local 192.168.2.4 port 34808 connected with 192.168.2.1 port 5001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0- 1.0 sec   441 MBytes  3.70 Gbits/sec
[  3]  1.0- 2.0 sec   266 MBytes  2.23 Gbits/sec
[  3]  2.0- 3.0 sec   206 MBytes  1.73 Gbits/sec
[  3]  3.0- 4.0 sec   294 MBytes  2.46 Gbits/sec
[  3]  4.0- 5.0 sec   229 MBytes  1.92 Gbits/sec
[  3]  5.0- 6.0 sec   230 MBytes  1.93 Gbits/sec
[  3]  6.0- 7.0 sec   248 MBytes  2.08 Gbits/sec
[  3]  7.0- 8.0 sec   241 MBytes  2.02 Gbits/sec
[  3]  8.0- 9.0 sec   229 MBytes  1.92 Gbits/sec
[  3]  9.0-10.0 sec   251 MBytes  2.11 Gbits/sec
[  3]  0.0-10.0 sec  2.57 GBytes  2.21 Gbits/sec

I want to know：
1. success rate is 100%, but the log has a lot of the error, is this right situation？
2. 4MB object, the op/s only about 70 op/s, is this reasonable?The performance has dropped a lot compare to the 64kB object

**Comment by chrislusf** [comment]
1. should be good.
2. 4MB x 70 op/s is about the same as 64KB x 3200 op/s. The bottleneck is your network.

**Comment by ahnselina** [comment]
> 1. should be good.
> 2. 4MB x 70 op/s is about the same as 64KB x 3200 op/s. The bottleneck is your network.

Thanks Chris. Much appreciated.
