### ISSUE TITLE
VisitNeedle panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ahnselina** [chrislusf/seaweedfs#1035]
Hi, I run performance test , the env info is the same as https://github.com/chrislusf/seaweedfs/issues/1033

Leader | 192.168.2.1:9333
-- | --
Other Masters: | 192.168.2.2:9333, 192.168.2.3:9333

Concurrent Connections | 70
-- | --
Version | 30GB 1.42

Data Center | Rack | RemoteAddr | #Volumes | #ErasureCodingShards | Max
-- | -- | -- | -- | -- | --
DefaultDataCenter | DefaultRack | 192.168.2.4:11011 | 1 | 0 | 7
DefaultDataCenter | DefaultRack | 192.168.2.4:11111 | 3 | 0 | 7
DefaultDataCenter | DefaultRack | 192.168.2.5:11111 | 2 | 0 | 7
DefaultDataCenter | DefaultRack | 192.168.2.5:11011 | 2 | 0 | 7
DefaultDataCenter | DefaultRack | 192.168.2.6:11111 | 3 | 0 | 7
DefaultDataCenter | DefaultRack | 192.168.2.6:11011 | 1 | 0 | 7

when finished a performance test, I found that there was a volume server down.
The error info is:
./weed -logdir=/var/log/seaweedfs volume -ip=192.168.2.6 -dir=/data2/seaweedfs -port=11111 -mserver=192.168.2.1:9333,192.168.2.2:9333,192.168.2.3:9333
I0808 15:37:57 24934 config.go:28] Reading : Config File "security" Not Found in "[/root /root/.seaweedfs /etc/seaweedfs]"
I0808 15:37:57 24934 file_util.go:19] Folder /data2/seaweedfs Permission: -rwxr-xr-x
I0808 15:37:57 24934 disk_location.go:109] Store started on dir: /data2/seaweedfs with 0 volumes max 7
I0808 15:37:57 24934 disk_location.go:112] Store started on dir: /data2/seaweedfs with 0 ec shards
I0808 15:37:57 24934 volume.go:162] Start Seaweed volume server 30GB 1.42 at 0.0.0.0:11111
I0808 15:37:57 24934 volume_grpc_client_to_master.go:24] Volume server start with seed master nodes: [192.168.2.1:9333 192.168.2.2:9333 192.168.2.3:9333]
I0808 15:37:57 24934 volume_grpc_client_to_master.go:68] Heartbeat to: 192.168.2.1:9333
I0808 15:39:06 24934 store.go:109] In dir /data2/seaweedfs adds volume:84 collection:testp1 replicaPlacement:001 ttl:
I0808 15:39:06 24934 volume_loading.go:83] loading index /data2/seaweedfs/testp1_84.idx to memory readonly false
I0808 15:39:06 24934 store.go:113] add volume 84
I0808 15:39:06 24934 store.go:109] In dir /data2/seaweedfs adds volume:85 collection:testp1 replicaPlacement:001 ttl:
I0808 15:39:06 24934 volume_loading.go:83] loading index /data2/seaweedfs/testp1_85.idx to memory readonly false
I0808 15:39:06 24934 store.go:113] add volume 85
I0808 15:39:06 24934 store.go:109] In dir /data2/seaweedfs adds volume:86 collection:testp1 replicaPlacement:001 ttl:
I0808 15:39:06 24934 volume_loading.go:83] loading index /data2/seaweedfs/testp1_86.idx to memory readonly false
I0808 15:39:06 24934 store.go:113] add volume 86
I0808 15:39:06 24934 store.go:109] In dir /data2/seaweedfs adds volume:87 collection:testp1 replicaPlacement:001 ttl:
I0808 15:39:06 24934 volume_loading.go:83] loading index /data2/seaweedfs/testp1_87.idx to memory readonly false
I0808 15:39:06 24934 store.go:113] add volume 87
I0808 15:43:04 24934 store.go:109] In dir /data2/seaweedfs adds volume:89 collection:testp2 replicaPlacement:001 ttl:
I0808 15:43:04 24934 volume_loading.go:83] loading index /data2/seaweedfs/testp2_89.idx to memory readonly false
I0808 15:43:04 24934 store.go:113] add volume 89
I0808 15:43:04 24934 store.go:109] In dir /data2/seaweedfs adds volume:90 collection:testp2 replicaPlacement:001 ttl:
I0808 15:43:04 24934 volume_loading.go:83] loading index /data2/seaweedfs/testp2_90.idx to memory readonly false
I0808 15:43:04 24934 store.go:113] add volume 90
I0808 15:43:04 24934 store.go:109] In dir /data2/seaweedfs adds volume:93 collection:testp2 replicaPlacement:001 ttl:
I0808 15:43:04 24934 volume_loading.go:83] loading index /data2/seaweedfs/testp2_93.idx to memory readonly false
I0808 15:43:04 24934 store.go:113] add volume 93
I0808 15:52:47 24934 volume_vacuum.go:46] Committing volume 89 vacuuming...
I0808 15:52:47 24934 volume_loading.go:83] loading index /data2/seaweedfs/testp2_89.idx to memory readonly false
I0808 15:55:27 24934 volume_vacuum.go:46] Committing volume 90 vacuuming...
I0808 15:55:27 24934 volume_loading.go:83] loading index /data2/seaweedfs/testp2_90.idx to memory readonly false
I0808 16:05:43 24934 volume_vacuum.go:46] Committing volume 93 vacuuming...
I0808 16:05:43 24934 volume_loading.go:83] loading index /data2/seaweedfs/testp2_93.idx to memory readonly false
I0808 16:08:48 24934 volume_vacuum.go:46] Committing volume 86 vacuuming...
I0808 16:08:49 24934 volume_loading.go:83] loading index /data2/seaweedfs/testp1_86.idx to memory readonly false
I0808 16:10:32 24934 volume_vacuum.go:46] Committing volume 87 vacuuming...
I0808 16:10:32 24934 volume_loading.go:83] loading index /data2/seaweedfs/testp1_87.idx to memory readonly false

**panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0xaf67b5]**

**goroutine 100916 [running]:**
github.com/chrislusf/seaweedfs/weed/storage.(*VolumeFileScanner4Vacuum).VisitNeedle(0xc007802140, 0xc0003cc000, 0x24d3bfd70, 0x24d3bfd80, 0xf4278)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/storage/volume_vacuum.go:264 +0x95
github.com/chrislusf/seaweedfs/weed/storage.ScanVolumeFileFrom(0xc000000003, 0xc00000e1d8, 0x24d3bfd70, 0x1b0d260, 0xc007802140, 0x0, 0x0)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/storage/volume_read_write.go:209 +0x2e6
github.com/chrislusf/seaweedfs/weed/storage.ScanVolumeFile(0x7ffef59005af, 0x10, 0xc0004839e0, 0x6, 0xc000000054, 0x0, 0x1b0d260, 0xc007802140, 0x0, 0x0)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/storage/volume_read_write.go:190 +0x3e3
github.com/chrislusf/seaweedfs/weed/storage.(*Volume).copyDataAndGenerateIndexFile(0xc0002d3b80, 0xc000474d20, 0x1e, 0xc000474d40, 0x1e, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/storage/volume_vacuum.go:302 +0x3e3
github.com/chrislusf/seaweedfs/weed/storage.(*Volume).Compact(0xc0002d3b80, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/storage/volume_vacuum.go:35 +0x285
github.com/chrislusf/seaweedfs/weed/storage.(*Store).CompactVolume(0xc000130300, 0x54, 0x0, 0x0, 0x1739700, 0x179fd40)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/storage/store_vacuum.go:19 +0x136
github.com/chrislusf/seaweedfs/weed/server.(*VolumeServer).VacuumVolumeCompact(0xc0000ebae0, 0x1b197a0, 0xc002aae690, 0xc0000cfbb0, 0xc0000ebae0, 0xc002aae690, 0xc0004ccba8)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/server/volume_grpc_vacuum.go:31 +0x81
github.com/chrislusf/seaweedfs/weed/pb/volume_server_pb._VolumeServer_VacuumVolumeCompact_Handler(0x179fd40, 0xc0000ebae0, 0x1b197a0, 0xc002aae690, 0xc0000ecd20, 0x0, 0x1b197a0, 0xc002aae690, 0xc0000cfba8, 0x2)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/pb/volume_server_pb/volume_server.pb.go:1902 +0x23e
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004162c0, 0x1b314e0, 0xc000511500, 0xc000452000, 0xc00016c120, 0x2879110, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/google.golang.org/grpc/server.go:989 +0x470
google.golang.org/grpc.(*Server).handleStream(0xc0004162c0, 0x1b314e0, 0xc000511500, 0xc000452000, 0x0)
	/home/travis/gopath/src/google.golang.org/grpc/server.go:1269 +0xda6
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000483820, 0xc0004162c0, 0x1b314e0, 0xc000511500, 0xc000452000)
	/home/travis/gopath/src/google.golang.org/grpc/server.go:708 +0x9f
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/travis/gopath/src/google.golang.org/grpc/server.go:706 +0xa1

**Comment by chrislusf** [comment]
what are the operations in your tests?

**Comment by ahnselina** [comment]
60000 upload object operation and then delete the objects

**Comment by chrislusf** [comment]
share the code?

**Comment by ahnselina** [comment]
I run the tests using COSBench tool, and the config as follows:
<?xml version="1.0" encoding="UTF-8" ?>
<workload name="S3Test" description="Performance">
    <storage type="s3" config="accesskey=any;secretkey=any;endpoint=http://192.168.2.53:8333" />
    <workflow>

        <workstage name="init">
            <work type="init" workers="1" config="cprefix=testp;containers=r(1,2)" />
        </workstage>


        <workstage name="sequential_WO_8W_4MB">
            <work name="sequential_WO_8W_4MB" workers="50" totalOps="60000">
                <operation type="write" ratio="100" config="cprefix=testp;containers=c(1);objects=s(1,60000);sizes=c(4)MB" />
            </work>
        </workstage>

        <workstage name="random_WO_8W_4MB">
            <work name="random_WO_8W_4MB" workers="50" totalOps="60000">
                <operation type="write" ratio="100" config="cprefix=testp;containers=c(2);objects=u(1,60000);sizes=c(4)MB" />
            </work>
        </workstage>

        <workstage name="cleanup">
            <work type="cleanup" workers="1" config="cprefix=testp;containers=r(1,2);objects=r(1,60000)" />
        </workstage>

        <workstage name="dispose">
            <work type="dispose" workers="1" config="cprefix=testp;containers=r(1,2)" />
        </workstage>

        <workstage name="init">
            <work type="init" workers="1" config="cprefix=testp;containers=r(1,2)" />
        </workstage>


        <workstage name="sequential_WO_32w_32KB">
            <work name="sequential_WO_32w_32KB" workers="400" totalOps="60000">
                <operation type="write" ratio="100" config="cprefix=testp;containers=c(1);objects=s(1,60000);sizes=c(32)KB" />
            </work>
        </workstage>

        <workstage name="random_WO_32W_64KB">
            <work name="random_WO_32W_64KB" workers="400" totalOps="60000">
                <operation type="write" ratio="100" config="cprefix=testp;containers=c(2);objects=u(1,60000);sizes=c(64)KB" />
            </work>
        </workstage>

        <workstage name="cleanup">
            <work type="cleanup" workers="1" config="cprefix=testp;containers=r(1,2);objects=r(1,60000)" />
        </workstage>
    
        <workstage name="dispose">
            <work type="dispose" workers="1" config="cprefix=testp;containers=r(1,2)" />
        </workstage>

    </workflow>
</workload>

I guess it maybe the delete task conflicts with the vacuum task?

**Comment by chrislusf** [comment]
COSBench does not work in my mac or ubuntu. Not sure how to reproduce. Is it always reproducible?

**Comment by ahnselina** [comment]
> COSBench does not work in my mac or ubuntu. Not sure how to reproduce. Is it always reproducible?
> 
> What does "cleanup" or "dispose" stage do? Delete the "testp" bucket?


yes , I try many times, it is always reproducible.
“cleanup” stage delete the objects
"dispose" stage delete the “testp1” "testp2" buckets

**Comment by chrislusf** [comment]
Added a fix which will fail the volume deletion stage if the volume is running compaction.

**Comment by ahnselina** [comment]
> Added a fix which will fail the volume deletion stage if the volume is running compaction.

OK, thanks. This problem is that when doing compaction, it happens to encounter the delete collection, then nm is nil, so it leads to panic?

**Comment by chrislusf** [comment]
yes
