### ISSUE TITLE
Update existing file fails - Even possible?

### ISSUE THREAD

**Issue by Joi3432** [chrislusf/seaweedfs#1036]
**Describe the bug**
I want to perform updates to existing files by uploading the data to the already existing fid. The first upload works, but then all following updates will fail with an HTTP error:

**System Setup**
Running version 1.4.2 on Linux64
./weed master -mdir="master01" -defaultReplication=002
./weed volume -port=8081 -mserver="localhost:9333" -dir="volume01" -max=100
./weed volume -port=8082 -mserver="localhost:9333" -dir="volume02" -max=100
./weed volume -port=8083 -mserver="localhost:9333" -dir="volume03" -max=100

**Expected behavior**
I would expect that the file upload works like the first with this file. But maybe I'm wrong and the update of an existing file is not possible. An other way would be to assign a new file id for every update and to delete the old.

**Sequence**

_Client:_
curl -F file=myFile http://127.0.0.1:8083/3,02b3f5780c

Response:
`{"size":8,"error":"failed to write to replicas for volume 3: [127.0.0.1:8081]: unexpected end of JSON input\n[127.0.0.1:8082]: unexpected end of JSON input","eTag":"0ca153a6"}`

_Master:_
No related console output

_volume01:_
`I0809 23:03:11 11674 common.go:73] error writing JSON {Name: Size:8 Error: ETag:0ca153a6} status 304: http: req`

_volume02:_
`I0809 23:03:11 11704 common.go:73] error writing JSON {Name: Size:8 Error: ETag:0ca153a6} status 304: http: request method or response status code does not allow body`

_volume03:_
```
I0809 23:03:11 11688 upload_content.go:136] failing to read upload response http://127.0.0.1:8081/3,02b3f5780c?ts=1565384591&ttl=&type=replicate 
I0809 23:03:11 11688 upload_content.go:136] failing to read upload response http://127.0.0.1:8082/3,02b3f5780c?ts=1565384591&ttl=&type=replicate
```

Thank you!

**Comment by chrislusf** [comment]
1. You only need to upload to one volume server, which will automatically replicate the file to other volume servers.

2. The status code is 304, meaning there are no change detected.

3. Recommended way is to "assign a new file id for every update and to delete the old".
