### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by dzang** [chrislusf/seaweedfs#1037]
we run a 3 nodes cluster, the filer crashed with the logs below:
`
I0810 09:30:20 50306 filer_server_handlers_read.go:110] retrieving from http://10.1.1.8:8086/356,1ceface4bc067f11
I0810 09:30:20 50306 filer_server_handlers_read.go:110] retrieving from http://10.1.1.9:8083/358,1ceface561ee49ac
E0810 09:30:20 50306 filer_server_handlers_write.go:220] failing to connect to volume server /buckets/flying/city_77accf10-de57-4b2a-9290-c454b74855bb_2450ce47-fa12-4675-9178-1a420758a7f4_2019-08-10-09-30-20?collection=flying: Put http://10.1.1.9:8083/358,1cefad550f83e29a: EOF, PUT
I0810 09:30:20 50306 filer_server_handlers_read.go:110] retrieving from http://10.1.1.9:8083/358,1ceface3c9c41095
I0810 09:30:20 50306 filer_server_handlers_read.go:110] retrieving from http://10.1.1.8:8084/357,1cefaceebf43bfd6
I0810 09:30:20 50306 filer_server_handlers_read.go:110] retrieving from http://10.1.1.9:8083/358,1cefacec70d021cb
I0810 09:30:20 50306 filer_server_handlers_read.go:110] retrieving from http://10.1.1.9:8083/358,1cefacea2dc550fc
I0810 09:30:20 50306 filer_server_handlers_read.go:110] retrieving from http://10.1.1.10:8086/355,1cefacf1c7d2c9fc
I0810 09:30:20 50306 filer_server_handlers_read.go:110] retrieving from http://10.1.1.8:8084/357,1cefad18509228e2
I0810 09:30:20 50306 filer_server_handlers_read.go:110] retrieving from http://10.1.1.8:8086/356,1cefacf9cbb94966
I0810 09:30:20 50306 filer_server_handlers_read.go:110] retrieving from http://10.1.1.10:8088/359,1cefad141ac736e7
I0810 09:30:20 50306 filer_server_handlers_read.go:110] retrieving from http://10.1.1.10:8088/359,1cefad26a6f3862d
I0810 09:30:20 50306 filer_server_handlers_read.go:110] retrieving from http://10.1.1.8:8084/357,1cefad3a7c0259cc
I0810 09:30:20 50306 filer_server_handlers_read.go:110] retrieving from http://10.1.1.9:8083/358,1cefad1a7570d893
I0810 09:30:20 50306 filer_server_handlers_read.go:110] retrieving from http://10.1.1.10:8088/359,1cefaced3a003efa
I0810 09:30:20 50306 filer_server_handlers_read.go:110] retrieving from http://10.1.1.9:8083/358,1cefad72b0d58766
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x5ddc4f]

goroutine 1891459290 [running]:
bufio.(*Writer).Available(...)
        /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/bufio/bufio.go:607
bufio.(*Writer).WriteString(0x0, 0x18c2de7, 0x19, 0x10100c00ecbd498, 0x0, 0x8000)
        /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/bufio/bufio.go:688 +0x7f
net/http.(*expectContinueReader).Read(0xc00905c1e0, 0xc00a722000, 0x8000, 0x8000, 0xc0130e2c20, 0x44409c, 0x8000)
        /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/net/http/server.go:890 +0x13b
net/http.transferBodyReader.Read(0xc00eb29cc0, 0xc00a722000, 0x8000, 0x8000, 0x0, 0x2a19e00, 0xc011385ea8)
        /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/net/http/transfer.go:62 +0x56
io.copyBuffer(0x7f97ebea0388, 0xc00f992df0, 0x1bd4440, 0xc00eb29cc0, 0xc00a722000, 0x8000, 0x8000, 0x3, 0x1, 0xc0130e2d01)
        /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/io/io.go:402 +0x122
io.Copy(...)
        /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/io/io.go:364
net/http.(*transferWriter).writeBody(0xc00eb29cc0, 0x1bce700, 0xc0101f65c0, 0x2, 0x2)
        /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/net/http/transfer.go:358 +0x16b
net/http.(*Request).write(0xc004719500, 0x1bce700, 0xc0101f65c0, 0x0, 0x0, 0xc00cf8d280, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/net/http/request.go:655 +0x721
net/http.(*persistConn).writeLoop(0xc00003d320)
        /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/net/http/transport.go:1979 +0x1b8
created by net/http.(*Transport).dialConn
        /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/net/http/transport.go:1358 +0xb0d`

**Comment by chrislusf** [comment]
Need more info. Please follow the issue template.

**Comment by dzang** [comment]
OS info : CentOS Linux release 7.5.1804 (Core), 3.10.0-862.el7.x86_6
filer use leveldb2

**Comment by chrislusf** [comment]
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
- OS version
- output of weed version
- if using filer, show the content of filer.toml

**Comment by dzang** [comment]
![image](https://user-images.githubusercontent.com/812872/62819384-20fde500-bb87-11e9-88f3-409c7e2da77b.png)
version 30GB 1.41 linux amd64

**Comment by chrislusf** [comment]
can not tell. seems there are some log lines missing. There are no SeaweedFS code in the stack trace.

**Comment by chrislusf** [comment]
seems related to https://github.com/golang/go/issues/30580

https://github.com/fabiolb/fabio/issues/659 has the same problem.

**Comment by chrislusf** [comment]
there are some log lines missing. There are no SeaweedFS code in the stack trace.

**Comment by dzang** [comment]
Hi chrislusf, any suggestions to debug or resolve this problem, upgrade higher go version or build an debug version weed?

**Comment by chrislusf** [comment]
Need logs to see where the stacktrace happens from the SeaweedFS code. Current log is missing these info.

**Comment by mastak** [comment]
Hi @chrislusf,

I faced with the same message when started rebalancing:
```
seaweedfs@data1:/root$ echo "volume.balance -force" | /usr/local/bin/weed shell -master=*.*.238.121:9333
ERROR 2019/08/12 08:49:39 Couldn't discover absolute path
ERROR 2019/08/12 08:49:39 stat .: permission denied
I0812 08:49:39 17634 config.go:28] Reading : Config File "security" Not Found in "[ /home/seaweedfs/.seaweedfs /etc/seaweedfs]"
moving volume 3 *.*.238.8:8081 => *.*.238.8:8082
2019/08/12 08:49:39 copying volume 3 from *.*.238.8:8081 to *.*.238.8:8082
2019/08/12 08:52:30 tailing volume 3 from *.*.238.8:8081 to *.*.238.8:8082
2019/08/12 08:52:42 deleting volume 3 from *.*.238.8:8081
error: delete volume 3 from *.*.238.8:8081: rpc error: code = Unavailable desc = transport is closing
```

Volume logs


```
 I0812 07:09:13  5021 volume.go:162] Start Seaweed volume server 30GB 1.42 at 0.0.0.0:8081
 I0812 07:09:13  5021 volume_grpc_client_to_master.go:24] Volume server start with seed master nodes: [*.*.238.121:9333]
 I0812 07:09:13  5021 volume_grpc_client_to_master.go:68] Heartbeat to: *.*.238.121:9333
 panic: runtime error: invalid memory address or nil pointer dereference
 [signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0xae0a0e]
 goroutine 81 [running]:
 github.com/chrislusf/seaweedfs/weed/storage.(*Store).CollectHeartbeat(0xc00011c240, 0xc009b696e8)
         /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/storage/store.go:171 +0x19e
 github.com/chrislusf/seaweedfs/weed/server.(*VolumeServer).doHeartbeat(0xc0001f4960, 0x1b19720, 0xc0000be010, 0x7ffeb4fb6e58, 0x13, 0xc0003ca280, 0x14, 0x1aed280, 0xc00000e288, 0x3b9aca00, ...)
         /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/server/volume_grpc_client_to_master.go:159 +0xe7a
 github.com/chrislusf/seaweedfs/weed/server.(*VolumeServer).heartbeat(0xc0001f4960)
         /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/server/volume_grpc_client_to_master.go:43 +0x28d
 created by github.com/chrislusf/seaweedfs/weed/server.NewVolumeServer
         /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/server/volume_server.go:87 +0x8c1
Aug 12 07:12:24 data2.prophy.science systemd[1]: seaweedfs-volume-8081.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 12 07:12:24 data2.prophy.science systemd[1]: seaweedfs-volume-8081.service: Failed with result 'exit-code'.
Aug 12 07:12:25 data2.prophy.science systemd[1]: seaweedfs-volume-8081.service: Service hold-off time over, scheduling restart.
Aug 12 07:12:25 data2.prophy.science systemd[1]: seaweedfs-volume-8081.service: Scheduled restart job, restart counter is at 9.
Aug 12 07:12:25 data2.prophy.science systemd[1]: Stopped seaweedfs-volume-8081.
Aug 12 07:12:25 data2.prophy.science systemd[1]: Started seaweedfs-volume-8081.
```

**Comment by mastak** [comment]
Some information:

Seaweedfs version: 1.42

2 servers Ubuntu 18.04.2 (4.15.0-52-generic), 4 volumes services (2 services on each node)

Filer config: https://paste.in.ua/3998/

Commands:
```
weed -logdir=/var/log/seaweedfs/master master -ip=•.*.238.121 -mdir=/data/seaweedfs/master-metadata -defaultReplication=010 -pulseSeconds=10 -metrics.address=*.*.238.121:9091
weed -logdir=/var/log/seaweedfs/filer filer -master=*.*.238.121:9333 -defaultReplicaPlacement=010
volumes_8081 -max=230 -pulseSeconds=5 -dataCenter=dc1 -rack=rack1
weed -logdir=/var/log/seaweedfs/volume_8082 volume -mserver=*.*.238.121:9333 -ip=*.*.238.121 -port=8082 -dir=/data/seaweedfs/volumes_8082 -max=230 -pulseSeconds=5 -dataCenter=dc1 -rack=rack1

weed -logdir=/var/log/seaweedfs/volume_8081 volume -mserver=*.*.238.121:9333 -ip=*.*.238.8 -port=8081 -dir=/data/seaweedfs/volumes_8081 -max=230 -pulseSeconds=5 -dataCenter=dc1 -rack=rack2
weed -logdir=/var/log/seaweedfs/volume_8082 volume -mserver=*.*.238.121:9333 -ip=*.*.238.8 -port=8082 -dir=/data/seaweedfs/volumes_8082 -max=230 -pulseSeconds=5 -dataCenter=dc1 -rack=rack2
```

**Comment by chrislusf** [comment]
@mastak thanks for reporting. Your report is similar to https://github.com/chrislusf/seaweedfs/issues/1035 I need to think of a better solution for that.

**Comment by chrislusf** [comment]
@dzang Is this reproducible? It seems a race problem with go http code and not originated from SeaweedFS.

**Comment by dzang** [comment]
> @dzang Is this reproducible? It seems a race problem with go http code and not originated from SeaweedFS.

This happend twice. We have not yet find a way to reproduce it, still trying.

**Comment by chrislusf** [comment]
This should have been fixed by the fix from @xushuxun
