### ISSUE TITLE
Questions about replication on node failure

### ISSUE THREAD

**Issue by Joi3432** [chrislusf/seaweedfs#1038]
I have a question about replication with the following infrastructure:
```
master01: ./weed master -mdir="master01" -defaultReplication=011

volume01: ./weed volume -port=8081 -mserver="master:9333" -dir="data" -dataCenter=dc01 -rack=rack1 -max=10
volume02: ./weed volume -port=8081 -mserver="master:9333" -dir="data" -dataCenter=dc01 -rack=rack1 -max=10
volume03: ./weed volume -port=8081 -mserver="master:9333" -dir="data" -dataCenter=dc01 -rack=rack1 -max=10

volume04: ./weed volume -port=8081 -mserver="master:9333" -dir="data" -dataCenter=dc01 -rack=rack2 -max=10
volume05: ./weed volume -port=8081 -mserver="master:9333" -dir="data" -dataCenter=dc01 -rack=rack2 -max=10
volume06: ./weed volume -port=8081 -mserver="master:9333" -dir="data" -dataCenter=dc01 -rack=rack2 -max=10
```

Lets assume node volume02 in rack1 will die and replaced. How is the data than replicated to keep the level of one copy in the same rack? Is that possible or do I think wrong? 

Edit: And another question:
What would be the procedure to add a new rack with increasing the defaultReplication to 021?

**Comment by chrislusf** [comment]
1. In `weed shell`, run `volume.balance -force` to fix the volumes with missing replicas.
2. restart `weed master` with `defaultReplication` set to 021
