### ISSUE TITLE
failover when volume dir's disk broken

### ISSUE THREAD

**Issue by qszxnp** [chrislusf/seaweedfs#1039]
hi ,
     I am thinking about failover when disk broken(as our disk is very old)
     I use filer and replication is 010, when i upload 1 file, it will be store in to volume server with the same vid.
     my question is，if one of the volume's data dir disk broken and data can not recover,how to start a new volume and recover lost data. i have 2 plan：
plan A: start a new volume with a clean dir and upload all file(maybe take long time) with replication 010
plan B:  copy .dat/.idx file from another volume to a clean dir and start a new volume in that dir.

    planB can work? 
ps: the .dat's md5 is diffrent  but the idx's md5 is same between volumes

**Comment by chrislusf** [comment]
plan B is fine.

plan C: start a new volume with a clean dir, run `volume.fix.replication` in `weed shell`.

**Comment by qszxnp** [comment]
thank you!
