### ISSUE TITLE
File Dir download

### ISSUE THREAD

**Issue by mohandass-pat** [chrislusf/seaweedfs#1040]
Hi,
   This seaweedfs amazing file system. Thanks for this. 
I'm using Directories-and-Files (https://github.com/chrislusf/seaweedfs/wiki/Directories-and-Files)
I just want to know Is there any options to do below items.

1) The there any options to download the whole directory (with all files) as zip or any formate?
2) How to copy the file or directory to one folder to another?
3) Is there any options to manage versioning?
4) Is there any options to get the folder size?

Kindly help me on these things. Thanks in advance :)

**Comment by chrislusf** [comment]
1, 2 and 4, mount the file system, and  do it as local operations.
3. No/Not yet.
4. run `fs.du` in `weed shell`
