### ISSUE TITLE
关于大文件上传，下载的问题

### ISSUE THREAD

**Issue by igool** [chrislusf/seaweedfs#1042]
你好，chrislusf,我这边有一个问题想请教一下你。看到你这边有介绍weed可以支持自动对大文件进行拆分，并能在下载的时候自动合并下载。
`Upload large files with Auto Split/Merge
If the file is large, it's better to upload this way:

weed upload -maxMB=64 the_file_name
This will split the file into data chunks of 64MB each, and upload them separately. The file ids of all the data chunks are saved into an additional meta chunk. The meta chunk's file id are returned.

When downloading the file, just

weed download the_meta_chunk_file_id
The meta chunk has the list of file ids, with each file id on each line. So if you want to process them in parallel, you can download the meta chunk and deal with each data chunk directly.`
请问一下，如果是java的客户端，如何进行操作。有相关的例子可以参考吗？多谢了。

**Comment by chrislusf** [comment]
you can use `weed filer.copy` if you use filer for file operations.

**Comment by igool** [comment]
如果是通过weed filer.copy这个来处理，我现在还不知道哪里可以参考。如果是JAVA端自己分片，就像平常那样存储，我看到有这样一句处理
`Create new large file
SeaweedFS delegates the effort to the client side. The steps are:

split large files into chunks
upload each file chunk as usual, with mime type "application/octet-stream". Save the related info into ChunkInfo struct. Each chunk can be spread onto different volumes, possibly giving faster parallel access.
upload the manifest file with mime type "application/json", and add url parameter "cm=true". The FileId to store the manifest file is the entry point of the large file.`
**upload the manifest file with mime type "application/json", and add url parameter "cm=true"**

这里要构造的manifest对象，是像这样
`type ChunkInfo struct {
	Fid    string `json:"fid"`
	Offset int64  `json:"offset"`
	Size   int64  `json:"size"`
}

type ChunkList []*ChunkInfo

type ChunkManifest struct {
	Name   string    `json:"name,omitempty"`
	Mime   string    `json:"mime,omitempty"`
	Size   int64     `json:"size,omitempty"`
	Chunks ChunkList `json:"chunks,omitempty"`
}`
然后，通过哪个地址可以upload上去？

**Comment by chrislusf** [comment]
create the ChunkManifest json object, and upload the serialized json object as a file, following the normal steps as "master assign" and "upload to assigned volume server"

**Comment by igool** [comment]
多谢，已经解决。
