### ISSUE TITLE
使用./weed master -mdir= "." -ip启动报错

### ISSUE THREAD

**Issue by zpz1024** [chrislusf/seaweedfs#1044]
[root@iz2 local]# ./weed master -mdir= "." -ip=xx.xxx.xxx.xx
I0815 19:38:30 21648 config.go:28] Reading : Config File "security" Not Found in "[/usr/local /root/.seaweedfs /etc/seaweedfs]"
I0815 19:38:30 21648 config.go:28] Reading : Config File "master" Not Found in "[/usr/local /root/.seaweedfs /etc/seaweedfs]"
F0815 19:38:30 21648 master.go:88] Check Meta Folder (-mdir) Writable  : stat : no such file or directory
goroutine 1 [running]:
github.com/chrislusf/seaweedfs/weed/glog.stacks(0xc0004d7800, 0xc00027c1c0, 0x6a, 0xdc)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:767 +0xb1
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).output(0x2889e20, 0xc000000003, 0xc0004e8230, 0x27f0c65, 0x9, 0x58, 0x0)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:718 +0x2d9
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).printf(0x2889e20, 0x3, 0x180c329, 0x2a, 0xc000537e78, 0x2, 0x2)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:656 +0x14e
github.com/chrislusf/seaweedfs/weed/glog.Fatalf(...)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:1149
github.com/chrislusf/seaweedfs/weed/command.runMaster(0x28760a0, 0xc0000b0030, 0x2, 0x2, 0x0)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/command/master.go:88 +0x826
main.main()
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/weed.go:66 +0x2fe

**Comment by chrislusf** [comment]
you have an extra space after equal sign in `-mdir= "."`
