### ISSUE TITLE
Change to 2-stage docker build and releasing

### ISSUE THREAD

**Issue by chrislusf** [chrislusf/seaweedfs#1047]
https://www.johnmiddleton.dev/docker/golang/containers/2019/08/17/docker-and-golang.html

Current build/releasing process can be optimized.

**Comment by jmidd** [comment]
Hi @chrislusf 
I'm the author of the above article, can I help with this?
John

**Comment by chrislusf** [comment]
Amazing! Yes, please!

**Comment by BruceWangNo1** [comment]
Any progress? @jmidd [Dockerfile](https://github.com/chrislusf/seaweedfs/blob/master/docker/Dockerfile)
