### ISSUE TITLE
How to configure for huge amount of images

### ISSUE THREAD

**Issue by 81662550** [chrislusf/seaweedfs#1048]
Hi, everyone.

I installed seaweedfs on two machines, with each 512GM memory and 40TB disk. I create 2 masters,  10 volume servers (each max 10 volumes) and a filer server with redis as the storage. Then, about 110 million images (each about 8KB~40KB) are put into seaweedfs. We use JMeter to simulate 200 users to get the images by filer path at the same time and find that we can get only 3000 images per seconds. However, for a smaller size dataset (1 million images), this number can be 20000.

Can we improve it? Or is there something wrong with the configuration? 
Thank you very much!

**Comment by chrislusf** [comment]
check whether the network is the limiting factor..
