### ISSUE TITLE
How do I delete dangling file id?

### ISSUE THREAD

**Issue by divinerapier** [chrislusf/seaweedfs#1050]
I use filer as an object storage like s3, uploading and downloading by a path. For example, I upload a file by a path '/a/b/c.txt', the filer will assign a file id and store it into backend (eg, redis). And then I upload another file by the same path '/a/b/c.txt', then filer give me another file id. Now, the previous file id is dangling. How can I lookup it, and delete it?

**Comment by chrislusf** [comment]
The filer will delete them.

**Comment by divinerapier** [comment]
If I do the garbage collection (GET volumeserver:9333/vol/vacuum). Will the covered space be recycled?

**Comment by chrislusf** [comment]
Yes.

**Comment by divinerapier** [comment]
Thanks a lot, let me have a try.
