### ISSUE TITLE
High Availability Issue: volume crashed cause data inconsistency

### ISSUE THREAD

**Issue by xushuxun** [chrislusf/seaweedfs#1052]
Seaweedfs topo:
host1(rack1): master1, volume1
host2(rack2): master2, volume2
host3(rack3): master3, volume3

Replication: 010

High Availability Goal: tolerance one machine crashed

Assume an object is going to be stored in volume1 and volume2, but suddenly host1 crashed, object failed to store in volume1 completely. When host1 come back, a client call for that object, Seaweedfs would tell the client to find object in volume1 or volume2. But volume1 do not contain that object, cause error.

My solution for this issue:
Implement a proxy layer in volume. When volume failed to find an object, ask master for the volumes list, proxy the request to another volume. When get the object, write the object to the local disk again.

===
假设有个对象将要写入volume1和volume2，host1突然宕机了，对象在host1没有落盘。后续host1恢复服务后，客户端请求这个对象时，Seaweedfs会告诉客户去volume1或volume2取数据，但是volume1并没有这个对象，会返回错误。

我的解决方案：
给volume加个代理层，如果volume找不到一个对象，先尝试去别的volume找，找到后，返回给客户，并回写本地磁盘。

如果你觉得这个修复方案可以的话，我可以尝试实现。

**Comment by chrislusf** [comment]
The write request would have failed in the beginning.

**Comment by xushuxun** [comment]
Seaweedfs doesn't use `fsync`, when data just written in kernel cache, volume would response success. But it still have a risk of losing data.

**Comment by chrislusf** [comment]
how about adding an `fsync` option for the write requests?

**Comment by xushuxun** [comment]
It would be nice.

**Comment by xushuxun** [comment]
I tried to use *os.File.Sync() when writing data file and index file. Performance will  drop dramatically, more than 10x.

**Comment by chrislusf** [comment]
could be useful when writes are few and correctness requirement is tight

**Comment by bash99** [comment]
would be nice if fsync can be a option of collection.

**Comment by doufighting** [comment]
hi, i have encounted with the same problem. does fsync option has been added in the recently version?

**Comment by chrislusf** [comment]
@doufighting what's your system's symptom?

**Comment by doufighting** [comment]
seaweedfs topo:
datacenter1: master1,volume1
datacenter2: master2,volume2
datacenter3: master3,volume3
Replication: 200
problem: sometimes datacenter3 may crashed, in this case , when i save a file, it should be failed, but it success and return a fileid, the file has be saved in datacenter1 、datacenter2. nextime when datacenter3 come back,  i query the file , the datacenter3 doesn't contain the file ,will return error.

您好，问题是我的集群设定是3个数据中心，副本集模式是200。当某个数据中心宕机时（如datacenter3 ），这时的写入请求应该失败，但是并没有，写入请求会收到文件写入后的fileid。当手动恢复datacenter3后，集群状态健康时，对这个fileid进行查询，因为随机路由，master节点可能会指向datacenter3，但是datacenter3上并没有该文件，会返回错误。
我希望能做到存储完全一致，当某个数据中心宕机时，此时不应该存储成功，不应该返回fileid，不知道seaweedfs有没有这种设置。

**Comment by chrislusf** [comment]
@doufighting do you want to have a separate "fsync" command to flush data to disk?

**Comment by doufighting** [comment]
yes, i think a separate 'fsync' would be better for write strict consistency

**Comment by onlyjob** [comment]
Also worth noticing that automatic repair/replication is not supported: #1267.

Ideally detection _and repair_ of inconsistencies should happen automatically in background.

If repair is left to storage admin to do manually then data may be endangered between maintenance periods due to reduced number of (healthy) replicas.

**Comment by chrislusf** [comment]
> yes, i think a separate 'fsync' would be better for write strict consistency

A separate `fsync=true` can be added for all http write requests.

> Also worth noticing that automatic repair/replication is not supported: #1267.

Automatic repair/replication, like other code, may have bugs. 

> Ideally detection and repair of inconsistencies should happen automatically in background.

Automatic repair/replication can be installed by configuring the master.toml file generated by `weed scaffold -config=master`.
