### ISSUE TITLE
Volume bloat after rebalance

### ISSUE THREAD

**Issue by mastak** [chrislusf/seaweedfs#1061]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**
The data leak at crush after `volume.balance`. 
My steps:
```
echo "volume.balance -force" | /usr/local/bin/weed shell -master=*.*.238.121:9333
> moving volume 19 *.*.238.8:8082 => *.*.238.8:8081
2019/09/08 15:16:48 copying volume 19 from *.*.238.8:8082 to *.*.238.8:8081
2019/09/08 15:19:26 tailing volume 19 from *.*.238.8:8082 to *.*.238.8:8081
2019/09/08 15:19:38 deleting volume 19 from *.*.238.8:8082
error: delete volume 19 from *.*.238.8:8082: rpc error: code = Unavailable desc = transport is closing
```
But after that the volume server at `*.*.238.8:8081` increased by 1 terabyte:
<img width="1197" alt="Screen Shot 2019-09-08 at 21 52 20" src="https://user-images.githubusercontent.com/628807/64492996-5a5b6a80-d283-11e9-9f40-d1c977c1f130.png">

As you can see the one volume is bloat, it is `*.*.238.8:8081`

**System Setup**
Seaweedfs 1.42:
host1(rack1): master, filer, volume1,volume2
host2(rack2): volume3,volume4

Ubuntu 18.04.2 (4.15.0-52-generic)

Default filer config with custom PG section.

**Comment by chrislusf** [comment]
I suppose you are using the default 30GB volume size. This could be related to a problem fixed in 1.43 release: "truncating the temp files when compacting, avoid wrong .dat file after compaction.".

https://github.com/chrislusf/seaweedfs/releases/tag/1.43

**Comment by mastak** [comment]
I have updated SeaweeFS to 1.43 (30GB), but still, have an error. It's not related to bloating, but I can't finish rebalancing.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0xaf15c9]
goroutine 40 [running]:
github.com/chrislusf/seaweedfs/weed/storage.(*Volume).MaxFileKey(0xc0000d1130, 0x0)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/storage/volume.go:116 +0x79
github.com/chrislusf/seaweedfs/weed/storage.(*Store).CollectHeartbeat(0xc0005a0300, 0xc0004251f8)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/storage/store.go:171 +0x19f
github.com/chrislusf/seaweedfs/weed/server.(*VolumeServer).doHeartbeat(0xc0000edb80, 0x1e2c1a0, 0xc0000e8000, 0x7fff4594be58, 0x13, 0xc0001a9080, 0x14, 0x1df6f00, 0xc0004e6220, 0x12a05f200, ...)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/server/volume_grpc_client_to_master.go:159 +0xe7a
github.com/chrislusf/seaweedfs/weed/server.(*VolumeServer).heartbeat(0xc0000edb80)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/server/volume_grpc_client_to_master.go:43 +0x28d
created by github.com/chrislusf/seaweedfs/weed/server.NewVolumeServer
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/server/volume_server.go:87 +0x8c1
```

**Comment by mastak** [comment]
I thought, after update to 1.43 and rebalancing all bloated data should go away, but no, I have the same result. How I can remove bloated data?
<img width="1213" alt="Screen Shot 2019-09-09 at 10 02 24" src="https://user-images.githubusercontent.com/628807/64509698-f79cba00-d2e8-11e9-9da7-d7f3dc0b2ec3.png">

**Comment by chrislusf** [comment]
you can ssh to *.*.238.8:8082 and remove volume 9 related files, 9.dat and 9.idx.

**Comment by chrislusf** [comment]
I added a fix to address the nil problem. Thanks for reporting!

**Comment by chrislusf** [comment]
To know where is one particular volume, you can use `volume.list` in `weed shell` to find the volume location.
