### ISSUE TITLE
{"error":"volumeId X not found."} error on deletion.

### ISSUE THREAD

**Issue by ijunaid8989** [chrislusf/seaweedfs#1062]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**
```
{"error":"volumeId 924 not found."}
```
The above error comes across when you delete in recursive mode.

I am linking this issue as a reference..Our ZFS drive on which we had the filer ldb,s and volume files got corrupt and we recovered it using python implementation of leveldb..
https://github.com/chrislusf/seaweedfs/issues/576

Now I run this command on it for deletion:

curl -X DELETE "http://IP:8888/irish-life-mall/snapshots/recordings/2017/10/?recursive=true"

It deletes many files in that directory 10 but at a certain point it fails. 

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount". = "/opt/go/bin/weed -v=0 server -filer=true -ip=IP -dir=/storage -volume.max=2370 -volume.images.fix.orientation=false -pulseSeconds=5"
- OS version Ubuntu 17.10
- output of `weed version` = version 0.76 linux amd64

**Expected behavior**
It should delete all files within a directory.

**Comment by chrislusf** [comment]
Does the volume 924 really exist or not?

I can add an option to "ignore errors" during deletion to current branch tip.

**Comment by ijunaid8989** [comment]
Is there any workaround if, the listing in filer is available... but the consecutive volume files are not present then we can clean the filer entries? 

So there will be only those filer listings whom data is present?

**Comment by ijunaid8989** [comment]
> Does the volume 924 really exist or not?
> 
> I can add an option to "ignore errors" during deletion to current branch tip.

Volume does not exist as well as, we are on 0.76 version on those filer volumes.
