### ISSUE TITLE
Corrupted .dat volume files are internally set as "readonly" and cannot be deleted

### ISSUE THREAD

**Issue by joeslay** [chrislusf/seaweedfs#1063]
In our seaweed folder if we have some valid .idx files and corrupt .dat files.

On load the CheckVolumeDataIntegrity function fails in seaweed for these files as expected. However this also sets the volumes as "readonly" which means that any attempt to delete the volume through seaweed fails in the Destroy() function, returning a "volume %d is read only" error message.

Can the check for the readonly flag in the Destroy() function be removed safely? It isn't clear why it's there or the intention behind it. 

If the readonly flag has multiple purposes that makes the check valid in certain circumstances, could there be another flag on the volume, e.g. an unknown/corrupted flag that is set if CheckVolumeDataIntegrity that allows the Destroy() function to work on corrupt files? 

The volumes in question also had TTLs  (only known from the .idx file), these files could be deleted after the TTL expires instead of the current behaviour of storing them forever.

**Comment by chrislusf** [comment]
Agree. The Destroy() can skip the readonly check.
