### ISSUE TITLE
weed mount: error: file not found!

### ISSUE THREAD

**Issue by flomo29** [chrislusf/seaweedfs#1065]
When I use "weed mount" and i copy files in the mount dir or when i access files or when i rename files: There is often the error: "Item not found!" or "File not found!", mostly when i want to rename a file. External programs, which want to work with files on the mount dir show me the same error. Not everytime, but very often.

**Comment by chrislusf** [comment]
please follow the issue template.

**Comment by chrislusf** [comment]
can not reproduce.

**Comment by chrislusf** [comment]
There are no printouts as "Item not found".

"File not found" is only used when looking up a file id. Renaming is only a meta data operation and does not involve the file id lookup.
