### ISSUE TITLE
build from source will get rpc error

### ISSUE THREAD

**Issue by 81662550** [chrislusf/seaweedfs#1068]
Hi, chrislusf.

I build seaweedfs with make from the source file on ubuntu 18.04. I have three masters on 3 different machines.

However, if I use filer.copy to upload images to the filer server, there will be always an error "Failed to assign from [ip1:9333 ip2:9333 ip3:9333]: rpc error: code = Unknown desc=raft.Server: Not current leader. copy file error: upload data to http:/// : Post http:///: no Host in request URL" and failed.

If I use the pre-build binary from your site, it works well. 

Are there any special steps?

Thank you very much!

**Comment by 81662550** [comment]
Even I start the master server and volume server with my own built binary, and upload images with the pre-built binary, it works well. Why?

**Comment by chrislusf** [comment]
do a `go get -u`
