### ISSUE TITLE
Cannot upload any file to a filer if it's first master is not leader on filer startup

### ISSUE THREAD

**Issue by lotsofone** [chrislusf/seaweedfs#1070]
**Describe the bug**
When uploading to a filer, the web page doesn't show the new file uploaded. And at the filer terminal shows:
E0926 14:14:14 27427 filer_server_handlers_write.go:67] failing to assign a file id: rpc error: code = Unknown desc = raft.Server: Not current leader
I0926 14:14:14 27427 filer_server_handlers_write.go:103] fail to allocate volume for /, collection:, datacenter:

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
We have three masters:
./weed master -mdir="./mdir" -ip={ip1/2/3} -port=8081 -peers={ip1}:8081,{ip2}:8081,{ip3}:8081
three volumes:
./weed volume -dir=./vdir1 -mserver={ip1}:8081,{ip2}:8081,{ip3}:8081 -port=8888 -ip={volume ip}
filer:
this is where to prevent the problem.
For example, now master {ip1} is the leader, and we use
./weed filer -port=8080 -master={ip1}:8081,{ip2}:8081,{ip3}:8081
to start the filer, then everything is ok.
if we use
./weed filer -port=8080 -master={ip2}:8081,{ip1}:8081,{ip3}:8081
to start the filer, then we cannot upload any file to the filer.

- OS version
CentOS Linux release 7.2 (Final)
- output of `weed version`
version 30GB 1.43 linux amd64
- if using filer, show the content of `filer.toml`
we use leveldb2
[leveldb2]
enabled = true
dir = "fdir"

**Expected behavior**
We can upload files

**Screenshots**
![image](https://user-images.githubusercontent.com/35299440/65661399-272b2080-e064-11e9-8a0d-26f669fb1ef0.png)
![image](https://user-images.githubusercontent.com/35299440/65663061-5cd20880-e068-11e9-9ce8-0ed8cdd7d5a8.png)

**Comment by iliul** [comment]
@chrislusf  any update on it ?

**Comment by iliul** [comment]
@chrislusf 你好，Chris

我在本地编译了最新版本，随后我进行benchmark测试，问题依然存在，主要问题是运行3个master时，使用 `benchmark -master 10.10.100.12:9333,10.10.100.13:9333,10.10.100.14:9333` 这样指定三个master进行压测过程中 leader master 会出现异常，也无法转为follower角色

master log：

```
I1017 11:13:36 33444 masterclient.go:109] master: 10.10.100.13:7080 removes volume 217
I1017 11:13:36 33444 masterclient.go:109] master: 10.10.100.13:7080 removes volume 453
I1017 11:13:36 33444 masterclient.go:88] master failed to receive from 10.10.100.14:9333: rpc error: code = Unknown desc = raft.Server: Not current leader
I1017 11:13:36 33444 masterclient.go:116] master failed to connect with master 10.10.100.14:9333: rpc error: code = Unknown desc = raft.Server: Not current leader
I1017 11:13:36 33444 masterclient.go:68] master Connecting to master 10.10.100.13:9333
I1017 11:13:36 33444 masterclient.go:82] master Connected to 10.10.100.13:9333
I1017 11:13:36 33444 masterclient.go:88] master failed to receive from 10.10.100.13:9333: rpc error: code = Unknown desc = raft.Server: Not current leader
I1017 11:13:36 33444 masterclient.go:116] master failed to connect with master 10.10.100.13:9333: rpc error: code = Unknown desc = raft.Server: Not current leader
I1017 11:13:36 33444 masterclient.go:68] master Connecting to master 10.10.100.14:9333
I1017 11:13:36 33444 masterclient.go:82] master Connected to 10.10.100.14:9333
I1017 11:13:36 33444 masterclient.go:88] master failed to receive from 10.10.100.14:9333: rpc error: code = Unknown desc = raft.Server: Not current leader
I1017 11:13:36 33444 masterclient.go:116] master failed to connect with master 10.10.100.14:9333: rpc error: code = Unknown desc = raft.Server: Not current leader
I1017 11:13:36 33444 master_server.go:125] event: &{typ:leaderChange source:0xc00020a120 value: prevValue:10.10.100.14:9333}
I1017 11:13:37 33444 masterclient.go:68] master Connecting to master 10.10.100.12:9333
I1017 11:13:37 33444 masterclient.go:82] master Connected to 10.10.100.12:9333
I1017 11:13:37 33444 masterclient.go:94] redirected to leader 10.10.100.13:9333
I1017 11:13:37 33444 masterclient.go:68] master Connecting to master 10.10.100.13:9333
I1017 11:13:37 33444 masterclient.go:82] master Connected to 10.10.100.13:9333
I1017 11:13:37 33444 masterclient.go:105] master: 10.10.100.14:7082 adds volume 128
I1017 11:13:37 33444 masterclient.go:105] master: 10.10.100.14:7082 adds volume 334
```

帮看一下，谢谢！

**Comment by chrislusf** [comment]
I do not understand. The master was elected sucessfully in the log you showed.

**Comment by iliul** [comment]
你好，可能我没有描述清楚，主要是两个疑问：

1，为什么会产生 leader 切换 ？
2，leader 切换到 10.10.100.13 后，cluster/status 返回结果中 peers 内不包含 10.10.100.12（原leader），如下：

```
GET /cluster/status?pretty=y HTTP/1.1
Host: 10.10.100.12:9333
Accept: application/json
Accept-Encoding: gzip, deflate
User-Agent: bat/0.1.0

HTTP/1.1 200 OK
Date: Thu, 17 Oct 2019 05:26:16 GMT
Content-Length: 102
Content-Type: application/json


{
  "Leader": "10.10.100.13:9333",
  "Peers": [
    "10.10.100.13:9333",
    "10.10.100.14:9333"
  ]
}
```

如果需要哪些日志记录，我可以再提供！

**Comment by iliul** [comment]
> I do not understand. The master was elected sucessfully in the log you showed.

我理解了，是我对代码理解不足造成了困惑，第二个问题没有问题，但仍然不清楚为什么造成leader切换，心跳超时 ？
