### ISSUE TITLE
上传的图片与下载下来的图片大小不一致

### ISSUE THREAD

**Issue by damonzhou1** [chrislusf/seaweedfs#1071]
1、上传一个300kb的图片至weedfs，返回的大小是300KB的图片
curl -F filename=@26.jpg http://127.0.0.1:9080/16,05d84dcc9d1528
{"name":"26.jpg","size":300217}
2、下载该图片，显示大小只有95KB
./weed download -server=127.0.0.1:9080 16,05d84dcc9d1528
![image](https://user-images.githubusercontent.com/55868350/65744413-dc281080-e12a-11e9-9a3e-cdac1b8324d8.png)

**Comment by chrislusf** [comment]
can not reproduce:

Downloads$ curl localhost:9333/dir/assign
{"fid":"3,0c52ce5addce","url":"localhost:8080","publicUrl":"localhost:8080","count":1}Downloads$
Downloads$
Downloads$ curl -F "filename=@b.jpg" "http://localhost:8080/3,0c52ce5addce"
{"name":"b.jpg","size":1759400,"eTag":"3c98c013"}Downloads$
Downloads$ ls -al b.jpg
-rw-r--r--@ 1 chris  staff  1759400 Sep 19 21:09 b.jpg
Downloads$ cd tmp/
tmp$ rm b.jpg
rm: b.jpg: No such file or directory
tmp$ weed download -server=localhost:9333 3,0c52ce5addce
tmp$ ls -ltr b.jpg
-rwxr-xr-x  1 chris  staff  1759400 Sep 26 23:16 b.jpg
