### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by portsip** [chrislusf/seaweedfs#1072]
We have installed seaweedfs with our software together in only one machine, now when we upload a file which size is 70MB, we see the seaweedfs processes consume 500MB memory(there has three processes, but two processes of them every one takes about 250MB), how could we configure it to reduce the memory usage ?

I have read this link https://github.com/chrislusf/seaweedfs/wiki/Optimization but seems that only for optimize the index if there has a lot of files, in our scenario there only one file uploaded.

I've just read this issue: 
#505 

So as author suggested, we can simply disable cache to avoid this issue ?
https://github.com/chrislusf/seaweedfs/commit/dcaf1796fe0e41e39ac5c9602cb190cf150e7849

**Comment by chrislusf** [comment]
use `weed upload` to split the large file into smaller chunks.
