### ISSUE TITLE
One volume broke?

### ISSUE THREAD

**Issue by Minikloon** [chrislusf/seaweedfs#1073]
**System Setup**
Master:
 ./weed master -ip=chi-hp-goliath3 -defaultReplication=002 -metrics.address=chi-hp-db4:9091

Volumes:
./weed -logdir=./logs/ volume -dir=data -max=100 -mserver=chi-hp-goliath3:9333 -ip=chi-hp-weed1 -port=8883 -index=leveldb
./weed -logdir=./logs/ volume -dir=data -max=100 -mserver=chi-hp-goliath3:9333 -ip=chi-hp-weed2 -port=8883 -index=leveldb
./weed -logdir=./logs/ volume -dir=data -max=100 -mserver=chi-hp-goliath3:9333 -ip=chi-hp-weed3 -port=8883 -index=leveldb

- OS version:  Centos 7
- output of `weed version: version 30GB 1.41 linux amd64

**The issue*
One specific volume (volume 14) seems to have corrupted. When running the HTTP GET on FIDs for that volume, Seaweed returns an empty byte array and outputs "read /fid isNormalVolume true error: not found" on the voume server console.

This is a screen of when the corruption seems to have taken place (seems to be during a commit): 
![image](https://user-images.githubusercontent.com/979743/65824325-1bdb1f00-e235-11e9-9d9e-8a38de32c326.png)

On the commit after that, there was an "error writing JSON", commited volume 14 and started erroring out with isNormalVolume true error...
![image](https://user-images.githubusercontent.com/979743/65825263-f35a2180-e242-11e9-9200-d4cd4407edf7.png)

We replaced the broken volume with a backup in order to fix the issue. We tried loading volume 14 on a different environment without replication and it had the same behavior (empty gets) as production. We also tried deleting the ldb folder to regenerate it but it was still returning
 empty files and erroring.

Here is the ldb folder zipped: [14.zip](https://github.com/chrislusf/seaweedfs/files/3666203/14.zip)

Here is the idx: [prod14idx.zip](https://github.com/chrislusf/seaweedfs/files/3666206/prod14idx.zip)

The data is around 24GB so not pratical to share here.

We also noticed that memory usage on the volume machines changed pattern when the incident happened:
![image](https://user-images.githubusercontent.com/979743/65824447-5776e880-e237-11e9-8174-a7d20f820584.png)

Please let us know any more information you need.

**Comment by Minikloon** [comment]
It appears the file load fine but fail to save. Here's the .toString() of the save request for the http client we're using:  

Response{protocol=http/1.1, code=500, message=Internal Server Error, url=http://chi-hp-weed1:8883/14,21b2ee4a43dc0d}

**Comment by chrislusf** [comment]
Try to use `weed fix` to re-generate the idx files.

**Comment by Minikloon** [comment]
We ran weed fix on volume 14, ran with a single volume server (all other volume servers offline) and it still returns a 500 Internal Server error.

**Comment by chrislusf** [comment]
the idx file content shows the keys do not exist. So the idx and level db index is behaving correctly. You can verify that with `see_idx` command in the `unmaintained` folder.

**Comment by Minikloon** [comment]
For a more actionable case, on a different volume (volume 12), we have some cases of files which are present in both the see_data and the see_idx, but seaweed still returns 404.

For example fid 12,296b6099cc92eb:
see_dat_12.txt
`12,296b6099cc92eb offset 18581854880 size 133768 cookie 99cc92eb appendedAt 2019-09-28 17:48:02.058541505 -0400 EDT`

see_idx_12.txt
`key:296b60 offset:2322731860 size:133768`

Gameserver logs:
```
[11:17:47 INFO]: [GameManager] Received world creation request for sb_dyn_nosave_92d940ad-10e8-4d9d-a795-adcf5fd6b0c6...
[11:17:47 INFO]: [GameManager] Loading world sb_dyn_nosave_92d940ad-10e8-4d9d-a795-adcf5fd6b0c6 from seaweed with fid 12,296b6099cc92eb...
[11:17:47 INFO]: [GameManager] [SeaweedFS] Picked volume url chi-hp-weed1:8883 for fid 12,296b6099cc92eb
[11:17:47 INFO]: [GameManager] [SeaweedFS] readFileAsync res Response{protocol=http/1.1, code=404, message=Not Found, url=http://chi-hp-weed1:8883/12,296b6099cc92eb}
 -- exception excluded --
[11:17:47 ERROR]: [GameManager] Specworld boot failure for Minikloon to 92d940ad-10e8-4d9d-a795-adcf5fd6b0c6, error: ERROR_ON_GAMESERVER
```
You can see above the 404 returned.

seaweedfs logs
`I1001 11:17:47 25996 volume_server_handlers_read.go:92] read /12,296b6099cc92eb isNormalVolume true error: entry not found: offset 6407560 found id 12879457900293054064 size 4246792410, expected size 132230`

The .dat for volume 12 seems to be maxed out, the OS reporting 34,392,304 btes on it. see_dat doesn't error out for that volume.

**Comment by chrislusf** [comment]
The root problem is that the fileId is assigned once and used many times to update. It's recommended that whenever to update anything, assign a new file id and delete the old file id.

**Comment by bash99** [comment]
> The root problem is that the fileId is assigned once and used many times to update. It's recommended that whenever to update anything, assign a new file id and delete the old file id.

@chrislusf , But as I can see, in filer mode, if we save to a exists entry, it just update it other than delete it then assign a new file id.
weed/filer2/filer.go: UpdateEntry
f.store.UpdateEntry(ctx, entry)

So us also encounter same file not found error, and it need manually run "weed fix" to fix it.
Any idea to automatic detect this error and run weed fix automatically?

**Comment by chrislusf** [comment]
@bash99 The chunks are assigned to new file id before `UpdateEntry`

Need a reproducible case.
