### ISSUE TITLE
Error 1205: Lock wait timeout exceeded; try restarting transaction

### ISSUE THREAD

**Issue by linqinghai** [chrislusf/seaweedfs#1081]
E1010 09:18:42     1 filer.go:161] update entry /oss/37098ed70ec33a13702e2ed6a6a7525d.jpg: update /oss/37098ed70ec33a13702e2ed6a6a7525d.jpg: Error 1205: Lock wait timeout exceeded; try restarting transaction
I1010 09:18:42     1 filer_server_handlers_write.go:188] failing to write /oss/37098ed70ec33a13702e2ed6a6a7525d.jpg to filer server : update entry /oss/37098ed70ec33a13702e2ed6a6a7525d.jpg: update /oss/37098ed70ec33a13702e2ed6a6a7525d.jpg: Error 1205: Lock wait timeout exceeded; try restarting transaction
I1010 09:18:42     1 delete_content.go:110] deleted 1 items

**Comment by chrislusf** [comment]
Seems you are using some transactional filer store.

**Comment by chrislusf** [comment]
seems you are using mysql. try to increase innodb_lock_wait_timeout in mysql config.
