### ISSUE TITLE
GET:/path/to/如何对文件夹进行分页获取？

### ISSUE THREAD

**Issue by justciffer** [chrislusf/seaweedfs#1082]
当文件夹数量很多时，返回的chunk被Truncated，无法获取完整的数据

**Comment by chrislusf** [comment]
// listDirectoryHandler lists directories and folers under a directory
// files are sorted by name and paginated via "lastFileName" and "limit".

**Comment by justciffer** [comment]
> // listDirectoryHandler lists directories and folers under a directory
> // files are sorted by name and paginated via "lastFileName" and "limit".

![image](https://user-images.githubusercontent.com/20924727/66621359-718ccf80-ec16-11e9-89c8-0f9ecdde1d5a.png)
只能获取文件夹下所有对子目录吗？
