### ISSUE TITLE
GET:/path/to/如何对文件夹下的Subdirectories进行分页获取？

### ISSUE THREAD

**Issue by justciffer** [chrislusf/seaweedfs#1083]
![image](https://user-images.githubusercontent.com/20924727/66622115-26c08700-ec19-11e9-973d-8bc6f3a320a8.png)
![image](https://user-images.githubusercontent.com/20924727/66622130-33dd7600-ec19-11e9-8a7d-b2296ec3f38e.png)
Subdirectories可以分页获取吗？

**Comment by chrislusf** [comment]
What's the seaweedfs version?

**Comment by chrislusf** [comment]
Can not if you are using 0.77 version or lower.

**Comment by justciffer** [comment]
OK，谢了
