### ISSUE TITLE
Build instructions in README produces panic'ing binary

### ISSUE THREAD

**Issue by helllamer** [chrislusf/seaweedfs#1086]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**
[README#Installation-guide](https://github.com/chrislusf/seaweedfs#installation-guide) Step 3 contains command:
`go get github.com/chrislusf/seaweedfs/weed`

It builds weed here without compiler errors, but `weed` binary panicing same as in #1058 :
```
panic: /debug/requests is already registered. You may have two independent copies of golang.org/x/net/trace in your binary, trying to maintain separate state...
goroutine 1 [running]:
go.etcd.io/etcd/vendor/golang.org/x/net/trace.init.0()
    /mnt/src/user/projects/pkgbuild/seaweedfs-git/src/src/go.etcd.io/etcd/vendor/golang.org/x/net/trace/trace.go:123 +0x1cd
```

**BUT**, if `weed` is built via `git clone ...` + `make` (without `go get ...`), everything is ok.

**System Setup**
- `/usr/bin/weed server -dir=/home/user/weedfs -volume.max=10 -volume.port=8080 -volume.publicUrl=192.168.0.1:9000`
- OS version: ArchLinux, fresh
- output of `weed version`:
  - `version 30GB 1.44 linux amd64`
  - `seaweedfs-git r2620.7de121d9-1`

**Additional context**
I'm maintainer of [seaweedfs-git PKGBUILD in Archlinux AUR](https://aur.archlinux.org/packages/seaweedfs-git/) for last 4 years.
I've not checked build last ~4 months, but before this time everything in `PKGBUILD` was worked without issues and strongly according to `README`'s build instructions. Today, it switched to `make` due to panic in `weed`.

**Comment by chrislusf** [comment]
It's a known problem due to go module. I do not know a good way to resolve this yet.

**Comment by roshanjonah** [comment]
rm -rf $GOPATH/src/go.etcd.io/etcd/vendor/golang.org/x/net/trace helped me!

**Comment by chrislusf** [comment]
fixed in https://github.com/chrislusf/seaweedfs/issues/1548

changed readme
