### ISSUE TITLE
Data-Backup improvement

### ISSUE THREAD

**Issue by yourchanges** [chrislusf/seaweedfs#1088]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

@chrislusf 

我现在有一个场景, 两个机房, 一个远端原始数据机房, 一个本地新机房,  新机房数据只想按需存相关数据, 当用户请求时, 抓取存本地weedfs.   

我们自己开发了一个前端代理, 本地没有, 从远端机房抓取, 存本地(post 到指定卷, 指定fid, 前提是本地卷数据文件和index文件存在),   

过程中使用weed backup 现在碰见两个问题:

1 weed backup 会完全备份远端卷数据,  这里可以加一个开关, 来达到只创建空卷数据文件和index文件. (我们已经调整了这个代码)
2 远端可能随时在更新, 本地卷文件和index文件不存在,  通过类似weed backup 创建的卷文件和index文件, 本地weed服务器感知不到, 需要重启( 这里需要添加类似刷新或者添加新卷信息API)

**梳理后简单来说, 其实, 卷服务器, 提供一个新API, 能够直接创建指定collection, ttl, vomuleid, replication 的一个新卷即可 (需要考虑replication影响)**

参考:

https://github.com/chrislusf/seaweedfs/wiki/Data-Backup

**Comment by yourchanges** [comment]
如果添加代码, 大概在什么位置,  最近变化比较大, 我们可以自行添加,  然后推PR.

**Comment by chrislusf** [comment]
2. After `weed backup`, you can call grpc API `VolumeUnmount` and `VolumeMount` to reload the new data.

**Comment by yourchanges** [comment]
@chrislusf 

还是请考虑下添加新API. 这个方便


另外一个问题是 新机房是1.44版本, 和老机房1.09 的grpc 好像不兼容, 直接用就会报错,  

```
lee@lee-Inspiron-7577 ~/workspace/seaweedfs/weed $ ./weed backup -collection=testbackup -server=192.168.254.7:9333 -volumeId=2043
I1018 11:06:30 21783 config.go:28] Reading : Config File "security" Not Found in "[/home/lee/workspace/seaweedfs/weed /home/lee/.seaweedfs /etc/seaweedfs]"
I1018 11:06:30 21783 volume_loading.go:86] loading index testbackup_2043.idx to memory readonly false
Error synchronizing volume 2043: rpc error: code = Unimplemented desc = unknown service volume_server_pb.VolumeServer

```

现在升级快, 兼容性保证还需要提高

这种就只有强制升级我们老的集群了么? 1.09 升级到1.44 有什么不兼容的?

**Comment by yourchanges** [comment]
我可以直接用grpc 调,

```
rpc AllocateVolume (AllocateVolumeRequest) returns (AllocateVolumeResponse) {
    }
```
这个么, 先不管replication

**Comment by yourchanges** [comment]
@chrislusf  need some tips:

I use follow code to test, but failed on last step:

code(collection=testbackup, volumeId=2037):
```
err:=operation.WithVolumeServerClient("127.0.0.1:5083",grpcDialOption, func(client volume_server_pb.VolumeServerClient) error {
		ctx := context.Background()
		req:=volume_server_pb.AllocateVolumeRequest{
			VolumeId:uint32(*s.volumeId),
			Collection:*s.collection,
			Preallocate:0,
			Replication:*s.replication,
			Ttl:*s.ttl,
		}
		resp,err:=client.AllocateVolume(ctx,&req)
		fmt.Println(resp)
		return err
	})

	fmt.Println(err)

	err=operation.WithVolumeServerClient("127.0.0.1:5083",grpcDialOption, func(client volume_server_pb.VolumeServerClient) error {
		resp,err:=client.VolumeMount(context.Background(),&volume_server_pb.VolumeMountRequest{VolumeId:uint32(*s.volumeId)})
		fmt.Println(resp)
		return err
	})
```

and then, I post a file to  http://127.0.0.1:5083/2037,0128ee3f0ee5aa7e, it says success, and check on http://127.0.0.1:5083/ui/index.html:

```

Id | Collection | Size | Files | Trash | TTL
-- | -- | -- | -- | -- | --
2037 | testbackup | 15454 Bytes | 1 | 0 / 0 Bytes


```

but, I get 404 error to GET the http://127.0.0.1:5083/2037,0128ee3f0ee5aa7e, the volume server logs :

```
I1018 14:56:09 22678 volume_server_handlers_read.go:56] volume 2037 reading 0128ee3f0ee5aa7e Size:0, DataSize:0, Name:, Mime:
I1018 14:56:09 22678 volume_server_handlers_read.go:90] read bytes -1 error not found
I1018 14:56:09 22678 volume_server_handlers_read.go:92] read /2037,0128ee3f0ee5aa7e isNormalVolume true error: not found

```

weedfs version: current master

**Comment by chrislusf** [comment]
try not to call `VolumeMount`.

**Comment by yourchanges** [comment]
@chrislusf   I have check  dat file and idx file, created by between normal and this new way.

there is the reason,  create file as new way, it only update the .dat file (by post/put request),  and the .idx file content is not updated.  The .idx file content is :

```
\00\00\00\00\00\00(\00\00\00\00\00<F
```


but  as in the normal way, The .idx file content is :

```
\00\00\00\00(\E7\AC\00\00\00\00\00<F
```

new way steps:

1  call "AllocateVolumeRequest"
2. call post http://volumeserver:5083/<fid>, with downloaded file.

so, which step should I add to fix this?

**Comment by chrislusf** [comment]
updates？

**Comment by yourchanges** [comment]
now, I need do the same thing on "weed filer" server, which grpc api should I call?

**Comment by chrislusf** [comment]
what is "same thing"? check `filer.proto` for filer existing APIs.

**Comment by yourchanges** [comment]
I have test with weed filer, it seems it will create the .dat , .idx and leveldb map relationship automatically. when I post a "new" path( same with remote filer's file path ) with a file.

**Comment by chrislusf** [comment]
I can not guess out what you are doing and what you are trying to achieve.

**Comment by yourchanges** [comment]
we can close this issue now. don't worry.
