### ISSUE TITLE
redirecting from a wrong node skips parts of the official url

### ISSUE THREAD

**Issue by steven2612** [chrislusf/seaweedfs#1089]
**Describe the bug**
I have uploaded a file to my system - 6,0280c8eae0
When looking up the volume:
curl http://10.26.0.150:9333/dir/lookup?volumeId=6
{"volumeId":"6","locations":[{"url":"10.26.0.10:8080","publicUrl":"https://weed-s01/weed01"},{"url":"10.26.0.150:8080","publicUrl":"https://weed-s02/weed01"}]}

When requisting the file from a node which does not have the volume 6 stored it redirects the client to the right public server adress but without the path:
request https://weed-s03/weed01/6,0280c8eae0 redirects to https://weed-s01/6,0280c8eae0 instead of https://weed-s01/weed01/6,0280c8eae0 which fails.

**System Setup**
weed master -defaultReplication 100 -ip 10.26.0.150 -mdir /var/lib/weedfs -peers 10.26.0.150:9333,10.26.0.10:9333,10.26.0.20:9333

weed volume -dataCenter bm01 -index=leveldb -dir /disks/mfs.a1/weedfs -ip 10.26.0.150 -max 9 -mserver 10.26.0.150:9333,10.26.0.10:9333,10.26.0.20:9333 -port 8080 -port.public 8081 -publicUrl https://weed-s01/weed01 -rack 01
There is a apache reverse proxy which redirects https://weed-s01/weed01 to port 8081
similar setup on the other volume nodes

Ubuntu 18.04.3 LTS
version 30GB 1.44 linux amd64

**Expected behavior**
redirect to https://weed-s01/weed01/6,0280c8eae0

**Comment by chrislusf** [comment]
I can not reproduce. Does the bug description have some errors?

**Comment by steven2612** [comment]
Hi, no, there are no errors in the logfiles

you can test it by yourself: https://tg6.plweb.at/weed01/6,0280c8eae0
should lead to https://www.plweb.at/weed01/6,0280c8eae0
but instead redirects to: https://www.plweb.at/6,0280c8eae0

Request URL: https://tg6.plweb.at/weed01/6,0280c8eae0
Request Method: GET
Status Code: 301 Moved Permanently
Remote Address: 212.186.174.190:443
Referrer Policy: no-referrer-when-downgrade
Connection: Keep-Alive
Content-Length: 68
Content-Type: text/html; charset=utf-8
Date: Thu, 24 Oct 2019 04:35:22 GMT
Keep-Alive: timeout=5, max=100
Location: https://www.plweb.at/6,0280c8eae0
Server: Apache/2.4.29 (Ubuntu)
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
Accept-Encoding: gzip, deflate, br
Accept-Language: de-AT,de-DE;q=0.9,de;q=0.8,en-US;q=0.7,en;q=0.6
Cache-Control: no-cache
Connection: keep-alive
Host: tg6.plweb.at
Pragma: no-cache
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: none
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36

also doing it directly by curl gives:
curl localhost:8081/6,0280c8eae0
<a href="https://www.plweb.at/6,0280c8eae0">Moved Permanently</a>.

but 
curl http://localhost:9333/dir/lookup?volumeId=6
{"volumeId":"6","locations":[{"url":"10.26.0.10:8080","publicUrl":"https://www.plweb.at/weed01"},{"url":"10.26.0.150:8080","publicUrl":"https://bm.plweb.at/weed01"}]}

**Comment by steven2612** [comment]
in your test code - i think the following line should be as follows:
`u.Path = "6,0280c8eae0"`
because the call is localhost:8081/6,0280c8eae0
if changing like this it gave the output i am getting ...

**Comment by steven2612** [comment]
Steps to reproduce:
> ./weed master &
> ./weed volume -dir="./wd01" -max=5 -mserver="localhost:9333" -port=8080 -port.public=8090 -publicUrl="http://srv01/dir01" &
> ./weed volume -dir="./wd02" -max=5 -mserver="localhost:9333" -port=8081 -port.public=8091 -publicUrl="http://srv02/dir02" &
> ./weed upload test.png
[{"fileName":"test.png","fileUrl":"http://srv01/dir01/7,01fa6d8997","fid":"7,01fa6d8997","size":12823}]
> curl -i http://localhost:8091/7,01fa6d8997
HTTP/1.1 301 Moved Permanently
Content-Type: text/html; charset=utf-8
Location: http://srv01/7,01fa6d8997
Date: Thu, 24 Oct 2019 11:07:43 GMT
Content-Length: 60
`<a href="http://srv01/7,01fa6d8997">Moved Permanently</a>.`


Expected:
> curl -i http://localhost:8091/7,01fa6d8997
HTTP/1.1 301 Moved Permanently
Content-Type: text/html; charset=utf-8
Location: http://srv01**/dir01**/7,01fa6d8997
Date: Thu, 24 Oct 2019 11:07:43 GMT
Content-Length: 60
`<a href="http://srv01**/dir01/**7,01fa6d8997">Moved Permanently</a>.`
