### ISSUE TITLE
"Volumes": null

### ISSUE THREAD

**Issue by bboxzhen** [chrislusf/seaweedfs#1100]
![360截图20191103165103576](https://user-images.githubusercontent.com/39783629/68082778-ad086b80-fe5b-11e9-80d3-4b7fa46df6e5.jpg)

#May I ask the author why this Volumes will be 0

curl "http://localhost:5042/status?pretty=y"
{
  "Version": "8000GB 1.34",
  "Volumes": null
}
This is my configuration：
# master
weed_pcap -logdir=/var/log/seaweedfs_pcap master -mdir=/var/log/bd_files/weed_master_data_pcap -port=9334 -defaultReplication="110" -ip="datacenter" -peers="seaweedfs:9334,deepengine:9334,datacenter:9334"
weed_pcap -logdir=/var/log/seaweedfs_pcap master -mdir=/var/log/bd_files/weed_master_data_pcap -port=9334 -defaultReplication="110" -ip="deepengine" -peers="seaweedfs:9334,deepengine:9334,datacenter:9334"
weed_pcap -logdir=/var/log/seaweedfs_pcap master -mdir=/var/log/bd_files/weed_master_data_pcap -port=9334 -defaultReplication="110" -ip="seaweedfs" -peers="seaweedfs:9334,deepengine:9334,datacenter:9334"

# datacenter volume
weed_pcap -logdir=/var/log/seaweedfs_pcap volume   -rack="seaweedfs3_pcap_rack1" -dataCenter="dc3_pcap"  -ip=datacenter  -max="3000" -dir="/test/bdpcaps/disk1/weed_data"  -mserver="seaweedfs:9334,deepengine:9334,datacenter:9334" -port=5041
weed_pcap -logdir=/var/log/seaweedfs_pcap volume   -rack="seaweedfs3_pcap_rack2" -dataCenter="dc3_pcap"  -ip=datacenter  -max="3000" -dir="/test/bdpcaps/disk2/weed_data"  -mserver="seaweedfs:9334,deepengine:9334,datacenter:9334" -port=5042
weed_pcap -logdir=/var/log/seaweedfs_pcap volume   -rack="seaweedfs3_pcap_rack3" -dataCenter="dc3_pcap"  -ip=datacenter  -max="3000" -dir="/test/bdpcaps/disk3/weed_data"  -mserver="seaweedfs:9334,deepengine:9334,datacenter:9334" -port=5043

# deepengine volume
weed_pcap -logdir=/var/log/seaweedfs_pcap volume   -rack="seaweedfs2_pcap_rack1" -dataCenter="dc2_pcap"  -ip=deepengine  -max="3000" -dir="/test/bdpcaps/disk1/weed_data"  -mserver="seaweedfs:9334,deepengine:9334,datacenter:9334" -port=5041
weed_pcap -logdir=/var/log/seaweedfs_pcap volume   -rack="seaweedfs2_pcap_rack2" -dataCenter="dc2_pcap"  -ip=deepengine  -max="3000" -dir="/test/bdpcaps/disk2/weed_data"  -mserver="seaweedfs:9334,deepengine:9334,datacenter:9334" -port=5042
weed_pcap -logdir=/var/log/seaweedfs_pcap volume   -rack="seaweedfs2_pcap_rack3" -dataCenter="dc2_pcap"  -ip=deepengine  -max="3000" -dir="/test/bdpcaps/disk3/weed_data"  -mserver="seaweedfs:9334,deepengine:9334,datacenter:9334" -port=5043

# seaweedfs volume
weed_pcap -logdir=/var/log/seaweedfs_pcap volume   -rack="seaweedfs_pcap_rack1" -dataCenter="dc1_pcap"  -ip=seaweedfs  -max="3000" -dir="/test/bdpcaps/disk1/weed_data"  -mserver="seaweedfs:9334,deepengine:9334,datacenter:9334" -port=5041
weed_pcap -logdir=/var/log/seaweedfs_pcap volume   -rack="seaweedfs_pcap_rack2" -dataCenter="dc1_pcap"  -ip=seaweedfs  -max="3000" -dir="/test/bdpcaps/disk2/weed_data"  -mserver="seaweedfs:9334,deepengine:9334,datacenter:9334" -port=5042
weed_pcap -logdir=/var/log/seaweedfs_pcap volume   -rack="seaweedfs_pcap_rack3" -dataCenter="dc1_pcap"  -ip=seaweedfs  -max="3000" -dir="/test/bdpcaps/disk3/weed_data"  -mserver="seaweedfs:9334,deepengine:9334,datacenter:9334" -port=5043

**Comment by chrislusf** [comment]
because volume creation is randomized.

**Comment by bboxzhen** [comment]
Is there a volume that will be used later? Because I keep storing data in it, but it seems that I have not used these volumes.
发自我的iPhone

------------------ Original ------------------

**Comment by bboxzhen** [comment]
谢谢你的回答，也就是说只要往里面写数据达到一定阀值后，那些volumes为0的也会写数据进去是吗？


发自我的iPhone

------------------ Original ------------------

**Comment by chrislusf** [comment]
Need to pre-assign volumes. see https://github.com/chrislusf/seaweedfs/wiki/Optimization#increase-concurrent-writes
