### ISSUE TITLE
How to combine user and file authority control

### ISSUE THREAD

**Issue by GarinQian** [chrislusf/seaweedfs#1101]
Excuse me, I'm a brand new user of seaweedfs. A problem bothers me that is how to combine file permissions and user functions with seaweedfs. And I add a proxy api program before the seaweedfs api to realize authority function. But then I encountered upload file performance problems.  When file is larger than 500MB, only 10 thread could be supported by proxy api to upload files to seaweedfs api.

**Comment by chrislusf** [comment]
Seems you are talking about two things: permissions and upload performance.

Seems you use your proxy to solve the permission problem. But no details about your code and can not help.

**Comment by GarinQian** [comment]
yes. my proxy use beego framework as a restful server. User transfer his file to the proxy program by a post request. Then the proxy upload file like below:
checkParamAndAuthority()
beego.Controller.SaveToFile("file", fullpath)
tx := db.MysqlConn.GetDb().Begin()
db.MysqlConn.InsertOrUpdateMetaData(tdfsTenantFile, tx)
cmd := exec.Command("curl", "-F", "filename=@"+fullpath, weedfsUrl)
cmd.Run()
err = db.MysqlConn.UpdateFidUrl(tdfsTenantFile, tx)
tx.Commit()

**Comment by chrislusf** [comment]
ok. but this code performance problem or permission problem is not an SeaweedFS problem.

**Comment by GarinQian** [comment]
I may have used SeaweedFS by mistake. Sorry to disturb you but should I offer sdk to users instead of a proxy api server? If I want to offer permission functions.

**Comment by chrislusf** [comment]
depends on your use case.
