### ISSUE TITLE
build weed on goarch=arm64 error  

### ISSUE THREAD

**Issue by binbinshi** [chrislusf/seaweedfs#1103]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**
when build the new version 1.44 weed by CGO in arch arm64 ,have a error

use cmd :  CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build weed/weed.go
```
# github.com/pingcap/parser/mysql
../go_path/pkg/mod/github.com/pingcap/parser@v0.0.0-20191021083151-7c64f78a5100/mysql/const.go:617:2: constant 2147483648 overflows SQLMode
../go_path/pkg/mod/github.com/pingcap/parser@v0.0.0-20191021083151-7c64f78a5100/mysql/const.go:618:2: constant 4294967296 overflows SQLMode
../go_path/pkg/mod/github.com/pingcap/parser@v0.0.0-20191021083151-7c64f78a5100/mysql/const.go:619:2: constant 8589934592 overflows SQLMode
../go_path/pkg/mod/github.com/pingcap/parser@v0.0.0-20191021083151-7c64f78a5100/mysql/util.go:44:19: constant 4294967295 overflows int
../go_path/pkg/mod/github.com/pingcap/parser@v0.0.0-20191021083151-7c64f78a5100/mysql/util.go:45:19: constant 4294967295 overflows int

```

**Expected behavior**
find TiDB is usually used under linux/64bit, we don't release or provide maintenance for other system/platform.  tidb issue   https://github.com/pingcap/tidb/issues/5224

**Additional context**
what do you think , how to fix the new fileStore tikv can not build on arm arch

**Comment by chrislusf** [comment]
Need to conditionally build etcd stores for linux 64bits only.

**Comment by chrislusf** [comment]
I actually can run these builds on my Mac.

```
weed$ CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build
weed$ CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build
```

**Comment by binbinshi** [comment]
thanks ,  solve my problem 
 CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build 

worked。
