### ISSUE TITLE
readbytes: index out of range 2

### ISSUE THREAD

**Issue by steven2612** [chrislusf/seaweedfs#1106]
**Describe the bug**
i have a system with currently 5 volume servers. a few days ago i upgraded to the latest version and did also ec.encode. so many of my volumes are now ec encoded.
now i have a strange problem - when trying to access a file: "64,f9c55e5657cb73"
volume 64 is ec encoded and a lookup says:
`{"volumeId":"64","locations":[{"url":"bm2:8280"},{"url":"bm6:8280"},{"url":"bm7:8280"},{"url":"bm8:8280"},{"url":"bm9:8280"}]}`
so the file should be accessable from all 5 volume servers. but only from bm8 i getting the file - all other response with 404 not found.
looking in the logfile of one of those nodes says:
```
I1107 18:48:30 28041 store_ec.go:126] ReadEcShardNeedle vid 64 version:2: <nil>
I1107 20:04:23 28041 volume_server_handlers_read.go:92] read /64,f9c55e5657cb73 isNormalVolume false error: readbytes: index out of range 2
```

with most files the system works fine - but some requests are showing the behavier described 

**System Setup**
Version: version 30GB 1.44 linux amd64
OS Version - mixed: Ubuntu 14.04.6 LTS and Ubuntu 18.04.3 LTS
```
weed volume -dataCenter=bm1 -rack=r1 -dir=/disks/weedfs1 -max 33 -ip=bm2 -mserver=bm2:9333,bm6:9333,bm7:9333 -port=8280 -port.public 8281
weed master -defaultReplication=001 -ip=bm2 -mdir=/data/weedfs -peers=bm2:9333,bm6:9333,bm7:9333
```

**Comment by chrislusf** [comment]
I suspect the volume servers can not talk to other volume servers via addresses like "bm6:8280".

**Comment by steven2612** [comment]
No, this has been the first thing i have checked ... on all systems there is a /etc/hosts file where those hosts are defined.
But just to be sure i tried to change to -ip ipaddr:
Now lookup says:
`{"volumeId":"64","locations":[{"url":"10.0.1.32:8280","publicUrl":"https://static.buchmedia.at/weed/bm2"},{"url":"10.0.1.36:8280","publicUrl":"https://static.buchmedia.at/weed/bm6"},{"url":"10.0.1.37:8280","publicUrl":"https://static.buchmedia.at/weed/bm7"},{"url":"10.0.1.38:8280","publicUrl":"https://static.buchmedia.at/weed/bm8"},{"url":"10.0.1.39:8280","publicUrl":"https://static.buchmedia.at/weed/bm9"}]}`
(and yes all those servers can speak to each other)
but the same behavior - bm8 - aka 10.0.1.38 - is possible to deliver the file - every other volume server response with 404 not found.
same entries in logfile

**Comment by chrislusf** [comment]
can you set volume server logging level to 4. ```weed -v=4 volume ... ``` to enable detailed logging, and show the logs when processing one request, on volume servers other than bm8?

**Comment by steven2612** [comment]
```
I1108 06:42:17  2676 volume_server_handlers_read.go:56] volume 64 reading f9c55e5657cb73 Size:0, DataSize:0, Name:, Mime:
I1108 06:42:17  2676 store_ec.go:138] read ec volume 64 offset 8755707616 size 2303926 intervals:[{BlockIndex:8 InnerBlockOffset:165773024 Size:2303952 IsLargeBlock:true LargeBlockRowsCount:2}]
I1108 06:42:17  2676 store_ec.go:291] read remote ec shard 64.8 from bm8:8280
I1108 06:42:17  2676 volume_server_handlers_read.go:90] read bytes 0 error readbytes: index out of range 2
I1108 06:42:17  2676 volume_server_handlers_read.go:92] read /64,f9c55e5657cb73 isNormalVolume false error: readbytes: index out of range 2

```

**Comment by steven2612** [comment]
additional - log from bm8 - same request - works:
```
I1108 16:47:29 60627 volume_server_handlers_read.go:56] volume 64 reading f9c55e5657cb73 Size:0, DataSize:0, Name:, Mime:
I1108 16:47:29 60627 store_ec.go:138] read ec volume 64 offset 8755707616 size 2303926 intervals:[{BlockIndex:8 InnerBlockOffset:165773024 Size:2303952 IsLargeBlock:true LargeBlockRowsCount:2}]
I1108 16:47:29 60627 volume_server_handlers_read.go:90] read bytes 2303952 error <nil>

```

**Comment by chrislusf** [comment]
Could you please share all the volume 64 related files, `64.*`, from bm8?

**Comment by steven2612** [comment]
Hi,
yes no problem - in the meantime i did another test. i copied all datafiles from volume 64 to one server and started 5 local instances +master:
```
weed -logdir master master -mdir master -port 9500
weed -logdir bm2 volume -dir bm2 -mserver localhost:9500 -port 9502
weed -logdir bm6 volume -dir bm6 -mserver localhost:9500 -port 9506
weed -logdir bm7 volume -dir bm7 -mserver localhost:9500 -port 9507
weed -logdir bm8 volume -dir bm8 -mserver localhost:9500 -port 9508
weed -logdir bm9 volume -dir bm9 -mserver localhost:9500 -port 9509
```
same effect - download possible via port 9508 - but not via the other volume servers
so this should be no network issue ...

you can download the datafiles via:
`https://static.buchmedia.at/weedtest/`
files:
```
./bm8/64.ec08
./bm8/64.ec06
./bm8/64.ec07
./bm8/64.ecx
./bm8/64.ecj
./bm2/64.ec01
./bm2/64.ec00
./bm2/64.ec02
./bm2/64.ecx
./bm2/64.ecj
./bm7/64.ec11
./bm7/64.ecx
./bm7/64.ecj
./bm7/64.ec10
./bm7/64.ec09
./bm6/64.ec13
./bm6/64.ecx
./bm6/64.ecj
./bm6/64.ec12
./bm9/64.ec05
./bm9/64.ec04
./bm9/64.ec03
./bm9/64.ecx
./bm9/64.ecj
```
so for example: `https://static.buchmedia.at/weedtest/bm2/64.ecx`

if i understood correct - the ec format splits the volume in 10 chunks and adds 4 parity chunks and distibutes those 14 chunks among the volume servers.
so i think what happens is, when accessing a file which is in one of the local chunks the download works fine - but when redirecting to another volume server there is this error.
but i dont know why some files are working fine and others not ..

**Comment by chrislusf** [comment]
Thanks a lot for the details! I added a fix.

**Comment by steven2612** [comment]
no problem - thanks for fixing - works !
a small detail i am not sure about - now with my compiled weed executable i am getting for a dir lookup:
`http://bm2:9333/dir/lookup?volumeId=64`
`{"volumeId":"64","locations":[{"url":"bm2:8280","publicUrl":"https://static.buchmedia.at/weed/bm2"},{"url":"bm2:8280","publicUrl":"https://static.buchmedia.at/weed/bm2"},{"url":"bm2:8280","publicUrl":"https://static.buchmedia.at/weed/bm2"},{"url":"bm9:8280","publicUrl":"https://static.buchmedia.at/weed/bm9"},{"url":"bm9:8280","publicUrl":"https://static.buchmedia.at/weed/bm9"},{"url":"bm9:8280","publicUrl":"https://static.buchmedia.at/weed/bm9"},{"url":"bm8:8280","publicUrl":"https://static.buchmedia.at/weed/bm8"},{"url":"bm8:8280","publicUrl":"https://static.buchmedia.at/weed/bm8"},{"url":"bm8:8280","publicUrl":"https://static.buchmedia.at/weed/bm8"},{"url":"bm7:8280","publicUrl":"https://static.buchmedia.at/weed/bm7"},{"url":"bm7:8280","publicUrl":"https://static.buchmedia.at/weed/bm7"},{"url":"bm7:8280","publicUrl":"https://static.buchmedia.at/weed/bm7"},{"url":"bm6:8280","publicUrl":"https://static.buchmedia.at/weed/bm6"},{"url":"bm6:8280","publicUrl":"https://static.buchmedia.at/weed/bm6"}]}`

so many duplicated entries - not a real problem - but why ?
