### ISSUE TITLE
使用docker安装配置，如何查看上传的文件在容器的哪个位置，如何挂载这些数据并且持久化

### ISSUE THREAD

**Issue by GeorgeWang1994** [chrislusf/seaweedfs#1109]
使用docker安装配置，如何查看上传的文件在容器的哪个位置，如何挂载这些数据并且持久化

**Comment by GeorgeWang1994** [comment]
文章实在是太少了，😭

**Comment by chrislusf** [comment]
https://github.com/chrislusf/seaweedfs/blob/master/docker/Dockerfile#L38
