### ISSUE TITLE
Could you explain weed's failover algorithm

### ISSUE THREAD

**Issue by fedotxxl** [chrislusf/seaweedfs#111]
We've got one master and 3 volumes server with 001 replication. 

I though failover works following way:
1. Periodically I ask location for volume `XX` (extract volume number from file id)
2. If volume `XX` is located on volume server 1 and 2 and server 1 is not available weed master will return server 2 only

So I tested it:
1. I disabled one volume server (`v1` was disabled, `v2` and `v3` was available)
2. All volumes except one (`YY`) works as expected. I asked location for `YY` (`lookup`) and it was empty although this volume are also located on `v3`.
3. It was strange. I restarted master server
4. In a few minutes `YY` volume **was added to v2**. Now I've got **empty** `YY` volume on `v2`.

My questions:
1. Why lookup returned empty for volume `YY`
2. Why `YY` was added to `v2` volume server after I restarted master? Why is it empty? Is it a bug?

**Comment by chrislusf** [comment]
Where is YY located? You can just list the volume server running folders to see the volumes.

**Comment by chrislusf** [comment]
Please do a "ls -l" to show the YY.dat file on v2 and v3.

**Comment by fedotxxl** [comment]
I'm sorry, I already removed empty files - their size was few kb.
I'll try to reproduce problem this evening

**Comment by fedotxxl** [comment]
We use  v. `0.65 `. It's something strange with this volume. I restarted all volume servers.

 `curl "http://localhost:8071/status?pretty=y"` and `curl "http://localhost:8073/status?pretty=y"` shows the same data -

>{
>      "Id": 43,
>      "Size": 1688713,
>      "ReplicaPlacement": {
>        "SameRackCount": 1,
>        "DiffRackCount": 0,
>        "DiffDataCenterCount": 0
>      },
>      "Ttl": null,
>      "Collection": "my.collection",
>      "Version": 2,
>      "FileCount": 312,
>      "DeleteCount": 0,
>      "DeletedByteCount": 0,
>      "ReadOnly": false
>    }

but `curl "http://localhost:9333/dir/lookup?volumeId=43&pretty=y"` returns only first volume location:

>{
>  "volumeId": "43",
>  "locations": [
>    {
>      "url": "dev.search.devadmin.com:8071",
>      "publicUrl": "dev.search.devadmin.com:8071"
>    }
>  ]
>}

for other volumes `lookup` returns all locations.

**Comment by chrislusf** [comment]
Can you please show the full outputs of 
http://localhost:8071/status?pretty=y
http://localhost:8073/status?pretty=y
http://localhost:9333/dir/status?pretty=y

**Comment by chrislusf** [comment]
No progress here.
