### ISSUE TITLE
[question] - file with missing shards(s)

### ISSUE THREAD

**Issue by eleaner** [chrislusf/seaweedfs#1110]
Hi,

I cannot easily find the answer
How can I easily identify if for whatever reason I have file(s) with shards?
(therefore not completely stored)

**Comment by chrislusf** [comment]
no easy way.

**Comment by eleaner** [comment]
@chrislusf 
is it by design? any reason for that?
I mean if it is highly unlikely to happen then I could try to understand
but either way, I would like to be able to check the availability and consistency of my data

**Comment by chrislusf** [comment]
For this, you will need to have a reverse index of block-to-file mapping. It comes at a cost to maintain it when files are changing. 

You can export the filer store metadata to analyze in an offline style.

**Comment by eleaner** [comment]
@chrislusf 
I am sorry, I don't understand
you sound like you think it this information is not needed or does not benefit enough, hence not worth of implementation

The way I see it you are telling me that I may have an HA cluster of 3 masters with three volume servers with HA Cassandra to store filer information and default replication set to 2. 
Yet I will still have no idea if my data is actually stored in seaweedfs unitl I will try to read it.
Am I correct?

**Comment by chrislusf** [comment]
I am sorry, I don't understand.

You can export the filer store metadata to analyze what is stored.

**Comment by eleaner** [comment]
could you point me to the documentation where I can read how to do it?

**Comment by chrislusf** [comment]
check https://github.com/chrislusf/seaweedfs/blob/master/weed/shell/command_fs_meta_save.go
to see how to iterate through all entries.

With all the entries information, you can see which files are using the missing volume.

**Comment by eleaner** [comment]
@chrislusf 
Oh man. That's way above my paygrade.
Could I file a feature request for that?
