### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference when start volume server

### ISSUE THREAD

**Issue by richard-yao** [chrislusf/seaweedfs#1113]
When I try to load file and start volume server with command:
`./weed volume -dir=/data0/seaweedfs_data -max=2048 -mserver=10.11.10.134:9333 -ip=10.11.10.134 -port=9080 -dataCenter=shdc -rack=rack2 -publicUrl=10.11.10.134:9080`

* Erro log: 
> I1111 13:21:58 13497 file_util.go:19] Folder /data0/seaweedfs_data Permission: -rwxr-xr-x
I1111 13:21:58 13497 volume_loading.go:79] loading index /data0/seaweedfs_data/105.idx to memory readonly false
I1111 13:21:58 13497 volume_loading.go:79] loading index /data0/seaweedfs_data/102.idx to memory readonly false
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x9aa317]

> goroutine 106 [running]:
github.com/chrislusf/seaweedfs/weed/storage.(*ReplicaPlacement).Byte(...)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/storage/replica_placement.go:39
github.com/chrislusf/seaweedfs/weed/storage.(*SuperBlock).Bytes(0xc00003a230, 0x0, 0xc000282dd0, 0x0)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/storage/volume_super_block.go:48 +0x67
github.com/chrislusf/seaweedfs/weed/storage.(*Volume).maybeWriteSuperBlock(0xc00003a1e0, 0x1d, 0x42)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/storage/volume_super_block.go:79 +0x1da
github.com/chrislusf/seaweedfs/weed/storage.(*Volume).load(0xc00003a1e0, 0xc000030101, 0x0, 0x0, 0xc0002769f6, 0x1)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/storage/volume_loading.go:58 +0x15d5
github.com/chrislusf/seaweedfs/weed/storage.NewVolume(0x7fff624d976e, 0x15, 0x0, 0x0, 0x6b, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/storage/volume.go:36 +0xdb
github.com/chrislusf/seaweedfs/weed/storage.(*DiskLocation).loadExistingVolume(0xc000571900, 0x170a240, 0xc000279520, 0x0, 0xc0001047c0)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/storage/disk_location.go:52 +0x1ef
github.com/chrislusf/seaweedfs/weed/storage.(*DiskLocation).concurrentLoadingVolumes.func2(0xc000124f20, 0xc000109740, 0xc000571900, 0x0, 0xc0001047c0)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/storage/disk_location.go:92 +0x8f
created by github.com/chrislusf/seaweedfs/weed/storage.(*DiskLocation).concurrentLoadingVolumes
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/storage/disk_location.go:89 +0x12a

**Comment by richard-yao** [comment]
Who can help me with this issue, my server version:
`version 1.15 linux amd64` on `Ubuntu 16.04.1 LTS`

**Comment by richard-yao** [comment]
emmm, when I remove empty .dat and .idx file from directory, and retry start volume server, it's worked and startup sucesfully! What's up??

**Comment by chrislusf** [comment]
https://github.com/chrislusf/seaweedfs/issues/1079

upgrade to latest version.
