### ISSUE TITLE
can i change path of filer？

### ISSUE THREAD

**Issue by GeorgeWang1994** [chrislusf/seaweedfs#1117]
if i have upload the file to the filer，but now i want to change path of filer，can i do it？

原因是之前已有的文件存储的路径的结构不是很合理，所以想更改下路径，但是由于文件过多，我们需要自己写脚本先更改文件路径再上传到Filer（文件过多脚本执行花的时间很多），或者是先上传到Filer再更改路径（不确定是否支持这么做？）。

期待您的回复。

**Comment by GeorgeWang1994** [comment]
how can i get the fast way

**Comment by chrislusf** [comment]
`weed shell` has `fs.mv` command
