### ISSUE TITLE
在使用copy命令上传的过程中，docker卡死

### ISSUE THREAD

**Issue by GeorgeWang1994** [chrislusf/seaweedfs#1119]
![image](https://user-images.githubusercontent.com/29206315/68843989-ff6f4500-0703-11ea-96eb-f1495e6bf6e1.png)

![image](https://user-images.githubusercontent.com/29206315/68844012-08f8ad00-0704-11ea-8a89-a1803df4f985.png)

**Comment by GeorgeWang1994** [comment]
当停掉命令后，docker恢复正常

**Comment by chrislusf** [comment]
need details on how to reproduce

**Comment by GeorgeWang1994** [comment]
重新尝试了一次，又正常了，具有偶发性，猜想是有可能和docker的配置过低导致的，我看内存消耗得非常的快。
