### ISSUE TITLE
how to migrate from old version of seaweedfs?

### ISSUE THREAD

**Issue by howardlau1999** [chrislusf/seaweedfs#1120]
We have a long running Docker instance of SeaweedFS with filer version 0.76. We tried copying the filer data folder to another machine as well as volumes data folder. Then we run a newer Docker version of SeaweedFS with filer version 1.44 and configured it to load data from previously backup folders (also with correct database type). Unfortunately, although the master filer and volumes started normally, everything is lost in the filer. When we run the same old version of SeaweedFS on the new machines, everything worked fine.

Because the original version was too old to use `weed shell` and `fs.meta.save`, it was just an echo shell. How can we migrate from old version to new version while keeping all filer indexes?

**Comment by ijunaid8989** [comment]
Short answer: It's not going to be possible for you.

We got into the same situation with 2 Master filer with 4 volumes each filer.

We were trying to update from 0.76 to 0.92.
Finally, we just started a new filer from scratch because the directory structure is also changed in newer versions. 

In my opinion, you have to do the same.

**Comment by howardlau1999** [comment]
@ijunaid8989 So you did not recover data from old versions?

**Comment by ijunaid8989** [comment]
@howardlau1999 We didn't lost any data. I don't know about your configurations.

But we are running Elixir/Phoenix application which is directly talking to seaweedfs. we are saving jpegs with different frequencies to the filer, and we have managed to program our application to deal with all 4 filers. Now our application is using the older filers for read-only and the newer one for write operations.
We kept older versions to the same versions. but added a new filer with latest one.

**Comment by howardlau1999** [comment]
Our system heavily depends on the Filer API so data recovery is necessary. Is there any migration script that helps me export/import metadata or do I have to try to write one to read from the leveldb?

**Comment by howardlau1999** [comment]
@ijunaid8989 OK. I understand your configuration. I have the same situation as you. So it seems that the only way to deal with this is running two versions of filer at the same time?

**Comment by howardlau1999** [comment]
@ijunaid8989 Our system written in Node.js uses Filer API to access the seaweedfs. We depends on the path to retrieve the file. So once the filer fails to work, our application has no way to access the file.

**Comment by ijunaid8989** [comment]
@howardlau1999 Yes ,  But there was a migration script written in Go, I tried to find it in Wiki but I couldn't find it.
I think it would be best to just have 2 filers one with old and one with new. also one for reading and another one for write may be? 

You have to look for a few things.

1. Directory structure changes.
2. How you will delete files
3. you should choose leveldb2
4. Starting filer in newer version is different than the old one. 

You can specify your filer.toml file as well if you want to have metrics etc. stuff.

**Comment by howardlau1999** [comment]
@ijunaid8989 Do you use fid to retrieve files?

**Comment by ijunaid8989** [comment]
@ijunaid8989 nope we are saving it with a directory structure.

camera_name / year / month / day / hour / minutes_seconds_000.jpg

**Comment by howardlau1999** [comment]
@ijunaid8989 I see. We are now running one master, one filer (0.76) and four volumes (0.76). Based on your solution, am I supposed to upgrade my master and volumes to newer versions, keep the 0.76 filer running and communicating to the new master but for read-only purpose, and start a 1.44 filer communicating with the same master for write-only purpose?

**Comment by ijunaid8989** [comment]
Nope you got it totally wrong..

You need to leave what you already have running.. (in working form.)

Just start everything from scratch as a new filer and volume. with a newer version.

You just have to leave older all master filer and volumes as it is they are right now.

**Comment by howardlau1999** [comment]
@ijunaid8989 or we just start a fresh new 1.44 seaweedfs with empty directories and figure out in the application which file belongs to which version

**Comment by ijunaid8989** [comment]
how you are getting the files? 

actually I might be giving you totally wrong direction not knowing your application configurations and how you are getting your files is your application is open source? in the case to see how you are getting and displaying your files?

**Comment by howardlau1999** [comment]
@ijunaid8989 We are getting files using paths as yours. e.g. images/:user_id/upload_date.jpg

**Comment by howardlau1999** [comment]
@ijunaid8989 For example, if a user uploads an image, our Node.js app will receive the image and send a POST request to the Filer API storing that image as /images/:user_id/upload_date.jpg, and we use the same path to get the image back.

**Comment by ijunaid8989** [comment]
in our application.

luckily we added new filers on 1 of November of each year. right now there are 4 filers.

So we already know if a user is requesting for a file, (with DateTime ),  where to look for it..

If you are also saving it with a date. then configure you application at one point to switch between filers. 

before showing the files to user.. analyze the date to which filer it belongs.

**Comment by ijunaid8989** [comment]
@howardlau1999 its easy then you can have 2 filers and also can handle requests as well every easily.

**Comment by howardlau1999** [comment]
@ijunaid8989 Thanks for your patience! But I still hope that there is a solution without the need to modify our application.

**Comment by ijunaid8989** [comment]
Yes @chrislusf may have one. :)

**Comment by howardlau1999** [comment]
@ijunaid8989 OK. After a lot of searching, I finally found this: https://github.com/chrislusf/seaweedfs/wiki/Directories-and-Files/c060251567c5c9b29f6ff929fb11f20607482de5

**Comment by ijunaid8989** [comment]
Yes, that was the script, I was telling you I am trying to find. :+1:  Tell me how it goes.

**Comment by howardlau1999** [comment]
@ijunaid8989 Unluckily, the script seems helpless because it can only copy from local disk to filer, instead of copying from one filer to another. I finally decided to write some python scripts to export the files list, and then download them using Filer API to a temp folder, then use that command to copy files back. There are 2 million files in our system so it may take a long while...

**Comment by ijunaid8989** [comment]
@howardlau1999 Yes, that's not a crazy idea, I hope it may work for you. You will surely be going to face many surprises, Good luck

**Comment by chrislusf** [comment]
Thanks @ijunaid8989 for helping!

@howardlau1999 it's not the most efficient way, but it is the most simple way.

**Comment by ijunaid8989** [comment]
@chrislusf No issues. Happy to help. :)
