### ISSUE TITLE
修改文件名的API在哪啊

### ISSUE THREAD

**Issue by 9527code** [chrislusf/seaweedfs#1121]
修改文件名的API在哪啊，找半天没找到

**Comment by ijunaid8989** [comment]
https://groups.google.com/forum/#!searchin/seaweedfs/rename$20a$20file%7Csort:date/seaweedfs/DrKRoGsRcIY/DxO94B5oedEJ

**Comment by 9527code** [comment]
fs.mv 有webapi吗？还是只能在weed shell 里使用?

**Comment by 9527code** [comment]
我尝试使用fs.cd 先切换到mysql进行修改后再转换到leveldb, 但是输出
total 9226 directories, 3657640 files
这个数据好像不对啊。21579709我的实际文件大概是这么多
