### ISSUE TITLE
weed shell 可以web访问吗?

### ISSUE THREAD

**Issue by 9527code** [chrislusf/seaweedfs#1122]
weed shell 可以web访问吗? 需要大批量更新文件名，不知道怎么其他方式 调用fs.mv

**Comment by 9527code** [comment]
另外如何获得grcp api？ 我使用的是.net core，没有找到proto文件在哪啊

**Comment by 9527code** [comment]
找到了

**Comment by wellyn-chen** [comment]
> 

> 找到了

Excuse me, what do you use?
