### ISSUE TITLE
Problems with long answer times (sometimes)

### ISSUE THREAD

**Issue by steven2612** [chrislusf/seaweedfs#1123]
since upgrading to 1.44 (from a very old version) i have the problem that some of my requests take a very long time. usually 300-400ms those exactly 30s.
for example:
```
ab -n 1000 -c 100 http://bm2:8281/90,01eb796d76da5ebf.jpg?width=500                                                              
This is ApacheBench, Version 2.3 <$Revision: 1528965 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking bm2 (be patient)
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
Completed 500 requests
Completed 600 requests
Completed 700 requests
Completed 800 requests
Completed 900 requests
Completed 1000 requests
Finished 1000 requests


Server Software:        
Server Hostname:        bm2
Server Port:            8281

Document Path:          /90,01eb796d76da5ebf.jpg?width=500
Document Length:        119694 bytes

Concurrency Level:      100
Time taken for tests:   30.064 seconds
Complete requests:      1000
Failed requests:        0
Total transferred:      119886000 bytes
HTML transferred:       119694000 bytes
Requests per second:    33.26 [#/sec] (mean)
Time per request:       3006.387 [ms] (mean)
Time per request:       30.064 [ms] (mean, across all concurrent requests)
Transfer rate:          3894.25 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    1   1.5      0       8
Processing:    19  404 940.6    381   30024
Waiting:       19  373  76.2    380     568
Total:         22  404 940.6    382   30024

Percentage of the requests served within a certain time (ms)
  50%    382
  66%    401
  75%    413
  80%    426
  90%    450
  95%    471
  98%    494
  99%    523
 100%  30024 (longest request)
```

i dont see where my problem is, also i cant remember such problems with the version before (0.76 or so)

Details:
- it make no difference if its a ec or non ec volume, vol 90 in this example is a normal volume (not ec)
- all volume servers have the same problem

hardware is relativly powerful:
Intel(R) Xeon(R) CPU           E5506  @ 2.13GHz 8 cores
94 GB Ram
harddrive: WDC WD40EZRX-00SPEB0 - 4TB - SATA 3.0, 6.0 Gb/s (current: 3.0 Gb/s)
neither cpu nor io is on limit
System is Ubuntu Server from 14.04.6 to 18.03 (different volume servers)

have you any hints how to find the problem, or where the exactly 30s waiting time are coming from?

**Comment by chrislusf** [comment]
maybe removing the width parameter from "/90,01eb796d76da5ebf.jpg?width=500"

**Comment by steven2612** [comment]
no, its the same with and without width parameter ...

so i did some more tests - i could reproduce it on all my systems (also at home):
```
weed server -volume.port=9501 -master.port=9500 -dir=.
weed upload -master localhost:9500 test.png
[{"fileName":"test.png","fileUrl":"localhost:9501/7,0120616cbb","fid":"7,0120616cbb","size":64598}]
ab -n 1000 -c 100 http://localhost:9501/7,0120616cbb
This is ApacheBench, Version 2.3 <$Revision: 1807734 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
Completed 500 requests
Completed 600 requests
Completed 700 requests
Completed 800 requests
Completed 900 requests
Completed 1000 requests
Finished 1000 requests


Server Software:
Server Hostname:        localhost
Server Port:            9501

Document Path:          /7,0120616cbb
Document Length:        64598 bytes

Concurrency Level:      100
Time taken for tests:   30.010 seconds
Complete requests:      1000
Failed requests:        0
Total transferred:      64845000 bytes
HTML transferred:       64598000 bytes
Requests per second:    33.32 [#/sec] (mean)
Time per request:       3001.032 [ms] (mean)
Time per request:       30.010 [ms] (mean, across all concurrent requests)
Transfer rate:          2110.11 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   1.3      0       8
Processing:     0  312 2985.4     12   30002
Waiting:        0   11   2.4     12      24
Total:          0  312 2985.8     12   30009

Percentage of the requests served within a certain time (ms)
  50%     12
  66%     12
  75%     13
  80%     13
  90%     14
  95%     15
  98%     20
  99%  30002
 100%  30009 (longest request)
```

from 1000 requests around 1-10 requests last exactly 30sec

**Comment by chrislusf** [comment]
Try to see perf with less concurrent threads, smaller files, etc

**Comment by steven2612** [comment]
same also with less concorent threads (down to one), file is relativly small (test with files 10kB to 60kB)

**Comment by chrislusf** [comment]
try `ab -k`

**Comment by steven2612** [comment]
yes - `ab -k` is working - but this is only a test tool to reproduce what i am using live. and there i have such problems:
i have a (very busy) website where i have a booksearch where i show around 30 books per page. all the covers are coming from seaweedfs. when i am browsing thrugh the results i have most of the time on every page one or two cover images which need much longer to load (30s) and i am trying to find a solution for this specific problem an narrowed it down to an seaweedfs problem. so ab is only a way to reproduce the problem.
the coverimages are delivered either direct (via nginx proxy) or indirect over a php script (because of image overlays or similar). whith nginx proxy i have some ways to lower the problem (keepalive, failover, cache ..) but with the php script i can't do a keepalive for example ...
i tried the test case on many of may computers so i can say this is no hardware problem or problem of the operating system (or background tasks), it seems only be realated to seaweedfs.
so the principial problem with the 30s delay on a few requests keeps beeing a problem.

**Comment by chrislusf** [comment]
`weed -idleTimeout=xxx` or close the http requests
