### ISSUE TITLE
Migrate from 0.76 to 1.43 and from Old Server to New Server

### ISSUE THREAD

**Issue by Kiltalaw** [chrislusf/seaweedfs#1128]
Hi chris,
 Could you please give me a suggestion about how to migrate v0.76 in old server to v1.43  in new server?
 I have met a problem that the program collecting images from collector and store the images into seaweedfs but we can not stop the program in product env.(We use the master and volume ,no filer,because we save the url or publicUrl and fid into nosql db and use them to get image)
So in this situation, how can we upgrade the seaweedfs version and migrate to new server?

**Comment by chrislusf** [comment]
maybe change your program in production to allow retries, so that the master and volume servers can restart.
