### ISSUE TITLE
希望增加Filer中ttl的功能

### ISSUE THREAD

**Issue by GeorgeWang1994** [chrislusf/seaweedfs#1133]
由于目前Filer无法指定ttl，非常希望增加这个功能

**Comment by chrislusf** [comment]
What store are you using?

If this feature is implemented, this feature will only be able to work with C* or Redis store.

**Comment by stlpmo-jn** [comment]
in the filer.toml, look like these :
[mysql]
connection_max_idle = 1000
connection_max_open = 1000

[redis]
redis_key_expiration = "60d"

i will impliment it next time.
