### ISSUE TITLE
convert ec volume back to normal

### ISSUE THREAD

**Issue by steven2612** [chrislusf/seaweedfs#1134]
Hi,

is there any way to convert a ec volume back to a normal volume ?

best regards,
Stefan

**Comment by chrislusf** [comment]
not developed yet.

**Comment by steven2612** [comment]
Is it possible to help with this, or are you already working on it?
i had converted a bunch of volumes to ec and did after that a cleanup - so there are many deleted files, it would be cool if there is a possibility to clean up and reduce the used storage ...

**Comment by chrislusf** [comment]
Not trivial. I just commited in the change.

**Comment by steven2612** [comment]
sorry for the late answer - i tried 1.48

it seems to work well - but at the end while deleting shards i got an error:
```
> ec.decode
ec encode volumes: [63 26 39 62 53 13 55 14 18 60 19 42 40 47 56 16 41 37 15 64 17 44 49 57 61 59 38]
ec volume 63 shard locations: map[bm2:8280:7 bm6:8280:8 bm7:8280:12344 bm8:8280:448 bm9:8280:3584]
collectEcShards: ec volume 63 collect shards to bm8:8280 from: map[bm2:8280:7 bm6:8280:8 bm7:8280:12344 bm8:8280:448 bm9:8280:3584]
copy 63.[9] bm9:8280 => bm8:8280
copy 63.[0 1 2] bm2:8280 => bm8:8280
copy 63.[3] bm6:8280 => bm8:8280
copy 63.[3 4 5] bm7:8280 => bm8:8280
generateNormalVolume from ec volume 63 on bm8:8280
unmount ec volume 63 on bm9:8280 has shards: [9 10 11]
unmount 63.[9 10 11] from bm9:8280
unmount ec volume 63 on bm8:8280 has shards: [0 1 2 3 4 5 6 7 8 9]
unmount 63.[0 1 2 3 4 5 6 7 8 9] from bm8:8280
unmount ec volume 63 on bm2:8280 has shards: [0 1 2]
unmount 63.[0 1 2] from bm2:8280
unmount ec volume 63 on bm6:8280 has shards: [3]
unmount 63.[3] from bm6:8280
unmount ec volume 63 on bm7:8280 has shards: [3 4 5 12 13]
unmount 63.[3 4 5 12 13] from bm7:8280
delete ec volume 63 on bm9:8280 has shards: [9 10 11]
delete 63.[9 10 11] from bm9:8280
delete ec volume 63 on bm8:8280 has shards: [0 1 2 3 4 5 6 7 8 9]
delete 63.[0 1 2 3 4 5 6 7 8 9] from bm8:8280
delete ec volume 63 on bm2:8280 has shards: [0 1 2]
delete 63.[0 1 2] from bm2:8280
delete ec volume 63 on bm6:8280 has shards: [3]
delete 63.[3] from bm6:8280
error: delete ec shards for volume 63: mountVolumeAndDeleteEcShards delete ec volume 63 on bm6:8280: rpc error: code = Internal desc = grpc: error while marshaling: proto: Marshal called with nil
```
it seems it deleted the shards, but there is an 63.vif file left on bm6

**Comment by steven2612** [comment]
I now decoded all ec shards. following i have noticed:
1. master background tasks - if configured - (ec.balance, ec.encode, ...) should not be running and prevented to start. (either do it manually, or better would be, if ec.decode does this itself) 
2. if some error accours it happens the .dat file is created but ec files not deleted.
3. it looks like deleted files are somewhere reseted - all data files have full size, but say (0 / 0 Bytes Trash) - even if i know there must be many deleted files.
4. i tried to check if there are deleted files - so i did a `weed export` - it prints only one file and following error message: ` volume_read_write.go:213] cannot read needle body: index out of range 1` - but webpage says: 1259033 files
5. i tried to reindex the dat file - copied the file to a tmp directory and run `weed fix` on the volume file. sadly it only generates a zero size index file (without error message)

how can i help to fix this ?

**Comment by chrislusf** [comment]
Thanks for all the details. I would check each item carefully.

5. added a fix for it. (https://github.com/chrislusf/seaweedfs/commit/aa73364a246548c20557804fb9a9323a72950985) But it would not help for your case. In EC volumes, the actual deletion is recorded in .ecj files on different volume servers. So `weed fix` would not help here.

**Comment by steven2612** [comment]
Hi !
i just compiled the new version with the fix.
yes - weed fix now works and all files are listed now - thanks.
i will write a script which will check which files are listed in my database to delete all other files, so its no problem in my case, now when i can get a list of all available files ..

**Comment by chrislusf** [comment]
added another fix (acf7ca7b93e0a33e9fc987dec600d1b9f1dc1e32) to do compaction correctly. 

However, your current volume files already lost the deletion info. So it could not help more here ...

**Comment by steven2612** [comment]
do you mean with "compaction fix" when doing the decoding ec shards, in the same time doing a compaction of the volume file? this would be nice.

**Comment by chrislusf** [comment]
I meant something else...

But what you stated is in place already.

**Comment by chrislusf** [comment]
already completed.
