### ISSUE TITLE
weed volume can't be registed to master server which assigned at start time

### ISSUE THREAD

**Issue by bluedragonflyliu** [chrislusf/seaweedfs#1136]
##start master at 135 weed master
##start volume at 131 weed volume -dir=/tmp/weed/data3 -max=5 -mserver=172.16.1.135:9333 -port=8083 -ip 172.16.1.131

###log in 131 server
weed volume -dir=/tmp/weed/data3 -max=5 -mserver=172.16.1.135:9333 -port=8083 -ip 172.16.1.131
I1125 05:17:30  5038 config.go:28] Reading : Config File "security" Not Found in "[/root /root/.seaweedfs /etc/seaweedfs]"
I1125 05:17:30  5038 file_util.go:19] Folder /tmp/weed/data3 Permission: -rwxr-xr-x
I1125 05:17:30  5038 disk_location.go:109] Store started on dir: /tmp/weed/data3 with 0 volumes max 5
I1125 05:17:30  5038 disk_location.go:112] Store started on dir: /tmp/weed/data3 with 0 ec shards
I1125 05:17:30  5038 volume.go:162] Start Seaweed volume server 30GB 1.45 at 0.0.0.0:8083
I1125 05:17:30  5038 volume_grpc_client_to_master.go:24] Volume server start with seed master nodes: [172.16.1.135:9333]
I1125 05:17:30  5038 volume_grpc_client_to_master.go:68] Heartbeat to: 172.16.1.135:9333
I1125 05:17:30  5038 volume_grpc_client_to_master.go:84] Volume Server found a new master newLeader: localhost:9333 instead of 172.16.1.135:9333
I1125 05:17:30  5038 volume_grpc_client_to_master.go:65] SendHeartbeat to localhost:9333: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp [::1]:19333: connect: connection refused"
I1125 05:17:30  5038 volume_grpc_client_to_master.go:45] heartbeat error: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp [::1]:19333: connect: connection refused"

###weed version 131
####weed version
#####version 30GB 1.45 linux amd64

###log at 172.16.1.135 server

I1125 18:17:45 16499 master_grpc_server.go:77] added volume server 172.16.1.131:8083
W1125 18:17:45 16499 master_grpc_server.go:53] SendHeartbeat.Recv server 172.16.1.131:8083 : rpc error: code = Canceled desc = context canceled
I1125 18:17:45 16499 master_grpc_server.go:24] unregister disconnected volume server 172.16.1.131:8083
I1125 18:17:45 16499 node.go:256] topo:DefaultDataCenter:DefaultRack removes 172.16.1.131:8083

###weed version at 135
####weed version
#####version 30GB 1.45 linux amd64

**Comment by chrislusf** [comment]
`weed master -ip 172.16.1.135`
