### ISSUE TITLE
Is there way to configure security.toml from docker-compose/run command?

### ISSUE THREAD

**Issue by OneB1t** [chrislusf/seaweedfs#1138]
**Describe the bug**
I want to configure JWT token and certificates for seaweed docker installation. And backup that configuration as part of docker-compose. Is there now any way to achieve this or i need to modify entrypoint.sh to generate security.toml from enviromental properties or code of seaweed itself.

**System Setup**
Ubuntu 18.04 + docker
seaweedfs 1.45

**Comment by chrislusf** [comment]
modify entrypoint.sh
