### ISSUE TITLE
support memsql through mysql connection

### ISSUE THREAD

**Issue by LazyDBA247-Anyvision** [chrislusf/seaweedfs#1141]
Hi Chris,
[memsql](https://docs.memsql.com/v6.8/introduction/how-memsql-works/) is providing a mysql client compatibility,
but the default connection parameters for mysql filer backend need to be changed.
the go driver: github.com/go-sql-driver/mysql
need to use in the connection string  param  **&interpolateParams=true**
https://github.com/go-sql-driver/mysql#interpolateparams
learned that on (and verified on a local build):
https://github.com/opencensus-integrations/ocsql/issues/17

How seaweedfs can support toggling this param?
or should I duplicate the mysql backend and PR with memsql (but except that connection string, all the same?)

Thanks!

**Comment by chrislusf** [comment]
Maybe need a PR to configure in the filer.toml file and pass the parameters
in.

**Comment by chrislusf** [comment]
adjust the connection string here

https://github.com/chrislusf/seaweedfs/blob/master/weed/filer2/mysql/mysql_store.go#L50
