### ISSUE TITLE
How is Filer with Redis store limited?

### ISSUE THREAD

**Issue by payton109** [chrislusf/seaweedfs#1143]
https://github.com/chrislusf/seaweedfs/wiki/Filer-Stores says that **number of entries in a folder** for Redis File Store is "limited" but I cannot find how it is limited. Could someone explain this limitation?
I need to store many (>thousands) of files each with a hash-like filename where collisions won't occur. Depending on the limit, I could use a multi-level directory structure, where the first part of a filename matches the corresponding directory name, or have every file in a single directory.

**Comment by chrislusf** [comment]
In redis, the directory entry is read and written as a whole, not efficient
for lots of files.
