### ISSUE TITLE
Web服务器HTTP危险方法检测

### ISSUE THREAD

**Issue by wideweide** [chrislusf/seaweedfs#1151]
在外网部署时，服务商检测提示：
漏洞编号 | 431 -- | -- 高风险
远程Web服务器允许PUT和/或DELETE方法。
PUT方法允许攻击者在服务器上上传任意网页。如果服务器配置为支持ASP或PHP等脚本，则可以让攻击者使用Web服务器的权限执行代码。  DELETE方法允许攻击者从Web服务器中删除任意内容。
在Web服务器配置中禁用PUT和/或DELETE方法。

----
虽然并未直接对外提供服务，且有防火墙拦截，仍然想知道有解决办法吗？

**Comment by chrislusf** [comment]
check 
https://github.com/chrislusf/seaweedfs/wiki/Security-Overview
https://github.com/chrislusf/seaweedfs/wiki/Security-Configuration

**Comment by userStarlight** [comment]
seaeedfs可以把8888端口号的WebUI给禁用了吗？

**Comment by chrislusf** [comment]
`weed filer -disableDirListing`
