### ISSUE TITLE
seaweedFs colony

### ISSUE THREAD

**Issue by xiaoqi-hhm** [chrislusf/seaweedfs#1154]
Can you provide a seaweedfs cluster installation configuration

**Comment by chrislusf** [comment]
Not clear what you are asking for.

**Comment by xiaoqi-hhm** [comment]
> Not clear what you are asking for.
我想要seaweedFs 集群的部署的方式和步骤，针对的是多台服务器的集群，谢谢

**Comment by chrislusf** [comment]
Not clear.

**Comment by xiaoqi-hhm** [comment]
如何实现集群化
