### ISSUE TITLE
volume 的询问

### ISSUE THREAD

**Issue by xiaoqi-hhm** [chrislusf/seaweedfs#1155]
你好
  volume是只能注册到本机的master吗，能不能让volume注册到另外一台服务器上的master上呢。

**Comment by chrislusf** [comment]
No. Yes.

**Comment by xiaoqi-hhm** [comment]
那怎么将volume注册到另外一台服务器上呢


`/usr/local/weed volume -dir="/data/seaweed/vol/vol2" -mserver="192.168.1.15:9333" -port=9084 -ip="192.168.1.16" $>>/data/seaweed/logs/vol4.log`
![image](https://user-images.githubusercontent.com/29480206/70767318-d4781f80-1d9b-11ea-97d2-2dae1a86f59a.png)

这个是我的配置信息，
我使用以上的配置信息注册不到15服务器上。

我是需要把master加上16的ip地址吗？

**Comment by chrislusf** [comment]
can not tell. Very likely it is the network problem.
