### ISSUE TITLE
Async replication to multi-target (filer)

### ISSUE THREAD

**Issue by bernardx** [chrislusf/seaweedfs#1157]
Is it possible to async replicate files to multiple targets? For example, I would like to sync to a mirror server and in the meantime sync another copy to S3 for backup purposes.

**Comment by chrislusf** [comment]
check `weed backup`

S3 does not allow incremental appending to a file. You can copy the files directly.

**Comment by bernardx** [comment]
Thanks for the quick reply. Yes, weed backup should definitely work for backup purposes.
 
However, what I really need is a real time async replicate from one server to two locations:  
```
weed (server)  ---> weed (home)
               ---> weed (office)
```
I dig a bit in the code, but it seems only one ReplicationSink is allowed currently.

**Comment by chrislusf** [comment]
Setup with ultiple replication sinks is possible by multiple instances of `weed filer.replicate`.

**Comment by bernardx** [comment]
Thanks, I'll check that.
