### ISSUE TITLE
No docker image

### ISSUE THREAD

**Issue by ArtworkAD** [chrislusf/seaweedfs#116]
The docker image is no longer in the docker hub. Are there plans to get it back?

**Comment by chrislusf** [comment]
I'm not familiar with docker image myself. Need some help here.

**Comment by ArtworkAD** [comment]
@chrislusf but it's in the docs http://weed-fs-fork.readthedocs.org/en/latest/gettingstarted.html#using-seaweed-fs-in-docker

If I have spare time I will try to setup a docker image

**Comment by chrislusf** [comment]
That doc page is not maintained. Read this one: https://github.com/chrislusf/weed-fs/wiki/Getting-Started

However, its content is outdated too. We switched to use "progrium/busybox" by default, which uses the latest release and its docker image size is much smaller.

https://github.com/chrislusf/weed-fs/blob/master/Dockerfile

There is also one docker file for building the latest:
https://github.com/chrislusf/weed-fs/blob/master/Dockerfile.go_build

Please help to adjust the docs.

**Comment by chrislusf** [comment]
@forrestsun Could you please help to update this page about the docker image?
 https://github.com/chrislusf/weed-fs/wiki/Getting-Started

**Comment by carmark** [comment]
I am working on the development based on docker, so I can try to update that docker file if @forrestsun is busy.

**Comment by chrislusf** [comment]
@carmark please go ahead. Thanks!

**Comment by carmark** [comment]
@chrislusf sure

**Comment by carmark** [comment]
@chrislusf please review the push request:#138.

I updated the Dockerfile, and modified the wiki page later.

**Comment by chrislusf** [comment]
Seems docker file is fine now.
