### ISSUE TITLE
How do I create an empty directory?

### ISSUE THREAD

**Issue by jamminbean** [chrislusf/seaweedfs#1161]
This is what I tried:

curl -X PUT "http://localhost:8888/test/"
=> {"error":"can not to write to folder /test/ without a file name"}

curl -X POST "http://localhost:8888/test/"
=> {"error":"request Content-Type isn't multipart/form-data"}

curl -X PUT "http://localhost:8888/test"
=> creates a 0 byte file

curl -X POST "http://localhost:8888/test"
=> {"error":"request Content-Type isn't multipart/form-data"}

**Comment by chrislusf** [comment]
currently not possible.

**Comment by chrislusf** [comment]
Added a commit to support 

```
curl -X POST "http://localhost:8888/test/"
```
