### ISSUE TITLE
docker arm

### ISSUE THREAD

**Issue by ZhaoRd** [chrislusf/seaweedfs#1162]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

example of a good issue report:
https://github.com/chrislusf/seaweedfs/issues/1005
example of a bad issue report:
https://github.com/chrislusf/seaweedfs/issues/1008

**Describe the bug**
使用华为的鲲鹏系统，CPU架构是ARM，运行docker镜像，报错信息：exec  user process caused "exec format error"

**Expected behavior**
exec  user process caused "exec format error"

**Comment by chrislusf** [comment]
use `docker pull chrislusf/seaweedfs:dev`
