### ISSUE TITLE
filer 文件丢失的问题

### ISSUE THREAD

**Issue by 330570902** [chrislusf/seaweedfs#1163]
我用Filer存放了一些图片，今天发现个 别图片返回 404 ，使用的是Cassandra 存储元数据，在Cassandra中可以查到记录。
怎样通过filemeta表中的 meta 字段内容 找出 这个文件存在那个Volume中 ，或者 怎样找出这个问题的原因？

**Comment by chrislusf** [comment]
I added a shell command `fs.meta.cat` to print out the meta data content.

To see why the file is not found, maybe start volume server by `weed -v=4 volume ...` and find something relevant.
