### ISSUE TITLE
weed/server/filer_grpc_server.go's ListEntries() not streaming multiple entries, only last

### ISSUE THREAD

**Issue by payton109** [chrislusf/seaweedfs#1164]
I've been using "weed filer" successfully and now I'm beginning to use gRPC interface instead of the HTTP interface (which I can successfully list, create, read, update, and delete files). I have already created a few files in my weed filer, and I can see them listed (screenshot below), but using both BloomRPC and grpcurl as gRPC clients (using filer_pb.proto for both) only displays one file. 
Shouldn't ListEntries() be streaming all of the files and directories the requested directory contains instead of just the last entry?

Filer:
![Filer](https://user-images.githubusercontent.com/1459904/71285574-7f0bb780-2333-11ea-98c0-9b2840a8e294.png)

BloomRPC:
![BloomRPC](https://user-images.githubusercontent.com/1459904/71285662-c2febc80-2333-11ea-8f41-5f22b297d7c1.png)

gRPCurl:
```
./grpcurl -d @ -plaintext -proto seaweedfs-filer.proto 0.0.0.0:18888 filer_pb.SeaweedFiler/ListEntries << EOM
> {
>   "directory": "/",
>   "prefix": "",
>   "startFromFileName": "",
>   "inclusiveStartFrom": false,
>   "limit": 100
> }
> EOM
{
  "entry": {
    "name": "krfozm7oMio",
    "isDirectory": true,
    "attributes": {
      "mtime": "1575752442",
      "fileMode": 2147484152,
      "crtime": "1575752442"
    }
  }
}
```

**Comment by chrislusf** [comment]
need to know the version

Since 1.46, the listing has changed to streaming.

**Comment by chrislusf** [comment]
btw: the ListEntries() is used in several places without issues. For example, directory listing in FUSE mode, or `fs.ls` in `weed shell`. So I am sure this is working fine. Very likely the tools are not working in a streaming way.

**Comment by payton109** [comment]
I was running 1.45, but streaming works now that I've upgraded to 1.47.
Thanks.

**Comment by chrislusf** [comment]
Cool! Somehow I could not get BloomRPC to work on my laptop.
<img width="1049" alt="Screen Shot 2019-12-20 at 8 40 01 PM" src="https://user-images.githubusercontent.com/1543151/71303117-235c2100-2369-11ea-9b9c-709b944c32de.png">
