### ISSUE TITLE
I added a new volume,but no new volumeid in it, and also have no data in it

### ISSUE THREAD

**Issue by Mikcal** [chrislusf/seaweedfs#1174]
Hi chris,
I have 3 volumes before,  I add a new volume, but no new volumeid in it, and also have no data in it
How should i add new volumeid in new volume? I use volume.balance to solve it ,but it also have no data and new volumeid.
thx.

> volume.list
Topology volume:6/28 active:6 free:22 volumeSizeLimit:30000 MB
  DataCenter DefaultDataCenter volume:6/28 active:6 free:22
    Rack DefaultRack volume:6/28 active:6 free:22
      DataNode 127.0.0.1:8332 volume:2/7 active:2 free:5
        volume id:1 size:8 version:3 modified_at_second:1577341331  
        volume id:4 size:3261464 file_count:3 version:3 modified_at_second:1577349897  
      DataNode 127.0.0.1:8332 total size:3261472 file_count:3 
      DataNode 127.0.0.1:8333 volume:3/7 active:3 free:4
        volume id:2 size:8 version:3 modified_at_second:1577341331  
        volume id:3 size:8 version:3 modified_at_second:1577341331  
        volume id:5 size:8 version:3 modified_at_second:1577341331  
      DataNode 127.0.0.1:8333 total size:24 file_count:0 
      DataNode 127.0.0.1:8334 volume:1/7 active:1 free:6
        volume id:6 size:8 version:3 modified_at_second:1577432087  
      DataNode 127.0.0.1:8334 total size:8 file_count:0 
      DataNode 127.0.0.1:8338 volume:0/7 active:0 free:7
      DataNode 127.0.0.1:8338 total size:0 file_count:0 
    Rack DefaultRack total size:3261504 file_count:3 
  DataCenter DefaultDataCenter total size:3261504 file_count:3 
total size:3261504 file_count:3 
> volume.balance
moving volume 2 127.0.0.1:8333 => 127.0.0.1:8338
> volume.list
Topology volume:6/28 active:6 free:22 volumeSizeLimit:30000 MB
  DataCenter DefaultDataCenter volume:6/28 active:6 free:22
    Rack DefaultRack volume:6/28 active:6 free:22
      DataNode 127.0.0.1:8332 volume:2/7 active:2 free:5
        volume id:1 size:8 version:3 modified_at_second:1577341331  
        volume id:4 size:3261464 file_count:3 version:3 modified_at_second:1577349897  
      DataNode 127.0.0.1:8332 total size:3261472 file_count:3 
      DataNode 127.0.0.1:8333 volume:3/7 active:3 free:4
        volume id:2 size:8 version:3 modified_at_second:1577341331  
        volume id:3 size:8 version:3 modified_at_second:1577341331  
        volume id:5 size:8 version:3 modified_at_second:1577341331  
      DataNode 127.0.0.1:8333 total size:24 file_count:0 
      DataNode 127.0.0.1:8334 volume:1/7 active:1 free:6
        volume id:6 size:8 version:3 modified_at_second:1577432087  
      DataNode 127.0.0.1:8334 total size:8 file_count:0 
      DataNode 127.0.0.1:8338 volume:0/7 active:0 free:7
      DataNode 127.0.0.1:8338 total size:0 file_count:0 
    Rack DefaultRack total size:3261504 file_count:3 
  DataCenter DefaultDataCenter total size:3261504 file_count:3 
total size:3261504 file_count:3

**Comment by chrislusf** [comment]
`volume.balance -force`
