### ISSUE TITLE
cannot load filer metadata

### ISSUE THREAD

**Issue by howardlau1999** [chrislusf/seaweedfs#1175]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

example of a good issue report:
https://github.com/chrislusf/seaweedfs/issues/1005
example of a bad issue report:
https://github.com/chrislusf/seaweedfs/issues/1008

**Describe the bug**
First I dumped metadata using `fs.meta.save` and it succeeded:
```text
> fs.meta.save

total 955197 directories, 1120586 files
meta data for http://localhost:8888/ is saved to localhost-8888-20191230-002225.meta
```
When using `fs.meta.load` to recover the same metadata, an error occurred: `error: proto: filer_pb.FullEntry: illegal tag 0 (wire type 0)`

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
```bash
weed master
weed filer -master localhost:9333
weed volume -max 10 -mserver localhost:9333 -port 9830
weed volume -max 10 -mserver localhost:9333 -port 9831
weed volume -max 10 -mserver localhost:9333 -port 9832
weed volume -max 10 -mserver localhost:9333 -port 9833
```
- OS version
```text
Ubuntu 18.04.3 LTS (GNU/Linux 4.4.0-159-generic x86_64)
```
- output of `weed version`
```text
# weed version
version 30GB 1.47 linux amd64
```
- if using filer, show the content of `filer.toml`
```toml
[leveldb2]
enabled = true
dir = "/data"
```

**Expected behavior**
There should be no errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/5250490/71564593-495a9180-2ade-11ea-9c8f-d99b50152135.png)

**Additional context**

**Comment by howardlau1999** [comment]
Thanks @chrislusf ! Will you release a new Docker image soon or need I build one myself

**Comment by howardlau1999** [comment]
@chrislusf Unfortunately, I downloaded the latest docker image and the same error occurred

**Comment by chrislusf** [comment]
need to use `docker pull chrislusf/seaweedfs:dev` or build from git tip.

**Comment by howardlau1999** [comment]
@chrislusf the dev image will panic:
```text
panic: /debug/requests is already registered. You may have two independent copies of golang.org/x/net/trace in your binary, trying to maintain separate state. This may involve a vendored copy of golang.org/x/net/trace.

goroutine 1 [running]:
go.etcd.io/etcd/vendor/golang.org/x/net/trace.init.0()
        /go/src/go.etcd.io/etcd/vendor/golang.org/x/net/trace/trace.go:123 +0x1cd
```

I chose to build one binary myself. Can you please check what's going wrong with the dev image?

I just pulled the image and `docker run` it
