### ISSUE TITLE
backward compatibility - change behavior

### ISSUE THREAD

**Issue by LazyDBA247-Anyvision** [chrislusf/seaweedfs#1176]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

on commit: bbb6ebc3c024e8f2992ba8ad4eb3426364e70566 
you add/changed the weed/filer2/filer_delete_entry.go
which now implements doBatchDeleteFolderMetaAndData
in the code you now check for isRecursive and have an Exception/error that disallow deletion of a folder, that code is being used by the s3api deleteObject (i know that the s3 shouldn't allow, same as yours now), but up till 1.44 we could delete s3 object and the filer would delete the folder content, so it is a breaking change on the code.

can we add some flag/parameter to the filer cmd args so isRecusive is true by default, because we can't set anything through the s3 api?

Thanks for your hard work!

**Comment by chrislusf** [comment]
how about if the url has a trailing "/", it will be default to `recursive=true`?
`
curl -X DELETE http://localhost:8888/path/to/  // default recursive=true
`

**Comment by LazyDBA247-Anyvision** [comment]
nice idea, but the issue is not with the filer HTTP endpoint,
the issue is with s3api deleteObject that we can't change or send the trailing '/'
so need some way to control the isRecursive without changing the uri.
