### ISSUE TITLE
[question] failed one of multi hdd - latest docker deployment

### ISSUE THREAD

**Issue by eleaner** [chrislusf/seaweedfs#1177]
I am not sure if it is a bug.
my use-case is following: 

multiple hdd mounted in /disks; respectively /disks/0, disks/1 etc
docker container is started with option server and `-master.dir=/data `
and with 
`-dir='/disks/0/seaweedfs,/disks/1/seaweedfs,/disks/2/seaweedfs,/disks/3/seaweedfs'`

the idea is that if HDD fails to mount the respective `seaweedfs` folder will not exist and seaweed won't start filling my root volume

in-container /data is bound to a local volume while /disks is bound to host /disks

unfortunately if `/disks/0/seaweedfs` does not exist, the container will refuse to start with message 
`F0107 13:13:08     1 volume.go:115] Check Data Folder(-dir) Writable /disks/0/seaweedfs : stat /disks/0/seaweedfs: no such file or directory`

subsequently, when  `/disks/0/seaweedfs` becomes available it will complain about the next missing one etc.

This means that I cannot start the volume server if one of many HDD fails to mount.
I ould much more prefer that I lose only one HDD instead of losing four

**Comment by chrislusf** [comment]
You can run one volume server for each folder.

**Comment by eleaner** [comment]
yes, I can,
but I assume they will not know that they are on one physical machine. 

How can I then prevent having all three replicas on one physical server?

**Comment by chrislusf** [comment]
you can think they are on the same rack, and use 020 for 3 replicas.
