### ISSUE TITLE
RemoteAddr in GUI Topology shows 127.0.0.1

### ISSUE THREAD

**Issue by eleaner** [chrislusf/seaweedfs#1178]
Docker deployment, version 1.49
three-master set up on the host network
now trying to connect volume servers and I see 127.0.0.1 in topology
the only context they could be considered local is that they sit on the same physical machine as one of the master servers

I would expect to see the real IP of the volume server. 127.0.0.1 won't be accessible by any client.

![image](https://user-images.githubusercontent.com/5169203/72005228-09657e00-3245-11ea-9128-f1376bfff340.png)

all volume servers you see are on the same physical machine (but I don't think it matters, I have the same with only one volume server)
each volume is started with those parameters (varying port and storage)
`volume -port 8980 -max 10 -rack=zinc -ip 192.168.1.35 -ip.bind '0.0.0.0' -dir /disk/seaweedfs -index leveldb -mserver 192.168.1.39:9333,192.168.1.35:9333,192.168.1.36:9333`

masters are run like that (varying IP)
`master -defaultReplication=020 -ip=192.168.1.36 -ip.bind='0.0.0.0' -mdir=/data -peers='192.168.1.39:9333,192.168.1.35:9333,192.168.1.36:9333'`

**Comment by chrislusf** [comment]
Use -ip.public

**Comment by eleaner** [comment]
flag provided but not defined: -ip.public

**Comment by eleaner** [comment]
@chrislusf 

it works perfectly fine without docker
weird

**Comment by eleaner** [comment]
@chrislusf 
I think something is wrong with your docker image 
I downloaded weed to an alpine container on the host network and works like a dream

**Comment by eleaner** [comment]
@chrislusf 

it's line 15 of entrypoint.sh
 `ARGS="-ip `hostname -i` -dir /data"`

On my machine, I have my hostname defined as 127.0.0.1 in /etc/hosts too (I am not sure if it is wrong) 

in line 20 this value supersedes the value I gave in my list of parameters
`exec /usr/bin/weed $@ $ARGS`
so efectively I run my command with second -ip flag
`volume -port 8980 -max 10 -rack=zinc -ip 192.168.1.35 -ip.bind '0.0.0.0' -dir /disk/seaweedfs -index leveldb -mserver 192.168.1.39:9333,192.168.1.35:9333,192.168.1.36:9333 -ip 127.0.0.1`
without even knowing it

I can easily go around it by redefining an entrypoint
