### ISSUE TITLE
General filer config find a unleagal character.

### ISSUE THREAD

**Issue by zhiyoucai** [chrislusf/seaweedfs#1181]
**Describe the bug**

When I use this command to general a filer config file:

```bash
weed scaffold filer -output=""
```

I find that there is something wrong in line 95:

![image](https://user-images.githubusercontent.com/16997921/72232409-fd3e3f80-35fb-11ea-94fa-d1eceea9106b.png)

"//" is not a leagal comment character, please replace it with "#".

**Comment by chrislusf** [comment]
thanks!
