### ISSUE TITLE
Suitability questions

### ISSUE THREAD

**Issue by stdex** [chrislusf/seaweedfs#1185]
I have 250K media files (max file size = 20mb), total disk volume 2TB.
Now I getting close to raw file storage limit. In this regard, I would like to try distributed file system.

I think the closest thing that might suit to me is - https://github.com/alibaba/tfs (Also this have nginx module for load balance - https://github.com/alibaba/nginx-tfs)
But this project is no longer supported and has very poor documentation.

What are the key points about seaweedfs that interest to me:
1) Is seaweedfs good for me if I don't need any files meta information and replication (need only distributed files by disks/servers and load balance)?
2) Each volume has size = 32GB. I should monitor free space in volume and create new volumes manually or this process should happen automatically?
3) Can I allocate wholly file in volume? In this case I should check free space in volume manually?
4) All file meta information stored in memory, but duplicate on disk? How to calculate the required amount of memory? What overhead on disk space I will receive by storing this information?
5) If I need backup all volmes in cluster, what I should do? How to calculate required free disk space? 
6) If something goes wrong in migration, can I get back all the files in raw from volumes? How long does it take?

**Comment by chrislusf** [comment]
There are simply too many questions here. I think you can try it out first. It should be faster than writing these detailed questions. :) TFS is too complicated.

Basically the file data is stored in volume servers, and file metadata is stored in leveldb or some common data store, https://github.com/chrislusf/seaweedfs/wiki/Filer-Stores.

The volume files can be moved around. The file metadata can also be exported and imported.
