### ISSUE TITLE
Filer backend password in filer.toml

### ISSUE THREAD

**Issue by LazyDBA247-Anyvision** [chrislusf/seaweedfs#1188]
Hi Chris,
saving the DB passwords in the filer.toml (mysql/postgres/etc...)
is not secure and in k8s implementation a little bit problematic to override in the configmap.

I saw  that [viper supports ENV](https://github.com/spf13/viper#working-with-environment-variables)
because my go skills are no-go :), would it be possible to add an ENV like 'SEAWEED_FILER_DB_PASSWORD' that will override the password field in the filer.toml in all DB backend implementation...

that would be a great feature/enabler for working with seaweed in k8s without overriding the "default" entry-point / writing specific init container to override the "filer.toml" from a k8s secret.

10x!

**Comment by chrislusf** [comment]
Great suggestion! Btw: The password settings are different for each filer
store. Which store you want to use?

**Comment by LazyDBA247-Anyvision** [comment]
Mysql (memsql) but probably postgresql is also compatible...

**Comment by chrislusf** [comment]
added fix in d335f04de6861b571190c13bd7d65e9a0c02f187

**Comment by LazyDBA247-Anyvision** [comment]
Amazing!

**Comment by chrislusf** [comment]
Maybe you can help by adding some Kubernetes examples to this repo?

**Comment by LazyDBA247-Anyvision** [comment]
Sure!, 
probably next week will make time to make a PR
