### ISSUE TITLE
weed shell should allow changing volume replication level

### ISSUE THREAD

**Issue by Radtoo** [chrislusf/seaweedfs#1192]
Since volume replication level is assigned at  volume creation, it would be good if it could be later manipulated through weed shell so replication levels can be increased / decreased on demand. Ideally, this would also be possible for erasure coded volumes.

Alternatively, there should be some other documented method to change replication/erasure coding levels indirectly in bulk on the files themselves by URL (even with JWT enabled, this seems to not have documentation) and through weed filer or weed shell fs.*.

As of seaweedfs release 1.52, this does not currently seem possible.

**Comment by chrislusf** [comment]
Added command to change a volume replication in the commit 40ae533fa34ae6e40fa31d6007e533a23391a5d8

Erasure coding level can not be dynamically changed.

Entries in the file system can not change its replication individually. Later, the replication level can be changed at a collection level ( or so called bucket as in S3).
