### ISSUE TITLE
when volume starting, the memory growth so fast that it will be killed by kernel

### ISSUE THREAD

**Issue by stlpmo-jn** [chrislusf/seaweedfs#1194]
SeaweedFS version : V1.47

when loading volumes, the volume server is killed by kernel, the reason is :
Out of memory: Kill process 18730 (volume) score 871 or sacrifice child

analysed by pprof  like this :
(pprof) top
Showing nodes accounting for 56037930.94kB, 100% of 56051868.91kB total
Dropped 171 nodes (cum <= 280259.34kB)
Showing top 10 nodes out of 19
      flat  flat%   sum%        cum   cum%
55455587.92kB 98.94% 98.94% 55455587.92kB 98.94%  github.com/chrislusf/seaweedfs/weed/storage/needle_map.NewCompactSection
581680.81kB  1.04%   100% 582432.97kB  1.04%  github.com/syndtr/goleveldb/leveldb/memdb.New
     360kB 0.00064%   100% 55456026.64kB 98.94%  github.com/chrislusf/seaweedfs/weed/storage/needle_map.(*CompactMap).Set
  218.55kB 0.00039%   100% 594111.02kB  1.06%  github.com/syndtr/goleveldb/leveldb.openDB
   32.09kB 5.7e-05%   100% 56051050.62kB   100%  github.com/chrislusf/seaweedfs/weed/storage.NewVolume
   28.19kB 5e-05%   100% 56051018.52kB   100%  github.com/chrislusf/seaweedfs/weed/storage.(*Volume).load
   11.09kB 2e-05%   100% 594872.11kB  1.06%  github.com/chrislusf/seaweedfs/weed/storage.NewLevelDbNeedleMap
    4.78kB 8.5e-06%   100% 56051058.91kB   100%  github.com/chrislusf/seaweedfs/weed/storage.(*DiskLocation).concurrentLoadingVolumes.func2
    4.44kB 7.9e-06%   100% 582437.41kB  1.04%  github.com/syndtr/goleveldb/leveldb.(*DB).mpoolGet
    3.06kB 5.5e-06%   100% 56051054.13kB   100%  github.com/chrislusf/seaweedfs/weed/storage.(*DiskLocation).loadExistingVolume

the problem looks like in github.com/chrislusf/seaweedfs/weed/storage/needle_map.NewCompactSection.

from volume.log，i find the flow is ：
(1), the volume server is loading existing volumes, Volume.load() in file volume_loading.go
(2), when check index file failed with function CheckVolumeDataIntegrity(), te var noWriteOrDelete set to true
(3), generate sdx file with function NewSortedFileNeedleMap()

in the function NewSortedFileNeedleMap(), the CompactMap will be used, the massive memory is used by needle_map.NewCompactSection

[memprofile.zip](https://github.com/chrislusf/seaweedfs/files/4157257/memprofile.zip)

**Comment by chrislusf** [comment]
what is the index type when starting the volume server?

**Comment by chrislusf** [comment]
I do not have the exact weed binary file. Could you please export the pprof mem info into an svg file? Just do `svg > some_name.svg` in go tool pprof

**Comment by chrislusf** [comment]
found the problem. Thanks for the detailed report!
