### ISSUE TITLE
Return HTTP 204 instead of 304 when file not changed on volume PUT

### ISSUE THREAD

**Issue by filiphanes** [chrislusf/seaweedfs#1196]
When making HTTP PUT request to volume server to already existing fid and sending the same file content, volume server returns status code 304 Not Modified,
but maybe it should return 204 No Content.

From https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/304
> It is an implicit redirection to a cached resource. This happens when the request method is safe, like a GET or a HEAD request, ...

As written in https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204
> The common use case is to return 204 as a result of a PUT request, updating a resource, without changing the current content of the page displayed to the user.

Is this behaviour similiar to other existing storage system?

I am aware that this change could cause compatibility issues with old clients.

**Comment by chrislusf** [comment]
Looks good! Will do.
