### ISSUE TITLE
deleting a folder through filer api does not delete files from the volume server

### ISSUE THREAD

**Issue by ignusws** [chrislusf/seaweedfs#1197]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**
Simple setup
docker-compose up -d
weed filer.copy /home/Downloads/files/test http://172.18.0.18:8888/
curl -X DELETE http://172.18.0.18:8888/test?recursive=true

Folder and files was deleted from the filer-server but remained on the volume-server. Deleting single file through filer api removes file from volume-server, deleting folder through weed mount also correctly removes files from volume-server

ALSO
if weed filer.copy executed twice on same folder than old files with same path wont be deleted from volume server

**System Setup**
- The default docker-compose setup from here: [docker/seaweedfs-compose.yml](https://github.com/chrislusf/seaweedfs/blob/master/docker/seaweedfs-compose.yml)
- OS version Linux Mint 19.2
- output of `weed version` version 30GB 1.53 linux amd64

**Expected behavior**
Files and folders should be deleted from volume-server on api call

**Comment by chrislusf** [comment]
How do you check the file is not deleted from the volume servers? There are a few seconds delay of actually deleting the file chunks from the volume server.

**Comment by chrislusf** [comment]
can not reproduce.

**Comment by ignusws** [comment]
> How do you check the file is not deleted from the volume servers?

![2020-02-12_13-47](https://user-images.githubusercontent.com/53160543/74309928-85039f00-4d9e-11ea-8e86-ce76df98bd6c.png)
through webui, trash shows zeros on all volumes

**Comment by chrislusf** [comment]
Thanks for the report! Found the first problem. The second problem is not reproducible though.
