### ISSUE TITLE
How to migrate image data using redis for caching

### ISSUE THREAD

**Issue by lostmem** [chrislusf/seaweedfs#1199]
Hello, I used redis as the filer cache, and now I have deployed three nodes as a cluster. How can I migrate the current architecture? I have checked that redis stores the hexadecimal value of the path, but how can I migrate the data in redis to the image?This makes me feel confused, please answer it, thank you
Ps:
This model doesn't use redis so I'm not sure I can do that
https://github.com/chrislusf/seaweedfs/wiki/Async-Replication-to-another-Filer

**Comment by chrislusf** [comment]
There are no such thing called filer cache.

**Comment by chrislusf** [comment]
For meta data migration, see https://github.com/chrislusf/seaweedfs/wiki/Filer-Stores#switching-between-different-stores

The non-meta data can be migrated by copying the volume files.
