### ISSUE TITLE
how to get back volumeid 6

### ISSUE THREAD

**Issue by huzhixiang** [chrislusf/seaweedfs#1204]
"writables": [
          22,
          13,
          23,
          12,
          21,
          10,
          8,
          9,
          24,
          11
        ]
      }
    ]
  },
  "Version": "30GB 1.41"
}[root@localhost app]# 
[root@localhost app]# 
[root@localhost app]# curl http://localhost:9333/dir/lookup?volumeId=6
{"volumeId":"6","error":"volumeId 6 not found."}[root@localhost app]# 
[root@localhost app]# 
[root@localhost app]# 
[root@localhost app]# 
[root@localhost app]# 
[root@localhost app]# curl http://localhost:9333/dir/lookup?volumeId=22
{"volumeId":"22","locations":[{"url":"10.15.2.41:8081","publicUrl":"10.15.2.41:8081"},{"url":"10.15.2.42:8081","publicUrl":"10.15.2.42:8081"}]}[root@localhost app]# 

a old file used volumeid 6 fileid is (6,0ebd8e709e21),now I can't find the volumeid 6 ,
there is only 22,13,23,12,21,10,8,9,24,11 how can I get back volumeid 6 to find my uploaded file

**Comment by chrislusf** [comment]
seems you deleted those volumes.

**Comment by huzhixiang** [comment]
> seems you deleted those volumes.

I just restart the master server and volumes server,after doing this I can not find the volumeid 6,could you tell me how to deal with this problem,to get back volumeid 6 or find ways to avoid this happen again,thank you.

**Comment by chrislusf** [comment]
How to reproduce this?

**Comment by huzhixiang** [comment]
I had killed the master server and volume server process in linux by command kill -9 xxxxxx.,then use the command to start master and volume server:
**nohup /usr/local/seaweedfs/weed master -port=9333 -mdir=/usr/local/seaweedfs/f1 -ip=10.15.2.41 -peers=10.15.2.41:9333,10.15.2.42:9333,10.15.2.43:9333 -defaultReplication=001 > /usr/local/seaweedfs/seaweedfs.log &
nohup /usr/local/seaweedfs/weed master -port=9333 -mdir=/usr/local/seaweedfs/f2 -ip=10.15.2.42 -peers=10.15.2.41:9333,10.15.2.42:9333,10.15.2.43:9333 -defaultReplication=001 > /usr/local/seaweedfs/seaweedfs.log &
nohup /usr/local/seaweedfs/weed master -port=9333 -mdir=/usr/local/seaweedfs/f3 -ip=10.15.2.43 -peers=10.15.2.41:9333,10.15.2.42:9333,10.15.2.43:9333 -defaultReplication=001 > /usr/local/seaweedfs/seaweedfs.log &
# now start the volume servers, specifying any one of the master server
nohup /usr/local/seaweedfs/weed volume -dir=/usr/local/seaweedfs/fv1 -ip=10.15.2.41 -port=8081 -mserver=10.15.2.41:9333,10.15.2.42:9333,10.15.2.43:9333 -dataCenter=dc1 -rack=rack1 > /usr/local/seaweedfs/seaweedfs.log &
nohup /usr/local/seaweedfs/weed volume -dir=/usr/local/seaweedfs/fv2 -ip=10.15.2.42 -port=8081 -mserver=10.15.2.41:9333,10.15.2.42:9333,10.15.2.43:9333 -dataCenter=dc1 -rack=rack1 > /usr/local/seaweedfs/seaweedfs.log &
nohup /usr/local/seaweedfs/weed volume -dir=/usr/local/seaweedfs/fv3 -ip=10.15.2.43 -port=8081 -mserver=10.15.2.41:9333,10.15.2.42:9333,10.15.2.43:9333 -dataCenter=dc1 -rack=rack1 > /usr/local/seaweedfs/seaweedfs.log &**

and I found that I lost the volume id which there was.did I operate wrong or illegal？ please give me some clues ,thanks.

**Comment by huzhixiang** [comment]
I had killed the master server and volume server process in linux by command kill -9 xxxxxx.,then use the command to start master and volume server:
-----------------------------------------
nohup /usr/local/seaweedfs/weed master -port=9333 -mdir=/usr/local/seaweedfs/f1 -ip=10.15.2.41 -peers=10.15.2.41:9333,10.15.2.42:9333,10.15.2.43:9333 -defaultReplication=001 > /usr/local/seaweedfs/seaweedfs.log &

nohup /usr/local/seaweedfs/weed master -port=9333 -mdir=/usr/local/seaweedfs/f2 -ip=10.15.2.42 -peers=10.15.2.41:9333,10.15.2.42:9333,10.15.2.43:9333 -defaultReplication=001 > /usr/local/seaweedfs/seaweedfs.log &

nohup /usr/local/seaweedfs/weed master -port=9333 -mdir=/usr/local/seaweedfs/f3 -ip=10.15.2.43 -peers=10.15.2.41:9333,10.15.2.42:9333,10.15.2.43:9333 -defaultReplication=001 > /usr/local/seaweedfs/seaweedfs.log &
-------now start the volume servers
nohup /usr/local/seaweedfs/weed volume -dir=/usr/local/seaweedfs/fv1 -ip=10.15.2.41 -port=8081 -mserver=10.15.2.41:9333,10.15.2.42:9333,10.15.2.43:9333 -dataCenter=dc1 -rack=rack1 > /usr/local/seaweedfs/seaweedfs.log &

nohup /usr/local/seaweedfs/weed volume -dir=/usr/local/seaweedfs/fv2 -ip=10.15.2.42 -port=8081 -mserver=10.15.2.41:9333,10.15.2.42:9333,10.15.2.43:9333 -dataCenter=dc1 -rack=rack1 > /usr/local/seaweedfs/seaweedfs.log &

nohup /usr/local/seaweedfs/weed volume -dir=/usr/local/seaweedfs/fv3 -ip=10.15.2.43 -port=8081 -mserver=10.15.2.41:9333,10.15.2.42:9333,10.15.2.43:9333 -dataCenter=dc1 -rack=rack1 > /usr/local/seaweedfs/seaweedfs.log &
-----------------------------------------
and I found that I lost the volume id which there was.did I operate wrong or illegal？ please give me some clues ,thanks.

**Comment by chrislusf** [comment]
Use "kill" for a proper shutdown, not "kill -9"
I think you need to learn what is the difference between "kill -9" and "kill".

**Comment by huzhixiang** [comment]
I will try, thank you
