### ISSUE TITLE
how to integrate existing data into a different machine?

### ISSUE THREAD

**Issue by jyjyj** [chrislusf/seaweedfs#1205]
Hi, I would like to move all my data from one VM (my seaweedfs instances are running on separate VMs) to another VM, while still being able to access all the data originally on the destination VM. Both have Filer, and I would like to access in the same way as before (filer_ip:filer_port/filename) on the destination VM. 

I have seen https://github.com/chrislusf/seaweedfs/issues/539, but am not sure it is applicable as I think it would overwrite the existing data in the 2nd VM?

For advice please, thanks!

**Comment by chrislusf** [comment]
If the filer does not change, just moving the volume files would be fine.
