### ISSUE TITLE
Leader in a cluster doesn't get full volumes layout after election.

### ISSUE THREAD

**Issue by eryx67** [chrislusf/seaweedfs#1209]
We have a cluster of three hosts, `192.168.10. [1,2,3]`.
Masters are started on every host.
After restart we found the situation when elected leader, `2`
knows only about volumes created after its start.

**Full picture**

Masters `1` and `3` were started at first and `3` became a leader.
Master `2` was started in few seconds and was elected as a leader
but knew nothing about existing volumes. For example the volume `2`
while masters `1` and `3` knew about it.

After restart of master `2` master `1` became a leader and full
layout picture was restored.

In attachments:

* log-start-sd-1.txt, log of master `1` at the moment which cause the situation
* log-start-sd-2.txt, log of master `2` at the moment which cause the situation
* log-start-sd-3.txt, log of master `3` at the moment which cause the situation
* status-with-m2-leader.txt, wrong layout when leader was master `2`
* status-without-m2-leader.txt, right layout when master `2` was switched off and
  master `1` became the leader
* volume-2-lookup-m1.txt, master `1` and `3` know about volume `2`,
  when master `2` is the leader and knows nothing about one
* volume-2-lookup-m2.txt, master `2` is the leader and knows nothing about volume `2`
[log-start-sd-1.txt](https://github.com/chrislusf/seaweedfs/files/4249317/log-start-sd-1.txt)
[log-start-sd-2.txt](https://github.com/chrislusf/seaweedfs/files/4249318/log-start-sd-2.txt)
[log-start-sd-3.txt](https://github.com/chrislusf/seaweedfs/files/4249319/log-start-sd-3.txt)
[status-with-m2-leader.txt](https://github.com/chrislusf/seaweedfs/files/4249320/status-with-m2-leader.txt)
[status-without-m2-leader.txt](https://github.com/chrislusf/seaweedfs/files/4249321/status-without-m2-leader.txt)
[volume-2-lookup-m1.txt](https://github.com/chrislusf/seaweedfs/files/4249322/volume-2-lookup-m1.txt)
[volume-2-lookup-m2.txt](https://github.com/chrislusf/seaweedfs/files/4249323/volume-2-lookup-m2.txt)

**Comment by chrislusf** [comment]
What's the command to start masters? Are the pulseSeconds settings consistent?

**Comment by eryx67** [comment]
All masters are started with similar command:
```
/bin/weed -v 0 -volumeSizeLimitMB=30000 -defaultReplication=011 -pulseSeconds=20 -mdir=/data/swfs/master -ip=192.168.10.1 -port=9333 -peers=192.168.10.1:9333,192.168.10.2:9333,192.168.10.3:9333
```
Volumes:
```
/bin/weed -v 0 volume -index=leveldbMedium -dataCenter=dc1 -rack=rack1 -pulseSeconds=5 -dir=/data/swfs/volume2 -max=100 -ip=192.168.10.1 -port=8082 -port.public=8182 -publicUrl=http://192.168.10.1:8182 -mserver=192.168.10.1:9333,192.168.10.2:9333,192.168.10.3:9333
```

**Comment by chrislusf** [comment]
The logs showed there is a network problem between server 2 and server 3 around 0219 09:39:50.

When are the status were fetched? I want to know whether this happened quickly, or it has been in the wrong state for a long period of time.

**Comment by eryx67** [comment]
> When are the status were fetched? I want to know whether this happened quickly, or it has been in 
> the wrong state for a long period of time.
It was a very short glitch less than 5 seconds. 
GlusterFS on the same hosts, which we are trying to replace with SeaweedFS just didn't note it.

**Comment by chrislusf** [comment]
Seems you increased the pulseSeconds to 20. 

The default value, 5 seconds are for internet, and can take a few seconds for the system to settle down. You can try to reduce pulseSeconds even lower for faster recovery.

**Comment by eryx67** [comment]
But the system remained in this wrong state for 5 days after before we noted it.
There were no net splits or crashes for that period.
So I guess the problem is not in `pulseSeconds`

**Comment by chrislusf** [comment]
could I have the full logs for the 3 master servers?

**Comment by eryx67** [comment]
Yes, I'll send them asap.

But just now we got the same situation without any connection errors between masters.
Leader was `192.168.10.1` and it wasn't changed for few days.
Without any indication it forgot about some volumes.
After restarting the leader new leader became `192.168.10.3` and picture restored.
I used little script to monitor leader's state.
Here is a log:
```
$ swfs_check check_volumes_topology check_leader_brains
volume server's list of volumes is different from leader's one [40, 41, 42, 46, 47, 48]

$ curl http://localhost:9333/dir/lookup?volumeId=42
{"volumeId":"42","error":"volume id 42 not found"}

$ curl http://localhost:9333/dir/lookup?volumeId=46
{"volumeId":"46","error":"volume id 46 not found"}[vms@cn-bm-sd-1 swfs]$

$ sudo systemctl stop swfs-master
$ sudo systemctl start swfs-master

$ curl http://localhost:9333/dir/lookup?volumeId=46               
{"volumeId":"46","locations":[{"url":"192.168.10.3:8085","publicUrl":"http://10.62.30.137:8185"},{"url":"192.168.10.3:8082","publicUrl":"http://10.62.30.137:8182"},{"url":"192.168.10.2:8086","publicUrl":"http://10.62.30.136:8186"}]}$

$ swfs_check check_volumes_topology check_leader_brains

$ curl http://localhost:9333/cluster/status
{"Leader":"192.168.10.3:9333","Peers":["192.168.10.3:9333","192.168.10.2:9333"]}$

$ curl http://localhost:9333/dir/lookup?volumeId=40
{"volumeId":"40","locations":[{"url":"192.168.10.2:8081","publicUrl":"http://10.62.30.136:8181"},{"url":"192.168.10.1:8085","publicUrl":"http://10.62.30.135:8185"},{"url":"192.168.10.1:8081","publicUrl":"http://10.62.30.135:8181"}]}$

$ swfs_check check_volumes_topology check_leader_brains

```

**Comment by chrislusf** [comment]
there are hard coded timeouts https://github.com/chrislusf/seaweedfs/blob/master/weed/util/grpc_client_server.go#L50

Please just use the default pulseSeconds settings.

**Comment by chrislusf** [comment]
Closing since no more updates.
