### ISSUE TITLE
With replication 011 and compression one of replicas is always written uncompressed

### ISSUE THREAD

**Issue by eryx67** [chrislusf/seaweedfs#1212]
We are working with replication mode `011`.
We write `wav` files to `SeaweedFS` v1.56
As we can see two replicas are written with compression and one always without compression.

Here is a list of some volumes in format
`Rack` `File size` `File Name`
```
sd-2 2G /data/swfs/sdf/volume/MAIL_20200228_181.dat
sd-3 2G /data/swfs/sda/volume/MAIL_20200228_181.dat
sd-3 5G /data/swfs/sdd/volume/MAIL_20200228_181.dat

sd-1 1G /data/swfs/sdc/volume/MAIL_20200228_183.dat
sd-3 1G /data/swfs/sda/volume/MAIL_20200228_183.dat
sd-3 2G /data/swfs/sdc/volume/MAIL_20200228_183.dat

sd-1 8G /data/swfs/sdb/volume/MAIL_20200228_192.dat
sd-1 2G /data/swfs/sdc/volume/MAIL_20200228_192.dat
sd-3 2G /data/swfs/sdc/volume/MAIL_20200228_192.dat
```

**Comment by chrislusf** [comment]
Suppose the uploads go to volume server A, and then replicated to B and C.

Seems the upload to server A was not stored as gzipped.

What is your way to upload?

btw: I tried to gzip some wav file, but did not find the compression is effective. They are about the same size as original wav files.

**Comment by eryx67** [comment]
We follow the recommended way:
```
GET /dir/assign?collection=MAIL_20200302&replication=011&ttl=5d`
```
and write to returned volume `url` and `fid`.

I made some tests and it seems that `url` returned by `assign` is most time the same per volume 
and that copy of volume is always uncompressed.

You can easily see it in following log:

```bash
$ curl 'http://mail-1:9333/dir/assign?collection=MAIL_20200302&ttl=5d'
{"fid":"246,1875868a0e0301","url":"192.168.10.1:8084","publicUrl":"http://10.62.30.135:8184","count":1}
```
Volume 246:
```
192.168.10.1:8082 171M /data/swfs/sdb/volume/MAIL_20200302_246.dat
192.168.10.1:8084 383M /data/swfs/sdd/volume/MAIL_20200302_246.dat
192.168.10.3:8083 171M /data/swfs/sdc/volume/MAIL_20200302_246.dat
```
```bash
curl 'http://mail-1:9333/dir/assign?collection=MAIL_20200302&ttl=5d'
{"fid":"245,1877f724812111","url":"192.168.10.3:8083","publicUrl":"http://10.62.30.137:8183","count":1}
```

Volume 245:
```
192.168.10.1:8082 189M /data/swfs/sdb/volume/MAIL_20200302_245.dat
192.168.10.3:8083 441M /data/swfs/sdc/volume/MAIL_20200302_245.dat
192.168.10.3:8084 192M /data/swfs/sdd/volume/MAIL_20200302_245.dat
```

```bash
$ curl 'http://mail-1:9333/dir/assign?collection=MAIL_20200302&ttl=5d'
{"fid":"236,1877196e692600","url":"192.168.10.1:8086","publicUrl":"http://10.62.30.135:8186","count":1}
```

Volume 236:
```
192.168.10.1:8084 164M /data/swfs/sdd/volume/MAIL_20200302_236.dat
192.168.10.1:8086 592M /data/swfs/sdf/volume/MAIL_20200302_236.dat
192.168.10.3:8086 207M /data/swfs/sdf/volume/MAIL_20200302_236.dat
```

```bash
$ curl 'http://mail-1:9333/dir/as00302&ttl=5d'on=MAIL_2020
{"fid":"234,18772c058d5db9","url":"192.168.10.1:8084","publicUrl":"http://10.62.30.135:8184","count":1}
```

Volume 234:
```
192.168.10.1:8083 170M /data/swfs/sdc/volume/MAIL_20200302_234.dat
192.168.10.1:8084 450M /data/swfs/sdd/volume/MAIL_20200302_234.dat
192.168.10.2:8083 224M /data/swfs/sdc/volume/MAIL_20200302_234.dat
```
```

**Comment by chrislusf** [comment]
Right. It depends on how you send the http PUT or POST request. You can encode the content via gzip.

**Comment by eryx67** [comment]
It's always PUT with uncompresed `file` content and `Content-Type` = `audio/wave`

**Comment by chrislusf** [comment]
Use "POST"

**Comment by chrislusf** [comment]
I added a commit for this https://github.com/chrislusf/seaweedfs/commit/7335e6219921fd3976179f6a74ea4a2dcdc43e1e

But the easiest fix for you is to change to "POST".

For existing volumes, you can stop the volume servers and just copy the small .dat files to replace the large .dat files.
