### ISSUE TITLE
filer  不支持复制

### ISSUE THREAD

**Issue by bensq2** [chrislusf/seaweedfs#1215]
你好，我在搭建测试的时候遇到了问题：

1. server1 (192.168.8.22)
./weed master -mdir="./data" -ip=192.168.8.22 -port=9333 -defaultReplication=010 
./weed filer -master="localhost:9333" 

server2:(192.168.8.29)
./weed volume -port=8081 -dir=./data -max=100 -ip=192.168.8.29 -mserver="192.168.8.22:9333" -dataCenter=dc1 -rack=rack1
./weed volume -port=8083 -dir=./data2 -max=100 -ip=192.168.8.29 -mserver="192.168.8.22:9333" -dataCenter=dc1 -rack=rack1

server3:(192.168.8.31)
./weed volume -port=8081 -dir=./data -max=100 -ip=192.168.8.31 -mserver="192.168.8.22:9333" -dataCenter=dc1 -rack=rack2
./weed volume -port=8083 -dir=./data2 -max=100 -ip=192.168.8.31 -mserver="192.168.8.22:9333" -dataCenter=dc1 -rack=rack2

这是我在三台机器上启动时用的三个命令
如果不使用server1的filer上传，
curl -F file=@file.js 192.168.8.22:9333/submit
010复制模式没有问题，可以看到29，31服务器都能找到对应的文件

但是如果使用filer上传
curl -F file=@file.js 192.168.8.22:8888/js/file.js

只有在一台server上能找到这个文件，没有复制到其他服务器，replication没有起到作用

请问，是哪里的问题，需要通过什么办法解决filer 上传能自动复制的问题

**Comment by chrislusf** [comment]
`weed filer -defaultReplicaPlacement=010`
