### ISSUE TITLE
The ttl to redis of filer do not work

### ISSUE THREAD

**Issue by yaodd** [chrislusf/seaweedfs#1217]
Hello, I use seaweedfs as our file system. We upload files through filer with ttl, like this

`curl -F "filename=@test.txt" "http://120.131.x.xxx/documents/test/?ttl=3m&collection=test"`

after 3m later, as expected I visit the url "http://120.131.x.xxx/documents/test/test.txt". It responsed 404. But when I look for the key "/documents/test/test.txt" in the redis, found it is still there, and it has not expire time. The k-v has been removed unit I delete it forcedly by

`curl -X DELETE  "http://120.131.x.xxx/documents/test/test.txt"`

Why the k-v in the redis can not be like the data on column through the "ttl" to be removed？
Or did I do something wrong?

**Comment by chrislusf** [comment]
This is a feature not added yet. The directory listing in Redis adapter did not follow the TTL.

**Comment by chrislusf** [comment]
Added lazy deletion.

**Comment by yaodd** [comment]
I found the table in the Wiki at  Filer-Directories and Files-Filer Stores says TTL is supported in Redis as filer store，and I found you have added this feature in #821 . The source code also shows

`_, err = store.Client.Set(string(entry.FullPath), value, time.Duration(entry.TtlSec) * time.Second).Result()`

Why are you saying the feature not added yet？ I try to change the source code , then run，found the code up there has been execute normally except the value of `entry.TtlSec` is 0. So that the k-v in redis has not expire time.

Now I am confused so much，please explain to me，thank you！

**Comment by yaodd** [comment]
> This is a feature not added yet. The directory listing in Redis adapter did not follow the TTL.

I found the table in the Wiki at Filer-Directories and Files-Filer Stores says TTL is supported in Redis as filer store，and I found you have added this feature in #821 . The source code in weed/filer2/redis/universal_redis_store.go also shows

_, err = store.Client.Set(string(entry.FullPath), value, time.Duration(entry.TtlSec) * time.Second).Result()

Why are you saying the feature not added yet？ I try to change the source code , then run，found the code up there has been execute normally except the value of entry.TtlSec is 0. So that the k-v in redis has not expire time.

Now I am confused so much，please explain to me，thank you！

**Comment by chrislusf** [comment]
Please try 1.59 release.

**Comment by yaodd** [comment]
> Please try 1.59 release.

1.59 release is still not work. But I saw issues #1225 and then I compile the latest source code that you committed latterly, and it worked！

Thank you for help, both of you.
