### ISSUE TITLE
文件上传失败，但是已经占用磁盘空间

### ISSUE THREAD

**Issue by bensq2** [chrislusf/seaweedfs#1218]
问题描述：

我上传一个8G的大文件时，因为意外中断了上传，但是volume的空间已经占用，filer server下看不到这个8G的文件，请问如何把磁盘空间释放。
已经尝试的操作：
curl "http://localhost:9333/vol/vacuum”

**Comment by chrislusf** [comment]
No easy way.

You can check the logs to find out what file ids it was using, and delete those file ids.

Or scan the volume to see what are the file ids created during the time window, via "see_dat" util, https://github.com/chrislusf/seaweedfs/blob/master/unmaintained/see_dat/see_dat.go , and delete those file ids.

Or list out all file ids in the file store and list out all file ids in the volume files, and then delete those extra file ids.

**Comment by zjzdy** [comment]
一个文件的上传不应该视为一个事务吗？上传失败不应该是由filer自动删除已使用的空间吗？

**Comment by chrislusf** [comment]
Depends on how the file is uploaded. It can upload data to volume servers before notifying the filer. If it fails, the filer would not know.
