### ISSUE TITLE
Memleak while GC

### ISSUE THREAD

**Issue by ingardm** [chrislusf/seaweedfs#1222]
**Describe the bug**
Memory leak while running vacuum, maybe in combination with broken pipe errors

**System Setup**
Ubuntu xenial 3x nodes all running master and volume

/usr/local/bin/weed -logtostderr master -mdir=/mnt/data01/meta -ip=10.1.21.14 -defaultReplication=010 -volumePreallocate -volumeSizeLimitMB 30000 -pulseSeconds 10 -peers=10.1.21.14:9333,10.1.21.15:9333,10.1.21.16:9333
/usr/local/bin/weed -logtostderr -v=1 volume -compactionMBps=50 -port=8080 -mserver=10.1.21.14:9333,10.1.21.15:9333,10.1.21.16:9333 -dir=/mnt/data01/data,/mnt/data02/data -index leveldb -max 3966,3966 -ip 10.1.21.14 -rack photol-104

12:22:48 [root@photol-104[GM]:~] $ weed version
version 30GB 1.58 linux amd64

**Expected behavior**
Memory not rising indefinantly until OOM

**Screenshots**
Screenshot of memory usage graph attached

**Additional context**
Events which can be seen in the graph:
GC started ( res mem starts rising, virtual mem starts rising as well after a while )
Mar 05 08:01:04 photol-104 weed[6260]: I0305 08:01:04  6260 volume_grpc_vacuum.go:36] compact volume 9136
Mar 05 08:01:04 photol-104 weed[6260]: I0305 08:01:04  6260 volume_vacuum.go:83] Committing volume 9136 vacuuming...

Vacuuming runs without errors until: ( at this point RES mem stops increasing - virtual continues to rise )
Mar 05 13:18:26 photol-104 weed[6260]: I0305 13:18:26  6260 common.go:80] error writing JSON status 200: write tcp 127.0.1.1:8080->127.0.0.1:34220: write: broken pipe
Mar 05 13:18:26 photol-104 weed[6260]: I0305 13:18:26  6260 common.go:80] error writing JSON status 200: write tcp 127.0.1.1:8080->127.0.0.1:34218: write: broken pipe
Mar 05 13:18:26 photol-104 weed[6260]: I0305 13:18:26  6260 common.go:81] JSON content: map[Volumes:[Id:58, Size:31454853643, ReplicaPlacement:010, Collection:photo-large-prod-002, Version:2, FileCount:103572,
DeleteCount:1029, DeletedByteCount:235490316, ReadOnly:false Id:59, Size:31455012092, ReplicaPlacement:010, Collection:photo-large-prod-002, Version:2,..........

There are a few broken pipe errors which does not correcpond to any change in the graph. RES mem starts rising again at around Mar 5 23:00 without anything specific in the logs
Virtual memory has been increasing steadily throughout.

12:16:22 [root@photol-104[GM]:~] $ journalctl -u weed-volume --since "2020-03-04 00:00:00" |grep "common.go" | grep -v "JSON content"
Mar 04 05:47:50 photol-104 weed[6260]: I0304 05:47:50  6260 common.go:80] error writing JSON status 200: write tcp 10.1.21.14:8080->10.244.18.63:53190: write: broken pipe
Mar 04 16:44:38 photol-104 weed[6260]: I0304 16:44:38  6260 common.go:80] error writing JSON status 200: write tcp 10.1.21.14:8080->10.244.18.63:57548: write: broken pipe
Mar 04 22:57:41 photol-104 weed[6260]: I0304 22:57:41  6260 common.go:80] error writing JSON status 200: write tcp 10.1.21.14:8080->10.244.18.63:44550: write: broken pipe
Mar 05 13:18:26 photol-104 weed[6260]: I0305 13:18:26  6260 common.go:80] error writing JSON status 200: write tcp 127.0.1.1:8080->127.0.0.1:34220: write: broken pipe
Mar 05 13:18:26 photol-104 weed[6260]: I0305 13:18:26  6260 common.go:80] error writing JSON status 200: write tcp 127.0.1.1:8080->127.0.0.1:34218: write: broken pipe
Mar 05 14:20:38 photol-104 weed[6260]: I0305 14:20:38  6260 common.go:80] error writing JSON status 200: write tcp 127.0.1.1:8080->127.0.0.1:42346: write: broken pipe
Mar 05 14:20:38 photol-104 weed[6260]: I0305 14:20:38  6260 common.go:80] error writing JSON status 200: write tcp 127.0.1.1:8080->127.0.0.1:42378: write: broken pipe
Mar 05 21:11:49 photol-104 weed[6260]: I0305 21:11:49  6260 common.go:80] error writing JSON status 200: write tcp 10.1.21.14:8080->10.244.18.63:39324: write: broken pipe
Mar 06 00:11:13 photol-104 weed[6260]: I0306 00:11:13  6260 common.go:80] error writing JSON status 200: write tcp 127.0.1.1:8080->127.0.0.1:34088: write: broken pipe
Mar 06 00:11:13 photol-104 weed[6260]: I0306 00:11:13  6260 common.go:80] error writing JSON status 200: write tcp 127.0.1.1:8080->127.0.0.1:34086: write: broken pipe
Mar 06 00:11:13 photol-104 weed[6260]: I0306 00:11:13  6260 common.go:80] error writing JSON status 200: write tcp 127.0.1.1:8080->127.0.0.1:34058: write: broken pipe
Mar 06 00:17:37 photol-104 weed[6260]: I0306 00:17:37  6260 common.go:80] error writing JSON status 200: write tcp 10.1.21.14:8080->10.244.18.63:40026: write: broken pipe
Mar 06 00:17:37 photol-104 weed[6260]: I0306 00:17:37  6260 common.go:80] error writing JSON status 200: write tcp 127.0.1.1:8080->127.0.0.1:34808: write: broken pipe
Mar 06 00:17:37 photol-104 weed[6260]: I0306 00:17:37  6260 common.go:80] error writing JSON status 200: write tcp 127.0.1.1:8080->127.0.0.1:34810: write: broken pipe
Mar 06 00:36:36 photol-104 weed[6260]: I0306 00:36:36  6260 common.go:80] error writing JSON status 200: write tcp 10.1.21.14:8080->10.244.18.63:52332: write: broken pipe
Mar 06 00:36:36 photol-104 weed[6260]: I0306 00:36:36  6260 common.go:80] error writing JSON status 200: write tcp 127.0.1.1:8080->127.0.0.1:37226: write: broken pipe
Mar 06 00:36:36 photol-104 weed[6260]: I0306 00:36:36  6260 common.go:80] error writing JSON status 200: write tcp 127.0.1.1:8080->127.0.0.1:37238: write: broken pipe
Mar 06 00:36:36 photol-104 weed[6260]: I0306 00:36:36  6260 common.go:80] error writing JSON status 200: write tcp 127.0.1.1:8080->127.0.0.1:37224: write: broken pipe
Mar 06 07:21:06 photol-104 weed[6260]: I0306 07:21:06  6260 common.go:80] error writing JSON status 200: write tcp 127.0.1.1:8080->127.0.0.1:32952: write: broken pipe
Mar 06 07:21:06 photol-104 weed[6260]: I0306 07:21:06  6260 common.go:80] error writing JSON status 200: write tcp 127.0.1.1:8080->127.0.0.1:32950: write: broken pipe
Mar 06 07:21:06 photol-104 weed[6260]: I0306 07:21:06  6260 common.go:80] error writing JSON status 200: write tcp 127.0.1.1:8080->127.0.0.1:32948: write: broken pipe
Mar 06 13:33:19 photol-104 weed[6260]: I0306 13:33:19  6260 common.go:80] error writing JSON status 200: write tcp 127.0.1.1:8080->127.0.0.1:51998: write: broken pipe
Mar 06 13:33:19 photol-104 weed[6260]: I0306 13:33:19  6260 common.go:80] error writing JSON status 200: write tcp 127.0.1.1:8080->127.0.0.1:52042: write: broken pipe
Mar 06 19:52:26 photol-104 weed[6260]: I0306 19:52:26  6260 common.go:80] error writing JSON status 200: write tcp 127.0.1.1:8080->127.0.0.1:43402: write: broken pipe
Mar 06 19:52:26 photol-104 weed[6260]: I0306 19:52:26  6260 common.go:80] error writing JSON status 200: write tcp 10.1.21.14:8080->10.244.18.63:49636: write: broken pipe
Mar 06 20:10:42 photol-104 weed[6260]: I0306 20:10:42  6260 common.go:80] error writing JSON status 200: write tcp 127.0.1.1:8080->127.0.0.1:45634: write: broken pipe
Mar 06 20:10:42 photol-104 weed[6260]: I0306 20:10:42  6260 common.go:80] error writing JSON status 200: write tcp 127.0.1.1:8080->127.0.0.1:45636: write: broken pipe
Mar 06 20:33:46 photol-104 weed[6260]: I0306 20:33:46  6260 common.go:80] error writing JSON status 200: write tcp 127.0.1.1:8080->127.0.0.1:48510: write: broken pipe
Mar 06 21:29:06 photol-104 weed[6260]: I0306 21:29:06  6260 common.go:80] error writing JSON status 200: write tcp 10.1.21.14:8080->10.244.18.63:34852: write: broken pipe
Mar 06 22:57:52 photol-104 weed[6260]: I0306 22:57:52  6260 common.go:80] error writing JSON status 200: write tcp 127.0.1.1:8080->127.0.0.1:38528: write: broken pipe
Mar 06 22:57:52 photol-104 weed[6260]: I0306 22:57:52  6260 common.go:80] error writing JSON status 200: write tcp 127.0.1.1:8080->127.0.0.1:38530: write: broken pipe
Mar 07 00:03:02 photol-104 weed[6260]: I0307 00:03:02  6260 common.go:80] error writing JSON status 200: write tcp 127.0.1.1:8080->127.0.0.1:46788: write: broken pipe
Mar 07 01:38:21 photol-104 weed[6260]: I0307 01:38:21  6260 common.go:80] error writing JSON status 200: write tcp 10.1.21.14:8080->10.244.18.63:45000: write: broken pipe
Mar 07 02:24:20 photol-104 weed[6260]: I0307 02:24:20  6260 common.go:80] error writing JSON status 200: write tcp 127.0.1.1:8080->127.0.0.1:36444: write: broken pipe
Mar 07 02:24:20 photol-104 weed[6260]: I0307 02:24:20  6260 common.go:80] error writing JSON status 200: write tcp 127.0.1.1:8080->127.0.0.1:36438: write: broken pipe
Mar 07 03:31:48 photol-104 weed[6260]: I0307 03:31:48  6260 common.go:80] error writing JSON status 200: write tcp 127.0.1.1:8080->127.0.0.1:44998: write: broken pipe
Mar 07 03:31:48 photol-104 weed[6260]: I0307 03:31:48  6260 common.go:80] error writing JSON status 200: write tcp 127.0.1.1:8080->127.0.0.1:45018: write: broken pipe

**Comment by ingardm** [comment]
<img width="620" alt="Screenshot 2020-03-08 at 11 43 38" src="https://user-images.githubusercontent.com/2324855/76161876-bb330500-6137-11ea-91f6-e1f038098dab.png">

**Comment by chrislusf** [comment]
Could you please send the full logs? Also, is the timezone in the graph same as the logs?

**Comment by chrislusf** [comment]
From #1108 , is the GC started by external command? How many GC are running at the same time?

**Comment by ingardm** [comment]
The time zone is the same in graph and logs.
It’s the same cluster as In 1108. Pretty sure the GC was started manually, but I’ll check with my colleague.

**Comment by roflmao** [comment]
One GC started: ```curl "http://localhost:9333/vol/vacuum?garbageThreshold=0.05"```

**Comment by chrislusf** [comment]
But the system has its own GC thread, right?

**Comment by roflmao** [comment]
This is correct. Is there a way of turning the built in off, or setting another threshold than 0.3 for the builtin? Will share full logs ASAP

**Comment by chrislusf** [comment]
`weed master -garbageThreshold=0.05`

**Comment by roflmao** [comment]
All logs from 2020-03-04 00:00:00:  https://www.jottacloud.com/s/006459682377e44416ea91b2676204b63da

**Comment by roflmao** [comment]
We will try with weed master -garbageThreshold=0.05 and no manual GC and check the graphs forward.

**Comment by chrislusf** [comment]
Thanks for all the details and testing! Found the issue. I will create a release soon.
