### ISSUE TITLE
fuse: panic in handler for Getxattr while trying to list the content of the folder

### ISSUE THREAD

**Issue by xirius** [chrislusf/seaweedfs#1223]
**Describe the bug**
Not sure if I'm doing it right!
I decided to test a small cluster with swarm; 3 masters, 3 volumes and 3 filers.
When I mount to the filer 1, it works. But if I try to mount to the filer 2 or 3 I get the exception below when I try to `ls -l test` folder.
```
ls -la test/
2020-03-08 22:28:00.759638 I | fuse: panic in handler for Getxattr [ID=0x3 Node=0x1 Uid=1000 Gid=1000 Pid=151052] "system.posix_acl_access" 0 @0: runtime error: invalid memory address or nil pointer dereference
goroutine 50 [running]:
github.com/seaweedfs/fuse/fs.(*Server).serve.func2(0x22ab8a0, 0xc00053a000, 0xc0004ffec0, 0xc0004ffdaf)
	/home/travis/gopath/pkg/mod/github.com/seaweedfs/fuse@v0.0.0-20190510212405-310228904eff/fs/serve.go:861 +0x1a2
panic(0x1b8ed20, 0x331a7a0)
	/home/travis/.gimme/versions/go1.13.8.linux.amd64/src/runtime/panic.go:679 +0x1b2
github.com/chrislusf/seaweedfs/weed/filesys.(*WFS).maybeLoadEntry.func1(0x22dc380, 0xc0000f4120, 0x3, 0xc00017a8f0)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/filesys/xattr.go:129 +0x35a
github.com/chrislusf/seaweedfs/weed/filesys.(*WFS).WithFilerClient.func1(0xc00005f880, 0xc000156090, 0xc00003fc60)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/filesys/wfs.go:98 +0x6b
github.com/chrislusf/seaweedfs/weed/util.WithCachedGrpcClient(0xc00036a8a8, 0xc00003fc60, 0xf, 0xc00036a8b8, 0x1, 0x1, 0x18ed317, 0xc0000f2280)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/util/grpc_client_server.go:69 +0xc6
github.com/chrislusf/seaweedfs/weed/filesys.(*WFS).WithFilerClient(0xc00017b2b0, 0xc00036a930, 0x5, 0x0)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/filesys/wfs.go:96 +0x9c
github.com/chrislusf/seaweedfs/weed/filesys.(*WFS).maybeLoadEntry(0xc00017b2b0, 0x7ffc7a9d47b1, 0x1, 0x7ffc7a9d47b2, 0x4, 0x0, 0x3387801, 0xc00052a600)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/filesys/xattr.go:120 +0x1c3
github.com/chrislusf/seaweedfs/weed/filesys.(*Dir).maybeLoadEntry(0xc00014d500, 0x5, 0xc00052a600)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/filesys/dir.go:422 +0x8e
github.com/chrislusf/seaweedfs/weed/filesys.(*Dir).Getxattr(0xc00014d500, 0x22b8ca0, 0xc000098840, 0xc00053a000, 0xc00028e460, 0x3387a01, 0x1f79ad8)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/filesys/dir.go:70 +0x8c
github.com/seaweedfs/fuse/fs.(*Server).handleRequest(0xc00039c000, 0x22b8ca0, 0xc000098840, 0x2272100, 0xc00014d500, 0xc000416980, 0x22ab8a0, 0xc00053a000, 0xc0004ffec0, 0x0, ...)
	/home/travis/gopath/pkg/mod/github.com/seaweedfs/fuse@v0.0.0-20190510212405-310228904eff/fs/serve.go:1131 +0x2388
github.com/seaweedfs/fuse/fs.(*Server).serve(0xc00039c000, 0x22ab8a0, 0xc00053a000)
	/home/travis/gopath/pkg/mod/github.com/seaweedfs/fuse@v0.0.0-20190510212405-310228904eff/fs/serve.go:882 +0x2fd
github.com/seaweedfs/fuse/fs.(*Server).Serve.func1(0xc00039c000, 0x22ab8a0, 0xc00053a000)
	/home/travis/gopath/pkg/mod/github.com/seaweedfs/fuse@v0.0.0-20190510212405-310228904eff/fs/serve.go:424 +0x7c
created by github.com/seaweedfs/fuse/fs.(*Server).Serve
	/home/travis/gopath/pkg/mod/github.com/seaweedfs/fuse@v0.0.0-20190510212405-310228904eff/fs/serve.go:422 +0x35e
ls: test/: Input/output error
total 0
```

**System Setup**
Commands for masters
```
ports:
  - 9333:9333
command: "master -ip=master1 -port=9333 -peers=master1:9333,master2:9334,master3:9335 -defaultReplication=002"
...
ports:
  - 9334:9333
command: "master -ip=master2 -port=9333 -peers=master1:9333,master2:9333,master3:9335 -defaultReplication=002"
...
ports:
  - 9335:9333
command: "master -ip=master3 -port=9333 -peers=master1:9333,master2:9334,master3:9333 -defaultReplication=002"
```

Commands for volumes
```
ports:
  - 8080:8080
command: '-v=2 volume -ip=volume1 -port=8080 -max=5 -mserver="master1:9333,master2:9334,master3:9335" -dataCenter=dc1 -rack=rack1'
...
ports:
  - 8081:8080
command: '-v=2 volume -ip=volume2 -port=8080 -max=5 -mserver="master1:9333,master2:9334,master3:9335" -dataCenter=dc1 -rack=rack1'
...
ports:
  - 8082:8080
command: '-v=2 volume -ip=volume3 -port=8080 -max=5 -mserver="master1:9333,master2:9334,master3:9335" -dataCenter=dc1 -rack=rack1'
```

Commands for filers
```
ports:
  - 8881:8888
command: '-v=4 filer -master="master1:9333,master2:9334,master3:9335"'
...
ports:
  - 8882:8888
command: '-v=4 filer -master="master1:9333,master2:9334,master3:9335"'
...
ports:
  - 8883:8888
command: '-v=4 filer -master="master1:9333,master2:9334,master3:9335"'
```

Mount command
```
./weed mount -outsideContainerClusterMode -filer=localhost:8882 -dir ~/test -filer.path=/test &
```

- Debian 10.3
- output of `weed version`: version 30GB 1.58 linux amd64
- if using filer, show the content of `filer.toml`
```
/ # cat /etc/seaweedfs/filer.toml 
[leveldb2]
enabled = true
dir = "/data/filerldb2"
```

**Expected behavior**
Expected to list the files.

**Additional context**
It seems to work when I mount only the filer 1. It is possible to have several filers ?
Can it be mounted to several filers in case on of them fails or the node becomes unreachable?
Something like: ./weed mount -filer=ip1:8880;ip2:8881;ip3:8882

```
./weed mount -outsideContainerClusterMode -filer=localhost:8880 -dir ~/test -filer.path=/test &
```

**Comment by chrislusf** [comment]
duplicate with https://github.com/chrislusf/seaweedfs/issues/1221

**Comment by chrislusf** [comment]
you can use 1.59 release now.

**Comment by chrislusf** [comment]
Currently, only one filer is supported. Multiple filers? maybe later. Not sure whether it would be useful or not.

**Comment by xirius** [comment]
@chrislusf Not sure why you think having multiple filers is not useful. What happens if the filer goes down or the whole server goes offline.
I like your project, it looks very promising! But it is currently missing some resilience features.
[Ceph FS](https://docs.ceph.com/docs/master/man/8/mount.ceph/) can be mounted with a list of monitors and stays available when some of them goes offline.
In other words, I can put the server offline (even reboot) to make some maintenance without affecting the whole system due to redundancy.

**Comment by chrislusf** [comment]
Filer is stateless if using shared store, just like a web app. Put load
balancer in front if needed.

**Comment by xirius** [comment]
Not sure I got the idea. weed mount needs a filer. Ok I can load balance the filer nodes but in my tests only one one filer works. I mean, if I have 3 filer nodes on 3 different severs (as describes above, all connected to 3 masters), when I "weed mount filler1" and create some files and then I mount "weed mount filer2" on another node I don't see any files.
Am I dong it wrong ? Mounting with one IP is fine, I can load balance between filers but I expect all 3 filers give the same information.

**Comment by chrislusf** [comment]
You are using embedded filer store, which is not shared. If you want filer to failover, you need to use a different filer store.

https://github.com/chrislusf/seaweedfs/wiki/Filer-Stores

**Comment by xirius** [comment]
@chrislusf Thanks Chris! I assumed the filer should replicate metadata for redundancy. It means the problem is how to scale a "shared" filer store (underlying database).
I like seaweed for it simplicity and such an option would be really awesome (filer (with local leveldb2) replication)!

**Comment by xirius** [comment]
Is there any example how to setup filer with PostgreSQL ?
