### ISSUE TITLE
Filer转换ttl错误导致redis中的记录的key永远不过期

### ISSUE THREAD

**Issue by HongyanShen** [chrislusf/seaweedfs#1225]
- 错误代码https://github.com/chrislusf/seaweedfs/blob/1.59/weed/server/filer_server_handlers_write.go#L178

- 错误说明
    当以 http://fileraddr.com/filename.suffix?ttl=3d 这种形式上传文件时，util.ParseInt以3d和0作为参数，导致函数内部出错，返回默认值0.

另外建议针对redis以外的filer store实现，将过期时间冗余进去，以便用户更方便的进行过期记录的清理。

**Comment by chrislusf** [comment]
Thanks for reporting this! Fixed now.

**Comment by chrislusf** [comment]
Thanks for your suggestion! I added support TTL support for all filer stores. https://github.com/chrislusf/seaweedfs/commit/89eb05b50f10b6ca74a374e5435df2f72019f635
