### ISSUE TITLE
并发append同一个切片可能导致空指针异常

### ISSUE THREAD

**Issue by HongyanShen** [chrislusf/seaweedfs#1226]
- 以下代码可能存在并发append同一切片的问题
    https://github.com/chrislusf/seaweedfs/blob/1.59/weed/replication/sink/s3sink/s3_sink.go#L119
    https://github.com/chrislusf/seaweedfs/blob/1.59/weed/replication/sink/filersink/fetch_write.go#L31

**Comment by chrislusf** [comment]
Send a PR?

**Comment by HongyanShen** [comment]
@chrislusf ok
