### ISSUE TITLE
how to mount mutil filer

### ISSUE THREAD

**Issue by zhujintao** [chrislusf/seaweedfs#1229]
[root@cserver01 bin]# weed mount -filer=192.168.1.101:8888,192.168.1.102:8888 -dir=/datashare
I0312 11:20:05  7768 config.go:30] Reading : Config File "security" Not Found in "[/usr/local/bin /root/.seaweedfs /etc/seaweedfs]"
This is SeaweedFS version 8000GB 1.60 linux amd64
mount point owner uid=0 gid=0 mode=drwxr-xr-x
current uid=0 gid=0
I0312 11:20:06  7768 mount_std.go:141] ParseFilerGrpcAddress: filer should have hostname:port format: [192.168.1.101 8888,192.168.1.102 8888]

**Comment by chrislusf** [comment]
one filer. multiple filers are not supported yet.
