### ISSUE TITLE
weed.go:22: undefined: Command

### ISSUE THREAD

**Issue by hetao29** [chrislusf/seaweedfs#123]
```
# command-line-arguments
src/github.com/chrislusf/seaweedfs/go/weed/weed.go:22: undefined: Command
```

**Comment by chrislusf** [comment]
Can not reproduce. I think you may need to checkout the seaweedfs again.

**Comment by hetao29** [comment]
ok, I will try again later. dodo..

何涛 Hetal

Tel: 13488810858

北京市海淀区，100080




2015-04-17 10:55 GMT+08:00 chrislusf <notifications@github.com>:
