### ISSUE TITLE
无法启动 filer ，程序一直在报错无法使用

### ISSUE THREAD

**Issue by GeorgeWang1994** [chrislusf/seaweedfs#1231]
使用的是1.44的版本，在使用的过程中程序一直在报错，导致无法正常启动

**Describe the bug**
![image](https://user-images.githubusercontent.com/29206315/76692901-1add6300-6698-11ea-97da-919a0f30ae78.png)

**System Setup**
1. 使用的是1.44的版本
2. fliter.toml如下：
[leveldb2]
enabled = true
dir = "/data/filerldb2"
3. 暂时无法获取操作系统信息
4. 问题具有偶发性

**Comment by chrislusf** [comment]
Looks like the initialization failed. Please look for error logs printed in this function:
https://github.com/chrislusf/seaweedfs/blob/master/weed/filer2/leveldb2/leveldb2_store.go#L39

Find logs after "filer store leveldb2 dir", for errors related to "Check Level Folder" or  "filer store open dir".

**Comment by GeorgeWang1994** [comment]
大概的猜测是不具有写的权限嘛

**Comment by chrislusf** [comment]
no logs?
