### ISSUE TITLE
integrity checks?

### ISSUE THREAD

**Issue by onlyjob** [chrislusf/seaweedfs#1232]
How SeaweedFS ensures integrity of data?
Is there CRC checks?

Data integrity in distributed storage systems is of _paramount importance_ but there is no mentioning of it in SeaweedFS documentation?

Automatic transparent integrity checks should be implemented (and documented) to ensure that invalid data is never served to the client.
Bitrot resistance must be automatic to protect against corruption of data.
Passive self-healing (scrubbing and auto-repair) is also good to have.

MooseFS and LizardFS have good approach to data integrity.
To be competitive, Seaweeds should have zero tolerance to data corruption.

Thanks.

**Comment by chrislusf** [comment]
Already implemented checksum checking.

**Comment by onlyjob** [comment]
Where is it implemented? In client? In block storage? Both? Please elaborate and document.

**Comment by chrislusf** [comment]
This was implemented following haystack paper. Every file, aka needle, has a checksum. This is created during write time and checked during read time on server side.

**Comment by onlyjob** [comment]
Awesome, Thanks.

I would recommend to add the client-side verification as well.

I hope you might find some interesting insights in the following discussion: https://github.com/lizardfs/lizardfs/issues/390

**Comment by chrislusf** [comment]
Good to know! The client-side verification is similar to what S3 is doing. (btw: It is using MD5)

The SeaweedFS filer, which supports S3, is using MD5 ETag for client side to verify.
