### ISSUE TITLE
lost datas after the numbers of master server changed

### ISSUE THREAD

**Issue by huzhixiang** [chrislusf/seaweedfs#1234]
there was 3 master server and 3 volume server in my project, and I want to  use only one master server. so I killed all master and volume process,restart them like this:
--1master
nohup /usr/local/seaweedfs/weed master -port=9333 -mdir=/usr/local/seaweedfs/1 -ip=10.15.2.41  > /usr/local/seaweedfs/seaweedfs.log &
--1volume
nohup /usr/local/seaweedfs/weed volume -max=1024 -dir=/usr/local/seaweedfs/v1 -ip=10.15.2.41 -port=8081 -mserver=10.15.2.41:9333 > /usr/local/seaweedfs/seaweedfs.log &
--2volume
nohup /usr/local/seaweedfs/weed volume -max=1024 -dir=/usr/local/seaweedfs/v2 -ip=10.15.2.42 -port=8081 -mserver=10.15.2.41:9333 > /usr/local/seaweedfs/seaweedfs.log &
--3volume
nohup /usr/local/seaweedfs/weed volume -max=1024 -dir=/usr/local/seaweedfs/v3 -ip=10.15.2.43 -port=8081 -mserver=10.15.2.41:9333 > /usr/local/seaweedfs/seaweedfs.log &

but I found that I lost the datas in the volume,is it odd?
this is the command  I executed before :
nohup /usr/local/seaweedfs/weed master -port=9333 -mdir=/usr/local/seaweedfs/1 -ip=10.15.2.41 -peers=10.15.2.41:9333,10.15.2.42:9333,10.15.2.43:9333 > /usr/local/seaweedfs/seaweedfs.log &
nohup /usr/local/seaweedfs/weed master -port=9333 -mdir=/usr/local/seaweedfs/2 -ip=10.15.2.42 -peers=10.15.2.41:9333,10.15.2.42:9333,10.15.2.43:9333 > /usr/local/seaweedfs/seaweedfs.log &
nohup /usr/local/seaweedfs/weed master -port=9333 -mdir=/usr/local/seaweedfs/3 -ip=10.15.2.43 -peers=10.15.2.41:9333,10.15.2.42:9333,10.15.2.43:9333 > /usr/local/seaweedfs/seaweedfs.log &

nohup /usr/local/seaweedfs/weed volume -max=1024 -dir=/usr/local/seaweedfs/v1 -ip=10.15.2.41 -port=8081 -mserver=10.15.2.41:9333,10.15.2.42:9333,10.15.2.43:9333 > /usr/local/seaweedfs/seaweedfs.log &
nohup /usr/local/seaweedfs/weed volume -max=1024 -dir=/usr/local/seaweedfs/v2 -ip=10.15.2.42 -port=8081 -mserver=10.15.2.41:9333,10.15.2.42:9333,10.15.2.43:9333 > /usr/local/seaweedfs/seaweedfs.log &
nohup /usr/local/seaweedfs/weed volume -max=1024 -dir=/usr/local/seaweedfs/v3 -ip=10.15.2.43 -port=8081 -mserver=10.15.2.41:9333,10.15.2.42:9333,10.15.2.43:9333 > /usr/local/seaweedfs/seaweedfs.log &
and this is the logs:
_I0317 16:21:55 18926 disk_location.go:68] data file /usr/local/seaweedfs/v2/3.dat, replicaPlacement=000 v=3 size=4363994392 ttl=
I0317 16:21:55 18926 disk_location.go:68] data file /usr/local/seaweedfs/v2/6.dat, replicaPlacement=000 v=3 size=4314755800 ttl=
I0317 16:21:55 18926 disk_location.go:68] data file /usr/local/seaweedfs/v2/1.dat, replicaPlacement=000 v=3 size=4210776520 ttl=
I0317 16:21:55 18926 disk_location.go:109] Store started on dir: /usr/local/seaweedfs/v2 with 13 volumes max 1024
I0317 16:21:55 18926 disk_location.go:112] Store started on dir: /usr/local/seaweedfs/v2 with 0 ec shards
I0317 16:21:55 18926 volume.go:162] Start Seaweed volume server 30GB 1.41 at 0.0.0.0:8081
I0317 16:21:55 18926 volume_grpc_client_to_master.go:24] Volume server start with seed master nodes: [10.15.2.41:9333]
I0317 16:21:55 18926 volume_grpc_client_to_master.go:68] Heartbeat to: 10.15.2.41:9333
I0317 18:43:29 18926 volume_server_handlers_read.go:92] read /21,013000823ed4 isNormalVolume true error: not found
I0317 18:43:47 18926 volume_server_handlers_read.go:92] read /21,013000823ed4 isNormalVolume true error: not found
I0317 18:44:38 18926 volume_server_handlers_read.go:92] read /21,013000823ed4 isNormalVolume true error: not found
I0317 18:44:43 18926 volume_server_handlers_read.go:92] read /21,013000823ed4 isNormalVolume true error: not found
I0317 18:44:48 18926 volume_server_handlers_read.go:92] read /21,013000823ed4 isNormalVolume true error: not found
I0317 18:44:53 18926 volume_server_handlers_read.go:92] read /21,013000823ed4 isNormalVolume true error: not found
I0317 18:44:57 18926 volume_server_handlers_read.go:92] read /21,013000823ed4 isNormalVolume true error: not found
I0317 18:45:02 18926 volume_server_handlers_read.go:92] read /21,013000823ed4 isNormalVolume true error: not found
I0317 18:45:04 18926 volume_server_handlers_read.go:92] read /21,013000823ed4 isNormalVolume true error: not found
I0317 18:45:17 18926 volume_server_handlers_read.go:92] read /21,013000823ed4 isNormalVolume true error: not found
I0317 18:45:19 18926 volume_server_handlers_read.go:92] read /21,013000823ed4 isNormalVolume true error: not found
I0317 18:45:20 18926 volume_server_handlers_read.go:92] read /21,013000823ed4 isNormalVolume true error: not found
I0317 18:46:56 18926 volume_server_handlers_read.go:92] read /21,013000823ed4 isNormalVolume true error: not found
I0317 18:57:59 18926 volume_server_handlers_read.go:92] read /21,013000823ed4 isNormalVolume true error: not found
I0317 19:00:49 18926 volume_server_handlers_read.go:92] read /21,0111048e00b2 isNormalVolume true error: not found
I0317 19:01:00 18926 volume_server_handlers_read.go:92] read /10,01121f8aac70 isNormalVolume true error: not found
I0317 19:01:13 18926 volume_server_handlers_read.go:92] read /9,01138b98918b isNormalVolume true error: not found
I0317 19:01:25 18926 volume_server_handlers_read.go:92] read /10,0135a8114e7c isNormalVolume true error: not found
I0317 19:01:52 18926 volume_server_handlers_read.go:92] read /9,012d611a3a14 isNormalVolume true error: not found
I0317 19:07:15 18926 volume_server_handlers_read.go:92] read /21,0111048e00b2 isNormalVolume true error: not found
I0317 19:24:03 18926 volume_server_handlers_read.go:92] read /21,0111048e00b2 isNormalVolume true error: not found
I0317 19:24:09 18926 volume_server_handlers_read.go:92] read /21,0111048e00b2 isNormalVolume true error: not found
I0317 19:24:12 18926 volume_server_handlers_read.go:92] read /21,0111048e00b2 isNormalVolume true error: not found
I0318 07:57:35 18926 volume_server_handlers_read.go:92] read /21,013000823ed4 isNormalVolume true error: not found
I0318 08:48:30 18926 store.go:109] In dir /usr/local/seaweedfs/v2 adds volume:256 collection: replicaPlacement:000 ttl:10m
I0318 08:48:30 18926 volume_loading.go:83] loading index /usr/local/seaweedfs/v2/256.idx to memory readonly false
I0318 08:48:30 18926 store.go:113] add volume 256
I0318 08:48:30 18926 store.go:109] In dir /usr/local/seaweedfs/v2 adds volume:258 collection: replicaPlacement:000 ttl:10m
I0318 08:48:30 18926 volume_loading.go:83] loading index /usr/local/seaweedfs/v2/258.idx to memory readonly false
I0318 08:48:30 18926 store.go:113] add volume 258
I0318 09:18:55 18926 store.go:179] volume 256 is deleted.
I0318 09:38:55 18926 store.go:179] volume 258 is deleted.
I0318 09:46:25 18926 store.go:109] In dir /usr/local/seaweedfs/v2 adds volume:267 collection: replicaPlacement:000 ttl:
I0318 09:46:25 18926 volume_loading.go:83] loading index /usr/local/seaweedfs/v2/267.idx to memory readonly false
I0318 09:46:25 18926 store.go:113] add volume 267
I0318 09:46:25 18926 store.go:109] In dir /usr/local/seaweedfs/v2 adds volume:270 collection: replicaPlacement:000 ttl:
I0318 09:46:25 18926 volume_loading.go:83] loading index /usr/local/seaweedfs/v2/270.idx to memory readonly false
I0318 09:46:25 18926 store.go:113] add volume 270
I0318 10:07:02 18926 store.go:109] In dir /usr/local/seaweedfs/v2 adds volume:276 collection: replicaPlacement:000 ttl:10m
I0318 10:07:02 18926 volume_loading.go:83] loading index /usr/local/seaweedfs/v2/276.idx to memory readonly false
I0318 10:07:02 18926 store.go:113] add volume 276
I0318 10:07:02 18926 store.go:109] In dir /usr/local/seaweedfs/v2 adds volume:277 collection: replicaPlacement:000 ttl:10m
I0318 10:07:02 18926 volume_loading.go:83] loading index /usr/local/seaweedfs/v2/277.idx to memory readonly false
I0318 10:07:02 18926 store.go:113] add volume 277
I0318 10:34:00 18926 store.go:179] volume 276 is deleted.
I0318 10:38:45 18926 store.go:181] volume 277 is expired.
I0318 10:38:50 18926 store.go:179] volume 277 is deleted.
I0318 10:51:19 18926 volume_vacuum.go:45] Committing volume 267 vacuuming...
I0318 10:51:19 18926 volume_loading.go:83] loading index /usr/local/seaweedfs/v2/267.idx to memory readonly false_

**I really need your help to find out the problems 
1 is there some wrong operate to change the master numbers.
2 why the data is lost
3 how can I recover my datas and avoid losing datas** 

I look forward to your clues and suggest,thank you.

**Comment by chrislusf** [comment]
Operations look fine.

how to tell the data is lost, not deleted or expired?
do you still have 21.dat file?

**Comment by huzhixiang** [comment]
no,I don't deltete the data deliberately.,and you can see 
_[app@localhost ~]<20200318 16:17:57>$ curl http://10.15.2.41:9333/dir/lookup?volumeId=21
{"volumeId":"21","error":"volumeId 21 not found."}[app@localhost ~]<20200318 16:18:02>$_ 
there is no 21.
and If I find 21.dat and 21.idx, can I just use mv command to move them back to the directory
to recover my data ?

**Comment by chrislusf** [comment]
> and If I find 21.dat and 21.idx, can I just use mv command to move them back to the directory
> to recover my data ?

Yes. But why those .dat and .idx files are missing?

**Comment by huzhixiang** [comment]
if the operation is legal ,then maybe someone operated miss.  Thank you, I have got what I want to know.
