### ISSUE TITLE
When filer.copy the same big folder more times, the old data space can't be vacuum.

### ISSUE THREAD

**Issue by zjzdy** [chrislusf/seaweedfs#1237]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**
When filer.copy the same big folder more times, the old data space can't be vacuum.
I try to storage more file(just like 300,000 file total 1TB), when upload more times with same path for Filer server, the vacuum operation is rarely effective.But only one file, the vacuum always good.
When volumeSizeLimitMB set to 8000000, the vacuum save space size offen less than the default value 30000.
In next, I try to use part of the files to test the vacuum after more times upload same folder and only use one volume. Look for `Expected behavior`.
This test is accidental, please test a few more times. And some times change garbageThreshold can save more space, some times not has different.

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
`weed.exe server  -filer -dir ./data5  -volume.max 1`
or
`weed.exe server  -filer -dir ./data5  -master.volumeSizeLimitMB 8000000  -volume.max 1`
- OS version
Windows 10 1909
- output of `weed version`
version 8000GB 1.64 windows amd64
- if using filer, show the content of `filer.toml`
default

**Expected behavior**
When filer.copy the same big folder more times, the old data space can't be vacuum.
Description:
Wait at least 5 seconds between any of the following operations and view the file size.(also between any two of the operations, include kill operation)
The files in the test4 folder are a subset of the test3 folder.

unzip test.zip to I:\
mkdir data5
`weed.exe server  -filer -dir ./data5  -volume.max 1`
1.dat size: no such file
`weed.exe filer.copy I:\test4 http://localhost:8888/`
1.dat size: 125 MB (131,429,856 Bytes)
`weed.exe filer.copy I:\test4 http://localhost:8888/`
1.dat size: 250 MB (262,860,376 Bytes)
`curl "http://localhost:9333/vol/vacuum"`
kill weed(use Ctrl+C)
1.dat size: 173 MB (181,863,672 Bytes) or 125 MB (131,429,856 Bytes)

rm -r data5
`weed.exe server  -filer -dir ./data5  -volume.max 1`
1.dat size: no such file
`weed.exe filer.copy I:\test3 http://localhost:8888/`
1.dat size: 133 MB (140,343,712 Bytes)
`weed.exe filer.copy I:\test3 http://localhost:8888/`
1.dat size: 267 MB (280,687,864 Bytes)
`curl "http://localhost:9333/vol/vacuum"`
kill weed(use Ctrl+C)
1.dat size: 267 MB (280,687,864 Bytes) or 143 MB (150,494,008 Bytes)

rm -r data5
`weed.exe server  -filer -dir ./data5  -master.volumeSizeLimitMB 8000000  -volume.max 1`
1.dat size: no such file
`weed.exe filer.copy I:\test3 http://localhost:8888/`
1.dat size: 133 MB (140,343,712 Bytes)
`weed.exe filer.copy I:\test3 http://localhost:8888/`
1.dat size: 267 MB (280,687,864 Bytes)
`curl "http://localhost:9333/vol/vacuum"`
1.dat size: 267 MB (280,687,864 Bytes)
`curl "http://localhost:9333/vol/vacuum?garbageThreshold=0.0001"`
kill weed(use Ctrl+C)
1.dat size: 215 MB (226,076,448 Bytes)

rm -r data5
`weed.exe server  -filer -dir ./data5  -master.volumeSizeLimitMB 8000000  -volume.max 1`
1.dat size: no such file
`weed.exe filer.copy I:\test3 http://localhost:8888/`
1.dat size: 133 MB (140,343,712 Bytes)
`weed.exe filer.copy I:\test3 http://localhost:8888/`
1.dat size: 152 MB (159,877,768 Bytes)
`curl "http://localhost:9333/vol/vacuum?garbageThreshold=0.0001"`
kill weed(use Ctrl+C)
1.dat size: 152 MB (159,877,768 字节)

When volumeSizeLimitMB set to 8000000, the vacuum save space size offen less than the default value 30000.
And more file(just like 300,000 file total 1TB), when upload more times with same path for Filer server, the vacuum operation is rarely effective.But only one file, the vacuum always good.
If the problem cannot be reproduced, consider increasing the number of files and directories.

**Additional context**
test.zip download:
http://www.mediafire.com/file/52atrnqby2u9ltp/test.zip/file
Alternate link: https://pan.baidu.com/s/1YNgCZ4q5M4D-tbZEwYEDcA  code: 8sqh

**Comment by chrislusf** [comment]
Did you have some pause between each command?

**Comment by zjzdy** [comment]
yes,  least 5 seconds.

**Comment by zjzdy** [comment]
But, if not pause between each command. When I run double filer.copy and vacuum, and wait data flush disk, kill it, again run weed, to run vacuum, wait some time, Shouldn't disk space also change?But also not change.

**Comment by chrislusf** [comment]
This is related to windows OS. The file content are kept in memory and not flushed. I will add some code to address this.

**Comment by zjzdy** [comment]
Sorry, I try version 8000GB 1.65 windows amd64, this problem still exists.
The first run is successful. But delete data, run again also has this problem. You can try more times.
```
weed.exe server  -filer -dir ./data5  -volume.max 1
S:\weed\weed.exe filer.copy I:\test3 http://localhost:8888/
S:\weed\weed.exe filer.copy I:\test3 http://localhost:8888/
curl "http://localhost:9333/vol/vacuum"
```
Also has least 5 seconds pause between each command.

**Comment by chrislusf** [comment]
Please try 1.67

**Comment by zjzdy** [comment]
OK, 1.67 No problems.
