### ISSUE TITLE
filler does not pass query params to volume server

### ISSUE THREAD

**Issue by ignusws** [chrislusf/seaweedfs#1239]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**
requests to filer like http://172.18.0.18:8888/test/1.jpg?width=200 didnt resize image

it looks like something was broken in version 1.59 (1.58 works as expected)
 
**System Setup**
version 30GB 1.64 linux amd64

**Comment by chrislusf** [comment]
this is expected. 

* Previous implementation is passing through to volume server, but it does not work for large chunked files.
* resizing image is CPU intensive and should be avoided.

Could you implement resizing in your own way?

**Comment by ignusws** [comment]
> this is expected.
>     * Previous implementation is passing through to volume server, but it does not work for large chunked files.
Files we want to processs is about 1MB at most right now, so thats not a problem
 
>     * resizing image is CPU intensive and should be avoided.
We do now this and plan to cache frequently requested resized images

> Could you implement resizing in your own way?
Resizing on a fly one of the features why we choose seaweedfs for storage so we can remove processing servers and simplify our infrastructure.
Do you plan to completely remove resizing in future releases from volume servers as well? Maybe you can put this feature behind some flag for filer and volume server and put warning about mentioned limitations?

**Comment by hunglsxx** [comment]
I try resize image via volume server. But i still got an error: `esizing.go:51 image: unknown format`
When i install seaweed on local with window 10, and request to volume server via chrome to resize image, everythings seem ok. But when i install seaweed on linux server, then request from client browser, it not work. i'm checked volume server, it show that bug (`esizing.go:51 image: unknown format`)
But, on linux local, when i try wget to image url to resize, it work. 
Is that your wish? :((

**Comment by hunglsxx** [comment]
@ignusws if you using nginx to proxy pass,you should add `proxy_set_header Accept-Encoding "";` to nginx config. It worked for me!

**Comment by ignusws** [comment]
> @ignusws if you using nginx to proxy pass,you should add `proxy_set_header Accept-Encoding "";` to nginx config. It worked for me!
Sadly didnt work, our problem is not with requesting resized image directly from volume server with work fine in latest version, but from filer server

Right now we can't change several of our apps and store image and file links directly in app database, so we rely on filer-server and its fuse mount thus direct volume server links is an option

**Comment by hunglsxx** [comment]
sad for you, I think the author has changed the architecture of seaweed too urgently without a plan for the user to solve the problem.
I just got the error this morning, and only when I looked at the @chrislusf 's commits did I find a solution

**Comment by chrislusf** [comment]
I can copy the logic from volume server to filer, in the next releaase.

**Comment by ignusws** [comment]
> I can copy the logic from volume server to filer, in the next releaase.

Thank you, I will be very grateful

**Comment by chrislusf** [comment]
Added back in https://github.com/chrislusf/seaweedfs/commit/308688c8d0b29caa06739338748cb3882c3a8559

**Comment by ignusws** [comment]
Thank you for implementing this feature for filer-server.

But we found bug in it. When width or height params exceeds image dimensions filer sends empty image whereas volume-server sends unscaled image

**Comment by chrislusf** [comment]
Added a fix for this.
