### ISSUE TITLE
Can not resize image via volume server

### ISSUE THREAD

**Issue by hunglsxx** [chrislusf/seaweedfs#1240]
I try resize image via volume server. But i still got an error: esizing.go:51 image: unknown format
When i install seaweed on local with window 10, and request to volume server via chrome to resize image, everythings seem ok. But when i install seaweed on linux server, then request from client browser, it not work. i'm checked volume server, it show that bug (esizing.go:51 image: unknown format)
But, on linux local, when i try wget to image url to resize, it work.

**Comment by chrislusf** [comment]
seems you mentioned you resolved your issue on https://github.com/chrislusf/seaweedfs/issues/1239
