### ISSUE TITLE
Can't delete objects using deleteObjects: getting the next error from seaweedfs log: panic: runtime error: index out of range

### ISSUE THREAD

**Issue by illya-anyvision** [chrislusf/seaweedfs#1241]
No matter whats is the amount of objects we try to delete we get the same error of connect ECONNREFUSED, and the log is: `goroutine 611 [running]:
github.com/chrislusf/seaweedfs/weed/s3api.(*S3ApiServer).DeleteMultipleObjectsHandler.func2(0xc0009cfc80, 0x27)
	/go/src/github.com/chrislusf/seaweedfs/weed/s3api/s3api_object_handlers.go:189 +0x26c
github.com/chrislusf/seaweedfs/weed/s3api.(*S3ApiServer).streamRemove.func1.1(0x559de676ed20, 0xc000873590, 0xc0005290e0, 0xc0008f7e90)
	/go/src/github.com/chrislusf/seaweedfs/weed/s3api/filer_util.go:165 +0x42
created by github.com/chrislusf/seaweedfs/weed/s3api.(*S3ApiServer).streamRemove.func1
	/go/src/github.com/chrislusf/seaweedfs/weed/s3api/filer_util.go:153 +0x273
I0320 16:00:24     1 config.go:27] Reading security.toml from 
I0320 16:00:24     1 config.go:30] Reading : Config File "security" Not Found in "[/ /root/.seaweedfs /etc/seaweedfs]"
I0320 16:00:24     1 tls.go:51] load cert/key error: open : no such file or directory
I0320 16:00:24     1 s3.go:138] S3 read filer buckets dir: /buckets
I0320 16:00:24     1 s3.go:145] connected to filer seaweedfs-filer-localnode.tls.ai:8888 grpc address seaweedfs-filer-localnode.tls.ai:18888
I0320 16:00:24     1 s3.go:178] Start Seaweed S3 API Server 30GB 1.61 at http port 8333
panic: runtime error: index out of range [116] with length 116
`

**Comment by chrislusf** [comment]
Could you add more logs. Seems there are other panic errors down below.

**Comment by chrislusf** [comment]
For ECONNREFUSED, this shows it is failing to connect to filer gRpc port.

Usually filer port is 8888, the gRpc port is 8888+10000=18888.

**Comment by illya-anyvision** [comment]
thanks for the response, here is the rest of the log:

`anic: runtime error: index out of range [116] with length 116

goroutine 611 [running]:
github.com/chrislusf/seaweedfs/weed/s3api.(*S3ApiServer).DeleteMultipleObjectsHandler.func2(0xc0009cfc80, 0x27)
	/go/src/github.com/chrislusf/seaweedfs/weed/s3api/s3api_object_handlers.go:189 +0x26c
github.com/chrislusf/seaweedfs/weed/s3api.(*S3ApiServer).streamRemove.func1.1(0x559de676ed20, 0xc000873590, 0xc0005290e0, 0xc0008f7e90)
	/go/src/github.com/chrislusf/seaweedfs/weed/s3api/filer_util.go:165 +0x42
created by github.com/chrislusf/seaweedfs/weed/s3api.(*S3ApiServer).streamRemove.func1
	/go/src/github.com/chrislusf/seaweedfs/weed/s3api/filer_util.go:153 +0x273
I0320 16:00:24     1 config.go:27] Reading security.toml from 
I0320 16:00:24     1 config.go:30] Reading : Config File "security" Not Found in "[/ /root/.seaweedfs /etc/seaweedfs]"
I0320 16:00:24     1 tls.go:51] load cert/key error: open : no such file or directory
I0320 16:00:24     1 s3.go:138] S3 read filer buckets dir: /buckets
I0320 16:00:24     1 s3.go:145] connected to filer seaweedfs-filer-localnode.tls.ai:8888 grpc address seaweedfs-filer-localnode.tls.ai:18888
I0320 16:00:24     1 s3.go:178] Start Seaweed S3 API Server 30GB 1.61 at http port 8333
panic: runtime error: index out of range [116] with length 116

goroutine 1300 [running]:
github.com/chrislusf/seaweedfs/weed/s3api.(*S3ApiServer).DeleteMultipleObjectsHandler.func2(0xc00083fbc0, 0x27)
	/go/src/github.com/chrislusf/seaweedfs/weed/s3api/s3api_object_handlers.go:189 +0x26c
github.com/chrislusf/seaweedfs/weed/s3api.(*S3ApiServer).streamRemove.func1.1(0x5648929d2d20, 0xc0005db9c0, 0xc0009417a0, 0xc00084ca20)
	/go/src/github.com/chrislusf/seaweedfs/weed/s3api/filer_util.go:165 +0x42
created by github.com/chrislusf/seaweedfs/weed/s3api.(*S3ApiServer).streamRemove.func1
	/go/src/github.com/chrislusf/seaweedfs/weed/s3api/filer_util.go:153 +0x273
`

**Comment by chrislusf** [comment]
Great! This is a bug and I will try to fix it.

**Comment by chrislusf** [comment]
Added fix. If you do not build from git tip, you may need to wait for the next release.

**Comment by illya-anyvision** [comment]
@chrislusf thank you! and yes we need a new release for this fix.
