### ISSUE TITLE
1.67 | FUSE3: hardlinks are not supported

### ISSUE THREAD

**Issue by onlyjob** [chrislusf/seaweedfs#1243]
```
$ touch 111
$ cp -vl 111 222
'111' -> '222'
cp: cannot create hard link '222' to '111': Input/output error
```

**Comment by chrislusf** [comment]
Correct. Not planned.

**Comment by onlyjob** [comment]
:(

**Comment by onlyjob** [comment]
Proper file system should support hardlinks. Perhaps you could add this feature to roadmap for future implementation?

**Comment by chrislusf** [comment]
No good design for hard link yet. It does not fit current data structure. Welcome any design though!

**Comment by chrislusf** [comment]
FYI: hard link now is supported in git tip.
