### ISSUE TITLE
1.67 | FUSE3: read is slower than write??

### ISSUE THREAD

**Issue by onlyjob** [chrislusf/seaweedfs#1244]
On GNU+Linux amd64, I've started a simplest one node server with data on the 2TB 7200 rpm HDD. I'm copying some large files (e.g. DVD ISO images) at the average speed around 28 MB/s (which is about 25% of speed that I get by copying files directly to underlying _ext4_ partition).
That's on the local machine so network speed is not the limit.  
However reading the files back is merely around 7 MiB/s -- ~4 times slower than write (no concurrency).

**Comment by chrislusf** [comment]
The writes have buffer, but currently the reads do not have buffering. Will add it later.

**Comment by chrislusf** [comment]
Added. Please help to test.
