### ISSUE TITLE
1.67: crash during `filer.copy`: No free volumes left.

### ISSUE THREAD

**Issue by onlyjob** [chrislusf/seaweedfs#1246]
`./weed filer.copy /mnt/md5/dir1/* http://localhost:8888/dir1/` failed as follows:

```
Failed to assign from [localhost:9333]: assign volume failure count:1 replication:"000" parent_path:"/dir1/" : assign volume: rpc error: code = Unknown desc = No free volumes left!
Failed to assign from [localhost:9333]: assign volume failure count:1 replication:"000" parent_path:"/dir1/" : assign volume: rpc error: code = Unknown desc = No free volumes left!
Failed to assign from [localhost:9333]: assign volume failure count:1 replication:"000" parent_path:"/dir1/" : rpc error: code = Unavailable desc = transport is closing
Failed to assign from [localhost:9333]: assign volume failure count:1 replication:"000" parent_path:"/dir1/" : rpc error: code = Unavailable desc = transport is closing
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x154873e]

goroutine 2696 [running]:
github.com/chrislusf/seaweedfs/weed/command.(*FileCopyWorker).uploadFileInChunks.func1(0xc00024c290, 0xc0001000c0, 0xc0004ee300, 0x7ffecaba62e5, 0x3b, 0x7ffecaba67aa, 0x7, 0x500000000, 0x3e8000001b6, 0x3e8, ...)
        /build/seaweedfs-1.67/weed/command/filer_copy.go:420 +0x1ae
created by github.com/chrislusf/seaweedfs/weed/command.(*FileCopyWorker).uploadFileInChunks
        /build/seaweedfs-1.67/weed/command/filer_copy.go:387 +0x398
```

Node (started as `weed server -filer=true`) logged the following:

    needle_parse_upload.go:109] Reading Content [ERROR] unexpected EOF

UI Disk Stats reports 11.60% Usage with 1.56 TiB Free space available. There are 7 volumes.

I was copying few dozen large files, each around 20 GiB.

Why new volumes were not created automatically? Why error was not handled gracefully?
Thanks.

**Comment by chrislusf** [comment]
Because by default there are only 7 volumes allocated. Change that via `weed server -volume.max=50`

**Comment by onlyjob** [comment]
IMHO it should be growing/creating volumes on demand up to available capacity.

**Comment by chrislusf** [comment]
On windows it is hard to detect available capacity. Let me find a way to default to use all disk spaces.

**Comment by onlyjob** [comment]
Thanks. Ironically UI already knows the total and available disk capacity so this is not a situation when available capacity is not determined.

I doubt that worrying about Windows worth the time... Nobody should use it, obviously. ;)

**Comment by chrislusf** [comment]
Added "-max=0" option to auto detect the available disk space on linux.

**Comment by xiaoweihong** [comment]
old version can use ?

**Comment by chrislusf** [comment]
@xiaoweihong no. Need to wait for 1.68
