### ISSUE TITLE
Can you add a tool to check the consistency between filer and volume ?

### ISSUE THREAD

**Issue by zjzdy** [chrislusf/seaweedfs#1249]
Can you add a tool to check the consistency between filer and volume ?
1. Report the records in filer, and the volume lost blocks.
2. Delete the record with block loss from filer. (also delete the non-lost block in the record)
3. Report the blocks that are not recorded in the filer and exist in the volume. (Assuming seaweedfs only uses filer server to upload files)
(May want to consider avoiding detecting blocks of files uploading)
4. Remove 3. reported blocks from volume.

**Comment by zjzdy** [comment]
5. Considering the risk of the delete operation, you can provide a feature to transfer the data that to be deleted to another(or new) seaweedfs server. (data recovery or forensics for future)

**Comment by chrislusf** [comment]
I can build a tool to export <fileId, file> pairs from a filer.
And another tool to export all fileIds from all volumes.

Supposedly you can use unix tools to sort, join, and find out the intersections. Or even some spark jobs to do so.

**Comment by zjzdy** [comment]
This is OK for me, I just need to stop the upload task and clear the untracked blocks caused by upload unexpected interruptions at intervals. (Avoid excessive waste of space due to long-term accumulation or sudden large number of upload exceptions)
But I still hope you can implement this tool in the future, it can be used for disaster recovery check and error detection.
Thanks.

**Comment by chrislusf** [comment]
There could be multiple filers on the same cluster. The assumptions can easily break and the tool can be dangerous.

**Comment by zjzdy** [comment]
Yes, I also think this tool is dangerous, but its danger is manageable, after all, this is not an APP for ordinary consumers. 
All features are optional. Operations 1 and 3 are used to generate read-only reports. Option 5 is used to reduce the risks of operations 2 and 4.
Among them, the user may be unclear about the assumptions and cause misoperation, but I think that is sufficient to avoid it through specific explanation or secondary confirmation.
If you are also worried about this, you can ask the user to enter all the addresses of the "weed filer" running on the volume for confirmation. It is better if you also consider directly support multiple filer :）

**Comment by chrislusf** [comment]
Added a `weed shell` command `volume.fsck`.

`echo volume.fsck | weed shell`
