### ISSUE TITLE
docker 版本 volume -ip 设置无效

### ISSUE THREAD

**Issue by yunluo213** [chrislusf/seaweedfs#1250]
docker命令：
docker run -p 9021:9021 -v /volume1:/data --name volume1 chrislusf/seaweedfs volume -max=100 -mserver=192.168.1.1:9011 -ip=192.168.1.1 -port=9021 -publicUrl=192.168.1.1:9021

volume信息：
dataNodes=[DataNode{url='http://127.0.0.1:9021', pubilcUrl='http://192.168.1.1:9021', volumes=7, free=93, max=100}]}]}

正常来说volume中url的值应该与docker run 中-ip值匹配 192.168.1.1:9021

ps:虽然我可以设置publicUrl，并使用此地址上传下载文件

**Comment by chrislusf** [comment]
The latest dev version should work. Try this:

`docker run -p 9021:9021 -v /volume1:/data --name volume1 chrislusf/seaweedfs:dev volume -max=100 -mserver=192.168.1.1:9011 -ip=192.168.1.1 -port=9021 -publicUrl=192.168.1.1:9021`
