### ISSUE TITLE
DeleteMultipleObjectsHandler is not honoring filer.options.recursive_delete

### ISSUE THREAD

**Issue by LazyDBA247-Anyvision** [chrislusf/seaweedfs#1251]
Hi Chris,

using 1.67, DeleteMultipleObjectsHandler is not checking the filer option:
filer.options.recursive_delete = true
and sends by default isRecursive=false

can we make DeleteMultipleObjectsHandler supports the same logic as DeleteHandler:
https://github.com/chrislusf/seaweedfs/blob/c0f0fdb3baeb6e9852c6876b23c1404b2c5e833d/weed/server/filer_server_handlers_write.go#L299

10x!

**Comment by chrislusf** [comment]
this is for S3 and does not need to follow filer.
changing it to ftrue.
