### ISSUE TITLE
Volume server cannot resize an image

### ISSUE THREAD

**Issue by binwu5** [chrislusf/seaweedfs#1252]
**Describe the bug**
`weed version`  8000GB 1.63 linux amd64

For the same image, just one volume server can do resizing, and other replication servers cannot . 
The get request via master server redirects to one volume server,  so the original image may be getted.

Log:
E0327 18:09:37 56703 resizing.go:51] image: unknown format

**Comment by chrislusf** [comment]
Not very clear on how to reproduce this. There are fixes related to this in recent versions. Please check v1.69

**Comment by binwu5** [comment]
I have checked v1.70.  The image cannot be resized by the way using fid.

Upload a new image via filer, assuming file path=/test/new.jpg and fid=1,ad23adf, then there are two way to resize the image.

- Use file path, like `http://filer_ip:port/test/new.jpg?width=xxx&height=xxx`. This way is normal.

- Use fid, like `http://volume_ip:port/1,ad23adf?width=xxx&height=xxx` or `http://master_ip:port/1,ad23adf?width=xxx&height=xxx`.  The image is not be resized, and the volume server outputs log `resizing.go:51] image: unknown format`.

I think the resizing problem is introduced from a middle version, because resizing a early already uploaded image by the way using fid is normal. This is confused, why can't new uploaded images be resized?

**Comment by chrislusf** [comment]
try to use http://volume_ip:port/1,ad23adf.jpg?width=xxx&height=xxx

**Comment by chrislusf** [comment]
volume server resizing is not supported if uploaded via filer directly. Need to use filer url to resize.

**Comment by chrislusf** [comment]
added a fix for this fee3319cbf4ed88f79c6e7fe19bada2bddabbb85
