### ISSUE TITLE
filer failed to connect with master localhost:9333: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:19333: i/o timeout

### ISSUE THREAD

**Issue by orange-jacky** [chrislusf/seaweedfs#1256]
**Describe the bug**
I0402 13:59:50 15839 masterclient.go:73] filer failed to keep connected to localhost:9333: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:19333: i/o timeout"
I0402 13:59:50 15839 masterclient.go:116] filer failed to connect with master localhost:9333: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:19333: i/o timeout"
I0402 14:00:11 15839 masterclient.go:73] filer failed to keep connected to localhost:9333: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:19333: i/o timeout"
I0402 14:00:11 15839 masterclient.go:116] filer failed to connect with master localhost:9333: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:19333: i/o timeout"
I0402 14:00:32 15839 masterclient.go:73] filer failed to keep connected to localhost:9333: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:19333: i/o timeout"
I0402 14:00:32 15839 masterclient.go:116] filer failed to connect with master localhost:9333: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:19333: i/o timeout"
I0402 14:00:53 15839 masterclient.go:73] filer failed to keep connected to localhost:9333: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:19333: i/o timeout"
I0402 14:00:53 15839 masterclient.go:116] filer failed to connect with master localhost:9333: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:19333: i/o timeout"
I0402 14:01:14 15839 masterclient.go:73] filer failed to keep connected to localhost:9333: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:19333: i/o timeout"
I0402 14:01:14 15839 masterclient.go:116] filer failed to connect with master localhost:9333: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:19333: i/o timeout"

I0402 14:01:35 15839 masterclient.go:73] filer failed to keep connected to localhost:9333: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:19333: i/o timeout"
I0402 14:01:35 15839 masterclient.go:116] filer failed to connect with master localhost:9333: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:19333: i/o timeout"
I0402 14:01:56 15839 masterclient.go:73] filer failed to keep connected to localhost:9333: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:19333: i/o timeout"
I0402 14:01:56 15839 masterclient.go:116] filer failed to connect with master localhost:9333: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:19333: i/o timeout"
I0402 14:02:17 15839 masterclient.go:73] filer failed to keep connected to localhost:9333: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:19333: i/o timeout"
I0402 14:02:17 15839 masterclient.go:116] filer failed to connect with master localhost:9333: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:19333: i/o timeout"
I0402 14:02:38 15839 masterclient.go:73] filer failed to keep connected to localhost:9333: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:19333: i/o timeout"
I0402 14:02:38 15839 masterclient.go:116] filer failed to connect with master localhost:9333: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:19333: i/o timeout"
I0402 14:02:59 15839 masterclient.go:73] filer failed to keep connected to localhost:9333: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:19333: i/o timeout"
I0402 14:02:59 15839 masterclient.go:116] filer failed to connect with master localhost:9333: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:19333: i/o timeout"
I0402 14:03:20 15839 masterclient.go:73] filer failed to keep connected to localhost:9333: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:19333: i/o timeout"
I0402 14:03:20 15839 masterclient.go:116] filer failed to connect with master localhost:9333: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:19333: i/o timeout"
I0402 14:03:41 15839 masterclient.go:73] filer failed to keep connected to localhost:9333: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:19333: i/o timeout"
I0402 14:03:41 15839 masterclient.go:116] filer failed to connect with master localhost:9333: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:19333: i/o timeout"
I0402 14:04:02 15839 masterclient.go:73] filer failed to keep connected to localhost:9333: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:19333: i/o timeout"
I0402 14:04:02 15839 masterclient.go:116] filer failed to connect with master localhost:9333: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:19333: i/o timeout"
I0402 14:04:23 15839 masterclient.go:73] filer failed to keep connected to localhost:9333: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:19333: i/o timeout"
I0402 14:04:23 15839 masterclient.go:116] filer failed to connect with master localhost:9333: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:19333: i/o timeout"
I0402 14:04:44 15839 masterclient.go:73] filer failed to keep connected to localhost:9333: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:19333: i/o timeout"
I0402 14:04:44 15839 masterclient.go:116] filer failed to connect with master localhost:9333: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:19333: i/o timeout"
I0402 14:05:05 15839 masterclient.go:73] filer failed to keep connected to localhost:9333: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:19333: i/o timeout"
I0402 14:05:05 15839 masterclient.go:116] filer failed to connect with master localhost:9333: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:19333: i/o timeout"
I0402 14:05:26 15839 masterclient.go:73] filer failed to keep connected to localhost:9333: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:19333: i/o timeout"
I0402 14:05:26 15839 masterclient.go:116] filer failed to connect with master localhost:9333: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:19333: i/o timeout"
I0402 14:05:47 15839 masterclient.go:73] filer failed to keep connected to localhost:9333: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:19333: i/o timeout"
I0402 14:05:47 15839 masterclient.go:116] filer failed to connect with master localhost:9333: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:19333: i/o timeout"
I0402 14:06:08 15839 masterclient.go:73] filer failed to keep connected to localhost:9333: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:19333: i/o timeout"
I0402 14:06:08 15839 masterclient.go:116] filer failed to connect with master localhost:9333: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:19333: i/o timeout"
I0402 14:06:29 15839 masterclient.go:73] filer failed to keep connected to localhost:9333: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:19333: i/o timeout"
I0402 14:06:29 15839 masterclient.go:116] filer failed to connect with master localhost:9333: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:19333: i/o timeout"

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

version 30GB 1.70 linux amd64

./weed server -master.port=9333 -volume.port=8080 -dir="./data"

./weed scaffold -config=filer -output="."
vi filer.toml
 [leveldb]
enabled = true
dir = "./leveldb"					# directory to store level db files

./weed filer > filer_stdout.log 2>&1 &

**Comment by chrislusf** [comment]
check 19333 is open or not.

**Comment by orange-jacky** [comment]
port 9333 19333 stay, and i fount master server always fake stop

**Comment by orange-jacky** [comment]
I0402 22:48:49 10649 masterclient.go:88] filer failed to receive from localhost:9333: rpc error: code = Canceled desc = grpc: the client connection is closing
I0402 22:48:49 10649 masterclient.go:116] filer failed to connect with master localhost:9333: rpc error: code = Canceled desc = grpc: the client connection is closing
I0402 22:51:07 10649 masterclient.go:88] filer failed to receive from localhost:9333: rpc error: code = Canceled desc = grpc: the client connection is closing
I0402 22:51:07 10649 masterclient.go:116] filer failed to connect with master localhost:9333: rpc error: code = Canceled desc = grpc: the client connection is closing
I0402 22:53:37 10649 masterclient.go:88] filer failed to receive from localhost:9333: rpc error: code = Canceled desc = grpc: the client connection is closing
I0402 22:53:37 10649 masterclient.go:116] filer failed to connect with master localhost:9333: rpc error: code = Canceled desc = grpc: the client connection is closing
I0402 22:53:54 10649 masterclient.go:88] filer failed to receive from localhost:9333: rpc error: code = Canceled desc = grpc: the client connection is closing
I0402 22:53:54 10649 masterclient.go:116] filer failed to connect with master localhost:9333: rpc error: code = Canceled desc = grpc: the client connection is closing
I0402 22:54:26 10649 masterclient.go:88] filer failed to receive from localhost:9333: rpc error: code = Canceled desc = grpc: the client connection is closing
I0402 22:54:26 10649 masterclient.go:116] filer failed to connect with master localhost:9333: rpc error: code = Canceled desc = grpc: the client connection is closing
I0402 22:54:32 10649 masterclient.go:88] filer failed to receive from localhost:9333: rpc error: code = Canceled desc = grpc: the client connection is closing
I0402 22:54:32 10649 masterclient.go:116] filer failed to connect with master localhost:9333: rpc error: code = Canceled desc = grpc: the client connection is closing
I0402 22:58:23 10649 masterclient.go:88] filer failed to receive from localhost:9333: rpc error: code = Canceled desc = grpc: the client connection is closing
I0402 22:58:23 10649 masterclient.go:116] filer failed to connect with master localhost:9333: rpc error: code = Canceled desc = grpc: the client connection is closing
I0402 23:03:40 10649 masterclient.go:88] filer failed to receive from localhost:9333: rpc error: code = Canceled desc = grpc: the client connection is closing
I0402 23:03:40 10649 masterclient.go:116] filer failed to connect with master localhost:9333: rpc error: code = Canceled desc = grpc: the client connection is closing
I0402 23:05:15 10649 masterclient.go:88] filer failed to receive from localhost:9333: rpc error: code = Canceled desc = grpc: the client connection is closing
I0402 23:05:15 10649 masterclient.go:116] filer failed to connect with master localhost:9333: rpc error: code = Canceled desc = grpc: the client connection is closing
I0402 23:08:06 10649 masterclient.go:88] filer failed to receive from localhost:9333: rpc error: code = Canceled desc = grpc: the client connection is closing
I0402 23:08:06 10649 masterclient.go:116] filer failed to connect with master localhost:9333: rpc error: code = Canceled desc = grpc: the client connection is closing
I0402 23:23:56 10649 masterclient.go:88] filer failed to receive from localhost:9333: rpc error: code = Canceled desc = grpc: the client connection is closing
I0402 23:23:56 10649 masterclient.go:116] filer failed to connect with master localhost:9333: rpc error: code = Canceled desc = grpc: the client connection is closing

**Comment by ijunaid8989** [comment]
@orange-jacky your port 19333 is open through Firewall or not?  if not then allows its connection to port 9333 and 9333's to 19333.

**Comment by orange-jacky** [comment]
> @orange-jacky your port 19333 is open through Firewall or not? if not then allows its connection to port 9333 and 9333's to 19333.

master, volume, filer run the same host,  not through firewall, port 9333 and 19333 still stay, and telent localhost 9333, it works.

[ubuntu@VM-0-3-ubuntu seaweedfs]$ss -tnlp | grep weed
LISTEN   0         128                       *:8080                   *:*        users:(("weed",pid=10505,fd=13))                                               
LISTEN   0         128                       *:9333                   *:*        users:(("weed",pid=10505,fd=9))                                                
LISTEN   0         128                       *:8888                   *:*        users:(("weed",pid=10649,fd=42))                                               
LISTEN   0         128                       *:18080                  *:*        users:(("weed",pid=10505,fd=12))                                               
LISTEN   0         128                       *:19333                  *:*        users:(("weed",pid=10505,fd=11))                                               
LISTEN   0         128                       *:18888                  *:*        users:(("weed",pid=10649,fd=43))   


[ubuntu@VM-0-3-ubuntu seaweedfs]$telnet  localhost 9333
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
^C
Connection closed by foreign host.
[ubuntu@VM-0-3-ubuntu seaweedfs]$telnet  localhost 19333
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
@^C

and filer still ouput rpc localhost:9333 err. it's strange

**Comment by chrislusf** [comment]
can not diagnose this. Maybe create some docker image to make it reproducible.

**Comment by yhan219** [comment]
I installed it using docker-compose. I have been using port 9333, so yesterday I closed port 19333 on the firewall, and now the same error appears. As you know, the port is not safe to open to the external network. How can I close 19333 on the external network and change the ip of the gprc to the ip of the internal network?

eg:
my external ip:14.215.177.39
my internal ip:192.168.10.105
my error log:

```
I0205 07:27:08     1 common.go:51] response method:POST URL:/submit?ttl=10d&collection=work with httpStatus:500 and JSON:{"error":"rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 4.215.177.39:19333: i/o timeout\""}
```
How can I make it access 192.168.10.105 instead of 14.215.177.39?

**Comment by lucsgiovanne** [comment]
I've had the same issue while using distributed volumes. On the master machine I needed to allow both 9333/tcp and 19333/tcp connections from any to stop the firewall from shutting down the connections and causing this error.

**Comment by chrislusf** [comment]
> I needed to allow both 9333/tcp and 19333/tcp connections from any

Yes. But what is the issue?

**Comment by lucsgiovanne** [comment]
> Yes. But what is the issue?

None. I'm sorry if I used this topic wrongly. I just intended to help whoever find the same issue to solve it faster than I did.

**Comment by GeorgeWang1994** [comment]
I've had the same issue while using distributed volumes
