### ISSUE TITLE
1.70/FUSE: Cannot close target file I/O error 5

### ISSUE THREAD

**Issue by onlyjob** [chrislusf/seaweedfs#1257]
I'm trying to copy file using FUSE client. Writing of file seemingly progresses to 100% when the error "Cannot close target file; I/O error (5)" is thrown.

Mount logs the following:

```
I0403 17:30:22 32276 dirty_page.go:133] /test/{FILENAME} saveToStorage [319627264,322379776): filerGrpcAddress assign volume: assign volume failure count:1 parent_path:"/test" : assign volume: failed to parse master grpc : server should have hostname:port format:
E0403 17:30:22 32276 filehandle.go:119] /test/{FILENAME} write fh 0: [322248704,322379776): filerGrpcAddress assign volume: assign volume failure count:1 parent_path:"/test" : assign volume: failed to parse master grpc : server should have hostname:port format:
```

As many Seaweedfs issues, this one is probably have something to do with configuration but ambiguous error messages like the above at the end of long operation that is clearly failed make SeaweedFS so difficult even to begin using...

I have no idea what is wrong but the created file is empty (filled with zeroes) which should not be.

Any advise? Why did file copy not abort with "out of space" or "read-only file system"? Thanks.

**Comment by chrislusf** [comment]
Please follow issue template and show your mount command, and command for filer, master, etc.

**Comment by onlyjob** [comment]
Regardless, error messages should me more informative and error handling be more robust.

**Comment by onlyjob** [comment]
Server is started as follows:

```
./weed server \
    -master.port=9333 \
    -master.dir=/mnt/hdd1/weed/metadata \
    -volume.port=9334 -dir=/mnt/hdd1/weed/data -volume.max=0 \
    -filer=true -filer.port=8888 \
;
```

Client mount is the simplest possible: `./weed mount -dir=/mnt/weed`.

`weed` executable is from `linux_amd64_large_disk`, v1.70.

FUSE mount is completely unusable, unable to receive files as described. :(

**Comment by chrislusf** [comment]
Added a fix to fail fast if wrong master is configured, rather than very late.

**Comment by chrislusf** [comment]
Maybe your server has less than 30GB disk space. When starting server, try to add `-master.volumeSizeLimitMB=1000`.

**Comment by onlyjob** [comment]
Looks like it fails to grow volumes as directory `data` is empty.

```
I0403 18:50:34 42437 dirty_page.go:133] /rsnap-tst.hashes-enc.sha1.md5 saveToStorage [0,60): filerGrpcAddress assign volume: assign volume failure count:1 parent_path:"/" : assign volume: rpc error: code = Unknown desc = No free volumes left!
E0403 18:50:34 42437 filehandle.go:159] flush /rsnap-tst.hashes-enc.sha1.md5: filerGrpcAddress assign volume: assign volume failure count:1 parent_path:"/" : assign volume: rpc error: code = Unknown desc = No free volumes left!
```

**Comment by onlyjob** [comment]
`-master.volumeSizeLimitMB=1000` did not help. Why would it be necessary?
That fiddling with volumes is very confusing...

Might be related to #1246.

**Comment by chrislusf** [comment]
Your command worked for me. What's the output for `curl "http://localhost:9333/dir/status?pretty=y"`

**Comment by chrislusf** [comment]
ok. now I can reproduce it. I need to use the large_disk version and set the volume size to be very large, so that no free volumes can be allocated.

**Comment by chrislusf** [comment]
I wonder why the `-volume.max=0` is not working. Maybe need to wait a bit. check http://localhost:9333/ to see how many volumes are allocated.

**Comment by onlyjob** [comment]
No volumes are allocated and the `data` directory is empty...

**Comment by chrislusf** [comment]
Wondering whether you find out why no volume is allocated. Maybe just set the volume.max directly, to narrow down where the problem is.

**Comment by onlyjob** [comment]
I suspect software bug to be a culprit. Whet else could it be? (Definitely not a file system permission issue, I've checked...) What's the point to allocate volumes manually when I need a dynamic on-demand allocation?

**Comment by chrislusf** [comment]
Need to have a way to reproduce this. May be related to disk space
reporting.

**Comment by chrislusf** [comment]
I added a file to use the same code to read disk status. https://github.com/chrislusf/seaweedfs/blob/master/unmaintained/check_disk_size/check_disk_size.go

Not sure your Go experience. But this file has no extra dependency at all. Just install go, and run it this way, and share the output.
``` 
# check current directory
go run check_disk_size.go

# check specified directory
go run check_disk_size.go -dir=/mnt/hdd1/weed/data

```

**Comment by onlyjob** [comment]
Thanks. Running `check_disk_size.go` returned the following:

```
statfs: {Type:4076150800 Bsize:4096 Blocks:488378134 Bfree:249574929 Bavail:249574929 Files:6056957 Ffree:530444 Fsid:{X__val:[66304 0]} Namelen:255 Frsize:4096 Flags:4128 Spare:[0 0 0 0]}

Total: 488378134 blocks x 4096 block size = 2000396836864 bytes
Free : 249574929 blocks x 4096 block size = 1022258909184 bytes
Used : 238803205 blocks x 4096 block size = 978137927680 bytes
Free Percentage : 51.10%
Used Percentage : 48.90%
OS: linux
Arch: amd64
```

File system is _f2fs_, there are 500K+ free inodes so the file system is perfectly usable...

**Comment by chrislusf** [comment]
So the disk reading is correct. Do you see logs printed out by this line? And what's the output? https://github.com/chrislusf/seaweedfs/blob/master/weed/storage/store.go#L424

```
glog.V(0).Infof("disk %s max %d unclaimedSpace:%dMB, unused:%dMB volumeSizeLimit:%d/MB", ...)
```

**Comment by onlyjob** [comment]
The following is logged by _server_ during attempt to write a file to FUSE mount:

```
I0405 14:29:57 58928 masterclient.go:88] filer failed to receive from localhost:9333: rpc error: code = Canceled desc = grpc: the client connection is closing
I0405 14:29:57 58928 masterclient.go:116] filer failed to connect with master localhost:9333: rpc error: code = Canceled desc = grpc: the client connection is closing
I0405 14:29:57 58928 masterclient.go:88] master failed to receive from localhost:9333: rpc error: code = Unavailable desc = transport is closing
I0405 14:29:57 58928 masterclient.go:116] master failed to connect with master localhost:9333: rpc error: code = Unavailable desc = transport is closing
I0405 14:29:57 58928 master_grpc_server.go:258] - client filer@127.0.0.1:18888
I0405 14:29:57 58928 master_grpc_server.go:258] - client master@127.0.0.1:53130
I0405 14:29:58 58928 master_grpc_server.go:247] + client master@127.0.0.1:54008
I0405 14:29:58 58928 master_grpc_server.go:247] + client filer@127.0.0.1:18888
```

The following is logged by _FUSE client_:

```
I0405 14:29:57 59006 dirty_page.go:133] /{{FILENAME}} saveToStorage [0,60): filerGrpcAddress assign volume: assign volume failure count:1 parent_path:"/" : assign volume: rpc error: code = Unknown desc = No free volumes left!
E0405 14:29:57 59006 filehandle.go:159] flush /{{FILENAME}}: filerGrpcAddress assign volume: assign volume failure count:1 parent_path:"/" : assign volume: rpc error: code = Unknown desc = No free volumes left!
```

**Comment by onlyjob** [comment]
Of course `-volume.max=0` is the culprit.
I've removed that option and 7 volumes were created automatically and I could copy the file to FUSE mount successfully.

Apparently `-volume.max=0` prevents creation of volumes, at least initially.

**Comment by onlyjob** [comment]
Also during copy of a large file FUSE client is being noisy, logging the following repeatedly:

```
E0405 14:52:50 59006 filehandle.go:111] /{{FILENAME}} write fh 0: [51010764800,51010895872): filerGrpcAddress assign volume: assign volume failure count:1 parent_path:"/" : assign volume: failed to parse master grpc : server should have hostname:port format:
```

**Comment by chrislusf** [comment]
Need to see the full server log.

**Comment by onlyjob** [comment]
Ah, my bad, at some point I think I've been mistakenly running older 1.67 binary instead of the 1.70  due to incorrect path in shell script... Sorry for noise and thank you for patience.

Let me re-test everything from scratch. I'll close this ticket shortly if everything is all right (or provide complete and accurate details with 1.70)...

**Comment by onlyjob** [comment]
1.70/FUSE failed to save a large file (~350G) with `Cannot close target file I/O error 5` at the end of copying. Mount failed and exited printing only the following to the console:

```
E0405 20:22:49 90542 filehandle.go:210] fh flush create /test/rsnap-tst.tar.xz: CreateEntry: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (98176147 vs. 4194304)
E0405 20:22:49 90542 filehandle.go:227] /test/rsnap-tst.tar.xz fh 0 flush: fh flush create /test/rsnap-tst.tar.xz: CreateEntry: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (98176147 vs. 4194304)
```

Volumes were growing successfully during copy and server was logging no errors.

**Comment by chrislusf** [comment]
I will address this. This is because the gRPC has a message size limit of 4MB. The meta data for the 350GB file is 98MB.

**Comment by chrislusf** [comment]
Added a temporary fix to increase the message size limit to 1GB. 

Later release will add another level of indirection for much larger or unlimited file size.
