### ISSUE TITLE
mount: confusing handling of filer port

### ISSUE THREAD

**Issue by onlyjob** [chrislusf/seaweedfs#1259]
`./weed mount -h` suggests that default `-filer` is `"localhost:8888"`. But attempting to mount without parameters throws the following error:

```
F0403 18:13:29 38160 mount_std.go:158] get filer localhost:18888 configuration: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:18888: connect: connection refused"                                                                                      
```

When mount is attempted with `-filer=localhost:18888` option it fails as follows:

```
F0403 18:16:57 38534 mount_std.go:158] get filer localhost:28888 configuration: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:28888: connect: connection refused"
```

So the actual `-filer` port is the given port + 10000 ??

Can it made less confusing please?

**Comment by chrislusf** [comment]
port + 10000 is the grpc address. Added a fix, but not sure how to make it easier to understand. Welcome suggestions!

**Comment by onlyjob** [comment]
Thanks. Maybe explaining what "grpc address" is, and documenting its relationships with filer could help??
If user tries to configure a "filer" port, why error is about "grpc" port?
Why "grpc" port is "filer" port + 10000??

**Comment by chrislusf** [comment]
Need to have two ports, for rest API and gRPC API.

+10000 is the same approach as Redis.
