### ISSUE TITLE
Suggested feature: weed master -weight

### ISSUE THREAD

**Issue by antitbone** [chrislusf/seaweedfs#1261]
This is not a bug but a suggestion of functionality.

In the case of a cluster with several master nodes it can be interesting to control which of the masters is elected.

"weed master" could have an optional additional parameter to change the weight of the master.
The default weight could be 100 if no parameter is defined.

**Example 1:**
Two main dc (dc1 and dc2)
- volume and filer nodes
- 1xx replication
- a master node.

Another dc (dc3) with only one master node.
- lower connectivity with higher latency

In case of loss of dc1 or dc2 it is preferable that the master passes to the second main dc.
dc3 master: "weed master -weight 90 ..."

**Example 2:**
Same configuration as example 1 but dc2 is only used as a backup site.
All access to the filers is performed on dc1.

It is preferable to have the master active on dc1.
dc1 master: "weed master -weight 110 ..."
dc3 master: "weed master -weight 90 ..."

Antoine

**Comment by chrislusf** [comment]
I understand the need. but this would not be trivial to implement on top of current raft protocol.

To "move" the leader, you can try to start the masters in the "main" dc first.

**Comment by chrislusf** [comment]
closing because unlikely this will be implemented.
