### ISSUE TITLE
Question regarding erasure coding

### ISSUE THREAD

**Issue by Gronis** [chrislusf/seaweedfs#1262]
Hi,

I've been reading through the docs trying to understand seaweedfs, but I have a few questions regarding erasure coding that could not be answered by simply study the docs.

### How does erasure coding works when a volume is replicated?
Lets say a volume is 3x replicated and > 95% saturated. Then after a `weed ec.encode` command is selected for erasure coding, are all replications of the selected volume replaced with erasure encoded versions, and the replicated versions removed?

Thank you.

**Comment by chrislusf** [comment]
Hi, only one of the replicated volume data will be erasure encoded. And the replicated versions will be removed. 

Thanks for the question. I will add this to the doc.
