### ISSUE TITLE
quick start guide

### ISSUE THREAD

**Issue by onlyjob** [chrislusf/seaweedfs#1263]
Please document (with examples) 

 * how to start multi-master cluster with nodes on different machines

 * how to start multiple volume servers 
   * how to use multiple HDDs on a single server
   * replicating between servers, not volumes on the same machine

 * FUSE guide: minimum requirements to replicate 3 copies between different machines
   * best practice for Filer? Run on every node?
   * Is there a fail-over for FUSE client?
   * Why FUSE client needs Filer?
   * Is there replication support in FUSE client? (can't copy file to FUSE mount with `defaultReplication=001`)

  * `-filer.defaultReplicaPlacement=001` is the same as `-master.defaultReplication=001` or redundant?

Background: I'm frustrated with how ridiculously difficult it is to setup even simplest multi-node SeaweedFS for testing. I've been doing distributed file systems for years, working with at least 8 of them yet SeaweedFS defeats me with hard to understand errors on every attempt to design even simplest replicated test setup. Practical HOWTO guide would be much appreciated.

IMHO Wiki examples are difficult to adapt for nodes on different servers.

**Comment by chrislusf** [comment]
For most commands, see `weed filer -h`, `weed mount -h`, etc for help messages.

> * how to start multi-master cluster with nodes on different machines

https://github.com/chrislusf/seaweedfs/wiki/Failover-Master-Server

> * how to start multiple volume servers

https://github.com/chrislusf/seaweedfs/wiki/Replication

>   * how to use multiple HDDs on a single server

Just start another volume server.

>   * replicating between servers, not volumes on the same machine

Treat the same machine as a rack, when starting the volume server.

> * FUSE guide: minimum requirements to replicate 3 copies between different machines

`weed mount -replication=020`, assuming each machine is used as a rack.

>   * best practice for Filer? Run on every node?

Setup a shared filer store. https://github.com/chrislusf/seaweedfs/wiki/Filer-Stores

>   * Is there a fail-over for FUSE client?

FUSE client runs on each server. No failover.

The filer is stateless. You can use nginx to proxy to multiple filers.

>   * Why FUSE client needs Filer?

The filer can be shared. 

>   * Is there replication support in FUSE client? (can't copy file to FUSE mount with `defaultReplication=001`)

`weed mount -replication`. 

> * `-filer.defaultReplicaPlacement=001` is the same as `-master.defaultReplication=001` or redundant?

Actually the `weed mount` also has the replication setting. The Filer setting is for files default replication. The Master setting is for object store default replication. You do not need to set them if the upper level set it already.


The system has many components. But it should be simple. There must be something you did not get yet. Just play with it and no need to run now. Let me know you aha moment.

**Comment by onlyjob** [comment]
> For most commands, see weed filer -h, weed mount -h, etc for help messages.

Seriously, this is obvious and not very helpful to point it out.

I'm aware of those wiki pages and I've filed this issue because they are insufficient.
Pointing out the very documents with incomplete or non-working instructions is hardly a solution to flaws in those documents.

>> how to use multiple HDDs on a single server?

> Start another volume server on the same machine.

Hmm, that's not ideal. I may have to run 20 volume servers on one machine and avoid port conflicts between them somehow.

> weed mount -replication=020, assuming each machine is used as a rack.

_Any_ replication other than `000` renders FUSE mount completely unusable throwing the following for every saved file, with files being empty at the end of copying:

    assign volume: failed to parse master : server should have hostname:port format

> The system has many components. But it should be simple.

It is anything but simple... :(

Take it from someone who operated Ceph, LizardFS, MooseFS, GlusterFS, XtremeFS, RozoFS, etc.

> There must be something you did not get yet. Just play with it and no need to run now. Let me know you aha moment.

What I get so far is _prohibitive amount of bugs in FUSE layer._

Have been "playing" too long already not being able to achieve a simplest replicated setup with FUSE client. My conclusion is "too immature to be used", without working setup example in docs/wiki. I'm nowhere near that "aha" moment. :(  Very disappointed, might come back in a year or so if development continues...

**Comment by chrislusf** [comment]
> > > how to use multiple HDDs on a single server?
> 
> > Start another volume server on the same machine.
> 
> Hmm, that's not ideal. I may have to run 20 volume servers on one machine and avoid port conflicts between them somehow.

You can also use `weed volume -dir=dir1,dir2,dir3`.


> > weed mount -replication=020, assuming each machine is used as a rack.
> 
> _Any_ replication other than `000` renders FUSE mount completely unusable throwing the following for every saved file, with files being empty at the end of copying:
> 
> ```
> assign volume: failed to parse master : server should have hostname:port format
> ```

Can not reproduce this.

So far, in release 1.71, the known bug https://github.com/chrislusf/seaweedfs/issues/1257 has a temporary fix for TB-sized files. Other known bugs have been fixed. Thanks for all the testing!

**Comment by onlyjob** [comment]
> You can also use weed volume -dir=dir1,dir2,dir3.

Awesome! Thanks.

> Can not reproduce this.

Unbelievable... I'll see if I can find energy to report in a dedicated new issue. So far it's been very frustrating to struggle from one bug to another without end in sight...

**Comment by chrislusf** [comment]
Added https://github.com/chrislusf/seaweedfs/wiki/Production-Setup

**Comment by onlyjob** [comment]
Very good, thanks!

**Comment by krakazyabra** [comment]
> You can also use `weed volume -dir=dir1,dir2,dir3`

I tried to add several filesystems to the variable `-dir`, but got error  
```
root@storage12:/data# ./weed volume -dir=data1,data2,data3
F0601 15:38:06 22585 volume.go:117] 3 directories by -dir, but only 1 max is set by -max
goroutine 1 [running]:
github.com/chrislusf/seaweedfs/weed/glog.stacks(0xc000548900, 0xc0001c8e40, 0x59, 0xb4)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:767 +0xb8
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).output(0x2efdb40, 0xc000000003, 0xc00052de30, 0x2e24ec3, 0x9, 0x75, 0x0)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:718 +0x351
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).printf(0x2efdb40, 0xc000000003, 0x1c5917d, 0x36, 0xc0008dfbf8, 0x2, 0x2)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:656 +0x14b
github.com/chrislusf/seaweedfs/weed/glog.Fatalf(...)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:1149
github.com/chrislusf/seaweedfs/weed/command.VolumeServerOptions.startVolumeServer(0xc000041140, 0xc000041160, 0xc000548810, 0x3, 0x3, 0xc000041e00, 0x1, 0x1, 0xc000530b60, 0xc000530b70, ...)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/command/volume.go:117 +0xd06
github.com/chrislusf/seaweedfs/weed/command.runVolume(0x2ee72c0, 0xc00003a1a0, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/command/volume.go:99 +0x116
main.main()
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/weed.go:66 +0x2f9
```
Also I specified `-max` variable, but it seems, that `weed volume` ignores this
```
root@storage12:/data# ./weed volume -max=200 -dir=data1,data2,data3
F0601 15:41:36 25146 volume.go:117] 3 directories by -dir, but only 1 max is set by -max
goroutine 1 [running]:
github.com/chrislusf/seaweedfs/weed/glog.stacks(0xc000546600, 0xc000260e40, 0x59, 0xb4)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:767 +0xb8
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).output(0x2efdb40, 0xc000000003, 0xc0006858f0, 0x2e24ec3, 0x9, 0x75, 0x0)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:718 +0x351
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).printf(0x2efdb40, 0xc000000003, 0x1c5917d, 0x36, 0xc0008cbbf8, 0x2, 0x2)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:656 +0x14b
github.com/chrislusf/seaweedfs/weed/glog.Fatalf(...)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:1149
github.com/chrislusf/seaweedfs/weed/command.VolumeServerOptions.startVolumeServer(0xc0000404c0, 0xc0000404d0, 0xc000546570, 0x3, 0x3, 0xc000041230, 0x1, 0x1, 0xc0000f35b0, 0xc0000f35c0, ...)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/command/volume.go:117 +0xd06
github.com/chrislusf/seaweedfs/weed/command.runVolume(0x2ee72c0, 0xc0001bc070, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/command/volume.go:99 +0x116
main.main()
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/weed.go:66 +0x2f9
```

**Comment by krakazyabra** [comment]
Sorry, my bad, but it is so unobvious:
```
./weed volume -max=0,0,0 -dir=data1,data2,data3
```
We need to specify `-max` for each volume.
