### ISSUE TITLE
Config path for database storage

### ISSUE THREAD

**Issue by dazoot** [chrislusf/seaweedfs#1265]
We store the files on a shared drive (cifs mounted).
We have local SSD drives.
Would like to specify the `weed volume` server to used an alternate folder for database storage.
So instead of storing .idx files on the network drive, store them local on fast SSD.

**Comment by chrislusf** [comment]
Which volume index are you using? memory or leveldb?

Well, yes, there will be two writes, one to .dat and one to .idx files.

If in memory, seems no need to store the index on SSD specifically, especially for reads.

**Comment by dazoot** [comment]
Leveldb.

**Comment by chrislusf** [comment]
In your case, how large are the SSD and HDD sizes respectively?

**Comment by dazoot** [comment]
we store 5TB of data.
SSD is 960GB

**Comment by chrislusf** [comment]
ok. btw: planning to support ssd-only volumes. would that be useful to your use case?

**Comment by dazoot** [comment]
Should be configurable:
- data_storage paths
- index_storage paths

So users can choose what suits them better.

**Comment by chrislusf** [comment]
Added this feature. Let me know how it works for you.

**Comment by chrislusf** [comment]
fixed in 2.13
