### ISSUE TITLE
replication guarantee / auto replication

### ISSUE THREAD

**Issue by onlyjob** [chrislusf/seaweedfs#1267]
Masters should automatically maintain replication level.

For example, with replication `001` and two volume servers, I'm adding a third volume server then stopping a second one yet no automatic replication is happening to ensure safety of data.

**Comment by chrislusf** [comment]
The automatic rebalancing will be problematic in large clusters. It can cause unexpected busy network activities, for example, the heartbeat may come and go, causing unnecessary busy system. Current recommended strategy is to keep existing data readonly, and automatically add new writable volumes.

There are `volume.balance` and `volume.fix.replication` commands in `weed shell`. You can configure them to run during off hours.

Will add them to the wiki.

**Comment by onlyjob** [comment]
Auto healing is __absolutely necessary__ in large cluster. Please reopen.

It is easy to implement automatic periodic execution of such maintenance commands for example after configurable delay since volume disappearance.

Storage admin should not have to script essential maintenance operations that should be completely transparent and automatic.

Have a look how it is implemented in MooseFS and LizardFS please.

**Comment by onlyjob** [comment]
Also `volume.fix.replication` does not even work:

```
$ ./weed shell
> volume.fix.replication
replicating volume 3 001 from 192.168.0.204:9334 to dataNode 192.168.0.250:9334 ...
error: rpc error: code = Unknown desc = failed to copy /mnt/NVMe/weed/data/3.dat file: receiving /mnt/NVMe/weed/data/3.dat: rpc error: code = Internal desc = unexpected EOF
```

See #1268 for details about volumes replication.
