### ISSUE TITLE
Volume server get request duration and cpu increase a lot when resizing image starts

### ISSUE THREAD

**Issue by binwu5** [chrislusf/seaweedfs#1270]
- weed version `8000GB 1.71 linux amd64`

mosts of image size are less than 100KB;
resizing image QPS is just around 2.

**Screenshots**
![image](https://user-images.githubusercontent.com/62281503/78874371-e1252f80-7a7e-11ea-9fec-1aad81e84e2d.png)

![image](https://user-images.githubusercontent.com/62281503/78872722-488db000-7a7c-11ea-8307-b07381e609fd.png)

**Comment by chrislusf** [comment]
Need to show which git version started this problem. It is hard to git bisect with your setup.

**Comment by chrislusf** [comment]
Very likely this is related to 2286eda575861cceb4464bf677e9885e069de385

Added fix for it: https://github.com/chrislusf/seaweedfs/commit/d2d15978502ff3b45b010f546beaf226321dddb1

**Comment by chrislusf** [comment]
You can re-open this if tested with latest release.

**Comment by binwu5** [comment]
I make a new version to test (v1.74 doesn't include the fix), and the performance is same as before.

**Comment by meotimdihia** [comment]
Resize features need to be reconsidered. I have tried it and the server is full of memory in minutes.
I have checked filer used 60% memory.
