### ISSUE TITLE
The benchmark did not see network traffic etc.  

### ISSUE THREAD

**Issue by salahgao** [chrislusf/seaweedfs#1275]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**

**System Setup**
- CentOS Linux release 7.2.1511 (Core) 
- version 30GB 1.73 linux amd64

The server is: 10.5.74.51:9333, 10.5.74.52:9333, 10.5.74.53:9333

The start command is:

```
./weed server -metrics.address=10.5.74.56:9091 -ip=10.5.74.51 -master.port=9333 -dir=./1 -volume.port=8080 -master.peers=10.5.74.51:9333,10.5.74.52:9333,10.5.74.53:9333
./weed server -metrics.address=10.5.74.56:9091 -ip=10.5.74.52 -master.port=9333 -dir=./1 -volume.port=8080 -master.peers=10.5.74.51:9333,10.5.74.52:9333,10.5.74.53:9333
./weed server -metrics.address=10.5.74.56:9091 -ip=10.5.74.53 -master.port=9333 -dir=./1 -volume.port=8080 -master.peers=10.5.74.51:9333,10.5.74.52:9333,10.5.74.53:9333
```

The test client is: 10.5.74.54

The test command is:

```
./weed benchmark -master=10.5.74.51:9333 -replication=002 -size=10485760 -n=20000 -c=50
```

The data size is 10MB requests 20,000 times

1. The test result is

```
------------ Writing Benchmark ----------
Concurrency Level:      50
Time taken for tests:   287.083 seconds
Complete requests:      20000
Failed requests:        0
Total transferred:      209715832316 bytes
Requests per second:    69.67 [#/sec]
Transfer rate:          713385.67 [Kbytes/sec]

Connection Times (ms)
              min      avg        max      std
Total:        154.5      717.3       2336.1      283.1

Percentage of the requests served within a certain time (ms)
   50%    684.6 ms
   66%    809.5 ms
   75%    889.1 ms
   80%    945.7 ms
   90%    1093.3 ms
   95%    1224.4 ms
   98%    1403.3 ms
   99%    1515.6 ms
  100%    2336.1 ms

------------ Randomly Reading Benchmark ----------
Concurrency Level:      50
Time taken for tests:   52.058 seconds
Complete requests:      20000
Failed requests:        0
Total transferred:      209715833119 bytes
Requests per second:    384.19 [#/sec]
Transfer rate:          3934121.34 [Kbytes/sec]

Connection Times (ms)
              min      avg        max      std
Total:        20.4      127.0       452.0      56.1

Percentage of the requests served within a certain time (ms)
   50%    115.5 ms
   66%    138.7 ms
   75%    157.9 ms
   80%    170.0 ms
   90%    203.6 ms
   95%    233.9 ms
   98%    270.2 ms
   99%    297.8 ms
  100%    452.0 ms
```
**Writing transfer rate: 713385.67 [Kbytes/sec]
Randomly Reading transfer rate: 3934121.34 [Kbytes/sec]**

2. 10.5.74.54 Network traffic is

![image](https://user-images.githubusercontent.com/849216/79293810-29bd6c80-7f07-11ea-862c-60c93f844e7a.png)

**The max transmit is 8.4 Mbps. The max receive is 42.2 Mbps.**

3. 10.5.74.51 Disk read and write

![image](https://user-images.githubusercontent.com/849216/79294065-dbf53400-7f07-11ea-9b20-4f32a7a575b3.png)

**The max written bytes is 4.526 MBs. No read bytes.**

4. Disk volume data size

![image](https://user-images.githubusercontent.com/849216/79295394-22985d80-7f0b-11ea-9937-1396a49426ee.png)

**The total data size is 247MB**

**My question**
- The network traffic is much smaller than the read and write transfer rate.
- Disk write 4.526 MBs is too small, and there is no read operation
- The disk volume data size is 247MB, which is smaller than the data request 20000 * 10MB.

**Comment by chrislusf** [comment]
Not clear what is the ask here.

**Comment by salahgao** [comment]
> Not clear what is the ask here.

I updated the comment, I don ’t know if it ’s clear.

**Comment by chrislusf** [comment]
This could be due to auto gzipping content. The fix is in this commit. https://github.com/chrislusf/seaweedfs/commit/d2d15978502ff3b45b010f546beaf226321dddb1

**Comment by chrislusf** [comment]
You can re-open this if tested with the coming release.

**Comment by salahgao** [comment]
Ok thank you.
