### ISSUE TITLE
volume问题

### ISSUE THREAD

**Issue by gitlihua** [chrislusf/seaweedfs#1276]
现在有192.168.10.11和192.168.10.12组成的数据中心，现在需要迁移到192.168.10.33和192.168.10.34 应该怎么迁移呢？filer是连接的redis，redis在192.168.10.10上 ，filer不用管，就是volmue怎么迁移过去？如图：
![image](https://user-images.githubusercontent.com/23493734/79323533-e849b300-7f40-11ea-927d-bb3cfd6b8727.png)

**Comment by chrislusf** [comment]
Just change to the new IP addresses or copy the files over.

**Comment by gitlihua** [comment]
我主要想问的是volume里的数据，seaweed这边有提供什么快速的命令可以迁移么？毕竟2个IP组成的数据中心有将近4T的数据。我原来的想法是使用rsync的命令，将volume里面的所有数据拷贝到新地址那边去，我感觉速度太慢了。就是想问下seaweed这边有没有什么比较快的方式，将volume里面的数据迁移过去？

**Comment by chrislusf** [comment]
No way is faster than copying the raw data, except some basic compression.

**Comment by gitlihua** [comment]
如何我要把10.11和10.12的数据中心，合成一个数据中心，不做冗余了，应该怎么做？我们使用的Replication=001

**Comment by chrislusf** [comment]
see `volume.configure.replication` in `weed shell`

**Comment by gitlihua** [comment]
之前的问题作废，我们现在想的是将10.11和10.12组成的数据中心，迁移到10.33上面去，应该怎么做？

**Comment by gitlihua** [comment]
之前的问题作废，我们现在想的是将10.11和10.12组成的数据中心，迁移到10.33上面去，10.33上面只挂一块硬盘 ，应该怎么做？

**Comment by chrislusf** [comment]
copy all the files to the same disk.

**Comment by gitlihua** [comment]
我的想法是用mount去挂载filer，新机器也采用这样的方式，然后2边进行本地目录对拷，为啥不让拷贝啊。
