### ISSUE TITLE
Filer REST API obsolete doc

### ISSUE THREAD

**Issue by rsc1975** [chrislusf/seaweedfs#1281]
First of all, I've created a [post in SO](https://stackoverflow.com/questions/61305120/unknown-seaweedfs-filer-api-response-format), but It seems that the tag "seaweedfs" didn't exist so, I'm no sure about what is the proper channel for this question/issue. 

We've just installed the current SeaweedFS version to be used as temporary repository for backup files, we centralized all our services/hosts daily backup in the Seaweedfs server and later the files are downloaded and removed from SeaweedFS.

Well, the system is working fine (more or less, we found an issue but with workaround that I'll explain in a different GitHub issue), We can upload, list and download files.

The problem is that the Filer REST API response hasn't got the expected format (according to the [doc examples](https://github.com/chrislusf/seaweedfs/wiki/Filer-Server-API))

    curl -H "accept: application/json" localhost:8888/dir1/?pretty=y

```javascript
{
  "Path": "/dir1",
  "Entries": [
    {
      "FullPath": "/dir1/nyfile.bin",
      "Mtime": "2020-04-16T17:56:55Z",
      "Crtime": "2020-04-16T17:56:55Z",
      "Mode": 432,
      "Uid": 1000,
      "Gid": 1000,
      "Mime": "application/octet-stream",
      "Replication": "000",
      "Collection": "",
      "TtlSec": 0,
      "UserName": "",
      "GroupNames": null,
      "SymlinkTarget": "",
      "Md5": "zQnaPjjZsQpiU+N3RXp7GQ==",
      "Extended": null,
      "chunks": [
        {
          "file_id": "7,030d2d9790",
          "size": 55320265,
          "mtime": 1587059815546104803,
          "e_tag": "7b71a215",
          "fid": {
            "volume_id": 7,
            "file_key": 3,
            "cookie": 221091728
          }
        }
      ]
    }
  ],
  "Limit": 100,
  "LastFileName": "weed.bin",
  "ShouldDisplayLoadMore": false
}
```

I have some questions related with this response:

* Where is the documentation (if exists) for the new Filer REST API ?
* How can I figure out what is a file and what is a directory with the new API ?
    * Currently, I'm using the "chunks" property, If there is "chunks" then It's a file otherwise is a directory. Is it correct?
* How can I get the size of a file ? Should I sum the size property in all its chunks ?

My system versión:

```shellscript
/etc/seaweedfs # cat filer.toml
[leveldb2]
enabled = true
dir = "/data/filerldb2"
/etc/seaweedfs # weed version
version 30GB 1.72 linux amd64
#Docker image:
 chrislusf/seaweedfs:latest
```

**Comment by chrislusf** [comment]
Thanks for the detailed question! I updated the tag description and is waiting for the peer review.

* Documentation not there yet. The REST API is not used internally. Use gRPC for more advanced usages.
* Mode follows os.Mode https://golang.org/pkg/os/#FileMode. Use os.ModeDir to determine file or directory.
* Chunks may have overlaps. Use the highest watermark for file size.

**Comment by rsc1975** [comment]
Oh, what a fast answer!!! Awesome 👍

**Comment by zhutongcloud** [comment]
Can i  ask how to control  filer API teturn "Uid and Gid" ?  Why  my filer server always return me "0 and 0",and  How to understand their meaning？ Thanks

**Comment by chrislusf** [comment]
uid and gid are for POSIX compatibility when running FUSE mount.

**Comment by zhutongcloud** [comment]
> uid and gid are for POSIX compatibility when running FUSE mount.

Oh, i got it ,Thanks
