### ISSUE TITLE
Two questions about Haystack paper.

### ISSUE THREAD

**Issue by lxyscls** [chrislusf/seaweedfs#1282]
![image](https://user-images.githubusercontent.com/4469678/79726892-16067180-831e-11ea-8161-616fbad37209.png)

Hello, 
    How to use the header/footer magic number to recover? I can't find any detail in the paper.
    And does the padding have any improvement on the efficiency? Is it neccessary?
    
Thank you very much if you can give me some guide or suggetion.

**Comment by chrislusf** [comment]
> How to use the header/footer magic number to recover? I can't find any detail in the paper.
Do not know.

> And does the padding have any improvement on the efficiency? Is it neccessary?
No.
