### ISSUE TITLE
tikv is missing in filer2 since tag v1.62

### ISSUE THREAD

**Issue by zmlcc** [chrislusf/seaweedfs#1284]
tikv exists in filer2 in tag v1.61 https://github.com/chrislusf/seaweedfs/tree/1.61/weed/filer2, but losts since tag v1.62 https://github.com/chrislusf/seaweedfs/tree/1.62/weed/filer2

**Comment by chrislusf** [comment]
Do you really want tikv?

* tikv client library increased the binary size by more than 10MB.
* tikv client library versioning caused compilation issues
* tikv seems not many users
* tikv users can use tidb instead
* tikv support to a separate branch https://github.com/chrislusf/seaweedfs/tree/tikv
