### ISSUE TITLE
How to create WEBDAV user to access specify file or specify path?  

### ISSUE THREAD

**Issue by Kiltalaw** [chrislusf/seaweedfs#1285]
@chrislusf Hi, I can not find the WEBDAV option document to create user to access the weed webdav , could you please tell me how to create user through the option file or interface ?

**Comment by chrislusf** [comment]
Currently there are no user setup for WEBDAV. What's your use case?

**Comment by Kiltalaw** [comment]
User likes to manage their private space for them to upload file, we want to use interface to create user and path or file read or write permission, home directory. It would be better to provide listener for WebDAV Or other component. It would be easily to integrate other system.

**Comment by chrislusf** [comment]
The `weed webdav` is really simple with just two files. Welcome for any ideas to improve!

https://github.com/chrislusf/seaweedfs/blob/master/weed/command/webdav.go
https://github.com/chrislusf/seaweedfs/blob/master/weed/server/webdav_server.go
