### ISSUE TITLE
"weed shell" is always connected if a [master.maintenance] script is enabled, preventing interactive use

### ISSUE THREAD

**Issue by Radtoo** [chrislusf/seaweedfs#1288]
"weed shell" always fails with the message that a shell is already connected, making it not possible to issue commands to seaweedfs over said shell.

This happens in all instances -even right after a reboot- as long as "weed server" is running. From what I can tell from the logs, "weed server" seems to automatically start & connect an client shell over ipv6.
```
master.go:137] Start Seaweed Master 8000GB 1.75 grpc server at 0.0.0.0:19333
master_grpc_server.go:264] + client master@10.0.0.1:4414
master_grpc_server.go:264] + client filer@10.0.0.1:1051
[...]
master_grpc_server.go:264] + client shell@[::1]:35914
configuration.go:25] Configure filer for leveldb2
```
"ss -p" also confirms that a "weed" process is connecting from [::1]:35914 to [::1]:19333 and also from [::1]:19333 to [::1]:35914, so I assume "weed shell" is probably correct in detecting an already connected shell.

**Comment by Radtoo** [comment]
I learned that having a [master.maintenance] section in the master.toml is what apparently responsible. Regardless if sleep_minutes is on a long interval it seems to always keep a shell connected. Commenting out this section works around the issue for now.  It however certainly feels like it should be possible to have both automatic maintenance commands run on the master server and also interactively use a weed shell.

It maybe should even be possible to connect multiple weed shells (like before 1.74) and run commands like "volume.list" or "fs.du" or "collection.list" from them. If certain commands happen to interfere with each other, why not instead just block them from running at the same time?

**Comment by Radtoo** [comment]
I learned that having a [master.maintenance] section in the master.toml is what apparently responsible. Regardless if sleep_minutes is on a long interval it seems to always keep a shell connected. Commenting out this section works around the issue for now. It however certainly feels like it should be possible to have both automatic maintenance commands run on the master server and also interactively use a weed shell.

It maybe should even be possible to connect multiple weed shells (like before 1.74) to run commands like "volume.list" or "fs.du" or "collection.list" from them. If certain commands happen to interfere with each other, why not instead just block them from running at the same time?

**Comment by chrislusf** [comment]
try to use a separate `weed shell` to run the admin scripts for now.

**Comment by chrislusf** [comment]
temporarily disabled this restriction in 1.76.
