### ISSUE TITLE
os.Exit directly after all signal handler done running

### ISSUE THREAD

**Issue by wyxloading** [chrislusf/seaweedfs#1289]
**Describe the bug**
Some "bug" in code. I was caught in the bug which make my program fail to graceful shutdown. BUT with a 0 exit code.
https://github.com/chrislusf/seaweedfs/blob/508ec01ab0668ab7ec7ba8a8484e043ac6c7b237/weed/util/signal_handling.go#L28-L35

<s>I think it's ok to remove the line `os.Exit(0)` directly. </s>

**System Setup**
- master

**Expected behavior**
We should not call `os.Exit()` in any signal handler.
Which might make the normal graceful shutdown fail at any moment.

EDIT: Remove the like `os.Exit(0)` directly is not ok.

**Comment by wyxloading** [comment]
I have required seaweedfs to my project, as i need the shell package (which depend on the util package), make my graceful shutdown a mess.

**Comment by chrislusf** [comment]
Not sure how to help you.

what you need from the shell package?
