### ISSUE TITLE
Random failures for 0.69

### ISSUE THREAD

**Issue by oracle1wr** [chrislusf/seaweedfs#129]
I'm experiencing very unstable behaviour on 0.69 version.  I have one master and two volumes. Applications go down every a couple of hours. If I put bigger then usual load those go down after a couple of minutes. 

I checked memory, there is no problem with it. Apps get ~20M and don't grow. 
I checked logs, (-v=4) there are nothing related to failure. No errors.

Only  cause I can imagine is data files corruption. Some images didn't persisted because of some error. I found servers down after that. I started up servers, data was there, but some most recent were not. When I tried to recreate missing images servers started failing very frequently.

Could you please advice, how to deal with this.

**Comment by chrislusf** [comment]
There are logs under /tmp by default. Please find anything special there.

**Comment by oracle1wr** [comment]
Here is what I found today in  volume logs:
==============================
I0421 23:11:56 87469 volume_server_handlers_read.go:25] parsing error: strconv.ParseUint: parsing "": invalid syntax /
I0421 23:11:56 87469 volume_server_handlers_read.go:25] parsing error: strconv.ParseUint: parsing "": invalid syntax /
I0421 23:33:59 87469 volume_server_handlers_read.go:36] volume 11 reading Cookie:1712356630, Id:397124, Size:0, DataSize:0, Name: , Mime:
I0421 23:33:59 87469 volume_server_handlers_read.go:50] read bytes 3242 error <nil>
=====================================
Master doesn't have anything, but is also went down.

**Comment by chrislusf** [comment]
It's hard to tell. If you have a reproducible script and files, that'll be great. But I know it's not easy.

**Comment by oracle1wr** [comment]
Ok, I'll try to get something reproducible.

**Comment by oracle1wr** [comment]
I deleted all dat and idx files, also cleaned masters data folder. I tried to add more volumes with command to a cleaned volume server: 
curl "http://localhost/admin/assign_volume?replication=000&volume=0"

and it went down. I start it up again, and rest were added with no problems.

**Comment by chrislusf** [comment]
I can not reproduce it. And the volume id starts from 1, not 0.

**Comment by oracle1wr** [comment]
Thank you Chris for being involved into this. I found a real issue. The problem was related to OpenShift fancy behaviour. 
The weed server works stable only if I specify addition parameters in server start up command:
"....  > $OPENSHIFT_LOG_DIR/volume.log 2>&1 ".

If I don't do that, the system behave really strange. The app goes down randomly. And if put some load it went down with higher chances.

So, Not a bug.

**Comment by chrislusf** [comment]
Thanks for the update!
Interesting to know this openshift behavior!
