### ISSUE TITLE
master startup in windows10 fail

### ISSUE THREAD

**Issue by mingkeYao** [chrislusf/seaweedfs#1291]
In Windows 10
when I type command  ".\weed.exe master" in PowerShell to startup , the window returns error.
log is below:

PS D:\bag\seaweed> .\weed.exe master
I0428 10:15:26 25468 file_util.go:20] Folder C:\Users\yao\AppData\Local\Temp Permission: -rwxrwxrwx
I0428 10:15:26 25468 master.go:150] current: 169.254.192.81:9333 peers:
I0428 10:15:26 25468 master_server.go:108] Volume Size Limit is 30000 MB
I0428 10:15:26 25468 master_server.go:196] adminScripts:
I0428 10:15:26 25468 master.go:113] Start Seaweed Master 30GB 1.77 at 0.0.0.0:9333
I0428 10:15:26 25468 raft_server.go:47] Starting RaftServer with 169.254.192.81:9333
I0428 10:15:27 25468 raft_server.go:87] current cluster leader:
I0428 10:15:27 25468 master_server.go:151] [ 169.254.192.81:9333 ] I am the leader!
I0428 10:15:27 25468 master.go:137] Start Seaweed Master 30GB 1.77 grpc server at 0.0.0.0:19333
I0428 10:15:27 25468 masterclient.go:75] master failed to keep connected to 169.254.192.81:9333: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 169.254.192.81:19333: connectex: A socket operation was attempted to an unreachable network."

It seem like the weed check the true ip address other then virtual one.
My computer'ip is 172.16.93.133

But when I type command  ".\weed.exe master -ip=localhost" , it goes well
and I use "weed master" in centos7, it goes well.
so maybe it's a bug

**Comment by chrislusf** [comment]
Set the IP then, since your ip can not auto detected.
