### ISSUE TITLE
Any solution for cold data?

### ISSUE THREAD

**Issue by chinajuanbob** [chrislusf/seaweedfs#1292]
The case is we have a lot of rare use date which is big and cost if store in the local hot devices or warm cloud place. Is there a solution that we could put them in the offline devices as cold data, but could still interact with meta (may with a flag to know if it is online or offline and possible to fetch data) in seaweed system? Thanks a lot!

**Comment by chrislusf** [comment]
Where do you put the cold data then?

Check this? https://github.com/chrislusf/seaweedfs/wiki/Cloud-Tier
