### ISSUE TITLE
What's the best practice for expanding volume?

### ISSUE THREAD

**Issue by youngcube** [chrislusf/seaweedfs#1295]
We start to test expanding volume. now we simply change `weedfs volume -max=${VOLNUM}'` to expand volume space. It might work. But we found an error `volume %d not found` in some random files throungth `filer` api.

Seaweedfs Version: 1.76

Here's our environment:

>
> A server which runs `master`,`filer`,`volume`,`etcd`(for `filer`)
>
> use `linux_amd64_large_disk.tar.gz`
>
> `volume` binds it's data in `/data` which contains 8T free space.
>

Way to reproduce this problem:

- start `master` with this command: `-mdir=/master -volumePreallocate -volumeSizeLimitMB=60000`
- start `volume` with this command: `-dir=/data -max=1`. now we have `60G` free space
- upload many small files (5k~5M) to fullfill `volume`
- after `5 hours` it will be full. check some files throungh `filer` and no error happens.
- restart `volume` with this command: `-dir=/data -max=60`. now we have `~3.6T` free space
- check some files throungh `filer` api and no error happens.
- keep uploading small files for about `5 hours`
- check some files throungh `filer` api and get this error `volume %d not found`. but not all files are inaccessible.
- if I restart `volume` with the same command (`-dir=/data -max=60`) again, these files can be accessed. but since we have a large mount of small files, it's hard to tell whether all files are accessible.

We want to know if change `-max=?` parameter is a correct way to expand volume space. If not, do we have to keep `-max=?` in a certain number and never change it again?

Thanks.

**Comment by chrislusf** [comment]
> keep -max=? in a certain number and never change it again

`max` is just a limit. The actual volume will be created when it is needed. You do not need to change the max.
