### ISSUE TITLE
S3 gateway ListBuckets bug, SerializationError: failed to decode REST XML response

### ISSUE THREAD

**Issue by lotsofone** [chrislusf/seaweedfs#1297]
**Describe the bug**
I am using aws-sdk-go to access the s3 gateway. When I list buckets, it prints
```
SerializationError: failed to decode REST XML response
        status code: 200, request id: 1588169425827409836
caused by: parsing time "2020-04-29T21:46:15+08:00" as "2006-01-02T15:04:05.999999999Z": cannot parse "+08:00" as "Z"
```
And I see no error in the weed s3 screen

Same thing also happens when I try to list objects.
https://github.com/aws/aws-sdk-go/issues/3175 is another similar issue

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
weed master -mdir="/data4/seaweed/tm" -ip=machine1 -port=9201
weed volume -dir=/data4/seaweed/tv -mserver=machine1:9201 -ip=machine1 -port=9300 -max=15 -fileSizeLimitMB=1024
weed filer -ip=machine2 -port=8081 -master=machine1:9201
weed s3 -port=9000 -filer=machine2:8081 -config=config.json

config:json:
```
{
  "identities": [
    {
      "name": "some_name",
      "credentials": [
        {
          "accessKey": "xxxxxxx",
          "secretKey": "xxxxxxxxxxxxxxxx"
        }
      ],
      "actions": [
        "Admin",
        "Read",
        "Write"
      ]
    }
  ]
}
```

- OS version
CentOS Linux release 7.2 (Final)
- output of `weed version`
version 8000GB 1.77 linux amd64
- aws-sdk-go version
github.com/aws/aws-sdk-go v1.30.11
- if using filer, show the content of `filer.toml`
I did not set a filer.toml, just simply `weed filer -xxx`
- code that access s3
```
package main

import (
	"fmt"
	"os"

	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/credentials"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/s3"
)

func exitErrorf(msg string, args ...interface{}) {
	fmt.Fprintf(os.Stderr, msg+"\n", args...)
	os.Exit(1)
}
func main() {
	host := "http://machine2:9000"                 
	ak := "xxxxxxxx"                   
	sk := "xxxxxxxxxxxxxxxxx" 

	s3Config := &aws.Config{
		Credentials:      credentials.NewStaticCredentials(ak, sk, ""),
		Endpoint:         aws.String(host),
		Region:           aws.String("us-east-1"),
		DisableSSL:       aws.Bool(true),
		S3ForcePathStyle: aws.Bool(true),
	}

	sess := session.New(s3Config)
	svc := s3.New(sess)
	//create bucket
	bucket := "gos3test"
	_, err := svc.CreateBucket(&s3.CreateBucketInput{
		Bucket: aws.String(bucket),
	})
	if err != nil {
		exitErrorf("Unable to create bucket %q, %v", bucket, err)
	}
	// list bucket
	rst, err := svc.ListBuckets(nil)
	if err != nil {
		exitErrorf("Unable to list buckets, %v", err)
	}

	fmt.Println("Buckets:")

	for _, b := range rst.Buckets {
		fmt.Printf("* %s created on %s\n",
			aws.StringValue(b.Name), aws.TimeValue(b.CreationDate))
	}
}
```
**Expected behavior**
It should list the bucket I just created

**What I see instead**
Bucket has been successfully created, /buckets/gos3test can be found in the filer page.
```
Unable to list buckets, SerializationError: failed to decode REST XML response
        status code: 200, request id: 1588214433913637953
caused by: parsing time "2020-04-29T21:46:15+08:00" as "2006-01-02T15:04:05.999999999Z": cannot parse "+08:00" as "Z"
```

**Comment by chrislusf** [comment]
Thanks for reporting! Added the fix.
