### ISSUE TITLE
The file directory has been deleted, but the file information in the directory has not been deleted

### ISSUE THREAD

**Issue by bboxzhen** [chrislusf/seaweedfs#1303]
curl -X DELETE http://seaweedfs:8888/object/2020-02-20?recursive=true
![image](https://user-images.githubusercontent.com/39783629/81281270-322f4000-908c-11ea-9174-63e708c847a7.png)
I deleted the entire directory, but the filer server did not delete the file information in the directory. The volume server has deleted these files.

[mongodb]
enabled = true
 uri = "mongodb://localhost:27017"
option_pool_size = 0
database = "seaweedfs"

**Comment by chrislusf** [comment]
Added a fix.

**Comment by bboxzhen** [comment]
> 添加了修复程序。
leveldb2，redis2。Is it also possible to delete the file information in the directory, because it is now found that their directory size has not decreased

**Comment by chrislusf** [comment]
Sorry I do not understand what is the question.

**Comment by bboxzhen** [comment]
> 对不起，我不明白这是什么问题。

curl -X DELETE http://seaweedfs:8888/test?recursive=true，可不可以让filer服务器把卷服务器的文件删除的同时，把filer服务的文件信息也给删掉。现在mongodb你是添加了修复程序，leveldb2，redis2也可以实现这个功能吗？

**Comment by chrislusf** [comment]
yes

**Comment by bboxzhen** [comment]
> 是
麻烦作者大人了，我现在测试redis和leveldb2是没有删除这些文件信息的

**Comment by chrislusf** [comment]
can not reproduce.

**Comment by chrislusf** [comment]
maybe also try this
```
curl -X DELETE http://localhost:8888/path/to?recursive=true&ignoreRecursiveError=true
```

**Comment by bboxzhen** [comment]
> maybe also try this
> 
> ```
> curl -X DELETE http://localhost:8888/path/to?recursive=true&ignoreRecursiveError=true
> ```

![image](https://user-images.githubusercontent.com/39783629/82002301-07e31100-9690-11ea-86f4-ddd9210bb9c5.png)

就算我删除文件目录，leveldb2这个存储大小也是不会下降的，随着文件越来越多，我害怕leveldb2的存储大小会不可控
