### ISSUE TITLE
After forced deletion, there seems to be no vacuum

### ISSUE THREAD

**Issue by bboxzhen** [chrislusf/seaweedfs#1305]
After I forced to delete, the page showed that there is still trash. Is there no reclaimed space, or is the page display problem?
curl "http://seaweedfs3:9334/vol/vacuum"
{"Topology":{"DataCenters":[{"Free":74,"Id":"dc1_pcap","Max":297,"Racks":[{"DataNodes":[{"EcShards":0,"Free":15,"Max":99,"PublicUrl":"seaweedfs1:5042","Url":"seaweedfs1:5042","Volumes":84}],"Free":15,"Id":"seaweedfs1_pcap_rack2","Max":99},{"DataNodes":[{"EcShards":0,"Free":26,"Max":99,"PublicUrl":"seaweedfs1:5041","Url":"seaweedfs1:5041","Volumes":73}],"Free":26,"Id":"seaweedfs1_pcap_rack1","Max":99},{"DataNodes":[{"EcShards":0,"Free":33,"Max":99,"PublicUrl":"seaweedfs1:5043","Url":"seaweedfs1:5043","Volumes":66}],"Free":33,"Id":"seaweedfs1_pcap_rack3","Max":99}]},{"Free":103,"Id":"dc3_pcap","Max":297,"Racks":[{"DataNodes":[{"EcShards":0,"Free":37,"Max":99,"PublicUrl":"seaweedfs3:5043","Url":"seaweedfs3:5043","Volumes":62}],"Free":37,"Id":"seaweedfs3_pcap_rack3","Max":99},{"DataNodes":[{"EcShards":0,"Free":28,"Max":99,"PublicUrl":"seaweedfs3:5042","Url":"seaweedfs3:5042","Volumes":71}],"Free":28,"Id":"seaweedfs3_pcap_rack2","Max":99},{"DataNodes":[{"EcShards":0,"Free":38,"Max":99,"PublicUrl":"seaweedfs3:5041","Url":"seaweedfs3:5041","Volumes":61}],"Free":38,"Id":"seaweedfs3_pcap_rack1","Max":99}]},{"Free":68,"Id":"dc2_pcap","Max":297,"Racks":[{"DataNodes":[{"EcShards":0,"Free":27,"Max":99,"PublicUrl":"seaweedfs2:5042","Url":"seaweedfs2:5042","Volumes":72}],"Free":27,"Id":"seaweedfs2_pcap_rack2","Max":99},{"DataNodes":[{"EcShards":0,"Free":24,"Max":99,"PublicUrl":"seaweedfs2:5041","Url":"seaweedfs2:5041","Volumes":75}],"Free":24,"Id":"seaweedfs2_pcap_rack1","Max":99},{"DataNodes":[{"EcShards":0,"Free":17,"Max":99,"PublicUrl":"seaweedfs2:5043","Url":"seaweedfs2:5043","Volumes":82}],"Free":17,"Id":"seaweedfs2_pcap_rack3","Max":99}]}],"Free":245,"Layouts":[{"collection":"","replication":"110","ttl":"","writables":[89,98,48,86,60,44,90,43,68,55,97,106,53,109,218,46,31,49,72,32,75,93,70,88,47,107,56,100,42,9,11,92,84,81,5,219,62,102,85,65,3,58,64,50,71,61,73,67,12,30,45,52,54,80,4,66,103,101,110,217,41,51,87,104,105,69,111,108,82,6,99,79,83]}],"Max":891},"Version":"8000GB 1.76"}

master send to master@10.0.1.9:50717: url:"seaweedfs1:5041" public_url:"seaweedfs1:5041" new_vids:123 new_vids:179 new_vids:161 new_vids:41 new_vids:106 new_vids:214 new_vids:70 new_vids:169 new_vids:185 new_vids:22 new_vids:87 new_vids:53 new_vids:168 new_vids:112 new_vids:167 new_vids:191 new_vids:218 new_vids:109 new_vids:180 new_vids:202 new_vids:142 new_vids:46 new_vids:136 new_vids:113 new_vids:31 new_vids:73 new_vids:121 new_vids:189 new_vids:49 new_vids:182 new_vids:141 new_vids:198 new_vids:208 new_vids:72 new_vids:36 new_vids:32 new_vids:131 new_vids:196 new_vids:217 new_vids:33 new_vids:50 new_vids:55 new_vids:18 new_vids:184 new_vids:21 new_vids:24 new_vids:34 new_vids:149 new_vids:134 new_vids:159 new_vids:154 new_vids:174 new_vids:25 new_vids:39 new_vids:83 new_vids:11 new_vids:157 new_vids:195 new_vids:192 new_vids:188 new_vids:80 new_vids:101 new_vids:199 new_vids:187 new_vids:23 new_vids:38 new_vids:97 new_vids:173 new_vids:183 new_vids:209 new_vids:125 new_vids:13 new_vids:128 

![image](https://user-images.githubusercontent.com/39783629/81382348-d4106480-9140-11ea-8140-7584fdf2cb10.png)

**Comment by chrislusf** [comment]
Volume 21: trash is below threshold.
Volume 13: volume is readonly for some reason.

**Comment by bboxzhen** [comment]
> 第21卷：垃圾低于阈值。
> 卷13：由于某种原因，卷是只读的。
But I enforced these two commands
curl "http://seaweedfs3:9334/vol/vacuum"
curl "http://seaweedfs3:9334/vol/vacuum?garbageThreshold=0"
![image](https://user-images.githubusercontent.com/39783629/81383359-80067f80-9142-11ea-9323-ca7b0bf64ec3.png)

**Comment by chrislusf** [comment]
Try to collect related logs on volume server.
