### ISSUE TITLE
How to setup Filer's async replication monitor?

### ISSUE THREAD

**Issue by youngcube** [chrislusf/seaweedfs#1306]
Hi. I have 2 `weedfs` cluster in different rack (`A`,`B`) and I want to make sure they all replicate. So I setup 2 `filer.replicate` program. One for `A->B` and another one for `B->A`.

I want to know how to setup async replicate monitor so that I can know `filer.replicate` has some problems like network error that makes the replicate failure.

More specifically, if `A->B` replicate failure for about 1 hour at 2020/05/07 11:10:00. I want to know that.

If there are no monitor or alert logic in `filer.replicate`, how can I make my own monitor? For example detect the `filer.replicate` logs check if include some specific logs? If so, what log should I focus?

Thanks!

**Comment by chrislusf** [comment]
monitor the error output of `weed filer.replicate`?

**Comment by kmlebedev** [comment]
@youngcube You can use rabbitMQ and monitor the status of the queue
