### ISSUE TITLE
In Filer's replication, is that ok if I have 2 weedfs with different max volume parameter?

### ISSUE THREAD

**Issue by youngcube** [chrislusf/seaweedfs#1307]
Hi.

I have 2 `weedfs` cluster in different rack (`A`,`B`) and I use `filer.replicate` program for `A->B` and `B->A`.

In `A`, I start `volume` with `volume -max=50`
In `B`, I start `volume` with `volume -max=70`

As you can see I use different `-max` for each `weedfs volume`

In `filer.replicate` log:

```
E0509 05:16:16     1 filer_replication.go:118] replicate /test/test/audio/ecc21b50-7a98-11ea-83e8-d478e1789c56.m4a: replicate entry chunks /test/test/audio/ecc21b50-7a98-11ea-83e8-d478e1789c56.m4a: copy 632,082b5de409e6b3: read part 632,082b5de409e6b3: LookupFileId locate volume id 632: <nil>
I0509 05:16:16     1 filer_sink.go:102] replicate entry chunks /test/test/video/7b4222e6-7a99-11ea-83e8-d478e1789c56.mp4: copy 633,082b5f6735f685: read part 633,082b5f6735f685: LookupFileId locate volume id 633: <nil>
E0509 05:16:16     1 filer_replication.go:118] replicate /test/test/video/7b4222e6-7a99-11ea-83e8-d478e1789c56.mp4: replicate entry chunks /test/test/video/7b4222e6-7a99-11ea-83e8-d478e1789c56.mp4: copy 633,082b5f6735f685: read part 633,082b5f6735f685: LookupFileId locate volume id 633: <nil>
...
```

It seems like `filer.replicate` can not find the current volume id

Also, I found some files can not be access due to `volume xxx not found` problem and return `500`. But when I restart `volume` program, these files can be access again.

So I want to know if it's ok I have 2 weedfs with different `-max` volume parameter when I want them both replicate. If not, Must I use same `-max` number for all these weedfs volume?
Thanks!

**Comment by chrislusf** [comment]
it is ok.

**Comment by youngcube** [comment]
Thanks for quick reply!
But what are these logs represent? Are they just info logs not error logs?

```
LookupFileId locate volume id 633: <nil>
```

----


> Also, I found some files can not be access due to volume xxx not found problem and return 500. But when I restart volume program, these files can be access again.

For this problem, what can I do to make sure I do not need to restart volume again?
Thanks!

**Comment by chrislusf** [comment]
which volume server did you restart? Need full logs on both clusters.

**Comment by youngcube** [comment]
I restart `A`‘s `volume` and the file can be access again.

I check `A`‘s `volume`'s logs and found these lines:

```
I0515 14:18:20     1 store_ec.go:52] MountEcShards 1.0
I0515 14:18:20     1 store_ec.go:52] MountEcShards 1.1
I0515 14:18:20     1 store_ec.go:52] MountEcShards 1.2
I0515 14:18:20     1 store_ec.go:52] MountEcShards 1.3
I0515 14:18:20     1 store_ec.go:52] MountEcShards 1.4
I0515 14:18:20     1 store_ec.go:52] MountEcShards 1.5
I0515 14:18:20     1 store_ec.go:52] MountEcShards 1.6
I0515 14:18:20     1 store_ec.go:52] MountEcShards 1.7
I0515 14:18:20     1 store_ec.go:52] MountEcShards 1.8
I0515 14:18:20     1 store_ec.go:52] MountEcShards 1.9
I0515 14:18:20     1 store_ec.go:52] MountEcShards 1.10
I0515 14:18:20     1 store_ec.go:52] MountEcShards 1.11
I0515 14:18:20     1 store_ec.go:52] MountEcShards 1.12
I0515 14:18:20     1 store_ec.go:52] MountEcShards 1.13
I0515 14:18:20     1 volume_grpc_erasure_coding.go:156] ec volume 1 shard delete []
** I0515 14:18:21     1 store.go:366] DeleteVolume 1 **
I0515 15:44:03     1 store_ec.go:52] MountEcShards 2.0
I0515 15:44:03     1 store_ec.go:52] MountEcShards 2.1
I0515 15:44:03     1 store_ec.go:52] MountEcShards 2.2
I0515 15:44:03     1 store_ec.go:52] MountEcShards 2.3
I0515 15:44:03     1 store_ec.go:52] MountEcShards 2.4
I0515 15:44:03     1 store_ec.go:52] MountEcShards 2.5
I0515 15:44:03     1 store_ec.go:52] MountEcShards 2.6
I0515 15:44:03     1 store_ec.go:52] MountEcShards 2.7
I0515 15:44:03     1 store_ec.go:52] MountEcShards 2.8
I0515 15:44:03     1 store_ec.go:52] MountEcShards 2.9
I0515 15:44:03     1 store_ec.go:52] MountEcShards 2.10
I0515 15:44:03     1 store_ec.go:52] MountEcShards 2.11
I0515 15:44:03     1 store_ec.go:52] MountEcShards 2.12
I0515 15:44:03     1 store_ec.go:52] MountEcShards 2.13
```

As you can see, there is a `DeleteVolume 1` in this log.

When this file can not be access, there is 500 error and return `volume 1 not found`

When I restart `A`'s `volume`，the volume 1 can be found again.

I want to know why `volume` delete some volume that contains data, how to aviod it?

Here's my `master.toml`, may be this reference to this problem?

```
[master.maintenance]
# periodically run these scripts are the same as running them from 'weed shell'
scripts = """
  ec.encode -fullPercent=95 -quietFor=1h
  ec.rebuild -force
  ec.balance -force
  volume.balance -collection=ALL_COLLECTIONS -force
  volume.fix.replication
"""
sleep_minutes = 1  
```

Thanks!

**Comment by chrislusf** [comment]
thanks for the logs. This is because of the erasure encoding. Seems a problem when switching from normal volume to Erasure Coded volume.

```
ec.encode -fullPercent=95 -quietFor=1h
```

**Comment by youngcube** [comment]
So if I just have 1`master`, 1 `filer`,may be add some more `volume` afterwards. but I can keep `master` and `filer` only one all the time. is it ok that i remove the `[master.maintenance]` column in `master.toml` to avoid this problem?
Thanks for quick reply!

**Comment by chrislusf** [comment]
yes, it is ok.
