### ISSUE TITLE
Benchmark wrong

### ISSUE THREAD

**Issue by zdyj3170101136** [chrislusf/seaweedfs#1309]
<img width="448" alt="截屏2020-05-11下午10 20 24" src="https://user-images.githubusercontent.com/52686065/81572298-9ed07480-93d5-11ea-9eb1-461fa36e7d39.png">
你使用以上变量来作为benchmark测试的单位。
因此state的data数组总共长为1e5，因此data数据的长度应该是一格100ms。

以下是你用来计算ms的，这里原来单位是10，我改为100后才能得到正确的ms单位。
<img width="782" alt="截屏2020-05-11下午10 22 05" src="https://user-images.githubusercontent.com/52686065/81572482-db03d500-93d5-11ea-800c-5149c0504cd9.png">

**Comment by chrislusf** [comment]
No. For example, one thread with 100000 requests finished in 10.393 seconds. The average is 0.1ms.

```
Concurrency Level:      1
Time taken for tests:   10.393 seconds
Complete requests:      100000
Failed requests:        0
Total transferred:      105558211 bytes
Requests per second:    9622.11 [#/sec]
Transfer rate:          9918.88 [Kbytes/sec]

Connection Times (ms)
              min      avg        max      std
Total:        0.0      0.1       0.6      0.1

Percentage of the requests served within a certain time (ms)
   50%      0.0 ms
   66%      0.1 ms
  100%      0.6 ms
```
