### ISSUE TITLE
集群数据迁移

### ISSUE THREAD

**Issue by song306** [chrislusf/seaweedfs#1311]
系统版本：centos7
内核版本：3.10.0-957.el7.x86_64
软件版本：version 30GB 1.44 linux amd64
旧机房节点1 192.168.8.10
root /bin/sh -c cd /data/seaweedFS/filer &&  /usr/local/seaweedFS/weed -logdir=/data/logs/seaweed/filer -v=2 filer  -defaultReplicaPlacement=100 -maxMB=100  -ip=192.168.8.10 -port=8888  -master=192.168.8.10:9333,192.168.8.20:9333,192.168.8.30:9333  -disableDirListing
root /usr/local/seaweedFS/weed -logdir=/data/logs/seaweed/filer -v=2 filer -defaultReplicaPlacement=100 -maxMB=100 -ip=192.168.8.10 -port=8888 -master=192.168.8.10:9333,192.168.8.20:9333,192.168.8.30:9333 -disableDirListing
root /usr/local/seaweedFS/weed -logdir=/data/logs/seaweed/volume1 -v=2 volume -dataCenter=DC1 -rack=RC1 -index=leveldb -ip=192.168.8.10 -ip.bind=192.168.8.10 -port=8081 -dir=/data/seaweedFS/volume1 -max=7 -mserver=192.168.8.10:9333,192.168.8.20:9333,192.168.8.30:9333
root /usr/local/seaweedFS/weed -logdir=/data/logs/seaweed/volume2 -v=2 volume -dataCenter=DC1 -rack=RC1 -index=leveldb -ip=192.168.8.10 -ip.bind=192.168.8.10 -port=8082 -dir=/data/seaweedFS/volume2 -max=7 -mserver=192.168.8.10:9333,192.168.8.20:9333,192.168.8.30:9333
root /usr/local/seaweedFS/weed -logdir=/data/logs/seaweed/volume3 -v=2 volume -dataCenter=DC1 -rack=RC1 -index=leveldb -ip=192.168.8.10 -ip.bind=192.168.8.10 -port=8083 -dir=/data/seaweedFS/volume3 -max=7 -mserver=192.168.8.10:9333,192.168.8.20:9333,192.168.8.30:9333
root /usr/local/seaweedFS/weed -logdir=/data/logs/seaweed/volume4 -v=2 volume -dataCenter=DC1 -rack=RC1 -index=leveldb -ip=192.168.8.10 -ip.bind=192.168.8.10 -port=8084 -dir=/data/seaweedFS/volume4 -max=6 -mserver=192.168.8.10:9333,192.168.8.20:9333,192.168.8.30:9333
root /usr/local/seaweedFS/weed -logdir=/data/logs/seaweed/volume5 -v=2 volume -dataCenter=DC1 -rack=RC1 -index=leveldb -ip=192.168.8.10 -ip.bind=192.168.8.10 -port=8085 -dir=/data/seaweedFS/volume5 -max=6 -mserver=192.168.8.10:9333,192.168.8.20:9333,192.168.8.30:9333
旧机房节点2 192.168.8.20
root  /bin/sh -c cd /data/seaweedFS/filer &&  /usr/local/seaweedFS/weed -logdir=/data/logs/seaweed/filer -v=2 filer  -defaultReplicaPlacement=100 -maxMB=100  -ip=192.168.8.20 -port=8888  -master=192.168.8.10:9333,192.168.8.20:9333,192.168.8.30:9333  -disableDirListing
root  /usr/local/seaweedFS/weed -logdir=/data/logs/seaweed/filer -v=2 filer -defaultReplicaPlacement=100 -maxMB=100 -ip=192.168.8.20 -port=8888 -master=192.168.8.10:9333,192.168.8.20:9333,192.168.8.30:9333 -disableDirListing
root  /usr/local/seaweedFS/weed -logdir=/data/logs/seaweed/volume1 -v=2 volume -dataCenter=DC2 -rack=RC1 -index=leveldb -ip=192.168.8.20 -ip.bind=192.168.8.20 -port=8081 -dir=/data/seaweedFS/volume1 -max=7 -mserver=192.168.8.10:9333,192.168.8.20:9333,192.168.8.30:9333
root  /usr/local/seaweedFS/weed -logdir=/data/logs/seaweed/volume2 -v=2 volume -dataCenter=DC2 -rack=RC1 -index=leveldb -ip=192.168.8.20 -ip.bind=192.168.8.20 -port=8082 -dir=/data/seaweedFS/volume2 -max=7 -mserver=192.168.8.10:9333,192.168.8.20:9333,192.168.8.30:9333
root  /usr/local/seaweedFS/weed -logdir=/data/logs/seaweed/volume3 -v=2 volume -dataCenter=DC2 -rack=RC1 -index=leveldb -ip=192.168.8.20 -ip.bind=192.168.8.20 -port=8083 -dir=/data/seaweedFS/volume3 -max=7 -mserver=192.168.8.10:9333,192.168.8.20:9333,192.168.8.30:9333
root  /usr/local/seaweedFS/weed -logdir=/data/logs/seaweed/volume4 -v=2 volume -dataCenter=DC2 -rack=RC1 -index=leveldb -ip=192.168.8.20 -ip.bind=192.168.8.20 -port=8084 -dir=/data/seaweedFS/volume4 -max=6 -mserver=192.168.8.10:9333,192.168.8.20:9333,192.168.8.30:9333
root  /usr/local/seaweedFS/weed -logdir=/data/logs/seaweed/volume5 -v=2 volume -dataCenter=DC2 -rack=RC1 -index=leveldb -ip=192.168.8.20 -ip.bind=192.168.8.20 -port=8085 -dir=/data/seaweedFS/volume5 -max=6 -mserver=192.168.8.10:9333,192.168.8.20:9333,192.168.8.30:9333
root  /usr/local/seaweedFS/weed -logdir=/data/logs/seaweed/master -v=2 master -ip=192.168.8.20 -ip.bind=192.168.8.20 -port=9333 -mdir=/data/seaweedFS/master -defaultReplication=100 -peers=192.168.8.10:9333,192.168.8.20:9333,192.168.8.30:9333 -whiteList=127.0.0.1,192.168.8.10,192.168.8.20,192.168.8.30

旧机房节点3 192.168.8.30
root /bin/sh -c cd /data/seaweedFS/filer &&  /usr/local/seaweedFS/weed -logdir=/data/logs/seaweed/filer -v=2 filer  -defaultReplicaPlacement=100 -maxMB=100  -ip=192.168.8.30 -port=8888  -master=192.168.8.10:9333,192.168.8.20:9333,192.168.8.30:9333  -disableDirListing
root /usr/local/seaweedFS/weed -logdir=/data/logs/seaweed/filer -v=2 filer -defaultReplicaPlacement=100 -maxMB=100 -ip=192.168.8.30 -port=8888 -master=192.168.8.10:9333,192.168.8.20:9333,192.168.8.30:9333 -disableDirListing
root /usr/local/seaweedFS/weed -logdir=/data/logs/seaweed/volume1 -v=2 volume -dataCenter=DC3 -rack=RC1 -index=leveldb -ip=192.168.8.30 -ip.bind=192.168.8.30 -port=8081 -dir=/data/seaweedFS/volume1 -max=7 -mserver=192.168.8.10:9333,192.168.8.20:9333,192.168.8.30:9333
root /usr/local/seaweedFS/weed -logdir=/data/logs/seaweed/volume2 -v=2 volume -dataCenter=DC3 -rack=RC1 -index=leveldb -ip=192.168.8.30 -ip.bind=192.168.8.30 -port=8082 -dir=/data/seaweedFS/volume2 -max=7 -mserver=192.168.8.10:9333,192.168.8.20:9333,192.168.8.30:9333
root /usr/local/seaweedFS/weed -logdir=/data/logs/seaweed/volume3 -v=2 volume -dataCenter=DC3 -rack=RC1 -index=leveldb -ip=192.168.8.30 -ip.bind=192.168.8.30 -port=8083 -dir=/data/seaweedFS/volume3 -max=7 -mserver=192.168.8.10:9333,192.168.8.20:9333,192.168.8.30:9333
root /usr/local/seaweedFS/weed -logdir=/data/logs/seaweed/volume4 -v=2 volume -dataCenter=DC3 -rack=RC1 -index=leveldb -ip=192.168.8.30 -ip.bind=192.168.8.30 -port=8084 -dir=/data/seaweedFS/volume4 -max=6 -mserver=192.168.8.10:9333,192.168.8.20:9333,192.168.8.30:9333
root /usr/local/seaweedFS/weed -logdir=/data/logs/seaweed/volume5 -v=2 volume -dataCenter=DC3 -rack=RC1 -index=leveldb -ip=192.168.8.30 -ip.bind=192.168.8.30 -port=8085 -dir=/data/seaweedFS/volume5 -max=6 -mserver=192.168.8.10:9333,192.168.8.20:9333,192.168.8.30:9333
root /usr/local/seaweedFS/weed -logdir=/data/logs/seaweed/master -v=2 master -ip=192.168.8.30 -ip.bind=192.168.8.30 -port=9333 -mdir=/data/seaweedFS/master -defaultReplication=100 -peers=192.168.8.10:9333,192.168.8.20:9333,192.168.8.30:9333 -whiteList=127.0.0.1,192.168.8.10,192.168.8.20,192.168.8.30

三台机器filer.toml一致
[ybom@zy-tw-yabo-public-seaweedfs02 filer]$ cat filer.toml  |grep -v ^# |grep -v ^$
[memory]
enabled = false
[leveldb]
enabled = false
dir = "."                                       # directory to store level db files
[leveldb2]
enabled = false
dir = "."                                       # directory to store level db files
[mysql]  # or tidb
enabled = false
hostname = "localhost"
port = 3306
username = "root"
password = ""
database = ""              # create or use an existing database
connection_max_idle = 2
connection_max_open = 100
[postgres] # or cockroachdb
enabled = false
hostname = "localhost"
port = 5432
username = "postgres"
password = ""
database = ""              # create or use an existing database
sslmode = "disable"
connection_max_idle = 100
connection_max_open = 100
[cassandra]
enabled = false
keyspace="seaweedfs"
hosts=[
        "localhost:9042",
]
[redis]
enabled = false
address  = "localhost:6379"
password = ""
database = 0
[redis_cluster]
enabled = true
addresses = [
    "192.168.8.10:7001",
    "192.168.8.20:7001",
    "192.168.8.30:7001",
]
password = "123qwe"
[etcd]
enabled = false
servers = "localhost:2379"
timeout = "3s"

方式一、使用export导出，再使用upload/filer.copy 上传
旧集群节点2 ：
/usr/local/seaweedFS/weed export -dir=/data/seaweedFS/volume4 -volumeId=1 -o=/data/seaweedfs_export/prod1.tar -fileNameFormat={{.Name}}
scp到新集群节点1
新集群节点1：
/usr/local/seaweedfs/weed  filer.copy ./*  http://10.10.0.29:8888/
测试结果：
90%文件路径丢失只有文件名(aa/bb/cc.png 变成了cc.png)
10%路径和文件名重合(aa/bb/cc.png 变成了aabbcc.png)
方式二、weed shell -master 192.168.8.10:9333 进入后
使用fs.meta.save执行备份，但文件数只有1096个
修改文件名的localhost为ip地址
在新集群上执行fs.meta.load 192.168.8.20-xxxxx
导入文件1096个
进一步排查：发现fs系列命名和volume命令结果差距较大。
![image](https://user-images.githubusercontent.com/65273517/81777713-009ef480-9524-11ea-9f86-4e3c532ed543.png)
与volume.list执行结果差距较大
volume.list
volume id:1 size:16505889296 file_count:80869 delete_count:1261 deleted_byte_count:326134228 replica_placement:100 version:3 compact_revision:2 modified_at_second:1589349596  
volume id:2 size:16515261360 file_count:80411 delete_count:1279 deleted_byte_count:236264728 replica_placement:100 version:3 compact_revision:2 modified_at_second:1589349594  
....
方式三、
1)unmount新机房的volumeid 1-7
2)覆盖1-7的.dat和.idx
3)重启filer/master/所有volumex进程
4)mount volumeid 1-7
5)fs.ls 文件为空
6)volume.list 数据正确
尝试删除filer 家目录下的文件 重启依旧无效
尝试weed fix 数据目录 无效重启依旧无效

新机房启动方式和旧机房一致，版本为version 30GB 1.65 linux amd64

请大佬指教下现在该怎么做

**Comment by chrislusf** [comment]
as discussed, move redis and dat idx files.
