### ISSUE TITLE
master panic

### ISSUE THREAD

**Issue by yiitz** [chrislusf/seaweedfs#1313]
`http: panic serving : invalid argument to Intn
                                              goroutine 29191211 [running]:
                                              net/http.(*conn).serve.func1(0xc001198e60)
                                                      /var/jenkins_home/go/src/net/http/server.go:1772 +0x139
                                              panic(0x171d160, 0x1da9230)
                                                      /var/jenkins_home/go/src/runtime/panic.go:973 +0x396
                                              math/rand.(*Rand).Intn(0xc000114150, 0x0, 0x0)
                                                      /var/jenkins_home/go/src/math/rand/rand.go:169 +0x9c
                                              math/rand.Intn(...)
                                                      /var/jenkins_home/go/src/math/rand/rand.go:337
                                              github.com/chrislusf/seaweedfs/weed/server.(*MasterServer).redirectHandler(0xc000182540, 0x1e07b00, 0xc0005bfc00, 0xc0009f5f00)
                                                      /var/jenkins_home/workspace/weed/weed/server/master_server_handlers_admin.go:106 +0x12d
                                              net/http.HandlerFunc.ServeHTTP(0xc000049a80, 0x1e07b00, 0xc0005bfc00, 0xc0009f5f00)
                                                      /var/jenkins_home/go/src/net/http/server.go:2012 +0x44
                                              github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001e6000, 0x1e07b00, 0xc0005bfc00, 0xc0009f5d00)
                                                      /var/jenkins_home/gopath/pkg/mod/github.com/gorilla/mux@v1.7.3/mux.go:212 +0xe2
                                              golang.org/x/net/http2/h2c.h2cHandler.ServeHTTP(0x1dd7ea0, 0xc0001e6000, 0xc000124e40, 0x1e07b00, 0xc0005bfc00, 0xc0009f5d00)
                                                      /var/jenkins_home/gopath/pkg/mod/golang.org/x/net@v0.0.0-20190909003024-a7b16738d86b/http2/h2c/h2c.go:98 +0x31a
                                              net/http.serverHandler.ServeHTTP(0xc0005be000, 0x1e07b00, 0xc0005bfc00, 0xc0009f5d00)
                                                      /var/jenkins_home/go/src/net/http/server.go:2807 +0xa3
                                              net/http.(*conn).serve(0xc001198e60, 0x1e100c0, 0xc000d517c0)`
线上部署了3个master，请求一个文件的时候只有主master返回，其他两个不知道为什么没有找到文件，master_server_handlers_admin.go 106行代码location.Locations长度为0导致panic

**Comment by chrislusf** [comment]
added a fix for this. 

usually this happens when the other 2 masters did not elected the leader yet.

How to reproduce it?

**Comment by yiitz** [comment]
没有特别做什么，就是跑了很久然后就出现了，中间在shell上执行过ec balance。另外还有一个问题，我有3个volume跑在一台机器上，这两天cpu压力有点大，我把其中一个volume迁移到新机器上后发现请求master时还重定向到停掉的volume的旧的ip和端口上，重启master之后正常（这个操作是在上面的issue之后做的，两者没有关系）。源码我小改了一下把http改成h2c支持http2了,就几行代码。

**Comment by yiitz** [comment]
几个volume这两天报慢的请求很频繁，很多5-10秒的，不知道有没有影响。版本是1.73
