### ISSUE TITLE
Replication Issue  -defaultReplication=020  

### ISSUE THREAD

**Issue by ajitpalsinghjat** [chrislusf/seaweedfs#1316]
We have started seaweedfs in our environment as below mentioned :

i) 2 Filer server running in Cluster
ii) 3 Master running in cluster
iii) 3 Volume server  (same data center but 3 different racks)

Commands : 

**Master:**   - 3 Master server 

/root/go/bin/weed master -ip=172.23.125.58 -port=9333 -mdir=/opt/mdata -peers=172.23.125.58:9333,172.23.125.52:9333,172.23.125.59:9334 -defaultReplication=020 &

**Volume:**  3 Volume server 

./weed volume -dir=/opt/data2 -ip=172.23.125.58 -port=4080 -mserver=172.23.125.58:9333,172.23.125.52:9333,172.23.125.59:9334 -dataCenter=dc1 -rack=rack3 &

- Master server running with the -defaultReplication=020 
- We want all the images should replicate on every volume server.

Issue: All the volume server are diff in size. like (1st volume 5 GB , 2nd volume 1.5 GB, 3rd volume 2.5 GB).

How to verify that all the images are getting replicate on all volume ?

**Comment by chrislusf** [comment]
Can you share the "ls -l" results on the volume servers?

defaultReplication is default value. Your code may have overwritten it.

**Comment by ajitpalsinghjat** [comment]
**ls -l :**

root@fi-test-app-52:~/.seaweedfs# ls -l

drwxr-xr-x 2 root root 4096 Dec 12 18:36 filer
-rw-r--r-- 1 root root  602 Dec 12 18:15 filer.toml
-rw-r--r-- 1 root root 2070 Dec 11 18:17 notification.toml
-rw-r--r-- 1 root root 2148 Dec 12 18:39 replication.toml
-rw-r--r-- 1 root root 1860 Jan 17 11:50 security.toml

-------------------------------------------------------------------------------------------------

**replication.toml**

[source.filer]
enabled = true
grpcAddress = "172.23.125.52:2035"
# all files under this directory tree are replicated.
# this is not a directory on your hard drive, but on your filer.
# i.e., all files with this "prefix" are sent to notification message queue.
directory = "/opt/filer"

[sink.filer]
enabled = true
grpcAddress = "172.23.125.58:2035"
# all replicated files are under this directory tree
# this is not a directory on your hard drive, but on your filer.
# i.e., all received files will be "prefixed" to this directory.
directory = "/opt/filer"
replication = ""
collection = ""
ttlSec = 0

[sink.s3]
--------------------------------------------------------------------------------------------------

**filer.toml**


[mysql]
enabled = true
hostname = "xxxxxxx"                     # xxx - replaced by actual values
port = xxxxxx
username = "xxxxxxxx"
password = "xxxxxxxxx"
database = "fileserverDB"              # create or use an existing database
connection_max_idle = 2
connection_max_open = 100
interpolateParams = false

**Comment by chrislusf** [comment]
Please show the filer command line you used.

**Comment by ajitpalsinghjat** [comment]
> Please show the filer command line you used.

1st server - >  /root/go/bin/weed filer -port 2035 -master=172.23.125.58:9333,172.23.125.52:9333,172.23.125.59:9334 mount -dir=/opt/filer &

2nd server -> /root/go/bin/weed filer -port 2035 -master=172.23.125.58:9333,172.23.125.52:9333,172.23.125.59:9334 mount -dir=/opt/filer &

**Comment by chrislusf** [comment]
add this to filer command line
`-defaultReplicaPlacement=020`

**Comment by ajitpalsinghjat** [comment]
> add this to filer command line
> `weed filer -defaultReplicaPlacement=020 `

Thanks for the quick reply, will do the changes and will test it.

Please help me on the below points as well:

i) Will it work on the only new coming data ?
ii) Do i need to run volume balancing for existing data replication .

Thanks again.

**Comment by chrislusf** [comment]
i) yes
ii) rebalancing does not hurt.

**Comment by ajitpalsinghjat** [comment]
> i) yes
> ii) rebalancing does not hurt.

Hi,

I have configured as per your suggestion and uploaded one file on filer IP, but that got written in one volume only and not synced with any other volume.

Now its running with below commands:

-  /root/go/bin/weed filer -port 2035 -master=172.23.125.61:9333,172.23.125.66:9333,172.23.125.66:9334 mount -dir=/opt/filer -defaultReplicaPlacement=020 &

-  /root/go/bin/weed volume -dir=/opt/data1 -ip=172.23.125.61 -port=3080 -mserver=172.23.125.61:9333,172.23.125.66:9333,172.23.125.66:9334 -dataCenter=dc1 -rack=rack1 &
 
-  /root/go/bin/weed master -ip=172.23.125.61 -port=9333 -mdir=/opt/mdata -peers=172.23.125.61:9333,172.23.125.66:9333,172.23.125.66:9334 -defaultReplication=020 &

**Comment by ajitpalsinghjat** [comment]
> > i) yes
> > ii) rebalancing does not hurt.
> 
> Hi,
> 
> I have configured as per your suggestion and uploaded one file on filer IP, but that got written in one volume only and not synced with any other volume.
> 
> Now its running with below commands:
> 
> * /root/go/bin/weed filer -port 2035 -master=172.23.125.61:9333,172.23.125.66:9333,172.23.125.66:9334 mount -dir=/opt/filer -defaultReplicaPlacement=020 &
> * /root/go/bin/weed volume -dir=/opt/data1 -ip=172.23.125.61 -port=3080 -mserver=172.23.125.61:9333,172.23.125.66:9333,172.23.125.66:9334 -dataCenter=dc1 -rack=rack1 &
> * /root/go/bin/weed master -ip=172.23.125.61 -port=9333 -mdir=/opt/mdata -peers=172.23.125.61:9333,172.23.125.66:9333,172.23.125.66:9334 -defaultReplication=020 &

Can you please suggest anything on this.

**Comment by chrislusf** [comment]
check how you upload files.

**Comment by ajitpalsinghjat** [comment]
i) Master replication working fine.
ii) Issue is in filer replication.
iii) Below is the method we used for file upload:

URL  http://172.23.125.53:2035

**REQUEST**

POST /filer/test/012345.jpg HTTP/1.1
User-Agent: PostmanRuntime/7.24.1
Accept: */*
Cache-Control: no-cache
Postman-Token: cd07283e-1055-4ad0-b9b1-fa7ac39af9d1
Host: 172.23.125.53:2035
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Type: multipart/form-data; boundary=--------------------------841874836375340273643570
Content-Length: 6183589
----------------------------841874836375340273643570
Content-Disposition: form-data; name=""; filename="xyz.csv"
<xyz.csv>
----------------------------841874836375340273643570--

**RESPONSE**

HTTP/1.1 201 Created
Content-Type: application/json
Etag: "5639bc87"
Date: Wed, 10 Jun 2020 06:47:31 GMT
Content-Length: 125
{"name":"xyz.csv","size":6183366,"fid":"2,11cac96f0b","url":"http://172.23.125.82:3080/2,11cac96f0b"}

**Comment by ajitpalsinghjat** [comment]
> The log does not have any useful info. Need to share some code to make a reproducible case.

Hi,

I last comment i shared the Request and Response from SOP UI (rest call).

**Please find the below code, where we calling filer :**


private RestTemplate restTemplate;
 

 

public FileSubmitResponse submitFile(byte[] bytesArray, String fileName) {
    String urlWithScheme = getUrlWithScheme(serverConfig.getLeaderEndPoint() + submitPath);
    LOGGER.info("submitFile  {}" , urlWithScheme);
    FileSubmitResponse fileSubmitResponse = null;
    ResponseEntity<FileSubmitResponse> response = null;
    boolean isError = false;
    try {
        MultiValueMap<String, Object> body
            = new LinkedMultiValueMap<>();
        body.add("file", new ByteArrayResource(bytesArray) {
            @Override
            public String getFilename() {
                return fileName;
            }
        });
        response = restTemplate.postForEntity(urlWithScheme, body, FileSubmitResponse.class);
        if (response != null && (response.getStatusCode() == HttpStatus.OK || response.getStatusCode() == HttpStatus.ACCEPTED || response.getStatusCode() == HttpStatus.CREATED)) {
            fileSubmitResponse = response.getBody();
        }
    } catch (Exception e) {
        isError = true;
        throw e;
    } finally {
        printIFError(urlWithScheme, isError, response == null);
    }
    return fileSubmitResponse;
}

**Comment by chrislusf** [comment]
what is the value for urlWithScheme?

**Comment by ajitpalsinghjat** [comment]
> what is the value for urlWithScheme?

Below is the value of urlWithScheme :

**http://10.11.52.5:2035**   (Its a Load balancer IP and behind that we have 2 filer server)

**Comment by chrislusf** [comment]
I could not reproduce it. Need some working scripts/code.

**Comment by ajitpalsinghjat** [comment]
> I could not reproduce it. Need some working scripts/code.

It would be helpful if you can provide some running code for this. Else it would be great if you can spare some time for us and we can show you our deployment and code over the remote (webex/Zoom/Anydesk).

Your help will appreciable as we need to move it to production due to some urgency.

**Comment by chrislusf** [comment]
If I start the servers with 
```
mkdir 1 2 3
weed server -dir=1 -volume.max=0 -filer -filer.defaultReplicaPlacement=200 &
weed volume -dataCenter=dc2 -port=8081 -dir=2 &
weed volume -dataCenter=dc3 -port=8082 -dir=3 &
```
And run
```
$ curl -F "file=@filer.toml" "http://localhost:8888/tmp2/"
{"name":"filer.toml","size":1322,"fid":"15,10036efafe2e60","url":"http://192.168.2.3:8081/15,10036efafe2e60"}
```

The list the volumes. The files are repeated in these volumes.
```
mobile_disk$ ls -al 1/15.dat
-rw-r--r--  1 chris  staff  984 Jun 16 13:07 1/15.dat
mobile_disk$ ls -al 2/15.dat
-rw-r--r--  1 chris  staff  984 Jun 16 13:07 2/15.dat
mobile_disk$ ls -al 3/15.dat
-rw-r--r--  1 chris  staff  984 Jun 16 13:07 3/15.dat
```

**Comment by ajitpalsinghjat** [comment]
> If I start the servers with
> 
> ```
> mkdir 1 2 3
> weed server -dir=1 -volume.max=0 -filer -filer.defaultReplicaPlacement=200 &
> weed volume -dataCenter=dc2 -port=8081 -dir=2 &
> weed volume -dataCenter=dc3 -port=8082 -dir=3 &
> ```
> 
> And run
> 
> ```
> $ curl -F "file=@filer.toml" "http://localhost:8888/tmp2/"
> {"name":"filer.toml","size":1322,"fid":"15,10036efafe2e60","url":"http://192.168.2.3:8081/15,10036efafe2e60"}
> ```
> 
> The list the volumes. The files are repeated in these volumes.
> 
> ```
> mobile_disk$ ls -al 1/15.dat
> -rw-r--r--  1 chris  staff  984 Jun 16 13:07 1/15.dat
> mobile_disk$ ls -al 2/15.dat
> -rw-r--r--  1 chris  staff  984 Jun 16 13:07 2/15.dat
> mobile_disk$ ls -al 3/15.dat
> -rw-r--r--  1 chris  staff  984 Jun 16 13:07 3/15.dat
> ```



Hi Crish,

I have created a script to simulate my environment :  2 filer server, 3 master server, 3 volume server.

Requirement # cd /opt ;  mkdir 1 2 3 f1 f2 m1 m2 m3
--------------------------------------------------------------------------------------------------------------------------------------------
**/replication.toml   for reference **

[source.filer]
enabled = true
grpcAddress = "localhost:2035"
# all files under this directory tree are replicated.
# this is not a directory on your hard drive, but on your filer.
# i.e., all files with this "prefix" are sent to notification message queue.
directory = "/opt/f1"

[sink.filer]
enabled = true
grpcAddress = "localhost:2036"
# all replicated files are under this directory tree
# this is not a directory on your hard drive, but on your filer.
# i.e., all received files will be "prefixed" to this directory.
directory = "/opt/f2"
replication = ""
collection = ""
ttlSec = 0


**Script :** 
--------------------------------------------------------------------------------------------------------------------------------------------
#/bin/bash

#Starting 2 filer server

/root/go/bin/weed filer -port 2035 -master=localhost:9333,localhost:9334,localhost:9335 mount -dir=/opt/f1 -defaultReplicaPlacement=020 &
/root/go/bin/weed filer -port 2036 -master=localhost:9333,localhost:9334,localhost:9335 mount -dir=/opt/f2 -defaultReplicaPlacement=020 &

# Starting 3 master server

/root/go/bin/weed master -ip=localhost -port=9333 -mdir=/opt/m1 -peers=localhost:9333,localhost:9334,localhost:9335 -defaultReplication=020 &
/root/go/bin/weed master -ip=localhost -port=9334 -mdir=/opt/m2 -peers=localhost:9333,localhost:9334,localhost:9335 -defaultReplication=020 &
/root/go/bin/weed master -ip=localhost -port=9335 -mdir=/opt/m3 -peers=localhost:9333,localhost:9334,localhost:9335 -defaultReplication=020 &

# Starting 3 volume server

/root/go/bin/weed volume -dir=/opt/1 -ip=localhost -port=3081 -mserver=localhost:9333,localhost:9334,localhost:9335 -dataCenter=dc1 -rack=rack1 &
/root/go/bin/weed volume -dir=/opt/2 -ip=localhost -port=3082 -mserver=localhost:9333,localhost:9334,localhost:9335 -dataCenter=dc1 -rack=rack2 &
/root/go/bin/weed volume -dir=/opt/3 -ip=localhost -port=3083 -mserver=localhost:9333,localhost:9334,localhost:9335 -dataCenter=dc1 -rack=rack3 &

**Comment by ajitpalsinghjat** [comment]
I Also want to highlight that we are using weed binaries are 7 month old not the updated one. it can be an issue ?

**Comment by chrislusf** [comment]
I do not have the binary 7 month old. Maybe you can use the latest binary to test.

**Comment by ajitpalsinghjat** [comment]
I have tested it with the latest weed binaries but still same issue. could you please try to run the below script for reproduce the issue:

I have created a script to simulate my environment : 2 filer server, 3 master server, 3 volume server.

Requirement #cd /opt ; mkdir 1 2 3 f1 f2 m1 m2 m3
**/replication.toml for reference **

[source.filer]
enabled = true
grpcAddress = "localhost:2035"

directory = "/opt/f1"

[sink.filer]
enabled = true
grpcAddress = "localhost:2036"

directory = "/opt/f2"
replication = ""
collection = ""
ttlSec = 0

Script :
#/bin/bash

#Starting 2 filer server

/root/go/bin/weed filer -port 2035 -master=localhost:9333,localhost:9334,localhost:9335 mount -dir=/opt/f1 -defaultReplicaPlacement=020 &
/root/go/bin/weed filer -port 2036 -master=localhost:9333,localhost:9334,localhost:9335 mount -dir=/opt/f2 -defaultReplicaPlacement=020 &

#Starting 3 master server

/root/go/bin/weed master -ip=localhost -port=9333 -mdir=/opt/m1 -peers=localhost:9333,localhost:9334,localhost:9335 -defaultReplication=020 &
/root/go/bin/weed master -ip=localhost -port=9334 -mdir=/opt/m2 -peers=localhost:9333,localhost:9334,localhost:9335 -defaultReplication=020 &
/root/go/bin/weed master -ip=localhost -port=9335 -mdir=/opt/m3 -peers=localhost:9333,localhost:9334,localhost:9335 -defaultReplication=020 &

#Starting 3 volume server

/root/go/bin/weed volume -dir=/opt/1 -ip=localhost -port=3081 -mserver=localhost:9333,localhost:9334,localhost:9335 -dataCenter=dc1 -rack=rack1 &
/root/go/bin/weed volume -dir=/opt/2 -ip=localhost -port=3082 -mserver=localhost:9333,localhost:9334,localhost:9335 -dataCenter=dc1 -rack=rack2 &
/root/go/bin/weed volume -dir=/opt/3 -ip=localhost -port=3083 -mserver=localhost:9333,localhost:9334,localhost:9335 -dataCenter=dc1 -rack=rack3 &

**Comment by chrislusf** [comment]
your scripts would not have worked. The commands are wrong.

> 
> /root/go/bin/weed filer -port 2035 -master=localhost:9333,localhost:9334,localhost:9335 mount -dir=/opt/f1 -defaultReplicaPlacement=020 &
> /root/go/bin/weed filer -port 2036 -master=localhost:9333,localhost:9334,localhost:9335 mount -dir=/opt/f2 -defaultReplicaPlacement=020 &

**Comment by ajitpalsinghjat** [comment]
Yes, I have tested it with your setup and its working fine but in this all the components are on same server. Our setup is different, we have 3 volume on different server.

- We need to replicate every image in all 3 volumes for High availability so we have created 3 different volume server.
- As per the documentation we have created 3 master server on 3 different server. 
- As per the document we have created 2 filer server (using mysql) on 2 different server.

We are hitting the Filer IP so it can replicate the images in volume servers. 

Please suggest us if anything we need to change in this, if you feel. Please let me know if you would require its architecture diagram.

**Comment by chrislusf** [comment]
These two commands are wrong. There are no `-dir=/opt/f1` option. The `filer.toml` is needed to configure filer leveldb folder.

> /root/go/bin/weed filer -port 2035 -master=localhost:9333,localhost:9334,localhost:9335 mount -dir=/opt/f1 -defaultReplicaPlacement=020 &
> /root/go/bin/weed filer -port 2036 -master=localhost:9333,localhost:9334,localhost:9335 mount -dir=/opt/f2 -defaultReplicaPlacement=020 &

**Comment by chrislusf** [comment]
Removing those wrong options, `mount -dir=/opt/f2` from `weed filere` will make the it work.

**Comment by ajitpalsinghjat** [comment]
Thanks chrislusf, Its working fine now. Thank you so much for your support.
