### ISSUE TITLE
After volume.balance moved a volume: stat idx file .idx failed

### ISSUE THREAD

**Issue by Radtoo** [chrislusf/seaweedfs#1317]
On Snapraid: Version 8000GB 1.77 linux amd64 (both machines involved)

During volume.balance, moved volumes' idx files became unrecognizable somehow:
```
> volume.balance -force
moving volume 2 192.168.1.113:8995 => 192.168.1.130:8526                                                                                                                            
2020-05-17 04:15:49.992744 I | copying volume 2 from 192.168.1.113:8995 to 192.168.1.130:8526
2020-05-17 04:20:24.665441 I | tailing volume 2 from 192.168.1.113:8995 to 192.168.1.130:8526
2020-05-17 04:20:36.823121 I | deleting volume 2 from 192.168.1.113:8995
2020-05-17 04:20:40.512024 I | moved volume 2 from 192.168.1.113:8995 to 192.168.1.130:8526
moving volume 3 192.168.1.113:8995 => 192.168.1.130:8526
2020-05-17 04:20:40.512072 I | copying volume 3 from 192.168.1.113:8995 to 192.168.1.130:8526
2020-05-17 04:25:18.733374 I | tailing volume 3 from 192.168.1.113:8995 to 192.168.1.130:8526
2020-05-17 04:25:30.890895 I | deleting volume 3 from 192.168.1.113:8995
2020-05-17 04:25:32.675848 I | moved volume 3 from 192.168.1.113:8995 to 192.168.1.130:8526
```
A few minutes I notice that this was moved rather than replicated, set the respective replication to 010, and try to re-replicate (multiple times, to show all moved volumes were affected):
```
> volume.fix.replication
replicating volume 2 010 from 192.168.1.130:8526 to dataNode 192.168.1.113:8995 ...
error: rpc error: code = Unknown desc = stat idx file .idx failed, stat .idx: no such file or directory

> volume.fix.replication
replicating volume 3 010 from 192.168.1.130:8526 to dataNode 192.168.1.113:8995 ...
error: rpc error: code = Unknown desc = stat idx file .idx failed, stat .idx: no such file or directory
```
The odd thing is that if I look at the filesystem, these files are present and seem to have been moved when it was indicated:
```
-rw-r--r--+  1 seaweedfs seaweedfs 31457805048 May 17 04:20 2.dat
-rw-r--r--+  1 seaweedfs seaweedfs     2098344 May 17 04:20 2.idx
-rw-r--r--+  1 seaweedfs seaweedfs          60 May 17 04:43 2.vif
-rw-r--r--+  1 seaweedfs seaweedfs 31483320088 May 17 04:25 3.dat
-rw-r--r--+  1 seaweedfs seaweedfs     2139450 May 17 04:25 3.idx
-rw-r--r--+  1 seaweedfs seaweedfs          60 May 17 04:43 3.vif
```
Is there a way to make it use these .idx files? Also: Maybe seaweedfs should run a sanity check prior to deleting remote volumes?

**Comment by chrislusf** [comment]
I could not reproduce it, but I added some more error checking before copying files.

**Comment by Radtoo** [comment]
The server startup seems to be ok with loading the idx files:
I0518 07:27:19 81450 volume_loading.go:104] loading index /mnt/seaweedfs-data/3.idx to memory. Even volume.fsck doesn't mind the respective volumes.  It's apparently mainly volume.fix.replication and volume.balance -force? 

I spotted two strange things though.

1. Shouldn't the messages actually say something like:
replicating volume 2 010 from 192.168.1.130:8526 to dataNode 192.168.1.113:8995 ...
error: rpc error: code = Unknown desc = stat idx file **2**.idx failed, stat **2**.idx: no such file or directory
or
replicating volume 3 010 from 192.168.1.130:8526 to dataNode 192.168.1.113:8995 ...
error: rpc error: code = Unknown desc = stat idx file **3**.idx failed, stat **3**.idx: no such file or directory

At least if I understand [this](https://github.com/chrislusf/seaweedfs/blob/75179544c35575be09f09f32103d5eb4562d28d1/weed/server/volume_grpc_copy.go#L149) correctly, it should have the idx file name, right?  But it missing from the error.

2. The mask for the ACLs on the respective files was wrong for unknown reasons:
```
> getfacl 2.idx
# owner: seaweedfs
# group: seaweedfs
user::rw-
user:seaweedfs:rwx              #effective:r--
group::r-x                      #effective:r--
group:seaweedfs:rwx             #effective:r--
mask::r--
other::r--
```
This doesn't match the default ACLs. Unfortunately changing it back to effective rwx doesn't actually make volume.fix.replication and volume.balance -force work again, even after restarting seaweedfs. But it is quite strange regardless. Maybe it caused issues at some point.
