### ISSUE TITLE
Volume Management Scripts Question

### ISSUE THREAD

**Issue by Jon-Murray** [chrislusf/seaweedfs#1319]
Hi,

   I am reading the documentation here: https://github.com/chrislusf/seaweedfs/wiki/Volume-Management

It says it is best practise to run   
```
  ec.encode -fullPercent=95 -quietFor=1h
  ec.rebuild -force
  ec.balance -force
  volume.balance -force
  volume.fix.replication
```

periodically. However, underneath it it does say: "If the master.toml has the above configuration, the scripts will run every 17 minutes. It has the same effect as running from weed shell directly. **However, be sure to avoid running both at the same time.**"

I currently have weed set up so i have a cluster set up as 4 servers (A,B,C,D), with 4 8TB drives each, and 3 master nodes (A,B,C). I wanted to generate this master config file to allow for periodic rebalancing, error checking, etc. on each of the three master nodes.

In my scenario I wanted to ask a few questions:

- Will replication, balancing, etc. take place if a node is not a master? 

- Will it relay it on to the master to execute it? If so, will this only do each operation once? (ie. no 3 concurrent rebalancing operations in my scenario)
 
- In the case of a corrupted/replaced drive, should i just replace the drive and wait for the automatic script to take care of it, or trigger this directly from weed shell? (i think i know the answer, but just making sure here!)
 
- Is it correct to have this master.toml (above) in all master nodes, or just the actual elected master node?

I am still in early days of this library but wanted to say thank you so much as it has been really great so far.

**Comment by chrislusf** [comment]
> * Will replication, balancing, etc. take place if a node is not a master?

These operations are for the whole cluster.

> * Will it relay it on to the master to execute it? If so, will this only do each operation once? (ie. no 3 concurrent rebalancing operations in my scenario)

There is a global lock for the whole cluster.

> * In the case of a corrupted/replaced drive, should i just replace the drive and wait for the automatic script to take care of it, or trigger this directly from weed shell? (i think i know the answer, but just making sure here!)

Either way. Just depends on whether you want it to run right away or not.

> * Is it correct to have this master.toml (above) in all master nodes, or just the actual elected master node?

On all master nodes.
