### ISSUE TITLE
Information System using Weed-fs

### ISSUE THREAD

**Issue by fincantieri** [chrislusf/seaweedfs#132]
can weed-fs use as mysql with queries and upload images or files in a specified directory?..i want to create a simple information system using php-resty + weed-fs.. is it possible Mr.Chrisluf?.. but i don't know how can i move the volumeId in a specified folder, and call the imageId by VolumeId to the url with sub directories.. i can't see any website developer that they use weed-fs in their image upload system.. so that i want to know, if this weed-fs can serve as mysql database.. Thank you..

**Comment by chrislusf** [comment]
Not sure about your requirements. Seems you can use the filer option?

"weed server -filer=true"

And access the filer via http directly?

**Comment by fincantieri** [comment]
i'm using php, ngx_openresty, and your weedfs, sir.. i didn't tried before the filer via http.. but, is it already supported in php?
Date: Wed, 29 Apr 2015 22:57:51 -0700
