### ISSUE TITLE
terminating "weed mount" leaves "dir" hanging

### ISSUE THREAD

**Issue by onlyjob** [chrislusf/seaweedfs#1321]
When `weed mount` is terminated by Ctrl+C, the mount directory is left in the unusable state.

It would be great to catch `SIGTERM`, `SIGINT`, etc. to invoke `fusermount -u` on the mount directory automatically.

Thanks.

**Comment by chrislusf** [comment]
It is already there, but only best-effort. https://github.com/chrislusf/seaweedfs/blob/master/weed/command/mount_std.go#L149

**Comment by onlyjob** [comment]
Apparently implementation is not good enough?

---

You are closing issues way too hastily. This is a legitimate problem and instead of improving a reproducible symptom, you have just dismissed the report. Not good.
