### ISSUE TITLE
seaweedfs filer panic after server crash and restart

### ISSUE THREAD

**Issue by tianjipeng** [chrislusf/seaweedfs#1326]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs
Report issues here. Ask questions here https://stackoverflow.com/questions/tagged/seaweedfs

**Describe the bug**
We use leveldb2 as filer storage, after server crash and restart, filer will always panic when start it.

**System Setup**
- command line: weed filer
- OS version: centos7.4
- output of `weed version`: 1.61
- content of `filer.toml`: 
``[leveldb2]
enabled = true
dir = "/filer"     # directory to store level db files``

**Expected behavior**
filer run normally

**Screenshots**
![image-2020-05-15-14-59-27-444](https://user-images.githubusercontent.com/6982153/82652957-1366a700-9c51-11ea-90ab-55a6c3052f3d.png)

**Additional context**
I find the root cause that return the wrong err  in weed/filer2/leveldb2/leveldb2_store.go :
<img width="718" alt="WX20200522-172759" src="https://user-images.githubusercontent.com/6982153/82653484-d5b64e00-9c51-11ea-8463-54c3fab8cbbb.png">
Meanwhile, leveldb2 provide Recover function to repaire corruted data，so if `dbErr` is `ErrCorrupted`，we should  call `Recover` function.

**Comment by chrislusf** [comment]
Thanks a lot for the debugging! Good to learn this Recover feature!
