### ISSUE TITLE
no replication of filer data??

### ISSUE THREAD

**Issue by onlyjob** [chrislusf/seaweedfs#1327]
How to configure _filer_ for multi-master replication??

I have 3 masters talking to each other but filer data is not replicated.

The intent is to have _filer_ speaking to master@localhost and mount local _filer_ with FUSE mount.  
Where is the catch??

Also there seems to be no redundancy for _filer_ whatsoever or did I miss anything??  
How can I setup FUSE mount with fail-over to backup filer??

Thanks.

**Comment by chrislusf** [comment]
Default filer uses local leveldb. For multiple filers, the filer store needs to be a distributed store and filer itself becomes stateless.

https://github.com/chrislusf/seaweedfs/wiki/Filer-Stores

FUSE already has metadata sync. Local filer does not help much. Using remote filer is fast enough.

**Comment by onlyjob** [comment]
I see that Filer is the single point of failure and that it is not designed to replicate data on its own.

IMHO Filer should be incorporated into Master and something should be done to save Filer's metadata to all Master nodes automatically. One might even consider to store Filer's data into Volumes hence eliminating need for external filer stores/backends.

This is a very serious problem. All Filer Stores have single point of failure (except Etcd which is not scalable enough to handle large metadata).

**Comment by chrislusf** [comment]
You can use CockroachDB / Cassandra / TiDB / Redis cluster for a no-SPOF filer store.

In the future, filer with leveldb will sync metadata with each other to avoid SPOF.

**Comment by onlyjob** [comment]
> You can use CockroachDB / Cassandra / TiDB / Redis cluster for a no-SPOF filer store.

Unfortunately this is not good enough. Those backends are too complex/sophisticated (hard to deploy, configure and maintain), too many moving parts, etc...

`weed mount` can talk to one filer only and that is the foremost problem to address -- fail-over must be built into FUSE client.

> In the future, filer with leveldb will sync metadata with each other to avoid SPOF.

Thanks. Native replication is much needed feature.

**Comment by shm-dmitry** [comment]
@onlyjob , you can use `-defaultReplicaPlacement=xxx` command line parameter.
Example: `weed filer -collection=filer -defaultReplicaPlacement=200`
I found it [here](https://github.com/chrislusf/seaweedfs/blob/ed92992003706834e188a3110f59f8e383468a10/weed/command/filer.go#L51)

**Comment by onlyjob** [comment]
That's not for a replication of filer's _metadata_ but for a data. Filer don't replicate its own metadata as the replication is delegated to [filer store](https://github.com/chrislusf/seaweedfs/wiki/Filer-Stores) that should be configured separately. Default filer's store have no replication.

**Comment by shm-dmitry** [comment]
@onlyjob 
I use CockroachDB cluster for metadata replication.
It was simplest way.
https://www.cockroachlabs.com/docs/stable/orchestrate-cockroachdb-with-docker-swarm-insecure.html#undefined

**Comment by chrislusf** [comment]
@shm-dmitry could you please share your setup? I can try to bake it into the default distributed setups.

**Comment by onlyjob** [comment]
Thanks, @shm-dmitry. Personally I would not touch anything running on Swarm. Docker is terrible enough on is own. These days we should be using (superior) libpod/Podman.

**Comment by shm-dmitry** [comment]
@onlyjob , I using swarm as very simple orchestrator. I liked it because I was able to configure it in half an hour.

@chrislusf - you will need an odd number of manager-nodes - 1, 3, 5
You can use manager node as worker node.
You cat start on one host `swarm master`, `filer` and `CockroachDB`
Docs [here](https://docs.docker.com/engine/swarm/admin_guide/) and [here](https://docs.docker.com/engine/swarm/join-nodes/).

I assume you have 3 nodes with `filer`, and you want to install CockroachDB on them.
I assume you will run all commands as `root`.
I assume you hosts are named `host00`, `host01` and `host02`. Change hostname in commands.

1. Install docker on all nodes you need:
```
gpg --keyserver subkeys.pgp.net --recv 7EA0A9C3F273FCD8
gpg --export --armor 7EA0A9C3F273FCD8 | sudo apt-key add -
apt-add-repository http://download.docker.com/linux/ubuntu
apt install docker-ce docker-ce-cli containerd.io
```

2. Init swarm:
On first node:
`docker swarm init`
`docker swarm join-token manager`
As result in stdout will be printed docker-join command for add new masters.
Just copy-past output and execute on two other nodes:
```
docker swarm join \
  --token xxxxxx \
  YOUR_IP_HERE:2377
```

3. Check swarm is running:
On any manager-node:
`docker nodes ls`
You will see output like here:
```
xxx *   node00            Ready               Active              Leader              19.03.5
yyy     node01            Ready               Active              Reachable           19.03.5
zzz     node02            Ready               Active              Reachable           19.03.5
```

4. Ok, swarm is configured and running - lets start `CockroachDB`
Execute this command on any manager-node
```
docker service create \
    --name "seaweedfs-filer_db__prod" \
    --config src=sys.timezone,target="/etc/timezone" \
    --mount type=volume,source=cockroachdb-1,target=/cockroach/cockroach-data \
    --hostname "{{.Node.Hostname}}" \
    --publish published=48080,target=8080,mode=host \
    --publish published=26257,target=26257,mode=host \
    --mode global \
    cockroachdb/cockroach:v20.1.1 \
    "start" \
    "--join=host00:26257,host01:26257,host02:26257" \
    "--logtostderr" \
    "--insecure"
```

This command will start `cockroachdb` on a cluster.
Wait a minute and check `cockroachdb` is running:
`docker service ls`
```
xxx        seaweedfs-filer_db__prod                    global              3/3                 cockroachdb/cockroach:v20.1.1
```

Now you have to initialize `CockroachDB` cluster.
Run on any node:
```
docker run -it --rm cockroachdb/cockroach:v20.1.1 init --host=host00 --insecure
``` 

All done.
You can visit web-admin-page here: http://host00:48080

5. Filer and DB configuration:
Connect to `CockroachDB` from any SQL Developer supports PGSQL and execute this:
```
create database filer;
use filer;
CREATE TABLE IF NOT EXISTS filemeta (
  dirhash     BIGINT,
  name        VARCHAR(65535),
  directory   VARCHAR(65535),
  meta        bytea,
  PRIMARY KEY (dirhash, name)
);
```

Setup filer:
Locate your `filer.toml` on all nodes and change it.
```
[postgres] 
enabled = true
hostname = "localhost"
port = 26257
username = "root"
password = ""
database = "filer"
sslmode = "disable"
connection_max_idle = 100
connection_max_open = 100
```

OK.
Now you can start `filer`:
Run on all nodes:
`weed filer -collection=filer -defaultReplicaPlacement=200`

**Comment by thiscantbeserious** [comment]
@shm-dmitry have a look at deploying a Kubernetes cluster in <1m with [k3s](https://k3s.io/
) and [k3sup](https://github.com/alexellis/k3sup).

Just way better then Docker Swarm in any way and makes it pretty accessible. I can recommend it absolutely after trying a few options. Especially nice in combination with [helm](https://helm.sh/) charts.

https://k3s.io/
https://github.com/alexellis/k3sup

**Comment by shm-dmitry** [comment]
@thiscantbeserious 

I do not want to dispute about which is better - swarm or kubernetes. It seems to me like a dispute between android and ios :)

I tried to install `minikube`, I spent 2-3 hours, but did not get any progress.
Then I tried `MicroK8s` with same result.
I read [this](https://kubernetes.io/docs/setup/), but it was not helps to me.
Unfortunately I did not have much time for this task.

So, I looked at swarm... 
I execute `docker swarm init` + `docker swarm join`... and its works!!

Yes, I understand that kubernetes is a more thoughtful solution.

But I have 25 virtual nodes with 50 docker services (~ 100 running containers), and its works...
Swarm is very easy to maintaining... 
Yes, there are some things that are missing or that do not like. But in general - this is not critical.

About this guide - yes, it will be cool.

**Comment by Gronis** [comment]
Hi,

> In the future, filer with leveldb will sync metadata with each other to avoid SPOF.

Is this feature planned?

**Comment by chrislusf** [comment]
Currently there is an HA implementation, where peers can subscribe to each other's metadata events, with `weed filer -peers=...`.

Still WIP. Currently if one filer goes down, how to catch up the updates are not implemented yet.

**Comment by Gronis** [comment]
Ok, nice! That is more than I expected.

**Comment by chrislusf** [comment]
Added in 1.93

https://github.com/chrislusf/seaweedfs/wiki/Filer-Store-Replication
