### ISSUE TITLE
-publicurl

### ISSUE THREAD

**Issue by fincantieri** [chrislusf/seaweedfs#133]
i just want to know, sir.. where could i place my image folder, so that when i upload image using curl -X PUT -F file=@/IT/SLR.jpg http://127.0.0.1:8081/image the image that i'm going to upload will be viewed in the browser.. like this http://<ipaddress>:<port>/<folder>/<volumeId> but, when i try to specify the publicurl, it is not working or the image is not there, still the image uploaded to /tmp/data1/22.dat but not in image folder specified in publicurl..

**Comment by fincantieri** [comment]
i tried to create a folder named "image" inside the html folder of openresty nginx, but weedfs didn't recognized the folder that i made..

**Comment by chrislusf** [comment]
Are you talking about "filer"? 
If you upload to "http://127.0.0.1:8081/image", without the ending "/", it will be saved as file "image", not a directory.
You can list the folder by checking "http://127.0.0.1:8081/image/"
or  "http://127.0.0.1:8081/"

**Comment by fincantieri** [comment]
i'm asking on how can i upload the volumeId and saved it to my specified folder using (curl -X PUT -F file=@/path/to/image.jpg http://ip:port/volumeId)  instead of this command, how can i upload it into direct folder, instead of auto saving it into (/tmp/data1/22.dat) the browser can't identify the 22.dat file to retrieve the photo from specified directory folder.. the client must access the url like this -->http://127.0.0.1:8081/<specified folder>/volumeId to retrieve the photo uploaded.. but, in your basic guide, it's just calling the direct image using volumeId.. i don't know yet what is the right command for this.. if i use my publicurl to upload the image via curl, it is not working, if i add folder like this ---> curl -X PUT -F file=@/path/to/image.jpg http://ip:port/<folder>/volumeId   <---this is not working too..

I'm referring the coding of weed-fs as mysqli.. it must have something query.. not just calling the image via volumeId..
Date: Thu, 30 Apr 2015 11:51:49 -0700

**Comment by chrislusf** [comment]
If you are using basic "weed master" + "weed volume", the system would not take any folder structure. 

If you need folder structure, you can use other proxy, e.g. Nginx, to front the seaweedfs.
