### ISSUE TITLE
[Feature Request] set s3 buckets data location per disk type (ssd/hdd)

### ISSUE THREAD

**Issue by dorsany** [chrislusf/seaweedfs#1333]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs
Report issues here. Ask questions here https://stackoverflow.com/questions/tagged/seaweedfs

I'm using seaweedfs `s3 gateway`, and I wanted to know if it's possible somehow to set the buckets data location per disk type / tag
I have a server with one partition built from several ssd disks
And a second partition built from several hdd disks
I have **one** seaweedfs `volume server` and I wanted to know if somehow it's possible to  tag/differentiate between the partitions (ssd and hdd disks) and to create the volumes for a collection based on a list/wildcard of buckets that needs to use the ssd/tag (faster) disks while other will use the default (hdd) disks, that can be also be used for "data locality" so a specific tag can reside on local node in a cluster.

The idea is that I have different **usage** between some buckets.
some buckets are mostly have intensive writes and infrequent reads are best suited for `hdd` disks
and some buckets with frequently intensive read/write (especially if `fsync` is enabled [1c65656 ](https://github.com/chrislusf/seaweedfs/commit/1c65656fb4a64ae739b9a23a2f97f4032182015c#diff-391e3bf3f0b8a13bb648f1538c439a4e)) are best suited for `ssd` disks
We would like to have A simpler architecture (without deploying additional `s3 gw`, `filer` servers, `volume` servers) by maybe adding additional lists of buckets for default, fast disks and slow disks and lists for volume server to set the path for the default, fast and slow disks.
I think that this feature can add great value so clients will be able to utilize better their current hardware and squeeze more performance from the seaweedfs

**Comment by DXist** [comment]
For performance there is an option not to use volume collections based on S3 buckets. Instead it's possible to maintain only single writable volume per device to minimize seeks and distribute read operations across wider set of devices for all buckets. Host could run several volume servers each serving the dedicated device (like OSD in Ceph). It's possible to introduce collections based on blob size. Larger blobs require more IO and different parallellizm (grow) configuration. Facebook in the article about Haystack reported more iops for video chunks than for images.

Volume servers could report moving average of device utilization and read/write stats. master could use this information to introduce weights in the fileId->volumeId distribution and load balance reads and writes.

Different device type like ssd could be presented as `StorageClass` of the bucket.

**Comment by dorsany** [comment]
@DXist  this is nice idea of how to implement CEPH technologies and scaling automatic performance  inside seaweedfs, but our suggestion is to provide the storage admin (us) a way to use the high performance of SSD on specific collections (same as the ability to set fsync on specific collections)
the SSD storage & iops on a single machine with other resource hungry technologies (Postgres / Memsql ) need to be managed and restricted.
i think your suggestion is a good way, but we are trying to have specific, deterministic and simple control over what will be on the seaweedfs volume that reside on the SSD and all the rest on the SATA disk.

in our case, the size of the objects/blobs/images can be the same size example: 8-10KB, but most of them can be on the SATA and async fsync, but another collection must be sync fsync and on SSD. so dynamic and automatic re balancing of data is prohibited and not needed.

**Comment by chrislusf** [comment]
@dorsany does the read also need SSD speed?

There are two ways to optimize for SSD + hard drive combination.
1. Allocate SSD to specific collections. (Vertical)
2. Use SSD as sort of a write cache for all volumes. (Horizontal)

The second way will have hard-drive read performance for "less hot" data.

**Comment by dorsany** [comment]
Hi @chrislusf ,

Thank you for your interest in my feature request suggestion. 
Well, we still struggling with what is the best solution that probably will cover all the scenarios.

a possible scenario, we have 3 servers:
1 server combined with SSD disk (1 partition mount on /ssd) and HDD disk (1 partition mount on /hdd)
1 server with only 1 SSD disk (1 partition mount on /ssd)
1 server with only HDD disk (1 partition mount on /hdd)

In this case, especially in k8s deployments, it might be more accurate to use 1 volume server per partition (1 volume process for 1 partition) so it can be easier to deploy by node labels. So on the first server, I will deploy 2 volume servers and the other servers only 1 volume server on a different partition.

If it will be 1 volume server per node (1 volume process per multiple partitions/disks) we will have to think of how to implement this by using a helm chart to dynamic change the volume process flags by each server's disks type. Maybe it can be a volume configuration so we will mention the type of the partition/disk? 

So for this specific git issue, my answer will be:

Option 1 is the simplest and best solution to support fsync sync and read-intensive collections

Option 2 Can support fsync use cases because when not using fsync the memory is the cache so no real need except fsync collections...
But, having also option 2 can bring an enterprise-level feature to seaweedfs, so you can have ALL collections fsync with some nvme disk buffer, and have all seaweed data persistence to disk on ACK.

so both will improve seaweedfs but only option 1 will solve the read-intensive problem ( we thought of some read buffer but probably won't help on heavy/big collections).
