### ISSUE TITLE
GZIP compression not working for upload via S3 gateway

### ISSUE THREAD

**Issue by bnewbold** [chrislusf/seaweedfs#1334]
**Describe the bug**

When uploading an XML file via S3 interface, using the `aws` command line tool, GZIP compression does not seem to be used.

Upload command:

    aws --endpoint-url http://localhost:8333 s3 cp thing.xml s3://testing/05.xml

Resulting weed metadata:

```
> fs.meta.cat buckets/testing/05.xml
{ 
  "name": "05.xml",
  "isDirectory": false,
  "chunks": [
    { 
      "fileId": "4,01ea64ba49af31",
      "offset": "0",
      "size": "182734",
      "mtime": "1590696448015795451",
      "eTag": "5c9dd265",
      "sourceFileId": "",
      "fid": {
        "volumeId": 4,
        "fileKey": "125540",
        "cookie": 3125391153
      },
      "sourceFid": null,
      "cipherKey": null,
      "isGzipped": false
    }
  ],
  "attributes": {
    "fileSize": "0",
    "mtime": "1590696448",
    "fileMode": 432,
    "uid": 13005,
    "gid": 13005,
    "crtime": "1590696448",
    "mime": "application/xml",
    "replication": "",
    "collection": "testing",
    "ttlSec": 0,
    "userName": "",
    "groupName": [
    ],
    "symlinkTarget": "",
    "md5": "jj33SNkPighNdGeVXKLLFw=="
  },
  "extended": {
  }
}
```

**EDIT TO ADD:** also tried `aws --endpoint-url http://wbgrp-svc169.us.archive.org:8333 s3 cp thing.xml s3://testing/06.xml --content-encoding application/gzip`, and the new file (`06.xml`) as also not compressed (`"isGzipped": false`).

**System Setup**

Running on Ubuntu Xenial.

`weed version`: `version 8000GB 1.79 linux amd64`

Invocation (with systemd) as a single process:

```
/usr/local/bin/weed server -dir /srv/seaweedfs/data -s3 -s3.port 8333 -volume.max 0 -volume.index=leveldb2 -volume.port 8380 -master.port 9333 -filer no -whiteList 127.0.0.1 -master.volumeSizeLimitMB 250000
```

**Expected behavior**

`isGzipped` flag true after uploading `thing.xml` with mimetype `application/xml`.

**Additional context**

It could be possible that the `-filer no` flag and running as a single processing is causing issues? Without that flag (and specifying a port number), get errors on upload. For this deployment expecting to only ever use the S3 interface (replacing a current deployment of `minio`), so do not need (or want) the filter API.

I have read this function: https://github.com/chrislusf/seaweedfs/blob/master/weed/util/compression.go#L56

and it seems like this file should get compressed.

**Comment by chrislusf** [comment]
The actual file on volume server is already compressed. This is not visible to filer.

Filer is required for S3 API. It will automatically start if S3 is enabled.
