### ISSUE TITLE
volumeId xxx not found error

### ISSUE THREAD

**Issue by huzhixiang** [chrislusf/seaweedfs#1336]
seaweedfs often throws exception :volumeId 100 not found error,and this is the command and logs below, hoping your help, thanks. 
-----command
--41master
nohup /usr/local/seaweedfs/weed master -port=9333 -mdir=/usr/local/seaweedfs/1 -ip=10.15.2.41 > /usr/local/seaweedfs/master.log &
--41volume
nohup /usr/local/seaweedfs/weed volume -max=1024 -dir=/usr/local/seaweedfs/v1 -ip=10.15.2.41 -port=8081 -mserver=10.15.2.41:9333 > /usr/local/seaweedfs/seaweedfs.log &
--42volume
nohup /usr/local/seaweedfs/weed volume -max=1024 -dir=/usr/local/seaweedfs/v2 -ip=10.15.2.42 -port=8081 -mserver=10.15.2.41:9333 > /usr/local/seaweedfs/seaweedfs.log &
--43volume
nohup /usr/local/seaweedfs/weed volume -max=1024 -dir=/usr/local/seaweedfs/v3 -ip=10.15.2.43 -port=8081 -mserver=10.15.2.41:9333 > /usr/local/seaweedfs/seaweedfs.log &
-----master log
I0317 16:27:37 22068 topology_event_handling.go:57] Removing Volume 383 from the dead volume server 10.252.210.139:8081
I0317 16:27:37 22068 volume_layout.go:261] Volume 383 has 0 replica, less than required 1
I0317 16:27:37 22068 volume_layout.go:237] Volume 383 becomes unwritable
I0317 16:27:27 22068 topology_event_handling.go:57] Removing Volume 380 from the dead volume server 10.252.210.137:8081
I0317 16:27:27 22068 volume_layout.go:261] Volume 380 has 0 replica, less than required 1
I0317 16:27:27 22068 volume_layout.go:237] Volume 380 becomes unwritable

I0317 16:27:37 22068 node.go:256] topo:DefaultDataCenter:DefaultRack removes 10.252.210.139:8081
2020/03/18 14:38:01 http: proxy error: dial tcp 10.252.210.138:9333: connect: connection refused
2020/03/18 14:38:01 http: proxy error: dial tcp 10.252.210.138:9333: connect: connection refused
2020/03/18 14:38:01 http: proxy error: dial tcp 10.252.210.138:9333: connect: connection refused

-----volume log
I0528 16:02:08  5592 volume_loading.go:83] loading index /data/seaweed/node1/944.idx to memory readonly false
I0528 16:02:08  5592 store.go:113] add volume 944
I0528 16:13:08  5592 store.go:181] volume 938 is expired.
I0528 16:13:13  5592 store.go:179] volume 938 is deleted.
I0528 16:13:28  5592 store.go:179] volume 942 is deleted.
I0528 16:18:53  5592 volume_grpc_client_to_master.go:45] heartbeat error: rpc error: code = Unavailable desc = transport is closing
I0528 16:18:58  5592 volume_grpc_client_to_master.go:68] Heartbeat to: 10.252.210.138:9333
I0528 16:18:58  5592 volume_grpc_client_to_master.go:45] heartbeat error: rpc error: code = Unknown desc = Raft Server not initialized!
I0528 16:19:03  5592 volume_grpc_client_to_master.go:68] Heartbeat to: 10.252.210.138:9333
I0528 17:52:33  5592 store.go:181] volume 917 is expired.
I0528 17:52:38  5592 store.go:181] volume 917 is expired.
I0528 17:52:43  5592 store.go:181] volume 917 is expired.

**Comment by chrislusf** [comment]
There are nothing related to volume 100 in the log.

**Comment by huzhixiang** [comment]
yes,I know it is just an example, volume xxx not found, xxx means a number.

**Comment by chrislusf** [comment]
I do not know which one you think has problem.

**Comment by huzhixiang** [comment]
first, does the logs verify that there are some problem,such as volume 938 is expired,Volume 383 becomes unwritable,volume 938 is expired,heartbeat error: rpc error: code = Unavailable desc = transport is closing and so on which cause the problem volume id not found exception.

second,the volume is created by the command I have keyed, which I think it is created by default things.

third,the weed version is 1.4.1.

thanks for your reply, hoping more answers.

**Comment by chrislusf** [comment]
the latest version is 1.79. I guess you did not mean 1.4.1, but actually mean 1.41

The logs is for reporting status. "volume 938 is expired" means it is expired by TTL. "Volume 383 becomes unwritable" means the volume is somehow disconnected.

The volumes are clearly created as TTL volumes.

**Comment by huzhixiang** [comment]
How can I fix the problem " volume is somehow disconnected" ?

**Comment by chrislusf** [comment]
You should find out why `volume server 10.252.210.139:8081` is not the command you used to start the volume server.

**Comment by huzhixiang** [comment]
my mistake, the command is from dev env and the logs is from test env. Except the ip and port, the command is the same between dev and test. 
there is the command in test env:
nohup /usr/local/seaweedfs/weed volume -max=1024 -dir=/usr/local/seaweedfs/v3 -ip=10.252.210.139 -port=8081 -mserver=10.252.210.138:9333 > /usr/local/seaweedfs/seaweedfs.log &

so the problem " volume is somehow disconnected" is stil there. Hoping your clues.

**Comment by chrislusf** [comment]
How can I debug if the info is not real?

The disconnected volume server usually is temporary.

**Comment by huzhixiang** [comment]
I update the first post, so you can see the real things.
"The disconnected volume server usually is temporary" do you mean it is normal during the business?
