### ISSUE TITLE
De-couple messaging component from main repo

### ISSUE THREAD

**Issue by prasannakog** [chrislusf/seaweedfs#1339]
The "messaging" component enables message passing between channels on same of different host. If this could be de-coupled (or distributed as a separate repo) it can help other projects too IMHO. 

It started with, for one of the projects I was searching for one such message driven system and I saw this https://github.com/seaweedfs/messaging-client-go.  However, its just examples for the client code , to adopt the server side I had to compile the entire seaweefs source.

**Comment by chrislusf** [comment]
I am not clear how to decouple. The messaging needs a `weed server` as the message storage backend. To run the server, just use `weed server -msgBroker`. That is it.

Let me know your suggestions. I already tried my best to get rid of zookeeper/etcd.

**Comment by prasannakog** [comment]
Ok, I would be interested to know the flow I hope we should get connected off this thread to understand about this better.

**Comment by chrislusf** [comment]
we can chat on the SeaweedFS slack.
