### ISSUE TITLE
[in-progress] Export data changed since X

### ISSUE THREAD

**Issue by fedotxxl** [chrislusf/seaweedfs#134]
Hello. Can you add param `-changed-since` which will export all files changed since some value? We need it for implementing incremental backups - exporting whole data every day is too expensive 

Technically we can `diff` two tar files but even exporting single volume will generate too many wasteful disk load

**Comment by chrislusf** [comment]
Here is how to backup data efficiently.

https://github.com/chrislusf/seaweedfs/wiki/Data-Backup

**Comment by fedotxxl** [comment]
@dyeldandi added -newer param. We make 1 full backup per week + incremental backup every day by `-newer` param
