### ISSUE TITLE
is it too big for "max=1024"

### ISSUE THREAD

**Issue by huzhixiang** [chrislusf/seaweedfs#1340]
the command:
nohup /opt/seaweedfs/weed volume -max=1024 -dir=/data/seaweed/node2/ -ip=10.252.210.138 -port=8081 -mserver=10.252.210.138:9333 > /opt/seaweedfs/seaweedfs-node.log &
is there any  problems if I use "max=1024"

**Comment by chrislusf** [comment]
```
volumeSize * ( max + 1 ) = allocated disk space
```

The volumeSize is configured by master and default to 30GB.

If your machine has free disk space more than 30750GB, it is fine.

**Comment by huzhixiang** [comment]
the free disk space of machine is 650G,so I should set the max size lower,
"nohup /opt/seaweedfs/weed volume -max=20 -dir=/data/seaweed/node2/ -ip=10.252.210.138 -port=8081 -mserver=10.252.210.138:9333 > /opt/seaweedfs/seaweedfs-node.log &"
can I use the command next startup without any more operation?Do I have to do some volume operations to keep data available?
