### ISSUE TITLE
No control of free space on disk.

### ISSUE THREAD

**Issue by ekozlov-search** [chrislusf/seaweedfs#1343]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs
Report issues here. Ask questions here https://stackoverflow.com/questions/tagged/seaweedfs

example of a good issue report:
https://github.com/chrislusf/seaweedfs/issues/1005
example of a bad issue report:
https://github.com/chrislusf/seaweedfs/issues/1008

**Describe the bug**
I have one master and two volumes. Volumes placed on two different machines with different disk capacity. Master assign new files to both volume machines, even when disk have low space. And we have errors
`I0603 10:41:32  5792 store_replicate.go:46] failed to write to local disk: write data1/290.dat: There is not enough space on the disk`. But other volume server have enough disk space.

**Expected behavior**
It would be nice if master not assign new files to volumes with free space lower then some parametrize watermark( for example 5% or 1 GB). Volume server can periodicaly check free space and mark unwritable volumes using watermark condition.

**Comment by chrislusf** [comment]
How did you start the volume servers?

**Comment by ekozlov-search** [comment]
Problem volume server started with master
weed -logdir log server -dir=data1 -master.port=9333 -master.volumeSizeLimitMB=2048 -volume.port=8083  -volume.max=1024 -ip 10.0.2.10 -dataCenter=dc1 -metrics.address=http://10.0.1.142:9274

But it not alone on the machine. Disk space can spend and release other service (for example SQL server).

**Comment by chrislusf** [comment]
You allocated 1024*2GB=2048GB disk space for this volume server.

**Comment by ekozlov-search** [comment]
Yes. I know. 
I suggest to control available space on disk. And mark unwritable volumes if space is low.

**Comment by chrislusf** [comment]
Currently setting `-max=0` will automatically allocate the volume count. 

However, if the disk space is shared with other applications, it is hard to manage.

**Comment by ekozlov-search** [comment]
Yes, the problem in shared disk space with other service.
I think so:

-  Add to VolumeInfo or VolumeLayout "LowSpace" flag.
- Made routine that periodicaly(for example once per minute) check statistic for -dir and change "LowSpace" flag.
- isWritable function consider "LowSpace" flag.

**Comment by chrislusf** [comment]
Or how about using `weed master -volumePreallocate` to allocate disk space for a volume early?

**Comment by ekozlov-search** [comment]
We using windows platform.  Preallocated disk is not supported on windows.

**Comment by chrislusf** [comment]
fixed by https://github.com/chrislusf/seaweedfs/pull/1351
