### ISSUE TITLE
unexpected compression of all files in volume

### ISSUE THREAD

**Issue by ingardm** [chrislusf/seaweedfs#1345]
**Describe the bug**
While researching another bug we discovered that all files in a volume were gzip compressed. All files are allocated without mimetype and filenames dont contain type either

**System Setup**
version 30GB 1.78 linux amd64
/usr/local/bin/weed -logtostderr master -mdir=/mnt/data-small/meta -ip=10.1.14.110 -defaultReplication=010 -volumePreallocate -volumeSizeLimitMB 30000 -garbageThreshold 0.3 -pulseSeconds 10 -peers=10.1.14.110:9333,10.1.14.111:9333,10.1.14.112:9333,10.1.14.113:9333,10.1.14.114:9333

/usr/local/bin/weed -logtostderr -v=1 volume -compactionMBps=50 -port=8081 -mserver=10.1.14.110:9333,10.1.14.111:9333,10.1.14.112:9333,10.1.14.113:9333,10.1.14.114:9333 -dir=/mnt/data-small/data -index leveldb -max 0 -ip 10.1.14.110 -publicUrl dn-377.site-001.jotta.no:8080 -rack dn-377

**Expected behavior**
I thought only certain mime types, file suffixes would cause seaweed to compress content

**Comment by chrislusf** [comment]
this was a feature already turned off now.

**Comment by ingardm** [comment]
Can you elaborate please? When was it turned off? How does compression work now?

**Comment by chrislusf** [comment]
It is complicated. The history of this file from  Apr 6, 2019 to Apr 14, 2020 has the details. 

https://github.com/chrislusf/seaweedfs/commits/master/weed/operation/upload_content.go

Currently it will try to
1. check given mime type
2. detect content type by sampling
3. detect content type ty file name extension
4. test whether it can be efficiently compressed

**Comment by ingardm** [comment]
Ok. We're not providing any mime type, so I guess its down to sampling. But we did see a jpeg blob being compressed and ended up with being larger than the original content.

**Comment by chrislusf** [comment]
Is it reproducible with the latest release?

**Comment by ingardm** [comment]
@chrislusf Yes, all files are still being gzipped seemingly no matter what mime type. We modified see_dat again summerize the compression benefit. I'll attach the output which shows original size, gzipped size and cumulative byte diff between original ang zipped

**Comment by ingardm** [comment]
[gzipcalc2.txt](https://github.com/chrislusf/seaweedfs/files/4752668/gzipcalc2.txt)

**Comment by chrislusf** [comment]
if the file comes already via a gzipped http post, the file will be stored as gzipped.

how did you upload files?

**Comment by ingardm** [comment]
I tried to upload a bunch of files with a simple bash script:
```
#!/bin/bash
assign=$(curl -s http://10.1.14.111:9333/dir/assign?collection=gzip)
fid=$(echo $assign | jq -r .fid)
vurl=$(echo $assign | jq -r .url)
upload=$(curl -s -F file=@$1 http://${vurl}/${fid}?collection=gzip)
echo ${upload}
```

We have a modified version of see_dat that prints if the needle was gzip'ed and it reports all needles in the volume was zipped. Example:
```
I0616 16:33:18  9896 see_dat.go:90] ----------------------------------------------------------------------------------
I0616 16:33:18  9896 see_dat.go:91] 8616,182b32da3a1901 offset 83116488 size 8933525(8.52 MiB) cookie 3a1901 appendedAt 2020-06-16 14:40:43.77588092 +0200 CEST  hasmime[true] mime[] (len: 0)
I0616 16:33:18  9896 see_dat.go:103] was gzip! stored_size: 8933501 orig_size: 14946435 diff: -6012934(-7379498) mime:application/octet-stream compression-of-128: 0.95
I0616 16:33:19  9896 see_dat.go:90] ----------------------------------------------------------------------------------
I0616 16:33:19  9896 see_dat.go:91] 8616,182b32db4628a2ac offset 92050048 size 93668641(89.33 MiB) cookie 4628a2ac appendedAt 2020-06-16 14:42:10.286553865 +0200 CEST  hasmime[true] mime[] (len: 0)
I0616 16:33:19  9896 see_dat.go:103] was gzip! stored_size: 93668593 orig_size: 93661420 diff: 7173(-7372325) mime:application/octet-stream compression-of-128: 1.22
I0616 16:33:19  9896 see_dat.go:90] ----------------------------------------------------------------------------------
```
There are 2 things to note from this example;
- From the first example you can see that the compression test seaweed does on first 128 bytes fails. The test says 0.95 and the code says it needs to be less than 0.90 - However the file ends up being compressed from 15MB to 9MB.
- From the 2nd example you can see the same test gives 1.22 meaning the file increases with 22% but it ends up only increasing 7173 bytes - but a waste on both storage and cpu there

**Comment by chrislusf** [comment]
can you also share the actual 2 files used?

**Comment by ingardm** [comment]
Hi sorry. Those files are private so cant share, but I think you will see that whatever files you upload will be gzipped.

**Comment by ingardm** [comment]
Let me attach another file which also increase in size:
```
I0616 22:33:43 47702 see_dat.go:91] 8614,182b33175411ad63 offset 257080352 size 210073(205.15 KiB) cookie 5411ad63 appendedAt 2020-06-16 22:32:27.835263496 +0200 CEST  hasmime[true] mime[] (len: 0)
I0616 22:33:43 47702 see_dat.go:103] was gzip! stored_size: 210053 orig_size: 210010 diff: 43(-16416903) mime:image/png compression-of-128: 1.22
```
<img width="619" alt="test" src="https://user-images.githubusercontent.com/2324855/84825349-9b0dbe80-b021-11ea-92b3-e63da84e8b59.png">

**Comment by chrislusf** [comment]
My test showed the file is not compressed.
```
$ curl "http://localhost:9333/dir/assign"
{"fid":"3,01d28c6bb7","url":"192.168.2.3:8080","publicUrl":"192.168.2.3:8080","count":1}
$ curl -F "file=@t.png" "http://localhost:8080/3,01d28c6bb7"
{"name":"t.png","size":210010,"eTag":"abc44689"}


$ see_dat -dir=1 -volumeId=3
I0616 13:50:48  1344 see_dat.go:35] 3,1d28c6bb7 offset 8 size 210070(205.15 KiB) cookie d28c6bb7 appendedAt 2020-06-16 13:50:12.317908 -0700 PDT
```

**Comment by ingardm** [comment]
@chrislusf can you analyze your dat file againt with this version of see_dat : https://github.com/chrislusf/seaweedfs/pull/1360
