### ISSUE TITLE
Volume files too big / files not accessible

### ISSUE THREAD

**Issue by ingardm** [chrislusf/seaweedfs#1346]
**Describe the bug**
After migrating a lot of data we noticed some volumes being read-only. Seemingly this is because the volumes have become too big ( 32GB ). Probably because of a race condition between when files are allocated and written to the same volume with high concurrency. We have been running our tests with 200 concurrent transfers

**System Setup**
5x nodes with :
version 30GB 1.78 linux amd64

/usr/local/bin/weed -logtostderr master -mdir=/mnt/data-small/meta -ip=10.1.14.110 -defaultReplication=010 -volumePreallocate -volumeSizeLimitMB 30000 -garbageThreshold 0.3 -pulseSeconds 10 -peers=10.1.14.110:9333,10.1.14.111:9333,10.1.14.112:9333,10.1.14.113:9333,10.1.14.114:9333

/usr/local/bin/weed -logtostderr -v=1 volume -compactionMBps=50 -port=8081 -mserver=10.1.14.110:9333,10.1.14.111:9333,10.1.14.112:9333,10.1.14.113:9333,10.1.14.114:9333 -dir=/mnt/data-small/data -index leveldb -max 0 -ip 10.1.14.110 -publicUrl dn-377.site-001.jotta.no:8080 -rack dn-377

**Expected behavior**
When running a verify test against our migrated data we expect all files to be retrieved and checksum to be correct

**Additional context**
When trying to fetch the file we get 404:
```
$ curl -v 'http://10.1.14.111:8080/4482,0ccb137316a96b84'
*   Trying 10.1.14.111...
* TCP_NODELAY set
* Connected to 10.1.14.111 (10.1.14.111) port 8080 (#0)
> GET /4482,0ccb137316a96b84 HTTP/1.1
> Host: 10.1.14.111:8080
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Server: nginx/1.14.0 (Ubuntu)
< Date: Thu, 04 Jun 2020 14:40:10 GMT
< Content-Length: 0
< Connection: keep-alive
<
* Connection #0 to host 10.1.14.111 left intact
```

The server logs the following:
```
Jun 04 11:02:43 dn-377 weed[56439]: I0604 11:02:43 56439 volume_server_handlers_read.go:90] read /4482,0ccb137316a96b84 isNormalVolume true error: entry not found: offset 133512
found id 7919113051668610654 size 4122763091, expected size 84869
```

The see_idx tool gives the following:
```
$ ./see_idx -dir . -volumeId 4482 -collection dfs-small-069 2>&1 | grep ccb1373
key:ccb1373 offset:16689 size:84869
```

The see_dat tool gives the following:
```
I0604 13:25:15 45758 see_dat.go:63] 4482,ccb137316a96b84 offset 34359871880 size 84869 cookie 16a96b84 appendedAt 2020-05-05 03:39:29.995502151 +0200 CEST flags gzip,hasmod,hasname,mime
```

**Comment by chrislusf** [comment]
How did you migrate?

**Comment by ingardm** [comment]
How do you mean? We have a golang tool which allocates and post's files from source servers to the seaweed cluster. I can define the concurrency i want the source servers to send the files. And for testing purposes we set it to 200. I'm assuming there are too many files in flight before the protection against the volume being too big kicks in.

**Comment by chrislusf** [comment]
* The master CLI has`-pulseSeconds 10`. Changing default pulse second is not recommended. This will delay the volume size reporting. It will be removed in later releases. 
* You can use the "large_disk" version, and still keep the volume size as 30GB.

**Comment by ingardm** [comment]
@chrislusf if this happens in production, how would we fix those volumes?

**Comment by chrislusf** [comment]
If on production, one possible way is to change the volume server to "large_disk" version, run `weed fix` to re-generate .idx files for all volumes on that volume server.
