### ISSUE TITLE
No data dispatched to some volume server.

### ISSUE THREAD

**Issue by howg0924** [chrislusf/seaweedfs#1348]
**Describe the bug**

We have 3 volume servers in our production environment since starting. When assign file keys, only 2 volume servers are used. The other one is never used.

Current data distribution is as the following photos shown:

[Volume server A - 10.140.0.5]
![snap1453](https://user-images.githubusercontent.com/34688429/83834030-e7065c80-a71f-11ea-8669-cf8973ad98f5.png)

[Volume server B - 10.140.0.6]
![snap1454](https://user-images.githubusercontent.com/34688429/83834047-f5547880-a71f-11ea-942a-7049dac3d143.png)

[Volume server C - 10.140.0.7]
![snap1455](https://user-images.githubusercontent.com/34688429/83834058-00a7a400-a720-11ea-9f52-221708d48eeb.png)

[Master server]
![snap1452](https://user-images.githubusercontent.com/34688429/83834430-e3bfa080-a720-11ea-8432-adf8876d3a94.png)

As you can see, volume server B has 2 times of data than volume server A, and volume server C has no data. Data are not evenly distributed among volume servers. 

Is this normal?

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".

weed master -ip=10.140.0.5 -port=9333 -mdir=/hdd1/SeaweedFS/MasterData

weed volume -dir=/hdd1/SeaweedFS/VolumeData -max=30 -ip=10.140.0.5 -mserver=10.140.0.5:9333 -port=8080 -publicUrl=10.140.0.5:8080 -images.fix.orientation=false

weed volume -dir=/hdd1/SeaweedFS/VolumeData -max=30 -ip=10.140.0.6 -mserver=10.140.0.5:9333 -port=8080 -publicUrl=10.140.0.6:8080 -images.fix.orientation=false

weed volume -dir=/hdd1/SeaweedFS/VolumeData -max=30 -ip=10.140.0.7 -mserver=10.140.0.5:9333 -port=8080 -publicUrl=10.140.0.7:8080 -images.fix.orientation=false

- OS version: Ubuntu 18.04
- output of `weed version`: version 8000GB 1.38 linux amd64
- if using filer, show the content of `filer.toml`

**Expected behavior**

Data are evenly distributed among 3 volume servers.

**Screenshots**

**Additional context**

**Comment by chrislusf** [comment]
see https://github.com/chrislusf/seaweedfs/wiki/Optimization#increase-concurrent-writes
