### ISSUE TITLE
[Feature Request] batch operations

### ISSUE THREAD

**Issue by guyskk** [chrislusf/seaweedfs#1352]
The scenario is I need save or delete multiple files, about 10~100 files per batch, about 10KB size per file, and I use customized fid to ensure the files save to single volume.

I think if we batch save the files, it's a single sequence write operation and it will be much faster than multiple put operations. Am I correct?

And if so, can seaweedfs support batch operations?

**Comment by chrislusf** [comment]
you can reuse http connection and send multiple files. batch does not have any extra savings.
