### ISSUE TITLE
Missing Volume's metrics

### ISSUE THREAD

**Issue by psukys** [chrislusf/seaweedfs#1354]
**Describe the bug**
Metrics reported by master server about volumes contain very little, in comparison to filer:
`SeaweedFS_filerStore_request_total` and `SeaweedFS_volumeServer_max_volumes`

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
```
usr/local/bin/weed server -filer -volume.max=0 \
-master.peers=192.168.1.212:9333,192.168.1.144:9333 \
-metrics.address=192.168.1.212:9091 -master.port=9333 \
-volume.port=9433 -dir=/mnt/seaweedfs -master.dir=/mnt/ssd/seaweedfs-mtd
```
(did line splitting for better formatting)

- OS version
`Ubuntu 20.04 LTS aarch64`
- output of `weed version`
`version 30GB 1.79 linux arm64`
- if using filer, show the content of `filer.toml`

**Expected behavior**
By checking grafana dashboard the following are missing:

- `SeaweedFS_volumeServer_total_disk_size`
- `SeaweedFS_volumeServer_request_total`

**Screenshots**
none

**Additional context**
none

**Comment by chrislusf** [comment]
fixed. 

It was related to timing issue with `weed server` specifically. Thanks for the details!
