### ISSUE TITLE
"error": "file over the limited 268435456 bytes"

### ISSUE THREAD

**Issue by wsyangyun** [chrislusf/seaweedfs#1356]
i see your code the common.go at line 109 that use 
pu, pe := needle.ParseUpload(r, 256*1024*1024)
so it cause  the start command parameter(fileSizeLimitMB) of no avail;
if i was wrong please check it out, thank you

i use the start command is 
weed -v=2 volume -fileSizeLimitMB=512 -dir....
but if i upload a file that the size bigger than 256*1024*1024 bytes then it return "error": "file over the limited 268435456 bytes" to me

**Comment by chrislusf** [comment]
it will read the whole file into memory. 256MB is already too large. why you want 512MB?

**Comment by wsyangyun** [comment]
ok，i know it now,but i saw the start command has parameter which that named fileSizeLimitMB.so i think it support any size file.if i was wrong,please check it out. 



jx20061608@163.com
 
From: Chris Lu
Date: 2020-06-11 12:48
To: chrislusf/seaweedfs
CC: wsyangyun; Author
Subject: Re: [chrislusf/seaweedfs] "error": "file over the limited 268435456 bytes" (#1356)
it will read the whole file into memory. 256MB is already too large. why you want 512MB?
