### ISSUE TITLE
When I import JPG files using the S3 API

### ISSUE THREAD

**Issue by Jacksliwen** [chrislusf/seaweedfs#1357]
When I import JPG files using the S3 API，when I export it to my computer use "cp" , it can not display Integrity. There is no such problem inversion v1.44 
![test](https://user-images.githubusercontent.com/48372041/84365252-c6e50a80-ac03-11ea-8b39-07c8953a0742.png)

**Comment by chrislusf** [comment]
user mistake? what was the exact problem?
