### ISSUE TITLE
weed server -port not work

### ISSUE THREAD

**Issue by afarcat** [chrislusf/seaweedfs#1359]
when use:
weed help server
Usage: weed server -port=8080 -dir=/tmp -volume.max=5 -ip=server_name

then input in cmd:
weed server -ip=192.168.0.110 -port=8080 -dir=./data

display as follow:
flag provided but not defined: -port

**Comment by chrislusf** [comment]
that's expected. see `weed server -h` for the options.

**Comment by chrislusf** [comment]
sorry, saw the problem. adding a fix.
