### ISSUE TITLE
Installation fails because go libraries still pointing to code.google instead of github

### ISSUE THREAD

**Issue by blalab** [chrislusf/seaweedfs#136]
When executing
 ```go get github.com/chrislusf/seaweedfs/go/weed```

This error will appear
```
package code.google.com/p/goprotobuf/proto: unable to detect version control system for code.google.com/ path
```

This is similar to this issue:
https://github.com/google/codesearch/issues/42

Seems to be a bug that is happening to google code being migrated to github.

I checked the source here:

https://code.google.com/p/go/source/browse/go/vcs/vcs.go?repo=tools

And indeed it tries to read from the old repository:

``` data, err := httpGET(expand(match, "https://code.google.com/p/{project}/source/checkout?repo={subrepo}")) ``` 

But it will get:

```
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="https://github.com/google/protobuf">here</A>.
</BODY></HTML>
```
Which apparently is not following and throwing the error instead

```
return fmt.Errorf("unable to detect version control system for code.google.com/ path") 
```

This doesn't seem to be a seaweedfs error. However it will not allow users (like me) to install and use it.

**Comment by chrislusf** [comment]
I thought I just fixed it yesterday. Did you refresh the code? If still happening, I will check again.

**Comment by blalab** [comment]
Thank you . It works now. I went to go/src/github.com in my machine, deleted folder chrislusf and ran go get github.com/chrislusf/seaweedfs/go/weed again.
