### ISSUE TITLE
Volume not found, but actutally present in filesystem

### ISSUE THREAD

**Issue by artemvang** [chrislusf/seaweedfs#1361]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs
Report issues here. Ask questions here https://stackoverflow.com/questions/tagged/seaweedfs

example of a good issue report:
https://github.com/chrislusf/seaweedfs/issues/1005
example of a bad issue report:
https://github.com/chrislusf/seaweedfs/issues/1008

**Describe the bug**
EC encoder can not mark volume as readonly because of SeaweedFS thinks that volume does not exist.
```
> ec.encode -fullPercent=95 -quietFor=1h
ec encode volumes quiet for: 3600 seconds
ec encode volumes: [133 131 439 446 440 437 444 443 436 449 435 447 441 140 448 445 451 118 180 434 450 442]
error: mark volume 133 as readonly on example.com:8083: rpc error: code = Unknown desc = volume 133 not found
```
But volume is actually present in filesystem.

```
$ ls /data/volume/ | grep 133
  133.dat
  133.ec03
  133.ec11
  133.ecj
  133.ecx
  133.idx
  133.sdx
  133.vif
```

Also, we have constant `404 Not Found` errors for files, that used to be present.

**System Setup**
- System has 5 volume servers, 1 master server and 1 filer.
- ` Linux seaweed.volume1 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
- `Ubuntu 18.04.3 LTS`
- `version 30GB 1.78 linux amd64`
- Filer uses postgresql 12.

**Expected behavior**
Encoding process has to mark volume as readonly.

**Screenshots**
![image](https://user-images.githubusercontent.com/9038018/84881671-de564480-b096-11ea-9122-a1b36b48be8f.png)

**Additional context**
We had several issues with our volume server one month ago (downtime for almost 6 hours), and after that, we started to face constant 404 errors and encoding errors.

**Comment by chrislusf** [comment]
Do you have replication setup for volume 133?

**Comment by chrislusf** [comment]
I added some fix for other bugs when I was reproducing your case. https://github.com/chrislusf/seaweedfs/commit/ae1994cbc1692133cc5f4ac30e8060a2b0d9dda8

**Comment by artemvang** [comment]
> now you can do is to delete 133.ec* files, and bounce the volume server.

Thanks, the issue was solved.
