### ISSUE TITLE
windos 为什么总是崩溃

### ISSUE THREAD

**Issue by gitlihua** [chrislusf/seaweedfs#1365]
![2Y~_K$}(FPH$OG`GL8H_QUG](https://user-images.githubusercontent.com/23493734/85189308-72671c80-b2e0-11ea-8fa3-1ca9d3de615f.png)
![25AA$%MB(8DX3$U3@YB)I6A](https://user-images.githubusercontent.com/23493734/85189312-7bf08480-b2e0-11ea-8b31-4e120eeaa156.png)
不知道为什么，运行一会，就会崩溃掉，重启就会好

**Comment by chrislusf** [comment]
the version is too old. Try to upgrade first.

**Comment by gitlihua** [comment]
我升级到1.81  为什么有些文件却读不出来了，退回到原版本就OK了

**Comment by chrislusf** [comment]
need logs to diagnose.
