### ISSUE TITLE
weed mount ： cannot sync file to other peer

### ISSUE THREAD

**Issue by qinzhao168** [chrislusf/seaweedfs#1369]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**
cannot sync mount dir to other peer 

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
- OS version
centos7 
- output of `weed version`
1.82
- if using filer, show the content of `filer.toml`
filer.toml
[redis]
enabled = true
address = "192.168.3.xx:6379"
password = ""
database = 0

**Expected behavior**
**master:**
weed -logtostderr=false master -ip=192.168.3.45 -port=9333 -defaultReplication=200 -mdir=/data -peers=192.168.3.45,192.168.3.46,192.168.3.47
**volume:**
weed -logtostderr=false volume -ip=192.168.3.45 -port=9334 -defaultReplication=200 -dir=/volume -ip 92.168.3.45 -port 9334 -ip.bind 92.168.3.45 -max 20 -mserver 192.168.3.45:9333,192.168.3.46:9333,192.168.3.47:9333 -publicUrl 192.168.3.45 
**filer:**
weed -logtostderr=false filer -ip=192.168.x.45 -port=9335 -ip 92.168.3.45 -port 9335 -ip.bind 92.168.3.45 -max 20 -mserver 192.168.3.45:9333,192.168.3.46:9333,192.168.3.47:9333 
**mount(fuse):**
weed -logtostderr=false mount   -dir=/mount -filer=92.168.3.45:9335 

when I add file to mount dir, not sync thnew file to  other peer 

**Screenshots**

**Additional context**

**Comment by qinzhao168** [comment]
![1518140651](https://user-images.githubusercontent.com/18432183/85253459-ca448580-b490-11ea-9d9d-8391d3f0ff52.jpg)

![1687362442](https://user-images.githubusercontent.com/18432183/85253587-1c85a680-b491-11ea-9a5c-a7f0ba8cfa19.jpg)
![2018743343](https://user-images.githubusercontent.com/18432183/85253590-1db6d380-b491-11ea-942a-7882ffbcc9d2.jpg)

**Comment by chrislusf** [comment]
* The commands are different from the screenshot. Which one is the "real" one? 192.168.x is intranet address. You do not need to hide.
* What are the mount and filer logs?

**Comment by qinzhao168** [comment]
@chrislusf 

Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**
cannot sync mount dir to other peer 

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
- OS version
centos7 
- output of `weed version`
1.82
- if using filer, show the content of `filer.toml`
filer.toml
[redis]
enabled = true
address = "192.168.3.45:6379"
password = ""
database = 0

**Expected behavior**
**master:**
weed -logtostderr=false master -ip=192.168.3.45 -port=9333 -defaultReplication=200 -mdir=/data -peers=192.168.3.45,192.168.3.46,192.168.3.47

weed -logtostderr=false master -ip=192.168.3.46 -port=9333 -defaultReplication=200 -mdir=/data -peers=192.168.3.45,192.168.3.46,192.168.3.47

weed -logtostderr=false master -ip=192.168.3.47 -port=9333 -defaultReplication=200 -mdir=/data -peers=192.168.3.45,192.168.3.46,192.168.3.47
**volume:**
weed -logtostderr=false volume  -defaultReplication=200 -dir=/volume -ip 92.168.3.45 -port 9334 -ip.bind 92.168.3.45 -max 20 -mserver 192.168.3.45:9333,192.168.3.46:9333,192.168.3.47:9333 -publicUrl 192.168.3.45 

weed -logtostderr=false volume  -defaultReplication=200 -dir=/volume -ip 92.168.3.46 -port 9334 -ip.bind 92.168.3.46 -max 20 -mserver 192.168.3.45:9333,192.168.3.46:9333,192.168.3.47:9333 -publicUrl 192.168.3.46

weed -logtostderr=false volume  -defaultReplication=200 -dir=/volume -ip 92.168.3.47 -port 9334 -ip.bind 92.168.3.47 -max 20 -mserver 192.168.3.45:9333,192.168.3.46:9333,192.168.3.47:9333 -publicUrl 192.168.3.47

**filer:**
weed -logtostderr=false filer -ip=192.168.3.45 -port=9335 -ip 92.168.3.45 -port 9335 -ip.bind 92.168.3.45 -max 20 -mserver 192.168.3.45:9333,192.168.3.46:9333,192.168.3.47:9333 

weed -logtostderr=false filer  -port=9335 -ip 92.168.3.46 -port 9335 -ip.bind 92.168.3.46 -max 20 -mserver 192.168.3.45:9333,192.168.3.46:9333,192.168.3.47:9333 

weed -logtostderr=false filer  -port=9335 -ip 92.168.3.47 -port 9335 -ip.bind 92.168.3.47 -max 20 -mserver 192.168.3.45:9333,192.168.3.46:9333,192.168.3.47:9333 

**mount(fuse):**
weed -logtostderr=false mount   -dir=/mount -filer=92.168.3.45:9335 
weed -logtostderr=false mount   -dir=/mount -filer=92.168.3.46:9335 
weed -logtostderr=false mount   -dir=/mount -filer=92.168.3.47:9335 



when I add file to mount dir, not sync thnew file to  other peer 

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.


It can be synchronized in the 1.61 version, but the synchronization fails in 1.82

**Comment by qinzhao168** [comment]
about mount and filer logs : 
Because it's an intranet, I can't get it out

**Comment by chrislusf** [comment]
For now, multiple mounts need to connect to one filer if they need to share file changes.

Later will add support to sync meta data changes among the filers.

**Comment by qinzhao168** [comment]
It can be synchronized to other nodes in 1.61, but this issue has occurred ： https://github.com/chrislusf/seaweedfs/issues/986

**Comment by chrislusf** [comment]
> It can be synchronized to other nodes in 1.61, but this issue has occurred ： #986

There is a change in how mount sync metadata in recent releases. The issue is unrelated.

**Comment by qinzhao168** [comment]
Which version is the latest stable version  ？

**Comment by qinzhao168** [comment]
Which version can i use now？ Thank you very much

**Comment by chrislusf** [comment]
you can use 1.75 if you can build by yourself.

**Comment by qinzhao168** [comment]
Thank you very much

**Comment by chrislusf** [comment]
In latest git tip, now you can configure `weed filer -peers=.......`, which will enable meta data synchronization across filers, and then the `weed mount` will be synchronized.
