### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by snoopyxu** [chrislusf/seaweedfs#137]
Start seaweedfs with following command:

./weed master 
./weed volume -dir="/var/weed" -max=5 -mserver="localhost:9333" -port=8888 &

Use wrk(a HTTP benchmarking tool) to test:
wrk -c 250 -d 30s -t 2 http://localhost:8888/39,650a59fe10

Appears many errors:

2015/05/06 11:18:01 http: Accept error: accept tcp [::]:8888: too many open files; retrying in 1s
...
I0506 11:18:28 21451 volume_server_handlers_read.go:132] response write error: write tcp [::1]:56249: broken pipe

It seems that seaweedfs could not afford more than 200 connections. 
Are there any solutions ?

**Comment by chrislusf** [comment]
Check your system's open file limit.

 unlimit -a

**Comment by snoopyxu** [comment]
I adjust my max open files, following are my output of ulimit -a:
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 4096
pipe size            (512 bytes, -p) 1
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 709
virtual memory          (kbytes, -v) unlimited

Then I test with 500 connections,  too many open files error disappear, but I have another error:

I0506 15:40:45 00800 volume_server_handlers_read.go:133] response write error: write tcp [::1]:49319: i/o timeout

I restart my seaweed volume with -idleTimeout=30 to get rid of i/o timeout error, but get broken pipe error:

I0506 15:43:32 01278 volume_server_handlers_read.go:133] response write error: write tcp 127.0.0.1:50615: broken pipe

How can I fix the broken pipe error? 
Thanks advance.
