### ISSUE TITLE
400: File Random Cookie does not match

### ISSUE THREAD

**Issue by johbac1** [chrislusf/seaweedfs#1372]
I have some files stored in seaweedfs for which I get 400/Random Cookie does not match when I try to delete them with a http DELETE request. 
As I understand it this random cookie is some kind of mechanism to prevent someone from just guessing a file id but in my case I have the file id's stored in a database, and it looks unlikely that they would have been corrupted so they now would match another file stored in seaweed (if they would just point to a nonexisting file I would expect to get a 404 when trying to delete them). 
How do I solve this, just want to be able to delete the files.

**Comment by chrislusf** [comment]
maybe it is already deleted?

you can use `weed export` to check what is inside the volume, or use `see_dat` in here https://github.com/chrislusf/seaweedfs/tree/master/unmaintained/see_dat

**Comment by johbac1** [comment]
> maybe it is already deleted?
> 
Why would I get this cookie error and not just a 404 if i try to delete something that already has been deleted?

**Comment by chrislusf** [comment]
Can not debug by your words.
