### ISSUE TITLE
.git files getting corrupted after a git pull

### ISSUE THREAD

**Issue by roshanjonah** [chrislusf/seaweedfs#1373]
**Describe the bug**
I use git clone (HTTP) to clone a private repo onto Seaweed Mount and when doing a git pull I get a git corrupted message. 

**System Setup**
- /usr/bin/weed mount -filer=XXX:8888 -dir=/mnt/XXX -filer.path=/ -cacheCapacityMB=12000 -cacheDir=/mnt/XXX-cache -asyncMetaDataCaching
- Ubuntu 18.04
- version 30GB 1.80  linux amd64

**Expected behavior**
It shouldn't error out due to corrupted index .git files

**Weed mount console logs**
`Binary: Built with gc go1.14.2 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss threadid file:line] msg
E0616 02:00:10   955 filehandle.go:213] fh flush create /ols/var/www/xxx.domain.com/public_html/apps/common/runtime/application.log: CreateEntry: rpc error: code = Internal desc = grpc: error unmarshalling request: unexpected EOF
E0616 02:00:10   955 filehandle.go:234] /ols/var/www/xxx.domain.com/public_html/apps/common/runtime/application.log fh 11096789771036427353 flush: fh flush create /ols/var/www/xxx.domain.com/public_html/apps/common/runtime/application.log: CreateEntry: rpc error: code = Internal desc = grpc: error unmarshalling request: unexpected EOF
E0619 04:30:14   955 filehandle.go:213] fh flush create /ols/var/www/xxx.domain.com/public_html/apps/common/runtime/application.log.2: CreateEntry: rpc error: code = Internal desc = grpc: error unmarshalling request: unexpected EOF
E0619 04:30:14   955 filehandle.go:234] /ols/var/www/xxx.domain.com/public_html/apps/common/runtime/application.log.2 fh 14635964342436889593 flush: fh flush create /ols/var/www/xxx.domain.com/public_html/apps/common/runtime/application.log.2: CreateEntry: rpc error: code = Internal desc = grpc: error unmarshalling request: unexpected EOF
E0619 04:40:14   955 filehandle.go:213] fh flush create /ols/var/www/xxx.domain.com/public_html/apps/common/runtime/application.log.2: CreateEntry: rpc error: code = Internal desc = grpc: error unmarshalling request: unexpected EOF
E0619 04:40:14   955 filehandle.go:234] /ols/var/www/xxx.domain.com/public_html/apps/common/runtime/application.log.2 fh 14635964342436889593 flush: fh flush create /ols/var/www/xxx.domain.com/public_html/apps/common/runtime/application.log.2: CreateEntry: rpc error: code = Internal desc = grpc: error unmarshalling request: unexpected EOF
E0619 05:20:14   955 filehandle.go:213] fh flush create /ols/var/www/xxx.domain.com/public_html/apps/common/runtime/application.log.2: CreateEntry: rpc error: code = Internal desc = grpc: error unmarshalling request: unexpected EOF
E0619 05:20:14   955 filehandle.go:234] /ols/var/www/xxx.domain.com/public_html/apps/common/runtime/application.log.2 fh 14635964342436889593 flush: fh flush create /ols/var/www/xxx.domain.com/public_html/apps/common/runtime/application.log.2: CreateEntry: rpc error: code = Internal desc = grpc: error unmarshalling request: unexpected EOF
E0619 09:10:13   955 filehandle.go:213] fh flush create /ols/var/www/xxx.domain.com/public_html/apps/common/runtime/application.log.5: CreateEntry: rpc error: code = Internal desc = grpc: error unmarshalling request: unexpected EOF
E0619 09:10:13   955 filehandle.go:234] /ols/var/www/xxx.domain.com/public_html/apps/common/runtime/application.log.5 fh 14635964342436889593 flush: fh flush create /ols/var/www/xxx.domain.com/public_html/apps/common/runtime/application.log.5: CreateEntry: rpc error: code = Internal desc = grpc: error unmarshalling request: unexpected EOF`

**Ubuntu server - git pull command**
`nobody@ja-srv-1:/mnt/janzswfs/ols/var/www/xxx.domain.com/public_html$ git pull
remote: Enumerating objects: 194, done.
remote: Counting objects: 100% (194/194), done.
remote: Compressing objects: 100% (76/76), done.
error: unknown object type 5 at offset 4206 in .git/objects/pack/pack-31baf29579ee2c5e7db7a0f85ac078800c359a85.pack
fatal: SHA1 COLLISION FOUND WITH 353293f2cb3f6b463858498ef893d33252325e0e !
fatal: index-pack failed`

`error: failed to validate delta base reference at offset 8239379 from .git/objects/pack/pack-31baf29579ee2c5e7db7a0f85ac078800c359a85.pack
error: unknown object type 5 at offset 8239436 in .git/objects/pack/pack-31baf29579ee2c5e7db7a0f85ac078800c359a85.pack
error: inflate: data stream error (incorrect header check)
error: unknown object type 5 at offset 8232513 in .git/objects/pack/pack-31baf29579ee2c5e7db7a0f85ac078800c359a85.pack
error: bad offset for revindex
error: failed to validate delta base reference at offset 11478 from .git/objects/pack/pack-31baf29579ee2c5e7db7a0f85ac078800c359a85.pack
error: inflate: data stream error (incorrect header check)
error: unknown object type 0 at offset 7475 in .git/objects/pack/pack-31baf29579ee2c5e7db7a0f85ac078800c359a85.pack
error: bad offset for revindex
error: unknown object type 5 at offset 7595 in .git/objects/pack/pack-31baf29579ee2c5e7db7a0f85ac078800c359a85.pack
error: unknown object type 0 at offset 7656 in .git/objects/pack/pack-31baf29579ee2c5e7db7a0f85ac078800c359a85.pack
error: failed to validate delta base reference at offset 4108 from .git/objects/pack/pack-31baf29579ee2c5e7db7a0f85ac078800c359a85.pack
error: failed to validate delta base reference at offset 4167 from .git/objects/pack/pack-31baf29579ee2c5e7db7a0f85ac078800c359a85.pack
error: unknown object type 5 at offset 4206 in .git/objects/pack/pack-31baf29579ee2c5e7db7a0f85ac078800c359a85.pack`

**Comment by chrislusf** [comment]
Need to make this reproducible.

**Comment by roshanjonah** [comment]
1) Git clone a repo /main-folder/sub-folder
2) Delete the .git folder. rm -rf main-folder/sub-folder/.git
3) Git clone a repo on a top-level folder
4) Move .git folder to second-level folder mv .git main-folder/sub-folder/.git
5) Git pull 

It seems to occur then. For some odd reason, filer doesn't seem to be deleting all the files when issued with the command to delete .git and they are clashing - that's my understanding. Here are some new outputs I have found on this issue.

 **Filer Errors**
`I0624 21:38:26   822 filer_delete_entry.go:32] delete directory /ols/var/www/xxx.domain.com/public_html/.git/objects/a9: fail to delete non-empty folder: /ols/var/www/xxx.domain.com/public_html/.git/objects/a9
I0624 21:38:26   822 filer_delete_entry.go:32] delete directory /ols/var/www/xxx.domain.com/public_html/.git/objects/aa: fail to delete non-empty folder: /ols/var/www/xxx.domain.com/public_html/.git/objects/aa
I0624 21:38:26   822 filer_delete_entry.go:32] delete directory /ols/var/www/xxx.domain.com/public_html/.git/objects/b1: fail to delete non-empty folder: /ols/var/www/xxx.domain.com/public_html/.git/objects/b1
I0624 21:38:26   822 filer_delete_entry.go:32] delete directory /ols/var/www/xxx.domain.com/public_html/.git/objects/b4: fail to delete non-empty folder: /ols/var/www/xxx.domain.com/public_html/.git/objects/b4
I0624 21:38:26   822 filer_delete_entry.go:32] delete directory /ols/var/www/xxx.domain.com/public_html/.git/objects/bc: fail to delete non-empty folder: /ols/var/www/xxx.domain.com/public_html/.git/objects/bc
I0624 21:38:26   822 filer_delete_entry.go:32] delete directory /ols/var/www/xxx.domain.com/public_html/.git/objects/bf: fail to delete non-empty folder: /ols/var/www/xxx.domain.com/public_html/.git/objects/bf
I0624 21:38:26   822 filer_delete_entry.go:32] delete directory /ols/var/www/xxx.domain.com/public_html/.git/objects/cb: fail to delete non-empty folder: /ols/var/www/xxx.domain.com/public_html/.git/objects/cb
I0624 21:38:26   822 filer_delete_entry.go:32] delete directory /ols/var/www/xxx.domain.com/public_html/.git/objects/cd: fail to delete non-empty folder: /ols/var/www/xxx.domain.com/public_html/.git/objects/cd
I0624 21:38:26   822 filer_delete_entry.go:32] delete directory /ols/var/www/xxx.domain.com/public_html/.git/objects/ce: fail to delete non-empty folder: /ols/var/www/xxx.domain.com/public_html/.git/objects/ce
I0624 21:38:26   822 filer_delete_entry.go:32] delete directory /ols/var/www/xxx.domain.com/public_html/.git/objects/dc: fail to delete non-empty folder: /ols/var/www/xxx.domain.com/public_html/.git/objects/dc
I0624 21:38:26   822 filer_delete_entry.go:32] delete directory /ols/var/www/xxx.domain.com/public_html/.git/objects/e2: fail to delete non-empty folder: /ols/var/www/xxx.domain.com/public_html/.git/objects/e2
I0624 21:38:26   822 filer_delete_entry.go:32] delete directory /ols/var/www/xxx.domain.com/public_html/.git/objects/f4: fail to delete non-empty folder: /ols/var/www/xxx.domain.com/public_html/.git/objects/f4
I0624 21:38:54   822 filer_delete_entry.go:32] delete directory /ols/var/www/xxx.domain.com/public_html/.git/objects: fail to delete non-empty folder: /ols/var/www/xxx.domain.com/public_html/.git/objects
I0624 21:38:54   822 filer_delete_entry.go:32] delete directory /ols/var/www/xxx.domain.com/public_html/.git: fail to delete non-empty folder: /ols/var/www/xxx.domain.com/public_html/.git
I0624 21:49:45   822 filer_deletion.go:55] deleting fileIds len=2 error: delete fileId 53,26a20317f109b2: already deleted
I0624 21:49:45   822 filer_deletion.go:60] delete 2 fileIds actual 0`

`I0610 13:18:00   822 filer_deletion.go:60] delete 2 fileIds actual 0
I0610 13:24:50   822 filer_deletion.go:55] deleting fileIds len=2 error: delete fileId 23,15cf6f648f8c4b: already deleted
I0610 13:24:50   822 filer_deletion.go:60] delete 2 fileIds actual 0
I0610 13:30:12   822 filer_deletion.go:55] deleting fileIds len=1 error: delete fileId 27,15cf254e87eb1c: already deleted
I0610 13:30:12   822 filer_deletion.go:60] delete 1 fileIds actual 0
I0610 14:00:12   822 filer_deletion.go:55] deleting fileIds len=1 error: delete fileId 23,15cf8ed84ae772: already deleted
I0610 14:00:12   822 filer_deletion.go:60] delete 1 fileIds actual 0
I0610 14:30:12   822 filer_deletion.go:55] deleting fileIds len=1 error: delete fileId 23,15cffda50b30a7: already deleted
I0610 14:30:12   822 filer_deletion.go:60] delete 1 fileIds actual 0
I0610 14:59:46   822 filer_deletion.go:55] deleting fileIds len=2 error: delete fileId 26,15d0968203c276: already deleted
I0611 02:59:40   822 upload_content.go:214] failing to upload to http://IP:8081/28,160df09ebd6620 Post "http://IP:8081/28,160df09ebd6620": EOF
I0611 02:59:40   822 filer_notify.go:81] log write failed /topics/.system/log/2020-06-11/02-59.segment: upload data http://IP:8081/28,160df09ebd6620: Post "http://IP:8081/28,160df09ebd6620": EOF
I0611 03:00:13   822 filer_deletion.go:55] deleting fileIds len=1 error: delete fileId 26,160d8d40ce0aa8: already deleted`

**Comment by roshanjonah** [comment]
Despite deleting the folder including .git folder in it, its not being deleted. When i clone a folder with same name, it throws out an error saying that a file from past deleted folder exists. But when I do "ls" list directory - it's not there. Something somewhere is not updating or deleting correctly.

**Filer errors**
`I0624 22:43:25   822 filer_delete_entry.go:32] delete directory /ols/var/www/xxx.domain.com/public_html/.git/objects: fail to delete non-empty folder: /ols/var/www/xxx.domain.com/public_html/.git/objects
I0624 22:43:25   822 filer_delete_entry.go:32] delete directory /ols/var/www/xxx.domain.com/public_html/.git: fail to delete non-empty folder: /ols/var/www/xxx.domain.com/public_html/.git
I0624 22:44:06   822 filer_delete_entry.go:32] delete directory /ols/var/www/xxx.domain.com/xx1.domain.com/.git: fail to delete non-empty folder: /ols/var/www/xxx.domain.com/xx1.domain.com/.git
I0624 22:44:06   822 filer_delete_entry.go:32] delete directory /ols/var/www/xxx.domain.com/xx1.domain.com: fail to delete non-empty folder: /ols/var/www/xxx.domain.com/xx1.domain.com`

**Comment by chrislusf** [comment]
try to restart the `weed mount` and see whether it makes any difference

**Comment by roshanjonah** [comment]
Unfortunately, this is the situation after the restart - restarted the server too! I tried to umount and then mount it back.

**Comment by chrislusf** [comment]
you can run `weed shell` and use `ls -al /ols/var/www/xxx.domain.com/public_html/.git/objects` to see what is left in the folder.

**Comment by roshanjonah** [comment]
I am getting 19 objects. Infact the whole .git folder is still there despite deleted it using "rm -rf .git" and I can't see it using "ls -a" command. All other folders and files come up but not .git but its definitely there and that's causing lots of issues in updating and pulling code.

`> ls -al /ols/var/www/xx1.domain.com/public_html/.git/objects
drwxr-xr-x   0 nobody nogroup      0 /ols/var/www/xx1.domain.com/public_html/.git/objects/0f
drwxr-xr-x   0 nobody nogroup      0 /ols/var/www/xx1.domain.com/public_html/.git/objects/14
drwxr-xr-x   0 nobody nogroup      0 /ols/var/www/xx1.domain.com/public_html/.git/objects/1e
drwxr-xr-x   0 nobody nogroup      0 /ols/var/www/xx1.domain.com/public_html/.git/objects/1f
drwxr-xr-x   0 nobody nogroup      0 /ols/var/www/xx1.domain.com/public_html/.git/objects/21
drwxr-xr-x   0 nobody nogroup      0 /ols/var/www/xx1.domain.com/public_html/.git/objects/30
drwxr-xr-x   0 nobody nogroup      0 /ols/var/www/xx1.domain.com/public_html/.git/objects/54
drwxr-xr-x   0 nobody nogroup      0 /ols/var/www/xx1.domain.com/public_html/.git/objects/57
drwxr-xr-x   0 nobody nogroup      0 /ols/var/www/xx1.domain.com/public_html/.git/objects/71
drwxr-xr-x   0 nobody nogroup      0 /ols/var/www/xx1.domain.com/public_html/.git/objects/88
drwxr-xr-x   0 nobody nogroup      0 /ols/var/www/xx1.domain.com/public_html/.git/objects/89
drwxr-xr-x   0 nobody nogroup      0 /ols/var/www/xx1.domain.com/public_html/.git/objects/aa
drwxr-xr-x   0 nobody nogroup      0 /ols/var/www/xx1.domain.com/public_html/.git/objects/b1
drwxr-xr-x   0 nobody nogroup      0 /ols/var/www/xx1.domain.com/public_html/.git/objects/b4
drwxr-xr-x   0 nobody nogroup      0 /ols/var/www/xx1.domain.com/public_html/.git/objects/bf
drwxr-xr-x   0 nobody nogroup      0 /ols/var/www/xx1.domain.com/public_html/.git/objects/cb
drwxr-xr-x   0 nobody nogroup      0 /ols/var/www/xx1.domain.com/public_html/.git/objects/ce
drwxr-xr-x   0 nobody nogroup      0 /ols/var/www/xx1.domain.com/public_html/.git/objects/dc
drwxr-xr-x   0 nobody nogroup      0 /ols/var/www/xx1.domain.com/public_html/.git/objects/f4
total 19`

**Comment by chrislusf** [comment]
What is the output of these commands in `weed shell`?

- `ls -al /ols/var/www/xx1.domain.com/public_html` 
- `ls -al /ols/var/www/xx1.domain.com/public_html/.git` 
- `meta.cat /ols/var/www/xx1.domain.com/public_html` 
- `meta.cat /ols/var/www/xx1.domain.com/public_html/.git`

**Comment by roshanjonah** [comment]
> What is the output of these commands in `weed shell`?
> 
> * `ls -al /ols/var/www/xx1.domain.com/public_html`
`total 34`
> * `ls -al /ols/var/www/xx1.domain.com/public_html/.git`
`drwxr-xr-x   0 nobody nogroup      0 /ols/var/www/xx1.domain.com/public_html/.git/objects
total 1`
> * `meta.cat /ols/var/www/xx1.domain.com/public_html`
`{
  "name": "public_html",
  "isDirectory": true,
  "chunks": [
  ],
  "attributes": {
    "fileSize": "0",
    "mtime": "1592974784",
    "fileMode": 2147484141,
    "uid": 65534,
    "gid": 65534,
    "crtime": "1592974784",
    "mime": "",
    "replication": "",
    "collection": "",
    "ttlSec": 0,
    "userName": "",
    "groupName": [
    ],
    "symlinkTarget": "",
    "md5": null
  },
  "extended": {
  }
}`
> * `meta.cat /ols/var/www/xx1.domain.com/public_html/.git`
`{
  "name": ".git",
  "isDirectory": true,
  "chunks": [
  ],
  "attributes": {
    "fileSize": "0",
    "mtime": "1593034756",
    "fileMode": 2147484141,
    "uid": 65534,
    "gid": 65534,
    "crtime": "1593034756",
    "mime": "",
    "replication": "",
    "collection": "",
    "ttlSec": 0,
    "userName": "",
    "groupName": [
    ],
    "symlinkTarget": "",
    "md5": null
  },
  "extended": {
  }
}`

**Comment by chrislusf** [comment]
> What is the output of these commands in weed shell?
> 
> ls -al /ols/var/www/xx1.domain.com/public_html
> total 34

what is the output?

**Comment by roshanjonah** [comment]
`> ls -al /ols/var/www/xx1.domain.com/public_html
-rw-r--r--   1 nobody nogroup    182 /ols/var/www/xx1.domain.com/public_html/.env.dist
drwxr-xr-x   0 nobody nogroup      0 /ols/var/www/xx1.domain.com/public_html/.git
drwxr-xr-x   0 nobody nogroup      0 /ols/var/www/xx1.domain.com/public_html/.github
-rw-r--r--   1 nobody nogroup   2133 /ols/var/www/xx1.domain.com/public_html/.gitignore
-rw-r--r--   1 nobody nogroup   5553 /ols/var/www/xx1.domain.com/public_html/.htaccess
-rw-r--r--   1 nobody nogroup    664 /ols/var/www/xx1.domain.com/public_html/.php_cs
-rw-r--r--   1 nobody nogroup   1154 /ols/var/www/xx1.domain.com/public_html/.travis.yml
-rw-r--r--   1 nobody nogroup    279 /ols/var/www/xx1.domain.com/public_html/.user.ini
-rw-r--r--   1 nobody nogroup   1859 /ols/var/www/xx1.domain.com/public_html/Gruntfile.js
-rw-r--r--   1 nobody nogroup  38419 /ols/var/www/xx1.domain.com/public_html/LICENSE.txt
drwxr-xr-x   0 nobody nogroup      0 /ols/var/www/xx1.domain.com/public_html/app
drwxr-xr-x   0 nobody nogroup      0 /ols/var/www/xx1.domain.com/public_html/bin
drwxr-xr-x   0 nobody nogroup      0 /ols/var/www/xx1.domain.com/public_html/build
-rw-r--r--   1 nobody nogroup    382 /ols/var/www/xx1.domain.com/public_html/codeception.yml
-rw-r--r--   1 nobody nogroup   7083 /ols/var/www/xx1.domain.com/public_html/composer.json
-rw-r--r--   1 nobody nogroup 527373 /ols/var/www/xx1.domain.com/public_html/composer.lock
-rw-r--r--   1 nobody nogroup   1627 /ols/var/www/xx1.domain.com/public_html/favicon.ico
-rw-r--r--   1 nobody nogroup    634 /ols/var/www/xx1.domain.com/public_html/index.php
-rw-r--r--   1 nobody nogroup    698 /ols/var/www/xx1.domain.com/public_html/index_dev.php
-rw-r--r--   1 nobody nogroup   7428 /ols/var/www/xx1.domain.com/public_html/logo.png
drwxr-xr-x   0 nobody nogroup      0 /ols/var/www/xx1.domain.com/public_html/media
-rw-r--r--   1 nobody nogroup   4043 /ols/var/www/xx1.domain.com/public_html/offline.php
-rw-r--r--   1 nobody nogroup  10487 /ols/var/www/xx1.domain.com/public_html/package-lock.json
-rw-r--r--   1 nobody nogroup    424 /ols/var/www/xx1.domain.com/public_html/package.json
-rw-r--r--   1 nobody nogroup   1393 /ols/var/www/xx1.domain.com/public_html/phpstan.neon
drwxr-xr-x   0 nobody nogroup      0 /ols/var/www/xx1.domain.com/public_html/plugins
-rw-r--r--   1 nobody nogroup   1594 /ols/var/www/xx1.domain.com/public_html/rector.yaml
-rw-r--r--   1 nobody nogroup    224 /ols/var/www/xx1.domain.com/public_html/robots.txt
drwxr-xr-x   0 nobody nogroup      0 /ols/var/www/xx1.domain.com/public_html/tests
drwxr-xr-x   0 nobody nogroup      0 /ols/var/www/xx1.domain.com/public_html/themes
drwxrwxr-x   0 nobody nogroup      0 /ols/var/www/xx1.domain.com/public_html/translations
-rw-r--r--   1 nobody nogroup  44310 /ols/var/www/xx1.domain.com/public_html/upgrade.php
drwxr-xr-x   0 nobody nogroup      0 /ols/var/www/xx1.domain.com/public_html/var
drwxr-xr-x   0 nobody nogroup      0 /ols/var/www/xx1.domain.com/public_html/vendor`

**Comment by chrislusf** [comment]
This shows the .git folder does exist. The `weed mount` should be able to see it.

**Comment by roshanjonah** [comment]
So when I run > ls -al /ols/var/www/xx1.domain.com/public_html

Why do you think it's still listing a folder called ".git" saying 0 in size? Shouldn't it be technically not there completely because I deleted it? 

For this reason, when I do new .git folder, it says there is one that already exists with files in it as per this command output

```
> ls -al /ols/var/www/xx1.domain.com/public_html/.git/objects
drwxr-xr-x   0 nobody nogroup      0 /ols/var/www/xx1.domain.com/public_html/.git/objects/0f
drwxr-xr-x   0 nobody nogroup      0 /ols/var/www/xx1.domain.com/public_html/.git/objects/14
drwxr-xr-x   0 nobody nogroup      0 /ols/var/www/xx1.domain.com/public_html/.git/objects/1e
drwxr-xr-x   0 nobody nogroup      0 /ols/var/www/xx1.domain.com/public_html/.git/objects/1f
drwxr-xr-x   0 nobody nogroup      0 /ols/var/www/xx1.domain.com/public_html/.git/objects/21
drwxr-xr-x   0 nobody nogroup      0 /ols/var/www/xx1.domain.com/public_html/.git/objects/30
drwxr-xr-x   0 nobody nogroup      0 /ols/var/www/xx1.domain.com/public_html/.git/objects/54
drwxr-xr-x   0 nobody nogroup      0 /ols/var/www/xx1.domain.com/public_html/.git/objects/57
drwxr-xr-x   0 nobody nogroup      0 /ols/var/www/xx1.domain.com/public_html/.git/objects/71
drwxr-xr-x   0 nobody nogroup      0 /ols/var/www/xx1.domain.com/public_html/.git/objects/88
drwxr-xr-x   0 nobody nogroup      0 /ols/var/www/xx1.domain.com/public_html/.git/objects/89
drwxr-xr-x   0 nobody nogroup      0 /ols/var/www/xx1.domain.com/public_html/.git/objects/aa
drwxr-xr-x   0 nobody nogroup      0 /ols/var/www/xx1.domain.com/public_html/.git/objects/b1
drwxr-xr-x   0 nobody nogroup      0 /ols/var/www/xx1.domain.com/public_html/.git/objects/b4
drwxr-xr-x   0 nobody nogroup      0 /ols/var/www/xx1.domain.com/public_html/.git/objects/bf
drwxr-xr-x   0 nobody nogroup      0 /ols/var/www/xx1.domain.com/public_html/.git/objects/cb
drwxr-xr-x   0 nobody nogroup      0 /ols/var/www/xx1.domain.com/public_html/.git/objects/ce
drwxr-xr-x   0 nobody nogroup      0 /ols/var/www/xx1.domain.com/public_html/.git/objects/dc
drwxr-xr-x   0 nobody nogroup      0 /ols/var/www/xx1.domain.com/public_html/.git/objects/f4
total 19
```

**Comment by chrislusf** [comment]
All folder size is 0. The .git folder does exist. Need to delete it first.

**Comment by chrislusf** [comment]
I tried these on normal disk. Seems there are `git pull` issues if the .git folder is moved from another clone.

```
Git clone a repo /main-folder/sub-folder
Delete the .git folder. rm -rf main-folder/sub-folder/.git
Git clone a repo on a top-level folder
Move .git folder to second-level folder mv .git main-folder/sub-folder/.git
Git pull
```

**Comment by roshanjonah** [comment]
That's exactly what I've done and where this issue all started from - I initially issued "rm -rf .git" inside the public_html folder where it says the .git exists but it just wouldn't delete and the errors of that filer have been posted above. It's an annoying issue. I can try to do this via weed shell but not a practical solution as we have many .git repos.

**Comment by roshanjonah** [comment]
I will try to git clone and not move the .git folder around and see if that addresses the issue.

**Comment by roshanjonah** [comment]
@chrislusf Unfortunately now it's not letting me clone the repo at all. It says .git/config is bad but there is no .git folder now even with weed shell. Any ideas?

**Comment by chrislusf** [comment]
you can run `fs.meta.save` in `weed shell` and send me the meta data file.

**Comment by roshanjonah** [comment]
Unfortunately, that hasn't fully fixed the issue, I am not getting the same filer errors but a different one but the mount server still throws the same GIT error!
