### ISSUE TITLE
can not find this notification output in filer replication

### ISSUE THREAD

**Issue by masoodkamyab** [chrislusf/seaweedfs#1375]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**
In [this](https://github.com/chrislusf/seaweedfs/wiki/Async-Replication-to-another-Filer) document when I execute `weed scaffold -config=filer`  it has this output :

    masood@office:~/Downloads➜  ./weed scaffold -config=filer

    # A sample TOML config file for SeaweedFS filer store
    # Used with "weed filer" or "weed server -filer"
    # Put this file to one of the location, with descending priority
    #    ./filer.toml
    #    $HOME/.seaweedfs/filer.toml
    #    /etc/seaweedfs/filer.toml

    ####################################################
    # Customizable filer server options
    ####################################################
    [filer.options]
    # with http DELETE, by default the filer would check whether a folder is empty.
    # recursive_delete will delete all sub folders and files, similar to "rm -Rf"
    recursive_delete = false
    # directories under this folder will be automatically creating a separate bucket
    buckets_folder = "/buckets"
    buckets_fsync = [          # a list of buckets with all write requests fsync=true
    	"important_bucket",
    	"should_always_fsync",
    ]

    ####################################################
    # The following are filer store options
    ####################################################

    [leveldb2]
    # local on disk, mostly for simple single-machine setup, fairly scalable
    # faster than previous leveldb, recommended.
    enabled = true
    dir = "."					# directory to store level db files
    
    [mysql]  # or tidb
    # CREATE TABLE IF NOT EXISTS filemeta (
    #   dirhash     BIGINT         COMMENT 'first 64 bits of MD5 hash value of directory field', 
    #   name        VARCHAR(1000)  COMMENT 'directory or file name',
    #   directory   TEXT           COMMENT 'full path to parent directory',
    #   meta        LONGBLOB,
    #   PRIMARY KEY (dirhash, name)
    # ) DEFAULT CHARSET=utf8;
    
    enabled = false
    hostname = "localhost"
    port = 3306
    username = "root"
    password = ""
    database = ""              # create or use an existing database
    connection_max_idle = 2
    connection_max_open = 100
    interpolateParams = false
    
    [postgres] # or cockroachdb
    # CREATE TABLE IF NOT EXISTS filemeta (    
    #   dirhash     BIGINT,
    #   name        VARCHAR(65535),
    #   directory   VARCHAR(65535),
    #   meta        bytes,
    #   PRIMARY KEY (dirhash, name)
    # );
    enabled = false
    hostname = "localhost"
    port = 5432
    username = "postgres"
    password = ""
    database = ""              # create or use an existing database
    sslmode = "disable"
    connection_max_idle = 100
    connection_max_open = 100
    
    [cassandra]
    # CREATE TABLE filemeta (
    #    directory varchar,
    #    name varchar,
    #    meta blob,
    #    PRIMARY KEY (directory, name)
    # ) WITH CLUSTERING ORDER BY (name ASC);
    enabled = false
    keyspace="seaweeds"
    hosts=[
    	"localhost:9042",
    ]
    
    [redis2]
    enabled = false    
    address  = "localhost:6379"
    password = ""
    database = 0
    
    [redis_cluster2]
    enabled = false
    addresses = [
        "localhost:30001",
        "localhost:30002",
        "localhost:30003",
        "localhost:30004",
        "localhost:30005",
        "localhost:30006",
    ]
    password = ""
    # allows reads from slave servers or the master, but all writes still go to the master
    readOnly = true
    # automatically use the closest Redis server for reads
    routeByLatency = true
    
    [etcd]
    enabled = false
    servers = "localhost:2379"
    timeout = "3s"
    
    [mongodb]
    enabled = false
    uri = "mongodb://localhost:27017"
    option_pool_size = 0
    database = "seaweedfs"
    
    
**System Setup**
- Debian 10
- x86_64 Linux 4.19.0-9-amd64

where can I find `[notification]` for config `RabbitMQ` to sync filer together?   
Is this possible to sync through `RabbitMQ`? and how if it is possible?

My `weed` version is :

    version 30GB 1.82 c48b407 linux amd64

**Comment by chrislusf** [comment]
Use `weed scaffold -config=notification` and see the section for `notification.gocdk_pub_sub`

**Comment by chrislusf** [comment]
Updated the doc.
