### ISSUE TITLE
Volume replication in background

### ISSUE THREAD

**Issue by wsj0000** [chrislusf/seaweedfs#1376]
I just have some idea to talk

1. Could the volume replicating in background to let the request return immediately. The vid could be assigned before the request return to keep the consistency. Before the replication completed, the request should be redirect read to the remote volume which keeping the chunk.
2. Or a lazy replication policy could be applied. When a non-local chunk is invoked, then replicate the chunk from remote instead of redirect read.
3. Or the replication could be execute manually. Like replicate the data in collection.
4. Maybe there was a way to combine the filer meta replication with the chunk data in volume in a transaction.

Most of above are the issues that trying to find a resolution of high-availability when using seaweedfs.

Just for discuss.

**Comment by chrislusf** [comment]
The volume level replication is tricky.

For HA, what about https://github.com/chrislusf/seaweedfs/wiki/Filer-Active-Active-xDC-synchronization ?

**Comment by wsj0000** [comment]
> The volume level replication is tricky.
> 
> For HA, what about https://github.com/chrislusf/seaweedfs/wiki/Filer-Active-Active-xDC-synchronization ?

Yeah! It is almost what I want! Thanks! 
I will close this issue.
