### ISSUE TITLE
update from 1.44 to 1.84, old data disappear

### ISSUE THREAD

**Issue by WYmindsky** [chrislusf/seaweedfs#1378]
config：3master、3filer、5volumes、1mount、1s3
             volume -max=256

**1.44:**
[root@cpu-001 ~]# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/sdg1       440G   16G  402G   4% /
devtmpfs         63G     0   63G   0% /dev
tmpfs            63G     0   63G   0% /dev/shm
tmpfs            63G  4.2G   59G   7% /run
tmpfs            63G     0   63G   0% /sys/fs/cgroup
/dev/sda        3.5T  9.3G  3.3T   1% /data1
/dev/sdb        3.5T  976G  2.4T  30% /data2
/dev/sdc        3.5T  660G  2.7T  20% /data3
/dev/sdd        3.5T  621G  2.7T  19% /data4
/dev/sde        3.5T  588G  2.7T  18% /data5
/dev/sdf        3.5T  798G  2.5T  24% /data6
tmpfs            13G     0   13G   0% /run/user/1001
tmpfs            13G     0   13G   0% /run/user/1237
tmpfs            13G     0   13G   0% /run/user/0
**SeaweedFS       607G  567G   40G  94% /data1/seaweedfs/data/mount**

**1,84:**
[root@cpu-001 ~]# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/sdg1       440G   16G  402G   4% /
devtmpfs         63G     0   63G   0% /dev
tmpfs            63G     0   63G   0% /dev/shm
tmpfs            63G  4.2G   59G   7% /run
tmpfs            63G     0   63G   0% /sys/fs/cgroup
/dev/sda        3.5T  9.3G  3.3T   1% /data1
/dev/sdb        3.5T  976G  2.4T  30% /data2
/dev/sdc        3.5T  660G  2.7T  20% /data3
/dev/sdd        3.5T  621G  2.7T  19% /data4
/dev/sde        3.5T  588G  2.7T  18% /data5
/dev/sdf        3.5T  798G  2.5T  24% /data6
tmpfs            13G     0   13G   0% /run/user/1001
tmpfs            13G     0   13G   0% /run/user/1237
tmpfs            13G     0   13G   0% /run/user/0
**10.18.1.28:9333/       110T  17M   110T  0% /data1/seaweedfs/data/mount**

567G data not exist，and another question：why 110T，we have 6 disk，unable to 110T，how to set it to real max space。

i just replace weed and restart all services。am i wrong ?

**Comment by chrislusf** [comment]
Please follow issue template.

**Comment by chrislusf** [comment]
256 x 30 GB = 110 TB
