### ISSUE TITLE
Go client for Seaweedfs

### ISSUE THREAD

**Issue by itzmanish** [chrislusf/seaweedfs#1379]
Hi, I am wondering if seaweedfs have client module in go or if there is any guide/mechanism to connect to weed server using golang without http call (I mean if i can connect it over tcp or grpc). If there is any please tell me. Thanks.

**Comment by ijunaid8989** [comment]
https://github.com/chrislusf/seaweedfs/wiki/Client-Libraries

**Comment by itzmanish** [comment]
> https://github.com/chrislusf/seaweedfs/wiki/Client-Libraries

Thanks @ijunaid8989 . I was reading wiki after opening this issue. It's my bad I haven't seen wiki before creating this issue.
