### ISSUE TITLE
s3api error: upload to filer error: failed to write to local disk: mismatching cookie 5b3f9bfb

### ISSUE THREAD

**Issue by WYmindsky** [chrislusf/seaweedfs#1381]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs
Report issues here. Ask questions here https://stackoverflow.com/questions/tagged/seaweedfs

example of a good issue report:
https://github.com/chrislusf/seaweedfs/issues/1005
example of a bad issue report:
https://github.com/chrislusf/seaweedfs/issues/1008

**Describe the bug**
update 1.44 to 1.84 failed，then i recover to 1.44。s3api err。

**System Setup**
ExecStart=/bin/bash -ce "exec /opt/app/weed/weed master -ip=10.18.1.28 -port=9333 -mdir=/data1/seaweedfs/data -peers=10.18.1.28:9333,10.18.1.29:9333,10.18.1.30:9333 >/data1/seaweedfs/data/master.log"

ExecStart=/bin/bash -ce "exec /opt/app/weed/weed filer -ip=10.18.1.28 -port=8888 -master=10.18.1.28:9333,10.18.1.29:9333,10.18.1.30:9333 >/data1/seaweedfs/data/filer.log"

ExecStart=/bin/bash -ce "exec /opt/app/weed/weed volume -dir=/data2/seaweedfs/data -max=256 -ip=10.18.1.28 -port=8090 -mserver=10.18.1.28:9333,10.18.1.29:9333,10.18.1.30:9333 >/data2/seaweedfs/data/volume.log"

ExecStart=/bin/bash -ce "exec /opt/app/weed/weed s3 -filer=10.18.1.28:8888 >/data1/seaweedfs/data/weed_s3.log"

- OS version
centos7.7
- output of `weed version`
version 30GB 1.44 linux amd64
- if using filer, show the content of `filer.toml`

**Expected behavior**
i dont kown what‘s wrong。

**Screenshots**
![image](https://user-images.githubusercontent.com/20678602/86343060-0646ca00-bc8b-11ea-8d6e-fd875b0c0d25.png)

**Additional context**

**Comment by chrislusf** [comment]
seems you need to provide details for https://github.com/chrislusf/seaweedfs/issues/1378 first.

**Comment by chrislusf** [comment]
Does it happen all the time or just right after the servers start up?

**Comment by WYmindsky** [comment]
> 
> 
> Does it happen all the time or just right after the servers start up?
i think after the servers start up, one day later, someone found the problem。

how to migrate data (1.44) to data (1.84), i deployed 1.84 on same server。disk size 499GB

**Comment by chrislusf** [comment]
seems you do not answer my question.

upgrade should be just replace the binary.
