### ISSUE TITLE
Why "Remove fixJpgOrientation feature"?

### ISSUE THREAD

**Issue by yourchanges** [chrislusf/seaweedfs#1384]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

From 1.83  the weedfs just  Remove fixJpgOrientation feature, it causes our prod env crash and some business not work.

there must be a work-around? or a warning before remove?

for best compatibility,  it should be keep until a big upgrade like 2.x.x?

**Comment by chrislusf** [comment]
Need a good way to communicate the deprecation changes.

For future CLI changes, if any, we will have deprecation releases, when we can print out a multi-line warning.

**Comment by chrislusf** [comment]
btw: I am synchronizing changes with helm chars in https://github.com/chrislusf/seaweedfs/tree/master/k8s/seaweedfs

Maybe need to add some sort of unit tests for that?

**Comment by yourchanges** [comment]
so do you have a  plan to add the " fixJpgOrientation feature" back again?

**Comment by yourchanges** [comment]
@chrislusf

**Comment by chrislusf** [comment]
no plan to add back the "fixJpgOrientation". No one is using it.

**Comment by yourchanges** [comment]
we use it, we have 10TB files on seaweedfs, a photo uploaded by our IOS customers( app or web ) will be automatically fix the jpg orientation.

**Comment by yourchanges** [comment]
@chrislusf any suggestions?
