### ISSUE TITLE
request file got error: {"error":"volume id 20 not found: volume id 20 not found"}

### ISSUE THREAD

**Issue by yiitz** [chrislusf/seaweedfs#1386]
版本： version 30GB 1.78 linux amd64
我线上有3台机器（同一网段）部署了master，因为做了负载均衡，请求同一个文件有时候正常，有时候报如题的错误。重启服务之后就正常了。猜测是master数据不一致导致

**Comment by chrislusf** [comment]
Please follow the issue template.

**Comment by yiitz** [comment]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs
Report issues here. Ask questions here https://stackoverflow.com/questions/tagged/seaweedfs

**Describe the bug**
我线上有3台机器（同一网段）部署了master，因为做了负载均衡，请求同一个文件有时候正常，有时候报如题的错误。重启服务之后就正常了。猜测是master数据不一致导致

**System Setup**
- List the command line to start
`weed master -mdir=/root/weedfs/master/data -defaultReplication=010 -ip="10.140.0.3" -peers=10.140.0.6:9333,10.140.0.3:9333,10.140.0.4:9333 -volumePreallocate`
`weed volume -max=67 -port=8081 -dir=./data -mserver="10.140.0.6:9333,10.140.0.3:9333,10.140.0.4:9333" -rack=rack1 -idleTimeout=300`
- OS version 
`Debian GNU/Linux 10`
- output of `weed version`
version 30GB 1.78 linux amd64

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by chrislusf** [comment]
Can you please show the error logs?

**Comment by chrislusf** [comment]
How did you request the file? And what was the logs at that time?

**Comment by yiitz** [comment]
> How did you request the file? And what was the logs at that time?

通过round robin的方式请求3个master,有的master就报了这个错，log应该是没有的吧，这个错误对seaweedfs来说应该是正常的。
