### ISSUE TITLE
panic in goraft

### ISSUE THREAD

**Issue by mischief** [chrislusf/seaweedfs#139]
here's the log of weedfs in a docker container on coreos.
http://sprunge.us/PdAc

systemd unit used to start weedfs:
```
[Unit]
Description=%p %i
After=docker.service
Requires=docker.service

[Service]
EnvironmentFile=/etc/environment
TimeoutStartSec=0
ExecStartPre=-/usr/bin/docker kill %p-%i
ExecStartPre=-/usr/bin/docker rm %p-%i
ExecStartPre=/usr/bin/docker pull mischief/weedfs
ExecStart=/usr/bin/docker run --name %p-%i --rm -p ${COREOS_PRIVATE_IPV4}:9333:9333 -p ${COREOS_PRIVATE_IPV4}:8080:8080 -p ${COREOS_PRIVATE_IPV4}:8888:8888 -v /opt/weedfs/data:/data mischief/weedfs -v 2 -logtostderr server -dir /data -filer -ip ${COREOS_PRIVATE_IPV4}
ExecStop=/usr/bin/docker rm %p-%i

[X-Fleet]
Conflicts=%p@*.service
```

the Dockerfile used to construct the mischief/weedfs image is the same as the Dockerfile in the weedfs repo. the version of weedfs in my image is `version 0.70 beta linux amd64`.

if there is other information i can provide please let me know..

**Comment by carmark** [comment]
@mischief Do you use the latest Dockerfile and build successfully?  I can not find the image on docker HUB and forked repository.

**Comment by mischief** [comment]
My dockerfile is the same as in the seaweedfs repo. My docker image is mischief/weedfs on docker hub.

**Comment by chrislusf** [comment]
Duplicated with issue 144

**Comment by chrislusf** [comment]
Possible work around is to add some delay before starting the different masters.
