### ISSUE TITLE
How to fix when volumeDataIntegrityChecking failed ?

### ISSUE THREAD

**Issue by zjzdy** [chrislusf/seaweedfs#1393]
I had a system crash and weed was not shut down properly.  Then the problem occurred when restarting.
weed version is 1.74+ and windows 10 amd64 system.
```
I0717 19:43:01 91060 volume_loading.go:94] volumeDataIntegrityChecking failed verifyNeedleIntegrity S:\weed\/data/57.idx failed: read data [31473654960,31499907751) : EOF
I0717 19:43:01 91060 disk_location.go:87] data file S:\weed\/data/49.idx, replicaPlacement=000 v=3 size=31462422064 ttl=
I0717 19:43:01 91060 volume_loading.go:94] volumeDataIntegrityChecking failed verifyNeedleIntegrity S:\weed\/data/58.idx failed: read data [31476752472,31488496274) : EOF
I0717 19:43:01 91060 disk_location.go:87] data file S:\weed\/data/50.idx, replicaPlacement=000 v=3 size=31683581352 ttl=
I0717 19:43:01 91060 volume_loading.go:94] volumeDataIntegrityChecking failed verifyNeedleIntegrity S:\weed\/data/59.idx failed: read data [31477174616,31480670766) : EOF
```

**Comment by zjzdy** [comment]
Only use filer save file. And maybe has upload new file when system crash.
I want to fix volumeDataIntegrityChecking failed and remove lost data or file record in the filer. What should I do ?

**Comment by chrislusf** [comment]
Currently need to build a tool to fix it. You can just leave it there so the volume is just read only.

**Comment by zjzdy** [comment]
Can I confirm which files are unavailable(unreadable) in the filer by any means?
Because sometimes I look for read errror log.
```
I0718 08:25:59 91060 volume_server_handlers_read.go:90] read /57,04da6284090d0f isNormalVolume true error: entry not found: offset 31167707776 found id 0 size 0, expected size 3607000
I0718 08:26:08 91060 volume_server_handlers_read.go:90] read /59,04f33b6730e583 isNormalVolume true error: EOF
I0718 08:27:21 91060 volume_server_handlers_read.go:90] read /59,04f32f165440f5 isNormalVolume true error: EOF
I0718 08:27:39 91060 volume_server_handlers_read.go:90] read /57,04da6f2ee814a1 isNormalVolume true error: entry not found: offset 31233494528 found id 0 size 0, expected size 7738751
I0718 08:29:01 91060 volume_server_handlers_read.go:90] read /59,04f3383994d63b isNormalVolume true error: EOF
I0718 08:30:02 91060 volume_server_handlers_read.go:90] read /57,04da68dd907c3e isNormalVolume true error: entry not found: offset 31185341688 found id 0 size 0, expected size 10526707
```
I want to reupload the files. But I don't know which file need reupload and if uploading the same file name will fail or error？

**Comment by chrislusf** [comment]
will need to look at filer logs to determine which file has error.

re-upload the file would be good.

**Comment by zjzdy** [comment]
I through parse fs.meta.save's data find all file which store in bad volume.
I find many file can't read, not only uploading file when crash. (I only test 1% files, all file can't read any data, return 404 or transmission error)
Now, I re-upload all file which store in bad volume. Can I delete the bad volume directly after stopping ?

**Comment by chrislusf** [comment]
In `weed shell`, there is a `volume.delete` command.

Do you know what is the problem with the volume? If you can share the volume dat file somehow, I can try to take a look.

**Comment by zjzdy** [comment]
Sorry, it stores private data. I cannot share it.
