### ISSUE TITLE
Async message broker implementation for seaweedfs 

### ISSUE THREAD

**Issue by joe-getcouragenow** [chrislusf/seaweedfs#1394]
I really like the design of the messaging system.

https://github.com/chrislusf/seaweedfs/tree/master/weed/messaging

If looks to me like Liftbridge is an excellent match to allow seaweed events to be published asynchronously using grpc and golang.

https://github.com/liftbridge-io

Liftbridge is quite similar to seaweeds in terms of coding / architecture styles also. Uses grpc to describe things. it even has the same concept of seperating the meta data from the data in order to make it easier to scale out.

The notification package seems to be where your current implementations are ? Glad to see GoCloud one. Would you be interested in a liftbridge one ?

**Comment by chrislusf** [comment]
Thanks!

The client currently is in https://github.com/seaweedfs/messaging-client-go
Need to move it to this repo later.

**Comment by joe-getcouragenow** [comment]
Ok.

**Comment by joe-getcouragenow** [comment]
> Thanks!
> 
> The client currently is in https://github.com/seaweedfs/messaging-client-go
> Need to move it to this repo later.

AH so you are using Seaweed as the persistence layer for your own Message Broker system ? Interesting...

**Comment by joe-getcouragenow** [comment]
So been playing around with things.

https://github.com/seaweedfs/messaging-client-go looks like a nice simple way of using SeaweedFS as a generic message queue. 

But, I am looking for a way of getting an event when a file changes so that clients can subscribe to file changes.
https://github.com/linxGnu/goseaweedfs does not seem to provide this which is understandable since its only a HTTP based system. It looks like this is the functionality ? https://github.com/chrislusf/seaweedfs/blob/master/weed/messaging/broker/broker_grpc_server.go

So if true, then i guess i need to be able to have a client subscribe to changes to a set of files or "volume", and then use the brokers in that folder and get my GUI client is to that broker ?

**Comment by chrislusf** [comment]
see `weed watch`.

The source code for it is in https://github.com/chrislusf/seaweedfs/blob/master/weed/command/watch.go

**Comment by joe-getcouragenow** [comment]
thanks

**Comment by joe-getcouragenow** [comment]
watch.go requires using a filer, and i dont need the filer for my use case.

So i was thinking that maybe i could get a notification from the Master-Server-API  ? Does it know when a file in a volume changes ?

**Comment by chrislusf** [comment]
> So i was thinking that maybe i could get a notification from the Master-Server-API ? Does it know when a file in a volume changes ?

No notifications for that. File updates or deletions do not always go through Master servers.
