### ISSUE TITLE
[Investigate]Add http2 support

### ISSUE THREAD

**Issue by chrislusf** [chrislusf/seaweedfs#140]
Need to investigate:

https://github.com/bradfitz/http2

**Comment by mcuadros** [comment]
http2, is being included by default on 1.6, and now is ready to test on the [experimental branch]("golang.org/x/net/http2"). 

The behaviour is exactly the same. 

At my company we are making a benchmark of some distributed file system, and having and http2 version of seaweedfs is something I want to test.

You dont mind if I work on the http2 integration?

**Comment by chrislusf** [comment]
Any help is hugely welcome! Also, if interested, you can also test this https://github.com/valyala/fasthttp , which seems faster.

**Comment by mcuadros** [comment]
This is a really quick and dirty test, having some fails even when you run the process, but the upload process works.

https://github.com/mcuadros/seaweedfs/commit/72fd0c7836fbcf2582acb68b414ae8a77360e525

Base on my benchmarks is going 2 times slower. Maybe I am doing something wrong

**Comment by ernado** [comment]
@mcuadros 
With TLS overhead it should be slower;
btw golang http2 implementation does not support non-TLS mode.

fasthttp on my benchmarks is faster (~1.5x) and spends less memory, but i think that disk always will be bottleneck.

**Comment by chrislusf** [comment]
http2 is already supported with latest Golang releases
