### ISSUE TITLE
S3 access logs, embed gateway, signed url

### ISSUE THREAD

**Issue by ddorian** [chrislusf/seaweedfs#1403]
Hi,

I have some question regarding s3:

1. Is there a way to get access logs ? They are also called bucket notifications in s3.
2. Does it make sense to embed the s3 gateway in the same process ? Since it's stateless, 1 more thing to not maintain.
3. Is there support for signed urls ? Also signed multi part uploads ?

Thank You

**Comment by chrislusf** [comment]
1. no logs now. you can use nginx logs?
2. `weed server -s3`
3. It should work. Let me know if there are bugs or not. I haven't heard of any usage or bug report about it.

**Comment by ddorian** [comment]
Access logs, like how many bytes,timestamp,query,user_agent on each request.

**Comment by chrislusf** [comment]
Add a nginx in front will get all the logs.

**Comment by ddorian** [comment]
@chrislusf is it possible to query the master to get the volume-id/volume-server where a s3 file resides ?

**Comment by chrislusf** [comment]
Yes. But that is not S3 API. What is the use case?

**Comment by ddorian** [comment]
@chrislusf the use case is to:
1. generate signed urls that expire (GET is enough)
2. signed urls point to the server where the file is hosted
3. keep access logs for GET/bandwidth used
4. not use filer..
5. supporting byte-range
6. get a list of server-ids where a file (or data part if EC) is located

I think I can do this by just putting a nxing-proxy that keeps access logs & does authentication in front of volume servers without s3. Correct ?

**Comment by chrislusf** [comment]
For presigned url, see https://github.com/chrislusf/seaweedfs/wiki/AWS-CLI-with-SeaweedFS#presigned-url
The presigned url points to the s3 server, since volume server is agnostic of the s3 and filer APIs.

> get a list of server-ids where a file (or data part if EC) is located
what is the purpose? There are gRPC APIs to do this.

**Comment by ddorian** [comment]
> what is the purpose? There are gRPC APIs to do this.

So I can give to a third party a direct url to one of the servers that contain the data (either replica, data part, or parity part). 
This way I lower inter-volume-server traffic.

> For presigned url, see https://github.com/chrislusf/seaweedfs/wiki/AWS-CLI-with-SeaweedFS#presigned-url

I think I can achieve this without using s3(filer) at all. 

Does the normal api support byte-range GET requests ?

**Comment by chrislusf** [comment]
> Does the normal api support byte-range GET requests ?

yes. Also multiple byte-range.

**Comment by ddorian** [comment]
@chrislusf 
When erasure coding:
1. Is it possible to keep byte-ranges for each data-part ?
2. And return the volume_ids + where each data-part is located along with start/end byte-ranges for each of them ?

**Comment by chrislusf** [comment]
1. yes. The EC implementation is very efficient for small files because they are batched together.
2. the volume server will handle it transparently.

**Comment by ddorian** [comment]
@chrislusf regarding accessing erasure coded files: https://github.com/chrislusf/seaweedfs/wiki/Erasure-Coding-for-warm-storage#how-the-read-works

Is it possible to contact A and know where the file is located (like volume B, in another node). So a request for fid=x, will return a list of servers that have data-parts, and list of servers that have parity-parts. Makes sense ?

And then the client can connect to B directly.

**Comment by chrislusf** [comment]
possible, but this would need deep knowledge about how the volume server works with EC volumes, to calculate where is the data, and how to merge the data in edge cases.

For clients, it works the same as a normal volume. Given a file id, the master will tell where is the ec volume servers. Pick any one of them, and the volume server would read the data from the right volume server.

**Comment by ddorian** [comment]
> but this would need deep knowledge about how the volume server works with EC volumes, to calculate where is the data, and how to merge the data in edge cases.

1. Master will tell which the volume servers are for file id
2. Ask any of the volume servers where to get file id
3. The volume server will know that file id is written in data-part-2, which resides in volume-server C. And returns volume server C.

Then you contact volume server C from the client. Does that make sense ?

**Comment by chrislusf** [comment]
mostly correct. Sometimes the data chunk can be on two volume servers if sitting on the edge of EC blocks.

These are all possible. There would need some code change somewhere.

**Comment by ddorian** [comment]
> These are all possible. There would need some code change somewhere.

This can probably be a new api on the volume-server, which you may want to call only in EC scenarios.

> Sometimes the data chunk can be on two volume servers if sitting on the edge of EC blocks.

Does it make sense to split data parts on file end ? 
To not split the file between 2+ blocks ?
Don't know if it's allowed in EC.

**Comment by chrislusf** [comment]
EC format is not easy to change. No matter how large the EC block is configured, there could be some file on multiple blocks.

The current design is already efficient enough. I am suspecting you are optimizing too early.
