### ISSUE TITLE
protect files from read

### ISSUE THREAD

**Issue by itzmanish** [chrislusf/seaweedfs#1409]
Since files on volume can be secured with jwt token for read by appending read=yes on url. 

But Isn't it a bug if a user remove read=yes flag from url one can access that file without providing jwt token in Authorisation header.

**Comment by chrislusf** [comment]
I do not understand where the `read=yes` comes from. 

Please read https://github.com/chrislusf/seaweedfs/wiki/Security-Overview#jwt-for-read-access-control

**Comment by itzmanish** [comment]
I have to expose file url to user to access. So how would i protect those files?

**Comment by chrislusf** [comment]
Use nginx to configure access

**Comment by itzmanish** [comment]
@chrislusf let me tell you my use case scenario-
I am making document management app like google drive where user can upload and download files. User can share file publicly or privately like google drive by adding email to file's access list. so how I can retrieve files only based on authorised user?

**Comment by ijunaid8989** [comment]
@itzmanish how are you building it? such as with any other language, you have to build a front end? or how have you been storing the files?

**Comment by itzmanish** [comment]
@ijunaid8989 storing files in seaweedfs. I want to only work over grpc. Also one thing I don't know how to retrieve a file or files by grpc since I don't see any rpc service for getting stream bytes of file content.

**Comment by ijunaid8989** [comment]
@itzmanish why do you only want to work with grpc? when they are clearly for metadata transactions?

**Comment by itzmanish** [comment]
@ijunaid8989 

> when they are clearly for metadata transactions?

I don't understand this statement. Can you please elaborate what do you mean by this?

> why do you only want to work with grpc?

I am more comfortable with grpc and seaweedfs does have grpc support so I am giving more preference to grpc.

**Comment by shumintao** [comment]
> Use nginx to configure access

怎么配置nginx  访问啊？
