### ISSUE TITLE
weed-fs on Linode

### ISSUE THREAD

**Issue by jake22599** [chrislusf/seaweedfs#141]
Hi, Im having issues with the master server system on my server in Linode. I have posted a detailed question on StackOverflow(http://stackoverflow.com/questions/30185696/weed-fs-in-linode-running-master).
Perhaps, somebody can help me out and look into it.

**Comment by chrislusf** [comment]
Use ip=your_ip_address instead of ip.bind

**Comment by jake22599** [comment]
if i replace it, it will crash after it finds the Master Server Leader.
But if i add that extra parameter, it is seen properly.
But some commands seems to still not working.

curl "http://{IP-ADDRESS}.166:9333/cluster/status?pretty=y"

shows {
  "Peers": [
    "localhost:9333"
  ]

While curl "http://{IP-ADDRESS}:9333/dir/status?pretty=y"
show nothing. Any idea

**Comment by chrislusf** [comment]
Very likely on the linode server itself, it can not access your "http://{IP-ADDRESS}:9333/cluster/status?pretty=y".
