### ISSUE TITLE
S3 API: failed to write to replicas for volume xx: file over the limited 268435456 bytes

### ISSUE THREAD

**Issue by robinWongM** [chrislusf/seaweedfs#1416]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs
Report issues here. Ask questions here https://stackoverflow.com/questions/tagged/seaweedfs

**Describe the bug**
When using S3 API `PutObject` to upload a large file (> 256 MB), S3 gateway will throw 500 Internal Error.
The log of S3 gateway recorded that
```
E0808 09:56:49     1 s3api_object_handlers.go:294] upload to filer error: failed to write to replicas for volume 22: [volume-test-3.volume-test:8080]: file over the limited 268435456 bytes
```

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".

The seaweedfs cluster is built on top of Kubernetes. Masters, volumes, filers and s3 gateways are replicated x 3.
```
weed master -defaultReplication 001 -ip $(hostname).master-test-peer -peers master-test-0.master-test-peer:9333,master-test-1.master-test-peer:9333,master-test-2.master-test-peer:9333
weed volume -dataCenter dc1 -rack rack1 -dir /data -ip $(hostname).volume-test -max 10 -mserver master-test:9333 -port 8080
weed filer -master master-test:9333
weed s3 -config /etc/seaweedfs/s3-config.json -filer filer-test:80
```
- OS version
```
Ubuntu 18.04.3 LTS
Linux 4.4.0-159-generic #187-Ubuntu SMP Thu Aug 1 16:28:06 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- output of `weed version`
```
version 30GB 1.87  linux amd64
```
- if using filer, show the content of `filer.toml`
```
[mysql]
enabled = true
username = "seaweedfs"
password = "*******************"
hostname = "mysql-cluster-test-mysql-master.mysql"
database = "seaweedfs"
port = 3306
```

**Expected behavior**
The file should be uploaded successfully.

**Comment by chrislusf** [comment]
Thanks for the detailed error report. 

Fixed in 3b1a95ac26debb3080794bf8605ea2d5636818c7
