### ISSUE TITLE
SeaweedFS not compatible with Hadoop 2.6 (Cloudera CDH-5.16)

### ISSUE THREAD

**Issue by jameno123** [chrislusf/seaweedfs#1417]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**
other/java/hadoop2/ will not compile against CDH-5.16 due to Override of non-existant truncate function and possible protobuf version differences.

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
- OS version: Ubuntu 16, CDH version: 5.16, Hadoop Version: 2.6
- output of `weed version`: version 8000GB 1.87 a6b59d5 linux amd64
- if using filer, show the content of `filer.toml`: 
```
# A sample TOML config file for SeaweedFS filer store
# Used with "weed filer" or "weed server -filer"
# Put this file to one of the location, with descending priority
#    ./filer.toml
#    $HOME/.seaweedfs/filer.toml
#    /etc/seaweedfs/filer.toml

####################################################
# Customizable filer server options
####################################################
[filer.options]
# with http DELETE, by default the filer would check whether a folder is empty.
# recursive_delete will delete all sub folders and files, similar to "rm -Rf"
recursive_delete = false
# directories under this folder will be automatically creating a separate bucket
buckets_folder = "/buckets"
buckets_fsync = [          # a list of buckets with all write requests fsync=true
        "important_bucket",
        "should_always_fsync",
]

####################################################
# The following are filer store options
####################################################

[leveldb2]
# local on disk, mostly for simple single-machine setup, fairly scalable
# faster than previous leveldb, recommended.
enabled = true
dir = "."                                       # directory to store level db files

```
**Expected behavior**
Seaweedfs hadoop2-client should compile or be indicated in the documentation that a specific version of hadoop is required

**Screenshots**
![image](https://user-images.githubusercontent.com/27821272/89716077-16cc1d80-d978-11ea-94e3-6a4eceda53c9.png)

**Additional context**
Removing the truncate function (which seems to be a non-supported API in hadoop 2.6) allows the code to compile but then it seems the protobuf versions are different. We understand that hadoop-2.6 is a very old verison. We are trying to migrate from hadoop to seaweedfs and have a ton (354M) small files so upgrading our cloudera version currently is not an option (one of the reasons we are looking into seaweedfs). It would be nice if we could get a build that works with hadoop-2.6 to allow this transition to happen - even if its just a custom patch that we an apply to our build.

**Comment by jameno123** [comment]
Clarification: when loading the seaweed client, the hdfs dfs -ls seaweed:// works correctly, but it breaks access to HDFS with the error in the screenshot. This is the part I am having trouble figuring out. Thank you in advance.

**Comment by chrislusf** [comment]
The error in the screenshot seems not related to SeaweedFS code.

Is there any docker image with the hadoop 2.6 setup? That will be really easy to try.

**Comment by jameno123** [comment]
After more research it seems that it's related to the shaded jar conflicting with protobuff. I'm not sure how this is interacting this way but my testing of relocating org.apache.hadoop seems to move the trouble around from making hdfs work to breaking seaweed.  I do not have a docker image but i could provide you access to a aws ec2 instance with the setup. Would that work? I'll post core-site.xml in a few minutes for you.

**Comment by jameno123** [comment]
Here is the requested core-site.xml, its very basic without a lot of options in it.

[core-site.xml.txt](https://github.com/chrislusf/seaweedfs/files/5048298/core-site.xml.txt)

If you wish for access the AWS EC2 instance please message me directly.

**Comment by chrislusf** [comment]
Runs fine for me:

```
hadoop-2.6.0-cdh5.16.2$ bin/hdfs dfs -Dfs.seaweedfs.impl=seaweed.hdfs.SeaweedFileSystem -libjars /Users/chris/go/src/github.com/chrislusf/seaweedfs/other/java/hdfs2/target/seaweedfs-hadoop2-client-1.4.4.jar -copyFromLocal NOTICE.txt seaweedfs://localhost:8888/
20/08/09 14:54:40 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Warning: fs.defaultFS is not set when running "copyFromLocal" command.
20/08/09 14:54:41 INFO hdfs.SeaweedFileSystemStore: rename source: seaweedfs://localhost:8888/NOTICE.txt._COPYING_ destination:seaweedfs://localhost:8888/NOTICE.txt
hadoop-2.6.0-cdh5.16.2$ bin/hdfs dfs -Dfs.seaweedfs.impl=seaweed.hdfs.SeaweedFileSystem -libjars /Users/chris/go/src/github.com/chrislusf/seaweedfs/other/java/hdfs2/target/seaweedfs-hadoop2-client-1.4.4.jar -ls seaweedfs://localhost:8888/*.txt
20/08/09 14:55:15 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Warning: fs.defaultFS is not set when running "ls" command.
-rw-r--r--   1 chris staff      14978 2020-08-09 14:54 seaweedfs://localhost:8888/NOTICE.txt
-rw-r--r--   1 chris staff       1366 2020-08-09 14:53 seaweedfs://localhost:8888/README.txt
hadoop-2.6.0-cdh5.16.2$
```

**Comment by jameno123** [comment]
What i did was place: /Users/chris/go/src/github.com/chrislusf/seaweedfs/other/java/hdfs2/target/seaweedfs-hadoop2-client-1.4.4.jar  into /usr/lib/hadoop

and then  hdfs dfs -ls seaweedfs://localhost:8888/ will work fine
but then, hdfs dfs -ls /    (using fs.defaultFS) will throw errors.

Its almost as if when seaweedfs-hadoop2-client is loaded it cant talk to the HDFS namenode anymore because of protobuf errors (screenshot above).

I am glad to toss you on my mv and walk through a chat with you... Just let me know your public key (via email) and i will respond with the ip address of the hosts. 

The only change i made was to set the CDH version of hdfs in hadoop.version and add the cloudera repository in settings.xml

pom.xml
```
diff --git a/other/java/hdfs2/pom.xml b/other/java/hdfs2/pom.xml
index 6d91917..31c6b23 100644
--- a/other/java/hdfs2/pom.xml
+++ b/other/java/hdfs2/pom.xml
@@ -6,7 +6,7 @@
 
     <properties>
         <seaweedfs.client.version>1.4.4</seaweedfs.client.version>
-        <hadoop.version>2.9.2</hadoop.version>
+        <hadoop.version>2.6.0-cdh5.16.2</hadoop.version>
     </properties>
 
     <groupId>com.github.chrislusf</groupId>
```

settings.xml
```
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                      https://maven.apache.org/xsd/settings-1.0.0.xsd">

  <profiles>
    <profile>
      <id>cloudera</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <repositories>
        <repository>
                  <id>cloudera</id>
                  <url>http://repository.cloudera.com/artifactory/cloudera-repos/</url>
        </repository>
      </repositories>
    </profile>
  </profiles>
</settings>
```
I place the settings.xml beside pom.xml and then compile with
mvn package -s settings.xml
(to pull in the cloudera specfic repo for HDFS 2.6)

In this screenshot below you can see that when i place the seaweed client jar into the lib/hadoop hdfs native access to hdfs stops working:

Test#1: with seaweed client jar in /usr/lib/hadoop attempt to access hdfs native -- FAILURE, cast com.google.protobuf.
Test#2: with seaweed client jar in /usr/lib/hadoop attempt to access seaweed -- WORKS as expected
Test#3: remove seaweed client jar from /usr/lib/hadoop, access hdfs native -- WORKS as expected
Test#4: remove seaweed client jar from /usr/lib/hadoop, access seaweed - fails, as expected.

So while access to seaweed works when the jar is in place access to HDFS native does not.

![image](https://user-images.githubusercontent.com/27821272/89743174-73116900-da6e-11ea-9365-caa9f6faec95.png)

**Comment by jameno123** [comment]
Forgot to mention, if you don't change the hadoop.version and compile against the cdh versions of the hadoop packages, you end up with this error when trying to natively access hdfs via "hdfs dfs -ls /"... This is what lead me down the path of attempting to compile against the cloudera versions of hadoop jars to begin with.

```
root@devvm-:/usr/src/seaweedfs/other/java/hdfs2/target# hdfs dfs -ls /
Exception in thread "main" java.lang.VerifyError: Bad return type
Exception Details:
  Location:
    org/apache/hadoop/hdfs/DFSClient.getQuotaUsage(Ljava/lang/String;)Lorg/apache/hadoop/fs/QuotaUsage; @160: areturn
  Reason:
    Type 'org/apache/hadoop/fs/ContentSummary' (current frame, stack[0]) is not assignable to 'org/apache/hadoop/fs/QuotaUsage' (from method signature)
  Current Frame:
    bci: @160
    flags: { }
    locals: { 'org/apache/hadoop/hdfs/DFSClient', 'java/lang/String', 'org/apache/hadoop/ipc/RemoteException', 'java/io/IOException' }
    stack: { 'org/apache/hadoop/fs/ContentSummary' }
  Bytecode:
    0x0000000: 2ab6 0381 2a13 0832 2bb6 02ed 4d01 4e2a
    0x0000010: b401 6a2b b908 3402 003a 042c c600 1d2d
    0x0000020: c600 152c b602 f3a7 0012 3a05 2d19 05b6
    0x0000030: 02f7 a700 072c b602 f319 04b0 3a04 1904
    0x0000040: 4e19 04bf 3a06 2cc6 001d 2dc6 0015 2cb6
    0x0000050: 02f3 a700 123a 072d 1907 b602 f7a7 0007
    0x0000060: 2cb6 02f3 1906 bf4d 2c07 bd03 4e59 0313
    0x0000070: 0350 5359 0413 037c 5359 0513 037e 5359
    0x0000080: 0613 0838 53b6 0354 4e2d c108 3899 0014
    0x0000090: b201 0613 083a b901 2002 002a 2bb6 083b
    0x00000a0: b02d bf                                
  Exception Handler Table:
    bci [35, 39] => handler: 42
    bci [15, 27] => handler: 60
    bci [15, 27] => handler: 68
    bci [78, 82] => handler: 85
    bci [60, 70] => handler: 68
    bci [4, 57] => handler: 103
    bci [60, 103] => handler: 103
  Stackmap Table:
    full_frame(@42,{Object[#2],Object[#527],Object[#754],Object[#633],Object[#2102]},{Object[#633]})
    same_frame(@53)
    same_frame(@57)
    full_frame(@60,{Object[#2],Object[#527],Object[#754],Object[#633]},{Object[#633]})
    same_locals_1_stack_item_frame(@68,Object[#633])
    full_frame(@85,{Object[#2],Object[#527],Object[#754],Object[#633],Top,Top,Object[#633]},{Object[#633]})
    same_frame(@96)
    same_frame(@100)
    full_frame(@103,{Object[#2],Object[#527]},{Object[#832]})
    append_frame(@161,Object[#832],Object[#171])

        at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:164)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2816)
        at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:98)
        at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2853)
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2835)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:387)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:186)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:371)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:296)
        at org.apache.hadoop.fs.shell.PathData.expandAsGlob(PathData.java:325)
        at org.apache.hadoop.fs.shell.Command.expandArgument(Command.java:235)
        at org.apache.hadoop.fs.shell.Command.expandArguments(Command.java:218)
        at org.apache.hadoop.fs.shell.FsCommand.processRawArguments(FsCommand.java:102)
        at org.apache.hadoop.fs.shell.Command.run(Command.java:165)
        at org.apache.hadoop.fs.FsShell.run(FsShell.java:315)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
        at org.apache.hadoop.fs.FsShell.main(FsShell.java:372)
```

**Comment by chrislusf** [comment]
Try to add this to the two hadoop dependencies in the hdfs2/pom.xml
```
            <scope>provided</scope>
```

**Comment by jameno123** [comment]
Should i leave hadoop.version set to 2.6 cdh? or leave it at 2.9 as you provide?

**Comment by jameno123** [comment]
I left the version to cdh and pulled in the cdh repo with the settings.xml, set dependency to scope>provided and it works as expected!

Thank you!

**Comment by chrislusf** [comment]
thanks for confirming!

**Comment by jameno123** [comment]
eppp well HDFS works! seaweed doesnt..

root@devvm-:/usr/src/seaweedfs/other/java/hdfs2# hdfs dfs -copyFromLocal settings.xml seaweedfs://127.0.0.1:8888/settings.xml
copyFromLocal: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: shaded/org/apache/http/concurrent/Cancellable
root@devvm-:/usr/src/seaweedfs/other/java/hdfs2#

**Comment by chrislusf** [comment]
revert your other changes

**Comment by jameno123** [comment]
Perfect! That works just as expected... Thank you for all your help.

```
root@devvm-:/usr/src/seaweedfs/other/java/hdfs2# cp target/seaweedfs-hadoop2-client-1.4.4.jar /usr/lib/hadoop/seaweedfs-hadoop2-client-1.4.4.jar 
root@devm-:/usr/src/seaweedfs/other/java/hdfs2# hdfs dfs -ls /
Found 1 items
drwxr-xr-x   - root supergroup          0 2020-08-09 21:38 /this-directory-is-on-hdfs
root@devvm-:/usr/src/seaweedfs/other/java/hdfs2# hdfs dfs -ls seaweedfs://127.0.0.1/
Found 2 items
drwxrwxrwx   - root root          0 2020-08-09 23:29 seaweedfs://127.0.0.1/this-directory-is-on-seaweed
drwxr-xr--   -                    0 2020-08-09 23:30 seaweedfs://127.0.0.1/topics
root@devvm-:/usr/src/seaweedfs/other/java/hdfs2# hdfs dfs -copyFromLocal pom.xml seaweedfs://127.0.0.1/pom.xml
20/08/09 23:36:19 INFO hdfs.SeaweedFileSystemStore: rename source: seaweedfs://127.0.0.1/pom.xml._COPYING_ destination:seaweedfs://127.0.0.1/pom.xml
root@devvm-:/usr/src/seaweedfs/other/java/hdfs2# hdfs dfs -copyFromLocal pom.xml /pom.xml
root@devvm-:/usr/src/seaweedfs/other/java/hdfs2# hdfs dfs -ls /
Found 2 items
-rw-r--r--   1 root supergroup       6938 2020-08-09 23:36 /pom.xml
drwxr-xr-x   - root supergroup          0 2020-08-09 21:38 /this-directory-is-on-hdfs
root@devvm-:/usr/src/seaweedfs/other/java/hdfs2# hdfs dfs -ls seaweedfs://127.0.0.1/
Found 3 items
-rw-r--r--   1 root root       6938 2020-08-09 23:36 seaweedfs://127.0.0.1/pom.xml
drwxrwxrwx   - root root          0 2020-08-09 23:29 seaweedfs://127.0.0.1/this-directory-is-on-seaweed
drwxr-xr--   -                    0 2020-08-09 23:30 seaweedfs://127.0.0.1/topics
```
