### ISSUE TITLE
Usage of SeaweedFS with Impala

### ISSUE THREAD

**Issue by jameno123** [chrislusf/seaweedfs#1420]
**Describe the bug**
On the same system we were testing on for CDH-5.16/hadoop-2.6 we were able to get seaweed to work correctly. However impala is still unable to reach data from seaweed and returns the following error. Have you ever made seaweed work with impala?

Hive was able to validate the connection to seaweedfs and the partition was created correctly. We can read and write data from inside of hive however impala is returning an error.

ERROR: AnalysisException: org.apache.impala.catalog.TableLoadingException: Failed to load metadata for table: test.test
CAUSED BY: RuntimeException: java.lang.ClassNotFoundException: Class seaweed.hdfs.SeaweedFileSystem not found
CAUSED BY: ClassNotFoundException: Class seaweed.hdfs.SeaweedFileSystem not found
CAUSED BY: TableLoadingException: Failed to load metadata for table: test.test
CAUSED BY: RuntimeException: java.lang.ClassNotFoundException: Class seaweed.hdfs.SeaweedFileSystem not found
CAUSED BY: ClassNotFoundException: Class seaweed.hdfs.SeaweedFileSystem not found

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
- OS version: ubuntu16
- output of `weed version`: version 8000GB 1.87 a6b59d5 linux amd64

**Expected behavior**
Data is able to be read by impala from seaweed hadoop connector

**Screenshots**
(not available)

**Additional context**
hdfs dfs -ls seaweedfs://  works fine (see: #1417)

**Comment by chrislusf** [comment]
This seems just a library issue. Needs to put the seaweedfs jar to Impala path.

**Comment by jameno123** [comment]
Hi Chris,

Thanks again for the quick reply ... According to the log file from /var/log/impala/impalad.INFO, i see that it is picking up the 1.4.5.jar from /var/lib/impala/*.jar classpath reference (as output by the logs below).

However, i still get the same error:
CAUSED BY: RuntimeException: java.lang.ClassNotFoundException: Class seaweed.hdfs.SeaweedFileSystem not found

I did check the classpath ahead of time before opening the bug, the fact that it is listed and still throwing an error is the part that is confusing me and the reason i opened the report.

java.class.path:/var/lib/impala/seaweedfs-hadoop2-client-1.4.5.jar:/usr/share/java/mysql-connector-java.jar:/etc/impala/conf:/etc/hadoop/conf:/etc/impala/conf:/etc/impala/conf:/usr/lib/impala/lib/libthrift-0.9.0.jar::/usr/lib/impala/lib/activation-1.1.jar:/usr/lib/impala/lib/ant-1.5.jar:/usr/lib/impala/lib/ant-1.9.1.jar:/usr/lib/impala/lib/ant-contrib-1.0b3.jar:/usr/lib/impala/lib/ant-launcher-1.9.1.jar:/usr/lib/impala/lib/antlr-2.7.7.jar:/usr/lib/impala/lib/antlr-runtime-3.3.jar:/usr/lib/impala/lib/aopalliance-1.0.jar:/usr/lib/impala/lib/apacheds-i18n-2.0.0-M15.jar:/usr/lib/impala/lib/apacheds-jdbm1-2.0.0-M2.jar:/usr/lib/impala/lib/apacheds-kerberos-codec-2.0.0-M15.jar:/usr/lib/impala/lib/apache-log4j-extras-1.2.17.jar:/usr/lib/impala/lib/api-asn1-api-1.0.0-M20.jar:/usr/lib/impala/lib/api-util-1.0.0-M20.jar:/usr/lib/impala/lib/asm-3.1.jar:/usr/lib/impala/lib/asm-commons-3.1.jar:/usr/lib/impala/lib/asm-tree-3.1.jar:/usr/lib/impala/lib/async-1.4.1.jar:/usr/lib/impala/lib/audience-annotations-0.7.0.jar:/usr/lib/impala/lib/avro.jar:/usr/lib/impala/lib/aws-java-sdk-bundle-1.11.134.jar:/usr/lib/impala/lib/azure-data-lake-store-sdk-2.2.9.jar:/usr/lib/impala/lib/bonecp-0.7.1.RELEASE.jar:/usr/lib/impala/lib/calcite-avatica-1.0.0-incubating.jar:/usr/lib/impala/lib/calcite-core-1.0.0-incubating.jar:/usr/lib/impala/lib/calcite-linq4j-1.0.0-incubating.jar:/usr/lib/impala/lib/commons-beanutils-1.8.3.jar:/usr/lib/impala/lib/commons-beanutils-core-1.8.0.jar:/usr/lib/impala/lib/commons-cli-1.2.jar:/usr/lib/impala/lib/commons-codec-1.9.jar:/usr/lib/impala/lib/commons-collections-3.2.2.jar:/usr/lib/impala/lib/commons-compiler-2.7.6.jar:/usr/lib/impala/lib/commons-compress-1.4.1.jar:/usr/lib/impala/lib/commons-configuration-1.6.jar:/usr/lib/impala/lib/commons-daemon-1.0.13.jar:/usr/lib/impala/lib/commons-dbcp-1.4.jar:/usr/lib/impala/lib/commons-digester-1.8.jar:/usr/lib/impala/lib/commons-el-1.0.jar:/usr/lib/impala/lib/commons-httpclient-3.1.jar:/usr/lib/impala/lib/commons-io-2.4.jar:/usr/lib/impala/lib/commons-lang-2.6.jar:/usr/lib/impala/lib/commons-lang3-3.1.jar:/usr/lib/impala/lib/commons-logging-1.1.3.jar:/usr/lib/impala/lib/commons-math-2.2.jar:/usr/lib/impala/lib/commons-math3-3.1.1.jar:/usr/lib/impala/lib/commons-net-3.1.jar:/usr/lib/impala/lib/commons-pool-1.5.4.jar:/usr/lib/impala/lib/commons-pool2-2.4.2.jar:/usr/lib/impala/lib/core-3.1.1.jar:/usr/lib/impala/lib/curator-client-2.7.1.jar:/usr/lib/impala/lib/curator-framework-2.7.1.jar:/usr/lib/impala/lib/curator-recipes-2.7.1.jar:/usr/lib/impala/lib/curator-test-2.11.1.jar:/usr/lib/impala/lib/curator-x-discovery-2.11.1.jar:/usr/lib/impala/lib/datanucleus-api-jdo-3.2.6.jar:/usr/lib/impala/lib/datanucleus-core-3.2.12.jar:/usr/lib/impala/lib/datanucleus-rdbms-3.2.12.jar:/usr/lib/impala/lib/derby-10.10.2.0.jar:/usr/lib/impala/lib/eigenbase-properties-1.1.4.jar:/usr/lib/impala/lib/error_prone_annotations-2.3.1.jar:/usr/lib/impala/lib/findbugs-annotations-1.3.9-1.jar:/usr/lib/impala/lib/flatbuffers-java-1.6.0.1.jar:/usr/lib/impala/lib/geronimo-annotation_1.0_spec-1.1.1.jar:/usr/lib/impala/lib/geronimo-jaspic_1.0_spec-1.0.jar:/usr/lib/impala/lib/geronimo-jta_1.1_spec-1.1.1.jar:/usr/lib/impala/lib/groovy-all-2.4.4.jar:/usr/lib/impala/lib/gson-2.2.4.jar:/usr/lib/impala/lib/guava-11.0.2.jar:/usr/lib/impala/lib/guice-3.0.jar:/usr/lib/impala/lib/guice-servlet-3.0.jar:/usr/lib/impala/lib/hadoop-annotations.jar:/usr/lib/impala/lib/hadoop-archives.jar:/usr/lib/impala/lib/hadoop-auth.jar:/usr/lib/impala/lib/hadoop-aws.jar:/usr/lib/impala/lib/hadoop-azure-datalake.jar:/usr/lib/impala/lib/hadoop-common.jar:/usr/lib/impala/lib/hadoop-hdfs.jar:/usr/lib/impala/lib/hadoop-mapreduce-client-common.jar:/usr/lib/impala/lib/hadoop-mapreduce-client-core.jar:/usr/lib/impala/lib/hadoop-mapreduce-client-jobclient.jar:/usr/lib/impala/lib/hadoop-mapreduce-client-shuffle.jar:/usr/lib/impala/lib/hadoop-yarn-api.jar:/usr/lib/impala/lib/hadoop-yarn-client.jar:/usr/lib/impala/lib/hadoop-yarn-common.jar:/usr/lib/impala/lib/hadoop-yarn-server-applicationhistoryservice.jar:/usr/lib/impala/lib/hadoop-yarn-server-common.jar:/usr/lib/impala/lib/hadoop-yarn-server-nodemanager.jar:/usr/lib/impala/lib/hadoop-yarn-server-resourcemanager.jar:/usr/lib/impala/lib/hadoop-yarn-server-web-proxy.jar:/usr/lib/impala/lib/hbase-annotations.jar:/usr/lib/impala/lib/hbase-client.jar:/usr/lib/impala/lib/hbase-common.jar:/usr/lib/impala/lib/hbase-protocol.jar:/usr/lib/impala/lib/high-scale-lib-1.1.1.jar:/usr/lib/impala/lib/hive-ant.jar:/usr/lib/impala/lib/hive-beeline.jar:/usr/lib/impala/lib/hive-classification.jar:/usr/lib/impala/lib/hive-cli.jar:/usr/lib/impala/lib/hive-common.jar:/usr/lib/impala/lib/hive-exec.jar:/usr/lib/impala/lib/hive-hbase-handler.jar:/usr/lib/impala/lib/hive-hcatalog-core.jar:/usr/lib/impala/lib/hive-hcatalog-server-extensions.jar:/usr/lib/impala/lib/hive-metastore.jar:/usr/lib/impala/lib/hive-serde.jar:/usr/lib/impala/lib/hive-service.jar:/usr/lib/impala/lib/hive-shims-common.jar:/usr/lib/impala/lib/hive-shims.jar:/usr/lib/impala/lib/hive-shims-scheduler.jar:/usr/lib/impala/lib/hsqldb-1.8.0.10.jar:/usr/lib/impala/lib/htrace-core-3.2.0-incubating.jar:/usr/lib/impala/lib/htrace-core4-4.0.1-incubating.jar:/usr/lib/impala/lib/httpclient-4.2.5.jar:/usr/lib/impala/lib/httpcore-4.2.5.jar:/usr/lib/impala/lib/impala-data-source-api-1.0-SNAPSHOT.jar:/usr/lib/impala/lib/impala-frontend-0.1-SNAPSHOT.jar:/usr/lib/impala/lib/ivy-2.4.0.jar:/usr/lib/impala/lib/

**Comment by jameno123** [comment]
opp... i think i got it... The catalogd server was not loading the classpath correctly! Sigh.. Sorry to bug. Thanks for the reply!
