### ISSUE TITLE
日志不停的刷read disk size: dir:"/data"，无法使用seaweedfs

### ISSUE THREAD

**Issue by GeorgeWang1994** [chrislusf/seaweedfs#1421]
**Describe the bug**

**System Setup**
开启weed filter功能
操作系统：ubuntu16
weed version： 1.18

下面是操作日志：

![image](https://user-images.githubusercontent.com/29206315/89892204-e949d300-dc08-11ea-9828-4031158dd643.png)

上述问题在每次重启以后就又恢复，但是不清楚是哪里的问题

**Expected behavior**
日志正常，同时seaweedfs恢复正常，能够通过客户端正常的连接

**Comment by chrislusf** [comment]
the log lines are normal lines. No useful info in this issue. Please follow issue template.
