### ISSUE TITLE
why  BREAK the filer API compatibility?

### ISSUE THREAD

**Issue by yourchanges** [chrislusf/seaweedfs#1424]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

see:

https://github.com/chrislusf/seaweedfs/commit/3b1a95ac26debb3080794bf8605ea2d5636818c7#r41432342

before that commit, the response contains the fid, 

and cause by this "refact", the API compatibility gone without any message?

our PROD ENV crashed again.

should we just try our best to keep API compatibility?

**Comment by chrislusf** [comment]
One large file may have multiple file ids. Do you  have this use case?
