### ISSUE TITLE
Any plan to support symlinks with FUSE and filer ?

### ISSUE THREAD

**Issue by SacDin** [chrislusf/seaweedfs#1425]
Hello,

Any plan or potential to support symlinks ?

Regards

**Comment by chrislusf** [comment]
already supported.

**Comment by SacDin** [comment]
Got it, thanks. Don't know why filer HTTP server shows 0B in listing but actual local filesystem show and works perfectly.

**Comment by chrislusf** [comment]
softlink is only used in FUSE

**Comment by wild-jie** [comment]
hi, how to create symlinks? when i upload  symlinks, it become a real file. thanks

**Comment by chrislusf** [comment]
`ln -s`

**Comment by wild-jie** [comment]
thanks for your reply. you mean can't upload symlinks&file from a dir, only support create  symlinks in FUSE

**Comment by chrislusf** [comment]
That's right. There seems no easy way to instruct the softlink via http upload.

**Comment by wild-jie** [comment]
thanks for your work, i'm new to seaweed.
