### ISSUE TITLE
S3 need to implement policy to limit file size

### ISSUE THREAD

**Issue by gao2009ss** [chrislusf/seaweedfs#1426]
版本1.90

问题一：

例如正确地址
http://127.0.0.1:8333/testbucket/file/topic/2020-08-19/image/93380c2d1739420d88ad743ed9ed02c0a16d44128a84c4e56b67cc8bf77d07bbc.jpg

使用listObjectsV2查询返回地址

http://127.0.0.1:8333/testbucket/file/topic/2020-08-19/image93380c2d1739420d88ad743ed9ed02c0a16d44128a84c4e56b67cc8bf77d07bbc.jpg

对比发现在文件名前面少了一个斜杆

查询代码：

`S3Client s3Client = ...

ListObjectsV2Request listObjectsReqManual = ListObjectsV2Request.builder()
    		        .bucket("testbucket")
    		        .maxKeys(6)
    		        .prefix("file/topic/")
    		        .build();

boolean done = false;
	while (!done) {
    		ListObjectsV2Response listObjResponse = s3Client.listObjectsV2(listObjectsReqManual);
    		for (S3Object content : listObjResponse.contents()) {
    		    System.out.println(content.key());
    		}

    		if (listObjResponse.nextContinuationToken() == null) {
    		    done = true;
    		}
    		System.out.println("分页");
    		listObjectsReqManual = listObjectsReqManual.toBuilder()
    		       .continuationToken(listObjResponse.nextContinuationToken())
    		       .build();
}`

问题二：建议S3接口实现Policy功能
使用S3接口就是需要它的预签名功能，Policy里的content-length-range属性可以限制上传文件大小,这样在客户端使用预签名URL直传就不会让文件上传大小超出限制

参照API 
https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-HTTPPOSTConstructPolicy.html
https://docs.aws.amazon.com/zh_cn/AmazonS3/latest/dev/HTTPPOSTExamples.html
https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-post-example.html

**Comment by chrislusf** [comment]
fixed the first one

**Comment by chrislusf** [comment]
Implemented PostPolicy.
