### ISSUE TITLE
Missing files on volume, duplicate keys on filer store (postgres)

### ISSUE THREAD

**Issue by evo-arni** [chrislusf/seaweedfs#1429]
My application writes quite a bit of files of various size (~300Gb in total), and within some time (hours or days), some files are not available on the volume server. 
S3 client is unable to get files it expects to find, and I see in the filer logs: 
`
2020/08/20 07:52:02 http: superfluous response.WriteHeader call from github.com/chrislusf/seaweedfs/weed/server.processRangeRequest (common.go:281)
I0820 07:52:041 stream.go:39] read 128,278152b6aaa6a6 failed, err: http://seaweedfs-volume-0.seaweedfs-volume:8080/128,278152b6aaa6a6: 404 Not Found
I0820 07:52:051 stream.go:39] read 128,278152b6aaa6a6 failed, err: http://seaweedfs-volume-0.seaweedfs-volume:8080/128,278152b6aaa6a6: 404 Not Found
`
On postgres side I can also see following errors: 
`
2020-08-20 09:14:57.669 GMT [54784] ERROR:duplicate key value violates unique constraint "filemeta_pkey"
2020-08-20 09:14:57.669 GMT [54784] DETAIL:Key (dirhash, name)=(-433982040352496476, chk-678) already exists.
2020-08-20 09:14:57.669 GMT [54784] STATEMENT:INSERT INTO filemeta (dirhash,name,directory,meta) VALUES($1,$2,$3,$4)
`

**System Setup**
- Centos 7, kernel 5.5.2, weed version 30GB 1.90  linux amd64
- 2 filers, 3 masters, 6 volumes, 2 S3 instances
- running in Kubernetes, HA postgresql as filer store.

filer.toml:
[leveldb2]
enabled = true
dir = "/data/filerldb2"

However /data/filerldb2 is empty, as postgres is enabled trough environment variables and leveldb is disabled (see below).

components are started as following : 

- /usr/bin/weed -logdir=/seaweedfs/logs -v=3 filer -port=8888 -dirListLimit=100000 -ip=10.42.78.108 -master=seaweedfs-master-0.seaweedfs-master:9333,seaweedfs-master-1.seaweedfs-master:9333,seaweedfs-master-2.seaweedfs-master:9333
- /usr/bin/weed -logdir=/seaweedfs/logs -v=3 master -port=9333 -mdir=/seaweedfs/data -ip.bind=0.0.0.0 -defaultReplication=1 -metrics.address=preprod-prom-pushgateway-1-prometheus-pushgateway:9091 -volumeSizeLimitMB=3000 -ip=seaweedfs-master-0.seaweedfs-master -peers=seaweedfs-master-0.seaweedfs-master:9333,seaweedfs-master-1.seaweedfs-master:9333,seaweedfs-master-2.seaweedfs-master:9333
- /usr/bin/weed -v=3 s3 -port=8333 -filer=seaweedfs-filer:8888 -config=/etc/seaweedfs/s3-secrets.json
- /usr/bin/weed -logdir=/seaweedfs/logs -v=3 volume -port=8080 -dir=/seaweedfs/data -max=50 -rack=rack1 -dataCenter=xxx3 -ip.bind=0.0.0.0 -read.redirect=true -ip=seaweedfs-volume-0.seaweedfs-volume -compactionMBps=40 -mserver=seaweedfs-master-0.seaweedfs-master:9333,seaweedfs-master-1.seaweedfs-master:9333,seaweedfs-master-2.seaweedfs-master:9333

ENV variables for filer:

- WEED_POSTGRES_USERNAME:               <set to the key 'username' in secret 'secret-seaweedfs-db'>  Optional: false
- WEED_POSTGRES_PASSWORD:               <set to the key 'password' in secret 'secret-seaweedfs-db'>  Optional: false
- SEAWEEDFS_FULLNAME:                   seaweedfs
- WEED_FILER_BUCKETS_FOLDER:            /buckets
- WEED_FILER_OPTIONS_RECURSIVE_DELETE:  false
- WEED_FILER_QUEUES_FOLDER:             /queues
- WEED_LEVELDB2_ENABLED:                false
- WEED_POSTGRES_DATABASE:               seaweed
- WEED_POSTGRES_ENABLED:                true
- WEED_POSTGRES_HOSTNAME:               preprod-seaweedfs-pg-postgresql
- WEED_POSTGRES_PORT:                   5432
- WEED_POSTGRES_SSLMODE:                disable

**Expected behavior**
- Expect not to see postgres duplicate key errors
- filer should not have metadata for files that are absent on volumes
- files should not be missing, at least should fail the upload on the spot.

**Additional context**
As filer is backed by Postgres store, assuming filer is stateless. However, logs are clearly stating that filer is doing insert while it had to do update. Or, insert should overwrite any existing record if we're overwriting a file.
Not sure if it would be easy to reproduce this issue, so if any other information is needed, please let me know.

**Comment by LazyDBA247-Anyvision** [comment]
@evo-arni  did you configured the filers with their ip's/dns (peers, other filers)
https://github.com/chrislusf/seaweedfs/blob/f48567c5c62bf8c8cebf568eeb919f25a4fc4289/weed/command/filer.go#L59

should solve some metadata issues.

**Comment by chrislusf** [comment]
Thanks for the detailed report! I added a fix to fall back to update.

**Comment by chrislusf** [comment]
> @evo-arni did you configured the filers with their ip's/dns (peers, other filers)
> https://github.com/chrislusf/seaweedfs/blob/f48567c5c62bf8c8cebf568eeb919f25a4fc4289/weed/command/filer.go#L59
> 
> should solve some metadata issues.

This is still experimental and not recommended yet.

**Comment by evo-arni** [comment]
Update to version 1.91 didn't fix the problem. Files get missing anyway, but now with different error on filer: 

> I0826 08:02:12     1 upload_content.go:225] failing to upload to http://seaweedfs-volume-1.seaweedfs-volume:8080/119,3f2cf495dcc728: Post http://seaweedfs-volume-1.seaweedfs-volume:8080/119,3f2cf495dcc728: EOF
> W0826 08:02:12     1 upload_content.go:94] uploading to http://seaweedfs-volume-1.seaweedfs-volume:8080/119,3f2cf495dcc728: failing to upload to http://seaweedfs-volume-1.seaweedfs-volume:8080/119,3f2cf495dcc728: Post http://seaweedfs-volume-1.seaweedfs-volume:8080/119,3f2cf495dcc728: EOF
> I0826 08:03:47     1 filer_server_handlers_read.go:37] Not found /buckets/preprod-game-scavenger/checkpoints/7f58ac99b4c12c8295a9343a3b5b3a75/chk-1266: filer: no entry is found in filer store
> I0826 08:10:48     1 filer_server_handlers_read.go:37] Not found /buckets/preprod-game-scavenger/checkpoints/7f58ac99b4c12c8295a9343a3b5b3a75/chk-1272: filer: no entry is found in filer store


So looks like the issue is related not only to duplicate keys in DB.

**Comment by chrislusf** [comment]
The previous fix is wrong. The duplication error stopped the operation before the fall-back update. 

Added a fix:
https://github.com/chrislusf/seaweedfs/commit/ed62f524524f557c9319f2199b2f3299866969cd
