### ISSUE TITLE
Which log v level is best for production environment?

### ISSUE THREAD

**Issue by yanyiwu** [chrislusf/seaweedfs#143]
v default is 0, but v=0 print too few logs.
I think one file uploaded , at least one line log should be printed.

**Comment by chrislusf** [comment]
We should try to follow some standard on the log level and details. How about this?

0: server starts up, failures
1: file level operations: add/update file
2: network level operations: replication to other nodes, etc.
3: cluster level information, volume server join the cluster, master join the cluster, heartbeats, etc.
4: internal debug info

**Comment by yanyiwu** [comment]
That's ok. Paste them into wiki would be better.

**Comment by SakaRawks** [comment]
Hello guys, does the log level option still exist ? I can't get it to work in any of my startup commands.

**Comment by chrislusf** [comment]
Yes.

  weed -v=xxx master

**Comment by SakaRawks** [comment]
Awesome, thanks. I didn't put the flag at the right place.

Btw I think it could be awesome to write something in the wiki about this.

**Comment by roflmao** [comment]
@chrislusf  Is there a loglevel to log 500 errors? Im trying to log when a volume server is down and replication level is not met. Tried this with all possible numbers (0,1,2,3,4)
```
/usr/local/bin/weed -v=1 -logtostderr master -mdir=/data/meta/ -ip=10.1.1.103 -defaultReplication=010 -volumePreallocate -volumeSizeLimitMB 30000 -pulseSeconds 100
```
