### ISSUE TITLE
S3 liveness/readiness probe fails

### ISSUE THREAD

**Issue by evo-arni** [chrislusf/seaweedfs#1430]
**Description**
On kubernetes, when using / as liveness and readiness checks for S3 component, they both fail.
Suspecting the reason is because S3 authorisation is enabled : 
```
/ # curl http://localhost:8333/
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied.</Message><Resource>/</Resource><RequestId>1598274710012142791</RequestId></Error>/ #
```

***System Setup***
My setup is exactly as described in issue #1429 

**Expected behavior**
S3 liveness and readiness checks need unauthenticated url to check for. If connecting to / is not an option, alternate URLs should be available.

**Comment by chrislusf** [comment]
Added a fix. 

You would also need to configure the anonymous access. See https://github.com/chrislusf/seaweedfs/wiki/Amazon-S3-API#configuration-example
