### ISSUE TITLE
 filer 进程异常退出

### ISSUE THREAD

**Issue by dale-wen** [chrislusf/seaweedfs#1432]
cluster info ：
start master
./weed master -mdir=/data/master
start volume
 ./weed volume -max=100 -mserver=10.193.103.4:9333 -dir=/data2  -port=8080
start filer 
./weed filer -master="10.193.103.4:9333" -dirListLimit=1000000 
start  fuse
 ./weed mount -filer=10.193.95.132:8888 -dir=/mnt/seaweedfs -filer.path=/ -cacheCapacityMB=100000

测试工具 mdtest 去写4K小文件

一段时间之后 filer 进程一次退出
异常信息如下：
I0826 16:18:48 52655 configuration.go:25] Configure filer for redis2
I0826 16:18:48 52655 meta_aggregator.go:125] subscribing remote 10.193.95.132:8888 meta change: subscribe: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.193.95.132:18888: connect: connection refused"
I0826 16:18:48 52655 filer.go:144] Start Seaweed Filer 30GB 1.91 2cdad77 at 10.193.95.132:8888
I0826 16:18:50 52655 filer_grpc_server_sub_meta.go:145] + listener filer:10.193.95.132:8888@10.193.95.132:33180
I0826 16:18:50 52655 filer_grpc_server_sub_meta.go:60]  filer:10.193.95.132:8888@10.193.95.132:33180 local subscribe / from 1970-01-01 08:00:00 +0800 CST
I0826 16:23:50 52655 filer_grpc_server_sub_meta.go:145] + listener mount@10.193.227.1:37846
I0826 16:23:50 52655 filer_grpc_server_sub_meta.go:25]  mount@10.193.227.1:37846 starts to subscribe / from 2020-08-26 16:23:50.896100358 +0800 CST
I0826 16:23:58 52655 filer_grpc_server_sub_meta.go:145] + listener mount@10.193.227.6:45668
I0826 16:23:58 52655 filer_grpc_server_sub_meta.go:25]  mount@10.193.227.6:45668 starts to subscribe / from 2020-08-26 16:23:58.343721991 +0800 CST
I0826 16:24:08 52655 filer_grpc_server_sub_meta.go:145] + listener mount@10.193.227.7:35014
I0826 16:24:08 52655 filer_grpc_server_sub_meta.go:25]  mount@10.193.227.7:35014 starts to subscribe / from 2020-08-26 16:24:08.26312215 +0800 CST
I0826 17:17:24 52655 filer_grpc_server_sub_meta.go:150] - listener mount@10.193.227.1:37846
panic: runtime error: slice bounds out of range [:762697419] with capacity 4197264

goroutine 127 [running]:
github.com/chrislusf/seaweedfs/weed/util/log_buffer.(*LogBuffer).LoopProcessLogData(0xc00019e0d0, 0x35696806, 0xed6d81316, 0x300cbe0, 0xc00070fb88, 0xc000f100f0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/util/log_buffer/log_read.go:51 +0x5c4
github.com/chrislusf/seaweedfs/weed/server.(*FilerServer).SubscribeMetadata(0xc00078ce40, 0xc0000cd0e0, 0x2122b80, 0xc000f100b0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/server/filer_grpc_server_sub_meta.go:40 +0x4e8
github.com/chrislusf/seaweedfs/weed/pb/filer_pb._SeaweedFiler_SubscribeMetadata_Handler(0x1c537c0, 0xc00078ce40, 0x211ebc0, 0xc0003c0a80, 0x303a3d0, 0xc000176600)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/pb/filer_pb/filer.pb.go:4252 +0x10c
google.golang.org/grpc.(*Server).processStreamingRPC(0xc0002364e0, 0x212a2c0, 0xc000703380, 0xc000176600, 0xc000582900, 0x2ff5200, 0x0, 0x0, 0x0)
        /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1329 +0xcbd
google.golang.org/grpc.(*Server).handleStream(0xc0002364e0, 0x212a2c0, 0xc000703380, 0xc000176600, 0x0)
        /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1409 +0xc66
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00047e1c0, 0xc0002364e0, 0x212a2c0, 0xc000703380, 0xc000176600)
        /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:746 +0xa1
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:744 +0xa1

**Comment by chrislusf** [comment]
how to reproduce it?

**Comment by dale-wen** [comment]
filer 开启 redis（单实例），挂在fuse （可以都用默认配置）
mdtest 写入4K小文件， 测试一段时间，这个bug必现，大概写入 1KW+ 文件个数的时候出现

**Comment by chrislusf** [comment]
what is the command to run mdtest?

**Comment by dale-wen** [comment]
mpirun -hostfile /root/hostfile --allow-run-as-root -np 32 mdtest -I 3050 -b 4 -z 5 -d /mnt/seaweedfs/client1  -C -F -L -w 4096

**Comment by chrislusf** [comment]
which version of mdtest? How to install it on Mac?

**Comment by dale-wen** [comment]
install it to centos :
openmpi安装注意事项：

安装地址：https://www.open-mpi.org/software/ompi/v4.0/

./configure --prefix=/usr/local/openmpi4 --enable-mca-no-build=btl-uct

make -j32 && make install

修改~/.bashrc

export PATH=/usr/local/openmpi4/bin:/usr/local/ior/bin:$PATH

export LD_LIBRARY_PATH=/usr/local/openmpi4/lib:/usr/local/ior/lib:$LD_LIBRARY_PATH

ior安装注意事项：

安装地址：https://github.com/hpc/ior

./configure CFLAGS="-I/usr/local/openmpi4/include" LDFLAGS="-L/usr/local/openmpi4/lib" --prefix=/usr/local/ior/

make && make install

**Comment by gongbing851217** [comment]
这个subcribe metadata这个功能能否取消掉的？

**Comment by chrislusf** [comment]
```
chris@chris-VirtualBox:~$ mpirun --use-hwthread-cpus --allow-run-as-root mdtest -I 3050 -b 4 -z 5 -d /mnt/seaweedfs/client1 -C -F -L -w 4096
-- started at 08/27/2020 23:19:45 --

mdtest-3.4.0+dev was launched with 1 total task(s) on 1 node(s)
Command line used: mdtest '-I' '3050' '-b' '4' '-z' '5' '-d' '/mnt/seaweedfs/client1' '-C' '-F' '-L' '-w' '4096'
Path: /mnt/seaweedfs
FS: 9.8 GiB   Used FS: 89.4%   Inodes: 0.6 Mi   Used Inodes: 37.5%

Nodemap: 1
1 tasks, 3123200 files

SUMMARY rate: (of 1 iterations)
   Operation                      Max            Min           Mean        Std Dev
   ---------                      ---            ---           ----        -------
   File creation             :        182.935        182.935        182.935          0.000
   File stat                 :          0.000          0.000          0.000          0.000
   File read                 :          0.000          0.000          0.000          0.000
   File removal              :          0.000          0.000          0.000          0.000
   Tree creation             :       1339.827       1339.827       1339.827          0.000
   Tree removal              :          0.000          0.000          0.000          0.000
-- finished at 08/28/2020 04:04:19 --

```

**Comment by dale-wen** [comment]
版本：version 30GB 1.91 2cdad77 linux amd64
mdtest 写入数据太少，而且压力小，它是在下面这个命令的时候，必现
mpirun -hostfile /root/hostfile --allow-run-as-root -np 32 mdtest -I 3050 -b 4 -z 5 -d /mnt/seaweedfs/client1 -C -F -L -w 4096

**Comment by chrislusf** [comment]
```
chris@chris-VirtualBox:~$ mpirun --use-hwthread-cpus --allow-run-as-root mdtest -I 3050 -b 4 -z 5 -d /mnt/seaweedfs/client1 -C -F -L -w 4096
-- started at 08/28/2020 13:04:22 --

mdtest-3.4.0+dev was launched with 4 total task(s) on 1 node(s)
Command line used: mdtest '-I' '3050' '-b' '4' '-z' '5' '-d' '/mnt/seaweedfs/client1' '-C' '-F' '-L' '-w' '4096'
Path: /mnt/seaweedfs
FS: 9.8 GiB   Used FS: 87.6%   Inodes: 0.6 Mi   Used Inodes: 36.8%

Nodemap: 1111
4 tasks, 12492800 files

SUMMARY rate: (of 1 iterations)
   Operation                      Max            Min           Mean        Std Dev
   ---------                      ---            ---           ----        -------
   File creation             :        252.361        252.361        252.361          0.000
   File stat                 :          0.000          0.000          0.000          0.000
   File read                 :          0.000          0.000          0.000          0.000
   File removal              :          0.000          0.000          0.000          0.000
   Tree creation             :       1060.710       1060.710       1060.710          0.000
   Tree removal              :          0.000          0.000          0.000          0.000
-- finished at 08/29/2020 02:49:27 --

```

**Comment by chrislusf** [comment]
Added a few fixes. Please try it out with the latest git tip.

**Comment by gongbing851217** [comment]
# I0907 17:49:29 19467 filer_grpc_server_sub_meta.go:154] - listener mount@10.21.49.28:43836
panic: runtime error: slice bounds out of range [:350671382] with capacity 4203679

goroutine 275 [running]:
github.com/chrislusf/seaweedfs/weed/util/log_buffer.(*LogBuffer).LoopProcessLogData(0xc000750750, 0x3634c5da, 0xed6e7f46e, 0x34a3980, 0xc0096a7b88, 0xc0003851d0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/util/log_buffer/log_read.go:51 +0x5c4
github.com/chrislusf/seaweedfs/weed/server.(*FilerServer).SubscribeMetadata(0xc000494960, 0xc000693140, 0x2452040, 0xc000385180, 0x0, 0x0)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/server/filer_grpc_server_sub_meta.go:40 +0x4ef
github.com/chrislusf/seaweedfs/weed/pb/filer_pb._SeaweedFiler_SubscribeMetadata_Handler(0x1e9e220, 0xc000494960, 0x244dcc0, 0xc0001d4240, 0x34d1198, 0xc0003c0f00)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/pb/filer_pb/filer.pb.go:4312 +0x10c
google.golang.org/grpc.(*Server).processStreamingRPC(0xc0005d3860, 0x245a320, 0xc009700c00, 0xc0003c0f00, 0xc000925b30, 0x348bb20, 0x0, 0x0, 0x0)
        /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1329 +0xcbd
google.golang.org/grpc.(*Server).handleStream(0xc0005d3860, 0x245a320, 0xc009700c00, 0xc0003c0f00, 0x0)
        /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1409 +0xc66
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc003de86a0, 0xc0005d3860, 0x245a320, 0xc009700c00, 0xc0003c0f00)
        /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:746 +0xa1
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:744 **+0xa1**

**Comment by chrislusf** [comment]
@gongbing851217 what is the version?

**Comment by gongbing851217** [comment]
1.9.3

**Comment by chrislusf** [comment]
@gongbing851217 please check 1.96

**Comment by gongbing851217** [comment]
1.96 fix this bug?
