### ISSUE TITLE
Volume not found, but it actually exists.

### ISSUE THREAD

**Issue by wsj0000** [chrislusf/seaweedfs#1436]
Version: 1.91
There are times that filer return 500 when downloading file. And the error said "volume 603 not found". But it actually exists on volume server. Ant when I restart the filer. It will be correct.
![image](https://user-images.githubusercontent.com/11285030/91559504-ca6a7100-e96a-11ea-8ecf-384f7f7cd148.png)

![image](https://user-images.githubusercontent.com/11285030/91559548-dfdf9b00-e96a-11ea-9f41-b85dd81a1a71.png)
I didn't open the verbose log on that case. I'm still checking stack trace. I will paste more information here next time it happened

**Comment by chrislusf** [comment]
Please share the command lines you used to start the servers.

**Comment by wsj0000** [comment]
**Master:**
weed master -ip=10.100.10.57 -defaultReplication=001 -port=9333
**Volume:** 

- Volume1:
```
weed volume -mserver="10.100.10.57:9333" -dir="./weed-volume-data" -dataCenter="DC-Cloud" -ip="10.100.10.151" -rack="Rack-1" -max=410 -port=8080
```
- Volume2: 
```
weed volume -mserver="10.100.10.57:9333" -dir="./weed-volume-data-1" -dataCenter="DC-Cloud" -ip="10.100.10.151" -rack="Rack-1" -max=410 -port=8081
```
**Filer:**
```
weed filer -master="10.100.10.57:9333" -port=8888
```
**S3 gateway:**
```
weed s3 -port=8870 -filer=10.100.10.57:8888 -config=~/config.json -domainName=resource.domain.local
```

An s3 gateway was added. But this also happened before the s3 gateway added. The issue seem has no necessary relation to S3 gateway.

**Comment by chrislusf** [comment]
there should be master logs on `10.100.10.57`, usually under `/tmp` with the name `weed.*`.

**Comment by wsj0000** [comment]
> there should be master logs on `10.100.10.57`, usually under `/tmp` with the name `weed.*`.

Logs found in /tmp but not record in that day. We start the weed in docker. Might be discard by docker when trying to fix it.
I will be watching on that. When the issues comes again. I will show it here.

Thanks for reply!

**Comment by noname9117** [comment]
1.92版本，也有这样的问题。3master +  3volume server，调用leader接口: /dir/lookup?volumeId= 提示找不到volumeId，其他master可以。（下图9333为leader）
![QQ图片20200921103227](https://user-images.githubusercontent.com/70991990/93729721-51240e00-fbf8-11ea-9bde-b67403b5f7de.png)
![QQ图片20200921103232](https://user-images.githubusercontent.com/70991990/93729722-52553b00-fbf8-11ea-8f03-87d1b2b0680b.png)
通过修改data_node.go源码：
![123](https://user-images.githubusercontent.com/70991990/93729771-79137180-fbf8-11ea-916b-af8fa6a25244.png)
偶尔会出现以下日志：
![QQ图片20200921105330](https://user-images.githubusercontent.com/70991990/93729866-d4ddfa80-fbf8-11ea-850d-f3abac848700.png)
希望帮忙排查下为什么volumelayout.vid2location里面会丢失volumeID，谢谢！
master 启动命令：`nohup /usr/local/seaweedfs192/weed master -port=9333 -mdir=/usr/local/seaweedfs192/mfile -ip=10.15.2.43 -defaultReplication=010 -peers=10.15.2.41:9333,10.15.2.42:9333,10.15.2.43:9333 >/usr/local/seaweedfs192/master.log &`
@chrislusf

**Comment by chrislusf** [comment]
@noname9117 Thanks for the debug info. Very helpful!

Added better locking for the `dn.volumes`. Not quite sure whether it is directly related.

**Comment by wsj0000** [comment]
> @noname9117 Thanks for the debug info. Very helpful!
> 
> Added better locking for the `dn.volumes`.
> 
> Not quite sure whether it is directly related. Could you please help to keep monitoring this? How often do the previous log show up? I want to confirm whether this fix is helpful or not.

The issue mentioned on @noname9117 looks very similar. The problem occur a few times these days. But there is few useful logs. Can you add a few logs to related location for debugging?
And I will try to build the master version to checkout whether it already be fixed. 
Thanks all @chrislusf @noname9117

**Comment by noname9117** [comment]
> @noname9117 Thanks for the debug info. Very helpful!
> 
> Added better locking for the `dn.volumes`.
> 
> Not quite sure whether it is directly related. Could you please help to keep monitoring this? How often do the previous log show up? I want to confirm whether this fix is helpful or not.

使用最新的代码打包后启动volume server有问题？ telnet 能通，应用假死，访问不了volume server。（重启也不能恢复，使用1.92版本启动后恢复）
volume server启动命令：`nohup /usr/local/seaweedfsnew/weed volume -max=1024 -dir=/usr/local/seaweedfs192/vfile -ip=10.15.2.41 -port=8081 -mserver=10.15.2.41:9333,10.15.2.42:9333,10.15.2.43:9333 -dataCenter=commonDc -rack=r1 >> /usr/local/seaweedfs192/seaweedfs.log &` 
![1](https://user-images.githubusercontent.com/70991990/93838341-e1775700-fcbb-11ea-8a4e-56938d4a7bbb.png)
![2](https://user-images.githubusercontent.com/70991990/93838344-e6d4a180-fcbb-11ea-9307-9fe9a5a9e697.png)
![3](https://user-images.githubusercontent.com/70991990/93838391-0966ba80-fcbc-11ea-84b0-60ddea2d5aa1.png)
@chrislusf

**Comment by chrislusf** [comment]
@noname9117 what are the logs?

**Comment by chrislusf** [comment]
@wsj0000 does this still happen now with newer versions?

**Comment by wsj0000** [comment]
> @wsj0000 does this still happen now with newer versions?

Not yet. I will close this issue. If this happen again, I will re-open it.

**Comment by ctacodes** [comment]
Could someone assist with this issue? I'm encountering an error when attempting to access the status page at `http://localhost:9333/status`. 

The error message I'm receiving is as follows:

`{"error":"volume id status not found: Unknown volume id status"}`
