### ISSUE TITLE
Urbackup migration causes EOF/IO Error in FUSE

### ISSUE THREAD

**Issue by timolow** [chrislusf/seaweedfs#1437]
**Describe the bug**
When trying to kick off a urbackup migration from moosefs fuse to seaweedfs fuse I get a IO error when urbackup service starts.

/var/log/urbackup.log
2020-08-29 14:28:52: ERROR: LMDB: Failed to open LMDB database file (Input/output error)
2020-08-29 14:28:52: ERROR: Error opening inode db

**System Setup**
./weed -v=4  mount  --dir /weed-mount -filer 192.168.1.131:8888 -collection urbackup -replication 010
./weed master -volumeSizeLimitMB 10000 -volumePreallocate -defaultReplication 010 -garbageThreshold .03 -metrics.address=192.168.1.131:9091
./weed filer -defaultReplicaPlacement 010 -collection filer

-OS Version
Ubuntu 18.04

- output of `weed version`
version 30GB 1.91  linux amd64 (compiled from git)

- if using filer, show the content of `filer.toml`
[leveldb2]

enabled = false
dir = "/root/filerldb2"					# directory to store level db files

[mysql]  

enabled = true
hostname = "192.168.1.131"
port = 3306
username = "weedfs"
password = "redacted"
database = "seaweedfs"              # create or use an existing database
connection_max_idle = 2
connection_max_open = 100
interpolateParams = false

**Expected behavior**
Urbackup should be able to write files to the fuse filesystem

**Screenshots**

**Additional context**
Steps to reproduce.

-Install Urbackup and have a backup completed.
-Mount weedfs fuse file system
-Create a migrate_storage_to file under /var/urbackup (https://www.urbackup.org/administration_manual.html#x1-9500010.8)
-restart urbackup service

**Comment by chrislusf** [comment]
> -Create a migrate_storage_to file under /var/urbackup (https://www.urbackup.org/administration_manual.html#x1-9500010.8)

Please list the steps to run. I have no knowledge of every tool used here.

**Comment by timolow** [comment]
Understood, 
echo '$weed_mount_point' > /var/urbackup/migrate_storage_to

Hope that helps

**Comment by chrislusf** [comment]
fixed in https://github.com/chrislusf/seaweedfs/commit/22fe4ae573d1e5eef22b6549c08410c59c14b71b
