### ISSUE TITLE
no fid

### ISSUE THREAD

**Issue by chengshihard** [chrislusf/seaweedfs#1441]
![image](https://user-images.githubusercontent.com/13564095/91791233-312aab80-ec45-11ea-8857-7ffd2c8c80f1.png)
![image](https://user-images.githubusercontent.com/13564095/91791246-3ab41380-ec45-11ea-9dbc-168555d0c8cc.png)
![image](https://user-images.githubusercontent.com/13564095/91791264-469fd580-ec45-11ea-95d1-0fa87babeca4.png)

**Comment by chrislusf** [comment]
yes

**Comment by chrislusf** [comment]
There are no file id any more when uploading to filer. File id is a concept of object store, not for file.
