### ISSUE TITLE
windows下通过filer模块上传文件的返回结果没有url和id字段

### ISSUE THREAD

**Issue by dzh592204** [chrislusf/seaweedfs#1442]
你好！
我在windows下使用weedfs; 通过filer模块上传文件后，返回结果如下：
curl -F "filename=@test.txt" "http://172.16.1.79:8888/path/"
结果：{"name":"test.jpg","size":271294}

我之前在linux下使用上面的命令，返回结果的各式包含了fid+url;
     执行成功返回结果如下：
     {"name":"test.txt","size":14,"fid":"4,04ef75710b","url":"http://172.16.1.6:9331/4,04ef75710b"}

是windows下不支持返回fid+url吗？ 还是我的版本或者配置需要修改？

**Comment by chrislusf** [comment]
Not supported any more. Fid is a concept of object store, not for file.

**Comment by dzh592204** [comment]
那我通过filer上传的文件和直接使用master申请id+url上传文件的方式怎么统一起来使用的？ 还是实际应用中这两种方式智能二选一？

**Comment by chrislusf** [comment]
You can only pick one.
