### ISSUE TITLE
Not supported any more. Fid is a concept of object store, not for file.

### ISSUE THREAD

**Issue by dzh592204** [chrislusf/seaweedfs#1443]
那我通过filer上传的文件和直接使用master申请id+url上传文件的方式怎么统一起来使用的？ 还是实际应用中这两种方式只能二选一？
--------------------
Not supported any more. Fid is a concept of object store, not for file.

_Originally posted by @chrislusf in https://github.com/chrislusf/seaweedfs/issues/1442#issuecomment-684576382_

**Comment by chrislusf** [comment]
you can only pick one.
