### ISSUE TITLE
File keys are leftover on Filer Store (redis)

### ISSUE THREAD

**Issue by eth0h4ckr** [chrislusf/seaweedfs#1448]
**Describe the bug**
Files that are deleted via the filer sometimes leave x00 (nill) keys on the filer store (redis). Also, sometimes when performing a directory list, an error will occur stating the file does not exist.

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".

/usr/bin/weed filer --master 127.0.0.1:9333 -collection col1

/usr/bin/weed master -defaultReplication 010 -port 9333 -peers=192.168.1.100:9333,192.168.1.102:9334,192.168.1.104:9335 -
mdir /var/lib/seaweedfs/master -volumeSizeLimitMB 60000

/usr/bin/weed volume -max=0,0 -dataCenter DC1-rack rack1 -dir=/data/d1/seaweedfs,/data/d2/seaweedfs -mserver=192.168.1.100:9333,192.168.1.102:9334,192.168.1.104:9335 -port 5200

- OS version
Ubuntu 16.04.7 LTS

- output of `weed version`
version 8000GB 1.88 b056707 linux amd64

- if using filer, show the content of `filer.toml`
filer.toml has default config

**Expected behavior**
All keys related to file/directory are removed

**Steps to reproduce**
Uploaded file
root@seaweedfs-test1:/var/tmp# curl -T myfile.txt "http://localhost:8888/dir1/myfile.txt"
{"size":12}

Confirmed keys exists in filer store (redis)
192.168.1.100:6379> KEYS "/dir1*"
1) "/dir1"
2) "/dir1\x00"
3) "/dir1/myfile.txt"

list directory to confirm file exists
root@seaweedfs-test1:/home/user# echo "fs.ls /dir1" | weed shell
myfile.txt

delete directory
curl -X DELETE http://localhost:8888/dir1?recursive=true

Check filer store (redis) to see if key exist
192.168.1.100:6379> KEYS "/dir1*"
1) "/dir1\x00"

Nil key for the directory still exists and does not get removed

**Comment by chrislusf** [comment]
Thanks a lot for the issue with so much details! 
I wish every issue is as clear as this!

Added a fix. Thanks!

**Comment by jameno123** [comment]
@chrislusf which every project fixed issues as fast as you do! Keep up the great work.

Is there a command to "clean up" all the previously left behind keys?  (fsck, for example)

Do you suggest for a system with millions (or, 100s of millions) of files and large number of filters to utilize redis as the filestore? or which file store do you recommend for large scale deployments?

**Comment by chrislusf** [comment]
Thanks!

No good way to clean up these keys. 

For large number of files, you can use Cassandra, or similar distributed key value stores.
