### ISSUE TITLE
filer with Elastic v7 metadata store wont start

### ISSUE THREAD

**Issue by ignusws** [chrislusf/seaweedfs#1452]
**Describe the bug**
Filer server wont start with Elastic7 metadata store

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
./weed server -master.port=9333 -volume.port=8880 -dir="/tmp/weed"
./weed filer

elastic was started with command:
docker run -d --name elasticsearch -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" elasticsearch:7.9.1
- OS version
lsb_release -a
No LSB modules are available.
Distributor ID: LinuxMint
Description:    Linux Mint 19.3 Tricia
Release:        19.3
Codename:       tricia

- output of `weed version`
version 30GB 1.93 432fe3d linux amd64
- if using filer, show the content of `filer.toml`
```
[elastic7]
enabled = true
servers = "http://127.0.0.1:9200"
# increase the value is recommend, be sure the value in Elastic is greater or equal here
index.max_result_window = 10000
```

**Expected behavior**
filer server should start

**logs from filer server**
```
./weed filer
I0908 01:24:22 14055 elastic_store.go:59] filer store elastic endpoints: http://127.0.0.1:9200, index.max_result_window:10000
F0908 01:24:23 14055 filer.go:101] read filer.store.id= : filer: no entry is found in filer store
goroutine 1 [running]:
github.com/chrislusf/seaweedfs/weed/glog.stacks(0xc000473f00, 0xc00013c460, 0x62, 0xd3)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:767 +0xb8
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).output(0x34a41a0, 0xc000000003, 0xc00046e230, 0x33d4cd8, 0x8, 0x65, 0x0)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:718 +0x351
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).printf(0x34a41a0, 0x3, 0x1ef680f, 0xf, 0xc00044b760, 0x3, 0x3)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:656 +0x14b
github.com/chrislusf/seaweedfs/weed/glog.Fatalf(...)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:1149
github.com/chrislusf/seaweedfs/weed/filer.(*Filer).setOrLoadFilerStoreSignature(0xc0006fc000, 0x2464e40, 0xc000413670)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/filer/filer.go:101 +0x4f4
github.com/chrislusf/seaweedfs/weed/filer.(*Filer).SetStore(0xc0006fc000, 0x2464e40, 0xc000413670)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/filer/filer.go:83 +0x68
github.com/chrislusf/seaweedfs/weed/filer.(*Filer).LoadConfiguration(0xc0006fc000, 0xc0000ec000)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/filer/configuration.go:24 +0x2f5
github.com/chrislusf/seaweedfs/weed/server.NewFilerServer(0xc00041b2c0, 0xc00041b2c0, 0xc0006f6000, 0x1, 0x0, 0x0)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/server/filer_server.go:111 +0x792
github.com/chrislusf/seaweedfs/weed/command.(*FilerOptions).startFiler(0x34a3d80)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/command/filer.go:111 +0x2b3
github.com/chrislusf/seaweedfs/weed/command.runFiler(0x348c280, 0xc00000c0b0, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/command/filer.go:87 +0x4b
main.main()
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/weed.go:66 +0x2f9
```

Same error with our test Elastic cluster with basic auth enabled (i recompiled binary and added additional settings for this to test)

And, as a suggestion. Maybe add more configuration parameters? there are plenty https://github.com/olivere/elastic/wiki/Configuration but most basic and useful:
username and password for basic auth
`elastic.SetBasicAuth("username", "password")`
ability to add more then one server.
`elastic.SetURL("http://10.0.1.1:9200", "http://10.0.1.2:9200")`
ability to change Healthcheck (right now it hardcoded as disabled)
`elastic.SetHealthcheck(enable)`

**Comment by chrislusf** [comment]
Thanks for reporting! I do not really have an ES setup. Please help to add the configurations.

All logic is in https://github.com/chrislusf/seaweedfs/tree/master/weed/filer/elastic/v7

**Comment by chrislusf** [comment]
@taozix added https://github.com/chrislusf/seaweedfs/pull/1455 with more options.
