### ISSUE TITLE
Can we seaweed be deployed more simple

### ISSUE THREAD

**Issue by taozix** [chrislusf/seaweedfs#1453]
Hi, in productive,weed need another etcd-cluster to generate sequence number which based on raft, and weed master is also implemented with raft, can weed generate numbers only using master.

**Comment by chrislusf** [comment]
There is only one raft. Where is the other etcd cluster?

**Comment by taozix** [comment]
two ways to generate seq-number, one is memory which has no data persistent, other is etcd, so need other etcd cluster ahead of deploying seaweed?

**Comment by chrislusf** [comment]
SeaweedFS does not need Etcd cluster. Where did you see the opposite?

**Comment by taozix** [comment]
[master.sequencer]
type = "etcd"     # Choose [memory|etcd] type for storing the file id sequence
# when sequencer.type = etcd, set listen client urls of etcd cluster that store file id sequence
# example : http://127.0.0.1:2379,http://127.0.0.1:2389
sequencer_etcd_urls = "http://127.0.0.1:2379"

**Comment by chrislusf** [comment]
I see. This is optional.

**Comment by taozix** [comment]
If choose memory to record the seq-number, will cause seq-number count from zero again after node restart？thanks.

**Comment by chrislusf** [comment]
No

**Comment by taozix** [comment]
i think file-key will restart from zero if using memory sequence generate, but it's also maybe ok because fid contains random file cookie.

**Comment by chrislusf** [comment]
no. the sequence number is already maintained by masters.
