### ISSUE TITLE
How about changing 301 to 308 on redirect to volume servers

### ISSUE THREAD

**Issue by lotsofone** [chrislusf/seaweedfs#1454]
it's okay to simply write code to get file from master in golang, the request will be redirected to the corresponding volume.
But not okay when deleting file, go request will automatically change method to GET:
https://github.com/golang/go/issues/21469
If it's 308, method won't be changed.

**Comment by chrislusf** [comment]
Is this specific to Go?

**Comment by chrislusf** [comment]
Changed. Thanks for the suggestion!
