### ISSUE TITLE
ListParts 

### ISSUE THREAD

**Issue by lxy-lxy98** [chrislusf/seaweedfs#1461]
version:1.90
起了一个seaweedfs的server,当Client端发起一个ListParts的请求时，server可以接收到请求但是不能将响应中的Parts字段 返回给Client

#1432 listPartOutputParts [{
  ETag: "\"d7e02d037f566a94069d42f3424a5184\"",
  LastModified: 2020-09-11 07:58:54 +0000 UTC,
  PartNumber: 1,
  Size: 5242880
} {
  ETag: "\"19516d404b818722bdb3534350f50053\"",
  LastModified: 2020-09-11 07:58:54 +0000 UTC,
  PartNumber: 2,
  Size: 5242880
} {
  ETag: "\"21e6e1deb3b4af85a92b3d4bb5fd190f\"",
  LastModified: 2020-09-11 07:58:55 +0000 UTC,
  PartNumber: 3,
  Size: 5242880
}]
比如这个可以在seaweedfs的Server展示出来但是  Client得不到这个字段的结果

**Comment by chrislusf** [comment]
no idea how to reproduce it.

**Comment by lxy-lxy98** [comment]
分片上传时
client调用ListParts()接口，得不到各个分片结果

**Comment by chrislusf** [comment]
no idea how to reproduce it. Please be specific with exact commands.

**Comment by chrislusf** [comment]
Please create issues as detailed as https://github.com/chrislusf/seaweedfs/issues/1448

**Comment by lze693** [comment]
我也遇到了 就是s3接口少了个 您只有
// Multipart upload operations
* NewMultipartUpload
* CompleteMultipartUpload
* AbortMultipartUpload
* ListMultipartUploads
* CopyObjectPart
少了ListParts接口(ListParts接口用于列举指定Upload ID所属的所有已经上传成功Part。用来判断分片是否上传)

**Comment by chrislusf** [comment]
@lze693 Thanks! A bit clearer now. At least I know this is about S3 client, not filer. But still, words are not enough. Please show me some code.

The `ListObjectParts` is implemented here: https://github.com/chrislusf/seaweedfs/blob/master/weed/s3api/s3api_server.go#L67

**Comment by chrislusf** [comment]
Added a fix! Thanks for reporting!

**Comment by lze693** [comment]
哥们等你发布哦

**Comment by lze693** [comment]
好的谢了 看您啥时候发布一下呢！

**Comment by chrislusf** [comment]
1.98 has this fix.

**Comment by lze693** [comment]
好的 谢谢大佬 有其他问题我再向您反馈

**Comment by lxy-lxy98** [comment]
谢谢您
