### ISSUE TITLE
Append only operation

### ISSUE THREAD

**Issue by hyprnick** [chrislusf/seaweedfs#1464]
Does your file system support appending to an existing file rather than uploading the whole file each time?

**Comment by chrislusf** [comment]
There is a grpc filer API for that. 
https://github.com/chrislusf/seaweedfs/blob/master/weed/pb/filer.proto#L25

Do you have any suggestion for a simpler API?

**Comment by hyprnick** [comment]
Thanks for the quick reply! I’ll have to check that out. I was only looking at the HTTP api. Not sure if that would be easy to add. 

We’re looking for a way to have a file system on kubernetes that allows for one writer many readers.

**Comment by chrislusf** [comment]
http API is easy to add. I need to find a conventional way to design the API.

**Comment by hyprnick** [comment]
Great work on this file system. The gRPC is plenty for us to test with.

**Comment by chrislusf** [comment]
I am interested to know what you are trying to build. Maybe the feature can be part of the file system.\

**Comment by hyprnick** [comment]
We were looking for an easier approach to distribute lots of data with low network usage:  https://www.hyprcubd.com/

**Comment by hyprnick** [comment]
Not much out there for WORM support (Write Once Read Many).  You have to move to RWX volumes in Kubernetes to get this and it's implemented using NFS which is far too slow.
