### ISSUE TITLE
Show progress to upload file by filer

### ISSUE THREAD

**Issue by fixNoobi** [chrislusf/seaweedfs#1466]
Hi,

On the old version, we are seed progress to upload file by filer, but now didn't seen from browser (chrome)

**Comment by chrislusf** [comment]
I don’t remember SeaweedFS filer UI has this feature before.

**Comment by fixNoobi** [comment]
I don't remember version seaweed, but when upload file on UI filer, browser show progress upload files.
Like this 
![image](https://user-images.githubusercontent.com/5132426/93021882-26312d00-f5ee-11ea-93a4-93cf8949c7d1.png)

**Comment by chrislusf** [comment]
Seems a feature of the browser
