### ISSUE TITLE
HDFS Client does not respect chunk sizes when writing to filer.

### ISSUE THREAD

**Issue by eth0h4ckr** [chrislusf/seaweedfs#1467]
**Describe the bug**
When writing data to seaweedfs from the hdfs, it seems the hdfs client does not respect the default chunk size or any manually defined chunk size on the filer. 

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
/usr/bin/weed volume -dataCenter DC1 -rack rack1 -dir=/var/lib/hadoop-hdfs/dn/seaweedfs -mserver 192.168.250.192:9333 -port 5200
/usr/bin/weed filer --master 192.168.250.192:9333 -collection col1 -maxMB 128
/usr/bin/weed master -ip 192.168.250.192 -port 9333 -mdir /var/lib/seaweedfs/master -volumeSizeLimitMB 20000 -volumePreallocate

- OS version
Ubuntu 16.04.6 LTS

- output of `weed version`
version 8000GB 1.88 b056707 linux amd64

- if using filer, show the content of `filer.toml`
Defaults

**Expected behavior**
When writing to seaweed from the hdfs client, the file chunks should respect what is defined on the filer

**Example Commands and output**
Example file is 315MB

Upload test file to filer via curl
`curl -T file1 "http://localhost:8888/test/file1"`

Show metadata for newly uploaded file
` echo "fs.meta.cat /test/file1" | weed shell | grep size`
"size": "134217728",
 size": "134217728",
 size": "61634848",

Delete File
`curl -X DELETE "http://localhost:8888/test/file1"`

Copy from hdfs to seaweedfs using hdfs client
` hdfs dfs -copyFromLocal file1 seaweedfs://127.0.0.1:8888/test/file1`

Show metadata for newly uploaded file
`echo "fs.meta.cat /test/file1" | weed shell | grep size | wc -l`
664

So it seems like random sizes. Example output below.

      "size": "4128768",
      "size": "4136960",
      "size": "4104192",
      "size": "4145152",
      "size": "4112384",
      "size": "4149248",
      "size": "4108288",
      "size": "4112384",
      "size": "4120576",
      "size": "4120576",
      "size": "4096",
      "size": "4096",
      "size": "4096",
      "size": "4096",
      "size": "4096",
      "size": "4096",
      "size": "4096",
      "size": "4096",
      "size": "4096",
      "size": "4096",
      "size": "4096",

**Comment by chrislusf** [comment]
HDFS writes in its own way. You can change it by adding this to the core-site.xml
```
    <property>
       <name>io.file.buffer.size</name>
       <value>4194304</value>
    </property>
```

**Comment by jameno123** [comment]
Ouch... 

Io.file.buffer.size is the size hdfs uses per write but that should not dictate the chunk size for the file in seaweed. That really seems like a bug in the file system implementation utilizing the wrong variable. Does the hdfs client not just write its data to a filter which should then split the file based on the chunk size? If not then there should be a fs.seaweed.chunk.size value. Basing the chunk size on a global write buffer size can cause serious performance impacts elsewhere in the hdfs stack. There's no way our hapoop engineers are going to allow us to change that value due to those impacts but seaweed is negatively being affected as a result. Trying to find side middle ground.

Is there anyway to add a property that the client will utilize instead of using that hdfs global?

**Comment by eth0h4ckr** [comment]
Just in case anyone runs into this issue I believe I have found the solution. You can define the value using the -D option without changing it globally. This will store the file in 128MB chunks in seaweedfs.

hdfs dfs -D "io.file.buffer.size=134217728" -copyFromLocal file1 seaweedfs://127.0.0.1:8888/

**Comment by chrislusf** [comment]
@jameno123 Thanks for the suggestion! 
@eth0h4ckr Thanks for confirming it.

Updated the jar to 1.4.7.

Now you can use this to adjust the buffer size. 4MB should be a good number. Most likely you do not need to.
```
    <property>
       <name>fs.seaweed.buffer.size</name>
       <value>4194304</value>
    </property>
```

If anyone found the number should be adjusted, please share your performance numbers.

**Comment by chrislusf** [comment]
Anyone wants to run Spark/Hadoop jobs on SeaweedFS? 

This change greatly improved the performance SeaweedFS on Hadoop. One user noticed dramatic performance improvements compared to same spark job on HDFS. 

I would like to have other independent tests to confirm.
