### ISSUE TITLE
master和volume分开部署时空指针的bug

### ISSUE THREAD

**Issue by jamsonzan** [chrislusf/seaweedfs#1469]
hello~

volume启动时：
func NewVolumeServer() {
        vs.store = storage.NewStore()
    	go vs.heartbeat()
}

如果重启时有s3的文件，storage.NewStore()会调用LoadRemoteFiles()，LoadRemoteFiles会使用BackendStorages。

但是BackendStorages是在vs.heartbeat()初始化的，就会panic。

https://github.com/chrislusf/seaweedfs/blob/10f908152682216189941f6b432ede8909c266b4/weed/storage/volume_tier.go#L40

**Comment by chrislusf** [comment]
Aha! That is an embarrassing bug! Thanks for the analysis!

**Comment by chrislusf** [comment]
I added a fix. Let me know if it works for you.

**Comment by jamsonzan** [comment]
> I added a fix. Let me know if it works for you.

nice! it work.
