### ISSUE TITLE
Filer ip bind

### ISSUE THREAD

**Issue by joegh556** [chrislusf/seaweedfs#1470]
I install weed in a server with external IP. I want to set up weed as a internal service. So I use -ip.bind in master, volume and filer bind to internal IP.

**Describe the bug**
It worked with master, volume and filer port 8888, but not works with port 18888. It still bind to 0.0.0.0

**System Setup**
- Debian 9
- weed version 1.99

**Comment by chrislusf** [comment]
Thanks for the bug report! Added a fix.
