### ISSUE TITLE
Too many file handles

### ISSUE THREAD

**Issue by bboxzhen** [chrislusf/seaweedfs#1471]
**Describe the bug**
I don't know why the new version will report this error

**System Setup**
- /opt/seaweedfs_files/weed filer  -master=seaweedfs:9333 -ip=seaweedfs -port=8889 -defaultReplicaPlacement="010"
- OS version
- version 8000GB 1.94 c18ea21 linux amd64
- [mongodb]
enabled = true
uri = "mongodb://my:2019@localhost.com:27017/?appName=seaweedfs"
option_pool_size = 0
database = "seaweedfs_filemeta"

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/39783629/93551359-3b1c1080-f9a0-11ea-8c45-618b3404daf4.png)
![image](https://user-images.githubusercontent.com/39783629/93551634-f0e75f00-f9a0-11ea-886a-bf4a2a4c15ff.png)

![image](https://user-images.githubusercontent.com/39783629/93551575-ceeddc80-f9a0-11ea-9f65-7e320cbe2e13.png)

**Comment by chrislusf** [comment]
It is a code bug. Added a fix for this.
