### ISSUE TITLE
weed mount  , try cp a large  file  over 4G  then very slow

### ISSUE THREAD

**Issue by caihexin** [chrislusf/seaweedfs#1476]
![图片](https://user-images.githubusercontent.com/13762872/93841632-c78f4180-fcc6-11ea-959f-50b8ac711d88.png)

compare

![图片](https://user-images.githubusercontent.com/13762872/93841657-e261b600-fcc6-11ea-95e5-fc12c4c9edad.png)

put a large file to weed store (cp or wget file to weed fuse store )   ,use weed mount very very slow, but use  weed filer.copy  quick.

**Comment by chrislusf** [comment]
so use `weed filer.copy`?

the `weed mount` is operated by the OS and is single threaded.

**Comment by caihexin** [comment]
weed filer.copy  of course very good ,weed mount  More places to use .    but now this service copy instable，

Can it be improved

**Comment by chrislusf** [comment]
This is fixed in 2.03.

**Comment by caihexin** [comment]
weed version
version 30GB 1.88 b056707 linux amd64


TEST: 
- net work use 10G speed
- copy file size 23G Nov 27 10:46 bk_cmdb1947.img
- command : 
weed mount -filer=192.168.19.20:8888 -dir=/mnt/weedstore
cp  /ywstore/vm/bk_cmdb1947.img   .

 
This is SeaweedFS version 30GB 1.88 b056707 linux amd64
mount point owner uid=0 gid=0 mode=drwxr-xr-x
current uid=0 gid=0
--begin
I1127 10:25:34 39287 volume_create_linux.go:19] Preallocated 65011712 bytes disk space for /tmp/2rNO/c0_1_0.dat
I1127 10:25:34 39287 chunk_cache_on_disk.go:66] loading leveldb /tmp/2rNO/c0_1_0.ldb
--end
I1127 10:46:31 39287 volume_create_linux.go:19] Preallocated 131072000 bytes disk space for /tmp/2rNO/cache_3.dat
I1127 10:46:31 39287 chunk_cache_on_disk.go:66] loading leveldb /tmp/2rNO/cache_3.ldb

--result


use weed mount , very very slow .   Can copy speed be increased?

**Comment by chrislusf** [comment]
yes. User 2.03 or later.

**Comment by caihexin** [comment]
Thank
