### ISSUE TITLE
can I restore the deleted bucket?

### ISSUE THREAD

**Issue by FrankYu** [chrislusf/seaweedfs#1478]
Hi, I have a three nodes cluster, 5 ssd disks per node.
I deleted some buckets for mistake, can I restore those buckets?  how can I restore them?
according https://github.com/chrislusf/seaweedfs#solid-state-disk, the deleted file hole should be still exist?

thanks

**Comment by FrankYu** [comment]
@chrislusf  @chrisluuber 
Hi Chris, can you give some advices?

**Comment by chrislusf** [comment]
Can not restore buckets.
