### ISSUE TITLE
ip binding issue with submitFromMasterServerHandler

### ISSUE THREAD

**Issue by hankya** [chrislusf/seaweedfs#148]
My setup is to have master server listen on only an internal ip address (10.0.0.3), When i use the submit api of the master, the master is trying to post to localhost:9333 for file id assignment, however, the server is not listening on localhost, hence it failed.

I looked at following code, and I wonder why don't we use the host properties coming from the request?

I want to propose following change
```golang
+              submitForClientHandler(w, r, "localhost:"+strconv.Itoa(ms.port))
-              submitForClientHandler(w, r, r.Host)
```

**Comment by chrislusf** [comment]
Please send a pull request for this. Also, need to deal with that r.Host is optionally empty.
