### ISSUE TITLE
How do we usually clean up dangling file ids?

### ISSUE THREAD

**Issue by lotsofone** [chrislusf/seaweedfs#1484]
My seaweedfs has many writes and deletions every day, and I use mysql to keep up those file ids.
Sometimes the deletion on seaweedfs fails. Sometimes it fails to write to db for newly created fid. After a long time, the fs may have many dangling fids.
I considered weed export. But if a file was uploaded by `weed upload` and splited into chunks, it will have many fids, and they will also be exported. Of course these fids of data chunks should not be deleted even if they don't appear in my db.
How do we usually handle this problem if running a big seaweedfs?

**Comment by chrislusf** [comment]
it has to be a multi-stage process. 
1) Scan volume file, similar to how `weed export` is implemented, to collect the chunk manifests and normal chunks.
2) Collect all chunks that are in your mysql. Resolve the chunk manifests.
3) Find out what chunks are not used.

**Comment by lotsofone** [comment]
Normal file chunk and splited data chunk looks same. So there is no way to tell what kind of chunk it is if we scaned a chunk unless we found another manifest pointing to it, right?

**Comment by chrislusf** [comment]
a needle has a flag for manifest. Just need to expose it when `weed export`
```
func (n *Needle) IsChunkedManifest() bool {
	return n.Flags&FlagIsChunkManifest > 0
}
```

**Comment by lotsofone** [comment]
Yes this FlagIsChunkManifest tell us whether it is a manifest.
If an fid is not a manifest, there are still two cases:
1. It could be a file that belong to a user and should appear in my db. Should be deleted if not exists in my db.
2. It could be a data chunk which is part of a big file. It should appear in one manifest. Should not be deleted if not exists in my db.
If some flag can tell which case it is, the clean up job can be parallel, we just need to scan one volume file to know what fids should be deleted in this volume. Otherwise we have to scan all volumes to make sure one fid doesn't exists in any other manifests.

**Comment by chrislusf** [comment]
Collect all the info in parallel, do the math, and then delete in parallel.
