### ISSUE TITLE
Suggestion: use etcd for distributed filer

### ISSUE THREAD

**Issue by davistan** [chrislusf/seaweedfs#149]
Hi, perhaps you may want to use https://github.com/coreos/etcd instead of redis?

**Comment by chrislusf** [comment]
I feel it is mostly for shared configurations, not for storing large number of files.

Seaweedfs is already using the same raft protocol as etcd for shared master cluster leader election.

**Comment by davistan** [comment]
Yes. That’s what I noticed, there are many similarities.
Perhaps weedfs can borrow some codes for distributed storage on raft to be used for filer.

Thanks.
