### ISSUE TITLE
When filer has invalid UTF-8 filename, volume.fsck happen error.

### ISSUE THREAD

**Issue by zjzdy** [chrislusf/seaweedfs#1493]
**Describe the bug**
When filer has invalid UTF-8 filename, volume.fsck happen error.

Error Output:
error: failed to collect file ids from filer: rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8

I debug this, error happen in weed/pb/filer_pb/filer_client_bfs.go:func TraverseBfs 's processErr := processOneDirectory.
The default output info can't known error file. I debug found the error filename url is http://localhost:8888/xxxx/%BB%E6%BB%AD%D7%E9:0%D5%C5%E3%E5%D7%D 3%BE%B4.jpg
I don't know why i can download it and chrome can parse a good filename (绘画组_0张沐子敬.jpg) , but fsck need it is UTF-8.(I know the filename isn't a good utf-8 filename)
Try to print enough error info for error filename, and check filename in upload or not use utf-8 string in grpc.

**System Setup**
version 30GB 2.0 9cac9c4 windows amd64
Windows 10

**Comment by chrislusf** [comment]
works for me. Please show the error stack.

**Comment by zjzdy** [comment]
Now, I don't have http://localhost:8888/xxxx/ folder, I will upload a file to  http://localhost:8888/xxxx/.
This is test command and output (shell env>command format):
```
cmd>curl -F file=@E:\Users\zjzdy\文档\Downloads\绘画组_02172823张沐子敬.jpg  "http://localhost:8888/xxxx/%BB%E6%BB%AD%D7.jpg"
{"name":"\ufffd滭\ufffd\ufffd_02172823\ufffd\ufffd\ufffd\ufffd\ufffdӾ\ufffd.jpg","size":1186688}

weed shell> lock
weed shell> volume.fsck
error: failed to collect file ids from filer: rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8
weed shell>
```
I add it after `err = processErr` and rebuild weed.
```
fmt.Printf("processErr: %v\n", err) 
println(dir)
debug.PrintStack()
```
The output is:
```
> lock
> volume.fsck
processErr: rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8
/xxxx
goroutine 356 [running]:
runtime/debug.Stack(0x141c6be2d, 0x1, 0x1)
        c:/go/src/runtime/debug/stack.go:24 +0xa4
runtime/debug.PrintStack()
        c:/go/src/runtime/debug/stack.go:16 +0x29
github.com/chrislusf/seaweedfs/weed/pb/filer_pb.TraverseBfs.func1(0xc00050e8c8, 0xc000234f30, 0x1421909e0, 0xc000506600, 0xc00050e8d0, 0xc0000220c0, 0xc00028d2c0)
        S:/weed/seaweedfs/weed/pb/filer_pb/filer_client_bfs.go:39 +0x190
created by github.com/chrislusf/seaweedfs/weed/pb/filer_pb.TraverseBfs
        S:/weed/seaweedfs/weed/pb/filer_pb/filer_client_bfs.go:23 +0x14b
error: failed to collect file ids from filer: rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8
>
```
Chrome show:
![20200926141755](https://user-images.githubusercontent.com/10596496/94331948-5d96d500-0003-11eb-9f6a-1760fbbaca1c.png)

**Comment by zjzdy** [comment]
And the call stack like:
```
command_volume_fsck.go's collectFilerFileIds ->
collectFilerFileIds's return doTraverseBfsAndSaving ->
command_fs_meta_save.go's doTraverseBfsAndSaving ->
doTraverseBfsAndSaving 's filer_pb.TraverseBfs ->
filer_client_bfs.go's TraverseBfs->
TraverseBfs's processOneDirectory
```
I don't track processOneDirectory's ReadDirAllEntries error, because i know which file has error  and we can delete the file from weed.

**Comment by chrislusf** [comment]
Hi, I added a fix to prevent invalid utf-8 characters in a file name.
