### ISSUE TITLE
Configurable erasure coded shards

### ISSUE THREAD

**Issue by Gronis** [chrislusf/seaweedfs#1496]
Right now, erasure coding is hard coded to use 10 data shards and 4 parity shards. It says in the wiki that this can easily be changed in the code.

I think this should be a setting configurable, similar to how replication settings are configurable. To recompile the code should not be needed to change this. Also if you use something like the docker image, this is even more painful since the docker image now uses pre-built binaries from github directly.

Is it possible to make this a setting? It seams like a small and easy change to save some headache.

**Comment by chrislusf** [comment]
what EC config you want to use?

**Comment by Gronis** [comment]
I only have a few machines and I don’t want the data to be unavailable if one of the machines goes offline. So maybe 10,5 or 10,6 for higher availability. I guess I still haven’t thought that part out entirely yet. I still need to do some testing to see what configurations work well.

I want to run with three machines with 3-4 disks each with roughly the same capacity on each disk. If one entire server is offline, all data should still be available. I could increase it to 4 machines, then 10,4 should be enough, but I rather don’t want to do that at this point in time.

**Comment by Gronis** [comment]
Or maybe it is more efficient to do 8,4. I don’t know. But I probably want around 30-40% of EC volumes to be “redundant” data

**Comment by Gronis** [comment]
I guess for larger installations like a data center, there is no reason to change this setting since you probably have tens or hundreds of machines. But for smaller installations like the one I’m working on, it makes sense I think.

**Comment by chrislusf** [comment]
I have not tested EC config other than 10.4. 

Later we can create separate build similar to large_disk for additional variations.

**Comment by Gronis** [comment]
Is there a reason it cannot be configured at runtime? Does it improve performance to know this at build time, or is it more work to make it a runtime configurable variable. Or is it simply undesirable to have this configurable at runtime?

**Comment by chrislusf** [comment]
> is it more work to make it a runtime configurable variable

yes
