### ISSUE TITLE
seaweadfs with nginx proxy achieve a port, different paths point to different weed filer servers  ?

### ISSUE THREAD

**Issue by caihexin** [chrislusf/seaweedfs#1498]
seaweedfs ,can use ngnix proxy ,To achieve a port, different paths point to different weed filer servers  ? case:

       location /w1 {
            client_max_body_size 5000m;
            proxy_pass http://172.16.0.11:8888/;

        }
        location /w2 {
            client_max_body_size 5000m;
            proxy_pass http://172.16.0.166:8888/;
         }

above  case   configuration must be wrong。

Is there any other plan ？？？

**Comment by chrislusf** [comment]
Not clear what you want. You can use Chinese here.

**Comment by caihexin** [comment]
目标例如使用10080端口，通过不同代理路径访问后台多个不同weed filer服务器,最终实现:
1、http://192.168.0.11:10080/w1 能够成功访问 http://172.16.0.11:8888
2、http://192.168.0.11:10080/w2 能够成功访问 http://172.16.0.1666:8888
我明白这个设置是nginx与seaweedfs配合问题. 但nginx只有这些设置，而我们在其它项目也有类似
问题，后来都是改的我们的项目配置才实现。而seaweedfs我没有找到工程访问对应配置路径。

   location /w1 {
        client_max_body_size 5000m;
        proxy_pass http://172.16.0.11:8888/;

    }
    location /w2 {
        client_max_body_size 5000m;
        proxy_pass http://172.16.0.166:8888/;
     }
