### ISSUE TITLE
S3 identities/credentials store in filer

### ISSUE THREAD

**Issue by kmlebedev** [chrislusf/seaweedfs#1500]
We use s3 credentials per buckets 
We want to create credentials on the fly through API without reloading `weed s3`

**Comment by chrislusf** [comment]
need to have a place to store the credentials though.

**Comment by ddorian** [comment]
Store the credentials in the filer store ?
Just another table.

**Comment by chrislusf** [comment]
I am leaning to storing the credentials in the filer as an encrypted file, e.g. `/buckets/s3.config`, only readable by weed s3  with a master key.

**Comment by ddorian** [comment]
Because buckets are stored in different collections, hence different volumes, there is high overhead to have a big number of  variable size buckets (10K+ buckets).

Hence there is no need to have scalable credential storage.

**Comment by kmlebedev** [comment]
Example https://github.com/chrislusf/seaweedfs/commit/2dcc178d0ae20a013a901e4b4472dc9d8843ba59

**Comment by kmlebedev** [comment]
@chrislusf I started to do a little
See at this  and I will move on
https://github.com/kmlebedev/seaweedfs/commit/e1190b3224638616cf4e1318ddcba0b1575f2130

**Comment by chrislusf** [comment]
What's the expected process to change the s3 credentials?

**Comment by kmlebedev** [comment]
> What's the expected process to change the s3 credentials?

I have not decided.
If process to change is through the s3 api server, then it seems the handlers are needed on a separate port. And with changes call function save to fller.
Or process to change is through the filer api server, but you need to notify s3 api server about the changes

**Comment by taozix** [comment]
just like radosgw？a new non-standard s3 api for user manage.

**Comment by chrislusf** [comment]
> just like radosgw？a new non-standard s3 api for user manage.

Can you show some doc on how radosgw handles this?

**Comment by taozix** [comment]
> > just like radosgw？a new non-standard s3 api for user manage.
> 
> Can you show some doc on how radosgw handles this?

https://docs.ceph.com/en/latest/radosgw/adminops/#
radosgw split the user permission into two parts,
1.permission for S3 bucket/object
2.capability for creating other user

**Comment by chrislusf** [comment]
Cool. Btw: do you know whether they support multiple s3 gateway instances? Does it take some time to sync the user management updates to all the s3 gateway instances?

**Comment by taozix** [comment]
> Cool. Btw: do you know whether they support multiple s3 gateway instances? Does it take some time to sync the user management updates to all the s3 gateway instances?

support multiple s3 gateway instances.
no, user's info is store as a rados object and rados object support watch mechanism, I think any rgw instances can watch updates.

**Comment by chrislusf** [comment]
Great! SeaweedFS also can subscribe to metadata changes and we can use that too. Good that I asked. Didn't think of it before. Thanks a lot!

**Comment by taozix** [comment]
not sure rgw use watch or read user info from rados for every s3 api. maybe "watch" is better.

**Comment by chrislusf** [comment]
The changes are checked in now.
