### ISSUE TITLE
new bucket/collection will get duplicate match volume:max_idx

### ISSUE THREAD

**Issue by kmlebedev** [chrislusf/seaweedfs#1503]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs
Report issues here. Ask questions here https://stackoverflow.com/questions/tagged/seaweedfs

**Describe the bug**
new bucket/collection will get duplicate volume:max_idx
If creating new bucket/collection after master leader loses volume topology(restart master pods for image version update in k8s) until start volume with max volume file id

**System Setup**
`make cluster`

**Expected behavior**
max volume idx in persistent store maybe in raft

**Commands**
1.  Start dev cluster from [local-cluster-compose.yml ](https://gist.github.com/kmlebedev/11f0176fc1e6a38015b28541e9e26ecb)
`docker-compose -f local-cluster-compose.yml -p seaweedfs up`
2.  Make buckets and write file
`for idx in {1..3}; do aws --endpoint-url http://localhost:8333 s3 mb s3://newbucket${idx} && openssl rand -hex 1000 | aws --endpoint-url http://localhost:8333 s3 cp - s3://newbucket${idx}/file${idx}; done`
3. Show volumes id
```echo volume.list | darwin/weed/weed shell
Topology volume:22/134 active:22 free:112 remote:0 volumeSizeLimit:1024 MB
  DataCenter DefaultDataCenter volume:22/134 active:22 free:112 remote:0
    Rack DefaultRack volume:22/134 active:22 free:112 remote:0
      DataNode volume0:8080 volume:6/30 active:6 free:24 remote:0
        volume id:3 size:8 collection:"newbucket1" version:3 modified_at_second:1601632468 
        volume id:10 size:8 collection:"newbucket2" version:3 modified_at_second:1601632469 
        volume id:12 size:8 collection:"newbucket2" version:3 modified_at_second:1601632469 
        volume id:18 size:8 collection:"newbucket3" version:3 modified_at_second:1601632470 
        volume id:20 size:8 collection:"newbucket3" version:3 modified_at_second:1601632470 
        volume id:21 size:8 collection:"newbucket3" version:3 modified_at_second:1601632470 
      DataNode volume0:8080 total size:48 file_count:0 
      DataNode volume1:8081 volume:8/52 active:8 free:44 remote:0
        volume id:4 size:8 collection:"newbucket1" version:3 modified_at_second:1601632468 
        volume id:5 size:8 collection:"newbucket1" version:3 modified_at_second:1601632468 
        volume id:6 size:1128 collection:"newbucket1" file_count:1 version:3 modified_at_second:1601632468 
        volume id:11 size:8 collection:"newbucket2" version:3 modified_at_second:1601632469 
        volume id:13 size:8 collection:"newbucket2" version:3 modified_at_second:1601632469 
        volume id:17 size:8 collection:"newbucket3" version:3 modified_at_second:1601632470 
        volume id:19 size:8 collection:"newbucket3" version:3 modified_at_second:1601632470 
        volume id:22 size:792 file_count:2 version:3 modified_at_second:1601632554 
      DataNode volume1:8081 total size:1968 file_count:3 
      DataNode volume2:8082 volume:8/52 active:8 free:44 remote:0
        volume id:1 size:8 collection:"newbucket1" version:3 modified_at_second:1601632468 
        volume id:2 size:8 collection:"newbucket1" version:3 modified_at_second:1601632468 
        volume id:7 size:8 collection:"newbucket1" version:3 modified_at_second:1601632468 
        volume id:8 size:1136 collection:"newbucket2" file_count:1 version:3 modified_at_second:1601632469 
        volume id:9 size:8 collection:"newbucket2" version:3 modified_at_second:1601632469 
        volume id:14 size:8 collection:"newbucket2" version:3 modified_at_second:1601632469 
        volume id:15 size:1136 collection:"newbucket3" file_count:1 version:3 modified_at_second:1601632470 
        volume id:16 size:8 collection:"newbucket3" version:3 modified_at_second:1601632470 
      DataNode volume2:8082 total size:2320 file_count:2 
    Rack DefaultRack total size:4336 file_count:5 
  DataCenter DefaultDataCenter total size:4336 file_count:5 
total size:4336 file_count:5 
```
4. Stop volume1 with max volume id:22 and masters restart
```
docker stop seaweedfs_volume1_1
docker restart seaweedfs_master0_1 seaweedfs_master1_1 seaweedfs_master2_1
```

5. Create new bucket
`
idx=4; aws --endpoint-url http://localhost:8333 s3 mb s3://newbucket${idx} && openssl rand -hex 1000 | aws --endpoint-url http://localhost:8333 s3 cp - s3://newbucket${idx}/file${idx}
` 
6. Start volmum1
`
docker start seaweedfs_volume1_1
`
7. Get duplicate  volume id:22
```
echo volume.list | darwin/weed/weed shell | grep -e id:22 -e 'DataNode.*remote'
      DataNode volume0:8080 volume:9/30 active:9 free:21 remote:0
        volume id:22 size:1136 collection:"newbucket4" file_count:1 version:3 modified_at_second:1601633467 
      DataNode volume1:8081 volume:8/22 active:8 free:14 remote:0
        volume id:22 size:792 file_count:2 version:3 modified_at_second:1601632554 
      DataNode volume2:8082 volume:13/52 active:13 free:39 remote:0
```

**Comment by ustuzhanin** [comment]
I`m try repair this problem...
start of problem in three lines of code:
https://github.com/chrislusf/seaweedfs/blob/master/weed/server/raft_server.go#L50

Second problem - ignore error in marshal:
https://github.com/chrislusf/raft/blob/master/server.go#L1460
Need fix marshla rules for Peer struct

Third problem - not create and load snapshot of raft state

I don't think it's a good idea to keep fixing fork of archived project.
Please choose what you like more for implementation of raft protocol:
https://github.com/etcd-io/etcd/tree/master/raft
https://github.com/hashicorp/raft

and i start work for changes

**Comment by chrislusf** [comment]
this should have been resolved by PR from @ustuzhanin
