### ISSUE TITLE
Unexpected leader-role failover with multiple masters

### ISSUE THREAD

**Issue by zehweh** [chrislusf/seaweedfs#1509]
Hi, me again

**Describe the bug**
I run 3 seaweed masters in kubernetes - let's call them: seaweedfs-master-0, seaweedfs-master-1, seaweedfs-master-2
They form a cluster where seaweedfs-master-0 is the leader. If I restart seaweedfs-master-0, the leader role switches to - let's say seaweedfs-master-1.
If I restart seaweedfs-master-0 again, the leader role switches from seaweedfs-master-1 to seaweedfs-master-2. 

**Expected behavior**
I expect that the leader role stays with the current, healthy master.

**System Setup**
- Docker-Image: chrislusf/seaweedfs:2.03 (same issue on previous versions)
- kubernetes 1.18 running containerd 1.2.13

**How to reproduce**
```bash 
# Reproducing this in minikube requires the installation of a CNI with e.g. flannel.

# Start a fresh minikube:
minikube start --driver=virtualbox --network-plugin=cni --cni=bridge --extra-config=kubeadm.pod-network-cidr=10.244.0.0/16

# Install flannel 
kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

# Install seaweed masters using the attached manifest
kubectl apply -f seaweed.txt

# It is a good idea to follow the logs on seaweedfs-master-1 & seaweedfs-master-2 in separate terminals to see the leader election
# kubectl -n seaweed-test logs seaweedfs-master-1 -f
# kubectl -n seaweed-test logs seaweedfs-master-2 -f

# Also, you can monitor the current leader
# kubectl -n seaweed-test exec -it seaweedfs-master-2 -- apk add curl
# kubectl -n seaweed-test exec -it seaweedfs-master-2 -- curl -s http://seaweedfs-master.seaweed-test:9333|grep master

# Now, seaweedfs-master-0 is probably the leader. Delete it with
kubectl -n seaweed-test delete pod seaweedfs-master-0

# The leader role switches to one of the other masters
# If you delete seaweedfs-master-0 again, the role switches again
kubectl -n seaweed-test delete pod seaweedfs-master-0

```

** Additional context **

I was not able to reproduce this without a CNI or even outside of kubernetes.
So maybe the changing IPs after a pod restart are the reason for this problem? Cached name resolution?

Manifest to reproduce this issue: [seaweed.txt](https://github.com/chrislusf/seaweedfs/files/5333991/seaweed.txt)

**Comment by chrislusf** [comment]
Ack. I am able to reproduce it on k8s. But not on local. Strange...

**Comment by kmlebedev** [comment]
I not acknowledge it on my k8s

**Comment by chrislusf** [comment]
added a fix for this
