### ISSUE TITLE
S3 Ability to disable listing on a bucket

### ISSUE THREAD

**Issue by divanikus** [chrislusf/seaweedfs#1511]
**Describe the bug**
I want seaweedfs to serve read-only files by link, which is a Read operation. But also I wish to disable the ability of a non-authorized user to get file listing in a bucket. Currently it seems to be impossible. Could this be implemented somehow?

**Comment by chrislusf** [comment]
Added support for "List" action in `weed s3 -config=...` in the config file.

With the fix, you can just use "Read" for anonymous users. See https://github.com/chrislusf/seaweedfs/wiki/Amazon-S3-API

**Comment by divanikus** [comment]
Oh, thank you!
