### ISSUE TITLE
2.0.3: FUSE mount "fail to delete non-empty folders"

### ISSUE THREAD

**Issue by tjohnston-cd** [chrislusf/seaweedfs#1514]
# System Setup
- Running `seaweedfs` components locally on my laptop (Arch Linux with 5.8.13 kernel) via the compose file: `docker-compose -f docker/seaweedfs-compose.yml -p seaweedfs up`
  - 2.0.3 git repo tag, but this also happens on more recent commits to `master`
- FUSE-mounting the root locally on my laptop: `sudo ./weed mount -filer=localhost:8888 -dir=./fuse -filer.path=/`
  - [2.0.3 released binary](https://github.com/chrislusf/seaweedfs/releases/download/2.03/linux_amd64.tar.gz)
- The filesystem containing all my docker volumes, my FUSE-mounted directory and my test files is ext4

# Description
I'm getting started working with `seaweedfs`, running a quick test of the FUSE mount in a single-node setup on my laptop.

- I copy some files in: `rsync -a asdf fuse/`
  - `asdf` is a directory containing a big codebase (85000 files altogether)
- Then I remove everything under that path: `rm -rf fuse/asdf`
- During the `rm -rf`, I get a few of these: `rm: cannot remove 'fuse/asdf/PATH REDACTED': File exists`
  - Usually around 1-5 of them
- When this happens, the `docker-compose` log has this from the filer:

```
filer_1    | E1008 20:47:20     1 filer_delete_entry.go:79] deleting a folder <PATH REDACTED> has children: <PATH REDACTED> ...
filer_1    | I1008 20:47:20     1 filer_delete_entry.go:36] delete directory <PATH REDACTED>: fail to delete non-empty folder: <PATH REDACTED>
```

When the `rm` returns, my whole tree of 85000 files/directories is removed, except for these files that could not be deleted. If I look in the directories, they appear to be empty (at least from the perspective of the FUSE mount).

If I run my `rm -rf` again, I just get the same errors as above.

**If I stop and restart the FUSE mount,** I'm able to run my `rm -rf` and delete the remaining files afterward (with no errors from `rm` or in the compose log for the filer).

# Expected behavior
I should be able to delete my directory without restarting the FUSE mount.

It seems like the FUSE mount is getting confused, but I'm not too sure. Anything I should try?

**Comment by chrislusf** [comment]
Thanks for the detailed report! 

It seems related to some deletion requests are out of order due to busy requests and network latency.

I adjusted the code to ignore the recursive deletion error, since the host OS should manage the recursive deletion cleanly.

Let me know whether the fix works for you.

**Comment by tjohnston-cd** [comment]
I've just tried the same test with 2.04 (on the compose side and the FUSE mount side), and I get the same result.

Would it be useful if I turn on some extra debug options?
