### ISSUE TITLE
How does this compares with MinIO?

### ISSUE THREAD

**Issue by rgl** [chrislusf/seaweedfs#1515]
I think it would be useful to also compare with [MinIO](https://min.io/) in the https://github.com/chrislusf/seaweedfs#compared-to-other-file-systems section.

**Comment by chrislusf** [comment]
Thanks for the suggestion!

Added here based on my limited knowledge:

https://github.com/chrislusf/seaweedfs#compared-to-minio

Welcome to fixes if anything missing or incorrect.
