### ISSUE TITLE
将seaweedfs部署到Kubernetes后，在Kubernetes集群外不能用weed mount进行fuse mount，请问这个可以支持吗？

### ISSUE THREAD

**Issue by paochiang** [chrislusf/seaweedfs#1521]
weed mount只能在k8s集群内部使用，在k8s外部无法mount

**Comment by chrislusf** [comment]
see `weed mount -h`

https://github.com/chrislusf/seaweedfs/wiki/FUSE-Mount#mount-outside-of-a-seaweedfs-cluster

**Comment by paochiang** [comment]
> see `weed mount -h`
> 
> https://github.com/chrislusf/seaweedfs/wiki/FUSE-Mount#mount-outside-of-a-seaweedfs-cluster

`Mount outside of a SeaweedFS cluster` 这个看过并试过了，没有作用，还是不能再k8s集群外mount。因为为了达到`All volume server container ports are open external to the cluster.` 这个条件我是修改了volume service的yaml文件，通过NodePort方式暴露外部访问端口号（默认值:30000-32767)，但weed mount后实际上在连接volume service时实际上访问的是内部端口8080。

并且-filer只能指定filer service的hostname和port，我看源码是通过10000+输入的port作为filer grpc的port，这两个端口号的取值方式导致也无法在k8s集群外部正常连接filer成功。（我修改了源码，单独指定filer grpc port 后可以连接filer成功，可以正常weed mount，但mount后读写文件时，发现访问volume service使用的是内部的端口号8080，最终还是无法读写文件）

另外，我这边测试时发现还有一个问题，mount时加上`outsideContainerClusterMode`参数后，mount后进行文件读写操作时就会卡住，没有反应，不知道是什么导致的。

**Comment by paochiang** [comment]
![image](https://user-images.githubusercontent.com/28077875/95698379-55ca6800-0c74-11eb-96ca-fcc106ce6e87.png)

根据这个架构，我理解如果想要在k8s集群外部正常mount并读写文件，那么在mount时肯定是需要手动指定filer、volume、master相关的外部端口号的，这样才能够在k8s集群外正常访问服务。

**Comment by chrislusf** [comment]
I refactored the code a bit.

In https://github.com/chrislusf/seaweedfs/blob/master/weed/filesys/wfs_filer_client.go#L29

Now it is possible to conditionally use `publicUrl` when `outsideContainerClusterMode`. I am debating whether we should just change the behavior of `outsideContainerClusterMode`.

**Comment by chrislusf** [comment]
Changed: https://github.com/chrislusf/seaweedfs/commit/7704469d294c20df46d1cbd418754dfa9ace0add

Now you can use volume server `-publicUrl` value with `weed mount -outsideContainerClusterMode` mode.

**Comment by paochiang** [comment]
> Changed: [7704469](https://github.com/chrislusf/seaweedfs/commit/7704469d294c20df46d1cbd418754dfa9ace0add)
> 
> Now you can use volume server `-publicUrl` value with `weed mount -outsideContainerClusterMode` mode.

👍  这个可以正常在k8s集群外正常mount使用了。
但有一点我比较疑惑看上面的架构图weed mount是需要直连master的，但是在执行weed mount命令时，并没有指定master相关的publicurl，请问weed mount是怎么在k8s集群外连接master的呢？

**Comment by chrislusf** [comment]
not needed now.

**Comment by paochiang** [comment]
好的，多谢！
