### ISSUE TITLE
the operation which delete file is success, but it didn't work

### ISSUE THREAD

**Issue by SniperHeadShot** [chrislusf/seaweedfs#1522]
**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
|- "weed master": /usr/local/file-server/weed volume -ip=114.163.1.6 -port=9080 -mserver=114.163.1.6:9333 -dir=/usr/local/file-server/vdata1 -max=222
|-- "weed volume": /opt/gato_bin/third_bin/file_server/weed volume -ip=114.163.1.17 -port=9081 -mserver=114.163.1.6:9333 -dir=/opt/gato_bin/third_bin/file_server/vdata2 -max=800
|-- etc.
- "weed filer/weed s3": null
- "details":
{"Topology":{"DataCenters":[{"Free":425,"Id":"DefaultDataCenter","Max":12566,"Racks":[{"DataNodes":[{"EcShards":0,"Free":0,"Max":800,"PublicUrl":"114.163.1.20:9082","Url":"114.163.1.20:9082","Volumes":800},{"EcShards":0,"Free":124,"Max":700,"PublicUrl":"114.163.1.21:9082","Url":"114.163.1.21:9082","Volumes":576},{"EcShards":0,"Free":106,"Max":700,"PublicUrl":"114.163.1.21:9081","Url":"114.163.1.21:9081","Volumes":594},{"EcShards":0,"Free":0,"Max":800,"PublicUrl":"114.163.1.19:9082","Url":"114.163.1.19:9082","Volumes":800},{"EcShards":0,"Free":0,"Max":800,"PublicUrl":"114.163.1.19:9081","Url":"114.163.1.19:9081","Volumes":800},{"EcShards":0,"Free":0,"Max":222,"PublicUrl":"114.163.1.6:9080","Url":"114.163.1.6:9080","Volumes":222},{"EcShards":0,"Free":0,"Max":800,"PublicUrl":"114.163.1.20:9080","Url":"114.163.1.20:9080","Volumes":800},{"EcShards":0,"Free":0,"Max":800,"PublicUrl":"114.163.1.20:9081","Url":"114.163.1.20:9081","Volumes":800},{"EcShards":0,"Free":94,"Max":700,"PublicUrl":"114.163.1.21:9080","Url":"114.163.1.21:9080","Volumes":606},{"EcShards":0,"Free":101,"Max":200,"PublicUrl":"114.163.1.17:9083","Url":"114.163.1.17:9083","Volumes":99},{"EcShards":0,"Free":0,"Max":222,"PublicUrl":"114.163.1.6:9081","Url":"114.163.1.6:9081","Volumes":222},{"EcShards":0,"Free":0,"Max":800,"PublicUrl":"114.163.1.18:9082","Url":"114.163.1.18:9082","Volumes":800},{"EcShards":0,"Free":0,"Max":800,"PublicUrl":"114.163.1.17:9080","Url":"114.163.1.17:9080","Volumes":800},{"EcShards":0,"Free":0,"Max":800,"PublicUrl":"114.163.1.18:9080","Url":"114.163.1.18:9080","Volumes":800},{"EcShards":0,"Free":0,"Max":800,"PublicUrl":"114.163.1.18:9081","Url":"114.163.1.18:9081","Volumes":800},{"EcShards":0,"Free":0,"Max":800,"PublicUrl":"114.163.1.17:9081","Url":"114.163.1.17:9081","Volumes":800},{"EcShards":0,"Free":0,"Max":800,"PublicUrl":"114.163.1.17:9082","Url":"114.163.1.17:9082","Volumes":800},{"EcShards":0,"Free":0,"Max":800,"PublicUrl":"114.163.1.19:9080","Url":"114.163.1.19:9080","Volumes":800},{"EcShards":0,"Free":0,"Max":222,"PublicUrl":"114.163.1.6:9082","Url":"114.163.1.6:9082","Volumes":222}],"Free":425,"Id":"DefaultRack","Max":12566}]}],"Free":425,"Max":12566,"layouts":[{"collection":"","replication":"000","ttl":"","writables":[10103,10596,10018,10017,10096,10508,2127,2164,2122,2159,2135,2138,2099,2163,2124,1869,1874,2180,2139,2169,2137]}]},"Version":"30GB 1.38"} 

- OS version: Linux version 3.10.0-327.el7.x86_64
- output of `weed version`: version 30GB 1.38 linux amd64

**Screenshots**
![2020-10-10_190150](https://user-images.githubusercontent.com/39480247/95653389-07f61880-0b2b-11eb-9429-568f3a7edf92.png)

**Additional context**
 Before that, I used scripts to delete a lot of files until seaweed no return, but I restarted the master node

**Comment by chrislusf** [comment]
the version is too old. Please upgrade first.

**Comment by SniperHeadShot** [comment]
now seaweedfs version is: version 30GB 2.03 4fc6733 linux amd64

{"error":"Deletion Failed: volume size limit 34359738368 exceeded! current size is 34359876753"}


i am also can't delete file, file server had userd 1 year ago.

**Comment by SniperHeadShot** [comment]
i try to move some .dat files to to other dir and restart seaweedfs, but the log count also is 34359876753

**Comment by SniperHeadShot** [comment]
-rw-r--r--. 1 root root  30G 10月 10 16:57 2182.dat
-rw-r--r--. 1 root root 2.9M 10月 10 16:57 2182.idx
-rwxr-xr-x. 1 root root   57 10月 11 15:43 2182.vif
... 
-rw-r--r--. 1 root root  33G 4月  26 07:19 2190.dat
-rw-r--r--. 1 root root 3.1M 4月  26 07:19 2190.idx
-rwxr-xr-x. 1 root root   57 10月 11 15:43 2190.vif

**Comment by SniperHeadShot** [comment]
i got it

```
func (v *Volume) syncDelete(n *needle.Needle) (Size, error) {
	glog.V(4).Infof("delete needle %s", needle.NewFileIdFromNeedle(v.Id, n).String())
	actualSize := needle.GetActualSize(0, v.Version())
	v.dataFileAccessLock.Lock()
	defer v.dataFileAccessLock.Unlock()

        // MaxPossibleVolumeSize uint64 = 4 * 1024 * 1024 * 1024 * 8 // 32GB
	if MaxPossibleVolumeSize < v.nm.ContentSize()+uint64(actualSize) {
		err := fmt.Errorf("volume size limit %d exceeded! current size is %d", MaxPossibleVolumeSize, v.nm.ContentSize())
		return 0, err
	}

	nv, ok := v.nm.Get(n.Id)
	// fmt.Println("key", n.Id, "volume offset", nv.Offset, "data_size", n.Size, "cached size", nv.Size)
	if ok && nv.Size.IsValid() {
		size := nv.Size
		n.Data = nil
		n.AppendAtNs = uint64(time.Now().UnixNano())
		offset, _, _, err := n.Append(v.DataBackend, v.Version())
		if err != nil {
			return size, err
		}
		v.lastAppendAtNs = n.AppendAtNs
		if err = v.nm.Delete(n.Id, ToOffset(int64(offset))); err != nil {
			return size, err
		}
		return size, err
	}
	return 0, nil
}
```
-------------------------------------
mabye oldest version ,the .dat file size > 32G
