### ISSUE TITLE
指定filer.path的weed mount后文件夹为空

### ISSUE THREAD

**Issue by paochiang** [chrislusf/seaweedfs#1528]
使用`./weed mount -outsideContainerClusterMode -filer=161.189.205.192:32601 -grpcfilerport=32602 -dir=/root/lbjmnt -filer.path=/lbj/data/ImageNet_ILSVRC2012_reduced`命令mount成功后，cd 进`/root/lbjmnt`目录后里面内容为空，正常应该有一个文件夹。

但使用`./weed mount -outsideContainerClusterMode -filer=161.189.205.192:32601 -grpcfilerport=32602 -dir=/root/lbjmnt` 命令不指定filer.path参数mount成功后，cd 进`/root/lbjmnt/lbj/data/ImageNet_ILSVRC2012_reduced`目录后里面内容是正常的，目录里的文件夹正常显示。

请问这个是什么导致的？

**Comment by chrislusf** [comment]
what version are you using? There are no such option as `-grpcfilerport`

**Comment by paochiang** [comment]
> grpcfilerport

2.04，`-grpcfilerport`参数是我修改源码后自己添加的，你忽略它

**Comment by chrislusf** [comment]
fixed

**Comment by paochiang** [comment]
试了下，正常了
