### ISSUE TITLE
2.0.4: `weed mount -readRetryTime=600` parse error

### ISSUE THREAD

**Issue by onlyjob** [chrislusf/seaweedfs#1529]
`weed mount -dir=/mnt/weed -readRetryTime=600` fails with

    invalid value "600" for flag -readRetryTime: parse error

**Comment by chrislusf** [comment]
```
  -readRetryTime duration
    	maximum read retry wait time (default 6s)
```

You can use `600s`

**Comment by onlyjob** [comment]
Hmm, thanks. That works. Somehow it is hard to figure out that unit qualifier is mandatory...
