### ISSUE TITLE
2.04: FUSE mount show empty folders when filer is down

### ISSUE THREAD

**Issue by onlyjob** [chrislusf/seaweedfs#1530]
FUSE mount _pretends_ to work when filer is down:

  1. start filer (e.g. `weed filer ...`)
  2. mount `/mnt/weed` (e.g. `weed mount -dir=/mnt/weed ...`)
  3. stop filer
  4. `find /mnt/weed | wc -l`: prints `8`, successfully counts files in root and top-level directories.

Here is the problem: `find /mnt/weed` is not expected to succeed when the filer is down.  
It should not be possible to walk directory tree without filer.  
FUSE mount should have waited for filer but instead it _pretended_ to know the content of the file system and incorrectly reported empty top level directories.

  5. start filer again, same as in step 1.
  6. `find /mnt/weed | wc -l`: prints `114`, as expected.

When the filer became available, the count of files/folders has changed because there are actually some files/folders nested under top level directories.

FUSE mount should not lie about file system content. When filer is not available, FUSE mount should wait for filer and never ever return fraudulent/fabricated information about folder's content.

**Comment by chrislusf** [comment]
Added some fix. There are some cache on FUSE side. 

The IO error will show up after a while, seems less than a minute.

**Comment by onlyjob** [comment]
Thanks for quick action. However please opt in favour of delay instead of error. Perhaps `-readRetryTime` should apply or the file system become unreliable when connectivity with filer is unstable, during restart of filer, etc.  
Error handling should avoid failures when filer is unreachable. This is a recoverable condition that can be handled gracefully without throwing error to applications.

**Comment by chrislusf** [comment]
thanks for the suggestion! added the fix.
