### ISSUE TITLE
2.04: FUSE client filer fail-over to eliminate single point of failure

### ISSUE THREAD

**Issue by onlyjob** [chrislusf/seaweedfs#1531]
With active-active filers, FUSE client should be able to fall back to backup filer when the primary filer is down.

Currently `weed mount` takes only one `-filer` argument. It would be great to pass `-filer filer_a:8888,filer_b:8888` to FUSE client for automatic fail-over. This would help to eliminate single point of failure when the filer is down.

It would be even better if list of filers could be automatically obtained from master without explicit `-filer` argument.

Thanks.

**Comment by tjohnston-cd** [comment]
Agreed! This would be very nice to have.

I'm reminded of LizardFS and [this post](https://github.com/chrislusf/seaweedfs/issues/887#issuecomment-478113684). Perhaps the FUSE mount could take the list of masters as arguments (and use that to find the filers, as you said). That could allow filers to be scaled up/down at runtime while keeping the mount alive.

With this feature, plus failover masters and active-active filers, seaweedfs could be used to deliver a replicated POSIX filesystem with no SPOF (and no use of a floating IP address as in LizardFS).
