### ISSUE TITLE
[BUG] remove bucket with same name on other filer with clear volume data on both

### ISSUE THREAD

**Issue by wsj0000** [chrislusf/seaweedfs#1535]
Version: 2.04
Reproduce steps:
 
1. start 2 filer on same master backend.
2. start object node for each filer.
3. create bucket on each filer with same bucket name.
4. upload some files. 
5. delete one of the bucket.

Result:
![image](https://user-images.githubusercontent.com/11285030/95950982-2e1c0100-0e28-11eb-80bc-542ac48c729b.png)
The volume all cleared.

**Comment by chrislusf** [comment]
As of now, there are no plan to officially support multiple filers with their own filer stores on the same object store. Correct me if I am wrong, this seems not a popular use case.

**Comment by wsj0000** [comment]
> As of now, there are no plan to officially support multiple filers with their own filer stores on the same object store. Correct me if I am wrong, this seems not a popular use case.

But, it might be forbidden to create the duplicated bucket when CreateBucket invoked.

**Comment by wsj0000** [comment]
> As of now, there are no plan to officially support multiple filers with their own filer stores on the same object store. Correct me if I am wrong, this seems not a popular use case.

If other don't know about this. The whole data will be truncated and ALSO include replication. This should be a problem.

**Comment by chrislusf** [comment]
added https://github.com/chrislusf/seaweedfs/commit/ace0ea3d28a7102dee0a0a0c78ffd30d6e068b67 to avoid duplicated collections.

The collection creation is lazy. The bucket's collection will only be created after the bucket has some content. So there could be edge cases when two buckets with the same name are created at the same time before written any content. But that should be rare.
