### ISSUE TITLE
i want to rebuild .idx file, what should i do

### ISSUE THREAD

**Issue by SniperHeadShot** [chrislusf/seaweedfs#1536]
**Describe the bug**
console log:
volume_loading.go:94] volumeDataIntegrityChecking failed verifyNeedleIntegrity D:\\doc\seaweedfs\vdata1/2314.idx failed: read data [8011768,8317828) : entry not found: offset 8011768 found id 64656466663738623534383463386536 size -1313679979, expected size 306060

recently, we upgrade the seaweedfs version from 1.38 to 2.03, the old .dat file size is 33G.
-rw-r--r--. 1 root root  33G 4月  26 07:40 2314.dat
-rw-r--r--. 1 root root 3.9M 4月  26 07:40 2314.idx
-rw-r--r--. 1 root root 2.5M 10月 14 15:10 2314.sdx
-rwxr-xr-x. 1 root root   57 10月 14 15:14 2314.vif

**System Setup**
- OS version: Linux version 3.10.0-327.el7.x86_64 
- output of `weed version`: version 30GB 2.03 linux amd64

**Comment by SniperHeadShot** [comment]
in other words, how build .idx file base on .dat file?thanks.

**Comment by craveica** [comment]
@SniperHeadShot 
weed help fix

**Comment by tengteng0421** [comment]
666, thanks, it works after fix
