### ISSUE TITLE
master masterClient failed to receive from ip: EOF

### ISSUE THREAD

**Issue by bboxzhen** [chrislusf/seaweedfs#1539]
**Describe the bug**
Seaweed cluster communication error.
Only 10.0.1.4 I did not start, 172.16.115.96 and 172.16.115.97 have been started and the network is connected, but this error occurs: master masterClient failed to receive from 172.16.115.96:9334: EOF
master masterClient failed to receive from 172.16.115.97:9334: EOF

**System Setup**
- /opt/seaweedfs_pcap/weed_pcap  master -mdir=/var/log/bd_files/weed_master_data_pcap  -defaultReplication="100" -ip.bind="172.16.115.96" -ip="172.16.115.96"  -port=9334 -peers="10.0.1.4:9334,172.16.115.96:9334,172.16.115.97:9334"
- /opt/seaweedfs_pcap/weed_pcap  master -mdir=/var/log/bd_files/weed_master_data_pcap  -defaultReplication="100" -ip.bind="172.16.115.97" -ip="172.16.115.97" -port=9334  -peers="10.0.1.4:9334,172.16.115.96:9334,172.16.115.97:9334"
- debain8
- version 8000GB 2.04 bbd0afd linux amd64

**Screenshots**
![image](https://user-images.githubusercontent.com/39783629/96203193-d00c2c80-0f93-11eb-8896-f09a8649f1e1.png)
![image](https://user-images.githubusercontent.com/39783629/96203214-e1553900-0f93-11eb-887e-8f2beded2b75.png)

**Additional context**

**Comment by chrislusf** [comment]
the first peer needs to be started at least once.

**Comment by bboxzhen** [comment]
> 第一个对等方至少需要启动一次。

10.0.1.4 I need to start this machine at least once, so the problem will not appear later?

**Comment by chrislusf** [comment]
Yes
