### ISSUE TITLE
2.05: spurious read errors on FUSE mount

### ISSUE THREAD

**Issue by onlyjob** [chrislusf/seaweedfs#1541]
One master, two volume servers, two filers with `-peers`, `-defaultReplicaPlacement=001` and `-encryptVolumeData`.

Reading files from FUSE mount randomly fails, sometimes after 4 GiB read, sometimes after 6 or 7 GiB. One in 2400...3500 files fails to read with `Read failed: Input/output error`.

Mount prints `... filehandle.go:81] file handle read {FILENAME} 0: EOF`.

Repeating recursive read of all files fails in about a minute on a random file. Reproducible 100%. No other errors logged by any other components.

**Comment by chrislusf** [comment]
>
>
> Repeating recursive read of all files fails in about a minute on a random
> file. Reproducible 100%. No other errors logged by any other components
>
What is the command to reproduce this?

>

**Comment by chrislusf** [comment]
Added a fix. Not quite sure how to confirm the fix.

**Comment by onlyjob** [comment]
> What is the command to reproduce this?

You have to use some sort of recursive integrity check utility reading significant amount of data. I've copied 17288 files to SeaweedFS, 67 GiB total. On this instance I'm reading all the files and checking their integrity against pre-calculated digests from another file system using https://gitlab.com/onlyjob/hasher (but it could be any other utility).

> Added a fix. Not quite sure how to confirm the fix.

I would be delighted to test. :) Thank you for quick resolution.

With c0ab458 I could not reproduce the issue any more.  I've read the whole dataset successfully, several times (formerly, before c0ab458, I could not do it even once).

I think you've nailed the problem perfectly. Thank you. Closing.

**Comment by chrislusf** [comment]
It would be a fun project to convert hashier from Perl into Go.

**Comment by onlyjob** [comment]
Why bother? I'm not excited about spending time to re-write something that works well in a different language only to have identical functionality in the end. Maybe as a learning opportunity but in such case I would probably chose _Rust_. ;)
Anyway, IMHO _hasher_ is unworthy of rewriting. It is neither popular nor important and it is pretty useful (to me) as is...
