### ISSUE TITLE
weed s3 如何开启 smb服务或nfs服务

### ISSUE THREAD

**Issue by lze693** [chrislusf/seaweedfs#1543]
您好！因为开启WebDAV服务后 window10挂载网络磁盘有文件大小的限制  导致该方案在window10情形下不行  查看了s3的相关文档发现可以支持smb和nfs 可我并不知如何在seaweedfs的s3服务上使用 希望您能否给予我帮助。

**Comment by chrislusf** [comment]
> 查看了s3的相关文档发现可以支持smb和nfs

where is it?

**Comment by lze693** [comment]
https://docs.amazonaws.cn/storagegateway/latest/userguide/GettingStartedAccessFileShare.html

**Comment by chrislusf** [comment]
> https://docs.amazonaws.cn/storagegateway/latest/userguide/GettingStartedAccessFileShare.html

this is for aws storage gateway. not related.

**Comment by lze693** [comment]
那是否有啥解决方案呀  WebDAV解决不了大文件 几个g的数据

**Comment by chrislusf** [comment]
`weed mount` to a Linux folder. Run some smb or nfs software to map the folder.

**Comment by lze693** [comment]
现在我的seaweedfs是运行在window10上的  不知在window10上是否有解决方案
