### ISSUE TITLE
weed mount 挂载后里面的文件拥有者是nfsnobody该如何解决

### ISSUE THREAD

**Issue by lze693** [chrislusf/seaweedfs#1544]
您好！上传后的文件 通过weed mount挂载 文件的拥有者是nfsnobody 存在权限问题

**Comment by chrislusf** [comment]
see `weed mount -h`

```
  -map.gid string
    	map local gid to gid on filer, comma-separated <local_gid>:<filer_gid>
  -map.uid string
    	map local uid to uid on filer, comma-separated <local_uid>:<filer_uid>

```

**Comment by lze693** [comment]
我尝试 sudo ./weed -logdir=./seaweedfs_data/logs -v=1 mount -filer=192.168.35.110:8888 -dir=./seaweedfs_data/data  -cacheDir=./seaweedfs_data/cache -map.gid=0:65534 -map.uid=0:65534 还是nfsnobody

**Comment by lze693** [comment]
master volume filer 都放在windows上了

**Comment by lze693** [comment]
我发现 master volume filer是在windows上使用  挂载就会出现nfsnobody   全放linux不会出现
