### ISSUE TITLE
[Feature] Add 'racklocation' to Filer

### ISSUE THREAD

**Issue by xrobau** [chrislusf/seaweedfs#1546]
Currently filer can only accept a 'dataCenter' parameter. It appears that master accepts a 'rack' param to allocate volumes, so is it possible to add a 'defaultRack' (or something) param to filer, so when I write to it, it's always going to write to the correct rack?

My use case for this is that I need to have data that is only ever stored in one legal jurisdiction, so I am utilizing 'datacenter' as 'country', and 'rack' as 'datacenter'. If I only want to store data in Canada, I can use 'defaultRack' of 'canada', but if it's temporary data that never needs to leave that datacenter, there's no way to tell filer to ask master for a volume in that rack (datacenter).

Edit: Of course, if there was a NEW field of 'country' that could be assigned to volume servers, and a volume could be limited to only being replicated in that country, that would be even better.

**Comment by chrislusf** [comment]
added.
