### ISSUE TITLE
把系统1中的旧数据, 迁移到新的系统2中

### ISSUE THREAD

**Issue by orange-jacky** [chrislusf/seaweedfs#1549]
配置weed master
   ./weed master -mdir="./mdata" >master_stdout.log    2>&1 &
配置Weed Volume Server
    ./weed volume -max=100 -mserver="localhost:9333" -dir="./data" -port=8088 >volume_stdout.log 2>&1 &
使用filer
    ./weed scaffold -config=filer -output="."
    配置使用mysql
    启动filer
   ./weed filer > filer_stdout.log 2>&1 &

用上面的步骤, 在机器1上配置doc1, 在机器2上配置doc2, 机器1和机器2是不同平台的云机器
doc1, doc2各自运行一段时间后, 都保存不同的数据, 现在需要把doc1的数据, 迁移到doc2, 而且需要保留doc2原来的数据, 改怎么操作?

**Comment by chrislusf** [comment]
You can try `weed filer.sync`

**Comment by orange-jacky** [comment]
机器1 weed 版本比较低, 没有 weed filer.sync命令
机器2 weed版本比较高, 有weed filer.sync命令, 现在需要从机器1转移数据到机器2, 该怎么操作




机器1weed
[ubuntu@VM-0-3-ubuntu seaweedfs]$./weed  version
version 30GB 1.74 linux amd64
[ubuntu@VM-0-3-ubuntu seaweedfs]$./weed  -h

SeaweedFS: store billions of files and serve them fast!

Usage:

	weed command [arguments]

The commands are:

    benchmark   benchmark on writing millions of files and read out
    backup      incrementally backup a volume to local folder
    compact     run weed tool compact on volume file
    filer.copy  copy one or a list of files to a filer folder
    download    download files by file id
    export      list or export files from one volume data file
    filer       start a file server that points to a master server, or a list of master servers
    filer.replicate replicate file changes to another destination
    fix         run weed tool fix on index file if corrupted
    master      start a master server
    mount       mount weed filer to a directory as file system in userspace(FUSE)
    s3          start a s3 API compatible server that is backed by a filer
    msg.broker  <WIP> start a message queue broker
    scaffold    generate basic configuration files
    server      start a master server, a volume server, and optionally a filer and a S3 gateway
    shell       run interactive administrative commands
    watch       see recent changes on a filer
    upload      upload one or a list of files
    version     print SeaweedFS version
    volume      start a volume server
    webdav      start a webdav server that is backed by a filer

Use "weed help [command]" for more information about a command.

For Logging, use "weed [logging_options] [command]". The logging options are:
  -alsologtostderr
    	log to standard error as well as files (default true)
  -log_backtrace_at value
    	when logging hits line file:N, emit a stack trace
  -logdir string
    	If non-empty, write log files in this directory
  -logtostderr
    	log to standard error instead of files
  -stderrthreshold value
    	logs at or above this threshold go to stderr
  -v value
    	log level for V logs
  -vmodule value
    	comma-separated list of pattern=N settings for file-filtered logging



机器2weed
search@JD:/data/search/seaweedfs$ ./weed version
version 30GB 2.05 898db14 linux amd64
search@JD:/data/search/seaweedfs$ ./weed -h

SeaweedFS: store billions of files and serve them fast!

Usage:

	weed command [arguments]

The commands are:

    benchmark   benchmark on writing millions of files and read out
    backup      incrementally backup a volume to local folder
    compact     run weed tool compact on volume file
    filer.copy  copy one or a list of files to a filer folder
    download    download files by file id
    export      list or export files from one volume data file
    filer       start a file server that points to a master server, or a list of master servers
    filer.replicate replicate file changes to another destination
    filer.sync  continuously synchronize between two active-active or active-passive SeaweedFS clusters
    fix         run weed tool fix on index file if corrupted
    master      start a master server
    mount       mount weed filer to a directory as file system in userspace(FUSE)
    s3          start a s3 API compatible server that is backed by a filer
    msgBroker   start a message queue broker
    scaffold    generate basic configuration files
    server      start a master server, a volume server, and optionally a filer and a S3 gateway
    shell       run interactive administrative commands
    watch       see recent changes on a filer
    upload      upload one or a list of files
    version     print SeaweedFS version
    volume      start a volume server
    webdav      start a webdav server that is backed by a filer

Use "weed help [command]" for more information about a command.

For Logging, use "weed [logging_options] [command]". The logging options are:
  -alsologtostderr
    	log to standard error as well as files (default true)
  -log_backtrace_at value
    	when logging hits line file:N, emit a stack trace
  -logdir string
    	If non-empty, write log files in this directory
  -logtostderr
    	log to standard error instead of files
  -stderrthreshold value
    	logs at or above this threshold go to stderr
  -v value
    	log level for V logs
  -vmodule value
    	comma-separated list of pattern=N settings for file-filtered logging
search@JD:/data/search/seaweedfs$

**Comment by orange-jacky** [comment]
weed filer.sync同步不了
机器1和机器2是不同的云服务器上, 我在机器2上通过ssh tunnel方式建立了机器2和机器1的通道
执行 weed filer.sync 报错, 执行curl是正常的, 说明连接已经打通, 但是weed filer.sync同步不了数据


在机器2上操作
ssh -L  192.168.0.3:2234:localhost:8888  ubuntu@xxx.xxx.xxx.xxx

search@JD:/data/search/seaweedfs$ ss -lntp
State    Recv-Q    Send-Q        Local Address:Port        Peer Address:Port                                             
LISTEN   0         128                 0.0.0.0:80               0.0.0.0:*                                                
LISTEN   0         128               127.0.0.1:1234             0.0.0.0:*                                                
LISTEN   0         128           127.0.0.53%lo:53               0.0.0.0:*                                                
LISTEN   0         128                 0.0.0.0:22               0.0.0.0:*                                                
LISTEN   0         128             192.168.0.3:2234             0.0.0.0:*       users:(("ssh",pid=21442,fd=4))           
LISTEN   0         128                       *:8080                   *:*                                                
LISTEN   0         128                       *:8081                   *:*       users:(("issue_server",pid=9585,fd=8))   
LISTEN   0         128                       *:9333                   *:*       users:(("weed",pid=17311,fd=9))          
LISTEN   0         128                    [::]:22                  [::]:*                                                
LISTEN   0         128                       *:8888                   *:*       users:(("weed",pid=18431,fd=11))         
LISTEN   0         128                       *:8088                   *:*       users:(("weed",pid=17338,fd=11))         
LISTEN   0         128                       *:19333                  *:*       users:(("weed",pid=17311,fd=11))         
LISTEN   0         128                       *:18888                  *:*       users:(("weed",pid=18431,fd=12))         
LISTEN   0         128                       *:18088                  *:*       users:(("weed",pid=17338,fd=10))         
LISTEN   0         128                       *:27017                  *:*                                                
LISTEN   0         128                       *:3306                   *:*                                                
LISTEN   0         128                       *:6379                   *:*                                                
search@JD:/data/search/seaweedfs$ ./weed filer.sync  -a=192.168.0.3:2234 -a.debug -b=192.168.0.3:8888 -b.debug
E1021 16:28:48 21451 filer_sync.go:92] sync from 192.168.0.3:2234 to 192.168.0.3:8888: GetFilerConfiguration 192.168.0.3:2234: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 192.168.0.3:12234: connect: connection refused"
E1021 16:28:48 21451 filer_sync.go:104] sync from 192.168.0.3:8888 to 192.168.0.3:2234: GetFilerConfiguration 192.168.0.3:2234: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 192.168.0.3:12234: connect: connection refused"
E1021 16:28:50 21451 filer_sync.go:92] sync from 192.168.0.3:2234 to 192.168.0.3:8888: GetFilerConfiguration 192.168.0.3:2234: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 192.168.0.3:12234: connect: connection refused"
E1021 16:28:51 21451 filer_sync.go:104] sync from 192.168.0.3:8888 to 192.168.0.3:2234: GetFilerConfiguration 192.168.0.3:2234: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 192.168.0.3:12234: connect: connection refused"
E1021 16:28:52 21451 filer_sync.go:92] sync from 192.168.0.3:2234 to 192.168.0.3:8888: GetFilerConfiguration 192.168.0.3:2234: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 192.168.0.3:12234: connect: connection refused"
E1021 16:28:53 21451 filer_sync.go:104] sync from 192.168.0.3:8888 to 192.168.0.3:2234: GetFilerConfiguration 192.168.0.3:2234: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 192.168.0.3:12234: connect: connection refused"
E1021 16:28:54 21451 filer_sync.go:92] sync from 192.168.0.3:2234 to 192.168.0.3:8888: GetFilerConfiguration 192.168.0.3:2234: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 192.168.0.3:12234: connect: connection refused"
E1021 16:28:55 21451 filer_sync.go:104] sync from 192.168.0.3:8888 to 192.168.0.3:2234: GetFilerConfiguration 192.168.0.3:2234: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 192.168.0.3:12234: connect: connection refused"
search@JD:/data/search/seaweedfs$ curl 192.168.0.3:2234
<!DOCTYPE html>
<html>
<head>
	<title>SeaweedFS Filer</title>
	<link rel="stylesheet" href="/seaweedfsstatic/bootstrap/3.3.1/css/bootstrap.min.css">
<style>
#drop-area {
  border: 1px transparent;
}
#drop-area.highlight {
  border-color: purple;
  border: 2px dashed #ccc;
}
.button {
  display: inline-block;
  padding: 2px;
  background: #ccc;
  cursor: pointer;
  border-radius: 2px;
  border: 1px solid #ccc;
  float: right;
}
.button:hover {
  background: #ddd;
}
#fileElem {
  display: none;
}
</style>
</head>
<body>
	<div class="container">
		<div class="page-header">
			<h1>
				<a href="https://github.com/chrislusf/seaweedfs"><img src="/seaweedfsstatic/seaweed50x50.png"></img></a>
				SeaweedFS Filer
			</h1>
		</div>
		<div class="row">
			<div>
			
				<a href="/" >
					 /
				</a>
			
				<label class="button" for="fileElem">Upload</label>
			</div>
		</div>

		<div class="row" id="drop-area">
			<form class="upload-form">
				<input type="file" id="fileElem" multiple onchange="handleFiles(this.files)">

			<table width="90%">
				
				
				<tr>
					<td>
					
						<img src="/seaweedfsstatic/images/folder.gif" width="20" height="23">
						<a href=/.meta/ >
							.meta
						</a>
					
					</td>
					<td align="right" nowrap>
					
					
					</td>
					<td align="right" nowrap>
					
					
					</td>
					<td nowrap>
						2020-04-20 11:55
					</td>
				</tr>
				
				<tr>
					<td>
					
						<img src="/seaweedfsstatic/images/folder.gif" width="20" height="23">
						<a href=/2020/ >
							2020
						</a>
					
					</td>
					<td align="right" nowrap>
					
					
					</td>
					<td align="right" nowrap>
					
					
					</td>
					<td nowrap>
						2020-04-02 23:26
					</td>
				</tr>
				
				<tr>
					<td>
					
						<img src="/seaweedfsstatic/images/folder.gif" width="20" height="23">
						<a href=/topics/ >
							topics
						</a>
					
					</td>
					<td align="right" nowrap>
					
					
					</td>
					<td align="right" nowrap>
					
					
					</td>
					<td nowrap>
						2020-04-20 14:42
					</td>
				</tr>
				

			</table>
			</form>
		</div>

		
	</div>
</body>
<script type="text/javascript">

let dropArea = document.getElementById("drop-area")


;['dragenter', 'dragover', 'dragleave', 'drop'].forEach(eventName => {
  dropArea.addEventListener(eventName, preventDefaults, false)   
  document.body.addEventListener(eventName, preventDefaults, false)
})


;['dragenter', 'dragover'].forEach(eventName => {
  dropArea.addEventListener(eventName, highlight, false)
})

;['dragleave', 'drop'].forEach(eventName => {
  dropArea.addEventListener(eventName, unhighlight, false)
})


dropArea.addEventListener('drop', handleDrop, false)

function preventDefaults (e) {
  e.preventDefault()
  e.stopPropagation()
}

function highlight(e) {
  dropArea.classList.add('highlight')
}

function unhighlight(e) {
  dropArea.classList.remove('highlight')
}

function handleDrop(e) {
  var dt = e.dataTransfer
  var files = dt.files

  handleFiles(files)
}

function handleFiles(files) {
  files = [...files]
  files.forEach(uploadFile)
  window.location.reload()
}

function uploadFile(file, i) {
  var url = window.location.href
  var xhr = new XMLHttpRequest()
  var formData = new FormData()
  xhr.open('POST', url, false)

  formData.append('file', file)
  xhr.send(formData)
}
</script>
</html>
search@JD:/data/search/seaweedfs$

**Comment by orange-jacky** [comment]
在机器2上操作
ssh -L  192.168.0.3:2234:localhost:8888  ubuntu@xxxxxxxxxx
ssh -L  192.168.0.3:12234:localhost:18888  ubuntu@xxxxxxxxxx


search@JD:/data/search/seaweedfs$ ./weed filer.sync  -a=192.168.0.3:2234 -a.debug -b=192.168.0.3:8888 -b.debug
I1021 16:39:30 22054 filer_sync.go:137] start sync 192.168.0.3:2234(0) => 192.168.0.3:8888(1121982392) from 1970-01-01 08:00:00 +0800 CST(0)
E1021 16:39:30 22054 filer_sync.go:104] sync from 192.168.0.3:8888 to 192.168.0.3:2234: rpc error: code = Unimplemented desc = unknown method KvGet for service filer_pb.SeaweedFiler
E1021 16:39:32 22054 filer_sync.go:104] sync from 192.168.0.3:8888 to 192.168.0.3:2234: rpc error: code = Unimplemented desc = unknown method KvGet for service filer_pb.SeaweedFiler
E1021 16:39:35 22054 filer_sync.go:104] sync from 192.168.0.3:8888 to 192.168.0.3:2234: rpc error: code = Unimplemented desc = unknown method KvGet for service filer_pb.SeaweedFiler
E1021 16:39:37 22054 filer_sync.go:104] sync from 192.168.0.3:8888 to 192.168.0.3:2234: rpc error: code = Unimplemented desc = unknown method KvGet for service filer_pb.SeaweedFiler
E1021 16:39:39 22054 filer_sync.go:104] sync from 192.168.0.3:8888 to 192.168.0.3:2234: rpc error: code = Unimplemented desc = unknown method KvGet for service filer_pb.SeaweedFiler
E1021 16:39:42 22054 filer_sync.go:104] sync from 192.168.0.3:8888 to 192.168.0.3:2234: rpc error: code = Unimplemented desc = unknown method KvGet for service filer_pb.SeaweedFiler
E1021 16:39:44 22054 filer_sync.go:104] sync from 192.168.0.3:8888 to 192.168.0.3:2234: rpc error: code = Unimplemented desc = unknown method KvGet for service filer_pb.SeaweedFiler
E1021 16:39:46 22054 filer_sync.go:104] sync from 192.168.0.3:8888 to 192.168.0.3:2234: rpc error: code = Unimplemented desc = unknown method KvGet for service filer_pb.SeaweedFiler
E1021 16:39:48 22054 filer_sync.go:104] sync from 192.168.0.3:8888 to 192.168.0.3:2234: rpc error: code = Unimplemented desc = unknown method KvGet for service filer_pb.SeaweedFiler
E1021 16:39:51 22054 filer_sync.go:104] sync from 192.168.0.3:8888 to 192.168.0.3:2234: rpc error: code = Unimplemented desc = unknown method KvGet for service filer_pb.SeaweedFiler
E1021 16:39:53 22054 filer_sync.go:104] sync from 192.168.0.3:8888 to 192.168.0.3:2234: rpc error: code = Unimplemented desc = unknown method KvGet for service filer_pb.SeaweedFiler


这种同步方式太难用了, 一堆的问题

**Comment by chrislusf** [comment]
You can export and move the meta data and the volume files to some new machine and re-construct system1, but it can not just "merge" into system2.

After re-constructing system1, you can use some tool, such as rclone, to move the files one by one.
