### ISSUE TITLE
Embedded usage? 

### ISSUE THREAD

**Issue by ernado** [chrislusf/seaweedfs#155]
Hi! I'm doing some R&D now on distributed image storage. 
Client on user machine can store 500K-3M files, average size is 500kb. Client should be statically compiled, with no 3-rd party deps, so I'm going to use embedded database. 

Now i'm researching on storage engine for that files. Is weedfs capable to run in embedded mode, efficiently working on that scale? And are there any advantages on using classic subfolder system? (for example, calculating a sha256 hash of file, storing a file in directory, that matches first N bytes of hash)

**Comment by chrislusf** [comment]
What's the "embedded mode"? weedfs is just a compiled binary file.
It should handle these problems without any scalability issue.

To store a file in a directory, you can use "weed filer" option.
Downside could be:
1. FUSE implementation is still not working yet. 
2. Updating should not be super frequent.
3. A little learning curve?

**Comment by ernado** [comment]
@chrislusf 
Embedded = running not as a binary file, but in my code. Like boltdb for example.

**Comment by chrislusf** [comment]
It's possible, but could be lots of effort. This is because the storage engine, volume server, is treated as "dumb". There are managerial operations not included in the volume server, e.g., assign volumes, compact volumes. For these, you can reverse engineer a bit to find out the HTTP APIs.

**Comment by ernado** [comment]
Ok, thank you :)
