### ISSUE TITLE
把旧系统1中的数据迁移到新的系统2中,weed filer.sync报错

### ISSUE THREAD

**Issue by orange-jacky** [chrislusf/seaweedfs#1550]
机器1 weed 版本比较低, 没有 weed filer.sync命令
机器2 weed版本比较高, 有weed filer.sync命令, 现在需要从机器1转移数据到机器2, 该怎么操作

机器1weed
[ubuntu@VM-0-3-ubuntu seaweedfs]$./weed  version
version 30GB 1.74 linux amd64

机器2weed
search@JD:/data/search/seaweedfs$ ./weed version
version 30GB 2.05 898db14 linux amd64

weed filer.sync同步不了
机器1和机器2是不同的云服务器上, 我在机器2上通过ssh tunnel方式建立了机器2和机器1的通道
执行 weed filer.sync 报错, 执行curl是正常的, 说明连接已经打通, 但是weed filer.sync同步不了数据

在机器2上操作
ssh -L  192.168.0.3:2234:localhost:8888  ubuntu@xxx.xxx.xxx.xxx

search@JD:/data/search/seaweedfs$ ss -lntp
State    Recv-Q    Send-Q        Local Address:Port        Peer Address:Port                                             
LISTEN   0         128                 0.0.0.0:80               0.0.0.0:*                                                
LISTEN   0         128               127.0.0.1:1234             0.0.0.0:*                                                
LISTEN   0         128           127.0.0.53%lo:53               0.0.0.0:*                                                
LISTEN   0         128                 0.0.0.0:22               0.0.0.0:*                                                
LISTEN   0         128             192.168.0.3:2234             0.0.0.0:*       users:(("ssh",pid=21442,fd=4))           
LISTEN   0         128                       *:8080                   *:*                                                
LISTEN   0         128                       *:8081                   *:*       users:(("issue_server",pid=9585,fd=8))   
LISTEN   0         128                       *:9333                   *:*       users:(("weed",pid=17311,fd=9))          
LISTEN   0         128                    [::]:22                  [::]:*                                                
LISTEN   0         128                       *:8888                   *:*       users:(("weed",pid=18431,fd=11))         
LISTEN   0         128                       *:8088                   *:*       users:(("weed",pid=17338,fd=11))         
LISTEN   0         128                       *:19333                  *:*       users:(("weed",pid=17311,fd=11))         
LISTEN   0         128                       *:18888                  *:*       users:(("weed",pid=18431,fd=12))         
LISTEN   0         128                       *:18088                  *:*       users:(("weed",pid=17338,fd=10))         
LISTEN   0         128                       *:27017                  *:*                                                
LISTEN   0         128                       *:3306                   *:*                                                
LISTEN   0         128                       *:6379                   *:*                                                
search@JD:/data/search/seaweedfs$ ./weed filer.sync  -a=192.168.0.3:2234 -a.debug -b=192.168.0.3:8888 -b.debug
E1021 16:28:48 21451 filer_sync.go:92] sync from 192.168.0.3:2234 to 192.168.0.3:8888: GetFilerConfiguration 192.168.0.3:2234: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 192.168.0.3:12234: connect: connection refused"
E1021 16:28:48 21451 filer_sync.go:104] sync from 192.168.0.3:8888 to 192.168.0.3:2234: GetFilerConfiguration 192.168.0.3:2234: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 192.168.0.3:12234: connect: connection refused"

search@JD:/data/search/seaweedfs$ curl 192.168.0.3:2234
<!DOCTYPE html>
<html>
<head>
	<title>SeaweedFS Filer</title>
	<link rel="stylesheet" href="/seaweedfsstatic/bootstrap/3.3.1/css/bootstrap.min.css">
<style>
#drop-area {
  border: 1px transparent;
}
....

在机器2上操作
ssh -L  192.168.0.3:2234:localhost:8888  ubuntu@xxxxxxxxxx
ssh -L  192.168.0.3:12234:localhost:18888  ubuntu@xxxxxxxxxx

search@JD:/data/search/seaweedfs$ ./weed filer.sync  -a=192.168.0.3:2234 -a.debug -b=192.168.0.3:8888 -b.debug
I1021 16:39:30 22054 filer_sync.go:137] start sync 192.168.0.3:2234(0) => 192.168.0.3:8888(1121982392) from 1970-01-01 08:00:00 +0800 CST(0)
E1021 16:39:30 22054 filer_sync.go:104] sync from 192.168.0.3:8888 to 192.168.0.3:2234: rpc error: code = Unimplemented desc = unknown method KvGet for service filer_pb.SeaweedFiler
E1021 16:39:32 22054 filer_sync.go:104] sync from 192.168.0.3:8888 to 192.168.0.3:2234: rpc error: code = Unimplemented desc = unknown method KvGet for service filer_pb.SeaweedFiler
E1021 16:39:35 22054 filer_sync.go:104] sync from 192.168.0.3:8888 to 192.168.0.3:2234: rpc error: code = Unimplemented desc = unknown method KvGet for service filer_pb.SeaweedFiler
E1021 16:39:37 22054 filer_sync.go:104] sync from 192.168.0.3:8888 to 192.168.0.3:2234: rpc error: code = Unimplemented desc = unknown method KvGet for service filer_pb.SeaweedFiler
E1021 16:39:39 22054 filer_sync.go:104] sync from 192.168.0.3:8888 to 192.168.0.3:2234: rpc error: code = Unimplemented desc = unknown method KvGet for service filer_pb.SeaweedFiler
E1021 16:39:42 22054 filer_sync.go:104] sync from 192.168.0.3:8888 to 192.168.0.3:2234: rpc error: code = Unimplemented desc = unknown method KvGet for service filer_pb.SeaweedFiler
E1021 16:39:44 22054 filer_sync.go:104] sync from 192.168.0.3:8888 to 192.168.0.3:2234: rpc error: code = Unimplemented desc = unknown method KvGet for service filer_pb.SeaweedFiler
E1021 16:39:46 22054 filer_sync.go:104] sync from 192.168.0.3:8888 to 192.168.0.3:2234: rpc error: code = Unimplemented desc = unknown method KvGet for service filer_pb.SeaweedFiler
E1021 16:39:48 22054 filer_sync.go:104] sync from 192.168.0.3:8888 to 192.168.0.3:2234: rpc error: code = Unimplemented desc = unknown method KvGet for service filer_pb.SeaweedFiler
E1021 16:39:51 22054 filer_sync.go:104] sync from 192.168.0.3:8888 to 192.168.0.3:2234: rpc error: code = Unimplemented desc = unknown method KvGet for service filer_pb.SeaweedFiler
E1021 16:39:53 22054 filer_sync.go:104] sync from 192.168.0.3:8888 to 192.168.0.3:2234: rpc error: code = Unimplemented desc = unknown method KvGet for service filer_pb.SeaweedFiler

这种同步方式太难用了, 一堆的问题
是否可以支持像其他db一样的 export, import , 或者dump, restore这种的离线方式

_Originally posted by @orange-jacky in https://github.com/chrislusf/seaweedfs/issues/1549#issuecomment-713405016_

**Comment by chrislusf** [comment]
You can export and move the meta data and the volume files to some new machine and re-construct system1, but it can not just "merge" into system2. 

After re-constructing system1, you can use some tool, such as rclone, to move the files one by one.

**Comment by orange-jacky** [comment]
> You can export and move the meta data and the volume files to some new machine and re-construct system1, but it can not just "merge" into system2.
> 
> After re-constructing system1, you can use some tool, such as rclone, to move the files one by one.

怎么用rclone,  to move the files one by one?

**Comment by chrislusf** [comment]
copy data under "./data" to new volume servers, and restart volume servers.

**Comment by orange-jacky** [comment]
./data下面的文件名有相同的, 要怎么处理, 我现在这两个机器的data目录下的名字没有相同的

**Comment by chrislusf** [comment]
that is why I said you can not just merge.



> You can export and move the meta data and the volume files to some new machine and re-construct system1, but it can not just "merge" into system2.
> 
> After re-constructing system1, you can use some tool, such as rclone, to move the files one by one.

**Comment by orange-jacky** [comment]
多谢, 已经成功迁移数据
这个维护起来有点麻烦, 可以考虑增加导入, 导出命令

**Comment by chrislusf** [comment]
Actually you can also just mount the old system, and run "weed filer.copy" from the old system to the new one.
