### ISSUE TITLE
[Feature Request] Enhance volume.fsck to allow for finding lost files

### ISSUE THREAD

**Issue by xrobau** [chrislusf/seaweedfs#1552]
As part of my testing of Disaster Recovery and redundancy, I've managed to end up with a handful of lost files.

```
> volume.fsck
volume:7        entries:1787    orphan:2        0.11%   120B
volume:6        entries:1839    orphan:1        0.05%   60B
volume:3        entries:1769    orphan:2        0.11%   120B
volume:1        entries:65      orphan:7        10.77%  334153B
volume:4        entries:1771    orphan:1        0.06%   60B
volume:2        entries:1786    orphan:4        0.22%   240B
volume:5        entries:1843    orphan:2        0.11%   120B

Total           entries:56849   orphan:19       0.03%   334873B
```

There doesn't appear to be any way to get a list of those orphan files from the volume.

I am thinking that this would be useful if someone created a new filer, saved a file to a volume, and then deleted the filer, losing the metadata.  

The admin could then consolidate all the IDs from the known filer(s) and then figure out which ones are REALLY orphan to assist in data recovery.

**Comment by chrislusf** [comment]
The orphans will be a just list of file ids. 
Maybe you can check the content and guess where it should come from. But usually it is hard to tell where it come from though.

**Comment by xrobau** [comment]
> The orphans will be a just list of file ids.

Yes, but if someone uploaded their bitcoin wallet.dat and then deleted the filer, they will want to manually recover the file!  This would only be useful in DR situations, when the metadata is gone and a file is critical to recover.

**Comment by chrislusf** [comment]
To avoid full volume .dat file scanning, current `volume.fsck` code only has partial file id, where the `cookie` in `<volume_id, file_key, cookie>` is missing.

Added code to print the partial file id.

With just <volume_id, file_key>, it is still not easy to read the file content, unless adding special code just for that...

**Comment by xrobau** [comment]
How would you then go about recovering the cookie, so you could get the potentially orphaned file?
