### ISSUE TITLE
The new version of the filer returns different results from the old version

### ISSUE THREAD

**Issue by bboxzhen** [chrislusf/seaweedfs#1554]
**System Setup**
- weed file
- Debian
- 2.05
- if using filer, show the content of `filer.toml`

**Expected behavior**
curl -F file=@/home/1.jpg http://192.168.1.64:8888/test/2020-10-22/

old version：
{"name":"linux_amd64_large_disk.tar.gz","size":26563590,"fid":"26,01e66e82b7ba7428","url":"http://192.168.1.64:5041/26,01e66e82b7ba7428"}
new version：
{'name': '1.pcap', 'size': 16215}

**Comment by chrislusf** [comment]
Yes, changed. Large file may have been sliced into multiple file ids.

**Comment by bboxzhen** [comment]
> 是的，改变了。大文件可能已切成多个文件ID。

Is there no way to know which node exists for the file I uploaded through filer? Can I only download it through filer?

**Comment by chrislusf** [comment]
you can use `weed shell` to run `fs.meta.cat` and see the file id.

**Comment by wangrd** [comment]
> Yes, changed. Large file may have been sliced into multiple file ids, which does not fit this return result format. The root problem is the file ids are concepts in volume server layer, not belonging to the filer.

In my opinion,whether the file is large or not , it has only one public fid so we can index it from outside directly. In other words, it may be a large file too when I upload it via volume server,but volume server still return a fid with that...
On the other side, that means I can only use the filer  to mount as puse or some simple case like that.
I have wanted to save custom headers with filer, but the jwt and fid not be support makes me confused.

**Comment by wangrd** [comment]
> > Yes, changed. Large file may have been sliced into multiple file ids, which does not fit this return result format. The root problem is the file ids are concepts in volume server layer, not belonging to the filer.
> 
> In my opinion,whether the file is large or not , it has only one public fid so we can index it from outside directly. In other words, it may be a large file too when I upload it via volume server,but volume server still return a fid with that...
> On the other side, that means I can only use the filer to mount as puse or some simple case like that.
> I have wanted to save custom headers with filer(see #2233 ), but the jwt and fid not be supported makes me confused.

**Comment by chrislusf** [comment]
@wangrd For advanced usage, you can use filer gRPC APIs directly.
