### ISSUE TITLE
fuse: panic in handler for Release                                  

### ISSUE THREAD

**Issue by angad-k** [chrislusf/seaweedfs#1556]
**Describe the bug**
weed mount exits with an error while a mongodb container is running on it

**System Setup**
- All the default command as given in the wiki
- SeaweedFS version 30GB 2.05 898db14 linux amd64
- Default contents of filer.toml

**Expected behavior**
Should run smoothly without any error.

**Error :**
<code>fuse: panic in handler for Release [ID=0x27b Node=0x2 Uid=0 Gid=0 Pid=0] 0x1 fl=OpenReadWrite rfl=0 owner=0x0: close of closed channel                                                                                      goroutine 921 [running]:                                                                                                github.com/seaweedfs/fuse/fs.(*Server).serve.func2(0x2393240, 0xc00069ee10, 0xc000449eb0, 0xc000449e26)                         /home/travis/gopath/pkg/mod/github.com/seaweedfs/fuse@v0.0.0-20190510212405-310228904eff/fs/serve.go:861 +0x1af panic(0x1cb6da0, 0x23335f0)                                                                                                     /home/travis/.gimme/versions/go1.15.3.linux.amd64/src/runtime/panic.go:969 +0x1b9                               github.com/chrislusf/seaweedfs/weed/filesys.(*FileHandle).Release(0xc0002a73e0, 0x23a19c0, 0xc002f73380, 0xc00069ee10, 0x0, 0x0)                                                                                                                        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/filesys/filehandle.go:190 +0x193                    github.com/seaweedfs/fuse/fs.(*Server).handleRequest(0xc0000ba000, 0x23a19c0, 0xc002f73380, 0x2366b00, 0xc0002a72c0, 0xc0002c0440, 0x2393240, 0xc00069ee10, 0xc000449eb0, 0x300015180, ...)                                                             /home/travis/gopath/pkg/mod/github.com/seaweedfs/fuse@v0.0.0-20190510212405-310228904eff/fs/serve.go:1307 +0x25a7                                                                                                                       github.com/seaweedfs/fuse/fs.(*Server).serve(0xc0000ba000, 0x2393240, 0xc00069ee10)                                             /home/travis/gopath/pkg/mod/github.com/seaweedfs/fuse@v0.0.0-20190510212405-310228904eff/fs/serve.go:882 +0x2c7 github.com/seaweedfs/fuse/fs.(*Server).Serve.func1(0xc0000ba000, 0x2393240, 0xc00069ee10)                                       /home/travis/gopath/pkg/mod/github.com/seaweedfs/fuse@v0.0.0-20190510212405-310228904eff/fs/serve.go:424 +0x6f  created by github.com/seaweedfs/fuse/fs.(*Server).Serve                                                                         /home/travis/gopath/pkg/mod/github.com/seaweedfs/fuse@v0.0.0-20190510212405-310228904eff/fs/serve.go:422 +0x35f </code>

**Comment by chrislusf** [comment]
this has been fixed in ad652ffb97cfdf6d866352a37992ece1c1870248

**Comment by angad-k** [comment]
When will the next release be which will include this fix?
