### ISSUE TITLE
[Feature Request] TTL based on path

### ISSUE THREAD

**Issue by tjohnston-cd** [chrislusf/seaweedfs#1557]
From reading about the [TTL feature](https://github.com/chrislusf/seaweedfs/wiki/Store-file-with-a-Time-To-Live), I think it could be very useful if it was not only an "opt-in" (e.g. user chooses to set a TTL).

What I would like is a way to mark certain paths in my `seaweedfs` configuration, so that everything under them is given a TTL automatically. Or maybe it could be something I set on the object store / filer at runtime?

For example, I could (as the administrator) create a `scratch/` directory, configured so that anything written to it is automatically given a 7-day TTL. This directory could be used to store things like CI build artifacts, and it would naturally roll off old files without any intervention. 

This could also be used to implement a system-wide "trash can" (e.g. all deletes move objects to the trash and apply a TTL to them).

What do you think?

**Comment by ddorian** [comment]
It would be better something like TTL per-collection.
And then you can translate "path" to "collection name".

**Comment by chrislusf** [comment]
Planning to support a configurable mapping, from path pattern to <collection, TTL, replication, volume growth>.

**Comment by ddorian** [comment]
@chrislusf he can do that manually in his application, no ?

**Comment by chrislusf** [comment]
Yes. but that is beyond the control of storage dev ops.

**Comment by tjohnston-cd** [comment]
Yeah, that's the idea - some of the applications that will access the filesystem are quite old and inflexible.

The plan sounds good. Thanks!

**Comment by chrislusf** [comment]
Added in 2.11
