### ISSUE TITLE
weed server , command "-dir" doesn't work

### ISSUE THREAD

**Issue by mingkeYao** [chrislusf/seaweedfs#1558]
when I start weed in docker with command 

"docker run -v /usr/local/weed:/usr/local/weed -p 9333:9333 -p 19333:19333 -p 8090:8090 -p 18090:18090 -d chrislusf/seaweedfs:2.05 server -dir=/usr/local/weed/data0 -volume.port=8090 -master.dir=/usr/local/weed/master -ip=10.11.2.71"

but data stores in /data,  not the command point "/usr/local/weed/data0"

as the picture bellow
![image](https://user-images.githubusercontent.com/33944326/96974050-450ad380-154b-11eb-8bdc-98e6c87b6cab.png)

and I can't find file at /usr/lcoal/weed/data0 in linux.
maybe it's a bug

**Comment by chrislusf** [comment]
Can you try the chrislusf/seaweedfs:dev version?
