### ISSUE TITLE
Spawn volume file with noWriteOrDelete

### ISSUE THREAD

**Issue by kmlebedev** [chrislusf/seaweedfs#1570]
**Describe the bug**
Spawn volume files with noWriteOrDelete likely after volume move in the moment restarts pods
**System Setup**
```2.07```

**Expected behavior**
secure volume mark readonly

**Additional context**
I Can't reproduce yet 
it doesn't give run weed shell tools,
for example 
```
volume.fsck -v -reallyDeleteFromVolume
error: purge for volume 58: delete fileId 58,d84b1: volume 58 is read only
```

**Comment by chrislusf** [comment]
fixed after the merge?

**Comment by kmlebedev** [comment]
> fixed after the merge?

No, it temporary. need to diagnose loss grpc command 
today I lost grpc command Unlock

**Comment by kmlebedev** [comment]
It was the effect of broken volumes
function doCheckAndFixVolumeData() mark broken volumes noWriteOrDelete

**Comment by kmlebedev** [comment]
@chrislusf can be closed
