### ISSUE TITLE
Awkwardness of starting master-filer

### ISSUE THREAD

**Issue by onlyjob** [chrislusf/seaweedfs#1572]
I need to start _master_ and _filer_ (but not _volume_) on one host.

`server` mode allows to start _master_ and (optionally) _filer_ but _volume_ can not be disabled...  
I think formerly it was possible with `-volume=false` but not on 2.07...

Standalone _filer_ don't take a `-dir` argument so it places its metadata to current working directory (which is awkward). In _server_ mode, _filer_'s metadata is stored under `-mdir` location but in dedicated _filer_ mode there is no way to define filer's metadata location.

Would it be possible to make the following changes please?

  * add `-dir` or `-filer.dir` option to _filer_ mode
  * add `-volume=[true|false]` option to _server_ mode

Thanks.

**Comment by chrislusf** [comment]
For filer metadata location, you can use filer.toml to control it.

**Comment by chrislusf** [comment]
Added fix for "add -volume=[true|false] option to server mode"

**Comment by onlyjob** [comment]
Thank you! Do you think `-filer.dir` would be useful as well, to allow overriding default location?

**Comment by chrislusf** [comment]
Filer dir is only for one kind of filer store. Not so straight forward.
