### ISSUE TITLE
What is the maximum number of nodes possible with seaweedfs?

### ISSUE THREAD

**Issue by hiqsociety** [chrislusf/seaweedfs#1576]
Great work by the way but everything is written so nicely but not easy to find the limitations of seaweedfs?

Sorry can't seem to find the "limitation" section under wiki

**Comment by chrislusf** [comment]
For object store setup, master + volume server, maybe the limitation is the speed that master to assign writable file ids for a large cluster. If that is a real case, we can move to use multiple masters to assign file ids.

Other layers should all be linear scalable now, except the filer store. but you can use any other existing scalable solution for that.

**Comment by gitmko0** [comment]
basically, how many nodes can i use with seaweedfs? can i run a dropbox hosting myself?
e.g. 100,000 servers?

**Comment by chrislusf** [comment]
See my previous answer.
