### ISSUE TITLE
file over the limited 268435456 bytes，  Upload 300m file error, can you help to answer it

### ISSUE THREAD

**Issue by eighthw** [chrislusf/seaweedfs#1579]
Upload 300m file error, can you help to answer it，

Is there a configurable parameter to control this size, version 1.77 and version 1.41 are normal

**Comment by chrislusf** [comment]
`weed volume   -fileSizeLimitMB=301`

**Comment by yhan219** [comment]
I would like to ask how to configure docker, my configuration does not seem to take effect
```
    command: 'volume -mserver="master:9333" -port=8080 -publicUrl=/file -fileSizeLimitMB=1024'
```
