### ISSUE TITLE
Help to get a list of file ids from a volume

### ISSUE THREAD

**Issue by insantr** [chrislusf/seaweedfs#1582]
Hey. How can we get the FID(File Id) list from volumes? 
We running server via:
`weed server -metrics.address=pushgateway:9091 -master.dir=/tmp -volume.index=leveldb -volume.max=666 -dir=/data -garbageThreshold=0.1 -ip 'hostname -i'`
Version: **SeaweedFS 30GB 1.36**
We assume that we have lost some of the file ids. How can we get a list of file ids exist in the volumes for compare with what we store in our database?

**Comment by chrislusf** [comment]
You can see the code of `volume.fsck` in `weed shell`. There is a gRPC API to fetch fetch file ids except the cookie part. It should be enough for you to find lost file ids.
