### ISSUE TITLE
Error in incremental backup: weed backup

### ISSUE THREAD

**Issue by blitzlepe** [chrislusf/seaweedfs#1583]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs
![image](https://user-images.githubusercontent.com/73666581/97623741-be8f3f80-19eb-11eb-995b-50d7de173748.png)

**Describe the bug**
When running the backup with:    
 `./weed backup -server=localhost:9333 -dir="/shares/LynxDigitalizacion" -volumeId=1`
Where  ` -dir="/shares/LynxDigitalizacion"` is a NAS volume mounted as NFS.

It works fine the first time, but runnning again same command, throws:
 `I1029 13:01:35 18205 volume_loading.go:94] volumeDataIntegrityChecking failed verifyNeedleIntegrity /shares/LynxDigitalizacion/1.idx failed: read data [9772313128,9776074523) : EOF
I1029 13:01:35 18205 needle_map_sorted_file.go:24] Start to Generate /shares/LynxDigitalizacion/1.sdx from /shares/LynxDigitalizacion/1.idx
I1029 13:01:35 18205 needle_map_sorted_file.go:26] Finished Generating /shares/LynxDigitalizacion/1.sdx from /shares/LynxDigitalizacion/1.idx
Error synchronizing volume 1: ReadNeedleBody offset 9772313128, bodyLength 3761408: EOF`

**System Setup**
Centos 8
SeaweedFS 2.07
Started server and volume with: `./weed server -master.port=9333 -volume.port=8890 -dir="./data"`

**Expected behavior**
Also tried running directly the weed backup in a ssh session in the NAS:
`./weed backup -server=172.21.1.251:9333 -dir="/shares/LynxDigitalizacion" -volumeId=1` 
but got same result, first backup runs well, incremental backup not.
Also tried in a windows 10 PC, no luck

**Screenshots**
![image](https://user-images.githubusercontent.com/73666581/97625251-e41d4880-19ed-11eb-8c61-5fa065bd6947.png)

![image](https://user-images.githubusercontent.com/73666581/97623662-9ef81700-19eb-11eb-9908-e1f79103acac.png)

![image](https://user-images.githubusercontent.com/73666581/97629984-82aca800-19f4-11eb-8a67-2665839c1911.png)

**Comment by chrislusf** [comment]
Thanks for the detailed issue report! Appreciate all the details!

Added a fix.

**Comment by blitzlepe** [comment]
Thank you for the fast response and fix, It works!
