### ISSUE TITLE
Volume server crashed after filer.copy executed [Version 2.07]

### ISSUE THREAD

**Issue by flomo29** [chrislusf/seaweedfs#1587]
**Describe the bug**

When i execute the following command, the volume server on my ARM device is crashing after a while, without error message in the volume log!

The following command was executed on my MacBook and the ip address is the server device:

./weed filer.copy data.test http://192.168.178.23:8888/
uploading data.test in 193 chunks ...
uploaded data.test-3 to http://192.168.178.23:8080/2,059f9ec1e2 [67108864,100663296)
uploaded data.test-5 to http://192.168.178.23:8080/1,01acc5bc8c [134217728,167772160)
uploaded data.test-4 to http://192.168.178.23:8080/7,047e0ddcd9 [100663296,134217728)
uploaded data.test-8 to http://192.168.178.23:8080/4,062a05e371 [234881024,268435456)
uploaded data.test-9 to http://192.168.178.23:8080/2,093ea8025d [268435456,301989888)
uploaded data.test-10 to http://192.168.178.23:8080/5,0a7ffb587b [301989888,335544320)
uploaded data.test-1 to http://192.168.178.23:8080/6,0895bd1189 [0,33554432)
uploaded data.test-7 to http://192.168.178.23:8080/4,027116adca [201326592,234881024)
uploaded data.test-11 to http://192.168.178.23:8080/3,0bb078ad0f [335544320,369098752)
uploaded data.test-2 to http://192.168.178.23:8080/2,075e506c78 [33554432,67108864)
uploaded data.test-6 to http://192.168.178.23:8080/6,03644ce93f [167772160,201326592)
uploaded data.test-12 to http://192.168.178.23:8080/5,0cffb0060c [369098752,402653184)
uploaded data.test-13 to http://192.168.178.23:8080/1,0ddf942d78 [402653184,436207616)
uploaded data.test-17 to http://192.168.178.23:8080/4,119e845b43 [536870912,570425344)
uploaded data.test-14 to http://192.168.178.23:8080/3,0ef29c754d [436207616,469762048)
uploaded data.test-16 to http://192.168.178.23:8080/6,10c2587a6a [503316480,536870912)
uploaded data.test-15 to http://192.168.178.23:8080/1,0f0f018d1f [469762048,503316480)
uploaded data.test-20 to http://192.168.178.23:8080/3,144d19147b [637534208,671088640)
uploaded data.test-21 to http://192.168.178.23:8080/7,156cc052eb [671088640,704643072)
uploaded data.test-18 to http://192.168.178.23:8080/2,126f557580 [570425344,603979776)
E1030 23:52:15  1576 upload_content.go:236] upload data.test-24 0 bytes to http://192.168.178.23:8080/4,164607e85d: Post "http://192.168.178.23:8080/4,164607e85d": EOF
E1030 23:52:15  1576 upload_content.go:236] upload data.test-23 0 bytes to http://192.168.178.23:8080/6,191b2af4f1: Post "http://192.168.178.23:8080/6,191b2af4f1": EOF
E1030 23:52:15  1576 upload_content.go:236] upload data.test-19 0 bytes to http://192.168.178.23:8080/3,13ee4b51f2: Post "http://192.168.178.23:8080/3,13ee4b51f2": EOF
E1030 23:52:15  1576 upload_content.go:236] upload data.test-22 0 bytes to http://192.168.178.23:8080/5,18400e84bf: Post "http://192.168.178.23:8080/5,18400e84bf": EOF
goroutine 62 [running]:
runtime/debug.Stack(0x7b, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.15.3.linux.amd64/src/runtime/debug/stack.go:24 +0x9f
runtime/debug.PrintStack()
	/home/travis/.gimme/versions/go1.15.3.linux.amd64/src/runtime/debug/stack.go:16 +0x25
<<< Printing the stack >>>

E1030 23:52:15  1576 upload_content.go:236] upload data.test-27 0 bytes to http://192.168.178.23:8080/2,1a4a8919c7: Post "http://192.168.178.23:8080/2,1a4a8919c7": write tcp 192.168.178.21:61210->192.168.178.23:8080: write: broken pipe
goroutine 117 [running]:
runtime/debug.Stack(0x7b, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.15.3.linux.amd64/src/runtime/debug/stack.go:24 +0x9f
runtime/debug.PrintStack()
	/home/travis/.gimme/versions/go1.15.3.linux.amd64/src/runtime/debug/stack.go:16 +0x25
<<< Printing the stack >>>

E1030 23:52:15  1576 upload_content.go:236] upload data.test-25 0 bytes to http://192.168.178.23:8080/3,170d853851: Post "http://192.168.178.23:8080/3,170d853851": EOF
goroutine 120 [running]:
runtime/debug.Stack(0xbf, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.15.3.linux.amd64/src/runtime/debug/stack.go:24 +0x9f
runtime/debug.PrintStack()
	/home/travis/.gimme/versions/go1.15.3.linux.amd64/src/runtime/debug/stack.go:16 +0x25
<<< Printing the stack >>>

E1030 23:52:15  1576 upload_content.go:236] upload data.test-28 0 bytes to http://192.168.178.23:8080/1,1bec7978de: Post "http://192.168.178.23:8080/1,1bec7978de": write tcp 192.168.178.21:61208->192.168.178.23:8080: write: broken pipe
W1030 23:52:15  1576 upload_content.go:103] uploading to http://192.168.178.23:8080/2,1a4a8919c7: upload data.test-27 0 bytes to http://192.168.178.23:8080/2,1a4a8919c7: Post "http://192.168.178.23:8080/2,1a4a8919c7": write tcp 192.168.178.21:61210->192.168.178.23:8080: write: broken pipe
E1030 23:52:15  1576 upload_content.go:236] upload data.test-26 0 bytes to http://192.168.178.23:8080/7,1c84353fd2: Post "http://192.168.178.23:8080/7,1c84353fd2": write tcp 192.168.178.21:61206->192.168.178.23:8080: write: broken pipe
goroutine 92 [running]:
runtime/debug.Stack(0xbf, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.15.3.linux.amd64/src/runtime/debug/stack.go:24 +0x9f
runtime/debug.PrintStack()
	/home/travis/.gimme/versions/go1.15.3.linux.amd64/src/runtime/debug/stack.go:16 +0x25
<<< Printing the stack >>>

W1030 23:52:15  1576 upload_content.go:103] uploading to http://192.168.178.23:8080/4,164607e85d: upload data.test-24 0 bytes to http://192.168.178.23:8080/4,164607e85d: Post "http://192.168.178.23:8080/4,164607e85d": EOF
goroutine 105 [running]:
runtime/debug.Stack(0x7b, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.15.3.linux.amd64/src/runtime/debug/stack.go:24 +0x9f
runtime/debug.PrintStack()
	/home/travis/.gimme/versions/go1.15.3.linux.amd64/src/runtime/debug/stack.go:16 +0x25
<<< Printing the stack >>>

W1030 23:52:15  1576 upload_content.go:103] uploading to http://192.168.178.23:8080/6,191b2af4f1: upload data.test-23 0 bytes to http://192.168.178.23:8080/6,191b2af4f1: Post "http://192.168.178.23:8080/6,191b2af4f1": EOF
W1030 23:52:15  1576 upload_content.go:103] uploading to http://192.168.178.23:8080/5,18400e84bf: upload data.test-22 0 bytes to http://192.168.178.23:8080/5,18400e84bf: Post "http://192.168.178.23:8080/5,18400e84bf": EOF
W1030 23:52:15  1576 upload_content.go:103] uploading to http://192.168.178.23:8080/3,13ee4b51f2: upload data.test-19 0 bytes to http://192.168.178.23:8080/3,13ee4b51f2: Post "http://192.168.178.23:8080/3,13ee4b51f2": EOF
W1030 23:52:15  1576 upload_content.go:103] uploading to http://192.168.178.23:8080/1,1bec7978de: upload data.test-28 0 bytes to http://192.168.178.23:8080/1,1bec7978de: Post "http://192.168.178.23:8080/1,1bec7978de": write tcp 192.168.178.21:61208->192.168.178.23:8080: write: broken pipe
W1030 23:52:15  1576 upload_content.go:103] uploading to http://192.168.178.23:8080/3,170d853851: upload data.test-25 0 bytes to http://192.168.178.23:8080/3,170d853851: Post "http://192.168.178.23:8080/3,170d853851": EOF
W1030 23:52:15  1576 upload_content.go:103] uploading to http://192.168.178.23:8080/7,1c84353fd2: upload data.test-26 0 bytes to http://192.168.178.23:8080/7,1c84353fd2: Post "http://192.168.178.23:8080/7,1c84353fd2": write tcp 192.168.178.21:61206->192.168.178.23:8080: write: broken pipe
Failed to assign from [localhost:9333]: assign volume failure count:1  collection:"test"  replication:"000"  path:"/data.testdata.test": assign volume: rpc error: code = Unavailable desc = transport is closing
Failed to assign from [localhost:9333]: assign volume failure count:1  collection:"test"  replication:"000"  path:"/data.testdata.test": assign volume: rpc error: code = Unavailable desc = transport is closing
E1030 23:52:15  1576 upload_content.go:236] upload data.test-29 0 bytes to http:///: Post "http:///": http: no Host in request URL
goroutine 63 [running]:
runtime/debug.Stack(0x56, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.15.3.linux.amd64/src/runtime/debug/stack.go:24 +0x9f
runtime/debug.PrintStack()
	/home/travis/.gimme/versions/go1.15.3.linux.amd64/src/runtime/debug/stack.go:16 +0x25
<<< Printing the stack >>>

W1030 23:52:15  1576 upload_content.go:103] uploading to http:///: upload data.test-29 0 bytes to http:///: Post "http:///": http: no Host in request URL
copy file error: upload data data.test to http:///: upload data.test-29 0 bytes to http:///: Post "http:///": http: no Host in request URL

**Server**

Commands on server:

`weed -logdir /mnt/backup/log_master/ master -mdir /mnt/backup/master 2> /dev/null > /dev/null &`
`weed -logdir /mnt/backup/log_volume/ volume -dir /mnt/backup/volume 2> /dev/null > /dev/null &`
`weed -logdir /mnt/backup/log_filer/ filer -collection test 2> /dev/null > /dev/null &`

**Log file from master:**

cat log_master/weed.WARNING 
Log file created at: 2020/10/30 22:49:57
Running on machine: odroidxu4
Binary: Built with gc go1.15.3 for linux/arm
Log line format: [IWEF]mmdd hh:mm:ss threadid file:line] msg
W1030 22:49:57 15383 master_grpc_server.go:57] SendHeartbeat.Recv server 192.168.178.23:8080 : rpc error: code = Canceled desc = context canceled

**Comment by chrislusf** [comment]
Seems the serve is overwhelmed. Can you try to use smaller chunk size:
`
weed filer.copy -concurrentChunks=2 -maxMB=1
`

**Comment by flomo29** [comment]
Yes. When i use your settings, i get a little bit over 10.0 MB/s. And with concurrent 4 and maxmb 10 i get 15.0 MB/s.

**Comment by chrislusf** [comment]
thanks for the update!
