### ISSUE TITLE
2.07: restaring one master caused fatal error on FUSE mount

### ISSUE THREAD

**Issue by onlyjob** [chrislusf/seaweedfs#1589]
During restart of _one_ master out of _three_, application using a FUSE mount failed with the following error: ` statvfs arror (EIO (Input/output error)) `. As mentioned earlier (in other tickets), FUSE client should wait and retry instead of immediately fail an operation. This is crucial for resiliency to network errors and normal maintenance operations such as restarting 1/3 masters which should not cause any errors.

**Comment by onlyjob** [comment]
Thank you. Will test shortly. Would it work as per `-readRetryTime`?

**Comment by chrislusf** [comment]
> Would it work as per `-readRetryTime`?

Yes.
