### ISSUE TITLE
about md5

### ISSUE THREAD

**Issue by momofiona** [chrislusf/seaweedfs#159]
can seeweedfs supply md5 value?

**Comment by chrislusf** [comment]
For read or write?

**Comment by yanyiwu** [comment]
Absolutely for Read.

I guess it is for duplicate removal

**Comment by chrislusf** [comment]
Currently when reading a file, a Etag header is sent back. That can be used for dup detection. Actually, when writing to the same file key, there will be a checking for duplication already. See go/storage/volume.go file isFileUnchanged() function.  https://github.com/chrislusf/seaweedfs/blob/master/go/storage/volume.go#L154
