### ISSUE TITLE
Volume x not found

### ISSUE THREAD

**Issue by glowkeeper** [chrislusf/seaweedfs#1593]
After starting `filer` via `weed server -filer=true`, this url resolves correctly:
```
http://localhost:8888/0x3CACC87DC563DA12FFF1A679332FBF7E6E218E4B/minidapp.conf
```
However, after shutting down `filer` (via ctrl-c), then restarting, the same url returns: 
```
volume 2 not found
```

**Comment by chrislusf** [comment]
Configure a directory:

weed server -dir=xxx

**Comment by glowkeeper** [comment]
Ah, okay - thanks! So `weed server -filer=true` does `weed server -dir=xxx` successfully when run the first time, but not the second time?

**Comment by chrislusf** [comment]
always use `weed server -dir=xxx -filer=true`

**Comment by glowkeeper** [comment]
You should document that (the wiki just says, `run weed server -filer=true`)
