### ISSUE TITLE
Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by glowkeeper** [chrislusf/seaweedfs#1595]
I'm using 2.08.

After starting `filer` via `weed server -filer=true`, I post some images to `filer`, like so:

`weed filer.copy -include *.png . http://192.168.43.200:8888/`

Then, I use the Fetch API of javascript to try and access an image from `filer`. Something like so:
```
await fetch("http://192.168.43.200:8888/images/icon.png")
```
Unfortunately, the fetch fails:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://192.168.43.200:8888/images/icon.png.
```
I can bypass that error by putting a proxy in front of `filer` and accessing the image via the proxy, but I'd like to avoid that.

**Comment by chrislusf** [comment]
can you provide an example html page to reproduce this?

**Comment by glowkeeper** [comment]
Gosh - not easily - that code is embedded deep inside a large react app'.

**Comment by chrislusf** [comment]
> I'm guessing _any_ javascript that uses the Fetch API will fail?

ok. Please provide one example.

**Comment by glowkeeper** [comment]
Okay, so this works:

---
<html>

<head>

</head>

<body style="background-image: url(./images/trader.jpg);">

<script type="text/javascript">

	async function getStuff() {

		const response = await fetch("http://localhost:8888/myTextFile.txt");
		const text = await response.text();
		console.log(text);
	}

	getStuff();

</script>

</body>

</html>
---

When it seems to fail is when my app' is loaded from another app running on a server, so the URL looks like this:

```
http://localhost:9004/minidapps/0x5951E6CF39D03B02FB2C11E1B9E18B52DA2C85B1/#/
```

**Comment by glowkeeper** [comment]
Can't reproduce the problem easily without giving you access to my whole setup (which I can't do, presently), which produces the issue every time. I've tried creating a local [http-server](https://github.com/http-party/http-server) on port 9004 and loading that script above, but that seems to work just fine. It _must) be something specific to how my app gets loaded via another webserver. I'll have to dig deeper...

**Comment by chrislusf** [comment]
You can compare the request and response headers when it does and does not work?

**Comment by glowkeeper** [comment]
Here's the failing url:

<img width="1440" alt="Screenshot 2020-11-03 at 22 09 19" src="https://user-images.githubusercontent.com/9264929/98046217-b6873380-1e21-11eb-9f66-100b6307e949.png">

Here's the working url:

<img width="1440" alt="Screenshot 2020-11-03 at 22 09 29" src="https://user-images.githubusercontent.com/9264929/98046262-cacb3080-1e21-11eb-947e-294c8e7e72dd.png">

**Comment by chrislusf** [comment]
The failing response is not sent by SeaweedFS. All SeaweedFS response has a "Server: SeaweedFS Filer ..." header value.

**Comment by chrislusf** [comment]
The failing URL has double forward slashes: "http://localhost:8888//...."

**Comment by glowkeeper** [comment]
> The failing URL has double forward slashes: "http://localhost:8888//...."

Yeah - that's my code not quite getting a rewrite correct - I haven't bothered fixing it because I don't think it's a problem
