### ISSUE TITLE
Support NFS v3

### ISSUE THREAD

**Issue by chrislusf** [chrislusf/seaweedfs#1600]
https://github.com/willscott/go-nfs/

**Comment by chrislusf** [comment]
seems the go-nfs is not production ready yet.

**Comment by shimbay** [comment]
is there any possibility to support nfs?

**Comment by chrislusf** [comment]
not any time soon

**Comment by chrislusf** [comment]
added NFSv3 in https://github.com/seaweedfs/seaweedfs/pull/9067
