### ISSUE TITLE
我想使用nginx反向代理下载seaweedfs图片？怎么设置？

### ISSUE THREAD

**Issue by shumintao** [chrislusf/seaweedfs#1604]
例如：

nginx配置：

```
 location /download  {
          client_max_body_size 5000m;
         proxy_pass http://10.4.176.34:8888/;
 }
```

当我访问时：

![image](https://user-images.githubusercontent.com/26895243/98530528-fdf63f80-22b9-11eb-9d84-d501eca02b66.png)
![image](https://user-images.githubusercontent.com/26895243/98530537-03538a00-22ba-11eb-95e4-4c3bb22b83f3.png)

**Comment by chrislusf** [comment]
Please ask on nginx related forums.

https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/

```
location /  {
         proxy_pass http://10.4.176.34:8888/;
 }
```
