### ISSUE TITLE
请教下如何配置volume的publicUrl

### ISSUE THREAD

**Issue by paochiang** [chrislusf/seaweedfs#1606]
目的：seaweedfs部署在k8s上，volume的pod(statefulset)数量为3，master和filer的pod(statefulset)数量为1，想在k8s集群外通过weed mount后操作文件。

问题：请教一下启动volume时如何配置publicUrl（据了解mount时outsideContainerClusterMode要配合publicUrl可以正常工作）？或者说3个volume的publicUrl配置为相同的ip+port会不会有问题？还是说必须配置为不同的ip+port，mount才能正常工作？

**Comment by chrislusf** [comment]
Each volume server needs to have its own publicUrl accessible by the `weed mount`

cc @howardlau1999

**Comment by chrislusf** [comment]
btw: in https://github.com/seaweedfs/seaweedfs-operator/issues/16

the seaweedfs operator added one ingress for each volume server.

**Comment by paochiang** [comment]
多谢告知，我现在是用seaweedfs项目下k8s文件夹下的chart部署到k8s集群的，因为有多个k8s集群所以需要跨k8s集群访问mount filer。我现在准备在volume server的 headless service基础上再为每个volume server单独起一个service，通过nodeport方式暴露为集群外可访问的服务，然后将这个端口前拼上外网IP，设置为volume server的publicUrl。

**Comment by paochiang** [comment]
现在有个问题还想请教一下，在项目里k8s文件夹下的chart里，修改`volume-statefulset.yaml`添加`publicUrl`时，对于`replicas>1`，请问怎么才能将不同的地址赋值给`publicUrl`？

**Comment by howardlau1999** [comment]
> 现在有个问题还想请教一下，在项目里k8s文件夹下的chart里，修改`volume-statefulset.yaml`添加`publicUrl`时，对于`replicas>1`，请问怎么才能将不同的地址赋值给`publicUrl`？

你可以尝试一下编写一个自定义的脚本通过k8s api来获取端口，或者固定好端口的模式通过脚本计算。然后再启动volume server

**Comment by paochiang** [comment]
> > 现在有个问题还想请教一下，在项目里k8s文件夹下的chart里，修改`volume-statefulset.yaml`添加`publicUrl`时，对于`replicas>1`，请问怎么才能将不同的地址赋值给`publicUrl`？
> 
> 你可以尝试一下编写一个自定义的脚本通过k8s api来获取端口，或者固定好端口的模式通过脚本计算。然后通过修改启动命令来用这个脚本启动volume server

多个volume的端口号可以获取到，比如是port1、port2、port3。但因为volume server是statefulset的，多个volume是通过将replicas的值设置为3。我不知道如何在volume启动命令里获知当前是第几个pod，从而将不同过的ip+port1、ip+port2、ip+port3赋值给publicUrl。

所以我想知道有没有可能后置赋值publicUrl的操作，比如在volume server启动后，或者是在weed mount时通过参数指定volume server的publicUrl？

**Comment by howardlau1999** [comment]
> > > 现在有个问题还想请教一下，在项目里k8s文件夹下的chart里，修改`volume-statefulset.yaml`添加`publicUrl`时，对于`replicas>1`，请问怎么才能将不同的地址赋值给`publicUrl`？
> > 
> > 
> > 你可以尝试一下编写一个自定义的脚本通过k8s api来获取端口，或者固定好端口的模式通过脚本计算。然后通过修改启动命令来用这个脚本启动volume server
> 
> 多个volume的端口号可以获取到，比如是port1、port2、port3。但因为volume server是statefulset的，多个volume是通过将replicas的值设置为3。我不知道如何在volume启动命令里获知当前是第几个pod，从而将不同过的ip+port1、ip+port2、ip+port3赋值给publicUrl。
> 
> 所以我想知道有没有可能后置赋值publicUrl的操作，比如在volume server启动后，或者是在weed mount时通过参数指定volume server的publicUrl？

StatefulSet 启动的时候会给 Pod 命名为 <name>-0,1,2,3 这样的形式，只需要通过正则将后面的序号提取就知道自己是第几个 Pod 了。

**Comment by paochiang** [comment]
> > > > 现在有个问题还想请教一下，在项目里k8s文件夹下的chart里，修改`volume-statefulset.yaml`添加`publicUrl`时，对于`replicas>1`，请问怎么才能将不同的地址赋值给`publicUrl`？
> > > 
> > > 
> > > 你可以尝试一下编写一个自定义的脚本通过k8s api来获取端口，或者固定好端口的模式通过脚本计算。然后通过修改启动命令来用这个脚本启动volume server
> > 
> > 
> > 多个volume的端口号可以获取到，比如是port1、port2、port3。但因为volume server是statefulset的，多个volume是通过将replicas的值设置为3。我不知道如何在volume启动命令里获知当前是第几个pod，从而将不同过的ip+port1、ip+port2、ip+port3赋值给publicUrl。
> > 所以我想知道有没有可能后置赋值publicUrl的操作，比如在volume server启动后，或者是在weed mount时通过参数指定volume server的publicUrl？
> 
> StatefulSet 启动的时候会给 Pod 命名为 `<name>-0,1,2,3` 这样的形式，只需要通过正则将后面的序号提取就知道自己是第几个 Pod 了。

了解了，多谢！
