### ISSUE TITLE
Filer doesn't list directories correctly 

### ISSUE THREAD

**Issue by nmt1994** [chrislusf/seaweedfs#161]
dc1-r1/weed volume -max=20 -dataCenter="DC1" -rack="Rack 1" -dir=./dc1-r1/ -port=8081 &
dc1-r2/weed volume -max=20 -dataCenter="DC1" -rack="Rack 2" -dir=./dc1-r2/ -port=8082 &
dc1-r3/weed volume -max=20 -dataCenter="DC1" -rack="Rack 3" -dir=./dc1-r3/ -port=8083 &
dc1-r12/weed volume -max=20 -dataCenter="DC1" -rack="Rack1.2" -dir=./dc1-r12/ -port=8084 &
dc2-r1/weed volume -max=20 -dataCenter="DC2" -rack="Rack 2.1" -dir=./dc2-r1/ -port=8085 & 
master2/weed master -mdir=./master2 -peers=localhost:9334 &
master/weed master -mdir=./master -port=9334 &
filer/weed filer -mdir=. 

These are my commands to run a cluster of servers .
Topology :
DC1 - Rack 1 + Rack 2 + Rack 3 + Rack 1 + Filer
DC2 - Rack 2.1
Each DC1 is set on different servers
On Windows Server 2008, this is the output when I tried to upload file 
{"Directory":"/","Files":[{"name":"test","fid":"33,9e6009c49e"}],"Subdirectories":null}
** To a not exist directory :
{"Directory":"/test/","Files":[{"name":"test","fid":"33,9e6009c49e"}],"Subdirectories":null}

Everything seems work fine on Ubuntu 14.04, since it doesn't show the file that doesn't exist in the current directory
{"Directory":"/","Files":null,"Subdirectories":[{"Name":"test","Id":1}]}

{"Directory":"/test/","Files":[{"name":"examples.desktop","fid":"12,100190d200a658"}],"Subdirectories":null}

**Comment by chrislusf** [comment]
There is a bug fixed similar to this.

**Comment by nmt1994** [comment]
I currently cannot find the workaround that you said that was fixed here. My only options now is to use Ubuntu Server instead

**Comment by nmt1994** [comment]
@chrislusf :
Hi , This is the nearest explanation that I can find here but no solution provided 
https://groups.google.com/forum/#!searchin/seaweedfs/filer/seaweedfs/wL1bCeQQ6F0/B6e2u1vpGGwJ
1) One thing that I also notice is the dir.LOG in Windows Server is never updated
2) I have tried upload 2 files with same name to different directory , but seems that the file is overwrite.
I think this was supposed to be the "flat namespace" without directory listing ? 
I am using Embedded LevelDB for Filer Server.
