### ISSUE TITLE
filer.copy: destination XYZ uses collection "asagi-images": unexpected collection "asagi-images"

### ISSUE THREAD

**Issue by Suika** [chrislusf/seaweedfs#1611]
**Describe the bug**
```
$ weed filer.copy -collection=asagi-images e/image http://localhost:8888/buckets/asagi-images/e/image/
destination /buckets/asagi-images/e/image/ uses collection "asagi-images": unexpected collection "asagi-images"
```

Probably 147d4d23b64173ac8cc48dba10e00fffa2ec5cbe is the cause of it or at least started to happen after that.

**System Setup**
- Docker Setup, see #1594
- Debian 9
- version 8000GB 2.10 15956d8 linux amd64
- Default docker filer config

**Expected behavior**
If copying data to a bucket and the right collection is definied in the arguments, do not error out.
If a different collection is defined in the arguments than the one of the bucket, error out.

I know that the collection does not need be defined in the arguments, but still.

**Comment by chrislusf** [comment]
Thanks for the detailed issue report!
