### ISSUE TITLE
"Fix missing volumes"  and  "Balance volumes"

### ISSUE THREAD

**Issue by sosogh** [chrislusf/seaweedfs#1615]
I am tring to understand what `Fix missing volumes`  and  `Balance volumes` exactly are .
(https://github.com/chrislusf/seaweedfs/wiki/Volume-Management)

so I make a test :

#### Installing SeaweedFS:(one master , two volume servers)

> weed master -defaultReplication=001   -mdir=/weed/metadata  
> weed volume -port=8081 -dir=/weed/data1 -max=1   -dataCenter=dc1 -rack=rack1
> weed volume -port=8082 -dir=/weed/data2 -max=1   -dataCenter=dc1 -rack=rack1

#### Uploading  10 files to it :

> weed mount -filer=localhost:8888 -dir=/mount/fuse
> cp 10files  /mount/fuse/.

#### Testing "Fix missing volumes"

1.  kill volume server 2(-port=8082) and  start a (new) volume server 3 (port=8083)
2.  run `volume.fix.replication`  in  `weed shell` , it show :
    `replicating volume 1 001 from 192.168.2.123:8081 to dataNode 192.168.2.123:8083 ...`

And now I understand that "Fix missing volumes"  is to fix volume replication ,  it is used  when replacing the broken volume server with the new good one .

#### Testing "Balance volumes"

I am not sure what balance  exactly mean , After reading this article  [What do we mean by Re-balance?](https://www.tecmint.com/perform-self-heal-and-re-balance-operations-in-gluster-file-system/).
I make a test :  

1.  start  volume server 4 (port=8084) and volume server 5 (port=8085) 
2.  run `volume.balance  -force`  in  `weed shell`  , but nothing happen 

I _thought_ that seaweedFS would move some files (maybe 5)  to another volume replica pair (volume server 4 and volume server 5). 

But it does not . So my question is : 

`what "Balance volumes" mean ? and when is it used ?`

Thank you !

**Comment by chrislusf** [comment]
"Balance volumes" if all volume servers have roughly the same number of volumes, they are balanced.

btw: that article is about glusterfs. Not related.

**Comment by chrislusf** [comment]
Thanks for sharing how GlusterFS does the rebalancing. Good to know that.

It is trying to balance at files level. This seems not very efficient at all. And there are little performance difference if only a few files are moved.

SeaweedFS balance volume servers at volume level. Basically a large batch of files. It is much much more efficient than processing each files one by one.
