### ISSUE TITLE
disk status check repeatedly logs every 5 seconds

### ISSUE THREAD

**Issue by Suika** [chrislusf/seaweedfs#1619]
**Describe the bug**
Currently using the 2.10 large_disk docker container.
The v2.10 had the tiny fix "adjust verbose logs for disk size checking outputs" added, yet the log continues to be spammed by the disk status checks every 5 seconds.

```
today at 11:48 I1115 10:48:12     1 disk.go:12] disk status: dir:"/data"  all:8001561124864  used:7784529891328  free:217031233536  percent_free:2.712361  percent_used:97.287636
today at 11:48 I1115 10:48:17     1 disk.go:12] disk status: dir:"/data"  all:8001561124864  used:7784529891328  free:217031233536  percent_free:2.712361  percent_used:97.287636
today at 11:48 I1115 10:48:22     1 disk.go:12] disk status: dir:"/data"  all:8001561124864  used:7784529891328  free:217031233536  percent_free:2.712361  percent_used:97.287636
```
**System Setup**
 - Docker Setup, see #1594
 - Debian 9
 - version 8000GB 2.10 15956d8 linux amd64
 - Default docker filer config

**Expected behavior**
Don't really thing that it should be something constant in the logs.
If there is no change in data size, why spam the log with it.

Maybe log it on volume server start and on volume expansion.

**Comment by chrislusf** [comment]
Disk usage is higher than 95%, so the log level is increased.
