### ISSUE TITLE
Nginx on VolumeServer !!

### ISSUE THREAD

**Issue by shahzaibcb** [chrislusf/seaweedfs#162]
Hi,

   We're running video sharing website consists of TeraBytes of videos and thumbs. To reduce Random I/O requests against millions of thumbs, we've came across weedFS tech in order to store multiple thumbs under single file to reduce HDD IOPS. 

We've deployed Weedfs master/volume vpss for our production testing and our developers just completed the php client coding to make weedfs compatible with our app. 

Though we're currently using basic master/volume model in order to serve thumbs to end-user i.e 

 http://thumbs.volume.com:8080/3,01637037d6.jpg

As you can see WeedFS volume server is currently being served as Web-Server but we believe that we should go with nginx webserver in order to serve large number of concurrent requests against static files (Nginx considered fastest for static serving). So is there a way we can render the volume server URL using http://master:9333volumeid/Fid  and then serve the specific request on port 80 using nginx on top of volume server  such as :

 http://thumbs.volume.com/3,01637037d6.jpg 

We came accross following guide, please let us know if this can help us achieve this goal ?

https://github.com/medcl/lua-resty-weedfs

Thanks in Advance !!
Shahzaib

**Comment by chrislusf** [comment]
AFAIK, lua-resty-weedfs is not designed for that, but you can use it as an example to start.

**Comment by shahzaibcb** [comment]
Thanks, if we don't go with nginx and run weedfs volume servers on port 80 (instead of default 8080) in order to serve thumbs directly via HTTP, what number of concurrent requests it can handle ? Currently, our nginx serve entertains round 20K concurrent connections against thumbs on each server. Just curious to know if weedfs HTTP can handle more than that ?

**Comment by chrislusf** [comment]
The benchmark number all depends on your file size, network, cpu, hard drive. Better test it yourself. But this number is within reach.

Remember to set the white list before opening the volume server to public.

btw: just fronting weedfs with nginx would not make the system faster, if weedfs is really the bottleneck.

**Comment by shahzaibcb** [comment]
Thanks for response, we've benchmarked concurrrent read requests using apache "ab" tool. The benchmark was between the weedfs volume server(:8080) VS Nginx(proxy_cache:80) in front of weedfs volume(:8080). I hereby conclude that nginx proxy_cache increased the read performance by caching the frequently accessed files.  

-On weedfs, the 20K req/s was finished around 7 seconds.
-On nginx in front of weeds ,completed 20k req/s around 4 and half seconds.
