### ISSUE TITLE
cleanup disk space

### ISSUE THREAD

**Issue by cleveryg** [chrislusf/seaweedfs#1623]
By weed Filer delete a large number of directories as well as files, hit you volume. Dat space has not been freed at all
The data directory was 3.3t before deletion
Delete command is：
curl -X DELETE "http://192.168.0.211:8888/china/dom/northwest/I47?recursive=true"
curl -X DELETE "http://192.168.0.211:8888/china/dom/northwest/I48?recursive=true"
curl -X DELETE "http://192.168.0.211:8888/china/dom/northwest/J46?recursive=true"
curl -X DELETE "http://192.168.0.211:8888/china/dom/northwest/J47?recursive=true"
curl -X DELETE "http://192.168.0.211:8888/china/dom/northwest/J48?recursive=true"
curl -X DELETE "http://192.168.0.211:8888/china/dom/northwest/k47?recursive=true"
curl -X DELETE "http://192.168.0.211:8888/china/dom/northwest/k48?recursive=true"
curl -X DELETE "http://192.168.0.211:8888/china/dom/northwest/K47?recursive=true"
curl -X DELETE "http://192.168.0.211:8888/china/dom/northwest/K48?recursive=true"
 curl -X DELETE "http://192.168.0.211:8888/china/dom/northwest/L49?recursive=true"
After deletion:
curl "http://192.168.0.211:9333/vol/vacuum"

After all the execution, the data directory is still 3.3T
But the storage space is not free??
How to free storage space??

**Comment by chrislusf** [comment]
lower garbageThreshold:

curl "http://192.168.0.211:9333/vol/vacuum?garbageThreshold=0.0001"

See https://github.com/chrislusf/seaweedfs/wiki/Master-Server-API#force-garbage-collection
