### ISSUE TITLE
How to clear the volume space and reduce the volume

### ISSUE THREAD

**Issue by cleveryg** [chrislusf/seaweedfs#1624]
I am in weed Filer by executing commands：
curl -X DELETE "http://192.168.0.211:8888/china/dom/northwest/I47?recursive=true"
curl -X DELETE "http://192.168.0.211:8888/china/dom/northwest/I48?recursive=true"
curl -X DELETE "http://192.168.0.211:8888/china/dom/northwest/J46?recursive=true"
curl -X DELETE "http://192.168.0.211:8888/china/dom/northwest/J47?recursive=true"
curl -X DELETE "http://192.168.0.211:8888/china/dom/northwest/J48?recursive=true"
curl -X DELETE "http://192.168.0.211:8888/china/dom/northwest/k47?recursive=true"
curl -X DELETE "http://192.168.0.211:8888/china/dom/northwest/k48?recursive=true"
curl -X DELETE "http://192.168.0.211:8888/china/dom/northwest/K47?recursive=true"
curl -X DELETE "http://192.168.0.211:8888/china/dom/northwest/K48?recursive=true"
The contraction command is then executed：
curl "http://192.168.0.211:9333/vol/vacuum"

But disk space has not decreased at all？？？why？？？
How to clear the volume space and reduce the volume？？？

**Comment by chrislusf** [comment]
lower garbageThreshold:

curl "http://192.168.0.211:9333/vol/vacuum?garbageThreshold=0.0001"

See https://github.com/chrislusf/seaweedfs/wiki/Master-Server-API#force-garbage-collection

**Comment by cleveryg** [comment]
> lower garbageThreshold:
> 
> curl "http://192.168.0.211:9333/vol/vacuum?garbageThreshold=0.0001"
> 
> See https://github.com/chrislusf/seaweedfs/wiki/Master-Server-API#force-garbage-collection

3Q
