### ISSUE TITLE
What is CPX file

### ISSUE THREAD

**Issue by cleveryg** [chrislusf/seaweedfs#1628]
Run Command to clear space:
curl "http://192.168.0.212:9333/vol/vacuum?garbageThreshold=0.0001"

However, the background log reported an error:
E1120 13:28:11 50415 volume_grpc_vacuum.go:66] cleanup volume 109: remove /mnt/bjshdata/weedfs-waipian-quanguo-back/weedfs215/data/109.cpx: no such file or directory

What is CPX file? Will it affect the clean space?

**Comment by chrislusf** [comment]
you can ignore it.

**Comment by chrislusf** [comment]
btw: your version is too old.

**Comment by cleveryg** [comment]
> you can ignore it.

hello，Thank you for your reply！！！
Why do I perform a curl "http://192.168.0.212:9333/vol/vacuum?garbageThreshold=0.0001", the disk space increases instead of decreasing.

**Comment by cleveryg** [comment]
> > you can ignore it.
> 
> hello，Thank you for your reply！！！
> Why do I perform a curl "http://192.168.0.212:9333/vol/vacuum?garbageThreshold=0.0001", the disk space increases instead of decreasing.

At the end of the command, disk space increases instead

**Comment by cleveryg** [comment]
> > > you can ignore it.
> > 
> > 
> > hello，Thank you for your reply！！！
> > Why do I perform a curl "http://192.168.0.212:9333/vol/vacuum?garbageThreshold=0.0001", the disk space increases instead of decreasing.
> 
> At the end of the command, disk space increases instead

curl "http://192.168.0.211:9333/vol/vacuum?garbageThreshold=0.00001"
{"Topology":{"DataCenters":[{"Free":876,"Id":"DefaultDataCenter","Max":1000,"Racks":[{"DataNodes":[{"EcShards":0,"Free":876,"Max":1000,"PublicUrl":"192.168.0.211:8083","Url":"192.168.0.211:8083","Volumes":124}],"Free":876,"Id":"DefaultRack","Max":1000}]}],"Free":876,"Layouts":[{"collection":"","replication":"000","ttl":"","writables":[126,120,122,123,121]}],"Max":1000},"Version":"8000GB 1.50"}

**Comment by chrislusf** [comment]
seems some bugs. upgrade first.
