### ISSUE TITLE
Need a help about file server architecture!

### ISSUE THREAD

**Issue by truonguit2010** [chrislusf/seaweedfs#163]
Hi,
I am trying to build an application. I have 
1. An mobile app as client.
2. APIs server.
3. File server. I love to use Weedfs.

When I want to upload image from mobile app to file server. I do:
1. Connect to APIs server to get fid. (APIs server connect to Weedfs)
2. Client received fid, and send file to server over http
3. After send file OK, Client notify to APIs server to save this fid to database.

It take 3 step to upload a file, how can I do that more clean. Do I need an server to handle file before Weedfs? This server will update database and send back fid to client.

Thank you!

**Comment by zhengying** [comment]
You can do like that: 
1.  send file to API server 
2.  API server save file to weedfs.
3.  return a fid  to client

**Comment by chrislusf** [comment]
Your design is more scalable. But I agree with @zhengying . Get it working the simple way first. It's simpler for security also.

**Comment by yourchanges** [comment]
For performance, we do it like this:
1. send file to weedfs with /submit api by js directly
2. send fid to api server to database
