### ISSUE TITLE
Issue reading parquet files out of seaweed

### ISSUE THREAD

**Issue by eth0h4ckr** [chrislusf/seaweedfs#1634]
**Describe the bug**
Unable to read Parquet files from seaweed via hive or impala.

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
```
weed -logdir /var/log/seaweedfs/filer filer -ip 127.0.0.1 -port 8888 -master 10.0.0.1:9333 -collection COL1 -maxMB 128 -defaultReplicaPlacement 001
weed -logdir /var/log/seaweedfs/master master -defaultReplication 001 -ip 10.0.0.1 -port 9333 -peers 10.0.0.1:9333 -mdir /var/lib/seaweedfs/master -volumeSizeLimitMB 64000 -volumePreallocate
weed -logdir /var/log/seaweedfs/volume volume -max=2 -dataCenter DC1 -rack rack1 -dir=/data/d2/seaweedfs -mserver 10.0.0.1:9333 -port 5200
```

- OS version
`Ubuntu 16.04.6 LTS`

- output of `weed version`
`version 8000GB 2.02 9ab98fa linux amd64`

- seaweed hadoop client
`seaweedfs-hadoop2-client-1.4.7.jar`

- seaweed hadoop client properties
```
<property>
<name>fs.seaweedfs.impl</name>
<value>seaweed.hdfs.SeaweedFileSystem</value>
</property>

<property>
<name>fs.AbstractFileSystem.seaweedfs.impl</name>
<value>seaweed.hdfs.SeaweedAbstractFileSystem</value>
</property>

<property>
<name>fs.seaweed.buffer.size</name>
<value>134217728</value>
</property>

```

- if using filer, show the content of `filer.toml`
```
# A sample TOML config file for SeaweedFS filer store
# Used with "weed filer" or "weed server -filer"
# Put this file to one of the location, with descending priority
#    ./filer.toml
#    $HOME/.seaweedfs/filer.toml
#    /etc/seaweedfs/filer.toml

####################################################
# Customizable filer server options
####################################################
[filer.options]
# with http DELETE, by default the filer would check whether a folder is empty.
# recursive_delete will delete all sub folders and files, similar to "rm -Rf"
recursive_delete = false
# directories under this folder will be automatically creating a separate bucket
buckets_folder = "/buckets"
buckets_fsync = [          # a list of buckets with all write requests fsync=true
        "important_bucket",
        "should_always_fsync",
]

####################################################
# The following are filer store options
####################################################

[redis2]
enabled = true
address  = "10.0.0.1:6390"
password = "SOMEPASSWORD"
database = 0

```

**Additional context**
When Parquet files are written to seaweed, they are easily read manually using Parquet-tools and dumping the contents to a plaintext file. But when impalad reads the file, it errors with the following error in impala:

`File 'seaweedfs://127.0.0.1:8888/dir1/file.parquet' has an invalid version number: ","s`

also

`Error from query blah:blah: ParquetScanner: reached EOF while deserializing data page header. file=seaweedfs://127.0.0.1:8888/dir1/file.parquet`

**Additional Notes**
It was mentioned by a co-worker the issue with reading the parquet file could be due to the file being little endian and maybe adding some null bytes to the file when its written to seaweedfs. We have also written a tool to anonymize our parquet data if you would like to test or have me do some more testing to add more context

**Comment by chrislusf** [comment]
Thanks! The bug has been fixed in 00a75d7c You can use the latest 1.5.6
