### ISSUE TITLE
Cannot grow volume group! No matching data node found! \ndc01:Free:1 \u003c Expected:2"

### ISSUE THREAD

**Issue by DoraemonAndRat** [chrislusf/seaweedfs#1635]
我启用了纠删码，但是在封存若干次以后就会出现这个错误，如果我想无限次的分配文件ID来上传，该如何处理，我需要做什么？
此外，启用EC之后是不是不支持TTL过期了？
目前脚本参数：ec.encode -fullPercent=0 -quietFor=1m，我这么设置是为了测试。

**Comment by chrislusf** [comment]
Need to add more volumes. `./weed volume -max=100`

see `weed volume -h` or `weed server -h`
