### ISSUE TITLE
weed mount后 os.LStat获取文件状态 里modeTime不完整

### ISSUE THREAD

**Issue by paochiang** [chrislusf/seaweedfs#1636]
问题描述：同一个文件在linux机器上直接os.Lstat得到的结果，和将该文件删除到seafweed后，通过weed mount后再os.Lstat获取到的结果相比，weed mount后modeTime有不完整的地方。

linux上直接os.Lstat结果（为了便于观察，做了换行）：
```
size:34104156 mode:436 modTime:{wall:395420915 ext:63740967826 loc:0x569320} 
sys:{Dev:64514 Ino:918535 Nlink:1 Mode:33204 Uid:1000 Gid:1000 X__pad0:0 Rdev:0 Size:34104156 Blksize:4096 Blocks:66616 
Atim:{Sec:1606123796 Nsec:695135779} 
Mtim:{Sec:1605371026 Nsec:395420915} 
Ctim:{Sec:1605371026 Nsec:395420915} X__unused:[0 0 0]}}
```

weed mount后os.Lstat结果（为了便于观察，做了换行）：
```
size:34104156 mode:420 modTime:{wall:0 ext:63741720596 loc:0x569320} 
sys:{Dev:3145889 Ino:16142416380117008597 Nlink:1 Mode:33188 Uid:1000 Gid:1000 X__pad0:0 Rdev:0 Size:34104156 Blksize:2097152 Blocks:66610 
Atim:{Sec:1606183658 Nsec:406432410} 
Mtim:{Sec:1606123796 Nsec:0} 
Ctim:{Sec:1606183658 Nsec:406432410} X__unused:[0 0 0]}}
```
可以看出来，第一行modTime的wall值为0，第4行Mtim的Nsec为0

补充：我在将weed mount后文件系统作为docker registry的backend时，push 镜像时会报错:```parsing time "" as "2006-01-02T15:04:05Z07:00": cannot parse "" as "2006"```，（用非weed mount的文件夹作为backend可以正常push镜像），排查问题时找到了一个类似的问题：https://github.com/docker/distribution/issues/1673 。 所以感觉是weed mount后文件的Stat的modTime导致的。

希望帮忙看些这两个缺失不一致的地方是不是有问题。多谢！

**Comment by chrislusf** [comment]
Seaweed version?

**Comment by paochiang** [comment]
2.09

**Comment by paochiang** [comment]
这个问题我找到了，和os.Lstat无关，是weed mount时没有指定```-outsideContainerClusterMode```导致连接不上seaweed volume。
修改后，上面的问题不存在了，但现在push镜像时会卡住：
![image](https://user-images.githubusercontent.com/28077875/100219931-97c41a80-2f51-11eb-9fb3-7d0b95492e6a.png)
并且自己手动```weed mount```后，尝试删除相关目录也会卡住：
![image](https://user-images.githubusercontent.com/28077875/100220383-3fd9e380-2f52-11eb-9340-acc17484e6b3.png)

weed.INFO 日志：
```
Log file created at: 2020/11/25 18:57:56
Running on machine: qa-4
Binary: Built with gc go1.15.3 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss threadid file:line] msg
I1125 18:57:56 21217 leveldb_store.go:40] filer store dir: /tmp/lbjc/6e2c/meta
I1125 18:57:56 21217 file_util.go:23] Folder /tmp/lbjc/6e2c/meta Permission: -rwxr-xr-x
I1125 18:57:56 21217 mount_std.go:207] mounted 10.10.10.214:22602/ to /home/orion/lbj/mnt
```
weed.qa-4.orion.log.INFO.20201125-191052.16598 日志：
```
Log file created at: 2020/11/25 19:10:52
Running on machine: qa-4
Binary: Built with gc go1.15.3 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss threadid file:line] msg
I1125 19:10:52 16598 leveldb_store.go:40] filer store dir: /tmp/lbjc/6e2c/meta
I1125 19:10:52 16598 file_util.go:23] Folder /tmp/lbjc/6e2c/meta Permission: -rwxr-xr-x
I1125 19:10:52 16598 mount_std.go:207] mounted 10.10.10.214:22602/ to /home/orion/lbj/mnt
```

seaweedfs-filer pod的日志：
```
I1125 11:10:52     1 filer_grpc_server_sub_meta.go:175] + listener mount@10.10.10.214:38540
I1125 11:10:52     1 filer_grpc_server_sub_meta.go:26]  mount@10.10.10.214:38540 starts to subscribe / from 2020-11-25 11:10:52.138497062 +0000 UTC
I1125 11:12:14     1 filer_deletion.go:60] deleting fileIds len=1
```
无weed.FATAL、weed.WARNING、weed.ERROR日志产生

**Comment by chrislusf** [comment]
Please follow the issue template. Add more details on how to reproduce.

**Comment by kmlebedev** [comment]
double https://github.com/chrislusf/seaweedfs/issues/1609
fixed in 2.12  version

**Comment by paochiang** [comment]
see new issue: https://github.com/chrislusf/seaweedfs/issues/1639
