### ISSUE TITLE
Volume Replication Recovery

### ISSUE THREAD

**Issue by weswam** [chrislusf/seaweedfs#164]
I have been reading through the available documentation and I had a question regarding replication.

If a volume is being replicated and the server holding the volume dies is there an automatic recovery from the remaining replica to ensure the replicated volumes still meet the desired replication settings?

If not what is the preferred method to recover from a volume server failure due to say a hard drive failure for example.

**Comment by chrislusf** [comment]
Currently if one replica is down, the other replica will change to read only mode. That's it.

To recover, just rsync over the damaged volume file, i.e., .dat and .idx files.

Hopefully there will be some "fix it" button on the UI to automate this. But right now, I do not want to put in any "smart" magic to do this automatically, which could lead to unexpected behaviors.

**Comment by gaoyang-projects** [comment]
i have a question about volume replication recovery.  
when volume node was crashed like disk unrecoverable.
 it's lost all of volume data (i.e., .dat and .idx files).
`http://localhost:9333/vol/status` show volumes status, but crashed volume node does not exists.

> currently if one replica is down, the other replica will change to read only mode

it's work，server will reject upload file request and error log like 

> Volume 26 has 0 replica, less than required 2

, but `http://localhost:9333/vol/status`  show me 

> "ReadOnly": false 

`
{
  "Id": 21,
  "Size": 8,
  "ReplicaPlacement": {
	"SameRackCount": 1,
	"DiffRackCount": 0,
	"DiffDataCenterCount": 0
  },
  "Ttl": {
	
  },
  "Collection": "sanrio",
  "Version": 2,
  "FileCount": 0,
  "DeleteCount": 0,
  "DeletedByteCount": 0,
  "ReadOnly": false
}
`

some questions:
1. how to find out volume node has how many volumeId to recovery ？
1.  if find out crached volumeIds can **weed backup**  instead **rsync** to recovery ？
1. when replica is not enough, but **/vol/status** show **"ReadOnly": false** , isn't it **true** ？

**Comment by chrislusf** [comment]
1. you can get the list of writable volumes. the volumes not writable could either be full or need-to-recover.
2. rsync
3. readonly is just the volume data file is read only or not.

**Comment by man4j** [comment]
2. Why rsync? weed backup also nice worked
