### ISSUE TITLE
[upgrade guidance] Which version is recommended to upgrade from version 1.50

### ISSUE THREAD

**Issue by GarinQian** [chrislusf/seaweedfs#1644]
We use seaweedfs version 1.50 on site. I see that you have many new features and bug fixes since 1.50. I would like to ask which version is relatively stable and recommend upgrading. And what kind of migration work does the upgrade need to do. Looking forward to your guidance and reply.

**Comment by chrislusf** [comment]
You can always use the latest release. All releases should be backward compatible, unless there are special notes on the release description.
