### ISSUE TITLE
Very slow read speeds when running impala queries against seaweedfs

### ISSUE THREAD

**Issue by eth0h4ckr** [chrislusf/seaweedfs#1645]
**Describe the bug**
Very slow read speeds when running a query against seaweed files via impala

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
```
weed -logdir /var/log/seaweedfs/filer filer -ip 127.0.0.1 -port 8888 -master 10.0.0.1:9333 -collection COL1 -maxMB 128 -defaultReplicaPlacement 001
weed -logdir /var/log/seaweedfs/master master -defaultReplication 001 -ip 10.0.0.1 -port 9333 -peers 10.0.0.1:9333 -mdir /var/lib/seaweedfs/master -volumeSizeLimitMB 64000 -volumePreallocate
weed -logdir /var/log/seaweedfs/volume volume -max=2 -dataCenter DC1 -rack rack1 -dir=/data/d2/seaweedfs -mserver 10.0.0.1:9333 -port 5200
```

- OS version
`Ubuntu 16.04.6 LTS`

- output of `weed version`
`version 8000GB 2.13 0e99531 linux amd64`

- seaweed hadoop client
`seaweedfs-hadoop2-client-1.5.6.jar`

- seaweed hadoop client properties
```
<property>
<name>fs.seaweedfs.impl</name>
<value>seaweed.hdfs.SeaweedFileSystem</value>
</property>

<property>
<name>fs.AbstractFileSystem.seaweedfs.impl</name>
<value>seaweed.hdfs.SeaweedAbstractFileSystem</value>
</property>

<property>
<name>fs.seaweed.buffer.size</name>
<value>134217728</value>
</property>

```

- if using filer, show the content of `filer.toml`
```
# A sample TOML config file for SeaweedFS filer store
# Used with "weed filer" or "weed server -filer"
# Put this file to one of the location, with descending priority
#    ./filer.toml
#    $HOME/.seaweedfs/filer.toml
#    /etc/seaweedfs/filer.toml

####################################################
# Customizable filer server options
####################################################
[filer.options]
# with http DELETE, by default the filer would check whether a folder is empty.
# recursive_delete will delete all sub folders and files, similar to "rm -Rf"
recursive_delete = false
# directories under this folder will be automatically creating a separate bucket
buckets_folder = "/buckets"
buckets_fsync = [          # a list of buckets with all write requests fsync=true
        "important_bucket",
        "should_always_fsync",
]

####################################################
# The following are filer store options
####################################################

[redis2]
enabled = true
address  = "10.0.0.1:6390"
password = "SOMEPASSWORD"
database = 0

```

**Additional context**
When running a query via impala, the query evetually completes but takes an extremely long time compared to a query ran against data that exists on hdfs. Im seeing the following error on the impala daemons:

`readDirect: FSDataInputStream#read error:
UnsupportedOperationException: Byte-buffer read unsupported by input streamjava.lang.UnsupportedOperationException: Byte-buffer read unsupported by input stream`

This error scrolls over and over until the query completes. Im able to cat out files, read and write files fine via hdfs but when queries are ran against the data it takes an extremely long time to complete.

**Comment by chrislusf** [comment]
Knew nothing about Impala. Please let me know how to setup Impala.

**Comment by chrislusf** [comment]
https://issues.apache.org/jira/browse/HDFS-14083 make sure your hdfs version has this fix also.

**Comment by chrislusf** [comment]
Added a fix, but not sure how to verify it.

**Comment by eth0h4ckr** [comment]
Thanks for the quick reply. The error still persists after applying the changes. It looks like the error is being triggered by the fact that `SeaweedFileSystem.java#open()` is returning a `FSDataInputStream` object and` read(ByteBuffer)` is not supported by the default `FSDataInputStream`.
 
Likely open() should return a `SeaweedDataInputStream` that supports the bytebuffer override instead of a native `FSDataInputStream`?
 
Also, 

Looks like the changes that were implemented are in:
    `SeaweedFileSystemStore`
 
Where hdfs is refering directly to:
```
  <property>
    <name>fs.seaweedfs.impl</name>
    <value>seaweed.hdfs.SeaweedFileSystem</value>
  </property>
```
 
Should those changes have been implemented inside of `SeaweedFileSystem `instead of `SeaweedFileSystemStore`?
Or should we change "`fs.seaweedfs.impl`" from "`seaweed.hdfs.SeaweedFileSystem`" to "`seaweed.hdfs.SeaweedFileSystemStore`" ?

**Comment by chrislusf** [comment]
Need to see the stack trace to fix the problem.

How about let's fix it the correct way? Can you teach me how to setup Impala with SeaweedFS by creating a wiki page similar to this? https://github.com/chrislusf/seaweedfs/wiki/run-Spark-on-SeaweedFS 

Or you can add the detailed steps here.

With the case reproduced locally, I should be able to fix it.

**Comment by chrislusf** [comment]
btw: Presto runs fine.

**Comment by jameno123** [comment]
@chrislusf  so tracing this through the stack is fun considering Impala is written in C.  I have had to manually debug the code line by line to build a stack trace for this.


Impala ./be/src/runtime/io/hdfs-monitored-ops.cc calls libhdfs::hdfsOpenFile(fs_, fname_.data(), flags_, 0, 0, blocksize_);
   where fname.data is "seaweedfs://..../file.parquet" and flags is O_RDONLY

Which basically runs:
1.      File f = new File(path);
2.       FSData{Input|Output}Stream f{is|os} = fs.open(f, buffersize);
3.       return f{is|os};

which ultimately calls libhdfs::readDirect(hdfsfs fs, hdfsFile file, chr &buf, 0) 

NOTE: file->file is set to the fsdatainputstream reference

libhdfs::readDirect() then:
1. extracts the fsdatainputstream from the hdfsFile  ("readPrepare")
2. Creates a new ByteBuffer "java/nio/ByteBuffer"
3. calls  fsdatainputstream.read(ByteBuffer) which was returned from SeaweedFilesystem.open()

Inside of fsdatainputstream (./hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/FSDataInputStream.java):

the hdfs/fs/FSDataInputStream#read(ByteBuffer) call then seems to extract the "inputstream"  which i believe is of type "BufferedFSInputStream" defined in SeaweedFileSystem#open()

            return new FSDataInputStream(new BufferedFSInputStream(inputStream, 4 * seaweedBufferSize));

FSDataInputStream#read() then attempts to check for ByteBufferReadable

    if (in instanceof ByteBufferReadable) {
      return ((ByteBufferReadable)in).read(buf);
    }

    throw new UnsupportedOperationException("Byte-buffer read unsupported by input stream");

Where "in" is the inputstream passed to new FSDataInputStream() constructor inside of SeaweedFilesystem#open
 to which it then tries to call "in.read(ByteBuffer)" which seems to ultimately be of type SeaweedInputStream.read()

Thats where im falling down because the check for ByteBufferReadable is basically failing.

So it would seem that the FSDataInputStream is expecting the "BufferedFSInputStream" to implement "ByteBufferReadable" which it does not.

So possibly just need to remove the "new BufferedFSInputStream()" ? and pass directly the SeaweedInputStream????

**Comment by jameno123** [comment]
Just simply removing the BufferedFSInputStream line then caused the following stack trace:

readDirect: FSDataInputStream#read error:
UnsupportedOperationException: java.lang.UnsupportedOperationException
        at java.nio.ByteBuffer.array(ByteBuffer.java:994)
        at seaweed.hdfs.SeaweedInputStream.read(SeaweedInputStream.java:114)
        at org.apache.hadoop.fs.FSDataInputStream.read(FSDataInputStream.java:147)

**Comment by jameno123** [comment]
Ps. were working on creating the setup guide to reproduce the environment. Our environment is currently setup through cloudera manager so its a bit difficult to step-by-step it. We'll have something for you later today.

**Comment by chrislusf** [comment]
> readDirect: FSDataInputStream#read error:
> UnsupportedOperationException: java.lang.UnsupportedOperationException
> at java.nio.ByteBuffer.array(ByteBuffer.java:994)
> at seaweed.hdfs.SeaweedInputStream.read(SeaweedInputStream.java:114)
> at org.apache.hadoop.fs.FSDataInputStream.read(FSDataInputStream.java:147)

Thanks! This is helpful.

**Comment by chrislusf** [comment]
Hi, I added another fix, to use ByteBuffer properly.

You will still need to "removing the BufferedFSInputStream". I am not sure how much perf impact it will be yet.

**Comment by chrislusf** [comment]
ok. Added another fix so you do not need to "removing the BufferedFSInputStream"

**Comment by jameno123** [comment]
This seems to correct the issues with impala and logging of errors but we're still trying to track down where its spending all the cycles.

select count(*) from table where partition = '2020-12-03', total of 733 files results in speeds of the following:

HDFS Native: 22sec
Seaweed: 8min 42sec

Granted a significant amount of this speed loss / delay is coming from the fact that impala is not tuned for seaweed (remote reads) still trying to figure out how to convince impala to open more connections to the filer to read the files. At this point it looks like the seaweed implementation is correct and that the tuning needs to occur inside of impala.

Thank you for your efforts we will open additional bugs as we find more specific details.

**Comment by chrislusf** [comment]
Thanks! Let me know how to setup impala.

**Comment by chrislusf** [comment]
these lines are suspicious

https://sourcegraph.com/github.com/apache/impala/-/blob/be/src/exec/hdfs-table-sink.cc#L402

```
  if (IsS3APath(output_partition->current_file_name.c_str()) ||
      IsABFSPath(output_partition->current_file_name.c_str()) ||
      IsADLSPath(output_partition->current_file_name.c_str()) ||
      IsOzonePath(output_partition->current_file_name.c_str())) {
    // On S3A, the file cannot be stat'ed until after it's closed, and even so, the block
    // size reported will be just the filesystem default. Similarly, the block size
    // reported for ADLS will be the filesystem default. So, remember the requested block
    // size.
    // TODO: IMPALA-9437: Ozone does not support stat'ing a file until after it's closed,
    // so for now skip the call to hdfsGetPathInfo.
    output_partition->block_size = block_size;
  } else {
    // HDFS may choose to override the block size that we've recommended, so for non-S3
    // files, we get the block size by stat-ing the file.
    hdfsFileInfo* info = hdfsGetPathInfo(output_partition->hdfs_connection,
        output_partition->current_file_name.c_str());
    if (info == nullptr) {
      return Status(GetHdfsErrorMsg("Failed to get info on temporary HDFS file: ",
          output_partition->current_file_name));
    }
    output_partition->block_size = info->mBlockSize;
    hdfsFreeFileInfo(info, 1);
  }
```

Seems related to block size. Try to adjust this to a normal number or use default 4MB.

```
<property>
<name>fs.seaweed.buffer.size</name>
<value>134217728</value>
</property>
```

**Comment by chrislusf** [comment]
Maybe hack this way: change `seaweedfs` here to `s3a`:
https://github.com/chrislusf/seaweedfs/blob/master/other/java/hdfs2/src/main/java/seaweed/hdfs/SeaweedFileSystem.java#L42

And use `s3a://filer:port/...` to access SeaweedFS files. Just to test whether it can work better.

**Comment by eth0h4ckr** [comment]
I have written an ansible playbook to deploy an impala environment where you can test this issue. Is this something I can send you privately to run and test on your end? I can send it via slack if that is acceptable.

**Comment by chrislusf** [comment]
slack should be fine.

**Comment by chrislusf** [comment]
This docker compose file is good? https://github.com/ibis-project/docker-impala/blob/master/docker-compose.yml

**Comment by chrislusf** [comment]
You can use the latest 1.6.0 from https://github.com/chrislusf/seaweedfs/wiki/Hadoop-Compatible-File-System
It has support for flush(), which may help for this issue.
