### ISSUE TITLE
use filer api  return result  has no "pid" and "url"

### ISSUE THREAD

**Issue by lzd0805** [chrislusf/seaweedfs#1648]
[root@serve home]# curl -F file=@/home/start1.sh "http://192.168.137.144:8888/path/sh/newname.sh"
{"name":"start1.sh","size":946}
[root@serve home]# curl -F file=@/home/dd.sh "http://192.168.137.144:8888/path/sh/newname.sh"
{"name":"dd.sh"}[
root@serve home]#

**Comment by chrislusf** [comment]
duplicating https://github.com/chrislusf/seaweedfs/issues/1424
