### ISSUE TITLE
Does the method get the fid of all the files in SeaweedFS？

### ISSUE THREAD

**Issue by LoveXiaoLiu** [chrislusf/seaweedfs#1651]
rt @chrislusf

**Comment by chrislusf** [comment]
https://github.com/chrislusf/seaweedfs/blob/master/weed/shell/command_volume_fsck.go

has the example of comparing all fids in the filer with the ones from the volume servers.

**Comment by LoveXiaoLiu** [comment]
> https://github.com/chrislusf/seaweedfs/blob/master/weed/shell/command_volume_fsck.go
> 
> has the example of comparing all fids in the filer with the ones from the volume servers.

I mean is there a good way to get the FID of all the files from the outside of system?

I have such a scenario: I plan to migrate the file data of SeaweedFS to COS, but I have lost the FID of all files, which makes me unable to get all the files. Is there a good way to get the FID of all files, or is there good way to migration file.


tks.
