### ISSUE TITLE
Seaweedfs1.41  volume conflict

### ISSUE THREAD

**Issue by doufighting** [chrislusf/seaweedfs#1653]
**Describe the bug**
I run seaweedfs cluster on 3 server, there has 1.dat, 2.dat ,3.dat ,4.dat ... 350.dat, 351.dat has been created, but nowadays, I found
1.dat has been created again, conflict with the old one, so the file stored on 1.dat cannot be found. What could this be happen?

**Comment by chrislusf** [comment]
what is the version?

**Comment by doufighting** [comment]
server is  Ubuntu 14.04.5 LTS ，seaweedfs version is 1.41, 
server A ：
./weed master -mdir="/data/master" -port=9333 -defaultReplication="100" -ip = "ip1" -peers = "ip1:9333,ip2:9333,ip3:9333" 
./weed volume -dir = "/data/vs_1" -max =30 -mserver="ip1:9333,ip2:9333,ip3:9333" -dataCenter=dc1 -rack=rack1 -port=9080 -ip="ip1"
./weed volume -dir = "/data/vs_2" -max =30 -mserver="ip1:9333,ip2:9333,ip3:9333" -dataCenter=dc1 -rack=rack1 -port=9081 -ip="ip1"
./weed volume -dir = "/data/vs_3" -max =30 -mserver="ip1:9333,ip2:9333,ip3:9333" -dataCenter=dc1 -rack=rack1 -port=9082 -ip="ip1"
./weed volume -dir = "/data/vs_4" -max =30 -mserver="ip1:9333,ip2:9333,ip3:9333" -dataCenter=dc1 -rack=rack1 -port=9083 -ip="ip1"
./weed volume -dir = "/data/vs_5" -max =30 -mserver="ip1:9333,ip2:9333,ip3:9333" -dataCenter=dc1 -rack=rack1 -port=9084 -ip="ip1"
./weed volume -dir = "/data/vs_6" -max =30 -mserver="ip1:9333,ip2:9333,ip3:9333" -dataCenter=dc1 -rack=rack1 -port=9085 -ip="ip1"

server B:
./weed master -mdir="/data/master" -port=9333 -defaultReplication="100" -ip = "ip2" -peers = "ip1:9333,ip2:9333,ip3:9333" 
./weed volume -dir = "/data/vs_1" -max =30 -mserver="ip1:9333,ip2:9333,ip3:9333" -dataCenter=dc2 -rack=rack1 -port=9080 -ip="ip2"
./weed volume -dir = "/data/vs_2" -max =30 -mserver="ip1:9333,ip2:9333,ip3:9333" -dataCenter=dc2 -rack=rack1 -port=9081 -ip="ip2"
./weed volume -dir = "/data/vs_3" -max =30 -mserver="ip1:9333,ip2:9333,ip3:9333" -dataCenter=dc2 -rack=rack1 -port=9082 -ip="ip2"
./weed volume -dir = "/data/vs_4" -max =30 -mserver="ip1:9333,ip2:9333,ip3:9333" -dataCenter=dc2 -rack=rack1 -port=9083 -ip="ip2"
./weed volume -dir = "/data/vs_5" -max =30 -mserver="ip1:9333,ip2:9333,ip3:9333" -dataCenter=dc2 -rack=rack1 -port=9084 -ip="ip2"
./weed volume -dir = "/data/vs_6" -max =30 -mserver="ip1:9333,ip2:9333,ip3:9333" -dataCenter=dc2 -rack=rack1 -port=9085 -ip="ip2"

server C :
./weed master -mdir="/data/master" -port=9333 -defaultReplication="100" -ip = "ip3" -peers = "ip1:9333,ip2:9333,ip3:9333" 
./weed volume -dir = "/data/vs_1" -max =30 -mserver="ip1:9333,ip2:9333,ip3:9333" -dataCenter=dc2 -rack=rack2 -port=9080 -ip="ip3"
./weed volume -dir = "/data/vs_2" -max =30 -mserver="ip1:9333,ip2:9333,ip3:9333" -dataCenter=dc2 -rack=rack2 -port=9081 -ip="ip3"
./weed volume -dir = "/data/vs_3" -max =30 -mserver="ip1:9333,ip2:9333,ip3:9333" -dataCenter=dc2 -rack=rack2 -port=9082 -ip="ip3"
./weed volume -dir = "/data/vs_4" -max =30 -mserver="ip1:9333,ip2:9333,ip3:9333" -dataCenter=dc2 -rack=rack2 -port=9083 -ip="ip3"
./weed volume -dir = "/data/vs_5" -max =30 -mserver="ip1:9333,ip2:9333,ip3:9333" -dataCenter=dc2 -rack=rack2 -port=9084 -ip="ip3"
./weed volume -dir = "/data/vs_6" -max =30 -mserver="ip1:9333,ip2:9333,ip3:9333" -dataCenter=dc2 -rack=rack2 -port=9085 -ip="ip3"

the 1.dat 2.dat has been created on server A /data/vs_1 and server B /data/vs_1 , but recently , I found the 1.dat 2.dat has been created again on  server A /data/vs_6 and server C /data/vs_6, conflict with the old file, I wonder how could this happen.

**Comment by chrislusf** [comment]
Actually I could not think of any reason unless some old bugs. Need some logs to tell.

**Comment by doufighting** [comment]
Is there any limit on volume id? now I have stored 357 dat file. run 14 volume server on one Ubuntu Server

**Comment by chrislusf** [comment]
no limit.
