### ISSUE TITLE
version 2.03 takes too much memory

### ISSUE THREAD

**Issue by duchaomin** [chrislusf/seaweedfs#1654]
I find it takes too much memory while I'am reading images with a weed-mount. Here is the code:
```
total = 0
if __name__ == '__main__':
    BASE_PATH = '/mnt/weeddata/imgs/13020700'
    for index in os.listdir(BASE_PATH):
        path = os.path.join(BASE_PATH, index)
        for file_path in os.listdir(path):
            file_path = os.path.join(path, file_path)
            total += 1
            if total  % 5000 == 0: print(f'total:{total}')
            try:
                im = Image.open(file_path)
            except:
                print(f'error:{file_path}')
```
Well, I just read all  the images(about 50 thousands ) in a folder and it takes 4gb memory.  I have tried some versions and find this problem exists since version 2.03

**Comment by chrislusf** [comment]
I could not reproduce. Could you please use the latest version, 2.14, and run the mount adding this parameter:
`weed mount -dir=... -memprofile=mount.mem.pprof`

And send the mount.mem.pprof files over?

**Comment by chrislusf** [comment]
Added a fix, please help to verify the fix.
