### ISSUE TITLE
2.14: master -peers claims I'm not passing a odd number of peers when actually I do 

### ISSUE THREAD

**Issue by bmillemathias** [chrislusf/seaweedfs#1655]
**Describe the bug**
Launching a master this way (as given in the example in the code https://github.com/chrislusf/seaweedfs/blob/06bb7bf6c00982deb9eae953c85a730a1745c368/weed/command/master.go#L54) `
```
weed master -peers 127.0.0.1:9003,127.0.0.1:9004,127.0.0.1:9005
```
return such error
```
I1208 17:57:36 75589 master.go:168] current: 192.168.27.141:9003 peers:127.0.0.1:9003,127.0.0.1:9004,127.0.0.1:9005    
F1208 17:57:36 75589 master.go:186] Only odd number of masters are supported! 
```                                         

but when launching this way `weed master -peers 127.0.0.1:9003,127.0.0.1:9004`
it works fine

**System Setup**
- List the command line to start "weed master": given above
- OS version: does not matter
- output of `weed version`: version 30GB 2.14 46b9122 linux amd64

**Expected behavior**

**Comment by chrislusf** [comment]
Please set `-ip 127.0.0.1` also. The `-ip` is used to identify itself. If not set, it tried to use your actual ip, `192.168.27.141`, and it is different from any one in the peers list.
