### ISSUE TITLE
Adding a quick explanation of each component

### ISSUE THREAD

**Issue by bmillemathias** [chrislusf/seaweedfs#1657]
**Describe the bug**
I did not find a concise explanation of the different role of component; master, volume and filer (I've have a rough idea of the 2 formers, but I did not found the role of the filer)
I think that would be helpful for new comers, That could be either in a specific document like architecture or perhaps in the FAQ.

best

**Comment by chrislusf** [comment]
How about these explanation?

Volume server: the data storage server hosting multiple volumes, each volume appends small files.
Master: All volume servers send heartbeats to master. The heartbeats have all volume information.
The volume servers and the master form a distributed object store layer.

Filers put the file content to the object store layer. Filer save file meta data, such as file attributes and directories, into filer store, which can be any key-value store, such as Redis/Cassandra/Mysql/Postgresl/ElasticSearch/MongoDB/etcd.

S3 API layer is a simple translation and can be started separately or together with filer.

**Comment by bmillemathias** [comment]
Thanks for the quick reply,

I admit my total lack of knowledge of in seaweedfs, I've just started to play with it yesterday

One potential information I just understand is that the filer provide HTTP end-point to upload/read file with path. Reading the documentation I did not think filer was useful to me, but actually this is the component I needed.
 
Thinking from a top-to-bottom POV and perhaps in direction to  other people being lost when starting, some introduction documentation would be helpful with a general presentation of seaweedfs, and some use-case ("creating a simple storage with HTTP access" for instance)

Sorry my answer is a bit messy,

**Comment by dch** [comment]
Maybe this is more useful/precise for newcomers? Obviously I can't speak for technical accuracy, but I'd like to add a lot more detail like this to s/w over time.

## SeaweedFS Components

seaweedfs comprises 3 main conceptual components, each of which may run on one or more servers or instances:

- master service

The master service works smart, not hard. It represents a raft cluster of 1 (or 3 or more servers) that own a consistent view of the entire seaweedfs cluster and communicate it to all participating nodes, through a raft Leader. The leader assigns file ids, appoints which volumes to store objects in, and owns deciding which nodes are part of the cluster. The number of servers in the master cluster must always be odd, to ensure that a majority consensus can be formed.

> NB I would actually say "1 or 3 more prime numbers" here because that is more sensible. And probably "not more than 7". Or maybe even 5... ?
 
- volume service

The volume service is where the hard work is done. It packs objects (files and chunks of files) efficiently into larger volumes, which can be arbitrarily large blocks on disk. Redundancy and replication of data is managed at the volume level, not on a per-object level.

- filer service

The optional filer service does heavy lifting so you don't have to. It translates seaweedfs volumes and objects, into user-visible paths (like URLs or file systems) over HTTP or UNIX FUSE mounts. While it is not as efficient as the direct object store, it provides a convenient and common abstraction that can be used to provide AWS style S3 buckets, normal looking filesystems, or web servers for down/uploads, to existing applications without modification.


Better? Accurate?

If we can do PRs for the wiki, that would be helpful.

**Comment by chrislusf** [comment]
Thanks! Looks good! It’s great to write from a user’s point of view! We can
tweak the details later. The wiki is open to everyone.

**Comment by dch** [comment]
I added this https://github.com/chrislusf/seaweedfs/wiki/Overview

@chrislusf I leave it to you to decide where/how to link it in under `Getting Started` section.
@bmillemathias feel free to edit or suggest further improvements

**Comment by chrislusf** [comment]
Thanks! I moved it to https://github.com/chrislusf/seaweedfs/wiki/Components and added link to it from the wiki sidebar.
