### ISSUE TITLE
[filer] add -dir equivalent to command-line

### ISSUE THREAD

**Issue by bmillemathias** [chrislusf/seaweedfs#1659]
**Describe the bug**
master and volume have a `-dir` or `-mdir` that can be passed to command when launching, that would be nice to have the same for the filer .

Best.

**Comment by bmillemathias** [comment]
As of now, filer creates files in `$CWD` which can dangerous, because it may be set to / (for instance on systemd).

**Comment by chrislusf** [comment]
Agree.
