### ISSUE TITLE
several seaweedfs cluster data combine

### ISSUE THREAD

**Issue by doufighting** [chrislusf/seaweedfs#1660]
I have run several seaweedfs cluster on different places. Now  I want to combine the data of these seaweedfs to a center cluster, is there any easy way for me to do this ?
您好，我在多个地方分别部署了seaweedfs集群，现在我单独建了一个中心集群，希望把这些集群的数据融合到这个中心集群中，如果直接把各个集群的dat文件拷贝到中心集群，由于每个集群的数据都是从1.dat 2.dat 顺序开始的，全拷贝到中心集群后，dat文件必定会冲突。目前我只能把各个地方的seaweedfs数据抽取出来重新写入到中心集群中，有没有更简便的方法可以实现这一目的。

**Comment by chrislusf** [comment]
the data is addressed by volume ids. So they can not sit together unless you change all file ids.
