### ISSUE TITLE
Even under different collections, the file names cannot be same

### ISSUE THREAD

**Issue by earthdiaosi** [chrislusf/seaweedfs#1661]
**Describe the bug**
Even under different collections, the file names cannot be same
```
$ cat hello.txt 
hello world!

$ curl -F file=@hello.txt "http://localhost:8888/tmp/?collection=c1"
{"name":"hello.txt","size":13}

$ curl "http://localhost:8888/tmp/hello.txt?collection=c1"
hello world!

$ echo "hello world! 2" > hello.txt
$ cat hello.txt 
hello world! 2

$ curl -F file=@hello.txt "http://localhost:8888/tmp/?collection=c2"
{"name":"hello.txt","size":15}

$ curl "http://localhost:8888/tmp/hello.txt?collection=c2"
hello world! 2

$ curl "http://localhost:8888/tmp/hello.txt?collection=c1"
hello world! 2
```

**System Setup**
- weed -v=4 filer -port=8888 -master=127.0.0.1:9333
- weed -v=4 volume -max=100 -mserver="127.0.0.1:9333" -dir="./data"
- weed -v=4 master -mdir="./master" -defaultReplication=000
- darwin amd64
- version 30GB 2.11 98827d6 darwin amd64
- none

**Expected behavior**
- the content of `hello.txt` in collection `c1` is `hello world!`.
- the content of `hello.txt` in collection `c2` is `hello world! 2`

**Screenshots**

**Additional context**

**Comment by chrislusf** [comment]
This is expected. 

Collection is not a folder, it is just one storage format, just similar to whether the content is replicated or not. The file name has nothing to do with the collection.
