### ISSUE TITLE
[documentation] Explain what is a collection and their properties

### ISSUE THREAD

**Issue by bmillemathias** [chrislusf/seaweedfs#1662]
**Describe the bug**
Collection are mentioned in different part of the wiki but without defining in one place what are they and what are their feature.

some questions I have around that will discovering seaweedfs (but there is more to say without doubt)
- is it just a simple namespacing mechanism ? 
- do collection have their specific volumes ?
- specific parameters for collection (replication, ...)

I hope it bring some value.

Best.

**Comment by chrislusf** [comment]
* Collection is just a group of volumes.
* Collection can have volumes with different TTLs, volumes with different replications.

**Comment by chrislusf** [comment]
btw: Maybe you can help to add your understandings to this page, https://github.com/chrislusf/seaweedfs/wiki/Components , from a beginner's POV.

**Comment by chrislusf** [comment]
Added some info to https://github.com/chrislusf/seaweedfs/wiki/Components
