### ISSUE TITLE
have a config file for shell 

### ISSUE THREAD

**Issue by bmillemathias** [chrislusf/seaweedfs#1664]
**Describe the bug**
that would simplify the use of weed shell if it could use a toml file where the master(s) and the filer(s) are already specified to avoid passing these parameters each time
another idea I have is the idea of having the possibility to be able to define several setups and giving a name (prod, devel) and be able to do a `weed shell -cluster prod`

Hope it makes sense.

best.

**Comment by chrislusf** [comment]
Make sense. But I want to avoid config files if possible. Specifically `weed shell`, seems you can easily create a script as
```
weed shell -master=... -filer=...
```
And name it as `weed_shell.prod.sh`

If creating a separate config file `prod.toml`,
```
master=...
filer=...
```
seems about the same amount of work.

Or we can support env variables for master and filer.

**Comment by antitbone** [comment]
Maybe a single configuration file ```shell.toml```

```
default_cluster=conf1

[conf1]
master=...
filer=...

[conf2]
master=...
filer=...
```

```weed shell``` go to default_cluster
or -cluster option```weed shell -cluster conf2```
