### ISSUE TITLE
Have all parameters being in configuration files

### ISSUE THREAD

**Issue by bmillemathias** [chrislusf/seaweedfs#1665]
**Describe the bug**
some parameters are exposed only in the configuration file, some parameters are exposed only on the command-line, that would good if all parameters exposed to command-line could be set in the configuration file to avoid extra-long cmdline (important thing like replication.
Or perhaps that would be simplier in the code for each setting this is either possible to set it in configuration file or in command-line.
in thr event of both are set, command-line would take offer option set in configuration.

For those using systemd that would also avoid having to run "systemd reload" to take into account change done on the systemd unit files before restarting the unit.

**Comment by dch** [comment]
Some related examples

- parameter names vary if you're running `master`not`server` -- `-master.peers=...` becomes `-peers=...` etc this is *extremely confusing* to be certain you're putting data in the right places
- there are many apparently overlapping `-dir ...` settings, at first glance its not clear which ones override others

**Comment by chrislusf** [comment]
The parameter names are related to legacy reasons. It is not good to revamp all the parameters which may cause more confusion.

Having parameters set in configuration files will basically add one additional place to set the parameters. It will be harder to tell which value is taking effect.

**Comment by dch** [comment]
I understand. How can we make this more clear then?

- make it clear in the wiki that config files should be used in preference to command line parameters
- make it clear in the wiki which command line parameters aren't found in config files
- maybe in some arbitrary future version, issue a deprecation warning for any command-line parameters that are duplicated in config files

**Comment by chrislusf** [comment]
fixed in https://github.com/chrislusf/seaweedfs/pull/1823

see see https://github.com/chrislusf/seaweedfs/wiki/Use-Config-File-for-Command-Line-Options
