### ISSUE TITLE
/etc/filer.conf naming or location too generic

### ISSUE THREAD

**Issue by bmillemathias** [chrislusf/seaweedfs#1666]
**Describe the bug**

(sorry to bug you about stupid thing)

Looking at the code I saw the filer can use a configuration file set in `/etc/filer.conf` but the path is a bit too generic (still my infrastructure hat on) when someone review files in the /etc directory
That would be better to have a path like `/etc/seaweedfs/filer.conf` (to use the already supported directory).

Best.

**Comment by chrislusf** [comment]
thanks! changed.
