### ISSUE TITLE
any fs.configure command is giving an error message

### ISSUE THREAD

**Issue by bmillemathias** [chrislusf/seaweedfs#1667]
**Describe the bug**

I'm trying to run what is described on https://github.com/chrislusf/seaweedfs/wiki/Path-Specific-Configuration but every operation is failing. Perhaps Iḿ not understanding something. Did I missed something ?
```
> bucket.create -name short-live
> bucket.list
  short-live
> fs.ls /buckets
short-live
> fs.configure -apply  -ttl 10m -locationPrefix=/buckets/short-live
error: filer: no entry is found in filer store

# Actually even fs.configure is grumpy
> fs.configure
error: filer: no entry is found in filer store
```

**System Setup**
3 masters, 3 volumes, 3 filers mo other component set up (db for instance)
```
weed version
version 30GB 2.14 46b9122 linux amd64
```

**Comment by chrislusf** [comment]
This should have been fixed in recent commits. Please try it with https://github.com/chrislusf/seaweedfs/releases/tag/dev

**Comment by bmillemathias** [comment]
> This has been fixed in recent commits. Please try it with https://github.com/chrislusf/seaweedfs/releases/tag/dev

I've at the mentionned page but the artefacts dates from Nov 4th so and comparing dev to 2.14 github UI I see no additional code in the `dev`tag. Am I missing something ?

**Comment by bmillemathias** [comment]
> > This has been fixed in recent commits. Please try it with https://github.com/chrislusf/seaweedfs/releases/tag/dev
> 
> I've looked at the aformentioned page but the artifact dates from Nov 4th so and comparing dev to 2.14 github UI I see no additional code in the `dev`tag. Am I missing something ?

**Comment by chrislusf** [comment]
it has the latest built from git master HEAD, delayed by 4 minutes.

**Comment by GarinQian** [comment]
Encountered the same problem, I create a `file.conf` file with the given JSON format in the folder /etc/, and then bypass this problem.

**Comment by chrislusf** [comment]
Closing this. Here is the output I have for a fresh new cluster with 2.15.

```
> fs.configure
{

}
> bucket.create -name short-live
create bucket under /buckets
created bucket short-live
> bucket.list
  short-live
> fs.ls /buckets
short-live
> fs.configure -apply  -ttl 10m -locationPrefix=/buckets/short-live
{
  "locations": [
    {
      "locationPrefix": "/buckets/short-live",
      "ttl": "10m"
    }
  ]
}
> fs.configure
{
  "locations": [
    {
      "locationPrefix": "/buckets/short-live",
      "ttl": "10m"
    }
  ]
}
>
```
