### ISSUE TITLE
Filer文件系统如何复制和移动

### ISSUE THREAD

**Issue by lze693** [chrislusf/seaweedfs#1668]
如何把已经存在文件系统中的文件复制或移动到其他目录中

**Comment by chrislusf** [comment]
You can use `weed mount` to move or copy.

Haven't figured out an easy way to do it via HTTP API.

**Comment by lze693** [comment]
我看您filer 的数据结构是这样的：
[postgres] # or cockroachdb
# CREATE TABLE IF NOT EXISTS filemeta (
#   dirhash     BIGINT,
#   name        VARCHAR(65535),
#   directory   VARCHAR(65535),
#   meta        bytea,
#   PRIMARY KEY (dirhash, name)
# );

复制接口时 比如 POST /path/to/file?copy= /new_path/to/file
只需要将filemeta 表中这条记录复制一下 更改 dirhash，name，directory即可

移动接口时 比如 POST /path/to/file?move= /new_path/to/file
只需要将filemeta 表中这条记录更改 dirhash，name，directory即可

可能会改变删除时的逻辑

**Comment by lze693** [comment]
我看了您的表结构是下面这样的：
CREATE TABLE IF NOT EXISTS filemeta (
  dirhash     BIGINT,
  name        VARCHAR(65535),
  directory   VARCHAR(65535), 
  meta        bytea,
  PRIMARY KEY (dirhash, name)
 );
是否可以如下实现：
复制接口时例如POST / path / to / file？copy = / new_path / to / file 只需filemeta表中这条记录复制一下更改dirhash，名称，目录即可

POST / path / to / file？move = / new_path / to / file 只需将filemeta表中这条记录更改dirhash，名称，目录即可

可能会改变删除时的逻辑

**Comment by chrislusf** [comment]
Yes. If you know the dirhash.

**Comment by lze693** [comment]
不知能否实现下呢 哥 为了保证同样MD5的文件只存在一份

**Comment by chrislusf** [comment]
what API do you want? It is already implemented in `weed mount`, `weed shell`, Hadoop.

**Comment by lze693** [comment]
1.因为我发现用mount 复制weed文件系统中已经存在的文件到weed文件系统其他目录volume数据大小会增加  
2.使用了postgres mount 重命名文件重命名不了
3.如何更改了postgres数据库数据 如何更新mount的缓存呢

**Comment by chrislusf** [comment]
> 1.因为我发现用mount 复制weed文件系统中已经存在的文件到weed文件系统其他目录volume数据大小会增加

This is expected.

> 2.使用了postgres mount 重命名文件重命名不了

Sounds a bug. Please create an issue for this, with reproducing steps.

> 3.如何更改了postgres数据库数据 如何更新mount的缓存呢

Sounds the same question for item 2.
