### ISSUE TITLE
files with deleted immediatly because of lastModified being wrongly set in the past (TZ difference between client and master)

### ISSUE THREAD

**Issue by bmillemathias** [chrislusf/seaweedfs#1669]
**Describe the bug**
I've started to play with ttl on collection and it appeared that even I set a ttl to 1h, files and volumes hosting them get removed immediately

files where uploaded from my workstation (which is **NOT** in the cluster) this way
```
weed upload -dir pictures/ -collection pictures_ttl_1h -ttl 1h -master xxx.xxx.xxx.xxx:9333
```
Date of the workstation
```
[me@workstation]$ date
Fri Dec 11 10:59:00 CET 2020
```

After digging the log I saw this
```
Dec 11 09:59:24 bmm-2 weed[3281]: I1211 09:59:24  3281 volume.go:208] now:1607680764 lastModified:1607672240
Dec 11 09:59:24 bmm-2 weed[3281]: I1211 09:59:24  3281 volume.go:210] ttl:1h lived:142
```
(the log could be improved to have the volume related to the entry)
```
root@bmm-2:~# date -d @1607672240 # lastModified
Fri Dec 11 07:37:20 UTC 2020
root@bmm-2:~# date -d @1607680764 # now
Fri Dec 11 09:59:24 UTC 2020
```
the files where just uploaded, so I don't understand the value of `lastModified`.
All servers are NTP-synced and have the same date.

Could it be because of the different time (not taking into account that workstation is in CET and servers are in UTC)?

**Comment by chrislusf** [comment]
the server is using the file's own last modified time to determine the age of the file.

Changed to use upload time.
