### ISSUE TITLE
Support for logging to Graylog

### ISSUE THREAD

**Issue by sachinwalia2k8** [chrislusf/seaweedfs#167]
I have started using WeedFS recently and really love it. It solved the problem I am trying to solve for quite some time with extremely easy setup.

We use graylog for all kinds of application and server logging. One thing I'd like to see in WeedFS is support for graylog. 

Unfortunately my skills in Go are next to none. Good news is there is already a Go client available for Graylog if someone wants to take a stab at it:

https://github.com/Graylog2/go-gelf

thanks.

**Comment by chrislusf** [comment]
This request is very specific. I guess this could be done by some generic log redirecting tool later.

**Comment by virtuallynathan** [comment]
Graylog takes any number of types of logging, including syslog. Someone could go through and use a go syslog package to add a flag in the command line for "log to syslog". If i recall, this one worked OK: https://github.com/mcuadros/go-syslog, and https://github.com/nathanaelle/syslog5424 also seems like it would work.

**Comment by chrislusf** [comment]
There has been not enough interest in this.
