### ISSUE TITLE
dev: filer/s3 apparent bucket delete performance regression

### ISSUE THREAD

**Issue by ginkel** [chrislusf/seaweedfs#1670]
**Describe the bug**

Hi Chris,

I am putting the remarks from https://github.com/chrislusf/seaweedfs/issues/1656#issuecomment-742544295 into a separate issue as the problem is most likely not directly related to #1656. 

Attempting to recursively delete a bucket that contains ~ 3.7 million files takes hours to complete (actually I interrupted the process after three hours when around 50% of the bucket's content was still in place).

This regression may be related to the change committed with https://github.com/chrislusf/seaweedfs/commit/0d345ac97d941bef0991c0cb08632ccf08c0ee83. Having a look at SeaweedFS and Node Exporter metrics in Grafana one can see that the `prefixList` (and consequently the `DELETE`) operation is taking really long. CPU is utilized nearly 100%. I/O load is very low.

![image](https://user-images.githubusercontent.com/174129/101890499-0edbee80-3ba1-11eb-9d72-957a4528b0fc.png)

![image](https://user-images.githubusercontent.com/174129/101891619-970ec380-3ba2-11eb-8e6e-3ac6114c6f90.png)

**System Setup**
```
weed master -mdir=/data -volumePreallocate -volumeSizeLimitMB=1024 -ip=10.132.0.35 -mdir=/data -peers=10.132.0.35:9333,10.132.15.228:9333,10.132.0.39:9333 -defaultReplication=002 -volumeSizeLimitMB=256
weed volume -dir=/data -max=0 -ip=10.132.0.35 -mserver=10.132.0.35:9333,10.132.15.228:9333,10.132.0.39:9333 -dataCenter=dc -rack=rack -dir=/data0,/data1 -metricsPort=9080
weed filer -ip=10.132.0.35 -master=10.132.0.35:9333,10.132.15.228:9333,10.132.0.39:9333 -peers=10.132.0.35:8888,10.132.15.228:8888,10.132.0.39:8888,10.132.0.38:8888 -metricsPort=9088 -s3 -s3.config=/etc/seaweedfs/s3.json

# uname -a
Linux instance-seaweedfs-0 5.4.0-1030-gcp #32-Ubuntu SMP Fri Nov 13 12:13:03 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

# weed version
version 30GB 2.14 3fedfec1 linux amd64
```

Thanks! :-)

**Expected behavior**
The bucket delete should complete in a much shorter timeframe (comparable to the time it takes to `PUT` the files, which is around 26 minutes for the test data).

**Additional context**
Bucket delete is performed via:

```
rclone \
  --cache-db-purge \
  --auto-confirm \
  --fast-list \
  --checkers 40 \
  --transfers 40 \
  purge target:/<bucket>/
```

`filer.toml`:

```
[filer.options]
# with http DELETE, by default the filer would check whether a folder is empty.
# recursive_delete will delete all sub folders and files, similar to "rm -Rf"
recursive_delete = false
# directories under this folder will be automatically creating a separate bucket
buckets_folder = "/buckets"
buckets_fsync = [          # a list of buckets with all write requests fsync=true
        "important_bucket",
        "should_always_fsync",
]

####################################################
# The following are filer store options
####################################################

[leveldb2]
# local on disk, mostly for simple single-machine setup, fairly scalable
# faster than previous leveldb, recommended.
enabled = true
dir = "/data"                                       # directory to store level db files
```

**Comment by chrislusf** [comment]
Ack.

Could you test what’s the speed to remove the bucket? E.g., aws s3 rb
s3://thebucket

**Comment by ginkel** [comment]
`aws s3 rb` is a blazing fast 45s:

```
root@client-seaweedfs-0:~# time aws s3 --endpoint=http://seaweedfs-int.<domain>e rb s3://konserve
remove_bucket: konserve

real    0m44.741s
user    0m0.495s
sys     0m0.065s
```

**Comment by chrislusf** [comment]
How about disable this "check empty folder" by default? It was added for #1637 @Kmlebedev

**Comment by chrislusf** [comment]
move "delete-directory-if-empty" to read time

**Comment by ginkel** [comment]
Works like a charm, thanks a lot!

**Comment by chrislusf** [comment]
Thanks for the update! How long does it take now?

**Comment by ginkel** [comment]
15 minutes. Still worse than `aws s3 rb`, but for compliant clients that assume that non-empty buckets cannot be deleted, I think it is ok.
