### ISSUE TITLE
2.13: With the same start parameters, the Linux version can start normally, but the Windows version cannot

### ISSUE THREAD

**Issue by GarinQian** [chrislusf/seaweedfs#1671]
**Describe the bug**
With the same start parameters, the Linux version can start normally, but the Windows version cannot.

**System Setup**
on windows:
.\weed.exe server --master.port=9333 --volume.port=9222 --volume.max=200 --filer --filer.port=9111 --dir="D:\weed\seaweedfs"
on CentOS7.4:
./weed server -master.port=9333 -volume.port=9222 -volume.max=200 -filer -filer.port=9111 -dir="./data"

- OS version
  version 30GB 2.13 0e99531 windows amd64
  version 30GB 2.13 0e99531 linux amd64

- if using filer, show the content of `filer.toml`
  [mysql]  # or tidb
  enabled = true
  hostname = "localhost"
  port = 3306
  username = "user1"
  password = "password1"
  database = "database1"              # create or use an existing database
  connection_max_idle = 2
  connection_max_open = 100
**Expected behavior**
   successfully visit  http://127.0.0.1:9111

**Screenshots**
on win10:
![image](https://user-images.githubusercontent.com/30383019/101905741-db29b480-3bf2-11eb-9e96-5e33db2a4561.png)
![image](https://user-images.githubusercontent.com/30383019/101906632-37d99f00-3bf4-11eb-88d4-6d5950f0da7d.png)

on centos7.4:
![image](https://user-images.githubusercontent.com/30383019/101905945-2774f480-3bf3-11eb-8e97-e979164a56b5.png)
![image](https://user-images.githubusercontent.com/30383019/101906699-5770c780-3bf4-11eb-987c-21b02be616a3.png)

**Comment by chrislusf** [comment]
> on windows:
> .\weed.exe server --master.port=9333 --volume.port=9222 --volume.max=200 --filer --filer.port=9111 --dir="D:\weed\seaweedfs"

can you use single dash instead of double dash?

**Comment by GarinQian** [comment]
不好意思之前表述的不太清楚，问题不是一个-和两个--，问题是windows启动的时候没指定ip和ip.bind，出现了如上面第一个截图中的获取到本地IP（10.122.0.154:9333）作为master，但是当时ipconfig出来并没有这个ip。今天又试了一下同样的步骤又没有复现了。

**Comment by chrislusf** [comment]
Thanks for the update!

**Comment by GarinQian** [comment]
昨天在家里没有复现，今天来公司办公室测试了一下，遇到了同样的问题。应该是跟公司的网络环境有关，我重新表述一下问题：

版本：version 30GB 2.13 0e99531 windows amd64

启动方式（并不是-和--的问题，windows上参数必须是--才能识别）：
方式一：.\weed.exe server --master.port=9333 --volume.port=9222 --volume.max=200 --filer --filer.port=9111 --dir="D:\weed\seaweedfs"
方式二：.\weed.exe server --ip=localhost --ip.bind=localhost --master.port=9333 --volume.port=9222 --volume.max=200 --filer --filer.port=9111 --dir="D:\weed\seaweedfs"

现象：方式二正常启动；方式一启动失败。
方式一失败原因：获取到本地IP（10.122.0.154:9333）作为master，但是10.122.0.154并不在本地网卡的IP列表里，也不在路由表的IP列表中。本地网卡IP和路由表情况见最后的截图。

测试：尝试把/weed/util/network/DetectedHostAddress修改为如下，则可以正常获取到本地IP：
func DetectedHostAddress() string {
	netInterfaces, err := net.Interfaces()
	if err != nil {
		glog.V(0).Infof("failed to detect ip address: %v", err)
		return ""
	}

	for i := 0; i < len(netInterfaces); i++ {
		if (netInterfaces[i].Flags & net.FlagUp) != 0 {
			addrs, _ := netInterfaces[i].Addrs()

			for _, address := range addrs {
				if ipnet, ok := address.(*net.IPNet); ok && !ipnet.IP.IsLoopback() {
					if ipnet.IP.To4() != nil {
						return ipnet.IP.String()
					}
				}
			}
		}
	}

	return "localhost"
}

IPconfig的结果：
C:\Users\jialin.qian>ipconfig /all

Windows IP 配置

   主机名  . . . . . . . . . . . . . : D-R305J3M3
   主 DNS 后缀 . . . . . . . . . . . : digital.envision.com
   节点类型  . . . . . . . . . . . . : 混合
   IP 路由已启用 . . . . . . . . . . : 否
   WINS 代理已启用 . . . . . . . . . : 否
   DNS 后缀搜索列表  . . . . . . . . : envisioncn.com
                                       digital.envision.com

以太网适配器 以太网:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . :
   描述. . . . . . . . . . . . . . . : Realtek PCIe GBE Family Controller
   物理地址. . . . . . . . . . . . . : A8-1E-84-B0-5E-3C
   DHCP 已启用 . . . . . . . . . . . : 否
   自动配置已启用. . . . . . . . . . : 是

无线局域网适配器 本地连接* 9:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . :
   描述. . . . . . . . . . . . . . . : Microsoft Wi-Fi Direct Virtual Adapter
   物理地址. . . . . . . . . . . . . : 94-B8-6D-E5-E4-D1
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是

无线局域网适配器 本地连接* 10:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . :
   描述. . . . . . . . . . . . . . . : Microsoft Wi-Fi Direct Virtual Adapter #2
   物理地址. . . . . . . . . . . . . : 96-B8-6D-E5-E4-D0
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是

以太网适配器 VMware Network Adapter VMnet1:

   连接特定的 DNS 后缀 . . . . . . . :
   描述. . . . . . . . . . . . . . . : VMware Virtual Ethernet Adapter for VMnet1
   物理地址. . . . . . . . . . . . . : 00-50-56-C0-00-01
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是
   本地链接 IPv6 地址. . . . . . . . : fe80::e061:4136:6f54:d89a%6(首选)
   IPv4 地址 . . . . . . . . . . . . : 192.168.70.1(首选)
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   获得租约的时间  . . . . . . . . . : 2020年12月14日 9:58:11
   租约过期的时间  . . . . . . . . . : 2020年12月14日 12:58:09
   默认网关. . . . . . . . . . . . . :
   DHCP 服务器 . . . . . . . . . . . : 192.168.70.254
   DHCPv6 IAID . . . . . . . . . . . : 838881366
   DHCPv6 客户端 DUID  . . . . . . . : 00-01-00-01-26-EC-18-47-A8-1E-84-B0-5E-3C
   DNS 服务器  . . . . . . . . . . . : fec0:0:0:ffff::1%1
                                       fec0:0:0:ffff::2%1
                                       fec0:0:0:ffff::3%1
   TCPIP 上的 NetBIOS  . . . . . . . : 已启用

以太网适配器 VMware Network Adapter VMnet8:

   连接特定的 DNS 后缀 . . . . . . . :
   描述. . . . . . . . . . . . . . . : VMware Virtual Ethernet Adapter for VMnet8
   物理地址. . . . . . . . . . . . . : 00-50-56-C0-00-08
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是
   本地链接 IPv6 地址. . . . . . . . : fe80::852a:450f:fe2:395f%21(首选)
   IPv4 地址 . . . . . . . . . . . . : 192.168.192.1(首选)
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   获得租约的时间  . . . . . . . . . : 2020年12月14日 9:58:02
   租约过期的时间  . . . . . . . . . : 2020年12月14日 12:58:03
   默认网关. . . . . . . . . . . . . :
   DHCP 服务器 . . . . . . . . . . . : 192.168.192.254
   DHCPv6 IAID . . . . . . . . . . . : 855658582
   DHCPv6 客户端 DUID  . . . . . . . : 00-01-00-01-26-EC-18-47-A8-1E-84-B0-5E-3C
   DNS 服务器  . . . . . . . . . . . : fec0:0:0:ffff::1%1
                                       fec0:0:0:ffff::2%1
                                       fec0:0:0:ffff::3%1
   主 WINS 服务器  . . . . . . . . . : 192.168.192.2
   TCPIP 上的 NetBIOS  . . . . . . . : 已启用

无线局域网适配器 WLAN:

   连接特定的 DNS 后缀 . . . . . . . :
   描述. . . . . . . . . . . . . . . : Intel(R) Dual Band Wireless-AC 3165
   物理地址. . . . . . . . . . . . . : 94-B8-6D-E5-E4-D0
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是
   本地链接 IPv6 地址. . . . . . . . : fe80::659d:14a7:8ba7:d1e3%22(首选)
   IPv4 地址 . . . . . . . . . . . . : 10.229.55.28(首选)
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   获得租约的时间  . . . . . . . . . : 2020年12月14日 9:59:25
   租约过期的时间  . . . . . . . . . : 2020年12月14日 12:47:45
   默认网关. . . . . . . . . . . . . : 10.229.55.1
   DHCP 服务器 . . . . . . . . . . . : 10.229.55.1
   DHCPv6 IAID . . . . . . . . . . . : 328513645
   DHCPv6 客户端 DUID  . . . . . . . : 00-01-00-01-26-EC-18-47-A8-1E-84-B0-5E-3C
   DNS 服务器  . . . . . . . . . . . : 10.86.11.76
                                       10.93.64.115
                                       10.81.2.203
   TCPIP 上的 NetBIOS  . . . . . . . : 已启用

以太网适配器 蓝牙网络连接:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . :
   描述. . . . . . . . . . . . . . . : Bluetooth Device (Personal Area Network)
   物理地址. . . . . . . . . . . . . : 94-B8-6D-E5-E4-D4
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是
ROUTER PRINT的结果：
![image](https://user-images.githubusercontent.com/30383019/102049816-92554400-3e1c-11eb-8234-ac1bd35fce45.png)

**Comment by chrislusf** [comment]
set `-ip`

**Comment by GarinQian** [comment]
嗯我现在加了-ip。我之前看你这边提供了默认获取本机地址，就没有设置-ip。可以考虑完善一下DetectedHostAddress，正确获取本地的可用IP。

**Comment by chrislusf** [comment]
Thanks for the suggestion! Added https://github.com/chrislusf/seaweedfs/commit/021358749bbce20a6d2563506e9f905ef041d8cc

You are welcome to make a PR later!

**Comment by GarinQian** [comment]
Thanks for the quick response. I will try it later. By the way, do you have any discussion groups? Sometimes, as users, we can find someone to discuss and exchange experience when we encounter problems.

**Comment by chrislusf** [comment]
you can use slack.

there is also two wechat groups. My wechat account is `chrislusf`
