### ISSUE TITLE
2.13: Unreachable links

### ISSUE THREAD

**Issue by GarinQian** [chrislusf/seaweedfs#1672]
There is a QR code on the page. When there are many files, the QR code blocks the file link at the bottom, making it really difficult to click to download the file. >_<
![image](https://user-images.githubusercontent.com/30383019/101909533-943ebd80-3bf8-11eb-8474-77bda1fd776c.png)

**Comment by chrislusf** [comment]
you can scroll down and the qr code will move down, right?
