### ISSUE TITLE
Filer文件系统 使用postgres作为存储介质出现的相关问题

### ISSUE THREAD

**Issue by lze693** [chrislusf/seaweedfs#1673]
1.mount挂载到本地后用winscp上传到该目录 告诉我xx文件无法被重命名到目标文件 然后删除这个文件也无法删除
![1](https://user-images.githubusercontent.com/26832376/101977586-605fa880-3c89-11eb-959b-34e0fb7c9616.png)
![2](https://user-images.githubusercontent.com/26832376/101977590-635a9900-3c89-11eb-9810-d602604958e9.png)
2..mount挂载到本地后无法对其中的文件进行重命名报错
![3](https://user-images.githubusercontent.com/26832376/101977848-7cfce000-3c8b-11eb-9b1a-47125aae1649.png)
3.我想通过修复数据库数据来达到将已经存在的数据快速移动快速复制的功能，但增加完数据后，s3和filer能快速看到，而mount不能看到
![11](https://user-images.githubusercontent.com/26832376/101978163-fac1eb00-3c8d-11eb-93f0-cb73266a83a6.png)
![13](https://user-images.githubusercontent.com/26832376/101978165-fbf31800-3c8d-11eb-97a6-bf6fd3dc71bb.png)
![22](https://user-images.githubusercontent.com/26832376/101978166-fc8bae80-3c8d-11eb-95da-278131e96790.png)

**Comment by chrislusf** [comment]
I can not reproduce with your description. Please have exact setup details,
command lines, versions, etc. And did you try it with other filer stores?

**Comment by lze693** [comment]
版本：version 8000GB 2.05 898db14 linux amd64
系统版本：CentOS Linux release 7.6.1810 (Core)
相关命令：
              weed_master：/home/admin/data/seaweedfs/weed -logdir=/home/admin/data/seaweedfs/logs -v=1 master -mdir=/home/admin/data/seaweedfs/master_data -ip=192.168.35.202 -port=9333
             weed_volume：/home/admin/data/seaweedfs/weed -logdir=/home/admin/data/seaweedfs/logs -v=1 volume -dir=/home/admin/data/seaweedfs/volume_data -max=100000000 -mserver=192.168.35.202:9333 -ip=192.168.35.202 -port=9000 -index=leveldb
             weed_filer：/home/admin/data/seaweedfs/weed -logdir=/home/admin/data/seaweedfs/logs -v=1 filer -master=192.168.35.202:9333 -ip=192.168.35.202 -port=8888  -maxMB=1024
             weed_s3：/home/admin/data/seaweedfs/weed -logdir=/home/admin/data/seaweedfs/logs -v=1 s3 -filer=192.168.35.202:8888 -config=/home/admin/data/seaweedfs/config.json -port=8333
             weed_mount：/home/admin/data/seaweedfs/weed -logdir=/home/admin/data/seaweedfs/logs -v=1 mount -filer=192.168.35.202:8888 -dir=/home/admin/data/seaweedfs/mount_data  -cacheDir=/home/admin/data/seaweedfs/mount_cache
            /etc/seaweedfs/filer.toml 文件
          [postgres] # or cockroachdb
          # CREATE TABLE IF NOT EXISTS filemeta (
          #   dirhash     BIGINT,
          #   name        VARCHAR(65535),
          #   directory   VARCHAR(65535),
          #   meta        bytea,
          #   PRIMARY KEY (dirhash, name)
          # );
         enabled = true
         hostname = "192.168.35.110"
         port = 5432
         username = "postgres"
         password = "123"
         database = "test"              # create or use an existing database
         sslmode = "disable"
         connection_max_idle = 100
         connection_max_open = 100             
          
        操作步骤：
        第一个问题：用winscp上传数据会报错 因为winscp是断点续传 上传完后会重命名
        第二个问题：用s3上传个文件后能在挂载中看见 对其重命名报错
        第三个问题：打开数据复制其中一条数据并修改其文件名 s3能立马看到 挂载一直看不到

**Comment by chrislusf** [comment]
Is this reproducible with latest version?
Is this reproducible with other filer stores?
Does it happen for all the files uploaded?

**Comment by lze693** [comment]
报错的 错误是 重复键违反唯一约束"filemeta_pkey"

**Comment by lze693** [comment]
使用了最新版 version 8000GB 2.15 813453f linux amd64 和前面版本一样报下面错误：
insert entry /world.tif: setHardLink [204 14 184 159 65 7 250 128 180 36 81 37 110 165 147 17 1]: kv insert: pq: 重复键违反唯一约束"filemeta_pkey"

leveldb没这个问题

**Comment by chrislusf** [comment]
Thanks for the details. I added a fix. It was because the error was not in english, so the error reporting is wrong.
