### ISSUE TITLE
Rocksdb vs leveldb

### ISSUE THREAD

**Issue by nivekuil** [chrislusf/seaweedfs#1675]
Hi, thanks for writing SeaweedFS. I was curious about the choice to use LevelDB as the storage backend for a few components. Most projects I see prefer RocksDB, the Facebook-developed fork. I don't know what technical advantages there are in this case, but I believe Rocks is generally preferred because it's actively developed, and some talk around LevelDB having a bad reputation with data corruption at scale.

**Comment by chrislusf** [comment]
RocksDB is in C++. If there is a pure Go port, SeaweedFS can use it too.

SeaweedFS is using go version of leveldb.
