### ISSUE TITLE
collection delete must require -name

### ISSUE THREAD

**Issue by bmillemathias** [chrislusf/seaweedfs#1677]
**Describe the bug**
I don't know if a lot of people are using the collection `""` (honestly I would prefer to have a real name like `default` for the built-in collection) but I discovered that `collection.delete -force` without specifying parameter `-name` deletes it which I find a bit dangerous.
What do you think about that ?

**System Setup**
- output of `weed version`: 2.15

**Expected behavior**
Have to set explicitly the parameter `-name` when deleting a collection

**Comment by chrislusf** [comment]
Yes! It is a dangerous command to play with. :) Added a fix.
