### ISSUE TITLE
[filer.copy] argument -collection not taken into account when passed after directory to copy.

### ISSUE THREAD

**Issue by bmillemathias** [chrislusf/seaweedfs#1678]
**Describe the bug**
on a fresh cluster I've launched a command `filer.copy` with a collection parameter but the files were is the collection `""`
```
weed -v 4 filer.copy  ../../Music/* -collection music http://xxx.xxx.xxx.xxx:8888/collections/music/
(copy in progress)
...
``` 

```
weed shell -master xxx.xxx.xxx.xxx:9333
> collection.list
collection:""
Total 1 collections.
```

**System Setup**
- config: 3 masters, 3 volumes servers (connected to all masters), 3 filer (connected to all masters and connected to other peer) 
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
  - masters: ```weed -v 2 master -mdir /opt/seaweedfs/weed.domain.tld/master -port 9333 --peers ip-1:9333,ip-2:9333,ip-3:9333 -defaultReplication 001```
  - volumes: ```weed -v 2 volume -dir /opt/seaweedfs/weed.domain.tld/volume -dataCenter=DefaultDataCenter -rack=DefaultRack -mserver ip-1:9333,ip-2:9333,ip-3:9333```
  - filers: ```weed -v 2 filer -dataCenter=DefaultDataCenter -rack=DefaultRack -master ip-1:9333,ip-2:9333,ip-3:9333 --peers ip-1:8888,ip-2:8888,ip-3:8888 -encryptVolumeData```
- OS version: Linux ubuntu 18.04
- output of `weed version`: `2.15`
- if using filer, show the content of `filer.toml`: empty

**Expected behavior**
Have the collection set for file transfered.

**Comment by bmillemathias** [comment]
Actually the order of argument matters so `-collection ...` has to be passed before the directory.
It's a bit misleading the command silently discard it.

**Comment by chrislusf** [comment]
I added a fix to show error a little bit more obviously.
