### ISSUE TITLE
weed s3 开启-config后无法上传文件和新建文件夹

### ISSUE THREAD

**Issue by lze693** [chrislusf/seaweedfs#1679]
weed版本：2.15
weed相关命令
       weed -logdir=./logs -v=1 master -mdir=./master_data -ip=192.168.35.110 -port=9333 -volumeSizeLimitMB=512000
       weed -logdir=./logs -v=1 volume -dir=./volume_data -max=100000000 -mserver=192.168.35.110:9333 -ip=192.168.35.110 -port=9000 -index=leveldb
       weed -logdir=./logs -v=1 filer -master=192.168.35.110:9333 -ip=192.168.35.110 -port=8888  -maxMB=1024
       weed -logdir=./logs -v=1 s3 -filer=192.168.35.110:8888 -port=8333 -config="./config.json"

      config.json:
     {
  "identities": [
    {
      "name": "anonymous",
      "actions": [
        "Read"
      ]
    },
    {
      "name": "some_name",
      "credentials": [
        {
          "accessKey": "some_access_key1",
          "secretKey": "，"
        }
      ],
      "actions": [
        "Admin",
        "Read",
        "List",
        "Tagging",
        "Write"
      ]
    },
    {
      "name": "some_read_only_user",
      "credentials": [
        {
          "accessKey": "some_access_key2",
          "secretKey": "some_secret_key2"
        }
      ],
      "actions": [
        "Read",
        "List"
      ]
    },
    {
      "name": "some_normal_user",
      "credentials": [
        {
          "accessKey": "some_access_key3",
          "secretKey": "some_secret_key3"
        }
      ],
      "actions": [
        "Read",
        "List",
        "Tagging",
        "Write"
      ]
    },
    {
      "name": "user_limited_by_bucket",
      "credentials": [
        {
          "accessKey": "some_access_key4",
          "secretKey": "some_secret_key4"
        }
      ],
      "actions": [
        "Read:bucket1",
        "Read:bucket2",
        "Read:bucket3",
        "Write:bucket1"
      ]
    }
  ]
}

用S3 Browser 9.2.1 进行s3的连接
使用some_access_key1,some_secret_key1后发现只能创建桶，不能创建文件夹和上传文件
报 The request signature we calculated does not match the signature you provided. Check your key and signing method的错误
前面用2.05版本的时候不会出现这个问题

**Comment by chrislusf** [comment]
Please follow issue template. 

What is the output of `weed version`?

**Comment by chrislusf** [comment]
can not reproduce.

**Comment by chrislusf** [comment]
`-volumeSizeLimitMB=512000` is too big. Try it with 512

**Comment by lze693** [comment]
版本 version 8000GB 2.15 813453f windows amd64

**Comment by lze693** [comment]
2.05版本也是这么设置的没有问题啊

**Comment by lze693** [comment]
报我们计算出的请求签名与您提供的签名不匹配。检查您的密钥和签名方法的错误 是因为需要使用signature-v4
