### ISSUE TITLE
Weed redirects user to correct volume server when wrong server is accessed

### ISSUE THREAD

**Issue by fedotxxl** [chrislusf/seaweedfs#168]
Suppose I've got 2 volume servers `A` and `B`. Volume 1 is located on server `A`. If I try to get file of volume `1` from server `B` weed will return 301 to server `A`.

problem: it uses `publicUrl` for redirect. We use same instance of weed for two projects with different domains. In this case sometimes it will redirect to incorrect domain. 

I think developers should not rely on this feature - this is mistake when file is accessed from incorrect server (Am I right?). Can we disable this feature (config option)?

**Comment by chrislusf** [comment]
Maybe we should disable this redirect altogether...

**Comment by fedotxxl** [comment]
Can you make it configurable?

**Comment by chrislusf** [comment]
Default to "not redirecting" ?
