### ISSUE TITLE
panic when loading volumes concurrently

### ISSUE THREAD

**Issue by qieqieplus** [chrislusf/seaweedfs#1682]
**Describe the bug**
Loading same volume more than once leads to SIGSEGV

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
- OS version
- output of `weed version`
- if using filer, show the content of `filer.toml`

1. start server: `./weed server`
2. upload some random files
3. restart with "-volume.index leveldb"
 `./weed server -volume.index leveldb`

4. crash log

> I1216 18:24:45 91019 master_grpc_server.go:250] + client master@10.170.160.252:56816
I1216 18:24:45 91019 volume_loading.go:128] loading leveldb /var/folders/1x/lbz9zhkd1_n0vd2zlmsl_0n40000gn/T/2.ldb
I1216 18:24:45 91019 volume_loading.go:128] loading leveldb /var/folders/1x/lbz9zhkd1_n0vd2zlmsl_0n40000gn/T/4.ldb
I1216 18:24:45 91019 volume_loading.go:128] loading leveldb /var/folders/1x/lbz9zhkd1_n0vd2zlmsl_0n40000gn/T/3.ldb
I1216 18:24:45 91019 volume_loading.go:128] loading leveldb /var/folders/1x/lbz9zhkd1_n0vd2zlmsl_0n40000gn/T/2.ldb
I1216 18:24:45 91019 volume_loading.go:128] loading leveldb /var/folders/1x/lbz9zhkd1_n0vd2zlmsl_0n40000gn/T/3.ldb
I1216 18:24:45 91019 volume_loading.go:128] loading leveldb /var/folders/1x/lbz9zhkd1_n0vd2zlmsl_0n40000gn/T/1.ldb
I1216 18:24:45 91019 volume_loading.go:128] loading leveldb /var/folders/1x/lbz9zhkd1_n0vd2zlmsl_0n40000gn/T/1.ldb
I1216 18:24:45 91019 volume_loading.go:128] loading leveldb /var/folders/1x/lbz9zhkd1_n0vd2zlmsl_0n40000gn/T/4.ldb
I1216 18:24:45 91019 volume_loading.go:128] loading leveldb /var/folders/1x/lbz9zhkd1_n0vd2zlmsl_0n40000gn/T/5.ldb
I1216 18:24:45 91019 volume_loading.go:128] loading leveldb /var/folders/1x/lbz9zhkd1_n0vd2zlmsl_0n40000gn/T/5.ldb
I1216 18:24:45 91019 volume_loading.go:135] loading leveldb /var/folders/1x/lbz9zhkd1_n0vd2zlmsl_0n40000gn/T/4.ldb error: resource temporarily unavailable
I1216 18:24:45 91019 volume_loading.go:135] loading leveldb /var/folders/1x/lbz9zhkd1_n0vd2zlmsl_0n40000gn/T/2.ldb error: resource temporarily unavailable
I1216 18:24:45 91019 volume_loading.go:135] loading leveldb /var/folders/1x/lbz9zhkd1_n0vd2zlmsl_0n40000gn/T/3.ldb error: resource temporarily unavailable
I1216 18:24:45 91019 volume_loading.go:135] loading leveldb /var/folders/1x/lbz9zhkd1_n0vd2zlmsl_0n40000gn/T/1.ldb error: resource temporarily unavailable
I1216 18:24:45 91019 volume_loading.go:135] loading leveldb /var/folders/1x/lbz9zhkd1_n0vd2zlmsl_0n40000gn/T/5.ldb error: resource temporarily unavailable
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x188 pc=0x49e80be]

**Expected behavior**
not crash

**Comment by chrislusf** [comment]
Added a fix to address this properly.

**Comment by qieqieplus** [comment]
These two fixes are basically doing the same thing in different places.
