### ISSUE TITLE
make install module error

### ISSUE THREAD

**Issue by runbestfast** [chrislusf/seaweedfs#1687]
% **make install**
go get  -d ./weed/
go: finding module for package google.golang.org/grpc/naming
rm -rf /home/travis/gopath/src/github.com/coreos/etcd/vendor/golang.org/x/net/trace
rm -rf /home/travis/gopath/src/go.etcd.io/etcd/vendor/golang.org/x/net/trace
go install  -ldflags "-X github.com/chrislusf/seaweedfs/weed/util.COMMIT=af2efe6" ./weed/
go: finding module for package google.golang.org/grpc/naming
**../../../../pkg/mod/google.golang.org/api@v0.9.0/internal/pool.go:20:2: module google.golang.org/grpc@latest found (v1.34.0), but does not contain package google.golang.org/grpc/naming**
make: *** [install] Error 1

**current go version:**
go version go1.15.6

**Comment by chrislusf** [comment]
what was the problem?

**Comment by runbestfast** [comment]
sorry, I change go.mod cause this problem.
