### ISSUE TITLE
2.02版以上使用MYSQL作为FILER SERVER的DATA STORE会不返回FID

### ISSUE THREAD

**Issue by jckinda** [chrislusf/seaweedfs#1689]
在2.02以上的FILER SERVER使用LEVELDB、REDIS作为DATA STORE都是会正常返回name, size, fid, url这四个值。但使用MYSQL作为DATA STORE的话只会返回name, size。在1.47版使用MYSQL作为DATA STORE没有这个问题。

1.47版
curl -F file=@help.psd http://127.0.0.1:9338/mysql2/
{"name":"help.psd","size":26308,"fid":"5,06fff028ea","url":"http://127.0.0.1:9334/5,06fff028ea"}

2.15版
curl -F file=@help.psd http://127.0.0.1:9338/mysql/
{"name":"help.psd","size":26308}

**Comment by chrislusf** [comment]
see https://github.com/chrislusf/seaweedfs/issues/1554
