### ISSUE TITLE
deduplication feature

### ISSUE THREAD

**Issue by pubyun** [chrislusf/seaweedfs#169]
store single copy for duplicated file

**Comment by chrislusf** [comment]
Please be more specific.

**Comment by chrislusf** [comment]
There is already a dedup feature, where uploading the same file will not be stored twice, unless it is a TTL volume.

**Comment by yanyiwu** [comment]
Are you sure? Where is this dedup feature?
I upload the same file all the way to do testing, and disk occupation grows all the way.
I dont think the dedup feature works. Or I use it incorrectly?

**Comment by chrislusf** [comment]
Please show me your test.

**Comment by chrislusf** [comment]
If the same file is submitted with the same file key, it would not be appended to dat file again.
