### ISSUE TITLE
spark visit data in seaweedfs

### ISSUE THREAD

**Issue by doufighting** [chrislusf/seaweedfs#1692]
**Describe the bug**
I have stored billion of images in seaweedfs cluster, now I want to do some analysis using spark, I wonder is there any way can spark visit the data stored in seaweedfs ?  the storage path is eg: http://ip:port/1,25b50e9ddg4.
您好，我在seaweedfs中存储了大量图片数据，现在我希望使用Spark对其进行分析，但是我并没有使用filer方式存储这些数据，这些数据的存储路径都是基本的fid模式，比如http://ip:port/1,25b50e9ddg4，这样的路径是否能经过什么转换从而在Spark中被直接访问到呢？

**Comment by chrislusf** [comment]
use http to visit the fid?

**Comment by doufighting** [comment]
I found the data stored by filer, can be used as sc.textFile("/buckets/large/ttt.txt") in spark, I wonder is there any way can translate data in seaweedfs cluster to filer ? 
您好，我注意到通过filer存储的数据可以在spark中 用 sc.textFile("/buckets/large/ttt.txt") 的方式访问，已经存储好的数据有没有办法能转换成filer模式 让spark访问呢？

**Comment by chrislusf** [comment]
They're just implemented with http. Nothing you can not do directly with file id.
