### ISSUE TITLE
Useful defaults for rack/datacenter

### ISSUE THREAD

**Issue by nivekuil** [chrislusf/seaweedfs#1694]
Currently, the default values for rack and datacenter are hard coded and as such are never useful. There could be default values here that are good enough for basic use cases. For example, hostname for rack so replicatiion across hosts works out of the box.

**Comment by chrislusf** [comment]
Hostname is for -ip 

What's a good option for rack?

**Comment by nivekuil** [comment]
> Hostname is for -ip

Ah, I actually have multiple volumes behind the same `-ip` so in order to disambiguate them I use hostname for rack. Does 001 replication still work in that context?

**Comment by chrislusf** [comment]
> > Hostname is for -ip
> 
> Ah, I actually have multiple volumes behind the same `-ip` (like a service name behind a container orchestrator) so in order to disambiguate them I use hostname for rack. Does 001 replication still work in that context?

No. The same `-ip` denotes that there is one volume server in the rack. So 001 would not work.

**Comment by nivekuil** [comment]
> No. The same -ip denotes that there is one volume server in the rack. So 001 would not work.
I see, thanks.

> What's a good option for rack?

I think of a rack as a failure domain bounded by shared power/networking.  The same could describe a single machine.  If it ever makes sense to run multiple volume servers per machine (e.g. 1 volume server per disk), then 001 replication would only e.g. tolerate a single disk loss, and you'd need 010 to survive a whole machine loss.  Taking into account such a case (M:N volume servers to machines) I think it makes sense to default rack to hostname, even if it is redundant when you do a 1:1 volume servers to machines setup.  At least it's more useful than setting the rack name to a global constant?

**Comment by chrislusf** [comment]
I see your point, but feel having hostname as rack is misleading.

The dc, rack, ip, and replication are together. Default rack to something may make sense at beginning, but can take time to find out when changing these configurations. It is better to have something that needs some thinking first. Your confusion with "001" and "-ip" actually illustrated this.

**Comment by nivekuil** [comment]
> The dc, rack, ip, and replication are together. Default rack to something may make sense at beginning, but can take time to find out when changing these configurations. It is better to have something that needs some thinking first. Your confusion with "001" and "-ip" actually illustrated this.

That makes sense.  I just remembered /etc/machine-id is a thing, which may be less confusing as it doesn't have any network meaning and it's constant across VMs (though it needs to be explicitly mounted in containers).
