### ISSUE TITLE
create tests suite on pull-requests / merges

### ISSUE THREAD

**Issue by bmillemathias** [chrislusf/seaweedfs#1696]
**Describe the bug**
That would be great to have test (running on github action / azure devops / ...) to run a test suite on PR / merge request.
The idea would be to test scenarii to validate functionality and spot possible regression like create a cluster, creating collection, ...
That would bring some confidence to people coming across the project.

As you create container that could be easily doable.

**Comment by chrislusf** [comment]
there are already tests for each PR.

https://github.com/chrislusf/seaweedfs/blob/master/.github/workflows/go.yml#L36

We can add some more actions later.
