### ISSUE TITLE
Not using http api on master with disableHttp

### ISSUE THREAD

**Issue by kmlebedev** [chrislusf/seaweedfs#1697]
**Describe the bug**
Minor. Not using http api on master

**System Setup**
```2.16```
```
/usr/bin/weed master -disableHttp
```

**Expected behavior**
/dir/lookup through gRPC maybe something else using http api on master  

**Screenshots**

**Additional context**
```
W1222 15:29:01     1 upload_content.go:100] uploading to http://fast-volume-3:8080/2,3cc5e7f4f801: unmarshalled error http://fast-volume-3:8080/2,3cc5e7f4f801: failed to lookup for 2: http://fast-master-2:9333/dir/lookup: 404 Not Found
I1222 15:29:01     1 filer_notify.go:99] log write failed /topics/.system/log/2020-12-22/12-21.segment: upload data http://fast-volume-3:8080/2,3cc5e7f4f801: unmarshalled error http://fast-volume-3:8080/2,3cc5e7f4f801: failed to lookup for 2: http://fast-master-2:9333/dir/lookup: 404 Not Found
```

**Comment by chrislusf** [comment]
It comes from the volume server replication.

Maybe we should think wether supporting `-disableHttp` worth the code change effort.

**Comment by kmlebedev** [comment]
Perhaps as a quick solution it is worth supporting TLS client certificates

**Comment by oangit** [comment]
Hello.
I have a similar error.
I have 3 masters, 2 filers, 4 volumes.
Replication 001
`/usr/bin/weed master -disableHttp`
`/usr/bin/weed filer -s3 -disableHttp`

weed version
version 30GB 2.31 f5b5e4d linux amd64

```
s3cmd mb s3://testbucket
Bucket 's3://testbucket/' created
```

and i have got error:

`
weed-volume[121703]: I0315 08:49:12 21703 common.go:53] response method:POST URL:/3,89be5c7ab5 with httpStatus:500 and JSON:{"size":226,"error":"failed to lookup for 3: http://10.193.85.148:9333/dir/lookup: 404 Not Found","eTag":"3714c624f25c64b3efdadf5a3fe04710"}
`

I can't upload the file.
```
s3cmd put virtio-win-0.1.185.iso s3://testbucket
upload: 'virtio-win-0.1.185.iso' -> 's3://testbucket/virtio-win-0.1.185.iso'  [part 1 of 27, 15MB] [1 of 1]
   851968 of 15728640     5% in    0s  1235.87 kB/s  failed
   851968 of 15728640     5% in    0s   969.91 kB/s  done
WARNING: Upload failed: /virtio-win-0.1.185.iso?partNumber=1&uploadId=270c2ff3-0390-4ee3-96ca-5a89e6612978 (500 (InternalError): We encountered an internal error, please try again.)
WARNING: Waiting 3 sec...
```

```
weed-filer[96595]: W0315 09:28:11 96595 upload_content.go:103] uploading to http://10.193.85.148:8080/3,072ca6d1e425: unmarshalled error http://10.193.85.148:8080/3,072ca6d1e425: failed to lookup for 3: http://10.193.85.148:9333/dir/lookup: 404 Not Found
```

I configured `jwt. signing` and specified all grpc tls authentications.

Please tell me how to make the most secure configuration ?
I would like to configure the ability to use s3 and restrict other entry points to the cluster.

**Comment by chrislusf** [comment]
Not supported, at least now. S3 proxy requests to Filer via http.

**Comment by chrislusf** [comment]
```
/usr/bin/weed master -disableHttp
```

Master with http disabled is supported now after 5a0f92423eb4f89d35b245b1913eb7ba60436742

Filer with http disabled is not supported, since S3 still need to go through filer via http, at least for now.
