### ISSUE TITLE
WeedFS inconsistent behavior !!

### ISSUE THREAD

**Issue by shahzaibcb** [chrislusf/seaweedfs#170]
Hi,
   
   First of all, please accept my gratitude for introducing such a robust model. :)

In the meantime, we're using weedfs on centos-6 server. The main issue we're presented with its master/volume service. Whenever we start weedfs using following command, it runs for 8-9 hours and get stopped. There's no error we found under /tmp/weed.Error or /tmp/weed.Fatal but its keep on doing that. 

weed master -pulseSeconds=20 -ip="track.domain.com" -mdir="/opt/weed/" &

Following is the binary we're using :

https://bintray.com/artifact/download/chrislusf/seaweedfs/weed_0.70beta_linux_amd64.tar.gz

Could you please help us on that ?

Thanks in advance !!

**Comment by chrislusf** [comment]
Please share the log. It may have some useful info.

**Comment by shahzaibcb** [comment]
Which one should i share ? /tmp/weed.INFO , weed.WARNING, weed.FATAL or weed.ERROR ?

**Comment by shahzaibcb** [comment]
Also could you please suggest us if weedfs is good for production ? We've got high traffic website whose thumbs will be shifted to weedfs in coming month. Your suggestion will be very helpful on that. :)

**Comment by shahzaibcb** [comment]
Volume server again died without any errors in /tmp/weed.Error, /tmp/weed.Fatal or /tmp/weed.warning. But this is what logged in weed Master server :

http://pastebin.com/B0VppDjF

**Comment by chrislusf** [comment]
How is the volume server started?

**Comment by chrislusf** [comment]
And what kind of traffic on the server?

**Comment by shahzaibcb** [comment]
weed volume -port=8080 -pulseSeconds=20 -max=25 -mserver=track.domain.pk:9333 -ip=X.X.X.X -dir=/files/weed -publicUrl=thumbs.domain.com -port.public=8080

We got total of 800GB space so we used 25 max volumes with default MaxLimitsizeMB=30000.

>> And what kind of traffic on the server?
Well, we've got video sharing website which serves user generated content (mp4,jpg) .Users can upload videos related to entertainment,songs,religios and but adult content not permited. :) Our application and Storage are separated. Currently the infrastructure is  very standard :

- 5 x Application servers cluster behind loadbalancer: php and mysql etc
- 10 x Storage : .jpg and .mp4 are on the same servers using traditional Directory systems i.e http://storage.domain.com/files/videos/year/month/day/file.mp4


New strategy :- 

- Separating thumbs to Different SSD servers in order to reduce high I/O load on storages to improve .mp4 streaming as SSD is very much efficient to server small and random requests such as .jpg.

- So deployed our first volume server dedicated to weedfs with 800GB space whereas master is currently on VPS. Its on testing phase right now and doing thumbs insertion on volume servers.

Concurrent users on website are around 10K+ and the average Aggregated Port for storages stays around 4Gbps.

**Comment by chrislusf** [comment]
Please do this. Set this to environment variable, just like setting PATH, export PATH=...

  export GOTRACEBACK=crash

And then start the weed volume server, to generate a core dump when it crashes.

**Comment by chrislusf** [comment]
Also, when you start the volume server, please direct the stdout and stderr to a file also.

**Comment by shahzaibcb** [comment]
Thanks for your help. After the last crash since yesterday, i had started master/volume on foreground of the screen window instead of running it on the background. So there's no need to direct its output to any file, screen window will pop any error if crash happens.

Btw, it's not crashed till now, maybe executing it on screen window is better than running it on the background ? 
I'll initiate export GOTRACEBACK=crash once the services gets crash again.

**Comment by shahzaibcb** [comment]
It looks to us that connection between master<->volume server got reset again today. Could you please tell whats this reset means ? Here's the log in volume server :

I0807 10:56:06 42086 volume.go:136] Start Seaweed volume server 0.70 beta at 0.0.0.0:8080
I0807 10:56:06 42086 volume_server.go:70] Volume server bootstraps with master track.domain.com:9333
I0808 13:43:29 42086 store.go:48] Reset master track.domain.com:9333 from: [track.domain.com:9333 track.domain.com:9333]
I0808 13:43:39 42086 volume_server.go:82] Volume Server Connected with master at track.domain.com:9333
I0808 14:03:05 42086 store.go:48] Reset master track.domain.com:9333 from: [track.domain.com:9333 track.domain.com:9333]
I0808 14:03:15 42086 volume_server.go:82] Volume Server Connected with master at track.domain.com:9333

As you can see that volume server was started a day ago (07-august) and the 'reset master' line is generated today (08-august). Just need to find out the meaning of this line.

**Comment by shahzaibcb** [comment]
At the same time, that was what we found on master server :

http://pastebin.com/mc0t1p2W

The matter of fact is, weedfs is working on both master/volume server without out interference.

**Comment by chrislusf** [comment]
These are temporary network issues and seaweesfs can recover from it. We
just need to watch for actual volume sever issues.

**Comment by shahzaibcb** [comment]
You're correct, that could be network issue as well. I'll closely monitoring it, will get back to you with updates.

Thanks !!

**Comment by seifer** [comment]
What about disk free space, swap? oom killer?

**Comment by shahzaibcb** [comment]
The installation is fresh, hardly some GB is used which was taken by OS during installation, as well as there's nothing related to oom killer in kernal messages . I have not faced that crash issue since 2 days.

**Comment by shahzaibcb** [comment]
Hi , as we've been closely monitoring the uptime of weed master/volume. Our monitoring detects service unavailable once in a day which could be very much related to small networking problem because it gets stable after that. Also we found some syntax errors on volume server today :

I0809 15:52:14 42086 volume_server_handlers_write.go:22] NewVolumeId error: strconv.ParseUint: parsing "a": invalid syntax
I0809 15:52:14 42086 volume_server_handlers_write.go:22] NewVolumeId error: strconv.ParseUint: parsing "aspq": invalid syntax
I0809 15:52:14 42086 volume_server_handlers_write.go:22] NewVolumeId error: strconv.ParseUint: parsing "dh": invalid syntax
I0809 15:52:14 42086 volume_server_handlers_write.go:22] NewVolumeId error: strconv.ParseUint: parsing "do.php": invalid syntax
I0809 15:52:14 42086 volume_server_handlers_write.go:22] NewVolumeId error: strconv.ParseUint: parsing "extralog": invalid syntax
I0809 15:52:14 42086 volume_server_handlers_write.go:22] NewVolumeId error: strconv.ParseUint: parsing "folder": invalid syntax
I0809 15:52:14 42086 volume_server_handlers_write.go:22] NewVolumeId error: strconv.ParseUint: parsing "forum": invalid syntax
I0809 15:52:14 42086 volume_server_handlers_write.go:22] NewVolumeId error: strconv.ParseUint: parsing "gate": invalid syntax

**Comment by shahzaibcb** [comment]
Unfortunately, volume server is again dead, and there is no error found in logfile(where i am directing its output) , as we execute weedfs volume from weed.sh file, here is what i found after weed got killed :

http://prntscr.com/83gv2p

Also the last line in logfile (/var/log/weed.log) we found was append at 9-august but it just crashed 1 hour ago (11-aug). Here it is :

[root@thumbs tmp]# tail -2 /var/log/weed.log
I0809 15:52:16 42086 volume_server_handlers_write.go:22] NewVolumeId error: strconv.ParseUint: parsing "jackposv2": invalid syntax
I0809 15:52:16 42086 volume_server_handlers_write.go:22] NewVolumeId error: strconv.ParseUint: parsing "alina": invalid syntax

----------------------------------------------

Also, the last modified status of weed.ERROR and weed.FATAL is 07-august :

lrwxrwxrwx.  1 root  root    53 Aug  7 10:55 weed.FATAL -> /tmp/weed.thumbs.root.log.FATAL.20150807-105526.41988
lrwxrwxrwx.  1 root  root    53 Aug  7 10:55 weed.ERROR -> /tmp/weed.thumbs.root.log.ERROR.20150807-105526.41988

--------------------------------------------------------

Here are the current logs of master:

http://pastebin.com/CMKjVvtX

------------------------------------------------------

Regarding disk usage and free memory of volume server:
[root@thumbs tmp]# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda2        20G  2.3G   16G  13% /
tmpfs           7.8G     0  7.8G   0% /dev/shm
/dev/sda1       488M   24M  440M   5% /boot
/dev/sda5       9.5G   22M  9.0G   1% /home
/dev/sda3        16G   41M   15G   1% /tmp
/dev/sda8       861G   80M  817G   1% /weed/files
/dev/sda6       7.7G  323M  7.0G   5% /var

[root@thumbs tmp]# free -m
             total       used       free     shared    buffers     cached
Mem:         15906       3093      12813          0        203       2140
-/+ buffers/cache:        749      15157
Swap:         4095          0       4095

-------------------------------
Now i'll start weed volume with GOTRACEBACK=crash .

**Comment by chrislusf** [comment]
The screenshot showed "killed". Very strange!

You can zip and send me all files /var/log/weed*

The volume log should be in another file.

Chris

**Comment by shahzaibcb** [comment]
Hi chris, well i am actually overwriting /var/log/weed.log using (> /var/log/weed.log) . Though, i have increased user open files limit, after that, crash didn't occurred since 11th august. I'll keep monitoring it for some days and will let you know if this solution fix the problem.

**Comment by chrislusf** [comment]
Thanks! What was the open file limit before?

**Comment by shahzaibcb** [comment]
Hi, it was default 1024 for each user. I have increased it to 700000 in /etc/security/limits.conf file :

* soft nofile 700000
* hard nofile 700000

**Comment by chrislusf** [comment]
User open file limit is important! I will put it in the wiki page.

**Comment by shahzaibcb** [comment]
Yes, it is important and i wonder why nobody else had this issue with weedfs ? In the meantime, everything is still stable, nothing crashed yet. :)

**Comment by chrislusf** [comment]
1024 is just too small. A few hundreds of concurrent requests will use all
of them.
