### ISSUE TITLE
Can only upload to first created S3 bucket

### ISSUE THREAD

**Issue by ALMaclaine** [chrislusf/seaweedfs#1705]
Weed Version: version 8000GB 2.16 6912bf9 darwin amd64
OS: Osx 10.15.7
weed s3
No filer

I'm using the aws cli command as described in the wiki.

https://github.com/chrislusf/seaweedfs/wiki/AWS-CLI-with-SeaweedFS

I'm able to successfully create multiple buckets, and they all show when using the `ls` command.

However, I can only upload files to the bucket that was created first.

If I attempt to upload to any bucket except the one created first I get an error similar to the following:

```An error occurred (InternalError) when calling the PutObject operation (reached max retries: 2): We encountered an internal error, please try again.```

Let me know if I can provide any other useful information.

**Comment by chrislusf** [comment]
Very likely you are running out of volumes.

Try to keep the volume size low. 

```
weed master -volumeSizeLimitMB=64
```

**Comment by ALMaclaine** [comment]
I've tried starting the server as follows:

`weed server -master.volumeSizeLimitMB=64 -s3`

However the issue persists. Only the first created bucket will allow adding objects.

The error message is the same:

`An error occurred (InternalError) when calling the PutObject operation (reached max retries: 2): We encountered an internal error, please try again.`

I created the buckets upon starting the server with the new command. My data directory is on a hard drive with 200gigs free space.

**Comment by chrislusf** [comment]
Show the logs on the servers.

Try to remove everything in your data directory. By default, 7 volumes with 30GB each will be created by default. It has already taken up all your data directory.

**Comment by ALMaclaine** [comment]
Okay, I got it.

It's a little counter intuitive for max volumes to be 8 and for s3 buckets to automatically generate 8 volumes.

**Comment by chrislusf** [comment]
in `weed shell`, you can configure it

```
> fs.configure -locationPrefix="/buckets/" -volumeGrowthCount=3 -apply
```

**Comment by chrislusf** [comment]
Added a note in https://github.com/chrislusf/seaweedfs/wiki/Amazon-S3-API#note

You are welcome to adjust the wiki if you find anything surprising. The wiki is open to everyone.

**Comment by ALMaclaine** [comment]
thank you
