### ISSUE TITLE
S3 not support vultr-object-storage 

### ISSUE THREAD

**Issue by runbestfast** [chrislusf/seaweedfs#1706]
**version:** master

**desc:** vultr-object-storage not support ServerSideEncryption / StorageClass

**Modify file:** s3_upload.go

```go
result, err = uploader.Upload(&s3manager.UploadInput{
		Bucket: aws.String(destBucket),
		Key:    aws.String(destKey),
		Body:   fileReader,
		ACL:    aws.String("private"),
		//ServerSideEncryption: aws.String("AES256"),
		//StorageClass:         aws.String("STANDARD_IA"),
		Tagging: aws.String(tags),
	})
```

**Comment by chrislusf** [comment]
I have no idea what problem you are describing.

**Comment by runbestfast** [comment]
云存储厂商的问题，不支持标准的ServerSideEncryption、StorageClass两个参数字段

**Comment by chrislusf** [comment]
Seems you are trying to use cloud tiering, right?

**Comment by runbestfast** [comment]
yes,  I used cloud tiering. I trying to choice cloud.

**Comment by runbestfast** [comment]
Random MultipartUpload -> RequestError -> "use of closed network connection" when uploading a lot of data to S3

**Comment by chrislusf** [comment]
ok. Seems no good solution yet for the above issue.

**Comment by chrislusf** [comment]
Is it possible to just handle this error and add some retries?

**Comment by runbestfast** [comment]
Retried uploading several times, but Almost every time it appears,  so I upgraded aws-sdk to solve the problem

**Comment by chrislusf** [comment]
Need to update the go module? can you please send a PR for this?

**Comment by runbestfast** [comment]
https://github.com/chrislusf/seaweedfs/pull/1734
