### ISSUE TITLE
What's a small file size for weedfs?

### ISSUE THREAD

**Issue by c4milo** [chrislusf/seaweedfs#171]
I see there are mentions everywhere about small file sizes but a size range is never explicitly stated. For instance, can I use Weedfs to store ~300mb files without any problems?

**Comment by chrislusf** [comment]
The file size is limited by the memory. The file is read into memory as a whole blob, and then saved to disk. So if your file is 300MB and the server is on a 1GB memory server, better split it into smaller parts.
