### ISSUE TITLE
Fix replication operatiion won't work and Master doesn't understant one of 2 replica is deleted

### ISSUE THREAD

**Issue by kaaaq** [chrislusf/seaweedfs#1710]
Hi,
I have one collection, named: "test001" with 16 volume id with replication= 001

I wanted to test "volume.fix.replication" in weed shell , So I choose one of the volume id from this collection (volum id 40) and then delete one of the volume replicas (I delete 3 files : "test001_40.dat test001_40.idx test001_40.vif" from volume server "A")
,So now I delete one replica and I still have 1 available replica on volume server "B" then I run "volume.fix.replication" but it showed nothing!
1.Why didn't it work?
Why master didn't understand this and didn't change the status of replica to readonly?

2.Another weird thing is that:
I tried to assign fid to deleted volume id and master didn't understand this! and it gave me fid!!!
When I want to uplad a file to this fid it can upload ! but it will create a new collection and volume id like this: 40,8e1cf10a7811f3d31b35172b_55.idx and I can get my file.
Why did this happen?

`weed version 2.16 6912bf9 linux amd64`

**Comment by chrislusf** [comment]
Very likely you did not restart. after deleting the files. On linux, even the file is deleted, the program still see the file.
