### ISSUE TITLE
Weed just accept 29.7MiB of first data chunck and cm=false parameter would show exact file instead of chunk file

### ISSUE THREAD

**Issue by kaaaq** [chrislusf/seaweedfs#1711]
I'm uploading a file with size "67279470" to specific volume id but it upload just 29.75 MiB of my file! even in response , it shows me size":67279470" but when I want to download my file from url, it is 29.7MB

```
weedfs@dev10:~$ curl -F file=@/home/weedfs/weed http://192.168.200.20:8080/8,8e3cf10b7811f43541db9afa
{"name":"weed","size":67279470,"eTag":"889c4f2e26150166813d7974ed204411"}
```
and I test following command to see data chunks but it shows me the exaxt file in command line (Binary codes) instead of data chunks!!

weedfs@dev10:~$ curl 192.168.200.20:8081/17,8e1cf10a7811f380d8311cd2?cm=false

When I want to check this file chunks I commit:
`curl http://192.168.200.20:8081/7,8e2cf10a7811f43541db9afa?cm=false`
but instead of returning a json to show me chunks, it return actula file

```
菮��H�D$0�H�L�=���uHH�H�H�H�f�H�l$�H�l$��+���H�mH�&�H�D$8H�L$@H�l$ H��(�H�L$H�&&�H�$H�LH�D$���H�L$������B�����H�DH�HH�@ H�L$H�D$���������dH�
                             %����H;a�SH��pH�l$hH�l$hH�D$xH�H H�@�H��$�H�fDH����H9���H�WH�
H�\$PH�wL�H9�rfH�t$HL�D$`L�H�$H�DH�L$�4���H�D$PH��$�H�AH�D$HH�A�=���uH�D$`H�H�l$hH��p�H�H�D$`�������H�L$@H�T$HH����H��sH�$H���H�D@�{9����u�����������������������H�DH�@H�D$������������������dH���f��
H��HH�l$@H�l$@H�D$PH�HH�L$0H�H�T$H�XH�\$8H�p H�t$ H�x0H�|$H�@(H�D$(L����L�$�ԫ��H�D�=8����H�L$0H�HH�H�L$H�H�L$ H�l�H�L$XH�D$`H�l$@H��H�H�x(H�L$(�*�����H�xH�L$8������H�xH�L$0�
����l���D������������������������������H�H8�H�D$H�D$�����������dH�
```
but with following command , it will upload my file (weed binary file correctly):
`./weedfs/weed upload -dir="/home/weedfs/weed"`

```
./weedfs/weed version
version 2.16 6912bf9 linux amd64
```

**Comment by chrislusf** [comment]
I could not reproduce

```
$ curl localhost:9333/dir/assign
{"fid":"12,0230549cc56068","url":"192.168.2.7:8080","publicUrl":"192.168.2.7:8080","count":1}weed$
$ curl -F "file=@/Users/chris/go/bin/weed" http://192.168.2.7:8080/12,0230549cc56068
{"name":"weed","size":83006332,"eTag":"5a525f76248cc92557ae7176c42ca7ca"}weed$
$ wget http://192.168.2.7:8080/12,0230549cc56068
--2020-12-28 10:51:45--  http://192.168.2.7:8080/12,0230549cc56068
Connecting to 192.168.2.7:8080... connected.
HTTP request sent, awaiting response... 200 OK
Length: 83006332 (79M) [application/octet-stream]
Saving to: ‘12,0230549cc56068’

12,0230549cc56068             100%[==============================================>]  79.16M   127MB/s    in 0.6s

2020-12-28 10:51:46 (127 MB/s) - ‘12,0230549cc56068’ saved [83006332/83006332]

$ ls -al 12,0230549cc56068
-rw-r--r--  1 chris  staff  83006332 Dec 28 10:51 12,0230549cc56068
$ ls -al `which weed`
-rwxr-xr-x  1 chris  staff  83006332 Dec 27 22:11 /Users/chris/go/bin/weed
$
```

**Comment by kaaaq** [comment]
Hi,
You are assigning a fid via Master, but I'm generating manually by myself,
I upload my file to a volume id:
`curl -F file=@/home/weedfs/weed 192.168.200.20:8081/24,8e3cf10b7811f48bbaf1417e`
and then I wget the file:

```
eitaa@dev10:~/test$ wget 192.168.200.20:8081/24,8e3cf10b7811f48bbaf1417e?cm=false
--2020-12-29 13:53:56--  http://192.168.200.20:8081/24,8e3cf10b7811f48bbaf1417e?cm=false
Connecting to 192.168.200.20:8081... connected.
HTTP request sent, awaiting response... 200 OK
Length: 67279470 (64M) [application/octet-stream]
```

It downloaded with 64M size
But when I checked the volume in ui it shows 29.75 MiB so Weed has chuncked the file but I can not see where the chunks are!:
`curl  192.168.200.20:8081/24,8e3cf10b7811f48bbaf1417e?cm=false`

```
菮��H�D$0�H�L�=���uHH�H�H�H�f�H�l$�H�l$��+���H�mH�&�H�D$8H�L$@H�l$ H��(�H�L$H�&&�H�$H�LH�D$���H�L$������B�����H�DH�HH�@ H�L$H�D$���������dH�
                             %����H;a�SH��pH�l$hH�l$hH�D$xH�H H�@�H��$�H�fDH����H9���H�WH�
H�\$PH�wL�H9�rfH�t$HL�D$`L�H�$H�DH�L$�4���H�D$PH��$�H�AH�D$HH�A�=���uH�D$`H�H�l$hH��p�H�H�D$`�������H�L$@H�T$HH����H��sH�$H���H�D@�{9����u�����������������������H�DH�@H�D$������������������dH���f��
H��HH�l$@H�l$@H�D$PH�HH�L$0H�H�T$H�XH�\$8H�p H�t$ H�x0H�|$H�@(H�D$(L����L�$�ԫ��H�D�=8����H�L$0H�HH�H�L$H�H�L$ H�l�H�L$XH�D$`H�l$@H��H�H�x(H�L$(�*�����H�xH�L$8������H�xH�L$0�
```


![image](https://user-images.githubusercontent.com/43205944/103276983-2dcde380-49dd-11eb-834f-735dfd919603.png)

**Comment by chrislusf** [comment]
No. If posting the file directly, there won't be any chunking. The chunking is on the client side.

**Comment by kaaaq** [comment]
So where is the rest of my file?
I'm sending a  64M file directly into that volume but it shows 29.75 MiB on ui !
If there is not any chuncking when posting directly so it should upload the whole file directly into choosen fid but there is only 
29.75 MiB of my file into volume id "24"

**Comment by kaaaq** [comment]
I was testing from the master server but in another server , when I type wget it will get just 29.75MiB of file
And UI information is correct
it is not important that you send file directly or with assign api , it will just send 29.75MiB of my file!!!

**Comment by chrislusf** [comment]
I can not reproduce it. Please see my steps above.

**Comment by chrislusf** [comment]
Please share your steps on the command line. A screenshot would be better. Exclamation marks show nothing.

**Comment by kaaaq** [comment]
OK,
I think weed is compressing my file and when I want to download file from browser , it show 29.75 but after downloading it completely , it shoes 64M:
before downloading: It shows 29.7 M

![image](https://user-images.githubusercontent.com/43205944/103280005-85bc1880-49e4-11eb-8960-f0122ee4867c.png)

When I'm downloading file(it wll exceed from 29.75M):

![image](https://user-images.githubusercontent.com/43205944/103280134-dc295700-49e4-11eb-86b6-4420b88b8a6c.png)

Finished downloading: it is 64.2M

![image](https://user-images.githubusercontent.com/43205944/103280271-37f3e000-49e5-11eb-98d9-96aa52d355d1.png)

**Comment by kaaaq** [comment]
So I think weed is compressing my file,
Can I tell weed "do not compress my file" ?

**Comment by chrislusf** [comment]
You can send some strange mime type, for example "binary/data", to get around the auto mime type detection.

**Comment by kaaaq** [comment]
> If posting the file directly, there won't be any chunking. The chunking is on the client side

What do you mean from saying this sentence?
When I'm creating a fid I would post my file to specific fid
And when I commit following command:
`curl localhost:9333/dir/assign` it would return a fid to me like this:
`{"fid":"12,0230549cc56068","url":"192.168.2.7:8080","publicUrl":"192.168.2.7:8080","count":1}`
and I will post my file to this fid,
So it is directly too and would not recognize for chunking, 
How will Weedfs recognize this fid is created by itself or it's from me to chunk data?
At the end we post our file to a fid.

**Comment by chrislusf** [comment]
you can split the files into 2 chunks and request 2 fids, and post them separately.
then request a 3rd fid to post the chunk manifest file. the last fid can be used to read the file.

**Comment by kaaaq** [comment]
> you can split the files into 2 chunks and request 2 fids, and post them separately.
> then request a 3rd fid to post the chunk manifest file. the last fid can be used to read the file.

No, I mean How can I tell weed to chunk data for me automatically?
(I don't want to chunk data manually)

**Comment by chrislusf** [comment]
use `weed upload`

**Comment by kaaaq** [comment]
> use `weed upload`

So, I can not chunk my file using curl automatically?
Because I can't use "weed upload" in my php or python code

**Comment by chrislusf** [comment]
> So, I can not chunk my file using curl automatically?

Correct.

**Comment by chrislusf** [comment]
> Is there any api in weed for uploading file automatically?

Use filer API

**Comment by kaaaq** [comment]
> you can split the files into 2 chunks and request 2 fids, and post them separately.
> then request a 3rd fid to post the chunk manifest file. the last fid can be used to read the file.

How should be the structure of chunk manifest file?
Can you give me an example about this steps that you said?

**Comment by chrislusf** [comment]
See https://github.com/chrislusf/seaweedfs/wiki/Large-File-Handling
