### ISSUE TITLE
consistent data (automaticaly check)

### ISSUE THREAD

**Issue by seifer** [chrislusf/seaweedfs#172]
Hi, we plan to use seaweedfs for large file storage. In this regard we have a problem with consistent data. How we can automaticaly check, that our cluster in consist state? Its will be good if master sometimes check volume for consist and we can periodicaly fetch this information from him. What do you think about it? Im going to implement something like this.

**Comment by chrislusf** [comment]
Do you mean to check data consistency? It i hard to do so efficiently without re-scan everything.

**Comment by seifer** [comment]
Well, yes it hard, but it strongly need for production. We can do periodic re-scan

**Comment by chrislusf** [comment]
Not sure what kind of check you are thinking about for one individual file.

**Comment by seifer** [comment]
Not individual file. I want to know all copies of the volume file (and disks) in what state. No data corruption. All disks are available. No bad sectors and etc.

**Comment by seifer** [comment]
Well, in total

1. Seaweedfs permanently collect garbage
2. Seaweedfs cant guarantee that data is consistent and all file copies is exist

Sounds bad(( Its a conscious assumptions?

**Comment by chrislusf** [comment]
Guarantee the file exists if the system acknowledged so.

**Comment by seifer** [comment]
We have large data storage. And problem with disks, files, sectors is usual. We want maximum atuomaticaly actions (check, reclaim, monitoring, recovery and etc) with our data storage and want maximum guarantee that our data will be redundant and always available for client.

The trash can become critical beacuse we cant provide consistent. Cant compare volumes on replicas.

Why its always need? Because shows our expirience that problems there is a arise during operation of a big cluster of data and all situations strange at first sight are very often demanded

We want to do system maximum safe.

**Comment by libwtf** [comment]
@seifer 
looks like you need to build some custom script that runs on the nodes periodically and executes md5deep for example. this hashes every file with md5 and you can output this to a file. compare for missing files and missmatching hashsums and redistribute them.

**Comment by seifer** [comment]
@libwtf Yes its. We work on the decision right now. Probably if we find simple solution than seaweedfs go to production))

**Comment by seifer** [comment]
@chrislusf Hi. What do you think about transaction id? With tid we can delete file in master volume and replicas if there was a failed replication

**Comment by eleaner** [comment]
@seifer 
did you ever find a solution to that issue?
