### ISSUE TITLE
panic: runtime error:   version 30GB 2.15

### ISSUE THREAD

**Issue by runbestfast** [chrislusf/seaweedfs#1721]
**Describe the bug**
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc8 pc=0xeac6e8]

goroutine 265 [running]:
github.com/chrislusf/seaweedfs/weed/storage.(*Volume).CollectStatus(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
       /go/github.com/seaweedfs/weed/storage/volume.go:234 +0x88
github.com/chrislusf/seaweedfs/weed/storage.(*Volume).ToVolumeInformationMessage(0x0, 0xc00047b500, 0xc0017f5418)
       /go/github.com/seaweedfs/weed/storage/volume.go:250 +0x45
github.com/chrislusf/seaweedfs/weed/storage.(*Store).CollectHeartbeat(0xc0005a09c0, 0xc002946600)
       /go/github.com/seaweedfs/weed/storage/store.go:214 +0x1c5
github.com/chrislusf/seaweedfs/weed/server.(*VolumeServer).doHeartbeat(0xc00047c000, 0xc00046a140, 0x12, 0xc00015a100, 0x13, 0x2463540, 0xc0000c1320, 0x12a05f200, 0xc00046a140, 0x12, ...)
       /go/github.com/seaweedfs/weed/server/volume_grpc_client_to_master.go:207 +0x135c
github.com/chrislusf/seaweedfs/weed/server.(*VolumeServer).heartbeat(0xc00047c000)
       /go/github.com/seaweedfs/weed/server/volume_grpc_client_to_master.go:74 +0x3f1
created by github.com/chrislusf/seaweedfs/weed/server.NewVolumeServer
       /go/github.com/seaweedfs/weed/server/volume_server.go:100 +0xb05

**System Setup**
version 30GB 2.15  linux amd64

**Expected behavior**
gobench

**Comment by chrislusf** [comment]
this is related to https://github.com/chrislusf/seaweedfs/issues/1682 and already fixed.

Please upgrade
