### ISSUE TITLE
One of the two volume servers that contain data returns error: invalid character '\x1f' and MIME type error

### ISSUE THREAD

**Issue by kaaaq** [chrislusf/seaweedfs#1724]
Hi,
I have 3 volume servers and 1 master node, I've created a collection name "Animated_2tacopy_count" with count=1 and replication=001
I upload my file with following command:

```

sweed@dev10:~$./weedfs/weed upload -collection=Animated_2tacopy_count=1 -dir="/home/sweed/animate.mp4
[{"fileName":"animate.mp4","fileUrl":"192.168.200.23:8081/22,1d9ff15aa7","fid":"22,1d9ff15aa7","size":178481324}]

```
when I'm asking Master for my file, it return volume servers randomly:

```
sweed@dev10:~$ curl -I  192.168.200.20:9333/22,24dbfea5ed
HTTP/1.1 308 Permanent Redirect
Content-Type: text/html; charset=utf-8
Location: http://192.168.200.21:8081/22,24dbfea5ed
Date: Thu, 31 Dec 2020 15:06:08 GMT

sweed@dev10:~$ curl -I  192.168.200.20:9333/22,24dbfea5ed
HTTP/1.1 308 Permanent Redirect
Content-Type: text/html; charset=utf-8
Location: http://192.168.200.22:8081/22,24dbfea5ed
Date: Thu, 31 Dec 2020 15:06:09 GMT
```
But in browser I can't see my file from volume serevr 192.168.200.21 but In another volume server "192.168.200.22" everything is ok,
actully when browser returns the ip address of 200.22 I can see my file but when it return 200.21 I have mime type error:

![image](https://user-images.githubusercontent.com/43205944/103415573-0111fb80-4b98-11eb-9c53-568dab440166.png)

And in journalctl of server 200.21 I have this error:

```
Dec 31 18:23:50 dev11 seaweedfs-volume[20791]: I1231 18:23:50 20791 volume_server_handlers_read.go:187] load chunked manifest (/22,24dbfea5ed) error: invalid character '\x1f' looking for beginning of value

Dec 31 18:25:30 dev11 seaweedfs-volume[20791]: I1231 18:25:30 20791 volume_server_handlers_read.go:187] load chunked manifest (/22,24dbfea5ed) error: invalid character '\x1f' looking for beginning of value
Dec 31 18:25:37 dev11 seaweedfs-volume[20791]: I1231 18:25:37 20791 volume_server_handlers_read.go:187] load chunked manifest (/22,24dbfea5ed) error: invalid character '\x1f' looking for beginning of value

Dec 31 18:25:48 dev11 seaweedfs-volume[20791]: I1231 18:25:48 20791 volume_server_handlers_read.go:187] load chunked manifest (/22,24dbfea5ed) error: invalid character '\x1f' looking for beginning of value

Dec 31 18:26:29 dev11 seaweedfs-volume[20791]: I1231 18:26:29 20791 volume_server_handlers_read.go:187] load chunked manifest (/22,24dbfea5ed) error: invalid character '\x1f' looking for beginning of value
Dec 31 18:26:40 dev11 seaweedfs-volume[20791]: I1231 18:26:40 20791 volume_server_handlers_read.go:187] load chunked manifest (/22,24dbfea5ed) error: invalid character '\x1f' looking for beginning of value

Dec 31 18:26:42 dev11 seaweedfs-volume[20791]: I1231 18:26:42 20791 volume_server_handlers_read.go:187] load chunked manifest (/22,24dbfea5ed) error: invalid character '\x1f' looking for beginning of value
Dec 31 18:26:43 dev11 seaweedfs-volume[20791]: I1231 18:26:43 20791 volume_server_handlers_read.go:187] load chunked manifest (/22,24dbfea5ed) error: invalid character '\x1f' looking for beginning of value

Dec 31 18:27:03 dev11 seaweedfs-volume[20791]: I1231 18:27:03 20791 volume_server_handlers_read.go:187] load chunked manifest (/22,24dbfea5ed) error: invalid character '\x1f' looking for beginning of value

```

**Comment by chrislusf** [comment]
> I've created a collection name "Animated_2tacopy_count" with count=1 and replication=001

How did you do that?

> sweed@dev10:~$./weedfs/weed upload -collection=Animated_2tacopy_count=1 -dir="/home/sweed/animate.mp4

Seems there is an extra `=1` in the command line? And missing the end quote for `-dir`?

Need to have a reproducible case.

**Comment by kaaaq** [comment]
Hi,
I tested it with new and clear collection:
Step1:
I've created a new collection with following command:
```
> curl "http://localhost:9333/vol/grow?replication=001&count=1&collection=fault_test_2volume"
```
So now I have 2 volume on 2 of 3 servers 
Step2:
I've uploaded my file:
```
./weedfs/weed upload -collection="fault_test_2volume" -dir="/home/animate.mp4"
```
It uploaded on my servers( 192.168.200.21 and 192.168.200.23)
When I want to see my video on 200.23 it shows it very well but on 200.21 I have problem:

![image](https://user-images.githubusercontent.com/43205944/103452254-8a354980-4ce2-11eb-96da-9c84fa858740.png)


and on volume server 200.11 journal-ctl I have this error:
```
Jan 02 10:00:54 dev11 seaweedfs-volume[20791]: I0102 10:00:54 20791 volume_server_handlers_read.go:187] load chunked manifest (/29,2ca38757d4) error: invalid character '\x1f' looking for beginning of value
```

**Comment by chrislusf** [comment]
> ```
> ./weedfs/weed upload -collection="fault_test_2volume" -dir="/home/animate.mp4"
> ```

This command did not have replication specified, so it used replication=000. 
One collection can also have multiple types of replications. 

I suppose the above `weed upload` command will generate at least 3 file ids. One of them is the chunk manifest. The other two or more are the chunks. The one you showed error is the second half of the mp3 file.

**Comment by kaaaq** [comment]
> > ```
> > ./weedfs/weed upload -collection="fault_test_2volume" -dir="/home/animate.mp4"
> > ```
> 
> This command did not have replication specified, so it used replication=000.
> One collection can also have multiple types of replications.
> 
> I suppose the above `weed upload` command will generate at least 3 file ids. One of them is the chunk manifest. The other two or more are the chunks. The one you showed error is the second half of the mp3 file.

But I've define replication in Master:
1.`./weed master -mdir="/home/sweedfs/master" -port=9333 -defaultReplication=001`
And I define replication when I wanted to create volume with "/vol/grow":
‍‍2.`> curl "http://localhost:9333/vol/grow?replication=001&count=1&collection=fault_test_2volume"`

**Comment by chrislusf** [comment]
Added code to read default collection from master. https://github.com/chrislusf/seaweedfs/commit/4250a3a67510dda9fe9d6e38d4ea617c97c4c214

**Comment by kaaaq** [comment]
> > ```
> > ./weedfs/weed upload -collection="fault_test_2volume" -dir="/home/animate.mp4"
> > ```
> 
> This command did not have replication specified, so it used replication=000.
> One collection can also have multiple types of replications.
> 
> I suppose the above `weed upload` command will generate at least 3 file ids. One of them is the chunk manifest. The other two or more are the chunks. The one you showed error is the second half of the mp3 file.

I still have problem even when I'm defining replication in "weed upload":
Please look at my steps:

Step1: I create a collection with replication=001 :
`
sweed@dev10:~$ curl "http://localhost:9333/vol/grow?replication=001&count=1&collection=fault_test_define_rep001"
{"count":2}
`
step2: then I upload my file using weed upload with defining "-replication=001"
```
sweed@dev10:~$ ./weedfs/weed upload -collection="fault_test_define_rep001" -dir="/home/animate.mp4" -replication=001

[{"fileName":"animate.mp4","fileUrl":"192.168.200.22:8081/192,a6384143af","fid":"192,a6384143af","size":178481324}]
```
please notice to this url `fileUrl":"192.168.200.22:8081`
`It is server  200.22`

Step3: curl fid from master to find all replica: one rep is  200.22 and another is 200.23
```
sweed@dev10:~$ curl -I 192.168.200.20:9333/192,a6384143af
Location: http://192.168.200.22:8081/192,a6384143af
```
```
sweed@dev10:~$ curl -I 192.168.200.20:9333/192,a6384143af
Location: http://192.168.200.23:8081/192,a6384143af
```
Step4: Downloading file:
From 200.22 (Its OK) 187MB
```
sweed@dev10:~$ wget http://192.168.200.22:8081/192,a6384143af
--2021-01-03 11:49:56--  http://192.168.200.22:8081/192,a6384143af
Connecting to 192.168.200.22:8081... connected.
HTTP request sent, awaiting response... 200 OK
Length: 178481324 (170M) [video/mp4]
Saving to: ‘192,a6384143af.1’

192,a6384143af.1                  100%[============================================================>] 170.21M   187MB/s    in 0.9s    

2021-01-03 11:49:57 (187 MB/s) - ‘192,a6384143af.1’ saved [178481324/178481324]
```

From 200.23 (Its NOT OK) 15.7MB
```
sweed@dev10:~$ wget http://192.168.200.23:8081/192,a6384143af
--2021-01-03 11:49:38--  http://192.168.200.23:8081/192,a6384143af
Connecting to 192.168.200.23:8081... connected.
HTTP request sent, awaiting response... 200 OK
Length: 211 [video/mp4]
Saving to: ‘192,a6384143af’

192,a6384143af                    100%[============================================================>]     211  --.-KB/s    in 0s      

2021-01-03 11:49:38 (15.7 MB/s) - ‘192,a6384143af’ saved [211/211]
```

**Comment by chrislusf** [comment]
Thanks! Found the problem and added a fix. The manifest file was compressed but not detected.
