### ISSUE TITLE
seaweedfs安全机制是什么？

### ISSUE THREAD

**Issue by hs518** [chrislusf/seaweedfs#1725]
我只是想实现：读不限制，写、删除操作在指定机器上操作，设置了白名单但是在白名单外的IP依旧可以删除volume上的数据。

**Comment by chrislusf** [comment]
For filer, there are read-only port that you can open to everyone. The full access port can be used for other access. You can configure them via nginx.

For volume servers, there are JWT you can use. https://github.com/chrislusf/seaweedfs/wiki/Security-Overview#jwt-based-access-control

**Comment by hs518** [comment]
read-only port&nbsp;具体是哪个，如何操作，百度关于SeaweedFS的文档太少了，基本都是千篇一律，深入的没有。JWT倒是实现了，还想看看有没有简单的方法。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chrislusf/seaweedfs"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月2日(星期六) 凌晨5:06
收件人:&nbsp;"chrislusf/seaweedfs"<seaweedfs@noreply.github.com&gt;;
抄送:&nbsp;"秋宇轩/:D"<qiuyuxuan518@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [chrislusf/seaweedfs] seaweedfs安全机制是什么？ (#1725)





 
For filer, there are read-only port that you can open to everyone. The full access port can be used for other access. You can configure them via nginx.
 
For volume servers, there are JWT you can use. https://github.com/chrislusf/seaweedfs/wiki/Security-Overview#jwt-based-access-control

**Comment by chrislusf** [comment]
check `weed filer -h` and `weed volume -h`
