### ISSUE TITLE
memory related bugs of rocksdb implementation

### ISSUE THREAD

**Issue by qieqieplus** [chrislusf/seaweedfs#1726]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

Hi Chris,
I maintained my own rocksdb branch previously, happy to find out it's now offically supported.
Here's some small suggestions for the current implementation.
1. Option objects created from `NewDefaultOptions` `NewDefaultReadOptions` `NewDefaultWriteOptions` contain cgo pointers need to be released explicitly.
2. rocksdb_store.go#L96 `entry.FullPath` leads to nil pointer dereference.
3. Rocksdb iterator related keys & values will be freed automatically upon iterator's destruction, so `iter.Close()` ensures no memory leak without `key.Free()` or `value.Free()`.

Other possible improvements:
1. Reuse default options when possible.
2. Use `db.Get`(and free by hand) instead of `db.GetBytes` to avoid memory copy when bytes are read only. Gorocksdb `charToByte` use reflect tricks by creating byte slice with underlying C char array to avoid char* to go []byte copy, while `C.GoBytes` performs memory copy.

**Comment by chrislusf** [comment]
This is great! Did you do any performance benchmarks between leveldb and rocksdb? I added a small test but not seeing any differences.

**Comment by qieqieplus** [comment]
There is no significant performance difference with my workloads.
but I'm mostly aim for 
1. removing expired keys based on TTL by rocksdb compaction filter, like current redis, cassandra filer implementation.
2. more tuning options, mainly reduce write amplification or reduce write stall.

**Comment by qieqieplus** [comment]
I'll provide more patches if you're interested in features like TTL, but it's not tested yet.

**Comment by chrislusf** [comment]
Yes. TTL feature would be interesting.
