### ISSUE TITLE
panic: raft: Index is beyond end of log: 3 38

### ISSUE THREAD

**Issue by norteee** [chrislusf/seaweedfs#1729]
搭建：启动3个master，1个volume，3个filer，存储使用redis-cluster
启动命令：

`master server: /usr/bin/weed master -mdir=/data -volumePreallocate -volumeSizeLimitMB=1024 -peers=10.90.139.247:9333,10.90.136.47:9333,10.90.137.97:9333 -ip=10.90.136.47 -port=9333

volume server: /usr/bin/weed volume -dir=/data -max=0 -mserver=10.90.139.247:9333,10.90.136.47:9333,10.90.137.97:9333 -port=9888 -ip=10.90.136.199

filer server: ./weed filer -master=10.90.136.47:9333,10.90.139.247:9333,10.90.137.97:9333 -peers 10.90.136.47:8888,10.90.139.247:8888,10.90.137.97:8888 -ip=10.90.136.47 -port=8888
`

目前出现过以下几个问题：

1. 启动上述服务后，停下leader; 可以选出新leader，但是volume没有同步过去；出现了几次
2. 剩下1个，此时已经无法选出leader了，最后一个master输出是：
    I0105 07:25:28     1 master_server.go:141] leader change event: 10.90.136.47:9333 =>
3. 接着重启停掉的master，出现下述错误(偶现一次)
`
panic: raft: Index is beyond end of log: 3 38

goroutine 258 [running]:
github.com/chrislusf/raft.(*Log).getEntriesAfter(0xc00012cc40, 0x26, 0x7d0, 0x0, 0x0, 0x0, 0x0)
	/root/go/pkg/mod/github.com/chrislusf/raft@v1.0.3/log.go:256 +0x87b
github.com/chrislusf/raft.(*Peer).flush(0xc00064aa80)
	/root/go/pkg/mod/github.com/chrislusf/raft@v1.0.3/peer.go:179 +0xe9
github.com/chrislusf/raft.(*Peer).heartbeat(0xc00064aa80, 0xc0000af500)
	/root/go/pkg/mod/github.com/chrislusf/raft@v1.0.3/peer.go:167 +0x23c
github.com/chrislusf/raft.(*Peer).startHeartbeat.func1(0xc00064aa80, 0xc0000af500)
	/root/go/pkg/mod/github.com/chrislusf/raft@v1.0.3/peer.go:100 +0x75
created by github.com/chrislusf/raft.(*Peer).startHeartbeat
	/root/go/pkg/mod/github.com/chrislusf/raft@v1.0.3/peer.go:98 +0x12d
`

**Comment by chrislusf** [comment]
You may need to run master with this option `weed master -resumeState`

the behavior seems reasonable.

**Comment by norteee** [comment]
@chrislusf 

加了参数之后会出现：

`panic: assertion failed: leader.elected.at.same.term.1125


goroutine 118 [running]:
github.com/chrislusf/raft._assert(...)
	/root/go/pkg/mod/github.com/chrislusf/raft@v1.0.3/util.go:60
github.com/chrislusf/raft.(*server).processAppendEntriesRequest(0xc0002d0a20, 0xc000050aa0, 0xc000050aa0, 0x0)
	/root/go/pkg/mod/github.com/chrislusf/raft@v1.0.3/server.go:983 +0xb37
github.com/chrislusf/raft.(*server).leaderLoop(0xc0002d0a20)
	/root/go/pkg/mod/github.com/chrislusf/raft@v1.0.3/server.go:884 +0x441
github.com/chrislusf/raft.(*server).loop(0xc0002d0a20)
	/root/go/pkg/mod/github.com/chrislusf/raft@v1.0.3/server.go:609 +0x1fd
github.com/chrislusf/raft.(*server).Start.func1(0xc0002d0a20)
	/root/go/pkg/mod/github.com/chrislusf/raft@v1.0.3/server.go:470 +0x64
created by github.com/chrislusf/raft.(*server).Start
	/root/go/pkg/mod/github.com/chrislusf/raft@v1.0.3/server.go:468 +0x1a8`

没出现上述问题的话，好像volume也没自动同步过去
是我设置的问题么？

/usr/bin/weed master -mdir=/data -volumePreallocate -volumeSizeLimitMB=1024 -resumeState -ip=10.90.137.97 -port=9333 -peers=10.90.139.247:9333,10.90.136.47:9333,10.90.137.97:9333

/usr/bin/weed volume -dir=/data -max=0 -mserver=10.90.139.247:9333,10.90.136.47:9333,10.90.137.97:9333 -port=9888 -ip=10.90.136.199

**Comment by chrislusf** [comment]
> 没出现上述问题的话，好像volume也没自动同步过去
> 是我设置的问题么？

what is the behavior? It takes a little time for the volume servers to switch to the new leader.

**Comment by chrislusf** [comment]
Updates?

**Comment by norteee** [comment]
@chrislusf 
抱歉之前弄别的停了一段时间；换了一种部署方式，暂时没有出现上述问题；但是有些疑问，所以想再打扰下；
我先阐述下我的测试背景和部署方式：
我想部署个文件系统供特定集群使用，只有这些会用，大概100来个节点来上传下载大概100m左右大小的文件，频率不高；做了个测试，如果把filer和master放在一起部署的话，流量就还是要通过部署filer的节点，这样下载的流量会受到到filer节点的限制？所以将filer和volume节点部署在一起，避免这个困扰。（另外filer的数据和master部署在一起）
部署方式：
![2021114-91415](https://user-images.githubusercontent.com/76904955/104570411-d9895b80-568c-11eb-9d2d-a9795d5fe1c9.jpeg)

但是出现了和之前filer-master部署不一样的结果，之前filer和master部署在同一个节点上时，内存并不会有多大波动；但是分开部署后，出现了filer占用很多内存的情况；由于我只分配了4个g，4个g全占满了，我有点疑惑，缓存什么呢？（当前系统里只有100+文件，文件大小2k-100m之间）
volume的话使用leveldb做缓存的情况下，也会占用部分内存（1g+），这里是缓存的什么呢？

期待您的答复！感谢！

**Comment by chrislusf** [comment]
filer memory = number_of_concurrent_access * chunk_size

volume memory = number_of_volumes * leveldb_memory_usage_per_voume, in order to access files quickly.

I recommend use separate filers.

**Comment by norteee** [comment]
> filer memory = number_of_concurrent_access * chunk_size
> 
> volume memory = number_of_volumes * leveldb_memory_usage_per_voume, in order to access files quickly.
> 
> I recommend use separate filers.

感谢回复，volume貌似还有一个是并发读取的时候，并发数量*文件大小，这个内存占用？这里的内存为什么不能在使用后立即释放呢？

**Comment by chrislusf** [comment]
Go 1.6 will be able to return memory to the operating system.

**Comment by norteee** [comment]
您是说内存缓慢下降是go自己的内存清理么？那用完就释放呢？

于2021年1月15日 (周五) 05:04 <notifications@github.com> 写道:

Go 1.6 will be able to return memory to the operating system.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/chrislusf/seaweedfs/issues/1729#issuecomment-760474955>,
or unsubscribe

**Comment by chrislusf** [comment]
> 是go自己的内存清理

**Comment by norteee** [comment]
好的了解，我再使用、了解下，有问题再打扰您，感谢！

于2021年1月18日 (周一) 12:51 <notifications@github.com> 写道:

是go自己的内存清理

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/chrislusf/seaweedfs/issues/1729#issuecomment-761978031>,
or unsubscribe
