### ISSUE TITLE
'unrecognized import path' when i install seaweedfs

### ISSUE THREAD

**Issue by breaklee** [chrislusf/seaweedfs#173]
how can i fix this?

------------------------------------

package github.com/chrislusf/seaweedfs/go/weed
	imports bazil.org/fuse: unrecognized import path "bazil.org/fuse"
package github.com/chrislusf/seaweedfs/go/weed
	imports bazil.org/fuse/fs: unrecognized import path "bazil.org/fuse/fs"

**Comment by chrislusf** [comment]
make sure you can access bazil.org

https://github.com/chrislusf/seaweedfs/issues/106
