### ISSUE TITLE
[Question] - Seawedfs Architecture

### ISSUE THREAD

**Issue by kaaaq** [chrislusf/seaweedfs#1731]
Hi,
I have some questions about seaweedfs:
1. I saw weed has 2 version 1.large file and 2. normal version
a.Where should I use large version and where should I use normal version?
b.In terms of architecture and storing files, How do each of them work (How they will store files?)

2. I read in wiki that from all masters just we can have one leader that all load is on Leader and in my opinion
this is Bottleneck, what should we do for big production scale?
Its not good to have just one leader for many volume servers and many hardware
What is the best solution for Big production scale with many hard drives and volume servers?

3. About erasure coding:
I read that we can have 2 tiers and just for warm tier we can use EC
Is it true?
a.You mean I can not use EC directly when user upload their files to weed like Minio? and first I should store users file in replication mode and After a period of time I can change the volumes to EC?
Would you please explain it more?

b.How should be the architecture of EC in productoin, I have no idea about implementing EC , please explain it more
How can I use it.
Should be in volume level or should I seprate my cluster when I want to change old file to EC?

c .I think if the passage of time includes it, changing files to EC has too overload, what is your suggestion to this?

**Comment by ddorian** [comment]
> I saw weed has 2 version 1.large file and 2. normal version
> a.Where should I use large version and where should I use normal version?
> b.In terms of architecture and storing files, How do each of them work (How they will store files?)
> 

It's "big volume". The volumes can be bigger than 30GB. So master will have less metadata because fewer volumes. @chrislusf can say what is the per-volume overhead ?

>  a.You mean I can not use EC directly when user upload their files to weed like Minio? and first I should store users file in replication mode and After a period of time I can change the volumes to EC?

Yes, you can "lock" a volume for no more writes/updated, and then you can EC it. On Minio, EC is probably done per-file while here it's done per-volume.

> I read in wiki that from all masters just we can have one leader that all load is on Leader and in my opinion
> this is Bottleneck, what should we do for big production scale?
> Its not good to have just one leader for many volume servers and many hardware
> What is the best solution for Big production scale with many hard drives and volume servers?

Look into the architecture more. You write/read to volume-servers directly while master is only for metadata.

> b.How should be the architecture of EC in productoin, I have no idea about implementing EC , please explain it more
> How can I use it.
> Should be in volume level or should I seprate my cluster when I want to change old file to EC?

It's already there. There are just [shell commands](https://github.com/chrislusf/seaweedfs/wiki/weed-shell) to change volumes to/from ec.

> c .I think if the passage of time includes it, changing files to EC has too overload, what is your suggestion to this?

 There are just [shell commands](https://github.com/chrislusf/seaweedfs/wiki/weed-shell) to change volumes to/from ec.

**Comment by kaaaq** [comment]
> It's "big volume". The volumes can be bigger than 30GB. So master will have less metadata because fewer volumes. @chrislusf can say what is the per-volume overhead ?
You mean I can not have bigger volume(30GB) in normal version?

**Comment by kaaaq** [comment]
Would you please answer my quesion? https://github.com/chrislusf

**Comment by chrislusf** [comment]
Thanks @ddorian for answering! His answers are all correct.

The per volume overhead is just in memory objects and hard to measure accurately. A rough estimation is about 1KB per volume? 
I have not seen any deployment with the master memory issues yet.

**Comment by kaaaq** [comment]
> It's "big volume". The volumes can be bigger than 30GB. So master will have less metadata because fewer volumes. @chrislusf can say what is the per-volume overhead ?

you mean that the only differnce between two versions is volume size? and in normal version I cant have volume larger than 30G?

**Comment by ddorian** [comment]
> you mean that the only differnce between two versions is volume size? and in normal version I cant have volume larger than 30G?

Yes.

**Comment by kaaaq** [comment]
> Look into the architecture more. You write/read to volume-servers directly while master is only for metadata.

Yes, you are correct but before write/read I should assign fid, that all request goes to leader for this
and in big scale, it can be trouble!

**Comment by chrislusf** [comment]
> Yes, you are correct but before write/read to volume server, I should assign fid, that all requests will go to leader for getting fid
> and in big scale, it can be trouble!

Correct. Let me know if you get to that scale.

**Comment by kaaaq** [comment]
> > Yes, you are correct but before write/read to volume server, I should assign fid, that all requests will go to leader for getting fid
> > and in big scale, it can be trouble!
> 
> Correct. Let me know if you get to that scale.

Can you examine an approximate number for this hardware:
20 volume servers with 10*10TB H.D.D on each server
Can leader tolerate this metadata? 
You said I will have 1KB per volume overhead for assigning fids and metadata?

**Comment by kaaaq** [comment]
> It's already there. There are just [shell commands](https://github.com/chrislusf/seaweedfs/wiki/weed-shell) to change volumes to/from ec.

I read all commands in weed shell, But my problem is architecture ,
What is the best architecture for implementing ec ?
Should I wait to volumes become filled and then run ec commands or should I do it ex: every day on each volume?
and we know that in clusters we have multiple volume , how should I do this ?
I said that if the passage of time includes it, changing files to EC has too overload, what is your suggestion to this? (should I have seprate cluster for changing volumes to EC?)

**Comment by ddorian** [comment]
> Can you examine an approximate number for this hardware:
> 20 volume servers with 10*10TB H.D.D on each server
> Can leader tolerate this metadata?

If 1 volume == 30GB == 1kb metadata in-memory on master.
Then 10GB memory on master == 300PB data size.

> You said I will have 1KB per volume overhead for assigning fids and metadata?

The scalability may be when you are upload 10K+ files/second. To do this, you'd first need 1K+ servers (note each file is replicated and it would be massive bandwidth 1Tbs+)

>  What is the best architecture for implementing ec ?

You just run the commands and seaweed will encode & move files around.

>  Should I wait to volumes become filled and then run ec commands or should I do it ex: every day on each volume?

See options of the commands. Usually they work after a volume has been idle for 1+ hour.

>  and we know that in clusters we have multiple volume , how should I do this ?

https://github.com/chrislusf/seaweedfs/wiki/Erasure-Coding-for-warm-storage#how-to-enable-it

>  I said that if the passage of time includes it, changing files to EC has too overload, what is your suggestion to this? (should I have seprate cluster for changing volumes to EC?)

Again, look at `ec.decode` command https://github.com/chrislusf/seaweedfs/wiki/weed-shell which will convert it to a normal volume.

>  20 volume servers with 10*10TB H.D.D on each server

This server looks familiar. I'm guessing it doesn't have 10Gbs+ network. You should be careful on recovery time (how long to fill a server, how long to spread a server's data around).

**Comment by kaaaq** [comment]
> It's "big volume". The volumes can be bigger than 30GB. So master will have less metadata because fewer volumes. @chrislusf can say what is the per-volume overhead ?

a. How big the volumes size can be in large version?
b. If I have 10TB hard with large version , How many volumes with which size do you prefer?
ex: 100*100GB Volumes is a Good number and size for 10TB hard? what is you suggestion? @chrislusf

**Comment by chrislusf** [comment]
20

**Comment by kaaaq** [comment]
> See options of the commands. Usually they work after a volume has been idle for 1+ hour.

How can I find 1 hour volume's slept in weed? because in the following command I should define volume id but How can I find that volume?
```
> ec.encode -help
Usage of ec.encode:
  -collection string
    	the collection name
  -fullPercent float
    	the volume reaches the percentage of max volume size (default 95)
  -quietFor duration
    	select volumes without no writes for this period (default 1h0m0s)
  -volumeId int
    	the volume id
```

**Comment by chrislusf** [comment]
> > See options of the commands. Usually they work after a volume has been idle for 1+ hour.
> 
> How can I find 1 hour volume's slept in weed? because in the following command I should define volume id but How can I find that volume?
> 
> ```
> > ec.encode -help
> Usage of ec.encode:
>   -collection string
>     	the collection name
>   -fullPercent float
>     	the volume reaches the percentage of max volume size (default 95)
>   -quietFor duration
>     	select volumes without no writes for this period (default 1h0m0s)
>   -volumeId int
>     	the volume id
> ```

Obviously you did not try it.

**Comment by kaaaq** [comment]
> This server looks familiar. I'm guessing it doesn't have 10Gbs+ network. You should be careful on recovery time (how long to fill a server, how long to spread a server's data around).

I think you have a miscalculation because if I have 10*10TB on each server and sine each spinning disk can not exceed 50 MB write, So all traffic in one server will not exceed 4Gb , and I think a 10Gb network is enough for each server
10 spinnig disk * 50 MB speed write = 500 MB = 4000 Mb  = 4Gb 
and I still have 6Gb free of my network

**Comment by kaaaq** [comment]
> > > See options of the commands. Usually they work after a volume has been idle for 1+ hour.
> > 
> > 
> > How can I find 1 hour volume's slept in weed? because in the following command I should define volume id but How can I find that volume?
> > ```
> > > ec.encode -help
> > Usage of ec.encode:
> >   -collection string
> >     	the collection name
> >   -fullPercent float
> >     	the volume reaches the percentage of max volume size (default 95)
> >   -quietFor duration
> >     	select volumes without no writes for this period (default 1h0m0s)
> >   -volumeId int
> >     	the volume id
> > ```
> 
> Obviously you did not try it.

Yes, I've tried it:
```
> ec.encode -volumeId=30
markVolumeReadonly 30 on 192.168.200.21:8081 ...
markVolumeReadonly 30 on 192.168.200.22:8081 ...
generateEcShards  30 on 192.168.200.21:8081 ...
parallelCopyEcShardsFromSource 30 192.168.200.21:8081
allocate 30.[2 5 8 11] 192.168.200.21:8081 => 192.168.200.22:8081
allocate 30.[1 4 7 10 13] 192.168.200.21:8081 => 192.168.200.23:8081
allocate 30.[0 3 6 9 12] 192.168.200.21:8081 => 192.168.200.21:8081
copy 30.[2 5 8 11] 192.168.200.21:8081 => 192.168.200.22:8081
copy 30.[1 4 7 10 13] 192.168.200.21:8081 => 192.168.200.23:8081
mount 30.[0 3 6 9 12] on 192.168.200.21:8081
mount 30.[2 5 8 11] on 192.168.200.22:8081
I0107 15:37:08 05588 command_ec_common.go:90] 192.168.200.21:8081 ec volume 30 deletes shards [2 5 8 11]
mount 30.[1 4 7 10 13] on 192.168.200.23:8081
I0107 15:37:08 05588 command_ec_common.go:90] 192.168.200.21:8081 ec volume 30 deletes shards [1 4 7 10 13]
unmount 30.[2 5 8 11 1 4 7 10 13] from 192.168.200.21:8081
delete 30.[2 5 8 11 1 4 7 10 13] from 192.168.200.21:8081
delete volume 30 from 192.168.200.21:8081
delete volume 30 from 192.168.200.22:8081

```

**Comment by kaaaq** [comment]
> a. up to 8TB
> b. 20 x 512GB
I have ongoing writes on my volumes so If I want to change the volume type to EC, I should wait 1 hour after fulling them or 95 percent of it, So 512 GB of volume data  isn't so much to change EC? I think it has high overhead
Can you say how much overhead it would have per 512GB volume?

**Comment by ddorian** [comment]
> I think you have a miscalculation because if I have 10*10TB on each server and sine each spinning disk can not exceed 50 MB write, So all traffic in one server will not exceed 4Gb , and I think a 10Gb network is enough for each server
> 10 spinnig disk * 50 MB speed write = 500 MB = 4000 Mb = 4Gb
> and I still have 6Gb free of my network

Dude, check the difference between "giga bit" and "giga byte". 

> I have ongoing writes on my volumes so If I want to change the volume type to EC, I should wait 1 hour after fulling them or 95 percent of it, So 512 GB of volume data isn't so much to change EC? I think it has high overhead
> Can you say how much overhead it would have per 512GB volume?

Based on your knowledge, use the default volume sizes, you don't need to mess with big volumes.

**Comment by ddorian** [comment]
> Dude, check the difference between "giga bit" and "giga byte".

Your calculations were ok, my mistake. But disks should be able to write 100MB/s. 
And you will also be serving reads at the same time.
So you have replication + reads + writes happening all the time.

**Comment by chrislusf** [comment]
> > > > See options of the commands. Usually they work after a volume has been idle for 1+ hour.
> > > 
> > > 
> > > How can I find 1 hour volume's slept in weed? because in the following command I should define volume id but How can I find that volume?
> > > ```
> > > > ec.encode -help
> > > Usage of ec.encode:
> > >   -collection string
> > >     	the collection name
> > >   -fullPercent float
> > >     	the volume reaches the percentage of max volume size (default 95)
> > >   -quietFor duration
> > >     	select volumes without no writes for this period (default 1h0m0s)
> > >   -volumeId int
> > >     	the volume id
> > > ```
> > 
> > 
> > Obviously you did not try it.
> 
> Yes, I've tried it:
> 
> ```
> > ec.encode -volumeId=30
> markVolumeReadonly 30 on 192.168.200.21:8081 ...
> markVolumeReadonly 30 on 192.168.200.22:8081 ...
> generateEcShards  30 on 192.168.200.21:8081 ...
> parallelCopyEcShardsFromSource 30 192.168.200.21:8081
> allocate 30.[2 5 8 11] 192.168.200.21:8081 => 192.168.200.22:8081
> allocate 30.[1 4 7 10 13] 192.168.200.21:8081 => 192.168.200.23:8081
> allocate 30.[0 3 6 9 12] 192.168.200.21:8081 => 192.168.200.21:8081
> copy 30.[2 5 8 11] 192.168.200.21:8081 => 192.168.200.22:8081
> copy 30.[1 4 7 10 13] 192.168.200.21:8081 => 192.168.200.23:8081
> mount 30.[0 3 6 9 12] on 192.168.200.21:8081
> mount 30.[2 5 8 11] on 192.168.200.22:8081
> I0107 15:37:08 05588 command_ec_common.go:90] 192.168.200.21:8081 ec volume 30 deletes shards [2 5 8 11]
> mount 30.[1 4 7 10 13] on 192.168.200.23:8081
> I0107 15:37:08 05588 command_ec_common.go:90] 192.168.200.21:8081 ec volume 30 deletes shards [1 4 7 10 13]
> unmount 30.[2 5 8 11 1 4 7 10 13] from 192.168.200.21:8081
> delete 30.[2 5 8 11 1 4 7 10 13] from 192.168.200.21:8081
> delete volume 30 from 192.168.200.21:8081
> delete volume 30 from 192.168.200.22:8081
> ```

the volumeId is optional
