### ISSUE TITLE
[Question] Viability of SeaweedFS as filer metadata store

### ISSUE THREAD

**Issue by M-Pixel** [chrislusf/seaweedfs#1732]
I'm curious why an external database is required for filer metadata.  I see that this has, of course, been asked and answered before  on Slack.  However, while I saw explanations as to why a database would be useful, I couldn't find any clarity on why SeaweedFS itself is insufficient.  Redis is a key-value store.  SeaweedFS is a key-value store.  If Redis can be used as the database, why can't Seaweed be used as the database?

**Comment by chrislusf** [comment]
SeaweedFS Filer uses LevelDB by default, which is just embedded key-value store. Its content is replicated asynchronously to other filers, if `-peers` is configured.

This is an eventual consistency model. But it is just one consistency model and other use cases can be very different.

That said, I do see other different data systems can be built on top of existing object storage. Still needs to find out which one the users really need.

**Comment by nivekuil** [comment]
The idea of SeaweedFS being a storage system with the API of s3 and the operational characteristics of redis is quite interesting. Storing small values directly in the metadata layer is actually the design of a recent storage project at Facebook; it seems SeaweedFS managed to come up with this unified metadata component (the filer) earlier and indepedently, which is one benefit of a single architect vs multiple teams.

I haven't tried https://github.com/chrislusf/seaweedfs/wiki/Filer-as-a-Key-Large-Value-Store yet but looking at the wiki page I have a few questions. How does enabling super large directories affect the s3 api? "This is assuming the /home/user is a new folder." what is a new folder, an empty folder or one that has not yet been configured as a super large directory? 

With `cacheToFilerLimit`, is the filer being used as a write-through cache, incurring the full latency of writing all replicas to the volumes? It could be interesting, though probably with substantial additional complexity, to just write to the filer store and asynchronously persist it to the volumes. I think this would only be a good idea with a strongly consistent filer store (redis-raft looks interesting for this) 

I also want to point out that there's a github discussions feature: https://docs.github.com/en/free-pro-team@latest/discussions/quickstart not sure how popular it'll be, but I see some projects trying it out.

**Comment by chrislusf** [comment]
@nivekuil thanks for the nice words!


> How does enabling super large directories affect the s3 api?

For listing operations in the large directory will return nothing. But other directories will work as usual.


> "This is assuming the /home/user is a new folder." 

I changed it to "an empty folder".

> is the filer being used as a write-through cache

Actually I am thinking to use the small data in filer as the source of truth, and simply do not write to volume servers. The data on volume servers without filer metadata is not really useful anyway. What do you think？

> there's a github discussions

Nice! Added.

**Comment by ddorian** [comment]
> I'm curious why an external database is required for filer metadata.

So he doesn't build/invent a new database. And he can spend more time doing the storage.
And you already have tools to easily query,replicate,maintain,monitor,backup,etc,etc each of those databases.

**Comment by ddorian** [comment]
> Actually I am thinking to use the small data in filer as the source of truth, and simply do not write to volume servers. The data on volume servers without filer metadata is not really useful anyway. What do you think？

Yes this makes sense. Many filesystems do this, where small objects are only written in metadata. See HopFS using NDB cluster for small files & metadata in HDFS https://content.logicalclocks.com/hubfs/research/ccgrid-scaling-hdfs-ieee-scale-prize-winner.pdf  http://www.diva-portal.org/smash/get/diva2:1260838/FULLTEXT01.pdf

**Comment by chrislusf** [comment]
"To the best of our knowledge, this is the first open-source tiered block stored solution for a hierarchical file system that uses a distributed relational database to store small files blocks."

Seems the author did not check SeaweedFS.
