### ISSUE TITLE
[Filer] Can't successfully upload/download some files

### ISSUE THREAD

**Issue by M-Pixel** [chrislusf/seaweedfs#1737]
> Error 0x80070021: The process cannot access the file because another process has locked a portion of the file.

Windows 10 displays the above error at the very end of attempting to copy a 30.8 GB file to a SeaweedFS WebDAV endpoint via Windows Explorer.  By "at the very end", I mean after the "bytes remaining" readout fully descends to 0.  After the first attempt, the error occurs immediately upon attempting to copy again (until the server is rebooted, after which point it will once more run through the progress bar before erroring).

I confirmed that I was able to copy the file to another drive, so the source file is not locked.  There is no file of the same name already in the destination folder.  Based on these facts, I believe that the error is misleading:  Although it supposes that another process has locked a portion of the file, the reality is probably that it simply received a failure when attempting to lock a file portion itself (locked-by-another-process is probably just the most common cause for lock acquisition failure).

I _was_ able to **upload** the file successfully via S3.  After uploading the file through S3, various S3 clients on various computers, as well as WebDAV clients on different computers, are able to see the file and its size.  However, when attempting to download the file through WebDAV, the same error occurs, and when attempting to download it through S3, a 404 error occurs.  For some other files, "System.IO.IOException: Unable to read the data from the transport connection: The connection was closed." is returned upon attempting to retrieve through S3.  Based on these facts, I suspect that the problem lies in Filer, Volume Service, or Master Service, rather than in WebDAV or S3.  There is clearly some fault in the S3 implementation compared to the WebDAV implementation in that it registers the file into the filesystem database despite failing to actually write its data (sufficiently) into the volume service.

I initially suspected that this may be related to file size:  This problem occured consistently on all files I tried which exceed 4.2GB and not on any files that are smaller.  However, eventually, it also occurred on a 1.7MB file.

Other files can still be read/written without error.  Nothing is logged (default verbosity) in coincidence with these problems, and there are no errors in the logs.   The only warnings logged are `W0106 18:05:34  8044 master_grpc_server.go:57] SendHeartbeat.Recv server xxxxxxxxx:10001 : rpc error: code = Canceled desc = context canceled` which appears on master on start-up.

Rebooting the server does not resolve the problem.

I'm using pre-built weed.exe 2.19 downloaded from GitHub.

What information should I collect in order to further diagnose this problem?

**Comment by M-Pixel** [comment]
The issue persists after completely nuking and re-initializing my installation.  So, I'm now able to reproduce with:

- Start master, volume1, volume2, filer, and WebDAV
- Try to copy particular file over WebDAV

In this case, I tried to copy a 10GB file.  I noticed that only 2.3GB is taken up on each of the two volume server folders.  An identical amount of data is occupied by both volume server folders.  I also noticed that the volume files' size, as reported by Windows Explorer, did not increase from 0 until significantly (a few minutes) after the file transfer near-completed then failed.

**Comment by chrislusf** [comment]
> * Try to copy particular file over WebDAV

How to reproduce this?

**Comment by M-Pixel** [comment]
Given how many files I'm encountering the issue on, my gut tells me that if I sent you one of the problem files, you probably wouldn't encounter the same issue.  Who knows if the repro will end up requiring the same hard drive, filesystem settings, operating system build, or something else.  I'm interested in firing up a debugger to see if I can diagnose the exact cause of the issue.  If you were running into this issue, which functions and values would you look into first?

**Comment by chrislusf** [comment]
Thanks!

For all important logic for WebDav related code is in this single file:
https://github.com/chrislusf/seaweedfs/blob/master/weed/server/webdav_server.go

This `CloseFunc` is the function to call when register the file to filer. These two functions are the only two operations that could fail.

https://github.com/chrislusf/seaweedfs/blob/master/weed/server/webdav_server.go#L450
https://github.com/chrislusf/seaweedfs/blob/master/weed/server/webdav_server.go#L458

To debug, there is this make file target:
https://github.com/chrislusf/seaweedfs/blob/master/weed/Makefile#L29

**Comment by dch** [comment]
do you have antivirus software running on this windows box? if so, try with it disabled, or to mark the seaweedfs data as out of scope.

**Comment by chrislusf** [comment]
@M-Pixel please re-open if you found something.
