### ISSUE TITLE
File locking support

### ISSUE THREAD

**Issue by Woellchen** [chrislusf/seaweedfs#1745]
I've got a question about the weed filer. Is there any file locking support? I could not find anything about it.
Talking specifically about FUSE mounts here, but would also be interested in general (filer directly).
On the wiki page https://github.com/chrislusf/seaweedfs/wiki/FUSE-Mount, locking is not listed as a supported feature.
So: is it possible to lock files in any way in SeaweedFS? Can I maybe add a custom flag somewhere and check for it on my own?
Thank you!

**Comment by chrislusf** [comment]
For FUSE mount, this is not supported, because all meta data operations are asynchronously replicated to filer meta store.

If you use filer, and use a shared filer store, such as redis, the metadata is not cached and safe to check, even with multiple filers. You can tag a file as some sort of flag, and check that directly via http.

But this tagging operation is not atomic compare and swap. All depends on your use case.

**Comment by chrislusf** [comment]
I would like to know your use case. Let's see what we can do here.

**Comment by Woellchen** [comment]
My use case is a LevelDB (https://github.com/syndtr/goleveldb) that needs to lock it's DB files in order to guarantee safe operations and not corrupt it.
While I could possibly build something around it that ensures consistency, it would not be a 100% safe solution.
So I would rather want to provide filesystem level locking.

**Comment by chrislusf** [comment]
I checked and am pretty sure FUSE can not support lock. May have to use some external lock mechanism.

**Comment by chrislusf** [comment]
Actually, do you need the locking across the cluster or just local machine?

**Comment by Woellchen** [comment]
The local machine would be a good start. Although the service will be distributed so it must definitely be across the cluster.
Currently I am using GlusterFS for that. They do support locking in their FUSE mounts and am having no problems with it.
The only problem is that GlusterFS performs very poorly with many small files. That's why I thought SeaweedFS could be a better alternative :)

**Comment by Woellchen** [comment]
To clarify this: FUSE does support file locking, just as GlusterFS does with it's FUSE mount.
The original FUSE library that you forked also still has added support for it: https://github.com/bazil/fuse/commit/699d88be52fbaaad10a4e121e2d8fb682f27d0c5#diff-4eec45b6a922746411c0f8aea183e30f77af1b0a5bea1688eaf343a5f9c23703
The flock command does work locally, but not on another server or mount instance. Do you think it would be possible to implement in SeaweedFS now?
Where would be the right place to add support for such thing?

**Comment by chrislusf** [comment]
Thanks for finding the exact commit. The upstream bazil FUSE branch stopped supporting MacOS, and the changes need to be merged in manually.

Also, it will be nice to have some tests. I tried https://github.com/gofrs/flock and the tests seem passing already even before adding the fix.

**Comment by chrislusf** [comment]
FYI: upgraded the fuse lib. https://github.com/chrislusf/seaweedfs/commit/84f05787f8eecfcb61e49882346ad5855b6bb784

**Comment by chrislusf** [comment]
question: if only supporting local file locks, seems the local OS can handle it already, without any support from FUSE, even for FUSE mounted files.

supporting distributed file locks are possible but needs a good design first.

**Comment by Woellchen** [comment]
I actually came across this fact yesterday, too and tested it with SeaweedFS. At least on Linux the local file locking across the mountpoint is working perfectly!
Thanks for taking the effort! If I can help in any way let me know. Otherwise the local file locking should be enough for the time being. Would still love to see distributed locking in the future :)
