### ISSUE TITLE
[FEATURE]: Add service discovery via DNS SRV records

### ISSUE THREAD

**Issue by danlsgiga** [chrislusf/seaweedfs#1747]
A great way to automate cluster forming seaweedfs master, volume and filer would be to pass a single address that is actually an SRV record for service discovery.

For example... something like `_http.master.seaweedfs.service.consul` returns this:

```
dig SRV _http.master.seaweedfs.service.consul

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-9.P2.el7 <<>> SRV _http.master.seaweedfs.service.consul
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 41581
;; flags: qr rd ra; QUERY: 1, ANSWER: 9, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;nomad.service.consul.		IN	SRV

;; ANSWER SECTION:
_http.master.seaweedfs.service.consul.	5	IN	SRV	1 1 9333 ac1002ed.addr.us-east-1.consul.
_http.master.seaweedfs.service.consul.	5	IN	SRV	1 1 9333 ac100142.addr.us-east-1.consul.
_http.master.seaweedfs.service.consul.	5	IN	SRV	1 1 9333 ac100081.addr.us-east-1.consul.

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Thu Jan 14 17:47:37 UTC 2021
;; MSG SIZE  rcvd: 499
```

and something like `_grpc.master.seaweedfs.service.consul` returns this:

```
dig SRV _grpc.master.seaweedfs.service.consul

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-9.P2.el7 <<>> SRV _grpc.master.seaweedfs.service.consul
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 41581
;; flags: qr rd ra; QUERY: 1, ANSWER: 9, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;nomad.service.consul.		IN	SRV

;; ANSWER SECTION:
_grpc.master.seaweedfs.service.consul.	5	IN	SRV	1 1 19333 ac1002ed.addr.us-east-1.consul.
_grpc.master.seaweedfs.service.consul.	5	IN	SRV	1 1 19333 ac100142.addr.us-east-1.consul.
_grpc.master.seaweedfs.service.consul.	5	IN	SRV	1 1 19333 ac100081.addr.us-east-1.consul.

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Thu Jan 14 17:47:37 UTC 2021
;; MSG SIZE  rcvd: 499
```

This would make super easy to have multiple `master` and `filers` forming active-active clusters without hardcoding IPs and ports.

**Comment by chrislusf** [comment]
Thanks for the suggestion! This could help on configuring the ip address, and the rack and data center.

However, there are still many other parameters. And setting DNS records is not a trivial task. It is unlikely this will be a builtin feature.

How about adding some separate scripts for this feature? Welcome to send a PR.

In general, the setup is complicated. In K8s, this can be much simplified with Seaweed operator. https://github.com/seaweedfs/seaweedfs-operator

**Comment by Cottand** [comment]
Hi @chrislusf hoping to reoen this.

>  setting DNS records is not a trivial task

I believe what is asked here is not for Seaweedfs to set or share DNS records, that can be left to service discovery providers like Consul. Instead, SeaweedFS only needs to resolve existing SRV records. This would allow:
Discovery of master.peers through SRV: 
- `-master.peers=dnssrv+_http.master.seaweedfs.service.consul` or
- -master.peersSrv=dnssrv+_http.master.seaweedfs.service.consul

Discovery by downstream services through SRV
-  `-master=dnssrv+_http.master.seaweedfs.service.consul` or
- `-masterSrv=_http.master.seaweedfs.service.consul`

This does not require SeaweedFS to run a DNS server or anything, only to resolve SRV records, which you can do with [net.LookupSRV](https://pkg.go.dev/net#LookupSRV). If you think this is worth doing I can try to put together a PR.

**Comment by n9** [comment]
This could also work with Kubernetes: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#srv-records
> For a headless Service, this resolves to multiple answers, one for each Pod that is backing the Service, and contains the port number and the domain name of the Pod of the form hostname.my-svc.my-namespace.svc.cluster-domain.example.

**Comment by chrislusf** [comment]
@danlsgiga @Cottand @n9 Thanks for your suggestions!

@Cottand Welcome for a PR!

**Comment by n9** [comment]
I am not a go raft implementations expert, but will this work seaweedfs's goraft fork (https://github.com/seaweedfs/raft). Or would it "require" the `useRaftHashicorp` (https://github.com/hashicorp/raft)?

(reference https://github.com/seaweedfs/seaweedfs/pull/4097#issuecomment-1369461332)

cc @kmlebedev

**Comment by Cottand** [comment]
For an initial PR I think I will just deal with discovering master, filer, etc, from their downstreams. For dealing with a changing raft cluster of masters I definitely need a better understanding of the existing implementation. For instance, the wiki suggests you [need to restart the entire cluster](https://github.com/seaweedfs/seaweedfs/wiki/Failover-Master-Server#faq) to remove or add a master node
