### ISSUE TITLE
Weedfs Volume Read Timeout !!

### ISSUE THREAD

**Issue by shahzaibcb** [chrislusf/seaweedfs#175]
Hi,

   We're getting plenty of i/o error in weedfs volume server :

I0813 17:50:32 63683 needle.go:78] Reading Content [ERROR] multipart: Part Read: read tcp 202.166.173.132:53772: i/o timeout
I0813 17:50:33 63683 needle.go:78] Reading Content [ERROR] multipart: Part Read: read tcp 202.166.173.132:53749: i/o timeout
I0813 17:50:33 63683 needle.go:78] Reading Content [ERROR] multipart: Part Read: read tcp 202.166.173.132:53703: i/o timeout
I0813 17:50:33 63683 needle.go:78] Reading Content [ERROR] multipart: Part Read: read tcp 202.166.173.132:53707: i/o timeout
I0813 17:50:34 63683 needle.go:78] Reading Content [ERROR] multipart: Part Read: read tcp 202.166.173.132:53730: i/o timeout
I0813 17:50:34 63683 needle.go:78] Reading Content [ERROR] multipart: Part Read: read tcp 202.166.173.132:53734: i/o timeout
I0813 17:50:43 63683 needle.go:78] Reading Content [ERROR] multipart: Part Read: read tcp 202.166.173.132:53804: i/o timeout
I0813 17:50:51 63683 needle.go:78] Reading Content [ERROR] multipart: Part Read: read tcp 202.166.173.132:53904: i/o timeout

Any tuning to resolve it ?

Regards.
Shahzaib

**Comment by chrislusf** [comment]
Volume server has an idleTimeout option

**Comment by shahzaibcb** [comment]
>>Volume server has an idleTimeout option
Alright, it means this is not a serious threat. Though i have increased idleTimeout from 10 to 15seconds.

Thanks !!
