### ISSUE TITLE
Feature Request: add volume.fix.replication arguments

### ISSUE THREAD

**Issue by LazyDBA247-Anyvision** [chrislusf/seaweedfs#1758]
Hi Chris,
because when running volume.fix.replication all missing volumes are been copied (multi TB operation usually)
really can't run it on a cronjob, immediately as one volume server is down, we start copying all data to other volume servers

can we at least add a -collection parameter so we can choose which collection MUST be always replicated, same as in volume.balance

nice to have: -collectionRegEx so we can use regEx to match multiple collections.

Regards.

**Comment by LazyDBA247-Anyvision** [comment]
Hi Chris,
seems there is an error when limiting the collections:
created 3 vol servers and 9 collections, workshop_1 -> workshop_9
I had stopped the third vol server
and tried running volume.fix.replication -> all ok, returned the third vol server and did volume.fix.replication, all good and fixed, (by the way it does ALL the volumes in one go, not 1 volume per run)
but when I run it again but using:
`volume.fix.replication -collectionPattern *7`
to fix only workshop_7 collection, it did fix that collection but printed error on all else...
output:
`> volume.fix.replication -collectionPattern *7
failed to place volume 18 replica as 001, existing:1
failed to place volume 22 replica as 001, existing:1
failed to place volume 25 replica as 001, existing:1
failed to place volume 3 replica as 001, existing:1
failed to place volume 6 replica as 001, existing:1
replicating volume 21 001 from seaweedfs-volume-0.seaweedfs-volume:8080 to dataNode seaweedfs-volume-1.seaweedfs-volume:8080 ...
failed to place volume 23 replica as 001, existing:1
failed to place volume 29 replica as 001, existing:1
failed to place volume 15 replica as 001, existing:1
failed to place volume 5 replica as 001, existing:1
failed to place volume 7 replica as 001, existing:1
failed to place volume 13 replica as 001, existing:1
replicating volume 19 001 from seaweedfs-volume-1.seaweedfs-volume:8080 to dataNode seaweedfs-volume-0.seaweedfs-volume:8080 ...
failed to place volume 12 replica as 001, existing:1
failed to place volume 10 replica as 001, existing:1
failed to place volume 1 replica as 001, existing:1
failed to place volume 8 replica as 001, existing:1
failed to place volume 27 replica as 001, existing:1
failed to place volume 17 replica as 001, existing:1
`

and on a volume.fix.replication without the new argument:
`> volume.fix.replication
replicating volume 3 001 from seaweedfs-volume-0.seaweedfs-volume:8080 to dataNode seaweedfs-volume-1.seaweedfs-volume:8080 ...
replicating volume 15 001 from seaweedfs-volume-0.seaweedfs-volume:8080 to dataNode seaweedfs-volume-1.seaweedfs-volume:8080 ...
replicating volume 27 001 from seaweedfs-volume-0.seaweedfs-volume:8080 to dataNode seaweedfs-volume-1.seaweedfs-volume:8080 ...
replicating volume 19 001 from seaweedfs-volume-0.seaweedfs-volume:8080 to dataNode seaweedfs-volume-1.seaweedfs-volume:8080 ...
replicating volume 29 001 from seaweedfs-volume-1.seaweedfs-volume:8080 to dataNode seaweedfs-volume-0.seaweedfs-volume:8080 ...
replicating volume 5 001 from seaweedfs-volume-0.seaweedfs-volume:8080 to dataNode seaweedfs-volume-1.seaweedfs-volume:8080 ...
replicating volume 7 001 from seaweedfs-volume-0.seaweedfs-volume:8080 to dataNode seaweedfs-volume-1.seaweedfs-volume:8080 ...
replicating volume 18 001 from seaweedfs-volume-1.seaweedfs-volume:8080 to dataNode seaweedfs-volume-0.seaweedfs-volume:8080 ...
replicating volume 1 001 from seaweedfs-volume-1.seaweedfs-volume:8080 to dataNode seaweedfs-volume-0.seaweedfs-volume:8080 ...
replicating volume 25 001 from seaweedfs-volume-1.seaweedfs-volume:8080 to dataNode seaweedfs-volume-0.seaweedfs-volume:8080 ...
replicating volume 22 001 from seaweedfs-volume-1.seaweedfs-volume:8080 to dataNode seaweedfs-volume-0.seaweedfs-volume:8080 ...
replicating volume 21 001 from seaweedfs-volume-1.seaweedfs-volume:8080 to dataNode seaweedfs-volume-0.seaweedfs-volume:8080 ...
replicating volume 12 001 from seaweedfs-volume-0.seaweedfs-volume:8080 to dataNode seaweedfs-volume-1.seaweedfs-volume:8080 ...
replicating volume 23 001 from seaweedfs-volume-0.seaweedfs-volume:8080 to dataNode seaweedfs-volume-1.seaweedfs-volume:8080 ...
replicating volume 28 001 from seaweedfs-volume-0.seaweedfs-volume:8080 to dataNode seaweedfs-volume-1.seaweedfs-volume:8080 ...
replicating volume 8 001 from seaweedfs-volume-1.seaweedfs-volume:8080 to dataNode seaweedfs-volume-0.seaweedfs-volume:8080 ...
replicating volume 10 001 from seaweedfs-volume-1.seaweedfs-volume:8080 to dataNode seaweedfs-volume-0.seaweedfs-volume:8080 ...
replicating volume 17 001 from seaweedfs-volume-0.seaweedfs-volume:8080 to dataNode seaweedfs-volume-1.seaweedfs-volume:8080 ...
replicating volume 13 001 from seaweedfs-volume-1.seaweedfs-volume:8080 to dataNode seaweedfs-volume-0.seaweedfs-volume:8080 ...
replicating volume 6 001 from seaweedfs-volume-1.seaweedfs-volume:8080 to dataNode seaweedfs-volume-0.seaweedfs-volume:8080 ...
`

regards.

**Comment by LazyDBA247-Anyvision** [comment]
https://github.com/chrislusf/seaweedfs/blob/b3f66199db4b6a9da48f091a33e87470877d6d73/weed/shell/command_volume_fix_replication.go#L208

probably need to skip if not matched pattern

**Comment by chrislusf** [comment]
thanks! I added the skip logic as you suggested.

**Comment by LazyDBA247-Anyvision** [comment]
and I think you should edit the comment:

* each time this will only add back one replica for one volume id. If there are multiple replicas
  are missing, e.g. multiple volume servers are new, you may need to run this multiple times.
  
* each time this will only add back one replica for each volume id that is under replicated. 
  If there are multiple replicas are missing, e.g. multiple volume servers are new, 
  you may need to run this multiple times.
  
 maybe more understandable?

**Comment by chrislusf** [comment]
thanks! updated.
