### ISSUE TITLE
weedFS init Daemon !!

### ISSUE THREAD

**Issue by shahzaibcb** [chrislusf/seaweedfs#176]
Hi,

  As i was unable to find any daemon to start weedFS. Here is the daemon script to enable it on boot. 

- Paste following contents into /etc/init.d/weed
- You can edit parameters like mdir ,ip etc by simply editing the code.

http://pastebin.com/wMdqy8xw

----------------------------------------------------------

This script is tested on centos-6 with weedFS master. However, to make it compatible with volume, few parameters would be required to replace.

**Comment by chrislusf** [comment]
Nice. This is master server only. Can we also have the init script for volume server? You can fork the wiki repo https://github.com/chrislusf/seaweedfs/wiki and add a section about the deployment script.

**Comment by shahzaibcb** [comment]
We're using init on both master/volume right now. I'll surely create a section with deployment init daemons.
