### ISSUE TITLE
掉线的volume server 能否在重新上线后将掉线期间被修改的数据标识为被删除？

### ISSUE THREAD

**Issue by paochiang** [chrislusf/seaweedfs#1760]
请教一个问题：

 &nbsp; &nbsp;   当副本数设置为`002`时，在一个`volume server`掉线后，此时通过`weed mount`的文件系统修改一个文件内容（因为起的volume server 数量大于3，所以掉线一个`volume server`仍然可以修改文件。并且实际上是创建新文件，旧文件应该是被设置`deleted`标志）。

  &nbsp;  &nbsp;  若该文件有一个副本在掉线的`volume server`里，那么请问文件修改完成后当这个`volume server`重新上线后，在这个`volume server`里的旧文件可以正确的设置`deleted`标志吗？

&nbsp;  &nbsp; 我担心这种旧文件若不能正确的设置`deleted`标志，那么这种旧文件是不是会成为脏文件？

**Comment by chrislusf** [comment]
Yes. It will. Need to use `volume.fsck` in `weed shell` to fix these orphan chunks.

You can ask questions in the discussions section.
