### ISSUE TITLE
Etcd filer store backend problems

### ISSUE THREAD

**Issue by Dando-Real-ITA** [chrislusf/seaweedfs#1767]
**Describe the bug**
When using ETCD as a filer backend, a few problems happen:
- When connecting with weed shell, it is impossible to use fs.ls or fs.meta.save. The first command starts an infinite loop, the second hangs
- When using multiple mounts connected to the same filer, changes on one mount lead to input/output errors, or hanging for example when executing ls -al, on the second mount, showing infinite loops when mount is started with -v=4 like
   ` filerstore_wrapper.go:96] InsertEntry /public`
   ` filerstore_wrapper.go:96] InsertEntry /public`

**System Setup**
Docker Swarm stack file:
[swarm-etcd.zip](https://github.com/chrislusf/seaweedfs/files/5898374/swarm-etcd.zip)

Command sequence:
- docker stack deploy -c swarm-etcd.yml fs
- sudo mkdir -p /mnt/seaweedfs/etcd
- sudo /opt/weed/bin/weed -v=4 mount -filer=localhost:8888 -dir=/mnt/seaweedfs/etcd -volumeServerAccess filerProxy
- cd /mnt/seaweedfs/etcd
- sudo mkdir public
- sudo chmod -R 777 public
- cd public
- sudo mkdir test
- hostname > test.txt
- echo "TEST" >test2.txt
- docker stack ps fs      # to get a running container id with seaweedfs
- docker exec -it **CONTAINER-ID** weed shell -master=master:9333 -filer=filer:8888
- fs.ls
- **INFINITE LOOP**
- force exit
- cd /mnt/seaweedfs
- sudo umount etcd
- sudo /opt/weed/bin/weed -v=4 mount -filer=localhost:8888 -dir=/mnt/seaweedfs/etcd -volumeServerAccess filerProxy
- cd etcd
- ls -al
- **HANGS**

When hanging, we can see on the mount logs:
```
I0130 17:34:19  1640 filerstore_wrapper.go:96] InsertEntry /public
I0130 17:34:19  1640 filerstore_wrapper.go:96] InsertEntry /public
I0130 17:34:19  1640 filerstore_wrapper.go:96] InsertEntry /public
I0130 17:34:19  1640 filerstore_wrapper.go:96] InsertEntry /public
I0130 17:34:19  1640 filerstore_wrapper.go:96] InsertEntry /public
```

**Expected behavior**
Should show only public and topics, once
Mount on multiple hosts should never show input/output errors or hang

**Screenshots**
![Screenshot 2021-01-30 172801](https://user-images.githubusercontent.com/3657228/106363459-97b11400-6320-11eb-87ba-9707a77f9197.png)

**Additional context**
Testing a scenario like https://github.com/chrislusf/seaweedfs/issues/1752 with etcd as a filer store, makes the other mounts not work properly anymore

**Comment by chrislusf** [comment]
Thanks for the detailed issue!
