### ISSUE TITLE
Cannot store more than 1GB in volume with Docker

### ISSUE THREAD

**Issue by Joseph-Hui** [chrislusf/seaweedfs#1770]
I run seaweedfs in a docker container on my Synology NAS, which has around 45TB storage. The following is how I run the container. 

```
docker run --name seaweedfs-s3 -d \
  --restart unless-stopped \
  -p 9333:9333 -p 8333:8333 -p 8080:8080 -p 18080:8080 \
  -v /volume1/seaweedfs/data:/data chrislusf/seaweedfs \
  server -dir="/data" -volume.max=1500 -s3
```
I was uploading large files (300-500M) via S3 API and very soon seaweedfs complaint no free volume available. I found the size of the *.dat files are all around 1GB, which was not the expected 32GB. I have a dev/test environment (non-Docker) running on Ubuntu and the size of the *.dat could reach 30GB. Is there anything I configured incorrectly or if it is a problem with the Docker version?

**Comment by Joseph-Hui** [comment]
I pulled the latest 13 days ago and just notice a fresh new latest is available. Restarted the container with the latest images seem the problem is resolved.

**Comment by chrislusf** [comment]
The docker image has fixed volume max size to 1GB. You need to overwrite the setting `weed server -master.volumeSizeLimitMB=30000`
