### ISSUE TITLE
数据怎么跨服务器迁移，服务器ip地址改变了，迁移过来的数据访问不了

### ISSUE THREAD

**Issue by lzd0805** [chrislusf/seaweedfs#1771]
我在一台服务器上 搭建了一个master和三个volume
迁移前
docker run -d -p 9333:9333 -p 19333:19333 -v /home/sea:/home/sea  --name master chrislusf/seaweedfs:2.13 master   -mdir=/home/sea/data/ -port=9333  
docker run -d -p 9301:9301 -p 19301:19301 -v /home/sea:/home/sea  --name volume1 --link master chrislusf/seaweedfs:2.13 volume -dir=/home/sea/vol/vol1 -max=5 -mserver="master:9333" -port=9301 -ip="192.168.137.144" -publicUrl='192.168.137.144'
docker run -d -p 9302:9302 -p 19302:19302 -v /home/sea:/home/sea  --name volume2 --link master chrislusf/seaweedfs:2.13 volume -dir=/home/sea/vol/vol2 -max=5 -mserver="master:9333" -port=9302 -ip="192.168.137.144" -publicUrl='192.168.137.144'
docker run -d -p 9303:9303 -p 19303:19303 -v /home/sea:/home/sea  --name volume3 --link master chrislusf/seaweedfs:2.13 volume -dir=/home/sea/vol/vol3 -max=5 -mserver="master:9333" -port=9303 -ip="192.168.137.144" -publicUrl='192.168.137.144'

迁移后
docker run -d -p 9301:9301 -p 19301:19301 -v /home/sea:/home/sea  --name volume1 --link master chrislusf/seaweedfs:2.13 volume -dir=/home/sea/vol/vol1 -max=5 -mserver="master:9333" -port=9301 -ip="192.168.137.143" -publicUrl='192.168.137.143'
docker run -d -p 9302:9302 -p 19302:19302 -v /home/sea:/home/sea  --name volume2 --link master chrislusf/seaweedfs:2.13 volume -dir=/home/sea/vol/vol2 -max=5 -mserver="master:9333" -port=9302 -ip="192.168.137.143" -publicUrl='192.168.137.143'
docker run -d -p 9303:9303 -p 19303:19303 -v /home/sea:/home/sea  --name volume3 --link master chrislusf/seaweedfs:2.13 volume -dir=/home/sea/vol/vol3 -max=5 -mserver="master:9333" -port=9303 -ip="192.168.137.143" -publicUrl='192.168.137.143'

我现在想把这台服务器上的数据迁移到另一台服务器上，数据怎么迁移呢，服务器的地址变了，我现在是volume节点下的数据直接拷贝过去，我用原先的id访问提示 "error": "volume id 7 not found: volume id 7 not found"

**Comment by chrislusf** [comment]
sound right. Can not debug by text.

**Comment by lzd0805** [comment]
有没有数据迁移的文档，我在wiki里也没找到相关的信息

**Comment by chrislusf** [comment]
remember to restart
