### ISSUE TITLE
Optimized DeleteMultipleObjectsHandler

### ISSUE THREAD

**Issue by LazyDBA247-Anyvision** [chrislusf/seaweedfs#1772]
Hi Chris,

the new optimization works, 
but not handling folders with folders without files, and the sub folders content was deleted....
example:

(Folder) /buckets/TempBucket/Folder1/ 
(File)     /buckets/TempBucket/Folder1/image.jpg 
(Folder) /buckets/TempBucket/Folder1/backup/
(Folder) /buckets/TempBucket/Folder1/backup/SourceImage/
(File)     /buckets/TempBucket/Folder1/backup/SourceImage/SourceImage.jpg
(File)     /buckets/TempBucket/Folder1/backup/SourceImage/SourceImage_metadata.json

when deleting:
(File)     /buckets/TempBucket/Folder1/image.jpg
(File)     /buckets/TempBucket/Folder1/backup/SourceImage/SourceImage.jpg
(File)     /buckets/TempBucket/Folder1/backup/SourceImage/SourceImage_metadata.json

you mark the folders, Folder With Deletion:
(Folder) /buckets/TempBucket/Folder1/ 
(Folder) /buckets/TempBucket/Folder1/backup/SourceImage/

but then you can't delete (error in log that folder is not empty):
(Folder) /buckets/TempBucket/Folder1/  
BECAUSE of 
(Folder) /buckets/TempBucket/Folder1/backup/
which didn't have any delets inside it...

can you think of a better way to handle it?

can we have a state where you won't "check" each delete for children? 
so we can send ALL paths (including "folders"), 
but at least you won't generate filer requests to list files/folders?

Thanks.

**Comment by chrislusf** [comment]
Thanks for the detailed explanation! Added a fix to recursively delete the empty folders.
