### ISSUE TITLE
[replication] Re-executing tasks in RabbitMQ

### ISSUE THREAD

**Issue by kmlebedev** [chrislusf/seaweedfs#1773]
The current module gocloud.dev/pubsub/rabbitpubsub is not allowed requeue: false to disable redeliver for placing in the queue of DLX

https://github.com/google/go-cloud/blob/cb748bb94dfc22d77278e8fa529cf14f57eb5a1e/pubsub/rabbitpubsub/amqp.go#L110

Configuration guid:  RabbitMQ delay retry/schedule with Dead Letter Exchange
https://medium.com/@kiennguyen88/rabbitmq-delay-retry-schedule-with-dead-letter-exchange-31fb25a440fc

https://github.com/google/go-cloud/issues/2952

**Comment by chrislusf** [comment]
the PR fixed it.
