### ISSUE TITLE
filer: elasticsearch7 no longer works 

### ISSUE THREAD

**Issue by antitbone** [chrislusf/seaweedfs#1774]
Hello

Since 2.21 elasticsearch7 does not work when db already exist.

On a new cluster (>=2.21), the 3 indces are created on startup.
```
indices: 
  .seaweedfs_buckets: green
  .seaweedfs_topics: green
  .seaweedfs_kv_entries: green
```
Filer and s3 are accessibles.

But if filer service are restarted, the filer don't restart.
filer daemon in not listening on network ports (filer and s3)

**cmdline**
```
weed-filer -logtostderr -v 6 filer -port=8888 -s3 -ip=test-seaweedfs1-f -defaultReplicaPlacement=002 -master=test-seaweedfs1-m:9333,test-seaweedfs2-m:9333,test-seaweedfs3-m:9333,test-seaweedfs4-m:9333,test-seaweedfs5-m:9333 -dataCenter=vau -encryptVolumeData
```

**filer.toml**
```
[filer.options]
recursive_delete = false

[elastic7]
enabled = true
servers = [
    "http://test-sdv-seaweedfs1-f:9200",
    "http://test-sdv-seaweedfs2-f:9200",
    "http://test-sdv-seaweedfs3-f:9200",
    "http://test-sdv-seaweedfs4-f:9200",
    "http://test-sdv-seaweedfs5-f:9200",
]
```

**log for >=2.21**
```
févr. 02 17:12:45 test-seaweedfs1 systemd[1]: Started seaweedfs-filer.
févr. 02 17:12:45 test-seaweedfs1 weed-filer[26971]: I0202 17:12:45 26971 config.go:29] Reading security.toml from
févr. 02 17:12:45 test-seaweedfs1 weed-filer[26971]: I0202 17:12:45 26971 metrics.go:155] filer server sends metrics to test-seaweedfs:9091 every 15 seconds
févr. 02 17:12:45 test-seaweedfs1 weed-filer[26971]: I0202 17:12:45 26971 config.go:29] Reading filer.toml from
févr. 02 17:12:45 test-seaweedfs1 weed-filer[26971]: W0202 17:12:45 26971 filer_server.go:115] skipping default store dir in ./filerldb2
févr. 02 17:12:45 test-seaweedfs1 weed-filer[26971]: I0202 17:12:45 26971 config.go:29] Reading notification.toml from
févr. 02 17:12:45 test-seaweedfs1 weed-filer[26971]: I0202 17:12:45 26971 config.go:36] Reading : Config File "notification" Not Found in "[/usr/local /var/empty/seaweed/.seaweedfs /usr/local/etc/seaweedfs /etc/seaweedfs]"
févr. 02 17:12:45 test-seaweedfs1 weed-filer[26971]: I0202 17:12:45 26971 elastic_store.go:70] filer store elastic endpoints: [http://test-seaweedfs1-f:9200 http://test-seaweedfs2-f:9200 http://test-seaweedfs3-f:9200 http://test-seaweedfs4-f:9200 http://test-seaweedfs5-f:9200].
févr. 02 17:12:45 test-seaweedfs1 weed-filer[26971]: I0202 17:12:45 26971 filer.go:101] existing filer.store.id = -379500687
févr. 02 17:12:45 test-seaweedfs1 weed-filer[26971]: I0202 17:12:45 26971 configuration.go:28] configured filer store to elastic7
févr. 02 17:12:45 test-seaweedfs1 weed-filer[26971]: I0202 17:12:45 26971 filerstore_wrapper.go:220] ListDirectoryPrefixedEntries /buckets from  prefix  limit 2147483648
```

No more log availble :/
The daemon in not listening on network port (filer, s3)

With 2.20 the service works and can be restarted, filer and s3 are accessibles.

Antoine

**Comment by chrislusf** [comment]
Could you please make a docker compose file to reproduce this?

**Comment by chrislusf** [comment]
Added a fix without testing.

**Comment by antitbone** [comment]
I won't be able to do the test until tomorrow.

**Comment by chrislusf** [comment]
ok. Anyway, adding a docker compose file will be good for future tests also.

**Comment by antitbone** [comment]
I don't have a docker-compose to provide yet.
My installation is done with anible without docker image.

No change with 2396ac2

I forgot to specify that
- elastic is in version 7.10.1. 
- my test cluster receives about 150 requests per second (goreplay from prod).

I modified filer.toml to only use one of the members of the elastic cluster
```
[filer.options]
recursive_delete = false

[elastic7]
enabled = true
servers = [
     "http: // test-seaweedfs1-f: 9200",
]
```

Here 3 network captures between the filer and its local elastic
made in the following order:
- 2.19
- 2.23-396ac2
- 2.20

[2.20.cap.gz](https://github.com/chrislusf/seaweedfs/files/5917829/2.20.cap.gz)
[2.23-2396ac234c060774ef0640f513fee2e424fbb706.cap.gz](https://github.com/chrislusf/seaweedfs/files/5917830/2.23-2396ac234c060774ef0640f513fee2e424fbb706.cap.gz)
[2.19.cap.gz](https://github.com/chrislusf/seaweedfs/files/5917834/2.19.cap.gz)

The elastic indexes already existed before the captures.

**Comment by chrislusf** [comment]
Actually I have some doubts about the Elastic search support. It is creating one index for each directory. If there are too many directories, there would be too many indices. cc @taozix

@antitbone What is your use case to use elastic search as the filer store?

**Comment by chrislusf** [comment]
Added a fix. The files under the root directory may not be accessible any more. You can copy them out first before upgrading.

**Comment by antitbone** [comment]
In my configuration I have on each host 4 services: volume/filer/s3 and 1 elastic node.
A load balancer distributes the traffic to the s3.
An ansible role deploys weed and elastic configurations and services

When adding a new server to increase capacity, the Elastic cluster allow the new filer/s3 to be directly accessible by the loadballancer without a synchronization phase.

In this configuration, the cluster can be extended without ever having a 500 or 404 error in the s3 service 

```
                            +---------+
                            |   LB    |
                            +----+----+
                                 |
                                 |
                                 |
                                 |
          +----------------------+-----+--------------------+
          |                            |                    |
          |                            |                    |
          |                            |                    |
+-----------------+         +-----------------+        +----+-------+
|     +-------+   |         |     +--------+  |        |            |
|     |  S3   |   |         |     |  S3    |  |        |            |
|     +-------+   |         |     +--------+  |        |            |
|     +-------+   |         |     +--------+  |        |            |
| +---+Filer  |   |         |  +--+ Filer  |  |        |            |
| |   +-------+   |         |  |  +--------+  |        |            |
| |   +-------+   |         |  |  +--------+  |        |            |
| |   |Volume |   |         |  |  | Volume |  |        |            |
| |   +-------+   |         |  |  +--------+  |        |            |
| |               |         |  |              |        |            |
| |   +-------+   |         |  |  +--------+  |        |            |
| |   |Elastic|   |         |  |  | Elastic|  |        |            |
| |   +---+---+   |         |  |  +---+----+  |        |            |
| |       |       |         |  |      |       |        |      +     |
+-----------------+         +-----------------+        +------------+
  |       |                    |      |                       |
  |       |                    |      |                       |
  +-------+--------------------+------+-----------------------+
```

**Comment by chrislusf** [comment]
thanks for the details! Do you have a lot of buckets? Do you need to delete some buckets? Existing elasticsearch filer store does not have an bucket specific index yet, which we can add later.
