### ISSUE TITLE
helm install error

### ISSUE THREAD

**Issue by summerisc** [chrislusf/seaweedfs#1775]
**Describe the bug**
clone the repo and try to run 
`helm install testName seaweedfs/`
within /k8s and got:
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Service): unknown field "selector" in io.k8s.api.core.v1.Service
Is there a version issue with the yml file?

**System Setup**
not applicable

**Expected behavior**
helm install success

**Screenshots**
![Screen Shot 2021-02-02 at 8 12 19 PM](https://user-images.githubusercontent.com/21230663/106683679-f67dc400-6592-11eb-80ef-953a80051020.png)

**Comment by chrislusf** [comment]
what is your helm version?

**Comment by summerisc** [comment]
Thanks for the reply. It's 
version.BuildInfo{Version:"v3.5.1", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.7"}

**Comment by chrislusf** [comment]
use helm 2

**Comment by chrislusf** [comment]
see readme https://github.com/chrislusf/seaweedfs/tree/master/k8s#seaweedfs---helm-chart-2x
