### ISSUE TITLE
S3 should return 204 on DELETE to nonexistent file (not 404)

### ISSUE THREAD

**Issue by MannerMan** [chrislusf/seaweedfs#1776]
**Describe the bug**
The Amazon S3 api specification states that a DELETE request to a non-existing file should return HTTP status `HTTP/1.1 204 No Content`, as described [here](https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteObject.html). Currently, seaweedfs S3 implementation returns `404 Not Found`.

**System Setup**
- List the command line to start: `./weed server -s3 -s3.config=config.json -dir="/minio/weed" -volume.max=100`
- OS version: `CentOS 8`
- output of `weed version`: `version 30GB 2.23 318a3d2 linux amd64`

**Expected behavior**
Seaweedfs should follow the Amazon S3 API specification and return HTTP 204 status-code when issuing a DELETE request to a non-existing file. This is important for compatibility with applications expecting S3 behavior.

**Additional context**
I stumbled upon this problem when attempting to use [pgbackrest](https://pgbackrest.org/) postgres backup software configured with seaweedfs S3 API as storage. When performing a regular backup, pgbackrest would almost finish but at the end run into an exception:
```
2021-02-02 16:04:39.364 P00  DEBUG:     common/io/http/request::httpRequestResponse: => {code: 404, reason: Not Found, header: {accept-ranges: 'bytes', content-length: '234', content-type: 'application/xml', date: 'Tue, 02 Feb 2021 15:04:39 GMT', server: 'SeaweedFS S3 30GB 2.23', x-amz-request-id: '1612278279364142795'}, contentChunked: false, contentSize: 234, contentRemaining: 0, closeOnContentEof: false, contentExists: true, contentEof: true, contentCached: true}
2021-02-02 16:04:39.365 P00  DEBUG:     common/exit::exitSafe: (result: 0, error: true, signalType: 0)
ERROR: [039]: HTTP request failed with 404 (Not Found):
       *** URI/Query ***:
       /dev-pgbackrest/backup/dev-pg-f3c001/latest
       *** Request Headers ***:
       authorization: <redacted>
       content-length: 0
       host: dev-seaweed-backup001-vip.<redacted>
       x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
       x-amz-date: <redacted>
       *** Response Headers ***:
       accept-ranges: bytes
       content-length: 234
       content-type: application/xml
       date: Tue, 02 Feb 2021 15:04:39 GMT
       server: SeaweedFS S3 30GB 2.23
       x-amz-request-id: 1612278279364142795
       *** Response Content ***:
       <?xml version="1.0" encoding="UTF-8"?>
       <Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Resource>/dev-pgbackrest/backup/dev-pg-f3c001/latest</Resource><RequestId>1612278279364119515</RequestId></Error>
```
Searching for this error came up with this pgbackrest bug; https://github.com/pgbackrest/pgbackrest/issues/985 which details the same problem of an S3 implementation returning 404 for DELETE. I think this problem stems from issue #1160 where it was incorrectly stated that the API should return 404 in this case.

Please let me know if I can provide additional information!

**Comment by chrislusf** [comment]
I added some fix. Not sure how to reproduce this. I used this before and after the fix. Both were returning 204.

```
aws --debug --endpoint-url http://localhost:8333 s3 rm s3://newbucket3/some_file
```

**Comment by MannerMan** [comment]
@chrislusf Thank you for the quick response! Is this fix available as a debug build somewhere so I can test, or is a new release planned soon? If not I'll attempt to do a build from master to test with.

**Comment by chrislusf** [comment]
https://github.com/chrislusf/seaweedfs/releases/tag/dev

**Comment by MannerMan** [comment]
@chrislusf Awesome! I can confirm that your fix worked, backup is now successful! Thanks! :+1:
