### ISSUE TITLE
K8s helm install cannot talk to volume server

### ISSUE THREAD

**Issue by summerisc** [chrislusf/seaweedfs#1779]
**Describe the bug**
After a helm chart install, unable to get to the volume server.
Try to run:
`curl http://10.244.0.27:9333/dir/assign` (master server ip exposed by ingress) and the request hangs there, never got a response or complete.
could access http://10.244.0.27:9333 and see this:
![Screen Shot 2021-02-03 at 3 03 53 PM](https://user-images.githubusercontent.com/21230663/106802492-09df6c80-6631-11eb-807e-8f3bb549f468.png)
check pod logs from seaweedfs-volume-0 and got this:
![Screen Shot 2021-02-03 at 3 04 38 PM](https://user-images.githubusercontent.com/21230663/106802578-2380b400-6631-11eb-880e-ff5113ea7af4.png)
seems talking to master server fine.
Mater server kube log looks like this:
![Screen Shot 2021-02-03 at 3 08 44 PM](https://user-images.githubusercontent.com/21230663/106803027-b7eb1680-6631-11eb-93b2-0081d326482b.png)
The only thing I change in helm chart is removing the node affinity cause it's a trial run on one node. Thank you.

**Expected behavior**
curl request returns fid and volume server url.

**Comment by chrislusf** [comment]
please connect to the cluster and test curl dir assign from inside

**Comment by summerisc** [comment]
Thanks for the reply. Since it's a cluster IP, I tried to port forward the master server pod port 9333 to localhost and try again it gives the same result. I also tried to get a busybox container running inside the pod to test internal IP and got the same result.

I am a little confused cause using ingress, outside of the cluster I can
`curl 10.244.0.29:9333`
responds the HTML page content
![Screen Shot 2021-02-03 at 4 13 02 PM](https://user-images.githubusercontent.com/21230663/106810261-b245fe80-663a-11eb-9224-f4dbfd358565.png)
if I try to
`curl 10.244.0.29:9333/random_word]`
it responds 
{"error":"volume id random not found: Unknown volume id random"}
![Screen Shot 2021-02-03 at 4 13 45 PM](https://user-images.githubusercontent.com/21230663/106810339-cc7fdc80-663a-11eb-9317-5768c6c2e5c2.png)

So it seems it's not the problem about not able to reach in cluster clusterIP?

**Comment by chrislusf** [comment]
could not tell what is wrong. what is the output of "/dir/status", and what is the output of "volume.list" via "weed shell"?

**Comment by summerisc** [comment]
the result of curl /dir/status is:
{"Topology":{"DataCenters":[{"Free":1654,"Id":"DefaultDataCenter","Max":1654,"Racks":[{"DataNodes":[{"EcShards":0,"Free":1654,"Max":1654,"PublicUrl":"seaweedfs-volume-0.seaweedfs-volume:8080","Url":"seaweedfs-volume-0.seaweedfs-volume:8080","VolumeIds":"","Volumes":0}],"Free":1654,"Id":"DefaultRack","Max":1654}]}],"Free":1654,"Layouts":[{"collection":"","replication":"000","ttl":"","writables":null}],"Max":1654},"Version":"30GB 2.23 318a3d2e"}
result of volume.list inside master pod via weed shell is:
![Screen Shot 2021-02-03 at 4 38 56 PM](https://user-images.githubusercontent.com/21230663/106812901-4feefd00-663e-11eb-816f-74bd1629d648.png)
Thanks

**Comment by chrislusf** [comment]
ok. seems the master can not connect into the volume server via port 18080

**Comment by summerisc** [comment]
could you advise what might be the reason for this? Or would change a port number helps?

**Comment by chrislusf** [comment]
I do not know whether the assumption is correct or not. Can you verify it?

**Comment by summerisc** [comment]
I would love to try anything I could to see what might cause the issue. Just wondering why you think 18080 would be the issue? Also, I saw 18080 is only used as the grpcPort for the volume server. I tried to change that value and helm upgrade but still no luck. Is this the value you talking about for the connection between master and volume? Any insights are appreciated.

**Comment by chrislusf** [comment]
because the master needs to connect to 18080 of volume servers to tell them to create volumes.

**Comment by summerisc** [comment]
Sure,  I understand that, but for 18080 I found it only appears as the grpcPort for the volume server, is this the place we talking about? Cause it seems not the port for server connection and I try to adjust that and have no luck.

**Comment by chrislusf** [comment]
> it only appears as the grpcPort for the volume server

Correct.

**Comment by summerisc** [comment]
after I switch different grpc port still got no luck, according to master server logs, the heartbeat grpc call fails:
`SendHeartbeat.Send response to to seaweedfs-volume-0.seaweedfs-volume:8080 rpc error: code = Unavailable desc = transport is closing`
It also has the log as:
`master received ec shards from seaweedfs-volume-0.seaweedfs-volume:8080: []`
does this might indicate the issue?
Also filer is currently not working due to some MySQL configuration, but I think it's not required to make volume server responding right?
![Screen Shot 2021-02-04 at 11 38 09 AM](https://user-images.githubusercontent.com/21230663/106924806-76b04080-66dd-11eb-8d05-49b08ed74b72.png)

Full log:
![Screen Shot 2021-02-04 at 11 36 05 AM](https://user-images.githubusercontent.com/21230663/106924546-2b962d80-66dd-11eb-95f5-d0ea42aa5df0.png)

**Comment by summerisc** [comment]
After I changed hostpath for volume storage to persistent volume it was able to curl dir/assign, but it returns:
`{"error":"No free volumes left!"}`
I was able to get file system for master and volume pod:
Master pod:
![Screen Shot 2021-02-04 at 4 03 41 PM](https://user-images.githubusercontent.com/21230663/106954977-8e4df000-6702-11eb-8dd3-bbcc0b5c3634.png)
Volume pod:
![Screen Shot 2021-02-04 at 4 04 09 PM](https://user-images.githubusercontent.com/21230663/106955017-9efe6600-6702-11eb-8b09-1531139c5e72.png)
it seems still have space for /data folder, while the volume list gives this
![Screen Shot 2021-02-04 at 4 06 14 PM](https://user-images.githubusercontent.com/21230663/106955201-e97fe280-6702-11eb-87e7-4414cf11ff5b.png)
If you could advise on this that would be great.

**Comment by summerisc** [comment]
confirm it's a hostpath issue, try to use persistent volume instead resolves issue.
