### ISSUE TITLE
Allow setting external address for master and filer

### ISSUE THREAD

**Issue by Derkades** [chrislusf/seaweedfs#1780]
I am trying to set up seaweedfs over the internet. Volume servers have -publicUrl which I assume should be set to `publicip:publicport`. However, the master and filer servers only have `-ip`. It seems there is currently no way to set the external port for master and filer servers, could you add this or point out if I am not understanding these options correctly?

**Comment by chrislusf** [comment]
what is your intended use case?

**Comment by Derkades** [comment]
I would like to expose the services on a different port than the http port +10000 (e.g in docker `--ports 26493:19333`)

**Comment by chrislusf** [comment]
please use nginx for port forwarding.

**Comment by Derkades** [comment]
I see, I did not realise gRPC was in fact just HTTP

**Comment by Derkades** [comment]
Actually, even if I used nginx instead of changing a docker port mapping for port forwarding, how would that fix the issue?

However, it seems that at least for now this is not the issue, I first need to figure out of connecting filer to master using gRPC instead of http will work at all

**Comment by chrislusf** [comment]
> how would that fix the issue?

what is the issue?

**Comment by Derkades** [comment]
As I discovered later there may not be any, apologies for the noise
