### ISSUE TITLE
Memory GC exception when HBase uses seaweedfs as HDFS

### ISSUE THREAD

**Issue by Britti-di-Brillido** [chrislusf/seaweedfs#1786]
When seaweedfs is used as the underlying support of HBase, the memory overflow of HBase occurs in a few seconds.

It should be judged that the Hlog is too slow to be added to seaweedfs and is blocked in memory. How can you solve this problem?

**Comment by chrislusf** [comment]
Please show how to reproduce it. Just description is too vague.

**Comment by Britti-di-Brillido** [comment]
__

> 请显示如何复制它。只是描述太含糊。

Hbase:1.4.13
hadoop:2.9.2
seaweedfs: 1.77

hbase->hadoop->seaweedfs

After testing, HBase data will burst memory (20GB) in a few seconds when it is inserted. When it is guessed that the data of Hlog is append seaweedfs, it is very slow and the data is blocked in memory.

Turn off HBase Hlog function and insert data in batches again. The memory runs smoothly without problems.

**Comment by chrislusf** [comment]
Please have some docker compose file or some other way to reproduce it. Only description is too vague.

**Comment by chrislusf** [comment]
Seems the HLog file content was not able to flush to disk.

You can use the latest 1.6.0 from https://github.com/chrislusf/seaweedfs/wiki/Hadoop-Compatible-File-System
It has support for flush(), which may help for this issue.
