### ISSUE TITLE
k8s seaweedfs-volume-0.seaweedfs-volume cannot be resolved

### ISSUE THREAD

**Issue by summerisc** [chrislusf/seaweedfs#1787]
**Describe the bug**
Use helm under k8s to deploy, call:
`curl -F "filename=@README.md" 10.244.0.132:8888/test` using filer server, get:
`{"error":"upload README.md 533 bytes to http://seaweedfs-volume-0.seaweedfs-volume:8080/7,26f68d6c73: Post \"http://seaweedfs-volume-0.seaweedfs-volume:8080/7,26f68d6c73\": dial tcp: lookup seaweedfs-volume-0.seaweedfs-volume on 10.96.0.10:53: no such host"}`

It seems the reason is the machine cannot resolve namespace `seaweedfs-volume-0.seaweedfs-volume`, volume server has only clusterIp, is there a way we could upload files from local machine to seaweedfs deployed on the k8s then? Thanks.

**Expected behavior**
success uploads file.

**Comment by chrislusf** [comment]
> Use helm under k8s to deploy

What steps did you take?

**Comment by summerisc** [comment]
I just used helm to deploy the pods, also configured MySQL backend for filer.
Pod status all looks fine:
![Screen Shot 2021-02-08 at 6 36 40 PM](https://user-images.githubusercontent.com/21230663/107295045-96789900-6a3c-11eb-83bf-c32a75d76b60.png)
the only problem when try to save files via filer, it gives the above error, full logs like this:
![Screen Shot 2021-02-08 at 6 37 44 PM](https://user-images.githubusercontent.com/21230663/107295113-bd36cf80-6a3c-11eb-851f-564f2e7ba1d8.png)

I think it is due to local machine cannot resolve name space: `seaweedfs-volume-0.seaweedfs-volume`
So just wondering how did you manage to upload files from the local machine to k8s deployed system and bypass this name resolving issue when you tested.

**Comment by chrislusf** [comment]
what are the changes you made to the chart values?

**Comment by summerisc** [comment]
the only thing I changed was the pod affinity, I removed the pod affinity check in the value chart. since currently I am testing on a single node cluster, but this change shouldn't affect any service/ pod network-related staff.

**Comment by chrislusf** [comment]
Can you share the code that you removed?

**Comment by summerisc** [comment]
sure, I pasted git diff for values here, it's pod afiinity and node selector change, thanks:
```
+++ b/k8s/seaweedfs/values.yaml
@@ -83,15 +83,15 @@ master:
   # Affinity Settings
   # Commenting out or setting as empty the affinity variable, will allow
   # deployment to single node services such as Minikube
-  affinity: |
-    podAntiAffinity:
-      requiredDuringSchedulingIgnoredDuringExecution:
-        - labelSelector:
-            matchLabels:
-              app: {{ template "seaweedfs.name" . }}
-              release: "{{ .Release.Name }}"
-              component: master
-          topologyKey: kubernetes.io/hostname
+  # affinity: |
+  #   podAntiAffinity:
+  #     requiredDuringSchedulingIgnoredDuringExecution:
+  #       - labelSelector:
+  #           matchLabels:
+  #             app: {{ template "seaweedfs.name" . }}
+  #             release: "{{ .Release.Name }}"
+  #             component: master
+  #         topologyKey: kubernetes.io/hostname
 
   # Toleration Settings for master pods
   # This should be a multi-line string matching the Toleration array
@@ -103,8 +103,8 @@ master:
   # Example:
   # nodeSelector: |
   #   beta.kubernetes.io/arch: amd64
-  nodeSelector: |
-    sw-backend: "true"
+  # nodeSelector: |
+  #   sw-backend: "true"
 
   # used to assign priority to master pods
   # ref: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/
@@ -172,15 +172,15 @@ volume:
   # Affinity Settings
   # Commenting out or setting as empty the affinity variable, will allow
   # deployment to single node services such as Minikube
-  affinity: |
-    podAntiAffinity:
-      requiredDuringSchedulingIgnoredDuringExecution:
-        - labelSelector:
-            matchLabels:
-              app: {{ template "seaweedfs.name" . }}
-              release: "{{ .Release.Name }}"
-              component: volume
-          topologyKey: kubernetes.io/hostname
+  # affinity: |
+  #   podAntiAffinity:
+  #     requiredDuringSchedulingIgnoredDuringExecution:
+  #       - labelSelector:
+  #           matchLabels:
+  #             app: {{ template "seaweedfs.name" . }}
+  #             release: "{{ .Release.Name }}"
+  #             component: volume
+  #         topologyKey: kubernetes.io/hostname
 
   # Resource requests, limits, etc. for the server cluster placement. This
   # should map directly to the value of the resources field for a PodSpec,
@@ -198,8 +198,8 @@ volume:
   # Example:
   # nodeSelector: |
   #   beta.kubernetes.io/arch: amd64
-  nodeSelector: |
-    sw-volume: "true"
+  # nodeSelector: |
+  #   sw-volume: "true"
 
   # used to assign priority to server pods
   # ref: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/
@@ -255,15 +255,15 @@ filer:
   # Affinity Settings
   # Commenting out or setting as empty the affinity variable, will allow
   # deployment to single node services such as Minikube
-  affinity: |
-    podAntiAffinity:
-      requiredDuringSchedulingIgnoredDuringExecution:
-        - labelSelector:
-            matchLabels:
-              app: {{ template "seaweedfs.name" . }}
-              release: "{{ .Release.Name }}"
-              component: filer
-          topologyKey: kubernetes.io/hostname
+  # affinity: |
+  #   podAntiAffinity:
+  #     requiredDuringSchedulingIgnoredDuringExecution:
+  #       - labelSelector:
+  #           matchLabels:
+  #             app: {{ template "seaweedfs.name" . }}
+  #             release: "{{ .Release.Name }}"
+  #             component: filer
+  #         topologyKey: kubernetes.io/hostname
 
   # updatePartition is used to control a careful rolling update of SeaweedFS
   # masters.
@@ -285,8 +285,8 @@ filer:
   # Example:
   # nodeSelector: |
   #   beta.kubernetes.io/arch: amd64
-  nodeSelector: |
-    sw-backend: "true"
+  # nodeSelector: |
+  #   sw-backend: "true"
 
   # used to assign priority to server pods
   # ref: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/
@@ -295,7 +295,7 @@ filer:
   # extraEnvVars is a list of extra enviroment variables to set with the stateful set.
   extraEnvironmentVars:
     WEED_MYSQL_ENABLED: "true"
-    WEED_MYSQL_HOSTNAME: "mysql-db-host"
+    WEED_MYSQL_HOSTNAME: "sw-database"
     WEED_MYSQL_PORT: "3306"
     WEED_MYSQL_DATABASE: "sw_database"
     WEED_MYSQL_CONNECTION_MAX_IDLE: "5"
@@ -346,8 +346,8 @@ s3:
   # Example:
   # nodeSelector: |
   #   beta.kubernetes.io/arch: amd64
-  nodeSelector: |
-    sw-backend: "true"
+  # nodeSelector: |
+  #   sw-backend: "true"
 
   # used to assign priority to server pods
   # ref: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/
@@ -368,8 +368,8 @@ cronjob:
   master: ""
   filer: ""
   tolerations: ""
-  nodeSelector: |
-    sw-backend: "true"
+  # nodeSelector: |
+  #   sw-backend: "true"
 
 certificates:
   commonName: "SeaweedFS CA"
```

**Comment by LazyDBA247-Anyvision** [comment]
@summerisc you are trying to use SW outside of the k8s network?
what step did you take to publish the filer port 8888?

we always use the SW internally, I will try to reproduce on my machine, publishing  k8s statefulsets is sometimes tricky :)

**Comment by LazyDBA247-Anyvision** [comment]
to access the filer I need to change the seaweedfs-filer-client SVC to have Cluster IP. (need to remove the ClusterIP: None)
do:
`kubectl delete svc seaweedfs-filer-client`
then let's recreate:

```
cat << EOF | kubectl create -f -
apiVersion: v1
kind: Service
metadata:
  labels:
    app: seaweedfs
    component: filer
    monitoring: "true"
  name: seaweedfs-filer-client
  namespace: default
spec:
  ports:
  - name: swfs-filer
    port: 8888
    protocol: TCP
    targetPort: 8888
  - name: swfs-filer-grpc
    port: 18888
    protocol: TCP
    targetPort: 18888
  - name: metrics
    port: 9327
    protocol: TCP
    targetPort: 9327
  selector:
    app: seaweedfs
    component: filer
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
EOF
```

and patch it with the real Host IP (replace XXX.XXX.XXX.XXX)
`kubectl patch svc seaweedfs-filer-client -p '{"spec":{"externalIPs":["XXX.XXX.XXX.XXX"]}}'`

then I think you have a problem with the curl command, you should have : 
curl -F "filename=@README.md" 10.244.0.132:8888/**_buckets/DestinationBucketName_**/README.md

**Comment by chrislusf** [comment]
it seems to me that the filer was failing to submit to `seaweedfs-volume-0.seaweedfs-volume`. 

However, the chart was using `swfs-volume`. So I could not tell where the `seaweedfs-volume` comes from. Unless @summerisc is not sharing the info.

**Comment by LazyDBA247-Anyvision** [comment]
the name is from:
https://github.com/chrislusf/seaweedfs/blob/a6e8d606b47e5f3e8cd8a57d2769d6f1404fbc8f/k8s/seaweedfs/templates/volume-statefulset.yaml#L117
POD_NAME is seaweedfs-volume-0 & the statefulset name is : seaweedfs-volume

to access each volume server externally (if needed) you will need to create a k8s svc NodePort to export the volume server on each Host (filer can use load balancing, as you don't care which you connect, but volume server you must? yes?)

you can update the volume arguments and add:
publicURL & PublicPort
so the filer will "tell" the client to connect to the correct port and host
-publicUrl=${HOST_IP}
-publicPort=30001

notice the name & the selector both seaweedfs-volume-0, run this for each volume replica... won't work for multiple volume servers on the same host :)

```
cat << EOF | kubectl create -f -
apiVersion: v1
kind: Service
metadata:
  name: seaweedfs-volume-0-external
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - port: 8080
      nodePort: 30001
  selector:
    statefulset.kubernetes.io/pod-name: seaweedfs-volume-0
EOF
```

**Comment by summerisc** [comment]
Thanks guys for the help. Really appreciate it.
@LazyDBA247-Anyvision helm chart has a default ingress to expose filer at 8888 so I didn't do extra work to expose filer server.
After replacing IP with port.public and publicUrl in the volume it works well with external service.
