### ISSUE TITLE
Transaction id

### ISSUE THREAD

**Issue by seifer** [chrislusf/seaweedfs#179]
Based on https://github.com/chrislusf/seaweedfs/issues/172.

I want know you opinion. Offer essence:

1. Add transaction id for all insert,delete,update operation
2. The client will have to receive transaction id from master for each modifications
3. As result probably we wiil be able to delete transaction which was failed (https://github.com/seifer/go-seaweedfs/commit/95f7ff388e88230b5b6a1f9f6cee25fd160191a5) without race conditions and vacuum will be able to collect trash.

is it possible or i mistake?

**Comment by chrislusf** [comment]
Adding a transaction id is a big change. The volume server is meant to be kept simple and dumb.

This can be implemented from the client side. If a write operation fails, send another request to revoke the changes. No transaction id is needed. The on-disk volume files for the same volume id would not be 100% equal, although logically they are equal.

**Comment by seifer** [comment]
Ok. Does it possible that master node and all replicas told "OK", but realy file not dump on disk.

For example if write (without fsync) was success but realy data not sync on disk (power off). What we must do in this case?

**Comment by chrislusf** [comment]
If this ever happens, the lost data is usually limited to the very end of the volume data file.

We can avoid this by forcing fsync, at the cost of write performance, which may or may not be critical.
