### ISSUE TITLE
Filer always returns 404, if specific volume server was selected

### ISSUE THREAD

**Issue by artemvang** [chrislusf/seaweedfs#1791]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs
Report issues here. Ask questions here https://stackoverflow.com/questions/tagged/seaweedfs
Please ask questions in https://github.com/chrislusf/seaweedfs/discussions

example of a good issue report:
https://github.com/chrislusf/seaweedfs/issues/1005
example of a bad issue report:
https://github.com/chrislusf/seaweedfs/issues/1008

**Describe the bug**
Filer always returns 404 if `volume_server2:8081` was selected:
```$ curl http://127.0.0.1:8888/sources/unpaywall_json/8d/44/358346da-6475-11eb-9692-0242ac150002
http://volume_server2:8081/610,19c17edd25af7b0c: 404 Not Found
curl: (18) transfer closed with 2996 bytes remaining to read
```

But file is present on the second server `volume_server2:8082` and request to `http://volume_server2:8082/610,19c17edd25af7b0c` returns its contents.

Lookup for `610` volume:
```
$ curl "http://localhost:9333/dir/lookup?volumeId=610&pretty=y"
{
  "volumeId": "610",
  "locations": [
    {
      "url": "volume_server2:8081",
      "publicUrl": "volume_server2:8081"
    },
    {
      "url": "volume_server2:8082",
      "publicUrl": "volume_server2:8082"
    }
  ]
}
```

**System Setup**
- master: `weed -logdir=/var/log/seaweedfs/master master -ip=master_ip -mdir=/data/seaweedfs/master-metadata -defaultReplication=010 -metrics.address=master_ip:9091
- filer: `weed -logdir=/var/log/seaweedfs/filer filer -master=master_ip:9333 -defaultReplicaPlacement=010`
- volume: `weed -logdir=/var/log/seaweedfs/volume_8081 volume -mserver=master_ip:9333 -ip=volume_ip -port=8081 -dir=/data/seaweedfs/volumes_8081 -max=230 -dataCenter=dc1 -rack=rack1`
- `Ubuntu 18.04.3 LTS`
- weed version for master server: `version 30GB 1.81 95a9686 linux amd64`
- weed version for volume server: `version 30GB 1.78 linux amd64`
- filer.toml:
```
[postgres]
enabled = true
hostname = "db_ip"
port = 5432
username = "weed"
password = "111"
database = "seaweedfs"
sslmode = "disable"
connection_max_idle = 50
connection_max_open = 100
```

**Expected behavior**
If file present in system, filer always has to return its contents. Maybe filer has a possibility to reindex files and map file URL to valid `volume_server/volume_id,file_id`?

**Comment by chrislusf** [comment]
can you use the latest version? It already has retries built in.
