### ISSUE TITLE
SeaweedfsDisk Usage Much Large Than Actual File Stored

### ISSUE THREAD

**Issue by Joseph-Hui** [chrislusf/seaweedfs#1793]
I set up Seaweedfs as a Docker instance for storing image file, which average size is about 500MB and I didn't use the large file version Seaweedfs. I used it as a S3 storage and there are around 5TB images to be uploaded via a Java program. Today, I notice the Java program cannot upload the images and the NAS, which has 44TB storage, reported it is almost full. I checked Seaweedfs has used up around 38TB disk space. When I list the S3 bucket, there are around 2TB images in it. There is only one S3 bucket used and one program uploading the image. So, why Seaweedfs is taking up so much disk space?

**Comment by chrislusf** [comment]
Please show the output of `volume.list` via `weed shell`

**Comment by Joseph-Hui** [comment]
I dumped the volumes with the following command in the attached file

 `curl "http://localhost:8080/status"
`

[volume-list.txt](https://github.com/chrislusf/seaweedfs/files/5956595/volume-list.txt)

**Comment by chrislusf** [comment]
There are about 1500 volumes. If each volume is pre-allocated with 30GB. So the total occupied disk space is about 45TB.

In each volume, only about 1.5GB data are actually stored.

**Comment by Joseph-Hui** [comment]
How can I stored more than 1.5GB data per volume?

**Comment by chrislusf** [comment]
Upload with the existing collection. And ensure `weed master -volumeSizeLimitMB=30000`

**Comment by Joseph-Hui** [comment]
I just summed the file count of each volume in the list and the total is around 470K. I should have around 6000 files to be uploaded. How come there are so much files in the volumes?

**Comment by Joseph-Hui** [comment]
I started the docker container with the following already.

`docker run --name seaweedfs-s3 -d \
  --restart unless-stopped \
  -p 9333:9333 -p 8333:8333 -p 8080:8080 -p 18080:8080 \
  -v /volume1/mongodb/seaweedfs/data:/data chrislusf/seaweedfs \
  server -dir="/data" -volume.max=1500 -master.volumeSizeLimitMB=30000 -s3`

and I should have the latest container image.

```
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
chrislusf/seaweedfs   latest              3f49588b43f9        9 days ago          91.7MB
```

**Comment by ddorian** [comment]
You should know that internally files are split into chunks (or 32MB by default I believe), so maybe that's the number of chunks and not files ?

**Comment by Joseph-Hui** [comment]
Make sense. But would it be better if it is reported as chunk count instead?

**Comment by ddorian** [comment]
> Make sense. But would it be better if it is reported as chunk count instead?

To the volume server, a "chunk" is a "file", it doesn't understand if it's a "chunk" or "full file". It's all bytes.
