### ISSUE TITLE
Invalid URI for NameNode address (check fs.defaultFS): seaweedfs://localhost:8888 is not of scheme 'hdfs'.

### ISSUE THREAD

**Issue by valsun2016** [chrislusf/seaweedfs#1795]
my sys is mac, Hadoop 3.3.0 , SeaweedFS version 30GB 2.22 2c5eac5 darwin amd64,

I strictly follow  https://github.com/chrislusf/seaweedfs/wiki/Hadoop-Compatible-File-System

and run ./start-dfs.sh

i get ，，ERROR: Cannot set priority of namenode process 18823

see log ，，，  /usr/local/Cellar/hadoop/3.3.0/libexec/logs，details ：

**Invalid URI for NameNode address (check fs.defaultFS): seaweedfs://localhost:8888 is not of scheme 'hdfs'.**

tks for helping **me**

**Comment by chrislusf** [comment]
similar to https://stackoverflow.com/questions/57229947/invalid-uri-for-namenode-address-s3a-is-not-of-schema-hdfs

You do not need to start name nodes.
