### ISSUE TITLE
master(not leader) does not forward file get request to master leader

### ISSUE THREAD

**Issue by bigwhite** [chrislusf/seaweedfs#180]
version: weed-fs 0.69

Typo：
two datacenter:dc1 and dc2. defaultReplication=100

masters:
weed -v=3 master -port=9333 -mdir=./1 -peers=localhost:9333,localhost:9334,localhost:9335 -defaultReplication=100
weed -v=3 master -port=9334 -mdir=./2 -peers=localhost:9333,localhost:9334,localhost:9335 -defaultReplication=100
weed -v=3 master -port=9335 -mdir=./3 -peers=localhost:9333,localhost:9334,localhost:9335 -defaultReplication=100

volumes:
weed -v=3 volume -port=8081 -dir=./v1 -mserver=localhost:9333 -dataCenter=dc1
weed -v=3 volume -port=8082 -dir=./v2 -mserver=localhost:9334 -dataCenter=dc1
weed -v=3 volume -port=8083 -dir=./v3 -mserver=localhost:9335 -dataCenter=dc2

when startup, 9334 is voted as leader.
I submit a file:
curl -F file=@hello.txt http://localhost:9333/submit
{"fid":"4,0100679e06","fileName":"hello.txt","fileUrl":"127.0.0.1:8082/4,0100679e06","size":39}

the file is stored in volume 8082(dc1) and 8083(dc2) as expected.

I am trying to get the file through leader master(9334) and it works:

$ curl -L http://127.0.0.1:9334/4,0100679e06
hello weed-fs!

Then I tried get the file through master 9333(not the leader):

$ curl -L http://127.0.0.1:9333/4,0100679e06
{"error":"volume id 4 not found"}

It seems that the 9333 master does not forward the request to leader. if so, the client should always know who is the leader.

Is this a problem? why do not all masters(not only the leader) know the file position?

**Comment by yanyiwu** [comment]
Fix typo error:

`9034` -> `9334`, `9093` -> `9334`

**Comment by bigwhite** [comment]
@yanyiwu I don't understand what you mean. Pls give more details!

**Comment by yanyiwu** [comment]
@bigwhite 
I mean `I am trying to get the file through leader master(9034) and it works:` is wrong, 
it should be `I am trying to get the file through leader master(9334) and it works:`

**Comment by bigwhite** [comment]
@yanyiwu already fix it,3ks. And what's your opinion about this issue? it is a issue about design tradeoff?

**Comment by bigwhite** [comment]
@yanyiwu already fix it,3ks. And what's your opinion about this issue? it is a issue about design tradeoff?

**Comment by yanyiwu** [comment]
@bigwhite 
I dont know the implement about it. 
so I dont know the real reason of your issue.
But in my situation, 
I use 3 master and 2 volume, and defaultReplication=001, it works fine. 

I am curious about your issue too.

**Comment by chrislusf** [comment]
Fixed in https://github.com/chrislusf/seaweedfs/issues/154

**Comment by chrislusf** [comment]
Your version does include this fix yet.

**Comment by bigwhite** [comment]
@chrislusf  you mean 0.69 version does not include #154 fix yet. I see. 3ks
