### ISSUE TITLE
Persistent connections to volume servers through FUSE

### ISSUE THREAD

**Issue by Woellchen** [chrislusf/seaweedfs#1802]
I've got one question regarding FUSE mounts and connections to volume servers.
As far as I could see on my server/s and from the code, retrieving or saving files to volume servers happens in dedicated HTTP requests. This is probably the case for all volume server operations.
Would it not be possible to keep the connections alive all the time? Or have some kind of connection pooler that keeps a bunch of idle connections that can be reused?
Making a new request each and every time is very expensive and adds a lot of overhead. It degrades the overall performance. Especially when the connections are also encrypted (TLS handshake..).
Did I miss something or could this be a nice feature for SeaweedFS?

**Comment by kmlebedev** [comment]
@chrislusf It seems enough to enable the reuse connection by means of tcp
See
https://github.com/zalando/skipper/pull/1511/files

**Comment by chrislusf** [comment]
Current code does try to exhaust the responses https://github.com/chrislusf/seaweedfs/blob/master/weed/util/http_util.go#L373

Maybe the per host connection count is too high? https://github.com/chrislusf/seaweedfs/blob/master/weed/util/http_util.go#L24

**Comment by kmlebedev** [comment]
> Current code does try to exhaust the responses https://github.com/chrislusf/seaweedfs/blob/master/weed/util/http_util.go#L373


> Maybe the per host connection count is too high? https://github.com/chrislusf/seaweedfs/blob/master/weed/util/http_util.go#L24

Need to  test
https://github.com/OJ/gobuster/issues/127
 MaxIdleConnsPerHost == number of goroutines/'threads'

**Comment by kmlebedev** [comment]
try set MaxIdleConns = MaxIdleConnsPerHost
```
	Transport = &http.Transport{
                 MaxIdleConns: 1024,
		MaxIdleConnsPerHost: 1024,
	}
```

**Comment by chrislusf** [comment]
adjusted with https://github.com/chrislusf/seaweedfs/commit/487e435679d6c8cc153b8ef048b8957478cd3d0c

but how to verify the fix?

**Comment by Woellchen** [comment]
Shall I test something? I can build a new binary and run it.
Meanwhile I did some tcpdumping. It turns out that it is always the volume server that closes the connection. It sends FINACK and mount returns with FINACK as well, followed by a last ACK from the volume server. So a normal connection close.
Maybe there is something on the volume server side that we can do?

**Comment by kmlebedev** [comment]
> Shall I test something? I can build a new binary and run it.
> Meanwhile I did some tcpdumping. It turns out that it is always the volume server that closes the connection. It sends FINACK and mount returns with FINACK as well, followed by a last ACK from the volume server. So a normal connection close.
> Maybe there is something on the volume server side that we can do?

You incorrectly mean FastOpen for Socket but I have not found how to enable it for net/http 
But I found https://github.com/valyala/fasthttp

**Comment by Woellchen** [comment]
Hm, what I really mean is how can we keep connections up without dying? At least for some configurable amount of time.
I just see that connections are closed after a few seconds (2 rounds of 15sec TCP keepalive?) and I want to keep them open for at least a few minutes.
Can we maybe use this: https://golang.org/pkg/net/#TCPConn.SetKeepAlive and https://golang.org/pkg/net/#TCPConn.SetKeepAlivePeriod?

**Comment by chrislusf** [comment]
@Woellchen try to adjust `weed volume -idleTimeout=30`

Existing code also disconnects if there are no data traffic. https://github.com/chrislusf/seaweedfs/blob/master/weed/util/net_timeout.go#L58

**Comment by Woellchen** [comment]
@chrislusf thanks! That actually helped. I still see degraded performance when loading files from time to time, so the root cause were not the kept-alive TCP connection.
I will try to do some debugging and find out what is wrong in my case.

**Comment by chrislusf** [comment]
Do you configure concurrent writers? Make sure it does not create too many goroutines.
```
weed mount -concurrentWriters=128

  -concurrentWriters int
    	limit concurrent goroutine writers if not 0 (default 128)
```
