### ISSUE TITLE
No free volumes left

### ISSUE THREAD

**Issue by breaklee** [chrislusf/seaweedfs#181]
how can i fix this error?

**Comment by chrislusf** [comment]
Starts volume server with a bigger number for "-max"

**Comment by breaklee** [comment]
@chrislusf  

i started weed with this option

weed volume -dir=/home/vagrant/data -max=10 
sudo weed master --volumeSizeLimitMB 20000 &

what does mean of '-max'?

**Comment by chrislusf** [comment]
Please use "weed volume -h" to see this and other options.

**Comment by breaklee** [comment]
-max="7": maximum numbers of volumes, count[,count]...

yes. is it important volume numbers when i upload files or total limit size?

@chrislusf

**Comment by chrislusf** [comment]
this is the number of volumes you allocate to the volume server.

**Comment by Dr13am** [comment]
I have two computers running weed  . 192.168.150.81 and 192.168.150.82
192.168.150.81 option:   ./weed master 
192.168.150.82 option: ./weed volume -dir="/tmp/v1" -max=10 -mserver="192.168.150.81" -port=8080 
but then i run curl -X POST http://localhost:9333/dir/assign   in  192.168.15081 
i have a error  " no free volume left!"
help help ..

**Comment by chrislusf** [comment]
-mserver="192.168.150.81:9333"
