### ISSUE TITLE
I draw a diagram about needle structure according to the code

### ISSUE THREAD

**Issue by bingoohuang** [chrislusf/seaweedfs#1815]
![image](https://user-images.githubusercontent.com/1940588/108376141-9eef8180-723d-11eb-80a6-5198ca9fb6e5.png)

1. Could you help me review it?
2. I want to extends more attributes like protected cypher security, more little files in a single needle and etc, which way is preferred?

Thanks very much!

**Comment by chrislusf** [comment]
1. Looks good. Can you share the original slides and image?
2. more attributes can be in the pairs data. Not sure what is "more little files in a single needle".

**Comment by chrislusf** [comment]
btw: you can use the Discussion section for similar discussions: https://github.com/chrislusf/seaweedfs/discussions

**Comment by chrislusf** [comment]
the slides link seems gone?

**Comment by bingoohuang** [comment]
it is here, https://github.com/chrislusf/seaweedfs/files/6009268/default.pptx

**Comment by chrislusf** [comment]
thanks! seem the ppt is the v4 version
