### ISSUE TITLE
docs: volume.configure.replication parameters

### ISSUE THREAD

**Issue by Derkades** [chrislusf/seaweedfs#1816]
```
> volume.configure.replication
error: empty replication value
> volume.configure.replication 100
error: empty replication value
> help volume.configure.replication
volume.configure.replication  # change volume replication value

        This command changes a volume replication value. It should be followed by "volume.fix.replication".
```
How do I specify a replication value? `help volume.fix.replication` has a lot of useful information but `help volume.configure.replication` does not

**Comment by chrislusf** [comment]
does this help?
```
volume.configure.replication -h

```

**Comment by Derkades** [comment]
Yes, thank you! Maybe you should change
`Type:   "help <command>" for help on <command>`
to
`Type:   "help <command>" and "<command> -h" for help on <command>`
or merge the two so it is more obvious?
