### ISSUE TITLE
-defaultReplication does not work for webdav uploads

### ISSUE THREAD

**Issue by Derkades** [chrislusf/seaweedfs#1817]
Filer `-defaultReplicaPlacement` is not specified so it should use master setting (I think?)

Master command line is `master ip=10.131.1.1 -defaultReplication=100 -mdir=/data -volumeSizeLimitMB=1000`
For filer: `filer -master="10.131.1.1:9333" -ip=10.131.1.1 -dataCenter=robin -defaultStoreDir=/data`
Volume servers:
`volume -mserver="10.131.1.1:9333" -ip="10.131.1.1" -port=8080 -dir=/data -dataCenter=robin -rack=server -max=20`
`volume -mserver="10.131.1.1:9333" -ip="10.131.2.1" -port=8080 -dir=/data -dataCenter=joshua -rack=pi -max=20`

Steps:
- Clear all directories of master, filer, and volume servers
- Start everything
- Topology shows my two servers in two "data centers"
  ![image](https://user-images.githubusercontent.com/15892014/108408813-cfc3bc80-7225-11eb-98c4-24bf521665d1.png)
- Confirm volume servers are empty
  ![image](https://user-images.githubusercontent.com/15892014/108408880-e10cc900-7225-11eb-9512-1d634f5a9a42.png)
- Upload a single file using webdav
  ![image](https://user-images.githubusercontent.com/15892014/108409241-42349c80-7226-11eb-8db4-de7f8ed88cd7.png)
- Check volume server interface again (the one in the same "data center" as filer). Now shows volumes
  ![image](https://user-images.githubusercontent.com/15892014/108409355-6c865a00-7226-11eb-8974-508241cc77b3.png)
- Enter weed shell and run replication
  ```
  dexec master weed shell -master 10.131.1.1:9333 -filer 10.131.1.1:8888
  master: 10.131.1.1:9333 filer: 10.131.1.1:8888
  > lock
  > volume.fix.replication
  ```
  Nothing happens
- Set replication manually for a volume and try again
  ```
  > volume.configure.replication -volumeId 4 -replication 100
  > volume.fix.replication
  replicating volume 4 100 from 10.131.1.1:8080 to dataNode 10.131.2.1:8080 ...
  ```
  it works!

Am I misunderstanding how -defaultReplication works or is this a bug?

**Comment by chrislusf** [comment]
webdav data is uploaded to volume servers directly, and currently do not have replication options yet.

https://github.com/chrislusf/seaweedfs/blob/master/weed/server/webdav_server.go#L384

**Comment by Derkades** [comment]
epic! your response time is amazing, thanks
