### ISSUE TITLE
Delete file cause inconsistent 

### ISSUE THREAD

**Issue by bigwhite** [chrislusf/seaweedfs#182]
version: weed-fs 0.70beta

Typo：
two datacenter:dc1 and dc2. defaultReplication=100

```
masters:
weed -v=3 master -port=9333 -mdir=./m1 -peers=localhost:9333,localhost:9334,localhost:9335 -defaultReplication=100
weed -v=3 master -port=9334 -mdir=./m2 -peers=localhost:9333,localhost:9334,localhost:9335 -defaultReplication=100
weed -v=3 master -port=9335 -mdir=./m3 -peers=localhost:9333,localhost:9334,localhost:9335 -defaultReplication=100

volumes:
weed -v=3 volume -port=8081 -dir=./v1 -mserver=localhost:9333 -dataCenter=dc1
weed -v=3 volume -port=8082 -dir=./v2 -mserver=localhost:9334 -dataCenter=dc1
weed -v=3 volume -port=8083 -dir=./v3 -mserver=localhost:9335 -dataCenter=dc2
```

when startup, 9333 is voted as leader.
I submit a file:
curl -F file=@hello.txt http://localhost:9333/submit
{"fid":"6,04dce94a72","fileName":"hello.txt","fileUrl":"127.0.0.1:8082/6,04dce94a72","size":39}

the file is stored in volume 8082(dc1) and 8083(dc2) as expected.

Then I shutdown the 8083(dc3) and try to delete "6,04dce94a72"：

```
$curl -L  -X DELETE http://127.0.0.1:9333/6,04dce94a72
{"error":"Deletion Failed."}
```

but on volume2(8082)，it delete successully!

```
I0820 17:32:20 07653 volume_server_handlers_write.go:53] deleting Cookie:3706276466, Id:4, Size:0, DataSize:0, Name: , Mime:

$ curl  http://127.0.0.1:8082/6,04dce94a72
nothing returned
```

why does it run like that? In my opinion, 8082 should not delete the file as dc2 is down. It cause data inconsistent among file copies.

**Comment by seifer** [comment]
Oh yes, this problem is discussed in this https://github.com/chrislusf/seaweedfs/issues/179 and https://github.com/chrislusf/seaweedfs/issues/172 issues.

To provide consistent data (at least logical) its real problem. And if you have petabytes data (as we) this problem emerge very fast.

Now i try solve this, but all solutions looks like very hard now.

**Comment by chrislusf** [comment]
It replied deletion failure. In this case, the deletion should be retried again until successful, or just give up. There is no guarantee anything when the system reports failure.

**Comment by bigwhite** [comment]
@chrislusf the fact is 0.70 version could guarantee consistent when storing files. the users would wish it do the same when deleting files.

before solving this,  It is better to write this limit to wiki: "There is no guarantee anything when the system reports failure." and give an advice to users: " the client should retry again or just give up."

**Comment by chrislusf** [comment]
Actually write and delete are the same, they are all updates. For replicated updates, if one of them fail, the whole request is returned with error. And on the disk, some volume may actually have the updates, some not.
