### ISSUE TITLE
Boot up more in cluster volume servers using helm

### ISSUE THREAD

**Issue by summerisc** [chrislusf/seaweedfs#1832]
**Describe the bug**
This might be more like a feature request than a bug report. What's the recommended way to boot up more volume servers with different storageClass. For examples, we have multiple local directories that mount to different storageClass. It seems we need to create separate volume servers for each storagClass. Currently, we could make another copy of volume-statefulset.yaml file and bound to another storage class, also add another set of values to Values.yaml. But it seems heavy redundant in terms of code/yaml files. Not sure if you could advise what's the best practice for your development when it comes to multiple in-cluster volume servers.

**Comment by chrislusf** [comment]
Will this help? https://github.com/chrislusf/seaweedfs/wiki/Tiered-Storage

**Comment by summerisc** [comment]
Thanks for the info. But it seems like a different topic, as it is a normal use case for us to boot more and more volume servers in cluster with the increasing data, and connect them to more storageClass. Want to check if there are easier ways to add more volume servers to the cluster instead of copying many copies of volume-statefulset.yaml file and boot up the statefulsets every time a new volume server is needed.

**Comment by chrislusf** [comment]
how about using https://github.com/seaweedfs/seaweedfs-operator ? Maybe do some coding to add different storage class.

**Comment by chrislusf** [comment]
actually I do not understand the question. why adding more volume servers needs to add different storageClass? There are no storageClass settings in volume-statefulset.yaml.

**Comment by summerisc** [comment]
Indeed, the current chart uses hostPath instead of storageClass to be used by the seaweedfs-volume-storage, but it cannot be used in production right? In production we will rely on storageClass to provide actual storage space. Regardless, adding more volume servers still need to configure volumes seaweedfs-volume-storage differently.

**Comment by chrislusf** [comment]
Are you using K8s on the cloud?

**Comment by summerisc** [comment]
We have our on-prem servers so mostly local servers. But I think the idea behind this stays the same right? Whether it's cloud/on-prem servers or hostPath/storageClass, if we want to boot up more volume servers with the chart currently it seems that duplicating volume-statefulset is the easiest option.

**Comment by chrislusf** [comment]
@LazyDBA247-Anyvision do you have some suggestions for this?

**Comment by LazyDBA247-Anyvision** [comment]
Stateful sets + any deployment from a single configuration (yaml) in k8s, have the same storage Class, and we do have 
storage class support in the values.yaml under the volume server part, I will update the chart :) the current SW chart is only a baseline...

```
  data:
    type: "persistentVolumeClaim"
    size: "24Ti"
    storageClass: "local-path-storage"
 ```
 @summerisc I would be happy to see any other helm chart that supports the same deployment/stateful set with two storage classes to the same pod on some alternating/label based/taint based pod assignment.

I think that adding another volume config to support an additional storage class (so two different ones for the volume servers), is the only option, and it is K8s limitation, not a seaweedfs chart issue.

**Comment by LazyDBA247-Anyvision** [comment]
updated chart:
https://github.com/chrislusf/seaweedfs/pull/1833
