### ISSUE TITLE
ByteBuffer.clear() method derives java.lang.NoSuchMethodError on java8

### ISSUE THREAD

**Issue by liuzhengcast** [chrislusf/seaweedfs#1836]
ByteBuffer.clear() method behaves different on java 8 and java9 above, 
when calling ByteBufferPool.release(this.buffer) in SeaweedOutputStream class, which calls obj.clear() method in ByteBufferPool class, No SuchMethodError appears on java 8.
The reason and solution is described in this article, 
https://www.jianshu.com/p/8f219d981aa9?share_token=c541612b-25bd-4155-b02f-ddd58fd16771

**Comment by chrislusf** [comment]
Thanks a lot for the issue report and the solution! Added the fix. You are also welcome to create a PR later.
