### ISSUE TITLE
SNAPSHOT of seaweeds-client 1.6.1 is missed in sonatype repository

### ISSUE THREAD

**Issue by liuzhengcast** [chrislusf/seaweedfs#1842]
In this repository, 
https://oss.sonatype.org/content/repositories/snapshots, there is only seaweedfs-client 1.0.1-SNAPSHOT, whereas I want to use the latest 1.6.1-SNAPSHOT version, which is missing, please upload the latest snapshot version of seaweeds-client. And is there giteer conversation room for this project ?

**Comment by chrislusf** [comment]
https://mvnrepository.com/artifact/com.github.chrislusf/seaweedfs-client/1.6.1
