### ISSUE TITLE
Replication fail with multiple volume servers

### ISSUE THREAD

**Issue by summerisc** [chrislusf/seaweedfs#1843]
**Describe the bug**
Try to run `curl -F "filename=@README.md" "http://${filerIp}:8888/target?replication=010"` and get `{"error":"rpc error: code = Unknown desc = Cannot grow volume group! No matching data node found! \n1:Only has 1 rack with more than 1 free data nodes, not enough for 2."}` while actually, we have 2 racks in one datacenter. Also tried to assign these two volume servers to different datacenter names and try to replicate with 100 strategy and got `{"error":"rpc error: code = Unknown desc = Cannot grow volume group! No enough data node found!"}`

**Screenshots**
![截屏2021-02-25 上午10 49 05](https://user-images.githubusercontent.com/21230663/109178657-169a4080-7757-11eb-8c95-0c03af8b13d2.png)

**Comment by chrislusf** [comment]
Your rack 2 has max of 7 volumes, and all were taken already.
