### ISSUE TITLE
Consisteny of the volume

### ISSUE THREAD

**Issue by lshmouse** [chrislusf/seaweedfs#185]
When going through the write path, we found when the volume server receives a write request, it will send the write to other replica locations of same volume. But if there is a problem in any volume server, the write to that server will be failed and the entire write will be failed too  

But the writes to  some volume servers have been succeed.  Then the volume data in different server may be not consistent. 

Will this be a problem? And how to handle this problem and delete the garbage in the end? 

Thanks~

**Comment by chrislusf** [comment]
Similar to #179, #172 

This is current design. Maybe the system can make a best effort to keep it consistent, but it would still not be 100% guarantee, especially in extreme cases.

**Comment by lshmouse** [comment]
Thanks, @chrislusf ~

**Comment by heipacker** [comment]
hi, is this bug fixed?

**Comment by chrislusf** [comment]
Not a bug.
