### ISSUE TITLE
[master] panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by icexile** [chrislusf/seaweedfs#1852]
**Describe the bug**
we run 3 nodes HA masters, one of the master crashes after some network error

**System Setup**
- List the command line to start "weed master": 
```
docker run -d --name=master0 --network=host -v /data0:/data0 weed:2.20 weed master -ip ip0 -mdir /data0 -peers ip0:9333,ip1:9333,ip2:9333 -port 9333 -volumePreallocate -volumeSizeLimitMB=30000
```
- OS version: CentOS 8
- output of `weed version`: ```version 30GB 2.20 f0d3b3b linux amd64```

**Expected behavior**
the master should not crash when error happens.

**Screenshots**
![image](https://user-images.githubusercontent.com/6914585/109481172-68c0c600-7ab7-11eb-96a6-920241d83f8e.png)

**Comment by chrislusf** [comment]
this is hard to address since it is related to raft and specific network conditions.

**Comment by icexile** [comment]
yes, we are trying to reproduce this issue but never occurs since then.
