### ISSUE TITLE
docker images with weed not a dynamic executable

### ISSUE THREAD

**Issue by kmlebedev** [chrislusf/seaweedfs#1856]
Good

```
cd ../weed; CGO_ENABLED=0 GOOS=linux go build -ldflags "-extldflags -static"
```

```
ldd ./weed
not a dynamic executable
```

Need to fix
```
docker run -it --entrypoint sh chrislusf/seaweedfs:latest
/ # ldd /usr/bin/weed
/lib/ld-musl-x86_64.so.1: /usr/bin/weed: Not a valid dynamic program
```

**Comment by chrislusf** [comment]
Not clear what is unexpected here.

**Comment by chrislusf** [comment]
what needs changes? Seems all the flags are already in place.
```
CGO_ENABLED=0 GOOS=linux go build -ldflags "-extldflags -static"
```

**Comment by kmlebedev** [comment]
> what needs changes? Seems all the flags are already in place.
> 
> ```
> CGO_ENABLED=0 GOOS=linux go build -ldflags "-extldflags -static"
> ```

I didn't find it right away. try adding to https://github.com/chrislusf/seaweedfs/blob/master/.github/workflows/release.yml#L37
```
    env:
      - CGO_ENABLED=0
```

**Comment by chrislusf** [comment]
> I didn't find it right away. try adding to https://github.com/chrislusf/seaweedfs/blob/master/.github/workflows/release.yml#L37
> 
> ```
>     env:
>       - CGO_ENABLED=0
> ```

@wangyoucao577 how to pass in additional env variables such as CGO_ENABLED?

**Comment by chrislusf** [comment]
> > what needs changes? Seems all the flags are already in place.
> > ```
> > CGO_ENABLED=0 GOOS=linux go build -ldflags "-extldflags -static"
> > ```
> 
> I didn't find it right away. try adding to https://github.com/chrislusf/seaweedfs/blob/master/.github/workflows/release.yml#L37
> 
> ```
>     env:
>       - CGO_ENABLED=0
> ```

@kmlebedev this is only related to building a dev version, and not used in docker images.

**Comment by kmlebedev** [comment]
> this is only related to building a dev version, and not used in docker images.

Then maybe here https://github.com/chrislusf/seaweedfs/blob/master/docker/Dockerfile.go_build#L8

**Comment by chrislusf** [comment]
Where did you find the binary is not static?

**Comment by kmlebedev** [comment]
> Where did you find the binary is not static?

on the hub.docker.com
```
docker pull chrislusf/seaweedfs:2.31
2.31: Pulling from chrislusf/seaweedfs
ba3557a56b15: Already exists
80362092e794: Pull complete
464ae6cea297: Pull complete
bfc12d47eb05: Pull complete
02f445ba7f10: Pull complete
9c8e24856a59: Pull complete
4de7afffb1bb: Pull complete
Digest: sha256:3211f5e09ef49610c8547b1a3918acd6e6a08d29402cb2ca62d80642b12da9d0
Status: Downloaded newer image for chrislusf/seaweedfs:2.31
docker.io/chrislusf/seaweedfs:2.31

docker run -it --entrypoint sh chrislusf/seaweedfs:2.31
/ # ldd /usr/bin/weed
	/lib/ld-musl-x86_64.so.1 (0x7f301a953000)
	libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x7f301a953000)
```

**Comment by wangyoucao577** [comment]
@chrislusf  to disable CGO in go-release-action, try add `pre_command: export CGO_ENABLED=0`.      
But this is not an issue since binary can work well in the docker image.

**Comment by kmlebedev** [comment]
> CGO_ENABLED



> @chrislusf to disable CGO in go-release-action, try add `pre_command: export CGO_ENABLED=0`.
> But this is not an issue since binary can work well in the docker image.

Thanks, in another project I tried to transfer env variables for compile code
https://github.com/kmlebedev/txmlconnector/blob/main/.github/workflows/release.yml#L31

**Comment by wangyoucao577** [comment]
@kmlebedev It supposed to not prevent. Let me check.

**Comment by wangyoucao577** [comment]
@kmlebedev  try out `wangyoucao577/go-release-action@bugfix/mutli-pre-cmd` please. I'll merge it a little bit later.

**Comment by wangyoucao577** [comment]
@kmlebedev 
v1.15 will solve the issue for you. Please have a try. Feel free to let me know if any issue.    
```
- name: Go Release Binaries
  uses: wangyoucao577/go-release-action@v1.15
```
