### ISSUE TITLE
Lost 29 volumes (out of ~850)

### ISSUE THREAD

**Issue by vsolovyov** [chrislusf/seaweedfs#1864]
We've had some errors in seaweed, and finally I've got time to investigate that. Turns out that a lot of our reads end up with HTTP 500 - `volume 420 not found`. When I do `curl "http://localhost:9333/dir/lookup?volumeId=420&pretty=y"` on master node, I get this:

```
{
  "volumeId": "420",
  "error": "volume id 420 not found"
}
```

I've run script through volumes sequentially and got this list of volumes that are not there: 420, 455, 456, 457, 458, 461, 462, 463, 464, 465, 469, 470, 471, 472, 477, 478, 479, 480, 481, 485, 488, 489, 490, 495, 499, 500, 501, 504, 509. Last one existing at a time I write this is 857.

**System Setup**
- Ubuntu 18.04/20.04
- Weed version: 2.24
- Filer stores data in PostgreSQL 13
- `--defaultReplication=010`
- Four servers with two-three separate disks each (8TB HDD), each disk is a separate volume and separate seaweed instance (with ports like 8081, 8082, 8083). Each server is configured as a separate rack, all in one data center.

Seaweed is started as a systemd services under a separate user, no containerization/virtualization behind.

**Expected behavior**
I really would expect for all volumes to continue existing.

**Screenshots**
<img width="930" alt="image" src="https://user-images.githubusercontent.com/1250501/110012754-88f7bb80-7d29-11eb-97cb-f14dfd869fcc.png">

This is from our own logs that make requests to Seaweed, each bar is 1 hour wide. Sadly, we did not log anything beyond that there was an error, so we don't even know if it's a 404, 500, some kind of timeout or whatever.

**Additional context**
We added a 4th server on 8 or 9th of February, launched rebalance, then had an initial spike of errors on the graph. We were advised here to update Seaweed (we had 1.81, running from June 2020). Don't really know what was the source of errors on 10..12 of February (I personally was on vacation that week).

Then we figured out that disks on our new data4 were formatted incorrectly (they had only 2 TB each, and 6 was left unused). So my engineer turned seaweed off on that server, copied all volumes from it to a backup location, reformatted all disks and set it up from scratch, copied data back to its locations and turned seaweed up. I think he also turned off replicate in a cron on either 9th or 18th of February.

We have a small number of servers and they're usually quite stable, so replicate historically had almost no work to do.

As I write this, I think the proper process was to replicate before turning off that server, wipe it, set it up again, and then just launch replicate again, because volume files in some backup location just went stale... And then I don't know how SeaweedFS will react, when one server turns up with volumes that are several hours old, and there are newer volumes with possibly newer data.

Last time that I can find volume 420 in logs is on 22th of February. I'm really not sure why it disappeared (or any other volume).

I've downloaded all the logs from all seaweeds (master, filer, all volume servers) locally, so I can grep them all together, etc., It's almost a gigabyte (74 mb zipped). I can probably share them if needed, there is nothing particularly sensitive, no private client data in logs, etc.

If I type `lock; volume.fix.replication` in weed shell right now, it says nothing.

**Comment by chrislusf** [comment]
> copied all volumes from it to a backup location

Are the missing volumes in the backup location?

**Comment by vsolovyov** [comment]
Sadly, it was presumed that everything went okay and that backup was
deleted.--
Vsevolod Solovyov

**Comment by kmlebedev** [comment]
Perhaps this is due to the fact that you did not copy  .vif files ?

**Comment by kmlebedev** [comment]
> All the files were copied, .dat, .idx and .vif. And this server still holds some of the volumes in the same range, like 410, 421, 460, etc that were copied from that backup.

@vsolovyov 
Then it is most likely
https://github.com/chrislusf/seaweedfs/issues/1806
You urgently need to upgrade to version 2.26

**Comment by kmlebedev** [comment]
@chrislusf  It might be worth deleting docker image tags for which there are critical bugs that can lead to data loss?
Its:

2.24-2.25 (https://github.com/chrislusf/seaweedfs/issues/1806)
2.30 (https://github.com/chrislusf/seaweedfs/issues/1878)

**Comment by chrislusf** [comment]
those builds have been deleted. Unless someone builds the old version themselves and not using the latest existing builds.

**Comment by vsolovyov** [comment]
@kmlebedev I assume it's better to upgrade to the latest release (2.31), than 2.26?

**Comment by kmlebedev** [comment]
> @kmlebedev I assume it's better to upgrade to the latest release (2.31), than 2.26?
2.26

**Comment by vsolovyov** [comment]
Ok, I'll upgrade to 2.26.

**Comment by vsolovyov** [comment]
@kmlebedev 2.26 has no builds, only the source code, so I'm going to use 2.27

**Comment by vsolovyov** [comment]
Had to upgrade to 2.31 anyway, because I was also hit by #1863

**Comment by chrislusf** [comment]
Closing since no more actionable items.
