### ISSUE TITLE
OpenReadOnly: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Suika** [chrislusf/seaweedfs#1866]
**Describe the bug**
Here we go agian. Continuation of #1803

1. Weed mount is using ~30GB of ram 
2. Has quite a number of errors while running. Here is the log from [screencopy.txt](https://github.com/chrislusf/seaweedfs/files/6093154/screencopy.txt)

```
$ ps aux | grep mount
root      4997  7.2 16.0 34996124 31709692 pts/6 Sl+ Feb25 902:24 weed mount -filer=localhost:8888 -dir=/mnt/weed -cacheDir=/snapraid/storage_c2/test/seaweed-cache -cacheCapacityMB=0
```

**System Setup**
- Seed Docker setup in #1594 but with newer seaweed version
- Debian 9
- `version 8000GB 2.28 37f104f linux amd64`
- default `filer.toml`
- FUSE: `weed mount -filer=localhost:8888 -dir=/mnt/weed -cacheDir=/snapraid/storage_c2/test/seaweed-cache -cacheCapacityMB=0`

**Expected behavior**

**Additional context**
Was not expectig it to use that much memory. Unless the caching is now completely done in RAM.

**Comment by chrislusf** [comment]
Need to run `weed mount -memprofile=xxx` to collect memory usage.

**Comment by Suika** [comment]
Doing so since a few hours, since I got these errors. Will let it run for a week or two untill it start going nuts.

**Comment by chrislusf** [comment]
You can `ctrl+c` the `weed mount` if the memory is becoming reasonably too large.

If it crashes by itself, the memory profile may not be collected.

**Comment by chrislusf** [comment]
The invalid memory is similar to https://github.com/chrislusf/seaweedfs/issues/1882

**Comment by chrislusf** [comment]
any update?

**Comment by Suika** [comment]
Took a bit of time, but here [CPU_MEM_PROF.zip](https://github.com/chrislusf/seaweedfs/files/6125794/CPU_MEM_PROF.zip)
This time it reached ~45GB

**Comment by chrislusf** [comment]
this has been fixed after upgrading fuse library.
