### ISSUE TITLE
[Question] - How weed deals with archived and zip files in partial downloading

### ISSUE THREAD

**Issue by kaaaq** [chrislusf/seaweedfs#1873]
Hi,
I'm uploaing a 2MB text file in weed , after uploading it return the size of file 2mb but it saved it 300KB,
So weed is archiving and changing my file format to zip,
My question is about partial downloading the file:
When I want to download my file I say : plz give me the file from offset 0 till offset 200000 (The first 200KB of my file) and then
next 200KB up to the end ...
1. How weed would deal with this issue when I'm downloading the first chunk, it will unzip the whole file and it would give me it partially ? if it's true  where it keeps the unzip file (in ram or a directory on system? )

2. think about situation that I want to get the first chunk of my file but I deal with an error (I dont know any error eg: connection error) and again I try , each time weed will unzip my file ?

**Comment by chrislusf** [comment]
1. It will unzip the whole file and it would give it partially. in ram.
2. yes.

**Comment by kaaaq** [comment]
>     2. yes.
@chrislusf 
1.How weed understands that it should remove the file from ram ? when I return 200 or it will remove it after each response and for new request it will load it on ram again eg: I'm downloading my file 200 KB by 200KB up to the end continuously , after each partial request weed will remove the file from ram and again for new request it will unzip it in ram ? How weed deals with this issue?

**Comment by chrislusf** [comment]
> it will remove it after each response and for new request it will load it on ram again

^^

**Comment by kaaaq** [comment]
> > it will remove it after each response and for new request it will load it on ram again
> 
> ^^
@chrislusf 
So for a 300 MB file if I want to give it partially with each time 300kB, weed should 1000 times unzip the file and because requests are continuously it has 2 negative aspect:
1.  it has so overhead for Cpu (for unziping)
2. I should wait for my file to decompress each time
How weed deals with this 2 issue ? for the first issue how much is the overhead of unzipping?
Can you explain it more?

**Comment by chrislusf** [comment]
It is not optimized for this use case.
