### ISSUE TITLE
[Question] - The logic behind file id (How recognize which numbers are file key and file cookie?)

### ISSUE THREAD

**Issue by kaaaq** [chrislusf/seaweedfs#1874]
Hi,
I was reading weed docs about file id, it is written that in "3,01637037d6" fid:
The number 3 at the start represents a volume id and we can recognize it by ","  (because 3 is before comma)
and it is written that: "it's one file key, 01, and a file cookie, 637037d6"
and based on your speech : "The file key is an unsigned 64-bit integer"
So a question comes in mind that how do you know "01" is file key and why you not said 0163 is file key?
How can weed/I recognize wich part is file key?

2.
How weed creates ( file key and file cookie ) , I mean based on which algorithm it creats this 2 numbers?

3.
How weed choose volumes that have the same order to be choosen ? (eg: I want to upload my file to test collection and there are 6 volumes that belong to test collection and 2 servers so with 001 replication weed has 3 options, How weed decide to choose volume id ? it would randomly choose of this 3 )

**Comment by chrislusf** [comment]
1. `637037d6` is the 4-byte cookie.
2. file key is assigned by master, incrementally. file cookie is randomly generated.
3. it is randomly selected, weighted by the volume emptiness.

**Comment by kaaaq** [comment]
>     1. `637037d6` is the 4-byte cookie.
So you mean at first I should extract the last 4-byte cookie and the remain is file key?
>     2. file key is assigned by master, incrementally. file cookie is randomly generated.
1. where weed saves this file key and file cookie? (I think file key is on master and file cookie is on volumes?)
2. does weed have a database for file keys or it saves them on file
3.because you said it will assign this value incrementally so weed should know the last value that  assigned, How weed check the last file key ? if leader has been rebooted or changed  how dose it know the last file key?

**Comment by kaaaq** [comment]
@chrislusf 
Now think about situation that I want to generate fid on myself,
How can I do it? :
1. about volume id , How can I find the appropriate volume e.g: find  by volume emptiness or  something like that.
2. about file key: because you said it is incrementally so How can I find the last file key ?
3. about file cookie: can I generate what I want just it should be 4KBs?

**Comment by chrislusf** [comment]
1. you can use the `large-disk` version, ask the master about the `/vol/status` first, and pace yourself.
2. by default it is incremental. You can use your own key. And use `weed volume -index=leveldb` for un-ordered keys.
3. The cookie should be 4B, not 4KB.

**Comment by kaaaq** [comment]
> Thanks for your answer
> @chrislusf
> 
> > ```
> > 1. `637037d6` is the 4-byte cookie.
> > ```
> 
> So you mean at first I should extract the last 4-byte cookie and the remain is file key?
> 
> > ```
> > 2. file key is assigned by master, incrementally. file cookie is randomly generated.
> > ```
> 
>     1. where weed saves this file key and file cookie? (I think file key is on master and file cookie is on volumes?)
> 
>     2. does weed have a database for file keys or it saves them on file
>        3.because you said it will assign this value incrementally so weed should know the last value that  assigned, How weed check the last file key ? if leader has been rebooted or changed  how dose it know the last file key?

Thanks for your answers @chrislusf,  would you please answer replied questions too?

**Comment by kaaaq** [comment]
> Thanks for your answer
> @chrislusf
> 
> > ```
> > 1. `637037d6` is the 4-byte cookie.
> > ```
> 
> So you mean at first I should extract the last 4-byte cookie and the remain is file key?
> 
> > ```
> > 2. file key is assigned by master, incrementally. file cookie is randomly generated.
> > ```
> 
>     1. where weed saves this file key and file cookie? (I think file key is on master and file cookie is on volumes?)
> 
>     2. does weed have a database for file keys or it saves them on file
>        3.because you said it will assign this value incrementally so weed should know the last value that  assigned, How weed check the last file key ? if leader has been rebooted or changed  how dose it know the last file key?
> 
>     3. If I call assign function, weed responds me a fid , If I don't use this fid will weed save this fid (I mean file key) in any place ?
>        (I want to ask weed for an fid and then I want to use just volume id that weed return and generate file key on myself )

Thanks for your answers @chrislusf, would you please answer replied questions too?
