### ISSUE TITLE
Set volumeSizeLimitMB to be larger than 30000?

### ISSUE THREAD

**Issue by johncadengo** [chrislusf/seaweedfs#1876]
I'm wondering if there is a way to make the volume size larger than 30GB?

Am I understanding it correctly that the largest an individual file can be that I store in seaweedfs is the size of the volume? So if I had a 50GB file, it would not fit? Or am I misunderstanding it?

Using docker, by the way.

This is the error I get when I try to set it larger than `30000`,

```
F0309 05:43:17     1 master.go:105] volumeSizeLimitMB should be smaller than 30000
goroutine 1 [running]:
github.com/chrislusf/seaweedfs/weed/glog.stacks(0xc001269400, 0xc0007346e0, 0x53, 0xa4)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:767 +0xb9
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).output(0x363eb40, 0xc000000003, 0xc0001d25b0, 0x2b6ae78, 0x9, 0x69, 0x0)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:718 +0x37a
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).printf(0x363eb40, 0x3, 0x22fc77b, 0x2e, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:656 +0x153
github.com/chrislusf/seaweedfs/weed/glog.Fatalf(...)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:1149
github.com/chrislusf/seaweedfs/weed/command.runMaster(0x361e900, 0xc00004c0f0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/command/master.go:105 +0x219
main.main()
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/weed.go:66 +0x30f
```

**Comment by johncadengo** [comment]
Ok, I see that if the file is larger than the volume size it should chunk the file. Does webdav handle this automatically for the end user? Say I mount the file system on a Mac client through webdav, and upload a file that's 50GB, will it automatically chunk it for me without me as an end user worrying about the chunking? And when I access it, it will just appear like a normal file?

Also, is there `large disk` version for docker?

**Comment by chrislusf** [comment]
> Ok, I see that if the file is larger than the volume size it should chunk the file. Does webdav handle this automatically for the end user? Say I mount the file system on a Mac client through webdav, and upload a file that's 50GB, will it automatically chunk it for me without me as an end user worrying about the chunking? And when I access it, it will just appear like a normal file?
> 
> Also, is there `large disk` version for docker?

yes.yes.yes.yes.

**Comment by prologic** [comment]
Hey @chrislusf Is this true also of the Filer and POSIX/Fuse client(s) and Docker Volume Plugin? Do I need to worry about file size limitations at all as an end user of SeaweedFS? yes, no? :D

**Comment by chrislusf** [comment]
Yes, no.
