### ISSUE TITLE
[volume] Ability to host 0 volumes, thus only acting as a proxy

### ISSUE THREAD

**Issue by dorian-stream** [chrislusf/seaweedfs#1887]
Having an option to host 0 volumes locally, so the volume-server only acts as a proxy. This way you can use the volume-server as a proxy/side-car and your app will only upload/download to this side car.

**Comment by chrislusf** [comment]
combining with #1888, seems you just want a proxy that can talk to masters and any volume servers?

Do you need to use filer? What is the use case?

**Comment by dorian-stream** [comment]
> combining with #1888, seems you just want a proxy that can talk to masters and any volume servers?

This for my app client code, so I can write new chunks (& getting ids) without my app being aware of any master-servers at all.

> What is the use case?

The idea is for the application code to be simpler & more robust. 
I don't have to code failover for volumes/masters, or keep tracking of volume-ids in my client code, but only talk to the "smart" local proxy, that I can run on each server. 

The use case was discussed [here](https://seaweedfs.slack.com/archives/C9MGUC1UG/p1614763515085200).

> Do you need to use filer?

No. That's what filer does though, proxies requests to volume+master+db. While in this case, it needs to proxy only to volume+master (no s3 or database needed).

> Another use case

Another use case is having a cache (think CDN) in front of the cluster. I don't want to write a varnish/nginx/etc module to smartly get the correct chunks from the correct volume-servers (implementing the client api), but I can dumb proxy all requests to a smart-local-volume-proxy that will know how the cluster works under the hood. 


See a fancy example that [minio](https://github.com/minio/sidekick) does.

**Comment by chrislusf** [comment]
ok. Will provide a `weed proxy` command to reverse proxy the requests, and handles details for the cluster.

**Comment by dorian-stream** [comment]
I believe it's better to add this in volume.
Example: Setting `-volume.max` to `-1` may be a special value that says "don't store any volumes".
And the master-apis would work automatically.
No need to have a new "proxy" service. From a developer point of view, it is expected that `volume` will proxy things by default.

**Comment by chrislusf** [comment]
the proxy seems a way to provide a cross-language API/language for the developers.

**Comment by dorian-stream** [comment]
Yes, but `volume` can be volume+proxy functionality, maybe no reason to split ?

**Comment by kmlebedev** [comment]
Its aka istio or envoy ?

**Comment by dorian-stream** [comment]
@kmlebedev no those are fancy microkubernetes. 

This is just an internal proxy so you only speak with volume-servers, even for master-apis. 
Just like in cassandra, when you insert/select/etc, if you do it at the wrong node, it gets redirected internally.

**Comment by chrislusf** [comment]
> Yes, but `volume` can be volume+proxy functionality, maybe no reason to split ?

- Overloading the volume server is not good since the url path may conflict with the master. 
- Later the proxy can also support filer, e.g., adding cache.
- The APIs can be different. For the blob layer, the API may not need to expose the master APIs. The user can just upload a file and get a file id or a list of file ids.

**Comment by dorian-stream** [comment]
> Overloading the volume server is not good since the url path may conflict with the master.

It seemed the least amount of coding to me.

> Later the proxy can also support filer, e.g., adding cache.

Filer is already a proxy to volume+master. It just has a different api on top (s3).

> The APIs can be different. For the blob layer, the API may not need to expose the master APIs. The user can just upload a file and get a file id or a list of file ids.

This won't work with aborted uploads. Some chunks will be left orphan. The same with getting back a file-id, but failing to save it in your database. 


My idea is was pretty small in functionality/code-size I think.

**Comment by kmlebedev** [comment]
@dorian-stream I do not understand what is the profit ?

**Comment by dorian-stream** [comment]
> @dorian-stream I do not understand what is the profit ?
> 
> It seems right now such a proxy can be a weed filler api.
> It can be run on the localhost in the same place with the your application and walk to get data from it

@kmlebedev at the minimum, filer needs an extra distributed database that I don't want to make highly available,maintain,backup,etc.

**Comment by kmlebedev** [comment]
> @kmlebedev at the minimum, filer needs an extra distributed database that I don't want to make highly available,maintain,backup,etc.

@dorian-stream 
if there is no database, then there is no metadata and all you have is a hash with an url, by which you can get the file
Is this what you walk around?

**Comment by dorian-stream** [comment]
@kmlebedev `filer` needs a database, called `filer store`, that is, basically, `path ---> chunk_ids`. It might look a simple table, but it still needs one.

https://github.com/chrislusf/seaweedfs/wiki/Directories-and-Files#architecture

**Comment by kmlebedev** [comment]
> @kmlebedev `filer` needs a database, called `filer store`, that is, basically, `path ---> chunk_ids`. It might look a simple table, but it still needs one.
> 
> https://github.com/chrislusf/seaweedfs/wiki/Directories-and-Files#architecture

This line in the table can be packed into a hash file
which will be given after uploading the file to the distributed storage

**Comment by dorian-stream** [comment]
> This line in the table can be packed into a hash file
> which will be given after uploading the file to the distributed storage

What do you mean by `hash file` ? 
Do you mean that you can have a [local leveldb](https://github.com/chrislusf/seaweedfs/wiki/Filer-Stores) as a `filer store`,  therefore no need to maintain a database ? 

Then you need that local leveldb on every filer store-server, which I intend to have many, 20+. So the overhead will be bigger than keeping an external db like postgresql/cassandra.

**Comment by kmlebedev** [comment]
> > This line in the table can be packed into a hash file
> > which will be given after uploading the file to the distributed storage
> 
> What do you mean by `hash file` ?
> Do you mean that you can have a [local leveldb](https://github.com/chrislusf/seaweedfs/wiki/Filer-Stores) as a `filer store`, therefore no need to maintain a database ?
> 
> Then you need that local leveldb on every filer store-server, which I intend to have many, 20+. So the overhead will be bigger than keeping an external db like postgresql/cassandra.

I mean, if you don't need a database, then you need to sacrifice metadata including the name and path to the file. 
Instead of a path, you will have an url that, for example, contains a static base64 string(row from filer store) from which the proxy understands how to get the file

**Comment by dorian-stream** [comment]
>  Instead of a path, you will have an url that, for example, contains a static base64 string(row from filer store) from which the proxy understands how to get the file

I **DO NOT WANT** a filer store. That's the whole point. What you say **CANNOT BE DONE WITHOUT A FILER STORE/DB**.

Feel free to ping on slack.

**Comment by kmlebedev** [comment]
> > Instead of a path, you will have an url that, for example, contains a static base64 string(row from filer store) from which the proxy understands how to get the file
> 
> I **DO NOT WANT** a filer store. That's the whole point. What you say **CANNOT BE DONE WITHOUT A FILER STORE/DB**.
> 
> Feel free to ping on slack.

Miracles do not happen, to get a file from distributed storage, you need to know how a specific file is from it.
From this essence of consciousness for the seaweed is called "filler store".
Accordingly, this knowledge is stored either inside the dfs or outside in your application in the form of file names

**Comment by dorian-stream** [comment]
> Miracles do not happen, to get a file from distributed storage, you need to know how a specific file is from it.
> From this essence of consciousness for the seaweed is called "filler store".
> Accordingly, this knowledge is stored either inside the dfs or outside in your application in the form of file names

This functionality is already available in filer store. I know.

I do not want this functionality.

Please either read the description again or open a new issue, because we're talking about different things.

**Comment by chrislusf** [comment]
Added `weed gateway` command: https://github.com/chrislusf/seaweedfs/commit/af313dff58bf82a731dbce72535b72f1979d6740

Here are the ways to use it (only blobs are implemented now)

```
	POST /blobs/
		return a chunk id
	DELETE /blobs/<chunk_id>
		delete a chunk id

	POST /files/path/to/a/file
		save /path/to/a/file on filer 
	DELETE /files/path/to/a/file
		delete /path/to/a/file on filer 

```

**Comment by ddorian** [comment]
@chrislusf 

Note that this is completely different from what I mentioned. 
```
	POST /blobs/
```
https://github.com/chrislusf/seaweedfs/wiki/Volume-Server-API#volume-server-writes is already available, why would you need the endpoint above ? You don't need to create a new endpoint when the one that exists is perfectly capable.

Also:
```
	POST /blobs/
```
This has the possibility of loosing a <fid> (if you fail to upload it to your datastore after getting one back from gateway).
And if a big file fails in the middle of uploading (say after 10 chunks uploaded), those will be left orphan in the cluster. If I wanted this functionality I could just use `weed upload` cli from my app, that was already available.

I've already explained these in the commends in this thread.

**Comment by chrislusf** [comment]
The gateway is meant to run as a sidecar to write to SeaweedFS.

> https://github.com/chrislusf/seaweedfs/wiki/Volume-Server-API#volume-server-writes is already available, why would you need the endpoint above ? You don't need to create a new endpoint when the one that exists is perfectly capable.

To use the volume server API, the client needs to get a file id assigned first. The POST /blobs/ will just upload and return a file id.

**Comment by ddorian** [comment]
> The gateway is meant to run as a sidecar to write to SeaweedFS.

Ok if you want to change the name of the endpoint, but it should provide the same functionality (IMHO). 

If you read the original threads (including https://github.com/chrislusf/seaweedfs/issues/1888), this is a completely different feature. The most important was the `/dir/assign` proxy to separate app-clients from master servers. 

Adding new endpoints is more docs, more confusion among users, more code and no new functionality, just separation. But the whole thing of the proxy is for it to be the same on the outside but work differently inside.

---------------------------------

I just want to say that it's ok to not want to write the functionality that I asked. But it's not ok to write another functionality, that has less features and is crippling/unacceptable (orphan chunks, ability to lose `<fid>`). 

You can close this issue as "won't fix".
