### ISSUE TITLE
[question] files uploaded via curl missing

### ISSUE THREAD

**Issue by Moltenkore** [chrislusf/seaweedfs#1899]
I recently came across seaweedfs so forgive me if this is a noob question.

When I upload via curl:
```
curl "http://localhost:9333/dir/assign"
curl "http://localhost:9333/dir/lookup?volumeId=2"
curl -F file=@/tmp/test-file.txt "http://10.1.1.11:8080/2,0d3abe3872"
```
And then do:
```
weed shell
ls
```
It shows no files.

Likewise when I call to the volume server:
```
curl -H "Accept: application/json" http://localhost:8888/                         
{"Path":"","Entries":null,"Limit":100,"LastFileName":"","ShouldDisplayLoadMore":false}
```
It also shows no files.

If I visit the URL however, my file is displayed: ``http://localhost:8080/2,0d3abe3872``

If instead I drop something in via webdav, the files are suddenly there when I list them via weed shell again but it will only show the files dropped in via webdav and not the file posted before via curl.

**Comment by chrislusf** [comment]
You are using blob storage directly, not involving file system layer. See. https://github.com/chrislusf/seaweedfs/wiki for more details.
