### ISSUE TITLE
[Question] - Best practice to run weed volume servers on production

### ISSUE THREAD

**Issue by kaaaq** [chrislusf/seaweedfs#1900]
Hi,
I want to setup new weed cluster for production but I have some question about it:
1. I have multiple server with at least 10 spinning disk on them , I want to make them volume servers but I'm looking for best practices, I read the wiki that I can run weed volume servers in two way:
First: add all disks to one weed service:
` 
weed volume -mserver=ip1:9333,ip2:9333,ip3:9333 -dataCenter=dc1 -rack=rack1 -ip=xxx.xxx.xxx.xxx -dir=/data/seaweedfs/volume1,/data/seaweedfs/volume2,/data/seaweedfs/volume3 -max=0,0,0 `
Second: add multiple service for each disk in one new port:
`
weed volume -mserver=ip1:9333,ip2:9333,ip3:9333 -dataCenter=dc1 -rack=rack1 -dir=/data/seaweedfs/volume1 -ip=xxx.xxx.xxx.xxx -max=0 -port=8081
weed volume -mserver=ip1:9333,ip2:9333,ip3:9333 -dataCenter=dc1 -rack=rack1 -dir=/data/seaweedfs/volume2 -ip=xxx.xxx.xxx.xxx -max=0 -port=8082
weed volume -mserver=ip1:9333,ip2:9333,ip3:9333 -dataCenter=dc1 -rack=rack1 -dir=/data/seaweedfs/volume3 -ip=xxx.xxx.xxx.xxx -max=0 -port=8083
`
Now a question comes in mind: If I run weed through second way , and I define replication 001, can weed understand that all this services are in one server and it shouldn't put replicas on them?

2. with second way that I mentioned above , because weed is binding disks on different port (it is getting full I/O isolation) , would it work better?

**Comment by chrislusf** [comment]
1. No. Maybe use 010 instead.
2. This is related to hardware and can not tell here.

**Comment by kaaaq** [comment]
Thanks @chrislusf 
>     2. This is related to hardware and can not tell here.
I think this is related to software not hardware, I asked this because we have this problem in openstack swift , would you please look at this link:
[](https://docs.openstack.org/swift/latest/deployment_guide.html#running-object-servers-per-disk)

**Comment by chrislusf** [comment]
Can not tell. The bottleneck can be network, cpu, memory, number of requests, file size, and disk.

**Comment by kaaaq** [comment]
> Can not tell. The bottleneck can be network, cpu, memory, number of requests, file size, and disk.

1. yeah but I'm considering all bottlenecks,
Can you tell me about just this issue? Is it worth to configure weed volume servers like second way? 

2. If I want to configure weed volume servers like second way:
All services that runs with different ports in one server should be on the same rack tag e.g: " -rack=rack1" and I should run it with raplica 010 ? Am I true?
