### ISSUE TITLE
what is 4&1 mean in func  prepareWriteBuffer？

### ISSUE THREAD

**Issue by diluga** [chrislusf/seaweedfs#1927]
hello, following the [sourcecode](https://github.com/chrislusf/seaweedfs/blob/master/weed/storage/needle/needle_read_write.go#L62) below:

```
func (n *Needle) prepareWriteBuffer(version Version) ([]byte, Size, int64, error) {
......
		if n.DataSize > 0 {
			n.Size = 4 + Size(n.DataSize) + 1  // what is 4 & 1 mean?
			if n.HasName() {
				n.Size = n.Size + 1 + Size(n.NameSize)
			}
...
```

 What is 4&1 mean? It is 4 mean len(n.Size)？

**Comment by chrislusf** [comment]
4 bytes are for storing the n.DataSize.
1 byte is for the n.Flags
