### ISSUE TITLE
FUSE growing RAM footprint

### ISSUE THREAD

**Issue by Suika** [chrislusf/seaweedfs#1929]
**Describe the bug**
Ever growing RAM footprint of FUSE mount. Here are the files [pprof.zip](https://github.com/chrislusf/seaweedfs/files/6181826/pprof.zip)

**System Setup**
- `version 8000GB 2.34 9672f9e linux amd64`

**Expected behavior**
A smaller, non-growing RAM footprint. Or at least something that does not explode.

**Comment by chrislusf** [comment]
I added some code change. 
Would be great if there is some scripts that can reproduce this, in order to confirm the fix.

**Comment by chrislusf** [comment]
Also, roughly how many files and folders are there?

**Comment by Suika** [comment]
If I remember correctly, the first unnamed volume contains all the folder entries, then the numbers are as follows:
Folders: ~88.223
Files: ~97.904.837

**Comment by Suika** [comment]
The FUSE mount is not used for writing, it is only used as layer for the applications to merge different folders together (mergerfs) and then have one layer be writable (disk) and the other read only (weed).
There is another application that continuously writes to seaweed via S3 at a rate of ~1.5 files/s.

Out of ~4-5M files that are mainly accessed via the FUSE mount, I can say that ~300-400k files were accessd over the last 3-4 days. For read purposes. But dunno how readdir and scandir calls influence this.

**Comment by chrislusf** [comment]
when accessing files, does the code close the file handles?

**Comment by Suika** [comment]
Will check with the people that wrote the software.

**Comment by Suika** [comment]
The tools accessing the data via fuse do close the handles from the talks. Either way, will close this and open a new one should something popup.
