### ISSUE TITLE
HTTP Resume Support?

### ISSUE THREAD

**Issue by cathalgarvey** [chrislusf/seaweedfs#193]
You can offer a HTTP source for downloadable files in bittorrent these days; I'm wondering if SeaweedFS would make a neat way to spin up a bittorrent cache application like burnbit but with uploading of own files.

The question becomes, as bittorrent clients usually use HTTP resume to fetch the specified chunks from Torrents one-at-a-time, the files get fetched in tens or hundreds of requests starting at different portions of the file.

I guess this is also relevant to downloading files from SeaweedFS using `wget -c`.

So, does SeaweedFS support HTTP resumes? :)

**Comment by chrislusf** [comment]
Yes.

**Comment by cathalgarvey** [comment]
Thanks, sorry for the trivial Q but would be a dealbreaker for certain applications.
