### ISSUE TITLE
[master] Save topology after changing master

### ISSUE THREAD

**Issue by kmlebedev** [chrislusf/seaweedfs#1932]
After restart, a new master with an empty topology is selected, which is filled as volumes are connected

One of the possible reasons 
https://github.com/chrislusf/seaweedfs/issues/1923

**Comment by chrislusf** [comment]
Not clear what to do for this issue.

The topology is not useful if the volume servers are not connected.

**Comment by kmlebedev** [comment]
Then you need to force the reconnection without waiting for the heartbeat

**Comment by kmlebedev** [comment]
https://github.com/chrislusf/seaweedfs/pull/3228
