### ISSUE TITLE
Only odd number of masters are supported!

### ISSUE THREAD

**Issue by rotproofbits** [chrislusf/seaweedfs#1935]
**Describe the bug**

```
I0323 15:00:10  2532 file_util.go:23] Folder /data/seaweedfs/media/master Permission: -rwxr-xr-x
I0323 15:00:10  2532 master.go:168] current: xxxxxxxxxx :9333 peers:10.10.150.10:9333,10.10.150.11:9333,10.10.150.12:9333
F0323 15:00:10  2532 master.go:186] Only odd number of masters are supported!
goroutine 1 [running]:
github.com/chrislusf/seaweedfs/weed/glog.stacks(0xc0002e2400, 0xc00013afc0, 0x4e, 0xbb)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:767 +0xb9
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).output(0x3650060, 0xc000000003, 0xc0001fb730, 0x2b793fa, 0x9, 0xba, 0x0)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:718 +0x37a
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).printf(0x3650060, 0xc000000003, 0x22face5, 0x29, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:656 +0x153
github.com/chrislusf/seaweedfs/weed/glog.Fatalf(...)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:1149
github.com/chrislusf/seaweedfs/weed/command.checkPeers(0xc000623c54, 0xb, 0x2475, 0x7ffc1f63b621, 0x35, 0x364f980, 0xc0009bfcd8, 0x76344a, 0x3650060, 0xc0001fb730)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/command/master.go:186 +0x295
github.com/chrislusf/seaweedfs/weed/command.startMaster(0xc000623c08, 0xc000129440, 0xc000129460, 0xc000129480, 0xc0001294a0, 0xc000623c80, 0xc000623c95, 0xc0001294b0, 0xc000623ca0, 0xc0001294d0, ...)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/command/master.go:117 +0x85
github.com/chrislusf/seaweedfs/weed/command.runMaster(0x36303a0, 0xc00004c0f0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/command/master.go:108 +0x1aa
main.main()
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/weed.go:66 +0x315
```

**System Setup**

- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".

 `/usr/local/sbin/weed-30gb master -ip.bind=10.10.150.10 -peers=10.10.150.10:9333,10.10.150.11:9333,10.10.150.12:9333 -mdir=/data/seaweedfs/media/master -volumePreallocate -defaultReplication=002 -volumeSizeLimitMB=4096`

- OS version

Debian 10

- output of `weed version`

version 30GB 2.29 f29ae0d linux amd64

- if using filer, show the content of `filer.toml`

N/A

**Expected behavior**

Seaweedfs to start normally, binding to a single private IP address, and then allowing connections ideally from any 10.0.0.0/8 address, but at least from the other masters/volume servers. (No volume servers started yet, but initially will be on the same server/internal IP address as masters.)

**Additional context**

Some possible documentation improvements:

It is unclear what the difference between `-ip.bind` and `-ip` is, but it appears that `-ip.bind` binds to the IP (and really should default to 127.0.0.1, not 0.0.0.0/0) and `-ip` restricts the IP that can access the server to only the specified IPs (also unclear if this can be a subnet mask.)

It's also unclear why the command-line arguments are changing and what the accepted and not-accepted arguments are, except for checking -h. It looks like users might need to do adjustments to startup scripts or config files with every upgrade of seaweed, since it looks like there's no backwards compatibility or marking of deprecated args. Much of the docs (which appear to be chiefly in the wiki?) seem to be referencing a mixture of old and new command args.

**Comment by chrislusf** [comment]
-ip is needed to identify the server itself. Need to add `-ip=10.10.150.10`.

> It's also unclear why the command-line arguments are changing and what the accepted and not-accepted arguments are, except for checking -h. It looks like users might need to do adjustments to startup scripts or config files with every upgrade of seaweed, since it looks like there's no backwards compatibility or marking of deprecated args. Much of the docs (which appear to be chiefly in the wiki?) seem to be referencing a mixture of old and new command args.

What version you are upgrading from? Can you give one example of a changed CLI argument?

**Comment by chrislusf** [comment]
seems the server is recognizing itself as `5.9.152.195`, not `10.10.150.10`.

**Comment by rotproofbits** [comment]
Yes, why would it do that (recognize itself as a random IP on the box instead of the specific IPs or 127.0.01; big security risk.

(For example, -volume.port, -volume.dir, etc)

**Comment by rotproofbits** [comment]
Can you delete this issue, since it shows my IP? ;) thanks

**Comment by rotproofbits** [comment]
For example, `grep -e "\-\(volume\|master\)\." . -R` in the wiki files. (-volume.max, etc)

**Comment by chrislusf** [comment]
> For example, `grep -e "\-\(volume\|master\)\." . -R` in the wiki files. (-volume.max, etc)

Can you be specific? For `-volume.max`, it is for `weed server`, not for `weed master`
