### ISSUE TITLE
[Doc] S3 limitation for conflicting object paths

### ISSUE THREAD

**Issue by candlerb** [chrislusf/seaweedfs#1938]
In an object store, `a/b` and `a/b/c` can both exist as objects at the same time.  However because SeaweedFS's S3 service is a front-end to the filer service, it can't handle `a/b` being both a directory and a file:

```
$ echo FOO >foo
$ echo BAR >bar
$ aws --endpoint-url http://localhost:8333 s3 cp foo s3://pail/foo
upload: ./foo to s3://pail/foo
$ aws --endpoint-url http://localhost:8333 s3 cp bar s3://pail/foo/bar
upload failed: ./bar to s3://pail/foo/bar An error occurred (InternalError) when calling the PutObject operation (reached max retries: 4): We encountered an internal error, please try again.
```

Logs generated:

```
E0324 07:22:06 20280 filer.go:233] CreateEntry /buckets/pail/foo/bar: /buckets/pail/foo should be a directory
I0324 07:22:06 20280 filer_server_handlers_write_autochunk.go:227] failing to write /buckets/pail/foo/bar to filer server : /buckets/pail/foo is a file
I0324 07:22:06 20280 common.go:53] response method:PUT URL:/buckets/pail/foo/bar with httpStatus:500 and JSON:{"error":"/buckets/pail/foo is a file"}
E0324 07:22:06 20280 s3api_object_handlers.go:380] upload to filer error: /buckets/pail/foo is a file
```

This is the same limitation as [documented for ChubaoFS](https://chubaofs.readthedocs.io/en/latest/design/objectnode.html#object-mode-conflict-important), but I couldn't find it in the SeaweedFS documentation.  A suitable place would be [here](https://github.com/chrislusf/seaweedfs/wiki/Amazon-S3-API) where other API differences are discussed.

I would also suggest that 500 is not the most appropriate error status: it's not a server bug, and it's not an intermittent server problem which can be fixed if the client retries later.  Chubao gives a 409 (Conflict) response.

**Comment by chrislusf** [comment]
Thanks for the details. Added a fix and adjusted the wiki.

You are also welcome to change the wiki directly. It is open to everyone.
