### ISSUE TITLE
Clarify Trust Model for Volumes

### ISSUE THREAD

**Issue by cathalgarvey** [chrislusf/seaweedfs#194]
Hello,
An interesting question that immediately comes to mind for me is: can I spin up a weed server, and then invite people to contribute space by spinning up volumes and pointing them at my server?

Of course, these people would then have file access, but files could be encrypted before storage in this way. More urgently, how might "donated volumes" present integrity challenges such as:

1. Volunteer joins and offers volume, then maliciously or innocently disconnects their volume after receiving files; can replication settings handle this sort of volume-churn?
2. Attacker connects lots of volumes to try and get SeaweedFS to redistribute existing data to their new volumes, allowing them to "steal" files that might get removed from other volumes, and then disconnect, depriving the network of these files.

What's the threat model here? Can replication settings be set up so that even a particular portion of volume storage-mass can be volunteered safely, provided the majority is trusted? Or is Seaweed fundamentally unsuitable for untrusted volumes?

Thanks!

**Comment by chrislusf** [comment]
Not designed for the use case. Very different.
