### ISSUE TITLE
{"error":"/dataset is a file"}

### ISSUE THREAD

**Issue by cherishman2005** [chrislusf/seaweedfs#1944]
**Describe the bug**
文件删了，为啥就不能再以文件夹的 形式上传文件了。
如果 刚好这个路径 必须线上用到，怎么解决？

**Screenshots**
![image](https://user-images.githubusercontent.com/17688273/112443781-4f462d80-8d88-11eb-8899-873f810211a7.png)

**Comment by chrislusf** [comment]
works for me.

<img width="720" alt="Screen Shot 2021-03-25 at 01 41 21" src="https://user-images.githubusercontent.com/1543151/112444731-98a46780-8d0b-11eb-81c3-6c0765003aff.png">

**Comment by cherishman2005** [comment]
remove filer db, and restart filer ok

**Comment by chrislusf** [comment]
removal of filer db should not be needed
