### ISSUE TITLE
some url response 400，but before a few hours can be available.

### ISSUE THREAD

**Issue by wu0407** [chrislusf/seaweedfs#196]
I found something in log:
I0921 18:35:25 07295 volume.go:104] loading file /opt/weedfs/10.idx readonly false
I0921 18:35:25 07295 store.go:213] data file /opt/weedfs/10.dat, replicaPlacement=000 v=2 size=233796408 ttl=
I0921 18:35:25 07295 volume.go:104] loading file /opt/weedfs/11.idx readonly false
I0921 18:35:25 07295 store.go:213] data file /opt/weedfs/11.dat, replicaPlacement=000 v=2 size=244400376 ttl=
I0921 18:35:25 07295 volume.go:104] loading file /opt/weedfs/12.idx readonly false
I0921 18:35:25 07295 store.go:213] data file /opt/weedfs/12.dat, replicaPlacement=000 v=2 size=234801008 ttl=
I0921 18:35:25 07295 volume.go:104] loading file /opt/weedfs/13.idx readonly false
I0921 18:35:25 07295 store.go:213] data file /opt/weedfs/13.dat, replicaPlacement=000 v=2 size=243400864 ttl=
I0921 18:35:25 07295 volume.go:104] loading file /opt/weedfs/14.idx readonly false
I0921 18:35:25 07295 store.go:213] data file /opt/weedfs/14.dat, replicaPlacement=000 v=2 size=240279680 ttl=
I0921 18:35:25 07295 volume.go:104] loading file /opt/weedfs/9.idx readonly false
I0921 18:35:25 07295 store.go:213] data file /opt/weedfs/9.dat, replicaPlacement=000 v=2 size=240233608 ttl=
I0921 18:35:25 07295 store.go:220] Store started on dir: /opt/weedfs with 6 volumes max 7
I0921 18:35:25 07295 volume.go:91] Start Seaweed volume server 0.65 at 0.0.0.0:9400
I0921 18:35:26 07295 needle.go:174] Invalid key_hash 01bd27a712cc8 length: 0 error encoding/hex: odd length hex string
I0921 18:35:26 07295 needle.go:174] Invalid key_hash 01bd27a712cc8 length: 0 error encoding/hex: odd length hex string
I0921 18:35:27 07295 needle.go:174] Invalid key_hash 01bd27a712cc8 length: 0 error encoding/hex: odd length hex string
I0921 18:35:27 07295 needle.go:174] Invalid key_hash 01bd27a712cc8 length: 0 error encoding/hex: odd length hex string
I0921 18:36:17 07295 needle.go:174] Invalid key_hash 01bd27a712cc8 length: 0 error encoding/hex: odd length hex string
I0921 18:36:20 07295 needle.go:174] Invalid key_hash 01cf59d2b27b7 length: 0 error encoding/hex: odd length hex string
I0921 18:36:24 07295 needle.go:174] Invalid key_hash 01b7fb39ea33f length: 0 error encoding/hex: odd length hex string
I0921 18:36:25 07295 needle.go:174] Invalid key_hash 01ca4d2b4f00d length: 0 error encoding/hex: odd length hex string
I0921 18:36:25 07295 needle.go:174] Invalid key_hash 01aa5f55c9af3 length: 0 error encoding/hex: odd length hex string
I0921 18:36:43 07295 needle.go:174] Invalid key_hash 01ca4d2b4f00d length: 0 error encoding/hex: odd length hex string

what happen ? how to repair it

**Comment by chrislusf** [comment]
Need to use the latest version or avoid sending "01ca4d2b4f00d", but sending "1ca4d2b4f00d". The former has odd number of digits. hex encoding requires even number of digits.

**Comment by wu0407** [comment]
this files are losed,but update to the 0.69 version, it has some output in log file

**Comment by wu0407** [comment]
sorry,i found code in client has some bug.lead to request error url
