### ISSUE TITLE
[system metrics] -  Pushgateway just recieves metrics of 2 weed volume servers

### ISSUE THREAD

**Issue by kaaaq** [chrislusf/seaweedfs#1964]
Hi,
I run Prometheus, Pushgateway and Grafana to access system metrics but it just shows metrics of two volume servers in Pushgateway.
 I configure this on 3 master servers:

```

-metrics.address=192.168.200.20:9091 -metrics.intervalSeconds=5

```
Pushgateway recognized just 2 weed volumes:

![image](https://user-images.githubusercontent.com/43205944/113588585-99ab9200-9645-11eb-8573-d809ba227688.png)

weed version:
`version 8000GB 2.29 f29ae0d linux amd64`

**Comment by chrislusf** [comment]
this is expected.

**Comment by chrislusf** [comment]
seems you have more than 2 volume servers. Can you show the master UI?

**Comment by kaaaq** [comment]
> seems you have more than 2 volume servers. Can you show the master UI?

I have 5 volume servers:

![image](https://user-images.githubusercontent.com/43205944/113667856-9d332d80-96c6-11eb-9fe9-cfda15356a89.png)

**Comment by chrislusf** [comment]
ok. but I can not tell why Pushgateway only received from 2 volume servers. There are no difference between them.

**Comment by kaaaq** [comment]
@chrislusf 
> ok. but I can not tell why Pushgateway only received from 2 volume servers. There are no difference between them.
So how can I understand what is the problem or where the problem comes from?

**Comment by kaaaq** [comment]
> ok. but I can not tell why Pushgateway only received from 2 volume servers. There are no difference between them.

@chrislusf 

I check tcp established connection on pushgateway server, but just 2 of weed volume servers stablished connection with pushgateway server:

test@ubuntu-test:~$ sudo netstat -ntlpua | grep 9091
tcp        0      0 172.30.103.249:17976    172.30.103.249:9091     ESTABLISHED 1223/prometheus 
tcp6       0      0 172.30.103.249:9091     172.30.102.103:56592    ESTABLISHED 29020/pushgateway
tcp6       0      0 172.30.103.249:9091     172.30.102.104:33604    ESTABLISHED 29020/pushgateway

172.30.103.249 is pushgateway server
172.30.102.103 is weed-volume-003 server
172.30.102.104 is weed-volume-004 server

**Comment by kaaaq** [comment]
@chrislusf 

I reset 3 remain volume servers that not connected to Pushgateway, after reseting they connected to pushgateway successfully
could you set an option that volume servers could get new options from master without restarting the weed volume service?
for example if I want to change the ip or "-metrics.intervalSeconds" to something else , I should restart all of my volume servers services
Could you fix this problem that weed doesn't need restart ?
