### ISSUE TITLE
[protoc] Unable to generate correct ".pb.go" file

### ISSUE THREAD

**Issue by wuh-fnst** [chrislusf/seaweedfs#1967]
Sorry, I need some help about the "protoc" environment.

I tried to regenerate `filer.pb.go` file.
But it didn't work
```
root@ubuntu:~# protoc filer.proto --go_out=plugins=grpc:./filer_pb --go_opt=paths=source_relative
--go_out: protoc-gen-go: plugins are not supported; use 'protoc --go-grpc_out=...' to generate gRPC
```

It works when I don't include grpc. 
`protoc filer.proto --go_out=./filer_pb  filer.proto`

The version number obtained in the `filer.pb.go` file is consistent with that in the code base, but the grpc related content is missing.
```
// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: filer.proto

package filer_pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)
```
Package version in my environment.
```
root@ubuntu:~# /root/go/bin/protoc-gen-go --version
protoc-gen-go v1.25.0
root@ubuntu:~# /root/go/bin/protoc-gen-go-grpc  -version
protoc-gen-go-grpc 1.1.0
```
Is this due to different versions of `protoc-gen-go-grpc`?
Can I know the version of `protoc-gen-go-grpc` used in the code base?

**Comment by chrislusf** [comment]
![Screen Shot 2021-04-06 at 01 18 04](https://user-images.githubusercontent.com/1543151/113680646-f1fa8800-9675-11eb-8b1c-1df2fcd61cc1.png)

This may help you.
https://stackoverflow.com/questions/61044883/switch-from-go-out-plugins-to-go-grpc-out-path-problem
