### ISSUE TITLE
Large file (video) storage and streaming

### ISSUE THREAD

**Issue by ArtworkAD** [chrislusf/seaweedfs#197]
Hey @chrislusf this is not an issue but a question. Would you self consider seaweed is capable of storing large video files, e.g. 500 MB? If so, do you think we could stream them fast to multiple users?

Before I make an effort to test this out I would like to hear your opinion.

**Comment by chrislusf** [comment]
Not capable. Better to have a layer in front to break the stream into 10mb or so blocks and store those blocks.
