### ISSUE TITLE
[weed mount] multiple weed mount, cannot sync file size correctly

### ISSUE THREAD

**Issue by paochiang** [chrislusf/seaweedfs#1970]
**Describe the bug**
Setup two `weed mount`,  write a 3G file through one `weed mount` filesystem(actually, file is uploaded to the mounted directory via sftp)，another `weed mount` filesystem cannot view the correct file size.

**System Setup**
- set up in k8s
master setup command(3 master):
![image](https://user-images.githubusercontent.com/28077875/112099597-c8098600-8bde-11eb-85f4-1c822106d00d.png)
filer setup command(3 filer):
![image](https://user-images.githubusercontent.com/28077875/112099755-0737d700-8bdf-11eb-91a8-bbe3731cdc49.png)
volume setup command(3 volume):
![image](https://user-images.githubusercontent.com/28077875/112099835-2cc4e080-8bdf-11eb-9de1-b08e4b6ea24e.png)

after setup, k8s pod status:
![image](https://user-images.githubusercontent.com/28077875/112102246-f0937f00-8be2-11eb-93d8-fe55315b9b3d.png)

one `weed mount` command(for file upload):
`weed mount -volumeServerAccess=publicUrl -cacheCapacityMB=0 -filer=10.10.10.215:22602 -dir=/mnt/swfs`

![image](https://user-images.githubusercontent.com/28077875/112100270-d2784f80-8bdf-11eb-9c93-3f609185f7ba.png)

another `weed mount` command(in k8s):
`weed mount -filer=seaweedfs-filer:8888 -cacheCapacityMB=0 -cacheDir=/tmp/mENTkEKuZK -dir=/tmp/JZIMicgwlp -filer.path=/pavostor`
- OS version
Ubuntu 18.04.4 LTS
- output of `weed version`
version 30GB 2.28 37f104f linux amd64
- if using filer, show the content of `filer.toml`
/etc/seaweedfs/filer.toml, actually use mysql
```
[leveldb2]
enabled = true
dir = "/data/filerldb2"
```

**Expected behavior**
After the `weed mount`, the correct file size can be viewed in another `weed mount`

**Screenshots**
command `du -h` cannot get correct size:
![image](https://user-images.githubusercontent.com/28077875/113810010-eacd9a00-979b-11eb-964e-67f26d82ec2f.png)

`os.Stat()` func cannot get correct size:
![image](https://user-images.githubusercontent.com/28077875/113810536-143af580-979d-11eb-855e-0552f0b572fa.png)

In `weed shell`, file size is correct:
![image](https://user-images.githubusercontent.com/28077875/113809943-cbcf0800-979b-11eb-9c9d-a0a855e0b5bf.png)

**Additional context**

new `weed mount` can get correct file size.

BTW,  this test was done last week, the log is not available now.

**Comment by chrislusf** [comment]
seems mysql and leveldb2 filer stores are both enabled?

**Comment by paochiang** [comment]
When deploying the filer, leveldb2 is disabled through the environment variable `WEED_LEVELDB2_ENABLED`
![image](https://user-images.githubusercontent.com/28077875/113826847-36d90880-97b5-11eb-9677-3bcbfb9f0057.png)

And there is nothing in the configured directory:
filer0
![image](https://user-images.githubusercontent.com/28077875/113827455-e6ae7600-97b5-11eb-8caf-ab169fabcaa2.png)
filer1
![image](https://user-images.githubusercontent.com/28077875/113827266-afd86000-97b5-11eb-8be9-bebef70eff1a.png)
filer2
![image](https://user-images.githubusercontent.com/28077875/113827511-fb8b0980-97b5-11eb-8621-5927ee71e1a8.png)

So it should only be mysql is enabled.

**Comment by chrislusf** [comment]
> When deploying the filer, leveldb2 is disabled through the environment variable `WEED_LEVELDB2_ENABLED`

it is undeterministic which one is in effect.

**Comment by paochiang** [comment]
Found the filer's log at startup：
![image](https://user-images.githubusercontent.com/28077875/113828663-3e99ac80-97b7-11eb-90cf-1ba344a3889e.png)

**Comment by paochiang** [comment]
After remounting, the size is displayed as normal：
![image](https://user-images.githubusercontent.com/28077875/113829839-8c62e480-97b8-11eb-8a9c-a369796821fe.png)

**Comment by chrislusf** [comment]
the log shows can not connect to peer filer

**Comment by paochiang** [comment]
Because other filers have not been started since the beginning, and finally the connection is normal:
![image](https://user-images.githubusercontent.com/28077875/113836677-ae139a00-97bf-11eb-899f-1840b8e8def6.png)

**Comment by paochiang** [comment]
I found a way to reproduce this problem, but I’m not sure if the first time is the same reason.

I found that when a file is uploading in first `weed mount` (upload a large file), the size of this file is zero in the second `weed mount`. After the file is written, the size of this file in the second `weed mount` is still zero. The second `weed mount` needs to be remounted to display the normal file size. Is this expected？(What I expect is that the file size displayed in the second `weed mount` after the file is written becomes the normal size)

**Comment by chrislusf** [comment]
Is this still reproducible? There have been several changes about this.

**Comment by paochiang** [comment]
> Is this still reproducible in latest version? There have been several changes about this.

Tried in version: `release 2.48`, it's can not be reproduced. I think this issue was fixed.  But I found that it takes some time for a large file(test write one 6GB file) written by one `weed mount` to be seen in another `weed mount`.

**Comment by chrislusf** [comment]
How much is "some time"?

**Comment by paochiang** [comment]
> How much is "some time"?

I don't know the exact time, but I think it's about 1 or 2 minutes
