### ISSUE TITLE
Slow performance in replication mode 010 while executing volume.fix.replication

### ISSUE THREAD

**Issue by vankosa** [chrislusf/seaweedfs#1977]
Hello
We have a cluster in replication mode 010 (before that there was one rack with 000, which we decided to expand). At the moment, there are about 150,000 volumes, with a limit of 1000 megabytes. 
Now we are going through the fix.replication stage to replicate the data from the first rack to the second. We have huge problems with the speed of data access, especially during replication.
Also, with a large data flow on the second rack, errors occur: requests.exceptions.ReadTimeout: `HTTPConnectionPool(host='node2.example.com', port=11009): Read timed out`
Our cluster:
3 master nodes
2 racks of 18 raid arrays (12 terabytes each), each 70% full on the first rack
The wizards are launched with the command: `weed master -defaultReplication="010" -port="9333" -peers=node1.example.com:9333,node2.example.com:9333,node3.example.com:9333 -volumeSizeLimitMB="1024" -ip="node2.example.com" -metrics.address="node2.example.com:9091"`
Volumes are launched with the command: `weed volume -dataCenter="netrack" -rack="node2" -port="11001" -port.public="11001" -mserver="node1.example.com:9333,node2.example.com:9333,node3.example.com:9333" -ip="node2.example.com" -max=10000 -dir=/mnt/disk1/swfs`

PS: At the moment, about 40% are replicated and it is impossible to work further

**Comment by chrislusf** [comment]
you can add `weed volume -compactionMBps=xxx` to limit the bandwidth used by `volume.fix.replication`

**Comment by vankosa** [comment]
The problem is that even after the replication stops, the access speed is very slow. And the replication itself is very slow, the network is 10G, but the speed is not more than 150 megabits

**Comment by chrislusf** [comment]
try to restart after the replication stops.

**Comment by vankosa** [comment]
Restart what? Replication, by the way, itself is not postponed. She fills the volume to the end.
There are really a lot of volumes, I agree, but you also need to store a lot of data

**Comment by vankosa** [comment]
There is also a nuance in that before connecting the second rack and starting replication, everything worked well. Problems started after replicating the fifth volume (~ 40,000 id)

**Comment by chrislusf** [comment]
restart the volume servers.

**Comment by kmlebedev** [comment]
@vankosa Can you show grafana dashboard ?

**Comment by vankosa** [comment]
Not a great idea. Indexing of such a large amount of data takes up to two hours, it stops the workflow

**Comment by kmlebedev** [comment]
> Not a great idea. Indexing of such a large amount of data takes up to two hours, it stops the workflow

But the data is replicated ?

**Comment by vankosa** [comment]
> @vankosa Can you show grafana dashboard ?

![image](https://user-images.githubusercontent.com/40017592/114142450-a10bbd80-991b-11eb-9048-1af67a3aee12.png)

**Comment by vankosa** [comment]
> > Not a great idea. Indexing of such a large amount of data takes up to two hours, it stops the workflow
> 
> But the data is replicated ?

Replication is performed from different volumes in the first rack to the same volume in the second rack. Restarting the volume to which it was replicated does not help.

**Comment by kmlebedev** [comment]
I see 98% of requests is this POST record? 
It turns out that the speed for writing or only for reading has dropped?

**Comment by vankosa** [comment]
> I see 98% of requests is this POST record?
> It turns out that the speed for writing or only for reading has dropped?

Only for writing

**Comment by kmlebedev** [comment]
> > I see 98% of requests is this POST record?
> > It turns out that the speed for writing or only for reading has dropped?
> 
> Only for writing

It's strange, the volume servers  doesn't know anything about replication, but as I understand it, they are the ones who slow down, not the filler

**Comment by vankosa** [comment]
> > > I see 98% of requests is this POST record?
> > > It turns out that the speed for writing or only for reading has dropped?
> > 
> > 
> > Only for writing
> 
> It's strange, the volume servers doesn't know anything about replication, but as I understand it, they are the ones who slow down, not the filler

filer is not used, we work directly through api master node

**Comment by vankosa** [comment]
I will clarify more.
The write speed is low not only through the master hosts, but also through the replication itself.

**Comment by kmlebedev** [comment]
> I will clarify more.
> The write speed is low not only through the master hosts, but also through the replication itself.

Cat you show examples for a curl slow requests ?

**Comment by vankosa** [comment]
> > I will clarify more.
> > The write speed is low not only through the master hosts, but also through the replication itself.
> 
> Can you show examples for a curl slow requests ?

```
curl --location --request POST 'http://master.example.com:9333/submit' \
--form 'file=@"filename.jpg"'
```

**Comment by chrislusf** [comment]
why there are 2 volume instances on `n103.unim.internal:11018`?

**Comment by vankosa** [comment]
> why there are 2 volume instances on `n103.unim.internal:11018`?

This error after restart after master, metrics are sometimes duplicated

**Comment by chrislusf** [comment]
do you have metrics on memory usage?

**Comment by vankosa** [comment]
> do you have metrics on memory usage?
Everything is interesting with this. On hosts, 256 gigabytes of RAM, but this is not enough, so we have large swap partitions. The first rack uses all the memory and another 150 gigabytes of swap. On the second, the amount of data is still not enough to use the swap, but the memory is almost all used up. This has been happening for a long time, long before the start of replication.

**Comment by vankosa** [comment]
![image](https://user-images.githubusercontent.com/40017592/114153550-18474e80-9928-11eb-815b-32c88695d978.png)
![image](https://user-images.githubusercontent.com/40017592/114153599-27c69780-9928-11eb-9889-2abe4fd5b2f2.png)

**Comment by chrislusf** [comment]
- stats on disk IO ops per second? Maybe something to do with RAID?
- show the output of `volume.list`
- Not recommended to use 'http://master.example.com:9333/submit'. You can use `weed upload`.

**Comment by vankosa** [comment]
> * stats on disk IO ops per second? Maybe something to do with RAID?
> * show the output of `volume.list`
> * Not recommended to use 'http://master.example.com:9333/submit'. You can use `weed upload`.

1. Disk IO no more than 200 Iops
2. There is 220k volumeID, I don't think it's a good idea
3. From the software side, the python library is used (https://pypi.org/project/python-weed/), curl was used as an example.

**Comment by kmlebedev** [comment]
> > do you have metrics on memory usage?
> 
> Everything is interesting with this. On hosts, 256 gigabytes of RAM, but this is not enough, so we have large swap partitions. The first rack uses all the memory and another 150 gigabytes of swap. On the second, the amount of data is still not enough to use the swap, but the memory is almost all used up. This has been happening for a long time, long before the start of replication.

Never use a swap on workloads!

**Comment by vankosa** [comment]
> > > do you have metrics on memory usage?
> > 
> > 
> > Everything is interesting with this. On hosts, 256 gigabytes of RAM, but this is not enough, so we have large swap partitions. The first rack uses all the memory and another 150 gigabytes of swap. On the second, the amount of data is still not enough to use the swap, but the memory is almost all used up. This has been happening for a long time, long before the start of replication.
> 
> Never use a swap on workloads!

Well, it worked fine before replication. And the first 5 volumes were also well replicated, and then it just began to work slowly.

**Comment by kmlebedev** [comment]
> > > > do you have metrics on memory usage?
> > > 
> > > 
> > > Everything is interesting with this. On hosts, 256 gigabytes of RAM, but this is not enough, so we have large swap partitions. The first rack uses all the memory and another 150 gigabytes of swap. On the second, the amount of data is still not enough to use the swap, but the memory is almost all used up. This has been happening for a long time, long before the start of replication.
> > 
> > 
> > Never use a swap on workloads!
> 
> Well, it worked fine before replication. And the first 5 volumes were also well replicated, and then it just began to work slowly.

Just do it

**Comment by vankosa** [comment]
> > > do you have metrics on memory usage?
> > 
> > 
> > Everything is interesting with this. On hosts, 256 gigabytes of RAM, but this is not enough, so we have large swap partitions. The first rack uses all the memory and another 150 gigabytes of swap. On the second, the amount of data is still not enough to use the swap, but the memory is almost all used up. This has been happening for a long time, long before the start of replication.
> 
> Never use a swap on workloads!

In fact, I understand this perfectly, but we have what we have

**Comment by kmlebedev** [comment]
> In fact, I understand this perfectly, but we have what we have

You do not understand how swap works, you either need to accept it or try to figure it out.
In fact, you have enough memory, it's just that it is occupied by pageCache.
Can you show htop, like this
https://disk.yandex.com/i/y6DSQYlkpfJTsQ

**Comment by vankosa** [comment]
Below is the first node, on top - the second
![image](https://user-images.githubusercontent.com/40017592/114164042-86ddd980-9933-11eb-9b1e-cb4572de56a9.png)

**Comment by kmlebedev** [comment]
> Below is the first node, on top - the second
> ![image](https://user-images.githubusercontent.com/40017592/114164042-86ddd980-9933-11eb-9b1e-cb4572de56a9.png)

The second picture is very bad and you really ran out of memory.
There are two options
1. Add server
2. Try to programmatically reduce memory consumption in seaweedfs

**Comment by vankosa** [comment]
1. Impossible
2. Can you tell me how? Should I use leveldb for indexes?

**Comment by vankosa** [comment]
One more moment, I just remembered.
The problems began after the swap was completely filled on the first node (it was only 100 gigabytes then). I added and re-started the volumes for reindexing. And since then there have been problems in the recording speed.

**Comment by kmlebedev** [comment]
> 1. Impossible
> 2. Can you tell me how? Should I use leveldb for indexes?
2. Try index from left to right until reaching the desired memory / performance balance

```
weed volume
  -index string
        Choose [memory|leveldb|leveldbMedium|leveldbLarge] mode for memory~performance balance. (default "memory")
```

**Comment by kmlebedev** [comment]
@vankosa How is it going ?

**Comment by vankosa** [comment]
> @vankosa How is it going ?

Good day!

We are waiting for the PAM to be added to the servers, after that we will continue.
At the moment, we have disconnected half of the volumes on the second server and it started to work well.

**Comment by vankosa** [comment]
> @vankosa How is it going ?

Hey!
Added RAM to a total volume of 500 gigabytes, it didn't help much, everything is still very slow

**Comment by chrislusf** [comment]
You can just copy all the files under `/mnt/disk1/swfs` from the first volume server to the second, and start.

**Comment by vankosa** [comment]
> You can skip `volume.fix.replicatin`. Just copy all the files under `/mnt/disk1/swfs` from the first volume server to the second, and start.

Yes, I thought about this option.
The problem is that the write speed drops even with replication turned off. Now, there seems to be no frank performance drawdown, while I'm watching. We plan to receive the load tomorrow afternoon, if it slows down the cluster, then I will manually transfer it by copying (at the moment, 7 volumes on the second server are already filled from random volumes of the first)

**Comment by vankosa** [comment]
After adding RAM and some replication of several more volumes, we get errors on n103 (second server):

`Apr 26 16:23:32 n103 seaweedfs-vol16[2022]: W0426 16:23:32  2022 volume_info.go:49] unmarshal error: unexpected EOF
Apr 26 16:23:32 n103 seaweedfs-vol16[2022]: W0426 16:23:32  2022 volume_tier.go:31] load volume 158646.vif file: unmarshal error: unexpected EOF
Apr 26 16:23:32 n103 seaweedfs-vol16[2022]: I0426 16:23:32  2022 volume_loading.go:86] readSuperBlock volume 158646 version 3
Apr 26 16:23:32 n103 seaweedfs-vol16[2022]: I0426 16:23:32  2022 volume_loading.go:133] loading index /mnt/disk16/swfs/158646.idx to memory
Apr 26 16:23:32 n103 seaweedfs-vol16[2022]: I0426 16:23:32  2022 disk_location.go:134] data file /mnt/disk16/swfs/158646.dat, replicaPlacement=010 v=3 size=8 ttl=
Apr 26 16:23:32 n103 seaweedfs-vol16[2022]: I0426 16:23:32  2022 store.go:384] mount volume 158646
Apr 26 16:23:38 n103 seaweedfs-vol16[2022]: I0426 16:23:38  2022 volume_loading.go:86] readSuperBlock volume 18948 version 3
Apr 26 16:23:38 n103 seaweedfs-vol16[2022]: I0426 16:23:38  2022 volume_loading.go:133] loading index /mnt/disk16/swfs/18948.idx to memory
Apr 26 16:23:38 n103 seaweedfs-vol16[2022]: I0426 16:23:38  2022 disk_location.go:134] data file /mnt/disk16/swfs/18948.dat, replicaPlacement=010 v=3 size=1077485640 ttl=
Apr 26 16:23:38 n103 seaweedfs-vol16[2022]: I0426 16:23:38  2022 store.go:384] mount volume 18948
Apr 26 16:23:39 n103 seaweedfs-vol16[2022]: W0426 16:23:39  2022 volume_info.go:49] unmarshal error: unexpected EOF
Apr 26 16:23:39 n103 seaweedfs-vol16[2022]: W0426 16:23:39  2022 volume_tier.go:31] load volume 154946.vif file: unmarshal error: unexpected EOF
Apr 26 16:23:39 n103 seaweedfs-vol16[2022]: I0426 16:23:39  2022 volume_loading.go:86] readSuperBlock volume 154946 version 3
Apr 26 16:23:39 n103 seaweedfs-vol16[2022]: I0426 16:23:39  2022 volume_loading.go:133] loading index /mnt/disk16/swfs/154946.idx to memory
Apr 26 16:23:39 n103 seaweedfs-vol16[2022]: I0426 16:23:39  2022 disk_location.go:134] data file /mnt/disk16/swfs/154946.dat, replicaPlacement=010 v=3 size=8 ttl=
Apr 26 16:23:39 n103 seaweedfs-vol16[2022]: I0426 16:23:39  2022 store.go:384] mount volume 154946
Apr 26 16:23:40 n103 seaweedfs-vol16[2022]: W0426 16:23:40  2022 volume_info.go:49] unmarshal error: unexpected EOF
Apr 26 16:23:40 n103 seaweedfs-vol16[2022]: W0426 16:23:40  2022 volume_tier.go:31] load volume 156753.vif file: unmarshal error: unexpected EOF
Apr 26 16:23:40 n103 seaweedfs-vol16[2022]: I0426 16:23:40  2022 volume_loading.go:86] readSuperBlock volume 156753 version 3
Apr 26 16:23:40 n103 seaweedfs-vol16[2022]: I0426 16:23:40  2022 volume_loading.go:133] loading index /mnt/disk16/swfs/156753.idx to memory
Apr 26 16:23:40 n103 seaweedfs-vol16[2022]: I0426 16:23:40  2022 disk_location.go:134] data file /mnt/disk16/swfs/156753.dat, replicaPlacement=010 v=3 size=8 ttl=
Apr 26 16:23:40 n103 seaweedfs-vol16[2022]: I0426 16:23:40  2022 store.go:384] mount volume 156753
Apr 26 16:23:40 n103 seaweedfs-vol16[2022]: W0426 16:23:40  2022 volume_info.go:49] unmarshal error: unexpected EOF
Apr 26 16:23:40 n103 seaweedfs-vol16[2022]: W0426 16:23:40  2022 volume_tier.go:31] load volume 155481.vif file: unmarshal error: unexpected EOF
Apr 26 16:23:40 n103 seaweedfs-vol16[2022]: I0426 16:23:40  2022 volume_loading.go:86] readSuperBlock volume 155481 version 3
Apr 26 16:23:40 n103 seaweedfs-vol16[2022]: I0426 16:23:40  2022 volume_loading.go:133] loading index /mnt/disk16/swfs/155481.idx to memory
Apr 26 16:23:40 n103 seaweedfs-vol16[2022]: I0426 16:23:40  2022 disk_location.go:134] data file /mnt/disk16/swfs/155481.dat, replicaPlacement=010 v=3 size=8 ttl=
Apr 26 16:23:40 n103 seaweedfs-vol16[2022]: I0426 16:23:40  2022 store.go:384] mount volume 155481
Apr 26 16:23:40 n103 seaweedfs-vol16[2022]: W0426 16:23:40  2022 volume_info.go:49] unmarshal error: unexpected EOF
Apr 26 16:23:40 n103 seaweedfs-vol16[2022]: W0426 16:23:40  2022 volume_tier.go:31] load volume 156418.vif file: unmarshal error: unexpected EOF
Apr 26 16:23:40 n103 seaweedfs-vol16[2022]: I0426 16:23:40  2022 volume_loading.go:86] readSuperBlock volume 156418 version 3
Apr 26 16:23:40 n103 seaweedfs-vol16[2022]: I0426 16:23:40  2022 volume_loading.go:133] loading index /mnt/disk16/swfs/156418.idx to memory
Apr 26 16:23:40 n103 seaweedfs-vol16[2022]: I0426 16:23:40  2022 disk_location.go:134] data file /mnt/disk16/swfs/156418.dat, replicaPlacement=010 v=3 size=8 ttl=
Apr 26 16:23:40 n103 seaweedfs-vol16[2022]: I0426 16:23:40  2022 store.go:384] mount volume 156418`

Replication is clearly failing

**Comment by chrislusf** [comment]
should be fine. the volume is empty.

**Comment by vankosa** [comment]
> should be fine. the volume is empty.

No, the volumes are not empty and there are a lot of such messages.

**Comment by vankosa** [comment]
Why was the ticket closed? The issue is not resolved, the performance is still low

**Comment by chrislusf** [comment]
> > should be fine. the volume is empty.
> 
> No, the volumes are not empty and there are a lot of such messages.

Do you want to show the messages?

**Comment by vankosa** [comment]
> > > should be fine. the volume is empty.
> > 
> > 
> > No, the volumes are not empty and there are a lot of such messages.
> 
> Do you want to show the messages?

They differ only in the volume number

**Comment by chrislusf** [comment]
> > > > should be fine. the volume is empty.
> > > 
> > > 
> > > No, the volumes are not empty and there are a lot of such messages.
> > 
> > 
> > Do you want to show the messages?
> 
> They differ only in the volume number

So the volumes are empty.
