### ISSUE TITLE
increase volume on the exist volume

### ISSUE THREAD

**Issue by wu0407** [chrislusf/seaweedfs#198]
In version 0.69,first use:
 weed  volume -dir=/opt/weedfs/vol1 -ip.bind=0.0.0.0 -ip=192.168.0.79 -mserver=192.168.0.79:9333 -port=9400

next use:
weed  volume -dir=/opt/weedfs/vol1 -ip.bind=0.0.0.0 -ip=192.168.0.79 -mserver=192.168.0.79:9333 -port=9400 -max=20

but nothing happen,not increase volume.

**Comment by chrislusf** [comment]
use this to pre-allocate volumes.

https://github.com/chrislusf/seaweedfs/wiki/API#pre-allocate-volumes

**Comment by wu0407** [comment]
thanks

**Comment by wu0407** [comment]
@chrislusf   server status is here，anything wrong？
[root@app-test local]# curl "http://127.0.0.1:9333/dir/status?pretty=y"
{
  "Topology": {
    "DataCenters": [
      {
        "Free": 13,
        "Id": "DefaultDataCenter",
        "Max": 20,
        "Racks": [
          {
            "DataNodes": [
              {
                "Free": 13,
                "Max": 20,
                "PublicUrl": "27.115.21.218:9400",
                "Url": "192.168.0.79:9400",
                "Volumes": 7
              }
            ],
            "Free": 13,
            "Id": "DefaultRack",
            "Max": 20
          }
        ]
      }
    ],
    "Free": 13,
    "Max": 20,
    "layouts": [
      {
        "collection": "",
        "replication": "000",
        "ttl": "",
        "writables": [
          3,
          4,
          5,
          6,
          7,
          1,
          2
        ]
      }
    ]
  },
  "Version": "0.69 20150413"

**Comment by wu0407** [comment]
logs:
I0924 12:32:39 21163 volume_growth.go:206] Failed to assign volume 16 to [Node:topo:DefaultDataCenter:DefaultRack:192.168.0.79:9400, volumes:map[3:Id:3, Size:162420232, ReplicaPlacement:000, Collection:, Version:2, FileCount:2331, DeleteCount:0, DeletedByteCount:0, ReadOnly:false 4:Id:4, Size:178616008, ReplicaPlacement:000, Collection:, Version:2, FileCount:2330, DeleteCount:0, DeletedByteCount:0, ReadOnly:false 5:Id:5, Size:176584200, ReplicaPlacement:000, Collection:, Version:2, FileCount:2288, DeleteCount:0, DeletedByteCount:0, ReadOnly:false 6:Id:6, Size:179385560, ReplicaPlacement:000, Collection:, Version:2, FileCount:2273, DeleteCount:0, DeletedByteCount:0, ReadOnly:false 7:Id:7, Size:176451984, ReplicaPlacement:000, Collection:, Version:2, FileCount:2256, DeleteCount:0, DeletedByteCount:0, ReadOnly:false 1:Id:1, Size:177486640, ReplicaPlacement:000, Collection:, Version:2, FileCount:2198, DeleteCount:0, DeletedByteCount:0, ReadOnly:false 2:Id:2, Size:168775568, ReplicaPlacement:000, Collection:, Version:2, FileCount:2246, DeleteCount:0, DeletedByteCount:0, ReadOnly:false], Ip:192.168.0.79, Port:9400, PublicUrl:192.168.0.79:9400, Dead:false] error Invalid JSON result for /admin/assign_volum:

**Comment by chrislusf** [comment]
you did not show what command you use.

**Comment by wu0407** [comment]
i use curl "http://localhost:9333/vol/grow?replication=000&count=13"  to pre-allocate volume,the log is master output.

**Comment by wu0407** [comment]
it likes as a bug

**Comment by chrislusf** [comment]
Your command line showed is different from what the status reported. The command line is not using publicUrl, but the volume status is showing publicUrl.

This is important since the master uses publicUrl to access the volume server to pre-allocate volumes.
