### ISSUE TITLE
[Question] - volume count 

### ISSUE THREAD

**Issue by kaaaq** [chrislusf/seaweedfs#1982]
Hi,
I've ran a new weed cluster since 4 days back and I created some collections on it e.g: " MegaGroup, Channel_1, Channel_40, ... "
and since that they till now just 20% of it filled , but some collections count are 12 and some of them are 24:

![image](https://user-images.githubusercontent.com/43205944/114261443-d84b9e80-99ef-11eb-9627-a437e27a1897.png)

1. Why weed created volume for some collection again (I mean the collection that have 24 volume) while they are still free?
2. What is the default number of volume creation if that collection is full in weed? (I mean, if I request volume fid for specific collection  that all of its volumes are full , How many volumes it will create? ) 
3. Can I define a default value on master that if there is no free volume so create my desired number of volume? is there any option for this? (e.g: -volume-default-count )

```
/usr/local/bin/weed version
version 8000GB 2.29 f29ae0d linux amd64 
```

**Comment by chrislusf** [comment]
2 and 3: see https://github.com/chrislusf/seaweedfs/wiki/Optimization#increase-concurrent-writes
1: different types of volumes, i.e., TTL, replication, will each have its set of volumes.

**Comment by kaaaq** [comment]
> 1: different types of volumes, i.e., TTL, replication, will each have its set of volumes.
They are not different types of volumes , they are the same, for example for collection: "User_50" and "UserCloud":
```
      {
        "collection": "User_50",
        "replication": "001",
        "ttl": "",
        "writables": [
          118,
          256,
          117,
          253,
          254,
          119,
          257,
          255,
          258,
          115,
          116,
          120
        ]
      },
      {
        "collection": "UserCloud",
        "replication": "001",
        "ttl": "",
        "writables": [
          283,
          284,
          285,
          286,
          287,
          288
        ]
      },
```
