### ISSUE TITLE
"lock" command would hang out the shell for using "volume.fix.replication"

### ISSUE THREAD

**Issue by kaaaq** [chrislusf/seaweedfs#1983]
Hi,
I've 5 volume servers with 3 disk and 8TB each of them
Last night I format one 8 TB disk and use volume.fix.replication to repair deleted volumes, it worked good for repairing half of the volumes but after that it started to show following error and exited the shell continuously when I commit volume.fix.replication:
```
error: copying from weed-volume-005.s02.test.local:8080 => weed-volume-002.s02.test.local:8080 : rpc error: code = Unknown desc = failed to copy /srv/node/sdb/Group_40_208.dat file: receiving /srv/node/sdb/Group_40_208.dat: rpc error: code = Unknown desc = read /srv/node/sdd/Group_40_208.dat: input/output error
```
I entered again volume.fix.replication but it shows error and exit from shell again:
```
error: copying from weed-volume-005.s02.test.local:8080 => weed-volume-002.s02.test.local:8080 : rpc error: code = Unknown desc = failed to copy /srv/node/sdb/User_10_124.dat file: receiving /srv/node/sdb/User_10_124.dat: rpc error: code = Unknown desc = read /srv/node/sdd/User_10_124.dat: input/output error
```
today when I wanted to repair it again it couldn't lock the shell and it waits for lock command without donig anything:

![image](https://user-images.githubusercontent.com/43205944/114296403-81fa6080-9ac0-11eb-9b98-e5d27340b483.png)

I restart all masters but still it is not working!!!
What should I do?

**Comment by chrislusf** [comment]
if lock is waiting, this means there is another processing has the lock.

**Comment by kaaaq** [comment]
> if lock is waiting, this means there is another processing has the lock.

In the middle of the "volume.fix.replication" process, it will happens a lot of errors as the following:
```
error: copying from weed-volume-005.s02.test.local:8080 => weed-volume-003.s02.test.local:8080 : rpc error: code = Unknown desc = fsdb/User_10_124.dat: rpc error: code = Unknown desc = read /srv/node/sdd/User_10_124.dat: input/output error

```
and I should run the command again,
Why is this happening? Can I reduce the number that this occurs?

**Comment by chrislusf** [comment]
you can re-run the command.

**Comment by kaaaq** [comment]
> you can re-run the command.

But the number of errors are too much! How can I reduce this errors that occur?

**Comment by kaaaq** [comment]
> if lock is waiting, this means there is another processing has the lock.

Now I have problem with locking  and I can not lock the shell,
If someone forget to unlock the shell from his node and exit from it , it would be locked for ever (I think this is my problem)
If there was any solution to unlock the shell from master/leader node or even weed says that: shell locked by which node, we can solve the problem by unlocking from that specific node (the first solution is better, I mean the ability to unlock shell from leader in emergency sitioation )

**Comment by chrislusf** [comment]
Restarting the `weed shell` may also help.

If not, restart the masters. If that still not working, you can `weed scaffold -config=master` and set `adminScript` to empty, which removes all admin scripts, and then restart master.

**Comment by chrislusf** [comment]
could not reproduce.

Added code to show which server holds the lock.
