### ISSUE TITLE
the max length of a dat file 

### ISSUE THREAD

**Issue by garfield-su** [chrislusf/seaweedfs#1986]
the OffsetSize in the definition of the const 'NeedleMapEntrySize' is 4 byte( uint32, 4GB ), also the SizeSize in the definition of the const 'NeedleMapEntrySize' is 4 byte( uint32, 4GB ). so I think the max length of dat file is 8GB ( 4GB +4 GB ). is there another way to increase the max length of dat file?

**Comment by chrislusf** [comment]
you can use the large-volume version.
