### ISSUE TITLE
S3 Bucket TTL?

### ISSUE THREAD

**Issue by divanikus** [chrislusf/seaweedfs#1987]
Hi! I'm using volume TTL auto configured through `fs.configure`. It works pretty good, but one thing I've noticed is that corresponding s3 buckets aren't disappearing after TTL expiration even if all volumes are gone. Can we have a bucket level TTL too?

**Comment by chrislusf** [comment]
buckets are a bit different. It is better to leave it as as.

**Comment by ramonmpa** [comment]
Yes you can.

https://github.com/seaweedfs/seaweedfs/issues/1798#issuecomment-1275205573
