### ISSUE TITLE
Upload file fail via filer WebUI

### ISSUE THREAD

**Issue by avarpow** [chrislusf/seaweedfs#1988]
**Describe the bug**
When "window.location.href" is a directory and without ending of "/",upload file will get a reponse {"error":"update entry /xxx/yyy: existing /xxx/yyy is a directory"}

directory url like /xxx/yyy/  can be uploaded successfully
**Expected behavior**
File uploaded.

**Additional context**
https://github.com/chrislusf/seaweedfs/blob/c42b95c596f762dcca2bc9c7e7a918ab8ca8b206/weed/server/filer_ui/templates.go#L185

**Comment by chrislusf** [comment]
thanks! added a fix.
