### ISSUE TITLE
About  log level for V logs

### ISSUE THREAD

**Issue by redtomatoL** [chrislusf/seaweedfs#1989]
```
logging_options 

-v value
    	log level for V logs
```

what does 'V logs' mean. and What does "value" have. 
 I see the document through execute './weed -h' ,Can I find more detailed documentation by some command or in some place?

**Comment by chrislusf** [comment]
the value can be: 0,1,2,3,4

**Comment by redtomatoL** [comment]
0,1,2,3,4  mean what，0 - error ,1-info 2-debug  ?

**Comment by mirdhyn** [comment]
My understanding of it is that this is not so much about semantic of the log (error/info/debug) but more how much details you need/want.
0 will give you what you probably only need as a user, 4 will be to debug deep internal functions. All of the levels includes infos and errors.

**Comment by redtomatoL** [comment]
thank you
