### ISSUE TITLE
[shell] does not return to the terminal by timeout

### ISSUE THREAD

**Issue by stallion2303** [chrislusf/seaweedfs#1995]
**Describe the bug** 
- I run the command weed shell on a machine where master/filer is missing or make a mistake with the ports, then the terminal hangs
- If I interrupt the running with Ctrl + C, then it returns to the terminal, but the cursor is not displayed

**System Setup** 
- CentOS Linux release 7.9.2009
- GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)
- weed version 30GB 2.39 742ab1e linux amd64
-  run weed shell
master: localhost: 9333 filer: localhost: 8888

 **Expected behavior** 
- Completion of the command by timeout in the absence of a connection to master/filer
- If I interrupt forcibly, then display the cursor.

**Comment by thaines** [comment]
I've had this happen to me - terminal gets left in raw mode, where characters aren't echoed back to the screen by default. You can still enter commands, so it's easy to fix by typing "stty sane" and hitting enter. The proper fix is to add a handler in the weed shell to ensure it always reverts to the line discipline from when it was run on exiting.
