### ISSUE TITLE
[export] huge error output for non-existent volumeId

### ISSUE THREAD

**Issue by stallion2303** [chrislusf/seaweedfs#1999]
**Screenshots**
<img width="1442" alt="Screenshot 2021-04-14 at 18 22 40" src="https://user-images.githubusercontent.com/9688322/114702666-8f2c7f00-9d4e-11eb-94e0-dccba0df3605.png">

**Comment by chrislusf** [comment]
what is the bug about?

**Comment by stallion2303** [comment]
This suggestion
Why not just show the error **Export Volume File [ERROR] failed to load volume 1: volume data file /tmp/1.dat does not exist**

**Comment by stallion2303** [comment]
thanks
