### ISSUE TITLE
kubernetes service and replicacation yaml / ui / elastic

### ISSUE THREAD

**Issue by lucmichalski** [chrislusf/seaweedfs#200]
Hi,

It would be great to have it deployable in Kubernetes, would make it really easy to use.

Is there any UI created to navigate through files like galeries of pictures ?
Is there a plugin that allows to create an index of all files into elasticsearch ?

Cheers,
Luc Michalski

**Comment by chrislusf** [comment]
It should be easy already. Kubernetes may make it easier, but not knowing much about it. Help needed.

No and No. These seems nice tools that can built on top of SeaweedFS.
