### ISSUE TITLE
Too many errors in postgresql log when uploading files with S3

### ISSUE THREAD

**Issue by Aytuar** [chrislusf/seaweedfs#2000]
**Describe the bug**
Too many errors in postgresql log when uploading files with S3 like these.
```
STATEMENT:  INSERT INTO "backetname" (dirhash,name,directory,meta) VALUES($1,$2,$3,$4)
ERROR:  duplicate key value violates unique constraint "backetname_pkey"
```

**System Setup**
- OS version - CentOS 7.6.1810
- output of `weed version` - 30GB 2.39 742ab1e linux amd64
- PostgreSQL - 9.6.20

filer_peers  ['10.11.0.1','10.10.0.1','10.11.0.2','10.10.0.2']

Filers in DC2
10.11.0.1
10.11.0.2
connect to server postgres DB2

Filers in DC1
10.10.0.1
10.10.0.2
connect to server postgres DB1

replication mode - 101
chunk size - 4MB

 ```
[filer.options]
recursive_delete = false
buckets_folder = "/buckets"

[postgres2]
enabled = true
createTable = """
  CREATE TABLE IF NOT EXISTS "%s" (
    dirhash   BIGINT,
    name      VARCHAR(65535),
    directory VARCHAR(65535),
    meta      bytea,
    PRIMARY KEY (dirhash, name)
  );
"""
```

**Expected behavior**
no errors

**Additional context**
Index recreation didn't help.

**Comment by chrislusf** [comment]
Please use the newer version to "weed scaffold"
