### ISSUE TITLE
Possible data loss on migration between tiers.

### ISSUE THREAD

**Issue by divanikus** [chrislusf/seaweedfs#2001]
**Describe the bug**
While playing with migrations I had several abrupt terminations of the migrations process because of volume servers' timeouts. Seems like at least a couple of times the volume was actually copied to a new tier, but because of the terminated migration, originals where left intact on the previous tier. After several reboots of the volume servers, some of my volumes eventually had 3 replicas, instead of 2 as of 010 policy. When I tried to do a migration next time, I got this:

```
moving volume 6384 from 192.168.65.59:8080 to 192.168.65.57:8080 with disk type hdd ...
markVolumeReadonly 6384 on 192.168.65.63:8080 ...
markVolumeReadonly 6384 on 192.168.65.62:8080 ...
markVolumeReadonly 6384 on 192.168.65.59:8080 ...
2021/04/14 01:51:58 copying volume 6384 from 192.168.65.59:8080 to 192.168.65.57:8080
2021/04/14 01:53:00 tailing volume 6384 from 192.168.65.59:8080 to 192.168.65.57:8080
2021/04/14 01:53:12 deleting volume 6384 from 192.168.65.59:8080
2021/04/14 01:53:13 moved volume 6384 from 192.168.65.59:8080 to 192.168.65.57:8080
```

The problem is, `192.168.65.59` and `192.168.65.57` are HDD tier servers, while `192.168.65.63` and `192.168.65.62` are from SSD tier. The end result is that volume 6384 was just deleted from everywhere, without any single copy left!

**System Setup**
- OS version: Debian 10.9
- output of `weed version`: version 30GB 2.39 742ab1e linux amd64
- if using filer, show the content of `filer.toml`
```
[leveldb2]
# local on disk, mostly for simple single-machine setup, fairly scalable
# faster than previous leveldb, recommended.
enabled = true
dir = "/var/lib/weed/filer"                                       # directory to store level db files
```

**Comment by chrislusf** [comment]
what was the command? `volume.tier.move -fromDiskType=hdd -toDiskType=hdd`?

**Comment by divanikus** [comment]
No, command always was like that
```
volume.tier.move -collection=#{bucket} -quietFor=1s -fullPercent=0.000001 -fromDiskType=ssd -toDiskType=hdd -force
```
