### ISSUE TITLE
Problem with clearing the ".upload " metadata in the postgres database when using filer metadata replication

### ISSUE THREAD

**Issue by AlekseyFicht** [chrislusf/seaweedfs#2006]
I also noticed that the other FILER does not delete data from the temporary directory ".uploads". This directory is created when downloading files in parts, and after the file is fully loaded, it is deleted.

Check out the screenshots from DBeaver, please.
Filer 1.

![Filer1_meta_10 10 10 148](https://user-images.githubusercontent.com/49243562/113541510-33eae600-9604-11eb-8185-2d960a8cace5.png)

Filer2.
![Filer2_meta_10 11 10 76](https://user-images.githubusercontent.com/49243562/113541516-364d4000-9604-11eb-9acb-93effe1da5e6.png)

Is this an error or normal behavior?
I would like the metadata databases to be the same.

_Originally posted by @AlekseyFicht in https://github.com/chrislusf/seaweedfs/issues/1957#issuecomment-813200963_

**Comment by AlekseyFicht** [comment]
version 30GB 2.39 742ab1e linux amd64

```
####################################################
# Customizable filer server options
####################################################
[filer.options]
# with http DELETE, by default the filer would check whether a folder is empty.
# recursive_delete will delete all sub folders and files, similar to "rm -Rf"
recursive_delete = false
# directories under this folder will be automatically creating a separate bucket
buckets_folder = "/buckets"

####################################################
# The following are filer store options
####################################################






[postgres2]
enabled = true
createTable = """
  CREATE TABLE IF NOT EXISTS "%s" (
    dirhash   BIGINT, 
    name      VARCHAR(65535), 
    directory VARCHAR(65535), 
    meta      bytea, 
    PRIMARY KEY (dirhash, name)
  );
"""
hostname = "10.10.86.105"
port = 5432
username = "seaweedfs"
password = "password"
database = "seaweedfs"          # create or use an existing database
schema = ""
sslmode = "disable"
connection_max_idle = 100
connection_max_open = 100
connection_max_lifetime_seconds = 0
# if insert/upsert failing, you can disable upsert or update query syntax to match your RDBMS syntax:
enableUpsert = true
upsertQuery = """INSERT INTO "%[1]s" (dirhash,name,directory,meta) VALUES($1,$2,$3,$4) ON CONFLICT (dirhash,name) DO UPDATE SET meta = EXCLUDED.meta WHERE "%[1]s".meta != EXCLUDED.meta"""
```

**Comment by AlekseyFicht** [comment]
Please add synchronization of the "uploads" folder

**Comment by AlekseyFicht** [comment]
Hi, @chrislusf 

I tried the "s3.clean.uploads" command, but it didn't help me.
In the logs, I saw that the function [https://github.com/chrislusf/seaweedfs/blob/master/weed/s3api/filer_util.go#L56-L74](doDeleteEntry) performs cleaning. 
Could you add this step to meta agregator or maybe there are other options to clean up dirty data in another filer database

**Comment by chrislusf** [comment]
same as #1957

**Comment by AlekseyFicht** [comment]
Thank you, Chris.
