### ISSUE TITLE
Etag from POST does not match Etag from GET in volume server

### ISSUE THREAD

**Issue by jameshartig** [chrislusf/seaweedfs#2007]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs
Report issues here. Ask questions here https://stackoverflow.com/questions/tagged/seaweedfs
Please ask questions in https://github.com/chrislusf/seaweedfs/discussions

example of a good issue report:
https://github.com/chrislusf/seaweedfs/issues/1005
example of a bad issue report:
https://github.com/chrislusf/seaweedfs/issues/1008

**Describe the bug**
https://github.com/chrislusf/seaweedfs/pull/1508 changed the Etag format in 1 spot but missed others. Anywhere that's still using `needle.Etag` is going to return the wrong string now.

GET to volume store
```
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Disposition: inline; filename="13,1483e14f70a4"
Content-Length: 1278604
Content-Type: text/csv
Etag: "b8e80476"
Last-Modified: Fri, 16 Apr 2021 16:14:05 GMT
Server: SeaweedFS Volume 30GB 2.31
Date: Fri, 16 Apr 2021 16:56:34 GMT
```

POST to volume store
```
HTTP/1.1 201 Created
Content-Md5: 49ftfAZJNSDDLWrBMuCj6g==
Content-Type: application/json
Etag: "e3d7ed7c06493520c32d6ac132e0a3ea"
Server: SeaweedFS Volume 30GB 2.31
Date: Fri, 16 Apr 2021 16:56:12 GMT
Content-Length: 101
```

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount": weed server
- OS version: CentOS 7
- output of `weed version`: version 30GB 2.31  linux amd64
- if using filer, show the content of `filer.toml`

**Expected behavior**
I expect the Etag headers to always match for the same file. This is necessary for us to ensure that a file being replicated was successfully replicated.

**Screenshots**

**Additional context**

**Comment by chrislusf** [comment]
@kmlebedev we can revert #1508 ? 

The volume servers do not store MD5. So the GET requests can not quickly calculate the MD5.

**Comment by kmlebedev** [comment]
> @kmlebedev we can revert #1508 ?
> 
> The volume servers do not store MD5. So the GET requests can not quickly calculate the MD5.

Let's leave it as it is for S3, but change it as it was before for the filler?
S3 seems to transmit its headers and you can look at them

**Comment by jameshartig** [comment]
> @kmlebedev we can revert #1508 ?

If its coming from S3 then add some conditional header or URL param that would change the format of the etag in the response for that request only. Is that doable?

**Comment by chrislusf** [comment]
A needle was using a 4-byte `n.Checksum` as its Etag(). It can not hold MD5.

So need to move the MD5 logic out of volume servers.

**Comment by kmlebedev** [comment]
Rf

> > @kmlebedev we can revert #1508 ?
> 
> If its coming from S3 then add some conditional header or URL param that would change the format of the etag in the response for that request only. Is that doable?

The original problem seems to be that the POST and GET request gives different Etag.
f we use longer "Etag" from POST query will it be ok?

**Comment by jameshartig** [comment]
The POST response includes the MD5 in the `Content-Md5` header. Can the s3 API handler look at that instead and return that as the etag rather than using the actual etag header?

**Comment by kmlebedev** [comment]
> The POST response from the volume server includes the MD5 in the `Content-Md5` header. Can the s3 API handler look at that instead and return that as the etag rather than using the actual etag header?

Yes, probably the volume server does not know anything about md5, since it is stored in the filer, but it is needed in the volume response, since it needs to be saved in the meta

**Comment by kmlebedev** [comment]
@chrislusf I have not found how to put md5 in the meta fileChunk Etag
https://github.com/chrislusf/seaweedfs/blob/master/weed/pb/filer_pb/filer.pb.go#L514

**Comment by chrislusf** [comment]
the chunk does not have md5. The file attribute has : https://github.com/chrislusf/seaweedfs/blob/master/weed/pb/filer_pb/filer.pb.go#L760

**Comment by kmlebedev** [comment]
> the chunk does not have md5. The file attribute has : https://github.com/chrislusf/seaweedfs/blob/master/weed/pb/filer_pb/filer.pb.go#L760
I how, but this function
https://github.com/chrislusf/seaweedfs/blob/c42b95c596f762dcca2bc9c7e7a918ab8ca8b206/weed/filer/filechunks.go#L37
for single file return ETag and for multichunk file return md5 at Etags chunks.
And this need to put md5 form volume server to etag field of FileChunk.
