### ISSUE TITLE
Weed cluster crashes because of out of memory

### ISSUE THREAD

**Issue by kaaaq** [chrislusf/seaweedfs#2014]
Hi,
l test my weed cluster with getting objects of it without any cache server in front of it, very soon all volume servers crashes and didn't came up , when I read journal log it was written weed volumes killed because of out of memory,
Weed would bring object for reading in memory and after reading it will remove it from ram?
Is there any way to tell weed read object from disk directly and don't bring files into memory? because without cache I need huge amount of memory for my weed cluster ...

**Comment by chrislusf** [comment]
how were the objects uploaded? how large are the objects? how many concurrent read requests?

**Comment by kaaaq** [comment]
> how were the objects uploaded? how large are the objects? how many concurrent read requests?
It is a test cluster and just for 30 seconds I put it under a little bit of my real load:
![image](https://user-images.githubusercontent.com/43205944/115351477-882cc300-a1cb-11eb-9fb4-47f65398b72f.png)
Get: 100
Post: 200

this is the latency at that moment, it goes high:
![image](https://user-images.githubusercontent.com/43205944/115351675-b9a58e80-a1cb-11eb-972f-6c37196d7108.png)

my object size are between 0 - 50 MB 

I upload objects via curl (using php library)

**Comment by chrislusf** [comment]
you can use `weed upload -maxMB=1` to upload the data in chunks, or use filer to upload and read the files.

**Comment by kaaaq** [comment]
> you can use `weed upload -maxMB=1` to upload the data in chunks, or use filer to upload and read the files.

@chrislusf 

there is no difference between 1MB chunk and 50 MB because my concurrent read in production is too high and can filled the memory again
Can I tell weed don't put objects in memory and read from disk?

**Comment by chrislusf** [comment]
can not.
