### ISSUE TITLE
Best practice for multiple filers FUSE mount

### ISSUE THREAD

**Issue by ysyyork** [chrislusf/seaweedfs#2015]
what's the best practice to make FUSE mount robust in multiple filers environment? For example, if I have 3 filer servers. Is it possible to specify these peers while I do `weed mount` so that if filer 1 is down, the mount will automatically redirect requests to filer 2 and 3. I only see options to specify peers while booting up filers here: https://github.com/chrislusf/seaweedfs/wiki/FUSE-Mount  but I don't know how to do the above with `weed mount`

**Comment by stallion2303** [comment]
use VRRP for example
usage: `weed mount -filer=vip:8888 ...`

**Comment by ysyyork** [comment]
> use VRRP for example
> usage: `weed mount -filer=vip:8888 ...`

sorry I'm not very clear. do you mind explaining a little more? how to set up VRRP?

**Comment by ysyyork** [comment]
NVM VRRP seems something not related to Seaweed. I'll figure out

**Comment by jvinolas** [comment]
Could it be done with haproxy in front of filers? It seems a more feasible way of doing it as it is able to handle grpc: https://www.haproxy.com/blog/haproxy-1-9-2-adds-grpc-support/

**Comment by tjohnston-cd** [comment]
Probably related to https://github.com/chrislusf/seaweedfs/issues/1531
