### ISSUE TITLE
filer read chunk 404 not found/416 Requested Range Not Satisfiable

### ISSUE THREAD

**Issue by summerisc** [chrislusf/seaweedfs#2036]
**Describe the bug**
on release 2.40, when I try to read some files/directories using filer it gives logs like:
```
E0428 18:23:52     1 stream.go:53] read chunk: http://10.244.1.174:8081/2,02c911cefafb32?readDeleted=true: 404 Not Found
2021/04/28 18:23:52 http: superfluous response.WriteHeader call from github.com/chrislusf/seaweedfs/weed/server.processRangeRequest (common.go:243)
E0428 18:23:52     1 stream.go:53] read chunk: http://10.244.1.174:8081/1,02c90f47658e58?readDeleted=true: 416 Requested Range Not Satisfiable
E0428 18:24:08     1 stream.go:53] read chunk: http://10.244.3.160:8083/7,097410ac8aebc5?readDeleted=true: 404 Not Found
2021/04/28 18:24:08 http: superfluous response.WriteHeader call from github.com/chrislusf/seaweedfs/weed/server.processRangeRequest (common.go:243)
E0428 18:24:08     1 stream.go:53] read chunk: http://10.244.3.160:8083/7,097410ac8aebc5?readDeleted=true: 404 Not Found
E0428 18:26:55     1 stream.go:53] read chunk: http://10.244.1.174:8081/2,02c911cefafb32?readDeleted=true: 404 Not Found
2021/04/28 18:26:55 http: superfluous response.WriteHeader call from github.com/chrislusf/seaweedfs/weed/server.processRangeRequest (common.go:243)
E0428 18:26:55     1 stream.go:53] read chunk: http://10.244.1.174:8081/1,02c90f47658e58?readDeleted=true: 416 Requested Range Not Satisfiable
E0428 18:27:59     1 stream.go:53] read chunk: http://10.244.3.160:8083/7,51c989500a56b8?readDeleted=true: 404 Not Found
2021/04/28 18:27:59 http: superfluous response.WriteHeader call from github.com/chrislusf/seaweedfs/weed/server.processRangeRequest (common.go:243)
E0428 18:27:59     1 stream.go:53] read chunk: http://10.244.3.160:8083/7,51c989500a56b8?readDeleted=true: 404 Not Found
```
it includes 404 for some files and 416 for some others. What could be this issue?

Besides that, some directories under the root path will disappear/show up when refresh the page, for example, this structure shows up first and after refresh it disappears, those folders disappearing are exactly the ones which has the 404 issue, so I think these two might be the same issue.
![Screen Shot 2021-04-28 at 2 43 26 PM](https://user-images.githubusercontent.com/21230663/116456284-18a07e80-a830-11eb-8ce4-d2c5f0da66f0.png)
![Screen Shot 2021-04-28 at 2 43 42 PM](https://user-images.githubusercontent.com/21230663/116456319-2229e680-a830-11eb-8dde-ad24e55905b0.png)

One thing might be helpful, if I kill one of the 4 filer pod(so that specific filer gets restarted), the missing directory shows up well and after some time, it just went missing and starts to show the above bahaviour.

**System Setup**
- output of `weed version` 
version 30GB 2.40 e983f91 linux amd64
- if using filer, show the content of `filer.toml` 
filer structure: 2 separate MySQL filer stores, each connects to 2 filers, so 4 filers in total, they all specified in `-peers`. paste the extraEnvVars from helm chart for reference:
```
filer1:
  extraEnvironmentVars:
    WEED_MYSQL_ENABLED: "true"
    WEED_MYSQL_HOSTNAME: "sw-database-1-10"
    WEED_MYSQL_PORT: "3306"
    WEED_MYSQL_DATABASE: "sw_database"
    WEED_MYSQL_CONNECTION_MAX_IDLE: "5"
    WEED_MYSQL_CONNECTION_MAX_OPEN: "75"
    # "refresh" connection every 10 minutes, eliminating mysql closing "old" connections
    WEED_MYSQL_CONNECTION_MAX_LIFETIME_SECONDS: "600"
    # enable usage of memsql as filer backend
    WEED_MYSQL_INTERPOLATEPARAMS: "true"
    WEED_LEVELDB2_ENABLED: "false"
    # with http DELETE, by default the filer would check whether a folder is empty.
    # recursive_delete will delete all sub folders and files, similar to "rm -Rf"
    WEED_FILER_OPTIONS_RECURSIVE_DELETE: "false"
    # directories under this folder will be automatically creating a separate bucket
    WEED_FILER_BUCKETS_FOLDER: "/buckets"

filer2:
  extraEnvironmentVars:
    WEED_MYSQL_ENABLED: "true"
    WEED_MYSQL_HOSTNAME: "sw-database"
    WEED_MYSQL_PORT: "3306"
    WEED_MYSQL_DATABASE: "sw_database"
    WEED_MYSQL_CONNECTION_MAX_IDLE: "5"
    WEED_MYSQL_CONNECTION_MAX_OPEN: "75"
    # "refresh" connection every 10 minutes, eliminating mysql closing "old" connections
    WEED_MYSQL_CONNECTION_MAX_LIFETIME_SECONDS: "600"
    # enable usage of memsql as filer backend
    WEED_MYSQL_INTERPOLATEPARAMS: "true"
    WEED_LEVELDB2_ENABLED: "false"
    # with http DELETE, by default the filer would check whether a folder is empty.
    # recursive_delete will delete all sub folders and files, similar to "rm -Rf"
    WEED_FILER_OPTIONS_RECURSIVE_DELETE: "false"
    # directories under this folder will be automatically creating a separate bucket
    WEED_FILER_BUCKETS_FOLDER: "/buckets"
```
**Expected behavior**
filer is able to list all the data and data can be downloaded with no issue.

**Comment by chrislusf** [comment]
the two mysql instances are out of sync.

this setup is not supported. Either having one filer store for each filer, or having one shared filer store for all filers.

**Comment by summerisc** [comment]
Thanks for pointing this out. I decrease the filer number to 2, so 1 mysql filer store serves 1 filer but still got this issue. Directories will disappear. It is stable showing the right directory only when I bring it down to 1 filer store and 1 filer.

Meanwhile, the 404 for downloading some files also shows up even if I just use 1 filer store and 1 filer. So this might be something else?

**Comment by chrislusf** [comment]
Please make a reproducible case with some docker compose file and steps to reproduce.
