### ISSUE TITLE
Unexpected response to s3 GET call on non-existent bucket

### ISSUE THREAD

**Issue by nneul** [chrislusf/seaweedfs#2039]
**Describe the bug**

Running a "GET /nonexistent-bucket?acl" - which is what a number of libraries use for "does this bucket exist" call, returns a ListBucketResult. According to S3 api docs, it should return a 'AccessControlPolicy' or at least a 404 for the nonexistent resource. 

**System Setup**

docker run -p 8333:8333 chrislusf/seaweedfs server -s3

```
nneul@optic:~ $ curl http://localhost:8333/nonexistent-bucket?acl
<?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>nonexistent-bucket</Name><Prefix></Prefix><Marker></Marker><MaxKeys>10000</MaxKeys><IsTruncated>false</IsTruncated></ListBucketResult>
```

**Expected behavior**

AccessControlPolicy in response - even if it's a dummy/empty policy document, or a 404 or other error indicating it couldn't handle the request due to the bucket not being there.

**Comment by nneul** [comment]
I think the underlying cause is that it's ignoring the ?acl - however, even with that, it shouldn't return the bucket in the ListBucketResult if it's not there.

**Comment by chrislusf** [comment]
should it return 501 "Not Implemented"?

**Comment by nneul** [comment]
I'm not sure... I think that's going to be driven more on interaction with how people are using it -- i.e. would it be better to have a stubbed/dummy response, or error out. I'm not an expert on the library/api usage in this case. 

I suspect that a dummy response is probably going to yield better application compatibility, but it also might open up a can of worms for how much you have to support to be "correct". 

In this specific case (one of my clients) - it's being used with the library to check 'does the bucket exist' to trigger other setup/creation/deletion/etc. -- so for it, having it semi-ignore the acl request and return the 404 would be better, but then it still leaves the question of what should be returned when the bucket does exist.

**Comment by Dougems** [comment]
I'd suggest since the resource specified in the path of the GET request does not exist that a 404 response code accompanied by a NoSuchBucket error code in the response body would achieve the behavior most consistent with the S3 protocol.

In the event that the resource does exist, then at that point any parameters/attributes present in the request (like acl) which are unsupported could produce the 501 code.

**Comment by chrislusf** [comment]
Added a fix to return 404 if bucket does not exist.
