### ISSUE TITLE
build failed for 32 bit arch using Go 1.5.1 due to an upstream bug

### ISSUE THREAD

**Issue by craveica** [chrislusf/seaweedfs#204]
Using Go 1.5.1 the build will fail for 32 bit arch due to an upstream bug. See more https://github.com/disintegration/imaging/issues/33

Until the bug is fixed upstream, compile it using Go 1.4.x.

**Comment by chrislusf** [comment]
Thanks for reporting this!

**Comment by craveica** [comment]
Fixed upstream.
