### ISSUE TITLE
W0502: failed to write to local disk: volume 174 is read only

### ISSUE THREAD

**Issue by Suika** [chrislusf/seaweedfs#2040]
**Describe the bug**
I was writing data via filer.copy to seaweed and it suddenly errored out like this:
```
W0502 05:08:01 13262 upload_content.go:102] uploading to http://172.27.0.7:8080/174,062d9796ff8a2207: unmarshalled error http://172.27.0.7:8080/174,062d9796ff8a2207: failed to write to local disk: volume 174 is read only
W0502 05:08:01 13262 upload_content.go:102] uploading to http://172.27.0.7:8080/174,062d979d7e510d7b: unmarshalled error http://172.27.0.7:8080/174,062d979d7e510d7b: failed to write to local disk: volume 174 is read only
W0502 05:08:01 13262 upload_content.go:102] uploading to http://172.27.0.7:8080/174,062d978fa4738ca9: unmarshalled error http://172.27.0.7:8080/174,062d978fa4738ca9: failed to write to local disk: volume 174 is read only
...
copy file error: upload data 531a8f351f18b11bf66b3e0073710618d24c27be82826b7baff9f5acb1e2f35c.jpg to http://172.27.0.7:8080/174,062d979e5d0bc024: unmarshalled error http://172.27.0.7:8080/174,062d979e5d0bc024: failed to write to local disk: volume 174 is read only
copy file error: upload data 531a40d12b36d56a06129ede415a2f95a73f7e99b43359c5e24db66742b1ec54.jpg to http://172.27.0.7:8080/174,062d979d7e510d7b: unmarshalled error http://172.27.0.7:8080/174,062d979d7e510d7b: failed to write to local disk: volume 174 is read only
...
```
It seems that while filer.copy was writing to the volume, it has passed the threshold on 1% free space and turned the whole volume server to read only.
I also see that the volume I was writing to is only 155.4/196GB full. Which pretty much tells me that seaweed/filer.copy can't handle a volume server turning suddenly ready only.

**System Setup**
- Seed Docker setup in #1594 but with newer seaweed version
- Debian 9
- `version 8000GB 2.39 something linux amd64` < I updated to 2.43, but it was running on 2.39 when it happened
- default `filer.toml`

**Expected behavior**
When a volume(server) turns read only there should be a retry or a message that will instruct filer.copy or other applications to retry.
I would say, have it redirect the data to a new volume but that would mess with the volume,key-cookie that was already returned and maybe recorded by another application.
So maybe make it work with weed own tools.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/2320837/116812531-b51f9500-ab3e-11eb-8927-22c9e99af615.png)

**Additional context**
I know that master provides a volume and key to which seawed hast to write to, but when something like that happens, it would be nice for filer.copy or even seaweed itself to find a way to write to a different location without erroring out.

**Comment by Suika** [comment]
Ok, here is another one. It seems seaweed can't comprehend when a volume was created using `-volumePreallocate`.
Say I have 8TB drive, I have a lot of volumes and I still have 220GB of free space left, which is >1% of free storage.
THEN seaweed goes and sees, hey my configured volume size is 196G so I actually fit into that volume server.
And then seaweed created the volume in that volume server using `-volumePreallocate`, wich naturally will preallocate the storage, pushing free space to ~20GB and instantly sliding into <1% free space.
When that happened, seaweed will lock the whole volume, even though the space for writing is there, it was simply preallocated and the logic doesn't consider this.

**Comment by chrislusf** [comment]
Useing the `-minFreeSpace=1GiB` should resolve this.

**Comment by chrislusf** [comment]
If no more volumes can be created, the compaction would not work since it will need to copy existing non-deleted data to a new volume.
