### ISSUE TITLE
Very slow speed of writing files to storage

### ISSUE THREAD

**Issue by vankosa** [chrislusf/seaweedfs#2042]
We have already opened a ticket https://github.com/chrislusf/seaweedfs/issues/1977, but have not received any recommendations on setting up seaweedfs or setting up the OS for this.
In this ticket I will write in more detail what is and what you want to get.

Volume.server config:

2 servers:
n102: 48 cores, 512 gigabytes of RAM, 36 disks of 14 terabytes, paired in raid1 (18 arrays), 10 gigabits network
n103: 36 cores, 512 gigabytes of RAM, 36 disks of 14 terabytes, paired in raid1 (18 arrays), 10 gigabits network
swfs-master-3: virtual machine, 4 cores, 4 gigabytes of RAM, used only as a master.

Each array is one volume, the maximum number of volumeid is 12000. Each volumeid is 1 gigabyte

Everything is started using systemd commands
`ExecStart=/usr/local/bin/weed master -defaultReplication=010 -port=9333 -peers=n102.unim.internal:9333,n103.unim.internal:9333,swfs-master-3.unim.internal:9333 -volumeSizeLimitMB=1024 -ip=n102.unim.internal -metrics.address=n102.unim.internal:9091` for the master and
`ExecStart=/usr/local/bin/weed volume -dataCenter=netrack -rack=n102 -port=11002 -port.public=11002 -mserver=n102.unim.internal:9333,n103.unim.internal:9333,swfs-master-3.unim.internal:9333 -ip=n102.unim.internal -max=12000 -dir=/mnt/disk2/swfs` for volumes.

Currently, 155000 volumeid is used on each server with a replication factor of 010.

The storages are fully replicated (it was long and difficult, but we did it).

Problem:
Very slow speed of writing files to storage (used directly by seaweedfs api, example request - curl --location --request POST 'http://master.example.com:9333/submit' --from 'file = @ "filename.jpg "') at QPS, starting from ~ 1200-1500 requests per second.

If you turn off half (8-9) volumes on n103, then the write speed becomes acceptable.

What can be configured, modified so that there are no problems with the speed of writing and reading?

PS: If you need additional data - tell me, I will add

**Comment by qieqieplus** [comment]
Have you tried setting a larger volumeSizeLimitMB?
If you are benchmarking, master volume assignment could be the bottleneck for two reasons:
1. Assign operation in master is blocking, sometimes it is very time consuming. A small size volume like 1GB could be filled up in a few seconds (in a benchmark scene) and all write requests  have to wait for another few seconds to be handled. 

2. Many internal operation in master is O(n), n stands for number of volumes you have.

**Comment by qieqieplus** [comment]
By the way, I implement an ahead of time volume assign in my fork to avoid the previous issue.
I'll send a PR if the community is interested. @chrislusf

**Comment by chrislusf** [comment]
> By the way, I implement an ahead of time volume assign in my fork to avoid the previous issue.
> I'll send a PR if the community is interested. @chrislusf 

Would like to see how you avoid the problem that a volume may be filled up.

**Comment by vankosa** [comment]
> Have you tried setting a larger volumeSizeLimitMB?
> If you are benchmarking, master volume assignment could be the bottleneck for two reasons:
> 
> 1. Assign operation in master is blocking, sometimes it is very time consuming. A small size volume like 1GB could be filled up in a few seconds (in a benchmark scene) and all write requests  have to wait for another few seconds to be handled.
> 2. Many internal operation in master is O(n), n stands for number of volumes you have.

Is there a way to combine volumes in this case?
We have 75% busy in each volumeserver and I do not fully understand how we can increase the volume size limit without any problems

**Comment by chrislusf** [comment]
> Is there a way to combine volumes in this case?

Can not.

**Comment by chrislusf** [comment]
closing if not more updates here.
