### ISSUE TITLE
Hex dump for first 5 bytes: 485454502f

### ISSUE THREAD

**Issue by samfces** [chrislusf/seaweedfs#2043]
**Describe the bug**
I am getting an error when trying to connect a seaweedfs java client to the seaweedfs filer, I get the following error: 
`First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f`

**System Setup**
- weed master: https://paste.minebox.es/vorivajoho.ini
- weed volume 1: https://paste.minebox.es/kalojohiro.ini
- weed volume 2: https://paste.minebox.es/irewuhotot.ini
- weed filer:  weed filer -port=18888
- weed mount: weed mount -filer=IP:18888 -dir=./mount
- OS version: Ubuntu 20.10
- weed version: 30GB 2.43 e24ba2aa linux amd64
- filer.toml: https://paste.minebox.es/apuhevugap.ini

**Expected behavior**
It is to be expected that the client will be able to connect without any problems.

**Additional context**
Client connector:

        filerClient = new FilerClient("IP", 18888);

        List<FilerProto.Entry> entries = filerClient.listEntries("/");

        for (FilerProto.Entry entry : entries) {
            System.out.println(entry.toString());
        }

**Comment by chrislusf** [comment]
use grpcPort https://github.com/chrislusf/seaweedfs/blob/master/other/java/client/src/main/java/seaweedfs/client/FilerClient.java#L17

for your case, it is `18888+10000=28888`
