### ISSUE TITLE
HEAD memory usage for large files is insane

### ISSUE THREAD

**Issue by qieqieplus** [chrislusf/seaweedfs#2046]
**Describe the bug**

Currently I'm using [minio/mc](https://github.com/minio/mc) as command shell, when I'm downloading large files from server, like

`mc cp s3/mybucket/large10g.txt 10g.txt`

mc will send HEAD request first to s3 api, then proxy to filer
the memory usage is about 2 times of the file size,
for example, a 10 GB file will cost like 20GB memory.

After debug for a while, it appears to me that has something to do with #1913

**Comment by chrislusf** [comment]
Reverted #1903
