### ISSUE TITLE
[BUG] - High Cpu utilization- compactionMBps Not working for disk read, it just limit disk write 

### ISSUE THREAD

**Issue by kaaaq** [chrislusf/seaweedfs#2048]
Hi, I have adjusted "-compactionMBps=100" in the configuration file of weed volume servers but when I run "ec.encode" command in weed shell, after encoding , when it wanted to spread .ec files to servers in the proccess of "parallelCopyEcShardsFromSource", it skiped my configs and I had a lot of disk IO wait on the volume server (100% cpu)
And this is Not because of disk write, this is because of disk read!:

![weed-iowait](https://user-images.githubusercontent.com/43205944/117266383-75241f00-ae6a-11eb-92eb-707dc41ace6b.png)

I think the config just would control disk write Not disk read, It can be a option not to send files parallel

```
>weed version
version 8000GB 2.40 e983f91 linux amd64
```

**Comment by kaaaq** [comment]
Hi,
I have this issue on weed version 2.63(version 8000GB 2.63 48f88f976879401009558ace060557d09279e1be linux amd64)
After ec shards created and weed wants to send them to other node, for reading ec chunks, it consumes 100% cpu even though I defined "-compactionMBps=100" in all weed servers, it's so dangerous, this limitation should work even when weed wants to read ec chunck from disk and send them to another servers not using all resource of system just the amount that I defined.

![image](https://user-images.githubusercontent.com/43205944/130319850-6f07436f-35c7-4578-b775-b9a462aa83f0.png)

**Comment by chrislusf** [comment]
Did you use the option `ec.encode -parallelCopy=false` added in 76c48ff ?

**Comment by kaaaq** [comment]
> Did you use the option `ec.encode -parallelCopy=false` added in [76c48ff](https://github.com/chrislusf/seaweedfs/commit/76c48ffe27e339145f140301f9a865bec40b515c) ?

@chrislusf 

No, but "parallelCopy=false" means don't copy shards in parallel , and it has nothing to do with disk read 
But I will try this with "parallelCopy=false" option and inform you.
Thanks
