### ISSUE TITLE
[FUSE] fuse library diff

### ISSUE THREAD

**Issue by fly3366** [chrislusf/seaweedfs#2061]
I checked tree fuse library from GitHub :

 seaweedfs/fuse (this project)
 hanwen/go-fuse
 jacobsa/fuse,

And I have use jacobsa/fuse get best performance.
Is there any blog for seaweedfs/fuse's trick? Any plan for try ANOTHER fuse library?

**Comment by chrislusf** [comment]
seaweedfs/fuse is from bazil.org/fuse. Just fix bugs if any.
