### ISSUE TITLE
Continuation of #2056 and #2062

### ISSUE THREAD

**Issue by Suika** [chrislusf/seaweedfs#2066]
**Describe the bug**
Continuation of Issue #2056 and #2062. #2062 is no longer happening and no extra volumes are created. So that issue is technically fixed.
Still errors out on filer upload.

[filer.log](https://github.com/chrislusf/seaweedfs/files/6466993/filer.log)
[filer-copy.log](https://github.com/chrislusf/seaweedfs/files/6466994/filer-copy.log)
[master.log](https://github.com/chrislusf/seaweedfs/files/6466995/master.log)
[volume.log](https://github.com/chrislusf/seaweedfs/files/6466996/volume.log)

**Comment by chrislusf** [comment]
There have been several fixes related to this. 
Is it possible to confirm whether the errors still happen?

**Comment by Suika** [comment]
Will be hard, since the said system is no longer under such heavy load. Will have to be on lookout for this type of problem.
