### ISSUE TITLE
how to config ? the file size always increase?

### ISSUE THREAD

**Issue by shenlanzifa** [chrislusf/seaweedfs#207]
i have two questions:
one is how to config the seaweedfs to make it work better.
another is when i have deleted all the files, the seaweedfs‘s data do not decrease, that's why?

**Comment by seifer** [comment]
I think, because files won't be remove so far you don't start 'compact' process.

**Comment by chrislusf** [comment]
Each setup can be different depending on the business requirements. Here are something you can look at: https://github.com/chrislusf/seaweedfs/wiki/Optimization

As @seifer mentioned, the compaction will happen when the garbage is more than the threshhold, default to 30%, and checked every 15 minutes. Or you can force it to garbage collect via API. https://github.com/chrislusf/seaweedfs/wiki/API#force-garbage-collection
