### ISSUE TITLE
Can`t Log In Docker Container !!

### ISSUE THREAD

**Issue by homayoonsadeghiarkami** [chrislusf/seaweedfs#2071]
Hi @chrislusf I am trying to log in a directory beside of stderr in my containers but some how it can not generate log files in that directory in my containers, I wonder why would this happen? the code in entrypoint.sh is like below:
```
'master')
  	ARGS="-mdir=/data -volumePreallocate=false -volumeSizeLimitMB=512"
  	shift
  	exec /usr/bin/weed -v=4 -logdir=/var/log/seaweedfs/master -alsologtostderr=true master $ARGS $@
	;;

  'volume')
  	ARGS="-dir=/data -max=0"
  	if isArgPassed "-max" "$@"; then
  	  ARGS="-dir=/data"
  	fi
  	shift
  	exec /usr/bin/weed -v=4 -logdir=/var/log/seaweedfs/volume -alsologtostderr=true volume $ARGS $@
	;;
```
I now I can work with docker logger drivers and somehow manage it but what is the problem in this way?

**Comment by chrislusf** [comment]
I suppose you need to create those directories first.

**Comment by homayoonsadeghiarkami** [comment]
thanks it worked very well 👍👍
