### ISSUE TITLE
s3 virtual style addressing

### ISSUE THREAD

**Issue by t3ndai** [chrislusf/seaweedfs#2076]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs
Report issues here. Ask questions here https://stackoverflow.com/questions/tagged/seaweedfs
Please ask questions in https://github.com/chrislusf/seaweedfs/discussions

**Describe the bug**

AWS sdk's e.g JS v3 have transitioned to virtual style addressing for buckets.[0] Which means 
using an s3 sdk with seaweedfs will result in files not being saved

```js

 Error: getaddrinfo ENOTFOUND rewose.localhost
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26) {
0|rewose  |   errno: -3008,
0|rewose  |   code: 'ENOTFOUND',
0|rewose  |   syscall: 'getaddrinfo',
0|rewose  |   hostname: 'rewose.localhost',
0|rewose  |   '$metadata': { attempts: 1, totalRetryDelay: 0 }
0|rewose  | }

````

[0]: https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html

**System Setup**

Debian 10
latest weed release 
weed server -s3 -dir="data"

I already created a bucket using the aws cli tool

**Expected behavior**

Not get an error

**Comment by chrislusf** [comment]
```
weed server -h
  ...
  -s3.domainName string
    	suffix of the host name in comma separated list, {bucket}.{domainName}

```
