### ISSUE TITLE
Upload to s3 filer fails with "corrupted on transfer: sizes differ"

### ISSUE THREAD

**Issue by AlexMikhalev** [chrislusf/seaweedfs#2077]
I have a setup with master started:
```
~/go/bin/weed server -filer -s3 -s3.config=s3_config.json -ip=rpi4node3 -volume.max=0,0 -master.volumeSizeLimitMB=1024 -volume.port=8088 -dir=/mnt/usbslow/weed,/mnt/usbfast/weed/ -master.dir=/mnt/usbfast/weed/master
```
which works well except for two large files in my backup test:
```
2021-05-23 00:02:52 ERROR : conceptnet5/data/psql/edges_gin.shuf.csv: corrupted on transfer: sizes differ 14163691260 vs 5242880000
2021-05-23 00:02:52 INFO  : conceptnet5/data/psql/edges_gin.shuf.csv: Removing failed copy
2021-05-23 00:04:16 ERROR : conceptnet5/data/psql/edges.csv: corrupted on transfer: sizes differ 21863832557 vs 5242880000
2021-05-23 00:04:16 INFO  : conceptnet5/data/psql/edges.csv: Removing failed copy
2021-05-23 00:04:25 ERROR : Attempt 3/3 failed with 2 errors and: corrupted on transfer: sizes differ 21863832557 vs 5242880000
Transferred:      100.660G / 100.660 GBytes, 100%, 49.633 MBytes/s, ETA 0s
Errors:                 2 (retrying may help)
Checks:            700197 / 700197, 100%
Elapsed time:     34m36.9s
<6>INFO  : 
Transferred:   	  100.660G / 100.660 GBytes, 100%, 49.633 MBytes/s, ETA 0s
Errors:                 2 (retrying may help)
Checks:            700197 / 700197, 100%
Elapsed time:     34m36.9s

```
My understanding filer should have chunked large files across multiple volumes but it's not happening or it's not able to retrieve them back on validation. 
```
filer.toml
[leveldb3]
# similar to leveldb2.
# each bucket has its own meta store.
enabled = true
dir = "/mnt/usbfast/weed/master/filerldb3"					# directory to store level db files
``
```
master.toml
[master.maintenance]
# periodically run these scripts are the same as running them from 'weed shell'
scripts = """
  lock
  ec.encode -fullPercent=95 -quietFor=1h
  ec.rebuild -force
  ec.balance -force
  volume.balance -force
  volume.fix.replication
  unlock
"""
```
weed shell
```
> fs.configure
{
  "locations": [
    {
      "locationPrefix": "/buckets/",
      "volumeGrowthCount": 1
    },
    {
      "locationPrefix": "/buckets/slowvolume",
      "volumeGrowthCount": 1
    }
  ]
}
```

Volumes started:
```
/go/bin/weed volume -mserver="rpi4node3:9333" -max=0,0 -port=8088 -disk=hdd,ssd -dir=/mnt/usbslow/weed,/mnt/usbfast/weed/
```
Weed version:
```
~/go/bin/weed version
version 30GB 2.48 2d0a0733 linux arm64

```
Backup command:
```
rclone --exclude-from filter.txt --check-first -P -u -v copy ~/py_code weed:alex_linux/py_code
```

There are no errors in the logs on master or volume.

**Comment by chrislusf** [comment]
could you show the result of `echo "fs.meta.cat /buckets/conceptnet5/data/psql/edges.csv | weed shell`?

**Comment by chrislusf** [comment]
Increase the default value for `--s3-chunk-size` and `--s3-max-upload-parts` in rclone

**Comment by AlexMikhalev** [comment]
@chrislusf thank you, it worked with --s3-chunk-size=150M --s3-upload-concurrency=2 
For those who will have the same issue: Amazon s3 and others have a hard limit on 10000 chunks, my files were larger than the default chunk size x 10000.
