### ISSUE TITLE
deleteColletion useful for me, please

### ISSUE THREAD

**Issue by maggot611** [chrislusf/seaweedfs#208]
weed server not allow user specify their own key fully, since key consist of VolumeId, Fid and Cookie. So now I use filers+redis to upload and download files with filename without directory specified. Some file should be deleted for certain time. Without using TTL for volume, I prefer to use "collection" for file when upload:

``` shell
curl -F @myvideo.mkv   "http://localhost:8888/myvideo.mkv?collection=20151017"    
```
When I want to detele all the files uploaded 20151017, if has deleteColletion API, I can code below:

``` shell
curl  "http://localhost:8888/deleteColletion?collection=20151017"
```

Awesome, isn't it !

Maybe upload file with TTL can achieve my goal, but when I use 
``` shell
curl -F @myvideo.mkv "http://localhost:8888/myvideo.mkv?ttl=24h"
```
volume's modified time be updated endlessly, that wolume cannot be deleted. This puzzled me.

**Comment by chrislusf** [comment]
I enabled the collection deletion api here: https://github.com/chrislusf/seaweedfs/commit/5feae4f74c5b3cd82cb8ba3623883d06c003b24f

TTL implementation detail is here: https://github.com/chrislusf/seaweedfs/wiki/Store-file-with-a-Time-To-Live#implementation-details
