### ISSUE TITLE
Filer.backup does not work as expected

### ISSUE THREAD

**Issue by Stranger10110** [chrislusf/seaweedfs#2084]
I am trying to test a backup to local disk (both on Windows and Linux) of files that are stored with Filer (MySQL), but it doesn't seem to work properly - it just doesn't copy all the files, only specific files and folders, not even full sizes. Maybe it's just getting stuck for whatever reason?
I also tried to change the directory on Filer in replication.toml, but it does no effect.
It also makes two folders of different dates, but I've configured it to "is_incremental = false".

**System Setup**
Weed cluster is started with Docker compose ([Docker.zip](https://github.com/chrislusf/seaweedfs/files/6539293/Docker.zip); it contains filer.toml as well).

OS version:
- Windows 10 Pro 20H2 19042.985
- Linux mx 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux

Weed version:
- version 30GB 2.49 42fb03a windows amd64
- version 30GB 2.49 42fb03a linux amd64

FIler.backup start command: .\weed.exe filer.backup -filerProxy
Replication.toml: [replication(.toml).txt](https://github.com/chrislusf/seaweedfs/files/6539325/replication.toml.txt)

**Expected behavior**
A full copy of files stored with Filer on a local disk.

**Screenshots**
Filer
![image](https://user-images.githubusercontent.com/17049504/119495375-05b79600-bd6b-11eb-8124-c9ba3110f943.png)
![image](https://user-images.githubusercontent.com/17049504/119495436-149e4880-bd6b-11eb-843e-b161daf55197.png)
![image](https://user-images.githubusercontent.com/17049504/119495607-40213300-bd6b-11eb-8b7d-95344f34aa38.png)
![image](https://user-images.githubusercontent.com/17049504/119495679-50d1a900-bd6b-11eb-82d5-3d3dd8c7ab3e.png)
![image](https://user-images.githubusercontent.com/17049504/119495646-4a433180-bd6b-11eb-8cfe-e41270d528e6.png)

Windows backup
![image](https://user-images.githubusercontent.com/17049504/119496680-672c3480-bd6c-11eb-838c-cb50fe294259.png)
![image](https://user-images.githubusercontent.com/17049504/119496471-321fe200-bd6c-11eb-8fdc-3b4a324e4fed.png)
![image](https://user-images.githubusercontent.com/17049504/119496503-38ae5980-bd6c-11eb-9f14-a25a5854abb0.png)
![image](https://user-images.githubusercontent.com/17049504/119496530-3fd56780-bd6c-11eb-91c0-b4d3d1f268a2.png)
![image](https://user-images.githubusercontent.com/17049504/119496563-47950c00-bd6c-11eb-90b1-7ae249db9c59.png)
![image](https://user-images.githubusercontent.com/17049504/119496648-5f6c9000-bd6c-11eb-9357-a33eca5a581e.png)

Linux backup
Same picture as on Windows.

**Additional context**
File.backup output from Windows: [win filer.backup log.txt](https://github.com/chrislusf/seaweedfs/files/6539218/win.filer.backup.log.txt).
File.backup output from Linux: [linux filer.backup log.txt](https://github.com/chrislusf/seaweedfs/files/6539249/linux.filer.backup.log.txt).

**Comment by kmlebedev** [comment]
@Stranger10110 Check the filer.replicate parameter 

```
[source.filer]
  enabled = true
  grpcAddress = "192.168.0.244:18080"
  directory = "/buckets"

[sink.local]
  enabled = true
  directory = "/data"
```

**Comment by Stranger10110** [comment]
@kmlebedev My settings are:
[source.filer]
enabled = true
grpcAddress = "localhost:18888" # 192.168.0.244 == localhost
directory = "/"

[sink.local]
enabled = true
directory = "./backup" # local folder to download files to
is_incremental = false.

![image](https://user-images.githubusercontent.com/17049504/119505750-f25df800-bd75-11eb-90ee-9f086dcdcb1a.png)

I don't understand, what's wrong with them?

**Comment by chrislusf** [comment]
Thanks for the details! Could you please add `-v=4` to the command, i.e., `weed -v=4 filer.backup ...`, and show the logs?

**Comment by Stranger10110** [comment]
Here it is: [win filer.backup log 2.txt](https://github.com/chrislusf/seaweedfs/files/6542747/win.filer.backup.log.2.txt)

I've changed folder structure by uploading 2 new folders ("base_1" and "base_2") since last launch. There are some changes (it downloaded these 2 new folders and made more "date" folders), but it's still does not work as expected. I think it ignores "is_incremental = false" as well.
![image](https://user-images.githubusercontent.com/17049504/119578193-c0c04d80-bdc4-11eb-9f03-1f530ff80703.png)
![image](https://user-images.githubusercontent.com/17049504/119578267-e0f00c80-bdc4-11eb-8f96-873deaacc98d.png)

(I don't see missing files in v=4 logs either)

**Comment by chrislusf** [comment]
I added some fix for the is_incremental. Please use this to run https://github.com/chrislusf/seaweedfs/releases/dev

**Comment by Stranger10110** [comment]
Yes, it's not incremental now, but still missing some of the files.

When I've run it first time, files were same as before. But I've deleted them, run again, cancel it in the middle of the process (with CTRL+C) and every time now it's got "stuck" again and miss more of the files.

I think it downloads to the time when I hit CTRL+C and no more, but I'm not 100% sure. Maybe a bug with restarting backup from the last point of progress?

**Comment by chrislusf** [comment]
I fixed some obvious problems with the local sink, and updated the dev release. Please help to check again. If still problem, please attach filer.backup logs.

**Comment by Stranger10110** [comment]
Unfortunately, almost no changes for me.

First try : downloaded those 2 "new" folders only (in folder test2; there is no 'Meta_test2' folder anymore too).
![image](https://user-images.githubusercontent.com/17049504/119746489-40b7e780-be99-11eb-98ab-fd09dde97dec.png)
[win_filer.backup_log_3.txt](https://github.com/chrislusf/seaweedfs/files/6550258/win_filer.backup_log_3.txt)

Second try: uploaded a new file (verthash.dat), retried to make a backup, result - those 2 folders and new file only.
![image](https://user-images.githubusercontent.com/17049504/119746769-e5d2c000-be99-11eb-9d66-787093f391f8.png)
[win_filer.backup_log_4.txt](https://github.com/chrislusf/seaweedfs/files/6550259/win_filer.backup_log_4.txt)

So it downloads files from some point of time and nothing before that, as it literally says it in the log:
"I0527 03:08:13 16648 filer_backup.go:99] resuming from 2021-05-26 03:16:46.1899912 +0300 MSK"

It needs a way to make it start from the start, I think, like '-startFromBeginning" parameter maybe

**Comment by chrislusf** [comment]
See "weed filer.backup -h"

**Comment by Stranger10110** [comment]
Oh, you mean -timeAgo, my bad, I've overlooked it.

I've set it to 9999999h, it now downloads all of the files, besides "base_1/*.*" files and "base_2" folder, and it seems it starts downloading over in the infinite loop after getting an error (look at the last line).
![image](https://user-images.githubusercontent.com/17049504/119756323-0f94e280-beac-11eb-9f0d-9c90df245e27.png)
![image](https://user-images.githubusercontent.com/17049504/119756586-67334e00-beac-11eb-8e75-51f28d083421.png)

I can't capture all of the logs since there are too many of them and I can't make Windows capture log to a file. These logs on the screenshot I can capture because backup pauses at this moment for a few seconds

**Comment by Stranger10110** [comment]
Interestingly enough, but it have run successfully on WSL 2
![image](https://user-images.githubusercontent.com/17049504/119758252-e45fc280-beae-11eb-8397-8c1bfcecaf96.png)

**Comment by chrislusf** [comment]
what is the `replication.toml` file for windows?

**Comment by Stranger10110** [comment]
Same as before
[replication.toml.txt](https://github.com/chrislusf/seaweedfs/files/6551475/replication.toml.txt)

**Comment by chrislusf** [comment]
it showed some "D:/tests/..." folder in the log. Not sure how that happened.

**Comment by Stranger10110** [comment]
> ![image](https://user-images.githubusercontent.com/17049504/119756323-0f94e280-beac-11eb-9f0d-9c90df245e27.png)

You mean there? Yes, it's in the error message, there are

- "backup/test2/base_1" (aka normal backup relative folder path) + 
- "D:/tests/Lab_1" (aka real local folder path, from where those files were uploaded) +
- "Metr_1.odt" (aka filename)

That's a really strange error, I don't understand it either...

**Comment by chrislusf** [comment]
can you use `weed shell` to display the file tree via `fs.tree test2`?

**Comment by Stranger10110** [comment]
PS D:\Seaweed> .\weed shell
master: localhost:9333 filer: localhost:8888
\> fs.tree test2
test2
├──Office 2007.dat
├──Platform_designer_lab
│   ├──Platform_designer_lab.docx
│   ├──Platform_designer_lab.pdf
│   ├──Platform_designer_lab_2.docx
│   ├──Platform_designer_lab_dirty.docx
│   ├──Скрины
│   │   ├──IMG_20201110_220652.jpg
│   │   ├──opcodes — копия.PNG
│   │   ├──original_connections.PNG
│   │   ├──original_connections_2.PNG
│   │   ├──reg_memory.PNG
│   │   ├──regs.PNG
│   │   ├──rng — копия.PNG
│   │   ├──rng.PNG
│   │   ├──rng2 — копия.PNG
│   │   └──rng2.PNG
│   ├──заметки.txt
│   └──ссылки.txt
├──Platform_designer_lab (1).docx
├──Platform_designer_lab.docx
├──Platform_designer_lab.pdf
├──SOME01.wbfs
├──base_1
│   ├──Metr_1.odt
│   ├──Metr_1.pdf
│   ├──Test
│   │   └──измерения.ods
│   └──измерения.ods
├──base_2
│   ├──blank_praktika_uchebnaya_novyy.pdf
│   ├──blanky.odt
│   ├──blanky.pdf
│   ├──praktika.odt
│   ├──praktika.pdf
│   └──uchebnaya_otchet.pdf
├──server.docx
└──verthash.dat
6 directories, 33 files

**Comment by chrislusf** [comment]
> * "D:/tests/Lab_1" (real local folder path, from where those files were uploaded) +

Is it the original file location before uploading to the source filer? Or the `filer.backup` destination folder?

**Comment by chrislusf** [comment]
ok. not too many files. Can you run this `weed filer.meta.tail -timeAgo=9999h` and share the output?

**Comment by Stranger10110** [comment]
Here it is: [meta.txt](https://github.com/chrislusf/seaweedfs/files/6561099/meta.txt)

P.S.: I do just some tests right now, so I don't care about these files, if you want me to do something with them to investigate bugs, just let me know

**Comment by Stranger10110** [comment]
I think that it was a bug in my Python client

But then why did backup on WSL 2 finished successfully? Is it because `D:/tests/Lab_1/Metr_1.pdf` is a correct path on Linux?
> Interestingly enough, but it have run successfully on WSL 2 (Ubuntu)
> ![image](https://user-images.githubusercontent.com/17049504/119758252-e45fc280-beae-11eb-8397-8c1bfcecaf96.png)

**Comment by chrislusf** [comment]
share your python code? I want to see how to prevent the bug in the future.

**Comment by Stranger10110** [comment]
I think I've already fixed that bug.
But basically I'm uploading files by a PUT method to `http://_filer_host_/_path_to_the_file`, so I think I have accidentally sent the wrong path (with `D:/tests/Lab_1/` prefix)

**Comment by chrislusf** [comment]
Thanks! Added a fix for windows.
