### ISSUE TITLE
[master] accept4: too many open files; retrying in 1s

### ISSUE THREAD

**Issue by muqiu428** [chrislusf/seaweedfs#2087]
**Describe the bug**
Use Fuse  mode to mount six clients, and use vdbench tool to write data to the mount path. After writing for a period of time, the master reports the following error
        http: Accept error: accept tcp [::]:9333: accept4: too many open files; retrying in 1s

**Cluster description**
1、./weed master -ip=192.168.3.231 -port=9333 -mdir=/opt/seaweedfs/master -defaultReplication=001
2、./weed volume -dataCenter dc1 -rack rack1 -dir /data/seaweedfs/volume -ip 192.168.3.232 -port 8080 -ip.bind 192.168.3.232 -max 290 -mserver 192.168.3.231:9333 -publicUrl 192.168.3.232:8080
3、./weed filer -port=8888 -master=192.168.3.231:9333
     filer.toml   use redis cluster:
[redis_cluster2]
enabled = true
addresses = [
    "192.168.3.235:7001",
    "192.168.3.235:7002",
    "192.168.3.231:7003",
    "192.168.3.231:7004",
    "192.168.3.232:7005",
    "192.168.3.232:7006",
]
4 、./weed mount -filer=192.168.3.233:8888 -dir=/mnt/seaweedfs
5、./weed version
version 30GB 2.49 42fb03a linux amd64

**vdbench command**
   ./vdbench -f seaweedfs_test       #Loop this command，sleep 2m

seaweedfs_test  contents：

hd=default,vdbench=/opt/vdbench/,user=root,shell=ssh
hd=cStor_node1,system=192.168.3.242
hd=cStor_node2,system=192.168.3.243
hd=cStor_node3,system=192.168.3.244
hd=cStor_node4,system=192.168.3.245
hd=cStor_node6,system=192.168.3.247
hd=cStor_node7,system=192.168.3.249
fsd=cStor_node1,anchor=/mnt/seaweedfs/vd/cStor_node1/seaweedfs_1024k_64thread49/,depth=3,width=10,files=100,sizes=1024k,shared=yes
fsd=cStor_node2,anchor=/mnt/seaweedfs/vd/cStor_node2/seaweedfs_1024k_64thread49/,depth=3,width=10,files=100,sizes=1024k,shared=yes
fsd=cStor_node3,anchor=/mnt/seaweedfs/vd/cStor_node3/seaweedfs_1024k_64thread49/,depth=3,width=10,files=100,sizes=1024k,shared=yes
fsd=cStor_node4,anchor=/mnt/seaweedfs/vd/cStor_node4/seaweedfs_1024k_64thread49/,depth=3,width=10,files=100,sizes=1024k,shared=yes
fsd=cStor_node6,anchor=/mnt/seaweedfs/vd/cStor_node6/seaweedfs_1024k_64thread49/,depth=3,width=10,files=100,sizes=1024k,shared=yes
fsd=cStor_node7,anchor=/mnt/seaweedfs/vd/cStor_node7/seaweedfs_1024k_64thread49/,depth=3,width=10,files=100,sizes=1024k,shared=yes
fwd=fwd_cStor_node1,fsd=cStor_node1,host=cStor_node1,operation=write,xfersizes=1024k,fileio=sequential,fileselect=sequential,threads=64
fwd=fwd_cStor_node2,fsd=cStor_node2,host=cStor_node2,operation=write,xfersizes=1024k,fileio=sequential,fileselect=sequential,threads=64
fwd=fwd_cStor_node3,fsd=cStor_node3,host=cStor_node3,operation=write,xfersizes=1024k,fileio=sequential,fileselect=sequential,threads=64
fwd=fwd_cStor_node4,fsd=cStor_node4,host=cStor_node4,operation=write,xfersizes=1024k,fileio=sequential,fileselect=sequential,threads=64
fwd=fwd_cStor_node6,fsd=cStor_node6,host=cStor_node6,operation=write,xfersizes=1024k,fileio=sequential,fileselect=sequential,threads=64
fwd=fwd_cStor_node7,fsd=cStor_node7,host=cStor_node7,operation=write,xfersizes=1024k,fileio=sequential,fileselect=sequential,threads=64
rd=seaweedfs_rd,fwd=fwd*,fwdrate=max,format=restart,elapsed=300,interval=1

**Comment by chrislusf** [comment]
* which "six clients"? I do not see 6 directories mounted in step 4.
* how long is "a period of time"?

**Comment by muqiu428** [comment]
1. 步骤 4 分别在6台机器上执行
2. 写6、7个小时之后开始报错
3. ulimit -a 是1024

**Comment by AlekseyFicht** [comment]
Hi, @muqiu428 
Try to increase user open file limit

https://github.com/chrislusf/seaweedfs/wiki/Optimization#increase-user-open-file-limit

**Comment by muqiu428** [comment]
Thank you @AlekseyFicht 
I've increased ulimit -n, and I'm testing it now

**Comment by chrislusf** [comment]
the flie limit seems the problem. Will close current issue unless it showed up again.
