### ISSUE TITLE
filer upload opeartion not support "collection"

### ISSUE THREAD

**Issue by maggot611** [chrislusf/seaweedfs#209]
lately weed version:

``` shell
* 5feae4f  - (HEAD, origin/master, origin/HEAD, master) enable collection deletion (21 hours ago) <chrislusf>
```

when I use cmd below,  weed create 7 volumes with attribute： ttl=1m, collection=video

``` shell
curl -F "file=@1.jpg" "http://localhost:9333/submit?collection=video&ttl=1m"
```

but when I use filer+redis for uploading, weed create 7 volumes only with attribute: ttl=1m. atrribute collection ignored by weed.

``` shell
curl -F "file=@1.jpg" "http://localhost:8888/1.jpg?collection=video&ttl=1m"
```

can weed open "collection" setting for filer upload ?

**Comment by maggot611** [comment]
another minor question：
when I upload file by filer with attribute ttl, the volume ID deleted when expired. But entry recorded in filer always exist until explicitely call "curl -x DELETE".

bug also exist when  I use filer with redis, the redis key not removed when file expired, except explicitely call "curl -x DELETE"

**Comment by chrislusf** [comment]
When starting filer, there is a "collection" option. Filer was designed to work with one collection. It's not due to technical challenges, but conceptually easier to manage. Let me know your use case.

**Comment by maggot611** [comment]
there is no other way except filer to upload/download file with original filename. is that so?
Meanwhile, I want to classify the files when use filer.
Some files uploaded is tmp files, belong to certain user, they should be deleted after a period of time, maybe one day, maybe one month, I don't know; Some files need to be store forever.
I use filer to upload file with user-defined collection, and there is a way to delete certain collection whenever I need to do so.

**Comment by chrislusf** [comment]
I am planning to add the option to specify a collection when uploading to filer.

**Comment by chrislusf** [comment]
Already supported now.
