### ISSUE TITLE
关于seaweedfs在docker容器中删除文件后磁盘空间不释放问题

### ISSUE THREAD

**Issue by Lake-zhang** [chrislusf/seaweedfs#2091]
操作系统:Ubuntu16.04
Docker Version:19.03.12
seaweedfs部署在docker容器中，Java调用api删除文件后，磁盘空间没有释放，显示执行 `curl "http://localhost:9333/vol/vacuum"`也没用起到作用，但是把seaweedfs放在docker外，也就是直接在物理机环境部署，在执行删除文件，显示执行 `curl "http://localhost:9333/vol/vacuum"`是可以释放磁盘空间的，是什么原因导致在容器内没有释放空间呢？

**Comment by chrislusf** [comment]
Please show master logs.

**Comment by chrislusf** [comment]
can not reproduce.

**Comment by catlovefish** [comment]
hello，如果在集群状态下面，扩容了，之前老节点写满盘了，会自动变为可读了
