### ISSUE TITLE
S3 API does not save metadata during put-object 

### ISSUE THREAD

**Issue by bennykwok** [chrislusf/seaweedfs#2092]
aws --endpoint-url http://localhost:8333 --profile seaweedfs s3api put-object --bucket testing --key testing.jpg --body testing.jpg --metadata Width=1024,Height=768 --debug 

PUT
/testing/testing.jpg
[skip some line]
x-amz-meta-height:1024
x-amz-meta-width:768

weed/s3api/s3api_object_handlers.go
line 39: func (s3a *S3ApiServer) PutObjectHandler(w http.ResponseWriter, r *http.Request) {

        for k, v := range r.Header {
                glog.V(0).Infof("header %s: %s", k, v)
        }

==========
output: 

I0527 20:37:00 55107 s3api_object_handlers.go:42] header X-Amz-Meta-Width: [1024]
I0527 20:37:00 55107 s3api_object_handlers.go:42] header0 X-Amz-Meta-Height: [768]

**Comment by chrislusf** [comment]
Fixed current code.
