### ISSUE TITLE
LXC/LXD on SeaweedFS results in I/O errors

### ISSUE THREAD

**Issue by Ne00n** [chrislusf/seaweedfs#2102]
**Describe the bug**
I get I/O errors when running LXC containers on SeaweedFS.

Example:

I0531 15:53:03  2099 wfs_filer_client.go:29] WithFilerClient 0 10.0.251.1:19533: input/output error
I0531 15:53:03  2099 dir_link.go:77] Link /containers/my-container/rootfs/usr/bin/perl -> /containers/my-container/rootfs/usr/bin/perl5.26.1: UpdateEntry: rpc error: code = Unknown desc = not found /containers/my-container/rootfs/usr/bin/perl: filer: no entry is found in filer store

Pastebin: https://pastebin.com/raw/E62V7Cuq

LXD:

snap install lxd --channel=4.0/stable
lxc storage create seaweedfs dir source=/mnt/seaweedfs/ (I did mount SeaweedFS before)
lxc launch -s seaweedfs ubuntu:18.04 my-container

**System Setup**
3 Nodes, 3x Master, 3x Volume, 3x Filer

/usr/local/bin/weed master -defaultReplication=001 -ip=10.0.251.1 -ip.bind=10.0.251.1 -port=9333 -mdir=/home/seaweedfs/master -peers=10.0.251.1:9333,10.0.251.2:9333,10.0.251.3:9333

/usr/local/bin/weed volume -ip=10.0.251.1 -ip.bind=10.0.251.1 -port=9433 -dir=/home/seaweedfs/volume -dataCenter=dc1 -rack=rack1 -mserver=10.0.251.1:9333,10.0.251.2:9333,10.0.251.3:9333

/usr/local/bin/weed filer -ip=10.0.251.1 -ip.bind=10.0.251.1 -port=9533 -master=10.0.251.1:9333,10.0.251.2:9333,10.0.251.3:9333

Same on all 3 nodes, only the IP does differ.
Used: https://github.com/Ne00n/seaweed-spawner-3000

- Ubuntu 20.04 on arm64
- 2.49
- if using filer, show the content of `filer.toml` ( could not find this one, sorry)

**Expected behavior**
It should not result in any I/O errors

Any idea on this guys?

**Comment by chrislusf** [comment]
Filers need to add -peers option

**Comment by Ne00n** [comment]
Did that, I destroyed the cluster and build a new one with -peers on the filers.

/usr/local/bin/weed filer -ip=10.0.251.1 -ip.bind=10.0.251.1 -port=9533 -master=10.0.251.1:9333,10.0.251.2:9333,10.0.251.3:9333 -peers=10.0.251.1:9533,10.0.251.2:9533,10.0.251.3:9533

Same errors: https://pastebin.com/raw/pRrRas0P

Any idea how to find the cause?

**Comment by Ne00n** [comment]
A few second later, the mount crashed.
https://pastebin.com/raw/nWKLCkCJ

**Comment by chrislusf** [comment]
I tried these commands and seems working fine:

```
snap install lxd --channel=4.0/stable
lxc storage create seaweedfs dir source=/mnt/seaweedfs/ (I did mount SeaweedFS before)
lxd init
lxc launch -s seaweedfs ubuntu:18.04 my-container
```

The errors were creating a hard link A to B, but B was not created first.

**Comment by chrislusf** [comment]
Added some fixes for mount. Please try it in dev release https://github.com/chrislusf/seaweedfs/releases/dev with the latest code.

**Comment by chrislusf** [comment]
Closing since no more updates.

**Comment by Ne00n** [comment]
> Filers need to add -peers option

This has been removed? When I run weed filer --help it does not seem to mention -peers anymore.

**Comment by chrislusf** [comment]
> > Filers need to add -peers option
> 
> This has been removed? When I run weed filer --help it does not seem to mention -peers anymore.

Yes
