### ISSUE TITLE
2.50: Feature request/issue: Allow -ip.bind with IPv6 in common notation and explicit choice of IPv4 and/or IPv6

### ISSUE THREAD

**Issue by Radtoo** [chrislusf/seaweedfs#2109]
I noticed that -ip.bind doesn't allow IPv6 addresses in common notation:
`weed server -ip.bind="::1"`
results in `Master startup error: listen tcp: address ::1:9333: too many colons in address`

This IPv4 analogue works fine: `weed server -ip.bind="127.0.0.1"`

I also noticed I don't actually know how to force either IPv4 or IPv6 while binding by hostname. Or how to listen to both at the same time.

Suggestion: Have -ip.bind4 and -ip.bind6 to make picking IPv4 or IPv6 explicit. Check for correct IP address syntax based on which it is. Allow using both at the same time.

**Comment by chrislusf** [comment]
https://github.com/chrislusf/seaweedfs/wiki/FAQ#support-ipv6

**Comment by Radtoo** [comment]
Square bracket notation and an interface - apparently an rfc6874 URL? Never had to use this before, so I didn't think of using it. A hint in the error or weed help might be a good idea.

But how would I force IPv6 with a hostname? Substituting the hostname for the IPv6 in the square brackets doesn't work (and the RFC doesn't actually suggest this is supported anyhow). Also not sure how I would bind on both IPv4 and IPv6 at the same time.

**Comment by chrislusf** [comment]
Leave the `-ip.bind` empty, it will listen on all available IP addresses.

**Comment by Radtoo** [comment]
So to get a mental picture of the possibilities, the current options for starting a weed server are:
- IPv6 on a specific IP & interface with only the RFC6874 brace notation being supported.
- IPv4 on all interfaces with a single IPv4 address.
- All interfaces/all addresses on IPv4 and IPv6 both (by default with no parameter specified).

But not:
- IPv4 or IPv6 as defined by hostname, optionally restricted to either IPv4 or IPv6.
- Both IPv4 and IPv6 at the same time with specific IPs or interfaces.
- IPv6 on multiple interfaces or IPv6 addresses.


> Leave the -ip.bind empty, it will listen on all available IP addresses.
Having a poke at this option. `weed shell -master="[::1]:9333" -filer="localhost:8888"` seems to work, but `weed shell -master="[::1]:9333" -filer="[::1]:8888"` or the same with the full IPv6 instead of ::1 and even with the interface added (e.g. -filer="[::1%enp1s0]:8888") fails with a parser error for the -filer parameter.
