### ISSUE TITLE
seaweedfs will read the whole content into memory, and duplicate ones for many clients reading the same file

### ISSUE THREAD

**Issue by chuqingq** [chrislusf/seaweedfs#211]
When downloading a file, seaweedfs will read the whole content into memory, and then send that.
And if many clients are downloading big files simultaneously, seaweedfs will generate many copies(not cache the content for the same file), and that will cost too much memory, so that linux OOM killer will kill volume process.
seaweedfs will generate many copies, and that will cost too much memory, so that OOM killer will kill volume process.

There are 2 solutions for this:
1. use NeedleCache, and make sure only one file content stays in memory
2. use syscall.Sendfile for downloading(but that doesnot support the CRC, picture rotating, resizing very well)

**Comment by chrislusf** [comment]
In the first place, SeaweedFS is not for big files. Big files can be chunked and stored individually in SeaweedFS.

Sendfile seems a good choice. but it depends on the OS.

**Comment by hsen-dev** [comment]
What is the best practice for storing big files (~1Gb) in weedfs? Is weed sucks too much memory for this case too? what is the recommended files size for using full feature with  weedFS? (if this question is irrelevant I'll post it as new issue)

**Comment by chuqingq** [comment]
@chrislusf OK. Would you please fix this?

**Comment by chrislusf** [comment]
unlikely any time soon. This is totally different from the O(1) disk seek feature.

**Comment by chrislusf** [comment]
Is this something you see in production or just theory?

**Comment by chuqingq** [comment]
I encountered this for testing and production.
When many clients are downloading the same file at the same time, many memory copy of the file content exists, which leading to OOM killing weed process.

I think uploading will have the same problem probably.
