### ISSUE TITLE
Windows: Network drive mapped by Winfsp, can create, modify but can't remove files.

### ISSUE THREAD

**Issue by bnuzhouwei** [chrislusf/seaweedfs#2110]
1. Mount a fold from seaweedfs using weed mount on linux.
2. Map the fold as a network drive on windows using [winfsp](https://github.com/billziss-gh/winfsp). \\\\sshfs\root@192.168.1.13, input the root password, got a network drive.
3. creating and modifying files in the network drive worked, but can't not delete files.
4. When deleting files, they exist after refresh the folder. But removing directories works well.

**Comment by chrislusf** [comment]
Can not reproduce. Please show logs for mount: `weed -v=4 mount ...`

**Comment by Hower-Pan** [comment]
I have same issue below is my log
i try del map drive file 2019-03-19_152939.jpg
dir directory file is back ....

[windows.log](https://github.com/chrislusf/seaweedfs/files/6656085/windows.log)

**Comment by chrislusf** [comment]
@Hower-Pan Thanks for the logs!!!

Please help to verify the fix with the dev release https://github.com/chrislusf/seaweedfs/releases/tag/dev

**Comment by Hower-Pan** [comment]
Hi Chris
This release is workable.  thank you

Chris Lu ***@***.***> 於 2021年6月16日 週三 上午3:46寫道：

**Comment by chrislusf** [comment]
@Hower-Pan thanks for the update!

**Comment by Stitch10925** [comment]
@bnuzhouwei 
Were you able to mount the same location in Windows as on Linux?

When using weed mount on Linux I get the root of my weedfs, however, when I use winsfp on windows it mounts but I get a "raw" mount with a caching and local folder, but I cannot access the files in my weedfs.
