### ISSUE TITLE
`weed upload` exits with 0 even on error

### ISSUE THREAD

**Issue by nagy** [chrislusf/seaweedfs#2113]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**
When running `weed upload` on any file, and the operation is not successful, it exits with a 0 exitcode. An exitcode of 0 signals a successful operation in unix. This makes catching such a failure in scripts hard.

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
  See below
- OS version
  nixos unstable
- output of `weed version`
    ```
    version 30GB 2.50  linux amd64
    ```
- if using filer, show the content of `filer.toml`

**Expected behavior**
I would expect that the command `weed upload` fails with a non-zero exitcode upon any unsuccesful operation.

**Additional context**
To easier reproduce this, just start an "empty" master server with `weed master` and dont start any volume servers. This should give you a chance to observe this:

```sh
$ weed upload /proc/cpuinfo
[{"fileName":"cpuinfo","error":"rpc error: code = Unknown desc = no free volumes left for {\"replication\":{},\"ttl\":{\"Count\":0,\"Unit\":0}}"}]
$ echo $?
0
```
The last line is printing the exitcode.

**Comment by chrislusf** [comment]
Do you want to send a pull request?

**Comment by nagy** [comment]
sure

**Comment by chrislusf** [comment]
Set the exit status here? https://github.com/chrislusf/seaweedfs/blob/master/weed/weed.go#L73

**Comment by nagy** [comment]
Yes, this is what I had in mind. If the commands themselves return the exitcode instead of just a boolean that it allows us to distinct wrong invocations from errors during execution. But that involves a bit more changes to all the commands.

I can gladly make a PR for this. Anyway, this issue can be closed.

**Comment by chrislusf** [comment]
> But that involves a bit more changes to all the commands.

Mostly users just want to know error or not. They may not be interested to know different error codes.
