### ISSUE TITLE
[feature] Filer Support Log Steaming

### ISSUE THREAD

**Issue by chrislusf** [chrislusf/seaweedfs#212]
1. Easy to store production logs. logs are streaming to seaweedfs filer, and filer will chunk the data and save it to seaweedfs volume servers.
2. Easy to parallel data fetching for analysis
   seaweedfs filer will provide the file as a list of fileids pointing to chunks. The chunks can be used for parallel fetching.

**Comment by hsen-dev** [comment]
+1
specially for part 2 for analysis

**Comment by chrislusf** [comment]
filer now support this. One file chunk can be uploaded, and the file metadata can be updated with the new file chunk.
