### ISSUE TITLE
'.gz' file will be extracted automaticly by seaweedfs, which is non-expected

### ISSUE THREAD

**Issue by chuqingq** [chrislusf/seaweedfs#213]
I upload a 'jdk.tar.gz' file. But when I download it, I get a 'jdk.tar' file.

I know this is a functionality, but I don't think this is correct.
I suggest seaweedfs should keep file unchanged, whatever the file is.
Seaweedfs could not compress it again for '.gz' or '.zip' to storage it.

**Comment by chrislusf** [comment]
We can have a special case for ".tar.gz", as seen here: https://github.com/chrislusf/seaweedfs/blob/master/go/storage/needle.go#L130

But seems it is not working for you? May need a fix for this.

**Comment by chuqingq** [comment]
Sorry, I made a mistake. I uploaded 'jdk.xxx.gz', not 'jdk.tar.gz'.

**Comment by chuqingq** [comment]
Do you mean you want: upload a '.gz' file, but download a extracted file?
