### ISSUE TITLE
`fuse` subcommand should daemonize automatically

### ISSUE THREAD

**Issue by PeterCxy** [chrislusf/seaweedfs#2137]
**Describe the bug**

When mounting via `mount -t fuse.xxx fuse ...`, the binary responsible for mounting the respective FUSE filesystem is expected to daemonize itself automatically and not block the `mount` command. This is required on systemd-based systems, because otherwise the `.mount` units will never enter the activated state. On non-systemd systems, this will also cause the mountall process to never finish if added to fstab.

**Expected behavior**

`weed fuse` should daemonize instead of running in the foreground. The daemonized process should automatically exit when unmounted.

**Comment by chrislusf** [comment]
same as #2135

**Comment by PeterCxy** [comment]
@chrislusf https://github.com/sevlyar/go-daemon

**Comment by danielflira** [comment]
I was not able to use go-daemon, so I just started a background "weed fuse" and finished foreground, hope this help. Any problem just let me know.
