### ISSUE TITLE
seaweedfs should check WhiteList before proxyToLeader

### ISSUE THREAD

**Issue by chuqingq** [chrislusf/seaweedfs#214]
`
	r.HandleFunc("/", ms.uiStatusHandler)
	r.HandleFunc("/ui/index.html", ms.uiStatusHandler)
	r.HandleFunc("/dir/assign", ms.proxyToLeader(ms.guard.WhiteList(ms.dirAssignHandler)))
	r.HandleFunc("/dir/lookup", ms.proxyToLeader(ms.guard.WhiteList(ms.dirLookupHandler)))
	r.HandleFunc("/dir/join", ms.proxyToLeader(ms.guard.WhiteList(ms.dirJoinHandler)))
	r.HandleFunc("/dir/status", ms.proxyToLeader(ms.guard.WhiteList(ms.dirStatusHandler)))
	r.HandleFunc("/col/delete", ms.proxyToLeader(ms.guard.WhiteList(ms.collectionDeleteHandler)))
	r.HandleFunc("/vol/lookup", ms.proxyToLeader(ms.guard.WhiteList(ms.volumeLookupHandler)))
`

If a request not in whitelist is sent to a non-leader master, this request will be handled by leader, which is unexpected.

**Comment by chrislusf** [comment]
If all masters should set the whitelist, this would not be an issue, right?

**Comment by chuqingq** [comment]
No, it is stlll an issue. I set the whitelist for all masters, but the unauthorized request is still handled.

I think if master2 redirects the request to master1(leader), master2 is in whitelist for master3.

**Comment by faaliyet** [comment]
nice catch
