### ISSUE TITLE
Files in backup missing

### ISSUE THREAD

**Issue by kw005** [chrislusf/seaweedfs#2140]
Tiny Cluster: 1 Master; 2 Vol Servers; Replication 001 

We did a backup for all 6 volumeIDs:

`weed backup -server=master:port -dir=. -volumeId=1...6`

and went from version 0.76 to 2.53. Most files seem to be there, however an image file in VolumeID 3 (one of the last uploaded files and accessible in 0.76) is missing in 2.53.

How can this happen and how can we ensure that every file from 0.76 is also there in 2.53 ?
What do we need to do?

**Comment by chrislusf** [comment]
try to run the backup command again.

**Comment by kw005** [comment]
Thanks for the reply. Second backup for 2.53 did not work either. Files are missing.
Version 1.47 and 2.27 worked however. Version 2.27+ might have some bug?

MP4 files are played well until 2.27  
For Example, in 2.52 MP4 files are not played at all. Even using Ningx in front via proxy_pass will not play mp4 files
Local downloading via curl localhost:port/FID > video.mp4 is working.

Why are mp4 files not played in 2.52+?

**Comment by chrislusf** [comment]
can not reproduce.

**Comment by kw005** [comment]
So, uploading a mp4 file and accessing via browser, the video file in 2.52+ is being played? Can you reproduce that?
We tested it with 3 server, same result - not played at all.

**Comment by chrislusf** [comment]
Yes. Worked for me.

**Comment by chrislusf** [comment]
duplicated with https://github.com/chrislusf/seaweedfs/issues/2156
