### ISSUE TITLE
For version 2.54, there are no download builds for linux amd64.

### ISSUE THREAD

**Issue by AlekseyFicht** [chrislusf/seaweedfs#2149]
Hello

For version 2.54, there are no download builds for linux_amd64.tar.gz
https://github.com/chrislusf/seaweedfs/releases/tag/2.54
there is only the source code of the zip file
can you fix that ?

**Comment by chrislusf** [comment]
this is caused by the migration of travis-ci.org to travis-ci.com

Adding a version 2.55 to resolve this.

**Comment by AlekseyFicht** [comment]
Thank you.
