### ISSUE TITLE
Cloud Tier Problem

### ISSUE THREAD

**Issue by Hower-Pan** [chrislusf/seaweedfs#2151]
Some background:

  Two seaweedfs site
  One AWS cloud s3 Service

Describe the bug:
  Implement Cloud Tier form one site to other site OK

  _**when I change  [storage.backend] config to aws from master.toml and restart master
  system still got original storage.backend parameter （I had conform config is changed)**_

  I try stop master service clear master data file restart it still NG
  
  So I reconfig  seaweedfs & remove all data 

  **_[storage.backend] Is got aws  parameter
  but i try upload the .dat file content to the cloud got below massage_**

  > volume.tier.upload -dest=s3.default -collection=2020 -volumeId=8
markVolumeReadonly 8 on 192.168.101.70:9222 ...
error: copy dat file for volume 8 on 192.168.101.70:9222 to s3.default: rpc error: code = Unknown desc = backend s3.default copy file /opt/seaweedfs/vol/2020_8.dat: failed to upload file /opt/seaweedfs/vol/2020_8.dat: SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.
        status code: 403, request id: 1UDXYAQBPMWFC6D4, host id:

  I had check aws_access_key_id ＆ aws_secret_access_key is correct

  Can you please help me check what wrong with it

                                          Thank you

**Comment by chrislusf** [comment]
the master.toml was loaded, but seems the credentials are not correct.

**Comment by Hower-Pan** [comment]
I use ~/.aws/credentials for aws  credentials and I use aws cli to check my buckets it's OK
so I think is not credentials  problem .



<img width="846" alt="image" src="https://user-images.githubusercontent.com/33602331/123241981-2ca4eb80-d514-11eb-837a-a4ea71810060.png">

**Comment by chrislusf** [comment]
try to set them in master.toml and see whether it makes any difference.

**Comment by Hower-Pan** [comment]
thank your support
I change master.toml values , restart volume servers is get new parameter  
it's good news for mr 

but AWS problem still not work.
aws_access_key_id aws_secret_access_key is no difference with  ~/.aws/credentials config

if credentials problem why had copied process ???
