### ISSUE TITLE
upload produces "mime", image is downloaded instead of shown in browser

### ISSUE THREAD

**Issue by kw005** [chrislusf/seaweedfs#2153]
We wanted to upload image file to the volume server. (2.27) We always get a wired mime result.
The browser will download the image (jpg) instead of showing it to the user.

`{"size":77048,"eTag":"f9bf9cc0c401fec012e99c024a2ad336","mime":"multipart/form-data; boundary=------------------------a560cf4fbe000bd9"}`

Can anybody help?

**Comment by ibmkhd** [comment]
Hi @kw005 how you solved this?
