### ISSUE TITLE
file handle read 404 Not Found, on a file that was uploaded without errors

### ISSUE THREAD

**Issue by Suika** [chrislusf/seaweedfs#2154]
**Describe the bug**
I fairly regularly use `weed filer.copy` to move data from my host system to seaweed as to not use the FUSE mount due to my history with it. And it's much faster than fuse.

Yet on regular basis I find some errors that pop up now and then, like:
```
E0624 21:31:04 15798 filehandle.go:150] file handle read /buckets/client_files/134853c041e77c57cb9927a8739067909435c047d38e5eb8bb7518a54c3.jpg: http://172.27.0.5:8080/187,066e450035acb262?readDeleted=true: 404 Not Found

E0624 23:36:16 15798 reader_at.go:146] fetching chunk &{FileId:187,066e450667b83f9d Offset:0 Size:4194304 LogicOffset:0 ChunkSize:4194304 CipherKey:[] IsGzipped:false}: http://172.27.0.5:8080/187,066e450667b83f9d?readDeleted=true: 404 Not Found
E0624 23:36:16 15798 filehandle.go:150] file handle read /buckets/client_files/9a03492bf1447407226804c868bc37768f9420e08c6620ae30b1e120358.png: http://172.27.0.5:8080/187,066e450667b83f9d?readDeleted=true: 404 Not Found
W0624 23:36:16 15798 filehandle.go:90] file handle read /buckets/client_files/9a03492bf1447407226804c868bc37768f9420e08c6620ae30b1e120358.png 0: http://172.27.0.5:8080/187,066e450667b83f9d?readDeleted=true: 404 Not Found
```

I know exactly that I downloaded that file ~4 hours ago and uploaded it via `weed filer.copy` 3 hours ago.
The filer copy threw no errors or what so ever. But while I was running some checks, I noticed that the application I use was erroring out on the file.
After that I tried accessing that file via FUSE and it returned IO error. And a few more of the messages that are up there.

I've gone and deleted the file in seaweed and re-uploaded via `filer.copy`. After this it worked. I don't know what happened, but it's strange.

I have been noticing these error a bit lot more lately.

Are there tools that seaweed has, to make sure that the entried in the Filer also have all the needed needles in the volume server?
I could go and try to hash every file recursively to make sure that every part of the file is touched and that the contens are fetched from the volume.
But wouldn't this type of thing be better located on the weed side?

**System Setup**
- Seed Docker setup in #1594 but with newer seaweed version
- Debian 9
- `version 8000GB 2.55 05af54a linux amd64`
- default `filer.toml`
- FUSE: `weed mount -filer=localhost:8888 -dir=/mnt/weed -cacheDir=/snapraid/storage_c2/test/seaweed-cache -cacheCapacityMB=0`

**Expected behavior**
A utility that checks for data consistency (and integrity) on the volume- and filer server.
ie. Check entries in the Filer against the Needles in the Volumes and make sure that they exist and return data.

**Additional context**
I constantly writing data to Seaweed via S3 and get a decent amount of EOF errors and what not. But files are somehow available.
Now that I get errors for files uploaded via `filer.copy`, it makes me worry a little about the data stored on seaweed.

**Comment by chrislusf** [comment]
I added a `weed shell` command, to print out missing chunks in filer:
```
volume.fsck -findMissingChunksInFiler
```

**Comment by chrislusf** [comment]
When `weed filer.copy`, try to keep the output and maybe we can find some pattern if the problem is on the `filer.copy`.

**Comment by Suika** [comment]
Will try and see the next time I run it.
