### ISSUE TITLE
Can't play mp4 video on chrome

### ISSUE THREAD

**Issue by bwlfhu** [chrislusf/seaweedfs#2156]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs
Report issues here. Ask questions here https://stackoverflow.com/questions/tagged/seaweedfs
Please ask questions in https://github.com/chrislusf/seaweedfs/discussions

**Describe the bug**
step1: upload mp4 video with filer;
step2: click file on filer page;
video can't play.

But I try to play with nginx, and success. 

**System Setup**
- docker run --name weed -d -p 9333:9333 -p 8080:8080 -p 18080:8080 -v /home/data/weedfs:/data chrislusf/seaweedfs server -dir="/data"
- docker run -d -p 8888:8888 --name filer chrislusf/seaweedfs filer -master="172.17.0.6:9333"
- CentOS7.6
- 2.53
- `filer.toml` -- run with docker

**Expected behavior**
play video normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/10275564/123411360-f4201300-d5e2-11eb-8edd-3ed928931e34.png)
![image](https://user-images.githubusercontent.com/10275564/123411396-fedaa800-d5e2-11eb-9297-16e98f58214b.png)

**Comment by kmlebedev** [comment]
Can you show network tools console with http requests ?

**Comment by chrislusf** [comment]
I used this and worked fine:
```
docker run -p 9333:9333 -p 8080:8080 -p 18080:8080 -p 8888:8888  -v /home/data/weedfs/:/data chrislusf/seaweedfs server -dir="/data" -filer
```

**Comment by chrislusf** [comment]
The port 19333 for master grpc was not open. I do not think your setup can run at all.

**Comment by bwlfhu** [comment]
> I used this and worked fine:
> 
> ```
> docker run -p 9333:9333 -p 8080:8080 -p 18080:8080 -p 8888:8888  -v /home/data/weedfs/:/data chrislusf/seaweedfs server -dir="/data" -filer
> ```

I was in wrong way before, actually Just filer docker is allright.
Now I use the right command and still can't play with chorme.

This is the network tools console with http requests:
![image](https://user-images.githubusercontent.com/10275564/123500742-c5517d80-d672-11eb-9889-37533c5f8ebe.png)

![image](https://user-images.githubusercontent.com/10275564/123500752-d69a8a00-d672-11eb-983c-9ebfb66b760b.png)

The video file is from android. I put it under nginx and play normally.

**Comment by chrislusf** [comment]
try use firefox or safari.

https://stackoverflow.com/questions/25131906/mp4-file-not-playing-in-chrome

**Comment by bwlfhu** [comment]
I use firefox but it only shows the first frame of video(video freeze), still can't play.

![image](https://user-images.githubusercontent.com/10275564/123591768-fcfd2880-d81e-11eb-93a4-35299b5d3705.png)

**Comment by bwlfhu** [comment]
I try version 2.11 and it's fine both on chrome and firefox.
Is there any change from that version?

![image](https://user-images.githubusercontent.com/10275564/123599795-9250ea80-d828-11eb-8459-ab7b979b3353.png)

**Comment by chrislusf** [comment]
Added a fix. Please try it with the latest dev version https://github.com/chrislusf/seaweedfs/releases/dev or 
```
docker pull chrislusf/seaweedfs:dev
```

**Comment by bwlfhu** [comment]
Thanks. It's OK now.

> Added a fix. Please try it with the latest dev version https://github.com/chrislusf/seaweedfs/releases/dev or
> 
> ```
> docker pull chrislusf/seaweedfs:dev
> ```
