### ISSUE TITLE
You should add missing `attr.Env = os.Environ()`

### ISSUE THREAD

**Issue by thephoenixofthevoid** [chrislusf/seaweedfs#2159]
Here you asked why env variables are lost:
https://github.com/chrislusf/seaweedfs/blob/1cac2f2278b2344ac41ac882c7b21593f212d3bd/weed/command/fuse.go#L214

The issue must be due to missing:
```
attr.Env = os.Environ()
```
here https://github.com/chrislusf/seaweedfs/blob/1cac2f2278b2344ac41ac882c7b21593f212d3bd/weed/command/fuse.go#L198

Another way to do this is to explicitly set Env to `nil` 

It seems all env. vars are lost.

Need to delete the workaround if everything works:
https://github.com/chrislusf/seaweedfs/blob/1cac2f2278b2344ac41ac882c7b21593f212d3bd/weed/command/fuse.go#L215-217

**Comment by chrislusf** [comment]
@thephoenixofthevoid send a PR?

cc @danielflira

**Comment by danielflira** [comment]
The condition about environment was wrote before the condition about master process. I don't know if it is related with my system (ubuntu 20.04) but without this validation I got this error:

```
root@macubuntu:/tmp# mount -t weed fuse /mnt -o child
I0627 00:36:51 80808 mount_std.go:236] mount: fusermount: exec: "fusermount": executable file not found in $PATH
```
The parameter -o child prevent StartProcess, and run weedfuse in foreground.

If I remember well about this, mount command runs weedfuse  without full PATH variable,  when weedfuse command runs fusermount an "command not found" error happens.

**Comment by danielflira** [comment]
I faked command /sbin/fake to use with mount:

```python3
#!/usr/bin/env python3

import os
import sys

print(os.environ.get("PATH", "environment var PATH does not exists"))
input()

sys.exit(0)
```
Running mount with fake command:

```sh
root@macubuntu:/tmp# mount -t fuse.fake fuse /mnt -o child
environment var PATH does not exists
```
The faked command with Bash:

```sh
#!/bin/bash

echo "${PATH}"
read

exit 0
```

Result:

```sh
root@macubuntu:/tmp# mount -t fuse.fake fuse /mnt -o child
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

I think that bash set PATH variable on his own.

**Comment by thephoenixofthevoid** [comment]
Well, before the Env was empty but the PATH being explicitly set. Now the variables are inherited as it seemed to suppose to be. Try running in the Shell with all env.vars being nuked beforehand. If it starts to work, start preserving some variables to finally find one responsible for behaviour change.

**Comment by danielflira** [comment]
The path is lost when the mount command runs weedfuse, not when weedfuse runs itself in the background. Also when ProcAttr.Env is empty the default library behavior is to assign os.Environ: https://golang.org/pkg/os/#ProcAttr .

The options I see are: define if not defined or receive by parameter to be assigned. Otherwise the user will have to do some workaround to set the PATH between mount command and weedfuse.

**Comment by chrislusf** [comment]
@danielflira so we should put back these lines?

```

// if err := os.Setenv("PATH", "/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin"); err != nil {
//	panic(fmt.Errorf("setenv: %s", err))
// }

```

**Comment by thephoenixofthevoid** [comment]
> The path is lost when the mount command runs weedfuse, not when weedfuse runs itself in the background. Also when ProcAttr.Env is empty the default library behavior is to assign os.Environ: https://golang.org/pkg/os/#ProcAttr .
> 
> The options I see are: define if not defined or receive by parameter to be assigned. Otherwise the user will have to do some workaround to set the PATH between mount command and weedfuse.

The path was lost twice, because nil is not [] (empty). Anyway, I like proposed solution in general.

**Comment by danielflira** [comment]
You are right nil is not empty, ProcAttr is created with nil:

https://play.golang.com/p/bZMYc_po9ov
