### ISSUE TITLE
presigned urls with query containing X-Amz-Content-Sha256 compare the hash against itself and accept any upload

### ISSUE THREAD

**Issue by ibsusu** [chrislusf/seaweedfs#2166]
**Describe the bug**
When I upload a .jpg in the place of an expected .webm the file is accepted for upload despite the hashes being different.  It doesn't have to be a .jpg, it's just an example.  Any file with a different hash is accepted for upload.

**System Setup**
Each command happens in a separate terminal
OS: Mac Big Sur
using a filer but I have not set a filer.toml at all.
weed version: version 30GB 2.55 05af54ad darwin amd64,  I've modified auth_signature_v4.go strictly to print out what `req.URL.Query().Get("X-Amz-Content-Sha256")` and `hashedPayload` are inside of `doesPresignedSignatureMatch` from line 344.
1. `weed server`
2. ` weed filer -s3 -s3.config=s3ConfigTemplate.json`

**s3ConfigTemplate.json**:
```
{
  "identities": [
    {
      "name": "some_name",
      "credentials": [
        {
          "accessKey": "some_access_key1",
          "secretKey": "some_secret_key1"
        }
      ],
      "actions": [
        "Admin",
        "Read",
        "List",
        "Tagging",
        "Write"
      ]
    },
    {
      "name": "some_read_only_user",
      "credentials": [
        {
          "accessKey": "some_access_key2",
          "secretKey": "some_secret_key2"
        }
      ],
      "actions": [
        "Read",
        "List"
      ]
    },
    {
      "name": "some_normal_user",
      "credentials": [
        {
          "accessKey": "some_access_key3",
          "secretKey": "some_secret_key3"
        }
      ],
      "actions": [
        "Read",
        "List",
        "Tagging",
        "Write"
      ]
    },
    {
      "name": "user_limited_by_bucket",
      "credentials": [
        {
          "accessKey": "some_access_key4",
          "secretKey": "some_secret_key4"
        }
      ],
      "actions": [
        "Read:bucket1",
        "Read:bucket2",
        "Read:bucket3",
        "Write:bucket1"
      ]
    }
  ]
}
```

**Erroneous PUT Command**
```
curl -XPUT -T "Musk-Ox.jpg" -H "Content-Type: video/webm" \
"http://localhost:8333/example/bearbro.webm?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=941877c9e5c26e819b009344a82a70af94ddc09946a262e30b70b27547cfeac4&X-Amz-Credential=some_access_key1%2F20210629%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20210629T223637Z&X-Amz-Expires=60&X-Amz-SignedHeaders=host&X-Amz-Signature=7d6355bf2250c436e5f3db5659c55769d0af8bb992f00ea535b0968c4e5f2ae9"
```

**Expected behavior**
I expect weed to reject the upload right around here: https://github.com/chrislusf/seaweedfs/blob/e9eb15e56ae1a6df23df38e195c3d702e6f48e03/weed/s3api/auth_signature_v4.go#L431

**Additional context**
this function just returns the query parameter.  Not sure why.  Should it not come from the payload itself?
https://github.com/chrislusf/seaweedfs/blob/e9eb15e56ae1a6df23df38e195c3d702e6f48e03/weed/s3api/auth_signature_v4.go#L61

I'm working on a fix, but I don't really program in go and I'm not entirely sure where to go from here so please be gentle.

**Comment by chrislusf** [comment]
https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html

Current logic is to use query parameter value of "X-Amz-Content-Sha256" to compare with the presigned value "X-Amz-Content-Sha256".

Adding server side payload sha256 encoding is unexpected. This would increase the load unnecessarily and should be avoided.

**Comment by ibsusu** [comment]
>Current logic is to use query parameter value of "X-Amz-Content-Sha256" to compare with the presigned value "X-Amz-Content-Sha256"

The AWS docs are a bit difficult to navigate on this topic. I was under the impression that the page you linked was specific to *signed* requests which come from developer owned machines rather than client side.  The *presigned* request urls which are primarily used client side  have its documentation here: https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html

And there it says about halfway down the page: 

>For more information about the signing process (details of creating a canonical request, string to sign, and signature calculations), see Signature Calculations for the Authorization Header: Transferring Payload in a Single Chunk (AWS Signature Version 4). The process is generally the same except that the creation of CanonicalRequest in a presigned URL differs as follows:

>You don't include a payload hash in the Canonical Request, because when you create a presigned URL, you don't know the payload content because the URL is used to upload an arbitrary payload. Instead, you use a constant string UNSIGNED-PAYLOAD.

Presigned urls were never meant to verify the uploaded file matched the hash.  Essentially *this is a non-standard addition for the s3 api*.  There are a couple of stackoverflow questions and requests for this feature.  It doesn't exist.

Regardless of all of that there is the problem that this does sha256 hashing on the server.  Since this is already non-standard a possible workaround would be to substitute the blake2b or blake3 in its place.  Both are *much* faster so it wouldn't be as big a hit performance-wise.  I was hoping that this could be hidden behind a flag or with a different header or query parameter.  Maybe s3 isn't the best place to do this?  Maybe a different api?  Maybe something I'm not even thinking about?

If it doesn't make sense to do it, that's fine.  I just wanted to bring up the possibility because this whole thing is pretty cool.  And I absolutely need it for my project to succeed.  Thank you for looking into it btw.  Reading those docs isn't exactly fun.

**Comment by ibsusu** [comment]
Btw I will write any tests that are needed if you're open including such a feature.  I just wanted to gauge your thoughts before I go deeper.

**Comment by chrislusf** [comment]
Does MD5 work for you?

**Comment by ibsusu** [comment]
Not for my usecase.  See this md5 collisions example: https://crypto.stackexchange.com/a/32492

After thinking about it this morning, adding this functionality to s3 might be a mistake.  I can just add a hash verifying extension similar to the s3 one for the filer to use so the s3 API can stay pure, even though the standard s3 way seems flawed to me.

I'll probably do that and post a PR so you can take a look and utilize it if you like.  No pressure.  Thanks for creating this project.
