### ISSUE TITLE
S3 API Metadata Problem When  Upload Large File

### ISSUE THREAD

**Issue by qwedsazzcc** [chrislusf/seaweedfs#2173]
seaweedfs  version 2.56 

Use S3 sdk (Release v1.38.64)  Uploader   PartSize set  5 * 1024 * 1024,  Concurrency set 2  upload a 10MB size file   with  some Metadata

In NewMultipartUploadHandler it can see x-amz-meta-*  in request headers ,  but in PutObjectPartHandler and   in 
 CompleteMultipartUploadHandler it's not

It's any way to solved it?

**Comment by chenat9** [comment]
One object only have one x-amz-meta-* field, and it should be determined when create an upload task. So putpart and complete method can not change it.

**Comment by chrislusf** [comment]
thanks @chenat9

**Comment by qwedsazzcc** [comment]
if file less  5MB , sdk  just call the PutObjectPartHandler  and Metadata will save in filer's  Extended . but 10MB file 's Extended is null . where is the metadata saved and how can I  get it.

**Comment by chrislusf** [comment]
ok. Need to add that. 

What is the command you used to reproduce this?

**Comment by qwedsazzcc** [comment]
> command

weed start with command  -logdir=xxxx -v=0 server -master.port=9333  -volume.max=35 -volume.port=8882 -s3.port=8891 -filer.port=8889 -dir=xxx  -s3 -s3.allowEmptyFolder


golang s3 sdk upload file code  is 

uploader := s3manager.NewUploader(sess, func(u *s3manager.Uploader) {
		u.PartSize = 5 * 1024 * 1024 // The minimum/default allowed part size is 5MB
		u.Concurrency = 2            // default is 5
	})

	// Upload the file to S3.
	_, err = uploader.Upload(&s3manager.UploadInput{
		Bucket:             aws.String(bucket),
		Key:                aws.String(key),
		Body:               bytes.NewReader(content),
		ContentDisposition: aws.String(fmt.Sprintf("attachment; filename=\"%s\"", header.Filename)),
		Metadata:           aws.StringMap(map[string]string{"Filename": header.Filename}),
		ContentType:        aws.String(fileType),
	})


after upload files , then call filer list with -H "Accept: application/json"  is return 

{
    "Path": "/buckets/xxx",
    "Entries": [
        {
            "FullPath": "/buckets/xxx/.uploads",
            "Mtime": "2021-07-02T09:51:02+08:00",
            "Crtime": "2021-07-02T09:51:02+08:00",
            "Mode": 2147484159,
            "Uid": 4294967295,
            "Gid": 4294967295,
            "Mime": "",
            "Replication": "",
            "Collection": "",
            "TtlSec": 0,
            "DiskType": "",
            "UserName": "",
            "GroupNames": null,
            "SymlinkTarget": "",
            "Md5": null,
            "FileSize": 0,
            "Extended": null,
            "HardLinkId": null,
            "HardLinkCounter": 0,
            "Content": null
        },
        {
            "FullPath": "/buckets/xxx/093d2498-66cd-4b0f-8527-ac7c6c0dcbcf",
            "Mtime": "2021-07-02T09:50:58+08:00",
            "Crtime": "2021-07-02T09:50:58+08:00",
            "Mode": 432,
            "Uid": 4294967295,
            "Gid": 4294967295,
            "Mime": "audio/vnd.wave",
            "Replication": "000",
            "Collection": "xxx",
            "TtlSec": 0,
            "DiskType": "",
            "UserName": "",
            "GroupNames": null,
            "SymlinkTarget": "",
            "Md5": "YJDQ5vDkiYhqEEPfcF59mQ==",
            "FileSize": 4616684,
            "Extended": {
                "X-Amz-Meta-Filename": "b25ob2xkLndhdg=="
            },
            "chunks": [
                {
                    "size": 4194304,
                    "mtime": 1625190658133852000,
                    "e_tag": "mYgEAMMfTf3ylV5yfhHyvQ==",
                    "fid": {
                        "volume_id": 5,
                        "file_key": 2,
                        "cookie": 1778789922
                    }
                },
                {
                    "offset": 4194304,
                    "size": 422380,
                    "mtime": 1625190658109608300,
                    "e_tag": "RG2OefMG1Dwn/hquG7I9Aw==",
                    "fid": {
                        "volume_id": 3,
                        "file_key": 1,
                        "cookie": 4285541292
                    }
                }
            ],
            "HardLinkId": null,
            "HardLinkCounter": 0,
            "Content": null
        },
        {
            "FullPath": "/buckets/xxx/7593d5ff-d922-444f-b26a-aea3c62e1c7d",
            "Mtime": "2021-07-02T09:51:02+08:00",
            "Crtime": "2021-07-02T09:51:02+08:00",
            "Mode": 504,
            "Uid": 4294967295,
            "Gid": 4294967295,
            "Mime": "",
            "Replication": "",
            "Collection": "",
            "TtlSec": 0,
            "DiskType": "",
            "UserName": "",
            "GroupNames": null,
            "SymlinkTarget": "",
            "Md5": null,
            "FileSize": 0,
            "Extended": null,
            "chunks": [
                {
                    "size": 4194304,
                    "mtime": 1625190662762741800,
                    "e_tag": "XX8BmjLDntn4DScog7fxLQ==",
                    "fid": {
                        "volume_id": 1,
                        "file_key": 3,
                        "cookie": 4001722649
                    }
                },
                {
                    "offset": 4194304,
                    "size": 1048576,
                    "mtime": 1625190662707263900,
                    "e_tag": "byEzFQVeWKreAY4dzE8rtA==",
                    "fid": {
                        "volume_id": 4,
                        "file_key": 6,
                        "cookie": 3865154028
                    }
                },
                {
                    "offset": 5242880,
                    "size": 4194304,
                    "mtime": 1625190662727667800,
                    "e_tag": "3pufGi3SDdjkfFolfRnrFw==",
                    "fid": {
                        "volume_id": 5,
                        "file_key": 4,
                        "cookie": 3528823812
                    }
                },
                {
                    "offset": 9437184,
                    "size": 886672,
                    "mtime": 1625190662707263900,
                    "e_tag": "iz/vw27OlGp0hbMH7xgVCg==",
                    "fid": {
                        "volume_id": 6,
                        "file_key": 5,
                        "cookie": 1630543494
                    }
                }
            ],
            "HardLinkId": null,
            "HardLinkCounter": 0,
            "Content": null
        }
    ],
    "Limit": 100,
    "LastFileName": "7593d5ff-d922-444f-b26a-aea3c62e1c7d",
    "ShouldDisplayLoadMore": false
}

**Comment by chrislusf** [comment]
Added a fix. Please help to confirm it.

**Comment by qwedsazzcc** [comment]
> Added a fix. Please help to confirm it.

@chrislusf   It's not fix 

I think it's should  call getEntry in CompleteMultipartUploadResult function in filer_multipart.go and save the Extended info 


like

```
        pentry, err := s3a.getEntry(s3a.genUploadsFolder(*input.Bucket),*input.UploadId)
	if err != nil {
		glog.Errorf("completeMultipartUpload %s %s error: %v", *input.Bucket, *input.UploadId, err)
		return nil, s3err.ErrNoSuchUpload
	}
        .......
        err = s3a.mkFile(dirName, entryName, finalParts,func(entry *filer_pb.Entry) {
		if entry.Extended == nil {
			entry.Extended = make(map[string][]byte)
		}
		for k,v := range pentry.Extended{
			entry.Extended[k] = v
		}
	})

```

**Comment by chrislusf** [comment]
Do you want to send a PR?

**Comment by qwedsazzcc** [comment]
> Do you want to send a PR?

https://github.com/chrislusf/seaweedfs/pull/2174
