### ISSUE TITLE
Volume on ARMv7 throws

### ISSUE THREAD

**Issue by sstent** [chrislusf/seaweedfs#2177]
**Describe the bug**
Volume on ARM32 throws an "unaligned 64-bit atomic operation" error on upload of a file

**System Setup**
- /usr/bin/weed volume -ip=odroid3.node.dc1.consul -port=9444 -mserver=seaweedfsmaster0.service.dc1.consul:9333,seaweedfsmaster1.service.dc1.consul:9333,seaweedfsmaster2.service.dc1.consul:9333 -dir=/data/vol
- OS version  = Ubuntu 5.4.118-221  armv7l armv7l armv7l GNU/Linux
- `weed version' = version 30GB 2.56 a2979aa linux arm
- hardware = Odroid HC1 (Samsung Exynos5422 Cortex™-A15 2Ghz and Cortex™-A7 Octa cores)

**Expected behavior**
Not to crash

**Additional context**
2021/07/02 15:46:52 http: panic serving 192.168.1.238:40226: unaligned 64-bit atomic operation
goroutine 101 [running]:
net/http.(*conn).serve.func1(0x32244e0)
	/home/travis/.gimme/versions/go1.16.5.linux.amd64/src/net/http/server.go:1824 +0x104
panic(0x171c1b8, 0x1e1dca8)
	/home/travis/.gimme/versions/go1.16.5.linux.amd64/src/runtime/panic.go:971 +0x4b4
runtime/internal/atomic.panicUnaligned()
	/home/travis/.gimme/versions/go1.16.5.linux.amd64/src/runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Load64(0x31473e4, 0xe5b38, 0x0)
	/home/travis/.gimme/versions/go1.16.5.linux.amd64/src/runtime/internal/atomic/asm_arm.s:263 +0x14
github.com/chrislusf/seaweedfs/weed/server.(*VolumeServer).privateStoreHandler(0x3147380, 0x1e56c4c, 0x34581e0, 0x30de680)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/server/volume_server_handlers.go:49 +0x4bc
net/http.HandlerFunc.ServeHTTP(0x300fa88, 0x1e56c4c, 0x34581e0, 0x30de680)
	/home/travis/.gimme/versions/go1.16.5.linux.amd64/src/net/http/server.go:2069 +0x34
net/http.(*ServeMux).ServeHTTP(0x325b440, 0x1e56c4c, 0x34581e0, 0x30de680)
	/home/travis/.gimme/versions/go1.16.5.linux.amd64/src/net/http/server.go:2448 +0x16c
net/http.serverHandler.ServeHTTP(0x30ec360, 0x1e56c4c, 0x34581e0, 0x30de680)
	/home/travis/.gimme/versions/go1.16.5.linux.amd64/src/net/http/server.go:2887 +0x88
net/http.(*conn).serve(0x32244e0, 0x1e59564, 0x31c09c0)
	/home/travis/.gimme/versions/go1.16.5.linux.amd64/src/net/http/server.go:1952 +0x7f0
created by net/http.(*Server).Serve
	/home/travis/.gimme/versions/go1.16.5.linux.amd64/src/net/http/server.go:3013 +0x318

**Comment by chrislusf** [comment]
Added a fix but need help to verify the fix.

**Comment by sstent** [comment]
Confirmed - working in 2.57

Thanks!

**Comment by sstent** [comment]
I do see a similar issue/error when trying do a lock

Version = 2.57


> lock
panic: unaligned 64-bit atomic operation

goroutine 1 [running]:
runtime/internal/atomic.panicUnaligned()
        /home/travis/.gimme/versions/go1.16.5.linux.amd64/src/runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Load64(0x36aacdc, 0x34de480, 0x8)
        /home/travis/.gimme/versions/go1.16.5.linux.amd64/src/runtime/internal/atomic/asm_arm.s:263 +0x14
github.com/chrislusf/seaweedfs/weed/wdclient/exclusive_locks.(*ExclusiveLocker).RequestLock.func1(0x1e7b77c, 0x34de480, 0x823b01, 0x34de480)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/wdclient/exclusive_locks/exclusive_locker.go:56 +0x4c
github.com/chrislusf/seaweedfs/weed/wdclient.(*MasterClient).WithClient.func1.1(0x1e7b77c, 0x34de480, 0xf, 0x2c027b8)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/wdclient/masterclient.go:161 +0x2c
github.com/chrislusf/seaweedfs/weed/pb.WithMasterClient.func1(0x3414960, 0xf, 0x3835cb4)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/pb/grpc_client_server.go:211 +0x64
github.com/chrislusf/seaweedfs/weed/pb.WithCachedGrpcClient(0x3835cbc, 0x304a1d0, 0xf, 0x3835cb4, 0x1, 0x1, 0x0, 0xb6eec088)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/pb/grpc_client_server.go:120 +0xfc
github.com/chrislusf/seaweedfs/weed/pb.WithMasterClient(0x1a36a45, 0xe, 0x1e59784, 0x34def90, 0x3835cfc, 0xa, 0x0)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/pb/grpc_client_server.go:209 +0x144
github.com/chrislusf/seaweedfs/weed/wdclient.(*MasterClient).WithClient.func1(0x8, 0x8)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/wdclient/masterclient.go:160 +0x94
github.com/chrislusf/seaweedfs/weed/util.Retry(0x1a30c47, 0xb, 0x3835d80, 0x17a7638, 0x34de280)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/util/retry.go:16 +0xdc
github.com/chrislusf/seaweedfs/weed/wdclient.(*MasterClient).WithClient(0x312ed20, 0x3835db8, 0x1e6d1cc, 0x3859000)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/wdclient/masterclient.go:156 +0x5c
github.com/chrislusf/seaweedfs/weed/wdclient/exclusive_locks.(*ExclusiveLocker).RequestLock(0x36aacd8, 0x304a1a0, 0xa)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/wdclient/exclusive_locks/exclusive_locker.go:54 +0x128
github.com/chrislusf/seaweedfs/weed/shell.(*commandLock).Do(0x2c02720, 0x2c02720, 0x0, 0x0, 0x3296cf0, 0x1e5a544, 0x310c0f0, 0xa6bf8190, 0x4)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/shell/command_fs_lock_unlock.go:30 +0x34
github.com/chrislusf/seaweedfs/weed/shell.processEachCmd(0x312e5a0, 0x304a0d9, 0x4, 0x3296cf0, 0x0)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/shell/shell_liner.go:87 +0x310
github.com/chrislusf/seaweedfs/weed/shell.RunShell(0x34dec18, 0x1e59784, 0x34def90, 0x1a36a37, 0x9, 0x22b8, 0x0, 0x1a234dc, 0x1)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/shell/shell_liner.go:58 +0x1a8
github.com/chrislusf/seaweedfs/weed/command.runShell(0x2be07b0, 0x3120018, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/command/shell.go:64 +0x1e4
main.main()
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/weed.go:73 +0x33c
