### ISSUE TITLE
PUT requests with multipart

### ISSUE THREAD

**Issue by spance** [chrislusf/seaweedfs#219]
Hi,

I found that the seaweedfs handle PUT requests only with multipart/form-data for uploading files, and refuses PUT requests with binary entity body.
Here is a quotable discussion that already explained the same issue clearly, see https://github.com/appdotnet/api-spec/issues/281#issue-10418417 .

And I known the seaweedfs need the file name to determine file type and content-type, so we could use `http://localhost:port/fid/fileName` to achieve the same purpose as multipart/form-data encoding, that just reflects HTTP semantics, and also keeps the property of idempotence in PUT method.

On the other hand, the consumption of handling multipart/form-data encoding is more than plain entity encoding, if we want the lower consumption on protocol layer, we have no better choice than PUT method with plain encoding.

Reproduce:

```
curl -v -H "expect:" -T a.h http://localhost:8080/6,014fe24a94
> PUT /6,014fe24a94 HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.42.1
> Accept: */*
> Content-Length: 892727
>
} [16384 bytes data]
< HTTP/1.1 400 Bad Request
< Content-Type: application/json
< Date: Thu, 05 Nov 2015 04:28:26 GMT
< Content-Length: 71
< Connection: close
<
{"error":"request Content-Type isn't multipart/form-data"}

console log:
I1105 12:32:40 02316 needle.go:58] MultipartReader [ERROR] request Content-Type \
 isn't multipart/form-data
```

**Comment by chrislusf** [comment]
Good to know this is a bug!

**Comment by spance** [comment]
Well, we could consider PUT policy like this:
```
PUT http://host:port/fid/fileName
OR
PUT http://host:port/fid  # with header 'Content-Type: image/xyz'
```
And the request must give 'Content-Length' header to determine a complete file.

**Comment by faaliyet** [comment]
Thanks @spance, I also found that, but didn't report this because I was thinking that I'm the only one who thinks it's a wrong design. Hopefully, there are other developers who agree with this.

 +1 :+1:

**Comment by chrislusf** [comment]
multipart file upload is already supported
