### ISSUE TITLE
failed to write to local disk: volume 2028 is read only

### ISSUE THREAD

**Issue by winwill2012** [chrislusf/seaweedfs#2203]
when i upload picture, weed return 
```
{"error":"failed to write to local disk: volume 2028 is read only"}
```
![image](https://user-images.githubusercontent.com/9719716/126316226-077f3cd4-7c79-4d62-a7c1-4ac2e366398b.png)

Disk usage is only `83%` 

![image](https://user-images.githubusercontent.com/9719716/126316272-07686494-34cc-4f84-b535-041a9d7216c1.png)

weed version: 1.88

I don't know how to resolve it.

**Comment by chrislusf** [comment]
Did restart help?

Also, please upgrade first in case this needs some fixes.

**Comment by winwill2012** [comment]
restart also can not resolve it.

**Comment by chrislusf** [comment]
do you use filer?

**Comment by chrislusf** [comment]
Please answer questions in the issue template.

**Comment by winwill2012** [comment]
Thanks，I already solved！
1. Restart voume service;
2. Wating for a few minutes;
3. Weed will assgin new volumes to store new files;
