### ISSUE TITLE
Filer leveldb3 performance considerations 

### ISSUE THREAD

**Issue by divanikus** [chrislusf/seaweedfs#2205]
We seem to hit some limitations of `filer`'s `leveldb3` storage and need some help on how to overcome them.
Our system is writing data to daily buckets. Once we have found that `chunk` and `put` operations suddenly doubled their execution time.

![image](https://user-images.githubusercontent.com/3438036/126405591-551a4128-7916-43ac-be77-241ccb1fb5af.png)

As you may see on the graph, at first it was at 50 ms, than doubled to 100 ms, later is became 200 ms and suddenly 400 ms. You may say that's 99th percentile and not a big deal, but we see all our ops are slowed down by exactly that time! Eventhough 80th percentile doesn't look that bad, slowdown is visible there too.

![image](https://user-images.githubusercontent.com/3438036/126405890-ad3831ba-0df6-4bf2-8ac4-6ca18a30db12.png)

Seems like it is related to number of files in the bucket, because starting a fresh bucket resets the request times to normal values. 

I guess we are doing something wrong, like writing too many files into one folder or something like that. Can you please give us a hint on what we can do to reduce filer requests time?

**Comment by chrislusf** [comment]
does separate into more buckets help?

**Comment by divanikus** [comment]
Currently we have one bucket per day. We thought on splitting it to lesser intervals like 6 hours per bucket or something like that. Simply starting a fresh bucket with zero files resets the request time.

**Comment by chrislusf** [comment]
How many files in a folder?
