### ISSUE TITLE
snowflake sequencer assumes hashing host:port to 1024 integers never collides

### ISSUE THREAD

**Issue by tv42** [chrislusf/seaweedfs#2213]
Reading v2.59 source, the snowflake sequencer assigns host id by hash(host:port) % 0x3ff.
1024 choices isn't all that many.
If I'm using my calculator correctly, a 3-master cluster will hit it 0.3% and 5-master 1% of the time.

Maybe `[master.sequencer]` `type="snowflake"` needs to take an ID, and refuse to work without a user-assigned one?
(Or, if the nodes are supposed to share the config file, a mapping from host:port to ID?)

**Comment by chrislusf** [comment]
Thanks for your analysis and suggestion!
