### ISSUE TITLE
Wildcard or *ALL_COLLECTIONS* for volume.tier.move?

### ISSUE THREAD

**Issue by divanikus** [chrislusf/seaweedfs#2219]
I'm using `volume.tier.move` for quite a while already. Currently I'm using separate scripts for migrations, which are getting bucket list with ssd volumes and then move them one by one. It would very nice to somehow exclude that logic and instead of running something like that:
```
volume.tier.move -collection="my-bucket-2021-07-26" -quietFor=86400s -fullPercent=0 -fromDiskType=ssd -toDiskType=hdd -force
```
better add to my master.toml something like this
```
volume.tier.move -quietFor=86400s -fullPercent=0 -fromDiskType=ssd -toDiskType=hdd -force
```
or this
```
volume.tier.move -collection="my-bucket-*" -quietFor=86400s -fullPercent=0 -fromDiskType=ssd -toDiskType=hdd -force
```
and let the cluster to migrate my data automagically.

**Comment by chrislusf** [comment]
Could you please try to add this feature?
All the logic is in this file https://github.com/chrislusf/seaweedfs/blob/master/weed/shell/command_volume_tier_move.go

I believe you can do it even not familiar with Go.

**Comment by divanikus** [comment]
Yeah, I've found it by myself too. Well, I'll try to give it a shot in a while.

**Comment by divanikus** [comment]
So, I've made a simple edit to allow wildcards, or choose all collections if nothing specified. I'm not sure if error handling of `filepath.Match` is done properly though.

**Comment by chrislusf** [comment]
Looks good! Thanks!
