### ISSUE TITLE
[fuse] read image fail

### ISSUE THREAD

**Issue by paochiang** [chrislusf/seaweedfs#2220]
**Describe the bug**
read image fail

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
```
# setup master
weed master -port=9333 -mdir=/tmp/master0 -defaultReplication=000 -ip=localhost
# setup volume
weed volume -port=8080 -dir=/tmp/volume0 -ip=localhost -mserver=localhost:9333
# setup filer
weed filer -port=8888  -ip=localhost -master=localhost:9333
# weed mount
weed -v 4 mount -filer=localhost:8888 -cacheCapacityMB=0 -cacheDir=/tmp/cache001 -dir=/root/mnt >> tmp_3.log 2>&1 &
```

- OS version
`Ubuntu 18.04.4 LTS`
- output of `weed version`
`version 30GB 2.60 5dede5d linux amd64`
- if using filer, show the content of `filer.toml`
```
[mongodb]
enabled = true
uri = "mongodb://localhost:27017"
option_pool_size = 0
database = "seaweedfs"
```

**Expected behavior**
read image succeed

**Screenshots**

**Additional context**
read image py file:
```
import cv2
import os
import time
cc = 0
def read_img(x):
    global cc
    img = cv2.imread(x)
    if img is not None:
        cc = cc + 1
    else:
        print(f"{time.strftime('%Y-%m-%d %H:%M:%S', time.localtime())}: read image fail,path:{x}")
    return True
filePath=r"/root/mnt/2020-10-23_1276_printed_barcode%%" # 文件夹路径
fileList=os.listdir(filePath)
for file in fileList:
    input_path = os.path.join(filePath, file)
    result = read_img(input_path)
print("succeed count:", cc)
```
output:
```
2021-07-27 17:17:50: read image fail,path:/root/mnt/2020-10-23_1276_printed_barcode%%/227ae923-0e91-4d14-948f-9a0e68d3b4f1#0#2865092277260#2020-10-23T06-05-38.431697#-44.05.jpg
succeed count: 2479
```
weed mount  logs:
[weed mount log](https://github.com/paochiang/data/blob/main/weed_mount_v4.log)

The image that failed every time is random.  
Local file system reads no problem.

**Comment by paochiang** [comment]
image data: [image zip](https://github.com/paochiang/data/blob/main/2020-10-23_1276_printed_barcode%25%25.zip)

**Comment by chrislusf** [comment]
I do not see error in the logs.

**Comment by paochiang** [comment]
Sometimes get errors like these:
```
root@dev-4:~# python3 read.py
2021-07-27 19:19:38: read image fail,path:/root/mnt/2020-10-23_1276_printed_barcode%%/2a8142f4-34d1-4cd8-9d02-4bcebf04be07#0#9923971517050#2020-10-23T04-32-23.190884#53.99.jpg
libpng error: Not a PNG file
2021-07-27 19:19:46: read image fail,path:/root/mnt/2020-10-23_1276_printed_barcode%%/a8de798c-e069-4552-a441-0796fe26b9ff#0#5728319836701#2020-10-23T07-00-05.718988#-40.90#barcode_0#-40.90.png
succeed count: 2478
```

total 2480 images

**Comment by paochiang** [comment]
https://github.com/opencv/opencv-python/issues/406#issuecomment-716398140

I think it may be related to seaweedfs use UTF-8 coding.

**Comment by paochiang** [comment]
Change the`img = cv2.imread(x)`  to `cv2.imdecode(np.fromfile(x, dtype=np.uint8), -1)`, then read the image is ok.

But usually this is used to solve the problem of CV2 reading non-ASCII file names: https://stackoverflow.com/questions/43185605/how-do-i-read-an-image-from-a-path-with-unicode-characters/43185606

**Comment by chrislusf** [comment]
The path needs to support non-ASCII characters. So it is a problem of cv2 handling non-ASCII names?

**Comment by paochiang** [comment]
I'm not sure, just guessing may be related to this reason.  And I don't know why reading image(`cv2.imread`) in the filesystem mounted by 'weed mount' will randomly error.

**Comment by paochiang** [comment]
I'm not sure, just guessing may be related to this reason.  And I don't know why reading image(`cv2.imread`) in the filesystem mounted by 'weed mount' will randomly error.

**Comment by paochiang** [comment]
I'm not sure, just guessing may be related to this reason.  And I don't know why reading image(`cv2.imread`) in the filesystem mounted by `weed mount` will randomly error.

**Comment by paochiang** [comment]
I'm not sure, just guessing may be related to this reason.  And I don't know why reading image(`cv2.imread`) in the filesystem mounted by `weed mount` will randomly error.

**Comment by chrislusf** [comment]
Not clear what is the next step here. Closing.
