### ISSUE TITLE
orphan volume created

### ISSUE THREAD

**Issue by combineads** [chrislusf/seaweedfs#2222]
When uploading the bulk data, the server disk capacity is full by the volume_growth logic.
However, I look at the actual data directory, the created volume is not visible on the volume server and only takes up capacity.
Can I manually delete these orphaned volumes using the rm command?
And I think I should look for a bug in the volume_growth logic when the disk is full.

`
# du * | sort -h
...
30720000	16857.dat
30720000	16862.dat
30720000	16867.dat
30720000	16872.dat
30720000	16873.dat
30720000	16876.dat
30720000	16882.dat
30720000	16893.dat
30720000	16902.dat
30720000	16909.dat
30720000	16924.dat
30720000	16927.dat
30720000	16939.dat
30720000	16940.dat
30720000	16948.dat
30720000	16950.dat
30720000	16954.dat
30720000	16958.dat
30720000	16993.dat
30720000	16996.dat
30720000	17004.dat
30720004	17002.dat
30720004	17005.dat
30720004	17012.dat
30720008	16997.dat
30720020	16983.dat
30720028	16973.dat
30720072	17032.dat
30720076	16959.dat
30720128	17036.dat
30720232	17021.dat
30720256	17028.dat
30720880	17023.dat
...
`

**Comment by chrislusf** [comment]
seems you enabled volume disk space preallocation. 

you can delete these files.
