### ISSUE TITLE
Multi server fail

### ISSUE THREAD

**Issue by jiaqigan** [chrislusf/seaweedfs#2227]
I tried to start multi servers between three devices,  however the connection would only remain for several minutes, then there is an error: "master masterClient failed to receive from 192.168.196.129:9333: EOF".

The commands I used are: 
./weed -logdir=./data/log/master server -master.port=9333 -dir=./master -volume.port=8080 -master.peers=192.168.196.129:9333,192.168.196.130:9334,192.168.196.131:9335
./weed -logdir=./data/log/master server -master.port=9334 -dir=./master -volume.port=8081 -master.peers=192.168.196.129:9333,192.168.196.130:9334,192.168.196.131:9335
./weed -logdir=./data/log/master server -master.port=9335 -dir=./master -volume.port=8082 [-master.peers=192.168.196.129:9333,192.168.196.130:9334,192.168.196.131:9335](url)

The error message I got:
I0801 07:13:10 65658 raft_server.go:154] Initializing new cluster
I0801 07:13:10 65658 master_server.go:156] leader change event:  => 192.168.196.129:9333
I0801 07:13:10 65658 master_server.go:158] [ 192.168.196.129:9333 ] 192.168.196.129:9333 becomes leader.
I0801 07:13:10 65658 master_grpc_server.go:249] + client master@192.168.196.130:48880
I0801 07:13:10 65658 disk_location.go:176] Store started on dir: ./master with 0 volumes max 8
I0801 07:13:10 65658 disk_location.go:179] Store started on dir: ./master with 0 ec shards
I0801 07:13:10 65658 volume.go:352] Start Seaweed volume server 30GB 2.60 5dede5d at :8080
I0801 07:13:10 65658 volume_grpc_client_to_master.go:52] Volume server start with seed master nodes: [192.168.196.129:9333 192.168.196.130:9334 192.168.196.131:9335]
I0801 07:13:10 65658 volume_grpc_client_to_master.go:114] Heartbeat to: 192.168.196.129:9333
I0801 07:13:10 65658 node.go:222] topo adds child DefaultDataCenter
I0801 07:13:10 65658 node.go:222] topo:DefaultDataCenter adds child DefaultRack
I0801 07:13:10 65658 node.go:222] topo:DefaultDataCenter:DefaultRack adds child 192.168.196.129:8080
I0801 07:13:10 65658 node.go:222] topo:DefaultDataCenter:DefaultRack:192.168.196.129:8080 adds child 
I0801 07:13:10 65658 master_grpc_server.go:71] added volume server 192.168.196.129:8080
I0801 07:13:11 65658 master_grpc_server.go:249] + client master@192.168.196.131:59154
I0801 07:13:14 65658 master_grpc_server.go:249] + client master@192.168.196.129:35334
I0801 07:13:15 65658 node.go:222] topo:DefaultDataCenter:DefaultRack adds child 192.168.196.131:8082
I0801 07:13:15 65658 node.go:222] topo:DefaultDataCenter:DefaultRack:192.168.196.131:8082 adds child 
I0801 07:13:15 65658 master_grpc_server.go:71] added volume server 192.168.196.131:8082
I0801 07:13:15 65658 node.go:222] topo:DefaultDataCenter:DefaultRack adds child 192.168.196.130:8081
I0801 07:13:15 65658 node.go:222] topo:DefaultDataCenter:DefaultRack:192.168.196.130:8081 adds child 
I0801 07:13:15 65658 master_grpc_server.go:71] added volume server 192.168.196.130:8081
I0801 07:14:06 65658 master_grpc_server.go:265] - client master@192.168.196.130:48880
I0801 07:14:07 65658 master_grpc_server.go:265] - client master@192.168.196.131:59154
I0801 07:14:10 65658 master_grpc_server.go:265] - client master@192.168.196.129:35334
I0801 07:14:10 65658 masterclient.go:121] master masterClient failed to receive from 192.168.196.129:9333: EOF
I0801 07:14:47 65658 masterclient.go:121] master masterClient failed to receive from 192.168.196.129:9333: EOF
I0801 07:15:24 65658 masterclient.go:121] master masterClient failed to receive from 192.168.196.129:9333: EOF
I0801 07:16:01 65658 masterclient.go:121] master masterClient failed to receive from 192.168.196.129:9333: EOF
I0801 07:16:38 65658 masterclient.go:121] master masterClient failed to receive from 192.168.196.129:9333: EOF

**Comment by chrislusf** [comment]
Need to set "-ip=xxxxx"

**Comment by jiaqigan** [comment]
I changed my commands to to:
./weed -logdir=./data/log/master server -ip=192.168.196.129 -master.port=9333 -dir=./master -volume.port=8080 -master.peers=192.168.196.129:9333,192.168.196.130:9334,192.168.196.131:9335
./weed -logdir=./data/log/master server -ip=192.168.196.130 -master.port=9334 -dir=./master -volume.port=8081 -master.peers=192.168.196.129:9333,192.168.196.130:9334,192.168.196.131:9335
./weed -logdir=./data/log/master server -ip=192.168.196.131 -master.port=9335 -dir=./master -volume.port=8082 -master.peers=192.168.196.129:9333,192.168.196.130:9334,192.168.196.131:9335

The log info are the same:
I0801 19:03:03 74866 raft_server.go:154] Initializing new cluster
I0801 19:03:03 74866 master_server.go:156] leader change event:  => 192.168.196.129:9333
I0801 19:03:03 74866 master_server.go:158] [ 192.168.196.129:9333 ] 192.168.196.129:9333 becomes leader.
I0801 19:03:03 74866 disk_location.go:176] Store started on dir: ./master with 0 volumes max 8
I0801 19:03:03 74866 disk_location.go:179] Store started on dir: ./master with 0 ec shards
I0801 19:03:03 74866 volume.go:352] Start Seaweed volume server 30GB 2.60 5dede5d at :8080
I0801 19:03:03 74866 volume_grpc_client_to_master.go:52] Volume server start with seed master nodes: [192.168.196.129:9333 192.168.196.130:9334 192.168.196.131:9335]
I0801 19:03:03 74866 volume_grpc_client_to_master.go:114] Heartbeat to: 192.168.196.129:9333
I0801 19:03:03 74866 node.go:222] topo adds child DefaultDataCenter
I0801 19:03:03 74866 node.go:222] topo:DefaultDataCenter adds child DefaultRack
I0801 19:03:03 74866 node.go:222] topo:DefaultDataCenter:DefaultRack adds child 192.168.196.129:8080
I0801 19:03:03 74866 node.go:222] topo:DefaultDataCenter:DefaultRack:192.168.196.129:8080 adds child 
I0801 19:03:03 74866 master_grpc_server.go:71] added volume server 192.168.196.129:8080
I0801 19:03:03 74866 master_grpc_server.go:249] + client master@192.168.196.130:49520
I0801 19:03:06 74866 master_grpc_server.go:249] + client master@192.168.196.131:59640
I0801 19:03:06 74866 master_grpc_server.go:249] + client master@192.168.196.129:37972
I0801 19:03:06 74866 node.go:222] topo:DefaultDataCenter:DefaultRack adds child 192.168.196.130:8081
I0801 19:03:06 74866 node.go:222] topo:DefaultDataCenter:DefaultRack:192.168.196.130:8081 adds child 
I0801 19:03:06 74866 master_grpc_server.go:71] added volume server 192.168.196.130:8081
I0801 19:03:07 74866 node.go:222] topo:DefaultDataCenter:DefaultRack adds child 192.168.196.131:8082
I0801 19:03:07 74866 node.go:222] topo:DefaultDataCenter:DefaultRack:192.168.196.131:8082 adds child 
I0801 19:03:07 74866 master_grpc_server.go:71] added volume server 192.168.196.131:8082
I0801 19:03:59 74866 master_grpc_server.go:265] - client master@192.168.196.130:49520
I0801 19:04:02 74866 master_grpc_server.go:265] - client master@192.168.196.131:59640
I0801 19:04:02 74866 master_grpc_server.go:265] - client master@192.168.196.129:37972
I0801 19:04:02 74866 masterclient.go:121] master masterClient failed to receive from 192.168.196.129:9333: EOF
I0801 19:04:39 74866 masterclient.go:121] master masterClient failed to receive from 192.168.196.129:9333: EOF

And I can't open http://192.168.196.129:9333/

**Comment by chrislusf** [comment]
works fine for me...

can not tell. maybe some network configuration issue?

If you find anything, please let me know.
