### ISSUE TITLE
JWT for http://<master>:<port>/submit

### ISSUE THREAD

**Issue by wangrd** [chrislusf/seaweedfs#2229]
I have got that we can set the security for mater and vlolume, and I have tried it following the [guide](https://github.com/chrislusf/seaweedfs/wiki/Security-Overview). But it seems not work when I request with `http://<master>:<port>/submit`,It always success ess even I don't have the auth key. However it works when I upload file through VolumeServer then retuen the 'jwt error'. that is intentional or juest not finish yet?

**Comment by chrislusf** [comment]
this is expected.

JWT is to protect volume servers when "unprotected" volume servers are spread in different places.

Having access to master means the client can get JWT from the master. There is no need to check JWT when submitting through master.

**Comment by wangrd** [comment]
am.... so how can I prevent expected uploads when some one konws the master's IP. that means they can put many junk files into my service, and let it down.

**Comment by wangrd** [comment]
> this is expected.
> 
> JWT is to protect volume servers when "unprotected" volume servers are spread in different places.
> 
> Having access to master means the client can get JWT from the master. There is no need to check JWT when submitting through master.

thanks for replay. am.... so how can I prevent expected uploads when some one konws the master's IP. that means they can put many junk files into my service, and let it down.

**Comment by chrislusf** [comment]
> thanks for reply. am.... so how can I prevent unexpected uploads when some one konws the master's IP. that means they can put many junk files into my service, and let it down.

Secure your master by putting it behind some proxy.

**Comment by wangrd** [comment]
> > thanks for reply. am.... so how can I prevent unexpected uploads when some one konws the master's IP. that means they can put many junk files into my service, and let it down.
> 
> Secure your master by putting it behind some proxy.

oh, now I see. I have thought that it also works on master becouse the `security.toml` also be seted in master.

**Comment by wangrd** [comment]
oh, now I see. I have thought that it also works on master becouse the `security.toml` also be seted in master.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Chris ***@***.***&gt;; 
发送时间: 2021年8月2日(星期一) 下午4:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chrislusf/seaweedfs] JWT for http://<master&gt;:<port&gt;/submit (#2229)





  
thanks for reply. am.... so how can I prevent unexpected uploads when some one konws the master's IP. that means they can put many junk files into my service, and let it down.
  
Secure your master by putting it behind some proxy.
 
&mdash;
