### ISSUE TITLE
enhance for filer [suggest]

### ISSUE THREAD

**Issue by lshengjian** [chrislusf/seaweedfs#223]
A file can only be stored in a directory. But in the knowledge management system, a knowledge can be retrieved from multiple threads.

**Comment by chrislusf** [comment]
Filer organizes files via directory. It seems this would need a tagging system.

**Comment by lshengjian** [comment]
Tagging system is too simple to meet the requirements. What I need is multi-dimensional retrieval. According to the geographical dimensions, for example, can be divided into seven continents, Asia can be divided into China, Japan, etc., and each country can be divided into provinces, etc. Also can according to the time dimension, BC and  every century, etc.

**Comment by lshengjian** [comment]
Perhaps we can separate to make a knowledge system to manage these basic documents, can consider to use MongoDB to save these information retrieval.

**Comment by chrislusf** [comment]
This can get fairly complicated and is out of the scope for filer. It's
better just use seaweedfs to store blobs and associate the file key to the
tags.
