### ISSUE TITLE
[Performance] Just get the file's headers

### ISSUE THREAD

**Issue by wangrd** [chrislusf/seaweedfs#2233]
I have a question about that, will it would to read the content of the file into momery when I just get headers from `http://<volume>:<port>/fid` API？If so, that may means a lot of performance loss.

**Comment by chrislusf** [comment]
Correct. There are no special optimization for HEAD operation yet.

PR is welcome!

**Comment by chrislusf** [comment]
I checked the code. Supporting this is not trivial. Do you actually see the performance problem or just "think" there would be?

**Comment by wangrd** [comment]
I try to save some basic info of the file via 'Seaweef-' header, like path,sender's Ip and so on. thus may have many request just ask for that headers to judge&nbsp;
whether to continnue. As I understand it, the file's content also be loaded in momery but just not return to client. I have not try the&nbsp;
pressure test yet.
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chrislusf/seaweedfs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月3日(星期二) 中午1:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chrislusf/seaweedfs] [Performance] Just get the file's headers (#2233)





 
I checked the code. Supporting this is not trivial. Do you actually see the performance problem or just "think" there would be?

**Comment by wangrd** [comment]
If it won't work,I will must save it to another place eg. oracle. it may not a optimal pattern.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangrd"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月3日(星期二) 中午1:50
***@***.***&gt;;

主题:&nbsp;回复： [chrislusf/seaweedfs] [Performance] Just get the file's headers (#2233)



I try to save some basic info of the file via 'Seaweef-' header, like path,sender's Ip and so on. thus may have many request just ask for that headers to judge 
whether to continnue. As I understand it, the file's content also be loaded in momery but just not return to client. I have not try the 
pressure test yet.
------------------ 原始邮件 ------------------
发件人:                                                                                                                        "chrislusf/seaweedfs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月3日(星期二) 中午1:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chrislusf/seaweedfs] [Performance] Just get the file's headers (#2233)





 
I checked the code. Supporting this is not trivial. Do you actually see the performance problem or just "think" there would be?

**Comment by chrislusf** [comment]
If using filer, the headers are in file metadata stored in filer store.

**Comment by wangrd** [comment]
Thanks a lot.
I have got it too,&nbsp;since I know the path of file is saved in filer.&nbsp;

**Comment by wangrd** [comment]
> If using filer, the headers are in file metadata stored in filer store.

By the way,is it necsssary if I want to upload file by range?

**Comment by wangrd** [comment]
> > If using filer, the headers are in file metadata stored in filer store.
> 
> By the way,is it necessary to use filer if I want to upload file by range?

**Comment by chrislusf** [comment]
append is only in filer.

**Comment by wangrd** [comment]
> > > If using filer, the headers are in file metadata stored in filer store.
> > 
> > 
> > By the way,is it necessary to use filer if I want to upload file by range?



> append is only in filer.

ok,thanks very much. 👍
