### ISSUE TITLE
`volume.fix.replication` retries even when there is no error

### ISSUE THREAD

**Issue by PeterCxy** [chrislusf/seaweedfs#2235]
**Describe the bug**

Setting the `-retry` option on `volume.fix.replication` causes it to retry for the given number of times even when there has been no error.

**Expected behavior**

It should only retry when there is error

**Screenshots**

![2021-08-03_19-12](https://user-images.githubusercontent.com/4532423/128006099-bd7b9dea-dd74-40e0-b99d-d073d8fda33a.png)

**Additional context**

It seems that the `continue` directive [here](https://github.com/chrislusf/seaweedfs/blob/master/weed/shell/command_volume_fix_replication.go#L163) should be `break` instead.

**Comment by chrislusf** [comment]
Thanks for the detail and debugging. Fixed. You are welcome to make a PR.

**Comment by PeterCxy** [comment]
Thanks, I didn't have a dev environment set up locally when I submitted the issue, and since I could not test if the finding was correct I didn't submit a PR.
