### ISSUE TITLE
Limitations of using Redis as filer-store

### ISSUE THREAD

**Issue by andreak** [chrislusf/seaweedfs#2236]
According to this:
https://github.com/chrislusf/seaweedfs/wiki/Filer-Stores
There's a limitation of "number of entries in a folder", which is described as "limited". What exactly is the limit?
Thanks.

**Comment by chrislusf** [comment]
For one directory, all the entries are stored in one blob.
Limited by memory size, read/write latency.

**Comment by andreak** [comment]
Thanks, are we talking millions, or billions of entries, do you know?
Does this only impact listing directories or direct access to files using filer-http?
Thanks.

**Comment by chrislusf** [comment]
The limit is for millions of directory entries for one directory.

This impacts listing.

**Comment by andreak** [comment]
Ok.
Sorry for "nagging" about this, but I just want to understand the performance-characteristics of using Redis with lots of file-entries in one `filer`-folder. We use folders in `filer` only as "containers", so the "real" (actual) folder/name structure is maintained using a custom DB "outside of SeaweedFS", so we might get to the point where we'll have billions of files in one `filer`-folder.
Will it impact POST/GET-performance (of single files) of `filer` as long as we don't list directories using `filer`?

**Comment by chrislusf** [comment]
Writing may get affected.

There is also an option "superLargeDirectories", if you do not need directory listing.

**Comment by chrislusf** [comment]
See https://github.com/chrislusf/seaweedfs/wiki/Super-Large-Directories

**Comment by andreak** [comment]
Nice, we don't need directory listing, thanks!
