### ISSUE TITLE
error: need to lock to continue

### ISSUE THREAD

**Issue by cherishman2005** [chrislusf/seaweedfs#2239]
**Describe the bug**

```
 echo "volume.move *.*.*.*:9622 *.*.*.*:9622 5456" |  /data/services/svr_seaweedfs_volume_d-1.0.0.15/bin/svr_seaweedfs_volume_d shell
```

running result:
```
error: need to lock to continue
```

how to resolve it with lock?

**Comment by combineads** [comment]
echo "lock; volume.move *.*.*.*:9622 *.*.*.*:9622 5456; unlock " | weed shell
or
echo "lock
volume.move *.*.*.*:9622 *.*.*.*:9622 5456
unlock " | weed shell

I don't know if it works in older versions as well.

**Comment by cherishman2005** [comment]
> echo "lock; volume.move _._._._:9622 _._._._:9622 5456; unlock " | weed shell
> or
> echo "lock
> volume.move _._._._:9622 _._._._:9622 5456
> unlock " | weed shell
> 
> I don't know if it works in older versions as well.

it's ok, thx!
