### ISSUE TITLE
How can I appoint the rack forcely?

### ISSUE THREAD

**Issue by wangrd** [chrislusf/seaweedfs#2240]
Is there a way to appoint the named rack forcely similar to the colecttion? as we know the `rack` parameter is only  preferred.

**Comment by wangrd** [comment]
When I appoint the rack' name by `http://localhost:9333/dir/assign?rack=temp`, but still returns a rendom volume id just like not appoint that the volume may not belong to the rack 'temp'.

**Comment by wangrd** [comment]
> When I appoint the rack' named by `http://localhost:9333/dir/assign?rack=temp`, but it still returns a rendom volume id just like not appoint to that the volume may not belong to the rack 'temp'.

In my test,it's necessary to appoint then datacenter when we want to appoint the rack.And if not, the `rack`parameter doesn't work...

**Comment by chrislusf** [comment]
rack and data center go together. 

rack name can be the same in different data centers.
