### ISSUE TITLE
gRpc connection error on filer when no volume left

### ISSUE THREAD

**Issue by mauroparente** [chrislusf/seaweedfs#2243]
After uploading a file by mounted volume when no more volumes can be created, the filer start to report multiple gRpc connection error and randomly error "volume X not found".

**System Setup**
**OS:** CentOS 7 - WSL2 on Windows 10
**Master**: /usr/sbin/weed master -mdir=/home/trogo/seaweed/masterData -volumeSizeLimitMB=10 -port=9333 -defaultReplication=000
**Volume**: /usr/sbin/weed volume -dir=/home/trogo/seaweed/volumeData -max=6 -mserver=127.0.0.1:9333
**Filer**: /usr/sbin/weed filer -port=8888 -master=127.0.0.1:9333
**MountPoint:** weed  mount -filer=127.0.0.1:8888 -dir=/home/trogo/seaweed/filerMount

This is the starting situation: only 1 volume has available space left (vol. 2) and no more volumes can be allocated. The volume 2 is "crowded".

```
> volume.list
Topology volumeSizeLimit:10 MB hdd(volume:6/6 active:6 free:0 remote:0)
  DataCenter DefaultDataCenter hdd(volume:6/6 active:6 free:0 remote:0)
    Rack DefaultRack hdd(volume:6/6 active:6 free:0 remote:0)
      DataNode 192.168.225.128:8080 hdd(volume:6/6 active:6 free:0 remote:0)
        Disk hdd(volume:6/6 active:6 free:0 remote:0)
          volume id:1  size:10618872  file_count:12  delete_count:1  deleted_byte_count:1048594  version:3  modified_at_second:1628351965
          volume id:2  size:9468216  file_count:14  version:3  compact_revision:1  modified_at_second:1628353537
          volume id:3  size:10597896  file_count:17  delete_count:2  deleted_byte_count:1091827  version:3  modified_at_second:1628353500
          volume id:4  size:10531264  file_count:13  delete_count:4  deleted_byte_count:3145857  version:3  modified_at_second:1628353500
          volume id:5  size:10515352  file_count:8  delete_count:2  deleted_byte_count:3145765  version:3  modified_at_second:1628351976
          volume id:6  size:11638272  file_count:11  delete_count:2  deleted_byte_count:3145764  version:3  modified_at_second:1628351655
        Disk hdd total size:63369872 file_count:75 deleted_file:11 deleted_bytes:11577807
      DataNode 192.168.225.128:8080 total size:63369872 file_count:75 deleted_file:11 deleted_bytes:11577807
    Rack DefaultRack total size:63369872 file_count:75 deleted_file:11 deleted_bytes:11577807
  DataCenter DefaultDataCenter total size:63369872 file_count:75 deleted_file:11 deleted_bytes:11577807
total size:63369872 file_count:75 deleted_file:11 deleted_bytes:11577807
```

Trying to upload a new file result in an error even if there is available space in existing volume.
When we try to upload by filer WebUI i can't upload, but no other error.
When we try to create a new file in mounted folder (with "weed mount"), we have an error same as above, but the filer service start to log continuous error:

```
0809 09:01:08    21 masterclient.go:121] filer masterClient failed to receive from 127.0.0.1:9333: rpc error: code = Canceled desc = grpc: the client connection is closing
I0809 09:01:08    19 master_grpc_server.go:265] - client filer@127.0.0.1:8888
I0809 09:01:09    19 master_grpc_server.go:249] + client filer@127.0.0.1:8888
I0809 09:01:11    21 masterclient.go:121] filer masterClient failed to receive from 127.0.0.1:9333: rpc error: code = Canceled desc = grpc: the client connection is closing
I0809 09:01:11    19 master_grpc_server.go:265] - client filer@127.0.0.1:8888
I0809 09:01:12    19 master_grpc_server.go:249] + client filer@127.0.0.1:8888
I0809 09:01:14    21 masterclient.go:121] filer masterClient failed to receive from 127.0.0.1:9333: rpc error: code = Canceled desc = grpc: the client connection is closing
I0809 09:01:14    19 master_grpc_server.go:265] - client filer@127.0.0.1:8888
I0809 09:01:15    19 master_grpc_server.go:249] + client filer@127.0.0.1:8888
```

After this error we start having randomly error on access existing files by HTTP:

`E0809 09:13:23    21 filer_server_handlers_read.go:168] failed to stream content /01.png: volume 6 not found`

**Comment by chrislusf** [comment]
what is the expected behavior?

**Comment by mauroparente** [comment]
Hi Chris,
I expect the filer continues to deliver existing image correctly.

If I restart the filer service, the error disappears, until the next upload attempt, and the delivery work correctly.

**Comment by mauroparente** [comment]
Hi Chris,
after enabling verbose log on all service, i think found the problem. The Filer service try to write a log in /topics/.system/log/YYY-MM-DD/XX-YY.segment without success. In this case happen an infinite loop in code.

https://github.com/chrislusf/seaweedfs/blob/85832d02c0a44250d4630c7951e97fcd4e7dd8c1/weed/filer/filer_notify.go#L100

This is the Filer log
```
I0810 11:55:36    15 filer_notify.go:102] log write failed /topics/.system/log/2021-08-10/11-37.segment: AssignVolume: rpc error: code = Unknown desc = no free volumes left for {"replication":{},"ttl":{"Count":0,"Unit":0}}
I0810 11:55:37    15 filer_notify.go:102] log write failed /topics/.system/log/2021-08-10/11-37.segment: AssignVolume: rpc error: code = Unknown desc = no free volumes left for {"replication":{},"ttl":{"Count":0,"Unit":0}}
I0810 11:55:38    15 filer_notify.go:102] log write failed /topics/.system/log/2021-08-10/11-37.segment: AssignVolume: rpc error: code = Unknown desc = no free volumes left for {"replication":{},"ttl":{"Count":0,"Unit":0}}
I0810 11:55:39    15 filer_notify.go:102] log write failed /topics/.system/log/2021-08-10/11-37.segment: AssignVolume: rpc error: code = Unknown desc = no free volumes left for {"replication":{},"ttl":{"Count":0,"Unit":0}}
```

I changed the infinite for loop by adding a limited number of retry and with this modification the Filer continues to deliver the exising content whitout error after the failed upload, but i think there is a better fix for that problem.

**Comment by chrislusf** [comment]
Thanks for your detailed report! And your investigation helped a lot to identify the root problem. Thanks!
