### ISSUE TITLE
Filer is not working properly with cassandra cluster

### ISSUE THREAD

**Issue by t4nmoy** [chrislusf/seaweedfs#2246]
I have 3 nodes Cassandra cluster and it's used by a filer server. I have configured filer for super large directories. If I take one of the Cassandra nodes down then sometimes read request on filer does not find the requested file until I restart the filer. After restarting the filer it works normally with the two Cassandra nodes and can find the file.

**Comment by chrislusf** [comment]
SeaweedFS version?

**Comment by t4nmoy** [comment]
SeaweedFS version:  2.60

**Comment by t4nmoy** [comment]
somehow the filer does not have the updated cluster information when the cluster orientation has been changed

**Comment by chrislusf** [comment]
Added a fix 9d85569c55a19097c90520e215224c4765b117be for this.

**Comment by t4nmoy** [comment]
Thanks

**Comment by nivekuil** [comment]
If restarting the filer makes a difference then I think the problem here is probably not cassandra consistency but the client not reconnecting, as in https://github.com/gocql/gocql/pull/1555 or https://github.com/gocql/gocql/issues/915

**Comment by chrislusf** [comment]
@nivekuil Thanks for checking and your analysis is very reasonable.
