### ISSUE TITLE
[Version 2.62] Volume server crash when i access file from public url

### ISSUE THREAD

**Issue by hunglsxx** [chrislusf/seaweedfs#2247]
Hi currently I install 1 cluster including a master and 1 volume for testing.
I have successfully pushed the file, but when I access the file through the public path (http), the volume server crashes immediately.
The error is reported below, I use version 2.62. Please check, many thanks
![Screenshot from 2021-08-11 01-27-37](https://user-images.githubusercontent.com/50700597/128915060-ca405659-512e-4470-bbbd-40501eb991b0.png)

![Screenshot from 2021-08-11 01-27-02](https://user-images.githubusercontent.com/50700597/128915036-b1e0c5fa-9ae0-4fb1-b352-2b26cb876490.png)
![Screenshot from 2021-08-11 01-28-08](https://user-images.githubusercontent.com/50700597/128915047-332c721b-bc0a-47c6-9751-f0a1693c8eed.png)
![Screenshot from 2021-08-11 01-27-20](https://user-images.githubusercontent.com/50700597/128915055-5fdeef4e-0345-4f73-a400-830896bd6008.png)

**Comment by chrislusf** [comment]
Thanks for the detailed report! Added a fix.
