### ISSUE TITLE
How to appoint a backup with DataCenter or Rack ?

### ISSUE THREAD

**Issue by wangrd** [chrislusf/seaweedfs#2249]
In my plan, there are many DataCenters, one is remote and others is local. Can I use the remote one as backups for some racke in locals(so user can read it from Internet)? That means I want appoint the remote datacenter as the target when I upload file and replicate it via volume server. Or is there a way to make the replication exits in all same rack of different datacenter?

**Comment by wangrd** [comment]
![image](https://user-images.githubusercontent.com/30856466/128988362-d0b8d1a7-7146-44a6-9fcd-2f17c36632d9.png)
Within the introduction above, I can't find a config for different datacenter and same rack.

**Comment by chrislusf** [comment]
The rack belongs to one data center. Two racks in different data center, even with the same name, are considered different.

For cross data center, you can use https://github.com/chrislusf/seaweedfs/wiki/Filer-Active-Active-cross-cluster-continuous-synchronization

**Comment by wangrd** [comment]
> The rack belongs to one data center. Two racks in different data center, even with the same name, are considered different.
> 
> For cross data center, you can use https://github.com/chrislusf/seaweedfs/wiki/Filer-Active-Active-cross-cluster-continuous-synchronization

Thanks.
Can appoint a data center as the only target for replication for other data centers?

**Comment by wangrd** [comment]
> > The rack belongs to one data center. Two racks in different data center, even with the same name, are considered different.
> > For cross data center, you can use https://github.com/chrislusf/seaweedfs/wiki/Filer-Active-Active-cross-cluster-continuous-synchronization
> 
> Thanks.
> Can appoint a data center as the only target for replication for other data centers?

Or can I makes a file exists in all data centers(not just 1 or 2)?

**Comment by chrislusf** [comment]
> Can appoint a data center as the only target for replication for other data centers?

Use preferred data center. See https://github.com/chrislusf/seaweedfs/wiki/Master-Server-API#assign-a-file-key



> Or can I makes a file exists in all data centers(not just 1 or 2)?

This request has come up before. 

1. You can use `weed backup` as a way to asynchronously copy to remote dc.
2. And set `treat_replication_as_minimums = true` in `master.toml`, to keep the volumes writable.

**Comment by wangrd** [comment]
> > Can appoint a data center as the only target for replication for other data centers?
> 
> Use preferred data center. See https://github.com/chrislusf/seaweedfs/wiki/Master-Server-API#assign-a-file-key
> 
 It's for uploading a file into appointed dc or rack. My purpose is to appoint it when use the para `replication` too.

**Comment by chrislusf** [comment]
> It's for uploading a file into appointed dc or rack. My purpose is to appoint it when use the para `replication` too.

filer also support parameter for dc or rack. https://github.com/chrislusf/seaweedfs/wiki/Filer-Server-API#postputget-files
