### ISSUE TITLE
is seaweedfs will maintain a goraft branch of its own?

### ISSUE THREAD

**Issue by hxiaodon** [chrislusf/seaweedfs#225]
Hi,Chris

github.com/chrislusf/raft which is forked from github.com/goraft/raft is unmaintained for a long time. Do you have any plan to replace it or it is not a problem since goraft is stable enough and could satisfy all the needs from seaweed

I pop up this issue because I have a plan to use seaweed in our production environment. Using an unmaintained component is my current concern.

Thanks!

**Comment by chrislusf** [comment]
Current forked raft version is fairly stable. We don't use any fancy features.

Latest raft version has different APIs. It'll take some time to upgrade, and possibly introduce new bugs. It's actually more stable to stay this way.
