### ISSUE TITLE
can not read while writing

### ISSUE THREAD

**Issue by nguyenhiepvan** [chrislusf/seaweedfs#2253]
I have 40 milions of files want to write, i used bin file and write some daemon services to start. i had 2 services: master and volume, while i writing on the volume server, i can't read files by public url but still writing on it, it returned 504 until i reseted volume servers.

**Comment by hunglsxx** [comment]
Seems to be the same as #2247

**Comment by chrislusf** [comment]
@nguyenhiepvan please use the issue template to create new issues and add more details.

**Comment by nguyenhiepvan** [comment]
> @nguyenhiepvan please use the issue template to create new issues and add more details.

i'm sorry but maybe @hunglsxx was right, your latest commit has fixed this issue, i am monitoring  system stability after rebuilt server. Thank you for replying!
