### ISSUE TITLE
[feature request] expose actual data size and trash size to Prometheus

### ISSUE THREAD

**Issue by PeterCxy** [chrislusf/seaweedfs#2256]
Currently the exposed metric `total_disk_size` refers to the on-disk size of volumes, not the actual used data size within volumes (as in the `Data size` column of seaweedfs's web interface). It may sometimes be useful to have access to the actual data size in a collection via Prometheus / Grafana, especially when volumes are large. This may be more computation-intensive, though, so I am not exactly sure if this will be a good idea. But since we are using a push gateway anyway, maybe we can increase the interval between pushes for such a computation-intensive metric?

**Comment by kmlebedev** [comment]
I didn't understand until the end what I want to monitor?
We have garbageThreshold(vacuum when garbage is more than this limit) 
which does not allow the difference between the volumes and the real known size per disk to grow strongly

**Comment by PeterCxy** [comment]
@kmlebedev The on-disk size is always the maximum size of the volume at least on my setup, so the monitored value do not change unless new volumes are created. If this is not the expected behavior then maybe it's a bug?

**Comment by kmlebedev** [comment]
> @kmlebedev The on-disk size is always the maximum size of the volume (for me, 1GB) at least on my setup, so the monitored value do not change unless new volumes are created. If this is not the expected behavior then maybe it's a bug?

There are two modes of operation of volumes with and without pre-allocation to disk.
`
volumePreallocate - Preallocate disk space for volumes (default is false)
If true is avoid disk space resale protection, but utilization decreases with a large number of half-empty buckets

**Comment by PeterCxy** [comment]
@kmlebedev Thanks, I totally forgot I enabled preallocation. Closing the issue.
