### ISSUE TITLE
Filer remote.storage with minio aws

### ISSUE THREAD

**Issue by tjikaljedy** [chrislusf/seaweedfs#2259]
I  am trying to configure seaweedfs and use minio aws connection, following how i run the seaweedfs:

Master - Volume - FIler:
weed server -master.port=9333 -volume.port=9444 -dir="$HOME/seaweedfs/workspace" -filer -filer.port=9555

Filer configure:
  "mappings": {
    "/localrepo": {
      "name": "minio",
      "bucket": "stagingdb",
      "path": "/"
    }
  }
}
> remote.configure
{
  "type": "s3",
  "name": "minio",
  "s3AccessKey": "GEOLB0844VX8ADFPGTHJ",
  "s3Region": "us-east-2",
  "s3Endpoint": "http://10.211.55.5:9000"

And seperate run console for sync remote:
weed filer.remote.sync -filer=localhost:9555 -dir=/localrepo

Until this no error, but once trying to upload with:
weed filer.copy readme.txt  http://localhost:9555/localrepo/

The error is come out in  filler sync  console:

E0815 22:31:39 22689 filer_pb_tail.go:68] process directory:"/localrepo" event_notification:{old_entry:{name:"readme.txt" chunks:{file_id:"6,02d7103225" size:14 mtime:1629040713866741008 e_tag:"oE+tYmFY3WmP1lf7QRmMkw==" fid:{volume_id:6 file_key:2 cookie:3608162853} is_compressed:true} attributes:{file_size:14 mtime:1629040713 file_mode:436 uid:1000 gid:1000 crtime:1629040713 mime:"text/plain; charset=utf-8"}} new_entry:{name:"readme.txt" chunks:{file_id:"4,0351bd87d3" size:14 mtime:1629041499539749292 e_tag:"oE+tYmFY3WmP1lf7QRmMkw==" fid:{volume_id:4 file_key:3 cookie:1371375571} is_compressed:true} attributes:{file_size:14 mtime:1629041499 file_mode:436 uid:1000 gid:1000 crtime:1629040713 mime:"text/plain; charset=utf-8"}} delete_chunks:true new_parent_path:"/localrepo" signatures:-1858701703} ts_ns:1629041499540877778: upload to s3 minio/stagingdb//readme.txt: RequestError: send request failed
caused by: Put "http://10.211.55.5:9000/stagingdb/readme.txt": net/http: HTTP/1.x transport connection broken: http: ContentLength=14 with Body length 0

Please Chris, and suggestion to figure out this error thx

**Comment by chrislusf** [comment]
What's your "weed version" output?

**Comment by tjikaljedy** [comment]
weed version
version 30GB 2.62 2c38f87 linux amd64

**Comment by chrislusf** [comment]
Thanks! I have added a fix. Please help to confirm.

**Comment by tjikaljedy** [comment]
E0816 08:48:08  7067 filer_pb_tail.go:68] process directory:"/localrepo"  event_notification:{new_entry:{name:"readme.txt"  chunks:{file_id:"6,02c46224d0"  size:14  mtime:1629078455594350816  e_tag:"oE+tYmFY3WmP1lf7QRmMkw=="  fid:{volume_id:6  file_key:2  cookie:3294766288}  is_compressed:true}  attributes:{file_size:14  mtime:1629078455  file_mode:436  uid:1000  gid:1000  crtime:1629078455  mime:"text/plain; charset=utf-8"}}  delete_chunks:true  new_parent_path:"/localrepo"  signatures:2097842696}  ts_ns:1629078455594996494: upload to s3 minio/stagingdb/readme.txt: InvalidStorageClass: Invalid storage class.
	status code: 400, request id: 169BA64111EC6A46, host id:

**Comment by tjikaljedy** [comment]
GREAT JOB BRO, DONE
