### ISSUE TITLE
How to specify a log path for seaweedfs output

### ISSUE THREAD

**Issue by hxiaodon** [chrislusf/seaweedfs#226]
Hi,Chris
seaweedfs use glog which support log rotate. I want to specify the -log_dir option in my production environment , then I think that  the seaweedfs's normal and abnormal output will be asynchronously written to the physical log files in that directory,  and there should be a new created log file every one hour

But it failed when I try the following command:
./weed server -master.port=9334 -dir=./2 -volume.port=8081 -master.peers=localhost:9333  -log_dir=mylog &
Could you give me some suggestions?

Thanks!

**Comment by yanyiwu** [comment]
Even though this issue has been solved by talking in IM(Weixin) ,
I think I have to paste solution here for someone else in the future:

```
./weed  -log_dir=mylog server -master.port=9334 -dir=./2 -volume.port=8081 -master.peers=localhost:9333  &
```
