### ISSUE TITLE
remote.syn > InvalidStorageClass: Invalid storage class.

### ISSUE THREAD

**Issue by tjikaljedy** [chrislusf/seaweedfs#2260]
E0816 08:48:08  7067 filer_pb_tail.go:68] process directory:"/localrepo"  event_notification:{new_entry:{name:"readme.txt"  chunks:{file_id:"6,02c46224d0"  size:14  mtime:1629078455594350816  e_tag:"oE+tYmFY3WmP1lf7QRmMkw=="  fid:{volume_id:6  file_key:2  cookie:3294766288}  is_compressed:true}  attributes:{file_size:14  mtime:1629078455  file_mode:436  uid:1000  gid:1000  crtime:1629078455  mime:"text/plain; charset=utf-8"}}  delete_chunks:true  new_parent_path:"/localrepo"  signatures:2097842696}  ts_ns:1629078455594996494: upload to s3 minio/stagingdb/readme.txt: InvalidStorageClass: Invalid storage class.
	status code: 400, request id: 169BA64111EC6A46, host id: 

The url is fix. but have invalidstorageclass error

_Originally posted by @tjikaljedy in https://github.com/chrislusf/seaweedfs/issues/2259#issuecomment-899159384_

**Comment by chrislusf** [comment]
fixed. Please help to confirm.

**Comment by tjikaljedy** [comment]
DONE BRO GOOD JOB

**Comment by tjikaljedy** [comment]
For text is done bro, but mp4 fail

1}} attributes:{file_size:28656460 mtime:1629086195 file_mode:420 uid:1000 gid:1000 crtime:1629086195 mime:"video/mp4"}} delete_chunks:true new_parent_path:"/localrepo" signatures:-1467893928} ts_ns:1629086195892817823: upload to s3 minio/stagingdb/diary-portrait-15s.mp4: MultipartUpload: upload multipart failed

**Comment by chrislusf** [comment]
this should be fixed now in 2.63

**Comment by tjikaljedy** [comment]
Hi Chris,

rror: Put "https://xxx.id/stagingdb/diary-portrait-15s.mp4?partNumber=4&uploadId=2~O8j1Mf-7rcJy0LlNpjUEqw4yMkH0zga": Bad digest: Expected d9acb694bb5b530397b6e82aa2880bc5 does not match calculated 03e462a6948bb8316618c750d5b08bc4 (*url.Error) 

The process from local to minio is no problem, but i thing the p

Duplicate of # FINALY IS DONE, THX CHRIS
