### ISSUE TITLE
The Filer service not resizing image

### ISSUE THREAD

**Issue by mauroparente** [chrislusf/seaweedfs#2262]
**Describe the bug**
The Filer service not resize image if the file extension isn't lowercase.
Ex: http://localhost:8888/images/foo.PNG?width=200&height=100

**Expected behavior**
The image should be resized

**Additional context**
I found that the **ext** parameter not has been lowercased before passing it to **shouldResizeImages** function:
https://github.com/chrislusf/seaweedfs/blob/8109594c6e01bc5a9b412e105f003a325858a1fc/weed/server/filer_server_handlers_read.go#L145

**Comment by chrislusf** [comment]
do you want to send a PR for this?
