### ISSUE TITLE
`weed mount` stalls some read operations while writing

### ISSUE THREAD

**Issue by PeterCxy** [chrislusf/seaweedfs#2263]
**Describe the bug**

It seems that on my setup, a `weed mount` process will stall some chunk read requests while writing a large file. After the write operation is finished, the process is unstalled and all read requests are processed. It does not seem like a volume server performance issue, because other `weed mount` processes and the S3 gateway work completely fine while the one doing writes is stuck.

To reproduce, try to read a large file while writing another large file to the mountpoint, e.g. using `dd`. If the file being read is not in the local cache, then the reading process may get stuck for a long time. 

**System Setup**

SeaweedFS version: 2.62
Mount command: `weed mount -filer=<redacted> -filer.path=<redacted> -collection=<redacted> -dir=<redacted> -concurrentWriters=1 -allowOthers=true -chunkSizeLimitMB=1 -cacheCapacityMB=10240 -cacheDir=<redacted>`

The bandwidth is not saturated during the write operation (in fact this is why I have `concurrentWriters=1` and `chunkSizeLimitMB=1` because I thought it might be due to my network not being able to handle the default 32 concurrent writers uploading chunks at the same time, but this did not change anything).

**Expected behavior**

The FUSE mount should continue to process read requests while the write request is ongoing.

**Comment by PeterCxy** [comment]
Okay it seems that by using `RWMutex` in the volume server, one single volume can never be written to and read at the same time (though I am not sure if this is the root cause of my problem, but I do have a small amount of volumes in the collection where this happens). Is this really necessary at all times? Since volumes are normally append-only except during compaction, I believe it is reasonable to allow reads to happen while writes are ongoing (though precautions need to be made to not return in-flight data that has not finished writing yet).

**Comment by PeterCxy** [comment]
According to the Go documentation, [a blocked Lock call prevents any RLocks from being acquired](https://pkg.go.dev/sync#RWMutex.RLock). It might be the case that multiple goroutines are trying to acquire the write lock to a volume at the same time, this preventing any reads from happening.

**Comment by PeterCxy** [comment]
@chrislusf I have figured out how to reproduce this issue locally.

1. Create a network namespace using `ip netns add <name>`
2. Acquire a `screen` session inside the network namespace by something like `ip netns exec <name> /bin/screen` (it is important to do everything inside one invocation of `ip netns exec`, because each execution of `ip netns exec` creates a new mount namespace, which prevents us from accessing the FUSE mount later)
3. Activate the `lo` interface inside the netns by `ip link set lo up`
4. Throttle the `lo` interface a bit by `tc qdisc add dev lo root netem delay 20ms rate 20Mbit` (this adds 20ms of single-trip latency and limits the throughput to 20Mbps, in order to amplify the issue I'm showing. You can use a different value for testing.)
5. Start SeaweedFS master, volume, and filer with something like `weed server -ip=127.0.0.1 -ip.bind=127.0.0.1 -dir=<redacted> -filer`
6. Switch to a new page inside the same `screen` session, then start the FUSE mount with `weed mount -chunkSizeLimitMB=2 -concurrentWriters=1 -cacheCapacityMB=0 -dir=<redacted>` (we limit the chunk size, concurrent writers and disable the local cache in order to make the situation happen earlier)
7. Now, in a new page in `screen`, create and write to a small text file inside the FUSE mountpoint. This is our test file that will be read while writing a large binary file.
8. Run `dd if=/dev/zero of=/path/to/fuse/mountpoint/test.bin bs=1M count=1024 status=progress` (you can increase the size of data to write if this happens too quickly on your setup, or change the throttling parameters earlier on the `lo` interface)
9. Before the command above ends, switch to a new `screen` page and try to access the small file created in step 7 with `cat`. Notice that `cat` will get stuck until the `dd` command in step 8 finishes running completely.

**Comment by PeterCxy** [comment]
This only seems to happen when there are a lot of ongoing write and read requests -- at some point in the request queue, all reads begin to get stuck and only writes are processed. Take this debug output for example: (I added log output around the `RLock()` call in `readNeedle` in `volume_read.go`)

```
I0817 13:46:32 51473 volume_read.go:17] reading needle 1,0ae3122338, acquiring read lock
I0817 13:46:32 51473 volume_read.go:19] reading needle 1,0ae3122338, read lock okay
I0817 13:46:33 51473 volume_read.go:17] reading needle 1,0b2e0c8014, acquiring read lock
I0817 13:46:33 51473 volume_read.go:19] reading needle 1,0b2e0c8014, read lock okay
I0817 13:46:33 51473 volume_read.go:17] reading needle 1,0b2e0c8014, acquiring read lock
I0817 13:46:33 51473 volume_read.go:19] reading needle 1,0b2e0c8014, read lock okay
I0817 13:46:33 51473 volume_read.go:17] reading needle 1,0c346954e1, acquiring read lock
I0817 13:46:33 51473 volume_read.go:19] reading needle 1,0c346954e1, read lock okay
I0817 13:46:33 51473 volume_read.go:17] reading needle 1,0c346954e1, acquiring read lock
I0817 13:46:33 51473 volume_read.go:19] reading needle 1,0c346954e1, read lock okay
I0817 13:46:33 51473 volume_read.go:17] reading needle 1,0d4157506e, acquiring read lock
I0817 13:46:33 51473 volume_read.go:19] reading needle 1,0d4157506e, read lock okay
I0817 13:46:33 51473 volume_read.go:17] reading needle 1,0d4157506e, acquiring read lock
I0817 13:46:33 51473 volume_read.go:19] reading needle 1,0d4157506e, read lock okay
I0817 13:46:33 51473 volume_read.go:17] reading needle 1,0eda71d03e, acquiring read lock
I0817 13:46:33 51473 volume_read.go:19] reading needle 1,0eda71d03e, read lock okay
I0817 13:46:33 51473 volume_read.go:17] reading needle 1,0eda71d03e, acquiring read lock
I0817 13:46:33 51473 volume_read.go:19] reading needle 1,0eda71d03e, read lock okay
I0817 13:46:33 51473 volume_read.go:17] reading needle 1,0ff5a33599, acquiring read lock
I0817 13:46:33 51473 volume_read.go:19] reading needle 1,0ff5a33599, read lock okay
I0817 13:46:33 51473 volume_read.go:17] reading needle 1,0ff5a33599, acquiring read lock
I0817 13:46:33 51473 volume_read.go:19] reading needle 1,0ff5a33599, read lock okay
I0817 13:46:33 51473 volume_read.go:17] reading needle 1,10533a013f, acquiring read lock
I0817 13:46:33 51473 volume_read.go:19] reading needle 1,10533a013f, read lock okay
I0817 13:46:33 51473 volume_read.go:17] reading needle 1,10533a013f, acquiring read lock
I0817 13:46:33 51473 volume_read.go:19] reading needle 1,10533a013f, read lock okay
I0817 13:46:33 51473 volume_read.go:17] reading needle 1,119233bb06, acquiring read lock
I0817 13:46:33 51473 volume_read.go:19] reading needle 1,119233bb06, read lock okay
I0817 13:47:04 51473 volume_read.go:17] reading needle 1,119233bb06, acquiring read lock
I0817 13:47:04 51473 volume_read.go:19] reading needle 1,119233bb06, read lock okay
```

Notice the irregular time gap between the *last* two invocations. Also note that it did not get stuck in the process of acquiring the lock, so it may have nothing to do with the usage of RWMutex after all.

**Comment by chrislusf** [comment]
how busy are the traffic? There is a new volume server option `-concurrentDownloadLimitMB=256` in 2.62. Do you think it may be related?

**Comment by PeterCxy** [comment]
@chrislusf I thought of that just now as well, so I tried to remove all checks of in-flight data in `volume_server_handlers.go`, but it is still happening.

My current way to reproduce it is to just write one 1GB file, try to `cat` it while writing another, and observe the `cat` process getting stuck in the middle of the reading.

**Comment by chrislusf** [comment]
can you reproduce without using mount? Mount has its own caching and write strategies, and skipping it can help to pinpoint the problem.

**Comment by PeterCxy** [comment]
@chrislusf I've not tested without mount, but I believe the problem should be on the volume server implementation, because in the metrics exposed to Prometheus, those stuck intervals are counted towards volume server response times (unless the response times are not collected from the volume servers themselves, then I may be wrong).

**Comment by PeterCxy** [comment]
@chrislusf I have found the cause of the issue -- it's in your fork of `fuse`. In particular, it is this commit: https://github.com/seaweedfs/fuse/commit/b6b8dbb79bb1958d5a3d3a01a68324135c8d0460. Removing this or drastically increasing N temporarily fixed the issue for me.

It distributes works to `N` queues, disregarding the fact that some work may be finished much slower than others. As a result, a request will inevitably be stuck waiting for a lot of slow requests ahead of it in the queue, while all of the other workers may be idling. I'd suggest either reverting the commit, or implementing some sort of shared work queue or work stealing to avoid such a situation.

I'm going to run some tests locally to see if a shared work queue is a better solution, or maybe this should just be reverted, since the goroutine scheduler itself implements work queuing and stealing.

**Comment by chrislusf** [comment]
Nice! I actually wonder how you found it out so quickly. :)
