### ISSUE TITLE
ReplicatedWrite will not return err when one volume server is down

### ISSUE THREAD

**Issue by hxiaodon** [chrislusf/seaweedfs#227]
Hi,Chris
I have a concern when I test the replicateWrite function in my local environment. Could you give me some suggestion?

The "problem" could be reproduced with the following steps:
1.  launch master server A:   ./weed master -port=9333 -mdir=./1 -defaultReplication=001 &
2.  launch volume server B:   ./weed volume -dir=./1 -port=8080 &
3.  launch volume server C:   ./weed volume -dir=./2 -port=8081 &

Then I get a fid from master server A and successfully upload a small file to volume sever B,  server B will replicate the file to server C before it return to client,  this guarantee the file content consistency among multiple volume servers

When I stopped one volume server(server C), I could still get a few fid numbers before the master detected the volume server C is dead(after that, dir/assign from master server will return err "Cannot grow volume group" which is expected).
When I try to use those new fid numbers to upload small files, I thought that the operation will fail because only one volume server is alive and the replication policy(001) could not be satisfied 

But I still could get the positive feedback from volume server. For example:
curl -X PUT -F file=@myfe.pptx http://127.0.0.1:8080/5,04175e4338
{"name":"myfe.pptx","size":255927}

When I track your code, I found that the ReplicatedWrite function(store_replicate.go line 15) will still synchronously invoke distributedOperation, but the distributedOperation will do nothing and just return true.

It is because the variable lookupResult(func distributedOperation) in my testing scenario will just return a slice which only contain server B, the replicate operation to other server will never happen, the small file just write into the volume B server. 

I think that even the volume C server is launched  after a while,  the small file will only be located at volume server B. ( there is a manual way to use weed backup tool to sync data between volume B and volume C when we stop the whole services)

Is it reasonable to modify your code and add following logic?
When volume server found that replication policy is not null and the other replicated servers is empty, it should return error

If my understanding about the "ReplicatedWrite" is incorrect, please point out.

Thanks~

**Comment by chrislusf** [comment]
You are right. Need to check the replication policy defined copy count matches the look up result. Please create a pull request.

**Comment by hxiaodon** [comment]
Chris, I have created a pull request
https://github.com/chrislusf/seaweedfs/pull/233
Please review when you are available, thanks!
