### ISSUE TITLE
Want to add more volume servers to master server

### ISSUE THREAD

**Issue by jiaqigan** [chrislusf/seaweedfs#2276]
I used these commands to start multi servers. After uploaded some files, I tried to add a new volume server to this cluster server. There was not connection issue between the new volume server and master servers, then I tried to upload some other files to the volume server, however no matter how many times  I tried, the new volume server still had no volume. All files were uploaded to the preview volume servers.

Commands to start multi servers:
./weed -logdir=./data/log/master server -ip=192.168.196.129 -master.port=9333 -master.dir=./master -master.defaultReplication=100 -master.peers=192.168.196.129:9333,192.168.196.130:9333,192.168.196.131:9333 -dir=./volume/vol1 -volume.port=8080 -dataCenter=dc1 -filer=true -filer.port=8888 -filer.peers=192.168.196.129:8888,192.168.196.130:8888,192.168.196.131:8888

./weed -logdir=./data/log/master server -ip=192.168.196.130 -master.port=9333 -master.dir=./master -master.defaultReplication=100 -master.peers=192.168.196.129:9333,192.168.196.130:9333,192.168.196.131:9333 -dir=./volume/vol1 -volume.port=8080 -dataCenter=dc1 -filer=true -filer.port=8888 -filer.peers=192.168.196.129:8888,192.168.196.130:8888,192.168.196.131:8888

./weed -logdir=./data/log/master server -ip=192.168.196.131 -master.port=9333 -master.dir=./master -master.defaultReplication=100 -master.peers=192.168.196.129:9333,192.168.196.130:9333,192.168.196.131:9333 -dir=./volume/vol1 -volume.port=8080 -dataCenter=dc2 -filer=true -filer.port=8888 -filer.peers=192.168.196.129:8888,192.168.196.130:8888,192.168.196.131:8888

Command to start new volume server:
./weed -logdir=./data/log/volume volume -dir=./volume -mserver=192.168.196.129:9333,192.168.196.130:9334,192.168.196.131:9335 -ip=192.168.196.137 -port=8080 -dataCenter=dc1 &

![WeChat Image_20210821182408](https://user-images.githubusercontent.com/52802365/130318817-730bcb3e-f0aa-4a22-8d68-742102e262f4.png)

**Comment by jiaqigan** [comment]
![WeChat Image_20210821182408](https://user-images.githubusercontent.com/52802365/130318836-2871ef3b-9f0f-435e-b5bf-ab0bbf31b559.png)

**Comment by chrislusf** [comment]
Pre-allocate volumes https://github.com/chrislusf/seaweedfs/wiki/Master-Server-API#pre-allocate-volumes

Or run `volume.balance` in `weed shell`

**Comment by jiaqigan** [comment]
Could you please be more specific about how to run volume.balance?

**Comment by chrislusf** [comment]
check `volume.balance -h` in `weed shell`.
