### ISSUE TITLE
Can't install seaweed - 

### ISSUE THREAD

**Issue by just-refresh** [chrislusf/seaweedfs#2277]
**Describe the bug**
Cant start the installation with:
`make install`

**System Setup**
- Debian 10

Get following Error:
```
go get  -d ./weed/
build github.com/chrislusf/seaweedfs/weed: cannot find module for path embed
make: *** [Makefile:32: deps] Error 1
```

**Comment by chrislusf** [comment]
The Makefile under `seaweedfs` was for travis and now deprecated. Need to clean it up.

Please use the Makefile under `seaweedfs/weed` folder.
