### ISSUE TITLE
大文件分片上传，下载文件非常慢

### ISSUE THREAD

**Issue by ghostsf** [chrislusf/seaweedfs#2278]
按照大文件分片上传的方式进行上传
https://github.com/chrislusf/seaweedfs/wiki/Large-File-Handling

参考Example处理，
大文件分片上传成功后（上传也比单个文件上传慢很多，做了多线程上传分片），
获取下载此大文件时，会变得非常得慢

是在下载的时候才可开始合并吗？ 还是什么其他什么原因呢？

**Comment by chrislusf** [comment]
This way, the download is not parallelized.

Filer can do auto chunking. You can use that.
