### ISSUE TITLE
files are not download completly

### ISSUE THREAD

**Issue by nirmalkoffice** [chrislusf/seaweedfs#2294]
Getting random behavior while downloading a file from seaweeds, sometimes file completely downlod sometimes not.
 

/ # weed version
version 0.99 linux amd64

 # curl -o 1.pdf -v  http://127.0.0.1:8080/383,04ad35a8ddf0bad8
*   Trying 127.0.0.1...
* TCP_NODELAY set
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET /383,04ad35a8ddf0bad8 HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.61.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Content-Disposition: inline; filename="579135.pdf"
< Content-Length: 15888400
< Content-Type: application/pdf
< Etag: "d5545aa2"
< Last-Modified: Wed, 18 Aug 2021 03:53:10 GMT
< X-File-Store: chunked
< Date: Sun, 29 Aug 2021 12:12:16 GMT
< 
{ [36612 bytes data]
* transfer closed with 10645520 bytes remaining to read
 32 15.1M   32 5120k    0     0   416M      0 --:--:-- --:--:-- --:--:--  416M
* Closing connection 0
curl: (18) transfer closed with 10645520 bytes remaining to read

**Describe the bug**
0829 12:09:36     1 volume_server_handlers_read.go:42] volume 383 reading 04ad35a8ddf0bad8 Size:0, DataSize:0, Name:, Mime:
I0829 12:09:36     1 volume_server_handlers_read.go:69] read bytes 1080 error <nil>
I0829 12:09:36     1 volume_server_handlers_read.go:42] volume 381 reading 04ad35a9f680d78a Size:0, DataSize:0, Name:, Mime:
I0829 12:09:36     1 volume_server_handlers_read.go:69] read bytes 1048576 error <nil>
I0829 12:09:36     1 volume_server_handlers_read.go:42] volume 383 reading 04ad35c050b3a843 Size:0, DataSize:0, Name:, Mime:
I0829 12:09:36     1 volume_server_handlers_read.go:69] read bytes 1048576 error <nil>
I0829 12:09:36     1 volume_server_handlers_read.go:42] volume 384 reading 04ad35c125bd9244 Size:0, DataSize:0, Name:, Mime:
I0829 12:09:36     1 volume_server_handlers_read.go:69] read bytes 1048576 error <nil>
I0829 12:09:36     1 volume_server_handlers_read.go:42] volume 387 reading 04ad35c2988ba82d Size:0, DataSize:0, Name:, Mime:
I0829 12:09:36     1 volume_server_handlers_read.go:69] read bytes -1 error Not Found
I0829 12:09:36     1 volume_server_handlers_read.go:71] read /387,04ad35c2988ba82d error: Not Found
I0829 12:09:36     1 volume_server_handlers_read.go:180] response write error: Read chunk needle error: [404] http://weed-volume-03-clusterip:8080/387,04ad35c2988ba82d
ent of `filer.toml`

**Comment by chrislusf** [comment]
seems one replica is missing.
please upgrade and run `volume.fix.replication` in `weed shell`.
