### ISSUE TITLE
Seaweedfs can do TTL for the specified bucket

### ISSUE THREAD

**Issue by wellyn-chen** [chrislusf/seaweedfs#2295]
Seaweedfs can do TTL for the specified bucket

**Comment by chrislusf** [comment]
Use path-specific configuration on `/buckets/<bucket>`

https://github.com/chrislusf/seaweedfs/wiki/Path-Specific-Configuration

**Comment by wellyn-chen** [comment]
Cannot set bucket rules like AWS？

**Comment by wellyn-chen** [comment]
> 使用特定于路径的配置 `/buckets/<bucket>`
> 
> https://github.com/chrislusf/seaweedfs/wiki/Path-Specific-Configuration

Cannot set bucket rules like AWS?
