### ISSUE TITLE
Supercronic Missing

### ISSUE THREAD

**Issue by ProjectInitiative** [chrislusf/seaweedfs#2296]
**Describe the bug**
Copying the config from [example](https://github.com/chrislusf/seaweedfs/blob/master/docker/seaweedfs-compose.yml#L31-L40) produces the following error:
/entrypoint.sh: exec: line 68: supercronic: not found

[File and line](https://github.com/chrislusf/seaweedfs/blob/master/docker/entrypoint.sh#L68) causing issue.

**System Setup**
- Master server (other 2 increase port by 1): `master -ip=master1 -peers="master2:9332,master3:9333" -port=9331 -volumePreallocate -defaultReplication=002`
- Volume server (other 2 increase port by 1): `weed volume -dir=/mnt/dir1 -mserver=master1:9331,master2:9332,master3:9333 -port=9991 -max=300 -index=leveldb -dataCenter=dc1 -rack=rack1 -metricsPort=9325`
- OS version - Ubuntu 20.04 (3 node cluster)
- Docker version: 20.10.8, build 3967b7d
- `weed version`: version 8000GB 2.64 95e2b83ca5e8c23a775b4cda6519fc8e5f1161af linux amd64

**Expected behavior**
Crontab Docker container should be installed or in path for running with Docker

**Screenshots**
![Screenshot from 2021-08-30 22-56-43](https://user-images.githubusercontent.com/6314611/131439409-8e76a7f5-bd1f-4df5-80b7-1940f694ec11.png)

**Comment by chrislusf** [comment]
You can install `supercronic` manually.

Only the released version docker image has `supercronic` pre-installed. I feel it is kind of "messy" and is not included in all docker images. Later it may be replaced by something neat.

**Comment by ProjectInitiative** [comment]
When you say "released" docker version, which version is that?

**Comment by ProjectInitiative** [comment]
Furthermore, if you're looking for a clean way to implement crontabs within the alpine container, I might have some code from a precious project that did exactly that. I don't believe there was anything else that needed to be installed in the Alpine container, just some code added to entrypoint.sh. I can take a look and make a PR if it works out!

**Comment by ProjectInitiative** [comment]
Noted, I'll see what I can do, I'd like to contribute to the project! It's pretty cool (even though I'm still learning the ropes)
