### ISSUE TITLE
[master] Configuration volumeSizeLimitMB per collection via VolumeGrowOption 

### ISSUE THREAD

**Issue by kmlebedev** [chrislusf/seaweedfs#2298]
Now there is only a global setting
```
master.volumeSizeLimitMB - Master stops directing writes to oversized volumes
```
I want configure volume size limit per collection similarly preallocate via VolumeGrowOption

**Comment by chrislusf** [comment]
To do so, the change would not be trivial. Not only it affects directing traffic, but also rebalancing, setting volume capacity, etc. Unlikely this will be implemeted.

**Comment by kmlebedev** [comment]
ok

> To do so, the change would not be trivial. Not only it affects directing traffic, but also rebalancing, setting volume capacity, etc. Unlikely this will be implemeted.

Yes, I looked more closely at the code and realized the same that it was not easy
