### ISSUE TITLE
How to limit mount metacache size?

### ISSUE THREAD

**Issue by joshuafc** [chrislusf/seaweedfs#2299]
get 'no space left on device' error at weed mount output.

version 30GB 2.65 cd838b1197e29fbeb204813f0f82523cc580411a linux amd64

```
E0831 19:42:13 15359 filehandle.go:261] /buckets/pvc-f8621ff4-8985-4c69-b179-70a2cd9a47b6/xxx/3ffdb599-c584-4b68-a8d8-b25060f31899.xml doFlush: flush data: write /home/xxx/seaweed_mount_point/cache_dir/db9cea61/sw/450743978: no space left on device
E0831 19:42:13 15359 filehandle.go:261] /buckets/pvc-f8621ff4-8985-4c69-b179-70a2cd9a47b6/xxx/efe12bf3-84be-4b58-b207-c58864520d76.png doFlush: flush data: write /home/xxx/seaweed_mount_point/cache_dir/db9cea61/sw/1004528992: no space left on device
```

`/home/xxx/seaweed_mount_point/cache_dir` is a in memory tmpfs, as `df -h` show:

tmpfs                        2.0G  1.7G  335M   84% /home/xxx/seaweed_mount_point/cache_dir

mount command is `weed mount -filer=10.101.0.114:8888 -dir=./point2 -filer.path=/ -allowOthers=false -cacheCapacityMB 980 -cacheDir /home/xxx/seaweed_mount_point/cache_dir`

cache_dir used 1.7G, more than setted `-cacheCapacityMB 980`, as mentioned at #1508 , there also metacache will use cache_dir. 

How to limit metacache size?  Or how can I known which size for cache_dir is enough for metacache?

**Comment by chrislusf** [comment]
Is it writing some large file?

cache directory has 3 things:
* previously used chunks : this is what cacheCapacityMB was intended.
* metadata : should be small enough.
* files write in progress. If writing large files, this could be a problem.

**Comment by joshuafc** [comment]
> Is it writing some large file?
> 
> cache directory has 3 things:
> 
> * previously used chunks : this is what cacheCapacityMB was intended.
> * metadata : should be small enough.
> * files write in progress. If writing large files, this could be a problem.

there are 3 millions small files in the directory

**Comment by joshuafc** [comment]
> Is it writing some large file?
> 
> cache directory has 3 things:
> 
> * previously used chunks : this is what cacheCapacityMB was intended.
> * metadata : should be small enough.
> * files write in progress. If writing large files, this could be a problem.

and there are about 20 threads reading/writing small files. files most at 0.1MB to  2MB,  very few files are 0.5GB.

**Comment by chrislusf** [comment]
the large files will take 0.5GB space. They are written to the local first, then uploaded (current implementation).

**Comment by joshuafc** [comment]
Thank you for your explanation. I understand the principle. Is there any empirical formula to calculate how much space should be allocated to the cache_dir tmpfs?
