### ISSUE TITLE
S3 api CopyObject unexpected behavior if the source file does not exist

### ISSUE THREAD

**Issue by AlekseyFicht** [chrislusf/seaweedfs#2306]
Hello

**Describe the bug**
S3 has a CopyObject command that lets you create a duplicate file.
Minio returns a 404 error if there is no source file, the target file is not created.
But, seaweedfs creates an empty target file

**System Setup**
- OS version Centos 7
- weed version
version 30GB 2.65 cd838b1197e29fbeb204813f0f82523cc580411a linux amd64

**Expected behavior**
Returns a 404 error if there is no source file

**Additional context**
We are using AWS SDK for Java.
Sample code

```java
final var request = CopyObjectRequest.builder()
            .sourceBucket("test")
            .sourceKey("asdasdsasdadas.pdf")
            .destinationBucket("test")
            .destinationKey("tedsa.pdf")
            .acl(PUBLIC_READ)
            .build();
        final var response = s3Client.copyObject(request);
```

**Comment by chrislusf** [comment]
Added a fix. But The return http status code is set to 400 (Bad Request). Please help to verify it.

**Comment by AlekseyFicht** [comment]
@chrislusf  Thanks for fast response.
But it doesn't work, I still get code 200

```
Response code: 200
ETag: d41d8cd98f00b204e9800998ecf8427e
lastModified: 2021-09-06T05:56:49.234483422Z
```

```
 final var copy = CopyObjectRequest.builder()
                .sourceBucket("test")
                .sourceKey(UUID.randomUUID() + ".pdf")
                .destinationBucket("test")
                .destinationKey("fg34.pdf")
                .acl(PUBLIC_READ)
                .build();
            final var copyResponse = s3Client.copyObject(copy);
            System.out.println("Response code: " + copyResponse.sdkHttpResponse().statusCode());
            System.out.println("ETag: " + copyResponse.copyObjectResult().eTag());
            System.out.println("lastModified: " + copyResponse.copyObjectResult().lastModified());
```

I think the absence of the file does not cause the error. Checking for missing file does not work.

**Comment by chrislusf** [comment]
You are right. 

Added https://github.com/chrislusf/seaweedfs/commit/f62df7f6952799616da410b6e4d0217aa1b449db
and https://github.com/chrislusf/seaweedfs/commit/0cda61d53927631fafa9efbeee789212af3ee1c1 to address this.

**Comment by AlekseyFicht** [comment]
Hello @chrislusf 
I found another problem in the 2.66 release. I think it is related to the recent change [491f763](https://github.com/chrislusf/seaweedfs/commit/491f7636f8a6d24dcb65f1b23132101b2f565b4b)

I have 4 filer and the metadata is stored in Mysql Galera cluster. After updating to 2.66,  I noticed that there are more tables in the database than before. The table names correspond to the files that were created when using the copyObject API. There is nothing inside the table.
See attachments.

I think the fix is [f62df7f ](https://github.com/chrislusf/seaweedfs/commit/f62df7f6952799616da410b6e4d0217aa1b449db) will close this problem

We need to release the next release as soon as possible.

![Screenshot from 2021-09-07 10-00-47](https://user-images.githubusercontent.com/49243562/132282404-69013cd8-d514-43d2-8095-bcdcedf387a5.png)

Dbeaver

![Screenshot from 2021-09-07 10-01-18](https://user-images.githubusercontent.com/49243562/132282426-8485f937-6d16-4f4a-b796-fd0d9ef2c637.png)

![Screenshot from 2021-09-07 10-04-01](https://user-images.githubusercontent.com/49243562/132282639-e8aa7c38-91d0-4cfe-851e-6c43adc4572a.png)

**Comment by AlekseyFicht** [comment]
We have updated the version to 2.67 and have tested a CopyObject command

Answer: 

`
software.amazon.awssdk.services.s3.model.S3Exception: Copy Source must mention the source bucket and key: sourcebucket/sourcekey. (Service: S3, Status Code: 400, Request ID: 1631075631955303645, Extended Request ID: null)
`

It seems to work correctly
thanks @chrislusf

**Comment by chrislusf** [comment]
Thanks for the update!
