### ISSUE TITLE
[filer] observed slow chunk read in concurrent write scenario 

### ISSUE THREAD

**Issue by paralevi** [chrislusf/seaweedfs#2308]
**Describe the bug**
I was tuning  the performance of concurrent writes with minio/warp benchmarking tool. I observed that when the number of concurrent requests increased, filer's chunk step became more time-consuming than any other steps.  
I figured out  `dataSize, err := bytesBuffer.ReadFrom(limitedReader)` in *filer_server_handlers_write_upload.go*  costed much more time  in higher concurrency. 
Any advice you could give would be much appreciated. 

**System Setup**
- OS version: Centos 7.2 3.10.0-327.el7.x86_64
- output of `weed version`: version 30GB 2.62 ebc3918f linux amd64
- 3 nodes, using S3 gateway:
```
concurrentUploadLimitMB=4096
maxMB=8
defaultReplicaPlacement=002
```

**Expected behavior**
stable write performance.

**Additional context**
I added a log:
```golang
start := time.Now()
dataSize, err := bytesBuffer.ReadFrom(limitedReader)
glog.V(4).Infof("%s read limitedReader cost: %d", fileName, time.Now().Sub(start).Milliseconds())
```
testing with warp on master node:
- `--obj.size 5MiB  --concurrent 8` read limitedReader cost: 286
- `--obj.size 5MiB  --concurrent 64` read limitedReader cost: 2830
-  `--obj.size 5MiB  --concurrent 128` read limitedReader cost: 6195

**Comment by chrislusf** [comment]
>>> 8*5/0.286
139.86013986013987
>>> 64*5/2.830
113.07420494699646
>>> 128*5/6.195
103.3091202582728

You can try to increase the network speed.

**Comment by paralevi** [comment]
Thanks. I will check the network settings.
