### ISSUE TITLE
s3.configure does not take effect until restart

### ISSUE THREAD

**Issue by PeterCxy** [chrislusf/seaweedfs#2309]
**Describe the bug**

On the latest release, `s3.configure` no longer takes effect immediately.

**System Setup**

- SeaweedFS 2.65

**Expected behavior**

`s3.configure` should take effect immediately after `-apply`.

**Additional context**

To reproduce, just try to add an access token via `s3.configure`, and notice that it is not accepted until the s3 gateway is restarted.

**Comment by chrislusf** [comment]
Do you have multiple filers and s3 gateways? How are the configured?

**Comment by PeterCxy** [comment]
No, just one single filer and one single s3 gateway.

**Comment by chrislusf** [comment]
works for me

**Comment by PeterCxy** [comment]
Closing due to unreliable reproduction. Will open a new one if I found a way to actually reproduce elsewhere.

**Comment by PeterCxy** [comment]
No, just one single filer and one single s3 gateway. Nothing fancy, just the simplest configuration.

**Comment by imfantuan** [comment]
> 不，只有一个文件管理器和一个 s3 网关。没什么特别的，只是最简单的配置。
> […](#)
> 2021 年 9 月 4 日美国东部时间晚上 10:22:18，Chris Lu ***@***.***> 写道：你有多个文件管理器和 s3 网关吗？是怎么配置的？

The same situation here : (
