### ISSUE TITLE
Unable to access volumes after restart

### ISSUE THREAD

**Issue by lwolf** [chrislusf/seaweedfs#231]
I have seaweed master and several volumes running in docker containers. 
Everything was working fine until I restarted machine. After this I can't access old volumes at all.
I tried restarting nodes/master in different order. But result is the same - I can't access old volumes.
The only way to add old volumes is to manually add this volume runnning `http://ip:port/admin/assign_volume?replication=001&volume=47&collection=collection-name`.
After this I can see volumes with correct sizes and file counts in web ui, but I'm getting 404 trying to access file. In the logs I can see this message:

```
weed-volume3-1 | 2015-12-26T09:23:46.882381452Z I1226 09:23:46 00001 volume_server_handlers_read.go:53] read error: Unsupported Version! (0) /47,6ec1d4a2d5bc2e
weed-volume3-1 | 2015-12-26T09:24:29.131064161Z I1226 09:24:29 00001 needle.go:211] Invalid key_hash 6ec1d4a2d5bc2e' length: 0 error encoding/hex: odd length hex string
weed-volume3-1 | 2015-12-26T09:24:32.311548879Z I1226 09:24:32 00001 volume_server_handlers_read.go:53] read error: Unsupported Version! (0) /47,6ec1d4a2d5bc2e
weed-volume3-1 | 2015-12-26T09:24:34.405941356Z I1226 09:24:34 00001 volume_server_handlers_read.go:53] read error: Unsupported Version! (0) /47,6ec1d4a2d5bc2e
weed-volume3-1 | 2015-12-26T09:24:35.179841335Z I1226 09:24:35 00001 volume_server_handlers_read.go:53] read error: Unsupported Version! (0) /47,6ec1d4a2d5bc2e
```

I tried removing `idx` file and rebuilding it - no effect. 

How can I fix this and restore my volumes?

**Comment by chrislusf** [comment]
The error you showed is not related to the issue. But it also showed you are using an old version. It's better to build the latest version.

To help your problem, please show the commands you use to start the master and volumes. Usually the master would need some time (about half a minute) to be fully active. So also need to know the timing and how fast you determine it is not working.

**Comment by lwolf** [comment]
Hi, thanks for reply. Looks like you are correct about old version, I was using docker image from `carmark/seaweedfs` with lattest commit from july. 
Now I'm using the lattest one.
I used to run it like this:
`master -mdir="/data" -port 9333 -ip.bind="0.0.0.0" -ip "10.10.1.94" -defaultReplication="001"`
`volume -dir="/data" -max=50 -mserver="10.10.1.94:9333" -port=9102  -ip "10.10.1.94"`
`volume -dir="/data" -max=50 -mserver="10.10.1.94:9333" -port=9103  -ip "10.10.1.94"`

Regarding timing - usually I'm looking at the logs to determine that everything is loaded. But also I tried to wait for half an hour. 

I tried to test new image from the directory where I have 6 old volumes:
`docker run --rm  -p 9333:9333 -p 8080:8080 --name weed -v /seaweed/volume1/:/data tutum.co/lwolf/seaweed server -ip "192.168.59.103" -dir='/data' -master.dir='/data'`

```
I1227 09:49:08 00001 file_util.go:20] Folder /data Permission: -rwxr-xr-x
I1227 09:49:08 00001 file_util.go:20] Folder /data Permission: -rwxr-xr-x
I1227 09:49:08 00001 topology.go:86] Using default configurations.
I1227 09:49:08 00001 master_server.go:59] Volume Size Limit is 30000 MB
I1227 09:49:08 00001 server.go:203] Start Seaweed Master 0.70 beta at 192.168.59.103:9333
I1227 09:49:08 00001 raft_server.go:90] Initializing new cluster
I1227 09:49:08 00001 master_server.go:93] [ 192.168.59.103:9333 ] I am the leader!
I1227 09:49:08 00001 store.go:225] Store started on dir: /data with 0 volumes max 7
I1227 09:49:08 00001 server.go:257] Start Seaweed volume server 0.70 beta at 192.168.59.103:8080
I1227 09:49:08 00001 volume_server.go:70] Volume server bootstraps with master 192.168.59.103:9333
I1227 09:49:08 00001 node.go:208] topo adds child DefaultDataCenter
I1227 09:49:08 00001 node.go:208] topo:DefaultDataCenter adds child DefaultRack
I1227 09:49:08 00001 node.go:208] topo:DefaultDataCenter:DefaultRack adds child 192.168.59.103:8080
```
After a minute I added 1 volume manually:
```
I1227 09:50:26 00001 store.go:192] In dir /data adds volume:68 collection:production replicaPlacement:000 ttl:
I1227 09:50:26 00001 volume.go:110] loading index file /data/production_68.idx readonly false
```
And tried to access file from it:
```
I1227 09:51:13 00001 volume_server_handlers_read.go:53] read error: CRC error! Data On Disk Corrupted /68,916038875fdf09
```

What is strange for me is that after every restart of any volume It can't find volumes
`I1227 09:49:08 00001 store.go:225] Store started on dir: /data with 0 volumes max 7`

**Comment by chrislusf** [comment]
No clear action to take for this.

**Comment by webgps** [comment]
> Hi, thanks for reply. Looks like you are correct about old version, I was using docker image from `carmark/seaweedfs` with lattest commit from july. Now I'm using the lattest one. I used to run it like this: `master -mdir="/data" -port 9333 -ip.bind="0.0.0.0" -ip "10.10.1.94" -defaultReplication="001"` `volume -dir="/data" -max=50 -mserver="10.10.1.94:9333" -port=9102 -ip "10.10.1.94"` `volume -dir="/data" -max=50 -mserver="10.10.1.94:9333" -port=9103 -ip "10.10.1.94"`
> 
> Regarding timing - usually I'm looking at the logs to determine that everything is loaded. But also I tried to wait for half an hour.
> 
> I tried to test new image from the directory where I have 6 old volumes: `docker run --rm -p 9333:9333 -p 8080:8080 --name weed -v /seaweed/volume1/:/data tutum.co/lwolf/seaweed server -ip "192.168.59.103" -dir='/data' -master.dir='/data'`
> 
> ```
> I1227 09:49:08 00001 file_util.go:20] Folder /data Permission: -rwxr-xr-x
> I1227 09:49:08 00001 file_util.go:20] Folder /data Permission: -rwxr-xr-x
> I1227 09:49:08 00001 topology.go:86] Using default configurations.
> I1227 09:49:08 00001 master_server.go:59] Volume Size Limit is 30000 MB
> I1227 09:49:08 00001 server.go:203] Start Seaweed Master 0.70 beta at 192.168.59.103:9333
> I1227 09:49:08 00001 raft_server.go:90] Initializing new cluster
> I1227 09:49:08 00001 master_server.go:93] [ 192.168.59.103:9333 ] I am the leader!
> I1227 09:49:08 00001 store.go:225] Store started on dir: /data with 0 volumes max 7
> I1227 09:49:08 00001 server.go:257] Start Seaweed volume server 0.70 beta at 192.168.59.103:8080
> I1227 09:49:08 00001 volume_server.go:70] Volume server bootstraps with master 192.168.59.103:9333
> I1227 09:49:08 00001 node.go:208] topo adds child DefaultDataCenter
> I1227 09:49:08 00001 node.go:208] topo:DefaultDataCenter adds child DefaultRack
> I1227 09:49:08 00001 node.go:208] topo:DefaultDataCenter:DefaultRack adds child 192.168.59.103:8080
> ```
> 
> After a minute I added 1 volume manually:
> 
> ```
> I1227 09:50:26 00001 store.go:192] In dir /data adds volume:68 collection:production replicaPlacement:000 ttl:
> I1227 09:50:26 00001 volume.go:110] loading index file /data/production_68.idx readonly false
> ```
> 
> And tried to access file from it:
> 
> ```
> I1227 09:51:13 00001 volume_server_handlers_read.go:53] read error: CRC error! Data On Disk Corrupted /68,916038875fdf09
> ```
> 
> With the lattest version I can restart nodes without loosing volumes, so now I only need to recover old volumes.

Did you resolve this problem?
