### ISSUE TITLE
volume server not showing back up on master after connection interruption

### ISSUE THREAD

**Issue by PeterCxy** [chrislusf/seaweedfs#2311]
**Describe the bug**

Sometimes volume servers seem to not show up on master after a connection interruption, despite the fact that the heartbeat goroutine seems to be back up running after the interruption, and the network is restored. The only fix seems to be restarting the problematic volume server.

**System Setup**

- SeaweedFS 2.65
- Simple setup with 1 master node, 1 filer, 1 s3 gateway, and 5 volume servers connected via a VPN

**Additional context**

This is the typical log output on the volume server after said interruption

```
volume_1  | I0905 20:40:41     1 volume_grpc_client_to_master.go:76] heartbeat error: rpc error: code = Unavailable desc = transport is closing
volume_1  | I0905 20:40:47     1 volume_grpc_client_to_master.go:114] Heartbeat to: 172.22.1.200:9333
```

The logged master IP / port is correct. No further errors or logs are shown, but the volume server is not present on master's list of volume servers. It seems that the heartbeat is somehow not sent correctly or the state on the master node is messed up.

Note that two of the volume servers run on the same physical server, and sometimes one would go down in this way while the other one stays up and works perfectly fine. This should rule out potential issues with the  network.

**Comment by chrislusf** [comment]
Noticed the same thing. Did you find a way to reproduce this kind of network interruption?

**Comment by chrislusf** [comment]
What is the log on the master side around the same time?

**Comment by PeterCxy** [comment]
@chrislusf It seems to be just normal dead volume server procedure (i.e. removing volumes and `unregister disconnected volume server`). However, I did notice that this whole procedure of handling a dead volume server did not finish before the dead server came back up -- maybe there's some race condition here? (volume server goes down -> unregistering process started -> volume server came back up -> unresgitering process finished, since the unregistering process did not finish when the volume server came back up, the registering process was not triggered?)

**Comment by PeterCxy** [comment]
If my hypothesis is correct then to reproduce this bug, we only need to make the interruption extremely short in time, or artificially slow down the process of deregistering volumes of dead volume servers (maybe adding a few sleeps here and there)

**Comment by PeterCxy** [comment]
In the master server log

```
seaweedfs_master | I0905 20:40:58     1 node.go:234] topo:op_par:2_d2 removes 172.22.1.8:8081
seaweedfs_master | I0905 20:40:58     1 master_grpc_server.go:29] unregister disconnected volume server 172.22.1.8:8081
```

Notice how this happens on `20:40:58`, while the volume server itself was back up as early as `20:40:47`.

**Comment by chrislusf** [comment]
Very nice analysis! Added code to protect against this case.
