### ISSUE TITLE
[S3] Support Server Side Encryption with Customer Provided Keys?

### ISSUE THREAD

**Issue by chrizonline** [chrislusf/seaweedfs#2313]
**Describe the bug**
Does seaweedFS support [Server-Side encryption with customer-provided keys (SSE-C)](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ServerSideEncryptionCustomerKeys.html) on S3 API?

I wrote a python script using [boto3](https://boto3.amazonaws.com/v1/documentation/api/1.9.46/reference/services/s3.html#id194) to [put_object](https://boto3.amazonaws.com/v1/documentation/api/1.9.46/reference/services/s3.html#S3.Client.put_object) with SSE-C, but was able to read the object content using [get_object](https://boto3.amazonaws.com/v1/documentation/api/1.9.46/reference/services/s3.html#S3.Client.get_object) **without** SSE-C. Tried the same piece of code on AWS S3 and it returns an expected error:

```
botocore.exceptions.ClientError: An error occurred (InvalidRequest) when calling the GetObject operation: The object was stored using a form of Server Side Encryption. The correct parameters must be provided to retrieve the object.
```

**System Setup**
- SeaweedFS 2.65
- Ubuntu 18.04.5 LTS
- Command to start master, volume, filer and s3
   ```
   # master
   ./weed master -mdir=./master -ip=192.168.1.10 -port=9333 -defaultReplication=010

   # volume
   ./weed volume -max=100 -port=8080 -mserver=192.168.1.10:9333 -dir=./volume1 -dataCenter=dc1 -rack=rack1

   # filer and s3
   ./weed s3 -filer="192.168.1.10:8888" -metricsPort=9327
    ```
- filer.toml
    ```
    [leveldb2]
    enabled=true
    dir="."
    ```
**Expected behavior**
If `boto3.client("s3").get_object(Bucket=bucket, Key=key)` is used **without** SSE-C, the expected behavior should be an error exception:
```
botocore.exceptions.ClientError: An error occurred (InvalidRequest) when calling the GetObject operation: The object was stored using a form of Server Side Encryption. The correct parameters must be provided to retrieve the object.
```

**Additional context**

Here is the code snippets of my python script

```
import boto3
import os

BUCKET = "newbucket" 
# use os.urandom(32)
KEY = b'\\e\xa9\xbb\xf7\xa3\x008v\xccm\x0f?\xa1\x96k,\x8d\xf0\x97\xd7\xd8*\x9b\xd0\xc0\x07\x9b>\xec\x855'
kwrgs =  {'endpoint_url': 'http://192.168.1.10:8333'}
cli = boto3.client("s3", **kwrgs)

def add_object():
    print("Adding object...")
    in_file = open("./sampleFiles/f7.txt", "rb")
    data = in_file.read()
    in_file.close

    response = cli.put_object(
        Body=data,
        Bucket=BUCKET,
        Key="f7.txt",
        SSECustomerKey=KEY,
        SSECustomerAlgorithm="AES256"

def download_object():
    response = cli.get_object(
        Bucket=BUCKET, 
        Key="f7.txt", 
        SSECustomerKey=KEY, 
        SSECustomerAlgorithm="AES256")
    print(response)
    print(response["Body"].read())
```

**Comment by chrislusf** [comment]
SSE-C currently is not supported.

**Comment by chrizonline** [comment]
Ok noted. Any plan in the road map?

**Comment by kmlebedev** [comment]
> Ok noted. Any plan in the road map?

can you look at [minio](https://github.com/minio/minio) code and send a PR?

**Comment by PeterCxy** [comment]
Minio S3 gateway may be an easy way to gain support for SSE for now.

**Comment by chrizonline** [comment]
@kmlebedev and @PeterCxy, thank you for your input. it accelerates my findings. I will close this issue

**Comment by chrislusf** [comment]
I wonder how important is this feature.
