### ISSUE TITLE
Volume node remain disconnected from master

### ISSUE THREAD

**Issue by mauroparente** [chrislusf/seaweedfs#2315]
**Describe the bug**
One or more volume server remain unavailable after disconnect/reconnect to master

**System Setup**

S.O. Ubuntu 20.04

1 master VM
/usr/sbin/weed master -options /opt/seaweedfs/master01/boot.ini
```
v=4
logdir=/opt/seaweedfs/master01/logs/
defaultReplication=000
garbageThreshold=0.1
ip=10.200.0.208
ip.bind=10.200.0.208
port=9333
volumeSizeLimitMB=30000
mdir=/opt/seaweedfs/master01/meta/
```

3 volume VM
/usr/sbin/weed volume -options /opt/seaweedfs/vol01/boot.ini
```
v=4
logdir=/opt/seaweedfs/vol02/logs/
dir=/opt/seaweedfs/vol02/data/
dir.idx=/opt/seaweedfs/vol02/data/
disk=vol02
ip=10.200.0.212
ip.bind=10.200.0.212
max=20
minFreeSpace=5GiB
mserver=10.200.0.208:9333
port=8081
```
**Expected behavior**
When the volume server reconnect to master it should be available again

**Additional context**
This happens when i remove a snapshot from master server that take much time. The VM "freeze" for some time and the "register/unregister" routines overlapping

This is the log from master01 and volume03 server
[master01_volume03.txt](https://github.com/chrislusf/seaweedfs/files/7116077/master01_volume03.txt)

I think it's because of this
https://github.com/chrislusf/seaweedfs/blob/6022db6d6aa29078d76ea7155b179e5ca8530365/weed/server/master_grpc_server.go#L30

**Comment by PeterCxy** [comment]
I reported a similar issue as #2311 yesterday and it seems to have been fixed by the latest release. Can you check if this is the case?

**Comment by chrislusf** [comment]
Duplicated with #2311
