### ISSUE TITLE
S3 API support  TTL ?

### ISSUE THREAD

**Issue by huamr** [chrislusf/seaweedfs#2317]
The Filer API supports TTL.So does the S3 API support  TTL? How to do

**Comment by chrislusf** [comment]
use path-specific configurations https://github.com/chrislusf/seaweedfs/wiki/Path-Specific-Configuration

configure for `/buckets/<bucket_name>`

**Comment by huamr** [comment]
thanks

**Comment by wellyn-chen** [comment]
> thanks


Hello! Have you realized it? How to implement docker deployment?
