### ISSUE TITLE
Path specific configuration does not take effect

### ISSUE THREAD

**Issue by wellyn-chen** [chrislusf/seaweedfs#2324]
I0908 07:48:53     1 filer_grpc_server_sub_meta.go:105] read on disk filer:192.168.53.187:9431@172.21.0.1:58090 local subscribe / from 2021-09-08 07:47:51.80204127 +0000 UTC
I0908 07:48:53     1 filer_grpc_server_sub_meta.go:120] read in memory filer:192.168.53.187:9431@172.21.0.1:58090 local subscribe / from 2021-09-08 07:47:51.80204127 +0000 UTC
I0908 07:50:04     1 filer_on_meta_event.go:51] procesing directory:"/etc/seaweedfs"  event_notification:{new_entry:{name:"filer.conf"  attributes:{file_size:122  mtime:1631087404  file_mode:420  crtime:1631087404}  content:"{\n  \"locations\": [\n    {\n      \"locationPrefix\": \"/picture/\",\n      \"collection\": \"picture\",\n      \"ttl\": \"5m\"\n    }\n  ]\n}"}  delete_chunks:true  new_parent_path:"/etc/seaweedfs"  signatures:-1413118406}  ts_ns:1631087404307518763
 

Files under the path will not be deleted automatically

**Comment by wellyn-chen** [comment]
> I0908 07:48:53 1 filer_grpc_server_sub_meta.go:105] read on disk filer:192.168.53.187:9431@172.21.0.1:58090 local subscribe / from 2021-09-08 07:47:51.80204127 +0000 UTC
> I0908 07:48:53 1 filer_grpc_server_sub_meta.go:120] read in memory filer:192.168.53.187:9431@172.21.0.1:58090 local subscribe / from 2021-09-08 07:47:51.80204127 +0000 UTC
> I0908 07:50:04 1 filer_on_meta_event.go:51] procesing directory:"/etc/seaweedfs" event_notification:{new_entry:{name:"filer.conf" attributes:{file_size:122 mtime:1631087404 file_mode:420 crtime:1631087404} content:"{\n "locations": [\n {\n "locationPrefix": "/picture/",\n "collection": "picture",\n "ttl": "5m"\n }\n ]\n}"} delete_chunks:true new_parent_path:"/etc/seaweedfs" signatures:-1413118406} ts_ns:1631087404307518763
> 
> Files under the path will not be deleted automatically

![image](https://user-images.githubusercontent.com/88520903/132471382-b3aefe5e-56cc-4e41-a220-634ae25eae4e.png)

**Comment by wellyn-chen** [comment]
It's working. Thank you！

**Comment by chrislusf** [comment]
what was the issue?
