### ISSUE TITLE
volume.balance causes rpc error: code = Unknown desc = mismatching cookie 0

### ISSUE THREAD

**Issue by MannerMan** [chrislusf/seaweedfs#2329]
**Describe the bug**
Performing `volume.balance -force` on the master server in our seaweed cluster causes error
```
> volume.balance -force
  moving  volume prod-pgbackrest_860 10.84.101.119:8080 => 10.84.101.134:8080
2021/09/09 09:00:32 copying volume 860 from 10.84.101.119:8080 to 10.84.101.134:8080
2021/09/09 09:00:32 tailing volume 860 from 10.84.101.119:8080 to 10.84.101.134:8080
2021/09/09 09:00:44 deleting volume 860 from 10.84.101.119:8080
2021/09/09 09:00:44 moved volume 860 from 10.84.101.119:8080 to 10.84.101.134:8080
  moving  volume prod-pgbackrest_309 10.84.101.119:8080 => 10.84.101.109:8080
2021/09/09 09:00:44 copying volume 309 from 10.84.101.119:8080 to 10.84.101.109:8080
2021/09/09 09:01:19 tailing volume 309 from 10.84.101.119:8080 to 10.84.101.109:8080
error: tail volume 309 from 10.84.101.119:8080 to 10.84.101.109:8080: rpc error: code = Unknown desc = mismatching cookie 0
> volume.fix.replication
volume 309 replication 001, but over replicated +3
deleting volume 309 from 10.84.101.130:8080 ...
```
We could previously balance volumes without issue, something must have happened in the cluster to cause this. It sometimes fails on the first volume it tries to balance, and somtimes manages to balance a few volumes before it fails. We have tried restarting the entire cluster (master, volume and filers).

**System Setup**
- OS version: CentOS 8
- output of `weed version`: `version 30GB 2.59 a45bbc0 linux amd64`

**Expected behavior**
Balancing volumes should work without errors. 

Please let me know if I can provide further information!

**Comment by chrislusf** [comment]
This has been fixed. Use the latest version.

**Comment by MannerMan** [comment]
@chrislusf I looked through the release notes previously but could not find a mentioning of a fix for this issue. Anyways, patching to the latest release did indeed fix the problem - closing this issue!
