### ISSUE TITLE
Is there an API for batch read from specific volume?

### ISSUE THREAD

**Issue by sman908** [chrislusf/seaweedfs#2330]
Let's say I want to upload a lot of files and I know that they will be processed together in most cases.
Is there a way to read them all in one request?

**Comment by chrislusf** [comment]
There are API to copy the .dat and .idx files to local, used by erasure encoding.

**Comment by sman908** [comment]
@chrislusf I don't think that it's what I'm talking about. I want to stream files (as tar for example) to be able to start processsing right away. Downloading `.dat` and `.idx` will probably wouldn't allow streaming.

Still, what's the API? Can you point to the documentation on it? And suppose I download `.idx` first. Can I then stream `.dat` and transform it into list of files on the fly?

**Comment by chrislusf** [comment]
> Still, what's the API? Can you point to the documentation on it? And suppose I download `.idx` first. Can I then stream `.dat` and transform it into list of files on the fly?

See https://github.com/chrislusf/seaweedfs/blob/e5fc35ed0c970fea060a5b3b7a3f5efb5af425d6/weed/server/volume_grpc_copy.go#L145

**Comment by chrislusf** [comment]
Added API to read all needles in a volume https://github.com/chrislusf/seaweedfs/blob/master/weed/pb/volume_server.proto#L61
