### ISSUE TITLE
customize fid

### ISSUE THREAD

**Issue by Ne00n** [chrislusf/seaweedfs#2331]
Hey again,

In an issue a while back, you said the fid can be customized.
Does that still work and when yes any example?

Reference: https://github.com/chrislusf/seaweedfs#write-file (assign)

Otherwise I need to use another datastore.

Ne00n

**Comment by chrislusf** [comment]
see https://github.com/chrislusf/seaweedfs/wiki/Optimization#insert-with-your-own-keys
