### ISSUE TITLE
Insufficient Space How do I delete a file with a specified date

### ISSUE THREAD

**Issue by bboxzhen** [chrislusf/seaweedfs#2335]
**System Setup**
- "weed master", "weed volume"
-  Debian
- version 8000GB 2.36 6b7aa96 linux amd64
- if using filer, show the content of `filer.toml`

**Expected behavior**

Now that the disk space is almost full, what do I need to do to delete the specified data instead of deleting all of it. As far as I know, volume shrinkage also requires space

**Screenshots**
![image](https://user-images.githubusercontent.com/39783629/132967404-1b5af6c8-9ad0-4e2a-af17-64384b4109f4.png)

**Additional context**

**Comment by chrislusf** [comment]
Create another volume server and move a few volumes there.

**Comment by bboxzhen** [comment]
> 创建另一个卷服务器并在那里移动一些卷。

Check whether the destination  server has the same volume ID

**Comment by bboxzhen** [comment]
> Create another volume server and move a few volumes there.
Check whether the destination  volume  server has the same volume ID
