### ISSUE TITLE
iam gateway(8111) api  takes effect only after s3 gateway is restarted？

### ISSUE THREAD

**Issue by huamr** [chrislusf/seaweedfs#2342]
Invoking an iam PutUserPolicy api to add a policy to a user takes effect only after s3 gateway is restarted.
The problem occurs when iam gateway and s3 gateway are deployed independently or together

**Comment by chrislusf** [comment]
This should work. Need a way to reproduce. 

cc @kmlebedev

**Comment by kmlebedev** [comment]
Yes, I have the same bug

**Comment by chrislusf** [comment]
how to make a call to PutUserPolicy?

**Comment by kmlebedev** [comment]
> how to make a call to PutUserPolicy?
but it is enough to check through weed shell s3.configure
https://github.com/chrislusf/seaweedfs/wiki/AWS-IAM-CLI

**Comment by kmlebedev** [comment]
I just switched today to launch c3 separately from the filler
and in the logos there were records about updates
```
Sep 24, 2021 @ 13:44:21.037 | I0924 08:44:20     1 auth_credentials_subscribe.go:29] updated /etc/iam/identity.json | s3
-- | -- | --
  | Sep 24, 2021 @ 13:44:21.041 | I0924 08:44:20     1 filer_notify.go:57] notifying entry update /etc/iam/identity.json | filer
  | Sep 24, 2021 @ 13:44:21.041 | I0924 08:44:20     1 filerstore_wrapper.go:148] UpdateEntry /etc/iam/identity.json | filer
```
