### ISSUE TITLE
filer server is bind to  a specific collection in command option

### ISSUE THREAD

**Issue by hxiaodon** [chrislusf/seaweedfs#235]
Hi,Chris

The JavaScript and CSS files could be cached by the Nginx server with their absolute full path involved, this is convenient for FE to refer them seamlessly. And you also developed the filer service which map file full path into file ID to achieve the same goal but with higher performance

I have 1 question:
The filer server 's collection property is changeless when it is started in current build, when a seaweedfs cluster will store a bunch of files which belongs to multiple collections, we should launch filer services against each collection at least once, and maybe files in one of the collections will not be frequently accessed while the other collections' accessing are very hot. The filer services 's loading is not balanced

I'm wondering if it is reasonable to let the filer server become stateless with collection, it means we can pass the collection parameter in http request(as replication option did), so we could build a filer services' cluster  easily, and effectively save machine resources 

Thanks!

**Comment by chrislusf** [comment]
Thanks for the suggestion! This came up before also. We can add this feature. Need to have an easy to use way to specify collection parameters.

**Comment by hxiaodon** [comment]
Please review the pull request, https://github.com/chrislusf/seaweedfs/pull/236
Thanks!

**Comment by chrislusf** [comment]
Hi, Thanks! It looks fine. I want to know how it is tested, and whether it
helped your use case.

Chris

**Comment by chrislusf** [comment]
I am not too sure whether any other operations will get affected after this
fix.

**Comment by hxiaodon** [comment]
Chris,
I made a test at my laptop
1. create a clean seaweedfs: 1 master, 1 volume(max volume size is 21) and 1 filer
2.  run following commands
     > curl -F "filename=@myfe.pptx" "http://localhost:8888/path/to/sources/?collection=test"
     > curl -F "filename=@myfe.pptx" "http://localhost:8888/path/to/sources/?collection=hello"
    >  curl -F "filename=@myfe.pptx" "http://localhost:8888/path/to/sources/"
3.  check the volume server's data

**Comment by hxiaodon** [comment]
Chris
I know what you mean
The filer service will just map the absolute full path to a unique file id without the collection info, when we try retrieving the resources by http get method,  some unexpected issue will occur...
For example, if we store /path/to/sources/myfe.pptx in different collection, and the file data(myfe.pptx) will diff from each other, the filer db store will overwrite and only save the last  file's file id,  even I change the filer code to support the collection query parameter in get request,  I will get the same data response.

I' m wondering if I could use the following workaround way to bypass/solve this issue
For example, when handling the post request(upload file), adding the collection as a prefix into the absolute path implicitly(in code),  and db store will save the full path like ' /collection/path/to/sources/myfe.pptx', when a user send a get request with a collection, I will firstly pre-append it to construct a new path and then search it in db store
What about your suggestions? Thanks!

**Comment by chrislusf** [comment]
How about using /collection/<collection_name>/path/to/file ?

**Comment by hxiaodon** [comment]
It looks good
From end user's perspective, it is transparent, he could use below way to update file
curl -F "filename=@myfe.pptx" "http://localhost:8888/path/to/sources/?collection=collectionName"
The program should save the final full path as /collectionName/path/to/sources/myfe.pptx 
if the filer service did not bind to a collection, and end user try the following command
curl -F "filename=@myfe.pptx" "http://localhost:8888/path/to/sources"
The program would save the  final full path as /path/to/sources/myfe.pptx

When end user try to download the file, he could specify the collection
curl "http://localhost:8888/path/to/sources/myfe.pptx?collection=collectionName" 
we should search /collection/path/to/sources/myfe.pptx from db store and respond  this file to user 
if no collection specified in url,  /path/to/sources/myfe.pptx will be used instead

If all above is reasonable, I will create a pull request
Thanks~

**Comment by chrislusf** [comment]
I mean we can require path with the format of /collection/collection Name/path/to/file, and store it as is.

This way, we do not need to add many additional features.

**Comment by hxiaodon** [comment]
I see. Then the code change will be focused on post request, parsing url path and get collection name and find volume against this collection. No /collection/$collectionName specified, current code logic could handle

**Comment by chrislusf** [comment]
URL parameter collection=<collection name> is supported during filer writes.
