### ISSUE TITLE
volume.tier.download unexpected EOF

### ISSUE THREAD

**Issue by Hower-Pan** [chrislusf/seaweedfs#2350]
Hi 
I build 2 site seaweedfs enable s3 tier upload volume by collection to remote site
but I try  to tier download some collection in local site 
I got some volume  "unexpected EOF" msg'
can help me to solve this problem

                                                  thank you

version: 30GB 2.64 95e2b83ca5e8c23a775b4cda6519fc8e5f1161af linux amd64

<img width="823" alt="image" src="https://user-images.githubusercontent.com/33602331/135578671-15d2666c-6b82-4a7c-90d4-1703ac3723a9.png">

<img width="490" alt="image" src="https://user-images.githubusercontent.com/33602331/135578703-1d9e8333-c3d5-4a56-8078-651e911de233.png">

**Comment by chrislusf** [comment]
seems some problem with the remote site. May restart will help. No more clue.

**Comment by chrislusf** [comment]
closing since no more updates

**Comment by Hower-Pan** [comment]
Sorry I forgot reply this email
I had fix my problem
this case is my fault , I had ghost datanode(same ip) so unexpected

thank your help..

Chris Lu ***@***.***> 於 2021年11月3日 週三 上午4:24寫道：
