### ISSUE TITLE
Cannot create or access buckets

### ISSUE THREAD

**Issue by selfagency** [chrislusf/seaweedfs#2358]
**Describe the bug**
Following the directions here, I downloaded and ran `seaweedfs-compose.yml` and spun up a proxy server with a valid https certificate in front of it. Everything spun up properly and I was able to log in using an S3 client (Cyberduck). However, when I tried to create a bucket, I got the error: `Internal error. Received fatal alert: internal_error. Please contact your web hosting service provider for assistance.` I tried a different S3 client (Transmit) and was able to create a bucket, but then when I tried to access it, I got the error: `Could not change directory to “test”. Key not found. This can occur if the directory was not originally created by Transmit.` Yet when I go back to the other S3 client, the bucket is there! When I try to access it, however, I again get the error: `Internal error. Received fatal alert: internal_error. Please contact your web hosting service provider for assistance.`

The Prometheus service also crashes on launch but that's a separate issue.

**System Setup**
- `wget https://raw.githubusercontent.com/chrislusf/seaweedfs/master/docker/seaweedfs-compose.yml`
- `docker-compose -f seaweedfs-compose.yml -p seaweedfs up`
- MacOS 12.0 Beta running Docker for M1 Macs

**Expected behavior**
To be able to create buckets and write to the fileserver.

**Comment by chrislusf** [comment]
How/Did you setup the access/secret keys?

**Comment by selfagency** [comment]
I didn't. I thought you didn't need to for development.
