### ISSUE TITLE
goraft is not safe, why not change to etcd

### ISSUE THREAD

**Issue by better0332** [chrislusf/seaweedfs#237]
at least, goraft seems not have read consistency

**Comment by chrislusf** [comment]
etcd is another component to install?

**Comment by better0332** [comment]
type MaxVolumeIdCommand struct {
	MaxVolumeId storage.VolumeId `json:"maxVolumeId"`
}
it seems sync for all master servers, but goraft is not strict read consistency(eg, when network partition, it may have two leader)

**Comment by chrislusf** [comment]
you are right.

I am wondering how etcd solve this problem, because it basically uses the same raft protocol.

**Comment by dgryski** [comment]
I believe the new raft package for etcd was designed to able to be used standalone: https://github.com/coreos/etcd/tree/master/raft

**Comment by chrislusf** [comment]
Thanks Damian for the tip!

About the partitioned network, this would not be a problem for the max volume id according to raft protocol. In this case, only one part with most majority can elect a leader. The part can only serve read requests.

**Comment by better0332** [comment]
" if a leader is partitioned from the remaining peers, a new leader may be elected while the old leader is holding the lease. This means there are 2 leader nodes"
https://www.consul.io/docs/internals/consensus.html(look "Consistency Modes")

etcd have Read Linearization use  a quorum=true
func (t *Topology) NextVolumeId() storage.VolumeId {
	vid := t.GetMaxVolumeId()
	next := vid.Next()
	go t.RaftServer.Do(NewMaxVolumeIdCommand(next)) //this can't sync for read only part, not block
	return next
}
The read only part node always get same VolumeId for NextVolumeId, it also may same as another leader assign NextVolumeId, then i confused

**Comment by chrislusf** [comment]
Right. The NextVolumeId() function needs to wait for writes to finish before returning the value.

**Comment by better0332** [comment]
Actually, wait NextVolumeId() is not enough(node may set same VolumeId when).I think its a design problem

**Comment by better0332** [comment]
I think VolumeId shoude be a atomic add opration.
https://github.com/coreos/etcd/blob/master/Documentation/api.md (Atomically Creating In-Order Keys)

**Comment by chrislusf** [comment]
With partitioned clusters, the commit would fail if it is on the wrong cluster.
