### ISSUE TITLE
Compared to IPFS?

### ISSUE THREAD

**Issue by lonnietc** [chrislusf/seaweedfs#2372]
Hello,

Just came across SeaweedFS and it seems to be pretty good from what I have read, but was wondering how it compares against IPFS which seems to do something similar and can also handle millions of files across millions of nodes?

I'm just trying to get an idea on things.

Thanks in advance

**Comment by chrislusf** [comment]
they are very different.

**Comment by lonnietc** [comment]
Thanks for the reply, but your response really did not help me understand how.

No worries as it seems like you did not want to really answer this question and just closed the post.  I will search for answers elsewhere.
