### ISSUE TITLE
What is master server, what is volume server, what is filer server?

### ISSUE THREAD

**Issue by netroby** [chrislusf/seaweedfs#238]
What is master server, what is volume server, what is filer server?

Can't quite get the three server type.

how to using them together?

Filer server  =>   Master server  => Volume server ?

**Comment by chrislusf** [comment]
master server and volume server work together to provide id-to-data service. You can use only this two if this is what you need.
filer server provide path-to-id service.

Filer server => Master server => Volume server will provide path-to-data
