### ISSUE TITLE
How to use Filer grpc API to retrieve the content of an object

### ISSUE THREAD

**Issue by douardda** [chrislusf/seaweedfs#2392]
Hi,

I am trying to use the Filer grpc API (from Python 3.8), and I can list the content of a directory with `ListEntries` but then, I cannot get its content.

I've generated the python code for the filer proto using:
```
python -m grpc_tools.protoc filer.proto
```
from the `seaweedfs/weed/pb/` directory (clone at rev 182f43ae).

Here is my code:

```
>>> import grpc
>>> import filer_pb2_grpc
>>> import filer_pb2
>>> channel = grpc.insecure_channel('10.0.0.11:18888')
>>> stub = filer_pb2_grpc.SeaweedFilerStub(channel)
>>> response = stub.ListEntries(filer_pb2.ListEntriesRequest(directory='/test'))
>>> print(list(response))
[entry {
  name: "1615307cc4523f183e777df67f168c86908e8007"
  chunks {
    size: 6
    mtime: 1634717912839796613
    e_tag: "qM/eYzG9WesqyW+JEcS2Zg=="
    fid {
      volume_id: 6
      file_key: 82
      cookie: 2347951551
    }
    is_compressed: true
  }
  attributes {
    file_size: 6
    mtime: 1634717912
    file_mode: 432
    crtime: 1634717912
    md5: "\250\317\336c1\275Y\353*\311o\211\021\304\266f"
  }
}
, entry {
  name: "tutu.txt"
  chunks {
    size: 16012
    mtime: 1634558857163328538
    e_tag: "qZkakE2niG7+BdwZvLHv+w=="
    fid {
      volume_id: 4
      file_key: 78
      cookie: 2555817740
    }
    is_compressed: true
  }
  attributes {
    file_size: 16012
    mtime: 1634558857
    file_mode: 432
    crtime: 1634558857
    mime: "text/markdown"
    md5: "\251\231\032\220M\247\210n\376\005\334\031\274\261\357\373"
  }
}
]
>>> r=stub.DownloadToLocal(filer_pb2.DownloadToLocalRequest(directory="/test", name="tutu.txt"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/devel/test_grpc/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/devel/test_grpc/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "filer: no entry is found in filer store"
	debug_error_string = "{"created":"@1634807272.142411158","description":"Error received from peer ipv4:10.0.0.11:18888","file":"src/core/lib/surface/call.cc","file_line":1069,"grpc_message":"filer: no entry is found in filer store","grpc_status":2}"
```
As you can see, I can list the content of the `/test` directory, in which there is a `tutu.txt` file, but I cannot retrieve it using `DownloadToLocal`.

So:
- what am I doing wrong? (I suspect the `DownloadToLocal` is not what I think it is, and may be more related to the peering feature).
- where can I find some documentation of each function available as a grpc service endpoint? I've tried to look at the code a bit, but I couldn't find some documentation-like content in there.
- my understanding at this point is that there is no "high level" grpc API endpoint equivalent to a simple http GET and I need to first get the list of chunks (that I know how to do) then retrieve each chunck content from volumes etc. in the (python) client code, right?

Thanks a lot

**Comment by chrislusf** [comment]
* `DownloadToLocal` is for caching from remote object store.
* No gRPC documents yet. Most of the gRPC APIs are for internal usage.
* Correct. No gRPC API to get the file content. Better use http API directly.
