### ISSUE TITLE
Using Seaweed FS for P2P?

### ISSUE THREAD

**Issue by lonnietc** [chrislusf/seaweedfs#2402]
Hello,

I am researching for viable Golang components for a P2P project in which the nodes will share data storage.

What I am wondering is how stable Seaweed FS is to nodes being added and removed dynamically?

Also, does the design of Seaweed FS imply that each P2P node would have to have its own directory when mapped into the system?  

Any information that you would provide would be greatly appreciated.
Thanks in advance

**Comment by chrislusf** [comment]
there are no p2p nodes. What you mean may be volume servers. Volume servers can be added or removed dynamically. They do not need to map their local directories to the system, but rather just provide storage space to the system.
