### ISSUE TITLE
Searching across all volumes for a file?

### ISSUE THREAD

**Issue by lonnietc** [chrislusf/seaweedfs#2404]
Hello,

I have been playing around with Seaweed and working with the information on the Github site, but was wondering if there was a way to search for a file across all volumes?

Thanks

**Comment by chrislusf** [comment]
What's your use case? Search by name, attributes, or text?

**Comment by lonnietc** [comment]
Hello,

Mostly exploring by name.

Considering how it might be used in a new P2P type application where each
node is a Seaweed volume.

**Comment by chrislusf** [comment]
You can have this process running, and index SeaweedFS metadata changes on an elastic search server:
`weed filer.meta.tail -timeAgo=30h -es=http://<elasticSearchServerHost>:<port> -es.index=seaweedfs`

**Comment by lonnietc** [comment]
Thanks for the information as it will be very useful in this build effort.

Have done some basic testing with Seaweed and it really is an awesome piece
of software.
