### ISSUE TITLE
weedfs for streaming videos?

### ISSUE THREAD

**Issue by butaixianran** [chrislusf/seaweedfs#241]
hi, weedfs is great in many ways, is it possible to use it for online videos?

Normally, video file size is from 300mb to 2gb.
For now, I even can't find an api to cut big file into chunks with Filer.

Is there any suggestion? or is there any plan for this in the future?

thanks, weed is really great

**Comment by chrislusf** [comment]
Currently the "weed upload" command supports chunking.

**Comment by butaixianran** [comment]
we won't use weed cli for uploading and downloading, it'll be great if this can be done with filer's http rest api.

**Comment by ArtworkAD** [comment]
Related: https://github.com/chrislusf/seaweedfs/issues/197 Did anything significant change that now makes it possible to stream videos using seaweedfs? I would love to do some testing if @chrislusf confirms that it is possible :+1:

**Comment by jjn2009** [comment]
Use something like ffmpeg to segment your files into a format like HLS.

**Comment by chrislusf** [comment]
The video file split and uploading should happen on client side, not on the master side. Current seaweedfs should not try to add more special logic for this..
