### ISSUE TITLE
"error: unexpected" when use docker image on Rasperry pi 4

### ISSUE THREAD

**Issue by tulequ** [chrislusf/seaweedfs#2418]
**Describe the bug**
can't use arm64 docker image on rasperry pi 4

**System Setup**
- Command:
```
$ docker run --rm -it chrislusf/seaweedfs
/usr/bin/weed: line 1: syntax error: unexpected "("

$ docker run --rm -it chrislusf/seaweedfs:2.76
/usr/bin/weed: line 1: syntax error: unexpected end of file (expecting ")")

# but if I download linux_arm64 then mount to docker, it will success
$ docker run --rm -it -v $HOME/weed:/usr/bin/weed chrislusf/seaweedfs
SeaweedFS: store billions of files and serve them fast!
...
```
- OS version: raspbian 10.10

**Expected behavior**
Should working on rasperry pi 4

**Comment by chrislusf** [comment]
Can not help much since I do not have access to rasperry pi.

Seems it was trying to execute https://github.com/chrislusf/seaweedfs/blob/master/docker/entrypoint.sh

**Comment by tulequ** [comment]
ok, I will try debug myself and update later
Does the image build from this file https://github.com/chrislusf/seaweedfs/blob/master/docker/Dockerfile?

But it happen when I run the binary file, not the entrypoint.sh

**Comment by chrislusf** [comment]
Currently the docker image for `chrislusf/seaweedfs:latest` is from
https://github.com/chrislusf/seaweedfs/blob/master/.github/workflows/container_latest.yml
which uses
https://github.com/chrislusf/seaweedfs/blob/master/docker/Dockerfile.go_build

**Comment by tulequ** [comment]
```
$ docker run --rm -it --entrypoint sh chrislusf/seaweedfs
/ # apk add file
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/aarch64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/aarch64/APKINDEX.tar.gz
(1/2) Installing libmagic (5.40-r1)
(2/2) Installing file (5.40-r1)
Executing busybox-1.33.1-r3.trigger
OK: 13 MiB in 18 packages
/ # file /usr/bin/weed
/usr/bin/weed: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=y82yWKl36bY4Y2fhucPf/Z4wobYZqXuJnr64adh1D/_e5Rbtdaox_5jEJilw8f/GXs8RisRZKL2vjX8LX4N, not stripped
/ # file /bin/busybox
/bin/busybox: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-aarch64.so.1, stripped
/ #
```
maybe something wrong with build process, it output x86-64 execute, it must be aarch64

**Comment by tulequ** [comment]
```
FROM amd64/golang:1.17-alpine as builder
```
I don't know why use amd64 here? or we must set GOARCH?

**Comment by chrislusf** [comment]
Thanks for debugging! Added a fix.
