### ISSUE TITLE
how to set volume's count

### ISSUE THREAD

**Issue by shenlanzifa** [chrislusf/seaweedfs#242]
how to set volume's count, i use the below script:

 nohup ./weed server -master.port=9333 -dir=/server1 -master.defaultReplicaPlacement="001" -volume.port=9080 -volume.max=9 -master.peers=localhost:9333,localhost:9334,localhost:9335 &>server1.log &
  sleep 1
  nohup ./weed server -master.port=9334 -dir=/server2 -master.defaultReplicaPlacement="001" -volume.port=9081 -volume.max=9 -master.peers=localhost:9333,localhost:9334,localhost:9335 &>server2.log &
  sleep 1
  nohup ./weed server -master.port=9335 -dir=/server3 -master.defaultReplicaPlacement="001" -volume.port=9082 -volume.max=9 -master.peers=localhost:9333,localhost:9334,localhost:9335 &>server3.log &

but -volume.max=9 seems does not work.  the volume's count is 6, not 9

**Comment by chrislusf** [comment]
volume.max=9 is the maximum number of volumes per volume server.

The volume count 6 is the actual number of volume created.

This may be what you actually wanted:
https://github.com/chrislusf/seaweedfs/wiki/Optimization#increase-concurrent-writes
