### ISSUE TITLE
Documentaton request: how to add seaweed fs volume to existing docker container

### ISSUE THREAD

**Issue by AlexMikhalev** [chrislusf/seaweedfs#2420]
I am successfully running seaweed fs on 3 RPI4, I would like to add seaweed fs volumes ( mounted via s3  for example) to media servers like emby or plex.  
Volumes will store photos and videos, so a single weed volume mount would not suffice, but s3 collection seems appropriate. 
I have seen https://github.com/chrislusf/seaweedfs/wiki/Deployment-to-Kubernetes-and-Minikube, but I am not ready to dig into Kubernetes (I prefer nomad). 
So, how to add seaweed fs volume to the existing docker image?

**Comment by chrislusf** [comment]
If I am not missing anything, you just need to `weed mount`. See https://github.com/chrislusf/seaweedfs/wiki/FUSE-Mount
