### ISSUE TITLE
AWS SDK for Java2.x AnonymousCredentialsProvider匿名访问seaweedfs出错

### ISSUE THREAD

**Issue by wdx-doge** [chrislusf/seaweedfs#2426]
遇到一个问题，使用AWS SDK for Java2.x的AnonymousCredentialsProvider匿名凭证访问seaweedfs的时候会出现问题：
a.使用AWS SDK for Java2.x的AnonymousCredentialsProvider匿名凭证，无法访问”weed filer -s3形式部署的seaweedfs”；
b.使用AWS SDK for Java2.x的AnonymousCredentialsProvider匿名凭证，可以访问“weed filer + weed s3形式部署的seaweedfs”；
c.AWS SDK for Java1.x的匿名凭证可以同时访问 "weed filer -s3形式部署的seaweedfs" 和 "weed filer + weed s3形式部署的seaweedfs"

**Comment by wdx-doge** [comment]
![image](https://user-images.githubusercontent.com/59191196/140846564-72423d03-86a8-47f8-8f27-f955d727591f.png)

**Comment by chrislusf** [comment]
How did you configure the endpoint? I see it points to filer http port, not SeaweedFS S3 default 8333 port.

If that is not the problem, please show the startup commands.

**Comment by wdx-doge** [comment]
.\weed filer -s3 -master="127.0.0.1:9333" -ip="127.0.0.1" -port=8888

**Comment by wdx-doge** [comment]
.\weed filer -s3 -master="127.0.0.1:9333" -ip="127.0.0.1" -port=8888

**Comment by wdx-doge** [comment]
### the startup commands：
.\weed master -ip=127.0.0.1
.\weed volume -dir="C:\Users\wdx\Desktop\weed\data" -mserver="127.0.0.1:9333" -dataCenter=dc1 -index=leveldb
.\weed filer -s3 -master="127.0.0.1:9333" -ip="127.0.0.1" -port=8888
### the code:
        try {
            URI uri = new URI("http://127.0.0.1:8888");
            S3Client  s3Client = S3Client.builder()
                    .region(Region.of("cn-north-1"))
                    .credentialsProvider(AnonymousCredentialsProvider.create())
                    .endpointOverride(uri)
                    .build();
                    File file = new File("C:\\Users\\wdx\\Desktop\\01.jpg");
             s3Client.createBucket(CreateBucketRequest.builder().bucket("test").build());
             s3Client.putObject(PutObjectRequest.builder().bucket("test").key("01.jpg").build(), RequestBody.fromFile(file));
        } catch (URISyntaxException e) {
             log.error("TestS3存储客户端失败！", e);
        }
### the filer before test:

**Comment by wdx-doge** [comment]
> ### the startup commands：
> .\weed master -ip=127.0.0.1 .\weed volume -dir="C:\Users\wdx\Desktop\weed\data" -mserver="127.0.0.1:9333" -dataCenter=dc1 -index=leveldb .\weed filer -s3 -master="127.0.0.1:9333" -ip="127.0.0.1" -port=8888
> 
> ### the code:
> ```
>     try {
>         URI uri = new URI("http://127.0.0.1:8888");
>         S3Client  s3Client = S3Client.builder()
>                 .region(Region.of("cn-north-1"))
>                 .credentialsProvider(AnonymousCredentialsProvider.create())
>                 .endpointOverride(uri)
>                 .build();
>                 File file = new File("C:\\Users\\wdx\\Desktop\\01.jpg");
>          s3Client.createBucket(CreateBucketRequest.builder().bucket("test").build());
>          s3Client.putObject(PutObjectRequest.builder().bucket("test").key("01.jpg").build(), RequestBody.fromFile(file));
>     } catch (URISyntaxException e) {
>          log.error("TestS3存储客户端失败！", e);
>     }
> ```
> 
> ### the filer before test:
> ![image](https://user-images.githubusercontent.com/59191196/140849405-4e979cc4-e44c-4129-8f83-31bfca72735c.png)
> 
> ### the filer after test:
> ![image](https://user-images.githubusercontent.com/59191196/140849477-34a81b58-10df-407b-bfda-769f67c0ee71.png) ![image](https://user-images.githubusercontent.com/59191196/140849493-734964f0-6ff7-42af-8d42-c2d09b8e8219.png)

change the startup commands from
  ".\weed filer -s3 -master="127.0.0.1:9333" -ip="127.0.0.1" -port=8888"
to 
  ".\weed filer -master="127.0.0.1:9333" -ip="127.0.0.1" -port=8888 
   .\weed s3  -filer="127.0.0.1:8888" -port=9000"
change the dode from
  "URI uri = new URI("http://127.0.0.1:8888");" 
to
  "URI uri = new URI("http://127.0.0.1:9000");"
can get the right results

**Comment by chrislusf** [comment]
Use s3 port 8333

**Comment by wdx-doge** [comment]
thanks
