### ISSUE TITLE
Tracking issue for filer service(updating and deleting) with cassandra store

### ISSUE THREAD

**Issue by hxiaodon** [chrislusf/seaweedfs#243]
Chris,
Claudiu reported some errors when using filer with cassandra store
https://github.com/chrislusf/seaweedfs/pull/239
Please help to take a review
Thanks!

**Comment by chrislusf** [comment]
This line should take care of actual deletion from volume servers.

https://github.com/chrislusf/seaweedfs/blob/master/go/weed/weed_server/filer_server_handlers.go#L256
