### ISSUE TITLE
Filer dataCenter parameter does not prioritize reads from the specified DC 

### ISSUE THREAD

**Issue by LuckyFrost** [chrislusf/seaweedfs#2441]
For example, we write data through filer S2 (DC1) with replication 100, then we try to read same data from the same filer S2 (DC1) and as a result, some of the readings come from DC2.
According to weed filer -help , this doesn't seem to work as described 
```
  -dataCenter string
        prefer to read and write to volumes in this data center
```

List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
```
S1:
/opt/weed -logdir=/var/log/weed filer -ip=S1 -s3 -defaultReplicaPlacement=100 -dataCenter=DC1
/opt/weed -logdir=/var/log/weed master -ip=S1 -mdir=/srv/mweed/  -volumeSizeLimitMB=307200 -defaultReplication=100 -peers=S2:9333,S1:9333,S3:9333 -metrics.address=m_ip:9091
/opt/weed -logdir=/var/log/weed volume -ip=S1 -mserver=S2:9333,S1:9333,S3:9333 -dir=/backup/vweed -dir.idx=/srv/vweed/ -disk=hdd -compactionMBps=40 -dataCenter=vin1 -rack=V1 -max=0

S2:
/opt/weed -logdir=/var/log/weed filer -ip=S2 -s3 -defaultReplicaPlacement=100 -dataCenter=DC1
/opt/weed -logdir=/var/log/weed master -ip=S2 -mdir=/srv/mweed/  -volumeSizeLimitMB=307200 -defaultReplication=100 -peers=S2:9333,S1:9333,S3:9333 -metrics.address=m_ip:9091
/opt/weed -logdir=/var/log/weed volume -ip=S2 -mserver=S2:9333,S1:9333,S3:9333 -dir=/backup/vweed -dir.idx=/srv/vweed/ -disk=hdd -compactionMBps=40 -dataCenter=vin1 -rack=V2 -max=0

S3:
/opt/weed -logdir=/var/log/weed filer -ip=S3 -s3 -defaultReplicaPlacement=100 -dataCenter=DC2
/opt/weed -logdir=/var/log/weed master -ip=S3 -mdir=/srv/mweed/  -volumeSizeLimitMB=307200 -defaultReplication=100 -peers=S2:9333,S1:9333,S3:9333 -metrics.address=m_ip:9091
/opt/weed -logdir=/var/log/weed volume -ip=S3 -mserver=S2:9333,S1:9333,S3:9333 -dir=/backup/vweed -dir.idx=/srv/vweed/ -disk=hdd -compactionMBps=40 -dataCenter=hil1 -rack=H1 -max=0
```

output of weed version
`version 8000GB 2.76 fc9e246592351085b31ce9ad0d6a4790fa54b4f1 linux amd64`

**Comment by ekhvalov** [comment]
Here some [code](https://github.com/chrislusf/seaweedfs/blob/master/weed/wdclient/vid_map.go#L73) that probably select volumes. The problem is that the volumes from other data centers also added to list even though to the end of the list. If it really needed to query only specific data center, then volumes from other data centers should be removed from that list.

**Comment by LuckyFrost** [comment]
> Here some [code](https://github.com/chrislusf/seaweedfs/blob/master/weed/wdclient/vid_map.go#L73) that probably select volumes. The problem is that the volumes from other data centers also added to list even though to the end of the list. If it really needed to query only specific data center, then volumes from other data centers should be removed from that list.

Just in case, I note that there should be an opportunity to read from another data center in case of loss of volume in the current one.

**Comment by chrislusf** [comment]
Right. The dc option is more a preference. The remote dc is a backup.

**Comment by chrislusf** [comment]
added code to randomize local dc and remote dc servers.
