### ISSUE TITLE
[filer] fs.filer.AggregateFromPeers is not required functionality

### ISSUE THREAD

**Issue by kmlebedev** [chrislusf/seaweedfs#2450]
It seems this is not required functionality for SQL store ?
https://github.com/chrislusf/seaweedfs/blob/c4e22b5a9a38979a922a400d0fb3a4d74dbe417c/weed/server/filer_server.go#L145

i have 
Since there was no connection between DC
```
I1115 11:08:44     1 meta_aggregator.go:100] connecting to peer filer 172.24.197.137:9090: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 172.24.197.137:19090: i/o timeout"
```

**System Setup**
```
2.78
```

**Comment by chrislusf** [comment]
It is not required if both are true:
* using SQL store
* not using `weed mount`, replication, etc which needs to listen to metadata events.
