### ISSUE TITLE
Weed fix fails on "negative offset" after server restart

### ISSUE THREAD

**Issue by charnger** [chrislusf/seaweedfs#2456]
**Describe the bug**
We have a system with 2 physical nodes which run 2 volume servers (one on each), 3 masters and 2 filers. Server1 needed to be restarted. Upon restart, we're seeing on:
`volume_loading.go:123] volumeDataIntegrityChecking failed verifyIndexFileIntegrity /mnt/image/weed/51.idx failed: index file's size is 47874048 bytes, maybe corrupted 
`
I fixed vol 51 (and 2 more) with:
`weed fix -volumeId 51
`
Now, the server starts up to vol 54 - I am getting the same error there, but fix fails:
```
weed fix -volumeId 54
I1117 04:03:40 03717 volume_loading.go:86] readSuperBlock volume 54 version 3
F1117 04:07:25 03717 fix.go:82] scan .dat File: cannot read needle header at offset -1392805776: readat 54.dat: negative offset
goroutine 1 [running]:
github.com/chrislusf/seaweedfs/weed/glog.stacks(0x0)
        /github/workspace/weed/glog/glog.go:767 +0x8a
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).output(0x3bde7a0, 0x3, 0xc00026c1c0, {0x2de8ca2, 0xc000853e78}, 0x1, 0x0)
        /github/workspace/weed/glog/glog.go:718 +0x3ab
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).printf(0x233882e, 0x1, {0x2357260, 0x12}, {0xc000853e78, 0x1, 0x1})
        /github/workspace/weed/glog/glog.go:656 +0x110
github.com/chrislusf/seaweedfs/weed/glog.Fatalf(...)
        /github/workspace/weed/glog/glog.go:1149
github.com/chrislusf/seaweedfs/weed/command.runFix(0x3bc1cd8, {0xc0001be060, 0x2, 0x2})
        /github/workspace/weed/command/fix.go:82 +0x265
main.main()
        /github/workspace/weed/weed.go:78 +0x3a3

```
What should I do to recover the storage? Can I just copy over the corresponding volume from second node?

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".

```
@server1: weed server -dataCenter=DC2 -master.port=10500 -volume.port=10503 -volume.max=0 -master.defaultReplication=100 -master.volumeSizeLimitMB=500000 -master.peers=server2:10500,server1:10501 -metricsPort=10509 -dir=/mnt/image/weed -filer=true -filer.port=10508 -filer.peers=localhost:10508,server2:10508
@server1: weed master -port=10501 -peers=localhost:10500,server2:10500 -mdir=/mnt/image/weed/second
@server2: weed server -dataCenter=DC1 -master.port=10500 -volume.port=10503 -volume.max=0 -master.defaultReplication=100 -master.volumeSizeLimitMB=500000 -master.peers=server1:10500,server1:10501 -metricsPort=10509 -dir=/mnt/image/weed -filer=true -filer.port=10508 -filer.peers=localhost:10508,server1:10508

```

- OS version: 20.04
- output of `weed version`: version 8000GB 2.74 182f43ae5fa2aed5a2526aaa23390e9b8d376e63 linux amd64

**Expected behavior**
I would expect:

1. Seaweedfs to recover to a read-only mode for the whole system, so that at least one filer would be accessible
2. weed fix to work for volume 54 or any other way to get the system working again

**Comment by LuckyFrost** [comment]
>Can I just copy over the corresponding volume from second node?
You can also try to delete (Or move to another place) volume, and then use the volume.fix.replication. I see this as a more practical option in a production environment, since in this case, the volume server will be able to handle traffic for the remaining volumes. The only drawback is the lack of parallelization, so the process can take a long time.

>Seaweedfs to recover to a read-only mode for the whole system, so that at least one filer would be accessible
I didn't quite understand what the relationship with filer. You can do as many of them as you like and when one falls, use the others. Also, they will not access broken volume servers. Some of the data will be available only for reading and adding, but not changing. 
To automatically fix the situation, you can use scripts in master.toml, however, please note that in this case, you need to have n + 1 in each datacenter/rack

**Comment by charnger** [comment]
> You can also try to delete (Or move to another place) volume, and then use the volume.fix.replication. I see this as a more practical option in a production environment, since in this case, the volume server will be able to handle traffic for the remaining volumes. The only drawback is the lack of parallelization, so the process can take a long time.
I copied the one non-fixable volume directly, fixed all the others and got the server back up. The downtime was non trivial though, so we need to fix the setup so that the redundancy also guarantees availability.

Will run volume.fix.replication as well now.

> I didn't quite understand what the relationship with filer. You can do as many of them as you like and when one falls, use the others. Also, they will not access broken volume servers. Some of the data will be available only for reading and adding, but not changing.

We have two filers, one at each of the two servers. All access to Seaweed FS is done via the filers. The theory was that having 2 volume servers and filers peered with each other, we would survive downtime of one of the servers, albeit in read-only mode

Another question: the server had to be hardware-rebooted, which probably caused the volume inconsistencies and even one unfixable volume. Is that expected?

**Comment by chrislusf** [comment]
> Another question: the server had to be hardware-rebooted, which probably caused the volume inconsistencies and even one unfixable volume. Is that expected?

Correct. To avoid that, need to have 3 servers.

**Comment by charnger** [comment]
> Correct. To avoid that, need to have 3 servers.
3 which servers? Filers? Masters? Volume servers?

**Comment by LuckyFrost** [comment]
@charnger, volume servers

Regarding masters, you must also have an odd number of masters (3/5/etc). This does not affect data consistency, but it does affect availability.

**Comment by charnger** [comment]
@LuckyFrost 
I see. Having 3x data size becomes a bit taxing for us, as one node has around 60TB. The goal was to get RAID1-like redundancy and read-only availability when one of the storage nodes is down. Is that not possible with SeaweedFS?

**Comment by LuckyFrost** [comment]
@charnger,
raid 1 also lacks consistency. If there is a data violation on one disk, you will not know which data is valid.
Actually, this is what you got in the weed and, fortunately, it turned out to identify which of the data is not correct in this case (but not in all)
In this case, you should have had a read-only copy available (when 1 volume fell). Having a problem with this?

**Comment by charnger** [comment]
>raid 1 also lacks consistency. If there is a data violation on one disk, you will not know which data is valid.
Yes. We have raid on the volume storage disks themselves however, so we're not that much concerned about disk-level data violation.

>In this case, you should have had a read-only copy available (when 1 volume fell). Having a problem with this?
The problem was that at that point, the whole system was not accessible. When we restarted everything solely on server2, we pretty much got what we wanted (1-node system that we should not really write to, but is able to serve in read-only mode). If there was a way to make this happen automatically without (long) interruption of service, that would serve our purpose.

**Comment by LuckyFrost** [comment]
I would not be surprised if this is possible, since the storage is positioned as a storage with strong consistency. 
However, I'm still interested - what errors were in filer when trying to read data (If you work through it)?
