### ISSUE TITLE
Filer ignores master parameter

### ISSUE THREAD

**Issue by LuckyFrost** [chrislusf/seaweedfs#2457]
Start command
``` 
/opt/weed -logdir=/var/log/weed master -ip=IP1 -mdir=/srv/mweed2/  -volumeSizeLimitMB=102400 -defaultReplication=000 -peers=IP1:9334,IP2:9334,IP3:9334 -metrics.address=IP4:9091 -port 9334 -port.grpc 19334

/opt/weed -logdir=/var/log/weed filer -ip=IP1 -port=8889 s3.port=8334 -defaultReplicaPlacement=000 -dataCenter=DC1 -master="IP1:9334,IP2:9334,IP3:9334"
```
Result - filer hangs on startup.

And now I started another master on the default port. Restarted filer and in the stdout of the filer:
```I1118 09:53:49 70206 masterclient.go:132] redirected to leader 192.168.0.149:9333```

So it looks like it just ignored the "-master" parameter and tried to connect to the localhost: default_port

**Comment by chrislusf** [comment]
I

> And now I started another master on the default port. Restarted filer and in the stdout of the filer: `I1118 09:53:49 70206 masterclient.go:132] redirected to leader 192.168.0.149:9333`

When the master is started not using the 9334 port, as `IP1:9334,IP2:9334,IP3:9334`, it is standalone and not in the master group. So this is expected.

**Comment by LuckyFrost** [comment]
@chrislusf, You were in a hurry to close the problem or I misunderstood your answer. I will describe in more detail:
Server1
```
/opt/weed -logdir=/var/log/weed master -ip=IP1 -mdir=/srv/mweed2/ -defaultReplication=000 -peers=IP2:9334,IP1:9334,IP3:9334 -port 9334 -port.grpc 19334
/opt/weed -logdir=/var/log/weed master -ip=IP1 -mdir=/srv/mweed/ -defaultReplication=000 -peers=IP2:9333,IP1:9333,IP3:9333
```

Server2
```
/opt/weed -logdir=/var/log/weed master -ip=IP2 -mdir=/srv/mweed2/ -defaultReplication=000 -peers=IP2:9334,IP1:9334,IP3:9334 -port 9334 -port.grpc 19334
/opt/weed -logdir=/var/log/weed master -ip=IP2 -mdir=/srv/mweed/ -defaultReplication=000 -peers=IP2:9333,IP1:9333,IP3:9333
```

Server3
```
/opt/weed -logdir=/var/log/weed master -ip=IP3 -mdir=/srv/mweed2/ -defaultReplication=000 -peers=IP2:9334,IP1:9334,IP3:9334 -port 9334 -port.grpc 19334
/opt/weed -logdir=/var/log/weed master -ip=IP3 -mdir=/srv/mweed/ -defaultReplication=000 -peers=IP2:9333,IP1:9333,IP3:9333
```
Part of output of master on port 9334
`current: IP1:9334 peers:IP2:9334,IP2:9334,IP3:9334`

Now on server1 I started filer:
`/opt/weed -logdir=/var/log/weed filer -ip=IP1 -port=8889 s3.port=8334 -defaultReplicaPlacement=000 -dataCenter=vin1 -master="IP2:9334,IP1:9334,IP3:9334"`

**Comment by chrislusf** [comment]
I see. Your configuration looks correct, but the error seems impossible. 

Can you try to run one master first?

**Comment by LuckyFrost** [comment]
Stopped all masters on all servers and started one on server1:

```
/opt/weed -logdir=/var/log/weed master -ip=IP1 -mdir=/srv/mweed2/  -volumeSizeLimitMB=102400 -defaultReplication=000  -metrics.address=IP4:9091 -port 9334 -port.grpc 19334
....
I1119 10:35:14 08603 masterclient.go:79] No existing leader found!
I1119 10:35:14 08603 raft_server.go:158] Initializing new cluster
I1119 10:35:14 08603 master_server.go:162] leader change event:  => IP1:9334
I1119 10:35:14 08603 master_server.go:164] [ IP1:9334 ] IP1:9334 becomes leader.
...
panic: assertion failed: leader.elected.at.same.term.0


goroutine 63 [running]:
github.com/chrislusf/raft._assert(...)
        /go/pkg/mod/github.com/chrislusf/raft@v1.0.7/util.go:60
github.com/chrislusf/raft.(*server).processAppendEntriesRequest(0xc000bb9200, 0xc0005a6870)
        /go/pkg/mod/github.com/chrislusf/raft@v1.0.7/server.go:983 +0x8df
github.com/chrislusf/raft.(*server).leaderLoop(0xc000bb9200)
        /go/pkg/mod/github.com/chrislusf/raft@v1.0.7/server.go:884 +0x3ba
github.com/chrislusf/raft.(*server).loop(0xc000bb9200)
        /go/pkg/mod/github.com/chrislusf/raft@v1.0.7/server.go:609 +0x165
github.com/chrislusf/raft.(*server).Start.func1()
        /go/pkg/mod/github.com/chrislusf/raft@v1.0.7/server.go:470 +0x5d
created by github.com/chrislusf/raft.(*server).Start
        /go/pkg/mod/github.com/chrislusf/raft@v1.0.7/server.go:468 +0x1bb
```

O_o

What am I doing wrong? ;(

**Comment by LuckyFrost** [comment]
The master stops crashing if I remove these parameters: 
```-port 9334 -port.grpc 19334```

**Comment by chrislusf** [comment]
can you add "=" between the CLI option name and values? Seems they are ignored.

**Comment by chrislusf** [comment]
clean up the directory `/srv/mweed2/` and `-mdir`on other master servers.

**Comment by LuckyFrost** [comment]
Ok, that helped fix the problem with the master. Not obvious enough. 
Filer still shows no signs of life - after launch, it just keeps silent 
`/opt/weed -logdir=/var/log/weed filer -ip=IP1 -port=8889 s3.port=8334 -defaultReplicaPlacement=000 -dataCenter=vin1 -master="IP2:9334,IP1:9334,IP3:9334"
`
I also tried to strace this process and I see that it is trying to connect to localhost + the wrong port: 
```
[pid 208501] connect(8, {sa_family=AF_INET6, sin6_port=htons(19333), inet_pton(AF_INET6, "::1", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, 28) = -1 EINPROGRESS (Operation now in progress)
[pid 208501] getsockopt(8, SOL_SOCKET, SO_ERROR, [111], [4]) = 0
[pid 208501] socket(AF_INET, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = 8
[pid 208501] connect(8, {sa_family=AF_INET, sin_port=htons(19333), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 EINPROGRESS (Operation now in progress)
```

**Comment by chrislusf** [comment]
did you miss a dash in front of `s3.port=8334`?

**Comment by LuckyFrost** [comment]
What a stupid mistake it turned out to be :(
Perhaps it can be closed, only one question remains - is it safe to clear mdir?

**Comment by chrislusf** [comment]
> Perhaps it can be closed, only one question remains - is it safe to clear mdir?

yes.
