### ISSUE TITLE
settings  "-max = 50" parameter problem

### ISSUE THREAD

**Issue by nonempty** [chrislusf/seaweedfs#246]
Hi,chrislusf
$weed  volume -port=8083 -dir=./volume -mserver=localhost:9335 -dataCenter=dc2 -max=50
-max=50：
Whether in ". / volume" directory to create 50 pair .idx and .dat each .dat , What is the maximum storage each  .dat  file

**Comment by chrislusf** [comment]
Each day is 30GB maximum .
