### ISSUE TITLE
S3 permissions is not working

### ISSUE THREAD

**Issue by DiaaEddin** [chrislusf/seaweedfs#2462]
after running `docker run -p 8333:8333 chrislusf/seaweedfs server -s3` then in weed shell
 ```
s3.configure -access_key=test1 -secret_key=test1 user=user1 -actions=Read,Write,List,Tagging,Admin -buckets=test1 -apply
```
and after uploading some files to test1 bucket  when I browse to `localhost:8333/test1` I still get a list of my files inside test1 bucket and anyone can read any file. 
I expect the files to be unreadable except for user1 when using this setup. 
I do not have any other user.
so how can I make use of the permissions when using s3?  is this a bug ? or am I doing something wrong?

**Comment by chrislusf** [comment]
you are using filer HTTP API to access, which does not authenticate users. You can close http port to external.

**Comment by DiaaEddin** [comment]
@chrislusf I am running seaweedfs s3 on a kubernetes cluster and I need to be able to have public buckets and private buckets. when enabling authentication using s3.configure the public are still able to read any file. 
Are there any workarounds for my usecase?

**Comment by chrislusf** [comment]
you can also configure nginx to control http API access

**Comment by kmlebedev** [comment]
You can use anonymous user for public backets

**Comment by DiaaEddin** [comment]
@chrislusf If I block http access how my website client are going to access the files 9n some buckets? 
I am a little confused here. is not s3.configure supposed to provide authentication? I only get the access denied error at the root of s3 but when accessing any file key I get no error and any one can read it.

**Comment by DiaaEddin** [comment]
> you are using filer HTTP API to access, which does not authenticate users. You can close http port to external.

how to access the api with authentication enabled? and what is presigned url for if everything on s3 gateway is public even when I use authentication? 
you are clearly stating that a file url at s3 gateway is not accessible by default when authentication is enabled. 
[AWS-CLI-with-SeaweedFS#presigned-url](https://github.com/chrislusf/seaweedfs/wiki/AWS-CLI-with-SeaweedFS#presigned-url) 
> If authentication is enabled, the url is not accessible without proper credentials. But you can presign a url and access it

**Comment by kmlebedev** [comment]
> @chrislusf If I block http access how my website client are going to access the files 9n some buckets? I am a little confused here. is not s3.configure supposed to provide authentication? I only get the access denied error at the root of s3 but when accessing any file key I get no error and any one can read it.

Can you demonstrate this by an example of your actions? start from `make dev`

**Comment by kmlebedev** [comment]
> > you are using filer HTTP API to access, which does not authenticate users. You can close http port to external.
> 
> how to access the api with authentication enabled? and what is presigned url for if everything on s3 gateway is public even when I use authentication? you are clearly stating that a file url at s3 gateway is not accessible by default when authentication is enabled. [AWS-CLI-with-SeaweedFS#presigned-url](https://github.com/chrislusf/seaweedfs/wiki/AWS-CLI-with-SeaweedFS#presigned-url)
> 
> > If authentication is enabled, the url is not accessible without proper credentials. But you can presign a url and access it



> s3.configure

At the first start, c3 is launched in exactly this mode, everything is available to everyone. But when creating the first user through s3.configure and only after restarting the c3 service, the access model starts working

**Comment by DiaaEddin** [comment]
@kmlebedev thank your very much.
I was missing the restarting step. after restarting the s3 pod every thing is working as expected. 
though it would be nice to mention this in the documentation.
Also providing the ability to add users and edit their access rights without the need to restart the service  will be appreciated.

**Comment by chrislusf** [comment]
> At the first start, c3 is launched in exactly this mode, everything is available to everyone. But when creating the first user through s3.configure and only after restarting the c3 service, the access model starts working

@kmlebedev this seems a bug since the s3 gateway should listen to the user configuration changes.

**Comment by kmlebedev** [comment]
> > At the first start, c3 is launched in exactly this mode, everything is available to everyone. But when creating the first user through s3.configure and only after restarting the c3 service, the access model starts working
> 
> @kmlebedev this seems a bug since the s3 gateway should listen to the user configuration changes.

@chrislusf  I somehow caught such a bug, but did not pay attention. Now I tried to reproduce from the branch master and it did not work
