### ISSUE TITLE
seaweed large disk build and master server fail-over related

### ISSUE THREAD

**Issue by t4nmoy** [chrislusf/seaweedfs#2471]
Hello,

I was evaluating the large disk build version by deploying a SeaweedFS cluster. In my scenario, I have 3 masters and 3 volume servers, and 1 filer server. what I have found is that if one master (leader) is killed then the filer and the volume servers stop communicating with the new master(leader) and everything just stops working. if I restart the previously killed master and restart the filer server then everything starts working again. can you please suggest what I'm doing wrong here? Thanks.

`master1`
===========================================

> Nov 26 08:46:02 storage01.db.internal.visena.net master.sh[1047809]: I1126 08:46:02 47809 node.go:222] topo:dc1:rack1 adds child 10.2.0.14:8081
Nov 26 08:46:02 storage01.db.internal.visena.net master.sh[1047809]: I1126 08:46:02 47809 node.go:222] topo:dc1:rack1:10.2.0.14:8081 adds child
Nov 26 08:46:02 storage01.db.internal.visena.net master.sh[1047809]: I1126 08:46:02 47809 master_grpc_server.go:70] added volume server 0: 10.2.0.14:8081
Nov 26 08:46:02 storage01.db.internal.visena.net master.sh[1047809]: I1126 08:46:02 47809 volume_layout.go:385] Volume 1 becomes writable
Nov 26 08:46:02 storage01.db.internal.visena.net master.sh[1047809]: I1126 08:46:02 47809 volume_layout.go:385] Volume 3 becomes writable
Nov 26 08:46:02 storage01.db.internal.visena.net master.sh[1047809]: I1126 08:46:02 47809 master_grpc_server.go:109] master see new volume 1 from 10.2.0.14:8081
Nov 26 08:46:02 storage01.db.internal.visena.net master.sh[1047809]: I1126 08:46:02 47809 master_grpc_server.go:109] master see new volume 3 from 10.2.0.14:8081
Nov 26 09:09:19 storage01.db.internal.visena.net master.sh[1047805]: /usr/local/bin/seaweed-master1/master.sh: line 4: 1047809 Killed                  /usr/local/bin/seaweed-master1/weed master -ip=10.2.0.14 -port=9333 -mdir=/dfs/master -peers="10.2.0.14:9333,10.2.0.15:9333,10.2.0.16:9333" -defaultReplication=001 -volumeSizeLimitMB=40000
Nov 26 09:09:19 storage01.db.internal.visena.net systemd[1]: seaweed-master-server1.service: Main process exited, code=exited, status=137/n/a
Nov 26 09:09:19 storage01.db.internal.visena.net systemd[1]: seaweed-master-server1.service: Failed with result 'exit-code'

master2
========================================

> Nov 26 06:45:05 storage02.db.internal.visena.net master.sh[57067]: I1126 06:45:05 57067 master_server.go:119] Volume Size Limit is 40000 MB
Nov 26 06:45:05 storage02.db.internal.visena.net master.sh[57067]: I1126 06:45:05 57067 master_server.go:213] adminScripts:
Nov 26 06:45:05 storage02.db.internal.visena.net master.sh[57067]: I1126 06:45:05 57067 master.go:125] Start Seaweed Master 8000GB 2.79 f3c789d662eeab2dcc07804cbb665752b3870d65 at :9333
Nov 26 06:45:05 storage02.db.internal.visena.net master.sh[57067]: I1126 06:45:05 57067 raft_server.go:71] Starting RaftServer with 10.2.0.15:9333
Nov 26 06:45:05 storage02.db.internal.visena.net master.sh[57067]: I1126 06:45:05 57067 raft_server.go:131] current cluster leader:
Nov 26 06:45:23 storage02.db.internal.visena.net master.sh[57067]: I1126 06:45:23 57067 master.go:148] Start Seaweed Master 8000GB 2.79 f3c789d662eeab2dcc07804cbb665752b3870d65 grpc server at :19333
Nov 26 06:45:59 storage02.db.internal.visena.net master.sh[57067]: I1126 06:45:59 57067 masterclient.go:125] master masterClient failed to receive from 10.2.0.14:9333: EOF
Nov 26 06:46:35 storage02.db.internal.visena.net master.sh[57067]: I1126 06:46:35 57067 masterclient.go:125] master masterClient failed to receive from 10.2.0.15:9333: EOF
Nov 26 06:46:36 storage02.db.internal.visena.net master.sh[57067]: I1126 06:46:36 57067 master_server.go:162] leader change event:  => 10.2.0.14:9333
Nov 26 06:46:36 storage02.db.internal.visena.net master.sh[57067]: I1126 06:46:36 57067 master_server.go:164] [ 10.2.0.15:9333 ] 10.2.0.14:9333 becomes leader.
Nov 26 09:09:19 storage02.db.internal.visena.net master.sh[57067]: I1126 09:09:19 57067 masterclient.go:125] master masterClient failed to receive from 10.2.0.14:9333: rpc error: code = Unavailable desc = error reading from server: EOF
Nov 26 09:09:19 storage02.db.internal.visena.net master.sh[57067]: I1126 09:09:19 57067 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:19 storage02.db.internal.visena.net master.sh[57067]: I1126 09:09:19 57067 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:20 storage02.db.internal.visena.net master.sh[57067]: I1126 09:09:20 57067 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:20 storage02.db.internal.visena.net master.sh[57067]: I1126 09:09:20 57067 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:21 storage02.db.internal.visena.net master.sh[57067]: I1126 09:09:21 57067 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:21 storage02.db.internal.visena.net master.sh[57067]: I1126 09:09:21 57067 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:22 storage02.db.internal.visena.net master.sh[57067]: I1126 09:09:22 57067 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:22 storage02.db.internal.visena.net master.sh[57067]: I1126 09:09:22 57067 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:23 storage02.db.internal.visena.net master.sh[57067]: I1126 09:09:23 57067 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:23 storage02.db.internal.visena.net master.sh[57067]: I1126 09:09:23 57067 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:24 storage02.db.internal.visena.net master.sh[57067]: I1126 09:09:24 57067 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:24 storage02.db.internal.visena.net master.sh[57067]: I1126 09:09:24 57067 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:25 storage02.db.internal.visena.net master.sh[57067]: I1126 09:09:25 57067 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:25 storage02.db.internal.visena.net master.sh[57067]: I1126 09:09:25 57067 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:26 storage02.db.internal.visena.net master.sh[57067]: I1126 09:09:26 57067 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:26 storage02.db.internal.visena.net master.sh[57067]: I1126 09:09:26 57067 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:27 storage02.db.internal.visena.net master.sh[57067]: I1126 09:09:27 57067 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:27 storage02.db.internal.visena.net master.sh[57067]: I1126 09:09:27 57067 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:28 storage02.db.internal.visena.net master.sh[57067]: I1126 09:09:28 57067 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:28 storage02.db.internal.visena.net master.sh[57067]: I1126 09:09:28 57067 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:29 storage02.db.internal.visena.net master.sh[57067]: I1126 09:09:29 57067 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:29 storage02.db.internal.visena.net master.sh[57067]: I1126 09:09:29 57067 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:29 storage02.db.internal.visena.net master.sh[57067]: I1126 09:09:29 57067 master_server.go:162] leader change event: 10.2.0.14:9333 =>
Nov 26 09:09:29 storage02.db.internal.visena.net master.sh[57067]: I1126 09:09:29 57067 master_server.go:162] leader change event:  => 10.2.0.15:9333
Nov 26 09:09:29 storage02.db.internal.visena.net master.sh[57067]: I1126 09:09:29 57067 master_server.go:164] [ 10.2.0.15:9333 ] 10.2.0.15:9333 becomes leader.
Nov 26 09:09:30 storage02.db.internal.visena.net master.sh[57067]: I1126 09:09:30 57067 master_grpc_server.go:262] + client filer@10.2.0.14:8888
Nov 26 09:09:30 storage02.db.internal.visena.net master.sh[57067]: I1126 09:09:30 57067 master_grpc_server.go:262] + client master@10.2.0.15:9333
Nov 26 09:09:30 storage02.db.internal.visena.net master.sh[57067]: I1126 09:09:30 57067 master_grpc_server.go:262] + client master@10.2.0.16:9333

master3
=========================================

> Nov 26 06:53:10 storage03.db.internal.visena.net master.sh[56739]: I1126 06:53:10 56739 file_util.go:23] Folder /dfs/master Permission: -rw-rw-rw-
Nov 26 06:53:10 storage03.db.internal.visena.net master.sh[56739]: I1126 06:53:10 56739 master.go:170] current: 10.2.0.16:9333 peers:10.2.0.14:9333,10.2.0.15:9333,10.2.0.16:9333
Nov 26 06:53:10 storage03.db.internal.visena.net master.sh[56739]: I1126 06:53:10 56739 master_server.go:119] Volume Size Limit is 40000 MB
Nov 26 06:53:10 storage03.db.internal.visena.net master.sh[56739]: I1126 06:53:10 56739 master_server.go:213] adminScripts:
Nov 26 06:53:10 storage03.db.internal.visena.net master.sh[56739]: I1126 06:53:10 56739 master.go:125] Start Seaweed Master 8000GB 2.79 f3c789d662eeab2dcc07804cbb665752b3870d65 at :9333
Nov 26 06:53:10 storage03.db.internal.visena.net master.sh[56739]: I1126 06:53:10 56739 raft_server.go:71] Starting RaftServer with 10.2.0.16:9333
Nov 26 06:53:10 storage03.db.internal.visena.net master.sh[56739]: I1126 06:53:10 56739 raft_server.go:131] current cluster leader:
Nov 26 06:53:28 storage03.db.internal.visena.net master.sh[56739]: I1126 06:53:28 56739 master.go:148] Start Seaweed Master 8000GB 2.79 f3c789d662eeab2dcc07804cbb665752b3870d65 grpc server at :19333
Nov 26 06:54:01 storage03.db.internal.visena.net master.sh[56739]: I1126 06:54:01 56739 master_server.go:162] leader change event:  => 10.2.0.14:9333
Nov 26 06:54:01 storage03.db.internal.visena.net master.sh[56739]: I1126 06:54:01 56739 master_server.go:164] [ 10.2.0.16:9333 ] 10.2.0.14:9333 becomes leader.
Nov 26 09:09:19 storage03.db.internal.visena.net master.sh[56739]: I1126 09:09:19 56739 masterclient.go:125] master masterClient failed to receive from 10.2.0.14:9333: rpc error: code = Unavailable desc = error reading from server: EOF
Nov 26 09:09:19 storage03.db.internal.visena.net master.sh[56739]: I1126 09:09:19 56739 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:19 storage03.db.internal.visena.net master.sh[56739]: I1126 09:09:19 56739 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:20 storage03.db.internal.visena.net master.sh[56739]: I1126 09:09:20 56739 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:20 storage03.db.internal.visena.net master.sh[56739]: I1126 09:09:20 56739 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:21 storage03.db.internal.visena.net master.sh[56739]: I1126 09:09:21 56739 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:21 storage03.db.internal.visena.net master.sh[56739]: I1126 09:09:21 56739 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:22 storage03.db.internal.visena.net master.sh[56739]: I1126 09:09:22 56739 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:22 storage03.db.internal.visena.net master.sh[56739]: I1126 09:09:22 56739 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:23 storage03.db.internal.visena.net master.sh[56739]: I1126 09:09:23 56739 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:23 storage03.db.internal.visena.net master.sh[56739]: I1126 09:09:23 56739 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:24 storage03.db.internal.visena.net master.sh[56739]: I1126 09:09:24 56739 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:24 storage03.db.internal.visena.net master.sh[56739]: I1126 09:09:24 56739 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:25 storage03.db.internal.visena.net master.sh[56739]: I1126 09:09:25 56739 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:25 storage03.db.internal.visena.net master.sh[56739]: I1126 09:09:25 56739 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:26 storage03.db.internal.visena.net master.sh[56739]: I1126 09:09:26 56739 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:26 storage03.db.internal.visena.net master.sh[56739]: I1126 09:09:26 56739 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:27 storage03.db.internal.visena.net master.sh[56739]: I1126 09:09:27 56739 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:27 storage03.db.internal.visena.net master.sh[56739]: I1126 09:09:27 56739 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:28 storage03.db.internal.visena.net master.sh[56739]: I1126 09:09:28 56739 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:28 storage03.db.internal.visena.net master.sh[56739]: I1126 09:09:28 56739 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:29 storage03.db.internal.visena.net master.sh[56739]: I1126 09:09:29 56739 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:29 storage03.db.internal.visena.net master.sh[56739]: I1126 09:09:29 56739 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:29 storage03.db.internal.visena.net master.sh[56739]: I1126 09:09:29 56739 master_server.go:162] leader change event: 10.2.0.14:9333 =>
Nov 26 09:09:29 storage03.db.internal.visena.net master.sh[56739]: I1126 09:09:29 56739 master_server.go:162] leader change event:  => 10.2.0.15:9333
Nov 26 09:09:29 storage03.db.internal.visena.net master.sh[56739]: I1126 09:09:29 56739 master_server.go:164] [ 10.2.0.16:9333 ] 10.2.0.15:9333 becomes leader.

filer-server
======================================

> Nov 26 08:16:43 storage01.db.internal.visena.net filer.sh[1139133]: W1126 08:16:43 39133 filer_server.go:122] skipping default store dir in ./filerldb2
Nov 26 08:16:43 storage01.db.internal.visena.net filer.sh[1139133]: I1126 08:16:43 39133 filer.go:124] existing filer.store.id = -766295472
Nov 26 08:16:43 storage01.db.internal.visena.net filer.sh[1139133]: I1126 08:16:43 39133 configuration.go:28] configured filer store to cassandra
Nov 26 08:16:43 storage01.db.internal.visena.net filer.sh[1139133]: I1126 08:16:43 39133 filer.go:89] the cluster has 1 filers
Nov 26 08:16:43 storage01.db.internal.visena.net filer.sh[1139133]: I1126 08:16:43 39133 meta_aggregator.go:100] connecting to peer filer 10.2.0.14:8888: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.2.0.14:18888: connect: connection refused"
Nov 26 08:16:43 storage01.db.internal.visena.net filer.sh[1139133]: I1126 08:16:43 39133 filer.go:222] Start Seaweed Filer 8000GB 2.79 f3c789d662eeab2dcc07804cbb665752b3870d65 at 10.2.0.14:8888
Nov 26 08:16:45 storage01.db.internal.visena.net filer.sh[1139133]: I1126 08:16:45 39133 filer_grpc_server_sub_meta.go:242] + listener filer:10.2.0.14:8888@10.2.0.14:51958
Nov 26 08:16:45 storage01.db.internal.visena.net filer.sh[1139133]: I1126 08:16:45 39133 filer_grpc_server_sub_meta.go:89]  filer:10.2.0.14:8888@10.2.0.14:51958 local subscribe / from 2021-11-26 08:15:43.792214706 +0100 CET
Nov 26 08:16:45 storage01.db.internal.visena.net filer.sh[1139133]: I1126 08:16:45 39133 filer_grpc_server_sub_meta.go:101] read on disk filer:10.2.0.14:8888@10.2.0.14:51958 local subscribe / from 2021-11-26 08:15:43.792214706 +0100 CET
Nov 26 08:16:45 storage01.db.internal.visena.net filer.sh[1139133]: I1126 08:16:45 39133 filer_grpc_server_sub_meta.go:117] read in memory filer:10.2.0.14:8888@10.2.0.14:51958 local subscribe / from 2021-11-26 08:15:43.792214706 +0100 CET
Nov 26 09:09:19 storage01.db.internal.visena.net filer.sh[1139133]: I1126 09:09:19 39133 masterclient.go:125] filer masterClient failed to receive from 10.2.0.14:9333: rpc error: code = Unavailable desc = error reading from server: EOF
Nov 26 09:09:19 storage01.db.internal.visena.net filer.sh[1139133]: I1126 09:09:19 39133 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:19 storage01.db.internal.visena.net filer.sh[1139133]: I1126 09:09:19 39133 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:20 storage01.db.internal.visena.net filer.sh[1139133]: I1126 09:09:20 39133 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:20 storage01.db.internal.visena.net filer.sh[1139133]: I1126 09:09:20 39133 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:21 storage01.db.internal.visena.net filer.sh[1139133]: I1126 09:09:21 39133 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:21 storage01.db.internal.visena.net filer.sh[1139133]: I1126 09:09:21 39133 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:22 storage01.db.internal.visena.net filer.sh[1139133]: I1126 09:09:22 39133 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:22 storage01.db.internal.visena.net filer.sh[1139133]: I1126 09:09:22 39133 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:23 storage01.db.internal.visena.net filer.sh[1139133]: I1126 09:09:23 39133 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:23 storage01.db.internal.visena.net filer.sh[1139133]: I1126 09:09:23 39133 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:24 storage01.db.internal.visena.net filer.sh[1139133]: I1126 09:09:24 39133 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:24 storage01.db.internal.visena.net filer.sh[1139133]: I1126 09:09:24 39133 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:25 storage01.db.internal.visena.net filer.sh[1139133]: I1126 09:09:25 39133 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:25 storage01.db.internal.visena.net filer.sh[1139133]: I1126 09:09:25 39133 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:26 storage01.db.internal.visena.net filer.sh[1139133]: I1126 09:09:26 39133 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:26 storage01.db.internal.visena.net filer.sh[1139133]: I1126 09:09:26 39133 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:27 storage01.db.internal.visena.net filer.sh[1139133]: I1126 09:09:27 39133 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:27 storage01.db.internal.visena.net filer.sh[1139133]: I1126 09:09:27 39133 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:28 storage01.db.internal.visena.net filer.sh[1139133]: I1126 09:09:28 39133 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:28 storage01.db.internal.visena.net filer.sh[1139133]: I1126 09:09:28 39133 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:29 storage01.db.internal.visena.net filer.sh[1139133]: I1126 09:09:29 39133 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:29 storage01.db.internal.visena.net filer.sh[1139133]: I1126 09:09:29 39133 masterclient.go:132] redirected to leader 10.2.0.14:9333
Nov 26 09:09:30 storage01.db.internal.visena.net filer.sh[1139133]: I1126 09:09:30 39133 masterclient.go:158] + filer 10.2.0.14:8888 leader:true
Nov 26 09:09:30 storage01.db.internal.visena.net filer.sh[1139133]: I1126 09:09:30 39133 filer_grpc_server_sub_meta.go:242] + listener filer:10.2.0.14:8888@10.2.0.14:51958
Nov 26 09:09:30 storage01.db.internal.visena.net filer.sh[1139133]: I1126 09:09:30 39133 filer_grpc_server_sub_meta.go:89]  filer:10.2.0.14:8888@10.2.0.14:51958 local subscribe / from 2021-11-26 09:08:30.099799453 +0100 CET
Nov 26 09:09:30 storage01.db.internal.visena.net filer.sh[1139133]: I1126 09:09:30 39133 filer_grpc_server_sub_meta.go:101] read on disk filer:10.2.0.14:8888@10.2.0.14:51958 local subscribe / from 2021-11-26 09:08:30.099799453 +0100 CET
Nov 26 09:09:30 storage01.db.internal.visena.net filer.sh[1139133]: I1126 09:09:30 39133 filer_grpc_server_sub_meta.go:117] read in memory filer:10.2.0.14:8888@10.2.0.14:51958 local subscribe / from 2021-11-26 09:08:30.099799453 +0100 CET

volume-server
======================================

> Nov 26 08:45:08 storage02.db.internal.visena.net volume.sh[58944]: I1126 08:45:08 58944 volume_loading.go:133] loading index /dfs/data/1.idx to memory
Nov 26 08:45:08 storage02.db.internal.visena.net volume.sh[58944]: I1126 08:45:08 58944 disk_location.go:138] data file /dfs/data/1.dat, replication=001 v=3 size=393027672 ttl=
Nov 26 08:45:08 storage02.db.internal.visena.net volume.sh[58944]: I1126 08:45:08 58944 volume_loading.go:86] readSuperBlock volume 2 version 3
Nov 26 08:45:08 storage02.db.internal.visena.net volume.sh[58944]: I1126 08:45:08 58944 volume_loading.go:133] loading index /dfs/data/2.idx to memory
Nov 26 08:45:08 storage02.db.internal.visena.net volume.sh[58944]: I1126 08:45:08 58944 disk_location.go:138] data file /dfs/data/2.dat, replication=001 v=3 size=398891384 ttl=
Nov 26 08:45:08 storage02.db.internal.visena.net volume.sh[58944]: I1126 08:45:08 58944 disk_location.go:180] Store started on dir: /dfs/data with 2 volumes max 2
Nov 26 08:45:08 storage02.db.internal.visena.net volume.sh[58944]: I1126 08:45:08 58944 disk_location.go:183] Store started on dir: /dfs/data with 0 ec shards
Nov 26 08:45:08 storage02.db.internal.visena.net volume.sh[58944]: I1126 08:45:08 58944 volume.go:360] Start Seaweed volume server 8000GB 2.79 f3c789d662eeab2dcc07804cbb665752b3870d65 at :8081
Nov 26 08:45:08 storage02.db.internal.visena.net volume.sh[58944]: I1126 08:45:08 58944 volume_grpc_client_to_master.go:50] Volume server start with seed master nodes: [10.2.0.14:9333 10.2.0.15:9334 10.2.0.16:9335]
Nov 26 08:45:08 storage02.db.internal.visena.net volume.sh[58944]: I1126 08:45:08 58944 volume_grpc_client_to_master.go:107] Heartbeat to: 10.2.0.14:9333
Nov 26 09:09:19 storage02.db.internal.visena.net volume.sh[58944]: I1126 09:09:19 58944 volume_grpc_client_to_master.go:69] heartbeat error: rpc error: code = Unavailable desc = error reading from server: EOF
Nov 26 09:09:24 storage02.db.internal.visena.net volume.sh[58944]: I1126 09:09:24 58944 volume_grpc_client_to_master.go:104] SendHeartbeat to 10.2.0.15:9334: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.2.0.15:19334: connect: connection refused"
Nov 26 09:09:24 storage02.db.internal.visena.net volume.sh[58944]: I1126 09:09:24 58944 volume_grpc_client_to_master.go:69] heartbeat error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.2.0.15:19334: connect: connection refused"
Nov 26 09:09:29 storage02.db.internal.visena.net volume.sh[58944]: I1126 09:09:29 58944 volume_grpc_client_to_master.go:104] SendHeartbeat to 10.2.0.16:9335: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.2.0.16:19335: connect: connection refused"
Nov 26 09:09:29 storage02.db.internal.visena.net volume.sh[58944]: I1126 09:09:29 58944 volume_grpc_client_to_master.go:69] heartbeat error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.2.0.16:19335: connect: connection refused"
Nov 26 09:09:34 storage02.db.internal.visena.net volume.sh[58944]: I1126 09:09:34 58944 volume_grpc_client_to_master.go:104] SendHeartbeat to 10.2.0.14:9333: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.2.0.14:19333: connect: connection refused"
Nov 26 09:09:34 storage02.db.internal.visena.net volume.sh[58944]: I1126 09:09:34 58944 volume_grpc_client_to_master.go:69] heartbeat error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.2.0.14:19333: connect: connection refused"
Nov 26 09:09:39 storage02.db.internal.visena.net volume.sh[58944]: I1126 09:09:39 58944 volume_grpc_client_to_master.go:104] SendHeartbeat to 10.2.0.15:9334: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.2.0.15:19334: connect: connection refused"
Nov 26 09:09:39 storage02.db.internal.visena.net volume.sh[58944]: I1126 09:09:39 58944 volume_grpc_client_to_master.go:69] heartbeat error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.2.0.15:19334: connect: connection refused"
Nov 26 09:09:44 storage02.db.internal.visena.net volume.sh[58944]: I1126 09:09:44 58944 volume_grpc_client_to_master.go:104] SendHeartbeat to 10.2.0.16:9335: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.2.0.16:19335: connect: connection refused"
Nov 26 09:09:44 storage02.db.internal.visena.net volume.sh[58944]: I1126 09:09:44 58944 volume_grpc_client_to_master.go:69] heartbeat error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.2.0.16:19335: connect: connection refused"
Nov 26 09:09:49 storage02.db.internal.visena.net volume.sh[58944]: I1126 09:09:49 58944 volume_grpc_client_to_master.go:104] SendHeartbeat to 10.2.0.14:9333: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.2.0.14:19333: connect: connection refused"
Nov 26 09:09:49 storage02.db.internal.visena.net volume.sh[58944]: I1126 09:09:49 58944 volume_grpc_client_to_master.go:69] heartbeat error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.2.0.14:19333: connect: connection refused"

**Comment by chrislusf** [comment]
what is not working?

**Comment by t4nmoy** [comment]
> what is not working?
Master server failover mechanism is not working for large disk build. if one master (leader) is killed then the filer and the volume servers stop communicating with the new master(leader) and everything just stops working.

**Comment by chrislusf** [comment]
the logs showed the failover worked.

**Comment by t4nmoy** [comment]
but from the log, it seems that the volume server fails to report to the new leader(master2) and there is no log in the leader(master2) which says that it got volume information from all the volume servers. what do you suggest here? thanks

**Comment by chrislusf** [comment]
> Volume server start with seed master nodes: [10.2.0.14:9333 10.2.0.15:9334 10.2.0.16:9335]

The volume server started with these master nodes, but the master starts with the following nodes. The ports are not matching.

> 1047809 Killed /usr/local/bin/seaweed-master1/weed master -ip=10.2.0.14 -port=9333 -mdir=/dfs/master -peers="10.2.0.14:9333,10.2.0.15:9333,10.2.0.16:9333" -defaultReplication=001 -volumeSizeLimitMB=40000

**Comment by t4nmoy** [comment]
ahh, thanks, that's my mistake
