### ISSUE TITLE
how to restore filer data from volume

### ISSUE THREAD

**Issue by reymondzzzz** [chrislusf/seaweedfs#2472]
I am testing seaweedfs on docker swarm and after recreate containers all filer data is removed. I created volume for  persisted data and It work right now. So if I will accidentally remove this data, how can I restore filesystem for access?

**Comment by LuckyFrost** [comment]
There are no ways. Volume server does not store paths and other meta-information

**Comment by chrislusf** [comment]
If you only need the file content, you can use `weed export` to export file name and content out of the volumes directly.
