### ISSUE TITLE
failed to write to local disk

### ISSUE THREAD

**Issue by DuncanPlayer** [chrislusf/seaweedfs#2473]
**Problem**
Upload 2GB video failed
{"name":"ceshi.mp4","size":2314382721,"error":"failed to write to local disk: volume size limit 34359738368 exceeded! current size is 57394","eTag":"07f99010"}

**Seaweedfs Setup**
- nohup  /data/xxx/swf/weed master -ip=$IP -port=9333 -volumeSizeLimitMB=30000  -mdir=/data/xxx/swf/data -peers=$IP:9333 > /data/xxx/swf/data/master.log &
- nohup /data/xxx/swf/weed volume -fileSizeLimitMB=30000 -dataCenter dc1 -rack rack1 -dir /data/xxx/swf/volume -ip $IP -port 9222 -ip.bind $IP -max 20 -mserver $IP:9333 -publicUrl $IP:9222 > /data/xxx/swf/volume/volume.log &
- disk space is ok

**Comment by chrislusf** [comment]
how did you upload?

**Comment by DuncanPlayer** [comment]
> how did you upload?
curl -F file=@./ceshi.mp4 x.x.x.x:port/fid

**Comment by chrislusf** [comment]
right. Please use `weed upload` for large files if you are uploading to volume servers directly.
