### ISSUE TITLE
fix volume idx error

### ISSUE THREAD

**Issue by wanghche** [chrislusf/seaweedfs#2474]
I have copy volume data to another server with same OS ubuntu 20.04. But start server get the error message: volumeDataIntegrityChecking failed verifyNeedleIntergrity /home/administrator/data/vol2/1.idx failed : index key 0x3439333966 does not match needle's Id 0x65633432383130303030303

I use command to fix : weed fix -dir=/home/administrator/data/vol2 volumeId=1 ，still error with
readSuperBlock volume 1 version 3
scan .dat File: cannot read needle header at offset -900977296: readat /home/administrator/data/vol2/1.dat negative offset

How can fix it
weed version: linux 2.64 big file

**Comment by chrislusf** [comment]
I suspect you are using a wrong `weed` binary.

**Comment by wanghche** [comment]
> I suspect you are using a wrong `weed` binary.

Thx @chrislusf , the reason of error found that is data damaged while copy，the original data is ok。
