### ISSUE TITLE
volume server log related

### ISSUE THREAD

**Issue by t4nmoy** [chrislusf/seaweedfs#2477]
Hello,
is it possible to increase the log level of a volume server so that when some volume is being used can be logged? I don't find any setting from `weed help volume`. is there any way to show this log?

Thanks.

**Comment by chrislusf** [comment]
you can increase the log level via `weed -v=4 volume ...`

you may need to add some more logs yourself.

**Comment by t4nmoy** [comment]
> you can increase the log level via `weed -v=4 volume ...`
> 
> you may need to add some more logs yourself.

Thanks a lot. this will be helpful
