### ISSUE TITLE
Invalid filename with "%" character after using CopyObject api aws.

### ISSUE THREAD

**Issue by AlekseyFicht** [chrislusf/seaweedfs#2482]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs
Report issues here. Ask questions here https://stackoverflow.com/questions/tagged/seaweedfs
Please ask questions in https://github.com/chrislusf/seaweedfs/discussions

**Describe the bug**
Hello.
If the file name is "file%231.pdf", then for some reason after copying creates the file "file#1.pdf"

How to reproduce.
through the AWS command does this too:
`aws --endpoint-url https://s3.mainserver.de --no-verify-ssl s3 cp s3://backet-test/readme.txt s3://backet-test/copied/file%231.txt`

file backet-test/copied/file#1.txt was created

minio creates file%231.txt

maybe decoding works here because it is Url-Like syntax - ?

**System Setup**
- OS version Centos 7
Weed vesrsion 2.70

**Expected behavior**
Ability to create file with '%' character

**Comment by chrislusf** [comment]
can not reproduce:
```
$ AWS_SECRET_ACCESS_KEY=admin_secret AWS_ACCESS_KEY_ID=admin_access aws --endpoint-url http://localhost:8333 s3 cp /Users/chrislu/Downloads/phone.jpeg s3://newbucket3/phone.jpeg
upload: ../Downloads/phone.jpeg to s3://newbucket3/phone.jpeg

$ AWS_SECRET_ACCESS_KEY=admin_secret AWS_ACCESS_KEY_ID=admin_access aws --endpoint-url http://localhost:8333 s3 cp /Users/chrislu/Downloads/phone.jpeg s3://newbucket3/phone%231.txt
upload: ../Downloads/phone.jpeg to s3://newbucket3/phone%231.txt

$ AWS_SECRET_ACCESS_KEY=admin_secret AWS_ACCESS_KEY_ID=admin_access aws --endpoint-url http://localhost:8333 s3 ls s3://newbucket3
2021-12-04 22:59:59      53058 phone%231.txt
2021-12-04 22:58:57      53058 phone.jpeg
```

**Comment by chrislusf** [comment]
thanks for reporting! fixed now.
