### ISSUE TITLE
deploy seaweedfs use seaweedfs-compose.yml, but cronjob service not start

### ISSUE THREAD

**Issue by stardustman** [chrislusf/seaweedfs#2483]
**Describe the bug**
I use [docker-compose](https://github.com/chrislusf/seaweedfs/blob/master/docker/seaweedfs-compose.yml) to start SeaweedFS.
but `cronjob` service not start successfully. others start successfully.

**Expected behavior**
cronjob start successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/22998204/144028831-de957b09-e870-4dec-a22d-2f354f274bb5.png)

is there something wrong?

**Comment by chrislusf** [comment]
the supercronic is deprecated. I will need to remove it.

the same admin script should be inside `master.toml` file.
