### ISSUE TITLE
retry mechanism is not working with filer for a specific case

### ISSUE THREAD

**Issue by t4nmoy** [chrislusf/seaweedfs#2485]
The retry mechanism of the filer does not work for a very specific case. I'll try my best to explain the issue. 
when the filer is trying to stream some chunk from volume server URLs (https://github.com/chrislusf/seaweedfs/blob/689f5513a955528f365e79c30d9965e7826b1509/weed/filer/filechunk_manifest.go#L158)
the retry mechanism will be bypassed for this reason (https://github.com/chrislusf/seaweedfs/blob/689f5513a955528f365e79c30d9965e7826b1509/weed/filer/filechunk_manifest.go#L175)
because of the reason (https://github.com/chrislusf/seaweedfs/blob/689f5513a955528f365e79c30d9965e7826b1509/weed/util/http_util.go#L329).

this will only happen when the filer is trying to stream some chunk and filler send the HTTP request to the volume server (https://github.com/chrislusf/seaweedfs/blob/689f5513a955528f365e79c30d9965e7826b1509/weed/util/http_util.go#L297) and then get a 200 OK (https://github.com/chrislusf/seaweedfs/blob/689f5513a955528f365e79c30d9965e7826b1509/weed/util/http_util.go#L302)  so it starts to stream some bytes (https://github.com/chrislusf/seaweedfs/blob/689f5513a955528f365e79c30d9965e7826b1509/weed/util/http_util.go#L324) but at this moment if the volume server is killed then it won't work for this condition (https://github.com/chrislusf/seaweedfs/blob/689f5513a955528f365e79c30d9965e7826b1509/weed/util/http_util.go#L329)

I think the solution should be  

> for {
		m, err = reader.Read(buf)
		fn(buf[:m])
		if err == io.EOF {
			return false, nil
		}
		if err != nil {
			return true, err
		}
	}

please let me know what do you think about this. thanks

**Comment by chrislusf** [comment]
if the volume server is killed, the request should not retry, correct?

**Comment by t4nmoy** [comment]
> if the volume server is killed, the request should not retry, correct?

I think the request should be retried again for the same chunk. suppose for a very large file all of the chunks are transmitted except the last chunk. if it's retried again then there is a chance we will be able to send the chunk from another volume server(https://github.com/chrislusf/seaweedfs/blob/689f5513a955528f365e79c30d9965e7826b1509/weed/filer/filechunk_manifest.go#L146). right?

**Comment by chrislusf** [comment]
you are right. you can send a PR?
