### ISSUE TITLE
SeaweedFS0.76升级到2.76问题

### ISSUE THREAD

**Issue by justor** [chrislusf/seaweedfs#2487]
SeaweedFS0.76迁移到2.76过程中出现文件丢失。具体来讲就是把0.76版本生的dat文件和idx文件放到2.76集群上虽然能够识别文件，但是却不能全部下载，dat中的最后一个文件无法下载。附件中有dat和idx文件，该dat文件中含有22个文件，但是只能下载下来21个文件。
[weedFile.tar.gz](https://github.com/chrislusf/seaweedfs/files/7647171/weedFile.tar.gz)

**Comment by chrislusf** [comment]
thanks for reporting. fixed now.

You would need to copy again, and delete any existing `.vif` files for the copied volume files.
