### ISSUE TITLE
ec.decode always fails

### ISSUE THREAD

**Issue by bddrey** [chrislusf/seaweedfs#2489]
**Describe the bug**
When running ec.decode, the result is error with no volume decoding being performed. The dat file is there, the dat file contains the files via weed export, but it will not be used by the volume server.

**System Setup**
Running test setup with 8 volume servers, one master, and one filer all on one machine.
mkdir fs0 fs1 fs2 fs3 fs4 fs5 fs6 fs7 fs8
./weed master
./weed volume -dir ./fs1/ -mserver=localhost:9333 -port=8081 -dataCenter=dc1 -rack=0 -max=22 & 
./weed volume -dir ./fs2/ -mserver=localhost:9333 -port=8082 -dataCenter=dc1 -rack=0 -max=22 & 
./weed volume -dir ./fs3/ -mserver=localhost:9333 -port=8083 -dataCenter=dc1 -rack=1 -max=22 &
./weed volume -dir ./fs4/ -mserver=localhost:9333 -port=8084 -dataCenter=dc1 -rack=1 -max=22 & 
./weed volume -dir ./fs5/ -mserver=localhost:9333 -port=8085 -dataCenter=dc2 -rack=0 -max=22 & 
./weed volume -dir ./fs6/ -mserver=localhost:9333 -port=8086 -dataCenter=dc2 -rack=0 -max=22 &
./weed volume -dir ./fs7/ -mserver=localhost:9333 -port=8087 -dataCenter=dc2 -rack=1 -max=22 & 
./weed volume -dir ./fs8/ -mserver=localhost:9333 -port=8088 -dataCenter=dc2 -rack=1 -max=22 &
./weed filer -master localhost:9333 -defaultReplicaPlacement 111 &
./weed s3 -filer localhost:8888
sudo ./weed mount -dir /mnt/filer/ -filer localhost:8888
rsync -auv /home/seaweedtest /mnt/filer/

- Running on Ubuntu 18 LTS within VirtualBox
- output of `weed version`: version 30GB 2.77 5cf33235 linux 386
- if using filer, show the content of `filer.toml`: no file created named 'filer.toml'

**Expected behavior**
Conversion of EC volume into normal volume

**Screenshots**
./weed shell -master localhost:9333
> lock
> ec.encode -volumeId 1 -fullPercent 0.01
> ec.encode -volumeId 2 -fullPercent 0.01
> ec.decode -volumeId 2
ec volume 2 shard locations: map[192.168.0.101:8081:514 192.168.0.101:8082:1023 192.168.0.101:8083:128 192.168.0.101:8084:1028 192.168.0.101:8085:2056 192.168.0.101:8086:8224 192.168.0.101:8087:4112 192.168.0.101:8088:64]
collectEcShards: ec volume 2 collect shards to 192.168.0.101:8082 from: map[192.168.0.101:8081:514 192.168.0.101:8082:1023 192.168.0.101:8083:128 192.168.0.101:8084:1028 192.168.0.101:8085:2056 192.168.0.101:8086:8224 192.168.0.101:8087:4112 192.168.0.101:8088:64]
generateNormalVolume from ec volume 2 on 192.168.0.101:8082
error: delete ec shards for volume 2: mountVolumeAndDeleteEcShards mount volume 2 on 192.168.0.101:8082: rpc error: code = Unknown desc = volume 2 not found on disk

**Additional context**
Have 2 EC volumes, both result in similar errors when run with ec.decode
'weed export' looks fine, all files shown, no errors or warnings.
'weed fix' has no issues on dat files 1 and 2

**Comment by chrislusf** [comment]
What's the output of volume.list?

**Comment by chrislusf** [comment]
does the volume server has any error output?

**Comment by chrislusf** [comment]
can not reproduce:

```
$ weed shell
master: localhost:9333 filers: [192.168.2.3:8888]
> volume.list
Topology volumeSizeLimit:30000 MB hdd(volume:4/176 active:4 free:172 remote:0)
  DataCenter dc1 hdd(volume:1/88 active:1 free:87 remote:0)
    Rack 0 hdd(volume:1/44 active:1 free:43 remote:0)
      DataNode 192.168.2.3:8081 hdd(volume:1/22 active:1 free:21 remote:0)
        Disk hdd(volume:1/22 active:1 free:21 remote:0)
          volume id:1 size:2539233200 file_count:617 replica_placement:111 version:3 modified_at_second:1638697922
        Disk hdd total size:2539233200 file_count:617
      DataNode 192.168.2.3:8081 total size:2539233200 file_count:617
      DataNode 192.168.2.3:8082 hdd(volume:0/22 active:0 free:22 remote:0)
        Disk hdd(volume:0/22 active:0 free:22 remote:0)
        Disk hdd total size:0 file_count:0
      DataNode 192.168.2.3:8082 total size:0 file_count:0
    Rack 0 total size:2539233200 file_count:617
    Rack 1 hdd(volume:0/44 active:0 free:44 remote:0)
      DataNode 192.168.2.3:8083 hdd(volume:0/22 active:0 free:22 remote:0)
        Disk hdd(volume:0/22 active:0 free:22 remote:0)
        Disk hdd total size:0 file_count:0
      DataNode 192.168.2.3:8083 total size:0 file_count:0
      DataNode 192.168.2.3:8084 hdd(volume:0/22 active:0 free:22 remote:0)
        Disk hdd(volume:0/22 active:0 free:22 remote:0)
        Disk hdd total size:0 file_count:0
      DataNode 192.168.2.3:8084 total size:0 file_count:0
    Rack 1 total size:0 file_count:0
  DataCenter dc1 total size:2539233200 file_count:617
  DataCenter dc2 hdd(volume:3/88 active:3 free:85 remote:0)
    Rack 0 hdd(volume:1/44 active:1 free:43 remote:0)
      DataNode 192.168.2.3:8085 hdd(volume:1/22 active:1 free:21 remote:0)
        Disk hdd(volume:1/22 active:1 free:21 remote:0)
          volume id:1 size:2539233200 file_count:617 replica_placement:111 version:3 modified_at_second:1638697922
        Disk hdd total size:2539233200 file_count:617
      DataNode 192.168.2.3:8085 total size:2539233200 file_count:617
      DataNode 192.168.2.3:8086 hdd(volume:0/22 active:0 free:22 remote:0)
        Disk hdd(volume:0/22 active:0 free:22 remote:0)
        Disk hdd total size:0 file_count:0
      DataNode 192.168.2.3:8086 total size:0 file_count:0
    Rack 0 total size:2539233200 file_count:617
    Rack 1 hdd(volume:2/44 active:2 free:42 remote:0)
      DataNode 192.168.2.3:8087 hdd(volume:1/22 active:1 free:21 remote:0)
        Disk hdd(volume:1/22 active:1 free:21 remote:0)
          volume id:1 size:2539233200 file_count:617 replica_placement:111 version:3 modified_at_second:1638697922
        Disk hdd total size:2539233200 file_count:617
      DataNode 192.168.2.3:8087 total size:2539233200 file_count:617
      DataNode 192.168.2.3:8088 hdd(volume:1/22 active:1 free:21 remote:0)
        Disk hdd(volume:1/22 active:1 free:21 remote:0)
          volume id:1 size:2539233200 file_count:617 replica_placement:111 version:3 modified_at_second:1638697922
        Disk hdd total size:2539233200 file_count:617
      DataNode 192.168.2.3:8088 total size:2539233200 file_count:617
    Rack 1 total size:5078466400 file_count:1234
  DataCenter dc2 total size:7617699600 file_count:1851
total size:10156932800 file_count:2468
>
>
>
>
>
>
>
> lock
> ec.encode -volumeId 1 -fullPercent 0.01
markVolumeReadonly 1 on 192.168.2.3:8085 ...
markVolumeReadonly 1 on 192.168.2.3:8088 ...
markVolumeReadonly 1 on 192.168.2.3:8087 ...
markVolumeReadonly 1 on 192.168.2.3:8081 ...
generateEcShards  1 on 192.168.2.3:8085 ...
parallelCopyEcShardsFromSource 1 192.168.2.3:8085
allocate 1.[0 8] 192.168.2.3:8085 => 192.168.2.3:8083
allocate 1.[4 12] 192.168.2.3:8085 => 192.168.2.3:8087
allocate 1.[2 10] 192.168.2.3:8085 => 192.168.2.3:8084
allocate 1.[5 13] 192.168.2.3:8085 => 192.168.2.3:8081
allocate 1.[7] 192.168.2.3:8085 => 192.168.2.3:8086
copy 1.[0 8] 192.168.2.3:8085 => 192.168.2.3:8083
allocate 1.[3 11] 192.168.2.3:8085 => 192.168.2.3:8088
allocate 1.[1 9] 192.168.2.3:8085 => 192.168.2.3:8082
allocate 1.[6] 192.168.2.3:8085 => 192.168.2.3:8085
copy 1.[7] 192.168.2.3:8085 => 192.168.2.3:8086
copy 1.[5 13] 192.168.2.3:8085 => 192.168.2.3:8081
copy 1.[2 10] 192.168.2.3:8085 => 192.168.2.3:8084
copy 1.[3 11] 192.168.2.3:8085 => 192.168.2.3:8088
copy 1.[1 9] 192.168.2.3:8085 => 192.168.2.3:8082
copy 1.[4 12] 192.168.2.3:8085 => 192.168.2.3:8087
mount 1.[6] on 192.168.2.3:8085
mount 1.[7] on 192.168.2.3:8086
I1205 01:54:17 34423 command_ec_common.go:95] 192.168.2.3:8085 ec volume 1 deletes shards [7]
mount 1.[0 8] on 192.168.2.3:8083
I1205 01:54:18 34423 command_ec_common.go:95] 192.168.2.3:8085 ec volume 1 deletes shards [0 8]
mount 1.[1 9] on 192.168.2.3:8082
I1205 01:54:18 34423 command_ec_common.go:95] 192.168.2.3:8085 ec volume 1 deletes shards [1 9]
mount 1.[4 12] on 192.168.2.3:8087
I1205 01:54:19 34423 command_ec_common.go:95] 192.168.2.3:8085 ec volume 1 deletes shards [4 12]
mount 1.[2 10] on 192.168.2.3:8084
I1205 01:54:19 34423 command_ec_common.go:95] 192.168.2.3:8085 ec volume 1 deletes shards [2 10]
mount 1.[5 13] on 192.168.2.3:8081
I1205 01:54:19 34423 command_ec_common.go:95] 192.168.2.3:8085 ec volume 1 deletes shards [5 13]
mount 1.[3 11] on 192.168.2.3:8088
I1205 01:54:19 34423 command_ec_common.go:95] 192.168.2.3:8085 ec volume 1 deletes shards [3 11]
unmount 1.[7 0 8 1 9 4 12 2 10 5 13 3 11] from 192.168.2.3:8085
delete 1.[7 0 8 1 9 4 12 2 10 5 13 3 11] from 192.168.2.3:8085
delete volume 1 from 192.168.2.3:8085
delete volume 1 from 192.168.2.3:8088
delete volume 1 from 192.168.2.3:8087
delete volume 1 from 192.168.2.3:8081
>
```

**Comment by chrislusf** [comment]
thanks for reporting. fixed now.

**Comment by bddrey** [comment]
Fixed in latest commit. Excellent work. Thank you!

**Comment by xiaoweihong** [comment]
> ec.decode  -volumeId 1
ec volume 1 shard locations: map[192.168.2.27:9300:12288 192.168.2.27:9301:257 192.168.2.27:9302:2 192.168.2.27:9303:4 192.168.2.27:9304:544 192.168.2.27:9305:192 192.168.2.27:9306:2952 192.168.2.27:9307:1040]
collectEcShards: ec volume 1 collect shards to 192.168.2.27:9306 from: map[192.168.2.27:9300:12288 192.168.2.27:9301:257 192.168.2.27:9302:2 192.168.2.27:9303:4 192.168.2.27:9304:544 192.168.2.27:9305:192 192.168.2.27:9306:2952 192.168.2.27:9307:1040]
copy 1.[4] 192.168.2.27:9307 => 192.168.2.27:9306
copy 1.[2] 192.168.2.27:9303 => 192.168.2.27:9306
copy 1.[1] 192.168.2.27:9302 => 192.168.2.27:9306
copy 1.[0] 192.168.2.27:9301 => 192.168.2.27:9306
copy 1.[6] 192.168.2.27:9305 => 192.168.2.27:9306
copy 1.[5] 192.168.2.27:9304 => 192.168.2.27:9306
generateNormalVolume from ec volume 1 on 192.168.2.27:9306
error: delete ec shards for volume 1: mountVolumeAndDeleteEcShards mount volume 1 on 192.168.2.27:9306: rpc error: code = Unknown desc = volume 1 not found on disk

 volume.list
Topology volumeSizeLimit:1000 MB hdd(volume:6/160 active:6 free:154 remote:0)
  DataCenter DefaultDataCenter hdd(volume:6/160 active:6 free:154 remote:0)
    Rack DefaultRack hdd(volume:6/160 active:6 free:154 remote:0)
      DataNode 192.168.2.27:9300 hdd(volume:6/20 active:6 free:14 remote:0)
        Disk hdd(volume:6/20 active:6 free:14 remote:0)
          volume id:9  size:146936  file_count:2  version:3  modified_at_second:1640947348 
          volume id:10  size:8  version:3  modified_at_second:1640945793 
          volume id:11  size:8  version:3  modified_at_second:1640945794 
          volume id:12  size:146936  file_count:2  version:3  modified_at_second:1640947343 
          volume id:13  size:8  version:3  modified_at_second:1640945794 
          volume id:14  size:8  version:3  modified_at_second:1640945794 
          ec volume id:7 collection: shards:[12 13]
          ec volume id:8 collection: shards:[12 13]
          ec volume id:1 collection: shards:[12 13]
          ec volume id:2 collection: shards:[12 13]
          ec volume id:3 collection: shards:[12 13]
          ec volume id:4 collection: shards:[12 13]
          ec volume id:5 collection: shards:[12 13]
          ec volume id:6 collection: shards:[12 13]
        Disk hdd total size:293904 file_count:4 
      DataNode 192.168.2.27:9300 total size:293904 file_count:4 
      DataNode 192.168.2.27:9301 hdd(volume:0/20 active:0 free:20 remote:0)
        Disk hdd(volume:0/20 active:0 free:20 remote:0)
          ec volume id:3 collection: shards:[8 9]
          ec volume id:4 collection: shards:[10 11]
          ec volume id:5 collection: shards:[7]
          ec volume id:6 collection: shards:[7 8]
          ec volume id:7 collection: shards:[9 10]
          ec volume id:8 collection: shards:[6]
          ec volume id:1 collection: shards:[0 8]
          ec volume id:2 collection: shards:[3 11]
        Disk hdd total size:0 file_count:0 
      DataNode 192.168.2.27:9301 total size:0 file_count:0 
      DataNode 192.168.2.27:9302 hdd(volume:0/20 active:0 free:20 remote:0)
        Disk hdd(volume:0/20 active:0 free:20 remote:0)
          ec volume id:1 collection: shards:[1]
          ec volume id:2 collection: shards:[2]
          ec volume id:3 collection: shards:[1 2]
          ec volume id:4 collection: shards:[3 4]
          ec volume id:5 collection: shards:[5 6]
          ec volume id:6 collection: shards:[2]
          ec volume id:7 collection: shards:[1 5]
          ec volume id:8 collection: shards:[0 10]
        Disk hdd total size:0 file_count:0 
      DataNode 192.168.2.27:9302 total size:0 file_count:0 
      DataNode 192.168.2.27:9303 hdd(volume:0/20 active:0 free:20 remote:0)
        Disk hdd(volume:0/20 active:0 free:20 remote:0)
          ec volume id:7 collection: shards:[2 3]
          ec volume id:8 collection: shards:[2 8]
          ec volume id:1 collection: shards:[2]
          ec volume id:2 collection: shards:[4 10]
          ec volume id:3 collection: shards:[3]
          ec volume id:4 collection: shards:[1 7]
          ec volume id:5 collection: shards:[1 11]
          ec volume id:6 collection: shards:[3]
        Disk hdd total size:0 file_count:0 
      DataNode 192.168.2.27:9303 total size:0 file_count:0 
      DataNode 192.168.2.27:9304 hdd(volume:0/20 active:0 free:20 remote:0)
        Disk hdd(volume:0/20 active:0 free:20 remote:0)
          ec volume id:2 collection: shards:[1]
          ec volume id:3 collection: shards:[0 4]
          ec volume id:4 collection: shards:[2 6]
          ec volume id:5 collection: shards:[4 8]
          ec volume id:6 collection: shards:[6 9]
          ec volume id:7 collection: shards:[7]
          ec volume id:8 collection: shards:[4 5]
          ec volume id:1 collection: shards:[5 9]
        Disk hdd total size:0 file_count:0 
      DataNode 192.168.2.27:9304 total size:0 file_count:0 
      DataNode 192.168.2.27:9305 hdd(volume:0/20 active:0 free:20 remote:0)
        Disk hdd(volume:0/20 active:0 free:20 remote:0)
          ec volume id:4 collection: shards:[9]
          ec volume id:5 collection: shards:[0]
          ec volume id:6 collection: shards:[0 1]
          ec volume id:7 collection: shards:[0 6]
          ec volume id:8 collection: shards:[1 9]
          ec volume id:1 collection: shards:[6 7]
          ec volume id:2 collection: shards:[0 8]
          ec volume id:3 collection: shards:[7 10]
        Disk hdd total size:0 file_count:0 
      DataNode 192.168.2.27:9305 total size:0 file_count:0 
      DataNode 192.168.2.27:9306 hdd(volume:0/20 active:0 free:20 remote:0)
        Disk hdd(volume:0/20 active:0 free:20 remote:0)
          ec volume id:4 collection: shards:[0 8]
          ec volume id:5 collection: shards:[2 10]
          ec volume id:6 collection: shards:[4 11]
          ec volume id:7 collection: shards:[4]
          ec volume id:8 collection: shards:[0 1 2 3 4 5 6 7 8 9]
          ec volume id:1 collection: shards:[3 7 8 9 11]
          ec volume id:2 collection: shards:[5 9]
          ec volume id:3 collection: shards:[5]
        Disk hdd total size:0 file_count:0 
      DataNode 192.168.2.27:9306 total size:0 file_count:0 
      DataNode 192.168.2.27:9307 hdd(volume:0/20 active:0 free:20 remote:0)
        Disk hdd(volume:0/20 active:0 free:20 remote:0)
          ec volume id:2 collection: shards:[6 7]
          ec volume id:3 collection: shards:[6 11]
          ec volume id:4 collection: shards:[5]
          ec volume id:5 collection: shards:[0 1 2 3 4 5 6 7 8 9]
          ec volume id:6 collection: shards:[5 10]
          ec volume id:7 collection: shards:[8 11]
          ec volume id:8 collection: shards:[11]
          ec volume id:1 collection: shards:[4 10]
        Disk hdd total size:0 file_count:0 
      DataNode 192.168.2.27:9307 total size:0 file_count:0 
    Rack DefaultRack total size:293904 file_count:4 
  DataCenter DefaultDataCenter total size:293904 file_count:4 
total size:293904 file_count:4 


the error is exist in version 2.83
