### ISSUE TITLE
seaweedfs webui should be extracted out of this project

### ISSUE THREAD

**Issue by yanyiwu** [chrislusf/seaweedfs#249]
Now seaweedfs provide web ui service within `weed master` and `weed volume` .
And when I modify the webui codes to improve, I have to modify the seaweedfs source code .
And when somebody want to use the latest web ui , he has to upgrade the latest weedfs and restart the service on the production environment. 

If web ui is in the another project instead of seaweedfs, maybe is can named seaweedfs-webui .
Everybody can feel free to modify or upgrade or restart  seaweedfs-webui .

After all, not everyone dare to upgrade and restart a server in the production environment , but almost everybody dare to restart the webui server.

**Comment by chrislusf** [comment]
Agree.

**Comment by yanyiwu** [comment]
Thanks your agreement, I hope that project can be speeded up to build up , because as a user of seaweedfs, I am sure the webui is very very import for maintenance of seaweedfs.

**Comment by yanyiwu** [comment]
@chrislusf Is there any progress?

**Comment by chrislusf** [comment]
No progress. This is a spare time project and no time to spare these days.

**Comment by faaliyet** [comment]
+1 :+1:

**Comment by chrislusf** [comment]
There are nothing particular to be done here. It's fine to start another project to operate on current weed master and volume servers. Existing web ui is just a basic one.
