### ISSUE TITLE
FileID clarification

### ISSUE THREAD

**Issue by davistan** [chrislusf/seaweedfs#250]
Quoting from the readme:
> Now you can save the fid, 3,01637037d6 in this case, to some database field.
> The number 3 here, is a volume id. After the comma, it's one file key, 01, and a file cookie, 637037d6.

Does the 3 represent a hex?
How about file key of 01? Do you need to pad it with zero?

I'm looking at writing a function to convert file id to uuid since both of them have the same size.
Thanks.

**Comment by chrislusf** [comment]
3 is volume id, not in hex.

01 is in hex. Padding is not required now.

**Comment by davistan** [comment]
Ok, got it. Thanks.

**Comment by davistan** [comment]
I've created a simple function to convert to and from (in javascript). Anyone can use it if needed and improvise as needed.
```js
function file2uuid(fileId) {
	var x = fileId.split(',')
	var volId = parseInt(x[0],10).toString(16)
	var cookie = x[1].substr(x[1].length-8,8)
	var fId = x[1].substr(0, x[1].length-8)

	volId = '0'.repeat(8-volId.length) + volId + '-'
	fId = '0'.repeat(16-fId.length) + fId
	fId = fId.substr(0,4)+'-'+fId.substr(4,4)+'-'+fId.substr(8,4)+'-'+fId.substr(12,8)
	return volId+fId+cookie
}

function uuid2file(uuid) {
	uuid = uuid.replace(/-/g, '')
	var volId = parseInt(uuid.substr(0,8), 16)
	var fId = parseInt(uuid.substr(8,16), 16)
	var cookie = uuid.substr(24,8)
	fId = fId.toString(16)
	if (fId.length = 1) fId = '0'+fId // add zero padding
	return volId.toString(16)+','+fId.toString(16)+cookie
}

console.log(uuid2file(file2uuid('3,01637037d6')))
```
