### ISSUE TITLE
Error "volId 0 err" Volumes couldn't load after upgrading to 2.82_large_disk

### ISSUE THREAD

**Issue by kaaaq** [chrislusf/seaweedfs#2514]
Hi,
I upgrade my cluster from 2.40 to 2.82_large_disk
Now there are two types and with many errors logged by weed that volumes couldn't load properly!:

Type 1 error:

```
Dec 16 00:25:47 weed-volume-001 seaweedfs-sdb-volume[1548]: checking MegaGroup_59.dat ...
Dec 16 00:25:47 weed-volume-001 seaweedfs-sdb-volume[1548]: volId 0 err (0x282caa0,0xc008df62d0)
Dec 16 00:25:47 weed-volume-001 seaweedfs-sdb-volume[1548]: checking MegaGroup_59.idx ...
Dec 16 00:25:47 weed-volume-001 seaweedfs-sdb-volume[1548]: volId 59 err (0x0,0x0)
Dec 16 00:25:47 weed-volume-001 seaweedfs-sdb-volume[1548]: checking MegaGroup_59.vif ...
Dec 16 00:25:47 weed-volume-001 seaweedfs-sdb-volume[1548]: volId 59 err (0x0,0x0)
Dec 16 00:25:47 weed-volume-001 seaweedfs-sdb-volume[1548]: checking Profile_39.dat ...
Dec 16 00:25:47 weed-volume-001 seaweedfs-sdb-volume[1548]: volId 0 err (0x282caa0,0xc008df62f0)
Dec 16 00:25:47 weed-volume-001 seaweedfs-sdb-volume[1548]: checking Profile_39.idx ...
Dec 16 00:25:47 weed-volume-001 seaweedfs-sdb-volume[1548]: volId 39 err (0x0,0x0)
Dec 16 00:25:47 weed-volume-001 seaweedfs-sdb-volume[1548]: checking Profile_39.vif ...
Dec 16 00:25:47 weed-volume-001 seaweedfs-sdb-volume[1548]: volId 39 err (0x0,0x0)
Dec 16 00:25:47 weed-volume-001 seaweedfs-sdb-volume[1548]: checking UserCloud_100_241.dat ...
Dec 16 00:25:47 weed-volume-001 seaweedfs-sdb-volume[1548]: volId 0 err (0x282caa0,0xc008df6310)
Dec 16 00:25:47 weed-volume-001 seaweedfs-sdb-volume[1548]: checking UserCloud_100_241.idx ...
Dec 16 00:25:47 weed-volume-001 seaweedfs-sdb-volume[1548]: volId 241 err (0x0,0x0)
Dec 16 00:25:47 weed-volume-001 seaweedfs-sdb-volume[1548]: checking UserCloud_100_241.vif ...
Dec 16 00:25:47 weed-volume-001 seaweedfs-sdb-volume[1548]: volId 241 err (0x0,0x0)
Dec 16 07:09:42 weed-volume-001 seaweedfs-sdk-volume[1541]: checking UserCloud_10_288.dat ...
Dec 16 07:09:42 weed-volume-001 seaweedfs-sdk-volume[1541]: volId 0 err (0x282caa0,0xc00064c260)
Dec 16 07:09:42 weed-volume-001 seaweedfs-sdk-volume[1541]: checking UserCloud_10_288.idx ...
Dec 16 07:09:42 weed-volume-001 seaweedfs-sdk-volume[1541]: volId 288 err (0x0,0x0)
Dec 16 07:09:42 weed-volume-001 seaweedfs-sdk-volume[1541]: checking UserCloud_10_288.vif ...
Dec 16 07:09:42 weed-volume-001 seaweedfs-sdk-volume[1541]: volId 288 err (0x0,0x0)
Dec 16 07:09:42 weed-volume-001 seaweedfs-sdk-volume[1541]: checking UserCloud_10_94.dat ...
Dec 16 07:09:42 weed-volume-001 seaweedfs-sdk-volume[1541]: volId 0 err (0x282caa0,0xc00064c280)
Dec 16 07:09:42 weed-volume-001 seaweedfs-sdk-volume[1541]: checking UserCloud_10_94.idx ...
Dec 16 07:09:42 weed-volume-001 seaweedfs-sdk-volume[1541]: volId 94 err (0x0,0x0)
Dec 16 07:09:42 weed-volume-001 seaweedfs-sdk-volume[1541]: checking UserCloud_10_94.vif ...
Dec 16 07:09:42 weed-volume-001 seaweedfs-sdk-volume[1541]: volId 94 err (0x0,0x0)

```

Type 2 :

```
Dec 16 00:25:47 weed-volume-001 seaweedfs-sdb-volume[1548]: checking UserCloud_10_283.dat ...
Dec 16 00:25:47 weed-volume-001 seaweedfs-sdb-volume[1548]: volId 0 err (0x282caa0,0xc008df6330)
Dec 16 00:25:47 weed-volume-001 seaweedfs-sdb-volume[1548]: checking UserCloud_10_283.idx ...
Dec 16 00:25:47 weed-volume-001 seaweedfs-sdb-volume[1548]: volId 283 err (0x0,0x0)
Dec 16 00:25:47 weed-volume-001 seaweedfs-sdb-volume[1548]: I1216 00:25:47  1548 volume_loading.go:89] readSuperBlock volume 283 version 3
Dec 16 00:25:47 weed-volume-001 seaweedfs-sdb-volume[1548]: I1216 00:25:47  1548 volume_loading.go:136] loading index /srv/node/sdb/UserCloud_10_283.idx to memory
Dec 16 00:25:47 weed-volume-001 seaweedfs-sdb-volume[1548]: I1216 00:25:47  1548 disk_location.go:140] data file /srv/node/sdb/UserCloud_10_283.dat, replication=010 v=3 size=107386792320 ttl=
Dec 16 00:25:47 weed-volume-001 seaweedfs-sdb-volume[1548]: I1216 00:25:47  1548 store.go:402] mount volume 283
Dec 16 00:25:47 weed-volume-001 seaweedfs-sdb-volume[1548]: I1216 00:25:47  1548 volume_grpc_client_to_master.go:158] volume server weed-volume-001:8080 adds volume 283

b:

Dec 16 07:09:42 weed-volume-001 seaweedfs-sdk-volume[1541]: checking UserCloud_10_95.dat ...
Dec 16 07:09:42 weed-volume-001 seaweedfs-sdk-volume[1541]: volId 0 err (0x282caa0,0xc00064c2a0)
Dec 16 07:09:42 weed-volume-001 seaweedfs-sdk-volume[1541]: checking UserCloud_10_95.idx ...
Dec 16 07:09:42 weed-volume-001 seaweedfs-sdk-volume[1541]: volId 95 err (0x0,0x0)
Dec 16 07:09:42 weed-volume-001 seaweedfs-sdk-volume[1541]: I1216 07:09:42  1541 volume_loading.go:89] readSuperBlock volume 95 version 3
Dec 16 07:09:42 weed-volume-001 seaweedfs-sdk-volume[1541]: I1216 07:09:42  1541 volume_loading.go:136] loading index /srv/node/sdk/UserCloud_10_95.idx to memory
Dec 16 07:09:42 weed-volume-001 seaweedfs-sdk-volume[1541]: I1216 07:09:42  1541 disk_location.go:140] data file /srv/node/sdk/UserCloud_10_95.dat, replication=010 v=3 size=107380026088 ttl=
Dec 16 07:09:42 weed-volume-001 seaweedfs-sdk-volume[1541]: I1216 07:09:42  1541 store.go:402] mount volume 95
Dec 16 07:09:42 weed-volume-001 seaweedfs-sdk-volume[1541]: I1216 07:09:42  1541 volume_grpc_client_to_master.go:158] volume server weed-volume-001:8089 adds volume 95

```

What do these errors mean?
Why they couldn't be loaded properly?

**Comment by chrislusf** [comment]
can not change from non large_disk version to large_disk version.

**Comment by kaaaq** [comment]
> can not change from non large_disk version to large_disk version.

Both are large-disk version @chrislusf

**Comment by chrislusf** [comment]
sorry, those were debug messages accidentally checked in.

**Comment by kaaaq** [comment]
> sorry, those were debug messages accidentally checked in.

What about these logs, each volume processed and load and then deleted!


```
Dec 15 20:34:24 weed-master-3 seaweedfs-master[1112]: volume 314 processed 50845450240 bytes
Dec 15 20:34:25 weed-master-3 seaweedfs-master[1112]: volume 314 processed 50981765120 bytes
Dec 15 20:34:27 weed-master-3 seaweedfs-master[1112]: volume 314 processed 51118080000 bytes
Dec 15 20:34:28 weed-master-3 seaweedfs-master[1112]: volume 314 processed 51254394880 bytes
Dec 15 20:34:30 weed-master-3 seaweedfs-master[1112]: volume 314 processed 51390709760 bytes
Dec 15 20:34:32 weed-master-3 seaweedfs-master[1112]: volume 314 processed 51527024640 bytes
Dec 15 20:34:33 weed-master-3 seaweedfs-master[1112]: volume 314 processed 51663339520 bytes
Dec 15 20:34:35 weed-master-3 seaweedfs-master[1112]: volume 314 processed 51799654400 bytes
Dec 15 20:34:36 weed-master-3 seaweedfs-master[1112]: volume 314 processed 51935969280 bytes
Dec 15 20:34:37 weed-master-3 seaweedfs-master[1112]: volume 314 processed 52072284160 bytes
```

```
Dec 15 20:42:08 weed-master-3 seaweedfs-master[1112]: volume 314 processed 95284101120 bytes
Dec 15 20:42:09 weed-master-3 seaweedfs-master[1112]: 2021/12/15 20:42:09 tailing volume 314 from weed-volume-001:8086 to weed-volume-003:8081
Dec 15 20:42:21 weed-master-3 seaweedfs-master[1112]: 2021/12/15 20:42:21 deleting volume 314 from weed-volume-001:8086
Dec 15 20:42:23 weed-master-3 seaweedfs-master[1112]: 2021/12/15 20:42:23 moved volume 314 from weed-volume-001:8086 to weed-volume-003:8081
Dec 15 20:42:23 weed-master-3 seaweedfs-master[1112]: hdd 0.00 0.00:0.00          moving  volume Channel_10_316 weed-volume-001:8086 => weed-volume-001:8082
Dec 15 20:42:23 weed-master-3 seaweedfs-master[1112]: 2021/12/15 20:42:23 copying volume 316 from weed-volume-001:8086 to weed-volume-001:8082
Dec 15 20:42:23 weed-master-3 seaweedfs-master[1112]: I1215 20:42:23  1112 topology.go:209] removing volume info: Id:314, Size:0, ReplicaPlacement:010, Collection:Channel_10, Version:3, FileCount:0, DeleteCount:0, DeletedByteCount:0, ReadOnly:false
Dec 15 20:42:23 weed-master-3 seaweedfs-master[1112]: I1215 20:42:23  1112 volume_layout.go:385] Volume 314 becomes writable
Dec 15 20:42:25 weed-master-3 seaweedfs-master[1112]: volume 316 processed 136314880 bytes
Dec 15 20:42:25 weed-master-3 seaweedfs-master[1112]: I1215 20:42:25  1112 volume_layout.go:372] Volume 316 becomes unwritable
Dec 15 20:42:26 weed-master-3 seaweedfs-master[1112]: volume 316 processed 272629760 bytes


```

**Comment by kaaaq** [comment]
> Looks like ok. What don't you like here? Volume 314 was copied from server A to server B and than removed from server A.
> 
> @chrislusf , maybe here " removing volume info: Id:314, Size:0, ReplicaPlacement:010, Collection:Channel_10, Version:3, FileCount:0, DeleteCount:0, DeletedByteCount:0, ReadOnly:false" It would not hurt to indicate from which server it was deleted.

My problem is with loading each volume and processing them and then sending them to another server @chrislusf
Why does processing each volume take a long time?
This wasn't in the last versions!

**Comment by kaaaq** [comment]
> > Looks like ok. What don't you like here? Volume 314 was copied from server A to server B and than removed from server A.
> > @chrislusf , maybe here " removing volume info: Id:314, Size:0, ReplicaPlacement:010, Collection:Channel_10, Version:3, FileCount:0, DeleteCount:0, DeletedByteCount:0, ReadOnly:false" It would not hurt to indicate from which server it was deleted.
> 
> 
> My problem is with loading each volume and processing them and then sending them to another server @chrislusf Why does processing each volume take a long time? This wasn't in the previous versions! For each reboot, weed will process volume again or it's just due to updating weed to new versions and weed is changing old idx to new idx format?
> 
> ```
> Dec 15 20:34:24 weed-master-3 seaweedfs-master[1112]: volume 314 processed 50845450240 bytes
> Dec 15 20:34:25 weed-master-3 seaweedfs-master[1112]: volume 314 processed 50981765120 bytes
> Dec 15 20:34:27 weed-master-3 seaweedfs-master[1112]: volume 314 processed 51118080000 bytes
> Dec 15 20:34:28 weed-master-3 seaweedfs-master[1112]: volume 314 processed 51254394880 bytes
> Dec 15 20:34:30 weed-master-3 seaweedfs-master[1112]: volume 314 processed 51390709760 bytes
> Dec 15 20:34:32 weed-master-3 seaweedfs-master[1112]: volume 314 processed 51527024640 bytes
> Dec 15 20:34:33 weed-master-3 seaweedfs-master[1112]: volume 314 processed 51663339520 bytes
> Dec 15 20:34:35 weed-master-3 seaweedfs-master[1112]: volume 314 processed 51799654400 bytes
> Dec 15 20:34:36 weed-master-3 seaweedfs-master[1112]: volume 314 processed 51935969280 bytes
> Dec 15 20:34:37 weed-master-3 seaweedfs-master[1112]: volume 314 processed 52072284160 bytes
> ```
> 
> ```
> Dec 15 20:42:08 weed-master-3 seaweedfs-master[1112]: volume 314 processed 95284101120 bytes
> Dec 15 20:42:09 weed-master-3 seaweedfs-master[1112]: 2021/12/15 20:42:09 tailing volume 314 from weed-volume-001:8086 to weed-volume-003:8081
> Dec 15 20:42:21 weed-master-3 seaweedfs-master[1112]: 2021/12/15 20:42:21 deleting volume 314 from weed-volume-001:8086
> Dec 15 20:42:23 weed-master-3 seaweedfs-master[1112]: 2021/12/15 20:42:23 moved volume 314 from weed-volume-001:8086 to weed-volume-003:8081
> Dec 15 20:42:23 weed-master-3 seaweedfs-master[1112]: hdd 0.00 0.00:0.00          moving  volume Channel_10_316 weed-volume-001:8086 => weed-volume-001:8082
> Dec 15 20:42:23 weed-master-3 seaweedfs-master[1112]: 2021/12/15 20:42:23 copying volume 316 from weed-volume-001:8086 to weed-volume-001:8082
> Dec 15 20:42:23 weed-master-3 seaweedfs-master[1112]: I1215 20:42:23  1112 topology.go:209] removing volume info: Id:314, Size:0, ReplicaPlacement:010, Collection:Channel_10, Version:3, FileCount:0, DeleteCount:0, DeletedByteCount:0, ReadOnly:false
> Dec 15 20:42:23 weed-master-3 seaweedfs-master[1112]: I1215 20:42:23  1112 volume_layout.go:385] Volume 314 becomes writable
> Dec 15 20:42:25 weed-master-3 seaweedfs-master[1112]: volume 316 processed 136314880 bytes
> Dec 15 20:42:25 weed-master-3 seaweedfs-master[1112]: I1215 20:42:25  1112 volume_layout.go:372] Volume 316 becomes unwritable
> Dec 15 20:42:26 weed-master-3 seaweedfs-master[1112]: volume 316 processed 272629760 bytes
> ```
> 
> 
> Another thing is that periodically following commands are running in the nodes (ec check and rebalancing, ...) It seems these checks hardcoded to weed, some commands like rebalancing are not good for every production due to its overhead: I read that I can create config file for this purpose in the master nodes but logs show that you hardcoded this in new version?! @chrislusf
> 
> ```
>  3181 Dec 16 09:42:49 weed-master-3 seaweedfs-master[1112]: I1216 09:42:49  1112 master_server.go:290] executing: volume.balance [-force]
>  3182 Dec 16 09:42:49 weed-master-3 seaweedfs-master[1112]: I1216 09:42:49  1112 master_server.go:290] executing: volume.fix.replication []
>  3183 Dec 16 09:42:49 weed-master-3 seaweedfs-master[1112]: I1216 09:42:49  1112 master_server.go:290] executing: s3.clean.uploads [-timeAgo=24h]
>  3184 Dec 16 09:42:49 weed-master-3 seaweedfs-master[1112]: I1216 09:42:49  1112 master_server.go:292] error: read buckets: get filer configuration: rpc error: code = Unavailable desc = connection             error: desc = "transport: Error while dialing dial tcp [::1]:18888: connect: connection refused"
>  3185 Dec 16 09:42:49 weed-master-3 seaweedfs-master[1112]: I1216 09:42:49  1112 master_server.go:290] executing: unlock []
>  3186 Dec 16 09:59:49 weed-master-3 seaweedfs-master[1112]: I1216 09:59:49  1112 master_server.go:290] executing: lock []
>  3187 Dec 16 09:59:49 weed-master-3 seaweedfs-master[1112]: I1216 09:59:49  1112 master_server.go:290] executing: ec.encode [-fullPercent=95 -quietFor=1h]
>  3188 Dec 16 09:59:49 weed-master-3 seaweedfs-master[1112]: collect volumes quiet for: 3600 seconds
>  3189 Dec 16 09:59:49 weed-master-3 seaweedfs-master[1112]: ec encode volumes: []
>  3190 Dec 16 09:59:49 weed-master-3 seaweedfs-master[1112]: I1216 09:59:49  1112 master_server.go:290] executing: ec.rebuild [-force]
> ```

Could you please answer the question  @chrislusf 
I'm worried about new weed version functionality!

**Comment by chrislusf** [comment]
this is related to https://github.com/chrislusf/seaweedfs/issues/2525

btw: Please no exclamation marks.

**Comment by kaaaq** [comment]
> this is related to #2525
> 
> btw: Please no exclamation marks.
Many thanks for your answer @chrislusf .

It would be great if could explain the following logs("volume x processed y bytes") and Why we didn't have these in the previous versions of weed.

```
Dec 15 20:34:24 weed-master-3 seaweedfs-master[1112]: volume 314 processed 50845450240 bytes
Dec 15 20:34:25 weed-master-3 seaweedfs-master[1112]: volume 314 processed 50981765120 bytes
Dec 15 20:34:27 weed-master-3 seaweedfs-master[1112]: volume 314 processed 51118080000 bytes
Dec 15 20:34:28 weed-master-3 seaweedfs-master[1112]: volume 314 processed 51254394880 bytes
Dec 15 20:34:30 weed-master-3 seaweedfs-master[1112]: volume 314 processed 51390709760 bytes
Dec 15 20:34:32 weed-master-3 seaweedfs-master[1112]: volume 314 processed 51527024640 bytes
Dec 15 20:34:33 weed-master-3 seaweedfs-master[1112]: volume 314 processed 51663339520 bytes
Dec 15 20:34:35 weed-master-3 seaweedfs-master[1112]: volume 314 processed 51799654400 bytes
Dec 15 20:34:36 weed-master-3 seaweedfs-master[1112]: volume 314 processed 51935969280 bytes
Dec 15 20:34:37 weed-master-3 seaweedfs-master[1112]: volume 314 processed 52072284160 bytes

Dec 15 20:42:08 weed-master-3 seaweedfs-master[1112]: volume 314 processed 95284101120 bytes
Dec 15 20:42:09 weed-master-3 seaweedfs-master[1112]: 2021/12/15 20:42:09 tailing volume 314 from weed-volume-001:8086 to weed-volume-003:8081
Dec 15 20:42:21 weed-master-3 seaweedfs-master[1112]: 2021/12/15 20:42:21 deleting volume 314 from weed-volume-001:8086
Dec 15 20:42:23 weed-master-3 seaweedfs-master[1112]: 2021/12/15 20:42:23 moved volume 314 from weed-volume-001:8086 to weed-volume-003:8081
Dec 15 20:42:23 weed-master-3 seaweedfs-master[1112]: hdd 0.00 0.00:0.00          moving  volume Channel_10_316 weed-volume-001:8086 => weed-volume-001:8082
Dec 15 20:42:23 weed-master-3 seaweedfs-master[1112]: 2021/12/15 20:42:23 copying volume 316 from weed-volume-001:8086 to weed-volume-001:8082
Dec 15 20:42:23 weed-master-3 seaweedfs-master[1112]: I1215 20:42:23  1112 topology.go:209] removing volume info: Id:314, Size:0, ReplicaPlacement:010, Collection:Channel_10, Version:3, FileCount:0, DeleteCount:0, DeletedByteCount:0, ReadOnly:false
Dec 15 20:42:23 weed-master-3 seaweedfs-master[1112]: I1215 20:42:23  1112 volume_layout.go:385] Volume 314 becomes writable
Dec 15 20:42:25 weed-master-3 seaweedfs-master[1112]: volume 316 processed 136314880 bytes
Dec 15 20:42:25 weed-master-3 seaweedfs-master[1112]: I1215 20:42:25  1112 volume_layout.go:372] Volume 316 becomes unwritable
Dec 15 20:42:26 weed-master-3 seaweedfs-master[1112]: volume 316 processed 272629760 bytes


```
