### ISSUE TITLE
Cluster: Kill leader process, another leader should be elected

### ISSUE THREAD

**Issue by markschmid** [chrislusf/seaweedfs#252]
I'm referring to the Failover Master Server wiki page (https://github.com/chrislusf/seaweedfs/wiki/Failover-Master-Server):

I have started 3 master and 3 volume servers with the commands shown on the page.
When I (unix) kill the master process that is currently the leader, should another master process automatically take over leadership? Because that does not seem to be the case. Or is that only triggered on the next file operation event?

**Comment by chrislusf** [comment]
Yes, one of the other 2 master should be elected as leader. This process may take one minute.

Let me know what happens.

**Comment by markschmid** [comment]
I've made additional tests and indeed, one of the other masters took over leadership after a while. Don't know why that did not work the last time... I will look into this some more. Thanks for your help.
