### ISSUE TITLE
上传的附件名很长

### ISSUE THREAD

**Issue by hudeyi100** [chrislusf/seaweedfs#2520]
上传一个文件名称很长的附件，然后根据fid打开，文件的后缀不见了，如何解决这样的问题？谢谢

**Comment by chrislusf** [comment]
shorten your file name. The current file name size is limited to 256.

**Comment by hudeyi100** [comment]
有没有办法，可配置文件名的最大长度？

**Comment by chrislusf** [comment]
sorry, there should are no limit when using filer.
