### ISSUE TITLE
文件导出功能

### ISSUE THREAD

**Issue by hudeyi100** [chrislusf/seaweedfs#2521]
文件导出，原始中文名称不显示，fid只是显示序号，如何让导出的数据，fid 和附件原始名称都显示？

**Comment by chrislusf** [comment]
see `weed export -h`

**Comment by hudeyi100** [comment]
谢谢您的回答，我已经看了这个命令，就是按照命令导出的，但导出的文件不是我想要的，我截个图给您看下，下面这张图，是原始数据（被上传到seaweedfs里的数据）
![1原始数据](https://user-images.githubusercontent.com/3301365/146752663-9d31ddf0-cfdd-405a-8a6e-1d8ea42a6ab3.png)
下面这张图，是我export 一个volumeID里的数据
![导出的数据](https://user-images.githubusercontent.com/3301365/146753200-c7aa43aa-67f1-42da-95af-b8885157c232.png)
