### ISSUE TITLE
Undocumented change to default admin scripts

### ISSUE THREAD

**Issue by kliberty** [chrislusf/seaweedfs#2525]
Commit  https://github.com/chrislusf/seaweedfs/commit/3d7390302d9b3b1e1bbbd23653dc52bdc3bd27c4#diff-1f7b377a963eee3cdc38f3f4b7c168638a43855c5e3b03e7fcc00504dba4389aL215 enabled `ec.encode` on masters which have no `master.toml` file.

I understand if these are the recommended defaults (and that I should have a `master.toml`), but this is not described in the release notes and it took me a while to dig through the commit history to figure out what as going on.

**Comment by chrislusf** [comment]
Sorry, I need to revert this to a more "common" default.
