### ISSUE TITLE
Garbage not deleted

### ISSUE THREAD

**Issue by vitalif** [chrislusf/seaweedfs#2526]
Hi, I uploaded a file through S3 and then deleted it (via a FUSE mount). I want to delete it from the volume, but it's still present in the volume data.

I've read https://github.com/chrislusf/seaweedfs/wiki/Master-Server-API#force-garbage-collection and tried it, but it doesn't seem to do anything.

Also I tried to manually compact all volumes using weed compact and it also didn't delete anything.

So I suspect the file is still present as a "tombstone" or something like that. How to actually delete it?

- Command: `/home/seaweedfs/weed server -volume.port=8090 -ip.bind=127.0.0.1 -ip=127.0.0.1 -dir=/home/seaweedfs/data -s3 -s3.config=/home/seaweedfs/s3.conf`
- Debian 11.1
- weed version 30GB 2.68 96514f0f00f1ca6f0f253c1c4080a45887d09ad9 linux amd64

**Comment by chrislusf** [comment]
> I've read https://github.com/chrislusf/seaweedfs/wiki/Master-Server-API#force-garbage-collection and tried it, but it doesn't seem to do anything.
> 
> Also I tried to manually compact all volumes using weed compact and it also didn't delete anything.

What were your commands used?

**Comment by vitalif** [comment]
`curl "http://127.0.0.1:9333/vol/vacuum?garbageThreshold=0.00001"`
`curl "http://127.0.0.1:9333/vol/vacuum?garbageThreshold=0.000000001"`
Then I waited because it says GC is ran every 15 minutes, nothing changed
Also I tried to run `weed compact -dir=. -volumeId=8` using a copy of data directory
Volume sizes didn't change after running this command so I presume nothing was removed
The name of the old file is still present in two volume *.dat files :-) no idea why it's present in 2 of them
At the same time, s3cmd listing doesn't show the object

**Comment by chrislusf** [comment]
try to use `volume.vacuum` in `weed shell`.

**Comment by vitalif** [comment]
Ran `volume.vacuum -garbageThreshold 0.00001` in weed shell.
Nothing changed.

**Comment by vitalif** [comment]
Please reopen )

**Comment by chrislusf** [comment]
Can not reproduce. Please add some screenshots.

**Comment by vitalif** [comment]
Ok. I found fsck command and ran it in shell. That's what I see:
```
> volume.fsck
volume:7    entries:774 orphan:201  25.97%  81573417B
volume:2    entries:721 orphan:190  26.35%  73208913B
volume:5    entries:738 orphan:182  24.66%  71591954B
volume:4    entries:731 orphan:202  27.63%  97263742B
volume:8    entries:1000    orphan:1000 100.00% 2490469B
volume:6    entries:675 orphan:172  25.48%  55850222B
volume:3    entries:677 orphan:160  23.63%  66179578B
volume:1    entries:785 orphan:210  26.75%  100437658B
```
I use only 1 server. How to remove these orphans?

**Comment by vitalif** [comment]
Ok I found #1532. It seems -reallyDeleteFromVolume helped.
Why do orphans appear at all?

**Comment by vitalif** [comment]
In fact it's rather strange, I wonder if if it deleted any real data... Because I don't think I did that amount of deletes.
It's a test site so the data itn't really valuable, but I still wonder if it may delete something which is in use...

**Comment by chrislusf** [comment]
I can not guess the actions you took.

**Comment by vitalif** [comment]
> I can not guess the actions you took.

I just used seaweedfs as an S3 server for a test site. Uploading and downloading files. Some of them could be multipart. Nothing special

**Comment by vitalif** [comment]
Can you give any hint about orphans? Why can they appear in theory?

**Comment by chrislusf** [comment]
reproducible steps would be helpful.

**Comment by vitalif** [comment]
I understand, but I can't reproduce it easily. I tried to start a clean seaweedfs instance, upload several files, delete some of them and run compaction and it worked fine.
That's why I'm asking you for hypothesis because you obviously know your code much better than me ))

**Comment by vitalif** [comment]
I have another test instance with orphans from my laptop. Do you want me to send you all files of this instance? It doesn't have anything sensitive, only test pictures. Data from weed shell:
```
$ ./weed shell
master: localhost:9333 filers: [192.168.1.153:8888]
> lock
> volume.fsck
volume:3        entries:13      orphan:13       100.00% 13315B
volume:5        entries:5       orphan:5        100.00% 3318B
volume:1        entries:11      orphan:11       100.00% 18092B
volume:6        entries:20      orphan:20       100.00% 22936B
volume:4        entries:18      orphan:18       100.00% 17818B
volume:2        entries:12      orphan:12       100.00% 16485B
volume:7        entries:12      orphan:12       100.00% 9568B

Total           entries:211     orphan:91       43.13%  101532B
This could be normal if multiple filers or no filers are used.
```

**Comment by vitalif** [comment]
Also here it doesn't show the volume that's named `uploads_8.dat` on disk. 1-7 are named `1.dat` .. `7.dat`, and it looks funny because for all volumes entries==orphan but total entries is > than total orphans...
