### ISSUE TITLE
Can  Filer Server API support fsync?

### ISSUE THREAD

**Issue by qwedsazzcc** [chrislusf/seaweedfs#2528]
Volume Serve API  URL Parameter fsync It's very useful to us，But our business needs filer ， Can  Filer Server API support  it

**Comment by LuckyFrost** [comment]
You can use any of the available filer DBs, which will have each write with fsync thanks to the settings of the base itself.

**Comment by chrislusf** [comment]
@qwedsazzcc I think you mean similar to fsync in volume API https://github.com/chrislusf/seaweedfs/wiki/Volume-Server-API#upload-file , adding a fsync to filer API also https://github.com/chrislusf/seaweedfs/wiki/Filer-Server-API#postputget-files?

**Comment by qwedsazzcc** [comment]
> @qwedsazzcc I think you mean similar to fsync in volume API https://github.com/chrislusf/seaweedfs/wiki/Volume-Server-API#upload-file , adding a fsync to filer API also https://github.com/chrislusf/seaweedfs/wiki/Filer-Server-API#postputget-files?

yes
