### ISSUE TITLE
Unable to use port=0 (any) for volume servers

### ISSUE THREAD

**Issue by rooterkyberian** [chrislusf/seaweedfs#253]
It seems it starts up fine, gets 'random' port from OS (Linux in this case), but still thinks it has binded to port 0 - and so it presents itself to master and master obviously cannot reach it at that port 0.

[Weed output (master+volume) and netstat confirming it binded correctly](https://gist.github.com/rooterkyberian/83eb547e1545db0fee03)

**Comment by chrislusf** [comment]
Current design just pass the specified port to the master, and does not support this random port feature.

Does it work for you that you specify a specific port?

**Comment by rooterkyberian** [comment]
Yes it works for non-zero port number. This is just a feature request. I have looked into the code and have seen that it works as you described - port number from command line is passed to server as is. I have yet to learn golang and this is why there is no pull requests, but just a 'note' about nice to have feature.

**Comment by faaliyet** [comment]
I think, it's not a bug nor an issue.
