### ISSUE TITLE
Upload portrait image will be rotated when using scaled version

### ISSUE THREAD

**Issue by kw005** [chrislusf/seaweedfs#2555]
Uploading a portrait image (cell phone image) file works fine and also the image looks as upload when accessing it like` host.com/3,23r09uref0894`
However, when accessing as a scaled version like `host.com/3,23r09uref08941?height=300&width=300&mode=fit`
it will be rotated by 90 degrees. 

Can anybody reproduce that bug or discovered the same issue?

**Comment by chrislusf** [comment]
Need to know how to reproduce.

**Comment by chrislusf** [comment]
I believe this seems a real bug. But it is an old feature. Need some more details.
