### ISSUE TITLE
Any plan for using godep(or glide) to manage dependencies ?

### ISSUE THREAD

**Issue by yanyiwu** [chrislusf/seaweedfs#256]
I think godep is a good tool to mange dependencies better for this project.
So I wonder whether this project will use it .

For example, TiDB use godep as well.

**Comment by yanyiwu** [comment]
```
go build
# github.com/chrislusf/seaweedfs/go/weed
./mount_std.go:77: cannot use File literal (type File) as type fs.Node in return argument:
        File does not implement fs.Node (wrong type for Attr method)
                have Attr("golang.org/x/net/context".Context, *fuse.Attr) error
                want Attr(*fuse.Attr)
./mount_std.go:85: cannot use Dir literal (type Dir) as type fs.Node in return argument:
        Dir does not implement fs.Node (wrong type for Attr method)
                have Attr("golang.org/x/net/context".Context, *fuse.Attr) error
                want Attr(*fuse.Attr)
./signal_handling.go:15: undefined: signal.Ignore
```

I think it is because `bazil.org/fuse/fs` version is wrong in my $GOPATH

If use `godep` to manager all the deps, it would not happen again.

**Comment by chrislusf** [comment]
Godep and the recent golang "vendor" support are good options. Do you know which one is good?

**Comment by yanyiwu** [comment]
I am not familar with golang "vendor" and it needs golang version > 1.5 .
I don't think golang 1.5 is popular enough for every company production environment.
So I think godep is more suitable for now. and it can be migrated to golang "vendor" easily by [godep-migrating-to-vendor](https://github.com/tools/godep#migrating-to-vendor) when you need.

**Comment by spance** [comment]
At present, we should use the latest version of Golang, because Golang is a relatively young language, the newer version will bring a lot of performance and security improvements.

This "vendor" feature has been officially released, we should trust it and use it.

**Comment by yanyiwu** [comment]
Now I think [glide](https://github.com/Masterminds/glide) is much better than godep, I am the fan of glide.

**Comment by chrislusf** [comment]
Let's go with glide. Someone can help on this?
