### ISSUE TITLE
fuse mount: editing files with GLib-based applications may lead to potential data loss

### ISSUE THREAD

**Issue by beipm** [chrislusf/seaweedfs#2561]
**Describe the bug**
I am using seaweedfs as a single node NAS-setup on a raspberry pi 4b 8gb and noticed this behaviour first on 2.82 after setting it up; however it is still reproducable on 2.83 and 2.84, even in a fresh debian 10 x86_64 installation inside a qemu-kvm-based machine using MATE-desktop and seaweed 2.84, therefore I suspect a bug here and report it hereby. I am aware that this is not the environment seaweedfs is designed for, however it is quite suiteable for my needs.

To reproduce the behaviour, I started the following commands after downloading the newest provided binary release on my vm (linux_amd64.tar.gz 2.84):
````
tar xvzf linux_amd64.tar.gz
mkdir mount
./weed server -filer
./weed mount -dir mount
````

As for my understanding, this creates a basic, non-replicated, local single-node setup with 1 master, 1 volume & 1 filer using leveldb2. As far as my investigation indicate, the problem is relatively configuration independent and occurs even when using separated components, replication or multiple nodes and with direct localhost-references using the loopback-device aswell, so I tried to get the scenario most barebone to reproduce it.

As long as I copy / move files into mount, everything seems to be fine and all data seems to be intact.
But when I create an empty file (e.g. ````touch test```) and edit it with a graphical editor, such as Pluma, mousepad, gedit, xed or even geany, inserting a text like for example 'Hello World!' and save that file via the editor, the content of the file becomes completely lost. Once I open the file again in the same editor, a different editor or even 'cat' it, in the best case it is empty as before the saving; with xed I noticed once that all the characters seem to be 'there', but got replaced with 0x00-bytes, however this was not reproducable.

When I edit the same file with command line editors like nano, vi or even the editor included in midnight commander, everything seems to be fine. Classical editors such as the lesstif based 'nedit' work also as expected, same with qt-based editors like Kate. File operations using pipes on the shell, like `echo 'hello world' > ./test && cat ./test` there is no problem aswell. It also does not happen when I create a new file in the aforementioned editors, enter some content and save it directly as a new file.

However, after saving the files using the problematic editors, executing `ls -la` or `stat` in the directory shows up several .goutputstream-XXXXX-Files which - according to ls & stat - should have some bytes of content, however trying to open them returns empty files. Examining the volume .dat-files using a hex editor or using the `strings` utility, the file contents created before, seemingly lost, appear to have been written to the volume.

Therefore I suspect that this issue might be connected to the habit of those GLib based applications, that they store the new file under a new, temporary name and - once that is completed - delete the old file and rename the temporary named one to the original name.
Might it be possible that there are race conditions in the mount- / filer-command while executing those delete / rename operations, which lead to destroyed references?

Unfortunately, I cannot reproduce this theory on the shell, like with `echo 'hello world' > ./test && cat ./test && echo 'hello world and beyond' > ./test.new && mv ./test.new ./test && cat ./test`, so there might be more behind the curtain. However, I noticed that the behaviour is not exclusive to text files; once I tried to open an image file using GLib-based "Shotwell", rotated the image file and tried to save, this resulted in an 'I/O error while saving' and a 0-byte-file. 'Eye of MATE', which is a fork of 'Eye of GNOME', also resulted in a 0-byte-file, but without presenting an I/O error prompt at saving.

Weirdly enough, this whole behaviour is suddenly not reproducable anymore when starting seaweed server with -v beyond 1.

V=1 server using pluma, file got lost:
````
[...]
I0105 23:18:14  1557 filer_grpc_server_sub_meta.go:245] + listener mount@[::1]:59934
I0105 23:18:14  1557 filer_grpc_server_sub_meta.go:34]  mount@[::1]:59934 starts to subscribe / from 2022-01-05 23:18:14.894648296 +0100 CET
I0105 23:18:23  1557 filer_grpc_server_rename.go:53] StreamRenameEntry old_directory:"/test" old_name:".goutputstream-BDORF1" new_directory:"/test" new_name="test" signatures:1166602783
I0105 23:18:23  1557 filer_grpc_server_rename.go:142] moving entry /test/.goutputstream-BDORF1 => /test/test
I0105 23:18:24  1557 filer_deletion.go:60] deleting fileIds len=1
````

V=1 server using bash snippet, file is intact:
````
I0105 23:24:11  1557 filer_grpc_server_rename.go:53] StreamRenameEntry old_directory:"/test" old_name:"test.new" new_directory:"/test" new_name:"test" signatures:1166602783
I0105 23:24:11  1557 filer_grpc_server_rename.go:142] moving entry /test/test.new => /test/test
I0105 23:24:11  1557 filer_deletion.go:60] deleting fileIds len=1
````

V=3 mount using pluma, file got lost:
````
I0105 23:47:33  1268 file_util.go:23] Folder /tmp/e05a079f/meta Permission: -rwxr-xr-x
I0105 23:47:33  1268 mount_std.go:241] mounted localhost:8888/ to mount
I0105 23:47:39  1268 dir.go:256] mkdir: directory:"/" entry:{name:"Namenloser Ordner" is_directory:true attributes:{mtime:1641422859 file_mode:2147484141 uid:1000 gid:1000 crtime:1641422859}} signatures:-1412334811
I0105 23:47:41  1268 meta_cache.go:87] InsertEntry //test
I0105 23:47:41  1268 meta_cache.go:74] DeleteEntry /Namenloser Ordner
I0105 23:47:46  1268 dir.go:202] create /test/neue Datei
I0105 23:47:48  1268 meta_cache.go:87] InsertEntry /test/test
I0105 23:47:48  1268 meta_cache.go:74] DeleteEntry /test/neue Datei
I0105 23:47:49  1268 filehandle.go:136] empty fh /test/test
I0105 23:47:56  1268 dir.go:202] create /test/.goutputstream-TXPDF1
I0105 23:47:56  1268 meta_cache.go:87] InsertEntry /test/test
I0105 23:47:56  1268 meta_cache.go:74] DeleteEntry /test/.goutputstream-TXPDF1
I0105 23:47:56  1268 dirty_pages_temp_file.go:93] /test/test saveToStorage 1,01459ec795 [0,13)
I0105 23:47:56  1268 filehandle.go:136] empty fh /test/test
````

V=3 mount using bash snippet, file is intact:
````
I0105 23:50:59  1268 filehandle.go:136] empty fh /test/test
I0105 23:52:01  1268 dirty_pages_temp_file.go:93] /test/test saveToStorage 3,04bb71d390 [0,12)
I0105 23:52:01  1268 dirty_pages_temp_file.go:93] /test/test.new saveToStorage 6,05785c7e81 [0,23)
I0105 23:52:01  1268 meta_cache.go:87] InsertEntry /test/test
I0105 23:52:01  1268 meta_cache.go:74] DeleteEntry /test/test.new
````

**System Setup**
- Occurs on RPi4 Raspbian based upon Debian Buster using linux_arm-Releases and is reproduceable as well in a qemu-kvm vm using a fresh Debian 11.2.0-installation and my regular Linux Mint 20.2 installation.
- occurs on Seaweed 2.82, 2.83, 2.84
- the involved roblematic applications are linked against libglib2.0, which was on debian package version 2.66.8-1; behaviour is same on a linux mint 20.2 using package versions 2.64.6-1~ubuntu20.04.4 for libglib2.0-0
- occurs using at least the following applications on Debian 11.2.0:
  - pluma 1.24.1-1 (libglib-2.0)
  - mousepad 0.5.2-1 (libglib-2.0)
  - gedit 3.38.1-1 (libglib-2.0)
  - geany 1.37.1-2 (libglib-2.0)
  - shotwell 0.30.11-1 (libglib-2.0)
  - eom 1.24.1-1 (libglib-2.0)
- no configuration file is required to reproduce the behaviour

**Expected behavior**
Saving a file in a text editor on a seaweed fuse mount should behave same as using a regular disk, regardless of what measures or transport wrapper libraries the application uses to store its data.

**Comment by chrislusf** [comment]
First of all, thanks for the detailed report! A good bug report is priceless!

I suspect these applications did not flush before the renaming. I will debug more.

**Comment by chrislusf** [comment]
This is fixed in https://github.com/chrislusf/seaweedfs/commit/67b0645808f853b8c6a88002edb0dbf796a092c5

You can use the dev version to try it out https://github.com/chrislusf/seaweedfs/releases/tag/dev

Thanks again for all the details!

**Comment by beipm** [comment]
Thank you for your fast and kind response and the new dev build, I just tested it. The bug seems to be mostly fixed as far as I can tell by early testing; however, the first file added to the filesystem with the new build got zeroed out; it has the correct size, but is filled with null-bytes when viewed with a hex editor. More oddly, this is a behaviour I cannot safely reproduce anymore, I don't recognize a pattern in this behaviour. In a second try, it affected the sixth file in the file system, after I closed the editor the first time, creating several files before. But as the former .goutputstream-Files are gone, this might be a new issue.

I thereby provide detailed logs and data files created by the current dev version 20220106-0528; first file added to this filesystem, directory/aloha, got zeroed out:
[20220106-0528-export.zip](https://github.com/chrislusf/seaweedfs/files/7820667/20220106-0528-export.zip)

**Comment by chrislusf** [comment]
I may have made an extra change. Please wait about 4 minutes and use the new dev version to try it again?

**Comment by beipm** [comment]
Unfortunately, no; the first file with the 20220106-0937-build got filled with zero-bytes aswell.

Again, I provide detailed logs and data files, created by the current dev version:
[20220106-0937-export.zip](https://github.com/chrislusf/seaweedfs/files/7820943/20220106-0937-export.zip)

As the problem seemed to be kind of erratic, I also did a screen capture of the behaviour using several editors, but it happened "only" on the first try, so maybe it helps in some way:
[seaweedfs#2561 - 20220106-0937 screencapture on youtube (unlisted)](https://www.youtube.com/watch?v=sSzFoUf9LQY)

It does not seem to be predictable, when the error occurs, but I tried it several times and I can get it at least safely to "happen" once per instance, as there are not that many tries required.

**Comment by chrislusf** [comment]
I added another fix. Please help to see whether this helps with the dev version.

**Comment by beipm** [comment]
I just tested it with the current 20220112-1110; I am unable to reproduce it anymore, the issue appears to be fixed.

Thank you very much :)

**Comment by chrislusf** [comment]
Thanks for the confirmation!
