### ISSUE TITLE
aws cli failed if s3 SSL was enabled

### ISSUE THREAD

**Issue by guol-fnst** [chrislusf/seaweedfs#2565]
I use aws cli to configure IAM policy for weed s3 service.  
```
aws configure
aws configure set default.s3.signature_version s3v4
```

I started s3 using the following command
`weed  s3 -port=29000 -filer=20.20.21.11:28000 -key.file=/etc/seaweedfs/server.key -cert.file=/etc/seaweedfs/server.crt`

It's ok to list buckets (aws --endpoint-url https://193.160.26.31:29000 s3 ls --no-verify-ssl)
But creating user failed when user aws cli:
```
#  aws --no-verify-ssl --endpoint-url https://193.160.26.31:29000  iam create-access-key --user-name test2
/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host '193.160.26.31'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,

Unable to parse response (no element found: line 1, column 0), invalid XML received. Further retries may succeed:

```

**Comment by guol-fnst** [comment]
Sorry, I made a mistake

**Comment by fujiawei-dev** [comment]
> Sorry, I made a mistake

I have the same problem, how did you solve it?

**Comment by kmlebedev** [comment]
iam listen another port
