### ISSUE TITLE
Master Closes connection to Volume server

### ISSUE THREAD

**Issue by clayscode** [chrislusf/seaweedfs#2567]
**Describe the bug**
Using the security configuration [here](https://github.com/chrislusf/seaweedfs/wiki/Security-Configuration) while hosting Master, Volume, and Filer on separate endpoints I get the following error message repeatedly:

```
I0110 01:06:01  6083 volume_grpc_client_to_master.go:41] checkWithMaster sw-master.lan:9333: get master sw-master.lan:9333 configuration: rpc error: code = Unavailable desc = connection closed
```

**System Setup**
Filer Command:
```
./weed filer -master=sw-master
```
Master Command:
```
./weed master -mdir=.
```
Volume Command:
```
./weed volume --max=100 -mserver="sw-master.lan:9333" -dir=./data
```

Operating System: Ubuntu 20.04.3 
SeaweedFS Version: 2.84

**Expected behavior**
Volume server should connect to master without error

If I remove the security configuration, all endpoints connect to each other without issue. The Filer server connects to Master without issue, the only problem is the volume server.

**Comment by chrislusf** [comment]
Is this file `security.toml` also placed in the volume server?

**Comment by clayscode** [comment]
```clay@sw-vol1:~$ ls -ltarh ~/.seaweedfs/
total 16K
drwxr-xr-x 7 clay clay 4.0K Jan  9 01:03 ..
drwxrwxr-x 3 clay clay 4.0K Jan  9 01:11 .
drwxrwxr-x 2 clay clay 4.0K Jan 10 01:01 out
-rw-rw-r-- 1 clay clay  784 Jan 10 01:04 security.toml
```
Yes, here is all the contents of the ~/.seaweedfs folder on my volume server

**Comment by chrislusf** [comment]
can you show the log with `./weed -v=1 volume --max=100 -mserver=192.168.22.81:9333 -dir=./data`

**Comment by clayscode** [comment]
Wow. I figured it out. I had an old security.toml file in the directory I was running the volume server from and that was getting read first instead of ~/.seaweedfs/security.toml. Thanks for your help!
