### ISSUE TITLE
Requirement for serving to 100K client

### ISSUE THREAD

**Issue by Rustixir** [chrislusf/seaweedfs#2570]
Hi .

I need serving to my client ( ~ 100K )
My files size is under 10MB ( 90% of them )

After see your benchmark i think be enough 
To run 3 volume with ( 4 core )

Yes ??

When my clients increase , we just add another
Volume node to master or need more work ?!

**Comment by chrislusf** [comment]
not sure how to answer a fuzzy question. How about a fuzzy "yes"?
