### ISSUE TITLE
run fio on fuse mount with chunk size 128MB cause machine frozen

### ISSUE THREAD

**Issue by half-life666** [chrislusf/seaweedfs#2586]
**Describe the bug**
Setup the 2 node seaweed, the main difference here is we use small volume size and chunksize 128MB for a cloud storage tier setup.

Run fio seq/rand write test on fuse mount, when the test reaches 100%, the whole machine is unresponsive for 5+ mins, I can't run any cmd on this machine at all.

However if I use dd to create multiple files it's fine, if I use default chunksize 2MB, when test reaches 100%, only high cpu useage is observed from top for a few seconds, then fio ended.

This issue can be easily reproducible with this setup.

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
  ```
  weed -logdir=/var/log/weed/master1 master -mdir=/mnt/weed/master1 -peers=localhost:9332,freemen:9331 -port=9331 -volumeSizeLimitMB=1024 -defaultReplication=001 

  weed -logdir=/var/log/weed/master2 master -mdir=/mnt/weed/master2 -peers=localhost:9331,172.17.0.3:9331 -port=9332 -volumeSizeLimitMB=1024 -defaultReplication=001

  weed -logdir=/var/log/weed/volume1 volume -disk=hdd -index=leveldb -dir=/mnt/weed/data1 -mserver=localhost:9331,localhost:9332,172.17.0.3:9333 -port=8081

  weed -logdir=/var/log/weed/filer1 filer -port=8801 -master=localhost:9331,localhost:9332,172.17.0.3:9331 -defaultReplicaPlacement=001 -collection=user1 -maxMB=128

  weed mount -filer='localhost:8801,172.17.0.3:8801' -dir=/mnt/fuse_weed -filer.path=/user1 -chunkSizeLimitMB=128 -cacheCapacityMB=0 -collection=user1

  ```

  ```
  weed -logdir=/var/log/weed/master3 master -mdir=/mnt/weed/master3 -peers=172.17.0.195:9331,172.17.0.195:9332 -port=9331 -volumeSizeLimitMB=1024 -defaultReplication=001

  weed -logdir=/var/log/weed/volume2 volume -disk=hdd -max=0 -index=leveldb -dir=/mnt/weed/data2 -mserver=172.17.0.195:9331,172.17.0.195:9332,localhost:9331 -port=8081
  ```

  fio config:
  ```
  [global]
  bs=64K
  iodepth=1
  direct=1
  ioengine=psync
  group_reporting
  time_based
  runtime=30
  numjobs=1
  name=seq-write
  rw=write
  
  [file1]
  filename=/mnt/fuse_weed/test_file1
  size=2G
  ```
- OS version
  `CentOS Linux release 7.9.2009 (Core)`
- output of `weed version`
   `version 30GB 2.82 c3b73ec23b9c7831e31503ebf3a64cc2f0a3c33d linux amd64`
- if using filer, show the content of `filer.toml`
   only changed below part:
   ```
   [leveldb2]
   # local on disk, mostly for simple single-machine setup, fairly scalable
   # faster than previous leveldb, recommended.
   enabled = true
   dir = "/mnt/weed/filerldb2"                    # directory to store level db files
   ```

**Expected behavior**
fio test should end without system frozen

**Screenshots**

fio reaches 100%:
![fio end](https://user-images.githubusercontent.com/82158894/149258881-c7ef8103-5644-4558-9314-88d540e3c88a.png)

run cmd frozen:
![du frozen](https://user-images.githubusercontent.com/82158894/149258962-44adf501-7c5b-41f4-a4ba-11c5af18eaa8.png)

**Additional context**

**Comment by chrislusf** [comment]
could you please try latest version? 2.82 is actually the last version using the un-optimized algorithm to write.

**Comment by half-life666** [comment]
I just tried weed 2.85, it's same.

**Comment by half-life666** [comment]
Another side effect is it will consume lot of space in the /tmp/ directory, e.g., after one or two fio test, it will show:

```
11G     /tmp/008aa696
2.1G    /tmp/7afc4149
```

if I don't disable the cache (`cacheCapacityMB=0`), the /tmp will become full easily in my 40GB system drive. Looks like I can't disable the meta cache for fuse mount.

**Comment by chrislusf** [comment]
you can reduce `weed mount -concurrentWriters=32` to avoid using too much memory.

**Comment by chrislusf** [comment]
When randomly write a large file, the large file will need to sit on the disk first, before flushing to the remote storage.

**Comment by half-life666** [comment]
> you can reduce weed mount -concurrentWriters=32 to avoid using too much memory.

Thanks, this helps, so the only question is, the fio performance varies a lot:
```
bw (  KiB/s): min= 3072, max=356992,
iops        : min=   48, max= 5578,
```
can this be improved?

**Comment by chrislusf** [comment]
it's hard to optimize for random IO. For sequential IO, it should be faster.
