### ISSUE TITLE
Parallel migration between tiers?

### ISSUE THREAD

**Issue by divanikus** [chrislusf/seaweedfs#2591]
We've been using tiered storage for a quite time already, even in production. But as our storage grows, we have faced the bottleneck in the current scheme. Hot storage is filling up quite fast, and as far as `volume.tier.move ` move one volume at time, `master` script simply can't keep up with that pace. I've already disabled almost all other operations on cluster and forced script rerun to every 30 minutes, but still. 
So it would be cool to be able to move volumes to another tier in parallel. Say, I have 3 ssd servers and 6 hdd servers. I think I can move up to 3 volumes at time without greatly affecting performance. Could this be implemented or I have missed something and it can be done already?

**Comment by chrislusf** [comment]
The algo is all in this file: https://github.com/chrislusf/seaweedfs/blob/master/weed/shell/command_volume_tier_move.go#L86

Probably you can try to adjust the algo. Need to avoid one server moving more than one volume at any moment.

**Comment by divanikus** [comment]
I'm afraid I'm not that familiar with Go, but I'll give it a shot. My pretty much straightforward approach can be maintaining a list of currently running `[from, to]` migrations and scanning for pairs which has neither `from` nor `to` from the previous list. If such pair found, just wind up another migration right away and restart scan. If no pairs found, wait till previous tasks finish. Also I can think of an option which explicitly limits the maximum number of running tasks. 

Let me now if I'm designing something stupid or not implementable.

**Comment by divanikus** [comment]
I came up with a little bit different approach, please review it.
