### ISSUE TITLE
i  am going to translate wiki page to Chinese Simplified ｜ 翻译成简体中文

### ISSUE THREAD

**Issue by EsqerYasen** [chrislusf/seaweedfs#2592]
wiki page - https://github.com/chrislusf/seaweedfs/wiki
我准备接下来一段时间（期望两个月之内）把wiki页面翻译成简体中文， 有没有人正在做这个工作？ 如果有在做的话为了不要重复工作可以告知我一下。 
I plan to translate the wiki page into Chinese Simplified, is anyone already translating?

**Comment by chrislusf** [comment]
You are very welcome!

The documentation is keep evolving. It'll be hard to keep the two versions in sync. I would suggest start a separate git repo for the Chinese version, so that it is easier to compare and find out the differences.

**Comment by EsqerYasen** [comment]
> You are very welcome!
> 
> The documentation is keep evolving. It'll be hard to keep the two versions in sync. I would suggest start a separate git repo for the Chinese version, so that it is easier to compare and find out the differences.

sure , what i am thinking is first translate Chinese Simplified  save it with markdown and will publish with gitbook.   how do you thin about it ?

**Comment by chrislusf** [comment]
gitbook should be fine.
