### ISSUE TITLE
Weed-fs constantly reports "Deletion Failed." error message

### ISSUE THREAD

**Issue by fedotxxl** [chrislusf/seaweedfs#260]
Hello
I try to delete some images. For some of them it reports `{"error":"Deletion Failed."}`. All volume servers are alive and connected to master server. Logs doesn't contain anything useful. Can you suggest something to fix it?

weed-fs version 0.69

**Comment by chrislusf** [comment]
Did you use replication?

**Comment by fedotxxl** [comment]
yes, we've got 3 volumes with `001` replication scheme. Both volume servers report this message

**Comment by fedotxxl** [comment]
Any ideas about reason of this problem? We've got a lot of such exceptions and we can reproduce it by curl:

```
curl -v -X DELETE http://images12.server.com:8072/8,01a29f06bc008de6_3
* About to connect() to images12.server.com port 8072 (#0)
*   Trying 50.7.104.90... connected
* Connected to images12.server.com (50.7.104.90) port 8072 (#0)
> DELETE /8,01a29f06bc008de6_3 HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.15.3 zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: images12.server.com:8072
> Accept: */*
> 
< HTTP/1.1 500 Internal Server Error
< Content-Type: application/json
< Date: Thu, 28 Apr 2016 12:00:47 GMT
< Content-Length: 28
< 
* Connection #0 to host images12.server.com left intact
* Closing connection #0
{"error":"Deletion Failed."}
```

Can you explain the reason / suggest ways to fix it?

**Comment by chrislusf** [comment]
Please look for any errors the volume server spits out when the deletion
error happens.

Chris

**Comment by chrislusf** [comment]
Also, I would like to know whether the second call to "curl -v -X DELETE
http://images12.server.com:8072/8,01a29f06bc008de6_3" has the same error.

I add more detailed error for these distributed deletions just now. but I
am not sure whether you can use the latest version to test.

Chris

**Comment by fedotxxl** [comment]
>Please look for any errors the volume server spits out when the deletion
error happens.
I didn't see any

>Also, I would like to know whether the second call to "curl -v -X DELETE
http://images12.server.com:8072/8,01a29f06bc008de6_3" has the same error.

Yes, it has the same error

>I add more detailed error for these distributed deletions just now. but I
am not sure whether you can use the latest version to test.

1. We updated out dev server but got another problem #299 
2. I'm not sure we will able to reproduce it on dev server

**Comment by chrislusf** [comment]
>> Also, I would like to know whether the second call to "curl -v -X DELETE
>> http://images12.server.com:8072/8,01a29f06bc008de6_3" has the same error.
> Yes, it has the same error

That's good to debug. You can look up to find out where volume 8 replica is located:
https://github.com/chrislusf/seaweedfs/wiki/API#lookup-volume
And send these to each volume server directly:
 curl -v -X DELETE http://images12.server.com:8072/8,01a29f06bc008de6_3?type=replicate
One of them should show some error. Please post each individual result here.

**Comment by fedotxxl** [comment]
No messages - I checked stdout and weed.INFO log. Should it work for 0.69?

**Comment by chrislusf** [comment]
Maybe just paste here the output for the two calls to delete.

**Comment by fedotxxl** [comment]
```
curl -v -X DELETE http://127.0.0.1:8072/8,01a29f06bc008de6_3?type=replicate
* About to connect() to 127.0.0.1 port 8072 (#0)
*   Trying 127.0.0.1... connected
* Connected to 127.0.0.1 (127.0.0.1) port 8072 (#0)
> DELETE /8,01a29f06bc008de6_3?type=replicate HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.16.2.3 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: 127.0.0.1:8072
> Accept: */*
> 
< HTTP/1.1 500 Internal Server Error
< Content-Type: application/json
< Date: Fri, 06 May 2016 13:31:18 GMT
< Content-Length: 28
< 
* Connection #0 to host 127.0.0.1 left intact
* Closing connection #0
{"error":"Deletion Failed."}
```

```
curl -v -X DELETE http://127.0.0.1:8073/8,01a29f06bc008de6_3?type=replicate
* About to connect() to 127.0.0.1 port 8073 (#0)
*   Trying 127.0.0.1... connected
* Connected to 127.0.0.1 (127.0.0.1) port 8073 (#0)
> DELETE /8,01a29f06bc008de6_3?type=replicate HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.16.2.3 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: 127.0.0.1:8073
> Accept: */*
> 
< HTTP/1.1 500 Internal Server Error
< Content-Type: application/json
< Date: Fri, 06 May 2016 13:31:30 GMT
< Content-Length: 28
< 
* Connection #0 to host 127.0.0.1 left intact
* Closing connection #0
{"error":"Deletion Failed."}
```

**Comment by chrislusf** [comment]
Still relevent?

**Comment by stepanbujnak** [comment]
What's the status of this? I noticed I've been getting tons of `500 Internal Server Error` when deleting a file. I use the same replication `001`. It seems that the file is deleted (getting 404 when requesting it again) but 500 is returned either way.

**Comment by chrislusf** [comment]
the error message now should contain the actual error now.
```
fmt.Errorf("Deletion Failed: %v", err)
```
