### ISSUE TITLE
2.86 - needs fsck to drop missing filer listings from filers

### ISSUE THREAD

**Issue by Radtoo** [chrislusf/seaweedfs#2605]
In Seaweedfs 2.86 (linux 8000GB amd64) you can use "weed shell" "volume.fsck -findMissingChunksInFiler". It detects missing files from volumes that are listed in the filers. Breaking volume .dat files in some way will generally result in some or a lot of files getting listed there.

But while this command can certainly find problems, it does not seem capable of fixing - removing entries from filers that were found to be missing from volumes. The missing files remain listed and produce various errors on attempted access depending on what accesses them through what method. On FUSE mounts various software will terminate on hitting an error like this, it's an unexpected type of I/O error.

I am thinking command_volume_fsck.go could use some kind of pendant to "-reallyDeleteFromVolume" for use with "-findMissingChunksInFiler" to just tell filer servers they should remove the detected entries from filers.

**Comment by Radtoo** [comment]
I started trying but did not get very far. I hit the question how to sanely get a handle on the live filer(s), whether to use filer.doDeleteFileIds to handle the deletions, whether item.fileKey is a reliable identifier or if the paths should be used, and such.

If you too are interested in fixing this, maybe you can trivially see what could be added here?
https://github.com/Radtoo/seaweedfs/blob/f2d71a22b5237432c1ee92b9aa327adff9a08ef1/weed/shell/command_volume_fsck.go#L399

**Comment by chrislusf** [comment]
The original intention was to just print out the affected files, which can be deleted by some other tools. For example, a simple shell script to go through them and send http delete requests.

**Comment by chrislusf** [comment]
One file with multiple chunks will show up multiple times. So there would need another step to dedup.

This can be trivially done via some linux shell scripts. We can add an option to output the list of files to a file. And let the user to send http delete requests.

**Comment by Radtoo** [comment]
>  For example, a simple shell script to go through them and send http delete requests.

This is harder than expected even now that you pointed at HTTP delete requests. After disabling JWT, I tried sending "curl -vX DELETE http://ip:port/volume,id" with the same volume,id as in "volume.fsck -findMissingChunksInFiler".

Nothing changes regardless if this is sent to a master (permanent redirect 308), volume (not found 404) or filer (200 OK - but it's OK in pretty much all instances).

Is it simply the wrong command to send? What would you use to instruct a filer to delete a record?

> The original intention was to just print out the affected files, which can be deleted by some other tools.

From this experience just now, I really think having the fsck code to drop filer entries and restore integrity would be a large advantage. I hit quite a few dead ends.

**Comment by chrislusf** [comment]
Use the filer URL to delete. `curl -X DELETE http://filer:port/path/to/the/file`

**Comment by Radtoo** [comment]
When the filenames are very simple, this seems to work. As you observed it would still be simpler to work off a list of identifiers saved into a file, but it can be done.

When filenames are normal complexity "user choice" with whitespace, lots of special characters like - " ' # ; various UTF and so on, it does not. 'curl: (3) URL using bad/illegal format or missing URL'.  

An additional URL encoder is now needed even just for the HTTP request. Unfortunately something simple like curl -G -vX DELETE --data-urlencode "/path/to/data" http://filer:port` does not seem to work, the encoding is slightly different (whitespaces are + for example, it doesn't work) and the URL comes with a "?" prefix anyhow which seaweedfs also does not use.

What would you do? Is there actually no way to delete via much simpler to use hash?

**Comment by chrislusf** [comment]
Seems we should just url encode the file names?

**Comment by Radtoo** [comment]
> Seems we should just url encode the file names?

Will admins really be familiar with and have URL encoder tooling capable of adjusting to what seaweedfs expects? As we can see, curl has a different encoding in mind than you did, and this will be the case for many simpler to use tools; they don't all agree exactly how it's done.

I'll also again mention that shell utilities aren't perfect either, when you have a larger data collection file names might be as bad as https://github.com/minimaxir/big-list-of-naughty-strings/blob/master/blns.txt or worse.

My impression is that it'd be _much_ better if the files could still be deleted from the filer via their volumeid,hash or just the hash... a simple alphanumerical string that can be passed via anything that speaks basic HTTP.

**Comment by chrislusf** [comment]
I mean the code here can add an url encoding https://github.com/Radtoo/seaweedfs/blob/f2d71a22b5237432c1ee92b9aa327adff9a08ef1/weed/shell/command_volume_fsck.go#L396

> the files could still be deleted from the filer via their volumeid,hash or just the hash... a simple alphanumerical string that can be passed via anything that speaks basic HTTP

This is using file id to look up a file. There are no ways to do this.

**Comment by Radtoo** [comment]
> I mean the code here can add an url encoding
I see what you mean. If you can pass this directly to common clients like curl, httpie and so on, I think that would cover most cleanups.

Or just offer to send these DELETE requests from "weed" to simply avoid string escaping/interpretation issues and such.

> This is using file id to look up a file. There are no ways to do this.
Maybe not a hash then. But I thought the filer had "fid" information, and it uniquely identifies a file? Can that not work?

**Comment by chrislusf** [comment]
Yes. Adding a HTTP delete can be a good option.

> "fid" information, and it uniquely identifies a file and filer entry

Yes, but not efficient. Need to iterate through all files to find one file.
