### ISSUE TITLE
File is always overwritten, even if it already exists

### ISSUE THREAD

**Issue by EKovtun** [chrislusf/seaweedfs#2607]
Hi, Chris. 
I didn't find your email, so I'll write here. 
I looked at the code and noticed that the file is always overwritten, despite the fact that it may already exist in the system with exactly the same name and md5 hash. 
The fact is that in the code, the file is sent for writing to the volume server, and only after that the filler checks the existence of metadata on this file (it searches for metadata by the key, which is only the full path of the file but not md5 hash). If the metadata is found, it updates them, otherwise it creates them.
What do you think? Is it correct to overwrite a file if it already exists with the same name and completely identical data? It looks like an overhead.
What do you think about it?

**Comment by ijunaid8989** [comment]
this is default behavior / intentional behavior.

**Comment by EKovtun** [comment]
> 

Won't it be an overhead? Considering that the file can be large and the network is slow

**Comment by ijunaid8989** [comment]
You are right but this is how a filesystem should work, no?

**Comment by EKovtun** [comment]
> You are right but this is how a filesystem should work, no?

Yes, but we strive for high performance. Perhaps it is worth checking the existence of the file before uploading it to the server?

**Comment by EKovtun** [comment]
However, there is a problem here that I can't solve yet. We need to somehow calculate the md5 hash of the file before uploading it to the server. Now the hash is calculated in chunks during file upload to the server.

**Comment by chrislusf** [comment]
This can be achieved via content addressing, but at the cost of introducing a bottleneck.

If the file system does not have any update and deletion, this is easy.
If not, a reference counter is needed to delete unused data.

There are some other things to worry about.

If you want to dedup by content, you can develop something else on an upper level.

**Comment by lewisl9029** [comment]
@chrislusf I'm storing a bunch of immutable, content-addressed files in filer, and currently have 2 options, afaik:

1. Check for existence with a HEAD request before sending a PUT, resulting in an extra network roundtrip of latency
2. Just send the PUT, resulting in unnecessary network traffic and disk IO to overwrite with identical data

I'd love to be able to have some way to send a PUT that aborts the transfer with some error (409?) if the file already exists, so I can avoid the latency and network traffic!

**Comment by kvtb** [comment]
Even setting readonly `fileMode` (like `0444`) does not prevent overwrite :(
