### ISSUE TITLE
Inotify after filer.sync not firing

### ISSUE THREAD

**Issue by KevinBLT** [chrislusf/seaweedfs#2608]
**Describe the bug**
Using `inotifywait -m --format '%:e %f' test` on a mounted volume
will fire when changing files on the same server.

Doing `echo "TEST" > test` will show:
```
Setting up watches.
Watches established.
OPEN 
ACCESS 
CLOSE_NOWRITE:CLOSE 
```
whereas doing `echo "from a sync target" > test`
will not show these events (the file is synchronized tho)

**System Setup**
```
weed -logdir=/var/log/seaweedfs server \
  -ip %H \
  -master.dir /var/.database/seaweedfs/meta \
  -dir /var/.storage \
  -volume.dir.idx /var/.database/seaweedfs/meta \
  -volume.index leveldbLarge \
  -filer.saveToFilerLimit 16384 \
  -filer
```

+ `weed filer.sync -a %i:8888 -b %H:8888 -isActivePassive`

- Ubuntu 21
- Weed 2.86

**Expected behavior**
Inotify should be called from the fuse mount just as local

What do you think? Or am I missing a point here?

**Comment by chrislusf** [comment]
Supporting inotify in FUSE is a common request: https://unix.stackexchange.com/questions/238956/is-there-a-way-to-use-inotify-on-remote-filesystems-specifically-webdav

When a file is updated locally, the changes go through FUSE layer, through which the events will be handled by OS kernel.

When a file is updated remotely, the changes just go into the `weed mount` directly. The changes are only "visible" when opening the file.

This feature is unlikely can be supported.

SeaweeedFS has its own change notification with gRPC API:
https://github.com/chrislusf/seaweedfs/wiki/Filer-Change-Data-Capture
