### ISSUE TITLE
[volume.check.disk] read needle blob offset EOF

### ISSUE THREAD

**Issue by kmlebedev** [chrislusf/seaweedfs#2626]
version

```
version 30GB 2.88 72700672 linux amd64
```

volume.fix.replication
```
volume 520 fast-volume-0.s3-fast-volume.service.dcix.consul:8080 has 2119 entries, fast-volume-7.s3-fast-volume.service.dck12.consul:8080 missed 1 entries
grpc_port:18080 volume 520: rpc error: code = Unknown desc = read needle blob offset 1345589040 size 407282: EOF
```

many errors
```
kubectl logs fast-cronjob-27393600-4k795 | grep 'read needle blob offset' | wc -l
      90
```

https://github.com/chrislusf/seaweedfs/issues/2268

Looks like it started after https://github.com/chrislusf/seaweedfs/commit/107a4884a8374540112ac018fac55f295d0597d4

**Comment by chrislusf** [comment]
Did reverting 107a488 help?

**Comment by kmlebedev** [comment]
> Did reverting [107a488](https://github.com/chrislusf/seaweedfs/commit/107a4884a8374540112ac018fac55f295d0597d4) help?
 Yes, reverting didn't help.

**Comment by chrislusf** [comment]
> volume 520 fast-volume-0.s3-fast-volume.service.dcix.consul:8080 has 2119 entries, fast-volume-7.s3-fast-volume.service.dck12.consul:8080 missed 1 entries
> grpc_port:18080 volume 520: rpc error: code = Unknown desc = read needle blob offset 1345589040 size 407282: EOF

This is reading file 520.dat on `fast-volume-0.s3-fast-volume.service.dcix.consul:8080`. What is the size of the 520.dat file?
Seems it is smaller than `1345589040`? Please let me know the size of `520.dat` and also share the index file 520.idx. I want to check the idx file content to see why it is reading at offset `1345589040`.

**Comment by kmlebedev** [comment]
> This is reading file 520.dat on `fast-volume-0.s3-fast-volume.service.dcix.consul:8080`. What is the size of the 520.dat file? Seems it is smaller than `1345589040`?

Is bigger 

```
kubectl exec -it fast-volume-0 -- sh -c 'ls -l /data/*520*'
-rw-rw-r--    1 root     99       1407536760 Jan 31 12:26 /data/recognition_520.dat
-rw-rw-r--    1 root     99           48304 Jan 31 12:26 /data/recognition_520.idx
-rw-rw-r--    1 root     99              57 Aug 17 12:14 /data/recognition_520.vif
 kubectl exec -it fast-volume-7 -- sh -c 'ls -l /data/*520*'
-rw-rw-r--    1 root     99       1413239096 Jan 31 12:26 /data/recognition_520.dat
-rw-rw-r--    1 root     99           48512 Jan 31 12:26 /data/recognition_520.idx
-rw-rw-r--    1 root     99              57 Aug 18 11:15 /data/recognition_520.vif
```
