### ISSUE TITLE
Mismatching signatures when using presigned URLs

### ISSUE THREAD

**Issue by mbuczko** [chrislusf/seaweedfs#2638]
Hey, I'm trying to follow the [presign url guide](https://github.com/chrislusf/seaweedfs/wiki/AWS-CLI-with-SeaweedFS#presigned-url) but each use of presigned URL ends up with:
```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><Resource>/assets/blah.jpg</Resource><RequestId>1644010465937989170</RequestId><Key>blah.jpg</Key><BucketName>assets</BucketName></Error>
```

I'm pretty sure that credentials are valid (eg. I'm able to list the bucket) and s3 configuration looks quite trivial:
```
{
  "identities": [
    {
      "name": "admin",
      "credentials": [
        {
          "accessKey": "xxx",
          "secretKey": "xxx"
        }
      ],
      "actions": [
        "Admin",
        "Read",
        "List",
        "Tagging",
        "Write"
      ]
    }
  ]
}
```

Any hint what may cause that inconsistency between the signature generated by `aws` cli and the one that seaweed calculates? I thought it might be a difference in regions, so I set region to `us-east-1` in my aws config, but unfortunately that didn't help.

seaweed version: 2.75

**Comment by mbuczko** [comment]
I have just updated seaweed to 2.88 and seems like everything started working - both GET and PUT requests.

I'm sorry for the noise :)

**Comment by chrislusf** [comment]
Make sure you only use one s3 configuration. Either from CLI or from `s3.configure`, but not mixed.
