### ISSUE TITLE
anyone who using failover and replication configuration?

### ISSUE THREAD

**Issue by breaklee** [chrislusf/seaweedfs#264]
i didn't understand about failover architecture and replication.
if there are 3 masters.
```
192.168.2.1:9333
192.168.2.2:9333
192.168.2.3:9333
```
i think there should be only one gateway to clustering 3 master servers.
which masters to connect from client?

and then suppose that client connected to 192.168.2.1:9333.
if that master is down, how client know other elected master server?

**Comment by chrislusf** [comment]
Pick anyone of them. If the one you use failed, pick another one from the
rest.
