### ISSUE TITLE
[store] failed to write to local disk: invalid argument	

### ISSUE THREAD

**Issue by kmlebedev** [chrislusf/seaweedfs#2648]
**Describe the bug**

logs
```
upload_content.go:109] uploading to http://fast-volume-6.s3-fast-volume.service.dcdp.consul:8080/825,01366342ecebf5fc: unmarshalled error http://fast-volume-6.s3-fast-volume.service.dcdp.consul:8080/825,01366342ecebf5fc: failed to write to local disk: invalid argument | fast-api-658d59f67b-vd9ct
store_replicate.go:48] failed to write to local disk: invalid argument | fast-volume-6
common.go:69] response method:POST URL:/825,01366342ecebf5fc with httpStatus:500 and JSON:{"name":"0006.part","size":5242880,"error":"failed to write to local disk: invalid argument","eTag":"971972b3"} | fast-volume-6
```

**System Setup**
```
2.88
```

**Comment by kmlebedev** [comment]
@chrislusf  I found where the error is printed https://github.com/chrislusf/seaweedfs/blob/433fde4b186a8244aabeb8659bb901a89b56e213/weed/topology/store_replicate.go#L49
but I did not find where the error "invalid argument" is returned from

**Comment by chrislusf** [comment]
Is the write request using `fsync`?

**Comment by kmlebedev** [comment]
> Is the write request using `fsync`?

No
```
W0208 09:59:31     1 upload_content.go:109] uploading to http://fast-volume-4.s3-fast-volume.service.dcdp.consul:8080/306,013669791416dd6d: unmarshalled error http://fast-volume-4.s3-fast-volume.service.dcdp.consul:8080/306,013669791416dd6d: failed to write to replicas for volume 306: [fast-volume-6.s3-fast-volume.service.dcix.consul:8080]: unmarshalled error http://fast-volume-6.s3-fast-volume.service.dcix.consul:8080/306,013669791416dd6d?ts=1644314370&ttl=&type=replicate: failed to write to local disk: invalid argument
```

**Comment by chrislusf** [comment]
does it happen often? can not tell, unless it is reproducible.

**Comment by kmlebedev** [comment]
> does it happen often? can not tell, unless it is reproducible.

found 963 bugs in 5 days
and all about one volume 306(registry) and often about the same file

now I'm trying to find the filename by id

**Comment by kmlebedev** [comment]
@chrislusf How to enable back synchronous writing in all replicas?

**Comment by zhuqunzhou** [comment]
I also encountered this problem,how did you solve the problem?

<img width="1056" alt="image" src="https://user-images.githubusercontent.com/10348876/157661526-7b17f410-23e5-43d5-bd3e-cf8b0a4570bf.png">
<img width="1384" alt="image" src="https://user-images.githubusercontent.com/10348876/157661608-86735715-b472-4f70-9eb8-1ce4743cf80d.png">

**Comment by kmlebedev** [comment]
Next https://github.com/chrislusf/seaweedfs/issues/2658

**Comment by kmlebedev** [comment]
> I also encountered this problem,how did you solve the problem?

Now this problem should not interfere with data replication. 
And I understand the reason here https://github.com/chrislusf/seaweedfs/issues/2658

**Comment by kmlebedev** [comment]
Shot together with https://github.com/chrislusf/seaweedfs/issues/2757 
```
3.14
```

```
upload_content.go:114] uploading to http://fast-volume-7:8080/1827,05f983b09f8aba26?ts=1658301141&ttl=&type=replicate: unmarshalled error http://fast-volume-7.s3-fast-volume.service.dcix.consul:8080/1827,05f983b09f8aba26?ts=1658301141&ttl=&type=replicate: failed to write to local disk: invalid argument
store_replicate.go:50] failed to write to local disk: invalid argument
```

**Comment by NyaMisty** [comment]
Still occurs in version 3.64
