### ISSUE TITLE
When out of Beta?

### ISSUE THREAD

**Issue by lucevers** [chrislusf/seaweedfs#265]
Important for production, when  will be seaweedfs out of Beta?

**Comment by chrislusf** [comment]
Currently I can easily mark it as out of beta, but I do not have a good way to publish binaries for all the platforms. Need some help to maybe use travis to generate the binaries.

**Comment by ClaudiuPID** [comment]
Maybe a service like: https://en.opensuse.org/openSUSE:Build_Service /  http://openbuildservice.org/  would be of interest.
Or you plan on having your own build server?

**Comment by chrislusf** [comment]
Any public free build service should be fine. Windows, Mac should also be supported.

**Comment by tgulacsi** [comment]
https://github.com/laher/goxc/blob/master/README.md ?
Wercker and Travis does not support Windows.

**Comment by chrislusf** [comment]
Actually I am releasing with goxc already. Just need to automate this.

**Comment by lucevers** [comment]
Thanks!

**Comment by fedotxxl** [comment]
is it done? is 0.70 compatible with 0.69?

**Comment by chrislusf** [comment]
automatic travis release to github is configured yesterday.
