### ISSUE TITLE
how to weed mount accurately?

### ISSUE THREAD

**Issue by minminmsn** [chrislusf/seaweedfs#266]
1,weed mount  
weed mount -filer="localhost:8888" -dir="/data/seaweedclient"  -debug=true
This is SeaweedFS version 0.70 beta linux amd64
2,check it
ll /data
d????????? ? ?             ?                  ?            ? seaweedclient

why the owner and  group of /data/seaweedclient  is "?" ?

**Comment by chrislusf** [comment]
I do not use it very often. Maybe a bug from the way I use the library.

https://github.com/chrislusf/seaweedfs/blob/master/go/weed/mount_std.go#L25

**Comment by chrislusf** [comment]
The API used is here:

https://github.com/bazil/fuse/blob/master/fuse.go#L157

Seems just need to add the options.
