### ISSUE TITLE
[store]failed to write to local disk

### ISSUE THREAD

**Issue by zhuqunzhou** [chrislusf/seaweedfs#2660]
**Describe the bug**
failed to write data sometimes.

**Benchmark command**
`warp put --host 172.24.10.133:8333 --duration=20m --obj.size 250K --concurrent 30`

**master logs**
<pre><code>
I0211 17:47:51 65915 volume_layout.go:373] Volume 64 becomes unwritable
volume 64 processed 1090519040 bytes
volume 64 processed 1226833920 bytes
volume 64 processed 1363148800 bytes
volume 64 processed 1499463680 bytes
volume 64 processed 1635778560 bytes
volume 64 processed 1772093440 bytes
2022/02/11 17:47:52 tailing volume 64 from 172.24.10.131:8082 to 172.24.10.131:8088
2022/02/11 17:48:06 deleting volume 64 from 172.24.10.131:8082
2022/02/11 17:48:06 moved volume 64 from 172.24.10.131:8082 to 172.24.10.131:8088
hdd 0.02 0.04:0.02        moving  volume warp-benchmark-bucket_67 172.24.10.131:8082 => 172.24.10.131:8083
2022/02/11 17:48:06 copying volume 67 from 172.24.10.131:8082 to 172.24.10.131:8083
I0211 17:48:06 65915 topology.go:209] removing volume info: Id:64, Size:0, ReplicaPlacement:010, Collection:warp-benchmark-bucket, Version:3, FileCount:0, DeleteCount:0, DeletedByteCount:0, ReadOnly:false from 172.24.10.131:8082
I0211 17:48:06 65915 volume_layout.go:386] Volume 64 becomes writable
volume 67 processed 136314880 bytes
volume 67 processed 272629760 bytes
volume 67 processed 408944640 bytes
volume 67 processed 545259520 bytes
volume 67 processed 681574400 bytes
volume 67 processed 817889280 bytes
volume 67 processed 954204160 bytes
volume 67 processed 1090519040 bytes
volume 67 processed 1226833920 bytes
volume 67 processed 1363148800 bytes
volume 67 processed 1499463680 bytes
volume 67 processed 1635778560 bytes
volume 67 processed 1772093440 bytes
volume 67 processed 1908408320 bytes
</code></pre>

**filer logs**
<pre><code>
W0211 17:47:52 65744 upload_content.go:109] uploading to http://172.24.10.132:8082/64,48a0593ccfccaa: unmarshalled error http://172.24.10.132:8082/64,48a0593ccfccaa: failed to write to replicas for volume 64: [172.24.10.131:8082]: unmarshalled error http://172.24.10.131:8082/64,48a0593ccfccaa?ts=1644572871&ttl=&type=replicate: failed to write to local disk: volume 64 is read only
W0211 17:47:52 65744 upload_content.go:109] uploading to http://172.24.10.132:8082/64,48a06483c820bc: unmarshalled error http://172.24.10.132:8082/64,48a06483c820bc: failed to write to replicas for volume 64: [172.24.10.131:8082]: unmarshalled error http://172.24.10.131:8082/64,48a06483c820bc?ts=1644572871&ttl=&type=replicate: failed to write to local disk: volume 64 is read only
W0211 17:47:52 65744 upload_content.go:109] uploading to http://172.24.10.132:8082/64,48a06bebe0d5bd: unmarshalled error http://172.24.10.132:8082/64,48a06bebe0d5bd: failed to write to replicas for volume 64: [172.24.10.131:8082]: unmarshalled error http://172.24.10.131:8082/64,48a06bebe0d5bd?ts=1644572871&ttl=&type=replicate: failed to write to local disk: volume 64 is read only
W0211 17:48:06 65744 upload_content.go:109] uploading to http://172.24.10.131:8082/67,491ec73b9c1748: unmarshalled error http://172.24.10.131:8082/67,491ec73b9c1748: failed to write to local disk: volume 67 is read only
W0211 17:48:06 65744 upload_content.go:109] uploading to http://172.24.10.131:8082/67,491ed480d2f67a: unmarshalled error http://172.24.10.131:8082/67,491ed480d2f67a: failed to write to local disk: volume 67 is read only
W0211 17:48:06 65744 upload_content.go:109] uploading to http://172.24.10.131:8082/67,491ed39b78861d: unmarshalled error http://172.24.10.131:8082/67,491ed39b78861d: failed to write to local disk: volume 67 is read only
W0211 17:48:06 65744 upload_content.go:109] uploading to http://172.24.10.131:8082/67,491ef06e364024: unmarshalled error http://172.24.10.131:8082/67,491ef06e364024: failed to write to local disk: volume 67 is read only
W0211 17:48:06 65744 upload_content.go:109] uploading to http://172.24.10.131:8082/67,491f1306e12840: unmarshalled error http://172.24.10.131:8082/67,491f1306e12840: failed to write to local disk: volume 67 is read only
W0211 17:48:06 65744 upload_content.go:109] uploading to http://172.24.10.131:8082/67,491f1bee2f92e4: unmarshalled error http://172.24.10.131:8082/67,491f1bee2f92e4: failed to write to local disk: volume 67 is read only
W0211 17:48:07 65744 upload_content.go:109] uploading to http://172.24.10.131:8082/67,491ec73b9c1748: unmarshalled error http://172.24.10.131:8082/67,491ec73b9c1748: failed to write to local disk: volume 67 is read only
W0211 17:48:07 65744 upload_content.go:109] uploading to http://172.24.10.131:8082/67,491ed39b78861d: unmarshalled error http://172.24.10.131:8082/67,491ed39b78861d: failed to write to local disk: volume 67 is read only
W0211 17:48:07 65744 upload_content.go:109] uploading to http://172.24.10.131:8082/67,491ed480d2f67a: unmarshalled error http://172.24.10.131:8082/67,491ed480d2f67a: failed to write to local disk: volume 67 is read only
</code></pre>

**Version**
`2.87`

**Comment by chrislusf** [comment]
there are already retries.
