### ISSUE TITLE
weed shell: volume.delete syntax changed?

### ISSUE THREAD

**Issue by peedy2495** [chrislusf/seaweedfs#2662]
Hello, I'm trying to delete some Volumes, but it doesn't work:

One example Volume:  
```curl "http://localhost:9333/dir/lookup?volumeId=2&pretty=y"
{
  "volumeOrFileId": "2",
  "locations": [
    {
      "url": "192.168.0.201:9081",
      "publicUrl": "192.168.0.201:9081"
    },
    {
      "url": "192.168.0.202:9081",
      "publicUrl": "192.168.0.202:9081"
    }
  ]
}
```

Ok, let's try it ...   
`volume.delete 192.168.0.201:9081 2`

Response:  
`error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: missing address"`

Any hints ?

**Comment by kmlebedev** [comment]
See help volume.delete -h
And use params -node and -id

**Comment by peedy2495** [comment]
Check! -h was not known for further syntax-spelling :+1:
