### ISSUE TITLE
Compile :: cache

### ISSUE THREAD

**Issue by Davidx7** [chrislusf/seaweedfs#267]
Small issue:

I'm trying to build a new UI for `seaweed` and will most likely publish it as well, to adapt is as you wish, but every time I compile, templates are not changing.

`/go/weed/weed_server/master_ui/`

`/go/weed/weed_server/volume_master_ui/`

Any clear cache method before the make file is active and compiling?

**Comment by chrislusf** [comment]
There are no cache. But you need to re-compile and restart.

Chris

**Comment by alexanderk23** [comment]
+1. It seems that when compiling, Go checks out and uses another copy of this repository (stored in GOPATH), so all local changes are meaningless and recompiling won't do anything.

**Comment by Davidx7** [comment]
Yes @alexanderk23 Same here! 
Can you check that @chrislusf  ?
