### ISSUE TITLE
how can i clustering?

### ISSUE THREAD

**Issue by breaklee** [chrislusf/seaweedfs#268]
i have two physical servers.
and i want to install master and volmue server per each server.

and file server runs each sever.
file server connect to localhost master server.
and they can share there files and id's etc.

how can i configure these settings?

or is it possible to configure weed?

**Comment by chrislusf** [comment]
For 2 servers, I would recommend you have a volume server on each box, and have one master and filer on one of the boxes.

**Comment by breaklee** [comment]
hi. @chrislusf 

thanks for recommendation.
i want to auto replication also.

if the server ( master and filer ) has going down,
how can we use seaweed function?
can i use auto failover ?
(like redis sentinel )

and there(shutdowned server) are also some part of volume server. ( maybe piece of files )
if some client request files saved in down server,
how can i serve right files?

**Comment by chrislusf** [comment]
Then you would need 3 servers, each with master, filer, volume servers
installed. And you would need a shared key-value store, such as redis or
cassandra, to store filer metadata.

And use replication 001.

Chris

**Comment by breaklee** [comment]
@chrislusf 

i didn't understand what filers do.
each volume server doesn't know about other masters installed on different server right?
so filer(distributed filer) needed?

and save/get files using filer.

if i using filer, and can i get some files saved on other volumes ?

**Comment by chrislusf** [comment]
Please read these:
https://github.com/chrislusf/seaweedfs/wiki/Failover-Master-Server
https://github.com/chrislusf/seaweedfs/wiki/Distributed-Filer
