### ISSUE TITLE
Master Free volumes not showing actual Free volumes in Volumeservers

### ISSUE THREAD

**Issue by roflmao** [chrislusf/seaweedfs#2699]
**Describe the bug**
seaweed master reports wrong number of Free volumes

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
```
/usr/local/bin/weed -logtostderr -v=1 master -mdir=/mnt/data-small01/meta -ip=10.2.14.30 -defaultReplication=010 -volumePreallocate -volumeSizeLimitMB 30000 -garbageThreshold 0.1 -peers=10.2.14.30:9333,10.2.14.31:9333,10.2.14.32:9333,10.2.14.33:9333,10.2.14.34:9333
/usr/local/bin/weed -logtostderr -v=1 volume -pprof -concurrentUploadLimitMB 99999 -concurrentDownloadLimitMB 99999 -compactionMBps=500 -port=8080 -mserver=10.2.14.30:9333,10.2.14.31:9333,10.2.14.32:9333,10.2.14.33:9333,10.2.14.34:9333 -dir=/mnt/data-small01/data,/mnt/data-small02/data -index leveldb -max 0,0 -ip 10.2.14.30 -rack dn-402 -dataCenter sw-073
```
- OS version
```Ubuntu 20.04```
- output of `weed version`
```version 30GB 2.63 3a3189c linux amd64```

**Expected behavior**
Number of free volumes should be a total of Volume Servers Max-Used
Free from master shows 318
Manual count is 11 with Max-Used for all volume servers

**Relevant info**
/dir/status from master:
https://gist.githubusercontent.com/roflmao/92b415324d3962f324fe8bc2081206c9/raw/2d0c539d74b6becd87e83133383c1e79dcd4df4c/gistfile0.txt

**Comment by chrislusf** [comment]
https://github.com/chrislusf/seaweedfs/blob/master/weed/topology/disk.go#L111
```
	freeVolumeSlotCount := a.maxVolumeCount + a.remoteVolumeCount - a.volumeCount
```

do you have any remote volume?

**Comment by roflmao** [comment]
@chrislusf No remote volumes
