### ISSUE TITLE
Add volume server

### ISSUE THREAD

**Issue by hczzll123** [chrislusf/seaweedfs#2707]
After add new volume server to expand capacity，Do I need to perform other command operations？
关于扩容后（启动了两个新的volume）还需要执行其它命令吗？ 因为我看新起的volume一直没有文件写进去。

**Comment by chrislusf** [comment]
you can run "volume.balance -force" in "weed shell".

**Comment by hczzll123** [comment]
> you can run "volume.balance -force" in "weed shell".

thank you for your reply , if i do not run the command, Will the cluster balance automatically? @chrislusf

**Comment by chrislusf** [comment]
by default it will run the balance automatically.
