### ISSUE TITLE
SeaweedFS as an image hosting backend

### ISSUE THREAD

**Issue by tdicks** [chrislusf/seaweedfs#271]
I host an image uploading site called cubeupload.com and we run on one main server with a ton of hard disk space, plus a few Varnish caches. As the site grows, we have to continually migrate to another content server with even more capacity.

I'd like to ask if SeaweedFS would be the answer to our troubles. We're currently hosting around 4 million images which take up around 2.1TB of disk. If we migrated to SeaweedFS, would it be reasonable to just add additional volume servers to increase the overall storage available?

**Comment by mosic** [comment]
I'm also interested in this question. I was planning on trying SeaweedFS for storing hundreds of millions of mostly small (30-300KB) images. We currently store about 50TB of data on a 90TB server and it would be ideal if we could just continue adding more servers.

Also an estimate of the expected read/write performance would be appreciated.

**Comment by marcoherbst** [comment]
To follow up on @mosic 's comment, our application is www.evercam.io , we're storing images from IP Cameras, typically hundreds of images per second (write) and pretty low read rates. We'd be looking for x2 or x3 replication. Have previously used S3.

**Comment by chrislusf** [comment]
Please try seaweedfs api with a few images, and you will understand why it can scale.

Go with single master and single filer server first. Add volume servers when storage is not enough.
