### ISSUE TITLE
set acl on replication upload

### ISSUE THREAD

**Issue by gfxlabs** [chrislusf/seaweedfs#2714]
**Describe the bug**
i use digitalocean spaces. they do not support a default upload acl for the bucket. you can set an acl when you upload the file, but seaweedfs does not support that.

i needed to use it, so i just patched it in here and uploaded an image to docker and it seems to be working

https://github.com/gfx-labs/seaweedfs/commit/2a2e72f8244c52f3e75a0e7ec738c7c20d262754

not sure if this is a feature that other people might need, it would be nice if i didn't need to patch this in every update, but if not many others need it i'm fine with doing that.

**Comment by chrislusf** [comment]
thanks! could you please make a PR?

btw: the text format seems different. Better not reformatting that much to make the PR easier to read.

**Comment by elee1766** [comment]
yeah, i'll set up a pr without the formatting change 👍

**Comment by gfxlabs** [comment]
https://github.com/chrislusf/seaweedfs/pull/2715
