### ISSUE TITLE
Java Send Request with JWT Token

### ISSUE THREAD

**Issue by TheSerumDev** [chrislusf/seaweedfs#2736]
Hello.

I followed the steps in your wiki (https://github.com/chrislusf/seaweedfs/wiki/Run-Blob-Storage-on-Public-Internet) it works as well as, but my question is now how I can sent the jwt token in each request with yours java library. I found nothing in the "FilerClient" class.

**Comment by chrislusf** [comment]
https://github.com/chrislusf/seaweedfs/blob/master/other/java/client/src/main/java/seaweedfs/client/SeaweedWrite.java#L80
