### ISSUE TITLE
Confirmation on how can we restore files from dir when using only Master/Volume

### ISSUE THREAD

**Issue by jereloh** [chrislusf/seaweedfs#2739]
I'm using only Master/volume no filer and storing individual generated links into a db tagged to a user. I'm planning to use this in production and to backup daily, in the event there is a need to recover files from backup, can I just spin up a weed instance to access the backup files? 

Will the link path e.g."3,01637037d6 " change ? (in http://localhost:8080/3,01637037d6). My understanding is that only ip/port will change as it will be set up in another environment. (I will still be able to access this file using http://newipaddr:port/"3,01637037d6 )

Note: I've tested this myself and notice no change (able to access eg.http://localhost:8080/3,01637037d6 and view similar files in volume using ./weed export from both machine) when i copy all dir files (.vif, .dat, .idx) into another machine and spinning this other weed instance. 

I'm looking for confirmation as I did not see much documentation about this.

**Comment by chrislusf** [comment]
This is correct.

**Comment by kmlebedev** [comment]
@jereloh How do you plan to use it in production if there is no guarantee that, for example, volume 3 will not be moved to another server volume?

**Comment by kmlebedev** [comment]
It seems that a separate http server will be required to generate the link via x-accel-redirect
