### ISSUE TITLE
是否有可能在weed filer模式上传文件和浏览文件列表时的返回信息中增加volume url值，将会帮助很大

### ISSUE THREAD

**Issue by javadevelopuser** [chrislusf/seaweedfs#274]
你好！

我们准备在项目中使用weedfs，考虑采用filer模式运行，文件上传测试过程如下：
上传bar.js文件至http://127.0.0.1:8888/test/
程序返回日志：
2016-03-31 16:38:05 INFO  WeedFSClientTest1  (WeedFSClientTest1.java:166) - - {"name":"sitemapindex.xml","size":32675}

能否把返回值改成这样的形式： {"name":"bar.js","size":32675,"fid":"2,125de60a06",**"url":"127.0.0.1:8080","publicUrl":"localhost:8080"**}
上文中加粗文字部分为希望新增字段值，若存在这几个字段值，则可以通过url+fid进行更新等操作。

在浏览器访问http://127.0.0.1:8888/test/时，返回值：{"Directory":"/test/","Files":[{"name":"bar.js","fid":"2,026605fd23"}]}
希望也能加上上文中的加粗文字部分字段值，方便后续程序持续处理。

非常感谢！

**Comment by chrislusf** [comment]
This is a mapping from vid to url. Only the master has the information. The client side should just cache it.

**Comment by 420303865** [comment]
希望在filer模式中 上传成功后 同时返回 fid
{"name":"bar.js","size":32675,"fid":"2,125de60a06"} 

因为有些时候我们可能会通过fid来访问 
比如 在filer模式下 不支持图片缩略图模式 这个时候就可以通过 fid 访问来实现

**Comment by chrislusf** [comment]
好，加上了 fid 和 url.

**Comment by 420303865** [comment]
太好了 谢谢

**Comment by zllkyo** [comment]
> 好，加上了 fid 和 url.
我使用2.0.5版本在windows上传完没有加fid和url,是版本问题吗？

**Comment by chrislusf** [comment]
removed. see https://github.com/chrislusf/seaweedfs/issues/1554
