### ISSUE TITLE
How to treat with invalid utf-8 characters in path?

### ISSUE THREAD

**Issue by banjiaojuhao** [chrislusf/seaweedfs#2743]
https://github.com/chrislusf/seaweedfs/blob/197ade6aebeea1316a757156cb7d6249bd102bd9/weed/util/fullpath.go#L15-L25
Should seaweed return error or save file into the directory `/?/?/` when user upload like below?
`curl -F file=@test.txt http://localhost:8888/%B2%E2%CA%D4/%B2%E2%CA%D4/`

**Comment by chrislusf** [comment]
we can add a check before creating the entry.
