### ISSUE TITLE
Add support to contabo object storage

### ISSUE THREAD

**Issue by SadmiB** [chrislusf/seaweedfs#2746]
Recently contabo launched their [object storage](https://contabo.com/en/object-storage/) and it sounds a good candidate to opt for, so it will be great to be supported by seaweed

**Comment by ijunaid8989** [comment]
@SadmiB thanks for posting, a PR is always welcome :)

**Comment by ddorian** [comment]
From their website, it should work:::

S3-compatible API

Our Object Storage is S3 compatible. You can use S3 API features like versioning or locking as needed.

**Comment by chrislusf** [comment]
@SadmiB add one similar to one of these, if it needs some special requirements. https://github.com/chrislusf/seaweedfs/tree/master/weed/remote_storage/s3

Seems only available in Europe as of now.
