### ISSUE TITLE
Does Erasure Coding negatively impact availability on clusters with few servers?

### ISSUE THREAD

**Issue by tobiasmuehl** [chrislusf/seaweedfs#2751]
Seaweed uses RS(10,4) for erasure coding. Let's say I have a file stored with `010` replication (1 copy on different rack) in a cluster that only has 2 volume servers, each in a different rack. If 1 volume server goes down, file is still available. As soon as the volume is sealed and Erasure coding starts, shards will be split between 2 volume servers. If 1 volume server goes down, more than 4 shards are missing and the file is not available anymore.

Am I getting this right?

**Comment by chrislusf** [comment]
Correct. If not enough volume servers, EC is not good.

**Comment by tobiasmuehl** [comment]
Can EC be disabled altogether for small clusters? Can it be turned on later as cluster grows larger?

**Comment by chrislusf** [comment]
If the admin script "ec.encode" is not run, no EC will happen.
