### ISSUE TITLE
Configurable configuration dir

### ISSUE THREAD

**Issue by nivekuil** [chrislusf/seaweedfs#2753]
I'd like to use podman secrets to manage the `filer.toml`, but the secret files are always mounted under `/run/secret/...` and there seems to be no way to add a config path, looking at https://github.com/chrislusf/seaweedfs/blob/dce1f02c9efcf78f05e7f81f3cc116e594591642/weed/util/config.go#L20-L27

**Comment by chrislusf** [comment]
Could you get around this by creating a link?

**Comment by nivekuil** [comment]
It would defeat the point of the secret I think. It's supposed to have special treatment to avoid having its contents leaked by other tools.

Mar 12, 2022 11:27:33 PM Chris Lu ***@***.***>:

**Comment by chrislusf** [comment]
`/usr/local/etc/seaweedfs/` was added just for bsd systems.

Adding one more is just getting too much. Need to switch to a dynamic way.

**Comment by danlsgiga** [comment]
Had the same "problem" with Nomad... To overcome it I defined the `work_dir` to where `filer.toml` is located.

But I agree with @nivekuil here... it would be great if we had a `-config` where we can define where to look for the `filer.toml` file

**Comment by chrislusf** [comment]
Maybe we can use an env variable for that. It is the easiest way, but sort of a hack.

A `-configDir` would be better. Need to add to almost all commands though.

Any better ideas?

**Comment by nivekuil** [comment]
> A `-configDir` would be better. Need to add to almost all commands though.

Maybe this could be part of the main command like `-v` if you prefer not to add it to subcommands?

**Comment by chrislusf** [comment]
@nivekuil Thanks for the nice suggestion! It's great that I asked. :)

Added a "-conf_dir" option.
