### ISSUE TITLE
[bug:volume] stuck replication on all volume servers (critical)

### ISSUE THREAD

**Issue by kmlebedev** [chrislusf/seaweedfs#2755]
**Describe the bug**

All file upload stopped due to volume replication
There may have been network problems

logs without  errors

many
```
s3-fast-api/harbor-registry/docker/registry/v2/repositories/proxy_docker-elastic-co/elasticsearch/elasticsearch/_uploads/c46580d0-225a-4549-a666-768f15856839/startedat | 504 | 60.001, 60.001, 60.000 | PUT
```

after one  volume-7 shutdown
```
upload_content.go:109] uploading to http://fast-volume-7.s3:8080/1259,0145c8e8c2a09536?ts=1647241384&ttl=&type=replicate: upload 47854270 108 bytes to http://fast-volume-7.s3:8080/1259,0145c8e8c2a09536?ts=1647241384&ttl=&type=replicate: Post "http://fast-volume-7.s3:8080/1259,0145c8e8c2a09536?ts=1647241384&ttl=&type=replicate": EOF
```

debug log from api
```
I0315 10:12:51     1 s3api_object_handlers.go:55] PutObjectHandler logs/dcdp/indices/ZABdOyHIRVqT0WKXw5GcZQ/2/__Y3d4e0C2THW7s_ma1UpErQ
I0315 10:12:51     1 filer_server_handlers_write_upload.go:51] received byte buffer 1
```

**System Setup**
```
2.90
```
![Снимок экрана 2022-03-15 в 14 06 52](https://user-images.githubusercontent.com/9497591/158343849-b6f1548a-e75b-485b-bed2-356f3541d02f.png)

**Comment by kmlebedev** [comment]
the problem repeated again tried to restart all the server filler did not help
But the restart of one server volume out of 20 helped

**Comment by kmlebedev** [comment]
Problem reaching concurrentUploadLimitMB limit
This is option dangerous and causes a domino effect

**Comment by chrislusf** [comment]
For concurrentUploadLimitMB, can we exclude the replication from the concurrentUploadLimitMB counting?

**Comment by kmlebedev** [comment]
> For concurrentUploadLimitMB, can we exclude the replication from the concurrentUploadLimitMB counting?

@chrislusf Yes, i was thinking the same thing.
I ran into several problems:
1.  Exclude the replication from the concurrentUploadLimitMB
2. All requests are not processed after hitting concurrentUploadLimitMB for up to several minutes
3. If the timeout is exceeded, for example, 30 seconds while waiting, you need to respond with 429 code

**Comment by paochiang** [comment]
https://github.com/chrislusf/seaweedfs/commit/0562fceb9925f6c2cd13b68f24d29dd1fd4c3e5e volume fail fast may be not very suitable. 

**change the code**
https://github.com/chrislusf/seaweedfs/blob/8f0410af2c01e158e85a635e3d6725ac6b966e1f/weed/server/volume_server_handlers.go#L54-L64
**to**
```
		if r.URL.Query().Get("type") != "replicate" {
			vs.inFlightUploadDataLimitCond.L.Lock()
			for vs.concurrentUploadLimit != 0 && atomic.LoadInt64(&vs.
				inFlightUploadDataSize) > vs.concurrentUploadLimit {
				glog.V(4).Infof("wait because inflight upload data %d > %d", vs.inFlightUploadDataSize, vs.concurrentUploadLimit)
				vs.inFlightUploadDataLimitCond.Wait()
			}
			vs.inFlightUploadDataLimitCond.L.Unlock()
			atomic.AddInt64(&vs.inFlightUploadDataSize, contentLength)
			defer func() {
				atomic.AddInt64(&vs.inFlightUploadDataSize, -contentLength)
				vs.inFlightUploadDataLimitCond.Signal()
			}()
		} else { //replicate
			atomic.AddInt64(&vs.inFlightUploadDataSize, contentLength)
			defer func() {
				atomic.AddInt64(&vs.inFlightUploadDataSize, -contentLength)
			}()
		}

```
Non-Relication keep waiting might be better.

**Comment by chrislusf** [comment]
> [0562fce](https://github.com/chrislusf/seaweedfs/commit/0562fceb9925f6c2cd13b68f24d29dd1fd4c3e5e) volume fail fast may be not very suitable.
> 
> **change the code**
> 
> https://github.com/chrislusf/seaweedfs/blob/8f0410af2c01e158e85a635e3d6725ac6b966e1f/weed/server/volume_server_handlers.go#L54-L64
> 
> 
> **to**
> ```
> 		if r.URL.Query().Get("type") != "replicate" {
> 			vs.inFlightUploadDataLimitCond.L.Lock()
> 			for vs.concurrentUploadLimit != 0 && atomic.LoadInt64(&vs.
> 				inFlightUploadDataSize) > vs.concurrentUploadLimit {
> 				glog.V(4).Infof("wait because inflight upload data %d > %d", vs.inFlightUploadDataSize, vs.concurrentUploadLimit)
> 				vs.inFlightUploadDataLimitCond.Wait()
> 			}
> 			vs.inFlightUploadDataLimitCond.L.Unlock()
> 			atomic.AddInt64(&vs.inFlightUploadDataSize, contentLength)
> 			defer func() {
> 				atomic.AddInt64(&vs.inFlightUploadDataSize, -contentLength)
> 				vs.inFlightUploadDataLimitCond.Signal()
> 			}()
> 		} else { //replicate
> 			atomic.AddInt64(&vs.inFlightUploadDataSize, contentLength)
> 			defer func() {
> 				atomic.AddInt64(&vs.inFlightUploadDataSize, -contentLength)
> 			}()
> 		}
> ```
> 
> Non-Relication keep waiting might be better.

Do you want to send a PR or some pseudo code?

**Comment by paochiang** [comment]
> 
> @paochiang Do you want to send a PR or some pseudo code to illustrate it better?
My pleasure: https://github.com/chrislusf/seaweedfs/pull/3081
