### ISSUE TITLE
filepath.Split use \ to split path on Windows

### ISSUE THREAD

**Issue by banjiaojuhao** [chrislusf/seaweedfs#2762]
`filepath.Split` use [os](https://pkg.go.dev/os).[PathSeparator](https://pkg.go.dev/os#PathSeparator) ([which is `\` on Windows](https://cs.opensource.google/go/go/+/refs/tags/go1.18:src/os/path_windows.go;l=8)) to split path.
If seaweed is running in Windows, path like `/a/b/c` will not be split into `/a/b/` and `c`.
[path.Split](https://pkg.go.dev/path#Split) split path with the final slash.

https://github.com/chrislusf/seaweedfs/blob/2aa9d9f84ac466e348821066f6332a8a5b777d47/weed/util/fullpath.go#L26-L30

**Comment by chrislusf** [comment]
Is this an actual bug? How to reproduce this?

**Comment by banjiaojuhao** [comment]
Sorry, my mistake.
> Windows accept / as path separator.
https://github.com/golang/go/blob/c379c3d58d5482f4c8fe97466a99ce70e630ad44/src/path/filepath/path.go#L191-L203
https://github.com/golang/go/blob/c379c3d58d5482f4c8fe97466a99ce70e630ad44/src/os/path_windows.go#L12-L16
