### ISSUE TITLE
collection submit fail

### ISSUE THREAD

**Issue by uncarman2017** [chrislusf/seaweedfs#2784]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs
Report issues here. Ask questions here https://stackoverflow.com/questions/tagged/seaweedfs
Please ask questions in https://github.com/chrislusf/seaweedfs/discussions

**Describe the bug**
when assign fid with collection, error raise as follows ,the url is http://XXX.XXX.XXX.XXX:9333/dir/assign?collection=works
{
    "error": "cannot grow volume group! Failed to assign 12: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp XXX.XXX.XXX.XXX:19335: connect: connection refused\""
}

But if I access with no collection param, it's successful。 Such as the url:  http://XXX.XXX.XXX.XXX:9333/dir/assign. The response as follows:
{
    "fid": "2,0152e6212c59",
    "url": "XXX.XXX.XXX.0:9335",
    "publicUrl": "XXX.XXX.XXX.0:9335",
    "count": 1
}

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".

``` 
cd /usr/local/weedfs

nohup ./weed -v=2 master -mdir=/usr/local/weedfs_data/master -port=9333 -defaultReplication=001 -ip=XXX.XXX.XXX.XXX &>>/usr/local/weedfs_data/master/wdfsmaster.log &

sleep 1s

nohup ./weed -v=2 volume -dir=/usr/local/weedfs_data/vola -port=9334 -max=20 -mserver=XXX.XXX.XXX.XXX:9333 -ip=XXX.XXX.XXX.XXX   &>>/usr/local/weedfs_data/vola/wdfsvola.log &

nohup ./weed -v=2 volume -dir=/usr/local/weedfs_data/volb -port=9335 -max=20 -mserver=XXX.XXX.XXX.XXX:9333 -ip=XXX.XXX.XXX.XXX &>>/usr/local/weedfs_data/volb/wdfsvolb.log &

nohup ./weed -v=2 filer -port=9336  -master=XXX.XXX.XXX.XXX:9333 -defaultReplicaPlacement=001 -ip=XXX.XXX.XXX.XXX &>>/usr/local/weedfs_data/filer/wdfsfiler.log &
```

**I install 1 master,2 volume server, 1 filer server in one PC.**

- OS version
- weed version:  version 30GB 2.91 09cd00f356c69b12d4f3b7caa8e16255031cc330 linux amd64

- if using filer, show the content of `filer.toml`

[leveldb2]
enabled = true
dir = "/usr/local/weedfs_data/filer/leveldb2"                    # directory to store level db files

Other configuration in "filer.toml" is default

**Expected behavior**
return fid and url , upload file to collection successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/31849893/159406673-31b023d8-e166-4f2b-8935-1e091b9567c0.png)

<img width="957" alt="微信截图_20220322121502" src="https://user-images.githubusercontent.com/31849893/159406844-2925bd8c-fc6d-4592-bcfd-bbd99ed7be84.png">

**Additional context**
Even if I clear the data folder of master/volume, then reboot, it still not works.

**Comment by chrislusf** [comment]
this should be not related to filer. 

Could you please make a docker compose file to reproduce this?

**Comment by uncarman2017** [comment]
> this should be not related to filer.
> 
> Could you please make a docker compose file to reproduce this?

I just use the binary  in "linux_amd64.tar.gz" downloaded from the page "https://github.com/chrislusf/seaweedfs/releases". Is there a problem?

**Comment by chrislusf** [comment]
This is fine

**Comment by uncarman2017** [comment]
But it caused the above problems, can you help me solve them

**Comment by uncarman2017** [comment]
> This is fine

But it caused the above problems, can you help me solve them

**Comment by uncarman2017** [comment]
I have fixed it, this not the problem of weedfs, thanks
