### ISSUE TITLE
Few writes are missed in filer append operation

### ISSUE THREAD

**Issue by 1995navinkumar** [chrislusf/seaweedfs#2785]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**
When concurrent write requests are fired for a file with append operation, few writes are being missed. The status code for all response is 201 though. 

**System Setup**
- start commands
     - weed master -ip=192.24.144.134 -ip.bind=192.24.144.134 -port=9333 -mdir=./master-dir/
     - weed volume -port=8333 -mserver=192.24.144.134:9333 -dir=./weed-data
     - weed filer -master=192.24.144.134:9333 -port=7333
- OS version - `Ubuntu 16.04`
- output of `weed version`
    -  version 30GB 2.94 2eda3a686ffc1707e67a45ff39c5852f02e5ec7b linux amd64
- if using filer, show the content of `filer.toml`
    - Using default configuration

**Expected behavior**
All write operation must append data to the file without being missed.

**Additional context**
I used node.js to write to the file concurrently. If the concurrency is 1 , all writes are being processed but when the concurrency is increased, few writes are being missed in the actual file. 

Please run `npm install queue form-data` before executing the script. 

If I run the above code, I get ~30 missed writes in the actual file. 

```js
const http = require("http");
var FormData = require('form-data');
var queue = require('queue');

var q = queue({
    results: [],
    concurrency : 6 // increase in concurrency increases the no.of missed write operation.
})

var url = `http://172.24.144.134:7333/serverout.txt?op=append`;  // change it to actual filer

var onSuccess = idx => cb => res => {
    var data = '';
    console.log(res.statusCode);
    res.on("data", chunk => {
        data += chunk;
    })

    res.on('end', res => {
        console.log(`req id : ${idx} - data : ${data}`);
        cb(null, JSON.parse(data));
    })
}

let loop = 100;
var options = { year: 'numeric', month: 'short', day: 'numeric' };
var formatter = new Intl.DateTimeFormat('en-us', options);

function formatDate(date) {
    return formatter.format(date);
}

function formatTime(now) {
    return [
        now.getHours(),
        ':',
        now.getMinutes(),
        ':',
        now.getSeconds()
    ].join('');
}

Array.from({ length: loop }).forEach((el, i) => {
    q.push(cb => {
        let form = new FormData();
        let now = new Date();
        form.append("file", `[${formatDate(now)}][${formatTime(now)}] [Info] [ReqId - ${i}] - This is a text from an application logger .\n`);

        let options = {
            method: "POST",
            headers: form.getHeaders()
        }

        let req = http.request(url, options, onSuccess(i)(cb));
        req.on("error", console.log);

        form.pipe(req);
        console.log(`Fired req id : ${i}`);
    })
})


q.on('success', function (result, job) {
    // console.log('The result is:', result);
})

// begin processing, get notified on end / failure
q.start(function (err) {
    if (err) throw err
    var sizes = q.results.flatMap(result => result[0].size);
    var set = new Set(sizes);
    console.log(`lost information = ${sizes.length - set.size}`)
})

```

**Comment by chrislusf** [comment]
Thanks for the detailed info!

This is very likely possible. There are no locks here. The last write wins.

Not sure of your requirement. But you may want to have your clients append to their own files, instead of one shared file.

**Comment by 1995navinkumar** [comment]
Thanks for replying @chrislusf 

> Not sure of your requirement

I'm trying to write application logs to a single file using filer. Since there will be more than one App.Servers, I wanted to test whether filer can handle concurrent write requests. 

> have your clients append to their own files, instead of one shared file

I want the file to be shared among the app servers, so that I can view the logs from different server as a whole. 

Can we queue the write requests in filer server and process one by one? Will that be okay? or is that something out of the scope of filer server to handle?

**Comment by LuckyFrost** [comment]
I want to note that your approach is extremely wrong. Use more suitable solutions for this, like elasticsearch or any other suitable for storing logs.
Even if someone adds locks on append, this can lead to huge problems with intensive parallel writing.

**Comment by chrislusf** [comment]
@1995navinkumar if really need to write to one single file, use some 3rd party locks. 

Or having different application on different servers writing to their own log files, and aggregate them during read time.
