### ISSUE TITLE
Chris, how can I contact you to discuss using your SeaweedFS core plus future modifications for a larger commercial project I have investors interested in?

### ISSUE THREAD

**Issue by alexn42** [chrislusf/seaweedfs#2825]

**Comment by kmlebedev** [comment]
@alexn42 I think you can contact via https://join.slack.com/t/seaweedfs/shared_invite/enQtMzI4MTMwMjU2MzA3LTEyYzZmZWYzOGQ3MDJlZWMzYmI0OTE4OTJiZjJjODBmMzUxNmYwODg0YjY3MTNlMjBmZDQ1NzQ5NDJhZWI2ZmY US working time
