### ISSUE TITLE
Delete file with mistake, Please help!

### ISSUE THREAD

**Issue by uncarman2017** [chrislusf/seaweedfs#2829]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs
Report issues here. Ask questions here https://stackoverflow.com/questions/tagged/seaweedfs
Please ask questions in https://github.com/chrislusf/seaweedfs/discussions

example of a good issue report:
https://github.com/chrislusf/seaweedfs/issues/1005
example of a bad issue report:
https://github.com/chrislusf/seaweedfs/issues/1008

**Describe the bug**
I deleted the file storage directory of weefs on a server by mistake, but weedfs is still running in memory. Open the weedfs management page and it seems that the picture files are still in memory. Is there any way to restore these files to the disk storage directory. Now I dare not restart weedfs. Once it is restarted, these files may not be found.

**Screenshots**
The webpage of seaweedfs shows these files exists, mybe in the cache or memory.
<img width="946" alt="1648455998(1)" src="https://user-images.githubusercontent.com/31849893/160357512-e9f4bd7f-a665-4d1e-858d-5bcb86b9537a.png">

**Additional context**

**Comment by chrislusf** [comment]
Please follow issue template. I do not know which directory you deleted.

See
https://superuser.com/questions/283102/how-to-recover-deleted-file-if-it-is-still-opened-by-some-process

**Comment by uncarman2017** [comment]
> Please follow issue template. I do not know which directory you deleted.
> 
> See https://superuser.com/questions/283102/how-to-recover-deleted-file-if-it-is-still-opened-by-some-process

I haven't understand.
I delete the folder "/usr/local/weed_data" with all seaweed files in it , can u help me restore it?
