### ISSUE TITLE
[BUG?] Can not read data when the node of leader is down

### ISSUE THREAD

**Issue by joy717** [chrislusf/seaweedfs#2862]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs
Report issues here. Ask questions here https://stackoverflow.com/questions/tagged/seaweedfs
Please ask questions in https://github.com/chrislusf/seaweedfs/discussions

example of a good issue report:
https://github.com/chrislusf/seaweedfs/issues/1005
example of a bad issue report:
https://github.com/chrislusf/seaweedfs/issues/1008

**Describe the bug**

I have a k8s which version is 1.18 with 3 nodes.
Each node sets up a server with command:
```
docker run --rm --net=host -d -v /bricks/brick1:/mydata chrislusf/seaweedfs server -s3 -dir=/mydata -volume.port=8081 -master.peers=x.x.x.x:9333,y.y.y.y:9333,z.z.z.z:9333
```
Then I use seaweedfs csi-driver for dynamic creating a RWX pvc.
And mount this pvc to a deployment which has 3 replicas on 3 nodes.
Everything is OK for writing and reading shared files.

If I stopped the leader `server` container, I can't read that files anymore.
It shows me:
```
cat: data/a.txt: Input/output error
```
It can be found that the leader has changed via the dashboard of master.

If I stopped a "un-leader" `server` container,  files are OK though.

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
```
docker run --rm --net=host -d -v /bricks/brick1:/mydata chrislusf/seaweedfs server -s3 -dir=/mydata -volume.port=8081 -master.peers=x.x.x.x:9333,y.y.y.y:9333,z.z.z.z:9333
```
- OS version
```
CentOS 7.6 
with kernel
5.16.13-1.el7.elrepo.x86_64
```
- output of `weed version`
```
version 30GB 2.96 0490ee87 linux amd64
```
- if using filer, show the content of `filer.toml`
```
[leveldb2]
enabled = true
dir = "/data/filerldb2"
```

**Expected behavior**
Should work correctly when the leader `server` down and then changed a new leader.

**Screenshots**

**Additional context**

**Comment by joy717** [comment]
<img width="1425" alt="image" src="https://user-images.githubusercontent.com/310284/161374174-6133ed1e-2125-49cb-833f-c0133a36375e.png">

After the old leader(192.168.30.180) down, Volume Server found a new leader(192.168.30.201).
But logs shows me that:
```
I0402 07:58:10     1 masterclient.go:99] master masterClient Connecting to master 192.168.30.201:9333
I0402 07:58:10     1 masterclient.go:122] filer masterClient Connected to 192.168.30.201:9333
I0402 07:58:10     1 masterclient.go:122] master masterClient Connected to 192.168.30.201:9333
I0402 07:58:10     1 masterclient.go:136] redirected to leader 192.168.30.180:9333
I0402 07:58:10     1 masterclient.go:99] filer masterClient Connecting to master 192.168.30.180:9333
I0402 07:58:10     1 masterclient.go:136] redirected to leader 192.168.30.180:9333
I0402 07:58:10     1 masterclient.go:99] master masterClient Connecting to master 192.168.30.180:9333
```

It's wired to redirect to a old(down) leader.

**Comment by chrislusf** [comment]
the election takes some time. It should elect a leader after about 15 seconds.

**Comment by joy717** [comment]
> the election takes some time. It should elect a leader after about 15 seconds.

It do has a new leader for server.
But can't read file after 30 minutes.

I'll try to deploy with helm chart instead of docker run.

**Comment by chrislusf** [comment]
how did you configure the csi-driver? Did you set the filers?

**Comment by joy717** [comment]
> how did you configure the csi-driver? Did you set the filers?

I used helm chart to deploy csi-driver with default configurations.
Only change the filer parameter:
```
seaweedfsFiler: "seaweedfs-filer:8888"
```

**Comment by chrislusf** [comment]
There are 3 filers. Need to configure them for the csi driver.

**Comment by joy717** [comment]
> There are 3 filers. Need to configure them for the csi driver.

I see.
I tried 3 filer server addresses, but still not worked.

**Comment by joy717** [comment]
I think I've found the root cause.
The docker run command:
```
docker run --rm --net=host -d -v /bricks/brick1:/mydata chrislusf/seaweedfs server -s3 -dir=/mydata -volume.port=8081 -master.peers=x.x.x.x:9333,y.y.y.y:9333,z.z.z.z:9333
```
does not specify `-filer.defaultReplicaPlacement` and `-master.defaultReplication` .
If filer doesn't specify `defaultReplicaPlacement`, will use `master.defaultReplication` instead.
The default value of  `master.defaultReplication` will be `000`
which means no redundant data will be saved. 
If I stop the `leader` container, the `volume service` in this container will be stopped too, but data are still in this `volume service`.
Even there is a new `leader` server container, but data are broken now.

Thus, the docker run command change to this, should resolve this problem:
```
docker run --rm --net=host -d -v /bricks/brick1:/mydata chrislusf/seaweedfs server -s3 -dir=/mydata -volume.port=8081 -master.peers=x.x.x.x:9333,y.y.y.y:9333,z.z.z.z:9333 -master.defaultReplication=3
```

BTW, I'm using helm chart to deploy instead of docker:

https://github.com/chrislusf/seaweedfs/issues/2877
