### ISSUE TITLE
fio randwrite crashes weed mount

### ISSUE THREAD

**Issue by paularlott** [chrislusf/seaweedfs#2866]
**Describe the bug**

Running random write test on fio crashes weed mount:

```
fio --randrepeat=1 --name=test --filename=/seaweedfs/testfile --bs=4k --iodepth=1 --size=1G --readwrite=randwrite
```

I also created a plugin to use SeaweedFS storage under Proxmox but it yields unusable VMs, I suspect it's related to this in some way, I'll retest and dig further once this one is solved.

**System Setup**

Servers are Ubuntu, and client is Debian / Proxmox 7.

Server 1:
```
weed server -dir=/srv/seaweedfs -s3 -s3.config=s3.json -master.defaultReplication=001 -filer.defaultReplicaPlacement=001 -volume.max=0
```

Server 2:
```
weed volume -dir=/srv/seaweedfs -mserver=192.168.8.50:9333 -max=0 &
weed filer -s3 -defaultReplicaPlacement=001 -master=192.168.8.50:9333
```

filer.toml
```
recursive_delete = false

[leveldb2]
# local on disk, mostly for simple single-machine setup, fairly scalable
# faster than previous leveldb, recommended.
enabled = true
dir = "./filerldb2"                    # directory to store level db files
```

Client Mount:

```
weed -v=2 mount -dir=/seaweedfs -filer='192.168.8.50:8888,192.168.8.51:8888' -filer.path=/
```

Client test:

```
fio --randrepeat=1 --name=test --filename=/seaweedfs/testfile --bs=4k --iodepth=1 --size=1G --readwrite=randwrite
```

All other fio tests appear working. However in this case weed mount crashes with attached output. This crash happens on a brand new deploy of SeaWeedFS having run nothing before hand.

**Expected behavior**
Test should run to completion.

** Copy of Crash Output **
[crash.txt.gz](https://github.com/chrislusf/seaweedfs/files/8403675/crash.txt.gz)

**Comment by chrislusf** [comment]
Thanks for the detailed report and the error logs!

Added the fix.

Not familiar with what is going on with Proxmox. Does it have some sort of renaming or hardlinks or some combinations?

**Comment by paularlott** [comment]
Fix works like a charm thanks. So back to testing.

Proxmox is creating a single large file, 16GB, in qcow2 format. This build seems to have change the behaviour so I'll see where I get to and create a new issue if I have anything to go on. Thanks again.
