### ISSUE TITLE
rsync never skips existing files.

### ISSUE THREAD

**Issue by AllardJ** [chrislusf/seaweedfs#2867]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs
Report issues here. Ask questions here https://stackoverflow.com/questions/tagged/seaweedfs
Please ask questions in https://github.com/chrislusf/seaweedfs/discussions

example of a good issue report:
https://github.com/chrislusf/seaweedfs/issues/1005
example of a bad issue report:
https://github.com/chrislusf/seaweedfs/issues/1008

**Describe the bug**

rsync transfers already existing files. I'm using weed mount on 2.96.

**System Setup**
`rsync -avlHAXWE --progress --relative`

**Expected behavior**

Skips the files. the metadata is bad or similar.

**Screenshots**

**Additional context**

**Comment by chrislusf** [comment]
what is the source and destination?
Is `weed mount` the source? Please show some actual full examples.

**Comment by AllardJ** [comment]
`weed mount` is the destination, it just keeps creating new files.

`rsync -avlHAXWE --progress --relative /tmp/Directory /weed/replace`

**Comment by chrislusf** [comment]
thanks for reporting! fixed now.
