### ISSUE TITLE
[Question]How to make filer server  concern the lead change。

### ISSUE THREAD

**Issue by ljming** [chrislusf/seaweedfs#289]
Hello.
How to make filer server  concern the leader change,   three master servers in a cluster.
And when starting a filer server can't bind ip address , why?

Thanks

**Comment by chrislusf** [comment]
> How to make filer server concern the lead change?

Not implemented yet.

> And when starting a filer server can't bind ip address , why?

Usually just bind to all interfaces. Not implemented. Should be trivial to do.
Added https://github.com/chrislusf/seaweedfs/issues/290 to track this.

**Comment by chrislusf** [comment]
#290 is fixed now.

**Comment by hxiaodon** [comment]
How to make filer server concern the lead change?

I just finish this feature,will submit later

**Comment by hxiaodon** [comment]
How to make filer server concern the lead change?

[https://github.com/chrislusf/seaweedfs/pull/312](#312) try to fix it

**Comment by chrislusf** [comment]
fixed.

**Comment by hxiaodon** [comment]
@ljming 
The 312 fix has something wrong, please take this new one [#335](https://github.com/chrislusf/seaweedfs/pull/335)
