### ISSUE TITLE
Add a tool to change a volume's replication setting.

### ISSUE THREAD

**Issue by fedotxxl** [chrislusf/seaweedfs#29]
Hello. We are going to try weed-fs in our pretty big project to store 3m+ images. There are few questions about replication which are not clear from docs:

1. Weed replicates volumes. Is it correct?
2. Is it possible to change replication type for volume `x`? Suppose we added one more server
3. Is it possible to control volume location? We've got 3 servers and `001` replication type. Volume `1` is located on server `A` and `B`. How can I move it from `B` to `C`?

**Comment by aszxqw** [comment]
`2. Could be a feature later. Now this is not possible. Theoretically you just need to write some code to change the replication type in the volume's super block, and make a copy of the volume. `

This feature is strong demand. I am waiting for it too.

**Comment by atrniv** [comment]
+1

**Comment by atrniv** [comment]
Is there any way to do this manually for now ? I need to do this for a migration of some production servers to a new cluster.

**Comment by wu0407** [comment]
+1

**Comment by mosic** [comment]
@chrislusf Can you give an update on this feature, is it on the roadmap?

If I understood it correctly, the way it is now I would need to know in advance what kind of replication I want to use, and if I wanted to change it later (e.g. from 100 to 200) I'm out of luck. Is that right?

**Comment by chrislusf** [comment]
Added a tool, "change_replication", in the "unmaintained" section. It can be used to view or change a volume's replication setting.
