### ISSUE TITLE
SeaWeedFS is getting stuck and I get timeouts

### ISSUE THREAD

**Issue by cigolpl** [chrislusf/seaweedfs#2903]
**Describe the bug**

My SeaWeedFS server is getting stuck at least once a day. Once it is stuck then S3 and `weed shell` is not responding anymore. 
I need to restart it by `sudo systemctl restart weed` to make it working again. I am using your tool as an alternative to S3 for storing and retrieving millions of images. 

**System Setup**

I am running weed like from sysctl:
ExecStart=weed -v=4 -logdir=/home/mateusz/logs server -volume.max=1000  -volume.disk=hdd -master.volumeSizeLimitMB=900240 -master.volumePreallocate=false   -dir=/data/seabackup/ -s3 -s3.config=/etc/weed/s3.conf

OS Version: 
Linux s3 5.13.0-28-generic #31~20.04.1-Ubuntu

Weed version:
version 8000GB 2.96 0490ee87efa25ecb77b71d5f7b08d539195db8c4 linux amd64

**Expected behavior**
SeaWeedFS is not getting stuck and it response with 200 and not timeout. 

**Screenshots**

**Additional context**

Error logs is telling me `too many open files` 
```
E0405 11:25:00 45712 filer_server_handlers_read.go:102] Internal /buckets/images/extra-s.ro-9839b549-09-2021-small.jpg: get /buckets/images/extra-s.ro-9839b549-09-2021-small.jpg : open /data/seabackup/filerldb2/06/004940.ldb: too many open files
E0405 11:25:00 45712 filer_server_handlers_read.go:102] Internal /buckets/images/prego.ro-260340be-04-2021-small.jpg: get /buckets/images/260340be-04-2021-small.jpg : open /data/seabackup/filerldb2/06/005455.ldb: too many open files
E0405 12:43:24 45712 s3api_object_handlers.go:330] post to filer: Get "http://xx.xx.xx.xx:8888/buckets/images/8292e24e-08-2021-small.jpg": dial unix /tmp/seaweefs-filer-8888.sock: socket: too many open files
```

but my `ulimit -n` is 1000000

**Comment by LuckyFrost** [comment]
limits.conf is not used when systemd is running.
Use LimitNOFILE

**Comment by cigolpl** [comment]
Thank you. Hope it's gonna help. Related: https://github.com/chrislusf/seaweedfs/issues/1984
