### ISSUE TITLE
Change replication settings of s3 bucket

### ISSUE THREAD

**Issue by PeterCxy** [chrislusf/seaweedfs#2908]
It seems that the replication settings of a s3 bucket is stored as part of the fuse attributes and cannot be changed afterwards from shell. It would be nice if there is another shell command to reconfigure this (for new volumes in the bucket, of course).

BTW, does the setting in `fs.configure` take precedence over the one set directly in the s3 bucket?

**Comment by chrislusf** [comment]
are you using s3 or fuse?

**Comment by PeterCxy** [comment]
s3, but [from the code](https://github.com/chrislusf/seaweedfs/blob/master/weed/shell/command_s3_bucket_create.go#L61) it seems that the replication settings is stored in FuseAttributes

**Comment by chrislusf** [comment]
Does the replication setting in FuseAttributes take effect? I could not find the code reading the value myself. Maybe a neglect to add the code.

**Comment by PeterCxy** [comment]
All I know is that I set the `-replication` property while creating the bucket, and this value is only written to FuseAttributes, and it clearly did take effect.

**Comment by chrislusf** [comment]
Found the code here: https://github.com/chrislusf/seaweedfs/blob/master/weed/server/filer_server_handlers_write.go#L212

The priority is:
1. the replication setting in the url
2. the replication setting in the `fs.configure`
3. the replication setting configured in `s3.bucket.create`. 
4. the filer default replication setting
