### ISSUE TITLE
Replication restoration, whats the best strategy for maintaining replication after volume loss

### ISSUE THREAD

**Issue by jjn2009** [chrislusf/seaweedfs#292]
I have a master setup with 001 default replication with 2 volume servers, 'node1' and 'node 2'. 

Lets say I have a volId of 1 which is replicated across 'node 1' and 'node 2'. In the event that node 1  goes down and is completely lost what is the best path to recreate the replica of volId 1 on node 2? Lets say I can add a new 'node 3' into the cluster for the purpose of recreating the volId 1 replica.

**Comment by chrislusf** [comment]
There is a "weed backup" to continuously backup to some place.

For "node 3", the simplest way is just to rsync the file over, since volume 1 will be readonly at that time.
