### ISSUE TITLE
enhancement: replace sort.Slice with slices.SortFunc to reduce reflection

### ISSUE THREAD

**Issue by leyou240** [chrislusf/seaweedfs#2920]
**Expected behavior**
replace sort.Slice with slices.SortFunc to reduce reflection in the project, since 1.18 support generic.
And need import golang.org/x/exp package.
https://github.com/golang/exp/blob/master/slices/sort.go#L17
Is it appropriate to do so? if true, i will pr

**Comment by chrislusf** [comment]
Yes! Thanks for the suggestion and waiting for the PR.

**Comment by leyou240** [comment]
#2929
