### ISSUE TITLE
how well does seaweed hand large files?  how about differential updates?

### ISSUE THREAD

**Issue by syadnom** [chrislusf/seaweedfs#293]
While I see that large files can be chunked, how well is this handled?  CPU heavy?  How about multi-gigabyte files?

How about handling differential updates?  If I'm updating a file, does it pull hashes of each chunk and only upload changed chunks?

Are chunks of a 'meta file id' stored on separate servers?  ie, can I upload a large file, chunked in 2M parts, with replication as 100 or 110?

**Comment by chrislusf** [comment]
chunking is on client side. No impact to the system.

does not handle differential updates. but you can just update one chunk.

yes.

Being NoFS, the client can choose how to organize the blobs into a large file. The server side does not care.
