### ISSUE TITLE
versioning?

### ISSUE THREAD

**Issue by syadnom** [chrislusf/seaweedfs#295]
Is there any support for versioning?  For instance, if a file is updated, can I have the previous data be stored as a previous version and also set a 'name' group for that version?

A use case would be storing some backups, then updating the files.  When pulling that file, I'd want to get a list of all versions and then pull a given version.  Further, if I could get a list of all files with a given version id....

I realize that I could simply upload a replacement file and handle the versioning in the front end application, but for larger files, it would be really important to only update a file and only changed chunks.

**Comment by chrislusf** [comment]
No.

This is complicated, even though it sounds easy. It's better to treat seaweedfs as a simple key~blob store and handle your specific logic on the client side.
