### ISSUE TITLE
When using DNS in `-peers` master is unable to start

### ISSUE THREAD

**Issue by nahsi** [chrislusf/seaweedfs#2959]
This is not a bug, but a feature request.

I'm trying to run SeaweedFS in Nomad using Consul for service discovery using DNS names in `-peers` option.
```
-peers=master-1.seaweedfs.service.consul:9333,master-2.seaweedfs.service.consul:9333,master-3.seaweedfs.service.consul:9333
```

Each master node is registered in Consul with the option [`initial_status`](https://www.nomadproject.io/docs/job-specification/service#initial_status) set to `passing`, so when Nomad registers master node in Consul, DNS name will be resolvable for some time (until check fails for several consecutive times).

```hcl
      service {
        name = "seaweedfs"
        port = "metrics"

        tags = [
          "master",
          "master-${meta.seaweedfs_index}",
        ]

        meta {
          alloc_id  = NOMAD_ALLOC_ID
          component = "master"
        }

        check {
          name     = "SeaweedFS master"
          type     = "http"
          protocol = "http"
          port     = "http"
          path     = "/stats/heath"
          interval = "20s"
          timeout  = "1s"

          initial_status = "passing"
        }
      }
```

But on start master immediately crashes with the message:
```
I0423 14:07:26     1 config.go:46] Reading : Config File "security" Not Found in "[/data /.seaweedfs /usr/local/etc/seaweedfs /etc/seaweedfs]"
I0423 14:07:26     1 config.go:46] Reading : Config File "master" Not Found in "[/data /.seaweedfs /usr/local/etc/seaweedfs /etc/seaweedfs]"
I0423 14:07:26     1 file_util.go:23] Folder /data Permission: -rwx------
I0423 14:07:26     1 master.go:255] current: 10.1.10.20:9333 peers:master-1.seaweedfs.service.consul:9333,master-2.seaweedfs.service.consul:9333,master-3.seaweedfs.service.consul:9333
F0423 14:07:26     1 master.go:271] Only odd number of masters are supported: [master-1.seaweedfs.service.consul:9333 master-2.seaweedfs.service.consul:9333 master-3.seaweedfs.service.consul:9333 10.1.10.20:9333]
goroutine 1 [running]:
```

The problem is that Nomad registers the service on start, but because it immediately crashes it deregisters it also immediately and DNS becomes unresolvable.

I think it can be fixed by adding some kind of DNS resolution retry? For example 10 retries with dynamically increasing backoff.

**Comment by kmlebedev** [comment]
It's wotk if you use dns name for ip param

**Comment by nahsi** [comment]
@kmlebedev It seems to work. Although now I need to think of a way to template `-ip` command with `seaweedfs_index` from node metadata.

Thanks!
