### ISSUE TITLE
raft election timeout issue

### ISSUE THREAD

**Issue by quetz** [chrislusf/seaweedfs#296]
Underlying raft server is configured as:
```go
s.raftServer.SetElectionTimeout(time.Duration(pulseSeconds) * 3450 * time.Millisecond)
```
This is a problem even with default `pulseSeconds` value which is 5, because it means that first 15 seconds after startup server is unavailable (no master elected). When using higher `pulseSeconds` value it becomes even worse.

Is there any reason to configure raft timeout like this? Why not use defaults (50/150ms) there?

**Comment by chrislusf** [comment]
Usually the masters could be in data centers, requiring longer timeout settings.
