### ISSUE TITLE
About fdatasync/fsync after each write

### ISSUE THREAD

**Issue by zjay1987** [chrislusf/seaweedfs#297]
Does seaweedfs employ any mechanism to ensure durable write operation and prevent data loss under power outage of entire cluster?

**Comment by chrislusf** [comment]
No. The last few updates could be lost depending on machine setup.

**Comment by zjay1987** [comment]
Does seaweedfs have any plans to improve data security under circumstances like this?

**Comment by chrislusf** [comment]
We could add an option to fsync to disk before returning successfully. This is rarely useful since it is paying performance cost for each operation, just in case a few latest files are persisted when power goes down, which is very rare. 

Usually in real data centers each machine has a small battery to flush stuff to disk when power goes off.

**Comment by zjay1987** [comment]
What about direct I/O? Direct I/O bypass the OS write buffer and touch the disk directly, I tested that it performs much better than fsync after each write, with the price of 512-bytes alignment. 

> Usually in real data centers each machine has a small battery to flush stuff to disk when power goes off

You are talking about UPS? In my experience, large-scale distributed file system cares about price cost seriously, the storage nodes are build with cheap hardware（such as desktop-level HDDs）, UPS for each node is a very very expensive option. 

By the way, power outage is just one of the many failures, there are hardware crash, OS crash... too, good online service cares about data loss seriously!

**Comment by chrislusf** [comment]
Not familiar with direct io. Maybe you can have a PR with this feature.

Not UPS. Just a small battery.

**Comment by zjay1987** [comment]
Yep, may be I can try when I have enough spare time.

> Not UPS. Just a small battery.

BBU on RAID controller?
