### ISSUE TITLE
How can I get the disk usage via http?

### ISSUE THREAD

**Issue by 1104662797** [chrislusf/seaweedfs#2979]
I have tried this `curl "http://localhost:8080/status"`  and `echo "fs.du http://localhost:8888/some/path" | weed shell` , but this don't work。

**Comment by chrislusf** [comment]
what was the error with `echo "fs.du http://localhost:8888/some/path" | weed shell`?

**Comment by 1104662797** [comment]
error: http://<filer>:<port> prefix is not supported any more

**Comment by chrislusf** [comment]
follow the error message and remove `http://<filer>:<port>`
