### ISSUE TITLE
Existing files disappear after forced garbage collection

### ISSUE THREAD

**Issue by Dpiryatinets** [chrislusf/seaweedfs#298]
Hello!
I have such a problem: 
1). I have several files stored in one volume;
2). I delete one of them sending a DELETE request.
3). After that I force garbage collection using curl "http://localhost:9333/vol/vacuum" (as you  mentioned here https://github.com/chrislusf/seaweedfs/wiki/API#force-garbage-collection).
4). And after that volume becomes completely clean. Even those files I did not delete are deleted. 
What do I do wrong?

**Comment by chrislusf** [comment]
Do not know unless you make it a reproducible case.
