### ISSUE TITLE
Volume vacuuming results in reading object timeout.

### ISSUE THREAD

**Issue by guol-fnst** [chrislusf/seaweedfs#2985]
When reading a object , if the volume where this object stored in is being  vacuumed, then it may take a long time.
Volume are locked in "CommitCompact()" when committing compact.
Is it unavoidable?

**Comment by kmlebedev** [comment]
@guol-fnst What exactly do you mean by may take a long time ?
It seems that the volume is not locked, but goes into read-only mode ?

**Comment by chrislusf** [comment]
@guol-fnst also, which version you are using?

**Comment by guol-fnst** [comment]
version: 2.86 2.96 2.99
I was doing a test (test pattern:30% write, 70% read) using cosbench, cosbench reported reading timeout.

I make a conclusion from source code. 
When committing compact, weed adds "v.dataFileAccessLock.Lock()" in CommitCompact(). 
When reading needles, weed adds "v.dataFileAccessLock.RLock()" in readNeedle().
If I make a mistake ,please ponit it out.

**Comment by guol-fnst** [comment]
> > I was doing a test (test pattern:30% write, 70% read) using cosbench, cosbench reported reading timeout.
> 
> The test was without replication?

yes
We have replication in volume directory
