### ISSUE TITLE
Unable to upload file after updating from 0.69.1 to 0.71 beta

### ISSUE THREAD

**Issue by fedotxxl** [chrislusf/seaweedfs#299]
We updated our dev servers to master version of weed fs. We've got 3 replicas on the same server. Everything is configured correctly (according to /status requests). When I try to upload file to volume server I got an error message:

`{"name":"5c7772362c2d5c.jpg","error":"Failed to write to replicas for volume 70: "}`

1. It misses error description - is it bug? can you fix it / we will update our servers and try again?
2. Any specific steps on updating from 0.69 to 0.71?

**Comment by chrislusf** [comment]
Just replace the binary, to upgrade.
