### ISSUE TITLE
support additional header name~value pairs

### ISSUE THREAD

**Issue by chrislusf** [chrislusf/seaweedfs#300]
Currently in the go/storage/needle.go file, NewNeedle() do not handle additional name~value pairs in headers.

We can have one additional bit in Needle.Flags byte, to mark that we have a string storing additional name~value paris.

**Comment by sparklxb** [comment]
I think I can help. Which request will the additional pairs be returned for, a GET or HEAD request for the file, or a special URL request? More details can be helpful. Thanks.

**Comment by chrislusf** [comment]
Just GET and HEAD requests.

**Comment by sparklxb** [comment]
There are 4 ways to POST/PUT additional name-value pairs:
1. put them in request header directly -- it's simple, but mixes them with header's key-value pairs;
2. all in url parameters;
3. all in a single multipart/form-data part with a special keyword as name;
4. every pair in different multipart/form-data part.
Which is the best？Please give me some advise.

**Comment by chrislusf** [comment]
1, with a prefix, such as Seaweed-xxxxx

**Comment by sparklxb** [comment]
Get it, Thanks!

**Comment by BruceWangNo1** [comment]
Is this done? @sparklxb
