### ISSUE TITLE
Empty response from the server in case of incorrect file id

### ISSUE THREAD

**Issue by fedotxxl** [chrislusf/seaweedfs#301]
```
[root@builddev weed-volume-1]# curl -IL 127.0.0.1:8071/708,01045f6d4cae611a
curl: (52) Empty reply from server
```

From the logs:
```
I0511 20:12:53 13249 volume_server_handlers_read.go:71] read error: Not Found /708,01045f6d4cae611a
```

**Comment by chrislusf** [comment]
This was intentional to avoid any possible id enumeration attack, to give the attacker as few clue as possible.

What do you think it should act in this case?

**Comment by fedotxxl** [comment]
I think it should return `404` - isn't it default web behaviour in this case?
