### ISSUE TITLE
I worry about the security of the Fid

### ISSUE THREAD

**Issue by siningintherain** [chrislusf/seaweedfs#3023]
Since we plan deploy our App in privatization. We would use the seaweedFS instead of OSS(Alibaba). But I'm afraid of the security of the solution in present.

Because of the OSS support the STS(Security Token Services), so we can upload files to the FileServer by JavaScript in WebSite straightly in present.
After we use the seaweedFS instead of the OSS, the problem is we can't upload files to the FileServer By JS relieved any more. 

Eg: 
**preupload**
`curl http://masterserver/dir/assign`

**returned**
`{"fid":"9,68affb648b","url":"volumeserver1","publicUrl":"volumeserver1","count":1} `

Then we can use the publicUrl to finish uploading. 
But I try to modified the fid to '9,**69**affb648b', I found it works ! I can use the 'new fid' to upload any files. This is what I'm worry about. 

So,I want to know does the seaweedfs can support STS? Thank you.

**Comment by chrislusf** [comment]
see https://github.com/chrislusf/seaweedfs/wiki/Security-Overview

**Comment by siningintherain** [comment]
Thanks Lu, it helps me a lot
https://github.com/chrislusf/seaweedfs/wiki/Security-Overview#securing-volume-servers
