### ISSUE TITLE
master node: fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by xxr3376** [chrislusf/seaweedfs#303]
I got `fatal error: concurrent map read and map write` when I am running a benchmark.

I have three machine with SSD, network are connected with IPOIB.
There is one volume server on each machine, and a master on one of them.

Master server start with:
> ulimit -n 8192
> ./weed master -port=9333 -ip=$IP -ip.bind=$IP -mdir=/data1/meta -defaultReplication 000

Volume server start with:
> ulimit -n 8192
> ./weed volume -dataCenter=1 -dir=/data1/volume -images.fix.orientation=false -index=memory -ip=$IP -ip.bind=$IP -mserver=$MASTER_IP -port=8080 -rack=1 -max=60

There is another machine run the benchmark `./weed benchmark -server $MASTER_IP:9333 -c 128 -size=102400 -n 1048576`, and I got this error on master server.

The weed I used compiled from source (commit: f8b03c45ef7e095542bc6c9a3d05412c04a9e211), using go version go1.6.1 linux/amd64.

Full tracback at [Here](https://github.com/chrislusf/seaweedfs/files/274133/out.txt), following is a snippet.

> fatal error: concurrent map read and map write
>
> goroutine 564 [running]:
> runtime.throw(0xe4f180, 0x21)
>         /usr/local/go/src/runtime/panic.go:530 +0x90 fp=0xc8207b0b78
> sp=0xc8207b0b60
> runtime.mapaccess2_fast32(0xaecde0, 0xc8204221b0, 0xe, 0x870e8c50af1e08b3,
> 0x1)
>         /usr/local/go/src/runtime/hashmap_fast.go:67 +0x5a fp=0xc8207b0b98
> sp=0xc8207b0b78
> github.com/chrislusf/seaweedfs/go/topology.(*DataNode).AddOrUpdateVolume(0xc820288000,
> 0xe, 0x8, 0xc8209f3d40, 0xc8205b2d0e, 0x0, 0x0, 0x2, 0x0, 0x0, ...)
>         /home/xxr/golang/src/github.com/chrislusf/seaweedfs/go/topology/data_node.go:35
> +0x46 fp=0xc8207b0c20 sp=0xc8207b0b98
> github.com/chrislusf/seaweedfs/go/topology.(*DataNode).UpdateVolumes(0xc820288000,
> 0xc8208eac00, 0x14, 0x20, 0x0, 0x0, 0x0)
>         /home/xxr/golang/src/github.com/chrislusf/seaweedfs/go/topology/data_node.go:62
> +0x5d4 fp=0xc8207b1310 sp=0xc8207b0c20
> github.com/chrislusf/seaweedfs/go/topology.(*Topology).ProcessJoinMessage(0xc820136fc0,
> 0xc82057c580)
>         /home/xxr/golang/src/github.com/chrislusf/seaweedfs/go/topology/topology.go:170
> +0x4eb fp=0xc8207b1710 sp=0xc8207b1310
> github.com/chrislusf/seaweedfs/go/weed/weed_server.(*MasterServer).dirJoinHandler(0xc8201e40e0,
> 0x7ff721d3b658, 0xc820a20750, 0xc8205a6540)
>         /home/xxr/golang/src/github.com/chrislusf/seaweedfs/go/weed/weed_server/master_server_handlers_admin.go:61
> +0x840 fp=0xc8207b18d8 sp=0xc8207b1710
> github.com/chrislusf/seaweedfs/go/weed/weed_server.(*MasterServer).(github.com/chrislusf/seaweedfs/go/weed/weed_server.dirJoinHandler)-fm(0x7ff721d3b658,
> 0xc820a20750, 0xc8205a6540)
>         /home/xxr/golang/src/github.com/chrislusf/seaweedfs/go/weed/weed_server/master_server.go:67
> +0x3e fp=0xc8207b1900 sp=0xc8207b18d8
> github.com/chrislusf/seaweedfs/go/weed/weed_server.(*MasterServer).proxyToLeader.func1(0x7ff721d3b658,
> 0xc820a20750, 0xc8205a6540)
>         /home/xxr/golang/src/github.com/chrislusf/seaweedfs/go/weed/weed_server/master_server.go:104
> +0x93 fp=0xc8207b1a38 sp=0xc8207b1900
> net/http.HandlerFunc.ServeHTTP(0xc820127fc0, 0x7ff721d3b658, 0xc820a20750,
> 0xc8205a6540)
>         /usr/local/go/src/net/http/server.go:1618 +0x3a fp=0xc8207b1a58
> sp=0xc8207b1a38
> github.com/gorilla/mux.(*Router).ServeHTTP(0xc8200d3270, 0x7ff721d3b658,
> 0xc820a20750, 0xc8205a6540)
>         /home/xxr/golang/src/github.com/gorilla/mux/mux.go:103 +0x270
> fp=0xc8207b1b70 sp=0xc8207b1a58
> net/http.serverHandler.ServeHTTP(0xc8200d5400, 0x7ff721d3b658, 0xc820a20750,
> 0xc8205a6540)
>         /usr/local/go/src/net/http/server.go:2081 +0x19e fp=0xc8207b1bd0
> sp=0xc8207b1b70
> net/http.(*conn).serve(0xc82031ea80)
>         /usr/local/go/src/net/http/server.go:1472 +0xf2e fp=0xc8207b1f98
> sp=0xc8207b1bd0
> runtime.goexit()
>         /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8207b1fa0
> sp=0xc8207b1f98
> created by net/http.(*Server).Serve
>         /usr/local/go/src/net/http/server.go:2137 +0x44e

**Comment by chrislusf** [comment]
thanks for reporting. I just added two commits for this. Please check.
