### ISSUE TITLE
How to backup data more efficiently

### ISSUE THREAD

**Issue by trojansun** [chrislusf/seaweedfs#3036]
**Describe the bug**
How to backup data more efficiently (asynchronous backup or cluster synchronization)

**System Setup**
- `weed filer.sync -a xx.xx.xx.xx:8888 -a.path=/buckets/img-b localhost:8888 -b.path=/buckets/img-isActivePassive`
- OS version : Linux x64 ubuntu 20.04 
- output of `weed version`  :  version 30GB 2.97 77a7d7253f6e4f5ac48b9ac9e35a45a3229c1af1 linux amd64
-  filer.toml
```
[postgres2]
enabled = true
createTable = """
  CREATE TABLE IF NOT EXISTS "%s" (
    dirhash   BIGINT,
    name      VARCHAR(65535),
    directory VARCHAR(65535),
    meta      bytea,
    PRIMARY KEY (dirhash, name)
  );
"""
hostname = "192.168.50.123"
port = 5432
username = "seaweedfs"
password = "seaweedfs"
database = "seaweedfs"          # create or use an existing database
schema = ""
sslmode = "disable"
connection_max_idle = 100
connection_max_open = 100
connection_max_lifetime_seconds = 0
# if insert/upsert failing, you can disable upsert or update query syntax to match your RDBMS syntax:
enableUpsert = true
upsertQuery = """INSERT INTO "%[1]s" (dirhash,name,directory,meta) VALUES($1,$2,$3,$4) ON CONFLICT (dirhash,name) DO UPDATE SET meta = EXCLUDED.meta WHERE "%[1]s".meta != EXCLUDED.meta"""
```

**Expected behavior**
When I use `weed filer.sync` and `weed filer.backup` for cluster synchronization or backup, its efficiency is slow.
My current small file generation volume is about a thousand per second. When I synchronize data to the backup environment (local path) or other filer, its efficiency is slow, when my local time is already on May 10 On May 9, the synchronization progress is only until May 9, and the subsequent data will still increase so much. How should this be implemented to improve the efficiency, thank you.

**Screenshots**

**Additional context**
command is
`weed filer.sync -a xx.xx.xx.xx:8888 -a.path=/buckets/img-b localhost:8888 -b.path=/buckets/img-isActivePassive`

The results are shown as follows (due to the production environment IP, the following content has been modified to xx.xx.xx.xx):
```
I0510 09:48:46 04008 filer_sync.go:150] start sync xx.xx.xx.xx:8888(-327560088) => localhost:8888(-40597861) from 2022-05-09 16:10:30.845158911 +0800 CST(1652083830845158911)
I0510 09:48:48 04008 filer_sync.go:175] sync xx.xx.xx.xx:8888 to localhost:8888 progressed to 2022-05-09 16:10:30.845218394 +0800 CST -1.60/sec
I0510 09:48:51 04008 filer_sync.go:175] sync xx.xx.xx.xx:8888 to localhost:8888 progressed to 2022-05-09 16:10:30.93586501 +0800 CST 76.12/sec
I0510 09:48:54 04008 filer_sync.go:175] sync xx.xx.xx.xx:8888 to localhost:8888 progressed to 2022-05-09 16:10:30.952436394 +0800 CST 242.30/sec
I0510 09:48:57 04008 filer_sync.go:175] sync xx.xx.xx.xx:8888 to localhost:8888 progressed to 2022-05-09 16:10:30.961465227 +0800 CST 1319.48/sec
I0510 09:49:00 04008 filer_sync.go:175] sync xx.xx.xx.xx:8888 to localhost:8888 progressed to 2022-05-09 16:10:31.061059838 +0800 CST 46.19/sec
I0510 09:49:03 04008 filer_sync.go:175] sync xx.xx.xx.xx:8888 to localhost:8888 progressed to 2022-05-09 16:10:31.093830161 +0800 CST 15.61/sec
```

**Screenshot of the issue in Chinese**
![github com_chrislusf_seaweedfs_issues_3036](https://user-images.githubusercontent.com/8565420/167528465-1d689408-1b30-403d-be05-84c0d6c2b45f.png)

**Comment by guo-sj** [comment]
Why not use English to describe this? This discussion may be useful to anybody in this community, so please use English to describe it which will make the discussion environment more harmonious and better.

**Comment by trojansun** [comment]
> Why not use English to describe this? This discussion may be useful to anybody in this community, so please use English to describe it which will make the discussion environment more harmonious and better.

My English is not very good, I'm afraid I can't express what I want.

**Comment by chrislusf** [comment]
Current `filer.sync` is single threaded. Need to parallelize it.

**Comment by trojansun** [comment]
> Current `filer.sync` is single threaded. Need to parallelize it.

Thanks, but when I run parallel they process the same files.

- 1
I0510 12:15:08 68026 filer_sync.go:175] sync xx.xx.xx.xx:8888 to localhost:8888 progressed to 2022-05-09 16:51:47.79919833 +0800 CST 57.98/sec
- 2
I0510 12:15:08 15451 filer_sync.go:175] sync xx.xx.xx.xx:8888 to localhost:8888 progressed to 2022-05-09 16:51:47.79919833 +0800 CST 46.39/sec

**Comment by chrislusf** [comment]
Sorry I wasn't clear. The code to parallelize it is not written yet.

**Comment by trojansun** [comment]
> Sorry I wasn't clear. The code to parallelize it is not written yet.
thanks
