### ISSUE TITLE
metrics 指标不全

### ISSUE THREAD

**Issue by EasonHe** [chrislusf/seaweedfs#3037]
**Additional context**

weed server -metricsPort=1234
weed master -metricsPort=1234
weed volume -metricsPort=1234
weed filer  -metricsPort=1234
发现grafana仪表盘中指标不全
1.要获取所有指标是不是  server   maste  volume 和filer 都得抓取,目前我只打开了filer 和S3 的1234 端口因为它们在一起启动.
2.如果有多节点需要都要配置prometheus 抓取指标么?

**Comment by chrislusf** [comment]
1. yes
2. yes

Or you can use `-metrics.address` to let nodes push metrics to a prometheus gateway.
