### ISSUE TITLE
Memory problems

### ISSUE THREAD

**Issue by LightCZ** [chrislusf/seaweedfs#304]
We wrote a simple .NET client for SeaweedFS and we plan to opensource it eventually (when things get a little bit polished), but we do have some problem.
Currently we run this on a computers with 1GB RAM available on Debian and we have SWAP turned OFF.  Everything works just fine for smaller files, but when we try to upload file larger than 1GB - the weed Volume process crash with out of memory fatal error:

Does this mean volume server actually tries to hold whole file in memory ? If so, then ... why, because this (at least according to my experience) wrong file handling. Shouldn't files be streamed directly to disk with only small buffer for each transfer in memory?

PS :There is a log of this crash

> fatal error: runtime: out of memory
> 
> runtime stack:
> runtime.throw(0x7ab278, 0x16)
>         /home/chris/apps/go/src/runtime/panic.go:530 +0x78
> runtime.sysMap(0x31090000, 0x20000000, 0x10c31e01, 0xa9a0d0)
>         /home/chris/apps/go/src/runtime/mem_linux.go:217 +0x15c
> runtime.(*mheap).sysAlloc(0xa8b800, 0x20000000, 0x10c20280)
>         /home/chris/apps/go/src/runtime/malloc.go:429 +0x13c
> runtime.(*mheap).grow(0xa8b800, 0x10000, 0x0)
>         /home/chris/apps/go/src/runtime/mheap.go:651 +0x68
> runtime.(*mheap).allocSpanLocked(0xa8b800, 0x10000, 0x8a7ac)
>         /home/chris/apps/go/src/runtime/mheap.go:553 +0x5b4
> runtime.(*mheap).alloc_m(0xa8b800, 0x10000, 0x0, 0x10c00401, 0xa8c048)
>         /home/chris/apps/go/src/runtime/mheap.go:437 +0x138
> runtime.(*mheap).alloc.func1()
>         /home/chris/apps/go/src/runtime/mheap.go:502 +0x40
> runtime.systemstack(0x10c31f70)
>         /home/chris/apps/go/src/runtime/asm_arm.s:261 +0xa8
> runtime.(*mheap).alloc(0xa8b800, 0x10000, 0x0, 0x10d90101, 0x90118)
>         /home/chris/apps/go/src/runtime/mheap.go:503 +0x58
> runtime.largeAlloc(0x1ffffe00, 0x1, 0x10c3c944)
>         /home/chris/apps/go/src/runtime/malloc.go:766 +0xb4
> runtime.mallocgc.func3()
>         /home/chris/apps/go/src/runtime/malloc.go:664 +0x34
> runtime.systemstack(0x10c14000)
>         /home/chris/apps/go/src/runtime/asm_arm.s:247 +0x80
> runtime.mstart()
>         /home/chris/apps/go/src/runtime/proc.go:1048
> 
> goroutine 23 [running]:
> runtime.systemstack_switch()
>         /home/chris/apps/go/src/runtime/asm_arm.s:192 +0x4 fp=0x10c3c888 sp=0x10c3c884
> runtime.mallocgc(0x1ffffe00, 0x603fe8, 0x1, 0x1)
>         /home/chris/apps/go/src/runtime/malloc.go:665 +0xa88 fp=0x10c3c8f8 sp=0x10c3c888
> runtime.newarray(0x603fe8, 0x1ffffe00, 0x10c3c94c)
>         /home/chris/apps/go/src/runtime/malloc.go:798 +0xe4 fp=0x10c3c918 sp=0x10c3c8f8
> runtime.makeslice(0x5fab50, 0x1ffffe00, 0x0, 0x1ffffe00, 0x0, 0x0, 0x0, 0x0)
>         /home/chris/apps/go/src/runtime/slice.go:32 +0x1d8 fp=0x10c3c940 sp=0x10c3c918
> bytes.makeSlice(0x1ffffe00, 0x0, 0x0, 0x0)
>         /home/chris/apps/go/src/bytes/buffer.go:198 +0x7c fp=0x10c3c970 sp=0x10c3c940
> bytes.(*Buffer).ReadFrom(0x10c3ca14, 0xb6eca8b8, 0x10f8b0b0, 0xffffe00, 0x0, 0x0, 0x0)
>         /home/chris/apps/go/src/bytes/buffer.go:170 +0xc0 fp=0x10c3c9c8 sp=0x10c3c970
> io/ioutil.readAll(0xb6eca8b8, 0x10f8b0b0, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
>         /home/chris/apps/go/src/io/ioutil/ioutil.go:33 +0x11c fp=0x10c3ca6c sp=0x10c3c9c8
> io/ioutil.ReadAll(0xb6eca8b8, 0x10f8b0b0, 0x0, 0x0, 0x0, 0x0, 0x0)
>         /home/chris/apps/go/src/io/ioutil/ioutil.go:42 +0x50 fp=0x10c3ca94 sp=0x10c3ca6c
> github.com/chrislusf/seaweedfs/go/storage.ParseUpload(0x10f6fc00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xd2300, 0x0, ...)
>         /home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/seaweedfs/go/storage/needle.go:76 +0x418 fp=0x10c3cb6c sp=0x10c3ca94
> github.com/chrislusf/seaweedfs/go/storage.NewNeedle(0x10f6fc00, 0x1, 0x10f7a960, 0x0, 0x0)
>         /home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/seaweedfs/go/storage/needle.go:141 +0x70 fp=0x10c3cc20 sp=0x10c3cb6c
> github.com/chrislusf/seaweedfs/go/weed/weed_server.(*VolumeServer).PostHandler(0x10d26050, 0xb6eca868, 0x10f9e200, 0x10f6fc00)
>         /home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/seaweedfs/go/weed/weed_server/volume_server_handlers_write.go:27 +0x394 fp=0x10c3cce8 sp=0x10c3cc20
> github.com/chrislusf/seaweedfs/go/weed/weed_server.(*VolumeServer).PostHandler-fm(0xb6eca868, 0x10f9e200, 0x10f6fc00)
>         /home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/seaweedfs/go/weed/weed_server/volume_server_handlers.go:37 +0x34 fp=0x10c3ccfc sp=0x10c3cce8
> github.com/chrislusf/seaweedfs/go/weed/weed_server.(*VolumeServer).privateStoreHandler(0x10d26050, 0xb6eca868, 0x10f9e200, 0x10f6fc00)
>         /home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/seaweedfs/go/weed/weed_server/volume_server_handlers.go:40 +0x2c0 fp=0x10c3cd20 sp=0x10c3ccfc
> github.com/chrislusf/seaweedfs/go/weed/weed_server.(*VolumeServer).(github.com/chrislusf/seaweedfs/go/weed/weed_server.privateStoreHandler)-fm(0xb6eca868, 0x10f9e200, 0x10f6fc00)
>         /home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/seaweedfs/go/weed/weed_server/volume_server.go:64 +0x34 fp=0x10c3cd34 sp=0x10c3cd20
> net/http.HandlerFunc.ServeHTTP(0x10c1ecd8, 0xb6eca868, 0x10f9e200, 0x10f6fc00)
>         /home/chris/apps/go/src/net/http/server.go:1618 +0x34 fp=0x10c3cd44 sp=0x10c3cd34
> net/http.(*ServeMux).ServeHTTP(0x10d31800, 0xb6eca868, 0x10f9e200, 0x10f6fc00)
>         /home/chris/apps/go/src/net/http/server.go:1910 +0x164 fp=0x10c3cd70 sp=0x10c3cd44
> net/http.serverHandler.ServeHTTP(0x10d261e0, 0xb6eca868, 0x10f9e200, 0x10f6fc00)
>         /home/chris/apps/go/src/net/http/server.go:2081 +0x190 fp=0x10c3cda0 sp=0x10c3cd70
> net/http.(*conn).serve(0x10fa23c0)
>         /home/chris/apps/go/src/net/http/server.go:1472 +0xee4 fp=0x10c3cfcc sp=0x10c3cda0
> runtime.goexit()
>         /home/chris/apps/go/src/runtime/asm_arm.s:990 +0x4 fp=0x10c3cfcc sp=0x10c3cfcc
> created by net/http.(*Server).Serve
>         /home/chris/apps/go/src/net/http/server.go:2137 +0x3bc
> 
> goroutine 1 [IO wait]:
> net.runtime_pollWait(0xb6f0b468, 0x72, 0x0)
>         /home/chris/apps/go/src/runtime/netpoll.go:160 +0x60
> net.(*pollDesc).Wait(0x10c0aab8, 0x72, 0x0, 0x0)
>         /home/chris/apps/go/src/net/fd_poll_runtime.go:73 +0x34
> net.(*pollDesc).WaitRead(0x10c0aab8, 0x0, 0x0)
>         /home/chris/apps/go/src/net/fd_poll_runtime.go:78 +0x30
> net.(*netFD).accept(0x10c0aa80, 0x0, 0xb6f0b518, 0x10f984c0)
>         /home/chris/apps/go/src/net/fd_unix.go:426 +0x21c
> net.(*TCPListener).AcceptTCP(0x10c1ed08, 0x122bb8, 0x0, 0x0)
>         /home/chris/apps/go/src/net/tcpsock_posix.go:254 +0x4c
> net.(*TCPListener).Accept(0x10c1ed08, 0x0, 0x0, 0x0, 0x0)
>         /home/chris/apps/go/src/net/tcpsock_posix.go:264 +0x34
> github.com/chrislusf/seaweedfs/go/util.(*Listener).Accept(0x10d31ce0, 0x0, 0x0, 0x0, 0x0)
>         /home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/seaweedfs/go/util/net_timeout.go:19 +0x54
> net/http.(*Server).Serve(0x10d261e0, 0xb6f0b4e0, 0x10d31ce0, 0x0, 0x0)
>         /home/chris/apps/go/src/net/http/server.go:2117 +0xfc
> net/http.Serve(0xb6f0b4e0, 0x10d31ce0, 0xb6f0b500, 0x10d31800, 0x0, 0x0)
>         /home/chris/apps/go/src/net/http/server.go:1976 +0x80
> main.runVolume(0xa83200, 0x10c4a078, 0x0, 0x0, 0x0)
>         /home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/seaweedfs/go/weed/volume.go:161 +0x13b0
> main.main()
>         /home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/seaweedfs/go/weed/weed.go:78 +0x64c
> 
> goroutine 18 [chan receive]:
> github.com/chrislusf/seaweedfs/go/glog.(*loggingT).flushDaemon(0xa87530)
>         /home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/seaweedfs/go/glog/glog.go:883 +0x60
> created by github.com/chrislusf/seaweedfs/go/glog.init.1
>         /home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/seaweedfs/go/glog/glog.go:410 +0x2cc
> 
> goroutine 6 [select]:
> github.com/chrislusf/seaweedfs/go/stats.(*ServerStats).Start(0x10d304a0)
>         /home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/seaweedfs/go/stats/stats.go:92 +0x390
> created by github.com/chrislusf/seaweedfs/go/weed/weed_server.init.1
>         /home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/seaweedfs/go/weed/weed_server/common.go:27 +0x50
> 
> goroutine 7 [syscall]:
> os/signal.signal_recv(0x0)
>         /home/chris/apps/go/src/runtime/sigqueue.go:116 +0x190
> os/signal.loop()
>         /home/chris/apps/go/src/os/signal/signal_unix.go:22 +0x14
> created by os/signal.init.1
>         /home/chris/apps/go/src/os/signal/signal_unix.go:28 +0x30
> 
> goroutine 8 [sleep]:
> time.Sleep(0x57435dc0, 0x1)
>         /home/chris/apps/go/src/runtime/time.go:59 +0x104
> github.com/chrislusf/seaweedfs/go/weed/weed_server.NewVolumeServer.func1(0x10d26050)
>         /home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/seaweedfs/go/weed/weed_server/volume_server.go:94 +0x5b8
> created by github.com/chrislusf/seaweedfs/go/weed/weed_server.NewVolumeServer
>         /home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/seaweedfs/go/weed/weed_server/volume_server.go:99 +0x874
> 
> goroutine 9 [select, locked to thread]:
> runtime.gopark(0x86ae68, 0x10c1cf8c, 0x744950, 0x6, 0x18, 0x2)
>         /home/chris/apps/go/src/runtime/proc.go:262 +0x148
> runtime.selectgoImpl(0x10c1cf8c, 0x0, 0xc)
>         /home/chris/apps/go/src/runtime/select.go:392 +0x1204
> runtime.selectgo(0x10c1cf8c)
>         /home/chris/apps/go/src/runtime/select.go:215 +0x10
> runtime.ensureSigM.func1()
>         /home/chris/apps/go/src/runtime/signal1_unix.go:279 +0x428
> runtime.goexit()
>         /home/chris/apps/go/src/runtime/asm_arm.s:990 +0x4
> 
> goroutine 10 [chan receive]:
> main.OnInterrupt.func1(0x10c0ab40, 0x10c1ed10)
>         /home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/seaweedfs/go/weed/signal_handling.go:25 +0x40
> created by main.OnInterrupt
>         /home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/seaweedfs/go/weed/signal_handling.go:29 +0x374
> 
> goroutine 21 [IO wait]:
> net.runtime_pollWait(0xb6f0b3f0, 0x72, 0x10cc3000)
>         /home/chris/apps/go/src/runtime/netpoll.go:160 +0x60
> net.(*pollDesc).Wait(0x10c4a938, 0x72, 0x0, 0x0)
>         /home/chris/apps/go/src/net/fd_poll_runtime.go:73 +0x34
> net.(*pollDesc).WaitRead(0x10c4a938, 0x0, 0x0)
>         /home/chris/apps/go/src/net/fd_poll_runtime.go:78 +0x30
> net.(*netFD).Read(0x10c4a900, 0x10cc3000, 0x1000, 0x1000, 0x0, 0xb6ec6018, 0x10c50000)
>         /home/chris/apps/go/src/net/fd_unix.go:250 +0x1c4
> net.(*conn).Read(0x10c4ca80, 0x10cc3000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
>         /home/chris/apps/go/src/net/net.go:172 +0xc8
> net/http.noteEOFReader.Read(0xb6eca6e8, 0x10c4ca80, 0x10cfc5e4, 0x10cc3000, 0x1000, 0x1000, 0x10c00b60, 0x0, 0x0)
>         /home/chris/apps/go/src/net/http/transport.go:1683 +0x5c
> net/http.(*noteEOFReader).Read(0x10caa600, 0x10cc3000, 0x1000, 0x1000, 0x10c3ee14, 0x0, 0x0)
>         <autogenerated>:284 +0xd0
> bufio.(*Reader).fill(0x10c573b0)
>         /home/chris/apps/go/src/bufio/bufio.go:97 +0x1c4
> bufio.(*Reader).Peek(0x10c573b0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
>         /home/chris/apps/go/src/bufio/bufio.go:132 +0xcc
> net/http.(*persistConn).readLoop(0x10cfc5b0)
>         /home/chris/apps/go/src/net/http/transport.go:1069 +0x158
> created by net/http.(*Transport).dialConn
>         /home/chris/apps/go/src/net/http/transport.go:853 +0xdc0
> 
> goroutine 22 [select]:
> net/http.(*persistConn).writeLoop(0x10cfc5b0)
>         /home/chris/apps/go/src/net/http/transport.go:1273 +0x344
> created by net/http.(*Transport).dialConn
>         /home/chris/apps/go/src/net/http/transport.go:854 +0xddc
>

**Comment by chrislusf** [comment]
The large files should be split into chunks and saved. In "weed upload" command is an example on how to do this.

Streaming to disk would not allow high concurrency.

**Comment by LightCZ** [comment]
I understand, so... is there any API documentation for chunks upload? I know how to do that with weed upload command, but thats pretty much no use for us, since we are writing our .NET client

**Comment by chrislusf** [comment]
Updated the other related issue for documentation. Let me know if something is not clear.
