### ISSUE TITLE
volume服务及数据迁移到到其它台服务器后启动成功后历史数据访问不存在

### ISSUE THREAD

**Issue by wellyn-chen** [chrislusf/seaweedfs#3041]
<Message>The specified key does not exist.</Message>

**Comment by chrislusf** [comment]
so the migration is not successful.

**Comment by wellyn-chen** [comment]
但是新的数据可以正常保存和读取，我再次重启迁移前的服务和数据依然访问不了？ 请问有什么方式可以处理的？

**Comment by wellyn-chen** [comment]
> so the migration is not successful.

新的数据可以正常保存和读取，我再次重新启动迁移前的服务和数据仍然无法处理？
