### ISSUE TITLE
backup volume disk usage

### ISSUE THREAD

**Issue by zemul** [chrislusf/seaweedfs#3044]
**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
master : weed master -mdir=/export/data/seaweedfs/master/mdir1 -peers=10.17.100.28:9333,10.17.100.29:9333,10.17.100.30:9333 -port=9333 -volumeSizeLimitMB=5000 -defaultReplication=001

- OS version.  [centos7]
- output of `weed version`   [version 30GB 2.88  linux amd64]

**Describe the bug**
command : weed backup -dir=. -collection=qqqq -volumeId=3273
Master Set volumeSizeLimitMB =5000, if voulme CompactionRevision is greater than 0，Backup file size =30G，I don't actually use that much

<img width="588" alt="image" src="https://user-images.githubusercontent.com/43405321/168020277-26e62c1d-cad0-4341-9cf1-1ee8cc6170a2.png">

/vol/status result:
{
"Id": 3273,
"Size": 4168,
"ReplicaPlacement": {
"node": 1
},
"Ttl": {
"Count": 0,
"Unit": 0
},
"DiskType": "",
"Collection": "qqqq",
"Version": 3,
"FileCount": 3,
"DeleteCount": 0,
"DeletedByteCount": 0,
"ReadOnly": false,
"CompactRevision": 2,
"ModifiedAtSecond": 1650448176,
"RemoteStorageName": "",
"RemoteStorageKey": ""
}

I suspect that's the problem, but I don't understand 

<img width="979" alt="image" src="https://user-images.githubusercontent.com/43405321/168020570-80b2e043-98af-4191-a45a-9041212ea993.png">

**Comment by chrislusf** [comment]
Thanks for the good details! Added a fix to remove the pre-allocation for backup.
