### ISSUE TITLE
Documentation for batch API

### ISSUE THREAD

**Issue by LightCZ** [chrislusf/seaweedfs#305]
We are writing .NET client for SeaweedFS and we would appreciate if there would be more elaborate documentation about file multipart upload API. We know that native client (in weed file) supports slicing file to chunks and parallel upload them (which is documented ... at least a little) but we would appreciate more developer API for this process, so we would not reverse-engineer your code. It would greatly help and so we would be able to integrate this into .NET client.

**Comment by chrislusf** [comment]
Thanks for your request and help on the client library!

Added here:

https://github.com/chrislusf/seaweedfs/wiki/Large-File-Handling

**Comment by LightCZ** [comment]
Just a quick question:
In the struct for chunk upload you are using "fid" which means "FileId" assigned by master (I suppose)
But when you are uploading Chunk manifest, its unclear what is final File id of submited file.
Also you have to go to master, with each chunk to get their FileId (i get this) but are you required to upload every chunk to the same volume or can you upload each chunk to different volume.

Let me cite your structures:
```
type ChunkInfo struct {
    Fid    string `json:"fid"`
    Offset int64  `json:"offset"`
    Size   int64  `json:"size"`
}

type ChunkList []*ChunkInfo

type ChunkManifest struct {
    Name   string    `json:"name,omitempty"`
    Mime   string    `json:"mime,omitempty"`
    Size   int64     `json:"size,omitempty"`
    Chunks ChunkList `json:"chunks,omitempty"`
}
```

**Comment by chrislusf** [comment]
The final FileId, which is the FileId used to access the file, is the FileId used to store the manifest file.

Each chunk can go to different volumes.

I will add these to the doc also.

**Comment by LightCZ** [comment]
One more question and I hope I ll have the whole picture about chunking upload.

Is it totally OK to upload chunks to different volumes with TimeToLive (TTL) but the manifest without it? This would be totally cool so if suddenly the splitting part fail, or something go wrong seaweed will clear parts of the unfinished file?

**Comment by chrislusf** [comment]
Interesting idea! Totally possible but not implemented, yet.

**Comment by LightCZ** [comment]
Converted to another issue so this would not get lost in history. This is really Must Have feature for multipart  upload and since you already have all pieces of puzzle (TTL, multipart, manifests...) it should not be so hard :
 #308 
Thanks anyway
