### ISSUE TITLE
Benchmark result seems not good, how can I make optimization

### ISSUE THREAD

**Issue by ningfdx** [chrislusf/seaweedfs#3069]
**Describe**
I deploy a SeaweedFS cluster, 4 machine with 4*8TB HDD disk, 3 mster + 3filer + 4 ** 4=16 volume server
And when I finish deploy and run some test on it, I found the io performance is wired.
The read rate is very slow.
![Screenshot from 2022-05-17 11-35-17](https://user-images.githubusercontent.com/17705801/168723421-2d0babc4-0e02-4014-985f-146bbd0970ec.png)

![Screenshot from 2022-05-17 11-05-53](https://user-images.githubusercontent.com/17705801/168720276-5798b043-8828-428d-a30c-9db55e851852.png)

**System Setup**
./weed master -mdir=/seaweedfs/master -ip={{ansible_host}} -port=9333 -peers={{masters_ip_str}}
./weed volume -dir=/data -ip={{ansible_host}} -max=0 -port=808{{item}} -mserver={{masters_ip_str}}
./weed filer -ip={{ansible_host}} -port=8888 -master={{masters_ip_str}}
fuse mount command is weed mount -filer=192.168.1.173:8888,192.168.1.172:8888,192.168.1.171:8888 -dir=/storage/adfs -filer.path=/testcase -collection=test-collection

![Screenshot from 2022-05-17 11-08-15](https://user-images.githubusercontent.com/17705801/168721877-39986144-754a-4be0-a915-1823846b64e4.png)

- OS version: Ubuntu 20.04.1 LTS
- output of `weed version` version 30GB 3.02 a4ca3ed1f0c2bcde1d36bb48f81dedc3e1924679 linux amd64
- if using filer, show the content of `filer.toml`
![Screenshot from 2022-05-17 11-10-34](https://user-images.githubusercontent.com/17705801/168720641-e7535312-c9da-4fc8-a8f9-fcdd73c34a67.png)

**Expected behavior**
Expect the benchmark be normal like https://github.com/chrislusf/seaweedfs/wiki/FUSE-Mount

**Additional context**
To avoid machine reason affect result, I pick another SSD machine, run the follw command to test io performance, got the same result.
./weed server -dir="/data/fs" -filer -s3 -volume.concurrentUploadLimitMB=1024 -volume.concurrentDownloadLimitMB=1024 -volume.compactionMBps=1024 -volume.fileSizeLimitMB=1024 -volume.max=0
./weed mount -filer=localhost:8888 -dir=/data/mountpoint -filer.path=/ 
File operations:
    reads/s:                      24.22
    writes/s:                     16.16
    fsyncs/s:                     53.20

Throughput:
    read, MiB/s:                  24.22
    written, MiB/s:               16.16

and the result run on the phisical SSD disk
File operations:
    reads/s:                      229.16
    writes/s:                     152.77
    fsyncs/s:                     488.89

Throughput:
    read, MiB/s:                  229.16
    written, MiB/s:               152.77

I have read the method in the https://github.com/chrislusf/seaweedfs/wiki/Optimization, but the test  result seems does's affected.

If you can provide the command and phisical hardware params in https://github.com/chrislusf/seaweedfs/wiki/FUSE-Mount, I'm glad to test with those params more times.

**Comment by chrislusf** [comment]
Totally random read write is slow. No good way to optimize unless you want to cache the whole file.

**Comment by ningfdx** [comment]
Thanks for your reply! Random Read/Write is slow, I agree with your opinion.
Well cause the issue content is too much to fully read, there have other 2 things.

1: sequence read is very slow since sequence write is fast.
![Screenshot from 2022-05-17 11-35-17](https://user-images.githubusercontent.com/17705801/168748220-263a592f-1005-4621-bb09-fc0fd1a23e73.png)

2: Why the same sysbench command and the SSD, my bench result is 1/50 than https://github.com/chrislusf/seaweedfs/wiki/FUSE-Mount#sysbench-benchmark-results .Is my cluster using the wrong options?
