### ISSUE TITLE
why start new cluster when joining peers failed? 

### ISSUE THREAD

**Issue by hankya** [chrislusf/seaweedfs#307]
Considering this scenario:

* I have a three node new cluster with flags -master.peers=localhost:9333,localhost:9334,localhost:9335
* Because of network partition, node 9333 lost connection with the rest two nodes, then 9333 get restarted for some reason and become a new leader
* Now we have two leaders among these three nodes, vids could get messed up (volume grow) with new coming traffic

A safer way is, when a node couldn't join a cluster, it shouldn't automatically stated as new cluster unless explicitly specified (a flag like --force-new-cluster )

Thank you!

**Comment by chrislusf** [comment]
Currently setting "-peers" means removing the old cluster configurations.

I need to change code so that removing the old cluster configurations only when "-peers" is set and different from last setting.
