### ISSUE TITLE
Records after ttl continue to be stored in the filer database

### ISSUE THREAD

**Issue by LuckyFrost** [chrislusf/seaweedfs#3075]
Filer database: MySql
fs.configure 
```{
  "locations": [
    {
      "locationPrefix": "/buckets/s3-test_ttl_10m",
      "ttl": "10m"
    }
  ]
}
```
- Added file s3-test_ttl_10m/12345 via s3
- Volume deleted itself after 10+ minutes
- Now when I try to get the file I get a 50x error and error in the filler logs:
``` failed to stream content /buckets/s3-test_ttl_10m/12345: volume 17 not found```
And the filer's database continues to store information about this file.

So, is this functionality not working? Because the database will forever accumulate garbage

**Comment by LuckyFrost** [comment]
Hi @chrislusf , I found bug, fs.configure does not apply to multipart uploads via s3. How to reproduce:

```dd if=/dev/urandom of=/tmp/1 bs=100M count=2 iflag=fullblock```
```/usr/local/bin/aws --endpoint-url http://localhost:8333 s3 cp /tmp/1 s3://s3-test_ttl_10m/test1```

Done: ttl not assigned to file test1 (But TTL works correctly on small files)

Additional info:

```
/opt/weed version
version 8000GB 3.04 9ff0d9900288a2dc92d3a82256fb3f359be20d3b linux amd64
```

```fs.configure -locationPrefix=/buckets/s3-test_ttl_10m/ -ttl 10m -apply```

filer db: cassandra

How I'm checking ttl: through file availability or
```cqlsh> select directory,name,TTL(meta) from seaweedfs.filemeta where directory='/buckets/s3-test_ttl_10m';```

**Comment by superadmin1234** [comment]
@LuckyFrost, Hi!
https://github.com/chrislusf/seaweedfs/wiki/Filer-Stores <= here everywhere where "yes" - it does not work and you need those that are "native"

@chrislusf I can also confirm that fs.configure ttl does not work when using multipart.

**Comment by LuckyFrost** [comment]
Looks like it doesn't work.
```
git clone https://github.com/chrislusf/seaweedfs.git
go install -tags 5BytesOffset
/root/go/bin/weed filer -s3
echo "fs.configure" | /opt/weed shell
master: localhost:9333 filers: [xx.xx.xx.xx:8888]
{
  "locations": [
    {
      "locationPrefix": "/buckets/s3-test_ttl_10m/",
      "ttl": "10m"
    },
  ]
}

dd if=/dev/urandom of=/tmp/1 bs=100M count=2 iflag=fullblock
usr/local/bin/aws --endpoint-url http://localhost:8333 s3 cp /tmp/1 s3://s3-test_ttl_10m/test8_big
upload: ../../../../tmp/1 to s3://s3-test_ttl_10m/test8_big

cqlsh> select directory,name,TTL(meta) from seaweedfs.filemeta where directory='/buckets/s3-test_ttl_10m';
 directory                | name            | ttl(meta)
--------------------------+-----------------+-----------
 /buckets/s3-test_ttl_10m |        .uploads |      null
 /buckets/s3-test_ttl_10m |       test6_big |      null
 /buckets/s3-test_ttl_10m |       test8_big |      null
```
Am I doing something wrong?

**Comment by chrislusf** [comment]
added 8402af0882ea33d840d3bb4b386b3bf665cdf615, please help to test.

**Comment by LuckyFrost** [comment]
I did some quick tests and it works!
Thank you!

**Comment by shsamkit** [comment]
Hi @superadmin1234 , 

>  https://github.com/chrislusf/seaweedfs/wiki/Filer-Stores <= here everywhere where "yes" - it does not work and you need those that are "native"

I am using postgres2, which is also marked `yes` under `TTL` so I am observing a similar behaviour where the entries for files deleted with ttl aren't deleted from the filer datastore. I do however see that once I query a specific file, that's deleted with ttl, via `fs.meta.cat`, sql does get around to deleting that file. Since that's the expected behaviour; is there a way to leverage this to delete the actual datastore entries? 

p.s. The note on the same table says "Easy to manage" for postgresql, is that in regards to easy to delete entries manually?
