### ISSUE TITLE
Support for TimeToLive for multipart upload

### ISSUE THREAD

**Issue by LightCZ** [chrislusf/seaweedfs#308]
When uploading new multipart upload it would be cool to upload chunks with TTL (Time To Live) but when finished by uploading manifest, it should change all parts TTL to ManifestTTL (Or reset TTL on chunks, when manifest does not have any). This way would be possible to clean after failed multipart upload and chunks will be automatically deleted, if no manifest was ever uploaded.

Should not be hard to implement.

**Comment by chrislusf** [comment]
Thanks for creating this!

**Comment by chrislusf** [comment]
changing ttl is not supported since each part's TTL is determined by the volume. Unless you want to move it to a different volume...
