### ISSUE TITLE
go: github.com/seaweedfs/goexif@v2.0.0+incompatible: reading github.com/seaweedfs/goexif/go.mod at revision v2.0.0: unknown revision v2.0.0

### ISSUE THREAD

**Issue by figbin** [chrislusf/seaweedfs#3087]
seaweedfs-3.05 / Mac OS

% make all
cd weed; go install
go: github.com/seaweedfs/goexif@v2.0.0+incompatible: reading github.com/seaweedfs/goexif/go.mod at revision v2.0.0: unknown revision v2.0.0
make: *** [install] Error 1

**Comment by chrislusf** [comment]
very likely your local build issue.
