### ISSUE TITLE
New filer only syncs a subset of files

### ISSUE THREAD

**Issue by paularlott** [chrislusf/seaweedfs#3089]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs
Report issues here. Ask questions here https://stackoverflow.com/questions/tagged/seaweedfs
Please ask questions in https://github.com/chrislusf/seaweedfs/discussions

example of a good issue report:
https://github.com/chrislusf/seaweedfs/issues/1005
example of a bad issue report:
https://github.com/chrislusf/seaweedfs/issues/1008

**Describe the bug**

I have created 2 filers using filer.toml of 

```
[filer.options]
recursive_delete = false

[leveldb2]
enabled = true
dir = "./filerldb2"
```

I've created around 20,000 files over 4,000 directories. Both filers show the correct list of files as expected, checked via the web interface on the filers.

I create a 3rd filer with the same filer.toml, when it starts it pulls data from the other filers as expected, however it completes with only a partial tree. Again checked by the web interface of the filer and by weed mount.

If I have a mount point already open I can issue `touch <file>` and the files I touch will appear in the new filer.

Restarting the new filer doesn't pull in any additional file meta data. There's no errors shown.

A second issue is starting with 2 filers, stopping one, writing additional files then restarting the stopped filer can cause a mismatch in the file tree, i.e some of the new files written are not pulled into the restarted filer.

**System Setup**

OS: Ubuntu 20.04
SeaweedFS: 3.06 also fails in 3.02

I have 1 master:

```
weed master -ip=1.2.3.4 -ip.bind=0.0.0.0 -mdir=./master -defaultReplication=001 -volumeSizeLimitMB=30000
```

3 volume servers

```
weed volume -dir=/srv/seaweedfs -mserver=1.2.3.4:9333 -max=0 -ip=192.168.8.50 -ip.bind=0.0.0.0
weed volume -dir=/srv/seaweedfs -mserver=1.2.3.4:9333 -max=0 -ip=192.168.8.51 -ip.bind=0.0.0.0
weed volume -dir=/srv/seaweedfs -mserver=1.2.3.4:9333 -max=0 -ip=192.168.8.52 -ip.bind=0.0.0.0
```

2 then 3 filers

```
weed filer -master=1.2.3.4:9333 -defaultReplicaPlacement=001
weed filer -master=1.2.3.4:9333 -defaultReplicaPlacement=001
weed filer -master=1.2.3.4:9333 -defaultReplicaPlacement=001
```

There's 3 VMs running this, 1 has master + volume + filer, the other 2 are volume + filer.

All VMs are on the same network, there's no firewalls etc.

**Expected behavior**

As per the documentation I'd expect the 3rd filer to start and load the entire file meta data from the other filers.

**Comment by coelho** [comment]
I believe I am seeing this issue as well in a production environment.

Setup:

- Kubernetes
- Version: 3.0.4
- 3x Master
- 3x Filer (storage: `mysql` [also tried `redis3_cluster`])
- 3x Volume (index: `leveldb`)
- FUSE Mount (via CSI) in a Pod (with 3x Filers)

A directory listing with metadata in a large tree returns a seemingly random subset of files. Every time executed, it returns a different sub-set. Restarting Masters/Filers/Volumes has no effect.

This is more specifically a Docker Registry.
Example workload is: `registry garbage-collect -m /etc/docker/registry/config.yml -d` (dry run)

Executing this multiple times (in the same Pod) returns any random number of files to prune, even though the directory is not changing (no writes):

```
1002 blobs marked, 2146 blobs and 718 manifests eligible for deletion
996 blobs marked, 2152 blobs and 717 manifests eligible for deletion
1022 blobs marked, 2125 blobs and 718 manifests eligible for deletion
```

The issue also seems to get worse over time. More and more files are lost, even though there are no writes.

This seems urgent @chrislusf ?

**Comment by chrislusf** [comment]
these are two different issues.

**Comment by chrislusf** [comment]
what are the results of `cluster.ps` and ``cluster.check` in `weed shell`?

**Comment by paularlott** [comment]
```
> cluster.ps
the cluster has 3 filers
  * 192.168.8.52:8888 (30GB 3.06 2f846777bbceea307771e79d4452e071b0bd5a51)
  * 192.168.8.50:8888 (30GB 3.06 2f846777bbceea307771e79d4452e071b0bd5a51)
  * 192.168.8.51:8888 (30GB 3.06 2f846777bbceea307771e79d4452e071b0bd5a51)

> cluster.check
Topology volumeSizeLimit:30000 MB hdd(volume:12/12 active:12 free:0 remote:0)
the cluster has 3 filers: [192.168.8.51:8888 192.168.8.52:8888 192.168.8.50:8888]
the cluster has 3 volume servers: [192.168.8.52:8080 192.168.8.50:8080 192.168.8.51:8080]
checking master 192.168.8.50:9333 to volume server 192.168.8.52:8080 ... ok round trip 3.000ms clock delta 1.230ms
checking master 192.168.8.50:9333 to volume server 192.168.8.50:8080 ... ok round trip 0.539ms clock delta 0.190ms
checking master 192.168.8.50:9333 to volume server 192.168.8.51:8080 ... ok round trip 4.920ms clock delta 1.501ms
checking volume server 192.168.8.52:8080 to master 192.168.8.50:9333 ... ok round trip 1.291ms clock delta 0.101ms
checking volume server 192.168.8.50:8080 to master 192.168.8.50:9333 ... ok round trip 0.186ms clock delta 0.036ms
checking volume server 192.168.8.51:8080 to master 192.168.8.50:9333 ... ok round trip 1.995ms clock delta 0.456ms
checking filer 192.168.8.51:8888 to master 192.168.8.50:9333 ... ok round trip 1.954ms clock delta 0.641ms
checking filer 192.168.8.52:8888 to master 192.168.8.50:9333 ... ok round trip 1.043ms clock delta -0.226ms
checking filer 192.168.8.50:8888 to master 192.168.8.50:9333 ... ok round trip 0.203ms clock delta 0.022ms
checking filer 192.168.8.51:8888 to volume server 192.168.8.52:8080 ... ok round trip 2.578ms clock delta 1.073ms
checking filer 192.168.8.51:8888 to volume server 192.168.8.50:8080 ... ok round trip 4.879ms clock delta 2.107ms
checking filer 192.168.8.51:8888 to volume server 192.168.8.51:8080 ... ok round trip 1.411ms clock delta 0.600ms
checking filer 192.168.8.52:8888 to volume server 192.168.8.52:8080 ... ok round trip 0.782ms clock delta 0.131ms
checking filer 192.168.8.52:8888 to volume server 192.168.8.50:8080 ... ok round trip 0.824ms clock delta -0.096ms
checking filer 192.168.8.52:8888 to volume server 192.168.8.51:8080 ... ok round trip 0.560ms clock delta 0.017ms
checking filer 192.168.8.50:8888 to volume server 192.168.8.52:8080 ... ok round trip 2.807ms clock delta 1.211ms
checking filer 192.168.8.50:8888 to volume server 192.168.8.50:8080 ... ok round trip 0.370ms clock delta 0.139ms
checking filer 192.168.8.50:8888 to volume server 192.168.8.51:8080 ... ok round trip 4.618ms clock delta 1.179ms
checking volume server 192.168.8.52:8080 to 192.168.8.50:8080 ... ok round trip 2.991ms clock delta 0.965ms
checking volume server 192.168.8.52:8080 to 192.168.8.51:8080 ... ok round trip 2.003ms clock delta 0.563ms
checking volume server 192.168.8.50:8080 to 192.168.8.52:8080 ... ok round trip 2.129ms clock delta 0.892ms
checking volume server 192.168.8.50:8080 to 192.168.8.51:8080 ... ok round trip 4.845ms clock delta 1.336ms
checking volume server 192.168.8.51:8080 to 192.168.8.52:8080 ... ok round trip 1.487ms clock delta 0.586ms
checking volume server 192.168.8.51:8080 to 192.168.8.50:8080 ... ok round trip 5.149ms clock delta 2.085ms
checking filer 192.168.8.51:8888 to 192.168.8.51:8888 ... ok round trip 0.320ms clock delta 0.005ms
checking filer 192.168.8.51:8888 to 192.168.8.52:8888 ... ok round trip 0.646ms clock delta 0.200ms
checking filer 192.168.8.51:8888 to 192.168.8.50:8888 ... ok round trip 1.681ms clock delta 0.451ms
checking filer 192.168.8.52:8888 to 192.168.8.51:8888 ... ok round trip 0.696ms clock delta -0.069ms
checking filer 192.168.8.52:8888 to 192.168.8.52:8888 ... ok round trip 0.868ms clock delta 0.221ms
checking filer 192.168.8.52:8888 to 192.168.8.50:8888 ... ok round trip 0.758ms clock delta -0.095ms
checking filer 192.168.8.50:8888 to 192.168.8.51:8888 ... ok round trip 1.648ms clock delta -0.311ms
checking filer 192.168.8.50:8888 to 192.168.8.52:8888 ... ok round trip 1.047ms clock delta 0.222ms
checking filer 192.168.8.50:8888 to 192.168.8.50:8888 ... ok round trip 0.112ms clock delta 0.013ms
> 
```

**Comment by paularlott** [comment]
If it matters, http://192.168.8.50:8888/ is the filer that was added and only pulled in a subset of the files in this test.

**Comment by chrislusf** [comment]
how did you start the mount?

were you able to setup some docker compose to reproduce this problem?

**Comment by paularlott** [comment]
Mount I used:

On macOS:
```
weed mount -filer=192.168.8.50:8888,192.168.8.51:8888,192.168.8.52:8888 -filer.path=/ -dir=~/weed -map.uid=501:1000 -map.gid=20:1000
```

On Ubuntu 20.04:

```
weed mount -filer=192.168.8.50:8888,192.168.8.51:8888,192.168.8.52:8888 -filer.path=/ -dir=~/weed
```

I've not tried running this in docker as my intent has always been to run the masters, volume servers and filers inside Linux Containers (LXC) or if that didn't work VMs.

I don't think the mount has anything to do with it as without mounting the file system you can see the filers are not in sync via their web interfaces. I assume you don't need mount for filers to sync up as you wouldn't be using mount if using the S3 interface on filers?

**Comment by paularlott** [comment]
@chrislusf I think the following sequence breaks the filers every time using the original setup of 1 master, 3 volume servers.

- Start 2 filers
- mount the file system, listing the IPs of all 3 filers even though only 2 are up at this point
- Copy files to the mount point, `cp -r folder /mnt/folder`
- Duplicate a folder on the mount point, `cp -r /mnt/folder /mnt/folder2`
- Start a 3rd filer, it will sync
- Stop the original 2 filers and delete everything, their filerldb2 folder.
- Rename a folder on the mount `mv /mnt/folder2 /mnt/something-else`
- Start the original 2 filers they will sync some but not all the data from the 3rd filer, it looks like they only sync what has been touched while they were down. Via the web interface something-else will be present but folder has gone on both filers.

Thanks,
Paul

**Comment by chrislusf** [comment]
could not reproduce. how large are the folders when renaming?

**Comment by paularlott** [comment]
The folder has about 7,935 items in it and 32MB ish, it's a copy of https://github.com/paularlott/fusionCSS that I'm copying to the mount point. Then duplicating on the mount point and finally renaming.

After then mv command and the restart of the other filers, only something-else syncs to the new filers, all the files are there. However folder is missing as is all the files in it. If I look on the filer that didn't get restarted I can see folder and something-else in its web interface along with all the files.

I'm running with -v 4 so I'm waiting for all activity to stop before I kill anything, I also can't see references to folder during the replay on the restarted filers.

**Comment by paularlott** [comment]
Not sure if this helps but I've been trying to narrow this down, this time one of the filers started fine and the other filer showed in the log meta replay as deleting the old name of the renamed folder:

```
I0526 21:58:04 20304 meta_replay.go:17] deleting /1234-wffewf-wfew-fef-ewf
```

However in the web interface it shows that folder still exists and not under the renamed name:

![SeaweedFS Filer 2022-05-26 22-09-15](https://user-images.githubusercontent.com/5309549/170504813-019b7b18-0b78-420a-a6f2-b6e559377fe3.png)

It can be fixed by running the following on the mount point:

```
find . -name "*" -exec touch {} \;
```

As best as I can tell there a time component in this. If you let the 1st filer fully start then start the 2nd it works every time, if you start the 2nd filer while the 1st is still replaying the logs that's when I get partial sync, missing files etc. The more you operator on the file system the longer the replay logs get and the easier it seems to be to trigger.

**Comment by chrislusf** [comment]
we are getting closer. Yes, there is a time value used to replay the metadata logs. If the amount of metadata is small, it'll be hard to reproduce.

**Comment by ldapomni** [comment]
It seems the same #2437. Filler sync problem.

**Comment by paularlott** [comment]
I've not been able to narrow this down any further, all I can say for sure is that if you keep renaming the top level folder the meta data grows and the issue can be replicated every time for me.

**Comment by paularlott** [comment]
Sorry, it looks like there's still an issue with this, but I we're closer.

I've pulled master and rebuilt SeaweedFS, destroyed the cluster and started clean.

Running 3 filers:

```
cp -r Code/fusionCSS/ /mnt/
cp -r /mnt/fusionCSS /mnt/fusionCSS2
ls /mnt
```

Stop 2 filers:

```
mv /mnt/fusionCSS2 /mnt/fusionCSS3
mv /mnt/fusionCSS3 /mnt/fusionCSS4
touch /mnt/testing
touch /mnt/another
mkdir -p /mnt/a/b/c/d
```

Delete the filerldb2 folders of the 2 stopped filers and start them again with minimal delay between starting.

Filer that didn't get stopped:

![SeaweedFS Filer 2022-05-30 09-43-04](https://user-images.githubusercontent.com/5309549/170902430-27736c01-7e75-47ff-b396-eb5a7c7ca264.png)

Filers that got stopped:

![SeaweedFS Filer 2022-05-30 09-43-29](https://user-images.githubusercontent.com/5309549/170902453-bb78368d-8349-4fcd-af55-531573079bf1.png)

So it synced over the files that I touched while the two filers were stopped but failed to pull over the untouched free.

Also tried just restarting just 1 of the two stopped filers but it yields the same results of a partial sync.

**Comment by chrislusf** [comment]
Please try the 3.08 version

**Comment by CsterKuroi** [comment]
similar issue after
1. `mv filerldb2/ filerldb2-test-lost/` 
2. restart filer
3. only syncs a subset of files
![image](https://user-images.githubusercontent.com/12230174/224602497-ab8f8590-51c4-4880-8d99-7d3d0f6c5cd9.png)

**Comment by chrislusf** [comment]
@CsterKuroi what files are missing? It's not possible to debug by the screenshot.

**Comment by CsterKuroi** [comment]
@chrislusf 
Just some test files uploaded by `warp`
```
warp put --obj.size=10KiB --duration=12h --noclear --bucket=warp-benchmark --host=127.0.0.1:8333 --access-key=<access>--secret-key=<secret>
```
And after step 1 2. 3 metioned above, filer only syncs a subset of files.
Trying TiKV to temporarily circumvent this issue as i'm new to weed.
