### ISSUE TITLE
[filer] filer's cpu consumption is very high

### ISSUE THREAD

**Issue by paochiang** [chrislusf/seaweedfs#3098]
**Describe the bug**
filer's cpu consumption  is very high

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
 setup in k8s, 3 filers、3 masters
```
filer-0:
/usr/bin/weed -logdir=/logs -v=1 filer -port=8888 -metricsPort 9327 -dirListLimit=100000 -defaultReplicaPlacement=002 -ip=10.244.208.155 -master=seaweedfs-master-0.seaweedfs-master:9333,seaweedfs-master-1.seaweedfs-master:9333,seaweedfs-master-2.seaweedfs-master:9333
filer-1:
/usr/bin/weed -logdir=/logs -v=1 master -port=9333 -mdir=/data -ip.bind=0.0.0.0 -defaultReplication=002 -volumeSizeLimitMB=30000 -metrics.intervalSeconds=15 -ip=seaweedfs-master-2.seaweedfs-master -peers=seaweedfs-master-0.seaweedfs-master:9333,seaweedfs-master-1.seaweedfs-master:9333,seaweedfs-master-2.seaweedfs-master:9333
filer-2:
/usr/bin/weed -logdir=/logs -v=1 filer -port=8888 -metricsPort 9327 -dirListLimit=100000 -defaultReplicaPlacement=002 -ip=10.244.67.93 -master=seaweedfs-master-0.seaweedfs-master:9333,seaweedfs-master-1.seaweedfs-master:9333,seaweedfs-master-2.seaweedfs-master:9333
master-0:
/usr/bin/weed -logdir=/logs -v=1 master -port=9333 -mdir=/data -ip.bind=0.0.0.0 -defaultReplication=002 -volumeSizeLimitMB=30000 -metrics.intervalSeconds=15 -ip=seaweedfs-master-0.seaweedfs-master -peers=seaweedfs-master-0.seaweedfs-master:9333,seaweedfs-master-1.seaweedfs-master:9333,seaweedfs-master-2.seaweedfs-master:9333
master-1:
/usr/bin/weed -logdir=/logs -v=1 master -port=9333 -mdir=/data -ip.bind=0.0.0.0 -defaultReplication=002 -volumeSizeLimitMB=30000 -metrics.intervalSeconds=15 -ip=seaweedfs-master-1.seaweedfs-master -peers=seaweedfs-master-0.seaweedfs-master:9333,seaweedfs-master-1.seaweedfs-master:9333,seaweedfs-master-2.seaweedfs-master:9333
master-2:
/usr/bin/weed -logdir=/logs -v=1 filer -port=8888 -metricsPort 9327 -dirListLimit=100000 -defaultReplicaPlacement=002 -ip=10.244.164.43 -master=seaweedfs-master-0.seaweedfs-master:9333,seaweedfs-master-1.seaweedfs-master:9333,seaweedfs-master-2.seaweedfs-master:9333

There are many `weed mount`,  `volumeServerAccess` uses both `publicUrl` and `direct`
```
- OS version
`Ubuntu 18.04.1 LTS`
- output of `weed version`
`version 30GB 2.85 19555385f7b99bce0e1f562f3cd4a4f440dd3d8e linux amd64`
- if using filer, show the content of `filer.toml`
use mongodb as filer store(by env: `WEED_MONGODB_ENABLED`、`WEED_MONGODB_URI`、`WEED_MONGODB_DATABASE`)

**Expected behavior**
CPU consumption is normal
**Screenshots**
filer-0:
<img width="1725" alt="filer0" src="https://user-images.githubusercontent.com/28077875/169953198-941359c6-5384-441a-8bf9-3a6ad07a73a7.png">

filer-1:
<img width="1734" alt="filer-1" src="https://user-images.githubusercontent.com/28077875/169953232-49c8a6e0-46ac-499a-bb0f-b0924a4bfaff.png">

filer-2:
<img width="1732" alt="filer-2" src="https://user-images.githubusercontent.com/28077875/169953249-09a0985a-5a6a-4efb-a1b8-1a29e67ea61a.png">

**Additional context**
filer log: [filer-log.zip](https://github.com/chrislusf/seaweedfs/files/8759721/filer-log.zip)

**Comment by chrislusf** [comment]
* What is the date in 01:45am in the screenshots?
* Did restart help?

**Comment by paochiang** [comment]
> * What is the date in 01:45am in the screenshots?

2022-05-24 , it’s UTC time zone

> * Did restart help?

Haven't restarted yet.  

Longer monitoring:
<img width="1764" alt="image" src="https://user-images.githubusercontent.com/28077875/169965643-0e5ecf75-5236-485c-924a-aac36f4c2185.png">

**Comment by chrislusf** [comment]
Added a fix to avoid the busy waiting https://github.com/chrislusf/seaweedfs/commit/7e25a2d41625165d6f006d21ea2faf262b3b6fc4

**Comment by paochiang** [comment]
@chrislusf 
When filer's cpu consumption is very high(about 70),  I collect about 10S data of `filer` through `perf`(about 1GB).
perf report:
<img width="1556" alt="image" src="https://user-images.githubusercontent.com/28077875/171176199-2184ce76-99fd-413b-bf51-816371415072.png">
The main time consumption is：
https://github.com/chrislusf/seaweedfs/blob/fbd99d53c1e45ef12c49ad1ec043c918f4da94e8/weed/server/filer_grpc_server_sub_meta.go#L160
related: https://github.com/golang/protobuf/issues/1242

Can we consider using `*filer_pb.SubscribeMetadataResponse` directly in struct `Logbuffer` to reduce `proto.Unmarshal`
calls?
