### ISSUE TITLE
服务器意外断电，加载volume报错，有什么好的办法避免吗？

### ISSUE THREAD

**Issue by xiaoweihong** [chrislusf/seaweedfs#3099]
**Describe the bug**
服务器意外断电，加载volume报错，volume server重启，导致服务不可用

可以通过weed fix 命令，将volume修复。希望有好的方式可以避免

**Screenshots**
![image](https://user-images.githubusercontent.com/13499653/169982872-0c433e6e-08bb-4249-b222-629e723b8a6f.png)

**Additional context**
version 2.93 arm64
![image](https://user-images.githubusercontent.com/13499653/169982968-93338551-cf90-427e-b0c2-7818fcd348f6.png)

**Comment by chrislusf** [comment]
No. Any recommendation?
