### ISSUE TITLE
Broken build on master

### ISSUE THREAD

**Issue by mosic** [chrislusf/seaweedfs#310]
Looks like the last commit (https://github.com/chrislusf/seaweedfs/commit/45a12505f2732b195cf4a7535297bb207ecfa925) broke the build: https://travis-ci.org/chrislusf/seaweedfs/builds/132873247

```
go/weed/filer.go:88: too many arguments in call to weed_server.NewFilerServer
go/weed/server.go:174: too many arguments in call to weed_server.NewFilerServer
```

The previous commit works fine.

**Comment by chrislusf** [comment]
should be fixed now. waiting for travis build.
