### ISSUE TITLE
Unable to get the very basic Docker command of seaweed to start/work

### ISSUE THREAD

**Issue by msmygit** [chrislusf/seaweedfs#3101]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs
Report issues here. Ask questions here https://stackoverflow.com/questions/tagged/seaweedfs
Please ask questions in https://github.com/chrislusf/seaweedfs/discussions

example of a good issue report:
https://github.com/chrislusf/seaweedfs/issues/1005
example of a bad issue report:
https://github.com/chrislusf/seaweedfs/issues/1008

**Describe the bug**
A simple very basic docker start up of the seaweedfs doesn't even work on the macOS Monteray version 12.4

**System Setup**
```
REDACTED-rmbp15:Downloads REDACTED$ docker run --name seaweedfs --rm -p 8333:8333 chrislusf/seaweedfs server -s3
I0519 00:23:56     1 master.go:255] current: 172.17.0.2:9333 peers:
I0519 00:23:56     1 file_util.go:23] Folder /data Permission: -rwxr-xr-x
I0519 00:23:56     1 master.go:255] current: 172.17.0.2:9333 peers:172.17.0.2:9333
I0519 00:23:56     1 master_server.go:131] Volume Size Limit is 1024 MB
I0519 00:23:56     1 file_util.go:23] Folder /data Permission: -rwxr-xr-x
I0519 00:23:56     1 master.go:147] Start Seaweed Master 30GB 3.04 9ff0d990 at 172.17.0.2:9333
I0519 00:23:56     1 raft_server.go:119] Starting RaftServer with 172.17.0.2:9333
I0519 00:23:56     1 volume_grpc_client_to_master.go:41] checkWithMaster 172.17.0.2:9333: get master 172.17.0.2:9333 configuration: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 172.17.0.2:19333: connect: connection refused"
I0519 00:23:56     1 raft_server.go:168] current cluster leader: 
I0519 00:23:58     1 volume_grpc_client_to_master.go:41] checkWithMaster 172.17.0.2:9333: get master 172.17.0.2:9333 configuration: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 172.17.0.2:19333: connect: connection refused"
I0519 00:23:58     1 s3.go:174] wait to connect to filer 172.17.0.2:8888 grpc address 172.17.0.2:18888
I0519 00:23:59     1 s3.go:174] wait to connect to filer 172.17.0.2:8888 grpc address 172.17.0.2:18888
I0519 00:23:59     1 volume_grpc_client_to_master.go:41] checkWithMaster 172.17.0.2:9333: get master 172.17.0.2:9333 configuration: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 172.17.0.2:19333: connect: connection refused"
I0519 00:24:00     1 s3.go:174] wait to connect to filer 172.17.0.2:8888 grpc address 172.17.0.2:18888
I0519 00:24:01     1 s3.go:174] wait to connect to filer 172.17.0.2:8888 grpc address 172.17.0.2:18888
I0519 00:24:01     1 volume_grpc_client_to_master.go:41] checkWithMaster 172.17.0.2:9333: get master 172.17.0.2:9333 configuration: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 172.17.0.2:19333: connect: connection refused"
I0519 00:24:02     1 s3.go:174] wait to connect to filer 172.17.0.2:8888 grpc address 172.17.0.2:18888
I0519 00:24:03     1 s3.go:174] wait to connect to filer 172.17.0.2:8888 grpc address 172.17.0.2:18888
I0519 00:24:03     1 volume_grpc_client_to_master.go:41] checkWithMaster 172.17.0.2:9333: get master 172.17.0.2:9333 configuration: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 172.17.0.2:19333: connect: connection refused"
I0519 00:24:04     1 s3.go:174] wait to connect to filer 172.17.0.2:8888 grpc address 172.17.0.2:18888
I0519 00:24:05     1 volume_grpc_client_to_master.go:41] checkWithMaster 172.17.0.2:9333: get master 172.17.0.2:9333 configuration: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 172.17.0.2:19333: connect: connection refused"
I0519 00:24:05     1 s3.go:174] wait to connect to filer 172.17.0.2:8888 grpc address 172.17.0.2:18888
I0519 00:24:06     1 s3.go:174] wait to connect to filer 172.17.0.2:8888 grpc address 172.17.0.2:18888
I0519 00:24:07     1 volume_grpc_client_to_master.go:41] checkWithMaster 172.17.0.2:9333: get master 172.17.0.2:9333 configuration: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 172.17.0.2:19333: connect: connection refused"
I0519 00:24:07     1 s3.go:174] wait to connect to filer 172.17.0.2:8888 grpc address 172.17.0.2:18888
I0519 00:24:08     1 s3.go:174] wait to connect to filer 172.17.0.2:8888 grpc address 172.17.0.2:18888
I0519 00:24:08     1 volume_grpc_client_to_master.go:41] checkWithMaster 172.17.0.2:9333: get master 172.17.0.2:9333 configuration: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 172.17.0.2:19333: connect: connection refused"
I0519 00:24:09     1 s3.go:174] wait to connect to filer 172.17.0.2:8888 grpc address 172.17.0.2:18888
I0519 00:24:10     1 s3.go:174] wait to connect to filer 172.17.0.2:8888 grpc address 172.17.0.2:18888
I0519 00:24:10     1 volume_grpc_client_to_master.go:41] checkWithMaster 172.17.0.2:9333: get master 172.17.0.2:9333 configuration: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 172.17.0.2:19333: connect: connection refused"
I0519 00:24:11     1 s3.go:174] wait to connect to filer 172.17.0.2:8888 grpc address 172.17.0.2:18888
I0519 00:24:12     1 s3.go:174] wait to connect to filer 172.17.0.2:8888 grpc address 172.17.0.2:18888
I0519 00:24:12     1 volume_grpc_client_to_master.go:41] checkWithMaster 172.17.0.2:9333: get master 172.17.0.2:9333 configuration: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 172.17.0.2:19333: connect: connection refused"
I0519 00:24:13     1 s3.go:174] wait to connect to filer 172.17.0.2:8888 grpc address 172.17.0.2:18888
I0519 00:24:14     1 volume_grpc_client_to_master.go:41] checkWithMaster 172.17.0.2:9333: get master 172.17.0.2:9333 configuration: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 172.17.0.2:19333: connect: connection refused"
I0519 00:24:14     1 master.go:196] Start Seaweed Master 30GB 3.04 9ff0d990 grpc server at 172.17.0.2:19333
I0519 00:24:14     1 s3.go:174] wait to connect to filer 172.17.0.2:8888 grpc address 172.17.0.2:18888
I0519 00:24:15     1 s3.go:174] wait to connect to filer 172.17.0.2:8888 grpc address 172.17.0.2:18888
I0519 00:24:15     1 masterclient.go:87] No existing leader found!
I0519 00:24:15     1 raft_server.go:190] Initializing new cluster
I0519 00:24:15     1 master_server.go:176] leader change event:  => 172.17.0.2:9333
I0519 00:24:15     1 master_server.go:179] [ 172.17.0.2:9333 ] 172.17.0.2:9333 becomes leader.
I0519 00:24:16     1 disk_location.go:182] Store started on dir: /data with 0 volumes max 0
I0519 00:24:16     1 disk_location.go:185] Store started on dir: /data with 0 ec shards
I0519 00:24:16     1 volume_grpc_client_to_master.go:50] Volume server start with seed master nodes: [172.17.0.2:9333]
I0519 00:24:16     1 volume.go:364] Start Seaweed volume server 30GB 3.04 9ff0d990 at 172.17.0.2:8080
I0519 00:24:16     1 volume_grpc_client_to_master.go:107] Heartbeat to: 172.17.0.2:9333
I0519 00:24:16     1 node.go:222] topo adds child DefaultDataCenter
I0519 00:24:16     1 node.go:222] topo:DefaultDataCenter adds child DefaultRack
I0519 00:24:16     1 node.go:222] topo:DefaultDataCenter:DefaultRack adds child 172.17.0.2:8080
I0519 00:24:16     1 node.go:222] topo:DefaultDataCenter:DefaultRack:172.17.0.2:8080 adds child 
I0519 00:24:16     1 master_grpc_server.go:72] added volume server 0: 172.17.0.2:8080
I0519 00:24:16     1 s3.go:174] wait to connect to filer 172.17.0.2:8888 grpc address 172.17.0.2:18888
I0519 00:24:17     1 s3.go:174] wait to connect to filer 172.17.0.2:8888 grpc address 172.17.0.2:18888
W0519 00:24:18     1 filer_server.go:144] skipping default store dir in /data/filerldb2
I0519 00:24:18     1 leveldb2_store.go:42] filer store leveldb2 dir: /data/filerldb2
I0519 00:24:18     1 file_util.go:23] Folder /data/filerldb2 Permission: -rwxr-xr-x
I0519 00:24:18     1 master_grpc_server.go:281] + client .filer@172.17.0.2:8888
I0519 00:24:18     1 s3.go:174] wait to connect to filer 172.17.0.2:8888 grpc address 172.17.0.2:18888
I0519 00:24:18     1 filer.go:122] create filer.store.id to -657845706
I0519 00:24:18     1 configuration.go:28] configured filer store to leveldb2
I0519 00:24:18     1 filer.go:90] the cluster has 1 filers
I0519 00:24:18     1 filer.go:247] Start Seaweed Filer 30GB 3.04 9ff0d990 at 172.17.0.2:8888
I0519 00:24:18     1 meta_aggregator.go:110] connecting to peer filer 172.17.0.2:8888: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 172.17.0.2:18888: connect: connection refused"
I0519 00:24:19     1 master_grpc_server.go:281] + client .master@172.17.0.2:9333
I0519 00:24:19     1 masterclient.go:180] + .master 172.17.0.2:9333 leader:false
I0519 00:24:19     1 masterclient.go:180] + .master 172.17.0.2:9333 leader:false
I0519 00:24:19     1 s3.go:170] S3 read filer buckets dir: /buckets
I0519 00:24:19     1 s3.go:177] connected to filer 172.17.0.2:8888 grpc address 172.17.0.2:18888
W0519 00:24:19     1 auth_credentials.go:79] fail to load config: read S3 config: filer: no entry is found in filer store
I0519 00:24:19     1 s3.go:250] Start Seaweed S3 API Server 30GB 3.04 9ff0d990 at http port 8333
I0519 00:24:19     1 filer_grpc_server_sub_meta.go:246] + listener s3@172.17.0.2:47058
I0519 00:24:19     1 filer_grpc_server_sub_meta.go:33]  s3@172.17.0.2:47058 starts to subscribe /etc/iam/identity.json from 2022-05-19 00:24:19.416309172 +0000 UTC
I0519 00:24:19     1 filer_grpc_server_sub_meta.go:246] + listener filer:172.17.0.2:8888@172.17.0.2:47064
I0519 00:24:19     1 filer_grpc_server_sub_meta.go:93]  filer:172.17.0.2:8888@172.17.0.2:47064 local subscribe / from 2022-05-19 00:23:18.428673172 +0000 UTC
I0519 00:24:19     1 filer_grpc_server_sub_meta.go:105] read on disk filer:172.17.0.2:8888@172.17.0.2:47064 local subscribe / from 2022-05-19 00:23:18.428673172 +0000 UTC
I0519 00:24:19     1 filer_grpc_server_sub_meta.go:121] read in memory filer:172.17.0.2:8888@172.17.0.2:47064 local subscribe / from 2022-05-19 00:23:18.428673172 +0000 UTC



^CI0519 00:38:52     1 volume_server.go:123] Stopping volume server...
I0519 00:38:52     1 volume.go:275] stop send heartbeat and wait 10 seconds until shutdown ...
volume server has be killed
W0519 00:38:52     1 master_grpc_server.go:57] SendHeartbeat.Recv server 172.17.0.2:8080 : rpc error: code = Canceled desc = context canceled
I0519 00:38:52     1 node.go:234] topo:DefaultDataCenter:DefaultRack removes 172.17.0.2:8080
I0519 00:38:52     1 master_grpc_server.go:34] unregister disconnected volume server 172.17.0.2:8080
I0519 00:39:02     1 volume.go:299] graceful stop cluster http server ... 
I0519 00:39:02     1 volume.go:304] graceful stop gRPC ...
I0519 00:39:02     1 volume_server.go:128] Shutting down volume server...
I0519 00:39:02     1 volume_server.go:130] Shut down successfully!
```

**Expected behavior**
This should simply work by following the docs
- https://github.com/chrislusf/seaweedfs#quick-start-for-s3-api-on-docker
- https://github.com/chrislusf/seaweedfs/wiki/Getting-Started#running-with-docker

**Screenshots**

**Additional context**
Unable to get started with a basic setup

**Comment by kmlebedev** [comment]
Please add option -filer to start filer server

**Comment by msmygit** [comment]
@kmlebedev, thank you! I did try adding `-filer` to the command this is what I get

```
$ docker run --name seaweedfs --rm -p 8333:8333 chrislusf/seaweedfs server -master.port=9333 -volume.port=8080 -dir="./seaweeddir/" -filer
Unable to find image 'chrislusf/seaweedfs:latest' locally
latest: Pulling from chrislusf/seaweedfs
df9b9388f04a: Pull complete 
97f54730e595: Pull complete 
03559b0f629f: Pull complete 
e483677695ea: Pull complete 
0941c91972d4: Pull complete 
ee9b90fd0044: Pull complete 
d65794718261: Pull complete 
4f4fb700ef54: Pull complete 
Digest: sha256:fb6a0c5c1596a79bd330a24ec90d46d72082fca08eb85c526b69092bc07b5caf
Status: Downloaded newer image for chrislusf/seaweedfs:latest
I0524 14:22:30     1 master.go:255] current: 172.17.0.2:9333 peers:
F0524 14:22:31     1 server.go:239] Check Meta Folder (-mdir="./seaweeddir/") Writable: stat ./seaweeddir/: no such file or directory
```

while there is a directory (empty too) that is very much available since many days ago!.

```
REDACTED-rmbp15:Downloads REDACTED$ ls -la ./seaweeddir/
total 0
drwxr-xr-x   2 REDACTED  staff    64 May 18 20:40 .
drwx------@ 93 REDACTED  staff  2976 May 18 20:57 ..
```

**Comment by chrislusf** [comment]
The initial command and output looks fine. What is not working?

**Comment by msmygit** [comment]
> The initial command and output looks fine. What is not working?

@chrislusf, please see below.

<details>
    <summary>Expand to view full stacktrace/console logging</summary>

    ## Console Output

   $ docker run --name seaweedfs --rm -p 8333:8333 chrislusf/seaweedfs server -s3
   I0524 14:42:01     1 master.go:255] current: 172.17.0.2:9333 peers:
   I0524 14:42:01     1 file_util.go:23] Folder /data Permission: -rwxr-xr-x
   I0524 14:42:01     1 master.go:255] current: 172.17.0.2:9333 peers:172.17.0.2:9333
   I0524 14:42:01     1 file_util.go:23] Folder /data Permission: -rwxr-xr-x
   I0524 14:42:01     1 master_server.go:131] Volume Size Limit is 1024 MB
   I0524 14:42:01     1 volume_grpc_client_to_master.go:43] checkWithMaster 172.17.0.2:9333: get master 172.17.0.2:9333 
   configuration: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 
   172.17.0.2:19333: connect: connection refused"
   I0524 14:42:01     1 master.go:147] Start Seaweed Master 30GB 3.06 2f846777 at 172.17.0.2:9333
   I0524 14:42:01     1 raft_server.go:119] Starting RaftServer with 172.17.0.2:9333
   I0524 14:42:01     1 raft_server.go:168] current cluster leader: 
   I0524 14:42:03     1 volume_grpc_client_to_master.go:43] checkWithMaster 172.17.0.2:9333: get master 172.17.0.2:9333 
   configuration: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 
   172.17.0.2:19333: connect: connection refused"
   I0524 14:42:03     1 s3.go:174] wait to connect to filer 172.17.0.2:8888 grpc address 172.17.0.2:18888
   I0524 14:42:04     1 s3.go:174] wait to connect to filer 172.17.0.2:8888 grpc address 172.17.0.2:18888
   I0524 14:42:05     1 volume_grpc_client_to_master.go:43] checkWithMaster 172.17.0.2:9333: get master 172.17.0.2:9333 
   configuration: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 
   172.17.0.2:19333: connect: connection refused"
   I0524 14:42:05     1 s3.go:174] wait to connect to filer 172.17.0.2:8888 grpc address 172.17.0.2:18888
   I0524 14:42:06     1 s3.go:174] wait to connect to filer 172.17.0.2:8888 grpc address 172.17.0.2:18888
   I0524 14:42:07     1 volume_grpc_client_to_master.go:43] checkWithMaster 172.17.0.2:9333: get master 172.17.0.2:9333 
   configuration: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 
   172.17.0.2:19333: connect: connection refused"
   I0524 14:42:07     1 s3.go:174] wait to connect to filer 172.17.0.2:8888 grpc address 172.17.0.2:18888
   I0524 14:42:08     1 s3.go:174] wait to connect to filer 172.17.0.2:8888 grpc address 172.17.0.2:18888
   I0524 14:42:09     1 volume_grpc_client_to_master.go:43] checkWithMaster 172.17.0.2:9333: get master 172.17.0.2:9333 
   configuration: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 
   172.17.0.2:19333: connect: connection refused"
   I0524 14:42:09     1 s3.go:174] wait to connect to filer 172.17.0.2:8888 grpc address 172.17.0.2:18888
   I0524 14:42:10     1 volume_grpc_client_to_master.go:43] checkWithMaster 172.17.0.2:9333: get master 172.17.0.2:9333 
   configuration: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 
   172.17.0.2:19333: connect: connection refused"
   I0524 14:42:10     1 s3.go:174] wait to connect to filer 172.17.0.2:8888 grpc address 172.17.0.2:18888
   I0524 14:42:11     1 s3.go:174] wait to connect to filer 172.17.0.2:8888 grpc address 172.17.0.2:18888
   I0524 14:42:12     1 volume_grpc_client_to_master.go:43] checkWithMaster 172.17.0.2:9333: get master 172.17.0.2:9333 
   configuration: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 
   172.17.0.2:19333: connect: connection refused"
   I0524 14:42:12     1 s3.go:174] wait to connect to filer 172.17.0.2:8888 grpc address 172.17.0.2:18888
   I0524 14:42:13     1 s3.go:174] wait to connect to filer 172.17.0.2:8888 grpc address 172.17.0.2:18888
   I0524 14:42:14     1 volume_grpc_client_to_master.go:43] checkWithMaster 172.17.0.2:9333: get master 172.17.0.2:9333 configuration: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 172.17.0.2:19333: connect: connection refused"
   I0524 14:42:14     1 s3.go:174] wait to connect to filer 172.17.0.2:8888 grpc address 172.17.0.2:18888
   I0524 14:42:15     1 s3.go:174] wait to connect to filer 172.17.0.2:8888 grpc address 172.17.0.2:18888
   I0524 14:42:16     1 volume_grpc_client_to_master.go:43] checkWithMaster 172.17.0.2:9333: get master 172.17.0.2:9333 configuration: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 172.17.0.2:19333: connect: connection refused"
   I0524 14:42:16     1 s3.go:174] wait to connect to filer 172.17.0.2:8888 grpc address 172.17.0.2:18888
   I0524 14:42:17     1 s3.go:174] wait to connect to filer 172.17.0.2:8888 grpc address 172.17.0.2:18888
   I0524 14:42:17     1 volume_grpc_client_to_master.go:43] checkWithMaster 172.17.0.2:9333: get master 172.17.0.2:9333 configuration: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 172.17.0.2:19333: connect: connection refused"
   I0524 14:42:18     1 s3.go:174] wait to connect to filer 172.17.0.2:8888 grpc address 172.17.0.2:18888
   I0524 14:42:19     1 volume_grpc_client_to_master.go:43] checkWithMaster 172.17.0.2:9333: get master 172.17.0.2:9333 configuration: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 172.17.0.2:19333: connect: connection refused"
   I0524 14:42:19     1 master.go:196] Start Seaweed Master 30GB 3.06 2f846777 grpc server at 172.17.0.2:19333
   I0524 14:42:19     1 s3.go:174] wait to connect to filer 172.17.0.2:8888 grpc address 172.17.0.2:18888
   I0524 14:42:20     1 s3.go:174] wait to connect to filer 172.17.0.2:8888 grpc address 172.17.0.2:18888
   I0524 14:42:21     1 masterclient.go:87] No existing leader found!
   I0524 14:42:21     1 raft_server.go:190] Initializing new cluster
   I0524 14:42:21     1 master_server.go:176] leader change event:  => 172.17.0.2:9333
   I0524 14:42:21     1 master_server.go:179] [ 172.17.0.2:9333 ] 172.17.0.2:9333 becomes leader.
   I0524 14:42:21     1 disk_location.go:209] Store started on dir: /data with 0 volumes max 0
   I0524 14:42:21     1 disk_location.go:212] Store started on dir: /data with 0 ec shards
   I0524 14:42:21     1 volume_grpc_client_to_master.go:52] Volume server start with seed master nodes: [172.17.0.2:9333]
   I0524 14:42:21     1 volume.go:364] Start Seaweed volume server 30GB 3.06 2f846777 at 172.17.0.2:8080
   I0524 14:42:21     1 volume_grpc_client_to_master.go:109] Heartbeat to: 172.17.0.2:9333
   I0524 14:42:21     1 node.go:222] topo adds child DefaultDataCenter
   I0524 14:42:21     1 node.go:222] topo:DefaultDataCenter adds child DefaultRack
   I0524 14:42:21     1 node.go:222] topo:DefaultDataCenter:DefaultRack adds child 172.17.0.2:8080
   I0524 14:42:21     1 node.go:222] topo:DefaultDataCenter:DefaultRack:172.17.0.2:8080 adds child 
   I0524 14:42:21     1 master_grpc_server.go:112] added volume server 0: 172.17.0.2:8080 [d83bf223-5754-411c-8474-c38b9c0cc6a0]
   I0524 14:42:21     1 master_grpc_server.go:48] found new uuid:172.17.0.2:8080 [d83bf223-5754-411c-8474-c38b9c0cc6a0] , map[172.17.0.2:8080:[d83bf223-5754-411c-8474-c38b9c0cc6a0]]
   I0524 14:42:21     1 s3.go:174] wait to connect to filer 172.17.0.2:8888 grpc address 172.17.0.2:18888
   I0524 14:42:22     1 s3.go:174] wait to connect to filer 172.17.0.2:8888 grpc address 172.17.0.2:18888
   W0524 14:42:23     1 filer_server.go:144] skipping default store dir in /data/filerldb2
   I0524 14:42:23     1 leveldb2_store.go:42] filer store leveldb2 dir: /data/filerldb2
   I0524 14:42:23     1 file_util.go:23] Folder /data/filerldb2 Permission: -rwxr-xr-x
   I0524 14:42:23     1 master_grpc_server.go:332] + client .filer@172.17.0.2:8888
   I0524 14:42:23     1 s3.go:174] wait to connect to filer 172.17.0.2:8888 grpc address 172.17.0.2:18888
   I0524 14:42:23     1 filer.go:122] create filer.store.id to -1018928121
   I0524 14:42:23     1 configuration.go:28] configured filer store to leveldb2
   I0524 14:42:23     1 filer.go:90] the cluster has 1 filers
   I0524 14:42:23     1 filer.go:247] Start Seaweed Filer 30GB 3.06 2f846777 at 172.17.0.2:8888
   I0524 14:42:23     1 filer_grpc_server_sub_meta.go:246] + listener filer:172.17.0.2:8888@172.17.0.2:40594
   I0524 14:42:23     1 filer_grpc_server_sub_meta.go:93]  filer:172.17.0.2:8888@172.17.0.2:40594 local subscribe / from 2022-05-24 14:41:23.889169497 +0000 UTC
   I0524 14:42:23     1 filer_grpc_server_sub_meta.go:105] read on disk filer:172.17.0.2:8888@172.17.0.2:40594 local subscribe / from 2022-05-24 14:41:23.889169497 +0000 UTC
   I0524 14:42:23     1 filer_grpc_server_sub_meta.go:121] read in memory filer:172.17.0.2:8888@172.17.0.2:40594 local subscribe / from 2022-05-24 14:41:23.889169497 +0000 UTC
   I0524 14:42:24     1 master_grpc_server.go:332] + client .master@172.17.0.2:9333
   I0524 14:42:24     1 masterclient.go:180] + .master 172.17.0.2:9333 leader:false
   I0524 14:42:24     1 masterclient.go:180] + .master 172.17.0.2:9333 leader:false
   I0524 14:42:24     1 s3.go:170] S3 read filer buckets dir: /buckets
   I0524 14:42:24     1 s3.go:177] connected to filer 172.17.0.2:8888 grpc address 172.17.0.2:18888
   W0524 14:42:24     1 auth_credentials.go:79] fail to load config: read S3 config: filer: no entry is found in filer store
   I0524 14:42:24     1 s3.go:250] Start Seaweed S3 API Server 30GB 3.06 2f846777 at http port 8333
   I0524 14:42:24     1 filer_grpc_server_sub_meta.go:246] + listener s3@172.17.0.2:40604
   I0524 14:42:24     1 filer_grpc_server_sub_meta.go:33]  s3@172.17.0.2:40604 starts to subscribe /etc/iam/identity.json from 2022-05-24 14:42:24.87743562 +0000 UTC
</details>


and then trying to follow the wiki documentation,

```
$ IP=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' weed)
Error: No such object: weed
```

and from the console output:
```
I0524 14:42:23 1 leveldb2_store.go:42] filer store leveldb2 dir: /data/filerldb2
I0524 14:42:23 1 file_util.go:23] Folder /data/filerldb2 Permission: -rwxr-xr-x
```

I wanted to check what's in that directory, but that directory doesn't even exist on the local machine.
```
$ ls -la /data/filerldb2
ls: /data/filerldb2: No such file or directory
```

**Comment by chrislusf** [comment]
The `/data/filerldb2` is on the docker instance.

**Comment by msmygit** [comment]
Why did we close this issue? @chrislusf

**Comment by chrislusf** [comment]
remove `-dir="./seaweeddir/"` from your command it will work.

**Comment by msmygit** [comment]
> remove `-dir="./seaweeddir/"` from your command it will work.

This worked @chrislusf , but what about my other questions? Could you please give me an end-to-end working simple CRUD operation with this FS? 

How to get the `weed` executable work?

Thank you in advance!

**Comment by chrislusf** [comment]
You can just run `weed server -s3`, and follow https://github.com/chrislusf/seaweedfs/wiki/Amazon-S3-API to setup and test s3 operations, which may be easier for you to follow.

There are a lot of other features which may take you more time to get familiar with.
