### ISSUE TITLE
Seaweedfs sets up ipv4 and ipv6 dual-stack services

### ISSUE THREAD

**Issue by Jendeng21** [chrislusf/seaweedfs#3109]
Seaweedfs sets up ipv4 and ipv6 dual-stack services using curl -XGET  
http://ipv6:9333/dir/assign, return json "" url" : "ipv4", "whether there should be a return to ipv6. 

**Describe the bug**

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
- OS version
- output of `weed version`
- if using filer, show the content of `filer.toml`

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by chrislusf** [comment]
Please follow the issue template and answer questions first.
