### ISSUE TITLE
 filer service exception is raised by using port 7333 download big file . The file in the filer service cannot be accessed

### ISSUE THREAD

**Issue by caihexin** [chrislusf/seaweedfs#3111]
weed filer  -master=192.168.0.233:9333 -port=8888  -port.readonly=7333 
 8888 filer service exception is raised by using port 7333 download big file . The file in the filer service cannot be accessed.

weed version

version 30GB 3.05 acc318e12bdeca0dcf0f4fc601cc659f7831fa92 linux amd64

**Comment by chrislusf** [comment]
need a way to reproduce.

**Comment by caihexin** [comment]
It is easy to reproduce. If you use the filer readonly port to download a 2G file, it will reproduce. There is no exception in the background log
