### ISSUE TITLE
[Bug] filer.sync skip the target offset when target server once down

### ISSUE THREAD

**Issue by creeew** [chrislusf/seaweedfs#3126]
**Describe the bug**
Command 'weed filer.sync -a {source_addr} -b {target_addr}' built two goroutines to sync files.
Source uploading new files when target is down, but these new files cannot sync to target when target is up. 

**System Setup**
weed server -master.defaultReplication=000 -filer

OS: Linux 3.10.0-327.el7.x86_64

weed version: version 30GB 2.88 7270067289802307556d117be422a1e5a208f558 linux amd64

Using default filer configuration without scaffold to produce filer.toml. And filer store in default leveldb.

We got two data center, naming a dc and b dc.  a dc ip address is a.a.a.a, b dc ip address b.b.b.b
Each data center using command `weed server -master.defaultReplication=000 -filer` to provide file system service. 
And in a dc, running command `weed filer.sync -a a.a.a.a:8888 -b b.b.b.b:8888 -a.debug -b.debug` to sync files between data centers.
And then, uploading files in a dc : `weed filer.copy test_file_in_a_dc http://a.a.a.a:8888/`
uploading files in b dc : `weed filer.copy test_file_in_b_dc http://b.b.b.b:8888/`
In a dc filer can find test_file_in_b_dc and in b dc filer can find test_file_in_a_dc.  Files sync successful.

Stop b dc seaweedfs. 
Uploading file in a dc during the b dc is down.
`weed filer.copy upload_in_a_when_b_down http://a.a.a.a:8888/`

b dc recover seaweedfs. a dc continue upload file.
`weed filer.copy upload_in_a_when_b_up http://a.a.a.a:8888/`
We can find synced file 'upload_in_a_when_b_up' in b dc filer. But there is no file named upload_in_a_when_b_down in b dc filer.

**Expected behavior**
Uploaded files like 'upload_in_a_when_b_down' can sync to another data center when down data center recover.

**Additional context**
target subscribe source file change log and using filer_sink to replay log in target filer.

When target is down, replay action `processEventFn` will fail. But we still store the lastest lastTsNs(offset) in memory. 
Even target recovered, source still using the wrong offset cause once we build streaming grpc connection we will never get the real offset in target filer store which only get one time when filer.sync goroutine start.
https://github.com/chrislusf/seaweedfs/blob/27732ecfa4dcbe6d02af350244c53a3cb200a010/weed/pb/filer_pb_tail.go#L74

Maybe we could assign *lastTsNs only when processEventFn execute successful. Please let me know if I am on a right path to deal with this situation and  I am willing to submit a PR.

**Comment by chrislusf** [comment]
Correct analysis! 

Currently there is only fatalOnError. It needs a retryForeverOnError option. Try to use some enum for this.
