### ISSUE TITLE
Massive 'i/o timeout' errors in log

### ISSUE THREAD

**Issue by jiaqigan** [chrislusf/seaweedfs#3131]
We've noticed that in the log, there were lots of 'i/o timeout' errors. Could you please help identify the cause of it? Really appriciate that!

Some contents of the log are below:
 I0530 18:23:09 25347 common.go:70] response method:POST URL:/atudata/cmdi_20211116152005_0002/cmdi_20211116152005_0002.20220525140124.2.dtlog/cmdi_20211116152005_0002.20220525140124.2.dtlog_36 with httpStatus:500 and JSON:{"error":"read tcp [2049:8054:5cc1:f010:1000::1]:8888-\u003e[2049:8054:5cc1:f010:1000::13]:54432: i/o timeout"}
I0530 18:24:10 25347 common.go:70] response method:POST URL:/atudata/Vanceview_20211102142759_0037/Vanceview_20211102142759_0037.20220530180851.1.dtlog/Vanceview_20211102142759_0037.20220530180851.1.dtlog_9 with httpStatus:500 and JSON:{"error":"read tcp [2049:8054:5cc1:f010:1000::1]:8888-\u003e[2049:8054:5cc1:f010:1000::14]:37304: i/o timeout"}
I0530 18:24:13 25347 common.go:70] response method:POST URL:/atudata/cmdi_20211116152005_0002/cmdi_20211116152005_0002.20220525140124.4.dtlog/cmdi_20211116152005_0002.20220525140124.4.dtlog_208 with httpStatus:500 and JSON:{"error":"read tcp [2049:8054:5cc1:f010:1000::1]:8888-\u003e[2049:8054:5cc1:f010:1000::13]:56342: i/o timeout"}
I0530 18:25:16 25347 common.go:70] response method:POST URL:/atudata/cmdi_20211116152005_0002/cmdi_20211116152005_0002.20220525140124.4.dtlog/cmdi_20211116152005_0002.20220525140124.4.dtlog_13 with httpStatus:500 and JSON:{"error":"read tcp [2049:8054:5cc1:f010:1000::1]:8888-\u003e[2049:8054:5cc1:f010:1000::12]:39746: i/o timeout"}
I0530 20:13:46 25347 common.go:70] response method:POST URL:/atudata/Vanceview_20220316185716_0006/Vanceview_20220316185716_0006.20220530170127.1.dtlog/Vanceview_20220316185716_0006.20220530170127.1.dtlog_5 with httpStatus:500 and JSON:{"error":"read tcp [2049:8054:5cc1:f010:1000::1]:8888-\u003e[2049:8054:5cc1:f010:1000::12]:46812: i/o timeout"}

**Comment by chrislusf** [comment]
maybe the system was busy.

**Comment by jiaqigan** [comment]
You mean our linux system was the busy or the seaweedfs system?
