### ISSUE TITLE
Seaweedfs 搭建 ipv4 和 ipv6 双栈服务，使用IPV6地址访问问题

### ISSUE THREAD

**Issue by Jendeng21** [chrislusf/seaweedfs#3139]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs
Report issues here. Ask questions here https://stackoverflow.com/questions/tagged/seaweedfs
Please ask questions in https://github.com/chrislusf/seaweedfs/discussions

example of a good issue report:
https://github.com/chrislusf/seaweedfs/issues/1005
example of a bad issue report:
https://github.com/chrislusf/seaweedfs/issues/1008

**Describe the bug**
seaweedfs 启动了IPV4和IPV6双栈服务，在使用curl -XGET http://2409:8c20:1831:503:100:2:3:24d:9333/dir/assign，返回了{"fid":"1,03824912e4","url":"10.15.2.78:8081","publicUrl":"10.15.2.78:8081","count":1}，这里使用的IPV6地址请求，返回的json
中url地址是否应该是你IPV6地址了？
下面是启动seaweedfs的master和volume，您看是否有问题。
**System Setup*
- weed master -mdir=/data/seaweedfs/master -port=9333 -ip.bind=[::] -peers=[2409:8c20:1831:503:100:2:3:24e]:9333,[2409:8c20:1831:503:100:2:3:24f]:9333 -defaultReplication=010
- weed volume -port=8081 -dir=/data/seaweedfs/volume -max=5 -ip.bind=[::] -mserver=[2409:8c20:1831:503:100:2:3:24d]:9333,[2409:8c20:1831:503:100:2:3:24e]:9333,[2409:8c20:1831:503:100:2:3:24f]:9333 -dataCenter=wuxici -rack=r77
- 主机系统版本：CentOS 7.5
- output of `weed version`：version 30GB 3.05
- if using filer, show the content of `filer.toml`

**Expected behavior**
1、通过ipv6地址请求，返回值中应该返回IPV6地址
2、通过IPV6地址上传文件后，能通过IPV6地址下载

**Screenshots**

**Additional context**

**Comment by chrislusf** [comment]
use `-ip=[2409:8c20:1831:503:100:2:3:24f]` when starting master and volume server.

**Comment by Jendeng21** [comment]
谢谢！
