### ISSUE TITLE
filer seems to ignore -localSocket= and crashes if run as non privileged due to default creation in /tmp/

### ISSUE THREAD

**Issue by Ne00n** [chrislusf/seaweedfs#3147]
**Describe the bug**
filer seems to ignore -localSocket= 
Instead it runs with the default in /tmp/ which crashes if run as non privileged user since no permissions

**System Setup**
- List the command line to start 
/usr/local/bin/weed filer -localSocket=/home/seaweedfs/filer.sock -ip=10.0.253.3 -ip.bind=10.0.253.3 -port=9533 -master=10.0.253.1:9333,10.0.253.6:9333,10.0.253.3:9333
/usr/local/bin/weed volume -ip=10.0.253.3 -ip.bind=10.0.253.3 -port=9433 -dir=/home/seaweedfs/volume -dataCenter=RBX5 -rack=xxxx -mserver=10.0.253.1:9333,10.0.253.6:9333,10.0.253.3:9333
/usr/local/bin/weed master -defaultReplication=100 -ip=10.0.253.3 -ip.bind=10.0.253.3 -port=9333 -mdir=/home/seaweedfs/master -peers=10.0.253.1:9333,10.0.253.6:9333,10.0.253.3:9333
- OS version
Debian 11
- output of `weed version`
version 30GB 3.09 4a046e4de7a40730895f8149120ce8d6e95f961d linux amd64
- if using filer, show the content of `filer.toml`
Was not created by default

**Expected behavior**
It should override the default path in /tmp/

**Screenshots**
https://i.imgur.com/dobyC3B.png

Any idea on this?

**Comment by chrislusf** [comment]
btw: why non-privileged users can not write to `/tmp`? I thought it usually should be open.

**Comment by Ne00n** [comment]
> btw: why non-privileged users can not write to `/tmp`? I thought it usually should be open.

systemd prevents applications wiriting to "public" /tmp/ and gives the application its own private temp folder
Plus in general the application is limited to the working directory which in this case is /home/seaweedfs
