### ISSUE TITLE
新版本weed filer ui网页提供了快捷删除文件夹功能这个太危险了！！！

### ISSUE THREAD

**Issue by caihexin** [chrislusf/seaweedfs#3149]
![图片](https://user-images.githubusercontent.com/13762872/172333878-d6942666-6c63-477e-b308-705ac86b96dc.png)
新版本weed filer ui提供了快捷删除文件夹功能这个太危险了，本来没有点技术能力，还不能大量删除文件，有了这个功能，可以方便的大量删除文件（也许是误删）。能否提供这个功能的开关设置或者不提供又或者能否提供删除文件后的快捷恢复功能？

**Comment by chrislusf** [comment]
Please send a PR?

**Comment by caihexin** [comment]
OK
