### ISSUE TITLE
weed3.06  webdav服务导致集群异常且7333服务无法对外提供服务

### ISSUE THREAD

**Issue by caihexin** [chrislusf/seaweedfs#3156]
weed
version 30GB 3.06 2f846777bbceea307771e79d4452e071b0bd5a51 linux amd64
错误日志如下：

I0607 17:21:00 31616 filer_grpc_server_sub_meta.go:33]  mount@192.168.19.149:29475 starts to subscribe / from 2022-0
2022/06/09 11:40:45 http: Accept error: accept tcp [::]:7333: accept4: too many open files; retrying in 5ms
2022/06/09 11:40:45 http: Accept error: accept tcp [::]:7333: accept4: too many open files; retrying in 10ms
2022/06/09 11:40:45 http: Accept error: accept tcp [::]:7333: accept4: too many open files; retrying in 20ms
2022/06/09 11:40:45 http: Accept error: accept tcp [::]:7333: accept4: too many open files; retrying in 40ms
I0609 11:40:45 31618 filechunk_manifest.go:147] read http://192.168.0.233:8080/9,0799b1f94e1448 failed, err: Get "ht
I0609 11:40:45 31618 filechunk_manifest.go:153] retry reading in 1s
I0609 11:40:45 31618 filechunk_manifest.go:147] read http://192.168.0.233:8080/10,0799d1b1b69446 failed, err: Get "h
I0609 11:40:45 31618 filechunk_manifest.go:153] retry reading in 1s
2022/06/09 11:40:45 http: Accept error: accept tcp [::]:7333: accept4: too many open files; retrying in 80ms
2022/06/09 11:40:45 http: Accept error: accept tcp [::]:7333: accept4: too many open files; retrying in 160ms
2022/06/09 11:40:45 http: Accept error: accept tcp [::]:7333: accept4: too many open files; retrying in 320ms
2022/06/09 11:40:46 http: Accept error: accept tcp [::]:7333: accept4: too many open files; retrying in 640ms

**Comment by kmlebedev** [comment]
You need increase system limit open files, see ulimit -a

**Comment by caihexin** [comment]
#  ulimit -a
core file size (blocks)         (-c) 0
data seg size (kb)              (-d) unlimited
scheduling priority             (-e) 0
file size (blocks)              (-f) unlimited
pending signals                 (-i) 96121
max locked memory (kb)          (-l) 64
max memory size (kb)            (-m) unlimited
open files                      (-n) 1024
POSIX message queues (bytes)    (-q) 819200
real-time priority              (-r) 0
stack size (kb)                 (-s) 8192
cpu time (seconds)              (-t) unlimited
max user processes              (-u) 96121
virtual memory (kb)             (-v) unlimited
file locks                      (-x) unlimited

**Comment by chrislusf** [comment]
open files (-n) 1024

this is too small.

**Comment by caihexin** [comment]
# ulimit -a
core file size (blocks)         (-c) 0
data seg size (kb)              (-d) unlimited
scheduling priority             (-e) 0
file size (blocks)              (-f) unlimited
pending signals                 (-i) 96121
max locked memory (kb)          (-l) 64
max memory size (kb)            (-m) unlimited
open files                      (-n) 1048576

now   increase system limit open files to 1048576 ,
To be observed
thank  @chrislusf  @kmlebedev
