### ISSUE TITLE
pls implement self-update cmd

### ISSUE THREAD

**Issue by chymian** [chrislusf/seaweedfs#3161]
to streamline the update-process, it would be great to have a "self-update" command.
recently a lot of developers started to implement a update-cmd for their binaries, like i.e. minio-cli, restic, resticprofile, …

that boils down update-procedure of the not packaged/auto-updated binary to one line in cron:
5 5 * * 6 root  mcli update
6 5 * * 6 root  restic self-update
7 5 * * 6 root  resticprofile self-update

simple & effective. works very well

**Comment by chrislusf** [comment]
ok. Seems this can be implemented following https://github.com/restic/restic/tree/46d08d94040f581df7bbf5eacca69434ba80a79e/internal/selfupdate

PR is welcome!

**Comment by chymian** [comment]
good. unfortunately, I'm not a dev.
hopefully, some dev like the idea and go for it.

**Comment by guol-fnst** [comment]
> ok. Seems this can be implemented following https://github.com/restic/restic/tree/46d08d94040f581df7bbf5eacca69434ba80a79e/internal/selfupdate
> 
> PR is welcome!

Maybe I would try to implement this feature.
