### ISSUE TITLE
we should add a filer monitor

### ISSUE THREAD

**Issue by 030io** [chrislusf/seaweedfs#317]
Sometime, key deleted successfully, but file delete failed.

**Comment by chrislusf** [comment]
how about we try to delete the file first?

**Comment by 030io** [comment]
I think the source code is too complex. We should delete some feature and increase stability.
More simple less bug.

**Comment by 030io** [comment]
I will put this application in a production environment.
I'll comment later.

**Comment by chrislusf** [comment]
Closing this. You can create a new one with more details or exact feature request.
