### ISSUE TITLE
[volume] cannot hydrate needle from file: CRC error! Data On Disk Corrupted

### ISSUE THREAD

**Issue by kmlebedev** [chrislusf/seaweedfs#3177]
**Describe the bug**

after update sw to 3.10 i catch bug https://github.com/chrislusf/seaweedfs/issues/3178 and restart pods got a lot of errors and rollback to version 3.07.
```
compact volume 708: cannot hydrate needle from file: CRC error! Data On Disk Corrupted
topology_vacuum.go:97] Error when vacuuming 708 on fast-volume-2:8080: rpc error: code = Unknown desc = cannot hydrate needle from file: CRC error! Data On Disk Corrupted
```

**System Setup**
```
testing tag (3.10)
version 30GB 3.10 623c1a4a linux amd64
```

**Comment by kmlebedev** [comment]
@chrislusf Seems to be an issue after https://github.com/chrislusf/seaweedfs/commit/056c480eb09efb4871a1ebac956972b6a0b23e8c

What has changed there?
Could the rollback of the version from 3.10 to 3.07 somehow affect?

**Comment by chrislusf** [comment]
Correct. Can not rollback.

**Comment by kmlebedev** [comment]
> Correct. Can not rollback.



> Correct. Can not rollback.

Maybe we should focus on this at the release?

**Comment by kmlebedev** [comment]
> > Correct. Can not rollback.
> 
> Maybe we should focus on this at the release message?

**Comment by chrislusf** [comment]
In this case, it's backward compatible (newer version can read write previous data), but not forward compatible (older version can not read newer format).

**Comment by acejam** [comment]
> In this case, it's backward compatible (newer version can read write previous data), but not forward compatible (older version can not read newer format).

While this may be true - if you cannot downgrade after upgrading, that's a big issue and breaks the definition of "backwards compatibility" that most likely follow. In other words, it's a one-way upgrade with no going back.
