### ISSUE TITLE
volume replicate occasionally failed

### ISSUE THREAD

**Issue by 030io** [chrislusf/seaweedfs#318]
When I upload a lot of files(about 100-200/s), volume replicate occasionally failed. Some files lost.
The bug is very dangerous.

**Comment by chrislusf** [comment]
the files are not confirmed uploaded unless replication is successful. Why the files are considered lost? Did you confirm the upload return status?

**Comment by 030io** [comment]
I see. I upload a file and the replication is failed, one volume had the file, another volume have no the file.
And the file is leak, The database of filer have no that record.So I can't delete it.
I think we should add a filer monitor that regularly delete file which no in filer.

By the way, the performance is awesome.

**Comment by hxiaodon** [comment]
@030io, Could you provide more details about this issue?
1. How about the failure rate? 
2. How about the replication policy in your testing/production environment? 
3. Do you have replication between diff rack/IDC?  If yes, how about the network bandwidth/stability between the rack/IDC

**Comment by 030io** [comment]
@hxiaodon 
1. very low(about 0.1%)
2. replication = 100
3. two dataCenter at one server

上传的时候挺吃io的,现在用的是测试环境,如果是上集群,可能失败率会更高吧
这个项目有个坑,volume之间要相互连接,wiki上没写,看源码才知道.
如果是集群,那防火墙就不太好设置了.

**Comment by hxiaodon** [comment]
@030io 
Let me confirm about you prerequisite when try reproducing this issue
1.  Volume servers could connected with each other successfully now
2.  2  volume servers against diff IDC now are deployed at the same physical machine

And the file replication still have problem with a very low probability? how about the http status code, do you get any 4xx 5xx errors in your stress testing log?

**Comment by 030io** [comment]
1. yes
2. yes

volume log:
I0611 07:36:15 14928 upload_content.go:78] failing to upload to http://127.0.0.1:8081/2,4c09d5d9cef3?ts=1465644963&type=replicate Post http://127.0.0.1:8081/2,4c09d5d9cef3?ts=1465644963&type=replicate: write tcp 127.0.0.1:59593->127.0.0.1:8081: write: broken pipe
I0611 08:11:46 14928 needle.go:80] Reading Content [ERROR] multipart: Part Read: read tcp 127.0.0.1:8080->127.0.0.1:55500: i/o timeout
I0611 08:14:08 14928 needle.go:80] Reading Content [ERROR] multipart: Part Read: read tcp 127.0.0.1:8080->127.0.0.1:55865: i/o timeout
I0611 08:14:52 14928 needle.go:80] Reading Content [ERROR] multipart: Part Read: unexpected EOF
I0611 08:14:58 14928 needle.go:80] Reading Content [ERROR] multipart: Part Read: unexpected EOF
I0611 08:15:45 14928 upload_content.go:78] failing to upload to http://127.0.0.1:8081/2,af61b424dab4?ts=1465647272&type=replicate Post http://127.0.0.1:8081/2,af61b424dab4?ts=1465647272&type=replicate: write tcp 127.0.0.1:53046->127.0.0.1:8081: write: broken pipe

filer log:
I0612 01:06:36 27740 filer_server_handlers_write.go:254] failing to connect to volume server /data/aab9756d4df477ddb7101a102cd2a63dac6a2632/902 Post http://127.0.0.1:8080/5,024bb14e04d4ab: read tcp 127.0.0.1:8888->127.0.0.1:37420: i/o timeout
I0612 01:06:36 27740 filer_server_handlers_write.go:254] failing to connect to volume server /data/167a9f8c6f98bc7430177f45912314b1f58385f6/2545 Post http://127.0.0.1:8080/1,024baa9c160b39: read tcp 127.0.0.1:8888->127.0.0.1:37408: i/o timeout
I0612 01:06:36 27740 filer_server_handlers_write.go:274] failing to post to volume server /data/4753a3b5347a8f4f02a85a76a3814ffae337fc4b/4781 Failed to write to replicas for volume 4: [127.0.0.1:8081]: multipart: Part Read: read tcp 127.0.0.1:8081->127.0.0.1:58940: i/o timeout
I0612 01:06:36 27740 filer_server_handlers_write.go:274] failing to post to volume server /data/b36a9dd3a9345c1733e41e1ea4f27ffedf91d55d/4184 Failed to write to replicas for volume 6: [127.0.0.1:8081]: multipart: Part Read: read tcp 127.0.0.1:8081->127.0.0.1:59731: i/o timeout
I0612 01:06:36 27740 filer_server_handlers_write.go:254] failing to connect to volume server /data/2c7fac7a8b18716e7209fc4ad769642deab43ae1/1582 Post http://127.0.0.1:8080/2,024baf28a9bcd5: read tcp 127.0.0.1:8888->127.0.0.1:37418: i/o timeout
I0612 01:06:37 27740 filer_server_handlers_write.go:254] failing to connect to volume server /data/e9ab630c84ddf5b468983577fabb21af8b5289fa/2773 Post http://127.0.0.1:8080/2,024bb0d0e0dc79: read tcp 127.0.0.1:8888->127.0.0.1:37419: i/o timeout

**Comment by chrislusf** [comment]
The volume log shows there are some requests are timed out, and the client got the failed return status as expected.

A side note:
Do not use "/data/e9ab630c84ddf5b468983577fabb21af8b5289fa/2773", which will create too many folders under /data.
You can use "/data/e9ab630c84ddf5b468983577fabb21af8b5289fa.2773". One folder can hold a lot of files.
