### ISSUE TITLE
Can't failover volume servers?

### ISSUE THREAD

**Issue by wangfeiping** [chrislusf/seaweedfs#319]
Hi,
We have three servers.
192.168.1.185 master leader 9333 volmue 9360
192.168.1.186 master 9333 volmue 9360
192.168.1.187 master 9333 volmue 9360

defaultReplicaPlacement=001

I upload a file and the file store on 185/187,
when I request url http://192.168.1.186:9360/7,1c4e386c69, it will redirect me to http://192.168.1.185:9360/7,1c4e386c69.
and then I close 185,
when  I request url http://192.168.1.186:9360/7,1c4e386c69,  why it still redirect me to http://192.168.1.185:9360/7,1c4e386c69?
It's can't failover volume servers?

It's OK when I request master server by http://192.168.1.186:9333/7,1c4e386c69, it will redirect me to http://192.168.1.187:9360/7,1c4e386c69.

This issue can be modified, okay?

Thanks,
wangfeiping

**Comment by hxiaodon** [comment]
Hi,
Please take a look at the source code(lookup.go)
![image](https://cloud.githubusercontent.com/assets/10990210/15990937/3f497f6e-30d5-11e6-823a-7c932dce401b.png)
The default cache updating period is 10 mins at volume server side, so I think if you try request  http://192.168.1.186:9360/7,1c4e386c69 after 10mins, 192.168.1.187 will be returned as expected
maybe you could modify code/rebuild and have a try

**Comment by 030io** [comment]
都是中国人 扯什么英文呀😳

**Comment by hxiaodon** [comment]
@030io 
First,comment in English here is not a show-off.
We want to let all programmers around the world could review the historical issues, discussions and the proposed solutions comfortably. And all github users, gophers could communicate freely and contribute for this project as long as they have time and have interest in the place.
Hope for your understanding!  Thanks!
BTW,We could talk and discuss with IM tools(QQ,WeChat) in Chinese.

**Comment by 030io** [comment]
All right.
It's a joke.
You are too serious.

**Comment by chrislusf** [comment]
Actually I do not understand why the request need to go to http://192.168.1.186:9360/7,1c4e386c69 in the first place.

**Comment by chrislusf** [comment]
@030io The joke was not that funny to everyone. People with different backgrounds are trying to help. Any inappropriate comments can discourage many people who interpret it differently.

**Comment by wangfeiping** [comment]
@030io 
抱歉，我是初学，不知道原来中国人的开元项目啊，了不起，继续学习！希望以后有机会能够申请PR！

**Comment by wangfeiping** [comment]
@hxiaodon 非常感谢
