### ISSUE TITLE
volume.vacuum Storage gets bigger

### ISSUE THREAD

**Issue by trojansun** [chrislusf/seaweedfs#3194]
**Describe the bug**
After the volume.vacuum -garbageThreshold 0.001 command is executed, the disk storage becomes larger.
Before the command is executed, the disk storage occupies 2.1G, and after the command is executed, the disk storage occupies 8.1G.

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
- OS version : Ubuntu 20.04
- output of `weed version` : version 30GB 3.08 8a49240d64f5e53f119e58b923c3a6b25e85b37b linux amd64
- if using filer, show the content of `filer.toml`

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by chrislusf** [comment]
can not reproduce.
