### ISSUE TITLE
scan volume file with corrupted needle in it 

### ISSUE THREAD

**Issue by hxiaodon** [chrislusf/seaweedfs#321]
Chris,

Suppose we have the following prerequisite:
1.  Volume replication policy is 000
2.  User upload files with high concurrency and throughput

If  the physical machine is suddenly power down, the last needle which is being appended to a volume file possibly could lead to writing some fragmented data(dirty data) into disk(Disk write caching), I could think of 2 cases:
1 .Needle header is fragmented
2. Needle body is  fragmented

When this server is recovered,  we would try to fix the index file because the index file may be corrupted also. The fix could work because the corrupted needle is the last one, all valid needle's info will be write into the index file

+-------------+
|SuperBlock   |
+-------------+
|Needle1      |
+-------------+
|Needle2  corrupted    |

After the index is recreated and the volume server is online, the write operation will continue to append needle(Per seaweedfs's design, auto offset alignment will be implemented from the end of the file once there is a write operation) ，the currrent data structure is:

+-------------+
|SuperBlock   |
+-------------+
|Needle1      |
+-------------+
|Needle2  corrupted    |
+-------------+
|Needle3      |
+-------------+
|Needle ...   |
+-------------+

This could work as long as index file is OK, we just loss one file.  But if the index file is corrupted again,  weed fix could not find the Needle3's offset by adding current offset with Needle2's data size and padding size,all other needles after 3 will not be added into the index file

![image](https://cloud.githubusercontent.com/assets/10990210/16108347/2c3370c6-33d5-11e6-8db8-683ca6139cfd.png)

Chris,please help to review above draft code, I use iteratively scanning way to find the next valid needle's position(maybe not a good idea if the corrupted needle data writing into disk is very large)

I pop up this extreme corner case because I want to provide a more stronger disaster recovery solution when no backup data in other machine    

Hope for your suggestion, thanks!

**Comment by hxiaodon** [comment]
OK, My understanding has something wrong, the loading volume function will not do the offset alignment work(append something at the end of the dat file if the file size could not %8)

Could we design a barrier needle, each time the volume is restarted(or add a command option to explicitly specify), this barrier needle will be appended to the end of file(index will not be updated). The barrier needle has special flag(e.g it's fid is a const max int64 value, or something like 0xFE 0xDC 0xBA 0x98 0x76 0x54 0x32 0x10 ), then we could quickly find the next valid needle by searching this fid

If there has been another light/easy solution to solve this problem,please let me know.

**Comment by hxiaodon** [comment]
I tried to verify the data integrity at my local, with ScanVolumeFile's 6th parameter be true(readNeedleBody) and modify below code:
![image](https://cloud.githubusercontent.com/assets/10990210/16112565/6c948cee-33ea-11e6-9d81-41dd661633d2.png)
Although it took a little while to find the next valid needle(without barrier's needle's help, crc checksum is my lighthouse), it works. And the following needles' data is not corrupted, the scanning work triggered by abnormal branch will not run any more

**Comment by chrislusf** [comment]
I appreciate a lot for your careful thinking. This is one area SeaweedFS needs improving. How about let's do this:

When server starts up, volume server checks whether last index entry is working fine. If not, volume server will treat this volume as readonly.

This would be much more easier to test all edge cases. And it is possible to recover any data later.

**Comment by hxiaodon** [comment]
Checking last index entry/needle is a good idea, Could we just move volume's offset to the beginning of the last needle if it it corrupted? And we treat index file with the same policy. I know there is risk to make sure all edge cases could be satisfied in this way

Setting the corrupted volume file as readonly does protect the snapshot and DevOps could recover data manually

**Comment by chrislusf** [comment]
It's better not to overwrite anything, which will negate the append-only semantics.

**Comment by chrislusf** [comment]
Let me know whether you want to work on it.

**Comment by hxiaodon** [comment]
I will submit a code fix for it. If the volume file's last needle is corrupted, mark it as read only, and output some additional log to remind user(outside monitor framework could send alert mail/msg depending on those new logs ).

**Comment by hxiaodon** [comment]
The fix logic will be:
1. Add index checking when loading volume file(only needlemap in Memory will be checked,leveldb and boltdb should be recovered from corrupted status by themselves), the *.idx file's size%16==0 will pass, and then get last index offset(file size-16),verify it's content's integrity(checksum)
2. If the index is not needlemap in memory, finding the last needle from index is difficult, I will use ScanVolumeFile's way to get the last needle's info, verify it's integrity and recheck(try get it ) from the index file
3. If the index or the dat file is corrupted, mark the volume as read only and add addtional logs.

Chris, please provide your opinion, thanks!

**Comment by hxiaodon** [comment]
package storage volume.go load func() from line 108
My draft fix code is below:
![image](https://cloud.githubusercontent.com/assets/10990210/16361634/5b09052c-3bc9-11e6-9d60-2092493a910e.png)
Please help to take a review.

**Comment by chrislusf** [comment]
This logic is nice and simple.

Please refactor the code to smaller functions.
