### ISSUE TITLE
Files copied to seaweed via webdav show as 0 size when accessed via fuse

### ISSUE THREAD

**Issue by xdadrm** [chrislusf/seaweedfs#3217]
**Describe the bug**
Files show as zero size in a Fuse mount, when they were copied into the seaweed filer via WebDav (Linux mount or Windows).
Accessing those files via WebDav or Web Interface is finem as are files copied via Fuse mount.

**System Setup**

  // Complete reproduction under Screenshots
  
  weed server -webdav -s3 -volume.max 64 &
  weed mount -filer=localhost:8888   -dir=/mnt/weed/fuse 
  mount -t davfs http://localhost:7333/   /mnt/weed/dav
  
- OS version
  Ubuntu 20.04.4 LTS , Ubuntu 22.04 LTS
- output of `weed version`
  version 30GB 3.12 4dc27e1ed598b1c1aa4facae856da1f71df00ea1 linux amd64
  (same results for 2.99, 3.02)
- if using filer, show the content of `filer.toml`
  empty

**Expected behavior**

Files show the true content even when written via WebDav.

**Screenshots**

apt install davfs2

# Setup
weed server -webdav -s3 -volume.max 64 &
weed mount -filer=localhost:8888           -dir=/mnt/weed/fuse 
mount -t davfs http://localhost:7333/   /mnt/weed/dav

# Reproduction
cp ./weed /mnt/weed/fuse/fuse_test_file1		# Write via Fuse
cp ./weed /mnt/weed/dav/dav_test_file2			# Write via WebDav

# Result
md5sum  /mnt/weed/*/*_test_file*
d5cf90a10d098152a6ede3f788b5fad2  /mnt/weed/dav/dav_test_file2
d5cf90a10d098152a6ede3f788b5fad2  /mnt/weed/dav/fuse_test_file1
d41d8cd98f00b204e9800998ecf8427e  /mnt/weed/fuse/dav_test_file2    <<< read 'WebDav' File via Fuse
d5cf90a10d098152a6ede3f788b5fad2  /mnt/weed/fuse/fuse_test_file1

ls -l /mnt/weed/fuse/dav_test_file2
-rw-rw-rw- 1 root root 0 Jun 21 14:43 /mnt/weed/fuse/dav_test_file2  << indeed, zero size

**Additional context**

Files copied into the filer via S3 also show correctly via WebDav and Fuse, the issue appears to be with writing via WebDav and then accessing via Fuse only

A very ugly reproducer script attached, benefits from rclone, devfs2 , fuser installed.
weed is expected in the current directory, **do not run on your production system** !

[test_seaweed.txt](https://github.com/chrislusf/seaweedfs/files/8950190/test_seaweed.txt)
.

**Comment by chrislusf** [comment]
I am using Mac and it worked fine.

**Comment by xdadrm** [comment]
Hm, I can reproduce on multiple systems - all Ubuntu though.

**Comment by Stitch10925** [comment]
This might explain a discussion I started a while ago:
https://github.com/chrislusf/seaweedfs/discussions/2898

I hope this fixes it. Thanks!
