### ISSUE TITLE
[bug:filer] rpc error: code = Unavailable desc = cl osing transport due to: connection error: desc = "error reading from server: EOF", received prior goaway: code: NO_ERROR

### ISSUE THREAD

**Issue by famosss** [chrislusf/seaweedfs#3219]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**
Some `filer` servers can't recover after the server throw exceptions.
Here are the exceptions
<img width="1399" alt="image" src="https://user-images.githubusercontent.com/10348876/175193549-74cebc47-1d5f-4e17-bd4a-bd645c52f649.png">

I have 6 `filer` servers,5 servers recover after throw the exceptions .the last `filer` server also has the `timewait` connection problem
<img width="975" alt="image" src="https://user-images.githubusercontent.com/10348876/175194169-b2a145cf-5255-49db-b9a4-70c8d1ed59f6.png">

master and volume servers have no error log.

**System Setup**
weed version: 3.12

**Comment by kmlebedev** [comment]
@famosss This seems to be normal, since the gRPC server closes all client connections every 10 hours and they hang in the time_white state for some time.

**Comment by famosss** [comment]
> @famosss This seems to be normal, since the gRPC server closes all client connections every 10 hours and they hang in the time_white state for some time.

I think the server should retry itself at least.

**Comment by famosss** [comment]
fixed.
<img width="630" alt="image" src="https://user-images.githubusercontent.com/10348876/175790253-c004df2e-8323-4d82-9614-41cef30c6b0f.png">
