### ISSUE TITLE
why the new volume is always "Volumes": 0

### ISSUE THREAD

**Issue by wangfeiping** [chrislusf/seaweedfs#322]
Hi,
I have 3 masters and 5 volume servers.
But why the new volume -192.168.1.187:9361 is always "Volumes": 0?

I use cmd like this:
nohup ./weed server -master.port=9333 \
  -master.conf /etc/weedfs/weedfs.conf \
  -master.defaultReplicaPlacement=002 \
  -dir="/apps/seaweedfs/volume-data" -volume.port=9360 -ip="192.168.1.185" \
  -master.peers=192.168.1.185:9333,192.168.1.186:9333,192.168.1.187:9333 \
  -volume.max 100 \
  >> master-nohup.out &

and

nohup ./weed volume -max=100 -mserver="192.168.1.185:9333" -dir="/apps/seaweedfs/volume-data2" \
  -ip="192.168.1.187" \
  -port 9361 \
  >> vol2-nohup.out &

Is there something wrong?

Thanks,
wangfeiping

{
  "Topology": {
    "DataCenters": [
      {
        "Free": 477,
        "Id": "dc1",
        "Max": 500,
        "Racks": [
          {
            "DataNodes": [
              {
                "Free": 97,
                "Max": 100,
                "PublicUrl": "192.168.1.187:9360",
                "Url": "192.168.1.187:9360",
                "Volumes": 3
              },
              {
                "Free": 100,
                "Max": 100,
                "PublicUrl": "192.168.1.187:9361",
                "Url": "192.168.1.187:9361",
                "Volumes": 0
              },
              {
                "Free": 89,
                "Max": 100,
                "PublicUrl": "192.168.1.185:9360",
                "Url": "192.168.1.185:9360",
                "Volumes": 11
              },
              {
                "Free": 94,
                "Max": 100,
                "PublicUrl": "192.168.1.186:9360",
                "Url": "192.168.1.186:9360",
                "Volumes": 6
              },
              {
                "Free": 97,
                "Max": 100,
                "PublicUrl": "192.168.1.185:9361",
                "Url": "192.168.1.185:9361",
                "Volumes": 3
              }
            ],
            "Free": 477,
            "Id": "rack1",
            "Max": 500
          }
        ]
      },
      {
        "Free": 0,
        "Id": "DefaultDataCenter",
        "Max": 0,
        "Racks": [
          {
            "DataNodes": null,
            "Free": 0,
            "Id": "DefaultRack",
            "Max": 0
          }
        ]
      }
    ],
    "Free": 477,
    "Max": 500,
    "layouts": [
      {
        "collection": "",
        "replication": "001",
        "ttl": "",
        "writables": null
      },
      {
        "collection": "",
        "replication": "002",
        "ttl": "",
        "writables": [
          17,
          18,
          19,
          15,
          16,
          14
        ]
      }
    ]
  },
  "Version": "0.70"
}

**Comment by hxiaodon** [comment]
the volume service could specify a dir list(seperated by comma) in it's command option,e.g
nohup ./weed server -master.port=9333 \
-master.conf /etc/weedfs/weedfs.conf \
-master.defaultReplicaPlacement=002 \
-dir="/apps/seaweedfs/volume-data,/apps/seaweedfs/volume-data2" -volume.port=9360 -ip="192.168.1.185" \
-master.peers=192.168.1.185:9333,192.168.1.186:9333,192.168.1.187:9333 \
-volume.max 200 

I think running one volume service at each physical machine/vm is a better choice~

Regarding your original question, I 'm also curious why.. Maybe the current assignment policy is to average write operation by machine/node instead of service instance

**Comment by wangfeiping** [comment]
@hxiaodon Thanks!

I just try to add volume servers. I can't control the online environment.
But it's still help me more, thank you!

**Comment by chrislusf** [comment]
When you just add a volume server, the volumes would not be used until new volumes are needed.

New volumes are needed when some volumes are almost full or a new kind of volumes(different TTL, different replication, etc) is requested.

You can use this API to allocate volumes directly. 
https://github.com/chrislusf/seaweedfs/wiki/API#pre-allocate-volumes

**Comment by wangfeiping** [comment]
@chrislusf Oh! Thanks!
