### ISSUE TITLE
[bug:filer]  failed to stream content /osss3/tests3/172.25.82.20-1MB-y1xglnh601-969216: volume 4182 not found

### ISSUE THREAD

**Issue by famosss** [chrislusf/seaweedfs#3220]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs
 Maybe related to [3219](https://github.com/chrislusf/seaweedfs/issues/3219)

**Describe the bug**
`Filer` server can't get the latest topo.

**master log.**

`weed.szth-24-10-131.root.log.INFO.20220622-100458.8:I0623 03:00:02     8 volume_layout.go:222] volume 4182 does not have enough copies

weed.szth-24-10-131.root.log.INFO.20220622-100458.8:I0623 03:00:02     8 volume_layout.go:227] volume 4182 remove from writable

weed.szth-24-10-131.root.log.INFO.20220622-100458.8:I0623 03:00:02     8 volume_growth.go:235] Created Volume 4182 on topo:idc1:rack1:172.24.10.131:32588

weed.szth-24-10-131.root.log.INFO.20220622-100458.8:I0623 03:00:02     8 volume_layout.go:222] volume 4182 does not have enough copies

weed.szth-24-10-131.root.log.INFO.20220622-100458.8:I0623 03:00:02     8 volume_layout.go:227] volume 4182 remove from writable

weed.szth-24-10-131.root.log.INFO.20220622-100458.8:I0623 03:00:02     8 volume_layout.go:391] Volume 4182 becomes writable

weed.szth-24-10-131.root.log.INFO.20220622-100458.8:I0623 03:00:02     8 volume_growth.go:235] Created Volume 4182 on topo:idc1:rack2:172.24.66.7:32580

weed.szth-24-10-131.root.log.INFO.20220622-100458.8:I0623 03:34:08     8 volume_layout.go:457] Volume 4182 becomes crowded

weed.szth-24-10-131.root.log.INFO.20220622-100458.8:I0623 03:40:12     8 volume_layout.go:378] Volume 4182 becomes unwritable

weed.szth-24-10-131.root.log.INFO.20220622-100458.8:I0623 03:40:12     8 volume_layout.go:445] Volume 4182 reaches full capacity.

weed.szth-24-10-131.root.log.INFO.20220623-100022.8:I0623 10:00:48     8 volume_layout.go:222] volume 4182 does not have enough copies

weed.szth-24-10-131.root.log.INFO.20220623-100022.8:I0623 10:00:48     8 volume_layout.go:227] volume 4182 remove from writable`

**filer server log**

`E0623 03:00:02     8 filer_server_handlers_read.go:244] failed to stream content /osss3/tests3/172.25.82.20-1MB-y1xglnh601-969216: volume 4182 not found

E0623 03:00:02     8 common.go:287] processRangeRequest headers: map[Accept-Ranges:[bytes] Access-Control-Expose-Headers:[Content-Disposition] Content-Disposition:[inline; filename="172.25.82.20-1MB-y1xglnh601-969216"] Content-Length:[1048576] Content-Type:[video/avi] Etag:["72f4fdcbd826b1e7b2869eaae94f9095"] Last-Modified:[Wed, 22 Jun 2022 19:00:02 GMT] Server:[SeaweedFS Filer 30GB 3.12]] err: volume 4182 not found

E0623 03:00:02     8 filer_server_handlers_read.go:244] failed to stream content /osss3/tests3/172.25.82.20-1MB-y1xglnh601-969216: volume 4182 not found

E0623 03:00:02     8 common.go:287] processRangeRequest headers: map[Accept-Ranges:[bytes] Access-Control-Expose-Headers:[Content-Disposition] Content-Disposition:[inline; filename="172.25.82.20-1MB-y1xglnh601-969216"] Content-Length:[1048576] Content-Type:[video/avi] Etag:["72f4fdcbd826b1e7b2869eaae94f9095"] Last-Modified:[Wed, 22 Jun 2022 19:00:02 GMT] Server:[SeaweedFS Filer 30GB 3.12]] err: volume 4182 not found

E0623 03:00:02     8 filer_server_handlers_read.go:244] failed to stream content /osss3/tests3/172.24.17.109-1MB-phzo4e7s31-930184: volume 4182 not found

E0623 03:00:02     8 common.go:287] processRangeRequest headers: map[Accept-Ranges:[bytes] Access-Control-Expose-Headers:[Content-Disposition] Content-Disposition:[inline; filename="172.24.17.109-1MB-phzo4e7s31-930184"] Content-Length:[1048576] Content-Type:[video/avi] Etag:["72f4fdcbd826b1e7b2869eaae94f9095"] Last-Modified:[Wed, 22 Jun 2022 19:00:02 GMT] Server:[SeaweedFS Filer 30GB 3.12]] err: volume 4182 not found

E0623 03:00:02     8 filer_server_handlers_read.go:244] failed to stream content /osss3/tests3/172.25.82.17-1MB-xve4uqscw2-952044: volume 4182 not found

E0623 03:00:02     8 common.go:287] processRangeRequest headers: map[Accept-Ranges:[bytes] Access-Control-Expose-Headers:[Content-Disposition] Content-Disposition:[inline; filename="172.25.82.17-1MB-xve4uqscw2-952044"] Content-Length:[1048576] Content-Type:[video/avi] Etag:["72f4fdcbd826b1e7b2869eaae94f9095"] Last-Modified:[Wed, 22 Jun 2022 19:00:02 GMT] Server:[SeaweedFS Filer 30GB 3.12]] err: volume 4182 not found

E0623 03:00:02     8 filer_server_handlers_read.go:244] failed to stream content /osss3/tests3/172.24.17.109-1MB-phzo4e7s31-930184: volume 4182 not found

E0623 03:00:02     8 common.go:287] processRangeRequest headers: map[Accept-Ranges:[bytes] Access-Control-Expose-Headers:[Content-Disposition] Content-Disposition:[inline; filename="172.24.17.109-1MB-phzo4e7s31-930184"] Content-Length:[1048576] Content-Type:[video/avi] Etag:["72f4fdcbd826b1e7b2869eaae94f9095"] Last-Modified:[Wed, 22 Jun 2022 19:00:02 GMT] Server:[SeaweedFS Filer 30GB 3.12]] err: volume 4182 not found

E0623 03:00:02     8 filer_server_handlers_read.go:244] failed to stream content /osss3/tests3/172.24.17.91-1MB-j21ca34sz6-978636: volume 4182 not found`

weed version:3.12

**Comment by LuckyFrost** [comment]
Similarly, I have problems with the fact that the filer often receives addresses of volume servers that do not have the requested data.
