### ISSUE TITLE
Filer unable to sync correctly after shutdown or restart

### ISSUE THREAD

**Issue by CaptainChaos** [chrislusf/seaweedfs#3224]
**Describe the bug**
We are using seaweedfs in a three-node cluster setup with docker swarm. Every node runs one master, one volume server and one filer. The filers are configured to use a local leveldb2 with persistent mounts, the volume servers have a persistent mount, too. There are no recurring jobs configured e.g. for volume.fix.replication etc.

In the very beginning of our setup, we restarted the stack regularly and experienced synchronisation problems between the filer instances, when all services were _basically_ brought up at the same time. This showed by some of the filers giving 404 on different files. We could fix it with fs.meta.save and doing fs.meta.load right afterwards. We also found out that if we bring up one filer with a complete, uncorrupted state first and add more filers later (when the complete and "unbroken" filer is already running), they sync correctly. The same was true for having multiple uncorrupted filers running and adding more fresh filers to the game later.

To circumvent the problem, we took seaweed out of our swarm stack which is regularly redeployed, and deployed it as its own stack so it is running constantly. Our feeling was that although master and volume server seemed to work fine with regular redeploys, filer often broke, sadly without giving us a clue in the logs about why it did - and with broke, I mean corrupted in a way that not all filers know about all files, giving 404 errors "randomly", but consistently for their own broken / missing files, i.e. the broken / missing files in a running filer don't change, but not every filer has the same broken files.

Last week, one of our three nodes briefly lost connection / went down, so one filer, one master and one volume server also went down for roughly one minute. After recovery, the node came back up and the three services re-joined the seaweed stack. Although there were no problems with the master or volume server, this third filer service now again had a broken database state in a similar way we experienced earlier when regularly restarting the services. It just gave us 404 on multiple files, although cluster.check, volume.list etc indicated that everything in our stack was healthy (no connection issues etc). Although fs.ls and therefor fs.meta.save seemed to give us a correct list of files, fs.meta.load didn't restore the broken (third) filer into a correct state.

We fixed it by stopping the corrupted filer container, deleting its data mount folder and bringing it back up clean. It correctly synchronized and everything is just fine again. Still, there seem to be issues with automatic filer synchronisation, preventing clusters from automatic failover recovery.

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
```
weed -v 3 -logtostderr=true filer -master=seaweedmaster-stagingnode01:9333,seaweedmaster-stagingnode02:9333,seaweedmaster-stagingnode03:9333 -s3 -s3.config=/etc/seaweedfs/s3.json -s3.port=8333
weed -v 3 -logtostderr=true master -ip=seaweedmaster-stagingnode01 -port=9333 -peers=seaweedmaster-stagingnode01:9333,seaweedmaster-stagingnode02:9333,seaweedmaster-stagingnode03:9333 -volumeSizeLimitMB=1024 -mdir=/data -volumePreallocate -defaultReplication=001
weed -v 3 -logtostderr=true volume -dir=/data -max=0 -mserver=seaweedmaster-stagingnode01:9333,seaweedmaster-stagingnode02:9333,seaweedmaster-stagingnode03:9333 -port=8080 -preStopSeconds=1
```

- OS version
`chrislusf/seaweedfs:3.09@sha256:5ead33097d7184a0ccebda48939d38fa2ccf5b1a6119b57ce21edf2e36fb0037@sha256:6cd760a0510c4148ec2b7eb129e858f373eed82f7ab53e71f6f30afe044fe58b`
- output of `weed version`
`version 30GB 3.09 4a046e4d linux amd64`
- if using filer, show the content of `filer.toml`
```
[leveldb2]
enabled = true
dir = "/data/filerldb2"
```

**Expected behavior**
We would expect filer instances which are brought down and back up again to be able to sync up with the existing filer instances.

**Screenshots**

**Additional context**
Lots of "Not found /buckets/... : filer: no entry found in filer store" - only in the corrupt filer node though.

```
I0622 18:28:20     1 auth_credentials.go:220] v4 auth type
I0622 18:28:20     1 auth_credentials.go:249] user name: ****** actions: [Admin Read List Tagging Write], action: Read
I0622 18:28:20     1 s3api_object_handlers.go:138] GetObjectHandler ****** /2081845fb21db096c5a376d20c0215bd27ff374233e30e048865f2d76979e20b
I0622 18:28:20     1 s3api_object_handlers.go:315] s3 proxying GET to http://192.168.77.2:8888/buckets/*****/2081845fb21db096c5a376d20c0215bd27ff374233e30e048865f2d76979e20b
I0622 18:28:20     1 filer_server_handlers_read.go:98] Not found /buckets/******/2081845fb21db096c5a376d20c0215bd27ff374233e30e048865f2d76979e20b: filer: no entry is found in filer store
I0622 18:28:20     1 auth_credentials.go:220] v4 auth type
I0622 18:28:20     1 auth_credentials.go:249] user name: ****** actions: [Admin Read List Tagging Write], action: Read
I0622 18:28:20     1 s3api_object_handlers.go:138] GetObjectHandler ****** /d3cfc99c87dfae1b47c9f3bcceedcbae217e1e1d02c4b511f01e0987f2323ad6
I0622 18:28:20     1 s3api_object_handlers.go:315] s3 proxying GET to http://192.168.77.2:8888/buckets/******/d3cfc99c87dfae1b47c9f3bcceedcbae217e1e1d02c4b511f01e0987f2323ad6
I0622 18:28:20     1 filer_server_handlers_read.go:98] Not found /buckets/*****/d3cfc99c87dfae1b47c9f3bcceedcbae217e1e1d02c4b511f01e0987f2323ad6: filer: no entry is found in filer store
```

**Comment by chrislusf** [comment]
The filers are using embedded leveldb. To make them really work like one cross node database, the metadata are replicated asynchronously. So there are some metadata not replicated in time due to sudden server shutdown.

Later we may add more metadata replication at the cost of response latency. But in the end, this is similar to implement a distributed database for the metadata. You may as well start to use a well-established shared database such as redis/cassandra/mysql/postgres/HBase/...

**Comment by chrislusf** [comment]
btw: this is being worked on as part of a new message pubsub feature. Just it would not be resolved very soon.
