### ISSUE TITLE
Can't see stored files on the filer page

### ISSUE THREAD

**Issue by chieftain-m** [chrislusf/seaweedfs#3229]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs
Report issues here. Ask questions here https://stackoverflow.com/questions/tagged/seaweedfs
Please ask questions in https://github.com/chrislusf/seaweedfs/discussions

**Describe the bug**
 I accidentally restarted the server cluster.the previously stored files are all there, but I can't see them on the filer page.

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
I set up the file system according to the following steps,
![image](https://user-images.githubusercontent.com/53212322/175552553-e0fa4c96-a4af-4e84-9557-719fed7f6e35.png)

- OS version
linux centos7.6

**Expected behavior**
**while I accidentally restarted the server cluster. I restarted the file system and performed the same steps as before.**
![65c72b5a8cf9851fcda386849a7e3a1](https://user-images.githubusercontent.com/53212322/175545644-de5eed55-afc9-4d81-a41c-5864afbe9a9c.png)

 **the previously stored files are all there, but I can't see them on the filer page.**
![6dcca904671797779de2dfc8a55812c](https://user-images.githubusercontent.com/53212322/175545696-d25d4b4c-7280-466c-927d-b84005d6b100.png)

**Comment by chieftain-m** [comment]
Can I still access the previous data in the old system, or the data is inaccessible in the new system？

**Comment by chrislusf** [comment]
find the folder `filerldb2`. If it is a restart, the folder should still be there.

**Comment by chieftain-m** [comment]
![image](https://user-images.githubusercontent.com/53212322/175754716-f29507ae-d6c7-4e43-bca3-2efbdc86d71c.png)
I find the folder `filerldb2`，it was built during the old system. How can I get the data?
