### ISSUE TITLE
Question: Why is everything logged to stderr?

### ISSUE THREAD

**Issue by de-robat** [chrislusf/seaweedfs#324]
First of all: Thank you for the module. Its awesome and works as expected in a really robust manner.

One thing im wondering about though, is that while starting the server and connecting seaweed volumes to a master server, several messages are logged via stderr instead of std out. Even though they are not really errors but rather information loggings. Has this any particular reason which im not aware of? We use the module in an integrated environment where we startup lots of different processes automatically, and within this system the seaweed module polutes our error log.

Any hints on why you've opted to just use stderr would be appreciated. Thanks in advance!

**Comment by chrislusf** [comment]
Thanks! Glad to hear that. You can share your use case with us or in some blog if allowed. This will encourage all committers here.

The logging behavior comes from the google's glog package. If you do "weed -h", you will see the glog options. "-alsologtostderr" is the one you may want to change.
