### ISSUE TITLE
About the main data center's usage

### ISSUE THREAD

**Issue by hxiaodon** [chrislusf/seaweedfs#325]
Chris:
I have a question about the "main data center". I thought that it means that the replication policy will be firstly implemented on the main data center.
Suppose I have 2 data center A and B, A is the main data center. My replication policy is 101, there will be 3 copy of  each volume file. 2 in same data center, and 1 in another.   
Initially there isn't any volume file  at each volume node. If I specify the datacenter name before curl dir/assign(http://localhost:9333/dir/assign?dataCenter=A), seaweed could always create 2 copy of volume file at main data center and 1 copy of volume file at the other data center if necessary? 
If I misunderstood the concept of main data center, please point out.
Thanks!

**Comment by hxiaodon** [comment]
I reviewed the relevant code

`
func (vg *VolumeGrowth) findEmptySlotsForOneVolume(topo *Topology, option *VolumeGrowOption) (servers []*DataNode, err error) {
......
}
`

The code logic seems match my assumption(main data center will have no less than half of the volume file's copy against a specific volume Id). Now my only concern is:
The RandomlyPickNodes function at  Line96 will try to find the main data center node under the topo root node as long as I explicitly specify the dataCenter Name when calling dir/assign. And the initial creating file operation will be failed with probability of 50%. Is this a bug?

**Comment by hxiaodon** [comment]
Never mind! The code has no problem.

**Comment by hxiaodon** [comment]
Chris:
Seems that  I need to add  2 additional parameter(dataCenter,rack) for the Assign function(assign_file_id.go) so that I could use the main data center/main rack feature
Please feel free to close this issue if my understanding has no problem. 
Thanks!

**Comment by chrislusf** [comment]
That's correct.
