### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by xxr3376** [chrislusf/seaweedfs#328]
## Version
* SeaweedFS: version 0.71 beta linux amd64
* Go: go version go1.6.1 linux/amd64

## Problem
I encounter this error in one **volume server** when I **read & write to same collection** heavily.

> fatal error: concurrent map read and map write
> 
> goroutine 2258 [running]:
> runtime.throw(0xe4f180, 0x21)
>         /usr/local/go/src/runtime/panic.go:530 +0x90 fp=0xc82601d280 sp=0xc82601d268
> runtime.mapaccess2_fast64(0xaecc60, 0xc823a5ccf0, 0x1fd21d2, 0x453096, 0xc82001c00c)
>         /usr/local/go/src/runtime/hashmap_fast.go:157 +0x5a fp=0xc82601d2a0 sp=0xc82601d280
> github.com/chrislusf/seaweedfs/go/storage.(*CompactSection).Get(0xc8248370c0, 0x1fd21d2, 0x0, 0x0)
>         /home/xxr/golang/src/github.com/chrislusf/seaweedfs/go/storage/compact_map.go:82 +0x59 fp=0xc82601d2d8 sp=0xc82601d2a0
> github.com/chrislusf/seaweedfs/go/storage.(*CompactMap).Get(0xc825f44180, 0x1fd21d2, 0xf0d9c1, 0xc800000002)
>         /home/xxr/golang/src/github.com/chrislusf/seaweedfs/go/storage/compact_map.go:150 +0x91 fp=0xc82601d318 sp=0xc82601d2d8
> github.com/chrislusf/seaweedfs/go/storage.(*NeedleMap).Get(0xc825f44180, 0x1fd21d2, 0x2, 0x42ee47)
>         /home/xxr/golang/src/github.com/chrislusf/seaweedfs/go/storage/needle_map_memory.go:92 +0x32 fp=0xc82601d340 sp=0xc82601d318
> github.com/chrislusf/seaweedfs/go/storage.(*Volume).readNeedle(0xc823984980, 0xc829756dc0, 0xc823984980, 0x0, 0x0)
>         /home/xxr/golang/src/github.com/chrislusf/seaweedfs/go/storage/volume.go:286 +0x76 fp=0xc82601d408 sp=0xc82601d340
> github.com/chrislusf/seaweedfs/go/storage.(*Store).ReadVolumeNeedle(0xc8201fe080, 0xc8000000f4, 0xc829756dc0, 0x4, 0x0, 0x0)
>         /home/xxr/golang/src/github.com/chrislusf/seaweedfs/go/storage/store.go:329 +0x67 fp=0xc82601d488 sp=0xc82601d408
> github.com/chrislusf/seaweedfs/go/weed/weed_server.(*VolumeServer).GetOrHeadHandler(0xc8202000e0, 0x7fa61fc93478, 0xc824604dd0, 0xc82beac1c0)
>         /home/xxr/golang/src/github.com/chrislusf/seaweedfs/go/weed/weed_server/volume_server_handlers_read.go:67 +0x174d fp=0xc82601da88 sp=0xc82601d488
> github.com/chrislusf/seaweedfs/go/weed/weed_server.(*VolumeServer).privateStoreHandler(0xc8202000e0, 0x7fa61fc93478, 0xc824604dd0, 0xc82beac1c0)
>         /home/xxr/golang/src/github.com/chrislusf/seaweedfs/go/weed/weed_server/volume_server_handlers.go:28 +0xf6 fp=0xc82601dad0 sp=0xc82601da88
> github.com/chrislusf/seaweedfs/go/weed/weed_server.(*VolumeServer).(github.com/chrislusf/seaweedfs/go/weed/weed_server.privateStoreHandler)-fm(0x7fa61fc93478, 0xc824604dd0, 0xc82b
> eac1c0)
>         /home/xxr/golang/src/github.com/chrislusf/seaweedfs/go/weed/weed_server/volume_server.go:64 +0x3e fp=0xc82601daf8 sp=0xc82601dad0
> net/http.HandlerFunc.ServeHTTP(0xc82053e170, 0x7fa61fc93478, 0xc824604dd0, 0xc82beac1c0)
>         /usr/local/go/src/net/http/server.go:1618 +0x3a fp=0xc82601db18 sp=0xc82601daf8
> net/http.(*ServeMux).ServeHTTP(0xc8201d4750, 0x7fa61fc93478, 0xc824604dd0, 0xc82beac1c0)
>         /usr/local/go/src/net/http/server.go:1910 +0x17d fp=0xc82601db70 sp=0xc82601db18
> net/http.serverHandler.ServeHTTP(0xc8201fe400, 0x7fa61fc93478, 0xc824604dd0, 0xc82beac1c0)
>         /usr/local/go/src/net/http/server.go:2081 +0x19e fp=0xc82601dbd0 sp=0xc82601db70
> net/http.(*conn).serve(0xc827695b00)
>         /usr/local/go/src/net/http/server.go:1472 +0xf2e fp=0xc82601df98 sp=0xc82601dbd0
> runtime.goexit()
>         /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82601dfa0 sp=0xc82601df98
> created by net/http.(*Server).Serve
>         /usr/local/go/src/net/http/server.go:2137 +0x44e

**Comment by chrislusf** [comment]
Seems your version is a little bit different from mine. Knowing the git hash would be better.

Added a possible fix. Not sure whether you could consistently reproduce this. Let me know how it works.

**Comment by hxiaodon** [comment]
@xxr3376 
RWLock has been added  in newest code [link](https://github.com/chrislusf/seaweedfs/blob/master/weed/storage/compact_map.go)
You could rebuild with the latest one and try again.

**Comment by xxr3376** [comment]
I loss the source directory of the binary file that I am currently using, That's why I didn't mention the git hash.
Anyway, I'll try the latest fix. I'am not sure that I can reproduce the problem, but I'll let you know if I find anything wrong.
