### ISSUE TITLE
[volume] stuck and CPU overload

### ISSUE THREAD

**Issue by kmlebedev** [chrislusf/seaweedfs#3282]
**Describe the bug**

stuck and CPU overload

**System Setup**
```
seaweedfs:3.04
```

**Additional context**

log kill -3 
[volume.stuck.trace.txt](https://github.com/chrislusf/seaweedfs/files/9064798/volume.stuck.trace.txt)

**Comment by chrislusf** [comment]
many go routines are stuck at 

```
github.com/chrislusf/seaweedfs/weed/storage/backend.(*DiskFile).ReadAt(0x40d625?, {0xc0f7470000?, 0x6f2946?, 0x1?}, 0xc0030f47db?)
	/Users/tochka/GolandProjects/seaweedfs/weed/storage/backend/disk_file.go:40 +0x25
```

It is just `*os.File.ReadAt()`. Not sure why it is stuck.

**Comment by blacktear23** [comment]
Is your block device stucked? Or weed process is at D status?

**Comment by kmlebedev** [comment]
add GOMAXPROC
