### ISSUE TITLE
写入变慢

### ISSUE THREAD

**Issue by thwlxmyljz** [chrislusf/seaweedfs#3285]
环境：
1、一个master，一个volumn，写入通过master的submit直接写
2、volumn服务磁盘有大约14T空间，volumn服务启动参数-max=1000
3、volumn服务器数据文件：单个dat文件是30G，一共产生了226个dat文件，大约是6T多，还有7T多空余空间
问题：
现在写入很慢，大部分写入都超时了，volumn上为啥不继续建立新的dat文件去存数据呢，不是还有很多空间么？

**Comment by thwlxmyljz** [comment]
version 30GB 2.20 f0d3b3b linux amd64

**Comment by chrislusf** [comment]
can not help without reproducible steps.

Try not to use master submit. It is not for production.
