### ISSUE TITLE
Writing benchmark  performance has big difference when whiteList enabled！

### ISSUE THREAD

**Issue by Adesun** [chrislusf/seaweedfs#330]
version 0.70  windows amd64. 

starting one master and  two volumes on host 192.168.8.2,  two volumes locate on different harddriver. starting benchmark on host 192.168.8.1, request per second whiteList disabled  is almost **six times** than request whiteList enabled, refer to attached files for details.

 weed -log_dir="D:\\Program Files\\seaweed\\Log\\" -alsologtostderr=false -v=4  master -mdir="D:\\Program Files\\seaweed\\Meta\\" -ip="192.168.8.2" -port=9555 **-whiteList="192.168.8.2,192.168.8.1"** 

 weed volume -dataCenter="DE" -dir="E:\\ProgramData\\SeaWeed\\" -mserver="192.168.8.2:9555" -ip="192.168.8.2" -port=9556
 weed volume -dataCenter="DG" -dir="G:\\ProgramData\\SeaWeed\\" -mserver="192.168.8.2:9555" -ip="192.168.8.2" -port=9557

[disabled.txt](https://github.com/chrislusf/seaweedfs/files/333624/disabled.txt)

[enable.txt](https://github.com/chrislusf/seaweedfs/files/333625/enable.txt)

**Comment by chrislusf** [comment]
whiteList should be enabled for both master server and volume server if you need to use it in production.

If enabled both on the master and volume server, the read operation could also be slower. Please help to check.

The operation to find IP address seems too slow somehow on your server. But I can not reproduce this.

To profile the program, when starting master server, you can add this option:
 -cpuprofile="master.prof"
to collect the profiling, and post the profiling here if you do not know how to read it.

**Comment by Adesun** [comment]
I got error message as follows when starting master with the option -cpuprofile="master.prof"

`weed -log_dir="D:\\Program Files\\seaweed\\Log\\" -alsologtostderr=false -v=4  master -mdir="D:\\Program Files\\seaweed\\Meta\\" -ip="192.168.8.2" -port=9555 -whiteList="192.168.8.2,192.168.8.1"   -cpuprofile="master.prof"`

`flag provided but not defined: -cpuprofile`

so just enabled whiteList both on the master and volume server, then test

`weed -log_dir="D:\\Program Files\\seaweed\\Log\\" -alsologtostderr=false -v=4 -cpuprofile="master.prof"  master -mdir="D:\\Program Files\\seaweed\\Meta\\" -ip="192.168.8.2" -port=9555 -whiteList="192.168.8.2,192.168.8.1" 

weed volume -dataCenter="DE" -dir="E:\\ProgramData\\SeaWeed\\" -mserver="192.168.8.2:9555" -ip="192.168.8.2" -port=9556 -whiteList="192.168.8.2,192.168.8.1" 

weed volume -dataCenter="DG" -dir="G:\\ProgramData\\SeaWeed\\" -mserver="192.168.8.2:9555" -ip="192.168.8.2" -port=9557 -whiteList="192.168.8.2,192.168.8.1" `

Writing and reading performance roughly looked the same as volume's whiteList disabled. refer to attached  **enabled.txt**  for details.

I also noticed the parameter of "weed server", so tried starting master and volume together

`weed -log_dir="D:\\Program Files\\seaweed\\Log\\" -alsologtostderr=false -v=4  server -cpuprofile="master.prof" -master.dir="D:\\Program Files\\seaweed\\Meta\\" -dataCenter="DE" -dir="E:\\ProgramData\\SeaWeed\\"  -ip="192.168.8.2" -master.port=9555 -volume.port=9556 -whiteList="192.168.8.2,192.168.8.1" `

and starting another volume 

`weed volume -dataCenter="DG" -dir="G:\ProgramData\SeaWeed\" -mserver="192.168.8.2:9555" -ip="192.168.8.2" -port=9557 -whiteList="192.168.8.2,192.168.8.1" `

Writing and reading  performance is normal and nearly the same as whiteList disabled. a little weird!
efer to attached  **enabled_server_mode.txt**  for details.

[enabled.txt](https://github.com/chrislusf/seaweedfs/files/334114/enabled.txt)

[enabled_server_mode.txt](https://github.com/chrislusf/seaweedfs/files/334115/enabled_server_mode.txt)

**Comment by Adesun** [comment]
@chrislusf 
any update about this ?

**Comment by chrislusf** [comment]
I tried your setup locally but can not reproduce anything similar.

I added profiling to "weed master".

 weed master -cpuprofile="m.prof"

You can try to run it and post the profile file here.
