### ISSUE TITLE
Mount panic [ Unlock of unlocked RWMutex ]

### ISSUE THREAD

**Issue by ningfdx** [chrislusf/seaweedfs#3306]
I guess the reason in this commit, https://github.com/chrislusf/seaweedfs/commit/28add5a53451aa0be30cc03c2fda22c4056d602b

I0713 14:45:10 01636 reader_at.go:105] ReadAt [25732022272,25732153344) (stream: true) of total file size 85899345920 bytes 8192 chunk views
2022/07/13 14:45:10 rx 12228780: READ n13211127795646166699 {Fh 258 [25732153344 +131072)  L 0 RDONLY,0x8000}
I0713 14:45:10 01636 slot_pool.go:60] --> 1
fatal error: sync: Unlock of unlocked RWMutex

goroutine 210 [running]:
runtime.throw({0x23278dd?, 0xc00ce7de60?})
        /usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc001c07590 sp=0xc001c07560 pc=0x43a4b1
sync.throw({0x23278dd?, 0x3a40?})
        /usr/local/go/src/runtime/panic.go:978 +0x1e fp=0xc001c075b0 sp=0xc001c07590 pc=0x46865e
sync.(*RWMutex).Unlock(0xc0039ac780)
        /usr/local/go/src/sync/rwmutex.go:201 +0x4a fp=0xc001c075e8 sp=0xc001c075b0 pc=0x47980a
sync.(*Cond).Wait(0x2f?)
        /usr/local/go/src/sync/cond.go:55 +0x7e fp=0xc001c07620 sp=0xc001c075e8 pc=0x4763be
github.com/chrislusf/seaweedfs/weed/filer.(*SingleChunkCacher).readChunkAt(0xc0039ac780, {0xc008488000, 0x18000, 0xf?}, 0x0)
        /nfd/poyehali/seaweedfs/weed/filer/reader_cache.go:190 +0xba fp=0xc001c07688 sp=0xc001c07620 pc=0xfb377a
github.com/chrislusf/seaweedfs/weed/filer.(*ReaderCache).ReadChunkAt(0xc011ea2270, {0xc008488000, 0x18000, 0x18000}, {0xc0072f8580, 0xf}, {0x0, 0x0, 0x0}, 0x0, ...)
        /nfd/poyehali/seaweedfs/weed/filer/reader_cache.go:79 +0x2bb fp=0xc001c077e0 sp=0xc001c07688 pc=0xfb28db
github.com/chrislusf/seaweedfs/weed/filer.(*ChunkReadAt).readChunkSliceAt(0xc000f9b7c0, {0xc008488000?, 0x4e94e5?, 0x0?}, 0xc005b3ab40, {0xc000f8ccb8, 0x1669, 0x1a69}, 0xc00075a000?)
        /nfd/poyehali/seaweedfs/weed/filer/reader_at.go:173 +0xbe fp=0xc001c07880 sp=0xc001c077e0 pc=0xfb1e9e
github.com/chrislusf/seaweedfs/weed/filer.(*ChunkReadAt).doReadAt(0xc000f9b7c0, {0xc008480000, 0x20000, 0x20000}, 0x5fdbf8000)
        /nfd/poyehali/seaweedfs/weed/filer/reader_at.go:136 +0x3ca fp=0xc001c079f8 sp=0xc001c07880 pc=0xfb1aaa
github.com/chrislusf/seaweedfs/weed/filer.(*ChunkReadAt).ReadAt(0xc000f9b7c0, {0xc008480000, 0x20000, 0x20000}, 0x5fdbf8000)
        /nfd/poyehali/seaweedfs/weed/filer/reader_at.go:106 +0x285 fp=0xc001c07ae0 sp=0xc001c079f8 pc=0xfb15c5
github.com/chrislusf/seaweedfs/weed/mount.(*FileHandle).readFromChunks(0xc00fbdc000, {0xc008480000, 0x20000, 0x20000}, 0x5fdbf8000)
        /nfd/poyehali/seaweedfs/weed/mount/filehandle_read.go:77 +0x8e5 fp=0xc001c07d48 sp=0xc001c07ae0 pc=0x1c98ca5
github.com/chrislusf/seaweedfs/weed/mount.(*WFS).Read(0xc000899a20, 0xc000692900?, 0xc000692a98, {0xc008480000, 0x20000, 0x20000})
        /nfd/poyehali/seaweedfs/weed/mount/weedfs_file_read.go:54 +0x1c6 fp=0xc001c07e48 sp=0xc001c07d48 pc=0x1ca33a6
github.com/hanwen/go-fuse/v2/fuse.doRead(0xc0006dc6e0, 0xc000692900)
        /nfd/poyehali/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.1-0.20220627082937-d01fda7edf17/fuse/opcode.go:374 +0x83 fp=0xc001c07ea8 sp=0xc001c07e48 pc=0x1c77da3
github.com/hanwen/go-fuse/v2/fuse.(*Server).handleRequest(0xc0006dc6e0, 0xc000692900)
        /nfd/poyehali/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.1-0.20220627082937-d01fda7edf17/fuse/server.go:514 +0x1f3 fp=0xc001c07f50 sp=0xc001c07ea8 pc=0x1c823f3
github.com/hanwen/go-fuse/v2/fuse.(*Server).loop(0xc0006dc6e0, 0xe0?)
        /nfd/poyehali/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.1-0.20220627082937-d01fda7edf17/fuse/server.go:487 +0x108 fp=0xc001c07fc0 sp=0xc001c07f50 pc=0x1c82088
github.com/hanwen/go-fuse/v2/fuse.(*Server).readRequest.func3()
        /nfd/poyehali/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.1-0.20220627082937-d01fda7edf17/fuse/server.go:354 +0x2b fp=0xc001c07fe0 sp=0xc001c07fc0 pc=0x1c8170b
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc001c07fe8 sp=0xc001c07fe0 pc=0x46dd81
created by github.com/hanwen/go-fuse/v2/fuse.(*Server).readRequest
        /nfd/poyehali/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.1-0.20220627082937-d01fda7edf17/fuse/server.go:354 +0x52b

**Comment by chrislusf** [comment]
There are several commits related to this right after. Please use the latest version.

**Comment by ningfdx** [comment]
I'm sorry, I use the master code at commit de97ba9, this happen on that version.
I read the latest code, but seems no change about this.

I guess the reason is sync.cond should not use the sync.RWLock. I copy the standard lib test code in /usr/local/go/src/sync/cond_test.go:80, change sync.Lock to sync.RWLock,
and every time run it, you will got the error 

you can try it
https://go.dev/play/p/zFI5QJsr3gE
```
fatal error: sync: Unlock of unlocked RWMutex
fatal error: sync: unlock of unlocked mutex
```

**Comment by chrislusf** [comment]
Thanks! Added a commit. Not sure how to reproduce this. Let me know if it helps.
