### ISSUE TITLE
Can I set image height and width using the filer similar to seaweedfs's "?height=200&width=200"

### ISSUE THREAD

**Issue by CheyenneForbes** [chrislusf/seaweedfs#332]

**Comment by hxiaodon** [comment]
This feature could be added easily. 
Chris, if no other concern, I will submit a fix.

**Comment by CheyenneForbes** [comment]
that would be great, thank you....3 more concerns, is the normal seaweedfs faster or slower than the filer? whats the difference? can seaweedfs process videos as it process images (height and width)? and what are the server requirements for seaweedfs?

**Comment by chrislusf** [comment]
thanks @hxiaodon that'll be great.

The filer just pass through the request to the volume server. So no difference.

The image processing power is limited. It is not faster than other tools, i.e. imagemagick. Do not abuse it.

**Comment by CheyenneForbes** [comment]
How fast would the "?height=200&width=200" option added to the filer?

**Comment by hxiaodon** [comment]
Maybe you could have a try with some stress testing/benchmark tools(e.g apache benchmark or wrk). I tested at my local(from a web browser), no accurate consuming time, it could resize the image quickly(within one second). 
As Chris has said, no evident difference is the expected result.

**Comment by CheyenneForbes** [comment]
My mistake, that should be "How soon will the feature to set image width and height be added to SWFS filer as you can do with the master server?"

**Comment by chrislusf** [comment]
It should have been added now. Please test with the latest commit.

**Comment by chrislusf** [comment]
fixed in https://github.com/chrislusf/seaweedfs/pull/333/files the first file.

**Comment by CheyenneForbes** [comment]
Hey, thank you :) can the editor automatically convert png to jpeg before
uploading?

On Wed, Jun 29, 2016 at 12:25 PM, Chris Lu <notifications@github.com> wrote:

> Closed #332 <https://github.com/chrislusf/seaweedfs/issues/332>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/chrislusf/seaweedfs/issues/332#event-708082281>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AH3qSOYR1WtDdGnTNhkk88RlJeeubX7aks5qQqqVgaJpZM4I_1d2>
> .
>



-- 
Cheyenne Forbes
Chief Executive Officer
Avapno Omnitech
Start-Up Jamaica
32 1/2 Duke St.
Kingston, Jamaica

Email cheyenne.osanu.forbes@gmail.com
Mobile 876-881-7889

**Comment by chrislusf** [comment]
The system is meant to be generic. The image specific operations are kept at minimum. This image type conversion is unlikely going to make it.

Chris
