### ISSUE TITLE
[filer] duplicated local subscription detected

### ISSUE THREAD

**Issue by kmlebedev** [chrislusf/seaweedfs#3320]
**Describe the bug**

Persistent error background

**System Setup**
```
version 8000GB 3.15 37578929 linux amd64
```

![Screenshot 2022-07-15 at 17 53 26](https://user-images.githubusercontent.com/9497591/179227025-5a4b32c4-b83e-46fb-887a-6b2b66c0f82a.png)

**Additional context**
```
I0715 12:40:02     1 meta_aggregator.go:102] subscribing remote 10.103.39.13:9090 meta change: rpc error: code = Unknown desc = duplicated local subscription detected for client filer:10.106.97.33:9090@10.106.97.33:41542 id 650053677
I0715 12:40:01     1 meta_aggregator.go:102] subscribing remote 10.103.39.35:9090 meta change: rpc error: code = Unknown desc = duplicated local subscription detected for client filer:10.106.97.2:9090@10.106.97.2:52844 id -1217481642
```

restarting api server does not help
```
kubectl -n s3 exec -it  api-77db57df9b-5g4cn -- kill -s TERM 1
kubectl -n s3 get pods api-77db57df9b-5g4cn
NAME                        READY   STATUS             RESTARTS   AGE
api-77db57df9b-5g4cn   1/1     Running   2          24h
```

**Comment by chrislusf** [comment]
there are no metadata changes.

Trigger some metadata change, e.g., uploading/deleting/modifying a file, this error should go away.

**Comment by kmlebedev** [comment]
> there are no metadata changes.

Metadata has been objectively changed
![Screenshot 2022-07-17 at 17 55 08](https://user-images.githubusercontent.com/9497591/179399363-44cb1e25-b6a0-4ec6-a3cd-a563bb3b3517.png)
![Screenshot 2022-07-17 at 17 53 54](https://user-images.githubusercontent.com/9497591/179399367-48b2612e-dc9c-4ec3-8fdc-eaf33d6b9383.png)

More and more messages

**Comment by chrislusf** [comment]
fbd8f868a124af47d1c91b742d587c4fab6f2a32 should have fixed this.

**Comment by kmlebedev** [comment]
@chrislusf  After updating to 3.16, the problem partially returned
![Screenshot 2022-07-18 at 13 47 47](https://user-images.githubusercontent.com/9497591/179476152-c8997b8f-1f1e-40c7-a3c4-cae71c151945.png)

**Comment by kmlebedev** [comment]
@chrislusf Maybe move this error message to at least level 1 for now?

**Comment by shichanglin5** [comment]
@kmlebedev  Do you know why this log keeps appearing?

**Comment by kmlebedev** [comment]
> Do you know why this log keeps appearing?
@shichanglin5 No, I don't know this part of the code about subscriptions well.
