### ISSUE TITLE
[wdclient] adding some TTL to the "old" volume location

### ISSUE THREAD

**Issue by kmlebedev** [chrislusf/seaweedfs#3327]
> This assumes the leader and the followers hold the source of truth of volume locations.
> If the follower becomes a leader, but a volume server does not come alive, the follower may wrongly think it knows where the volume is.
> Currently the topology is already synced to the followers in wdclient, but was reset when the leader fails. We may fix this by adding some TTL to the "old" volume location.

https://github.com/chrislusf/seaweedfs/issues/3310

**Comment by kmlebedev** [comment]
@shichanglin5 Do you wants to work this issue?

**Comment by shichanglin5** [comment]
![image](https://user-images.githubusercontent.com/48707349/180375563-375a2f51-6acf-48a6-b8cf-e2abaca7f3ed.png)

I think it is easier to use linked list than ttl  @kmlebedev @chrislusf

**Comment by chrislusf** [comment]
This design is better.

**Comment by shichanglin5** [comment]
> This design is better.

In order to avoid the vidmap cache being empty due to the failure of the master reconnection immediately after the successful reconnection, I set the length of the linked list to 5 by default.

**Comment by kmlebedev** [comment]
Checking on the production cluster, changing the leader is completely painless. This is a cool feature!
