### ISSUE TITLE
Whitelist Support for Filer Service

### ISSUE THREAD

**Issue by mtolman** [chrislusf/seaweedfs#334]
Hi,

I'm interested in using the default (leveldb) Filer service, but it doesn't seem to currently support whitelisting support. Is this correct?

I went ahead and modified my local repository to add read and write whitelisting support to the Filer service and it seems to work fine. I'm happy to upload the changes I've made, but I must admit this is my first shot at coding in Go as well as contributing to a github project. Are there any contribution guidelines that I should be aware of?

Thanks,
Mike

**Comment by chrislusf** [comment]
You are very welcome to contribute. Just follow the existing code example, and basic go convention (go fmt, go vet).

Chris
