### ISSUE TITLE
两集群数据合并，能否单独调整某个volume的大小？

### ISSUE THREAD

**Issue by winwill2012** [chrislusf/seaweedfs#3347]
**Describe the bug**
计划将两个seaweedfs集群数据合并（A集群数据合并到B集群），并且需要保持A集群上原来的文件的fid不变，但合并时发现某些B集群上的fid对应的A集群的volume已达到volume大小限制（30GB），合并时就会报错：
```
{"name":"1.png","size":7940,"error":"failed to write to local disk: Volume Size 34360028888 Exeededs 34359738368","eTag":"631310bd"}
```
合并方式为调用B集群的接口
```
curl -X POST -F file=@$1 http://192.168.254.7:5083/164,03e8933b1a9f1a90
```

**System Setup**
- OS：Linux 3.10.0-1062.12.1.el7.x86_64
- weed version：version 30GB 1.88 b056707 linux amd64
- 

**Expected behavior**
希望给个建议的方案，能够将数据合并到B集群的指定的volume中，fid不变

**Comment by chrislusf** [comment]
This would not work since the file id from A may collide with the ones from B. Basically this will delete some files on B.

If you are really sure what you are doing, you may try to migrate to the large volume version. Need to re-generate all the .idx files.

**Comment by winwill2012** [comment]
We will ignore the situation than fid conflict, and i have more three questions:
1、 How to migrate volume from normal version to large version, has any reference or tutorials?
2、Dose it will damage the .dat file if  re-gerernate all the .idx files?
3、If migrate volume version failed，can i roolback to normal version gracefully?

thanks

**Comment by chrislusf** [comment]
see https://github.com/chrislusf/seaweedfs/wiki/FAQ#how-to-change-from-30gb-version-to-large-volume-8000g-version

**Comment by yourchanges** [comment]
how about the question 2 and question3?
```
2、Dose it will damage the .dat file if re-gerernate all the .idx files?
3、If migrate volume version failed，can i roolback to normal version gracefully?
```
