### ISSUE TITLE
Filer:Move files and directories url parameter support

### ISSUE THREAD

**Issue by kejun-cloud** [chrislusf/seaweedfs#3355]
When move files and directories through filer.

**example:**
http://192.168.0.21:8888/a/b-mv.jpg?mv.from=/a/b2.jpg&ttl=1d
http://192.168.0.21:8888/a/b-mv.jpg?mv.from=/a/b2.jpg&ttl=

**suggest:**
”ttl=“ parameter is invalid. can be support it ?

**Comment by chrislusf** [comment]
this is not supported since the ttl needs to be determined during the upload time.

**Comment by kejun-cloud** [comment]
How to solve the problem of ttl attribute change when copying flees ? Or how to modify the ttl attribute of the file. 
Will this be considered for a future version without this feature

**Comment by chrislusf** [comment]
Need to see how to reproduce the problem.

**Comment by kejun-cloud** [comment]
How to reset the ttl attribute when copying files? Or how to modify the ttl attribute of the file? If the current version does not have this feature, will it be added in future versions?
