### ISSUE TITLE
how would I setup SeaweedFS servers with these specs?

### ISSUE THREAD

**Issue by CheyenneForbes** [chrislusf/seaweedfs#336]
how would I setup SeaweedFS (masters and volumes) to handle storage for something as large as Vine or Instagram if I have access to "unlimited" amounts of servers with these specs:

Processor: Dual Intel Xeon E5-2650 V3 10-Core
RAM: 8-64GB DDR4 SDRAM
Primary Array (OS/Database): 4 x 250-2TBGB SSD (MLC) – Hardware RAID 10
Secondary Array (DATA): 4 x 2-12TB SATA (7,200 RPM) – Hardware RAID 10

**Comment by chrislusf** [comment]
Please read wiki https://github.com/chrislusf/seaweedfs/wiki
