### ISSUE TITLE
3.17 version is 100x slow than 3.02

### ISSUE THREAD

**Issue by julor** [chrislusf/seaweedfs#3363]
**Describe the bug**
3.17 version is 100x slow than 3.02 。the same file in 3.02 vesion can download in 2ms,but when I after changed to 3.17 version, I got 156ms,which is 100x slow。
in 3.17 verson，using command filer.copy to copy local files to weedfs ,when I change to 3.02 version ,I got "read chunk xxx:404 Not Found"

**System Setup**
- Start weed by "weed server -dir=data -volume.max=0 -s3 -s3.config=config.json".
- windows 10
- output of `SeaweedFS  8000GB 3.02 AND SeaweedFS 8000GB 3.17 `

**Expected behavior**
Nothing did， exceptchange 3.02 version to 3.17.

**Comment by chrislusf** [comment]
this is fixed in 3.18
