### ISSUE TITLE
Setup SeaweedFS with a redis cluster that requires a password

### ISSUE THREAD

**Issue by CheyenneForbes** [chrislusf/seaweedfs#337]
My Redis cluster requires a password for client libraries to connect to it, does SeaweedFS have the ability to connect to a cluster that requires a password? if not it would be great if it could. I tried this command but it fails:

`weed filer -redis.server=localhost:6379 -redis.pass='my password'`

**Comment by hxiaodon** [comment]
The option name should be "-redis.password"

**Comment by CheyenneForbes** [comment]
thank you, also it would be great if we could duplicate already uploaded files via the filer and return a new name/id

**Comment by chrislusf** [comment]
"weed filer -h" should give you all the options.

>  it would be great if we could duplicate already uploaded files via the filer and return a new name/id

Maybe elaborate a bit about your use case so that I can understand this requirement.

**Comment by CheyenneForbes** [comment]
when user1 sends an image to user2, it is uploaded using the filer (http)
and the other data(text, time, etc) are stored in a database. If user2
forwards the image to user3, instead of user2 re-uploading the image a
request is sent to the filer with the file name then it duplicates the file
and return the new filename

On Sat, Jul 2, 2016 at 10:32 PM, Chris Lu <notifications@github.com> wrote:

> "weed filer -h" should give you all the options.
>
> it would be great if we could duplicate already uploaded files via the
> filer and return a new name/id
>
> Maybe elaborate a bit about your use case so that I can understand this
> requirement.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/chrislusf/seaweedfs/issues/337#issuecomment-230133373>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AH3qSBfjv9ZXFAD4YIy5YtQGjH0IezK6ks5qRy1TgaJpZM4JDqAG>
> .
>



-- 
Cheyenne Forbes
Chief Executive Officer
Avapno Omnitech
Start-Up Jamaica
32 1/2 Duke St.
Kingston, Jamaica

Email cheyenne.osanu.forbes@gmail.com
Mobile 876-881-7889

**Comment by chrislusf** [comment]
de-duplication is interesting, but it would be out of SeaweedFS' scope.
