### ISSUE TITLE
TTL management in filer

### ISSUE THREAD

**Issue by cschiano** [chrislusf/seaweedfs#339]
Hello,

When using the ttl feature with the filer 
```
curl -F "filename=@README.md" "http://localhost:8888/README.md?ttl=1m"
```

After 1m or so, the file is correctly deleted from the volume, but it is still visible when listing files in the filer, even after 3 minutes
```
http://localhost:8888/?pretty=y
```
For your information, the filer, the master and the volume are on 3 different machines.

I think this is a bug and that file expirations should be synchronized between filer and volumes. More generally, how do you manage filer's state if files are manually deleted on the volumes?

Thank you,
Clément

**Comment by chrislusf** [comment]
There are no sync now. And the filer does not remember any ttl or deletion information. I do not know whether this feature is required.

**Comment by chrislusf** [comment]
Please reopen if still having problems.

**Comment by zcalusic** [comment]
Hello @chrislusf and thanks for this amazing software!

We have an interesting workload where files are constantly uploaded at a high rate, and all of them have a TTL attached, so it's expected that they will dissapear after some time (measured in days). We're using filer via HTTP API (leveldb database), and so far this has been working great, at least in the master/volume server department. It's very fast and efficient.

Unfortunately, we have now discovered that filer database just keeps growing, based on this ticket it seems it will grow indefinitely until it fills up the disk? From what I understand, it remembers every file that was ever uploaded and has no mechanism to clear entries pointing to files that are long gone from the volume servers?

Would you reconsider adding TTL support to filer server, too, how hard would that be? Just like the master server has it, and volume servers have it, filer is the only one that can't join the party.

This is kind of a showstopper for us, so if you have any other suggestion how to handle such workload, we'd appreciate it.

Personally, I would be very dissapointed to not give a chance to SeaweedFS, seeing how well thought and performant it is... :disappointed:
