### ISSUE TITLE
Chunking large files with Filer service

### ISSUE THREAD

**Issue by mtolman** [chrislusf/seaweedfs#342]
I've been trying to use the large file / chunking feature. Should this work with the Filer service, or is it only supported when using the direct API?

Thanks!
Mike

**Comment by chrislusf** [comment]
Currently only support the direct API.

Let me know your use case, and any suggestions on how the API should look like?

**Comment by mtolman** [comment]
Well, I like how you have set up chunking as it works in the direct API. It seems like with the Filer, the only difference is that instead of passing the Fid for each chunk, you would pass a Path (something like "myfolder/myfile.jpg"):

`
type ChunkInfo struct {
    **Path**    string `json:"fid"`
    Offset int64  `json:"offset"`
    Size   int64  `json:"size"`
}
`

By the way -- in the direct API, what should the Offset property be set to for each chunk?

Thanks,
Mike

**Comment by chrislusf** [comment]
The offset should be the number of bytes before this chunk

**Comment by chrislusf** [comment]
There is a "weed filer.copy" command added recently, which can take care of chunking. The filer itself does not do chunking for this case.

Let me know whether this helps.

**Comment by mtolman** [comment]
I guess this might work, but it isn't quite what I was looking for. I was hoping to use filer REST API to upload large file and file it with a particular name. For example, I might have a 1GB file called test.iso that I want to file as "http://10.91.100.1:8888/isos/123", or something like that. It looks like the filer.copy command takes a path and appends the filename?

**Comment by chrislusf** [comment]
I was thinking you can always rename and then copy, so I removed this feature for simplicity. It should be kind of easy to add it back.
