### ISSUE TITLE
大文件下载自动中断

### ISSUE THREAD

**Issue by bob-xu** [chrislusf/seaweedfs#343]
版本：
commit d3ae3a8e146f0340776c4383458cebdc683bef7f
Date:   Tue Jul 5 10:23:14 2016 -0700

场景：
1.上传100M左右的文件
2. curl -v -L http://192.168.1.148:8085/135,54a915fef9c617cc27 -o aa.mp4
*   Trying 192.168.1.148...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to 192.168.1.148 (192.168.1.148) port 8085 (#0)
> GET /135,54a915fef9c617cc27 HTTP/1.1
> Host: 192.168.1.148:8085
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Content-Disposition: inline; filename="小班上册第1课.mp4"
< Content-Length: 170256825
< Content-Type: video/mp4
< Etag: "588d0c3d"
< Last-Modified: Sun, 17 Jul 2016 03:34:07 GMT
< Date: Sun, 17 Jul 2016 04:25:38 GMT
< 
{ [1189 bytes data]
 36  162M   36 59.7M    0     0  5901k      0  0:00:28  0:00:10  0:00:18 5486k* transfer closed with 106556916 bytes remaining to read
* Closing connection 0
curl: (18) transfer closed with 106556916 bytes remaining to read

请大神们给点指导意见，我这准备上生产了！

**Comment by hxiaodon** [comment]
I tried reproducing this issue at my dev environment with a 160MB gzip file, both uploading and downloading(with your curl command) have no problem.
![image](https://cloud.githubusercontent.com/assets/10990210/16899762/40dd7abe-4c42-11e6-8d53-4e38f3714577.png)
To focus on the seaweedfs,
1. Please make sure your curl command testing bypass any intermediate reverse-proxy, it means 192.168.1.148 should be your volume server's ip address and there is no complex network connection topology between your curl client and volume server 
2. Please check if there is any abnormal/questionable log at your volume server

**Comment by chrislusf** [comment]
Please check "weed volume -idleTimeout" setting.

**Comment by bob-xu** [comment]
@chrislusf 太感谢了，-idleTimeout设置为0是否为无限制？

**Comment by bob-xu** [comment]
@chrislusf 经测试发现设置为0 不行，请问一下设置这个参数的意义是什么，最大值可以设置为多少？

**Comment by chrislusf** [comment]
Please use "weed volume -h" to see the help.

  -idleTimeout int
    	connection idle seconds (default 10)

This is to save cost to re-create connections. If not used for the number of seconds, the connection's resources will be released. Set it higher if your file size is big and network connections are slow.

**Comment by bob-xu** [comment]
@chrislusf 明白了，谢谢！
