### ISSUE TITLE
Filer.Copy and Weed Memory Usage

### ISSUE THREAD

**Issue by mtolman** [chrislusf/seaweedfs#348]
Hi,

I'm running some SeaweedFS tests on Windows, and I am seeing weed.exe using lots of memory when I download a large file.  In my test, I use the filer.copy command to upload a large ISO file:

> weed filer.copy -maxMB=100  d:\ISO\large.iso http://localhost:8888/isos/

The ISO file I'm testing is 4GB. The command completes successfully, and weed.exe at this point is using around 400MB of memory.

Once I click to download the file, weed.exe grows to use over 11GB of memory. This seems excessive :)

I understand SeaweedFS isn't necessarily designed to handle large files like this, but I thought the chunking approach would let you do this anyways. Does seaweed reconstruct the chunked file to make it available for download?

Thanks,
Mike

**Comment by mtolman** [comment]
By the way -- I see this same behavior on a linux box (CentOS 7).

**Comment by chrislusf** [comment]
When you say "weed.exe grows to use over 11GB of memory", you mean the weed filer instance?

**Comment by mtolman** [comment]
Sorry - I should have been more clear. I'm running the all-in-one service: 
  weed server -filer=true
So it's hard to tell where the memory is going

**Comment by chrislusf** [comment]
Current model is to read all file content into memory.

Do you want to have something like "weed filer.download", which is basically a customized client, or really have to directly download the file via URL?

**Comment by mtolman** [comment]
My current implementation uses the HTTP GET and POST APIs exposed by the Filer service. For me these seem the most simple and flexible. Is there a reason that the entire file needs to be read into memory? I've been trying to figure out how to modify the code to use a streaming approach, but I'm new to golang, so I'm struggling :)

**Comment by chrislusf** [comment]
hi, I checked the code and they are working as expected. how did you write the large file? 

Try to use these Go APIs similar to this:

https://github.com/chrislusf/seaweedfs/blob/master/weed/operation/submit.go
