### ISSUE TITLE
Add gracely restart without downtime

### ISSUE THREAD

**Issue by chrislusf** [chrislusf/seaweedfs#35]
https://github.com/facebookgo/grace

With this, the volume servers can restart without any downtime, while still can load updates.

**Comment by yourchanges** [comment]
+1

**Comment by raceli** [comment]
+1

**Comment by pyinx** [comment]
+1

**Comment by jinleileiking** [comment]
not work with supervisor

**Comment by chrislusf** [comment]
The facebook package seems not easily usable. May need a different way to achieve this, if this is still needed.
