### ISSUE TITLE
API to directly write file into weedfs from Http URL

### ISSUE THREAD

**Issue by sachinwalia2k8** [chrislusf/seaweedfs#355]
the API to write file allows uploading from local filesystem. However in case where you want to upload a large file it may be inefficient to do write twice - once in local file system and then to weedfs. Is it possible to provide an API that can directly copy file to weedfs from http/https URL with appropriate buffering? Something like below:

`curl -X POST -d "fileName=<file-name>&fileUrl=http://www.something.com/someimg.png" http://127.0.0.1:8080/3,01637037d6
`

**Comment by chrislusf** [comment]
This is more of a feature request for curl?
