### ISSUE TITLE
Question about disk size limit?

### ISSUE THREAD

**Issue by lujiango** [chrislusf/seaweedfs#359]
请教一个问题：
（1）比如我有三台VolumeServer每台机器500GB硬盘，每台VolumeServer已经有100个物理volume文件(每个Volume物理文件的上限是32GB，副本机制001)，理论上每台机器应该至少需要空间100*32GB=3200GB。假如每台机器的500GB被占满，但是每个Volume物理文件并没有达到32GB上限，如果这个时候有写请求会怎么样？如果我再增加两台各500GB硬盘的VolumeServer，写请求会自动切换到新的机器吗？磁盘已满的VolumeServer上面的物理volume会变成只读吗？

**Comment by chrislusf** [comment]
1) FAIL
2) No
3) No.

**Comment by lujiango** [comment]
可以手动设置某个volume为只读吗？如果不支持的话，可否提供实现思路呢？谢谢！

**Comment by lujiango** [comment]
现在我面临一个问题，就是我上面描述的问题，如果一个磁盘就500GB，但是已经分配了很多volume物理文件（上限32GB），500GB将会占满，后面的写请求会失败的，有好的方式处理这个问题吗？

**Comment by chrislusf** [comment]
You can "chmod *.dat 444" and then restart.
