### ISSUE TITLE
Add an undelete feature

### ISSUE THREAD

**Issue by marcoherbst** [chrislusf/seaweedfs#362]
As [Chris suggests](https://groups.google.com/forum/#!topic/seaweedfs/bX-jtPeVJP8), this could be similar to the Export feature.

**Comment by ijunaid8088** [comment]
One question on this topic..

Is the vacuum process not deleting the files but sending them to trash folder?

which eventually means the disk space isn't going to be cleaned but it will remain as full as it is?

**Comment by chrislusf** [comment]
The file will be purged on compaction.

It is not efficient to implement the undelete, since it needs a scanning of the whole volume file to find the latest copy. It's better not to include this feature.
