### ISSUE TITLE
Question about meta data size?

### ISSUE THREAD

**Issue by lujiango** [chrislusf/seaweedfs#365]
一个文件会对应产生一个needle，然后会在VolumeServer的内存中缓存查找信息，那么一个文件缓存的查询定位信息是多少字节呢？

**Comment by chrislusf** [comment]
Not sure what you are asking. This is the API to set the lookup information to the cache.

	Put(key uint64, offset uint32, size uint32) error

**Comment by lujiango** [comment]
Thank you!!
