### ISSUE TITLE
Question about memory usage?

### ISSUE THREAD

**Issue by lujiango** [chrislusf/seaweedfs#368]
I started 3 maters and 3 volumes, replica strategy 001.
memory useage:
master1:10m  volume1:26m
master2:9m    volume2:27m
master3:10m  volume3:25m

Then, use ./weed benchmark upload 60 million files, every file's size is 1KB.
I found memory useage:
volume1:671m
volume2:894m
volume3:1.1g
Actually, 671m + 894m + 1.1g = 2614.4m
But, theoretically 60000000*2*24byte= 1831.1m

Why is the difference between the actual value and the theoretical value so much?

Where is "2614.4-1831.1=783.3" gone?

Sorry,my english is not good.

**Comment by chrislusf** [comment]
This is not an in memory store. You are comparing operational memory, which relates to runtime behavior, vs files stored on disk.
