### ISSUE TITLE
Volume 5 becomes unwritable

### ISSUE THREAD

**Issue by y0ngb00n** [chrislusf/seaweedfs#370]
Hi all,

l've running the weed version 0.7 for a while. l've received the error "Volumn X becomes unwritable."

l could not find the cause of the issue. Any clue of the cause of the issue? 
Is there anyway l could do to prevent this error happen?

Cheers,

[weed.localhost.root.log.INFO.20160914-115638.22517.txt](https://github.com/chrislusf/seaweedfs/files/471735/weed.localhost.root.log.INFO.20160914-115638.22517.txt)

[vagrant@localhost tmp]$ cat weed.INFO 
Log file created at: 2016/09/14 11:56:38
Running on machine: localhost
Binary: Built with gc go1.6 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss threadid file:line] msg
I0914 11:56:38 22517 file_util.go:20] Folder /tmp/data Permission: -rwxr-xr-x
I0914 11:56:38 22517 file_util.go:20] Folder /tmp/data Permission: -rwxr-xr-x
I0914 11:56:38 22517 topology.go:86] Using default configurations.
I0914 11:56:38 22517 master_server.go:59] Volume Size Limit is 30000 MB
I0914 11:56:38 22517 server.go:205] Start Seaweed Master 0.70 at localhost:9333
I0914 11:56:38 22517 raft_server.go:90] Initializing new cluster
I0914 11:56:38 22517 master_server.go:93] [ localhost:9333 ] I am the leader!
I0914 11:56:38 22517 volume.go:110] loading index file /tmp/data/1.idx readonly false
I0914 11:56:38 22517 store.go:218] data file /tmp/data/1.dat, replicaPlacement=000 v=2 size=5692392 ttl=
I0914 11:56:38 22517 volume.go:110] loading index file /tmp/data/2.idx readonly false
I0914 11:56:38 22517 store.go:218] data file /tmp/data/2.dat, replicaPlacement=000 v=2 size=6561624 ttl=
I0914 11:56:38 22517 volume.go:110] loading index file /tmp/data/3.idx readonly false
I0914 11:56:38 22517 store.go:218] data file /tmp/data/3.dat, replicaPlacement=000 v=2 size=6518120 ttl=
I0914 11:56:38 22517 volume.go:110] loading index file /tmp/data/4.idx readonly false
I0914 11:56:38 22517 store.go:218] data file /tmp/data/4.dat, replicaPlacement=000 v=2 size=8213552 ttl=
I0914 11:56:38 22517 volume.go:110] loading index file /tmp/data/5.idx readonly false
I0914 11:56:38 22517 store.go:218] data file /tmp/data/5.dat, replicaPlacement=000 v=2 size=7587232 ttl=
I0914 11:56:38 22517 volume.go:110] loading index file /tmp/data/6.idx readonly false
I0914 11:56:38 22517 store.go:218] data file /tmp/data/6.dat, replicaPlacement=000 v=2 size=6232808 ttl=
I0914 11:56:38 22517 volume.go:110] loading index file /tmp/data/7.idx readonly false
I0914 11:56:38 22517 store.go:218] data file /tmp/data/7.dat, replicaPlacement=000 v=2 size=7565560 ttl=
I0914 11:56:38 22517 store.go:227] Store started on dir: /tmp/data with 7 volumes max 7
I0914 11:56:38 22517 server.go:259] Start Seaweed volume server 0.70 at localhost:8800
I0914 11:56:38 22517 volume_server.go:73] Volume server bootstraps with master localhost:9333
I0914 11:56:38 22517 node.go:208] topo adds child DefaultDataCenter
I0914 11:56:38 22517 node.go:208] topo:DefaultDataCenter adds child DefaultRack
I0914 11:56:38 22517 node.go:208] topo:DefaultDataCenter:DefaultRack adds child localhost:8800
I0914 19:12:27 22517 topology_event_handling.go:58] Removing Volume 5 from the dead volume server Node:topo:DefaultDataCenter:DefaultRack:localhost:8800, volumes:map[3:Id:3, Size:6518120, ReplicaPlacement:000, Collection:, Version:2, FileCount:134, DeleteCount:63, DeletedByteCount:5758741, ReadOnly:false 4:Id:4, Size:8213552, ReplicaPlacement:000, Collection:, Version:2, FileCount:153, DeleteCount:71, DeletedByteCount:7296394, ReadOnly:false 5:Id:5, Size:7587232, ReplicaPlacement:000, Collection:, Version:2, FileCount:119, DeleteCount:53, DeletedByteCount:5890148, ReadOnly:false 6:Id:6, Size:6232808, ReplicaPlacement:000, Collection:, Version:2, FileCount:113, DeleteCount:52, DeletedByteCount:5188652, ReadOnly:false 7:Id:7, Size:7565560, ReplicaPlacement:000, Collection:, Version:2, FileCount:144, DeleteCount:70, DeletedByteCount:6933063, ReadOnly:false 1:Id:1, Size:5692392, ReplicaPlacement:000, Collection:, Version:2, FileCount:114, DeleteCount:53, DeletedByteCount:4918953, ReadOnly:false 2:Id:2, Size:6561624, ReplicaPlacement:000, Collection:, Version:2, FileCount:131, DeleteCount:61, DeletedByteCount:5842917, ReadOnly:false], Ip:localhost, Port:8800, PublicUrl:localhost:8800, Dead:true

I0914 19:12:27 22517 volume_layout.go:181] Volume 5 has 0 replica, less than required 1
I0914 19:12:27 22517 volume_layout.go:157] Volume 5 becomes unwritable

**Comment by chrislusf** [comment]
Not sure. Please try to restart to see whether volume 5 can be added back.

Use the latest version from git should help.
