### ISSUE TITLE
Got an error: Failed to write to local disk when uploading a 0 byte file

### ISSUE THREAD

**Issue by wanghao1891** [chrislusf/seaweedfs#372]
I create a 0 byte file which name is a.out, `touch a.out`, then i upload it to weed:
`./weed upload -server "192.168.77.33:9333" -maxMB 16 a.jpg`
I got an error:
`[{"fileName":"a.jpg","fileUrl":"192.168.77.33:9001/2,5908d998f13b","fid":"2,5908d998f13b","error":"Failed to write to local disk"}]`

If i create a 0 file which name is a.txt, `touch a.txt`, then i upload it to weed:
`./weed upload -server "192.168.77.33:9333" -maxMB 16 a.txt`
success, and the result:
`[{"fileName":"a.txt","fileUrl":"192.168.77.33:9001/7,59097825e795","fid":"7,59097825e795","size":23}]`

I try to create other files that have different extensions, like `.jpg`, `.ext`, etc, I also get the same error.

 Please help me, thank you!

**Comment by chrislusf** [comment]
zero length file is not supported.

*.txt is automatically gzipped, so the content is actually not 0 bytes. That's why it can succeed.

**Comment by wanghao1891** [comment]
@chrislusf Can you tell me why zero lenth file is not supported?

**Comment by wanghao1891** [comment]
Ok, I will upload files without extensions to avoid this problem. Thank you!

**Comment by chrislusf** [comment]
zero length file is treated as deleted.
