### ISSUE TITLE
compacting volume with volumeDataIntegrityChecking failure

### ISSUE THREAD

**Issue by hxiaodon** [chrislusf/seaweedfs#374]
Chris,

In my dev environment, I encounter the following issue 2 times. Basically speaking, the volumeDataIntegrityChecking will be failed occasionally after compacting volume

Gabage Collection(Compacting data)
```
I0922 06:05:40 43900 volume_server_handlers_vacuum.go:16] checked compacting volume = 68 garbageThreshold = 0.3 vacuum = true
I0922 06:05:40 43900 volume_server_handlers_vacuum.go:25] compacted volume = 68 , error = <nil>
I0922 06:05:40 43900 volume_loading.go:62] open to write file d/local-bucket_68.idx
I0922 06:05:40 43900 volume_loading.go:69] volumeDataIntegrityChecking failed verifyNeedleIntegrity d/local-bucket_68.idx failed: File Entry Not Found. Needle 255448 Memory 255445
I0922 06:05:40 43900 volume_loading.go:73] loading index file d/local-bucket_68.idx **readonly true**
I0922 06:05:40 43900 needle_map_memory.go:51] max file key: 2716525
I0922 06:05:40 43900 volume_server_handlers_vacuum.go:34] commit compact volume = 68 , error = <nil>
```

The error log(Needle 255448 Memory 255445)'s meaning is: after compacting volume 68 and regenerated idx file, the last needle's size from index file is 255445 while the actual size in dat file(Needle Header field) is 255448.
And the first time I found this issue, the error log is "....Needle 13794 Memory 13795...."

Then the client side will see the following error:
```
code = 500, upload file fail, bucket = local-bucket, file = BD1473829201000000000438109-signed.pdf, errMsg = statusCode: 500 | errorMsg: {"error":"Failed to write to local disk (Volume 68 is read only)"}
```

Restart volume server, and the volumeDataIntegrityChecking succeeded again
```
I0926 14:53:17 18189 volume_loading.go:62] open to write file d/local-bucket_68.idx
I0926 14:53:17 18189 volume_loading.go:73] loading index file d/local-bucket_68.idx readonly false
I0926 14:53:17 18189 needle_map_memory.go:51] max file key: 2716525
I0926 14:53:17 18189 disk_location.go:38] data file ./d/local-bucket_68.dat, replicaPlacement=101 v=2 size=31627576 ttl=
```

I reviewed the relevant code , the corresponding logic is:

1. compact checking: if needed, jump to step 2
2. compacting: copy valid(undeleted and lastest updated files) data to tmp dat and idx file
3. commit compacting: add write lock and overwrite old dat and idx with the tmp ones, then load the overwrited volume ,release write lock

My concern is that if there is a write operation between step 2 and step 3, maybe that file **will be lost** after compacting. 
I'm not clear about the copy on write mechanism you commented~
![image](https://cloud.githubusercontent.com/assets/10990210/18827218/46fb97ba-8404-11e6-8e06-fe8da324c14a.png)
Could you help to explain?

 Until now, my above concern seems not to have anything to do with the original volumeDataIntegrityChecking failure because the commit compacting has write lock protected(idx and dat's modification is atomic operation). And after restarted volume server, volumeDataIntegrityChecking is OK(this could prove the atomicity)

Hope for your suggestion. Thanks!

**Comment by chrislusf** [comment]
I agree there is some holes in here. Between 2 and 3, we will need to lock the volume, makeup the difference, commit the compaction, and then unlock the volume.

**Comment by chrislusf** [comment]
I added a makeupDiff() function in the volume_compact.go file.

Is it possible for you to implement the details? Similar to checking the last entry. Basically find the corresponding last entry in the oldDatFile, and copy all bytes after that.

**Comment by hxiaodon** [comment]
Sure, I will do that. Does this function could solve my issue(volumeDataIntegrityChecking failed)? So far I have no idea about it~

**Comment by hxiaodon** [comment]
Latest update from my side
I think the root cause has finally been found. let's replay the compacting:

1. compact checking: if needed, jump to step 2
2. compacting: copy valid(undeleted and lastest updated files) data to tmp dat and idx file
2-3.  there is a new write operation, updated to weed's lru cache
3. commit compacting: 

- add write lock 
- overwrite old dat and idx with the tmp ones(rename)  

 - load the overwrited volume
   - volumeDataIntegrityChecking
     - dat hit cache while index read tmp index which is not the latest 
- release write lock

Anyway, makeupDiff should resolve this problem

**Comment by chrislusf** [comment]
Thanks for the fix!
