### ISSUE TITLE
large file storage

### ISSUE THREAD

**Issue by carr123** [chrislusf/seaweedfs#377]
I hava many large files to save, each of 50MB to 200MB in size.
i heard that seaweedfs cache file contents in memory for fast access, but i have limited  server RAM resource (1GB or 2GB at most), so, i'm afraid ram could be run out of.
is there any solusion ?  can those large files just be served from disk not from memory ?
thanks.

**Comment by chrislusf** [comment]
You can store files in smaller chunks. See "weed upload" and "weed download" commands.
