### ISSUE TITLE
configuration support

### ISSUE THREAD

**Issue by CheyenneForbes** [chrislusf/seaweedfs#379]
does @chrislusf  offer production configuration support for seaweedfs?

**Comment by chrislusf** [comment]
Maybe later.

**Comment by CheyenneForbes** [comment]
Could I have an email address for you? my company would like to use
seaweedfs in a full production deployment

**Comment by chrislusf** [comment]
chris.lu at gmail dot com

**Comment by CheyenneForbes** [comment]
Did you get the email?

**Comment by CheyenneForbes** [comment]
Did you get the email?
