### ISSUE TITLE
Weed constantly giving timeout error

### ISSUE THREAD

**Issue by ijunaid8088** [chrislusf/seaweedfs#381]
We are saving image to weedFS but for past few days we are getting many saving timeout error.. Could this be due to low memory? or someother reasons.. Can any has any suggestions about it?

**Comment by chrislusf** [comment]
The upload happens within your data center or across internet? Try to change the idleTimeout.

> weed volume -h
  -idleTimeout int
    	connection idle seconds (default 10)

**Comment by ijunaid8088** [comment]
hi.. just for information that our master Max and #Volumes became equal could that be an issue as well? 

Topology
Data Center	Rack	RemoteAddr	#Volumes	Max
DefaultDataCenter	DefaultRack	----:8080	674	2000
DefaultDataCenter	DefaultRack	----:8080	2270	2270

**Comment by ijunaid8088** [comment]
It's across the internet.. we are sending a HTTP request to upload the image

**Comment by ijunaid8088** [comment]
Also, we have started weeds as 

`exec {{seaweedfs_path}} -v 0 server -filer true -ip {{seaweedfs_master_ip}} -dir {{storage_dir}} -volume.max 2270 -volume.images.fix.orientation false -pulseSeconds 5 `

I didnt see any such option there but yes we have coded timeout to 5000 means 2 seconds

**Comment by chrislusf** [comment]
weed server -h

  -idleTimeout int
    	connection idle seconds (default 10)

**Comment by ijunaid8088** [comment]
Okay sir one last thing..

my current -volum.max is 2270.. 

If I will increase that max size.. 

and start weed again.. Will that harm already created volumes ? or something horrible will happen to existing images?

**Comment by chrislusf** [comment]
No. But can your disk fit that many volumes when all volumes reach the 30GB limit?

**Comment by ijunaid8088** [comment]
We have 1 master and 1 volume right now..

master showing free storage as 5.987601252352 TB (5987601252352 byte)
volume showing free storage as 4.424445792256 TB

Is that enough?

**Comment by chrislusf** [comment]
No. Each volume max size is 30GB, unless you change the limit. See "weed server -h" for help.

**Comment by ijunaid8088** [comment]
hi.. just for information that our master Max and #Volumes became equal
could that be an issue as well?

Topology
Data CenterRackRemoteAddr#VolumesMax
DefaultDataCenter DefaultRack 138.201.13.132:8080
<http://138.201.13.132:8080/ui/index.html> 674 2000
DefaultDataCenter DefaultRack 138.201.13.150:8080
<http://138.201.13.150:8080/ui/index.html> 2270 2270





Regards


*Junaid Farooq*
Software Developer, Evercam.io
+92334- <+92347-8666955>6944005 | junaid@evercam.io | Evercam
<http://evercam.io/> | Skype: darulehsan1
<https://mail.google.com/mail/u/0/#>
<http://www.facebook.com/ijunaid8088>  <http://pk.linkedin.com/in/iamjunnii>
  <http://github.com/ijunaid8088>  <http://twitter.com/ijunaid8088>
