### ISSUE TITLE
Volume server don't reconnect after disconnect

### ISSUE THREAD

**Issue by fedotxxl** [chrislusf/seaweedfs#382]
Hello. Volume server lost connection a few hours ago and don't try to reconnect to master server. Is it correct?
v0.69

**Comment by chrislusf** [comment]
Not correct. Maybe you can enable glog level 4 to see what went wrong if it happens again.
"weed -v 4 -vmodule weed_server volume ..."

**Comment by fedotxxl** [comment]
Is adding `-v 4` enough to change log level? We can try...

**Comment by chrislusf** [comment]
yes. but it could be very verbose.

**Comment by fedotxxl** [comment]
That it's not an option - we had this problem only once for few weeks... 
So in general it should try to reconnect to master server?

After volume restart it connected to master in a second...

**Comment by chrislusf** [comment]
I see. I think upgrading to the latest version would help to resolve this.

**Comment by fedotxxl** [comment]
@chrislusf can you reopen ticket? updated to 0.70 - still has this issue - volume server doesn't reconnect after connection lost.

**Comment by di3663** [comment]
The lastest version still has this issue. Volume server does not reconnect.
