### ISSUE TITLE
Can't download a *.tar.gz file which is uploaded with parameter '-maxMB'

### ISSUE THREAD

**Issue by wanghao1891** [chrislusf/seaweedfs#383]
The version of weed is 0.70

* I try to upload a `.tar.gz` file, like:

        ./bin/weed upload -server=192.168.77.33:9333 -maxMB 16 /tmp/log.tar.gz

    return:

        [{"fileName":"/tmp/wt-standard-log.tar.gz","fileUrl":"192.168.77.33:9001/3,011c0d4532c4b7","fid":"3,011c0d4532c4b7","size":84907230}]

* I download it, like this:

        ./bin/weed download --server=192.168.77.33:9333 3,011c0d4532c4b7

    got error:

        Download Error:  3,011c0d4532c4b7 Get http://192.168.77.33:9001/3,011c0d4532c4b7: EOF

* the volume server got errors:

2016/11/03 10:04:05 http: panic serving 192.168.77.7:59084: runtime error: invalid memory address or nil pointer dereference
goroutine 90 [running]:
net/http.(*conn).serve.func1(0xc820166600)
	/home/chris/apps/go/src/net/http/server.go:1389 +0xc1
panic(0xc194a0, 0xc820012070)
	/home/chris/apps/go/src/runtime/panic.go:426 +0x4e9
compress/gzip.(*Reader).Close(0x0, 0x0, 0x0)
	/home/chris/apps/go/src/compress/gzip/gunzip.go:309 +0x5f
panic(0xc194a0, 0xc820012070)
	/home/chris/apps/go/src/runtime/panic.go:426 +0x4e9
io/ioutil.readAll.func1(0xc820edb190)
	/home/chris/apps/go/src/io/ioutil/ioutil.go:30 +0x11e
panic(0xc194a0, 0xc820012070)
	/home/chris/apps/go/src/runtime/panic.go:426 +0x4e9
compress/gzip.(*Reader).Read(0x0, 0xc820f2aa00, 0x200, 0x200, 0x200, 0x0, 0x0)
	/home/chris/apps/go/src/compress/gzip/gunzip.go:262 +0x43
bytes.(*Buffer).ReadFrom(0xc820edb0e8, 0x7fe85646c8b8, 0x0, 0x0, 0x0, 0x0)
	/home/chris/apps/go/src/bytes/buffer.go:176 +0x23f
io/ioutil.readAll(0x7fe85646c8b8, 0x0, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/chris/apps/go/src/io/ioutil/ioutil.go:33 +0x156
io/ioutil.ReadAll(0x7fe85646c8b8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/chris/apps/go/src/io/ioutil/ioutil.go:42 +0x51
github.com/chrislusf/seaweedfs/go/operation.UnGzipData(0xc820f2a814, 0x1a2, 0x1dc, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/seaweedfs/go/operation/compress.go:54 +0x18e
github.com/chrislusf/seaweedfs/go/operation.LoadChunkManifest(0xc820f2a814, 0x1a2, 0x1dc, 0xc820c6d101, 0x0, 0x0, 0x0)
	/home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/seaweedfs/go/operation/chunked_file.go:56 +0x6e
github.com/chrislusf/seaweedfs/go/weed/weed_server.(*VolumeServer).tryHandleChunkedFile(0xc820082150, 0xc820f200a0, 0x0, 0x0, 0x7fe85649d4b0, 0xc820169790, 0xc820f18380, 0x0)
	/home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/seaweedfs/go/weed/weed_server/volume_server_handlers_read.go:147 +0xad
github.com/chrislusf/seaweedfs/go/weed/weed_server.(*VolumeServer).GetOrHeadHandler(0xc820082150, 0x7fe85649d4b0, 0xc820169790, 0xc820f18380)
	/home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/seaweedfs/go/weed/weed_server/volume_server_handlers_read.go:97 +0x24ac
github.com/chrislusf/seaweedfs/go/weed/weed_server.(*VolumeServer).privateStoreHandler(0xc820082150, 0x7fe85649d4b0, 0xc820169790, 0xc820f18380)
	/home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/seaweedfs/go/weed/weed_server/volume_server_handlers.go:28 +0xf6
github.com/chrislusf/seaweedfs/go/weed/weed_server.(*VolumeServer).(github.com/chrislusf/seaweedfs/go/weed/weed_server.privateStoreHandler)-fm(0x7fe85649d4b0, 0xc820169790, 0xc820f18380)
	/home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/seaweedfs/go/weed/weed_server/volume_server.go:64 +0x3e
net/http.HandlerFunc.ServeHTTP(0xc820ed49a0, 0x7fe85649d4b0, 0xc820169790, 0xc820f18380)
	/home/chris/apps/go/src/net/http/server.go:1618 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc82016f4a0, 0x7fe85649d4b0, 0xc820169790, 0xc820f18380)
	/home/chris/apps/go/src/net/http/server.go:1910 +0x17d
net/http.serverHandler.ServeHTTP(0xc820084500, 0x7fe85649d4b0, 0xc820169790, 0xc820f18380)
	/home/chris/apps/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc820166600)
	/home/chris/apps/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/home/chris/apps/go/src/net/http/server.go:2137 +0x44e

* The same file, if i remove suffix `.gz`, then i can download it successfully

* If i don't add `-maxMB`, then i can download it successfully

Please help me, thanks!

**Comment by chrislusf** [comment]
it's a valid bug but no time to get to this yet.

**Comment by sparklxb** [comment]
@chrislusf the bug described above is same as issue 413.

**Comment by chrislusf** [comment]
cool. Thanks! Resolved by https://github.com/chrislusf/seaweedfs/pull/428
