### ISSUE TITLE
Master server process terminated on daily basis

### ISSUE THREAD

**Issue by sprintcheng** [chrislusf/seaweedfs#384]
Hi,
I am using the latest version weed-fs 0.7(go_0.70_linux_amd64),  I set up one master server with two volume server at two different VMs, but I found after running 8 hours, the master server process is gone.

and during that moment, there is no network activity, the two volume process is still there

I1103 11:42:34  9884 file_util.go:20] Folder /opt/opt1/dc1node2 Permission: -rwxr-xr-x
I1103 11:42:34  9884 topology.go:86] Using default configurations.
I1103 11:42:34  9884 master_server.go:59] Volume Size Limit is 30000 MB
I1103 11:42:34  9884 master.go:69] Start Seaweed Master 0.70 at 9.181.24.221:9333
I1103 11:42:35  9884 raft_server.go:103] Old conf,log,snapshot should have been removed.
I1103 11:43:01  9884 master_server.go:89] [ 9.181.24.221:9333 ] 9.181.24.221:9333 becomes leader.
I1103 11:43:02  9884 node.go:208] topo adds child dc1
I1103 11:43:02  9884 node.go:208] topo:dc1 adds child dc1rack1
I1103 11:43:02  9884 node.go:208] topo:dc1:dc1rack1 adds child 9.181.24.223:8083
I1103 11:43:02  9884 node.go:208] topo:dc1:dc1rack1 adds child 9.181.24.221:8082

**where you can see master server started at around 11:42**

I1103 11:43:02 32364 volume_server.go:85] Volume Server Connected with master at 9.181.24.221:9333
I1103 19:30:35 32364 store.go:48] Reset master 9.181.24.221:9333 from: [9.181.24.221:9333 9.181.24.221:9333]

**Then at 19:30, I just saw reset master message, yet volume server not connect with master**.

perform ps -ef|grep weed to check weed process, only found volume process, master process is already gone

[root@hadoop2 tmp]# ps -ef |grep weed
root     11405 11370  0 22:50 pts/2    00:00:00 grep weed
root     32364     1  0 Nov01 ?        00:02:20 ./weed volume -dataCenter=dc1 -rack=dc1rack1 -ip=9.181.24.221 -ip.bind=9.181.24.221 -max=8 -dir=/opt/opt1/dc1node2 -mserver=hadoop2:9333 -port=8082

how can I fix this issue, I did some research on the internet, someone found ulimit for opened file number is not large enough, I also tune that parameter as following

[root@hadoop2 tmp]# ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 193128
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 402800
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 10240
cpu time               (seconds, -t) unlimited
max user processes              (-u) 193128
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
 
Yet still the issue persists, can anyone help me out. 

Thanks
Sprint

**Comment by chrislusf** [comment]
It seems an error from the master causing it to crash.

Better use the version from the git tip.

"Yet still the issue persists, can anyone help me out." Is it consistently reproducible?

**Comment by sprintcheng** [comment]
hi,
yes,it can be recreated on day to day basis.how can i troublesoot this issue via any trace logging.
regards

**Comment by chrislusf** [comment]
Please use the latest version from git, and maybe add glog version to 4, e.g., "weed -v=4 master". The log goes to the system temp directory.

**Comment by sprintcheng** [comment]
so,that means i need get souce code and build it into binary executable. is there any latest binary build availabe here, or i can get it from mirror site.

regards

**Comment by chrislusf** [comment]
install go, and then
  "go get github.com/chrislusf/seaweedfs/weed"

**Comment by chrislusf** [comment]
https://github.com/chrislusf/seaweedfs#installation-guide-for-users-who-are-not-familiar-with-golang

**Comment by sprintcheng** [comment]
Hi Chris,
I am still using binary weed-fs 0.7(go_0.70_linux_amd64), and add checking process script into crontab, after that the master sever process is up to running till now.  I will close the issue, and thanks for your suggestion

Thanks again
Sprint
