### ISSUE TITLE
New volume is up but port 8888 is showing nothing 

### ISSUE THREAD

**Issue by ijunaid8088** [chrislusf/seaweedfs#387]
Hi Chris.. this more like a question.. i have added a new storage server as volume server to master. And it started very well.. being shown in index page.. and also post 8080 is working.. but there is nothing on port 8888.. 

NB. The volume just have added.. and even other volume server has  remaining volumes.. will the port will be available when the other volumes will be fill completely?

**Comment by chrislusf** [comment]
port 8888 is for filer. You need to start a filer server.

**Comment by ijunaid8088** [comment]
@chrislusf how to start filer server? 

`/usr/bin/weed -v=0 volume -mserver=18.01.13.50:9333 -ip=8.9.48.9 -dir=/storage -max=2270 -images.fix.orientation=false -pulseSeconds=1`
I have started volume like this.. on local machine everything is fine. i start in the same way and i got the port 8888..

**Comment by ijunaid8088** [comment]
Our other volume server is also started the same way but the filer is working.. I can see files at `8888`

**Comment by ijunaid8088** [comment]
and master is started with 
`weed -v=0 server -filer=true -ip=18.01.13.50 -dir=/storage -volume.max=2370 -volume.images.fix.orientation=false -pulseSeconds=5`

**Comment by chrislusf** [comment]
There are no filer server on volume server.

**Comment by chrislusf** [comment]
To start filer, "weed filer ..."
