### ISSUE TITLE
How to quick change the replication 000 to 001 without data lost?

### ISSUE THREAD

**Issue by yourchanges** [chrislusf/seaweedfs#389]
I have setup a seaweedfs server with replication 000 on single server,  and now the size is up to 1TB and some important data has been saved, so I need a quick way to do a topology upgrade from 000 to 001  to improve both the read performance and data security.

Is there a possible way?

**Comment by chrislusf** [comment]
Does changing the master option to default replication to 001 work for you?

**Comment by yourchanges** [comment]
ok, I'll do a study to find the way, and share it here.

**Comment by ciscorn** [comment]
@yourchanges 
I managed to do that by changing the second byte of the *.dat file from 0 to 1.
https://gist.github.com/ciscorn/22867eb4f5af698298dd2a7331ea31c1

**Comment by yourchanges** [comment]
I have test follow steps:
1. stop all weed servers, master and volume
2. setup a new volume server on other host
3. scp all volume files from the first(orginal) volume server to the new one
4. change the master startup args with **-defaultReplication="001"** 
5. start masert server, and then start the two volume servers
6. Test
    For old saved files, to access both volume server, the file is available(even don't change the replication type in *.dat file from @ciscorn )
   For the new posted files, it works as the replication==001, the files are saved both in two volume server.

7. ENV
   seaweedfs 0.71 beta
   do not test against with filer feature

**Comment by yourchanges** [comment]
@chrislusf @ciscorn 

Can you confirm we should do the "changing the second byte of the *.dat file from 0 to 1" step?

**Comment by chrislusf** [comment]
This works fine.

There is a go script to change the TTL already. See https://github.com/chrislusf/seaweedfs/blob/master/unmaintained/change_superblock/change_superblock.go#L19
