### ISSUE TITLE
fatal error: concurrent map read and map write when migrating data to seaweedfs

### ISSUE THREAD

**Issue by hxiaodon** [chrislusf/seaweedfs#391]
Chris
This issue is not easy to reproduce without migrating data(heavy R/W loading with frequent adding new volume actions).  I have 3 weed master servers at prod environment, the master leader crash after running for sometime(maybe 2 hours ,or maybe 2 days)  

At the initial time, I thought that the RWLock should be the key problem. After digging into it,  I did not find any bug at application code.

The data_node.go file does not export any pub API which could  directly R/W struct DataNode's  volumes field. And when analyzing the backtrace file, there are about 3-4 goroutines R/W  volumes field with APIs at data_node.go, one in line 85(inside the RWLock.RLock() scope, in running status ) ,others are in semacquire status. What I'm confused for the goroutines in semacquire status is that one goroutine is in RWLock.Lock() while another is in RWLock.RLock(), RLock() and semacquire status means there is being an writing operation when the crash happen, but I could not find it.

Could you give some suggestions? Thanks!

[weed-master-err.zip](https://github.com/chrislusf/seaweedfs/files/573688/weed-master-err.zip)

**Comment by chrislusf** [comment]
I suspect your code is not in sync with the repo. data_node.go:56 is a Lock(), not RLock()

goroutine 14343569 [semacquire]:
sync.runtime_Semacquire(0xc820444104)
	/usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*RWMutex).RLock(0xc8204440f8)
	/usr/local/go/src/sync/rwmutex.go:37 +0x58
github.com/chrislusf/seaweedfs/weed/topology.(*DataNode).UpdateVolumes(0xc8204440c0, 0xc8214b2000, 0x209, 0x22e, 0x0, 0x0, 0x0)
	/data/go-project/objectStore/src/github.com/chrislusf/seaweedfs/weed/topology/data_node.go:56 +0x20e

**Comment by hxiaodon** [comment]
Sharp analysis!!
I was reviewing the latest code while the online service is build by old version. Thanks!
