### ISSUE TITLE
weed volume out of memory!

### ISSUE THREAD

**Issue by bob-xu** [chrislusf/seaweedfs#397]
系统中存储的单个文件大概在100M左右，大约有1w个文件，在运行中会经常出现out of memory 崩溃掉，请问有没有什么解决方案？
或可不可以weed volume 提供一个参数来设置缓存的大小或数量？

**Comment by chrislusf** [comment]
Can you test this? Change this line:

https://github.com/chrislusf/seaweedfs/blob/master/weed/storage/needle_byte_cache.go#L27

change 512 to 1, to see whether this helps with the memory issue.

**Comment by bob-xu** [comment]
@chrislusf 好的，我测试一下，谢谢！

**Comment by bob-xu** [comment]
@chrislusf 经测试可以有效减少内存问题，希望可以添加一个参数，另外是否可以有一个参数设置缓存大小的，例如--cachesize=100M

**Comment by chrislusf** [comment]
I added an option to enable caching. In most cases, we can just rely on OS buffer cache.

https://github.com/chrislusf/seaweedfs/commit/dcaf1796fe0e41e39ac5c9602cb190cf150e7849
