### ISSUE TITLE
Is there a way to secure access to seaweedfs?

### ISSUE THREAD

**Issue by simonbruneaud** [chrislusf/seaweedfs#398]
Is there a way to secure access to seaweedfs?
password, token, whatever?

**Comment by chrislusf** [comment]
There are plans to use 2-way ssl, and also Json Web Token. It seems there are not enough interest yet.

**Comment by light2cloud** [comment]
hi 你好，我想问一下现在seaweed fs有啥对公网安全的配置吗?

**Comment by ijunaid8989** [comment]
Hello, I would like to ask if seaweed fs is now configured for public network security?
