### ISSUE TITLE
weed backup tool would miss syncing the updated fids

### ISSUE THREAD

**Issue by hxiaodon** [chrislusf/seaweedfs#399]
Chris:
The weed backup tool now only remove the fids which the src do not have but dest have, and add  the ones which src have but desc does not have at the backup place.
For those files which are updated many times, I think that the backup tool will do nothing for them.

If this is a bug, do you have any good suggestion to fix it? e.g . Add the file crc32 checksum value in fetchVolumeFileEntries() function(This need to scan the whole volume and get it from each needle),and for the fid keys in both src and dest index,  if the corresponding file size and checksum value are both same, ignore syncing.

Hope for your suggestions.Thanks!

**Comment by chrislusf** [comment]
Could you help me to think of a case where current backup strategy would fail? If it does happen, we should switch to more strict way to backup.

**Comment by hxiaodon** [comment]
OK!
Suppose we have an online empty volume file(the max volume number for the volume service is 1), at the first time, the weed back tool running will sync nothing.

Then the weed client add file A,B,C into above volume. and at this time, the weed back tool running will sync A,B and C to the backup place correctly

Then the weed client add file D, delete file A ,and update file B, after this, the weed backup tool running will add file D, delete file A but do nothing for the updated  file B 

Does above case make sense?

**Comment by chrislusf** [comment]
Yes. We will need a new simpler algorithm.

**Comment by hxiaodon** [comment]
A simpler algorithm? What's you plan? 
I could not think of a way to make the backup more simpler.
My draft idea has something to do with the remote compact version, if the backup side find that the remote volume's compact version is changed compared with the last one written in a local tag file after being successfully backed up, then scanning the whole volume to get checksum is necessary. Or we could just depend on the offset and size for those fids existed in local and remote, offset change means the file is updated

**Comment by chrislusf** [comment]
Can you write out your algorithm in psuedo code?

**Comment by hxiaodon** [comment]
Sure, I will provide the psuedo code(later this week), and please help to review～

**Comment by hxiaodon** [comment]
fetchVolumeFileCRCChecksums function will get a map typed data with needle id as key and needle crc checksum as value. To reduce the network transferring cost, we could use protobuf's map feature and wrap this map and the compactVersion field into a struct which will be marshal into the http response body.

**Comment by chrislusf** [comment]
I think this crcMap would work mostly, but not sure whether it is water tight in edge cases.

I was thinking just treating the remote .dat file as a change log and just copy every bits of it.
