### ISSUE TITLE
fatal error: concurrent map read and map write - StartRefreshWritableVolumes

### ISSUE THREAD

**Issue by chris-19871987** [chrislusf/seaweedfs#400]
Hello,

We are experiencing random crashes of weed master, sample stderr log: 
[weed-master-stderr.zip](https://github.com/chrislusf/seaweedfs/files/597153/weed-master-stderr.zip)

Problem occurs mostly during heavy usage of seaweedfs volumes (random reads + adding new files).

Regards,
Chris

**Comment by chrislusf** [comment]
Pretty sure you are hitting a problem that are recently fixed.

https://github.com/chrislusf/seaweedfs/issues/392

**Comment by chrislusf** [comment]
Please re-open if upgrading did not help.
