### ISSUE TITLE
Master Failover won't work

### ISSUE THREAD

**Issue by zehweh** [chrislusf/seaweedfs#403]
I'm having trouble with master failover with this setup:

server1: weed master server, weed volume server
server2: weed master server, weed volume server
server3: weed volume server

```
curl "http://server1:9333/cluster/status?pretty=y"
{
  "IsLeader": true,
  "Leader": "server1:9333",
  "Peers": [
    "server2:9333"
  ]
```

```
curl "http://server2:9333/cluster/status?pretty=y"
{
  "Leader": "server1:9333",
  "Peers": [
    "server1:9333"
  ]
}
```

Now, when I stop the weed master process on the current leader (aka server1), this happens:

volume servers:
I1122 10:06:13  2162 store.go:327] Failed to join http://server2:9333/dir/join with response:
I1122 10:06:13  2162 store.go:48] Reset master server2:9333 from: [server1:9333 server2:9333]
I1122 10:06:14  2162 store.go:327] Failed to join http://server2:9333/dir/join with response:
I1122 10:06:14  2162 store.go:48] Reset master server2:9333 from: [server1:9333 server2:9333]
I1122 10:06:15  2162 store.go:327] Failed to join http://server2:9333/dir/join with response:
I1122 10:06:15  2162 store.go:48] Reset master server2:9333 from: [server1:9333 server2:9333]
I1122 10:06:17  2162 store.go:327] Failed to join http://server2:9333/dir/join with response:
I1122 10:06:17  2162 store.go:48] Reset master server2:9333 from: [server1:9333 server2:9333]
I1122 10:06:18  2162 store.go:48] Reset master server1:9333 from: [server1:9333 server2:9333]

master server on server2:
2016/11/22 10:06:25 http: proxy error: dial tcp server1:9333: getsockopt: connection refused
2016/11/22 10:06:25 http: proxy error: dial tcp server1:9333: getsockopt: connection refused
2016/11/22 10:06:27 http: proxy error: dial tcp server1:9333: getsockopt: connection refused

```
curl "http://server2:9333/cluster/status?pretty=y"
{
  "Peers": [
    "server1:9333"
  ]
}
```

It seems that server2 doesn't want to be leader. Any ideas?

I'm using version 0.7 with the following command line options:

`/usr/bin/weed master -defaultReplication=002 -ip=server1 -peers=server1:9333,server2:9333
`

If you need any further information, please let me know.

Thanks for the great work!

**Comment by chrislusf** [comment]
Need odd number of master servers.
