### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by ijunaid8088** [chrislusf/seaweedfs#405]
We have 1 master volume and 2 volume servers..

Do we have such parameters that so that we can keep a volume just for read operations and dont write anything on it anymore? 

One more thing. we had a volume server of 70 TB. We first started it with max 2000 volumes and it had been created 763 and we needed to stop it to create more so we stopped it to 765 max. But it is consuming the total 70 TB. why is it so?

other hand we have 2370 max volumes in the same 74TB. why 765 taking all the available space?

**Comment by chrislusf** [comment]
1. chmod 644 for the volume dat files. Probably a restart is needed.
2. I do not know without any details.

**Comment by ijunaid8088** [comment]
Sorry to ask but what kind of details you need. I can give you anything what you want But am unaware that what you want from me to see what is the issue!

**Comment by ijunaid8088** [comment]
after chmod 664 will they get vacuumed as well or not?

**Comment by ijunaid8088** [comment]
I did chmod as `find /images/. -name "*.dat" | xargs chmod 644` restarted it. But its still writing to the same volumes.

**Comment by ijunaid8088** [comment]
I tried chmod 444 and it made them readonly.. But am still not sure that vacuum is happening or not.

**Comment by chrislusf** [comment]
I checked the code. It still vacuums even it is readonly. I think we should not vacuum if it is readonly.

**Comment by ijunaid8088** [comment]
Okay thanks for the feedback.
1: What are you preferring now? chmod 444 or 644? 
2: I have tried to do something that I chmod 444 a volume. and then I deleted a file on it. it returned `{"error":""}`, the port `8888` stopped showing this file BUT on `localhost:8080`, I could still see that the file is present in volume files NOT in trash column. What this could be?
3: Our system is sending constant requests for deleting whole directories in recursive way, What will be the effect of this? (doing readOnly) 

I cannot see this on `http://localhost:8888/javascript/` but its not on trash as well.
![image](https://cloud.githubusercontent.com/assets/13561999/20645113/8244d430-b474-11e6-8976-0fcaedebeffe.png)

thanks in advance!

**Comment by chrislusf** [comment]
It should be 444. My mistake.

The deletion would not work if the volume server restarts.

Chris

**Comment by ijunaid8088** [comment]
Hi Chris, After a restart how long it could take that volume server came up again? we have a 70TB, V server I restarted it, its been 5 hours its not up yet.

**Comment by chrislusf** [comment]
It should not be this long.

Chris

**Comment by ijunaid8088** [comment]
In logs. Its loading volume files.




Regards


*Junaid Farooq*
Software Developer, Evercam.io
+92334- <+92347-8666955>6944005 | junaid@evercam.io | Evercam
<http://evercam.io/> | Skype: darulehsan1
<https://mail.google.com/mail/u/0/#>
<http://www.facebook.com/ijunaid8088>  <http://pk.linkedin.com/in/iamjunnii>
  <http://github.com/ijunaid8088>  <http://twitter.com/ijunaid8088>

**Comment by ijunaid8088** [comment]
Is there any way to vacuum a specific volume with volume id? as if volume is 2567, is there any way to vacuum it?

**Comment by chrislusf** [comment]
You can trigger the vaccum this way by sending http requests to volume
server:

see
https://github.com/chrislusf/seaweedfs/blob/9ba52db5858c480cb8cf4125b0d698f188f22ba8/weed/topology/topology_vacuum.go#L134

and

https://github.com/chrislusf/seaweedfs/blob/9ba52db5858c480cb8cf4125b0d698f188f22ba8/weed/topology/topology_vacuum.go#L150

**Comment by ingardm** [comment]
@ijunaid8989 After https://github.com/chrislusf/seaweedfs/commit/9ba52db5858c480cb8cf4125b0d698f188f22ba8 do you still see vacuuming of older volumes? We're only seeing vacuuming of the newest volumes and we've not set readonly on any volumes. It seems the code above excludes older full volumes no matter how many deleted files/bytes they have.

**Comment by ijunaid8989** [comment]
@ingardm Actually we are not on that latest version we are just using the old version 0.70Beta. So I am not sure what is the case, But at that time Chris added the functionality for not to vacuum read only volumes.
