### ISSUE TITLE
weed-volume losses connection weed-master

### ISSUE THREAD

**Issue by fedotxxl** [chrislusf/seaweedfs#408]
Hello. We already had this problem. You've got `pulseSeconds`, `idleTimeout` options on master / volume. They have help description but it's still not clear what are they for and how to configure them. 

Can you explain:
1. What's the difference between pulseSeconds / idleTimeout
2. Why do I need to configure them on master / volume? Which value is used?
3. How to increase timeout to decrease probability of loosing connection between volume and master?

**Comment by chrislusf** [comment]
1. on volume server, pulseSeconds is the interval to send heartbeats to master. idleTimeout is for network connections to read/write clients.
2. on master, pulseSeconds needs the value to determine whether the volume server is alive if it passed some limit, e.g. 5 times of the pulseSeconds.
3. Increase pulseSeconds on master server, and decrease the pulseSeconds on volume server.
