### ISSUE TITLE
current version 0.71 is Beta version, how to download stable version?

### ISSUE THREAD

**Issue by tonyhu** [chrislusf/seaweedfs#410]
down load binary seaweed from https://bintray.com/chrislusf/seaweedfs/seaweedfs,
it's beta version,how to download stable?

**Comment by chrislusf** [comment]
not built. Please just build directly.

**Comment by tonyhu** [comment]
i have dowload the latest sourcecode, then build, the  "weed version" command output is "version 0.71 beta linux amd64"
