### ISSUE TITLE
Assign file id, response ,public url and url,what's the difference

### ISSUE THREAD

**Issue by tonyhu** [chrislusf/seaweedfs#412]
The assign file id api ,return json output like {"fid":"3,0c0d9a36a1","url":"127.0.0.1:8081","publicUrl":"127.0.0.1:8081","count":1}

and upload file return json output like:
{"fileName":"hello.txt","fileUrl":"127.0.0.1:8081/2,0df4be02f5","fid":"2,0df4be02f5","size":36}

i want to know ,what's the difference? why we need two url?

**Comment by chrislusf** [comment]
One is for internal usage. The other is for external usage. Public URL is not used by the system to access the volume server.
