### ISSUE TITLE
upload big .gz file more than maxMB, wget the fileurl failed!!! 

### ISSUE THREAD

**Issue by tonyhu** [chrislusf/seaweedfs#413]
Hi chris, i just do some test,if i upload big .gz file more than maxMB, upload is success, but i can't download, if i upload not .gz file, it can be work.

 
step 1: upload file more than maxMB
weed upload -maxMB=7 -master=localhost:9333 go_0.70_linux_amd64.tar.gz 
(go_0.70_linux_amd64.tar.gz size is 8MB)

json response:
[{"fileName":"go_0.70_linux_amd64.tar.gz","fileUrl":"127.0.0.1:8081/2,39701f556f","fid":"2,39701f556f","size":8362775}]

step 2: wget  file
wget  127.0.0.1:8081/2,39701f556f 

but ,the response always

Connecting to 127.0.0.1:8081... connected.
HTTP request sent, awaiting response... No data received.
Retrying.

i will put seaweedFS in product environment, so i am doing some test, wish get your resp,
thanks

**Comment by chrislusf** [comment]
works for me.

**Comment by tonyhu** [comment]
"works for me“, then you close ? you are so interesting, if you don't have time to maintenance this project, you can declare, don't be so  irresponsible

**Comment by ijunaid8088** [comment]
@tonyhu which weed version are you using?

**Comment by chrislusf** [comment]
@tonyhu I do have other things to work on. This is a spare time project. Thanks. If you have problem, please update to the latest version. At least my version which is the latest works for me.

**Comment by tonyhu** [comment]
@ijunaid8088 my  version is : version 0.71 beta linux amd64

**Comment by ijunaid8088** [comment]
@tonyhu First:

what are the results if you set this as url in browser `127.0.0.1:8081/2,39701f556f` ?

2nd try to use `weed upload -maxMB=7 -server=localhost:9333 go_0.70_linux_amd64.tar.gz`

Not `master` .. and then show me what happened?

**Comment by chrislusf** [comment]
I think this could be related to the special handing for .tar.gz file.

**Comment by tonyhu** [comment]
@ijunaid8088 if run : weed upload -maxMB=7 -server=localhost:9333 go_0.70_linux_amd64.tar.gz
the console output: flag provided but not defined: -server，

![capture](https://cloud.githubusercontent.com/assets/3353127/21123515/2acdba08-c114-11e6-9706-8227cc3cc0b1.PNG)

 i run it in ubuntu 14.04 .

**Comment by ijunaid8088** [comment]
@tonyhu https://github.com/chrislusf/seaweedfs/pull/428 Problem to your solution has arrived :)

**Comment by tonyhu** [comment]
thks everyone !
