### ISSUE TITLE
No fid? Post file to Filer server but just return {"name":"001.jpg","size":1605633}?

### ISSUE THREAD

**Issue by wangfeiping** [chrislusf/seaweedfs#415]
I don't know why?
How to fix it?

I deployed the go_0.70_linux_amd64.tar.gz on centos 6.6.
Thanks!

**Comment by wangfeiping** [comment]
I deployed the go_0.70_linux_amd64.tar.gz

**Comment by chrislusf** [comment]
filer's purpose is to hide the details of file ids. why you need the file ids?

**Comment by wangfeiping** [comment]
@chrislusf
I deployed seaweedfs as a base service(but not open service), but I can't decide how other developers use.
Most of them were asked to provide this functionality

I read the wiki https://github.com/chrislusf/seaweedfs/wiki/API
Filer server
POST/PUT/Get files

# Basic Usage:
> curl -F file=@report.js "http://localhost:8888/javascript/"
{"name":"report.js","size":866,"fid":"7,0254f1f3fd","url":"******

but I just get 
{"name":"report.js","size":866}

I try to implement it by myself. and I first try to register a file on filer: 
curl --data "path=/test/echo.png&fildId=2,4496641af592" http://localhost:8888/admin/register

but it just return 
{"error":"request Content-Type isn't multipart/form-data"}

**Comment by chrislusf** [comment]
My memory is wrong. The fid should already be there. Maybe you are using an older version?

**Comment by wangfeiping** [comment]
@chrislusf 
Thank you!
I used go_0.70_linux_amd64.tar.gz on centos 6.6.
Do I need to build the lastest master?

**Comment by wangfeiping** [comment]
@chrislusf 
I download the go_0.70_linux_amd64.tar.gz pack and deployed it again, but still can't get fid.
I try to find wiki about how to build seaweedfs, but doesn't find anything.
Could you tell me where to download a right pack for this?

**Comment by chrislusf** [comment]
"go get ..." directly.

**Comment by wangfeiping** [comment]
@chrislusf 
Thanks.
I get some problem because of great firewall, but I think I found a solution.
