### ISSUE TITLE
Master split brain

### ISSUE THREAD

**Issue by brstgt** [chrislusf/seaweedfs#418]
Referring from https://groups.google.com/forum/#!topic/seaweedfs/v-i5VtlTf_U

We use 3 masters to provide master-failover. Currently we plan to switch back to a single master with VRRP on two machines for failover. The reason it occured two times in 1 week that we had a split brain situation where 1 master did not “find” the other masters. This resulted in 1 volume servers attached to master 1 and 3 volume servers on master 2. This has the following effects:
When doing round-robin among masters, mostly ⅓ of all request will fail
Both masters start to create new volume which can overlap. In our case we had one volume id with different collections and different replications created. When masters and volumes are reconciled again, this leads to write and or read fails in best case and to unpredictable inconsistencies in the worst case.
Generated file ids can overlap which will produce inconsistencies on reconciliation

No matter why this happened - it happened. So I / we have to deal with it.

Proposal:
In a multi-master environment, each master should have an ID and or know the total amount of masters. So each master can create globally unique volume + file ids.

Example:
Master 1 creates 1, 4, 7
Master 2 creates 2, 5, 8
Master 3 creates 3, 6, 9

We used this behavior for many many years and billions of records for sequence generation. MySQL can be configured like that to create auto-increments.

**Comment by chrislusf** [comment]
This proposal is a nice suggestion and very feasible.

**Comment by brstgt** [comment]
Please also consider my last comment in https://groups.google.com/forum/#!topic/seaweedfs/v-i5VtlTf_U:

For fast master switching / vol-id creation:
It would be best to not use an increment for volume ids. Instead UUIDs or just a unique but maybe not so long number could be used.
I could imagine of something like unix timestamp + per node modulo increment with max value encoded in 0-9,a-z for shorter URLs.

A simple increment is always exposed to race conditions and race conditions are always bad.
An offset increment per node (1, 4, 7 + 2, 5, 8 + 3, 6, 9, ...) works until the number of masters changes or the initial value is lost. This either also requires a hard state or introduces a race condition again. Not the same but similar to 1.
A predictable and unique offset helps to reduce risks if soft state is lost. Current timestamp is always larger than the last vol created. To allow creation of multiple volumes per timestamp (depending on timestamp resulution) you can add an increment value (like in 2.). So different masters can create volumes at the same time without ever reusing an existing vol id or to have a race condition if 2 split brain masters create a volume at the same time(stamp).
I don't know if it is completely backwards compatible as this changes the vol id from int to string. On the other side, a fileId is also always a string and normally stored as a single reference to a file.

What do you think?

**Comment by brstgt** [comment]
Have you made any progress or plans on this?
FYI: We currently do not use multimaster due to the bad experience we had. At the moment we have a master process on 2 servers and use VRRP to switch between them. It's not perfect but better than the situation before where some vol server connected to master A and some to master B.

I don't know if 0.74 improved this situation. Maybe drop a note if this is the case.

**Comment by chrislusf** [comment]
Not yet.

**Comment by brstgt** [comment]
Do you have any objections to change the vol id in the URL to a string?
I was thinking a lot about this issue and came to the conclusion that in the end it will be much easier to not use increments for vol-ids.
According to murphys law, things break if they can and unfortunately they can.
There is not the only problem of a master split brain situation but also a race condition if not all volumes are present on startup - which is not so unlikely to happen as large vol servers may take minutes to boot.
So why not use a collision free id?
This would require at least 64bit for a reasonable safety. A base64 (or better a radix-64) encoding could help to keep the id shorter. See examples here: http://www.shortguid.com/#/guid/uid-64. Also same encoding as for FIDs would be ok.

My proposal for vol-id generation:
- timestamp since either unix epoch or implementation timestamp (creates smaller offsets) either seconds or milliseconds
- master host id (configured or hash from IP), maybe 12-16bits
- counter to allow multiple vols per time unit, maybe 8-16bits depending on ms or s

I know this would require some work to refactor volume ids from uint32 to string or uint64 but IMHO at the end it is worth it.

Btw.: Same applies to FIDs. Maybe the generator can be exactly the same or assigns more bits to a counter. Probably there are many more FIDs than VIDs in the same period but need to be only unique to a VID

If you agree, I would offer help on refactoring.

**Comment by bugs181** [comment]
I'm very ignorant when it comes to storage mechanisms. I've been keeping my eye on SeaweedFS for a while becomes it solves some of my unique problems. That said, I know next to nothing about the mechanism this project uses. I have yet to do research on the matter but in the last comment you mention using a string for FIDs. I'm curious if a file-hash would be suitable in this case - as then we also get automatic de-duplication if handled correctly.

**Comment by chrislusf** [comment]
@bugs181 It's not memory efficient to use a big hash value as a key.

**Comment by chrislusf** [comment]
this commit should have fixed the split-brain issue. https://github.com/chrislusf/seaweedfs/commit/03f50180f3f6bfca5ae61fab0fa1c3b1db939e05
