### ISSUE TITLE
Volume repair and eventual consistency

### ISSUE THREAD

**Issue by brstgt** [chrislusf/seaweedfs#419]
Referring from https://groups.google.com/forum/#!topic/seaweedfs/v-i5VtlTf_U

Seaweed does not guarantee consistency when a node is down. This applies to deletes ALL the time and puts in the period between a node goes down and the master recognizes that and marks the volumes as unwriteable. Or: If the replication of a file fails for some other reason. The server returns a 500 then but it does not assert consistency, so the uploaded file exists on the coordinator volume but not on one or more failed replicas.

For this situation a repair process is required. I have built one with external tools, which somehow works but it could be much more efficient and secure when done in SW.

There are several ways to guarantee eventual consistency. If we take a look at Cassandra, this can be achieved by hinted handoffs and or a repair process.
As a first step, a repair would probably be easier to implement. As far as I can see you also write deletes to index file as a kind of tombstone what also make it possible to repair deletes.

Rough repair process (with incremental repair):
set repair_time = now()
read last_repair_time
foreach volume:
list volume index of all replicas where 
timestamp < repair_time (avoids race conditions)
timestamp >= last_repair_time
build diff based on timestamp + crc
stream files and deletions with original timestamp + remaining ttl
set last_repair_time on volume

To improve performance on incremental repairs and maybe to maintain backwards compatibility (if necessary) you could create a separate index file (like a commit log) for repairs which can be truncated to timestamp > repair_time after each repair.
To make compaction safe, there should be either a grace period for tombstones or the compaction should should only throw away tombstones after they have been repaired (tombstone_timestamp < last_repair_time). So it can be guaranteed, there are no stale deletes around.
Unfortunately I cannot build an external repair tool with the tools SW provides currently as I have no access to tombstones with “weed export”.

**Comment by chrislusf** [comment]
This is possible but too complicated to implement. 

With the heartbeat changes from periodic http to streaming gRPC call, the lost volume will be detected much faster.

The recommended way is to fail fast and let the master try to allocate a new set of volumes.

**Comment by eleaner** [comment]
@brstgt
did you ever manage to fulfill this requirement?
