### ISSUE TITLE
Question about weed backup!

### ISSUE THREAD

**Issue by lujiango** [chrislusf/seaweedfs#421]
环境：搭建集群，副本001。
操作：使用weed backup备份数据。
现象：备份的文件，有些collection的文件大小与原始的两个互为副本文件大小都不一致，有什么特殊的处理导致他们大小不一致，数据是否有丢失的问题。

**Comment by ijunaid8088** [comment]
Environment: build a cluster, a copy of 001.
Action: Use weed backup to back up your data.
Phenomenon: the backup file, some of the collection file size and the original two copies of each other are not the same file size, what special treatment led to their size inconsistencies, whether the data is missing.

**Comment by chrislusf** [comment]
There are some problem with "weed backup". Please just setup "rsync" instead for now.

**Comment by luzianscherrer** [comment]
What's the current status here? Should we use "weed backup" or should we use an "rsync" solution? What would the latter be exactly?

**Comment by chrislusf** [comment]
Rsync

**Comment by yourchanges** [comment]
we can not fix the "weed backup"? 
There are lots of volume files which size is mostly more than 20GB, if use rsync, all those files will be send again and again.

**Comment by chrislusf** [comment]
Please help.

**Comment by chrislusf** [comment]
https://github.com/chrislusf/seaweedfs/issues/399  "weed backup" is fixed in https://github.com/chrislusf/seaweedfs/pull/902
