### ISSUE TITLE
Filer and chunk manifests

### ISSUE THREAD

**Issue by CheyenneForbes** [chrislusf/seaweedfs#422]
How would I upload a chunk manifest (and/or chucks) to a "directory" as I would just upload a small file with "localhost:port/images.name.jpg"?

**Comment by chrislusf** [comment]
Could you please explain more about the use case? I do not feel we have this feature at all.

**Comment by CheyenneForbes** [comment]
**to upload a small jpeg file:**
post file "http://localhost:8888/path/to/sources/new_name"

**to read a small jpeg file:**
request file from "http://localhost:8888/path/to/sources/new_name"

### What I'm asking if is possible for chucks
is there anyway to request a file that was uploaded as chunks (with "application/octet-stream" and a chunk meta data file) from the Filer as I would request a file uploaded with file type "image/jpeg" using "http://localhost:8888/path/to/sources/new_name"

**Comment by mtolman** [comment]
I added chunking to the Filer a while back and it is working well for me. To use it, you need to set this option: "-filer.maxMB=10", or whatever size chunk you want to use. When you set this option, there is no need to upload a chunk manifest to the filer. Just upload the file normally

**Comment by chrislusf** [comment]
Which part is not working? Large and small files are the same. The chunking is automatically done.

**Comment by CheyenneForbes** [comment]
- when I am using the Filer to upload a large file all I need to do is POST the file to the Filer and the Filer will split the file into chunks and create the ChunkManifest itself?

- if I POST chunks of a file to "localhost:8888/folder/same_file_name" (using the Filer) will each POST rewrite what was saved as "localhost:8888/folder/same_file_name" or just the new chunk to it?

- are collections on volume servers "the same" as folders? "localhost:8888/folder/file"

- if I am not using the Filer, what should be "sent" to a collection? the chunks or the chunk manifest?

**Comment by mtolman** [comment]
I'll take a stab at answering your questions--

>when I am using the Filer to upload a large file all I need to do is POST the file to the Filer and the Filer will split the file into chunks and create the ChunkManifest itself?

yes, as long as you set the filer.maxMB setting

>if I POST chunks of a file to "localhost:8888/folder/same_file_name" (using the Filer) will each POST rewrite what was saved as "localhost:8888/folder/same_file_name" or just the new chunk to it?

I believe it will overwrite

>are collections on volume servers "the same" as folders? "localhost:8888/folder/file"

I may be wrong, but I don't think collections on volume servers are related at all to how they are filed with Filer

>if I am not using the Filer, what should be "sent" to a collection? the chunks or the chunk manifest?

If you aren't using Filer, I'm not sure what you mean by "collection"

**Comment by CheyenneForbes** [comment]
how can I prevent it from overwriting? I want to send chunks from my application to seeweedFS while being able to access the file from the filer

what are collections? whats the purpose and what is it similar to in a normal file system

**Comment by chrislusf** [comment]
@CheyenneForbes can you write to a different file instead? Show your use case would be helpful.

**Comment by CheyenneForbes** [comment]
I want to record from my webcam and CCTV cam to seaweedfs, my encoder
outputs mp4 via PUT/POST as a HTTP client

Regards,

Cheyenne Forbes

Chief Executive Officer
Avapno Omnitech Limited

Chief Operating Officer
Avapno Solutions, Co.

Chairman
Avapno Assets, LLC

Bethel Town P.O
Westmoreland
Jamaica

Email: cheyenne.osanu.forbes@gmail.com
Mobile: 876-881-7889
Landline: 876-957-1821
skype: cheyenne.forbes1

**Comment by chrislusf** [comment]
It seems you just need to upload to a folder, with a different name for each hour, for example.

**Comment by CheyenneForbes** [comment]
is there any other way to do it? if i go with that way I would have to rewrite the encoder and computer vision algorithms... these are the way I thought of doing it: 


1. upload the chunks as they leave the encoder to volume servers then add the info to the ChunkManifest then upload it

**questions:**

- should all the chunks of the same ChunkManifest be on the same "volume server"/"volume"?
- what are collections? what are they similar to on a normal file system?

2. POST/PUT the data from the encoder to the filer (recording to url )

**question:**

1. where are Filer (distrbuted) instances located? master or volume servers?

**Comment by chrislusf** [comment]
> upload the chunks as they leave the encoder to volume servers then add the info to the ChunkManifest then upload it
If you can get it work, it should be fine.

> should all the chunks of the same ChunkManifest be on the same "volume server"/"volume"?
No.
> what are collections? what are they similar to on a normal file system?
You do not need to use it.

> where are Filer (distrbuted) instances located? master or volume servers?
anywhere.

**Comment by CheyenneForbes** [comment]
is there anyway to access a file added using a ChunkManifest from the Filer? for example requesting "localhost:8888/webcam_rec/chunk_manifest_name_field.mp4"

**Comment by chrislusf** [comment]
I do not understand the question. To access the file,
 curl "http://localhost:8888/webcam_rec/chunk_manifest_name_field.mp4"

**Comment by CheyenneForbes** [comment]
When uploading the chunk manifest, how can I tell SeaweedFS I want it to be accessed from webcam_rec or cctv_rec if I didnt upload it to the Filer but directly to the volume server with the FID?

**Comment by chrislusf** [comment]
upload it to the filer is easier.

I do not understand why you want to skip filer when uploading, but still want to use filer to access later.
