### ISSUE TITLE
Large file download failed

### ISSUE THREAD

**Issue by chaochao1221** [chrislusf/seaweedfs#423]
File downloads greater than 60M will fail.

version:
v0.69

command:  
> ./weed master
> weed volume -dir="/data1" -max=5  -mserver="localhost:9333" -port=8080 &  
> curl -X POST http://localhost:9333/dir/assign
> curl -X PUT -F file=@115830-5155.ppt http://127.0.0.1:8080/6,02e0dae649

download:
Access http://192.168.xxx.xx:8080/6,02e0dae649?dl=1 on another computer,the download process will be interrupted.

**Comment by chrislusf** [comment]
Can you show the output of "curl -X PUT -F file=@115830-5155.ppt ..."
Can you show how do you access "http://192.168.xxx.xx:8080/6,02e0dae649?dl=1"? and how it is interrupted?

Why there is a "dl=1"?

**Comment by chaochao1221** [comment]
>  curl -X PUT -F file=@115830-5155.ppt http://127.0.0.1:8080/4,03ede1f4a6
    {"name":"115830-5155.ppt","size":64062464}%

![image](https://cloud.githubusercontent.com/assets/16441917/21465999/6a7bb618-c9f3-11e6-90d9-ad9dd78ff7cc.png)
![image](https://cloud.githubusercontent.com/assets/16441917/21465944/14fe8db0-c9f2-11e6-96c4-60f7f31bed0a.png)
![image](https://cloud.githubusercontent.com/assets/16441917/21465945/1a772db0-c9f2-11e6-9789-0bc6a867ff85.png)


Thank you for your reply.I use the chrome browser to download the file more than 60 M, when downloading more than 40 M will be interrupted, I and my friends tried many times, when the speed of several hundred k / s because the download is slow, the interrupt rate of recurrence High, when the speed of 3M / s will soon be able to download down, so this problem does not occur

**Comment by chrislusf** [comment]
set the "idleTimeout" to a bigger number.

chris$ weed volume -h
  -idleTimeout int
    	connection idle seconds (default 10)
