### ISSUE TITLE
Where to put Filer in production

### ISSUE THREAD

**Issue by CheyenneForbes** [chrislusf/seaweedfs#425]
if I want to use seaweedFs in production for a project where high scaling is important,  where should the Filer(s) be?
1. on the master server
2. on each volume server
3. dedicated Filer servers

**Comment by ijunaid8088** [comment]
Filer should be on master server.

**Comment by CheyenneForbes** [comment]
When using the Filer on the master server,
- if there are millions of requests for files (upload/download) per 30 seconds will this cause performance issues since theres just one master server? will memory run out?
- also is there anytime I shouldnt use the Filer?
- does scale well?

**Comment by ijunaid8088** [comment]
We are in production with one master volume server having filer with it and 2 other volume server, each of 70TB.

And we are sending more than millions of requests per 30 seconds or even less, Everything works fine. Weed is so flexible in such issues.

Of course, if you only have one master volume server, the memory will go out when it will be full or if you are not doing vacuum on it.

You need to add other volume servers as well as you are doing so many upload requests.

There is not any such time when you should not use Filer, or I didn't understand the question. 

Scale well? what do you mean by that?..


anyhow if am not wrong you are the one who asked for a file system which is better? Perhaps then we are in production with xfs. of 70TB

**Comment by CheyenneForbes** [comment]
Thank you, can I have the OS, processor and RAM of your master and volume servers?

also you said "We are in production with one master volume server having filer with it and 2 other volume server" does this mean theres no problem in using the master server as a volume server?

**Comment by ijunaid8088** [comment]
Yeah there is totally no issues in that. I dont see any option not to USE master as volume server.

We are with those commands..

server
```
weed -v=0 server -filer=true -ip={{seaweedfs_master_ip}} -dir={{storage_dir}} -volume.max=2270 -volume.images.fix.orientation=false -pulseSeconds=5 
```

volume
```
weed -v=0 volume -mserver={{seaweedfs_master_ip}}:9333 -ip={{seaweedfs_volume_ip}} -dir={{storage_dir}} -max=2270 -images.fix.orientation=false -pulseSeconds=1
```

all specs are here https://www.hetzner.de/ie/hosting/produkte_rootserver/sx291

We are using those Servers.

**Comment by CheyenneForbes** [comment]
thank you

**Comment by ijunaid8088** [comment]
You are welcome. 

You can also share for what purpose you are using it so I can explore it as well.

**Comment by CheyenneForbes** [comment]
I am the sole developer of a social platform ( http://www.avapnobuzz.tk/ ) from my company (Avapno Omnitech, Limited) which will launch in February 2017 to compete with Facebook, Instagram and Snapchat. Seaweedfs will be used to store short videos/images posted by users, voice messages and also to record live streams (maximum of 90 minutes for each recording)... this will be the biggest thing coming from my country (Jamaica) in technology.. I will also be using seaweedfs in more projects in 2017 (including a video/music streaming service and a "new type of" general purpose online file storage)

**Comment by CheyenneForbes** [comment]
I am the sole developer of a social platform ( [http://www.avapnobuzz.tk/] ) from my company (Avapno Omnitech, Limited) which will launch in February 2017 to compete with Facebook, Instagram and Snapchat. Seaweedfs will be used to store short videos/images posted by users, voice messages and also to record live streams (maximum of 90 minutes for each recording)... this will be the biggest thing coming from my country (Jamaica) in technology.. I will also be using seaweedfs in more projects in 2017 (including a video/music streaming service and a "new type of" general purpose online file storage)

**Comment by CheyenneForbes** [comment]
there is an issue with the landing page, i'm about to fix it, i'll comment here as soon as I fix it

**Comment by ijunaid8088** [comment]
that sound awesome.. what is your development stack ? on which language you are building this everything?

**Comment by CheyenneForbes** [comment]
user/message/posts database - hbase (with phoenix)
storage - seaweedfs
web/api servers - c++
instant messaging - MQTT protocol (erlang)
mobile apps - cordova
cdn - verizon digital media services
live streaming - custom server written in C

**Comment by ijunaid8088** [comment]
Phoenix (Elixir?)

are you people open source?

**Comment by CheyenneForbes** [comment]
not that Phoenix.. Apache Phoenix, its a highly scalable "SQL skin" for HBase, it allows you to run SQL queries on HBase data

**Comment by CheyenneForbes** [comment]
the issue with the landing page was resolved, you can see what to expect from the platform [http://www.avapnobuz.tk/](http://www.avapnobuz.tk/)

**Comment by ijunaid8088** [comment]
Yeah that's awesome.. you are the only person whose going to do every work? And have written streaming server?

**Comment by CheyenneForbes** [comment]
yes... funding, "good" coders and other resources are limited in my country, plus I just turned 18 in july

**Comment by ijunaid8088** [comment]
Nice you are doing great!



Regards


*Junaid Farooq*
Software Developer, Evercam.io
+92334- <+92347-8666955>6944005 | junaid@evercam.io | Evercam
<http://evercam.io/> | Skype: darulehsan1
<https://mail.google.com/mail/u/0/#>
<http://www.facebook.com/ijunaid8088>  <http://pk.linkedin.com/in/iamjunnii>
  <http://github.com/ijunaid8088>  <http://twitter.com/ijunaid8088>
