### ISSUE TITLE
Request timeout!

### ISSUE THREAD

**Issue by ijunaid8088** [chrislusf/seaweedfs#426]
Is there any possibilities in weedfs that there could be request timeouts?

Our server is sending so many requests for reading and writing but few times in a month we see some request timeouts. 

like 800 timeouts within 5 minutes and then everything is fine. 

@chrislusf Can you think of any reason ? why it could be? Why such time come that weedfs server stops or get idle? or anyother issues?

Right now our master volume server is full, we have 2 other volumes. 1 is full and now all the wriatble volumes are on 3rd one. we are on 0.71 beta version. Can you suggest something?

**Comment by chrislusf** [comment]
I am not sure whether you have the latest fix which removes some caching.

**Comment by ijunaid8088** [comment]
Actually, this behaviour is not permanent, like few days there will be no such error, but sometimes there are 2K.

we are on 0.71 Beta but its too old, like a year old may be. where i can get/build the latest version from repository?

**Comment by chrislusf** [comment]
just use "go get" to build the latest version.

No good clue. Could it be just some network issue or the problem really happens on volume server?

**Comment by ijunaid8088** [comment]
Okay thanks..

Yeah it could be.. Network issue seems impossible to me as we are on stable
servers.

I really dont understand till now that what could be the problem on volume
server.

On master server we get that issue a lot as ` Failed to read file size
/storage/2233.dat stat /storage/2233.dat: bad file descriptor`
this volume server is on that volume server which is full. this could be an
issue? Is there any way to remove that issue from 2233 volume?



Regards


*Junaid Farooq*
Software Developer, Evercam.io
+92334- <+92347-8666955>6944005 | junaid@evercam.io | Evercam
<http://evercam.io/> | Skype: darulehsan1
<https://mail.google.com/mail/u/0/#>
<http://www.facebook.com/ijunaid8088>  <http://pk.linkedin.com/in/iamjunnii>
  <http://github.com/ijunaid8088>  <http://twitter.com/ijunaid8088>

**Comment by chrislusf** [comment]
Does not seem a big issue. the Size() function is only used for stats reporting.

Not sure why "/storage/2233.dat" is wrong. It is a very basic function call "dataFile.Stat()". Maybe you can manually check what's wrong with this file.

**Comment by ijunaid8088** [comment]
Right, then we don't need to worry about this.

on the index page for that server 

![image](https://cloud.githubusercontent.com/assets/13561999/21514740/7a87a946-ccea-11e6-9982-9a9b420cdb39.png)

it is showing the stats already

**Comment by ijunaid8088** [comment]
this is the results while
```
root@media /storage # ls -l 2233.dat 
-rw-r--r-- 1 root root 31457871704 Nov 26 21:49 2233.dat
```
