### ISSUE TITLE
filer directory listing in html instead of json

### ISSUE THREAD

**Issue by dfrost999** [chrislusf/seaweedfs#429]
Hi,

I just installed the new Version 0.72 and I don't manage to get filer directory listings in json format anymore. The output is html. I tried setting an accept head "Accept: application/json" and the like but no change.
Is there a way to still have json output?

Thanks,
Deacon

**Comment by chrislusf** [comment]
This seems related to https://github.com/chrislusf/seaweedfs/pull/424
