### ISSUE TITLE
Where is store file metadata in Seaweedfs?

### ISSUE THREAD

**Issue by lorico** [chrislusf/seaweedfs#431]
Hello,
Sorry for the dumb question, but I don't understand how metadata is saved when importing 1 file into a volume server, then exported back to disk ?
ie: I have 1 picture, with a creation date, modified date etc...
1/ I import it into a volume server (let's say volume 3)
2/ then I use the weed export function on volume 3, and I am getting back my initial picture in a nice tar file, with all metadata (creation date, modified date etc...) as in the begining.
- Where is the magic ? where is store this metadata ? as when I lookup the file by its fid, 
=> I don't get those metadata into the generated json (at best I get filename & size) ?

Hope somebody can give me a light here...
thx

**Comment by chrislusf** [comment]
the metadata you mentioned are stored together with the file itself. On disk, it's stored as: metadata1, metadata2, metadata3, ..., actual data.

**Comment by stevenkitter** [comment]
version: "2"

services:
  master:
    image: chrislusf/seaweedfs
    ports:
      - 9333:9333
    command: 'master -mdir="/home/ubuntu/production/files/file_ids"'
    networks:
      - internal
  volume:
    image: chrislusf/seaweedfs
    ports:
      - 8080:8080
      - 18080:18080
    command: 'volume -max=5 -mserver="master:9333" -port=8080 -dir="/home/ubuntu/production/files/data"'
    depends_on:
      - master
    networks:
      - internal
  filer:
    image: chrislusf/seaweedfs
    ports:
      - 8888:8888
      - 18888:18888
    command: 'filer -master="master:9333"'
    depends_on:
      - master
      - volume
    networks:
      - internal

networks:
  internal:
    external: true

this is my docker-compose, but nothing in my /home/ubuntu/production/files/data, where the files.

**Comment by chrislusf** [comment]
@stevenkitter it is specified in filer.toml, which is "current directory"

 https://github.com/chrislusf/seaweedfs/blob/master/docker/filer.toml

Let me know whether you find it or not.
