### ISSUE TITLE
When download file, I can't get the filename

### ISSUE THREAD

**Issue by wangjie** [chrislusf/seaweedfs#433]
util.http_util.go中方法 DownloadUrl通过Content-Disposition获取filename时有问题，还需要考虑inline或attachment前缀。

if strings.HasPrefix(contentDisposition[0], "filename=") {
            filename = contentDisposition[0][len("filename="):]
            filename = strings.Trim(filename, "\"")
}

use case:
1) upload one file, and we get the fileId
2) download the file with method DownloadUrl by fileId, and can't get filename.

**Comment by chrislusf** [comment]
DownloadUrl is not meant to be a generic method as a public API.

**Comment by chrislusf** [comment]
fixed by https://github.com/chrislusf/seaweedfs/pull/434
