### ISSUE TITLE
upload css.gz suffix file without chunk, and download it, the md5 is not equal.

### ISSUE THREAD

**Issue by wangjie** [chrislusf/seaweedfs#437]
if ext == ".gz" {
			if strings.HasSuffix(fileName, ".css.gz") ||
				strings.HasSuffix(fileName, ".html.gz") ||
				strings.HasSuffix(fileName, ".txt.gz") ||
				strings.HasSuffix(fileName, ".js.gz") {
				fileName = fileName[:len(fileName)-3]
				isGzipped = true
			}
}

when we read the file, for it doesn't with suffix gz, and  can't set Content-Encoding=gzip.

**Comment by chrislusf** [comment]
see https://github.com/chrislusf/seaweedfs/wiki/Optimization#gzip-content
