### ISSUE TITLE
seaweedfs keeps trying to use localhost when I already specified an IP  

### ISSUE THREAD

**Issue by rbnx** [chrislusf/seaweedfs#438]
I'm trying seaweedfs for the first time, I'm using 3 machines. 

Whenever I try to connect to the leader server I specify a public IP but seaweed keeps trying to use localhost

`./weed volume -dir="/var/swfs" -max=10  -mserver="<SOME_PUBLIC_IP>:7001" -port=7003
`
`2017/01/11 07:04:34 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:7001: getsockopt: connection refused"; Reconnecting to {localhost:7001 <nil>}`

I have to retry the command several times for seaweed to stop trying to use localhost and use the public ip .

When it's finally working I try to follow the examples in README.md 

`curl -X POST http://<LEADER_IP>:7001/dir/assign
`
but again, it tries localhost and not the actual ip

`{"error":"Cannot grow volume group! Failed to assign 1: Post http://127.0.0.1:7002/admin/assign_volume: dial tcp 127.0.0.1:7002: getsockopt: connection refused"}`

**Comment by chrislusf** [comment]
Please post your volume server startup printouts

**Comment by rbnx** [comment]
```
VOLUME 1:

./weed volume -dir="/var/swfs" -max=10  -mserver="<LEADER_IP>:7001" -port=7003
I0111 07:04:57 26898 file_util.go:20] Folder /var/swfs Permission: -rwxrwxrwx
I0111 07:04:57 26898 disk_location.go:97] Store started on dir: /var/swfs with 0 volumes max 10
I0111 07:04:57 26898 volume.go:141] Start Seaweed volume server 0.72 at 0.0.0.0:7003
I0111 07:04:57 26898 volume_grpc_client.go:17] Volume server bootstraps with master <LEADER_IP>:7001
I0111 07:04:57 26898 volume_grpc_client.go:51] Heartbeat to <LEADER_IP>:7001


VOLUME 2:

./weed volume -dir="/var/swfs" -max=10  -mserver="<LEADER_IP>:7001" -port=7002
I0111 06:43:26 18327 file_util.go:20] Folder /var/swfs Permission: -rwxrwxrwx
I0111 06:43:26 18327 disk_location.go:97] Store started on dir: /var/swfs with 0 volumes max 10
I0111 06:43:26 18327 volume.go:141] Start Seaweed volume server 0.72 at 0.0.0.0:7002
I0111 06:43:26 18327 volume_grpc_client.go:17] Volume server bootstraps with master <LEADER_IP>:7001
I0111 06:43:26 18327 volume_grpc_client.go:51] Heartbeat to <LEADER_IP>:7001
```

**Comment by chrislusf** [comment]
Please also specify volume server ip address "weed volume -ip xxxx"

**Comment by chrislusf** [comment]
what's the master's printout?

**Comment by chrislusf** [comment]
There were some changes related to this area in last few days. Please sync the code if your code is a little behind.

**Comment by chrislusf** [comment]
any updates?

**Comment by rbnx** [comment]
@chrislusf 
Sorry, I was out for a bit.
adding the -ip flag as you suggested solved my problem. Thanks!
