### ISSUE TITLE
Adding S3 compatible API

### ISSUE THREAD

**Issue by wendigo** [chrislusf/seaweedfs#44]
Is it possible to implement API compatible with S3?

**Comment by chrislusf** [comment]
It's possible. There is another project doing this already:
https://github.com/tgulacsi/s3weed

In the future, we can incorporate the S3 API also.

**Comment by wendigo** [comment]
Cool, thanks for the info!

**Comment by stuartpb** [comment]
You know, I'd actually like to see a daemon/library that does the *reverse* - imitating seaweed's API for S3-interface backends. This way, you can write your code for the (simpler) blob storage paradigm presented by weed, then deploy it to use S3 (or Swift or RADOS or whatever backing store with an S3-compatible API) with a more mainstream provider until a dedicated weedfs solution manifests itself.

**Comment by chrislusf** [comment]
This is added in 0.92 release.
