### ISSUE TITLE
Reading the Directory Tables / Finding the very first file

### ISSUE THREAD

**Issue by ijunaid8088** [chrislusf/seaweedfs#444]
Do you think building a feature in SeaweedFS as: what is the very first file or directory tree and last file or directory tree created? could be tough or easy to do?

Actually, we are dealing with Cameras, and we have some specific file structure on volumes such, 

`master:port/ballymore-wave/snapshots/recordings/2016/10/24/07/`

What if a user wants to know which file has been added first and which one added the very last? the main directory is `master:port/ballymore-wave/` but there could be many files within on directory even more than one directory in root directory, Is that possible or is there any existing feature in seaweedFS, where we can read the directory tables and can tell, Which was the first even file was added to that directory, with some specific extension, for example, *jpg ? which jpeg file was added the very first and which was added the very end till now? 

Am adding @chrislusf to that conversation as well, If you have some good ideas about it?

**Comment by chrislusf** [comment]
It's possible to do, but this is kind of specific to your need and may not be one of the SeaweedFS generic features.

**Comment by ijunaid8088** [comment]
:) Thanks for the reply but, can you give me lead on this, If I may put that feature then where should I put it? May someone else also has the idea of doing this but never asked for it?
