### ISSUE TITLE
Doc updates for 0.73 / 0.74

### ISSUE THREAD

**Issue by brstgt** [chrislusf/seaweedfs#445]
Please add some release notes

- NOT to use 0.73 as it can completely f*** existing volumes
- Upgrade notices on 0.74 as to recreate index files, how to do that, why and what can happen if this is not done
- Update admin routes in WIKI, they are really outdated

**Comment by ijunaid8088** [comment]
We are using this product, Its a huge favour to us, Its kind of annoying that you are using such words on GH. First, you used complete word now * one.
Please remove/edit that word from here and your previous issue as well :)

**Comment by chrislusf** [comment]
I have deleted the 0.73 release and only the 0.74 releases are available to download.

**Comment by chrislusf** [comment]
Actually, @brstgt could you please provide a section of text to describe the new API you added and the examples, similar to descriptions in this page?

https://github.com/chrislusf/seaweedfs/wiki/API

**Comment by brstgt** [comment]
I will. Now it is 5am and weekend here. I will do that on Monday. If you
would like to give me access to the wiki I can help updating the docs
directly.

Btw the **** words were not meant to depreciate your work and effort. They
were meant only to emphasize the severity of that situation. Sorry for
that.

Am 21.01.2017 05:28 schrieb "Chris Lu" <notifications@github.com>:

**Comment by ijunaid8088** [comment]
@brstgt Yeah I can understand. We all go through such issues in production, You issue helped me as well I was about to update us as well. but stopped due to your URGENT issue :)
