### ISSUE TITLE
avoid "request Content-Type isn't multipart/form-data"

### ISSUE THREAD

**Issue by CheyenneForbes** [chrislusf/seaweedfs#446]
I am trying to upload the bytes of a jpg file but I am getting "request Content-Type isn't multipart/form-data" when I try to POST it

**Comment by chrislusf** [comment]
Please show how to reproduce it.

**Comment by CheyenneForbes** [comment]
1. read the bytes from a png file (any file format)

2. set content type header to "image/png"

3. set the read bytes as the request body

4. set method to POST

5. execute request

**Comment by CheyenneForbes** [comment]
I'm not using the filer

**Comment by chrislusf** [comment]
Should use "multipart/form-data" to post, as the error message suggested. You can look at example in https://github.com/chrislusf/seaweedfs/blob/master/weed/operation/upload_content.go#L47

**Comment by CheyenneForbes** [comment]
could the functionality be added to allow us to upload to seaweedfs volume servers without using "multipart/form-data" and upload the file content as the body and set the content-type header to the file type (eg. image/png)? would be great for when using "multipart/form-data" isnt an option for a project

**Comment by CheyenneForbes** [comment]
can it be done?

**Comment by chrislusf** [comment]
Is this a standard way to do http post?

**Comment by CheyenneForbes** [comment]
I'm not sure, I only know it can be done. I was asking if it can be done because some of my code is in erlang and due to the errors of the multipart libraries in erlang only uploading the file content (the bytes) as the body and set the content-type header to the file type (eg. image/png) is suitable for production. If I am correct my question should be "Can I upload files to weedfs volume servers without using multipart/form-data?"

**Comment by CheyenneForbes** [comment]
I did some research and it is a standard way to do http file post... 

```
POST /5,0349f2040d HTTP/1.1
Content-Encoding: gzip
Content-Type: text/plain

demo text content blah blah blah
```
