### ISSUE TITLE
./weed benchmark crash

### ISSUE THREAD

**Issue by cartosquare** [chrislusf/seaweedfs#449]
Developers:

when I run benchmark according to wiki page: https://github.com/chrislusf/seaweedfs/wiki/Benchmarks, the benchmark crashes. 

my OS is macOS Sierra 10.12.3.

weed version:
version 0.72 darwin amd64

Please see the logs in the attach files.

[volume_8085.txt](https://github.com/chrislusf/seaweedfs/files/753595/volume_8085.txt)
[server.txt](https://github.com/chrislusf/seaweedfs/files/753596/server.txt)
[benchmark.txt](https://github.com/chrislusf/seaweedfs/files/753594/benchmark.txt)

**Comment by chrislusf** [comment]
Did you compile it in Go 1.7?

**Comment by cartosquare** [comment]
No, I download the binary file.

**Comment by chrislusf** [comment]
Please try the latest 0.74 version?

**Comment by cartosquare** [comment]
The 0.74 version is ok.:)

**Comment by chrislusf** [comment]
Are you able to consistently reproduce the issue with 0.72?

**Comment by cartosquare** [comment]
Yes, I tried several times today, sometimes the master server dead with following fatal error: 
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x4f87b5e6a6ff pc=0x94ad0]

and followed by lots of goroutine  [IO wait] outputs.

sometimes the benchmark or volume server will died after many EOF error:
failing to upload to http://127.0.0.1:8084/6,0196d9289759a9 Post http://127.0.0.1:8084/6,0196d9289759a9: EOF
