### ISSUE TITLE
needle's rawblock cache maybe hit by mistake occasionally in edge scenario

### ISSUE THREAD

**Issue by hxiaodon** [chrislusf/seaweedfs#450]
Chris:
Today I found one volume file become read only(id: 3002) after compaction, so I took time to find out the root cause

Below is my online log:
```
I0206 06:56:50 17728 volume_server_handlers_vacuum.go:16] checked compacting volume = 2957 garbageThreshold = 0.1 vacuum = false
I0206 06:56:50 17728 volume_server_handlers_vacuum.go:16] checked compacting volume = 3002 garbageThreshold = 0.1 vacuum = true
I0206 06:56:51 17728 volume_server_handlers_vacuum.go:25] compacted volume = 3002 , error = <nil>
I0206 06:56:51 17728 volume_loading.go:62] open to write file /data/seaweedfs/weed-volume/lawsuit-bucket_3002.idx
I0206 06:56:51 17728 volume_loading.go:69] volumeDataIntegrityChecking failed verifyNeedleIntegrity /data/seaweedfs/weed-volume/lawsuit-bucket_
3002.idx failed: File Entry Not Found. Needle 5040252 Memory 5040257
I0206 06:56:51 17728 volume_loading.go:73] loading index file /data/seaweedfs/weed-volume/lawsuit-bucket_3002.idx readonly true
I0206 06:56:51 17728 needle_map_memory.go:51] max file key: 258388066 for file: /data/seaweedfs/weed-volume/lawsuit-bucket_3002.idx
I0206 06:56:51 17728 volume_server_handlers_vacuum.go:34] commit compact volume = 3002 , error = <nil>
```
From above volume log,  we could conclude that the volumeDataIntegrityChecking failed after the 3002 volume is compacted.

But when I restart this volume server, everything seems to be OK
```
Log file created at: 2017/02/06 11:30:38
Running on machine: xxxxxxxxx
Binary: Built with gc go1.7.3 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss threadid file:line] msg
I0206 11:30:38 51565 file_util.go:20] Folder /data/seaweedfs/weed-volume Permission: -rwxrwxr-x
I0206 11:30:38 51565 volume_loading.go:62] open to write file /data/seaweedfs/weed-volume/lawsuit-bucket_3002.idx
I0206 11:30:38 51565 volume_loading.go:73] loading index file /data/seaweedfs/weed-volume/lawsuit-bucket_3002.idx readonly false
I0206 11:30:38 51565 needle_map_memory.go:51] max file key: 258388066 for file: /data/seaweedfs/weed-volume/lawsuit-bucket_3002.idx
I0206 11:30:38 51565 disk_location.go:64] data file /data/seaweedfs/weed-volume/lawsuit-bucket_3002.dat, replicaPlacement=101 v=2 size=39271144 ttl=
```

And I suspect that the Needle's ReadData function get the cached needle data by mistake which lead to the following error:
3002.idx failed: File Entry Not Found. Needle 5040252 Memory 5040257

Because the current block cache key format is:
`cacheKey := fmt.Sprintf("%d:%d:%d", r.Fd(), offset>>3, readSize)`
If the fid is reused by OS and one needle's offset in old dat file and new compacted dat file is same(their file size diff is less than the needle alignment padding size), then the cache hitting is triggered. This is actually a edge case, but it did happen

Do you have any suggestion on this scenario? 
Thanks!

**Comment by chrislusf** [comment]
1. your theory is possible.

2. Why the integrity check failed but compaction commit still happened?

**Comment by hxiaodon** [comment]
Regarding the point 2, I review the volume's loading code
![image](https://cloud.githubusercontent.com/assets/10990210/22639337/7aaff668-ec88-11e6-9d1a-d23374657140.png)
The commitCompact -> volume.load() will not throw error but log it.

**Comment by hxiaodon** [comment]
Chris:
How about adding the compact version into block cache key?
Below is the code change
```
func ReadNeedleBlob(r *os.File, offset int64, size uint32,version Version) (dataSlice []byte, block *Block, err error) {
	padding := NeedlePaddingSize - ((NeedleHeaderSize + size + NeedleChecksumSize) % NeedlePaddingSize)
	readSize := NeedleHeaderSize + size + NeedleChecksumSize + padding
	return getBytesForFileBlock(r, offset, int(readSize),version)
}

func (n *Needle) ReadData(r *os.File, offset int64, size uint32, version Version) (err error) {
	bytes, block, err := ReadNeedleBlob(r, offset, size,version)
	if err != nil {
		return err
	}
...

func getBytesForFileBlock(r *os.File, offset int64, readSize int,version Version) (dataSlice []byte, block *Block, err error) {
	// check cache, return if found
	cacheKey := fmt.Sprintf("%d:%d:%d:%d", r.Fd(), offset>>3, readSize,version)
...
```

**Comment by hxiaodon** [comment]
Adding compact version as part of the block cache key will reduce the incorrect hit probability(not sure if it could eliminate the issue thoroughly). And it will lead to the specific volume's entire cache miss after the compaction.
Does this code change make sense? Thanks!

**Comment by chrislusf** [comment]
This change sounds good. But it's good to let it run a while to see the results.

**Comment by hxiaodon** [comment]
OK. I will ship this draft fix in dev environment firstly

**Comment by chrislusf** [comment]
@hxiaodon  how is it?

**Comment by hxiaodon** [comment]
Chris:
       I'm a little bit ashamed that I did not work on this issue since Feb 13.  I will sync the latest seaweedfs code and create the pull request by the end of this week.

**Comment by chrislusf** [comment]
I plan to remove the caching layer, since not much improvement are noticed.

https://github.com/chrislusf/seaweedfs/tree/skip_memory_pool

**Comment by hxiaodon** [comment]
Chris:
Will this application caching be removed permanently? I feel that the OS page cache will not be always good enough since it will cache the whole 4KB page blocks(even this page just have partial valid data) instead of many possible far smaller files in a consolidated memory 

The current lru cache used by seaweedfs is hashicorp one, how about [bigcache or freecache](https://github.com/allegro/bigcache#bigcache-vs-freecache), these 2 lib are efficient ones compared with others

Of course weedfs is a disk storage solution, adding memory cache layer out of it is also a good solution.

**Comment by chrislusf** [comment]
Depends on performance numbers.

**Comment by chrislusf** [comment]
not applicable since the cache has been removed now.
