### ISSUE TITLE
How to set multiple server conf

### ISSUE THREAD

**Issue by joveth** [chrislusf/seaweedfs#453]
Sorry to disturb you.
Well,I'm using this to store my images on two linux machines.
The weedfs.conf like this:

    <Configuration>
      <Topology>
         <DataCenter name="dc1">
         <Rack name="rack1">
           <Ip>172.28.109.1</Ip>
      </Rack>
    </DataCenter>
    <DataCenter name="dc2">
      <Rack name="rack1">
        <Ip>172.28.109.2</Ip>
      </Rack>
    </DataCenter>
    </Topology>
    </Configuration>`

And In 172.28.109.1 the start code is:

    weed master -defaultReplication=100 -conf="weedfs.conf" -mdir=$master_dir &

    check_dir $vol_dir/vol1
    weed volume  -publicUrl=http://172.28.109.1:7070 -port=7070 -dir=$vol_dir/vol1 &
    check_dir $vol_dir/vol2
    weed volume  -publicUrl=http://172.28.109.1:7071 -port=7071 -dir=$vol_dir/vol2 &
    check_dir $vol_dir/vol3
    weed volume  -publicUrl=http://172.28.109.1:7072 -port=7072 -dir=$vol_dir/vol3 &

And in 172.28.109.2 the code is:

    weed master -defaultReplication=100 -conf="weedfs.conf" -mdir=$master_dir &

    check_dir $vol_dir/vol1
    weed volume  -publicUrl=http://172.28.109.2:7070 -port=7070 -dir=$vol_dir/vol1 &
    check_dir $vol_dir/vol2
    weed volume  -publicUrl=http://172.28.109.2:7071 -port=7071 -dir=$vol_dir/vol2 &
    check_dir $vol_dir/vol3
    weed volume  -publicUrl=http://172.28.109.2:7072 -port=7072 -dir=$vol_dir/vol3 &

When use the /dir/assign to get fid but return error.

    {"error":"Cannot grow volume group! Not enough data node found!"}

As  the wiki cannot get enough infor.So help me!Or just give somg tips.

Thank you very much!

**Comment by chrislusf** [comment]
weedfs.conf is deprecated.

**Comment by joveth** [comment]
@chrislusf Well,what's this mean?Can not use weedfs.conf?or other replace it?Some tips?

**Comment by chrislusf** [comment]
I mean do not use it. The command line options have it all covered.

**Comment by joveth** [comment]
@chrislusf I'm  sorry for that . I didn't show my problems correctly. I mean that I want two server , when upload an image to one of them .the other can backup a same.So how the conf shows . Thank you very much.

**Comment by ijunaid8088** [comment]
@joveth No need to say sorry that much. You are a user of SeaweedFS and you have right to ask a question.

**Comment by chrislusf** [comment]
@joveth You just need one master server.

weed master -defaultReplication=100 -mdir=$master_dir

weed volume  -publicUrl=http://172.28.109.1:7070 -port=7070 -dir=$vol_dir/vol1 -dataCenter=dc1 -rack=rack1
...

weed volume  -publicUrl=http://172.28.109.2:7070 -port=7070 -dir=$vol_dir/vol1  -dataCenter=dc2 -rack=rack1
...
