### ISSUE TITLE
Strange behavior in latest release linux_amd64..

### ISSUE THREAD

**Issue by ijunaid8088** [chrislusf/seaweedfs#454]
Not sure what the issue is but I downlaoded the latest  version from https://github.com/chrislusf/seaweedfs/releases/download/0.74/linux_amd64.tar.gz and started volume server  and getting this error what it could be? 
`/usr/bin/weed -v=0 volume -mserver=138.21.150:9333 -ip=88.9..88 -dir=/storage -max=2270 -images.fix.orientation=false -pulseSeconds=1`
```
I0222 19:46:39  5279 file_util.go:20] Folder /storage Permission: -rwxr-xr-x
I0222 19:46:39  5279 disk_location.go:97] Store started on dir: /storage with 0 volumes max 2270
I0222 19:46:39  5279 volume.go:141] Start Seaweed volume server 0.74 at 0.0.0.0:8080
I0222 19:46:39  5279 volume_grpc_client.go:17] Volume server bootstraps with master 138.201.13.150:9333
I0222 19:46:39  5279 volume_grpc_client.go:52] Heartbeat to 138.21.150:9333
2017/02/22 19:46:39 transport: http2Client.notifyError got notified that the client transport was broken read tcp 88.99.139.88:55008->138.21.150:9333: read: connection reset by peer.
I0222 19:46:39  5279 volume_grpc_client.go:25] heartbeat error: rpc error: code = 13 desc = transport is closing
2017/02/22 19:46:39 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 138.21.150:9333: operation was canceled"; Reconnecting to {138.21.150:9333 <nil>}
2017/02/22 19:46:39 grpc: addrConn.transportMonitor exits due to: grpc: the connection is closing
I0222 19:46:40  5279 store.go:35] Resetting master nodes: nodes:[138.21.150:9333 138.21.150:9333], leader:
I0222 19:46:40  5279 volume_grpc_client.go:52] Heartbeat to 138.21.1.150:9333
2017/02/22 19:46:40 transport: http2Client.notifyError got notified that the client transport was broken read tcp 88.1.88:55012->138.2.1.150:9333: read: connection reset by peer.
```

**Comment by chrislusf** [comment]
Are those the real IP addresses?

**Comment by ijunaid8088** [comment]
Actually those were.. i just edited them.. also version 0.70 works totally
fine..

**Comment by chrislusf** [comment]
The heartbeat is changed from simple http call to gRPC calls. It needs a persistent connection, in this case, 88.9..88:55008->138.21.150:9333.

Make sure both master and volume server are the same version.

**Comment by ijunaid8088** [comment]
Okay then thats the issue..

Other master and volume are on 0.71 Beta..

Btw when seaweedFS was on version 70.. at that momet it was fine to have
different versions on master and volume..



Regards


*Junaid Farooq*
Software Developer, Evercam.io
+92334- <+92347-8666955>6944005 | junaid@evercam.io | Evercam
<http://evercam.io/> | Skype: darulehsan1
<https://mail.google.com/mail/u/0/#>
<http://www.facebook.com/ijunaid8088>  <http://pk.linkedin.com/in/iamjunnii>
  <http://github.com/ijunaid8088>  <http://twitter.com/ijunaid8088>
