### ISSUE TITLE
Filer path does not have TTL?

### ISSUE THREAD

**Issue by wangfeiping** [chrislusf/seaweedfs#456]
I try to submit file with TTL, it's OK.
And then, I try to submit file with TTL to filer, but the file path still exist when time out and the file stored has been deleted.
I use the latest version that built by myself, and I don't find any doc about filer TTL.
Do I need to manually clean up?
Or just is my mistake?

**Comment by wangfeiping** [comment]
I found an error!
curl -F "f=@/apps/seaweedfs/car.jpg" "http://localhost:8888/public/test/?ttl=3m"
{"fileName":"car.jpg","size":105878,"fid":"9,036729976b","fileUrl":"172.28.32.130:9360/9,036729976b"}

curl -X DELETE http://localhost:8888/public/test/car.jpg
{"error":""}
curl -X DELETE http://localhost:8888/public/test/
{"error":""}
curl -X DELETE http://localhost:8888/public/
{"error":""}

in filer log:
I0223 11:26:01 15588 filer_server_handlers_write.go:319] error Directory /public/test Not Found occur when finding /public/test/car.jpg in filer store

but the file and path seems like deleted successfully.

**Comment by chrislusf** [comment]
Correct. Filer path does not have TTL.
