### ISSUE TITLE
Seaweed + Consul Integration

### ISSUE THREAD

**Issue by curtisyu** [chrislusf/seaweedfs#457]
Hi, I’m currently looking into running Seaweed on a cluster of machines that already have Consul (https://www.consul.io/, https://github.com/hashicorp/consul) running for service discovery (given our server environment is highly dynamic). We are interested in running Seaweed without a single point of failure (https://github.com/chrislusf/seaweedfs/wiki/Failover-Master-Server).

When starting multiple masters, instead of using hard-coded IPs as parameters, is there a way to have Seaweed use Consul for discovery? Thanks.

**Comment by chrislusf** [comment]
The master servers are kind of like Consul DNS server themselves. 

Not sure how SeaweedFS should work in this case.
