### ISSUE TITLE
Filer is filling other directory as well.

### ISSUE THREAD

**Issue by ijunaid8088** [chrislusf/seaweedfs#459]
I started master server as 

weed -v=0 server -filer=true -dir=storage -pulseSeconds=1 -volume.images.fix.orientation=false

Volume server as 

weed -v=0 volume -mserver=localhost:9333 -port=1234 -dir=/home/ijunaidfarooq/vstorage -max=2 -images.fix.orientation=false -pulseSeconds=1

and filer on that directory as

weed filer -port=7878 -dir=/home/ijunaidfarooq/vstorage.

and I sent the file to 7878 port as 

curl -F file=@pgadmin.log "http://localhost:7878/javascript/"

File is available at 7878 port. But its not being saved in filer directory, but in master volume's directory. why is it so?

UPADATE:

Moreover I am just using that filer port to save images but data is also going in master filer as well. even am not sening reuqest to it but seaweed filling /storage as well.? why is it so?

**Comment by chrislusf** [comment]
Filer stores the directory structure. The actual files are still stored in the volume servers.

**Comment by ijunaid8088** [comment]
Okay thanks for closing the issue :)

One  more thing. What is the benefit of having filer at different volumes? I have started filer on vstorage directory on which i have started the volume. It should store files to that volume only on which directory i have started the filer? NO?

Anyhow thanks :)

**Comment by chrislusf** [comment]
That's the current design. Where you start the filer has nothing to do with where the data is stored.

**Comment by ijunaid8088** [comment]
Okay, thanks for quick response :)

as you have seen I have posted a question there 
https://groups.google.com/forum/#!topic/seaweedfs/1YOXS5IWYcE

In case you can guide me please if that is possible as well?
