### ISSUE TITLE
Custom set metadata cannot be retrieved via Filer

### ISSUE THREAD

**Issue by stepanbujnak** [chrislusf/seaweedfs#460]
When I upload a file using following command:

    curl -H 'Seaweed-Key1: value1' -F file=@hello.txt http://localhost:8888/hello.txt

it might return something like:

    {"name":"hello.txt","size":36,"fid":"11,13a44278381b","url":"http://localhost:8080/11,13a44278381b"}

and then retrieve the headers using Filer like this:

    curl -I http://localhost:8888/hello.txt

I will not get the `Key1` header, however, when I retrieve headers using the Volume API like this:

    curl -I http://localhost:8080/11,13a44278381b

I will get back the header. I feel like I should be able to do the same using the Filer API.

**Comment by stepanbujnak** [comment]
One interested thing I just noticed, when requesting headers using the FID like this

    curl -LI http://localhost:9333/11,13a44278381b

sometimes I get back the custom set field and sometimes I don't.

**Comment by stepanbujnak** [comment]
**Update**

I'm setting `replication=001` when uploading the file, and when I request one location, I get the custom set field and when I request the other location I don't. So I guess the problem is that the custom set fields are not replicated?

**Comment by sparklxb** [comment]
@stepanbujnak thank you for your report. When I add the metadata feature, I don't test it when using Filer. I'll fix it in 12 hours. Sorry for my carelessness.

**Comment by sparklxb** [comment]
@stepanbujnak I have tested all you mentioned above in latest code. I don't find anything wrong in the first two comments. Please test them using latest code.
Bug in third comment has been fixed in pr #461.

**Comment by chrislusf** [comment]
closing this if no more actions.
