### ISSUE TITLE
Industry use?

### ISSUE THREAD

**Issue by sidewaiise** [chrislusf/seaweedfs#462]
Just wondering if you have any case studies yet where this was a choice platform for large file serving for industry?

**Comment by chrislusf** [comment]
This is a spare time project. No time to write them down yet.

**Comment by sidewaiise** [comment]
Thanks Chris. Just wondering if I can use it for work with confidence. Looked at this several years back and great to see it's evolving still.

If you can share any use cases at all, would be really useful. Cheers
