### ISSUE TITLE
View contents of the manifest file

### ISSUE THREAD

**Issue by stepanbujnak** [chrislusf/seaweedfs#464]
Is it possible to view the actual json specification of the manifest file? I'm trying to get FIDs of all the chunks but cannot figure out how.

**Comment by sparklxb** [comment]
The manifest file is used internally and not exposed externally.

**Comment by stepanbujnak** [comment]
Yes, I know, but being able to view contents of the file by e.g. passing `?cm=false` as a parameter would be nice.

**Comment by chrislusf** [comment]
Nice fix. Need to document this API
