### ISSUE TITLE
Simplify id creation

### ISSUE THREAD

**Issue by Superman132** [chrislusf/seaweedfs#465]
I think that it might be smart to reduce the amount of steps to upload a file. Instead of

1. Going to /dir/assign and receiving the fid
2. upload the file with the fid at /{fid}

You could change it to

1. Upload the file to directly to /dir/assign and receive the fid in the response.

This api design is very similar to Ambry, and could make this library better

Thanks

**Comment by sparklxb** [comment]
You can upload file directly by /submit . See more in https://github.com/chrislusf/seaweedfs/wiki/Volume-Server-API.

**Comment by chrislusf** [comment]
@Superman132 Also, separating the fid assignment from the actual uploading gives clients more control. It's possible to customize the fid.
