### ISSUE TITLE
"weed repair": a tool to ensure all volume replica are not missing and in sync

### ISSUE THREAD

**Issue by chrislusf** [chrislusf/seaweedfs#466]

**Comment by brstgt** [comment]
Hm I did that in PHP (without taking tombstones into account as I didn't see a way to read them) but I don't know if this will help you. And my solution is quite tightly integrated with our own framework. But maybe it could inspire you.

**Comment by chrislusf** [comment]
@brstgt It'll be good to see your code or pseudo code, and we can see how to adjust it or start from scratch.

**Comment by brstgt** [comment]
I created a temporary repo for this https://github.com/brstgt/seaweed_repair_snippet
The code is not executable standalone. It is part of a framework. But it should outline what it does to repair/sync volumes.

Repair script:
https://github.com/brstgt/seaweed_repair_snippet/blob/master/bin/seaweed/repair.php

Uses mainly this class:
https://github.com/brstgt/seaweed_repair_snippet/blob/master/Service/Model/Seaweed/Admin/Repair.php

**Comment by brstgt** [comment]
@chrislusf
Not a single reply on my post? Are you maintaining seaweed at all any more?

**Comment by chrislusf** [comment]
do not understand the php logic.

**Comment by brstgt** [comment]
You could have asked. How can I help you then? What exactly is unclear?

**Comment by rockiee281** [comment]
Hi,@brstgt  I'm poor at php. But if u can explain your program maybe I can develop a standalone python script to do this repair job

**Comment by brstgt** [comment]
From my point of view, a proper repair has to be handled by seaweed directly. For a solid repair you need to be able to read all the information from the volumes. You could still provide an interface to export volumes with more detailed information but it would still be less performant than doing it directly in seaweed.

**Comment by ingardm** [comment]
@chrislusf Could you provide some insight into how you envision this to be implemented? I think we'll take a stab at implementing something for repairs, but as @brstgt mentioned, this should be handled by seaweed directly.

**Comment by chrislusf** [comment]
There could be 2 steps:
1. ensure the number of replicas are correct. If missing one replica, assign one volume server according to the replica setting.
2. for missing replicas, copy from the largest existing copy.

**Comment by brstgt** [comment]
IMHO this is a little bit more complex if you do it correctly! It's not only about volume-count it's also about comparing and repairing multiple volumes and all files contained in them. You can't simply copy over the "largest" copy. You have to consider timestamps and also tomb-stones.

**Comment by ingardm** [comment]
@chrislusf we made a script that will tell us about volume differences:
```
$ ./seaweed_volume_differ.sh
344,122265,"10.1.21.12:8080"
344,122266,"10.1.21.13:8080"
344,122266,"10.1.21.10:8080"
```

We've also seen from the logfile that the replication failed on one occasion:
```
weed[15045]: I0201 15:45:59 15045 upload_content.go:89] failing to upload to http://10.1.21.12:8080/344,025aebae94365551?ts=1517496359&type=replicate Post http://10.1.21.12:8080/344,025aebae94365551?ts=1517496359&type=replicate: read tcp 10.1.21.13:39254->10.1.21.12:8080: read: connection reset by peer
```

So in this case we'd want to replicate the one missing file from 10.1.21.12 from either 10.1.21.13 or 10.1.21.10. Is there a way I can retrigger the replicate call as seen in the logfile?

And if I didnt have the log file, how would I find out which file to replicate?

**Comment by zicklag** [comment]
Can somebody tell me if I understand this correctly: If I have a SeaweedFS cluster with replication configured, and the data on one of my volume servers gets destroyed ( like a failed disk or something like that ), then I have no way of making sure that that data is re-replicated so that the proper number of replicas exists?

I was considering using SeaweedFS in production, but this is a pretty major deal. Having the replication there doesn't help me much if I can't actually be sure that volumes have the correct number of replicas. I could loose one drive, replace it, and not loose data the first time it happens, but if the other drive fails after that and I only had two replicas configured, then my data would be gone because the data wasn't re-replicated when the broken drive was replaced.

**Comment by chrislusf** [comment]
Currently the set of replicated volumes with some of them broken will become readonly, but no data is lost.

**Comment by zicklag** [comment]
But if they are not re-replicated, and another drive fails, then that data *will* be lost, because there is now less replicas than initially specified.

**Comment by zicklag** [comment]
I've got a partner with an enterprise use-case for a clustered filesystem for Docker Swarm and so far this looks like the only deal breaker. As far as I've seen, everything else that we need is taken care of. SeaweedFS is brilliantly simple and I've only had to spend two days on it to get my Docker volume plugin migrated and setup a Dockerized highly available cluster to test it with. It is an ideal solution beating even LizardFS in simplicity and ease of use, which is amazing.

If there is any way I could help with this, I *might* be able to carve out some time for it, but I'm probably going to need some guidance. Not sure if this is the kind of thing somebody who doesn't have an in-depth knowledge of the system can help with.

**Comment by chrislusf** [comment]
Thanks! I plan to work on it in the coming week.

Maybe you can help on https://github.com/chrislusf/seaweedfs/issues/891

**Comment by chrislusf** [comment]
fixed in https://github.com/chrislusf/seaweedfs/commit/6b70b3610530d9b3637fd4179a0f2cecc5541fdd

**Comment by zicklag** [comment]
Awesome! Thank you lots! I can't wait to try it!
