### ISSUE TITLE
Connection closed

### ISSUE THREAD

**Issue by ijunaid8088** [chrislusf/seaweedfs#467]
Hello All.

we are using seaweedFS to save our images from cameras, we are with 3 volume servers and 1 master volume server. At first when we had only 2 volume servers we mostly get timeout errors from seaweedFS, But after adding a new volume server, Now we are getting error as 

```
{%HTTPoison.Error{id: nil, reason: :closed},
 [{HTTPoison, :request!, 5, [file: 'lib/httpoison.ex', line: 66]},
  {EvercamMedia.Snapshot.Storage, :seaweedfs_save, 5,
   [file: 'lib/evercam_media/snapshot/storage.ex', line: 27]},
  {EvercamMedia.Snapshot.Storage, :save, 4,
   [file: 'lib/evercam_media/snapshot/storage.ex', line: 277]}]}
```

Before that reason was Timeout and now its closed, Can anyone point what could be the problem here?

**Comment by chrislusf** [comment]
I do not know how to reproduce this.

**Comment by ijunaid8088** [comment]
Thanks for reply Chris. 

I will post a use case today, about it.

Anyhow from your previous answers.. am considering it IdleTimeout issue or no internet connection issue on other side where the volune server is.

**Comment by ijunaid8088** [comment]
Hi Chris

```
:\"Get http://{volume_ip}:8080/32788,c2cff08bd3729b47: dial tcp {volume_ip}:8080: getsockopt: connection refused\"}"
```

This is what I found out. What could this be? These errors come, when I requested a file from master server's filer.

**Comment by chrislusf** [comment]
seems there are too many connections to the volume server.

**Comment by ijunaid8088** [comment]
Hi, Chris Thanks for the reply.

Actually, we are using online servers, and our all master, volume servers are on https://www.hetzner.de/ie/hosting/produkte_rootserver/sx291

and Yes it's using `IPv6 Subnet (/64)` but it has never happened before, we are using seaweedFS on same servers for past few years, This problem just starts coming now.

Also too many connections? Do we need to reduce these connections? Eventually, SeaweedFS is capable of presenting a million files at a time. So, so many read and write requests are correct, right?

**Comment by chrislusf** [comment]
Your server may be running out of sockets. Try to reduce the connection
timeout limit.

**Comment by ijunaid8088** [comment]
Thanks for the reply Chris. 

are you talking about IdleTimeout? in seaweedFS or something else? Sorry for asking silly questions but am not sure of which timeout you are talking about?

**Comment by chrislusf** [comment]
yes, the IdleTimeout.

**Comment by ijunaid8088** [comment]
Hello Chris.

Sorry for first misleading. We are not using IPV6, we are on ipv4. So here is the use case.

We have 1 master volume server and 3 volume server, running at the moment, having size as 70 TB.

As we are dealing with Cameras, We are getting jpegs from cameras with different frequencies.
e.g.. 

1 Per Second, 1 Every 2 Seconds, 1 Every 5 Seconds, 1 Every 10 Seconds, 1 Every 60 Seconds, 1 Every 5 minutes, 1 Every 10 minutes.

1: 1 Per second means, we are requesting an image from Camera, and then sending it to master filter to store it.

Right now we have 129 Cameras on 1 Per Second frequency, and they are doing the infinite recording. at the moment, which means we are sending 129 requests per second to SeaweedFS to save jpegs. same as Other 16 Cameras for 1 every 5 seconds, 193 cameras for 1 every 2 seconds.

Just for your information, this is our **hard disk Configurations** for every Server:
```
=== START OF INFORMATION SECTION ===
Device Model:     HGST HUS726060ALE610
Serial Number:    NCH38X2Z
LU WWN Device Id: 5 000cca 24dcf960c
Firmware Version: APGNT907
Sector Sizes:     512 bytes logical, 4096 bytes physical
Rotation Rate:    7200 rpm
ATA Version is:   ACS-2, ATA8-ACS T13/1699-D revision 4
SATA Version is:  SATA 3.1, 6.0 Gb/s (current: 6.0 Gb/s)
Local Time is:    Tue Mar 14 07:52:46 2017 CET
SMART support is: Available - device has SMART capability.
SMART support is: Enabled
```

Can you suggest something now about idleTimeout or closed issue? 

Also We are on ipv4 do you suggest to move to ipv6?

**Comment by marcoherbst** [comment]
To follow on from @ijunaid8088 Jpeg sizes vary from 40kb to 400kb , the average is probably around 300kb and growing.

One concern I had re: Timeout solution is that the base load for writing is very constant, the rate at which we save images does not fluctuate. 

All 4 seaweed servers are in the same datacentre.

**Comment by chrislusf** [comment]
I am suspecting the library you use does not properly close the connections, or does not try to re-use connections.

You can go to the server and see the open files to see whether there are too many open connections.

**Comment by ijunaid8088** [comment]
Hi Chris..
Thanks for your reply..
That makes sense what are you saying. I just ran this command on master server to see opened connections:
to see HTTP ones
```
root@Ubuntu-1404-trusty-64-minimal ~ # netstat | grep http | wc -l
5061
root@Ubuntu-1404-trusty-64-minimal ~ # 
```
Connections on filer port
```
root@Ubuntu-1404-trusty-64-minimal ~ # netstat -an | grep :8888 | sort
tcp6       0      0 master_server_ip:8888     volume_server_ip:34336    ESTABLISHED
tcp6       0      0 master_server_ip:8888     volume_server_ip:35428    ESTABLISHED
tcp6       0      0 master_server_ip:8888     volume_server_ip:39950    ESTABLISHED
tcp6       0      0 master_server_ip:8888     volume_server_ip:40566    ESTABLISHED
tcp6       0      0 master_server_ip:8888     volume_server_ip:41219    ESTABLISHED
tcp6       0      0 master_server_ip:8888     volume_server_ip:42703    ESTABLISHED
tcp6       0      0 master_server_ip:8888     volume_server_ip:42712    ESTABLISHED
tcp6       0      0 master_server_ip:8888     volume_server_ip:43413    ESTABLISHED
tcp6       0      0 master_server_ip:8888     volume_server_ip:48089    ESTABLISHED
tcp6       0      0 master_server_ip:8888     volume_server_ip:48333    ESTABLISHED
tcp6       0      0 master_server_ip:8888     volume_server_ip:51288    ESTABLISHED
tcp6       0      0 master_server_ip:8888     volume_server_ip:52004    ESTABLISHED
tcp6       0      0 master_server_ip:8888     volume_server_ip:56077    ESTABLISHED
tcp6       0      0 master_server_ip:8888     volume_server_ip:56515    ESTABLISHED
tcp6       0      0 master_server_ip:8888     volume_server_ip:56683    ESTABLISHED
tcp6       0      0 master_server_ip:8888     volume_server_ip:59447    ESTABLISHED
tcp6       0      0 master_server_ip:8888     159.8.184.13:36142      TIME_WAIT  
tcp6       0      0 master_server_ip:8888     159.8.184.13:36199      TIME_WAIT  
tcp6       0      0 master_server_ip:8888     159.8.184.13:36240      FIN_WAIT2  
tcp6       0      0 :::8888                 :::*                    LISTEN     
tcp6       1      0 master_server_ip:8888     volume_server_ip:59886    CLOSE_WAIT
```
and to check on port 80

```
root@Ubuntu-1404-trusty-64-minimal ~ # netstat -an | grep :80 | sort
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN     
tcp        0      0 master_ip:32768    volume_ip:8080     ESTABLISHED
tcp        0      0 master_ip:32770    volume_ip:8080     ESTABLISHED
tcp        0      0 master_ip:32772    volume_ip:8080     ESTABLISHED
tcp        0      0 master_ip:32774    volume_ip:8080     ESTABLISHED
tcp        0      0 master_ip:32776    volume_ip:8080     ESTABLISHED
tcp        0      0 master_ip:32778    volume_ip:8080     ESTABLISHED
tcp        0      0 master_ip:32780    volume_ip:8080     ESTABLISHED
-------continues-----
tcp        0      0 master_ip:37742    volume_ip_2:8080       ESTABLISHED
tcp        0      0 master_ip:37744    volume_ip_2:8080       ESTABLISHED
tcp        0      0 master_ip:37748    volume_ip_2:8080       ESTABLISHED
tcp        0      0 master_ip:37750    volume_ip_2:8080       ESTABLISHED
tcp        0      0 master_ip:37752    volume_ip_2:8080       ESTABLISHED
tcp        0      0 master_ip:42034    volume_ip_3:8080         ESTABLISHED
tcp        0      0 master_ip:42268    volume_ip_3:8080         ESTABLISHED
tcp        0      0 master_ip:42312    volume_ip_3:8080         ESTABLISHED
tcp        0      0 master_ip:42342    volume_ip_3:8080         ESTABLISHED
tcp        0      0 master_ip:42404    volume_ip_3:8080         ESTABLISHED
tcp        0      0 master_ip:42444    volume_ip_3:8080         ESTABLISHED
tcp        0      0 master_ip:42446    volume_ip_3:8080         ESTABLISHED
tcp        0      0 master_ip:42448    volume_ip_3:8080         ESTABLISHED
---continues and ending at
tcp        0      0 master_ip:60994    volume_ip:8080     ESTABLISHED
tcp        0      0 master_ip:60996    volume_ip:8080     ESTABLISHED
tcp        0      0 master_ip:60998    volume_ip:8080     ESTABLISHED
tcp6       0      0 :::8080                 :::*                    LISTEN  
```

Just for your information. Which Library we were using it use hackney pool to upload and download files,

At first, we had set the timeout for that HTTP request hackney pool to 10 seconds and max connection to 5K

and as you know we are running all master and volume with default idleTimeout values 10 , so they were on the same line. But after consulting few leads, I set the max connections to 1000 and timeout to 5 seconds. 

Also just to tell you:  Without a pool, Http request library will close the TCP connection after a request finishes. When using a pool, it keeps the connection until it reaches the timeout.

**Comment by chrislusf** [comment]
thanks for the update!

**Comment by ijunaid8088** [comment]
Actually, that didn't solve the problem yet. :)

My question was:

Having timeout to 5 seconds in our HTTP request and 10 seconds in seaweedFS volumes.. is that fine? 

Also, you see the connections, Is that fine to have that much of connection?
