### ISSUE TITLE
Filer /admin/mv is not atomic

### ISSUE THREAD

**Issue by stepanbujnak** [chrislusf/seaweedfs#468]
I have 1 file in filer, let's call it `hello`. When I request `/admin/mv?from=hello&to=hello.1` in one thread and `/admin/mv&from=hello&to=hello.2` in another thread, there are now two possible outcomes:

1. one of the requests returns `200 OK` and the other returns `500 Internal Server Error`
2. both requests return `200 OK` and I end up with both `hello.1` and `hello.2` files

Would it be possible to make it so that only one of the requests with succeed and the other one will always fail? Also it should fail with more sensible status code, like `409 Conflict`.

**Comment by chrislusf** [comment]
Can you help to put a lock here? https://github.com/chrislusf/seaweedfs/blob/master/weed/filer/embedded_filer/filer_embedded.go#L123

Should be simple even if you are new to Go.
