### ISSUE TITLE
Deleting a collection prevents future insertions into collection of the same name

### ISSUE THREAD

**Issue by 4scastro** [chrislusf/seaweedfs#476]
I've noticed that if I write some image data to a collection, delete that collection, and then attempt to write image data again to a collection of the same name the second insertion fails. This is probably better explained by the commands that I'm running and the output that I'm receiving.

So starting with a clean slate I first insert some image data into a collection:

`curl -X POST http://localhost:9333/dir/assign?collection=data`
`{"fid":"6,01b7f306cd","url":"localhost:8080","publicUrl":"localhost:8080","count":1}`
`curl -X PUT -F file=@test.jpg http://127.0.0.1:8080/6,01b7f306cd`
`{"name":"test.jpg","size":758811}`

So far so good. I am also able to successfully delete the collection:

`curl -X POST http://localhost:8080/admin/delete_collection?collection=data`
`{"error":""}`

Then I repeat the attempt to insert the same image data into a collection of the same name:

`curl -X POST http://localhost:9333/dir/assign?collection=data`
`{"fid":"1,024fc8edca","url":"localhost:8080","publicUrl":"localhost:8080","count":1}`
`curl -X PUT -F file=@test.jpg http://127.0.0.1:8080/1,024fc8edca`

However this time I get an error message as a response:

`{"name":"test.jpg","error":"Failed to write to local disk (Volume 1 not found!)"}`

My first instinct was that I had done something catastrophically wrong; however, I am able to write data to collections of different names as usual, so it would seem it is just writing data to a previously deleted collection which is the problem. To me this indicates a bug, then again I have only been using seaweed for a day, so it may be that I'm misunderstanding the intention of collections (please tell me if this is the case!).

Cheers,
Simon

**Comment by chrislusf** [comment]
You are deleting from the volume server. Try to delete from the master server.

**Comment by 4scastro** [comment]
Hi Chris,

Thanks for the quick reply. If I delete from the master server then I get a "404 page not found message". The command I ran was:

`curl -X POST http://localhost:9333/admin/delete_collection?collection=data`

**Comment by chrislusf** [comment]
curl http://localhost:9333/col/delete?collection=data

But I think you showed a bug here after SeaweedFS switched to gRPC. The deleted volumes are not reported back to the master server now. Need to fix it in a proper way.

**Comment by 4scastro** [comment]
Late reply here, but that command works perfectly. thank you!
