### ISSUE TITLE
WebP resize support

### ISSUE THREAD

**Issue by vitalybaev** [chrislusf/seaweedfs#478]
WebP image format grows very fast on the web, It will be cool to support resizing for that.
I could take look deeper and open a Pull Request for this.

**Comment by chrislusf** [comment]
Thanks!

**Comment by chrislusf** [comment]
Hi, sorry I need to pull out webp support due to "go test" failures and build failures on windows.

See https://github.com/chai2010/webp/issues/9

Not sure how to solve this.

**Comment by vitalybaev** [comment]
@chrislusf Sure, I'll look at the possible fixes for this in the future.

**Comment by chrislusf** [comment]
It seems there are no pure-go webp encoder/decoder still.
