### ISSUE TITLE
Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by azharmalik3** [chrislusf/seaweedfs#479]
Hi,

we are using seaweedFS to save our images and mp4 video file. Now, we are planning to save HLS files on seaweedFS. Everything is perfect, HLS files are now saving on seaweedFS but when we try to use HLS URL in HTML5 video player it gives following warnings:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at
http://{seaweedFS-URL}/gpocam/timelapses/testt-ymgqr/index.m3u8. (Reason: CORS header 'Access-Control-Allow-Origin' missing).
```

When I used the same URL in VLC then it works but not worked in the browser's player. Can anyone point the problem here?

**Comment by chrislusf** [comment]
browser policy problem. not directly related to seaweedfs. closing.
