### ISSUE TITLE
Master and volume can't find each other

### ISSUE THREAD

**Issue by gheibia** [chrislusf/seaweedfs#481]
I start the master this way:

    weed -log_dir=/var/data/logs master -mdir=/var/data/weedData/master

And volume:

    weed -log_dir=/var/data/logs volume -mserver=dns_entry_name:9333 -dir=/var/data/weedData/volume

`dns_entry_name` is simply a DNS entry name that resolves to the IP address of the server on which master is running.

I'm seeing the following lines in the volume's log:

    I0411 01:44:48     1 store.go:35] Resetting master nodes: nodes:[localhost:9333 dns_entry_name:9333], leader:
    I0411 01:44:48     1 volume_grpc_client.go:48] &{0xc4200e0600}.SendHeartbeat(_) = _, rpc error: code = Unavailable desc = grpc: the connection is unavailable
    I0411 01:44:48     1 volume_grpc_client.go:25] heartbeat error: rpc error: code = Unavailable desc = grpc: the connection is unavailable

I can  verify using `nslookup` that the name does indeed resolves the IP. Is there something I should be doing differently?

**Comment by chrislusf** [comment]
seems you have or had another master running on localhost:9333

Kill the master instances, clean up /var/data/weedData/master, and then start your commands.

**Comment by gheibia** [comment]
I did that. The issue persists.

**Comment by chrislusf** [comment]
Need to see new log outputs

**Comment by gheibia** [comment]
Dropped the folders.

    $ sudo rm -rf *
    $ mkdir master
    $ mkdir volume
    $ ls -lR .
    .:
    total 8
    drwxr-xr-x    2 docker   docker        4096 Apr 11 16:43 master
    drwxr-xr-x    2 docker   docker        4096 Apr 11 16:43 volume

    ./master:
    total 0

    ./volume:
    total 0

Master's log:

    Log file created at: 2017/04/11 16:44:35
    Running on machine: weedmasterdeployment-3833302323-8sps1
    Binary: Built with gc go1.7.3 for linux/amd64
    Log line format: [IWEF]mmdd hh:mm:ss threadid file:line] msg
    I0411 16:44:35     1 file_util.go:20] Folder /var/data/weedData/master Permission: -rwxr-xr-x
    I0411 16:44:35     1 master_server.go:62] Volume Size Limit is 30000 MB
    I0411 16:44:35     1 master.go:87] Start Seaweed Master 0.74 at 0.0.0.0:9333
    I0411 16:44:35     1 raft_server.go:56] Peers Change: [] => []
    I0411 16:44:35     1 raft_server.go:98] Initializing new cluster
    I0411 16:44:35     1 master_server.go:95] [ localhost:9333 ] I am the leader!


Volume's log:

    Log file created at: 2017/04/11 16:46:22
    Running on machine: weedvolumedeployment-3446514637-5pfcw
    Binary: Built with gc go1.7.3 for linux/amd64
    Log line format: [IWEF]mmdd hh:mm:ss threadid file:line] msg
    I0411 16:46:22     1 file_util.go:20] Folder /var/data/weedData/volume Permission: -rwxr-xr-x
    I0411 16:46:22     1 disk_location.go:106] Store started on dir: /var/data/weedData/volume with 0 volumes max 7
    I0411 16:46:22     1 volume.go:141] Start Seaweed volume server 0.74 at 0.0.0.0:8080
    I0411 16:46:22     1 volume_grpc_client.go:17] Volume server bootstraps with master weedmasterdeployment_server:9333
    I0411 16:46:22     1 volume_grpc_client.go:48] &{0xc4200c4180}.SendHeartbeat(_) = _, rpc error: code = Unavailable desc = grpc: the connection is unavailable
    I0411 16:46:22     1 volume_grpc_client.go:25] heartbeat error: rpc error: code = Unavailable desc = grpc: the connection is unavailable

Both machines (VMs) have unique DNS entries. For instance, here is the dig result for the master server's name that volume server says it can't find.

    dig +vc -p 5300 @127.0.0.1 weedmasterdeployment_server

    ; <<>> DiG 9.10.3-P4-Ubuntu <<>> +vc -p 5300 @127.0.0.1 weedmasterdeployment_server
    ; (1 server found)
    ;; global options: +cmd
    ;; Got answer:
    ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 1376
    ;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

    ;; QUESTION SECTION:
    ;weedmasterdeployment_server.	IN A

    ;; ANSWER SECTION:
    weedmasterdeployment_server.	30 IN A	10.0.0.54

    ;; Query time: 42 msec
    ;; SERVER: 127.0.0.1#5300(127.0.0.1)
    ;; WHEN: Tue Apr 11 09:55:42 PDT 2017
    ;; MSG SIZE  rcvd: 80

**Comment by chrislusf** [comment]
You can print out the value of mn.leader. This is the URL to use when connecting to the master. Other than that, there are no more magic to connect to the master.

https://github.com/chrislusf/seaweedfs/blob/bfd2739fcee72d46f87de2d15455fc285dd9ecd7/weed/storage/store.go#L64

**Comment by chrislusf** [comment]
I think you can try
 weed master -ip=dns_entry_name ...

**Comment by gheibia** [comment]
Will do and update later. Thanks for your help.

**Comment by gheibia** [comment]
yea, that does the trick, but I wonder why. I thought the "mserver" flag in volume is basically the way for volume to register itself with master.

**Comment by chrislusf** [comment]
Master needs to know itself ip since there could be multiple master
instances.

**Comment by gheibia** [comment]
But in this case the "ip" setting in master is helping volume to find it, not other master. That's the puzzling piece to me. I mean if the volume needs to find a master, it could simply provide its IP or name, couldn't it?

**Comment by chrislusf** [comment]
The volume server uses the master address in the command line as a seed to
find all the masters.

Chris
