### ISSUE TITLE
backup CRC error! Data On Disk Corrupted

### ISSUE THREAD

**Issue by 316014408** [chrislusf/seaweedfs#483]
root@247:~/backup# ./weed backup -server=192.168.122.241:8333 -dir=./ -volumeId=3
I0421 09:09:11  3899 volume_loading.go:69] volumeDataIntegrityChecking failed verifyNeedleIntegrity 3.idx failed: CRC error! Data On Disk Corrupted
I0421 09:09:11  3899 volume_loading.go:73] loading index file 3.idx readonly true
I0421 09:09:11  3899 volume_sync.go:131] Fetch needle {21 4349 17370} from 192.168.122.244:9080: Appending volume 3 error: 3.dat is read-only
I0421 09:09:11  3899 volume_sync.go:131] Fetch needle {21 4349 17370} from 192.168.122.244:9080: Appending volume 3 error: 3.dat is read-only
I0421 09:09:11  3899 volume_sync.go:131] Fetch needle {21 4349 17370} from 192.168.122.244:9080: Appending volume 3 error: 3.dat is read-only
Error synchronizing volume 3: Appending volume 3 error: 3.dat is read-only

**Comment by chrislusf** [comment]
Just copy the volume. The backup command has problem.

Related to:
https://github.com/chrislusf/seaweedfs/issues/421

**Comment by chrislusf** [comment]
"3.dat is read-only"
