### ISSUE TITLE
Could not see any directories and files when use Distributed Filer mode.

### ISSUE THREAD

**Issue by gaoyang-projects** [chrislusf/seaweedfs#484]
i start Distributed Filer Service use command like this :
`
weed -log_dir=/var/logs/filer filer -master="192.168.x.x:9333" -redis.server="192.168.x.x:6379" -redis.database=10 -defaultReplicaPlacement="001"
`

when i put some file to directory
curl -F "filename=@Makefile" "http://localhost:8888/path/to/sources/new_name"

filer service could not list any directories,  then redis data
`
127.0.0.1:6379[10]> keys *
 1) "/path/to/sources/new_name"
 2) "..."
`

when i use standlone mode and try again, it's work . can list directories and files . it is any problem here ? 

something mismatch with wiki

1. restfull api add `pretty=true` does not work  should add request header "accept=application/json".
1. lastest version is "0.75" but `weed --version` show  "version 0.74 linux amd64"

**Comment by chrislusf** [comment]
Is this using the redis pull request?

**Comment by gaoyang-projects** [comment]
Sorry, i do not know redis pull request  .

distributed filer mode server response ：
`
{
  "Path": "/path/",
  "Files": null,
  "Directories": null,
  "Limit": 100,
  "LastFileName": "",
  "ShouldDisplayLoadMore": false
}
`
standlone filer mode server response ：
`
{
  "Path": "/path/",
  "Files": null,
  "Directories": [
    {
      "Name": "to",
      "Id": 2
    }
  ],
  "Limit": 100,
  "LastFileName": "",
  "ShouldDisplayLoadMore": false
}
`

**Comment by chrislusf** [comment]
dir listing is not supported.

The PR https://github.com/chrislusf/seaweedfs/pull/254 is trying to address this. But not tested yet.

**Comment by gaoyang-projects** [comment]
123
