### ISSUE TITLE
Are we losing a volume server for sometime.??

### ISSUE THREAD

**Issue by ijunaid8989** [chrislusf/seaweedfs#485]
Hello, All..

As we are using Seaweed for a couple of years and its working good, the almost heart of our system, Totally dependent on that. Thanks for such a nice file system.

From few days we are having a little trouble with our one volume server, As we have 1 master and 3 volume servers at the moment and we have added ping monitoring to all our servers and master servers.

On master server for port 8888. and for others, we are doing the ping at port 8080. as on that port, we can see the volume server status and statistics. 
All of a sudden our one volume starting giving error on port 8080 as 
```
State is now:   ERROR    (07:23h 2017.04.29)
State before:   ERROR    (was about 8 hours)
Service params: type=tcp port=8080
Service uptime: 99.98%
Check output:
```

Will you please guide us that what could be the issue in this? Are we under the threat of losing one volume server? Or we are not doing ping in right way? Should it be on port 8080 for volume server? 

NOTE : whenever we got this email, we always check the `9333/ui/index.html` page and even the volume server for which we get the email is also listed there and also we can see the statistics on `8080/ui/index.html`..

**Comment by chrislusf** [comment]
what's your "ping monitoring" and how does it determine the state is ERROR or not?
