### ISSUE TITLE
garbage collection failed

### ISSUE THREAD

**Issue by alohaking** [chrislusf/seaweedfs#486]
I just start a master and a volume server on windows.

```
./weed master

./weed volume -dir=./data
```

and I upload a zip file

```
curl -X POST http://localhost:9333/dir/assign

curl -X PUT -F file=@/xx/src.zip http://127.0.0.1:8080/1,010387ae54
```
then delete the zip file for garbage collection testing

```
curl -X DELETE http://127.0.0.1:8080/1,010387ae54
curl http://localhost:9333/vol/vacuum
```

get the error message

```
I0504 17:24:45 51396 volume_vacuum.go:38] Committing vacuuming...
I0504 17:24:48 51396 volume.go:63] Failed to read file size data/1.dat GetFileType data/1.dat: use of closed file or network connection
```

so, I do something wrong?

**Comment by chrislusf** [comment]
I can not reproduce. Maybe you are using an older version?

chris$ weed upload unison.log
[{"fileName":"unison.log","fileUrl":"localhost:8080/4,01083c8a97","fid":"4,01083c8a97","size":435355}]
chris$ curl -X DELETE http://localhost:8080/4,01083c8a97
{"size":435377}
chris$ curl http://localhost:9333/vol/vacuum
{"Topology":{"DataCenters":[{"Free":0,"Id":"DefaultDataCenter","Max":7,"Racks":[{"DataNodes":[{"Free":0,"Max":7,"PublicUrl":"localhost:8080","Url":"localhost:8080","Volumes":7}],"Free":0,"Id":"DefaultRack","Max":7}]}],"Free":0,"Max":7,"layouts":[{"collection":"","replication":"000","ttl":"","writables":[1,2,3,5,6,7,4]}]},"Version":"0.74"}

**Comment by chrislusf** [comment]
this is the server side output

I0527 17:41:31 46807 volume_server_handlers_read.go:71] read error: Not Found /4,01083c8a97
I0527 17:41:31 46807 volume_server_handlers_read.go:71] read error: Not Found /4,01083c8a97
I0527 17:42:03 46807 master_server_handlers_admin.go:44] garbageThreshold = 0.3
I0527 17:42:03 46807 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0527 17:42:03 46807 topology_vacuum.go:99] check vacuum on collection: volume:4
I0527 17:42:03 46807 volume_layout.go:203] Volume 4 becomes unwritable
I0527 17:42:03 46807 topology_vacuum.go:45] 0 Start vacuuming 4 on localhost:8080
I0527 17:42:03 46807 topology_vacuum.go:50] 0 Complete vacuuming 4 on localhost:8080
I0527 17:42:03 46807 topology_vacuum.go:69] Start Commiting vacuum 4 on localhost:8080
I0527 17:42:03 46807 volume_vacuum.go:38] Committing vacuuming...
I0527 17:42:03 46807 volume_loading.go:88] loading index 4.idx to btree readonly false
I0527 17:42:03 46807 topology_vacuum.go:74] Complete Commiting vacuum 4 on localhost:8080
I0527 17:42:03 46807 volume_layout.go:215] Volume 4 becomes writable
I0527 17:42:03 46807 topology_vacuum.go:99] check vacuum on collection: volume:5
I0527 17:42:03 46807 topology_vacuum.go:99] check vacuum on collection: volume:6
I0527 17:42:03 46807 topology_vacuum.go:99] check vacuum on collection: volume:7
I0527 17:42:03 46807 topology_vacuum.go:99] check vacuum on collection: volume:1
I0527 17:42:03 46807 topology_vacuum.go:99] check vacuum on collection: volume:2
I0527 17:42:03 46807 topology_vacuum.go:99] check vacuum on collection: volume:3
