### ISSUE TITLE
how to set replication policy from 000 to 001 on working server?

### ISSUE THREAD

**Issue by ralphdc** [chrislusf/seaweedfs#488]
./weed server -ip 192.168.88.49 -master.port=9333 -dir=/var/www/weedfs -volume.port=8180 -master.peers=192.168.88.47:9333 ....
because I am a new hand, and not familiar with seaweed, default replication "000" has been used.
The problem is we decide to set replication policy from "000" to "001", but many pictures have been uploaded into seaweed under "000".

who can tell me how to resolve it ?

**Comment by chrislusf** [comment]
Use this tool to fix it manually.

https://github.com/chrislusf/seaweedfs/blob/master/unmaintained/change_superblock/change_superblock.go

**Comment by ralphdc** [comment]
Hello, Please tell me how to use this tool?
do I have to install go-lang environment?

**Comment by chrislusf** [comment]
yes. someone with basic Go knowledge can help you.
