### ISSUE TITLE
How to make a volume server readOnly by using HTTP api. 

### ISSUE THREAD

**Issue by yanyiwu** [chrislusf/seaweedfs#49]
How to make a volume server readOnly by using HTTP api. 
When the disk of VolumeServer's machine is lack of space, how to stop MasterServer assigning fid to that VolumeServer.

**Comment by chrislusf** [comment]
Currently no API to change a server to be readOnly.

If it is to fix an actual issue, one quick way is to reduce each volume size on master by running "weed master -volumeSizeLimitMB=xxx" to a smaller number.

**Comment by shel3over** [comment]
if you are using something like a reverse proxy to expose the API to the outside, you can just do some restrictions on the reproxy configuration

**Comment by fedotxxl** [comment]
+1 to implement it

**Comment by chrislusf** [comment]
There are a set of commands to manage the volumes now via `weed shell`. This operation may not be needed any more.

```
  volume.balance                	# balance all volumes among volume servers
  volume.copy                   	# copy a volume from one volume server to another volume server
  volume.delete                 	# delete a live volume from one volume server
  volume.fix.replication        	# add replicas to volumes that are missing replicas
  volume.list                   	# list all volumes
  volume.mount                  	# mount a volume from one volume server
  volume.move                   	# <experimental> move a live volume from one volume server to another volume server
  volume.unmount                	# unmount a volume from one volume server
```
