### ISSUE TITLE
create new volumes evenly

### ISSUE THREAD

**Issue by ingardm** [chrislusf/seaweedfs#492]
Hi
I've configured a new cluster with 1 master and 4 volume nodes. Each volum node has 4x datadirs.
When I started the cluster it automatically created 6 volume files spread on random nodes/datadirs. We've copied quite a lot of data to this cluster for testing purposes and atm the datadir with the highest number of volumefiles has 41 volumes, and lowest number is 24. Why is it so unevenly spread? 

For instance the following shows 6 new volumes (with replica) being created with 4, 3, 3, 2 volume files on the 4 nodes:

`I0512 20:09:00 23820 volume_layout.go:197] Volume 238 becomes unwritable
I0512 20:09:00 23820 volume_layout.go:197] Volume 237 becomes unwritable
I0512 20:09:00 23820 volume_layout.go:197] Volume 235 becomes unwritable
I0512 20:09:01 23820 volume_layout.go:197] Volume 240 becomes unwritable
I0512 20:09:01 23820 volume_layout.go:197] Volume 236 becomes unwritable
I0512 20:09:02 23820 volume_layout.go:197] Volume 239 becomes unwritable
I0512 20:09:02 23820 volume_growth.go:205] Created Volume 241 on topo:DefaultDataCenter:DefaultRack:10.1.14.23:8082
I0512 20:09:02 23820 volume_growth.go:205] Created Volume 241 on topo:DefaultDataCenter:DefaultRack:10.1.14.24:8083
I0512 20:09:02 23820 volume_growth.go:205] Created Volume 242 on topo:DefaultDataCenter:DefaultRack:10.1.14.24:8083
I0512 20:09:02 23820 volume_growth.go:205] Created Volume 242 on topo:DefaultDataCenter:DefaultRack:10.1.14.23:8082
I0512 20:09:02 23820 volume_growth.go:205] Created Volume 243 on topo:DefaultDataCenter:DefaultRack:10.1.14.27:8081
I0512 20:09:02 23820 volume_growth.go:205] Created Volume 243 on topo:DefaultDataCenter:DefaultRack:10.1.14.22:8083
I0512 20:09:02 23820 volume_growth.go:205] Created Volume 244 on topo:DefaultDataCenter:DefaultRack:10.1.14.24:8083
I0512 20:09:02 23820 volume_growth.go:205] Created Volume 244 on topo:DefaultDataCenter:DefaultRack:10.1.14.22:8080
I0512 20:09:02 23820 volume_growth.go:205] Created Volume 245 on topo:DefaultDataCenter:DefaultRack:10.1.14.23:8080
I0512 20:09:02 23820 volume_growth.go:205] Created Volume 245 on topo:DefaultDataCenter:DefaultRack:10.1.14.27:8083
I0512 20:09:02 23820 volume_growth.go:205] Created Volume 246 on topo:DefaultDataCenter:DefaultRack:10.1.14.27:8081
I0512 20:09:02 23820 volume_growth.go:205] Created Volume 246 on topo:DefaultDataCenter:DefaultRack:10.1.14.27:8080`

**Comment by chrislusf** [comment]
you can pre-allocate volumes https://github.com/chrislusf/seaweedfs/wiki/Master-Server-API#pre-allocate-volumes

**Comment by chrislusf** [comment]
the volumes are randomly created based on how empty the volume server is.

**Comment by ingardm** [comment]
@chrislusf That doesnt make sense when we saw smallest and highest number of volumes being 24 and 41 volumes?
