### ISSUE TITLE
Both volumes with 1 replica created on same host

### ISSUE THREAD

**Issue by ingardm** [chrislusf/seaweedfs#495]
Hi
I think it has previously been suggested that its better to run one volume server per datadir, than one server with multiple dirs. However I've seen that some times both volumes in a replica set gets added to the same physical server (but on different volume servers):
I0518 12:58:09 10152 volume_growth.go:205] Created Volume 1435 on topo:DefaultDataCenter:DefaultRack:10.1.14.27:8081
I0518 12:58:09 10152 volume_growth.go:205] Created Volume 1435 on topo:DefaultDataCenter:DefaultRack:10.1.14.27:8083

Is there a way to avoid this?

**Comment by chrislusf** [comment]
you can treat one machine as one "rack" with many different volume servers.

**Comment by ingardm** [comment]
@chrislusf yeah that would be one way of getting around the problem. But we are planning on using multiple racks so I'd rather not misuse that functionality for something internal to one server.
