### ISSUE TITLE
File Entry Not Found. Needle 174568 Memory 0 /83362,01028f3fae53f5a66e

### ISSUE THREAD

**Issue by ijunaid8989** [chrislusf/seaweedfs#496]
I just found an error in my seaweed volume server logs

volume_server_handlers_read.go:69] read error: File Entry Not Found. Needle 174568 Memory 0 /83362,01028f3fae53f5a66e

Can you tell what is this related to?

**Comment by chrislusf** [comment]
The file is deleted.
