### ISSUE TITLE
no vacuuming of older (non-writable) volumes

### ISSUE THREAD

**Issue by ingardm** [chrislusf/seaweedfs#497]
Hi
As far as I can tell the system does not vacuum volumes that have been filled up and thus are no longer writable. I've seen that I can call admin/vacuum/check|vacuum|commit?volume=xyz directly on the volume servers, but I'd like this to happen automatically. Would it not make more sense to do the automatic vacuuming of the volumes that are not writable instead of only running it for the writable ones?

**Comment by chrislusf** [comment]
There is a vacuum threshold when master starts.

**Comment by ingardm** [comment]
Can you elaborate please?

**Comment by ingardm** [comment]
I'm aware of the garbageThreshold. In my testing we've uploaded 30TB ish. Then deleted lots of files, even deleted all the files from some of the older volumes. But it is still not automatically compacted. From the code it seems it only selects which volumes to compact from the writable ones? The older full volumes even if 100% is marked as deleted is still not writable and therefore never compacted either.

**Comment by chrislusf** [comment]
related to https://github.com/chrislusf/seaweedfs/issues/405

**Comment by ingardm** [comment]
The fix works as intended

**Comment by lucifer-wsp** [comment]
Hi
I still catching the problem of no vacuuming for older volumes.
And i use the 0.74 version.
Would you help me ?

**Comment by chrislusf** [comment]
Yes.

**Comment by lucifer-wsp** [comment]
sorry, i saw that the problem had been repaired in 0.76 version.
Thx !
