### ISSUE TITLE
Excessive memory usage

### ISSUE THREAD

**Issue by nvx** [chrislusf/seaweedfs#498]
With ~9 million files across 21 volumes using leveldb, the volume server when started up without any .ldb directories consumes ~8gb of ram which seems a tad higher than expected (basing on the sub-200MB for 1.5 million files in the Optimisation page of the wiki gives under 1.2GB for 9 million files), but if restarted it balloons out to more than 16gb ram consumed and the system runs out of ram.

The number of files stored has been increasing over time, but I don't recall it ever requiring this much ram in the past.

Is there any sort of corruption that might lead to this sort of issue? And if so, how can it be detected and fixed?

**Comment by nvx** [comment]
Interestingly, starting without -index=leveldb, it only consumes ~3.6gb. I did try removing the *.ldb directories to allow it to recreate assuming they might have been corrupt, but it only helped the first startup hit 8gb, while subsequent hit over 16gb before running the system out of ram.

**Comment by nvx** [comment]
I use custom file ids, but they are in roughly increasing order (they correspond to a sql counter, but insertion into weed happens later, and not necessarily in the same order as they are inserted into the sql table). I note there is a caveat about keeping it roughly in order for the memory data structure to be efficient. Would this affect leveldb? And if so, could it to the extent mentioned here?

**Comment by chrislusf** [comment]
Custom Id matters. If possible, upload or send the .idx file to analyze
further.

**Comment by nvx** [comment]
What is the preferred way of sending the files? There are 21 idx files, ~150mb all up. Strangely the files all seem to be either 4.6MB or 7.3MB. Guessing they're allocated in chunks or something?

**Comment by chrislusf** [comment]
Any way to share files is fine. Dropbox, Google drive, etc.

**Comment by ingardm** [comment]
We're also seeing high mem usage for all volume servers. We're not using leveldb though. For instance a volume server with 617 volumes uses virt=15.5G res=8.7G. Number of files spread across the 617 volumes is around 70 million. Each volume has around 100k - 130k each.

**Comment by nvx** [comment]
That's actually not that bad considering you've got an order of magnitude more files stored, and yet you're still in the same order of magnitude of ram usage. (I'm only looking at res ram usage, virt is likely misleading in this case).

**Comment by nvx** [comment]
I've compressed all the idx files and uploaded them to Google Drive: https://drive.google.com/file/d/0Bz4ZtL56Bas2M0RLSHFzUEpTZnM/view?usp=sharing

You might have to request access.

**Comment by ingardm** [comment]
@nvx its still a lot more than the 16bytes per file that is said to be the mem usage on the wiki

**Comment by nvx** [comment]
Sure, but to store the map in memory to efficiently look it up there's definitely overheads.

The Memory Consumption section of https://github.com/chrislusf/seaweedfs/wiki/Optimization gives some examples.

That page mentions for ~1.5 million files, not using leveldb or boltdb it used ~400mb of RAM. Scale that up to 70 million and that's almost 19gb. Of course some of the overheads are fixed, which would explain why you're using less, but it's definitely in the realms of "about right". Using leveldb or boltdb would reduce this though.

My issue I'm seeing higher memory usage with leveldb than the standard in-memory index, which should definitely not be the case.

**Comment by ingardm** [comment]
To test the memory consumption, the leveldb or boltdb index are created. There are 7 volumes in benchmark collection, each with about 1553K files. The server is restarted, then I start the benchmark tool to read lots of files. For leveldb, server memory starts at 142,884KB, and stays at 179,340KB. For boltdb, server memory starts at 73,756KB, and stays at 144,564KB. For in-memory, server memory starts at 368,152KB, and stays at 448,032KB.

**Comment by ingardm** [comment]
@nvx It says 7x 1.5mil equals ~400M

**Comment by nvx** [comment]
Hmm I missed the "7 volumes" bit and was assuming it was 1.5 million total.  That said, those numbers don't really pass the sniff test, 7*1.5 million * 16 bytes == 164,062KiB, which is more memory than boltdb is using. Seems too good to be true? Although if that's the actual numbers we can expect in normal operation that's amazing and whatever I've done horribly wrong is even worse than I initially thought!

I must admit I didn't notice the memory consumption at all really during the first ~4-5 million records, so maybe it is legit?

**Comment by ingardm** [comment]
We haven't tracked it either tbh. We'll redo our testing next week and nuke all volumes. Unless it's interesting for @chrislusf to see the data from the current amount of data?

**Comment by ingardm** [comment]
@nvx we can try with leveldb first as well for comparison. If I read the docs correctly it will create the leveldb upon restart with the correct options? @chrislusf is it ok to run one or a few volume servers with leveldb while the rest uses ram or would I need to restart all of them?

**Comment by nvx** [comment]
That's correct. It gets stored with the volume files, it makes a directory called <volume>.ldb for each volume.

**Comment by ingardm** [comment]
@chrislusf Would it be of any interest with a heap dump to help track this?

**Comment by ingardm** [comment]
```(pprof) top
7879.06MB of 7917.32MB total (99.52%)
Dropped 311 nodes (cum <= 39.59MB)
Showing top 10 nodes out of 33 (cum >= 7849.60MB)
      flat  flat%   sum%        cum   cum%
 3016.78MB 38.10% 38.10%  6054.56MB 76.47%  github.com/chrislusf/seaweedfs/weed/storage.(*CompactMap).Set
 2762.05MB 34.89% 72.99%  2762.05MB 34.89%  runtime.hashGrow
 1851.18MB 23.38% 96.37%  1851.18MB 23.38%  github.com/chrislusf/seaweedfs/weed/util.newByteChunkPool.func1
  249.05MB  3.15% 99.52%  3037.27MB 38.36%  runtime.mapassign
         0     0% 99.52%    66.22MB  0.84%  github.com/chrislusf/seaweedfs/weed/server.(*VolumeServer).(github.com/chrislusf/seaweedfs/weed/server.privateStoreHandler)-fm
         0     0% 99.52%    66.22MB  0.84%  github.com/chrislusf/seaweedfs/weed/server.(*VolumeServer).PostHandler
         0     0% 99.52%    66.22MB  0.84%  github.com/chrislusf/seaweedfs/weed/server.(*VolumeServer).PostHandler-fm
         0     0% 99.52%    66.22MB  0.84%  github.com/chrislusf/seaweedfs/weed/server.(*VolumeServer).privateStoreHandler
         0     0% 99.52%  3037.27MB 38.36%  github.com/chrislusf/seaweedfs/weed/storage.(*CompactSection).Set
         0     0% 99.52%  7849.60MB 99.14%  github.com/chrislusf/seaweedfs/weed/storage.(*DiskLocation).concurrentLoadingVolumes.func2```

**Comment by ingardm** [comment]
Another observation: After seeing mem usage of 8-9G (res) while we were writing heavily to the cluster, I'm now seeing the same volume servers running with 2-3G res mem when they're not written to. So it seems the bulk of the mem used is related to heavy writing (perhaps in combination with having lots of volumes/files?)

**Comment by chrislusf** [comment]
@nvx Thanks for your for customized file ids, please use the new "btree" mode which is just committed.

**Comment by nvx** [comment]
Neat I'm down to 580MB resident now.

To satisfy my curiosity though, what caused the issue with the file ids I'm using? Is inserting out of order? (ie if I started fresh and reinserted strictly sequentially with the same IDs would the issue have not occurred). Or is it the gaps in IDs (I don't think there would actually be that many gaps as a % of total numbers anyway, but I'm sure there's some)?

When not using custom IDs, does the file id always increase even across volumes? Or on a new volume does the file id start at 1 again? (If the latter, was that the cause)?

Might be worth documenting the sort of usecase that would cause this issue with the other index types, and that btree should be used in those cases, because it definitely seems to have done the trick for me.

Are there any downsides to using btree for other workloads too?

As far as this issue is concerned though, I'm happy to close it off if this is the accepted solution for the custom IDs I'm using.

**Comment by chrislusf** [comment]
The default assumption is that the file id always increase monotonically, and the data structure takes advantages of this.

The new btree mode is for custom id, which does not always increase monotonically.
