### ISSUE TITLE
WeedFS requires Bash to run

### ISSUE THREAD

**Issue by DaAwesomeP** [chrislusf/seaweedfs#500]
I was trying to start SeaweedFS via a systemd service like this:
```
[Unit]
Description=SeaweedFS
After=network.target

[Service]
Type=simple
ExecStart=/usr/bin/weed server -master.port=9333 -volume.port=9433 -dir="/var/webapp_fs/data/"
WorkingDirectory=/var/webapp_fs
User=webapp_fs
Group=webapp_fs

[Install]
WantedBy=multi-user.target
```
But starting it would result in an error:
```
F0515 15:10:44  1237 server.go:148] Check Data Folder(-dir) Writable "/var/webapp_fs/data/" : stat "/var/webapp_fs/data/": no such file or directory
```
But when I run it with bash, it works fine:
```
ExecStart=/bin/bash -c "/usr/bin/weed server -master.port=9333 -volume.port=9433 -dir=\"/var/webapp_fs/data/\""
```
Why do I need to use Bash (or any shell, but I didn't test that) to run SeaweedFS? Is there an environment variable missing?

**Comment by ijunaid8989** [comment]
Are you on ubuntu 14.04?

**Comment by DaAwesomeP** [comment]
Debian 8
systemd 215
Kernel 3.16.0-4-amd64

**Comment by ijunaid8989** [comment]
Can you run an upstart job? instead of systemd? I usually don't fancy systemd

**Comment by ijunaid8989** [comment]
while looking at your script, 

while starting the weed directly you are using `\"/var/webapp_fs/data/\""` may this is the difference? 

Why do I need a bash or shell: Usually you want your weed daemon to run smooth and also keep it running so you do need it, The main reason for creating Unit jobs or upstarts is to maintaining your programs to run with some logs and also stop start it on system level, even if your whole system rebooted again.

**Comment by DaAwesomeP** [comment]
> Can you run an upstart job? instead of systemd? I usually don't fancy systemd

I'm not really familiar with Upstart, and I believe that Systemd is intended to replace Upstart on mondern Debian systems.

>while starting the weed directly you are using \"/var/webapp_fs/data/\"" may this is the difference?

When starting weed directly from the command line I used `/usr/bin/weed server -master.port=9333 -volume.port=9433 -dir="/var/webapp_fs/data/"`. I escaped the quotes in there because that is inside the `bash -c` quotes. I don't think that that is the issue, as it works with the Bash version.

> Why do I need a bash or shell: Usually you want your weed daemon to run smooth and also keep it running so you do need it, The main reason for creating Unit jobs or upstarts is to maintaining your programs to run with some logs and also stop start it on system level, even if your whole system rebooted again.

How does the bash or shell help it to run smoothly? Yes, I am aware of why I would run weed as a service. I will use it for automatic restarts, starting when the system does, and logging.

**Comment by frol** [comment]
Well, you have a syntax error in your SystemD command:

```
ExecStart=/usr/bin/weed server -master.port=9333 -volume.port=9433 -dir="/var/webapp_fs/data/"
```

Since it is running without any shell, it passes the quotes directly to the `/usr/bin/weed` args, thus, it translates to (roughly):

```
execve("/usr/bin/weed server", "-master.port=9333", "-volume.port=9433", "-dir=\"/var/webapp_fs/data/\"")
```

and weed tries to open `"/var/webapp_fs/data/"` file (with quotes!) and fails.

Drop the quotes or use them around the whole argument (like `"-dir=/var/webapp_fs/data/"`): https://stackoverflow.com/a/31503633/1178806

**Comment by chrislusf** [comment]
Does this mean this post is wrong?

https://www.howtoforge.com/how-to-install-and-configure-seaweedfs-cluster-on-ubuntu-2004/
