### ISSUE TITLE
How to structure for public/private content

### ISSUE THREAD

**Issue by DaAwesomeP** [chrislusf/seaweedfs#501]
My webapp will have two categories of images served: public and private. I plan to route the publicly-accessible images directly to an Nginx reverse proxy. The private images will go through a NodeJS reverse proxy to check for authentication.

I was planning on using Filer and having two directories of images with UUID files names that match my PostgreSQL database. However, I noticed that Filer allows you to move folders but not files. Should I create a folder for each file? Would this be efficient? I don't want to use up disk space or system resources any more than I would have to otherwise. Will I have to garbage collect more often? I'm kind of worried about the speed of Filer and moving around files/directories.

I want to be absolutely sure that the user-only content remains that way. Yes, I could just let weed determine file IDs as it normally does, but then I run the risk of someone guessing or incrementing numbers until they find all of the private images.

**Comment by chrislusf** [comment]
seems you do not need filer for private images.

the file id has a randomized cookie to guard against guessing numbers.

**Comment by DaAwesomeP** [comment]
@chrislusf Then let's just say that I'm paranoid. What would be the recommended method to store the files if I need to authenticate some of them?

**Comment by ijunaid8989** [comment]
@DaAwesomeP The most better solution is to just make your weed master secured for a specific IP request, and Then Let handle your own NodeJS for public and Private requests.

But this should be a medium. You are only showing AJAX calls not what is going around but you need to ceate few endpoints to handle your cause.
