### ISSUE TITLE
Backing up master filer and all volumes

### ISSUE THREAD

**Issue by ijunaid8989** [chrislusf/seaweedfs#502]
Hello, Chris. 

First of all thanks for this awesome tool. It's heart of our whole system. 

As you know we have 1 master and 3 volumes servers running and we have planned to backup everything, on GDrive. I am uploading all volumes to Drive. starting from Master Volume. 

Question: On Master Filer there many other folders too as filer and snapshot, etc, But I am only backing up the volume files (.dat) only. is this Okay? Someday when we will download these .dat files and start master volume with that, with filer true. then Everything will work fine? or you suggest something else?

**Comment by chrislusf** [comment]
1) .dat files are enough for volume servers. but preferably also .idx files.
2) master servers do not need anything.
3) filer server need the filer database file

**Comment by ijunaid8989** [comment]
Thanks for the answer Chris.
The folder where we have started weed server, there are

ida and idx files..
and
```
1302.dat  1608.dat  1913.dat  2241.dat  38.dat     695.dat  9.dat
1302.idx  1608.idx  1913.idx  2241.idx  38.idx     695.idx  9.idx
1303.dat  1609.dat  1914.dat  2242.dat  390.dat    696.dat  backup
1303.idx  1609.idx  1914.idx  2242.idx  390.idx    696.idx  conf
1304.dat  160.dat   1915.dat  2244.dat  391.dat    697.dat  config.json
1304.idx  160.idx   1915.idx  2244.idx  391.idx    697.idx  filer
1305.dat  1610.dat  1916.dat  2245.dat  392.dat    698.dat  log
1305.idx  1610.idx  1916.idx  2245.idx  392.idx    698.idx  snapshot
```

and filer folder
```
065665.ldb  114753.ldb   160692.ldb   210512.ldb  262976.ldb  LOCK
065666.ldb  114754.ldb   160693.ldb   210513.ldb  262977.ldb  LOG
065667.ldb  114755.ldb   160694.ldb   210542.ldb  263002.ldb  LOG.old
065668.ldb  1147707.ldb  160715.ldb   210543.ldb  263003.ldb  MANIFEST-157424
```
So I was asking there is backup, conf, config.json, filer and log, snapshot folder here..
and in filer folder there is lock , log, log.old, Manifest file. Now can you tell me what to backup? 
I am backing up `.dat` files, (I will backup idx as well). but filer db file ? These all seems to be filer db files.

**Comment by chrislusf** [comment]
the whole filer folder should be replicated.
