### ISSUE TITLE
low writing performance than v0.75 when running benchmark

### ISSUE THREAD

**Issue by Adesun** [chrislusf/seaweedfs#504]
server  win2012 64bit   192.168.8.2
client  win8.1 64bit 192.168.8.1
network speed 1G

**same machine same config just different exe version.** 
starting one master and two volumes on host 192.168.8.2, two volumes locate on different harddriver. starting benchmark on host 192.168.8.1.
weed benchmark -server="192.168.8.2:9555" -c 16 -n 512000 

**1. server 0.76 && client 0.76**

------------ Writing Benchmark ----------
Concurrency Level:      16
Time taken for tests:   70.038 seconds
Complete requests:      512000
Failed requests:        0
Total transferred:      540447154 bytes
Requests per second:    7310.32 [#/sec]
Transfer rate:          7535.63 [Kbytes/sec]

Connection Times (ms)
              min      avg        max      std
Total:        0.0      2.2       678.0      6.0

Percentage of the requests served within a certain time (ms)
   50%      2.0 ms
   80%      2.9 ms
   90%      3.0 ms
   95%      4.0 ms
   99%      5.0 ms
  100%    678.0 ms

------------ Randomly Reading Benchmark ----------
Concurrency Level:      16
Time taken for tests:   22.895 seconds
Complete requests:      512000
Failed requests:        0
Total transferred:      540457279 bytes
Requests per second:    22362.66 [#/sec]
Transfer rate:          23052.33 [Kbytes/sec]

Connection Times (ms)
              min      avg        max      std
Total:        0.0      0.7       20.0      0.5

Percentage of the requests served within a certain time (ms)
   50%      0.9 ms
   66%      1.0 ms
   98%      1.9 ms
   99%      2.0 ms
  100%     20.0 ms

**2. server 0.75 && client 0.75**

------------ Writing Benchmark ----------

Concurrency Level:      16
Time taken for tests:   63.422 seconds
Complete requests:      512000
Failed requests:        0
Total transferred:      540413168 bytes
Requests per second:    8072.96 [#/sec]
Transfer rate:          8321.25 [Kbytes/sec]

Connection Times (ms)
              min      avg        max      std
Total:        0.0      1.9       287.0      3.1

Percentage of the requests served within a certain time (ms)
   50%      1.9 ms
   66%      2.0 ms
   90%      3.0 ms
   98%      4.0 ms
   99%      4.9 ms
  100%    287.0 ms

------------ Randomly Reading Benchmark ----------

Concurrency Level:      16
Time taken for tests:   22.751 seconds
Complete requests:      512000
Failed requests:        0
Total transferred:      540430216 bytes
Requests per second:    22504.21 [#/sec]
Transfer rate:          23197.08 [Kbytes/sec]

Connection Times (ms)
              min      avg        max      std
Total:        0.0      0.7       17.0      0.5

Percentage of the requests served within a certain time (ms)
   50%      0.9 ms
   66%      1.0 ms
   98%      1.9 ms
   99%      2.0 ms
  100%     17.0 ms

**Comment by ijunaid8989** [comment]
Thats nice.

**Comment by chrislusf** [comment]
no change related to write performance at all.

**Comment by Adesun** [comment]
seems weird !  overall, it's a little slower than v0.75 after tested dozens of times.

**Comment by chrislusf** [comment]
No actionable items.
