### ISSUE TITLE
high memory usage during write

### ISSUE THREAD

**Issue by ingardm** [chrislusf/seaweedfs#505]
Hi
We're seeing quite high mem usage when we write files to the cluster. I've included two screen grabs from our monitoring. The process idles with 5ish GB resident mem, and climbes quite fast to 10ish when we start writing files to it. I think the drops are when this volume server doesnt receive any writes, but I'm not sure about that. As I'm writing this this volume server has 893 volumes. Please let me know if I can provide more logs / index files etc to help track this. The version I'm running does have pprof included as well so I can provide heap/thread/etc stats as well. I put some comments in this issue https://github.com/chrislusf/seaweedfs/issues/498 as well regarding the same situation.

![screen shot 2017-05-29 at 23 29 45](https://cloud.githubusercontent.com/assets/2324855/26562544/4daebbd0-44c7-11e7-8876-874e4811a69a.png)
![screen shot 2017-05-29 at 23 29 34](https://cloud.githubusercontent.com/assets/2324855/26562545/4db9640e-44c7-11e7-959f-cd504069909d.png)

**Comment by chrislusf** [comment]
what is the expected behavior? what's the write and read throughput? you do not need to pre-allocate all the volumes. A couple for each hard drive should be good enough.

**Comment by ingardm** [comment]
@chrislusf We didn't preallocate all those volumes. They've been automatically added by the system as we've uploaded more data. The expected behaviour would be that the volume server process does not use as much ram? It climbes steadily when data is being written to it. Which means for more data you'd need more memory, but I cant really understand why having written more data to disk should use more and more memory?
![screen shot 2017-06-01 at 19 25 18](https://cloud.githubusercontent.com/assets/2324855/26692201/1980615c-4700-11e7-9b00-e96e2287ec7c.png)

**Comment by ingardm** [comment]
@chrislusf the write throughput has been roughly 30TB during the time where you can see the memory graph increasing. 30T divided on 12 volume servers with 1x replication. So roughly 5T of data will hit each of them if the load is spread evenly. There are no reads on this system. We're still in testing phase

**Comment by chrislusf** [comment]
By throughput, I mean how many files per second, how large are the files.

**Comment by ingardm** [comment]
139454096 files totalling roughly 30T over roughly 30 hours so on avg roughly 1300 files/s

**Comment by ingardm** [comment]
That makes it out to be 230K on avg. I dont have the exact distribution on this dataset, but for a similar dataset there was roughly 30% of the files below 20K

**Comment by chrislusf** [comment]
5GB memory is expected to hold 140M files, or 280M files since it is replicated.

all files are read into memory and then persist to disk. With 1300 files/second, check whether some of these files are too big.

**Comment by ingardm** [comment]
@chrislusf I deleted all volumes and started testing with the benchmark tool:
weed benchmark -size=204800 -read=false  -c=48 -n=104857600

Concurrency Level:      48
Time taken for tests:   18416.747 seconds
Complete requests:      104857598
Failed requests:        2
Total transferred:      21478139181144 bytes
Requests per second:    5693.60 [#/sec]
Transfer rate:          1138895.20 [Kbytes/sec]

Connection Times (ms)
              min      avg        max      std
Total:        3.0      8.4       760.1      2.9
![screen shot 2017-06-02 at 07 45 49](https://cloud.githubusercontent.com/assets/2324855/26712542/9c746ff6-4767-11e7-8cef-f25bc79a7e1b.png)

The graph shows the same steady increase in memory consumption up to 4148M and then after the benchmark stops it drops to 2212M.

**Comment by ingardm** [comment]
@chrislusf I've run the same test mentioned above 4 times now. During the course of the test the memory consumption rises semi steadily, sometimes in chunks, but a little while after the writes stop the memory drops off (the volume servers are idle at this point). So you can see the same happening in all four runs. Each run pushing ~5500reqs/sec and 104857597 files total. (maxing out the 10gig interface).

I'm wondering how many of the index files are loaded into memory at any given time? Whats causing the volume server to drop almost half its res mem when the writes stop?

![screen shot 2017-06-03 at 18 00 44](https://cloud.githubusercontent.com/assets/2324855/26755094/a671252e-4886-11e7-839b-b2d6e826c18d.png)

**Comment by chrislusf** [comment]
This is expected.

All index file content are loaded into memory, at any point of time.

When the write stops, the memory holding the incoming files are released.

**Comment by ingardm** [comment]
@chrislusf how do you explain the choppy jump in memory usage for the second run then? It seems from the graph as there might be something else at play?

**Comment by chrislusf** [comment]
can you try this branch to see whether removing caching can help?

https://github.com/chrislusf/seaweedfs/tree/skip_memory_pool

**Comment by ingardm** [comment]
@chrislusf seems to be pretty much the same with that branch
![screen shot 2017-06-05 at 21 36 17](https://cloud.githubusercontent.com/assets/2324855/26799780/2ddf5fd8-4a37-11e7-9746-3577f14cdbfd.png)

**Comment by chrislusf** [comment]
Thanks for testing! There isn't anything taking much memory then except needles in memory.
