### ISSUE TITLE
VolumeId not found

### ISSUE THREAD

**Issue by azharmalik3** [chrislusf/seaweedfs#506]
I want to delete a directory which contains images. When I send delete request using `recursive=true` with seaweed URL it gives following error in response

```
{body: "{\"error\":\"volumeId not found.\\nvolumeId not found.\\nvolumeId not found.\\nvolumeId not found.\\nvolumeId not found.\\nvolumeId not found.\"}"}
```

I don't know why it gives this error only for some directories otherwise it works.

**Comment by chrislusf** [comment]
seems the specific volume does not exist or the volume server containing the volume is not connected to the master.

**Comment by chrislusf** [comment]
Need details.

**Comment by ijunaid8989** [comment]
@chrislusf Can you specify please, what details you need ?

**Comment by chrislusf** [comment]
Anything to reproduce the test case.
