### ISSUE TITLE
How to recover old files from old volume servers's copy to one new volume server

### ISSUE THREAD

**Issue by gaokunbuaa** [chrislusf/seaweedfs#509]
Hi:
Assuming I have three volume servers in one rack and I configure replica as 001, which means we have one copy for each file. If one volume server is down and I start up one brand new volume server to replace it; 
At this condition, is that possible to recover the backup status for those old files, that means still make each file has one copy

thanks a lot.

**Comment by chrislusf** [comment]
Just copy the data files that's missing the copy.

**Comment by gaokunbuaa** [comment]
But, I mean if the disk is broken

**Comment by chrislusf** [comment]
copy from other 2 servers.

**Comment by gaokunbuaa** [comment]
多谢！
