### ISSUE TITLE
Any new features?

### ISSUE THREAD

**Issue by Superman132** [chrislusf/seaweedfs#510]
Just curious, Is this project finished or more features are planned? Maybe a tutorial on how to deploy with kubernetes? Anyways, keep up the great work.

P. S. I love this project, one of my favorites :)

**Comment by chrislusf** [comment]
Some todos:
1. reed solomon encoding
2. better management tools
3. a local client as a reverse proxy to the system

Not enough time yet.

**Comment by Superman132** [comment]
Okay cool, thanks

**Comment by beeing** [comment]
For item 1, can refer to [minio](https://github.com/minio/minio) which is developed on Go and implements similar coding. Perhaps this can speed up the effort.
