### ISSUE TITLE
Can I remove the TTL from a file?

### ISSUE THREAD

**Issue by CheyenneForbes** [chrislusf/seaweedfs#511]
**Use case:**

When a user uploads an image for a blog post I want the file to have a TTL of 1 hour. If the user cancels the post, the image will be deleted but if the user posts the blog the TTL will be removed from the file.

**If that isn't possible:**
Can I copy a file via HTTP? For example using a link like this:
`http://127.0.0.1:8080/5,01637037d6?from=3,01637037d6`

**Comment by chrislusf** [comment]
This is more like a convenience tool. It's better not to include this feature.

**Comment by CheyenneForbes** [comment]
which do you refer to in the previous comment? removing a TTL or copying?

**Comment by chrislusf** [comment]
copying.
Removing ttl is not supported.

**Comment by CheyenneForbes** [comment]
do you have any plans to support removing TTL?

**Use case**
Photo is uploaded for preview when a user is commenting with a photo, if the user submits the comment the TTL is removed but if for any reason the comment wasnt submitted the image will be removed automatically after the TTL

**Comment by chrislusf** [comment]
No plan to support this.
