### ISSUE TITLE
多master模式不工作

### ISSUE THREAD

**Issue by gaokunbuaa** [chrislusf/seaweedfs#512]
Hi Chris Lu:
发现多master模式下，停掉leader后，剩下的master没能选出leader，从而volume server连接master失败；

版本：0.76
环境：一台windows，ip为10.0.0.95，一台centos，IP为10.0.0.163
步骤：
1.windows上启动master
weed master -mdir=master -ip=10.0.0.95 ip.bind=10.0.0.95
2.centos上启动另一个master
weed master -mdir=master -peers=10.0.0.95:9333 -ip=10.0.0.163 ip.bind=10.0.0.163
3.window上启动一个volume server
weed.exe volume -dir=data -port="8081" -mserver=10.0.0.95:9333 -ip=10.0.0.95 ip.bind=10.0.0.95

启动成功后，上传一个文件1.jpg
http://10.0.0.163:9333/submit
通过http://10.0.0.95:9333/和http://10.0.0.163:9333/均能正常访问文件

4. 停掉leader 95，仍然通过http://10.0.0.163:9333/submit上传文件，返回失败：
{
    "error": "Raft Server not initialized!"
}

# **95上master的log如下：**
weed master -mdir=master -ip=10.0.0.95 ip.bind=10.0.0.95
I0615 17:27:50  5980 file_util.go:20] Folder master Permission: -rwxrwxrwx
I0615 17:27:50  5980 master_server.go:62] Volume Size Limit is 30000 MB
I0615 17:27:50  5980 master.go:87] Start Seaweed Master 0.76 at 0.0.0.0:9333
I0615 17:27:50  5980 raft_server.go:56] Peers Change: [10.0.0.163:9333 10.0.0.95:9333] => []
I0615 17:27:50  5980 raft_server.go:98] Initializing new cluster
I0615 17:27:50  5980 master_server.go:95] [ 10.0.0.95:9333 ] I am the leader!
I0615 17:27:55  5980 raft_server_handlers.go:16] Processing incoming join. Current Leader 10.0.0.95:9333 Self 10.0.0.95:9333 Peers map[]
I0615 17:27:55  5980 raft_server_handlers.go:20] Command:{"name":"10.0.0.163:9333","connectionString":"http://10.0.0.163:9333"}
I0615 17:27:55  5980 raft_server_handlers.go:27] join command from Name 10.0.0.163:9333 Connection http://10.0.0.163:9333
I0615 17:28:08  5980 node.go:223] topo adds child DefaultDataCenter
I0615 17:28:08  5980 node.go:223] topo:DefaultDataCenter adds child DefaultRack
I0615 17:28:08  5980 node.go:223] topo:DefaultDataCenter:DefaultRack adds child 10.0.0.95:8081
I0615 17:28:08  5980 master_grpc_server.go:36] added volume server 10.0.0.95:8081

# **95上的volume log如下：**
weed.exe volume -dir=data -port="8081" -mserver=10.0.0.95:9333 -ip=10.0.0.95 ip.bind=10.0.0.95
I0615 17:28:08 10076 file_util.go:20] Folder data Permission: -rwxrwxrwx
I0615 17:28:08 10076 volume_loading.go:73] loading index data/6.idx to memory readonly false
I0615 17:28:08 10076 volume_loading.go:73] loading index data/1.idx to memory readonly false
I0615 17:28:08 10076 volume_loading.go:73] loading index data/5.idx to memory readonly false
I0615 17:28:08 10076 volume_loading.go:73] loading index data/4.idx to memory readonly false
I0615 17:28:08 10076 volume_loading.go:73] loading index data/2.idx to memory readonly false
I0615 17:28:08 10076 disk_location.go:56] data file data/6.dat, replicaPlacement=000 v=2 size=8 ttl=
I0615 17:28:08 10076 volume_loading.go:73] loading index data/7.idx to memory readonly false
I0615 17:28:08 10076 disk_location.go:56] data file data/7.dat, replicaPlacement=000 v=2 size=8 ttl=
I0615 17:28:08 10076 disk_location.go:56] data file data/2.dat, replicaPlacement=000 v=2 size=639800 ttl=
I0615 17:28:08 10076 disk_location.go:56] data file data/1.dat, replicaPlacement=000 v=2 size=8 ttl=
I0615 17:28:08 10076 disk_location.go:56] data file data/5.dat, replicaPlacement=000 v=2 size=8 ttl=
I0615 17:28:08 10076 disk_location.go:56] data file data/4.dat, replicaPlacement=000 v=2 size=8 ttl=
I0615 17:28:08 10076 volume_loading.go:73] loading index data/3.idx to memory readonly false
I0615 17:28:08 10076 disk_location.go:56] data file data/3.dat, replicaPlacement=000 v=2 size=8 ttl=
I0615 17:28:08 10076 disk_location.go:106] Store started on dir: data with 7 volumes max 7
I0615 17:28:08 10076 volume.go:143] Start Seaweed volume server 0.76 at 0.0.0.0:8081
I0615 17:28:08 10076 volume_grpc_client.go:17] Volume server bootstraps with master 10.0.0.95:9333
I0615 17:28:08 10076 volume_grpc_client.go:52] Heartbeat to 10.0.0.95:9333
2017/06/15 17:29:14 transport: http2Client.notifyError got notified that the client transport was broken read tcp 10.0.0.95:12367->10.0.0.95:9333: wsarecv: An existing connection was forcibly closed by the remote host..
I0615 17:29:14 10076 volume_grpc_client.go:95] Volume Server heart beat stops with rpc error: code = Internal desc = transport is closing
I0615 17:29:14 10076 volume_grpc_client.go:25] heartbeat error: rpc error: code = Internal desc = transport is closing 2017/06/15 17:29:14 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp 10.0.0.95:9333: operation was canceled"; Reconnecting to {10.0.0.95:9333 <nil>}
2017/06/15 17:29:14 grpc: addrConn.transportMonitor exits due to: grpc: the connection is closing
I0615 17:29:19 10076 store.go:35] Resetting master nodes: nodes:[10.0.0.163:9333 10.0.0.95:9333 10.0.0.95:9333], leader:
I0615 17:29:21 10076 volume_grpc_client.go:25] heartbeat error: No master found: No master node available!
I0615 17:29:28 10076 volume_grpc_client.go:25] heartbeat error: No master found: No master node available!
I0615 17:29:35 10076 volume_grpc_client.go:25] heartbeat error: No master found: No master node available!
I0615 17:29:42 10076 volume_grpc_client.go:25] heartbeat error: No master found: No master node available!
I0615 17:29:49 10076 volume_grpc_client.go:25] heartbeat error: No master found: No master node available!
I0615 17:29:56 10076 volume_grpc_client.go:25] heartbeat error: No master found: No master node available!
I0615 17:30:03 10076 volume_grpc_client.go:25] heartbeat error: No master found: No master node available!
I0615 17:30:10 10076 volume_grpc_client.go:25] heartbeat error: No master found: No master node available!
I0615 17:30:17 10076 volume_grpc_client.go:25] heartbeat error: No master found: No master node available!
I0615 17:30:24 10076 volume_grpc_client.go:25] heartbeat error: No master found: No master node available!
I0615 17:30:31 10076 volume_grpc_client.go:25] heartbeat error: No master found: No master node available!
I0615 17:30:38 10076 volume_grpc_client.go:25] heartbeat error: No master found: No master node available!
I0615 17:30:45 10076 volume_grpc_client.go:25] heartbeat error: No master found: No master node available!
I0615 17:30:52 10076 volume_grpc_client.go:25] heartbeat error: No master found: No master node available!
I0615 17:30:59 10076 volume_grpc_client.go:25] heartbeat error: No master found: No master node available!

# **163上的master log如下**
weed master -mdir=master -peers=10.0.0.95:9333 -ip=10.0.0.163 ip.bind=10.0.0.163
I0615 17:28:01  9904 file_util.go:20] Folder master Permission: -rwxrwxr-x
I0615 17:28:01  9904 master_server.go:62] Volume Size Limit is 30000 MB
I0615 17:28:01  9904 master.go:87] Start Seaweed Master 0.76 at 0.0.0.0:9333
I0615 17:28:01  9904 raft_server.go:56] Peers Change: [10.0.0.163:9333 10.0.0.95:9333] => [10.0.0.95:9333]
I0615 17:28:01  9904 raft_server.go:78] Joining cluster: 10.0.0.95:9333
I0615 17:28:02  9904 raft_server.go:166] Attempting to connect to: http://10.0.0.95:9333/cluster/join
I0615 17:28:02  9904 raft_server.go:211] Post returned status:  200

**Comment by gaokunbuaa** [comment]
仿照https://github.com/chrislusf/seaweedfs/wiki/Failover-Master-Server中的Startup multiple master servers部分启动多master，貌似启动第三个master时报错

## **weed master -port=9333 -mdir=./1**
I0615 17:41:35 10113 file_util.go:20] Folder ./1 Permission: -rwxrwxr-x
I0615 17:41:35 10113 master_server.go:62] Volume Size Limit is 30000 MB
I0615 17:41:35 10113 master.go:87] Start Seaweed Master 0.76 at 0.0.0.0:9333
I0615 17:41:35 10113 raft_server.go:56] Peers Change: [] => []
I0615 17:41:35 10113 raft_server.go:98] Initializing new cluster
I0615 17:41:35 10113 master_server.go:95] [ localhost:9333 ] I am the leader!
I0615 17:41:47 10113 raft_server_handlers.go:16] Processing incoming join. Current Leader localhost:9333 Self localhost:9333 Peers map[]
I0615 17:41:47 10113 raft_server_handlers.go:20] Command:{"name":"localhost:9334","connectionString":"http://localhost:9334"}
I0615 17:41:47 10113 raft_server_handlers.go:27] join command from Name localhost:9334 Connection http://localhost:9334


## **weed master -port=9334 -mdir=./2 -peers=localhost:9333**
I0615 17:41:46 10127 file_util.go:20] Folder ./2 Permission: -rwxrwxr-x
I0615 17:41:46 10127 master_server.go:62] Volume Size Limit is 30000 MB
I0615 17:41:46 10127 master.go:87] Start Seaweed Master 0.76 at 0.0.0.0:9334
I0615 17:41:46 10127 raft_server.go:56] Peers Change: [] => [localhost:9333]
I0615 17:41:46 10127 raft_server.go:78] Joining cluster: localhost:9333
I0615 17:41:47 10127 raft_server.go:166] Attempting to connect to: http://localhost:9333/cluster/join
I0615 17:41:47 10127 raft_server.go:211] Post returned status:  200 
I0615 17:42:00 10127 raft_server_handlers.go:16] Processing incoming join. Current Leader localhost:9333 Self localhost:9334 Peers map[localhost:9333:0xc420240d20]
I0615 17:42:00 10127 raft_server_handlers.go:20] Command:{"name":"localhost:9335","connectionString":"http://localhost:9335"}
I0615 17:42:00 10127 raft_server_handlers.go:27] join command from Name localhost:9335 Connection http://localhost:9335
I0615 17:42:00 10127 raft_server_handlers.go:47] Redirecting to 301 http://localhost:9333/cluster/join



## **weed master -port=9335 -mdir=./3 -peers=localhost:9334**
I0615 17:41:59 10133 file_util.go:20] Folder ./3 Permission: -rwxrwxr-x
I0615 17:41:59 10133 master_server.go:62] Volume Size Limit is 30000 MB
I0615 17:41:59 10133 master.go:87] Start Seaweed Master 0.76 at 0.0.0.0:9335
I0615 17:41:59 10133 raft_server.go:56] Peers Change: [] => [localhost:9334]
I0615 17:41:59 10133 raft_server.go:78] Joining cluster: localhost:9334
I0615 17:42:00 10133 raft_server.go:166] Attempting to connect to: http://localhost:9334/cluster/join
I0615 17:42:00 10133 raft_server.go:211] Post returned status:  404 404 page not found

I0615 17:42:00 10133 raft_server.go:171] Post returned error:  404 page not found

I0615 17:42:00 10133 raft_server.go:82] No existing server found. Starting as leader in the new cluster.
I0615 17:42:00 10133 master_server.go:95] [ localhost:9335 ] I am the leader!

**Comment by chrislusf** [comment]
You need odd number of masters.
