### ISSUE TITLE
[question]Can seaweedfs scan files according filename?

### ISSUE THREAD

**Issue by jinleileiking** [chrislusf/seaweedfs#513]
My files are:

```
aaa/bbb/ccc/999.ts
aaa/bbb/ccc/100000.ts
aaa/bbb/ccc/100005.ts
aaa/bbb/ccc/100011.ts
```

Is there any way like cmd `ls aaa/bbb/ccc/[100000~100011].ts` to get
```
aaa/bbb/ccc/100000.ts
aaa/bbb/ccc/100005.ts
aaa/bbb/ccc/100011.ts
```

**Comment by chrislusf** [comment]
I assume you are using filer.

Listing files under a folder is very efficient. Pattern matching can be done on the client side.

**Comment by ijunaid8989** [comment]
@jinleileiking for what purpose are you using this? 

Instead of doing cmd commands, it's better to make an API service call, to get those files.

**Comment by jinleileiking** [comment]
@ijunaid8989 I didnot find the api. I will check apis :)

**Comment by ijunaid8989** [comment]
@jinleileiking Thats good but I was asking your use case, maybe I can help, what are you building? in which language are you building?

**Comment by jinleileiking** [comment]
@ijunaid8989 I will put some ts files to seaweedfs. I need to scan all the ts in a period of time, just as the issue. I did not find some apis or other doc to get a list of files with reg. Can you give a clue? Thanks.

**Comment by jinleileiking** [comment]
I am using golang

**Comment by jinleileiking** [comment]
I can save the file metadata in hbase. But it is awful.

**Comment by jinleileiking** [comment]
> I assume you are using filer.
> Listing files under a folder is very efficient. Pattern matching can be done on the client side.

@chrislusf Any Pattern matching examples?
