### ISSUE TITLE
[feature]put several files in one cmd

### ISSUE THREAD

**Issue by jinleileiking** [chrislusf/seaweedfs#515]
just like redis api mget,mset , put several files in one api like 'mput'
 reduce network cost

**Comment by ijunaid8989** [comment]
Its very nice that you are using this tool and exploring it.. but it would be very useful, if you will post issue with more suitable information.. e.g what you tried, what were the errors... etc..

**Comment by jinleileiking** [comment]
updated

**Comment by chrislusf** [comment]
add your use case here. Do you want to combine writes to master, volume server, or filer server?

**Comment by chrislusf** [comment]
need to understand what the use case is trying to optimize for.
