### ISSUE TITLE
Is there any way to let volume readonly automatic？

### ISSUE THREAD

**Issue by sincerefly** [chrislusf/seaweedfs#517]
I use three computer, one master, others let it store data(A and B)

I get fid from master, and put file to volumes, now, I testing if A disk is full, the master also distribute the A's fid, and store file to A, visit the file, it's damaged.

Is there a way that weed know disk full, and no distribute A's fid, only distribute B?

Or If I write a script and crontab it, checking disk is going to full or not, what command can let volume become readonly

Thank

**Comment by ijunaid8989** [comment]
https://github.com/chrislusf/seaweedfs/issues/405

**Comment by ijunaid8989** [comment]
Anyhow if we could have this feature, Life would be so easy.

**Comment by sincerefly** [comment]
@ijunaid8989 Thank you, I change the dat file to 444 and restart the system, It's become readonly

Yes, If weed can auto do this, It must be Exciting : )

**Comment by ijunaid8989** [comment]
@sincerefly You are welcome..

Out of interest what are you building? and are you really using 3 computers physically?

**Comment by sincerefly** [comment]
@ijunaid8989 I am testing it, maybe my company‘s software will use it store file, and I use virtualbox install fedora simulation three computer not physically computer
