### ISSUE TITLE
weed export encounter panic: runtime error

### ISSUE THREAD

**Issue by chenzhuoli** [chrislusf/seaweedfs#519]
When I execute the export command, and encounter a panic runtime error below. Thanks for your attention.
**./weed  export -dir=/home/dell/data/weedfs/volume00 -volumeId=6 -o=v6.tar -fileNameFormat="{{.Key}}-{{.Name}}"**
**panic: runtime error: invalid memory address or nil pointer dereference**
[signal 0xb code=0x1 addr=0x0 pc=0x58c0dc]

goroutine 1 [running]:
panic(0xc7b4a0, 0xc82000e0d0)
	/opt/dist/go-1.6/src/runtime/panic.go:464 +0x3e6
github.com/chrislusf/seaweedfs/weed/storage.(*Volume).readSuperBlock(0xc820150100, 0x7f1a9ef98028, 0xc82000e1e0)
	/Users/tanyanlong/Documents/git/src/github.com/chrislusf/seaweedfs/weed/storage/volume_super_block.go:64 +0x8c
github.com/chrislusf/seaweedfs/weed/storage.(*Volume).load(0xc820150100, 0xc820150000, 0x0, 0x0, 0x0)
	/Users/tanyanlong/Documents/git/src/github.com/chrislusf/seaweedfs/weed/storage/volume_loading.go:50 +0x549
github.com/chrislusf/seaweedfs/weed/storage.loadVolumeWithoutIndex(0x7fff1d3b3844, 0x1f, 0x0, 0x0, 0xc800000006, 0x0, 0xc820150100, 0x0, 0x0)
	/Users/tanyanlong/Documents/git/src/github.com/chrislusf/seaweedfs/weed/storage/volume_loading.go:15 +0xd1
github.com/chrislusf/seaweedfs/weed/storage.ScanVolumeFile(0x7fff1d3b3844, 0x1f, 0x0, 0x0, 0xc800000006, 0x0, 0xc8201c1b70, 0x11fd601, 0xc8201c1c88, 0x0, ...)
	/Users/tanyanlong/Documents/git/src/github.com/chrislusf/seaweedfs/weed/storage/volume_read_write.go:180 +0xae
github.com/chrislusf/seaweedfs/weed/command.runExport(0x11f4120, 0xc82000a0e0, 0x0, 0x0, 0x0)
	/Users/tanyanlong/Documents/git/src/github.com/chrislusf/seaweedfs/weed/command/export.go:151 +0xf75
main.main()
	/Users/tanyanlong/Documents/git/src/github.com/chrislusf/seaweedfs/weed/weed.go:64 +0x68d
dell@ubuntu-face:~/face/weedfs/weedfs_0.71$ ./weed  export -dir=/home/dell/data/weedfs/volume00 -volumeId=6 -o=v6.tar -fileNameFormat="{{.Key}}-{{.Name}}"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x58c0dc]

goroutine 1 [running]:
panic(0xc7b4a0, 0xc82000e0d0)
	/opt/dist/go-1.6/src/runtime/panic.go:464 +0x3e6
github.com/chrislusf/seaweedfs/weed/storage.(*Volume).readSuperBlock(0xc820152000, 0x7f6f42e12028, 0xc82000e1e0)
	/Users/tanyanlong/Documents/git/src/github.com/chrislusf/seaweedfs/weed/storage/volume_super_block.go:64 +0x8c
github.com/chrislusf/seaweedfs/weed/storage.(*Volume).load(0xc820152000, 0xc820150000, 0x0, 0x0, 0x0)
	/Users/tanyanlong/Documents/git/src/github.com/chrislusf/seaweedfs/weed/storage/volume_loading.go:50 +0x549
github.com/chrislusf/seaweedfs/weed/storage.loadVolumeWithoutIndex(0x7ffc3815b821, 0x1f, 0x0, 0x0, 0xc800000006, 0x0, 0xc820152000, 0x0, 0x0)
	/Users/tanyanlong/Documents/git/src/github.com/chrislusf/seaweedfs/weed/storage/volume_loading.go:15 +0xd1
github.com/chrislusf/seaweedfs/weed/storage.ScanVolumeFile(0x7ffc3815b821, 0x1f, 0x0, 0x0, 0xc800000006, 0x0, 0xc8201bfb70, 0x11fd601, 0xc8201bfc88, 0x0, ...)
	/Users/tanyanlong/Documents/git/src/github.com/chrislusf/seaweedfs/weed/storage/volume_read_write.go:180 +0xae
github.com/chrislusf/seaweedfs/weed/command.runExport(0x11f4120, 0xc82000a170, 0x0, 0x0, 0x0)
	/Users/tanyanlong/Documents/git/src/github.com/chrislusf/seaweedfs/weed/command/export.go:151 +0xf75
main.main()
	/Users/tanyanlong/Documents/git/src/github.com/chrislusf/seaweedfs/weed/weed.go:64 +0x68d

**Comment by chenzhuoli** [comment]
export works ok now. thanks

**Comment by chrislusf** [comment]
what's fixed? what's the right command line options?
