### ISSUE TITLE
struct of file key

### ISSUE THREAD

**Issue by goodtogood** [chrislusf/seaweedfs#520]
I know it has three parts volume id, file id and file cookie. but what's the exact format of file key?  
for example 7,06600d5ead3144      7,066006f8e1da58
volume id is 7,  what about file id and file cookie?
thx

**Comment by chrislusf** [comment]
cookie is 5ead3144
file id is 06600d

cookie is fixed size, 32 bits.

**Comment by goodtogood** [comment]
if I use custom file key, is it needed the file id or cookie has the same size as the example above?

**Comment by chrislusf** [comment]
no limit to file id.

cookie should be fixed size, 32 bits.

**Comment by goodtogood** [comment]
got it . thx!
