### ISSUE TITLE
About some strange phenomenons on our application with seaweedfs

### ISSUE THREAD

**Issue by ralphdc** [chrislusf/seaweedfs#521]
Frankly, seaweedfs is a wonderful project on enormous quantities of picture storage, we have used this tool for a long time, during its working time, I find a question and want to get some help:
at first, I start seaweed as follows:

/usr/local/sunlight/weed server -ip 192.168.88.47 -master.port=9333  -dir=/var/www/weedfs -volume.port=8180** 

after it goes a long time, I use command just like "kill 16309" to stop weed process and use a new command line  to start:

/usr/local/sunlight/weed -log_dir=/var/log/weed/ server -ip 192.168.88.47 -master.port=9333 -master.defaultReplicaPlacement=001 -dir=/var/www/weedfs -volume.port=8180 -volume.max=10 -master.peers=192.168.88.49:9333,192.168.88.48:9333

some configure files that created by weed at first time does not be deleted(/var/www/weedfs), so they are still used, after it works a long time, when i check the weed process , it shows normally,
ps -ef|grep weed | grep -v grep
root     11600     1  0 18:47 pts/0    00:00:02 /usr/local/sunlight/weed -log_dir=/var/log/weed/ server -ip 192.168.88.47 -master.port=9333 -master.defaultReplicaPlacement=001 -dir=/var/www/weedfs -volume.port=8180 -volume.max=10 -master.peers=192.168.88.49:9333,192.168.88.48:9333

But, when check the cluster state,
curl 192.168.88.47:9333/dir/status?pretty=y

{
  "Topology": {
    "DataCenters": null,
    "Free": 0,
    "Max": 0,
    "layouts": null
  },
  "Version": "0.74"
}

All seadweedfs nodes are not shown, and seaweed does not service.

The log file content:
cat weed.linux-47.root.log.ERROR.20170623-164126.1953

Log file created at: 2017/06/23 16:41:26
Running on machine: linux-47
Binary: Built with gc devel +c1730ae Wed Jan 18 15:40:33 2017 +0000 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss threadid file:line] msg
F0623 16:41:26  1953 server.go:220] Master startup error: listen tcp 0.0.0.0:9333: bind: address already in use
goroutine 11 [running]:
github.com/chrislusf/seaweedfs/weed/glog.stacks(0xc42000e001, 0xc4202a4000, 0x459, 0x2710)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:767 +0xa7
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).output(0x104d2a0, 0xc400000003, 0xc420011130, 0xff3424, 0x9, 0xdc, 0x0)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:721 +0x1a3
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).printf(0x104d2a0, 0x3, 0xc82e10, 0x18, 0xc42004bf30, 0x1, 0x1)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:656 +0x14f
github.com/chrislusf/seaweedfs/weed/glog.Fatalf(0xc82e10, 0x18, 0xc42004bf30, 0x1, 0x1)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:1149 +0x67
github.com/chrislusf/seaweedfs/weed/command.runServer.func2(0xc4201844f0, 0xc420184500)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/command/server.go:220 +0x4ce
created by github.com/chrislusf/seaweedfs/weed/command.runServer
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/command/server.go:258 +0x80a

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc42018450c)
	/home/travis/.gimme/versions/go/src/runtime/sema.go:47 +0x34
sync.(*WaitGroup).Wait(0xc420184500)
	/home/travis/.gimme/versions/go/src/sync/waitgroup.go:131 +0x7a
github.com/chrislusf/seaweedfs/weed/command.runServer(0x10422e0, 0xc420010150, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/command/server.go:260 +0x81b
main.main()
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/weed.go:64 +0x3d2

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/home/travis/.gimme/versions/go/src/runtime/asm_amd64.s:2197 +0x1

goroutine 5 [runnable]:
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).flushDaemon(0x104d2a0)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:882
created by github.com/chrislusf/seaweedfs/weed/glog.init.1
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:410 +0x21d

goroutine 6 [runnable]:
text/template/parse.(*lexer).emit(0xc420060e00, 0x6)
	/home/travis/.gimme/versions/go/src/text/template/parse/lex.go:156 +0xd3
text/template/parse.lexText(0xc420060e00, 0xca7700)
	/home/travis/.gimme/versions/go/src/text/template/parse/lex.go:269 +0x1f2
text/template/parse.(*lexer).run(0xc420060e00)
	/home/travis/.gimme/versions/go/src/text/template/parse/lex.go:231 +0x58
created by text/template/parse.lex
	/home/travis/.gimme/versions/go/src/text/template/parse/lex.go:224 +0x16d

goroutine 9 [runnable]:
github.com/chrislusf/seaweedfs/weed/stats.(*ServerStats).Start(0xc42017c0c0)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/stats/stats.go:90
created by github.com/chrislusf/seaweedfs/weed/server.init.1
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/server/common.go:27 +0x5b

goroutine 10 [runnable]:
os/signal.loop()
	/home/travis/.gimme/versions/go/src/os/signal/signal_unix.go:20
created by os/signal.init.1
	/home/travis/.gimme/versions/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 12 [runnable]:
github.com/chrislusf/seaweedfs/weed/topology.(*Topology).StartRefreshWritableVolumes.func1(0xc420171450)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/topology/topology_event_handling.go:12
created by github.com/chrislusf/seaweedfs/weed/topology.(*Topology).StartRefreshWritableVolumes
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/topology/topology_event_handling.go:20 +0x43

goroutine 13 [runnable]:
github.com/chrislusf/seaweedfs/weed/topology.(*Topology).StartRefreshWritableVolumes.func2(0xc420171450, 0xc6ebde, 0x3)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/topology/topology_event_handling.go:21
created by github.com/chrislusf/seaweedfs/weed/topology.(*Topology).StartRefreshWritableVolumes
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/topology/topology_event_handling.go:28 +0x79

goroutine 14 [runnable]:
github.com/chrislusf/seaweedfs/weed/topology.(*Topology).StartRefreshWritableVolumes.func3(0xc420171450)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/topology/topology_event_handling.go:29
created by github.com/chrislusf/seaweedfs/weed/topology.(*Topology).StartRefreshWritableVolumes
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/topology/topology_event_handling.go:36 +0x9b

**Comment by chrislusf** [comment]
the error is

Master startup error: listen tcp 0.0.0.0:9333: bind: address already in use

try to make sure the port 9333 is not used
