### ISSUE TITLE
Recommendation to weed 18TB NTFS Volume

### ISSUE THREAD

**Issue by jawadatgithub** [chrislusf/seaweedfs#522]
Please Recommend weed config for single 18 TB NTFS volume:

```
OS: MS Windows 2012 R2
CPU: Xeon® Processor E5-2620 v3, 2.4 GHZ, 6 cores, 12 logical processors.
RAM: 32 GB
18 TB (Total Storage Size)
30 GB (weed volume Size)
18000/30=600 volumes
by default each volume-server max vols is 7

Data: Only Jpeg files.
Insertion Rate: 100 Images per second.
Each event consist of 2 Jpegs: 1st is thumbnail (1KB - 5KB), 2nd is the real Image (60KB - 100KB).
```

**My Question is How to divide/distribute  the 600 volumes of 30GB size among weed-volume-servers?**

Let me give two possible config Options to clarify further:

mkdir C:\weed\meta
C:\Tools\weed>weed master -mdir="C:\\weed\\meta"

**1st Option**: use 6 volume-servers, each of them handle 100 volumes of 30GB size.
```
mkdir C:\weed\volsA
C:\Tools\weed>weed volume -dir="C:\\weed\\volsA" -max=100  -mserver="localhost:9333" -port=8080
....
mkdir C:\weed\volsF
C:\Tools\weed>weed volume -dir="C:\\weed\\volsF" -max=100  -mserver="localhost:9333" -port=8085
```

**2nd Option**: use 60 volume-servers, each of them handle 10 volumes of 30GB size.
```
mkdir C:\weed\vols00
C:\Tools\weed>weed volume -dir="C:\\weed\\vols00" -max=10  -mserver="localhost:9333" -port=8000
....
mkdir C:\weed\vols59
C:\Tools\weed>weed volume -dir="C:\\weed\\vols59" -max=10  -mserver="localhost:9333" -port=8059
```

**In terms of performance and stability, which option is better? the 1st or the 2nd?**

**2nd Question: Is it good in term of performance to assign separate collection of thumbnails? and how the master divide the storage between collections? in other words, how to instruct weed-master to allocate 5% of storage to thumbs collection and 95% to pictures collection?**
```
Ex: 
http://localhost:9333/dir/assign?collection=thumbs
http://localhost:9333/dir/assign?collection=pictures
```

**Comment by chrislusf** [comment]
1. One volume server should be good enough. Maybe more volume servers can increase performance a bit(need to benchmark to test it), but I would prefer easier management myself.

2. No need. Collection is for easier purging.

**Comment by jawadatgithub** [comment]
Great, I have one more quick question:

The 18 TB will hold about 1 billion jpgs, and ttl is 1 year for each jpeg, **should I do manual purging** using:

`curl -X DELETE http://127.0.0.1:8080/3,01637037d6`

**Or should I relax and let ttl=1y handle that?**

```
http://localhost:9333/dir/assign?ttl=1y
curl -F "file=@x.go" http://127.0.0.1:8080/5,01637037d6?ttl=1y
```

**Comment by chrislusf** [comment]
relax

**Comment by jawadatgithub** [comment]
Awesome! we can close the issue now.

**Comment by ijunaid8989** [comment]
It already been closed :)
