### ISSUE TITLE
An old question that we always meet

### ISSUE THREAD

**Issue by ralphdc** [chrislusf/seaweedfs#526]
Now, we create 5000 clients  every second to visit our  php service, which uses  seaweedfs to store images.
Three DELL servers have constructed a perfect image service,
after one day test, We found seaweed state  down,
when seaweed works well for a period after its start,  It always breaks down, and we don't know the reason....

curl 127.0.0.1:9333/dir/status?pretty=y

{
  "Topology": {
    "DataCenters": null,
    "Free": 0,
    "Max": 0,
    "layouts": null
  },
  "Version": "0.74"
}

ps -ef|grep weed

root       2810      1  0 Jul03 ?        00:02:35 /usr/local/sunlight/weed -log_dir=/var/log/weed server -ip 192.168.89.211 -master.port=9333 -master.defaultReplicaPlacement=001 -dir=/var/www/weedfs -volume.port=8180 -volume.max=10 -master.peers=192.168.89.212:9333,192.168.89.213:9333 2

seaweed log:

cat  weed.linux-A1.root.log.INFO.20170703-151026.2810
Log file created at: 2017/07/03 15:10:26
Running on machine: linux-A1
Binary: Built with gc devel +c1730ae Wed Jan 18 15:40:33 2017 +0000 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss threadid file:line] msg
I0703 15:10:26  2810 file_util.go:20] Folder /var/www/weedfs Permission: -rwxrwxrwx
I0703 15:10:26  2810 file_util.go:20] Folder /var/www/weedfs Permission: -rwxrwxrwx
I0703 15:10:26  2810 topology.go:81] Using default configurations.
I0703 15:10:26  2810 master_server.go:67] Volume Size Limit is 30000 MB
I0703 15:10:26  2810 server.go:217] Start Seaweed Master 0.74 at 192.168.89.211:9333
I0703 15:10:27  2810 raft_server.go:56] Peers Change: [192.168.89.211:9333] => [192.168.89.212:9333 192.168.89.213:9333]
I0703 15:10:27  2810 raft_server.go:78] Joining cluster: 192.168.89.212:9333,192.168.89.213:9333
I0703 15:10:27  2810 raft_server.go:166] Attempting to connect to: http://192.168.89.212:9333/cluster/join
I0703 15:10:30  2810 raft_server.go:171] Post returned error:  Post http://192.168.89.212:9333/cluster/join: dial tcp 192.168.89.212:9333: getsockopt: no route to host
I0703 15:10:30  2810 raft_server.go:166] Attempting to connect to: http://192.168.89.213:9333/cluster/join
I0703 15:10:31  2810 raft_server.go:211] Post returned status:  200 
I0703 15:10:31  2810 volume_loading.go:73] loading index file /var/www/weedfs/3.idx readonly false
I0703 15:10:31  2810 disk_location.go:44] data file /var/www/weedfs/3.dat, replicaPlacement=001 v=2 size=19233384 ttl=
I0703 15:10:31  2810 disk_location.go:97] Store started on dir: /var/www/weedfs with 1 volumes max 10
I0703 15:10:31  2810 server.go:290] Start Seaweed volume server 0.74 at 192.168.89.211:8180
I0703 15:10:31  2810 volume_grpc_client.go:17] Volume server bootstraps with master 192.168.89.211:9333
I0703 15:10:31  2810 volume_grpc_client.go:25] heartbeat error: No master found: No master node available!
I0703 15:10:36  2810 volume_grpc_client.go:52] Heartbeat to 192.168.89.213:9333
I0705 19:44:13  2810 master_server.go:96] [ 192.168.89.211:9333 ] 192.168.89.211:9333 becomes leader.
I0705 19:55:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0705 20:10:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0705 20:25:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0705 20:40:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0705 20:55:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0705 21:10:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0705 21:25:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0705 21:40:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0705 21:55:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0705 22:10:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0705 22:25:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0705 22:40:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0705 22:55:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0705 23:10:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0705 23:25:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0705 23:40:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0705 23:55:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0706 00:10:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0706 00:25:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0706 00:40:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0706 00:55:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0706 01:10:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0706 01:25:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0706 01:40:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0706 01:55:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0706 02:10:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0706 02:25:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0706 02:40:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0706 02:55:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0706 03:10:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0706 03:25:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0706 03:40:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0706 03:55:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0706 04:10:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0706 04:25:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0706 04:40:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0706 04:55:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0706 05:10:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0706 05:25:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0706 05:40:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0706 05:55:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0706 06:10:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0706 06:25:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0706 06:40:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0706 06:55:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0706 07:10:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0706 07:25:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0706 07:40:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0706 07:55:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0706 08:10:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0706 08:25:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0706 08:40:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0706 08:55:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0706 09:10:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0706 09:25:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0706 09:40:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0706 09:55:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0706 10:10:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0706 10:25:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0706 10:40:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0706 10:55:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0706 11:10:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0706 11:25:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0706 11:40:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3
I0706 11:55:27  2810 topology_vacuum.go:83] Start vacuum on demand with threshold:0.3

**Comment by chrislusf** [comment]
what's the symptom of "It always breaks down"?

The elected master is "192.168.89.213:9333", what's the output of this?

curl 192.168.89.213:9333/dir/status?pretty=y

**Comment by chrislusf** [comment]
I suppose this "heartbeat error: No master found: No master node available!" problem is resolved in latest commits.
