### ISSUE TITLE
startup time

### ISSUE THREAD

**Issue by dfrost999** [chrislusf/seaweedfs#527]
Hi,

I'm running V. 0.70 for almost a year now and it is working great (approx. ~2TB of jpegs in 75 Volumes), so thanks for this great Software! It's running on Windows (yeah, I know...) with a leveldb config and Filer.

The only concern I have is: when weed.exe is restarted it takes about 40 minutes to get operable again as it is checking/rebuilding all data volumes. Is this expected behaviour or is it because SeaweedFS detects an unorderly shutdown (I run it with nssm as a "fake" Windows service)?
Any hints are appreciated.

Cheers,
Deacon

**Comment by chrislusf** [comment]
volume server restarts does take a long time to load index data into memory.

But 40 minutes is pretty long. How many volumes on each machine? Do you create a lot of folders in filer?

**Comment by dfrost999** [comment]
at the moment it is only one machine running weed master + volume + filer (75 Volumes total).
There are quite a number of folders in the filer volumes (~10'000 total, it's a "/<some-camera-ID>/YYYY/MM/dd" scheme)...

**Comment by chrislusf** [comment]
Less folders, or no folder, is better.

"/some-camera-ID-YYYY-MM-dd" can reduce the folders.
