### ISSUE TITLE
how to use yourself unique id

### ISSUE THREAD

**Issue by jeromeheng** [chrislusf/seaweedfs#528]
When I find a file ，I must use two params ( volum id and magic number) as fid .
How I want to use myself uniqu_id (just like uuid) ，and I also want to use this uuid that it can find out file
Thx ！

**Comment by chrislusf** [comment]
fileKey=volumdId(32bits),fileId(64bits),cookie(32bits)

uuid is 128 bits, not supported.

**Comment by jeromeheng** [comment]
@chrislusf   
So，I must use fileKey，or I must write a file that will be return two params，then I use "volume Id + fileId" to seed this file 。Unique_id will not be supported ？

**Comment by stevenkitter** [comment]
i don't like  this format like "1,11ud231". the "," is so low. how can i use uuid.
