### ISSUE TITLE
[to be continue]how to use unique_id

### ISSUE THREAD

**Issue by jeromeheng** [chrislusf/seaweedfs#530]
@chrislusf
Add an question with #528 
So，I must use fileKey，or I must write a file that will be return two params，then I use "volume Id + fileId" to seed this file 。Unique_id will not be supported ？
By the way， I must use myself unique_id ，whether or not it not supported ， and do you have your experience to help me ?

**Comment by jeromeheng** [comment]
Add a question with  https://github.com/chrislusf/seaweedfs/issues/528

**Comment by chrislusf** [comment]
store the pair of <unique_id, fileKey> in some database.

**Comment by stevenkitter** [comment]
@chrislusf  query the database waste time.so only fileKey?
