### ISSUE TITLE
Failed to write with error

### ISSUE THREAD

**Issue by jeromeheng** [chrislusf/seaweedfs#535]
when I use ：./weed benchmark -collection="benchmark" -c=20 -size=150000 -n=10000 -server="node74:9333"
there are some error (eg ：Failed to write with error:Failed to write to local disk (Volume Size Limit 104857600000 Exceeded! Current size is 34359748705)
Mycluster has 5 master and  15 volume  about 5 nodes

**Comment by chrislusf** [comment]
what's your master and volume command lines?

**Comment by jeromeheng** [comment]
@chrislusf 
5nodes
5master  just like:
nohup ./weed master -mdir="/home/sensetime/liuheng/master" -ip="node74" -ip.bind=node74" -pulseSeconds=30 -port=9333 -peers="node74:9333,node75:9333,node76:9333,node77:9333,node78:9333"  -defaultReplication="001" -volumeSizeLimitMB=100000 -volumePreallocate=true &
15volume just like:
nohup ./weed volume -dataCenter="dc1"  -rack="rack1"  -ip="node74" -ip.bind="node74" -pulseSeconds=10 -max="12" -dir="/data4/v4/"  -mserver="node74:9333" -port=8096 &

**Comment by chrislusf** [comment]
set "-volumeSizeLimitMB=100000" to be 30000 or lower.

**Comment by jeromeheng** [comment]
@chrislusf 
why do you do this ？ How could I use it to set this  correctly ?
