### ISSUE TITLE
how to  increase write/read iops

### ISSUE THREAD

**Issue by jeromeheng** [chrislusf/seaweedfs#536]
I have two clusters for testing
cluster1 ：
  3nodes 3 master  6volume(one volume ，one  disk with sas )
cluster2：
  5nodes 5 master  15volume(one volume ，one  disk)
there are two result for my testing
cluster1  
curl -d "collection=benchmark&count=10" "http://node74:9333/vol/grow"
-n 10W -size 20K -c 20 			cost time: 18.330s 106721.33 [Kbytes/sec]
10W 20K 50   		                        cost time: 17.643s 110875.41 [Kbytes/sec]

cluster2
curl -d "collection=benchmark&count=30" "http://node74:9333/vol/grow"
10W 20K 20 			cost time: 18.369s 106496.94 [Kbytes/sec]
10W 20K 50   		        cost time: 17.758s 110156.47 [Kbytes/sec]

there are similar with speeding  between cluster1 and cluster2

**Comment by chrislusf** [comment]
You are using 1Gbit/s network? Check your network speed.

**Comment by jeromeheng** [comment]
@chrislusf 
I use "ethtool enp3s0f0" to test my network,
there are five nodes that it is speeding "1000Mb/s"
