### ISSUE TITLE
Failed to write to replicas for volume

### ISSUE THREAD

**Issue by jeromeheng** [chrislusf/seaweedfs#537]
eg: ./weed benchmark -collection="benchmark0" -c=10 -size=30000 -n=1000000 -server="node74:9333"
when I run the benchmark about five nodes , Exeception was thrown .
Completed 387484 of 1000000 requests, 38.7% 1324.0/s 37.9MB/s
Completed 388811 of 1000000 requests, 38.9% 1327.0/s 38.0MB/s
Failed to write with error:Failed to write to replicas for volume 115: [172.20.2.76:8098]: Post http://node72:8098/115,e7cd29aff0bd10?ts=1500443943&type=replicate: EOF
Completed 390071 of 1000000 requests, 39.0% 1260.0/s 36.1MB/s
Completed 391245 of 1000000 requests, 39.1% 1174.0/s 33.6MB/s
........

**Comment by chrislusf** [comment]
I am not able to reproduce. What's the master command line you use?
