### ISSUE TITLE
replicating opetations [1] is less than volume's replication copy count [2]

### ISSUE THREAD

**Issue by joveth** [chrislusf/seaweedfs#538]
Well,I copied the volume data from another server.
The new server command:
`server -master.port=9333  -volume.port=8777   -volume.max=100 -dir=/data` 

The old use two server with `-dataCenter=dc1 -rack=rack1 `

Now.I update file on the new server as the fid exist but got

`{"name":"files","error":"Failed to write to replicas for volume 4: replicating opetations [1] is less than volume's replication copy count [2]"}`

What can i do?

Forgive my pool english,thank you!

**Comment by joveth** [comment]
The volume status
`{
    "Version": "0.76",
    "Volumes": [
        {
            "Id": 1,
            "Size": 12140915,
            "ReplicaPlacement": {
                "SameRackCount": 1,
                "DiffRackCount": 0,
                "DiffDataCenterCount": 0
            },
            "Ttl": {},
            "Collection": "",
            "Version": 2,
            "FileCount": 258,
            "DeleteCount": 45,
            "DeletedByteCount": 2619841,
            "ReadOnly": false
        },
        {
            "Id": 2,
            "Size": 16567866,
            "ReplicaPlacement": {
                "SameRackCount": 1,
                "DiffRackCount": 0,
                "DiffDataCenterCount": 0
            },
            "Ttl": {},
            "Collection": "",
            "Version": 2,
            "FileCount": 244,
            "DeleteCount": 45,
            "DeletedByteCount": 3330666,
            "ReadOnly": false
        },
        {
            "Id": 3,
            "Size": 15312585,
            "ReplicaPlacement": {
                "SameRackCount": 1,
                "DiffRackCount": 0,
                "DiffDataCenterCount": 0
            },
            "Ttl": {},
            "Collection": "",
            "Version": 2,
            "FileCount": 256,
            "DeleteCount": 41,
            "DeletedByteCount": 3416600,
            "ReadOnly": false
        },
        {
            "Id": 4,
            "Size": 12115608,
            "ReplicaPlacement": {
                "SameRackCount": 1,
                "DiffRackCount": 0,
                "DiffDataCenterCount": 0
            },
            "Ttl": {},
            "Collection": "",
            "Version": 2,
            "FileCount": 240,
            "DeleteCount": 33,
            "DeletedByteCount": 2108705,
            "ReadOnly": false
        },
        {
            "Id": 5,
            "Size": 16774204,
            "ReplicaPlacement": {
                "SameRackCount": 1,
                "DiffRackCount": 0,
                "DiffDataCenterCount": 0
            },
            "Ttl": {},
            "Collection": "",
            "Version": 2,
            "FileCount": 261,
            "DeleteCount": 46,
            "DeletedByteCount": 4803436,
            "ReadOnly": false
        },
        {
            "Id": 6,
            "Size": 14850633,
            "ReplicaPlacement": {
                "SameRackCount": 1,
                "DiffRackCount": 0,
                "DiffDataCenterCount": 0
            },
            "Ttl": {},
            "Collection": "",
            "Version": 2,
            "FileCount": 240,
            "DeleteCount": 36,
            "DeletedByteCount": 2324520,
            "ReadOnly": false
        },
        {
            "Id": 7,
            "Size": 113824,
            "ReplicaPlacement": {
                "SameRackCount": 0,
                "DiffRackCount": 0,
                "DiffDataCenterCount": 0
            },
            "Ttl": {},
            "Collection": "",
            "Version": 2,
            "FileCount": 2,
            "DeleteCount": 0,
            "DeletedByteCount": 0,
            "ReadOnly": false
        }
    ]
}`

**Comment by chrislusf** [comment]
requiring 2 volumes, but you have only one.
