### ISSUE TITLE
How to move files from one weed-volume server to another, and get rid of first 

### ISSUE THREAD

**Issue by VBeliaev** [chrislusf/seaweedfs#539]
Current situation:
We have 1 master server, 3 weed volume servers. Replication is: 001. So file is stored on 2 servers

What is needed:
Remove one weed-volume server  and have replications 001, so file will be on both servers

Questions:
1) In "additional features" there is information that :"Adding/Removing servers does not cause any data re-balancing". Is there way to change in configuration to rebalance? If no, Q2.
2) If copy data from server that planed to be removed to two other servers and update replication to   . Wiill weed master work with ths files? If no , Q3
3) If make weed backup, all data will be stored on that server.  After removing one weed volume and changing replication to , will it make two servers, each containing full data? 
4) Also there is idea to change replication to 002, and all data will be at 3 servers. After all data will be copied , remove one server, change replication to 001, but server we planed to remove don't have enough space for it 

If none of these way can make it, or there is way to do it easier, please write about it

**Comment by chrislusf** [comment]
For volume server A, B, C, if you want to remove server A:
1. Go to server B, copy any *.dat *.idx file that only exist on server A
2. Same for server C
