### ISSUE TITLE
A Random error found in logs 

### ISSUE THREAD

**Issue by ijunaid8989** [chrislusf/seaweedfs#540]
Got this error. Totally unknown to me, I have posted the trace if anyone can help, what it's about..

SeaweedFS version: 0.71 Beta.
OS: Ubuntu 14.04

> 2017/07/20 18:30:10 http: panic serving <ip_master>:49198: runtime error: slice bounds out of range goroutine 731515 [running]: net/http.(*conn).serve.func1(0xc93f10ae00) 	/root/.asdf/installs/golang/1.6.3/go/src/net/http/server.go:1389 +0xc1 panic(0xc86000, 0xc820010030) 	/root/.asdf/installs/golang/1.6.3/go/src/runtime/panic.go:443 +0x4e9 github.com/chrislusf/seaweedfs/weed/storage.(*Needle).readNeedleDataVersion2(0xc821bdd6b0, 0xc89fac8000, 0x995c, 0x9968) 	/opt/go/src/github.com/chrislusf/seaweedfs/weed/storage/needle_read_write.go:201 +0x49d github.com/chrislusf/seaweedfs/weed/storage.(*Needle).ReadNeedleBody(0xc821bdd6b0, 0xcbebaa83d8, 0x2, 0x6301639d8, 0x9968, 0x0, 0x0) 	/opt/go/src/github.com/chrislusf/seaweedfs/weed/storage/needle_read_write.go:249 +0x2ad github.com/chrislusf/seaweedfs/weed/storage.ScanVolumeFile(0x7ffdd37f9f12, 0x8, 0x0, 0x0, 0xcb00007f24, 0x0, 0xc8a7865818, 0xd9bd01, 0xc8a7865848, 0x0, ...) 	/opt/go/src/github.com/chrislusf/seaweedfs/weed/storage/volume_read_write.go:197 +0x631 github.com/chrislusf/seaweedfs/weed/storage.(*Volume).copyDataAndGenerateIndexFile(0xc9705f7400, 0xc9f25b5ba0, 0x12, 0xc9f25b5bc0, 0x12, 0x0, 0x0) 	/opt/go/src/github.com/chrislusf/seaweedfs/weed/storage/volume_vacuum.go:90 +0x39b github.com/chrislusf/seaweedfs/weed/storage.(*Volume).Compact(0xc9705f7400, 0x0, 0x0) 	/opt/go/src/github.com/chrislusf/seaweedfs/weed/storage/volume_vacuum.go:24 +0x24d github.com/chrislusf/seaweedfs/weed/storage.(*Store).CompactVolume(0xc82021a000, 0xc96c5faef7, 0x5, 0x0, 0x0) 	/opt/go/src/github.com/chrislusf/seaweedfs/weed/storage/store_vacuum.go:31 +0x1c0 github.com/chrislusf/seaweedfs/weed/server.(*VolumeServer).vacuumVolumeCompactHandler(0xc820066150, 0x7f3a14fa2660, 0xcbce5351e0, 0xc8fa050380) 	/opt/go/src/github.com/chrislusf/seaweedfs/weed/server/volume_server_handlers_vacuum.go:19 +0x7e github.com/chrislusf/seaweedfs/weed/server.(*VolumeServer).(github.com/chrislusf/seaweedfs/weed/server.vacuumVolumeCompactHandler)-fm(0x7f3a14fa2660, 0xcbce5351e0, 0xc8fa050380) 	/opt/go/src/github.com/chrislusf/seaweedfs/weed/server/volume_server.go:54 +0x3e net/http.HandlerFunc.ServeHTTP(0xc8ab879d00, 0x7f3a14fa2660, 0xcbce5351e0, 0xc8fa050380) 	/root/.asdf/installs/golang/1.6.3/go/src/net/http/server.go:1618 +0x3a net/http.(*ServeMux).ServeHTTP(0xc8201b29c0, 0x7f3a14fa2660, 0xcbce5351e0, 0xc8fa050380) 	/root/.asdf/installs/golang/1.6.3/go/src/net/http/server.go:1910 +0x17d net/http.serverHandler.ServeHTTP(0xc931805580, 0x7f3a14fa2660, 0xcbce5351e0, 0xc8fa050380) 	/root/.asdf/installs/golang/1.6.3/go/src/net/http/server.go:2081 +0x19e net/http.(*conn).serve(0xc93f10ae00) 	/root/.asdf/installs/golang/1.6.3/go/src/net/http/server.go:1472 +0xf2e created by net/http.(*Server).Serve 	/root/.asdf/installs/golang/1.6.3/go/src/net/http/server.go:2137 +0x44e

--

**Comment by chrislusf** [comment]
Can not tell without commit number. The lines are changing.

**Comment by chrislusf** [comment]
Need to adjust the build so that the build version can have the git version.

**Comment by ijunaid8989** [comment]
Thanks for your reply. I couldn't reproduce it again.
