### ISSUE TITLE
Newly added server hasn't been used yet

### ISSUE THREAD

**Issue by ijunaid8989** [chrislusf/seaweedfs#541]
![image](https://user-images.githubusercontent.com/13561999/28605431-21a0ca5a-71eb-11e7-8771-998bd77753af.png)

I just added a new volume server and the old one has 600+ remaining ones, The master only doing vacuums and etc. is there any time limit when it's going to touch the newly added?

**Comment by chrislusf** [comment]
https://github.com/chrislusf/seaweedfs/wiki/Master-Server-API#pre-allocate-volumes

add more volumes

**Comment by ijunaid8989** [comment]
my question was only this..

when there will lower volumes, Master will automatically get this newly added server in use?

**Comment by chrislusf** [comment]
Yes.
