### ISSUE TITLE
Persistently pre-allocate volumes' files

### ISSUE THREAD

**Issue by gheibia** [chrislusf/seaweedfs#542]
The current implementation appends each image at the end of the volume file. That is, a volume's data file grows with each image added. This is against one of the key aspects of Haystack's spec. Also, in some scenarios that I've tested, this leads to huge fragmentation and slows down retrieval.

Instead, the application should persistently pre-allocate a large file to ensure the file is mostly contiguous (I don't think that can be guaranteed) and mitigate the risk of fragmentation. It can then write image binaries in that file by tracking where was the last image written. I'm not talking about sparse files. They suffer from the same issue.

In newer version of Linux Kernel this can be done using "fallocate" system call and is already supported by ext4 and xfs (and a couple of other ones). In older systems (or other file systems that don't support fallocate) the only way to do this is to pre-allocate and fill the file with zeros which is slow and inefficient. But if it needs to happen, it can happen once and when the volume is starting up for the first time (unlike today that it happens when the first image is added).

Useful link:
https://www.spinics.net/lists/linux-ext4/msg43070.html

**Comment by chrislusf** [comment]
https://github.com/chrislusf/seaweedfs/blob/master/weed/command/master.go#L41

**Comment by gheibia** [comment]
Oh, cool. I didn't realise this is already in place. I'll have to try the new version then.
