### ISSUE TITLE
benchmark report 404 on /dir/assign

### ISSUE THREAD

**Issue by kelgon** [chrislusf/seaweedfs#543]
Hi, I need some help here.

I set up a seaweadfs cluster, which works fine. Passed all my reads/writes tests. But when I run ./weed benchmark command, it reports 100% 404 Not Found on /dir/assign request:

./weed benchmark -server=127.0.0.1:9333 -n=100

------------ Writing Benchmark ----------
writing file error: http://127.0.0.1:9333/dir/assign: 404 Not Found
writing file error: http://127.0.0.1:9333/dir/assign: 404 Not Found
...98 more of this

I tested http://127.0.0.1:9333/dir/assign with both curl and browser, it works well:

curl http://127.0.0.1:9333/dir/assign  
{"fid":"9,07a4983afa","url":"someurl:8080","publicUrl":"someurl:18080","count":1}

I use version 0.76, linux_arm64.tar.gz
my machine runs on Centos7, kernel 4.4.36-1.el7.elrepo.x86_64

thanks in advance

**Comment by kelgon** [comment]
Well, I think I've figured out the problem.
Turns out I am running out of volumes, when I request /dir/assign?collection=benchmark, master reports "No free volumes left".
I deleted some volumes and run benchmark again and it works fine.

But I think something can be done with the output of benchmark command, report 404 Not Found seems weird and misleading.

**Comment by chrislusf** [comment]
right. can you please help on this?

**Comment by kelgon** [comment]
I'd love to help but sadly I have nearly 0 experience in golang. Anyway I've managed to make a fix, feel free to criticize it.
