### ISSUE TITLE
Enable timestamp parameter for Filer

### ISSUE THREAD

**Issue by dfrost999** [chrislusf/seaweedfs#545]
Hello Chrislusf,

I think it would be a great enhancement for Filer, if a parameter for "ts" could be provided at file creation time to override the "Last-Modified"-timestamp (which seems to be the epoch at upload time) with a custom one. The ttl-url-parameter is already considered by Filer, so "ts" would be a logical enhancement, in case one uploads files via filer later but wants to keep the original file date-time.
Thanks for considering.

Cheers,
Deacon

**Comment by chrislusf** [comment]
added in latest commits.
