### ISSUE TITLE
does seaweedfs filer support redis cluster?

### ISSUE THREAD

**Issue by yunbj** [chrislusf/seaweedfs#546]
Hi.

I'm trying to use filer.
When I upload a file, filer returns 500 error with "(error) MOVED ..." message.
I guess the message is returned by redis and it means that key will be stored on other redis server.

So, I'm curious whether filer supports redis cluster.
If supports, how can I configure?

BR
Byungjo

**Comment by chrislusf** [comment]
Not now.

Need a redis cluster to develop this on.

**Comment by chrislusf** [comment]
yes now
