### ISSUE TITLE
weed upload not support flag "server" but the doc show wrong example.

### ISSUE THREAD

**Issue by monday-ch** [chrislusf/seaweedfs#549]
It looks command "weed upload" not support flag -server any more, but the doc for this command still show an example "weed upload -server=localhost:9333 -dir=one_directory -include=*.pdf".  

Because we use a earlier version of seaweedfs, and we use '-server' frequent, hope there still support '-server' or at least keep the right doc .

Thanks for the awesome seaweedfs

**Comment by chrislusf** [comment]
use "weed upload -master=..."
