### ISSUE TITLE
preformance

### ISSUE THREAD

**Issue by cfirs** [chrislusf/seaweedfs#550]
I tried using the tool on Windows, I ran a server with the command:./weed server -dir="./data"
and, I  used existing packages for node.js

But when I checked the performance (by comparing 1000 file calls) to the performance of the standard file system, the seaweed performance was significantly less good:

Fs: 2903.296ms
seaweedFS: 12889.028ms

what can be the reason for this diffrent?
tnx!

**Comment by chrislusf** [comment]
Did you check 1,000,000 files?

**Comment by cfirs** [comment]
now i checked for 100,000 reads of 0.5 MB file and:
FS: 120533.272ms
seaweed: 585344.686ms

and 1M reads
FSP: 1211021.928ms
seaweed: did't finish afther 20 min...

i  dont think that for 1M reads seafeed will win.

**Comment by chrislusf** [comment]
1M files, not reads.

**Comment by phal0r** [comment]
Would be nice to hear more of your test scenario. Could you provide some code?

**Comment by chrislusf** [comment]
Closing if no reproducible test case.
