### ISSUE TITLE
filer: allowing directory/regular files with same name in one directory

### ISSUE THREAD

**Issue by chanyoung** [chrislusf/seaweedfs#551]
Hello,

Currently filer allows to create same name of directory/regular files in one directory.
I'm not sure this is intended design but in fuse, it doesn't work well as below.

![2017-08-13 23-27-26](https://user-images.githubusercontent.com/6683987/29250548-0c149520-807f-11e7-99f2-06b14e9f2ed2.png)

However, it looks fine when accessed via web.

![2017-08-14 00-06-26](https://user-images.githubusercontent.com/6683987/29250843-a97b5f7e-8084-11e7-893c-9c17edde93ae.png)

I think weedfs need to disallow same name different type files in one directory, especially if have a plan to support fuse in unix/linux system.

Thanks.

**Comment by chrislusf** [comment]
understood. SeaweedFS filer stores directory and file separately. Ensuring directory~file uniqueness needs additional checking.

but I prefer not to do this additional checking, since FUSE is not really the best way to use SeaweedFS.
