### ISSUE TITLE
why there is no machine node in topology?

### ISSUE THREAD

**Issue by rockiee281** [chrislusf/seaweedfs#553]
Hi, in order to use multi disk on my machine, I need to start several datanode on single machine, but I find there is only datacenter/rack/datanode 3 level in the topology. If I want to my master/replication volume allocated on different physical machine, I have to define different rack for them, and different datacenter for my racks. This seems to be strange, I wander is there some design in weed-fs to prevent master/replication volume be allocated to different datanode on  one physical machine ? Will `001` spread master/replication volume to different machine, judge by IP  address

**Comment by chrislusf** [comment]
For datanodes on the same machine, you can treat them as if they are
separate machines and they are on the same rack.

Chris

**Comment by chrislusf** [comment]
You can also use multiple folders in one volume server.

**Comment by rockiee281** [comment]
> You can also use multiple folders in one volume server.

thanks，this is just what I  want

**Comment by rockiee281** [comment]
btw, will weed schedule different folders for concurrent read/write?

**Comment by chrislusf** [comment]
Each volume is single threaded. Cross volumes are parallel.

**Comment by rockiee281** [comment]
Maybe we can add multi folders support example to README for some newbie like me ：)
