### ISSUE TITLE
List files on Volume Server API

### ISSUE THREAD

**Issue by maikotz** [chrislusf/seaweedfs#554]
Is there a possibility to list the content or "directory" of a volume server? 

I'm facing the problem, that an application logged a file ID but the request returns a 404 error. 
It's possible that the upload was interrupted or something else strange happened but to be sure, I would need some more info than I get from  volumeserver:8080/status?pretty=y

Is there anything I can open / parse the metadata / idx files? 

Any help appreciated

**Comment by chrislusf** [comment]
"weed export -h"

**Comment by maikotz** [comment]
Thanks for the quick response! 

If I don't use the fileNameFormat parameter I'll get the following:

```
/tmp # weed export -dir=/data -volumeId=12 -o=/tmp/name.tar -newer='2006-01-02T15:04:05'
/tmp # tar xvf name.tar
tar: invalid tar header checksum
```

But if I use it, everything works. Thanks 

```
/tmp # weed export -dir=/data -volumeId=12 -o=/tmp/name.tar -newer='2006-01-02T15:04:05' -fileNameFormat='{{.Id}}-{{.Name}}'
```
