### ISSUE TITLE
{"error":"No free volumes left!"}

### ISSUE THREAD

**Issue by zhaoyingjun** [chrislusf/seaweedfs#556]
i move my data volume  from slaveA to slaveB,then l start slaveB, the volume just only read.
please test me how turn the volume to write

**Comment by ijunaid8989** [comment]
increase the volume limit, your all other volumes seem to be filled already/

**Comment by zhaoyingjun** [comment]
my weed version is 0.70, how to increase the the volume limit?

**Comment by ijunaid8989** [comment]
with which command you are starting seaweedFS?

You might add this to your command `-volume.max=2270` or may be `-volume.max="2270"`

2270 is the number., you can change it with your limit

**Comment by zhaoyingjun** [comment]
master ?

**Comment by ijunaid8989** [comment]
Yes, how you started your master?

**Comment by zhaoyingjun** [comment]
./weed -v=3 master -ip=xxxxxx -port=9333 -mdir=/home/ubuntu/masterdata

**Comment by ijunaid8989** [comment]
`./weed -v=3 master -ip=xxxxxx -port=9333 -mdir=/home/ubuntu/masterdata -volume.max=50`

Do this, by default the volume limit is 7..

**Comment by zhaoyingjun** [comment]
ok thx

**Comment by ijunaid8989** [comment]
Post here if it worked then close the issue.

Thanks.

**Comment by zhaoyingjun** [comment]
ok

**Comment by zhaoyingjun** [comment]
-volume.max it is not work  in 0.70?

**Comment by ijunaid8989** [comment]
type `./weed server`

you will see a list of commands, find the command about Volume max and add that to your command

**Comment by zhaoyingjun** [comment]
I0831 14:40:38  3424 volume_layout.go:157] Volume 6 becomes unwritable
I0831 14:40:38  3424 volume_layout.go:157] Volume 1 becomes unwritable
I0831 14:40:38  3424 volume_layout.go:157] Volume 2 becomes unwritable
I0831 14:40:38  3424 volume_layout.go:157] Volume 3 becomes unwritable
I0831 14:40:38  3424 volume_layout.go:157] Volume 4 becomes unwritable
I0831 14:40:38  3424 volume_layout.go:157] Volume 5 becomes unwritable

how the Volume 5 becomes writable?

**Comment by ijunaid8989** [comment]
they are unwritable because they are totally filled. 

don't you see anything to increase the volume limit?

**Comment by zhaoyingjun** [comment]
ok i know ,"./weed volume -max=50" is right
