### ISSUE TITLE
Could not specify the IP when running in docker or kubernetes

### ISSUE THREAD

**Issue by Macrame** [chrislusf/seaweedfs#557]
I tried to use the local IP for docker or kubernetes:
**Docker:**
_HOST_IP=`ip addr show | grep ens192 | grep global | awk '{print $2}' | cut -d / -f1`
docker run --privileged=true --name $container_name -d --link seaweedfs-master:master -v /data/file/storage:/data -p 6001:6000  $image_name volume -max=500 -mserver=master:9333 -ip=${HOST_IP} -publicUrl=${HOST_IP}:6001 -port=6000_
**Kubernetes:**
_apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: weedfs-volume
  labels:
    app: weedfs-volume
  namespace: xxxxx
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: weedfs-volume
    spec:
      terminationGracePeriodSeconds: 60
      volumes:
      - name: log
        hostPath:
          path: /data/weed/log
      - name: data
        hostPath:
          path: /data/weed/file
      containers:
      - name: weedfs-volume
        image: chrislusf/seaweedfs
        #livenessProbe:
        #  httpGet:
        #    path: /health
        #    port: 8080
        #    scheme: HTTP
        #  initialDelaySeconds: 120
        #  timeoutSeconds: 5
        ports:
        - containerPort: 8080
        args:
          -  volume
          - -mserver=weedfs-master:9333
          - -max=500
          - -publicUrl=images.xxx.com
          - -ip=weedfs-volume
          - -port=8080
_
It still uses the IP assigned by Docker or Flannel sadly.

I just want to store the local IP(the host machine) and the public URL(public IP or domain) after I call the /dir/assign to the weed-master in lua script.

**Comment by woody712** [comment]
same question

**Comment by chrislusf** [comment]
Using the service name as parameter for `-ip` should work now. See https://github.com/chrislusf/seaweedfs/blob/master/docker/seaweedfs-compose.yml
