### ISSUE TITLE
How can I get list of writable volumes?

### ISSUE THREAD

**Issue by man4j** [chrislusf/seaweedfs#559]
I try use this API:

curl "http://localhost:8080/status?pretty=y"

But information is incorrect. I see: 

`
 "Id": 5,
      "Size": 38,
      "ReplicaPlacement": {
        "SameRackCount": 0,
        "DiffRackCount": 0,
        "DiffDataCenterCount": 1
      },
      "Ttl": {},
      "Collection": "",
      "Version": 2,
      "FileCount": 2,
      "DeleteCount": 0,
      "DeletedByteCount": 0,
      **"ReadOnly": false**
`

But I can't write any data to this volume (because replica is down):
curl -X PUT -F file=./2.txt http://localhost:8080/5,046eed65ad
{"error":"Failed to write to replicas for volume 5: replicating opetations [1] is less than volume's replication copy count [2]"}

I need this info for automatically repair replicated volumes if replica is down. Thanks!

**Comment by chrislusf** [comment]
https://github.com/chrislusf/seaweedfs/wiki/Master-Server-API#check-system-status

You may or may not need to combine info from master and volumes to find the non-writable volumes.
