### ISSUE TITLE
Failed to write to replicas if volume node change IP address

### ISSUE THREAD

**Issue by man4j** [chrislusf/seaweedfs#561]
In docker swarm cluster container may change ip address (for weed volume). And master server understand it. Master server correctly generate file identifiers for volume server which the change ip. And master server correctly lookup file and return correct ip address. But volume server still remembered old ip address and dont accept new writes (..."error":"Failed to write to replicas for volume...).

**Comment by man4j** [comment]
I think that is general problem in design. Because software identify nodes by ip address instead host names. And i expect similar problem if master-node change ip address and other masters can't detect this peer and he is still alone.

**Comment by chrislusf** [comment]
If volume node changes IP address, there will be write errors at first. When the volume server register itself with the new IP address, the volume will be writable again.
