### ISSUE TITLE
Cannot grow volume group！

### ISSUE THREAD

**Issue by Dr13am** [chrislusf/seaweedfs#562]
when i  use weedfs， i often meet  “Cannot grow volume group”， i find  volume -max  （dufalut “7”） ，I need big storage ，so I modify the upper limit，But there are still problems ，what should  i do ？

**Comment by chrislusf** [comment]
increase the upper limit or post more details here.

**Comment by Dr13am** [comment]
I recently found such a mistake:

 runtime: out of memory: cannot allocate 1310720-byte block (3484090368 in use)
fatal error: out of memory,

 how can I solve it?

**Comment by chrislusf** [comment]
Add memory?

**Comment by chrislusf** [comment]
the pull request may have resolved this issue.
