### ISSUE TITLE
volume servers in multimaster setup

### ISSUE THREAD

**Issue by aivanise** [chrislusf/seaweedfs#563]
It is not possible to specify more than one master server to the volume server, so if the volume server is started with a master server that is down it will happily wait forever without trying the others, which is not really HA

it should be possible to specify multiple masters, e.g. like this

`weed volume -mserver server1:port,server2: port`

similar to the -peers option in weed master

**Comment by chrislusf** [comment]
The specified master server will tell the master list to the volume server.

**Comment by craveica** [comment]
@chrislusf if the specified master server is down (let's say failed to start), who is telling volume server about other masters?

**Comment by aivanise** [comment]
exactly, please reopen, this is a real issue

**Comment by craveica** [comment]
@aivanise for now, you can use haproxy to load balance/failover masters and set volume servers to connect to it.

**Comment by aivanise** [comment]
yeah, but then I need another HAProxy HA cluster as otherwise HAProxy becomes SPOF. Not exactly ideal having to support one cluster with another.

**Comment by craveica** [comment]
yeah, not ideal. It works for me as I need a HA haproxy for other services.

**Comment by craveica** [comment]
@chrislusf 
Can you add an option to specify master servers list instead of only 1 master server?

**Comment by chrislusf** [comment]
added in https://github.com/chrislusf/seaweedfs/commit/c546c309f10154688431433c031d62dc20edfc85
