### ISSUE TITLE
filer servers in multimaster setup

### ISSUE THREAD

**Issue by aivanise** [chrislusf/seaweedfs#564]
currently weed filer is not multimaster aware at all, it will happily "bootstrap" on a non existing master server and happily serve internal errors, the same if the master is there but goes down and the leader is switched to another master

It should be possible to pass a list of master servers to the filer and it should check them all until it finds a working one, i.e. 

`weed filer -masters server1:port,server2,server3...`

**Comment by chrislusf** [comment]
added in https://github.com/chrislusf/seaweedfs/commit/c546c309f10154688431433c031d62dc20edfc85
