### ISSUE TITLE
Question about upper limit for volume.max ?

### ISSUE THREAD

**Issue by maikotz** [chrislusf/seaweedfs#569]
Hi,

I run seaweed in k8s and on persistent storage, disregarding performance issues, is there an upper limit for the max volumes? At the moment I'm on 300. 

I use a couple of collections and have not a lot of concurrent apps accessing the volume server, but rather lots of files stored on seaweed. 
For backup and restore purposes it would be a lot easier to run in a single instance till I hit the performance or master size limit inside the cluster, so is there any argument that speaks for multiple instances with fewer max volumes?

**Comment by chrislusf** [comment]
It's ok to have many volumes.
