### ISSUE TITLE
Replication and Node Errors

### ISSUE THREAD

**Issue by kw005** [chrislusf/seaweedfs#570]
I would like to use seaweedfd and got some questions/understanding issues.
When I use a replication factor, e.g. 2 (I got two servers/nodes in total)
```
> weed volume -dir="/tmp/data1" -max=5  -mserver="localhost:9333" -port=8080 &
> weed volume -dir="/tmp/data2" -max=10 -mserver="localhost:9333" -port=8081 &
```
and would like to store an image file 1.jpg
`curl -X PUT -F file=@/home/chris/1.jpg _http://127.0.0.1:8080/3,01637037d6_` 

this is being stored on every server above? I have gotten back the URL "127.0.0.1:8080" which is being stored in the database, but what if the server 8080 goes down? I assume due to replication, the image is stored on 8081 as well - but do I have to store both URLs in the database, is there a unique URL which I can save and use - how does the replication feature and URL usage works here? Do I have to lookup (e.g. every 15 min) the respective volumeId?

**Comment by chrislusf** [comment]
If you will never move the volume server, you can store both URLs.
If the volume server moves, you need to check for moved URLs from the master.
