### ISSUE TITLE
Replication Handling

### ISSUE THREAD

**Issue by kw005** [chrislusf/seaweedfs#572]
If the cluster has a replication level of 2 and a volume goes down permanently, are the files on the other second volume being replicated to another/new volume automatically or how is this being done?

If so, is there a timeout, e.g. volumeID X unreachable withing 5 min, start replicating to new volume?
If there is a timeout, can this be configured due to server maintenance issues etc. and/or can the volume be shut down for maintenance  only?

**Comment by chrislusf** [comment]
the volumes will become read only.

**Comment by kw005** [comment]
all volumes will become read only? If so, there will be write errors everywhere? That would be horrible if we have 1000+ volumes. The probability that a volume will crash is high, the more volumes we have.
If not, there is no automatic replication like HDFS etc. has, we have to do it manually? That would also not also not very helpful at all. :(

**Comment by chrislusf** [comment]
the volumes with missing replica will become read only.

**Comment by kw005** [comment]
OK, so, I just have to get it right:
I got 10 volumes, replication level: 2  - there are 5 volumes, every volume has 1 replica. 
If volume 1 has replica 6, if volume 1 goes down, volume 6 is read only. There is enough space available over the 10 volumes, but the replica 6 would not be automatic scheduled to other volumes that it becomes writable again?

**Comment by chrislusf** [comment]
volume 1 will be read only.

**Comment by kw005** [comment]
The new replica has to done manually?
