### ISSUE TITLE
timeout for volume & master server

### ISSUE THREAD

**Issue by maikotz** [chrislusf/seaweedfs#580]
0.74 in kubernetes environment

I didn't find anything in the commit notes of the last 2 releases so I don't know if this was already addressed or not. 

When a volume or master server gets rescheduled to another kubernetes node it leads to connection loss between master and volume.

Situation 1: master server gets rescheduled. 
Since the master is persisting the list of volume server in memory and not in /data, the information about volume servers are lost during restart. Volume server doesn't send an heatbeat again and master stays online with no volume servers.

Situation 2: volume server gets rescheduled. master stays online. 
Master server volume server list constists of online and offline volume server. Occasionally a stale / outdated volume server will be returned to a /dir/assign request and the requests fails on clientside.

Proposal 1: It would be good if the hearbeat frequency would be adjustable or better a timeout value could be set when a node is considered dead. If the node is considered dead, the master should remove it from the in memory table and volume server frequently send keep alive packages to master to reregister. 

Proposal 2: If the volume server list is stored persistently in the /data directory, the rescheduled master could connect to the volume servers and verify their existence. Also it would be great to be able to trigger this whenever a new volume server registers itself. 

Please correct me if I'm missing something here. :-)
Cheers.

**Comment by chrislusf** [comment]
please ask questions on the mailing list.
