### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by kw005** [chrislusf/seaweedfs#583]
When installing it and running "go install" I got the following error message:

/srv/src/github.com/chrislusf/seaweedfs/weed# go install
../../../gocql/gocql/conn.go:9:2: cannot find package "context" in any of:
        /usr/lib/go/src/pkg/context (from $GOROOT)
        /srv/src/context (from $GOPATH)

Can anybody help please?

**Comment by chrislusf** [comment]
upgrade your Go version
