### ISSUE TITLE
api/command on "replication stats"

### ISSUE THREAD

**Issue by kw005** [chrislusf/seaweedfs#585]
Is there a command/API call which provides an overview about which servers are replicated with which?

Example: I got 10 servers, replication level: 3
Example Output: Server vs. Replication servers:
1: Server 1 <-> Server 3 <-> Server 4
2: Server 2 <-> Server 5 <-> Server 8
3: Server 6 <-> Server 7 <-> Server 9

**Comment by chrislusf** [comment]
no.

the replication is on volume level, not server level.

**Comment by kw005** [comment]
Yes, or volume levels. The goal is to get known where a file is located on these 3 out of 10 servers. How do I do that?

**Comment by chrislusf** [comment]
use http://master:port/dir/lookup by a volume id.
