### ISSUE TITLE
Backup/File Data dump and Replication Change over time

### ISSUE THREAD

**Issue by kw005** [chrislusf/seaweedfs#587]
I got 2 questions:
1) How am I able to backup/dump all files (images etc.) from a volume?
`weed backup -server=master:port -dir=. -volumeId=5`
Does not backup files, just .dat and .idx, right?

2) I had a replication level of 2, but we wanna change that level to 3. Are files, which have been written over time, automatically replicated from 2 to 3? If so, how can we achieve this?

**Comment by chrislusf** [comment]
please ask questions on the mailing list.

**Comment by chrislusf** [comment]
1. I do not understand the question.
2. There is a tool to change the replication for a volume file. After changing both files, create another copy and add the volume to one volume server. 
https://github.com/chrislusf/seaweedfs/tree/master/unmaintained/change_superblock

**Comment by kw005** [comment]
OK, thank you.
