### ISSUE TITLE
Force garbage collection

### ISSUE THREAD

**Issue by ijunaid8989** [chrislusf/seaweedfs#589]
Is there any possibility that forced garbage collection removes the files present on volume? 

I have tried this so far

curl "http://master:9333/vol/vacuum?garbageThreshold=0.2"

Is there any possibility that it removes all files in the volumes ? not only Trash ones? 
![image](https://user-images.githubusercontent.com/13561999/32427683-730018f8-c2e3-11e7-9c9c-e04533c69450.png)

It removed ALL ldbs files in filer folder.. why?

**Comment by chrislusf** [comment]
please ask questions on the mailing list.

**Comment by chrislusf** [comment]
filer folder is not related to vacuum. Please show some screenshots of the ldb files you are talking about.
