### ISSUE TITLE
Filer syncing with volumes

### ISSUE THREAD

**Issue by ijunaid8989** [chrislusf/seaweedfs#590]
We had our filer folder, with all the ldbs,

I ran the Basho's leveldb repair on that filer and then attached it with master... 

1: I forced the vacuum.

It deleted all the ldbs from filer.. and I cannot see any file

I added the old filer folder back to its place and started master again,

Now I can see the files again, on its paths, But, 

Is there any way to sync that vacuum on master (Forced Garbage collection) with the filer folder?

**Comment by chrislusf** [comment]
please ask questions on the mailing list.

**Comment by chrislusf** [comment]
There are two possible kinds of ldb files and they are not related. But I can not tell which you are using.
