### ISSUE TITLE
Backup

### ISSUE THREAD

**Issue by kw005** [chrislusf/seaweedfs#592]
Is the backup script enough for backup everything (looping through all volumes). What about the master server, all the metadata etc., e.g. scenario of loosing the master and all volumes?

**Comment by chrislusf** [comment]
please ask questions on the mailing list.

**Comment by chrislusf** [comment]
no need to backup master.

backup volumes on the volume server will be good enough.

**Comment by kw005** [comment]
OK, thanks.
