### ISSUE TITLE
weed backup:  Appending volume error 

### ISSUE THREAD

**Issue by kw005** [chrislusf/seaweedfs#594]
Found older posts from last year that the weed backup has problems.
Does the weed backup still has these errors? If, when are these going to be fixed?

`Appending volume 1 error: /teradata/volumes/1.dat is read-only`

**Comment by chrislusf** [comment]
Maybe fix it later. it only happens if the file is deleted and added back with the same file id. Usually you should always request a new file id when writing.

"Appending volume 1 error: /teradata/volumes/1.dat is read-only" I do not understand whether this is related to the above question.

**Comment by kw005** [comment]
Nothing has been deleted, I just wrote a new file the the cluster. The .dat file just increased by size and the backup start failing at this part.

**Comment by devendrasr** [comment]
any updates on this issue?
we are also facing problems while creating backup.

**Comment by chrislusf** [comment]
The original issue should be related to a fixed bug on writing to the dat files during compaction. This is not related to "weed backup".

Closing this and track the fix for "weed backup" in https://github.com/chrislusf/seaweedfs/issues/399
