### ISSUE TITLE
Transfer all files to a new seaweedfs cluster

### ISSUE THREAD

**Issue by CheyenneForbes** [chrislusf/seaweedfs#596]
Is there a standard way to move all files to a new seaweedfs cluster and keep the same fid?

senario:

I launched my platform using virtual servers (as its cheaper) but now I am ready to move to dedicated servers but I want to know the right way to move the data to a new cluster so my users dont hunt me down to torture me for messing up the data they trusted my platform with.

**Comment by chrislusf** [comment]
Yes. Just copy all the volume .dat and .idx files.

please ask questions on mailing list.

**Comment by shamork** [comment]
is there any inconsistence if copy files when the cluster is running?
