### ISSUE TITLE
Master to Master transfer

### ISSUE THREAD

**Issue by ijunaid8989** [chrislusf/seaweedfs#598]
Sorry for posting here, No one answering the mailing list for any question.

We had an old master server A with version 0.70, and Now we have a new one with the same version B, with both filer=true

Is there any possibility, we can shift all the old master (A) data to new master (B),

while said, data, I meant, all the volumes files and also the filer structure on master A. Is there any way to do that?

**Comment by chrislusf** [comment]
Copying all the files for the filer and volume servers should be enough.
