### ISSUE TITLE
Connection problems

### ISSUE THREAD

**Issue by nd2s** [chrislusf/seaweedfs#599]
I am running the latest release on FreeBSD (`version 0.76 freebsd amd64`) with following parameters:

```
/usr/local/bin/weed -log_dir /var/log/seaweedfs server -ip 127.0.0.1 -ip.bind 127.0.0.1 -volume.max 10 -dir /usr/local/seaweedfs -volume.port 9000 -master.port 9333
```

To be 100% precise I am using `daemon` to daemonise:

```
/usr/sbin/daemon -f -p /var/run/weed.pid -u weed <COMMAND>
```

Frequently all SeaweedFS log output seems to just stop (no errors) and I lose the ability to connect (seen in `nginx` logs and tested with `curl -v -L "https://127.0.0.1:9333/status`). Restarting solves the problem.

I am also losing the ability to connect from my backend daemon (`go`) after SeaweedFS has been running for a few minutes. But it is still accessible from other programs `nginx`, `curl`. All the services use ipv4 addresses to connect (`127.0.0.1`).

Is there any known issue that could cause this behaviour? I can't find any indication of the problem in the system logs either.

**Comment by chrislusf** [comment]
Not aware of anything related. Maybe it is running out of file handlers?

**Comment by nd2s** [comment]
Unfortunately there is no limit on open files for this (or any) user. :(

```
  openfiles            infinity
```
 Also there aren't problems visible in the system logs.

**Comment by chrislusf** [comment]
this seems no clue and nothing actionable.
