### ISSUE TITLE
Failed to read file size data

### ISSUE THREAD

**Issue by lorico** [chrislusf/seaweedfs#601]
Hi Chris,
First of all, congratulations for the trememdous work you have done ! I love seaweed!

I have a strange issue: 
After starting a simple server, and doing some read/writes of simple text files, after like 5-10min (and even if I don't do any operation at that time), I get this error message looping, on all volumes files:
> I1124 09:04:19 15880 volume.go:63] Failed to read file size data/6.dat GetFileType data/6.dat: use of closed file

=> Any idea what would be causing that problem ?

Thanks a lot in advance for the help

**Comment by chrislusf** [comment]
can you please do a "ls -al" on those files?

**Comment by lorico** [comment]
Well, I was running this under windows 10.
Should I test it with Linux to see if I have the same issue ? Would it be related to windows ?

**Comment by chrislusf** [comment]
Yes. Related to windows.

**Comment by chrislusf** [comment]
similar problem is resolved https://github.com/chrislusf/seaweedfs/issues/761
