### ISSUE TITLE
pressure test failure rate is high

### ISSUE THREAD

**Issue by gxgeek** [chrislusf/seaweedfs#604]
I am a novice, the use of seaweedfs I deployed a one master and  two volumes 

Do not know why the pressure test failure rate is high
My deployment command

nohup ./weed -log_dir = "/ var / log / weed" master -ip = 192.168.0.21 -ip.bind = 192.168.0.21> /var/log/weed-master.log 2> & 1 &

nohup ./weed volume -dir = "/ var / weed / data1" -max = 5 -mserver = "192.168.0.21:9333" -port = 8080 -ip = 192.168.0.21 -ip.bind = 192.168.0.21> / var / log / weed-volume.log 2> & 1 &

nohup ./weed volume -dir = "/ var / weed / data1" -max = 10 -mserver = "192.168.0.21:9333" -port = 8081 -ip = 192.168.0.26> / var / log / weed-volume. log 2> & 1 &

Use ad  measurement
ab -k -c 10 -n 100000 http://192.168.0.21:9333/dir/assign

Complete requests: 100000
Failed requests: 25077

**Comment by chrislusf** [comment]
What's in the master output?

**Comment by gxgeek** [comment]
Reboot today and test again


Complete the request: #10000
Failed request: 7559


[root @ 252-254-200-60 weed] # tail -100f weed.INFO
Log file created at: 2017/11/30 09:05:09
Running on machine: 252-254-200-60
Binary: Built with gc devel + d64c490 Sun May 28 10:23:38 2017 +0000 for linux / amd64
Log line format: [IWEF] mmdd hh: mm: ss threadid file: line] msg
I1130 09:05:09 15980 file_util.go: 20] Folder / tmp Permission: -rwxrwxrwx
I1130 09:05:09 15980 master_server.go: 62] Volume Size Limit is 30000 MB
I1130 09:05:09 15980 master.go: 87] Start Seaweed Master 0.76 at 192.168.0.21:9333
I1130 09:05:09 15980 raft_server.go: 56] Peers Change: [192.168.0.21:9333] => []
I1130 09:05:09 15980 raft_server.go: 98] Initializing new cluster
I1130 09:05:09 15980 master_server.go: 95] [192.168.0.21:9333] I am the leader!
I1130 09:06:23 15980 node.go: 223] topo adds child DefaultDataCenter
I1130 09:06:23 15980 node.go: 223] topo: DefaultDataCenter adds child DefaultRack
I1130 09:06:23 15980 node.go: 223] topo: DefaultDataCenter: DefaultRack adds child 192.168.0.21:8080
I1130 09:06:23 15980 master_grpc_server.go: 36] added volume server 192.168.0.21:8080
I1130 09:08:07 15980 node.go: 223] topo: DefaultDataCenter: DefaultRack adds child 192.168.0.26:8081
I1130 09:08:07 15980 master_grpc_server.go: 36] added volume server 192.168.0.26:8081

**Comment by chrislusf** [comment]
Your folder name is weird. why "/ tmp" has an empty space in the path? And it is not "/ var / log / weed" that is in the command line.

**Comment by gxgeek** [comment]
I do not know how to improve the success rate

or  do not know where I set wrong
Can anyone help me?

**Comment by gxgeek** [comment]
I try launching user    docker image
test
$ ab -k -c 10 -n 10000 http://127.0.0.1:9333/dir/assign

Time taken for tests: 3.219 seconds
Complete requests: 10000
Failed requests: 4468

the second
Time taken for tests: 3.103 seconds
Complete requests: 10000
Failed requests: 0

**Comment by chrislusf** [comment]
seems just your docker network problem.

**Comment by chrislusf** [comment]
I tested this way:
1. clear the folders for the master and volume servers
2. start weed master and volume servers
3.  curl http://localhost:9333/dir/assign
{"fid":"5,016ea8f128","url":"localhost:8080","publicUrl":"localhost:8080","count":1}
The 01 in "016ea8f128" is the id == 1.
4. ab -k -c 10 -n 10000 http://127.0.0.1:9333/dir/assign
Complete requests:      10000
Failed requests:        9746
   (Connect: 0, Receive: 0, Length: 9746, Exceptions: 0)
5. curl http://localhost:9333/dir/assign
{"fid":"7,2712c3fb05ce","url":"localhost:8080","publicUrl":"localhost:8080","count":1}

The 2712 is the hex value of 10002.

This shows all the requests are processed and the ids are assigned as expected.

This is something to do with how "ab" determines "Failed requests". Not related to SeaweedFS
