### ISSUE TITLE
crash - runtime: VirtualAlloc of 0 bytes failed with errno=1455

### ISSUE THREAD

**Issue by little-pan** [chrislusf/seaweedfs#606]
// seaweedfs 0.76 release
runtime: VirtualAlloc of 0 bytes failed with errno=1455
fatal error: runtime: failed to commit pages

runtime stack:
runtime.throw(0xc5a271, 0x1f)
        /home/travis/.gimme/versions/go/src/runtime/panic.go:596 +0x9c
runtime.sysUsed(0xc042080000, 0x2000)
        /home/travis/.gimme/versions/go/src/runtime/mem_windows.go:74 +0x1bc
runtime.(*mheap).allocSpanLocked(0x107d960, 0x1, 0x1097408, 0x2258f0)
        /home/travis/.gimme/versions/go/src/runtime/mheap.go:813 +0x2d4
runtime.(*mheap).alloc_m(0x107d960, 0x1, 0xc04209004b, 0x2258f0)
        /home/travis/.gimme/versions/go/src/runtime/mheap.go:661 +0x126
runtime.(*mheap).alloc.func1()
        /home/travis/.gimme/versions/go/src/runtime/mheap.go:728 +0x54
runtime.systemstack(0x323fdf0)
        /home/travis/.gimme/versions/go/src/runtime/asm_amd64.s:360 +0xb5
runtime.(*mheap).alloc(0x107d960, 0x1, 0x1004b, 0x2258f0)
        /home/travis/.gimme/versions/go/src/runtime/mheap.go:727 +0xa8
runtime.(*mcentral).grow(0x107ff70, 0x0)
        /home/travis/.gimme/versions/go/src/runtime/mcentral.go:232 +0x9b
runtime.(*mcentral).cacheSpan(0x107ff70, 0x2258f0)
        /home/travis/.gimme/versions/go/src/runtime/mcentral.go:106 +0x341
runtime.(*mcache).refill(0x2206a8, 0x4b, 0x2258f0)
        /home/travis/.gimme/versions/go/src/runtime/mcache.go:123 +0xb2
runtime.(*mcache).nextFree.func1()
        /home/travis/.gimme/versions/go/src/runtime/malloc.go:553 +0x39
runtime.systemstack(0xc042014000)
        /home/travis/.gimme/versions/go/src/runtime/asm_amd64.s:344 +0x7e
runtime.mstart()
        /home/travis/.gimme/versions/go/src/runtime/proc.go:1116

goroutine 134 [running]:
runtime.systemstack_switch()
        /home/travis/.gimme/versions/go/src/runtime/asm_amd64.s:298 fp=0xc0422b9
a60 sp=0xc0422b9a58
runtime.(*mcache).nextFree(0x2206a8, 0x4b, 0x2258f0, 0x0, 0x2244c0)
        /home/travis/.gimme/versions/go/src/runtime/malloc.go:552 +0xb0 fp=0xc04
22b9ab8 sp=0xc0422b9a60
runtime.mallocgc(0x800, 0xb213a0, 0xc0421cca01, 0xc0421ccaa8)
        /home/travis/.gimme/versions/go/src/runtime/malloc.go:707 +0x735 fp=0xc0
422b9b60 sp=0xc0422b9ab8
runtime.makeslice(0xb213a0, 0x800, 0x800, 0x4035f0, 0xc0422b9be8, 0xc0422b9be8)
        /home/travis/.gimme/versions/go/src/runtime/slice.go:54 +0x7e fp=0xc0422
b9b90 sp=0xc0422b9b60
bufio.NewWriterSize(...)
        /home/travis/.gimme/versions/go/src/bufio/bufio.go:540
net/http.newBufioWriterSize(0x1021e80, 0xc04207c038, 0x800, 0x0)
        /home/travis/.gimme/versions/go/src/net/http/server.go:811 +0xa4 fp=0xc0
422b9bf8 sp=0xc0422b9b90
net/http.(*conn).readRequest(0xc042254000, 0x102ae40, 0xc0420300c0, 0xc04207c000
, 0x0, 0x0)
        /home/travis/.gimme/versions/go/src/net/http/server.go:999 +0x7cc fp=0xc
0422b9d48 sp=0xc0422b9bf8
net/http.(*conn).serve(0xc042254000, 0x102ae40, 0xc0420300c0)
        /home/travis/.gimme/versions/go/src/net/http/server.go:1735 +0x515 fp=0x
c0422b9fc8 sp=0xc0422b9d48
runtime.goexit()
        /home/travis/.gimme/versions/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc
0422b9fd0 sp=0xc0422b9fc8
created by net/http.(*Server).Serve
        /home/travis/.gimme/versions/go/src/net/http/server.go:2696 +0x28f

**Comment by chrislusf** [comment]
Not enough information.

**Comment by little-pan** [comment]
Windows server 2008 r2 system issue -  not enough available memory.
