### ISSUE TITLE
How I can work with SeaWeeds FS in R ?

### ISSUE THREAD

**Issue by andirey** [chrislusf/seaweedfs#607]
I have to process a lot of small files as fast and cheap cost as possible by using R.
How can I work in R ? I see some libraries on Python but can't found in R. 
https://github.com/chrislusf/seaweedfs/wiki/Client-Libraries

**Comment by chrislusf** [comment]
I am not familiar with R. 

Basically to access SeaweedFS data, you just need HTTP.

**Comment by andirey** [comment]
Thanks! There is R package for working with HTTP
https://cran.r-project.org/web/packages/httr/httr.pdf
So, maybe using it I can access SeaweedFS data storage.
What is the speed for R/W operations to the SeaweedFS ?
Is it about the same as for the FS on AWS EC2, for example? Or is about AWS S3?
Will be glad to see some comparative analysis for speed.
Thanks ahead

**Comment by chrislusf** [comment]
I checked R a bit. You actually can just use R to read http file directly.

The performance is more depend on your network speed in most cases.

**Comment by andirey** [comment]
Ok, thanks. Will try to test & use SeaweedFS.
