### ISSUE TITLE
volumeSizeLimitMB on volume

### ISSUE THREAD

**Issue by marianvlad** [chrislusf/seaweedfs#617]
There is a way to set the size per volume? I have two servers and I want to use 1TB space from the first server and 2TB from the second server.

**Comment by chrislusf** [comment]
Set "-max" for each volume server, to control the number of volumes.

**Comment by marianvlad** [comment]
And to control the size of a volume I can set volumeSizeLimitMB to master?

e.g:  volumeSizeLimitMB=100000 for 100GB

And if I want to use just 1TB from a server I need to set "-max=10"?

**Comment by marianvlad** [comment]
I don't know why if I'm use "-max=15", It creates only 7 volumes.
