### ISSUE TITLE
Volume attempts to connect a non-existent master server

### ISSUE THREAD

**Issue by christ-shaw** [chrislusf/seaweedfs#618]
Hi everyone, 
I am trying to deploy a distributed file system through seaweeds  involving two computers;
A master node is deployed in one of the computer ,whose IP is 192.168.34.187, and it works well.
However , a wired exception comes out when we are going to start up the volume node  in the other computer. It seems to attempt to send heartbeats to a unknown master node . As the result ,it cannot start up successfully. 

We  hava designated the master address "192.168.34.187:9333",but the volume node still insist that localhost:9333 is its master node rather than 192.168.34.187:9333

The log as follows:

root@skjrkjltenv01 weed]# ./weed -v=4 volume -max=100 -mserver=192.168.34.187:9333 -ip="192.168.34.186"   -dir="data" -port=9332
I0123 14:01:47 16236 file_util.go:20] Folder data Permission: -rwxr-xr-x
I0123 14:01:47 16236 disk_location.go:106] Store started on dir: data with 0 volumes max 100
I0123 14:01:47 16236 volume.go:141] Start Seaweed volume server 0.74 at 0.0.0.0:9332
I0123 14:01:47 16236 volume_grpc_client.go:17] Volume server bootstraps with master 192.168.34.187:9333
I0123 14:01:47 16236 store.go:48] Listing masters on 192.168.34.187:9333
I0123 14:01:47 16236 list_masters.go:18] list masters result :{"IsLeader":true,"Leader":"localhost:9333"}
I0123 14:01:47 16236 store.go:53] current master nodes is nodes:**[localhost:9333 192.168.34.187:9333], leader:localhost:9333**
2018/01/23 14:01:47 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:9333: getsockopt: connection refused"; Reconnecting to {localhost:9333 <nil>}
I0123 14:01:47 16236 volume_grpc_client.go:48] &{0xc420215080}.SendHeartbeat(_) = _, rpc error: code = Unavailable desc = grpc: the connection is unavailable
I0123 14:01:47 16236 volume_grpc_client.go:25] heartbeat error: rpc error: code = Unavailable desc = grpc: the connection is unavailable
2018/01/23 14:01:47 Failed to dial localhost:9333: context canceled; please retry.
^CI0123 14:01:48 16236 volume_server.go:93] Shutting down volume server...
I0123 14:01:48 16236 volume_server.go:95] Shut down successfully!

**Comment by chrislusf** [comment]
start the master server with "-ip" option.
