### ISSUE TITLE
upload large file using client

### ISSUE THREAD

**Issue by DengrongGuan12** [chrislusf/seaweedfs#619]
hi, I followed your steps of [Large File Handling](https://github.com/chrislusf/seaweedfs/wiki/Large-File-Handling)  
But i  can not download total file using manifest file id. Did you mean that we should merge file chunk by client self?  
If not , may you provide a simple example about uploading large file?Because I found there are no apis in Client lib to upload large file.
thx very much~

**Comment by chrislusf** [comment]
"weed upload" has the code on how to do this.
