### ISSUE TITLE
Can't use -secure.secret parameter

### ISSUE THREAD

**Issue by gclove** [chrislusf/seaweedfs#620]
`-secure.secret=string` It doesn't work.

```
-secure.secret string
     	secret to encrypt Json Web Token(JWT)
```

**Comment by ijunaid8989** [comment]
Not implemented yet.

**Comment by Sunzhuokai** [comment]
How's it going about this?

**Comment by chrislusf** [comment]
Need help.

**Comment by chrislusf** [comment]
not needed any more. see https://github.com/chrislusf/seaweedfs/wiki/Security-Overview#jwt-based-access-control
