### ISSUE TITLE
large file not found in filer service

### ISSUE THREAD

**Issue by DengrongGuan12** [chrislusf/seaweedfs#621]
hi~
I setted maxMB = 5 when I started weed filer.
And then I upload a file larger than 5MB and succeed.
But I can not find this file in specific path.
![image](https://user-images.githubusercontent.com/8155869/35423987-de0203a4-028b-11e8-8014-078fa1b5cbda.png)
![image](https://user-images.githubusercontent.com/8155869/35424026-fa095354-028b-11e8-8ab2-9fb112e35353.png)
![image](https://user-images.githubusercontent.com/8155869/35424042-0d22fcba-028c-11e8-805c-3620cb576e8c.png)
What's reason for that?
thx very much~

**Comment by chrislusf** [comment]
because you put "cm=false" in the url

**Comment by DengrongGuan12** [comment]
but why this file not show in filer or what operation can make it show in filer?
