### ISSUE TITLE
how to do a pre auth before upload file

### ISSUE THREAD

**Issue by 13428282016** [chrislusf/seaweedfs#622]

**Comment by 13428282016** [comment]
I want upload file to my php server first for checking permission，then  upload to  seaweedfs from php server  ，but it take  double upload。how to  upload directly to seaweefs with checking permission

**Comment by chrislusf** [comment]
not supported yet.

**Comment by phal0r** [comment]
It should not be a feature of seaweed. I would suggest that the best practice is, to put a security proxy in front, which does authentication and authorization via a central authentication server based on the open id connect protocol or similar (saml 2). That means, this should be a concern for the infrastructure, not seaweed.
