### ISSUE TITLE
leader master's shutting down cause other master's uploading failure when using filer

### ISSUE THREAD

**Issue by DengrongGuan12** [chrislusf/seaweedfs#624]
hi~
I started two master and a filer binded on leader master.
Then I shut down leader master(port:9334) and upload file to another master(port:9333), an error occurred like below:
![image](https://user-images.githubusercontent.com/8155869/35500856-dc8c924e-0512-11e8-8458-4a52879d9d97.png)

Is this a bug or how to avoid single point of failure when using filer?

**Comment by chrislusf** [comment]
need to show how to reproduce this.

**Comment by DengrongGuan12** [comment]
step1:
![image](https://user-images.githubusercontent.com/8155869/35545843-22dd8fa2-05ac-11e8-9e19-7e8a46d82fe9.png)
![image](https://user-images.githubusercontent.com/8155869/35545868-4017077e-05ac-11e8-9164-74f96167735a.png)

We can see master 9333 is leader from below:
![image](https://user-images.githubusercontent.com/8155869/35545893-5e361efc-05ac-11e8-9e4e-a56c82f88194.png)
step 2:
![image](https://user-images.githubusercontent.com/8155869/35546064-3b668ab4-05ad-11e8-9c21-55c0fd867992.png)
step 3:
kill 57132(master on port 9333)
![image](https://user-images.githubusercontent.com/8155869/35546118-88bce2c2-05ad-11e8-98c7-d39bfbb1514f.png)
step 4:
upload file to 9334
![image](https://user-images.githubusercontent.com/8155869/35546146-c5b305d0-05ad-11e8-84f3-b7aee58b81fb.png)

**Comment by chrislusf** [comment]
Need odd number of masters.

**Comment by chrislusf** [comment]
not yet.
