### ISSUE TITLE
freebsd 无法预先分配磁盘.

### ISSUE THREAD

**Issue by fslove** [chrislusf/seaweedfs#625]
未在linux下测试,不知道是不是系统问题.
I0130 00:22:57 53235 store.go:168] In dir /home/data/data adds volume:8 collection: replicaPlacement:000 ttl:
I0130 00:22:57 53235 volume_create.go:14] Preallocated disk space for /home/data/data/8.dat is not supported

**Comment by chrislusf** [comment]
Not supported for non-linux
