### ISSUE TITLE
填充32kb数据5000~8000w后,使用publicurl进行ab压力测试.

### ISSUE THREAD

**Issue by fslove** [chrislusf/seaweedfs#627]
> 随机填充32kb数据5000 ~ 8000w条后,使用publicurl进行下载部分的ab压力测试.
> 少部分时间web交互都是500错误,AB模拟100clinet,10线程并发,weed在freebsd 11下.硬盘是sas并非SSD.
> 有30%的时间是在1 ~ 2000ms内完成.
> 有40%的时间是在5000 ~ 6000ms内完成.
> 有30%的时间是http 500错误.
> 我想问的是,为什么会出现5~6秒的运算过程呢?
> 当然了,测试环境不是localhost或者局域网,tcp建立握手lag约200 ~ 300ms.

**Comment by chrislusf** [comment]
do not know. Not directly related to SeaweedFS
