### ISSUE TITLE
404 without deleting

### ISSUE THREAD

**Issue by thrusong** [chrislusf/seaweedfs#628]
Hello,

Just want to say I absolutely love Seaweed-FS and have been using it successfully for two years.

I'm using it behind a soon-to-launch subscription service and I'd like to be able to "turn off" files without actually deleting them. 

Essentially, I want to serve a "404 - Not Found" if they haven't paid and actually serve the file if their account is in good standing (customers can end their account but pick it up again at any time).

Is there an easy way to accommodate this?

**Comment by chrislusf** [comment]
This can be done by some scripts on nginx in front of SeaweedFS.

**Comment by chrislusf** [comment]
not a feature for SeaweedFS
