### ISSUE TITLE
Raft master election issues when failover occurs

### ISSUE THREAD

**Issue by existemi** [chrislusf/seaweedfs#629]
There seems to be two or possibly more things wrong the the raft implementation:
- if a elected master gets isolated it will remain leader after it gets reconnected to the network, resulting in inability to assign uploads to volumes until a new election takes place.
- if a non-elected isolated master get reconnected to the network, it will imidiately become elected master, resulting in the former master “loosing connection” to the volumes.

Details
---

We are currently testing with a three master setup, running each master like this:
```
weed master -ip 10.1.1.103 -port=9333 -mdir=./master -peers=10.1.1.103:9333,10.1.1.105:9333,10.1.1.105:9334
```
The inital cluster gets booted, with the first master to start becoming leader.

Then we tried to drop all traffic in and out of the first master, which is currently the leader. This results in the isolated master remaining leader:
```
$ curl localhost:9333/cluster/status
{"IsLeader":true,"Leader":"10.1.1.103:9333","Peers":["10.1.1.105:9333","10.1.1.105:9334"]}
```

And the two other masters electing a new leader:
```
master_server.go:91] [ 10.1.1.105:9334 ] 10.1.1.105:9334 becomes leader.
```
(Btw, this message only gets logged on the elected leader, even with `v=3`)
```
$ curl localhost:9334/cluster/status
{"IsLeader":true,"Leader":"10.1.1.105:9334","Peers":["10.1.1.103:9333","10.1.1.105:9333"]}
```

After opening up all traffic again, both leaders remain leaders until next election.

Doing `weed upload` at this moment result in these messages:
```
[{"fileName":"file.tar.gz","error":"/dir/assign result JSON unmarshal error:unexpected end of JSON input, json:"}]
[{"fileName":"file.tar.gz","error":"http://weed-002.site-001.jotta.no:9334/dir/assign : 404 Not Found"}]
```

After a while, 10-20 seconds, all masters again agree and all continues to work.

---

If we then try to isolate a master which is not the current leader, nothing happens. But when we introduce it to the network again, that master immediately becomes leader:
```
master_server.go:91] [ 10.1.1.103:9333 ] 10.1.1.103:9333 becomes leader.
node.go:223] topo:DefaultDataCenter:test-105 adds child 10.1.1.105:8080
master_grpc_server.go:36] added volume server 10.1.1.105:8080
```
The “former” master logging lost volumes resulting in `{"error":"No free volumes left!"}` error messages:
```
master_grpc_server.go:63] lost volume server 10.1.1.105:8080
topology_event_handling.go:52] Removing Volume 54 from the dead volume server 10.1.1.105:8080
volume_layout.go:227] Volume 54 has 1 replica, less than required 2
volume_layout.go:203] Volume 54 becomes unwritable
```

edit: some typos/clarifications

**Comment by existemi** [comment]
Yes I believe this will be the right behavior.

To resolve the 2nd case, it should ensure any current elected master get more votes in the election, so that any newly added masters does not imidiately get elected.

**Comment by chrislusf** [comment]
this should be resolved with the commit
