### ISSUE TITLE
weed upload command in windows upload a file and download it, the filename is file_id

### ISSUE THREAD

**Issue by BloodyKnight** [chrislusf/seaweedfs#632]
in windows when upload a file using weed upload command, the filename is an absolute path, then we download it, the header is as below:
![image](https://user-images.githubusercontent.com/4455405/36660725-21071af4-1b14-11e8-84c9-62a743928069.png)
we can see that the filename is an absolute path, so the downloaded name is invalid and finally it show the file_id.
By the way, linux has no the problem.

**Comment by BloodyKnight** [comment]
PS：when use -dir=xxx paramter it occurs

**Comment by chrislusf** [comment]
added a fix just now. please try it out.

**Comment by BloodyKnight** [comment]
fixed, thanks very much!
