### ISSUE TITLE
restart filer cause error

### ISSUE THREAD

**Issue by mingkeYao** [chrislusf/seaweedfs#633]
because of power fail , I restart my weed on Linux , the Linux commands like the follows:
1)	./weed master -ip=172.16.93.38 -peers=“172.16.93.38:9334,172.16.93.38:9333”
2)	./weed master -ip=172.16.93.38 -port=9334 -peers=“172.16.93.38:9333,172.16.93.38:9334” -mdir=/root/webserver/weed_0.70beta_linux_amd64/master
3)	./weed volume -mserver=172.16.93.38:9333 -dir=“/root/webserver/weed_0.70beta_linux_amd64/data” -ip=172.16.93.38
4)	./weed volume -mserver=172.16.93.38:9333 -dir=“/root/webserver/weed_0.70beta_linux_amd64/data2” -ip=172.16.93.38 -port=8081
5)	./weed filer -master=172.16.93.38:9333 -port=8890 -dir=“/root/webserver/weed_0.70beta_linux_amd64/filert”

the first 4 commands work well , and I can visit localhost:9333 ,it look well.
but the last one above cause an error :
Folder /root/webserver/weed_0.70beta_linux_amd64/filer Permission: -rwxr-xr-x
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x18 pc=0x6da720]

I do not know anything wrong , and I used those commands recently , it worked well.
I want to know how to deal with it.
Or I want to know how to copy the old files in the broken filer to new a new filer by Linux commands.

**Comment by chrislusf** [comment]
Need to see the full error stack.

**Comment by mingkeYao** [comment]
Folder /root/webserver/weed_0.70beta_linux_amd64/filert Permission: -rwxr-xr-x
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x18 pc=0x6da720]

goroutine 16 [running]:
runtime.panic(0xb23960, 0xff5e53)
        /home/chris/apps/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/chrislusf/seaweedfs/go/filer/embedded_filer.(*DirectoryManagerInMap).MoveUnderDirectory(0xc20803c120, 0xc2080373d4, 0x0, 0xc2080373d5, 0x5, 0xc2080373db, 0x0, 0x0, 0x0)
        /home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/seaweedfs/go/filer/embedded_filer/directory_in_map.go:222 +0x220
github.com/chrislusf/seaweedfs/go/filer/embedded_filer.(*DirectoryManagerInMap).processEachLine(0xc20803c120, 0xc2080373d0, 0xb, 0x0, 0x0)
        /home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/seaweedfs/go/filer/embedded_filer/directory_in_map.go:95 +0x4a1
github.com/chrislusf/seaweedfs/go/filer/embedded_filer.(*DirectoryManagerInMap).load(0xc20803c120, 0x0, 0x0)
        /home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/seaweedfs/go/filer/embedded_filer/directory_in_map.go:118 +0x1c6
github.com/chrislusf/seaweedfs/go/filer/embedded_filer.NewDirectoryManagerInMap(0xc2080f80c0, 0x37, 0xc20803c120, 0x0, 0x0)
        /home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/seaweedfs/go/filer/embedded_filer/directory_in_map.go:67 +0x23e
github.com/chrislusf/seaweedfs/go/filer/embedded_filer.NewFilerEmbedded(0x7ffee4bd570d, 0x11, 0x7ffee4bd572f, 0x2f, 0xc208036a64, 0x0, 0x0)
        /home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/seaweedfs/go/filer/embedded_filer/filer_embedded.go:20 +0xcc
github.com/chrislusf/seaweedfs/go/weed/weed_server.NewFilerServer(0xc2080c65a0, 0x22bb, 0x7ffee4bd570d, 0x11, 0x7ffee4bd572f, 0x2f, 0xbc2480, 0x0, 0xbc3c40, 0x3, ...)
        /home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/seaweedfs/go/weed/weed_server/filer_server.go:52 +0x6ea
main.runFiler(0xff3fc0, 0xc20800e050, 0x0, 0x0, 0x0)
        /home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/seaweedfs/go/weed/filer.go:84 +0x2f0
main.main()
        /home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/seaweedfs/go/weed/weed.go:78 +0x612

goroutine 19 [finalizer wait]:
runtime.park(0x42b110, 0xffd168, 0xffabe9)
        /home/chris/apps/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0xffd168, 0xffabe9)
        /home/chris/apps/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
        /home/chris/apps/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
        /home/chris/apps/go/src/pkg/runtime/proc.c:1445

goroutine 20 [syscall]:
os/signal.loop()
        /home/chris/apps/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
        /home/chris/apps/go/src/pkg/os/signal/signal_unix.go:27 +0x32

goroutine 21 [chan receive]:
github.com/chrislusf/seaweedfs/go/glog.(*loggingT).flushDaemon(0x1000a60)
        /home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/seaweedfs/go/glog/glog.go:840 +0x75
created by github.com/chrislusf/seaweedfs/go/glog.init·1
        /home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/seaweedfs/go/glog/glog.go:402 +0x2b2

goroutine 17 [syscall]:
runtime.goexit()
        /home/chris/apps/go/src/pkg/runtime/proc.c:1445

goroutine 25 [select]:
github.com/chrislusf/seaweedfs/go/stats.(*ServerStats).Start(0xc2080f8d80)
        /home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/seaweedfs/go/stats/stats.go:92 +0x385
created by github.com/chrislusf/seaweedfs/go/weed/weed_server.init·1
        /home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/seaweedfs/go/weed/weed_server/common.go:27 +0x43

The information above show as I start the Linux command :
./weed filer -master=172.16.93.38:9333 -port=8890
-dir=“/root/webserver/weed_0.70beta_linux_amd64/filert”

**Comment by chrislusf** [comment]
There should be a file "dir.log" under "/root/webserver/weed_0.70beta_linux_amd64/filert".

It has problem processing one entry started with "mov "

If ok, you can attach the "dir.log" file to this issue.

**Comment by mingkeYao** [comment]
Maybe you are right. I used to use "mov" command by HTTP protocol . But it seemed not work, so I did not notice that any more.
add     /riskFile1      1
add     /riskFile       2
add     /riskFile/120   3
add     /riskFile/121   4
add     /riskFile/122   5
add     /Plan   6
add     /Plan/Template  7
add     /Plan/Template/测试模板 8
add     /Plan/Template/aaa      9
add     /test4  10
del     /test4/
add     /ymk    11
add     /ymk/test4      12
del     /Plan/Template/测试模板/
mov             /ymk/
mov             /       ymk1
add     /Plan/images    13
add     /Plan/images/20180129   14
mov     /ymk/test4      /ymk/
mov             /
mov             /       ymk1
add     /ymk1   15
mov             /ymk1/
mov             /ymk1/
mov             /ymk1/
add     /Plan/Plans     16
add     /Plan/Plans/test预案    17
add     /Plan/Plans/ttt预案     18
del     /Plan/Plans/ttt预案/
add     /Plan/Template/预案模板（测试） 19
add     /Plan/Plans/其他预案（测试）    20
del     /Plan/Plans/其他预案（测试）/
add     /Plan/Plans/撰写预案（测试）    21
mov     /Plan/Template/预案模板（测试）/        /Plan/Template/aaa/
add     /Plan/Template/bbb      22
add     /Plan/Template/bbb123   23
mov     /Plan/Template/bbb      /Plan/Template  bbb1234
mov     /Plan/Template/bbb1234  /Plan/Template  bbb1234321
mov     /Plan/Template/bbb1234321       /Plan/Template  bbb222
mov     /Plan/Template/bbb222   /Plan/Template  bbb222111
mov     /Plan/Plans/test预案    /Plan/Plans     test预案111
del     /Plan/Plans/撰写预案（测试）/
add     /riskFile/117   24
del     /Plan/Template/bbb222111/
del     /Plan/Template/bbb123/
del     /Plan/Template/aaa/预案模板（测试）/
del     /Plan/Template/aaa/
add     /Plan/Template/预案模板（测试） 25
add     /riskFile/124   26
add     /riskFile/125   27
add     /riskFile/126   28
add     /riskFile/127   29
add     /riskFile/130   30
add     /riskFile/131   31
add     /riskFile/132   32
add     /Plan/Plans/综合预案测试        33
add     /riskFile/135   34
add     /PatrolFile     35
add     /PatrolFile/111 36
add     /PatrolFile/111/PO1B01F01L005-排烟风机  37
add     /riskFile/138   38
add     /riskFile/137   39
add     /PatrolFile/112 40
add     /PatrolFile/112/PO1B01F01L005-排烟风机  41
add     /riskFile/139   42
add     /riskFile/144   43
add     /riskFile/145   44
...
There is many "add" logs , and only "add" , so I do not attach them here

**Comment by mingkeYao** [comment]
ok , I remove the "dir.log" file  and restart a filer successfully , it works well. But I find there are no subdirectories in the root of this filer. The follow is the related directory .
![image](https://user-images.githubusercontent.com/33944326/37757634-a4f7fd9c-2de8-11e8-80c8-f5b82df5f115.png)

Maybe I used to change or remove something but I forget now. 
Maybe it is the software's error.
Thank you so much .

**Comment by chrislusf** [comment]
This is a bug for level db implementation. In the soon-to-be-released new filer design, the bug would not be relevant.

However, no direct upgrade path since it is rather complicated.
