### ISSUE TITLE
Volume Marked as Unwritable

### ISSUE THREAD

**Issue by mtolman** [chrislusf/seaweedfs#635]
Hi Chris,
I have found a bug that can cause individual volumes to become unwritable over time -- requiring a restart of seaweedfs to get the volumes back in a writable state. We have seen this in production where you see errors like this in the log file:

"Failed to read file size /tmp/7.dat stat /tmp/7.dat: bad file descriptor"
"failing to assign a file id .../dir/assign: 404 Not Found"

I believe this is caused by a rare case when the os.Stat() method in linux returns an error code because it can't read the size of a file on disk -- perhaps it is in use or something like that. When this happens, the [Size()](https://github.com/chrislusf/seaweedfs/blob/master/weed/storage/volume.go#L58) method in volume.go returns a -1 instead of the actual file size. This -1 is passed along to the master server, and it compares the -1 against the maximum volume size and sees that -1 is greater than the max:

In [CollectDeadNodeAndFullVolumes](https://github.com/chrislusf/seaweedfs/blob/master/weed/topology/node.go#L246), the Size property gets converted from -1 to a uint64...

    if uint64(v.Size) >= volumeSizeLimit

... and so the -1 then becomes the max value of a uint64, and it is always greater than volumeSizeLimit. The master server then considers the volume to be too large and it stops allowing writes to it.

My naive thought for fixing this would simply be to return a 0 instead of a -1 [here](https://github.com/chrislusf/seaweedfs/blob/master/weed/storage/volume.go#L64). That would solve the integer overflow issue. 

I just want to make sure that this sounds like an appropriate fix to you, and ask if you can think of any unwanted side effects that this might cause.

Thanks!
Mike

**Comment by chrislusf** [comment]
Makes great sense! You can create a PR to fix this.
