### ISSUE TITLE
seaweadfs with nginx

### ISSUE THREAD

**Issue by toplinuxsir** [chrislusf/seaweedfs#636]
I want to make the seaweadfs master behind the nginx proxy , The nginx config as below 
```
upstream master {
     server 10.192.2.233:9333;
}

server{
   ####to omit the other config 
  location /upload/fs {
       proxy_pass http://master/;
        proxy_redirect          off;
        proxy_set_header        Host            $host;
       proxy_set_header        X-Real-IP       $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
  }
}
```

But when I access http://nginx-server-ip/upload/fs/submit
the url redirect to http://ningx-server-ip/submit 
How to resovle ? 
Thanks !

**Comment by ozbek** [comment]
This looks like an NGINX configuration related question, i.e., off topic here, but changing `location /upload/fs` to `location /` should help.

**Comment by chrislusf** [comment]
thanks @ozbek !
