### ISSUE TITLE
Cannot build on Windows10

### ISSUE THREAD

**Issue by JonasTan2015** [chrislusf/seaweedfs#639]
Ran this command to build:
Mingw32-make windows_build
Error#1 solved: could not recognize GOOS as an internal command. 
Solution: Changed to   SET GOOS=windows SET GOARCH=amd64.

Error#2: Cannot find Zip as an internal command.
Solution:#2: Download 7zip. Add to PATH

Error#3: Makefile.   rm is not a windows command.

**Comment by chrislusf** [comment]
Please run this on some linux box, which will build for other systems.
