### ISSUE TITLE
How to backup data?

### ISSUE THREAD

**Issue by fedotxxl** [chrislusf/seaweedfs#64]
How can I backup weed data? Suppose I can't stop writes. Can you explain it and add it to docs?

**Comment by chrislusf** [comment]
rsync?

**Comment by fedotxxl** [comment]
How will it work if I add new files to weed every second?

**Comment by aszxqw** [comment]
use `-defaultReplication="002"` , so one file added will lead to three writes to three volume servers.
use two of them to be read , and use the left one as the backup.

**Comment by fedotxxl** [comment]
I wanna have snapshots. If weed / any other process corrupt any file I will be able to restore snapshot.

**Comment by t0mmyt** [comment]
+1 on the backups.

Replication is cool for HA but deletes and corruption is also replicated.  Snapshots (and/or exports potentially readable by something else) would be awesome.

**Comment by chrislusf** [comment]
Here is how to backup data efficiently.

https://github.com/chrislusf/seaweedfs/wiki/Data-Backup

**Comment by sakethsusarla** [comment]
Can I use Restic as a tool to backup and restore data on SeaweedFS? Has anyone already tried it? The TODOs section in the [Data Backup docs page](https://github.com/seaweedfs/seaweedfs/wiki/Data-Backup#todo) of SeaweedFS suggests that restore isn't supported. I'm looking for a warm/hot backup solution for SeaweedFS.

**Comment by chrislusf** [comment]
restic should be supported now. Please help to confirm. And if confirmed, also fix the wiki page?
