### ISSUE TITLE
mount volume

### ISSUE THREAD

**Issue by whynotAC** [chrislusf/seaweedfs#641]
index--->leveldb

operation:
1. unmount volume(vid=3)
2. mount volume(vid=3)

error: 
I0502 16:02:19 03815 disk_location.go:59] new volume 3.dat error resource temporarily unavailable

fix:

add l.volumes[vid].close()  in file storage/disk_location.go  line 171 before delete(l.volumes, vid);

**Comment by chrislusf** [comment]
Create a pull request?
