### ISSUE TITLE
Expanding localized volumes to other regions seems to be impossible

### ISSUE THREAD

**Issue by raffi-semerciyan** [chrislusf/seaweedfs#644]
Hi Chris,

First thank you for this very great system!

We are trying to expand an existing Cluster to other regions and would like the existing data being replicated during that process. But it seems like we are not able to figure out how to do it and whether it is possible to do it.

Let me clarify:

1. Create a simple cluster in Region A with one master and 2 volumes on different rack and replication is 010.
```
Master A  
 |___ Volume A-001-Rack1
 |___ Volume A-001-Rack2
```

2. Import files. These files because of the selected replication level are going to be replicated on both volume servers.

3. Later on, we discovered that we would need these same files in another region B. 
So we create a new cluster in region B
And the Master B is peered with Master A
Volume B servers are peered with Master B locally.

```
Master A  
|      |___ Volume A-001-Rack1
|      |___ Volume A-001-Rack2
|
Master B  
       |___ Volume B-001-Rack1
       |___ Volume B-001-Rack2
```

4. We modify Master A conf file to also have a replication level of 110 and make sure Master B also have this replication level of 110. We restart both masters which are peered with each others.

At this point, we would expect a kind of synchronization of the historical data.

But it seems like once a volume has been created with a given replication level, it will stay with this replication level.

So, would it be possible to follow a specific procedure to modify a local cluster to a multi-region cluster and sync the historical data over this multi-region cluster?

**Comment by chrislusf** [comment]
Use this to change the replication level. https://github.com/chrislusf/seaweedfs/blob/master/unmaintained/change_superblock/change_superblock.go

And then copy the volume files manually.

BTW: usually you need odd number of masters.

**Comment by raffi-semerciyan** [comment]
Awesome Chris! Thanks! Going to try this.

**Comment by raffi-semerciyan** [comment]
Hi Chris. Just to report that it is working.

Just a note however: all the historical volumes became unwritable but their content can be read from any region.

New volumes have been created when uploading new data and are writable.

Note sure whether this is expected behavior.
