### ISSUE TITLE
Migration from Replica level 010 to 210 leads to unwrittable volumes when 3rd region is added

### ISSUE THREAD

**Issue by raffi-semerciyan** [chrislusf/seaweedfs#646]
Hi Chris,

this is a kind of follow up from issue #644  (https://github.com/chrislusf/seaweedfs/issues/644) and believe to have found a bug.

Let me summarize what I'm trying to do.

I started with a single region where I had a replication level of 010  (2 volume servers, one on rack a and another one on rack c) (with seaweed 0.76):

```
Master Region A  
       |___ Volume A-a001 / Rack-a
       |___ Volume A-c001 / Rack-c
```

and want to go to a 3 region replications 210 deployment:

```
Master Region A  
|      |___ Volume A-a-001 / Rack-a
|      |___ Volume A-c-001 / Rack-c
|
Master Region B  
|      |___ Volume B-a-001 / Rack-a
|      |___ Volume B-c-001 / Rack-c
|
Master Region C  
       |___ Volume C-a-001 / Rack-a
       |___ Volume C-c-001 / Rack-c
```
I shutdown ALL the region A servers (master and both volume).
I used the change_superblock successfully to modify the volume .dat files replication level from 010 to 210 on the two volume servers in region A before copying them on their respective volume servers in Region B and C.

I started the 3 masters (one in each region) and they peered properly (I cleaned/erased the data folder of the first master).

Then I started the 2 volume servers in Region A. They properly registered to the cluster and the topology has been updated accordingly.

Then I started the 2 volume servers in Region B. They properly registered to the cluster and the topology has been updated accordingly.

And to my surprise, at this point when I check the cluster status, the 6 volumes I had are writable!

Then when I started the 2 volumes servers in the last region C, then the topology is properly updated but now all the 6 volumes become UNWRITABLE.

At this point the cluster can only be used for reading. It is not possible to create any new file with 

```
curl -X POST http://master-A:9333/dir/assign
```

As response I systematically get is

```
{"error":"Cannot grow volume group! No free volume slot found!"}
```

(I configured maximum 32 volumes so I'm pretty sure there are more rooms left).

If I shutdown all the volume servers of one of the regions server, then the volumes become writable again. 

Do you have an idea of what is going wrong or what I did wrong?

**Comment by chrislusf** [comment]
What're the specific command lines to start the master and volume servers?

**Comment by raffi-semerciyan** [comment]
Hi Chris, 

thanks for your quick response. Please find the desired information:

```
# Master A
weed master -ip=k5-na2-swma-a-001 -port=9333 -mdir=/data/tools/repository/seaweedfs/var/data/master -volumeSizeLimitMB=30000 -defaultReplication=210 -peers=k5-na2-swma-a-001:9333,k5-ap3-swma-a-001:9333

# Master B
weed -log_dir='/data/tools/repository/seaweedfs/var/log' master -ip=k5-ap3-swma-a-001 -port=9333 -mdir=/data/tools/repository/seaweedfs/var/data -volumeSizeLimitMB=30000 -defaultReplication=210 -peers=k5-eu2-swma-a-001:9333,k5-na2-swma-a-001:9333

# Master C
weed -log_dir='/data/tools/repository/seaweedfs/var/log' master -ip=k5-eu2-swma-a-001 -port=9333 -mdir=/data/tools/repository/seaweedfs/var/data/ -volumeSizeLimitMB=30000 -defaultReplication=210 -peers=k5-ap3-swma-a-001:9333,k5-na2-swma-a-001:9333


# Volume A - a
weed volume -mserver=k5-na2-swma-a-001:9333 -ip=k5-na2-swsl-a-001 -port=18080 -dir=/data/tools/repository/seaweedfs/var/data/ -max=32 -rack=a -dataCenter=virginia

# Volume A - b
weed volume -mserver=k5-na2-swma-a-001:9333 -ip=k5-na2-swsl-c-001 -port=18080 -dir=/data/tools/repository/seaweedfs/var/data/ -max=32 -rack=c -dataCenter=virginia

# Volume B - a
weed -log_dir='/data/tools/repository/seaweedfs/var/log' volume -mserver=k5-eu2-swma-a-001:9333 -ip=k5-eu2-swsl-a-001 -port=18080 -dir=/data/tools/repository/seaweedfs/var/data/ -max=32 -rack=a -dataCenter=eu-ireland

# Volume B - b
weed -log_dir='/data/tools/repository/seaweedfs/var/log' volume -mserver=k5-eu2-swma-a-001:9333 -ip=k5-eu2-swsl-c-001 -port=18080 -dir=/data/tools/repository/seaweedfs/var/data/ -max=32 -rack=c -dataCenter=eu-ireland

# Volume C - a
weed -log_dir='/data/tools/repository/seaweedfs/var/log' volume -mserver=k5-ap3-swma-a-001:9333 -ip=k5-ap3-swsl-a-001 -port=18080 -dir=/data/tools/repository/seaweedfs/var/data/ -max=32 -rack=a -dataCenter=ap-singapore

# Volume C - b
weed -log_dir='/data/tools/repository/seaweedfs/var/log' volume -mserver=k5-ap3-swma-a-001:9333 -ip=k5-ap3-swsl-c-001 -port=18080 -dir=/data/tools/repository/seaweedfs/var/data/ -max=32 -rack=c -dataCenter=ap-singapore

```

**Comment by chrislusf** [comment]
The above seems all good. Please show the results these for each server

http://master:9333/dir/status?pretty=y
http://volume:8080/status?pretty=y

**Comment by chrislusf** [comment]
you can store 3 times and store 3 file ids instead of one file id.
