### ISSUE TITLE
is there any api could copy a file

### ISSUE THREAD

**Issue by lycaste** [chrislusf/seaweedfs#649]
i want copy a file with a new url.
i  do not want download first and then  upload....

**Comment by chrislusf** [comment]
do you mean to add a soft link to the file?

**Comment by lycaste** [comment]
@chrislusf 不好意思 英文太蹩脚，怕说不清，我中文描述下，就是文件复制一份，同时重新生成一个新链接，但是这个链接指向的是新的地址。为了在新纪录update文件的时候不影响原来记录的文件

**Comment by chrislusf** [comment]
Interesting idea. There are no good ways to do this yet.
