### ISSUE TITLE
High availability is not available.

### ISSUE THREAD

**Issue by twosunnus** [chrislusf/seaweedfs#652]
使用seaweedfs的时候，线上环境遇到这个问题，不知道是不是weed的bug
3个master节点，27个volume节点
1个master节点所在的虚机挂了，整个集群出现问题，虚机硬重启，整个集群未恢复，重新启动虚机上的master节点，整个集群恢复

启动命令如下：
sudo /home/sw/weed-0.76 -log_dir=/home/sw/logs master -mdir="/home/sw/master" -volumeSizeLimitMB=1000 -ip="192.168.4.35" -ip.bind="192.168.4.35" -port=9333 -peers="192.168.4.43:9333,192.168.4.35:9333,192.168.4.33:9333" -defaultReplication="001" -pulseSeconds=1 &

sudo /home/sw/seaweedfs/weed-0.76 -log_dir=./logs volume -dataCenter=dc1 -rack="rack1" -dir=/data1/seaweedfs,/data2/seaweedfs,/data3/seaweedfs,/data4/seaweedfs,/data5/seaweedfs,/data6/seaweedfs,/data7/seaweedfs,/data8/seaweedfs,/data9/seaweedfs,/data10/seaweedfs,/data11/seaweedfs,/data12/seaweedfs -max=1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000 -idleTimeout=120 -ip="192.168.0.21" -ip.bind="192.168.0.21" -mserver="filestorage.xxxx.com" -port="18081" -pulseSeconds=1 &

query:200qps
save:150qps

**Comment by chrislusf** [comment]
can not help without any details.
