### ISSUE TITLE
AB benchmark stuck if not use -k

### ISSUE THREAD

**Issue by LoginQin** [chrislusf/seaweedfs#659]
There seems to be a problem when use `ab` for benchmark test and not use the `-k` option.

If I use `-k` (HTTP keep alive) for test,  It work fine and very fast! 

But when remove the `-k` option,  It stuck there and very very very slow.... 

I don't know if the production environment will be like that.

I try another version( 0.77 to 0.76,)  Or use in Window, Or Linux (CentOS7.3)    Or use `weed server` Or

start with `master` and `volumn` .... 

The test problem is still there.

Didn't anyone else have a problem like me? 
Is there something wrong with my operation? 
Or maybe I shouldn't care?

**Comment by chrislusf** [comment]
the benchmark is for testing SeaweedFS performance, not the cost of re-establishing connections.
