### ISSUE TITLE
some think or question when i used seaweedfs

### ISSUE THREAD

**Issue by HalfWater** [chrislusf/seaweedfs#662]
非常感谢您提供的seaweedfs，它给我提供了一些便利，也给我带来了一些思考。
thank you for your works of seaweedfs. when i used it, i make my job easy, and get some think and question.

1.根据Dockerfile，您的基础系统镜像使用的alpine，而没有选择最常用的ubuntu，可能是我不太熟悉apline的原因，docker exec -it weed bash，并不能成功执行bash命令，错误如下：
OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"bash\": executable file not found in $PATH": unknown
我猜测可能是因为您使用的基础镜像frolvlad/alpine-glibc:alpine-3.5并没有安装bash。

From the Dockerfile ,your bash image is alpine, not ubuntu, when i execute docker exec -it weed bash, it's failed,the wrong result like this :
OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"bash\": executable file not found in $PATH": unknown
I think it because of the base image frolvlad/alpine-glibc:alpine-3.5 not installed bash tool.

2.当我将seaweedfs运行在远程主机的docker中之后，curl -X POST http://localhost:9333/dir/assign返回的是url与publicUrl是docker ip,而不是宿主机的ip，导致最后客户端(与docker宿主机不是同一台机器)在使用的时候，不能正常发起post请求。
您在https://github.com/chrislusf/seaweedfs/wiki/Getting-Started中的最后提供了一个
docker run --name weed -d -p 9333:9333 -p 8080:8080 \
  -v /opt/weedfs/data:/data cydev/weed server -dir="/data" \ 
  -publicIp="$(curl -s cydev.ru/ip)"
我在run master中加入 -publicIp="hostIp",容器不能正常启动
我没有特别理解，请问是否可以在docker-compose.yml配置或者run中为publicIp加入参数

When i runed seaweedfs in remote machine docker , curl -X POST http://localhost:9333/dir/assign return url and publicUrl is docker container ip, not host machine ip,so that i used in java client( is not docker host machine),cannot post request.
On the last of https://github.com/chrislusf/seaweedfs/wiki/Getting-Started,you provide：
In production
docker run --name weed -d -p 9333:9333 -p 8080:8080 \
  -v /opt/weedfs/data:/data cydev/weed server -dir="/data" \ 
  -publicIp="$(curl -s cydev.ru/ip)"
when i  update it for mine and runed this command , weed cannot run up normaly.
i cannot understand,can config docker-compose.yml or add run variable for publicIp

3.比如我上传了一张图片，要想查看此图片，需要先路由出该volumeId对应的host:port,然后在host:port/fid的方式查看图片，为什么不直接host:9333/fid的方式直接跳转至对应的图片。
我想您可能是基于两方面的考虑，直接交给9333进行路由，一方面会增加master的负载，另一方面则可能master和volume的ip是不一致的。

when i uploaded an image,i want to view this image,i must get host:post for this volumeId，then use
host:ip/fid,why not use masterhost:9333/fid ?
i think it because of:a.Increase the load of master, b.master ip not equals volume ip

4.PUT/POST -F , DELETE 需要url+'/'+fid，而不是masterhost:9333/fid的原因猜测可能跟3是一致的。
   PUT/POST -F , DELETE need url+'/'+fid,why not masterhost:9333/fid ?

不知道对于直接从masterip:9333/fid的方式有没有更好的处理方法。
do you have better solution for masterhost:9333/fid.

**Comment by chrislusf** [comment]
1. the docker configuration is just an example. you can customize it in your own way.
2. I am not familiar with docker myself. Not sure.
3. yes. This is to avoid load on master. The volumeId lookup result can be cached.
4. same as above.
