### ISSUE TITLE
seaweedfs运行在docker之中，返回的是容器ip，而不是宿主机ip，客户端无法直接调用

### ISSUE THREAD

**Issue by HalfWater** [chrislusf/seaweedfs#663]
由于机器数量有限，需要在一台物理机上模拟seaweedfs集群，同时也尝试使用容器化的seaweedfs。

当weedfs运行在远程云服务器的docker中之后，
curl -X POST http://myhost:9333/dir/assign，
返回的url及publicUrl是docker 容器的ip地址，如172.21.0.3的这种ip，如果我的docker环境和我的客户端(java运行时)不在同一个机器，172.21.0.3是无法直接连接的。
请问在未来的weedfs里面会解决这个问题吗？

或者可以通过配置实现返回的url及publicUrl是真实的宿主机ip及端口吗？

通过docker需要解决以下两个问题：
1.在seeweedfs中判断运行时环境是否为docker
2.在获取宿主机host ip机binding port.

有一种比较不优雅的方式是通过在启动容器（docker run）的时候指定环境变量然后判断。
通过环境变量传入docker run --env HOST_IP=192.168.0.160，通过环境变量$HOST_IP获取

**Comment by chrislusf** [comment]
This is a docker question. Use some docker tricks and publicUrl setting.
