### ISSUE TITLE
Grpc Java client block forever while filer server responsed with http1 400 - root cause lies in cmux matcher for grpc 

### ISSUE THREAD

**Issue by pink-lucifer** [chrislusf/seaweedfs#665]
Greetings, 

I am seeing an issue while utilizing grpc java client versus filer server, the java client will block forever... while actually server responsed with an http 1.1 400 bad request.

I have reproduced the issue with grpc helloworld example under [grpc-helloworld](https://github.com/pink-lucifer/seaweedfs-clients/tree/master/experiments/grpc-helloworld)

Is it possible to change the matcher in [filer.go](https://github.com/chrislusf/seaweedfs/blob/master/weed/command/filer.go) to be 
m.MatchWithWriters(cmux.HTTP2MatchHeaderFieldSendSettings("content-type", "application/grpc")
as per note from cmux?

At your convinience, please take a look, thanks in advance!

## Note from cmux [limitation](https://github.com/soheilhy/cmux#limitations)
Java gRPC Clients: Java gRPC client blocks until it receives a SETTINGS frame from the server. If you are using the Java client to connect to a cmux'ed gRPC server please match with writers:

grpcl := m.MatchWithWriters(cmux.HTTP2MatchHeaderFieldSendSettings("content-type", "application/grpc")

**Comment by chrislusf** [comment]
Thanks for debugging and reporting this!

We may need to have a separate port for gRPC because of this and TLS limitations.

Btw: are you just trying to migrate to filer2?

**Comment by pink-lucifer** [comment]
np, i see others made same decision and change,  [dgraph-io issue ](https://github.com/dgraph-io/dgraph/issues/1131).

Not yet tried filer2, i am doing some experiments on this.

**Comment by chrislusf** [comment]
fixed in https://github.com/chrislusf/seaweedfs/commit/299312c8057c5b96f67a8ac825ee026fe01dd8fc
