### ISSUE TITLE
How to migrate from 0.76 to 0.90?

### ISSUE THREAD

**Issue by toplinuxsir** [chrislusf/seaweedfs#668]
How to migrate from 0.76 to 0.90?
Thanks !

**Comment by neiltwist** [comment]
Do you use the filer?

**Comment by chrislusf** [comment]
For multi-master setup, the "weed master -peers" option needs to be a complete list during startup. Same for "weed volume -mserver" option and "weed filer -master" option.

If using filer, see "weed filer -h" and
see https://github.com/chrislusf/seaweedfs/wiki/Directories-and-Files#upgrading-from-previous-filer-storage

**Comment by toplinuxsir** [comment]
I do not use filer ,so th eupgrade is simple ?

**Comment by neiltwist** [comment]
Yes, just make sure to specify all masters in the command used to start both the master and the volume servers.
