### ISSUE TITLE
sometime when a new directory was added , dir.log had repeated records

### ISSUE THREAD

**Issue by mingkeYao** [chrislusf/seaweedfs#669]
as is show at below picture
![image](https://user-images.githubusercontent.com/33944326/42072517-7cf08334-7b93-11e8-8a0c-4a038f5da9c3.png)

and then filer can't start . 
The tips as below 
![image](https://user-images.githubusercontent.com/33944326/42072510-7327ef86-7b93-11e8-83b3-cea70d7b9b6c.png)

**Comment by chrislusf** [comment]
If this is the case, you can manually edit the dir.log and remove the duplicates.

You are using a version before 0.90. Please try the latest one which has totally different filer design.

The downside of the different design is that the filer upgrade is difficult.
