### ISSUE TITLE
-whiteList is not working on SeaweedFS

### ISSUE THREAD

**Issue by ijunaid8989** [chrislusf/seaweedfs#672]
We have one master started as a filer at port 8888, and 4 volumes, (5th volume is master its self.)

master IP: 94.xxx.xxx.56

the application IP which making request to the master filer: 88.xx.xxx.251

On master configuration, I added this at the end of the command.

```
-whiteList="88.xx.xxx.251,94.xxx.xxx.56"
```

and on Volume configuration, I added this.

```
-whiteList="94.xxx.xxx.56"
```

Restarted master and all volumes. I tried to delete a file from master filer from my local machine, It deleted and then I tried to add the same file through curl from the local machine, It added as well. Even my local IP was not listed in `-whiteList`

**Comment by chrislusf** [comment]
You would need to print some messages to debug here: https://github.com/chrislusf/seaweedfs/blob/master/weed/security/guard.go#L98

**Comment by chrislusf** [comment]
any updates?

**Comment by ijunaid8989** [comment]
I don't know anything about go. So It's not possible for me.

**Comment by ijunaid8989** [comment]
I have added logging using
```
fmt.Fprintf(g.whiteList, "whiteList:\n")
```
and
```
host, err := GetActualRemoteHost(r)
fmt.Fprintf(host, "host request:\n")
```
and build the project also tested it in production, Control never came to this point.

I have tried to remove double quotes as well from ip string as 
```
-whiteList=88.xx.xxx.251,94.xxx.xxx.56
```
It didn't work in version 76. Also. in any way, it should come to this point, if the -whiteList param has been added.

```
fmt.Errorf("Not in whitelis: %s", r.RemoteAddr)
```

with this message: `{"error":"http://localhost:9333/dir/assign: 401 Unauthorized"}` but it doesn't come to that point.

**Comment by ijunaid8989** [comment]
I kind of find a bug in this.

The issue was: I was listing the same IP address to whiteList to which seaweedfs has been deployed.

Our seaweedfs has been deployed to this IP `94.xxx.xxx.56` and I also placed it for whiteList as well with another IP.
But seaweedfs was considering it as a localhost?  and Accepting requests requests from my local machine? Is that possible? I just removed its own IP and and now on a request from my local machine it gave me an error as

{"error":"http://94.xxx.xxx.56:9333/dir/assign: 401 Unauthorized"}

**Comment by chrislusf** [comment]
I see. The operation from filer are sent to the master and volume servers, but the filer is on the whitelisted server.

**Comment by ijunaid8989** [comment]
Yes, the server which is filer too is whiteListed, and It happened to be the same IP on which it was started but my IP was 101.53.241.106, it was not in the whitelist, but it accepted it considering it as a localhost to the same IP it was deployed.

**Comment by ijunaid8989** [comment]
Plus. 

I removed Master Filer's own IP from -whiteList, which was `94.xxx.xxx.38`

it started giving error as
```
0712 14:25:40 20225 guard.go:130] Not in whitelist: 94.xxx.xxx.38:59332
I0712 14:25:40 20225 filer_server_handlers_write.go:100] failing to assign a file id http://94.xxx.xxx.38:9333/dir/assign: 401 Unauthorized
```

So In short, If I remove the server own IP, It doesn't let make any request. and If I put the IP in -whiteList, any request from localhost is acceptable.

**Comment by chrislusf** [comment]
The whitelist on volume servers is going to be deprecated in coming releases.

See https://github.com/chrislusf/seaweedfs/wiki/Security-Overview
