### ISSUE TITLE
How can I get fid after batch uploading files?

### ISSUE THREAD

**Issue by guoshuman** [chrislusf/seaweedfs#673]

**Comment by chrislusf** [comment]
how do you do the batch upload? It should tell you the fid during the upload progress.

**Comment by guoshuman** [comment]
Sorry,I think I might have referred to a wrong blog.
Besides,Is there a mistake in this order：
`weed upload -server=localhost:9333 -dir=one_directory -include=*.pdf`
I think it shuld be
`weed upload -master=localhost:9333 -dir=one_directory -include=*.pdf`
![image](https://user-images.githubusercontent.com/24473758/42364191-e82e9f7a-812c-11e8-9697-422ed7da0c8b.png)

**Comment by chrislusf** [comment]
just do "weed upload -h", you will see the options to use for your current binaries.
