### ISSUE TITLE
some error  when copy files from local directory to weed mount diretory

### ISSUE THREAD

**Issue by accumulatepig** [chrislusf/seaweedfs#674]
In weed mount log, print some errors like this:  

2018/07/05 18:21:03 fuse: panic in handler for Write [ID=0x9d435 Node=0x8da7 Uid=205 Gid=205 Pid=113595] 0x4 7268 @0 fl=0 lock=0 ffl=OpenWriteOnly: ru
ntime error: invalid memory address or nil pointer dereference
goroutine 4935620 [running]:
bazil.org/fuse/fs.(*Server).serve.func2(0xecc900, 0xc00029c380, 0xc00166def8, 0xc00166de77)
        /home/travis/gopath/src/bazil.org/fuse/fs/serve.go:857 +0x1ac
panic(0xcb7ca0, 0x1507d10)
        /home/travis/.gimme/versions/go/src/runtime/panic.go:494 +0x1b9
github.com/chrislusf/seaweedfs/weed/filesys.(*FileHandle).Write(0xc002ae7e00, 0xecff40, 0xc0055896c0, 0xc00029c380, 0xc001527f58, 0x47e401, 0x0)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/filesys/filehandle.go:148 +0x5b2
bazil.org/fuse/fs.(*Server).handleRequest(0xc0002700c0, 0xecff40, 0xc0055896c0, 0xec4cc0, 0xc0039f99a0, 0xc01752e100, 0xecc900, 0xc00029c380, 0xc00166
def8, 0xec4860, ...)
        /home/travis/gopath/src/bazil.org/fuse/fs/serve.go:1265 +0x158e
bazil.org/fuse/fs.(*Server).serve(0xc0002700c0, 0xecc900, 0xc00029c380)
        /home/travis/gopath/src/bazil.org/fuse/fs/serve.go:878 +0x410
bazil.org/fuse/fs.(*Server).Serve.func1(0xc0002700c0, 0xecc900, 0xc00029c380)
        /home/travis/gopath/src/bazil.org/fuse/fs/serve.go:425 +0x6e
created by bazil.org/fuse/fs.(*Server).Serve
        /home/travis/gopath/src/bazil.org/fuse/fs/serve.go:423 +0x31e

something wrong during the copy process?

**Comment by chrislusf** [comment]
which version did you use?

**Comment by accumulatepig** [comment]
0.9 version
https://github.com/chrislusf/seaweedfs/releases/download/0.90/linux_arm64.tar.gz

**Comment by accumulatepig** [comment]
0.9 version
https://github.com/chrislusf/seaweedfs/releases/download/0.90/linux_amd64.tar.gz

**Comment by chrislusf** [comment]
Added a fix to a possibly nil variable. Do you have some way to reproduce this?

**Comment by accumulatepig** [comment]
yes , write a shell to loop copy files from local directory to weed mount directory, it will be reproduced.

**Comment by chrislusf** [comment]
can you please check whether the fix works?
