### ISSUE TITLE
support 128 bit needle id

### ISSUE THREAD

**Issue by chrislusf** [chrislusf/seaweedfs#675]
a file key is a tuple of <volume number, needle id,  cookie>

some users want to use their own needle id, which can be 128 bit UUID.

**Comment by chrislusf** [comment]
related to https://github.com/chrislusf/seaweedfs/issues/528

**Comment by chrislusf** [comment]
see https://github.com/chrislusf/seaweedfs/wiki/Optimization#customize-needle-id-to-128-bit

fixed by commit https://github.com/chrislusf/seaweedfs/commit/495a77667156e56e4c666bf809f4a1795bbd1d4c

**Comment by andreak** [comment]
> see https://github.com/chrislusf/seaweedfs/wiki/Optimization#customize-needle-id-to-128-bit
> 
> fixed by commit [495a776](https://github.com/chrislusf/seaweedfs/commit/495a77667156e56e4c666bf809f4a1795bbd1d4c)

There's no section #customize-needle-id-to-128-bit
Can you explain in detail how to use SeaweedFS with UUID?
Thanks.

**Comment by chrislusf** [comment]
This feature has been removed since nobody used it.

**Comment by andreak** [comment]
Ok
