### ISSUE TITLE
just show 1000 files  when ls weed mount  directory

### ISSUE THREAD

**Issue by accumulatepig** [chrislusf/seaweedfs#676]
when exec linux shell command ls in weed mount directory , just 1000 files limited to show? does any way to show more? thks

**Comment by chrislusf** [comment]
the linux shell command does not have any way to paginate through all the files.

this can be a setting in filer server. currently it is hard coded to 1000

**Comment by chrislusf** [comment]
added filer option to adjust the dir listing size limit in commit https://github.com/chrislusf/seaweedfs/commit/702ff48cdac224e0ec9f8b9f03591785496e5874

**Comment by accumulatepig** [comment]
what's the rule to show the 1000 files ,  By lastest create time or file name  ....?  thks
