### ISSUE TITLE
你好，问下Volume Server 参数 -max=100没起作用？

### ISSUE THREAD

**Issue by PoplarDddCN** [chrislusf/seaweedfs#677]
/weed volume -max=100 -mserver="localhost:9333" -dir="./data"

服务开启了，/data目录下只有 1.dat ~ 7.dat，请问在什么情况下会用到 8.dat ..... 100.dat？

**Comment by chrislusf** [comment]
see https://github.com/chrislusf/seaweedfs/wiki/Optimization#increase-concurrent-writes
