### ISSUE TITLE
filer能够对volumne进行健康检查

### ISSUE THREAD

**Issue by qszxnp** [chrislusf/seaweedfs#678]
hi，filer我觉都可以添加一个检查volume是否存活的功能，例如当一个collection的rc是010的时候，挂掉一个volume，这个collection内的文件虽然在另一个volume里面存在，但是用filer接口（http://127.0.0.1:8888/filename）访问的时候，会出现时好时坏的效果，可以考虑在filer上加入对volume的健康检查

**Comment by qszxnp** [comment]
英语有点渣，见谅。。。我怕用英语写出来自己都看不懂

**Comment by qszxnp** [comment]
刚看到filer有一个10分钟的刷新机制，

**Comment by chrislusf** [comment]
still an issue or not?
