### ISSUE TITLE
copying 7 volumes server's data to one master with POST

### ISSUE THREAD

**Issue by ijunaid8989** [chrislusf/seaweedfs#679]
We have 2 masters with 3 volumes and 4 volumes each with version 76. We are now going to start a new master with version 90. and start recording on it.

Beside recording from live cameras, we are going to use POST method to copy a file from the old master and move it to the new master with the same directory structure.

My question is: Can seaweedfs single master v90 can bear 1000 requests per second?

**Comment by chrislusf** [comment]
depends on your requests. there are no performance change in terms of serving traffic.
