### ISSUE TITLE
crash when export(version 0.90)

### ISSUE THREAD

**Issue by wjx0912** [chrislusf/seaweedfs#681]
http://101.200.50.71/seaweedfs01.png

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8e04b0]

**Comment by chrislusf** [comment]
Not reproducible. Please try the latest code and add some debug messages? It is having difficulty to open file 1.dat

**Comment by chrislusf** [comment]
seems no updates and can not reproduce.
