### ISSUE TITLE
delete collection permanently？

### ISSUE THREAD

**Issue by qszxnp** [chrislusf/seaweedfs#682]
As i use api:http://localhost:18080/admin/delete_collection?replication=000 to delete an collection,the writables volume would be remove but the collection i deleted is still here when i call " curl http://127.0.0.1:9333/dir/status?pretty=y"

    so is there any other api to delete collection ?

**Comment by chrislusf** [comment]
added fix https://github.com/chrislusf/seaweedfs/commit/f7afa802505a27bb42647e5b50d30af567b88eed
