### ISSUE TITLE
An advise to improve weedmount write file performence in multiple dc architecture

### ISSUE THREAD

**Issue by accumulatepig** [chrislusf/seaweedfs#683]
when write a file by weedmount , a request will be send to master to get the fileIDs,  if the volumeserver  is assigned to the same dc with weedmount client  priority , it will be improve the write perfomence . but if the same dc volumeserver is not ailviliable or not find, another dc volumerserver will be assigned .

**Comment by chrislusf** [comment]
Is this what you want? https://github.com/chrislusf/seaweedfs/blob/master/weed/operation/assign_file_id.go#L31

**Comment by accumulatepig** [comment]
Weed mount doesn't have the datacenter flag, how do you know the weedmount client and volumeserver  in the same data center,  and assign the volumerserver to weedmount client to write?
