### ISSUE TITLE
filer delete directory cache when delete directory throught api

### ISSUE THREAD

**Issue by qszxnp** [chrislusf/seaweedfs#684]
i think it is a bug, reproduce method：
1、create a file：curl -F file=@abc "http://localhost:8888/dir/"
2、delete file and dir：
    a）curl http://localhost:8888/dir/abc    -X DELETE
    b)  curl http://localhost:8888/dir    -X DELETE
3、create file again：curl -F file=@abc "http://localhost:8888/dir/"
4、list dir curl http://localhost:8888/dir  -H "Accept: application/json"
 and you would get 404

i think the reason is cacheDirectory，i would be fix by delete cache when delete dir

**Comment by qszxnp** [comment]
i add a cacheDelDelDirectory in func (f *Filer)DeleteEntryMetaAndData can fix this bug

**Comment by chrislusf** [comment]
send a pull request?

**Comment by qszxnp** [comment]
https://github.com/chrislusf/seaweedfs/pull/686
