### ISSUE TITLE
About weed filer -dirListLimit   limit sub dir listing size

### ISSUE THREAD

**Issue by accumulatepig** [chrislusf/seaweedfs#696]
weed filer -dirListLimit   limit sub dir listing size ,but  just show the oldest file ,does any display rules can be set ,like by create time desc or asc , file name etc...   thks

**Comment by chrislusf** [comment]
It is sorted by name

**Comment by chrislusf** [comment]
which filer store did you use?

**Comment by accumulatepig** [comment]
https://github.com/chrislusf/seaweedfs/releases/download/0.91/linux_amd64.tar.gz

0.91 version ,thks

**Comment by accumulatepig** [comment]
could you add some rules to set, like create time  desc or asc

**Comment by chrislusf** [comment]
do not support other ordering. It would not be efficient if list size is big.

which filer store did you use? Cassandra? Redis? MySql? PostSql? LevelDB?

**Comment by accumulatepig** [comment]
myqsl  and when I use weed mount to show the files by ls ,  i just wanna get the lastest dirListLimit size file

**Comment by chrislusf** [comment]
It would not be efficient to do so. However, you can customize the code to create your own adapter to do this.

add a create time column and sort by that column.
https://github.com/chrislusf/seaweedfs/blob/master/weed/filer2/mysql/mysql_store.go
