### ISSUE TITLE
Content-Type header cause upload failure for filer

### ISSUE THREAD

**Issue by sriki77** [chrislusf/seaweedfs#698]
The following multipart upload fails because of the no space after semi colon before boundary

```
POST /test/20180724?collection=test_files HTTP/1.1
Host: 127.0.0.1:8888
Accept: */*
Content-Length: 185
Content-Type: multipart/form-data;boundary=------------------------4635620c85f0c23f

--------------------------4635620c85f0c23f
Content-Disposition: form-data; name="file"; filename="out.txt"
Content-Type: text/plain


--------------------------4635620c85f0c23f--

```
The above result in `HTTP 500 `with the following error in logs

`I0726 21:13:11 89272 filer_server_handlers_write.go:180] Can not to write to folder /test/20180724/ without a file name!
`

The issue is no space between `; `and `boundary`

Following fails
`Content-Type: multipart/form-data;boundary=------------------------4635620c85f0c23f`

Following works
`Content-Type: multipart/form-data; boundary=------------------------4635620c85f0c23f`

**Comment by chrislusf** [comment]
which client did you use? I wonder whether this is a bug or just trying to handle existing implementations.

**Comment by sriki77** [comment]
I am using spring rest template of Java Spring. The rest template does not put a space, while the curl command does. I tried the upload without the space on some other web server, it worked - but failed on seaweedfs

**Comment by chrislusf** [comment]
can you give specific file names, e.g. write to "/test/20180724/out.txt?collection=test_files" ?

**Comment by chrislusf** [comment]
please create some reproducible case. the problem seems to be somewhere else.

**Comment by chrislusf** [comment]
If the test case can be in Go and be part of the unit test, it would be helpful to ensure future correctness. If not, we can skip it for now.
