### ISSUE TITLE
docker运行，上传文件出现一点问题

### ISSUE THREAD

**Issue by chenxushuo** [chrislusf/seaweedfs#699]
上传文件以后变成了这样：
^B^@^@^@^@^@^@^@^U^US|^@^@^@^@^@^@^@^A^@^@^A)^@^@^@×------------------------------870660c03d56^M
Content-Disposition: form-data; name="file"; filename="123.txt"^M
Content-Type: text/plain^M
^M
123123123
123123123
123123123
^M
------------------------------870660c03d56--^M
^N^@Fmultipart/form-data; boundary=----------------------------870660c03d56^@[Zê(âÅC^S[Zê

导致获得文件的时候无法识别。
123123123
123123123
123123123
为原文件内容

**Comment by chrislusf** [comment]
Please make a reproducible case.

**Comment by chenxushuo** [comment]
I just run it in simple mode：
docker run --rm -v /data/weedfs:/data -p 9333:9333 --name master chrislusf/seaweedfs master
docker run --rm -v /data/weedfs:/data --link master:master -p 8080:8080 chrislusf/seaweedfs volume -dir=/data -max=100 -mserver="master:9333" -port=8080

curl http://192.168.1.219:9333/dir/assign
curl -X PUT -F file=@./123.txt http://192.168.1.219:8080/7,01e40165b0

“192.168.1.219“ is  the host ip；
-----------------------------------------------------------
And  run weed （v9.2）in host mod，everything war ok！

**Comment by chrislusf** [comment]
Use
curl -F file=@./123.txt http://192.168.1.219:8080/7,01e40165b0

Only POST support multipart

https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST

GET does not
https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/GET

**Comment by chenxushuo** [comment]
3Q verymuch！
