### ISSUE TITLE
Redis的value值该怎么解码

### ISSUE THREAD

**Issue by guoshuman** [chrislusf/seaweedfs#700]
![image](https://user-images.githubusercontent.com/24473758/43308563-942983c0-91b4-11e8-9980-dab3ccf49931.png)
请问利用filer.copy上传图片后，存入redis的值是怎么存入的呀，该怎么解码，我在wiki中找不到，也不是很会看源码。

**Comment by chrislusf** [comment]
see func (entry *Entry) EncodeAttributesAndChunks() at https://github.com/chrislusf/seaweedfs/blob/98110c16970a1c231a5cc04e0eb85ec48d649e14/weed/filer2/entry_codec.go#L12

encoded as https://github.com/chrislusf/seaweedfs/blob/master/weed/pb/filer.proto Entry message.

**Comment by guoshuman** [comment]
好的，谢谢
