### ISSUE TITLE
automatic add file header?

### ISSUE THREAD

**Issue by wjx0912** [chrislusf/seaweedfs#703]
my command:
curl.exe -X POST  http://192.168.10.163:9333/dir/assign
curl.exe -X PUT -F file=@C:\Users\wyt\Desktop\label_map.pbtxt  http://192.168.10.163:39071/3,2eb0308e7a

**after i upload file, then download it,  i find three line automatic add to the begin of file:**

`--------------------------2b478d5e450ec9f3

Content-Disposition: form-data; name="file"; filename="label_map.pbtxt"

Content-Type: application/octet-stream
`

**why automatic add the three line? how to remove it?**

**Comment by chrislusf** [comment]
Do not use put. Only post support multipart.
