### ISSUE TITLE
想请教一个拓扑结构上的问题

### ISSUE THREAD

**Issue by guoshuman** [chrislusf/seaweedfs#704]
dataCenter，Rack的数量是不是会影响上传速度。
我用weed upload批量上传文件，一个文件夹下有10w个300KB左右的小文件，上传了一天也才到3000w条数据，请问是不是有可能和开启的集群结构有关。
开启的集群结构是（两台数据存储的服务器）：1个dc，两个rack，每个rack开启12个volume服务，每个volume服务上最多有50个volume。

**Comment by chrislusf** [comment]
只和replication有关
