### ISSUE TITLE
Can you please share a Redis Cluster filer configuration example? Thanks

### ISSUE THREAD

**Issue by meirhazon1** [chrislusf/seaweedfs#705]
Hello,
Can you please share a Redis Cluster filer configuration example?
The following is for a single redis node, what is the configuration for a redis cluster?

[redis]
enabled = true
address  = "10.132.0.22:6379"
password = ""
db = 0
 
Thanks so much,
Meir

**Comment by chrislusf** [comment]
I do not know how to setup a redis cluster in the first place.

**Comment by meirhazon1** [comment]
Hi,
If I understand correctly, there is no way to configure the file filer.toml to support redis cluster?
Can I have multiple servers in the address line? how will multiple addresses be treated by the filer?

[redis]
enabled = true
**address = "10.132.0.22:6379"**
password = ""
db = 0

thank you
