### ISSUE TITLE
[help wanted] Trying to setup peers while setting up master

### ISSUE THREAD

**Issue by PragatiGarg** [chrislusf/seaweedfs#708]
**Description**
I am trying to set up a failover master system. I am getting an error while weed is trying to elect a leader. Please find attached a screenshot of the error
 
**System Setup**
Command Line to start master: ./weed master -port=9333 -mdir=./mdata -peers=206.189.141.222:9333,206.189.131.111:9333,206.189.141.192:9333

**Expected behaviour**
A weed server is expected to start with peers and a leader elected

**Screenshots**
![image](https://user-images.githubusercontent.com/12114615/44194687-5cbcc500-a154-11e8-82b9-5dce4bd71fba.png)

**Comment by chrislusf** [comment]
set master ip address also

**Comment by PragatiGarg** [comment]
Thank You!
