### ISSUE TITLE
Backup from SeaweedFS Filer to S3 or Google Cloud Storage or Azure

### ISSUE THREAD

**Issue by chrislusf** [chrislusf/seaweedfs#709]
Although cloud storage is slow, it is cheap, and upload is free. Backing up to cloud is financially a good choice.

Currently SeaweedFS Filer supports sending notifications to Kafka. It is possible to subscribe to the kafka topic and send files changes to the cloud.

**Comment by gedw99** [comment]
Is it possible to swap the broker used ? I would like to use NATtS streaming instead.

**Comment by ijunaid8989** [comment]
As you are supporting filer.toml file for giving filer options and picking the file from `/etc/seaweefs` also we need to specify the filer location by ourselves now.

Can you think of an option like, for example as user choose leveldb. and want to specify the location to AWS? We are always very keen to create backups of the filer, on each Sunday. But sometimes it works and sometimes it's not. Also with time filer's size get increased its approx 90GB right now. Would that be possible so we can just send filer to some other location where it cannot get lost at any cost? like any option to save it to another server or storage box or AWS s3? Or you can give some better opinion on that? We are about to go in production with v.097. I am just exploring what are the new option we can use to make it better one.

**Comment by chrislusf** [comment]
@gedw99 the broker is in a plugin style. You are welcome to add your own implementation. https://github.com/chrislusf/seaweedfs/tree/master/weed/notification

**Comment by chrislusf** [comment]
@ijunaid8989 the filer.toml can be in current folder, $home/.seaweeedfs, or /etc/seaweedfs/ We can add an option to specify the filer.toml directly later.

Current implementation support filer1 -> kafka -> filer2 already. Adding S3 backup is working in progress.

**Comment by ijunaid8989** [comment]
@chrislusf Thanks for your answer, I hope you understand what I actually mean to say. 

S3 backup meant to be for filer folder? or for the whole server with idx and dats? My current situation is to save the filer as it grows , somewhere else other than the actual server, so if server goes down we have filer to continue with other volume servers

**Comment by chrislusf** [comment]
s3 backup is for filer. Kind of one-directionally sync any filer folder (or root folder) to a folder under an S3 bucket

**Comment by ijunaid8989** [comment]
@chrislusf That will be awesome, when do you think we can have this feature in working form? that would be an amazing feature to have.

**Comment by ijunaid8989** [comment]
@chrislusf Okay just to get into your account, we are doing filer backups and once we backed up filer without stopping it first. and that backup filer didn't work.

Then we stopped it first and then backed up. and it worked.

As you have added syncing, and of course its runtime, will that synced filer will work?

**Comment by chrislusf** [comment]
@ijunaid8989 filer replication works in near real time. Now it passed my initial tests.

It can replicate to

- Anther filer
- AWS S3
- Google Cloud Storage

**Comment by ijunaid8989** [comment]
https://github.com/chrislusf/seaweedfs/commit/a5b5887efce03252b0f64b9918e81a0ea59beac7

Sounds good but are you checking the integrity of the filer files? I mean As we are using leveldb for the filer. and In past, one of the seaweedfs masters got crashed and it happened to be an embedded filer as well, v74. When we recovered the storage drive, all leveldb files happened to be corrupt and as a matter of fact, files can get corrupt in any way, so what is the strategy of filer sync? Do you also check either is a valid file to sync it to s3 or any storage or just what it generates, will go to s3?

**Comment by chrislusf** [comment]
It's processed in a streaming way. When filer data is changed, it will be replicated to S3 in a few seconds. If filer is corrupted later, the change would not propagate downstream since the replicator would not be able to read the updated file.
