### ISSUE TITLE
upgrade 0.91 to 0.93

### ISSUE THREAD

**Issue by accumulatepig** [chrislusf/seaweedfs#711]
My current version is 0.91 ,and weed master、volume 、filer、mount  are in use , i wanna upgrade to 0.93 ,  is it the right way to restart everything with the weed  latest version ?
thks

**Comment by chrislusf** [comment]
mostly yes. maybe verify the command line options are still the same.

**Comment by accumulatepig** [comment]
thank you , i will try it
