### ISSUE TITLE
version 0.93, Filer can not open uploaded files in web browser.

### ISSUE THREAD

**Issue by fengyuad** [chrislusf/seaweedfs#712]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**
Version 0.93, filer can upload files and can use file-id to get the file content directly from volume server , however, it can not open uploaded files in web browser when click on the file. If files were uploaded through old versions of filer, the current version of filer would still open it in the web browser.

**System Setup**
Filer: args: ["-log_dir", "/var/containerdata/logs",  "-v","4","filer", "-port", "8888", "-master","master1_ip:9333,master2_ip:9333,master3_ip:9333","-ip","filer_ip","-defaultReplicaPlacement","200"]

Master:
 args: ["-log_dir", "/var/containerdata", "-v","4", "master", "-port", "9333", "-mdir", "/var/containerdata", "-peers","master1_ip:9333,master2_ip:9333,master3_ip:9333","-ip","master1_ip","-defaultReplication","200"]

Volume:
args: ["-log_dir", "/var/containerdata",  "-v","4","volume", "-port", "8080", "-mserver", "master1_ip:9333,master2_ip:9333,master3_ip:9333","-dir", "/var/containerdata","-max","100","-dataCenter","dc1","-ip", "volume1_ip","-idleTimeout","3"]

To Upload files:
 curl -F file=@filename "http://filer_ip:8888/directory/filename/"

To Find uploaded files in the web browser:
type url: filer_ip, select the uploaded files in the list and click on it.

**Expected behavior**
Files should be open and readable from web browser if uploaded through filer.

**Comment by chrislusf** [comment]
please add steps show your command lines to upload files.

**Comment by chrislusf** [comment]
What's your file type? Try some text file first.

**Comment by chrislusf** [comment]
I think your problem happens when the very first time to upload a file.

There is a commit https://github.com/chrislusf/seaweedfs/commit/76cbe8bf3371fbdbb65cf13fe0d767164b53b151 for this.

Let me know whether this is the case.

**Comment by Eloahman** [comment]
The same problem.
Upload success through filer and file can be listed by filer but can not be achieved by filer.
```
nohup ./weed server -master.port=9333 -volume.port=8081 -dir="./data" -filer=true 2>&1 &
```
My run command.

**Comment by chrislusf** [comment]
@Eloahman what's the version you are using?

**Comment by Eloahman** [comment]
@chrislusf 
0.94 linux amd64
With Ubuntu 16.04

**Comment by chrislusf** [comment]
@Eloahman please try out 0.95. This should be related to a data racing problem when the first few volumes are created.
