### ISSUE TITLE
Can not open uploaded file

### ISSUE THREAD

**Issue by suoigwg** [chrislusf/seaweedfs#716]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**
I ran `./weed master` and `./weed volume -dir="./tmp" -max=5 -mserver="localhost:9333" -port=8080` on my machine followed by 
`curl -X POST http://localhost:9333/dir/assign`
Then I put a file by
`curl -X PUT -F file=@/hom/Users/user/Desktop/test.png  http://127.0.0.1:8080/5,01b3767907`
However when I tried 
`wget  http://localhost:8080/5,01b3767907 -o test.png `
When I tried to open in, I got 
`It may be damaged or use a file format that Preview doesn’t recognize.`

**System Setup**
macOS 10.13.6 with latest binary 
**Expected behavior**
I expect to see the picture a put
**Screenshots**

**Additional context**

**Comment by chrislusf** [comment]
use HTTP POST, not HTTP PUT, when uploading files.

` curl -F file=@/hom/Users/user/Desktop/test.png http://127.0.0.1:8080/5,01b3767907`
