### ISSUE TITLE
about volumeId health detected

### ISSUE THREAD

**Issue by accumulatepig** [chrislusf/seaweedfs#720]
version: 0.94
when i removed a volume id's dat and idx file,  the file on the volumeId also can be read from weed mount directory (maybe cache in memory?), and curl  http://xxx:9333/dir/status?pretty=y shows the volumeId also can be writable  ,  it means the volumeID can be allocated to write a file, then write a.txt file to the volumeid shows success(actual in cache not flush to disk?) ,and read succes now, but when restart the volume server directly or copy the volumeid back before restart,  Input/output error shows when read a.txt from weed mount directory ,the a.txt file lost

**Comment by chrislusf** [comment]
maybe make sure the .dat and .idx files are not removed.

**Comment by accumulatepig** [comment]
Similar scenarios may also have the same problem ， like  dat file  corrupt, the file write to the corrupt volumeId maybe lost

**Comment by accumulatepig** [comment]
@chrislusf   no mechanism to confirm the volumeId actual can be write before allocate the volumeid,  
This is not the most important issue，the issue is the file write to the allocate unhealthy(maybe file corrupt or deleted..etc) volumeid success(application also believes that success ), actually, It didn’t write to volume disk at that moment,when restart volume server , the file lost . File loss is intolerable for file system because of  own mechanism.     when the file write to the the unhealthy volumeid should return fail errors immediately ,so the application can be sense that
