### ISSUE TITLE
Filer fails when saving files with more than 2 folders deep hierarchy

### ISSUE THREAD

**Issue by ChecksumDK** [chrislusf/seaweedfs#723]
Hi 
I am using the ver. 0.95 windows_amd64 binaries and have the following problem:

- C:\Program Files\SeaweedFS>curl -F "filename=@filer.toml" "http://localhost:8888/changelog/123/"              - Works. File and folders are visible in filer
- C:\Program Files\SeaweedFS>curl -F "filename=@filer.toml" "http://localhost:8888/changelog/123/test.toml"     - Works. File and folders are visible in filer
- C:\Program Files\SeaweedFS>curl -F "filename=@filer.toml" "http://localhost:8888/changelog/123/C01/"          - File is uploaded, but C01 folder is not visible in filer
- C:\Program Files\SeaweedFS>curl -F "filename=@filer.toml" "http://localhost:8888/changelog/123/C01/test.toml" - File is uploaded, but C01 folder is not visible in filer

**Comment by ChecksumDK** [comment]
It works with version 0.77

**Comment by chrislusf** [comment]
I followed the exact steps and can not reproduce.

**Comment by ChecksumDK** [comment]
The problem is reproducible for me. I am using local db. I am running weed on a windows server 2012 64 bit. Weed is started like this: 
`weed.exe server -dir="C:\ProgramData\SeaweedFS\data" -filer=true -master.port=9333 -volume.port=8080`
filer.toml: [filer.toml.txt](https://github.com/chrislusf/seaweedfs/files/2360300/filer.toml.txt)

Can I turn on some kind of debug logging? Do you need more information?

**Comment by chrislusf** [comment]
Does it happen for lower cased folder names? eg. c01, not C01?

**Comment by ChecksumDK** [comment]
Yes. Same problem with lower and upper cased folder names with 0.96.
I can give you access to the server using teamviewer if you like.

**Comment by chrislusf** [comment]
remove the last "\\" from the directory setting in your filer.toml.txt
