### ISSUE TITLE
strange volume id

### ISSUE THREAD

**Issue by song-zhang** [chrislusf/seaweedfs#725]
Hi， I found many err logs in volumes.log:

I0825 01:52:18 37279 volume_server_handlers_write.go:23] NewVolumeId error: strconv.ParseUint: parsing "connector.asp": invalid syntax
I0825 01:52:21 37279 volume_server_handlers_write.go:23] NewVolumeId error: strconv.ParseUint: parsing "horde": invalid syntax
I0825 01:52:23 37279 volume_server_handlers_write.go:23] NewVolumeId error: strconv.ParseUint: parsing "spywall": invalid syntax
I0825 01:52:37 37279 volume_server_handlers_write.go:23] NewVolumeId error: strconv.ParseUint: parsing "invoker": invalid syntax
I0825 01:52:38 37279 volume_server_handlers_write.go:23] NewVolumeId error: strconv.ParseUint: parsing "invoker": invalid syntax
I0825 01:52:39 37279 volume_server_handlers_write.go:23] NewVolumeId error: strconv.ParseUint: parsing "jbossmq-httpil": invalid syntax
I0825 01:52:52 37279 volume_server_handlers_write.go:23] NewVolumeId error: strconv.ParseUint: parsing "rtrlet": invalid syntax
I0825 01:52:55 37279 volume_server_handlers_write.go:23] NewVolumeId error: strconv.ParseUint: parsing "": invalid syntax
I0825 01:53:09 37279 volume_server_handlers_write.go:23] NewVolumeId error: strconv.ParseUint: parsing "havalite": invalid syntax
I0825 01:53:09 37279 volume_server_handlers_write.go:23] NewVolumeId error: strconv.ParseUint: parsing "shoutbox": invalid syntax
I0825 01:53:47 37279 volume_server_handlers_write.go:23] NewVolumeId error: strconv.ParseUint: parsing "webcalendar": invalid syntax
I0825 01:54:18 37279 volume_server_handlers_write.go:23] NewVolumeId error: strconv.ParseUint: parsing "phpBB": invalid syntax
I0825 01:54:21 37279 volume_server_handlers_write.go:23] NewVolumeId error: strconv.ParseUint: parsing "cgi-bin": invalid syntax
I0825 01:56:01 37279 volume_server_handlers_write.go:23] NewVolumeId error: strconv.ParseUint: parsing "uploadify.php": invalid syntax
I0825 01:56:22 37279 volume_server_handlers_write.go:23] NewVolumeId error: strconv.ParseUint: parsing "": invalid syntax
I0825 01:57:21 37279 volume_server_handlers_write.go:23] NewVolumeId error: strconv.ParseUint: parsing "WANem": invalid syntax
I0825 01:57:21 37279 volume_server_handlers_write.go:23] NewVolumeId error: strconv.ParseUint: parsing "rtrlet": invalid syntax
I0825 01:57:34 37279 volume_server_handlers_write.go:23] NewVolumeId error: strconv.ParseUint: parsing "": invalid syntax
I0825 01:57:34 37279 volume_server_handlers_write.go:23] NewVolumeId error: strconv.ParseUint: parsing "xoda": invalid syntax
I0825 01:57:34 37279 volume_server_handlers_write.go:23] NewVolumeId error: strconv.ParseUint: parsing "xoda-0.4.0": invalid syntax
I0825 01:57:34 37279 volume_server_handlers_write.go:23] NewVolumeId error: strconv.ParseUint: parsing "xoda-0.4.1": invalid syntax
I0825 01:57:34 37279 volume_server_handlers_write.go:23] NewVolumeId error: strconv.ParseUint: parsing "xoda-0.4.2": invalid syntax
I0825 01:57:34 37279 volume_server_handlers_write.go:23] NewVolumeId error: strconv.ParseUint: parsing "xoda-0.4.3": invalid syntax
I0825 01:57:34 37279 volume_server_handlers_write.go:23] NewVolumeId error: strconv.ParseUint: parsing "xoda-0.4.4": invalid syntax
I0825 01:57:34 37279 volume_server_handlers_write.go:23] NewVolumeId error: strconv.ParseUint: parsing "xoda-0.4.5": invalid syntax
I0825 01:57:41 37279 volume_server_handlers_write.go:23] NewVolumeId error: strconv.ParseUint: parsing "plus": invalid syntax
I0825 05:01:22 37279 volume_server_handlers_write.go:23] NewVolumeId error: strconv.ParseUint: parsing "news": invalid syntax

Why the master assign  so much strange volumeid?

**Comment by chrislusf** [comment]
You got some crawler hitting the volume server
