### ISSUE TITLE
failed to read file size 2.dat stat 2.dat: use of closed file

### ISSUE THREAD

**Issue by swwaden** [chrislusf/seaweedfs#727]
执行完vacuum后，有个volume文件报这个错误。而且出现数据丢失的现象

**Comment by swwaden** [comment]
<a href="http://127.0.0.1:8081/6,013529e2aadf14">Moved Permanently</a>.

**Comment by chrislusf** [comment]
Windows?

**Comment by chrislusf** [comment]
What's the reason for closing this?

**Comment by GGYB** [comment]
使用docker for win10。将/data 挂载至外部文件夹，发现了同样的问题。 1.dat文件消失了，多了 1.cpd 1.cpx 文件。

**Comment by chrislusf** [comment]
resolved in https://github.com/chrislusf/seaweedfs/issues/761
