### ISSUE TITLE
echo string >> file   in weed mount directory show error

### ISSUE THREAD

**Issue by accumulatepig** [chrislusf/seaweedfs#728]
version:0.96
when echo string append to a exist file in weed mount directory  ,error shows :
#echo 'helloworld' > test.txt
#cat test.txt
helloworld
#echo 'helloworld' >> test.txt
-bash: echo: write error: Input/output error

version:0.94
#echo 'helloworld' > test.txt
#cat test.txt
helloworld
#echo 'helloworld2' >> test.txt    （no error, but equal echo 'helloworld2' > test.txt ,not >> ）
#cat test.txt
helloworld2

**Comment by accumulatepig** [comment]
This is the weed mount error log:
2018/09/10 16:54:45 fuse: panic in handler for Write [ID=0x4e95 Node=0x14 Uid=205 Gid=205 Pid=25007] 0x1 4 @6 fl=0 lock=0 ffl=OpenWriteOnly+OpenAppend: runtime error: slice bounds out of range
goroutine 146199 [running]:
bazil.org/fuse/fs.(*Server).serve.func2(0x1056de0, 0xc420284070, 0xc42032eef8, 0xc42032ee6f)
        /home/go/src/bazil.org/fuse/fs/serve.go:857 +0x1b1
panic(0xdf4760, 0x1542310)
        /usr/local/go/src/runtime/panic.go:502 +0x229
github.com/chrislusf/seaweedfs/weed/filesys.(*ContinuousDirtyPages).AddPage(0xc4204b6d80, 0x105ab20, 0xc4203e06c0, 0x6, 0xc420760050, 0x4, 0x20fb0, 0x0, 0x0, 0x0, ...)
        /home/go/src/github.com/chrislusf/seaweedfs/weed/filesys/dirty_page.go:94 +0x1022
github.com/chrislusf/seaweedfs/weed/filesys.(*FileHandle).Write(0xc4201c41e0, 0x105ab20, 0xc4203e06c0, 0xc420284070, 0xc4206480a0, 0xc42054a201, 0xc42040e060)
        /home/go/src/github.com/chrislusf/seaweedfs/weed/filesys/filehandle.go:141 +0x266
bazil.org/fuse/fs.(*Server).handleRequest(0xc4203080c0, 0x105ab20, 0xc4203e06c0, 0x104dc00, 0xc4206faaf0, 0xc4203e0480, 0x1056de0, 0xc420284070, 0xc42032eef8, 0xbeddaa35bacc77a4, ...)
        /home/go/src/bazil.org/fuse/fs/serve.go:1265 +0x1582
bazil.org/fuse/fs.(*Server).serve(0xc4203080c0, 0x1056de0, 0xc420284070)
        /home/go/src/bazil.org/fuse/fs/serve.go:878 +0x41e
bazil.org/fuse/fs.(*Server).Serve.func1(0xc4203080c0, 0x1056de0, 0xc420284070)
        /home/go/src/bazil.org/fuse/fs/serve.go:425 +0x6e
created by bazil.org/fuse/fs.(*Server).Serve
        /home/go/src/bazil.org/fuse/fs/serve.go:423 +0x331

**Comment by chrislusf** [comment]
linux or mac?

**Comment by accumulatepig** [comment]
linux , i will check the fix

**Comment by accumulatepig** [comment]
@chrislusf  great , the fix 267201f works for me .
