### ISSUE TITLE
Is there a way to implement sts support?

### ISSUE THREAD

**Issue by zhyon404** [chrislusf/seaweedfs#730]
Is there a way to implement sts support describe here [link](https://medium.com/@ashan.fernando/upload-files-to-aws-s3-using-signed-urls-fa0a0cf489db) to upload direct in browser without leak sercat information?

**Comment by chrislusf** [comment]
Currently no. Has plan to add Json Web Token(JWT) to upload. Will that work?

**Comment by zhyon404** [comment]
That certainly help, but my use case is to find an alternative to the s3 for private deployment.
JWT can't be replacement for that. 
Also see issue mentioned here.[link](https://github.com/minio/minio/issues/6381).
Implement AssumeRole API provide addition benefit.   I would be grateful if you could consider implement AssumeRole API.

**Comment by chrislusf** [comment]
Having some reproducible cases will be helpful. Is there any existing code that I can use to try and verify it works?

**Comment by chrislusf** [comment]
seems too much work involved for this use case. This either need some help, or need to be put off.
