### ISSUE TITLE
How to properly migrate from volume version 2 to version 3

### ISSUE THREAD

**Issue by avonjo** [chrislusf/seaweedfs#732]
How to properly migrate from volume version 2 to version 3?
Is there a streamlined way aside from doing an export and import?

**Comment by chrislusf** [comment]
No need to to do anything. It's all automatically handled.

**Comment by avonjo** [comment]
Thanks for the quick response.  I have to validate this again. I might have missed something.  Last time I tried (though it was quick in production)   swap weed version 0.76 to 0.95  didn't work.

**Comment by chrislusf** [comment]
Filer would not work, if you use it.

**Comment by avonjo** [comment]
Can we reopen this issue?
