### ISSUE TITLE
File upload corrupted when using 0.92 on volume originally created from 0.76

### ISSUE THREAD

**Issue by avonjo** [chrislusf/seaweedfs#733]
I'm not using filer. My setup was running 0.76 for several months so I have several files in the volume already.

When uploading to 0.76 i get below response...
```
curl -X PUT -F file=@/home/phrero/FILE.jpg http://VolumeIP:VolumePort/13,52137f199062
{"name":"FILE.jpg","size":88878}
```
The file is OK when I fetch the file.

However, when uploading the same file after swapping binary to 0.92 using the volume created from 0.72, I get below response.
```
curl -X PUT -F file=@/home/phrero/FILE.jpg http://VolumeIP:VolumePort/13,52137f199062
{"size":89108}
```
The file is not the same and I can't open it.  Files that were uploaded when still in 0.76 can be read in 0.92.  New files uploaded after upgrade to 0.92 doesn't work. I choose 0.92 because I thought I needed to maintain volume version (volume version 2)

When I revert back to 0.76  and repeat the above command. It's working again.

**Comment by chrislusf** [comment]
use POST, not PUT

**Comment by avonjo** [comment]
Hi Chris,
We use POST in master  /dir/assign

the documentation says PUT or POST to store or update a file see [README](/chrislusf/seaweedfs/blob/master/README.md)     and we have chosen PUT

PUT works in 0.76

Do you mean PUT doesn't work in 0.92  ???

**Comment by chrislusf** [comment]
Correct.
