### ISSUE TITLE
Maybe some  weed mount permission problem

### ISSUE THREAD

**Issue by accumulatepig** [chrislusf/seaweedfs#734]
version: base 0.96 with 267201f   fix
weed mount by a non root user named app.
Create empty file by app user, and shows no permission
$ touch test  
touch: setting times of `test': Permission denied
$ ls -l test       (but owner is  root)
---------- 1 root root 0 Jan  1  1970 test
$ cat test   (and file cannot be read)
cat: test: Input/output error

when write something to the empty file by app user,everythings seems ok
$ echo helloworld > test 
$ cat test   (file can be read)
helloworld
$ ls -l test  (owner changes to  app)
-rw-rw-r-- 1 app app 11 Sep 23 22:25 test

Maybe some permission problems?

**Comment by chrislusf** [comment]
Can not reproduce with latest version or the commit, on Mac or Ubuntu.

Try the latest version.

**Comment by accumulatepig** [comment]
I just try the 0.96 lastest version run in centos 6.5 and  the file's permission is ok when touch an empty file by non root user ,  but read the empty file always error

$ touch emptyfile
$ ls -l emptyfile 
-rw-rw-r-- 1 app app 0 Sep 24 00:49 emptyfile
$ cat emptyfile 
cat: emptyfile: Input/output error

weed mount logs:
I0924 00:49:23 28136 dir.go:123] create: directory:"/" entry:<name:"emptyfile" attributes:<mtime:1537721363 file_mode:436 uid:205 gid:205 crtime:1537721363 replication:"100" > > 
I0924 00:49:23 28136 filehandle.go:206] //emptyfile set chunks: 0
I0924 00:49:23 28136 filehandle.go:206] //emptyfile set chunks: 0
I0924 00:49:30 28136 filehandle.go:54] empty fh //emptyfile

weed filer no logs about this

**Comment by chrislusf** [comment]
thanks for the log!!!

fixed in https://github.com/chrislusf/seaweedfs/commit/578f8a6dec0e8c396221ae165ad3db18096ea957
