### ISSUE TITLE
Filer saved resized image

### ISSUE THREAD

**Issue by parserpro** [chrislusf/seaweedfs#735]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

When I save images (JPGs) using Filer, I got resized files on volumes. I.e. original file has 4+ MB, but saved file is only ~800 KB

**System Setup**
weed master -mdir='/data' -defaultReplication=002
weed volume -max=5 -mserver="master:9333" -port=8080 -dir="/data" -dataCenter=dc1 -rack=rack1
weed filer -master="master:9333"

**Expected behavior**
Files on volumes should be the same size as original

**Screenshots**

**Additional context**

**Comment by ijunaid8989** [comment]
I think you need to add `-volume.images.fix.orientation=false` while starting the master server.

**Comment by parserpro** [comment]
master_1         | flag provided but not defined: -volume.images.fix.orientation

**Comment by chrislusf** [comment]
@parserpro see "weed volume -h"

**Comment by parserpro** [comment]
ok. thank you.
