### ISSUE TITLE
How to disable mime guessing and download fie directly in browser?

### ISSUE THREAD

**Issue by LanserShi** [chrislusf/seaweedfs#742]
Hi Chris, seaweedfs helps us a lot. Many thanks.
We use publicUrl in browser to download files directly (if it's not the proper usage, please tell me), but the "Content-Type" in response header made the browser "display" content instead of pop up a download dialog. Maybe you have some interface/parameter to tell the browser "download" instead of "display”. Please point out. Thanks again.

**Comment by ijunaid8989** [comment]
Plus, can you separate, directory listing and filer's json response.

We don't want to let anyone browse through our files. but Also need the Filer json responses, Will that be possible?

**Comment by chrislusf** [comment]
To download or to display is the browser's choice. Mime is just following http protocol. I think maybe you should try other ways to fix this. One hacky way can be using nginx to remove the mime. But it is not a correct thing to do to remove mime.

**Comment by chrislusf** [comment]
@ijunaid8989 how about using grpc calls to replace your json listing?

**Comment by chrislusf** [comment]
@LanserShi if mime was provided during upload time, it will be stored and used. If not, MIME is determined by filename.

**Comment by LanserShi** [comment]
"if mime was provided during upload time, it will be stored and used" -- could you please give an example?

**Comment by chrislusf** [comment]
during upload time, you can also set content-type in the http header.
