### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by devendrasr** [chrislusf/seaweedfs#743]
We need ssl in order to make wfs master and workers available to public internet. Do we have any roadmap around this?

**Comment by ijunaid8989** [comment]
You need to add nginx  to your remote server and then you can add SSL to that server, also can give a domain name to your IP as well.

**Comment by chrislusf** [comment]
@devendrasr not on the road map, yet. This is related to http vs https performance, access control, etc. Current way is just using nginx. This can fold under using JWT to access. Closing this.
