### ISSUE TITLE
filer.关于大文件分片上传问题

### ISSUE THREAD

**Issue by sapluk** [chrislusf/seaweedfs#745]
作者您好！我现在在使用您的seaweedfs项目，遇到问题，希望能得到您的解答，谢谢！
我使用的是filer进行文件的操作，因为我需要路径的支持

我现在需要实现分片上传功能，我阅读了wiki [Large File Handling](https://github.com/chrislusf/seaweedfs/wiki/Large-File-Handling)，filer在处理大文件时会自动将其切分并存储，但是由调用者自行拆分可能更符合我的要求。我尝试在前端对文件进行拆分，分别进行上传，在合并时遇到问题。

以下是我的操作步骤
```
1. 分别上传切分好的文件
POST 192.168.0.101:8888/testMultipartUpload/0.tmp
POST 192.168.0.101:8888/testMultipartUpload/1.tmp

2. 分别得到对应的文件信息响应值
{
    "name": "0.tmp",
    "size": 3145728,
    "fid": "3,3b21a5cbc6",
    "url": "http://192.168.0.101:8080/3,3b21a5cbc6"
}
{
    "name": "1.tmp",
    "size": 1466545,
    "fid": "1,3cbfebe645",
    "url": "http://192.168.0.101:8081/1,3cbfebe645"
}

3. 合并请求【失败】
POST 192.168.0.101:8888/testMultipartUpload/test.zip?cm=true
Header.Content-Type: application/json

{
	"Name": "test.zip",
	"Mime": "application/zip",
	"Size": 4612273,
	"Chunks": [
		{
			"Fid": "3,3b21a5cbc6",
			"Offset": 0,
			"Size": 3145728
		},{
			"Fid": "1,3cbfebe645",
			"Offset": 3145728,
			"Size": 1466545
		}
	]
}

响应: 
{
    "error": "request Content-Type isn't multipart/form-data"
}
```

在项目的代码中，seaweedfs-master\weed\server\filer_server_handlers_write.go [Line:124-132]，有看到对cm参数的支持，不知道我的调用是否正确
```
        // This allows a client to generate a chunk manifest and submit it to the filer -- it is a little off
	// because they need to provide FIDs instead of file paths...
	cm, _ := strconv.ParseBool(query.Get("cm"))
	if cm {
		q := u.Query()
		q.Set("cm", "true")
		u.RawQuery = q.Encode()
	}
	glog.V(4).Infoln("post to", u)
```

目前我的解决方案:
1. 前端计算文件md5(秒传支持)后，向javaweb服务器请求上传操作
2. 如果filer服务器没有该文件，则对文件进行分片上传
3. 前端分别上传分片至javaweb服务器(鉴权/集群)，javaweb判断分片是否已经存在
4. javaweb服务器上传分片至filer服务器(无法直接临时存储在javaweb服务器)
5. 前端发送合并请求
6. javaweb服务器将所有分片下载，进行合并操作，md5校验
7. 将合并完的文件上传至filer服务器

我的文件需要上传至filer服务器，下载，合并完再上传
我想得到直接合并的功能，不知道现有的功能是否能够支持，谢谢！

**Comment by chrislusf** [comment]
see "weed upload" for example, which uses the function operation.Upload().

Your logic seems alright to me. Let me know what went wrong.

**Comment by chrislusf** [comment]
Sorry, "weed upload" is for uploading to volume servers. "weed filer.copy" is for uploading to filer servers.

In filer server, the list of chunks is stored directly in filer store via grpc API, not as a JSON list.
