### ISSUE TITLE
weed scaffold filer failed, the content still empty

### ISSUE THREAD

**Issue by terasum** [chrislusf/seaweedfs#749]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**

I want to create a filer config, and I followed what as [wiki's](https://github.com/chrislusf/seaweedfs/wiki/Filer-Setup) said
but the command just output the config content, but the`filer.toml` still empty.

**System Setup**

Firstly, I created a directory:

```
mkdir -P $HOME/.seaweedfs
```
and create a filer.toml

```
cd $HOME/.seaweedfs
touch filer.toml
```

Then

```
cd $HOME/.seaweedfs
weed scaffold filer -output="."
```

**Expected behavior**
the config content should be written into `filer.toml`

**Screenshots**

![image](https://user-images.githubusercontent.com/20042193/46851183-39975480-ce29-11e8-8273-e3bffed5d2b6.png)

![image](https://user-images.githubusercontent.com/20042193/46851162-26848480-ce29-11e8-8ebf-4389088d80a4.png)

**Additional context**

MacOS 10.13.6

**Comment by chrislusf** [comment]
weed scaffold -config filer -output="."
