### ISSUE TITLE
Kubernetes Setup with replication cannot assign directory

### ISSUE THREAD

**Issue by bal291** [chrislusf/seaweedfs#752]
Hi I have deployed 1 master and 2 volume servers with 001 replication to my kubernetes cluster (not local). Currently not mounting out the data. 

**MasterDeployment.yaml**
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: weedmasterdeployment
spec:
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: haystack
    spec:
      containers:
      - name: weedmaster
        image: chrislusf/seaweedfs:latest
        args: ["-log_dir", "/var/containerdata/logs", "master", "-port", "9333", "-mdir", ".", "-**defaultReplication", "001"**, "-ip", "haystackservice"]
        ports:
        - containerPort: 9333

**VolumeDeployment.yaml**
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: weedvolumedeployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: haystack
    spec:
      containers:
      - name: weedvol
        image: chrislusf/seaweedfs:latest
        args: ["-log_dir", "/var/containerdata/logs", "volume", "-port", "8080", "-dir", "./data", "-dataCenter", "dc1", "-rack", "rack1", "-mserver", "hay$
        ports:
        - containerPort: 8080
        - containerPort: 18080

**Service.yaml**
apiVersion: v1
kind: Service
metadata:
  name: haystackservice
spec:
  selector:
    app: haystack
  ports:
  - name: mport
    protocol: TCP
    port: 9333
    nodePort: 30069
  - name: vport
    protocol: TCP
    port: 8080
    nodePort: 30070
  - name: vgport
    protocol: TCP
    port: 18080
    nodePort: 30071
  type: NodePort

Everything deploys fine. 
root@node1:~/weed# kubectl get pods
**NAME                                    READY   STATUS    RESTARTS   AGE**
weedmasterdeployment-d759dbc47-l42hh    1/1     Running   0          4m56s
weedvolumedeployment-5847ddb5f8-6mf7f   1/1     Running   0          105s
weedvolumedeployment-5847ddb5f8-vm6g8   1/1     Running   0          104s

However when I call http://192.168.1.201:30069/dir/assign I get this error:
 "error": "Cannot grow volume group! No matching data node found! \ndc1:Only has 0 racks with more than 2 free data nodes, not enough for 1."
If I don't enable replication then it works fine but I don't understand why the replication setup doesn't work.

Thanks

**Comment by bal291** [comment]
Sorry it seems like the VolumeDeployment.yaml above didn't copy correctly. Here it is now:

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: weedvolumedeployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: haystack
    spec:
      containers:
      - name: weedvol
        image: chrislusf/seaweedfs:latest
        args: ["-log_dir", "/var/containerdata/logs", "volume", "-port", "8080", "-dir", "./data", "-dataCenter", "dc1", "-rack", "rack1", "-mserver", "haystackservice:9333", "-ip", "haystackservice"]
        ports:
        - containerPort: 8080
        - containerPort: 18080

**Comment by chrislusf** [comment]
please show the result from /dir/status

**Comment by bal291** [comment]
Hi sorry for the late reply.
Here it is:
http://192.168.1.201:30069/dir/status

{
    "Topology": {
        "DataCenters": [
            {
                "Free": 7,
                "Id": "dc1",
                "Max": 7,
                "Racks": [
                    {
                        "DataNodes": [
                            {
                                "Free": 7,
                                "Max": 7,
                                "PublicUrl": "haystackservice:8080",
                                "Url": "haystackservice:8080",
                                "Volumes": 0
                            }
                        ],
                        "Free": 7,
                        "Id": "rack1",
                        "Max": 7
                    }
                ]
            }
        ],
        "Free": 7,
        "Max": 7,
        "layouts": [
            {
                "collection": "",
                "replication": "001",
                "ttl": "",
                "writables": null
            }
        ]
    },
    "Version": "0.99"
}

**Comment by chrislusf** [comment]
I am no export on kubernetes. But from the /dir/status, the volume servers are sharing the same ip address, so the master server thinks there is only one volume server.

To fix it, the volume server "-ip" option needs to specify different values.
