### ISSUE TITLE
mount as fuse error

### ISSUE THREAD

**Issue by weiranzhixin** [chrislusf/seaweedfs#764]
when run command:
`weed mount -filer=localhost:8888 -dir=/some/existing/dir -filer.path=/`
report errors as fellow:
```
I1106 20:15:45 28245 dir.go:239] list /: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:18888: connect: connection refused"
```
I have started master,   volume1: port=8080, volume2:port=8081

**Comment by chrislusf** [comment]
Need to start filer.

**Comment by chrislusf** [comment]
There are no known bugs now.  You are welcome to benchmark it and publish the results.

Usually 1 master, 1 filer, multiple volume servers. Multiple filers if you are using existing data store, e.g. MySql, PostGres, Cassandra, Redis.

**Comment by weiranzhixin** [comment]
* run `time ll skirt ` command consumes 40-50seconds, it is too long
* `skirt` is a fuse directory containing 9363 JPG files, single file size: 50k-200k

**Comment by chrislusf** [comment]
release 1.02, it should be very quick for "time ls -al /your/directory". Please let me know how it works for you.

**Comment by weiranzhixin** [comment]
* release 1.02 is the version I used,  package name is linux_386.tar.gz
* host os : ubuntu 16.04 
* weedfs set up as follows:
  - 1 `./weed master &`
  - 2 `./weed volume -dir="/home/hh/seaweed/data1" -max=5  -mserver="localhost:9333" -port=8080 &`
  - 3 `./weed volume -dir="/home/hh/seaweed/data2" -max=5  -mserver="localhost:9333" -port=8081 &`
  - 4 `./weed scaffold -config=filer -output=.`
  - 5 `./weed filer &`
  - 6  `./weed mount -filer=localhost:8888  -dir=/home/hh/seaweedmount  -filer.path=/ &`
  - 7 `cd /home/hh/seaweedmount  && cp ~/skirt_length .`
  - 8 `time ll skirt_length `
  one test result is 
```sh
real	0m46.315s
user	0m0.127s
sys	0m0.239s

```

**Comment by chrislusf** [comment]
Thanks! Can you please add logging to step 6, and paste the logs here?
6 ./weed -v=4 mount -filer=localhost:8888 -dir=/home/hh/seaweedmount -filer.path=/ &

btw: I suppose your "ll" is an alias for "ls -l"?

**Comment by weiranzhixin** [comment]
[weedmount.log](https://github.com/chrislusf/seaweedfs/files/2560696/weedmount.log)

btw: I suppose your "ll" is an alias for "ls -l"?
yes it is

**Comment by chrislusf** [comment]
The logs shows you are using 1.01 "This is SeaweedFS version 1.01 linux 386"

**Comment by weiranzhixin** [comment]
eeee, let me re-deploy and test again

**Comment by weiranzhixin** [comment]
I installed 1.0.2 version , first time I run `ll`, it consumes about 2s, then I do the operation multiple times, time increase, it coud be 10s, 16s, 13s., 15s
[weed.log](https://github.com/chrislusf/seaweedfs/files/2560775/weed.log)

**Comment by chrislusf** [comment]
this is because the cache for the directory listing is set to 0.3 seconds. I will increase it to 3 seconds in next release.

**Comment by chrislusf** [comment]
updated to 1.04. Welcome to test it again.

**Comment by guleng** [comment]
@chrislusf  我是用的版本是：version 30GB 2.81 5ea97157 linux amd64     不跟master同节点启动filer时报同样错误，启动master服务时好像不能指定filer的地址吗？

**Comment by chrislusf** [comment]
@guleng I do not what error you are referring to. Please create a separate issue.



> 启动master服务时好像不能指定filer的地址吗？

Correct.

**Comment by guleng** [comment]
@chrislusf 启动master服务时日志里报错  
error: read buckets: get filer configuration: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:18888: connect: connection refused"

filer和master服务不在同一个节点上时报这个错误，我寻找启动master是能不能指定filer的地址时没找到该参数

**Comment by chrislusf** [comment]
please create a separate issue following issue template.
