### ISSUE TITLE
上传html文件的时候报错（request Content-Type isn\'t multipart/form-data），请问这个怎么解决

### ISSUE THREAD

**Issue by 582727501** [chrislusf/seaweedfs#765]
seaweedfs error write http://192.168.8.96:8181/83,08ca0893eda12bb8 Curl_Response::__set_state(array(
   'body' => '{"error":"request Content-Type isn\'t multipart/form-data"}',
   'headers' => 
  array (
    'Http-Version' => '1.1',
    'Status-Code' => '400',
    'Status' => '400 Bad Request',
    'Content-Type' => 'application/json',
    'Date' => 'Wed, 07 Nov 2018 00:00:14 GMT',
    'Content-Length' => '58',
  ),
   'params' => 
  array (
    'file' =>     '<!DOCTYPE html>
<html class="ua-win ua-wk">
<head>
    <meta name="referrer" content="always"/>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
        <meta http-equiv="x-ua-compatible" content="ie=8"/>

上传html文件的时候报错（request Content-Type isn\'t multipart/form-data）
请问这个怎么去解决这个问题呢

**Comment by chrislusf** [comment]
use http POST

**Comment by 582727501** [comment]
> use http POST
i have used http post

**Comment by 582727501** [comment]
the version i used seaweedfs is 0.7,  how can i reslove the problem

**Comment by 582727501** [comment]
the version i used seaweedfs is 0.7, how can i solve the problem

**Comment by chrislusf** [comment]
Do you mind to share how you make the request, so we can help you?

**Comment by 582727501** [comment]
ok，hold on

**Comment by 582727501** [comment]
upload.php
$params = array(
      'file' => $content,
  );
$response = $this->curl->upload($url, $params);
if($response === false) {
       $this->err_msg($url, $this->curl->error());
 }

curl.php
    function upload($url, $vars = array()) {
        return $this->request('POST', $url, $vars, TRUE);
    }
    function request($method, $url, $vars = array(), $upload=FALSE) {
        $this->error = '';
        $this->request = curl_init();
        //新增&& $method != 'POST'否则不支持上传文件
        //if (is_array($vars) /*&& $method != 'POST'*/) {
        if (is_array($vars) && !$upload) {
            $vars = http_build_query($vars, '', '&');
        }

        $this->set_request_method($method);
        $this->set_request_options($url, $vars);
        $this->set_request_headers();

        $response = curl_exec($this->request);

        if ($response) {
            $response = new Curl_Response($response);
        } else {
            $this->error = curl_errno($this->request).'-'.curl_error($this->request);
        }

        curl_close($this->request);
        return $response;
    }

    protected function set_request_headers() {
        $headers = array();
        foreach ($this->headers as $key => $value) {
            $headers[] = $key.': '.$value;
        }
        //$headers[] = 'Accept-Encoding: gzip, deflate';
        // $headers[] = 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8';
        // $headers[] = 'Accept-Language: zh-cn,zh;q=0.8,en-us;q=0.5,en;q=0.3';
        // $headers[] = 'Connection: keep-alive';
        // $headers[] = 'Cache-Control: max-age=0';
        $headers[] = 'Expect:';
        curl_setopt($this->request, CURLOPT_HTTPHEADER, $headers);
        //curl_setopt($this->request, CURLOPT_HTTPHEADER, array('Expect:'));
    }

**Comment by 582727501** [comment]
upload.php
$params = array(
'file' => $content,
);
$response = $this->curl->upload($url, $params);
if($response === false) {
$this->err_msg($url, $this->curl->error());
}

curl.php
function upload($url, $vars = array()) {
return $this->request('POST', $url, $vars, TRUE);
}
function request($method, $url, $vars = array(), $upload=FALSE) {
     $this->error = '';
     $this->request = curl_init();
    //新增&& $method != 'POST'否则不支持上传文件
    //if (is_array($vars) /&& $method != 'POST'/) {
    if (is_array($vars) && !$upload) {
         $vars = http_build_query($vars, '', '&');
     }

    $this->set_request_method($method);
    $this->set_request_options($url, $vars);
    $this->set_request_headers();

    $response = curl_exec($this->request);

    if ($response) {
        $response = new Curl_Response($response);
    } else {
        $this->error = curl_errno($this->request).'-'.curl_error($this->request);
    }

    curl_close($this->request);
    return $response;
}

protected function set_request_headers() {
    $headers = array();
    foreach ($this->headers as $key => $value) {
        $headers[] = $key.': '.$value;
    }
    //$headers[] = 'Accept-Encoding: gzip, deflate';
    // $headers[] = 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8';
    // $headers[] = 'Accept-Language: zh-cn,zh;q=0.8,en-us;q=0.5,en;q=0.3';
    // $headers[] = 'Connection: keep-alive';
    // $headers[] = 'Cache-Control: max-age=0';
    $headers[] = 'Expect:';
    curl_setopt($this->request, CURLOPT_HTTPHEADER, $headers);
    //curl_setopt($this->request, CURLOPT_HTTPHEADER, array('Expect:'));

**Comment by 582727501** [comment]
Strangely, there are some successes, but the probability of reporting this error is also very high.
奇怪的是，有些是成功的，但是失败的概率还是挺高的

**Comment by chrislusf** [comment]
set the Content-Type in request header.

**Comment by 582727501** [comment]
set the Content-Type = multipart/form-data  or Content-Type= application/json?
Which is the correct answer?

**Comment by chrislusf** [comment]
the way you do http multipart upload in PHP is wrong. Maybe ask for help from some PHP experts.

**Comment by tomnattle** [comment]
i am PHP expert,plz ask me!

**Comment by 582727501** [comment]
sometimes success Curl_Response::__set_state(array(
   'body' => '{"size":28573}',
   'headers' => 
  array (
    'Http-Version' => '1.1',
    'Status-Code' => '201',
    'Status' => '201 Created',
    'Content-Type' => 'application/json',
    'Date' => 'Wed, 07 Nov 2018 09:26:40 GMT',
    'Content-Length' => '14',
  ),
))


sometimes  error object Curl_Response::__set_state(array(
   'body' => '{"error":"request Content-Type isn\'t multipart/form-data"}',
   'headers' => 
  array (
    'Http-Version' => '1.1',
    'Status-Code' => '400',
    'Status' => '400 Bad Request',
    'Content-Type' => 'application/json',
    'Date' => 'Wed, 07 Nov 2018 09:27:16 GMT',
    'Content-Length' => '58',
  ),
))

sometimes success, sometimes error ,  
Can you help me ?
Do you have any suggestions to solve this problem?

**Comment by 582727501** [comment]
{"error":"request Content-Type isn\'t multipart/form-data"}'
Which circumstances will bring back this mistake?
