### ISSUE TITLE
上传html文件的时候报错 （ request Content-Type isn\'t multipart/form-data），请问这个怎么解决

### ISSUE THREAD

**Issue by 582727501** [chrislusf/seaweedfs#766]
https://github.com/chrislusf/seaweedfs/issues/765

sometimes success Curl_Response::__set_state(array(
'body' => '{"size":28573}',
'headers' =>
array (
'Http-Version' => '1.1',
'Status-Code' => '201',
'Status' => '201 Created',
'Content-Type' => 'application/json',
'Date' => 'Wed, 07 Nov 2018 09:26:40 GMT',
'Content-Length' => '14',
),
))

sometimes error object Curl_Response::__set_state(array(
'body' => '{"error":"request Content-Type isn't multipart/form-data"}',
'headers' =>
array (
'Http-Version' => '1.1',
'Status-Code' => '400',
'Status' => '400 Bad Request',
'Content-Type' => 'application/json',
'Date' => 'Wed, 07 Nov 2018 09:27:16 GMT',
'Content-Length' => '58',
),
))

sometimes success, sometimes error ,
Can you help me ?
Do you have any suggestions to solve this problem?

**Comment by 582727501** [comment]
{"error":"request Content-Type isn't multipart/form-data"}'
Which circumstances will bring back this mistake?

**Comment by chrislusf** [comment]
@582727501 when in the request, "Content-Type isn't multipart/form-data".
