### ISSUE TITLE
Maybe it's time to use go module

### ISSUE THREAD

**Issue by RocFang** [chrislusf/seaweedfs#768]
Hi, @chrislusf 

When I follow the instructions of installing seaweedfs,  I found there is a lack of dependency management.
Even though there is a related issues: https://github.com/chrislusf/seaweedfs/issues/256, it seems not be used.
Maybe it's time to use go module now?
Thanks.

**Comment by chrislusf** [comment]
Need help on this. Not familiar with go module.

**Comment by RocFang** [comment]
@chrislusf 
The steps are below:

```
cd weed
go mod init github.com/chrislusf/seaweedfs/weed
go get ./...
after this, there will be two new files, go.mod and go.sum to record the dependencies,then
go build
```
But there is a problem,  the latest release tag of  uuid library github.com/satori/go.uuid  has break the compatibility of uuid.NewV4(), so the go build will fail.
The latest master code of github.com/satori/go.uuid has resolve it, but the tag has not been released.  So we have to change the version in go.mod:
```
go mod edit -require=github.com/satori/go.uuid@b2ce2384e17bbe0c6d34077efa39dbab3e09123b
```
and now go build will success.

After commit the go.mod and go.sum, every time we clone seaweedfs to anywhere, go build will use the same dependencies.

Thanks.

**Comment by chrislusf** [comment]
chris:weed chris$ go mod init github.com/chrislusf/seaweedfs/weed
go: modules disabled inside GOPATH/src by GO111MODULE=auto; see 'go help modules'

Seems the go module support is still preliminary. Let's wait until 1.12 to revisit this.

**Comment by RocFang** [comment]
@chrislusf  
sorry for reply to this closed issues:)
The reason for the message you posted is, golang 1.11+ supported both gopath and gomodule, if we put code in the gopath ,it will disable go module by default. 
So you just have to clone your code to any other dir, and the go module is enabled.

Just a explainning for your failling message,and I agree with your opinion.
