### ISSUE TITLE
Cluster using seaweedfs dockers

### ISSUE THREAD

**Issue by meirhazon1** [chrislusf/seaweedfs#770]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**
I am trying to add a volume to a master from multiple nodes, 
I am using seaweedfs dockers.
It doesnt work, it works only on the master node.
I have tried using the node ip, using overlay network, it doesnt work.

error:

9 07:51:53     1 volume_grpc_client_to_master.go:32] heartbeat error: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 172.17.0.2:9333: connect: connection refused"

**System Setup**
at this time 1 master, multiple remote volume nodes, second phase, master redundancy and replication of 2 for the volumes.

master created:  docker run -d -p 9333:9333 --name master chrislusf/seaweedfs master
volume command: docker run -p 8080:8080 -p 18080:18080 --name volume  chrislusf/seaweedfs volume -max=5 -mserver="10.132.0.12:9333" -port=8080

root@seaweed-2 ~]# docker run -p 8080:8080 -p 18080:18080 --name volume  chrislusf/seaweedfs volume -max=5 -mserver="10.132.0.12:9333" -port=8080
I1119 07:58:34     1 file_util.go:19] Folder /data Permission: -rwxr-xr-x
I1119 07:58:34     1 disk_location.go:106] Store started on dir: /data with 0 volumes max 5
I1119 07:58:34     1 volume_grpc_client_to_master.go:19] Volume server start with masters: [10.132.0.12:9333]
I1119 07:58:34     1 volume.go:158] Start Seaweed volume server 1.07 at 0.0.0.0:8080
I1119 07:58:34     1 volume_grpc_client_to_master.go:53] Heartbeat to: 10.132.0.12:9333
I1119 07:58:34     1 volume_grpc_client_to_master.go:75] Volume Server found a new master newLeader: 172.17.0.2:9333 instead of 10.132.0.12:9333
I1119 07:58:34     1 volume_grpc_client_to_master.go:50] SendHeartbeat to 172.17.0.2:9333: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 172.17.0.2:9333: connect: connection refused"
I1119 07:58:34     1 volume_grpc_client_to_master.go:32] heartbeat error: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 172.17.0.2:9333: connect: connection refused"
^CI1119 07:58:35     1 volume_server.go:66] Shutting down volume server...
I1119 07:58:35     1 volume_server.go:68] Shut down successfully!
[root@seaweed-2 ~]# 

**volume command:**** [root@seaweed-2 ~]# docker run -p 8080:8080 -p 18080:18080 --name volume --link master chrislusf/seaweedfs volume -
max=5 -mserver="master:9333" -port=8080
/usr/bin/docker-current: Error response from daemon: Could not get container for master.
See '/usr/bin/docker-current run --help'.
[root@seaweed-2 ~]# 

Thanks so much,
Meir

**Comment by chrislusf** [comment]
Seems a docker network issue. I am not familiar with this.

**Comment by meirhazon1** [comment]
Hi,
Thanks for the reply.
Look, not a networking issue, I also created an overlay network, didnt help.

telnet 10.132.0.12 9333
Trying 10.132.0.12...
Connected to 10.132.0.12.
Escape character is '^]'.

Any idea?

Thanks,
Meir

**Comment by meirhazon1** [comment]
Look, without docker at all on the system, using version 1.0.8

root@seaweed-01 ~]# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1460
        inet 10.132.0.12  netmask 255.255.255.255  broadcast 10.132.0.12
        inet6 fe80::4001:aff:fe84:c  prefixlen 64  scopeid 0x20<link>
        ether 42:01:0a:84:00:0c  txqueuelen 1000  (Ethernet)
        RX packets 1041  bytes 18759074 (17.8 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 917  bytes 92090 (89.9 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
[root@seaweed-01 ~]# ./weed master -defaultReplication=001
I1119 08:56:42  1328 file_util.go:19] Folder /tmp Permission: -rwxrwxrwx
I1119 08:56:42  1328 master_server.go:68] Volume Size Limit is 30000 MB
I1119 08:56:42  1328 master.go:80] Start Seaweed Master 1.08 at 0.0.0.0:9333
I1119 08:56:42  1328 raft_server.go:47] Starting RaftServer with localhost:9333
I1119 08:56:46  1328 raft_server.go:88] current cluster leader: localhost:9333
I1119 08:56:46  1328 master_server.go:102] [ localhost:9333 ] I am the leader!
I1119 08:56:47  1328 node.go:223] topo adds child dc1
I1119 08:56:47  1328 node.go:223] topo:dc1 adds child rack1
I1119 08:56:47  1328 node.go:223] topo:dc1:rack1 adds child 127.0.0.1:8081
I1119 08:56:47  1328 master_grpc_server.go:66] added volume server 127.0.0.1:8081
I1119 08:56:47  1328 master_grpc_server.go:22] unregister disconnected volume server 127.0.0.1:8081
I1119 08:56:47  1328 node.go:237] topo:dc1:rack1 removes 127.0.0.1:8081



root@seaweed-2 ~]# ./weed volume -port=8081 -dir=/tmp/1 -max=100 -mserver="10.132.0.12:9333" -dataCenter=dc1 -rack=rack1
I1119 08:56:47  1339 file_util.go:19] Folder /tmp/1 Permission: -rwxr-xr-x
I1119 08:56:47  1339 disk_location.go:106] Store started on dir: /tmp/1 with 0 volumes max 100
I1119 08:56:47  1339 volume.go:158] Start Seaweed volume server 1.08 at 0.0.0.0:8081
I1119 08:56:47  1339 volume_grpc_client_to_master.go:19] Volume server start with masters: [10.132.0.12:9333]
I1119 08:56:47  1339 volume_grpc_client_to_master.go:53] Heartbeat to: 10.132.0.12:9333
I1119 08:56:47  1339 volume_grpc_client_to_master.go:75] Volume Server found a new master newLeader: localhost:9333 instead of 10.132.0.12:9333
I1119 08:56:47  1339 volume_grpc_client_to_master.go:50] SendHeartbeat to localhost:9333: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp [::1]:9333: connect: connection refused"
I1119 08:56:47  1339 volume_grpc_client_to_master.go:32] heartbeat error: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp [::1]:9333: connect: connection refused"
^CI1119 08:56:49  1339 volume_server.go:66] Shutting down volume server...
I1119 08:56:49  1339 volume_server.go:68] Shut down successfully!
[root@seaweed-2 ~]# 

Thanks,
Meir

**Comment by meirhazon1** [comment]
works, the documentation is a bit misleading. 
Thanks
