### ISSUE TITLE
Volume server is connected to the master but after seconds the connection breaks

### ISSUE THREAD

**Issue by meirhazon1** [chrislusf/seaweedfs#771]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**

**System Setup**
List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by meirhazon1** [comment]
Volume server is connected to the master but after seconds the connection breaks

Master:

root@seaweed-01 ~]# docker run -p 9333:9333 --name master chrislusf/seaweedfs master -defaultReplication=010 -mdir="/tmp/sea" -ip=10.132.0.12
I1119 10:16:40     1 file_util.go:19] Folder /data Permission: -rwxr-xr-x
I1119 10:16:40     1 master_server.go:68] Volume Size Limit is 30000 MB
I1119 10:16:40     1 master.go:80] Start Seaweed Master 1.07 at 0.0.0.0:9333
I1119 10:16:40     1 raft_server.go:47] Starting RaftServer with 172.17.0.2:9333
I1119 10:16:40     1 raft_server.go:51] Peers Change: [] => []
I1119 10:16:41     1 raft_server.go:75] Initializing new cluster
I1119 10:16:41     1 raft_server.go:88] current cluster leader: 172.17.0.2:9333
I1119 10:16:41     1 master_server.go:102] [ 172.17.0.2:9333 ] I am the leader!
I1119 10:16:43     1 node.go:223] topo adds child dc1
I1119 10:16:43     1 node.go:223] topo:dc1 adds child rack1
I1119 10:16:43     1 node.go:223] topo:dc1:rack1 adds child 172.17.0.2:8080
I1119 10:16:43     1 master_grpc_server.go:66] added volume server 172.17.0.2:8080
I1119 10:16:43     1 master_grpc_server.go:22] unregister disconnected volume server 172.17.0.2:8080
I1119 10:16:43     1 node.go:237] topo:dc1:rack1 removes 172.17.0.2:8080
Volume Server: 

root@seaweed-2 ~]# docker run -p 8080:8080 -p 18080:18080 --name volume chrislusf/seaweedfs volume -max=5 -mserver="10.132.0.12:9333" -dir="/data" -dataCenter=dc1 -rack=rack1
I1119 10:16:43     1 file_util.go:19] Folder /data Permission: -rwxr-xr-x
I1119 10:16:43     1 disk_location.go:106] Store started on dir: /data with 0 volumes max 5
I1119 10:16:43     1 volume.go:158] Start Seaweed volume server 1.07 at 0.0.0.0:8080
I1119 10:16:43     1 volume_grpc_client_to_master.go:19] Volume server start with masters: [10.132.0.12:9333]
I1119 10:16:43     1 volume_grpc_client_to_master.go:53] Heartbeat to: 10.132.0.12:9333
I1119 10:16:43     1 volume_grpc_client_to_master.go:75] Volume Server found a new master newLeader: 172.17.0.2:9333 instead of 10.132.0.12:9333
I1119 10:16:43     1 volume_grpc_client_to_master.go:50] SendHeartbeat to 172.17.0.2:9333: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 172.17.0.2:9333: connect: connection refused"
I1119 10:16:43     1 volume_grpc_client_to_master.go:32] heartbeat error: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 172.17.0.2:9333: connect: connection refused"
^CI1119 10:16:46     1 volume_server.go:66] Shutting down volume server...
I1119 10:16:46     1 volume_server.go:68] Shut down successfully!

**Comment by meirhazon1** [comment]
Though I give the parameter "ip" the masters listens on all the maser server ports, it is causing issues since the volume server identifies multiple masters on the network. 
Please advice.

-mserver="10.132.0.12:9333"

docker run -d -p  9333:9333 --name master chrislusf/seaweedfs master -defaultReplication=010 -mdir="/tmp/sea" -ip=10.132.0.12

docker run -p 8080:8080 -p 18080:18080 -v /data:/data --name volume chrislusf/seaweedfs volume -max=5 -mserver="10.132.0.12:9333" -dir="/data" -dataCenter=dc1 -rack=rack1

[root@seaweed-2 ~]# docker run -p 8080:8080 -p 18080:18080 -v /data:/data --name volume chrislusf/seaweedfs volume -max=5 -mserver="10.132.0.12:9333" -dir="/data" -dataCenter=dc1 -rack=rack1
I1119 10:33:32     1 file_util.go:19] Folder /data Permission: -rwxr-xr-x
I1119 10:33:32     1 disk_location.go:106] Store started on dir: /data with 0 volumes max 5
I1119 10:33:32     1 volume.go:158] Start Seaweed volume server 1.07 at 0.0.0.0:8080
I1119 10:33:32     1 volume_grpc_client_to_master.go:19] Volume server start with masters: [10.132.0.12:9333]
I1119 10:33:32     1 volume_grpc_client_to_master.go:53] Heartbeat to: 10.132.0.12:9333
I1119 10:33:32     1 volume_grpc_client_to_master.go:75] Volume Server found a new master newLeader: 172.17.0.2:9333 instead of 10.132.0.12:9333
I1119 10:33:32     1 volume_grpc_client_to_master.go:50] SendHeartbeat to 172.17.0.2:9333: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 172.17.0.2:9333: connect: connection refused"
I1119 10:33:32     1 volume_grpc_client_to_master.go:32] heartbeat error: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 172.17.0.2:9333: connect: connection refused"
^CI1119 10:33:33     1 volume_server.go:66] Shutting down volume server...
I1119 10:33:33     1 volume_server.go:68] Shut down successfully!
[root@seaweed-2 ~]#

**Comment by meirhazon1** [comment]
I have added the parameter ip.bind, doesnt seems to work,
without it the master listens on all interfaces. causes issues. 

root@seaweed-01 ~]# docker run  -p  9333:9333 --name master chrislusf/seaweedfs master -defaultReplication=010 -mdir="/tmp/sea" -ip=10.132.0.12 -ip.bind=10.132.0.12
I1119 10:39:36     1 file_util.go:19] Folder /data Permission: -rwxr-xr-x
I1119 10:39:36     1 master_server.go:68] Volume Size Limit is 30000 MB
I1119 10:39:36     1 master.go:80] Start Seaweed Master 1.07 at 10.132.0.12:9333
F1119 10:39:36     1 master.go:84] Master startup error: listen tcp 10.132.0.12:9333: bind: cannot assign requested address
goroutine 1 [running]:
github.com/chrislusf/seaweedfs/weed/glog.stacks(0xc0002d5e00, 0xc0004e0000, 0x7c, 0xa4)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:767 +0xad
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).output(0x23b92e0, 0xc000000003, 0xc0004c72d0, 0x2139d8b, 0x9, 0x54, 0x0)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:718 +0x301
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).printf(0x23b92e0, 0x3, 0x14a0c2b, 0x18, 0xc000569e58, 0x1, 0x1)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:656 +0x14c
github.com/chrislusf/seaweedfs/weed/glog.Fatalf(...)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:1149
github.com/chrislusf/seaweedfs/weed/command.runMaster(0x236e5e0, 0xc00003c130, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/command/master.go:84 +0x412
main.main()
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/weed.go:67 +0x313

**Comment by chrislusf** [comment]
clean up /tmp/sea and try again.
