### ISSUE TITLE
Image does not appear on the browser

### ISSUE THREAD

**Issue by yhan219** [chrislusf/seaweedfs#772]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**
I found that the user uploaded image has problems opening in the browser, such as https://file.liuguohai.com/file/79,286e2b19ff00 .But when I re-download and upload it is ok, such as https://file.liuguohai.com/file/2,3d90b238cc6a .The md5 values of these two files are no different.

**System Setup**

weed master -port=9333 -mdir=./data
weed volume -max=1000 -port=9222 -publicUrl=/file -dir=./data

**Expected behavior**
https://file.liuguohai.com/file/79,286e2b19ff00
This image can be displayed normally on the browser.

**Comment by chrislusf** [comment]
The content-type is different. It should be "content-type: image/png", but the https://file.liuguohai.com/file/79,286e2b19ff00 has "content-type: png". This is determined during the uploading time, provided by the upload client.
