### ISSUE TITLE
Build statically linked executables

### ISSUE THREAD

**Issue by peick** [chrislusf/seaweedfs#775]
To improve compatibility with different OS and older OS version, I would love to see statically linked executable of "weed".

**Comment by chrislusf** [comment]
Is this what you want?

https://github.com/chrislusf/seaweedfs/releases

**Comment by peick** [comment]
A statically linked executable is an executable that does not use any shared libraries.

At the moment the `weed` executable depends on these shared libraries:

```
$ ldd ./weed
	linux-vdso.so.1 (0x00007f13fd599000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f13fd155000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f13fcd64000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f13fd374000)
```

What I need is this:

```
$ ldd ./weed
	not a dynamic executable
```

In go you can easily achieve this with:

```
CGO_ENABLED=0 go build -ldflags "-extldflags -static"
```

**Comment by chrislusf** [comment]
Builds are configured in .travis.yml file. Maybe you can help me with that?
