### ISSUE TITLE
After collection deletion, disk space doesn't release

### ISSUE THREAD

**Issue by albertlinux** [chrislusf/seaweedfs#776]
We are testing collection deletion, but after collection deletion, disk space doesn't release. We tried vacuum API, nothing seems happened. Need help, thanks!

**Comment by chrislusf** [comment]
need details.

**Comment by albertlinux** [comment]
We have three physical machine. Each machine has one master and one volume server and one data dir. We created about 10000+ collections, each only has one file(20KB per file). After creation, i saw seaweedfs's data dir are about 800MB on each machine. Then we use collection deletion api to delete these collections one by one. During this period, I saw the size of data dir rise to about 1000MB and finally down to 800MB. Then i used the vacuum api(curl "http://localhost:9333/vol/vacuum"), expecting the data dir's size to go down. But after about one hour, the size of the data dir is stil 800MB.

**Comment by albertlinux** [comment]
Each volume server are set to different rack.  The replication level is 010.

**Comment by chrislusf** [comment]
Just delete files starting with the collection name. And restart.

**Comment by albertlinux** [comment]
Thanks!
