### ISSUE TITLE
请问怎么获取文件列表中每个文件的createTime

### ISSUE THREAD

**Issue by chanfansang** [chrislusf/seaweedfs#779]
Hi，Chris
我通过weed export 命令，获取到了指定volumeId中的文件列表：
key=  Name= Size=  gzip=  mime= 
这4个参数。
我如果想得到这些文件的生成时间，我该怎么做？
求回复: )

**Comment by chrislusf** [comment]
chris@ubuntu18:~/data$ weed export -volumeId=1
key     name    size    gzip    mime    modified        ttl     deleted
1,088754dc76            4876    false           2018-12-03T07:51:33             false
1,0cff13abbd            4876    false           2018-12-03T07:58:13             false
1,0db8fa2211            4876    false           2018-12-03T08:01:06             false
1,137a984b44            4876    false           2018-12-03T08:21:20             false
1,1489b1b04b            4876    false           2018-12-03T08:28:23             false
1,169b600bf2            4876    false           2018-12-03T08:38:01             false
1,1aee8f3b14            4876    false           2018-12-03T09:13:51             false
1,1ed02132fc            4876    false           2018-12-03T09:36:40             false
