### ISSUE TITLE
volume had run out of disk space but still write successfully

### ISSUE THREAD

**Issue by PapaYofen** [chrislusf/seaweedfs#780]
**Describe the bug**
Version: 1.08
one master, one volume( -max=100)
volume's dir  is in the mount path whose disk space is 500GB, when volume run out of disk space but not reach the volume limit size, master can assgin fileid and volume write needle successfully.
And use the fileid to retreive the uploaded content, volume server return not found.

**System Setup**
weed master -port=9333 -defaultReplication=000
weed volume -port=8080 -max=100 -dir=/mnt/weed/volume

**Expected behavior**
When volume dir run out of disk space, write needle should return err

**Comment by chrislusf** [comment]
To wait for fsync is too slow. 

Do not over promise on max volume count.

**Comment by PapaYofen** [comment]
可能英文没表达清，volume进程参数dir=/mnt/weed/volume，总共有500GB空间，有7个volume被写满了32GB，有１4个volume还没达到32GB，但此时500GB已经被所有用完了，此时仍然能从master assign到fileid，也仍能往其中14个未満32GB 的volume写数据成功，只不过用返回的fileid去volume取数据时会返回NOTFOUND错误．

另，还特意写了个golang程序用os FILE.Write在/mnt/weed/volume建文件写数据，写的时候会返回err=write /mnt/weed/volume/testfile: no space left on device

`
package main

import (
	"flag"
	"fmt"
	"os"
	"time"
)

var (
	config = flag.String("file", "testfile", "file to written")
)

func main() {
	flag.Parse()
	f, err := os.Create(*config)
	if err != nil {
		fmt.Printf("open err=%v\n", err)
		return
	}

	b := make([]byte, 1024*1024, 1024*1024)

	for {
		time.Sleep(10 * time.Second)
		n, err := f.Write(b)
		if err != nil {
			fmt.Printf("write size=%d,err=%v\n", n, err)
		}
	}
}
`

**Comment by PapaYofen** [comment]
找到问题了，应该是upload_content.go里需要对client.Do的response statuscode判断，目前不判断导致客户端误以为落盘成功．

**Comment by chrislusf** [comment]
cool. Could you please send a pull request?

**Comment by PapaYofen** [comment]
@chrislusf  抱歉,
原有代码在硬盘满时已有返回了详细的错误信息,之前的PR反而让详细的错误信息被忽略而只返回Internal Server Error的错误, 我会revert重新发送个PR
