### ISSUE TITLE
SeaweedFS cannot detect file type if extension is set incorrectly on linux machine

### ISSUE THREAD

**Issue by notonestepback** [chrislusf/seaweedfs#786]
Hi. I have local seaweedfs deployment on my windows 10 machine and production on linux machine.
seaweedfs versions are same 1.11
the only difference is that on local machine there is one master and one volume server
production setup consists of 3 masters and 2 volume servers which are replicated

if file extension does not match with actual file type on windows machine seaweedfs returns correct content-type. on linux machine it seems it detects content type from extension and so it is incorrect

for example:
upload headers: 
Content-Type: {multipart/form-data; boundary="Upload----12/09/2018 20:48:19"}

Content-Disposition: {form-data; name=200px-Heavy_taunt_laugh; filename=200px-Heavy_taunt_laugh.docx; filename*=utf-8''200px-Heavy_taunt_laugh.docx}

actual file type is png

headers returned from seaweedfs volume server running on windows:
Content-Disposition: inline; filename="200px-Heavy_taunt_laugh.docx"
Content-Length: 98514
Content-Type: image/png

so content type is correct.

headers returned from seaweedfs volume server running on linux:
content-disposition: inline; filename="200px-Heavy_taunt_laugh.docx"
content-length: 98514
content-type: application/vnd.openxmlformats-officedocument.wordprocessingml.document

**Comment by chrislusf** [comment]
The Linux does not know the as the type. It is just a best-effort guess.

**Comment by notonestepback** [comment]
thanks for your reply. what is reason of it? why it cannot know
