### ISSUE TITLE
weed mount ls error

### ISSUE THREAD

**Issue by accumulatepig** [chrislusf/seaweedfs#787]
version: version 1.11 linux amd64 
when i  exec ls command on weed mount node , shows the error:
ls: reading directory /mydirectory/: Input/output error

mount log print:
I1211 18:29:26 50236 dir.go:250] list /mydirectory: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (5658718 vs. 4194304)

large files or directory in  /mydirectory cause the problem ? and how can i fix it ,thanks

**Comment by accumulatepig** [comment]
after fix 42b8f11 ,weed mount -dirListLimit  can be a Larger number？

**Comment by chrislusf** [comment]
correct.
