### ISSUE TITLE
about weed mount node df -h result

### ISSUE THREAD

**Issue by accumulatepig** [chrislusf/seaweedfs#788]
version:version 1.11 linux amd64
volume server: 5T * 9 nodes , and  current volume node usage info:
Filesystem                 Size  Used Avail Use% Mounted on
/dev/mapper/xxxxxx  4.9T  257G  4.7T   6% /voulme                     --node1
/dev/mapper/xxxxxx  4.9T  212G  4.7T   5% /voulme                     --node2
/dev/mapper/xxxxxx  4.9T  235G  4.7T   5% /voulme                     --node3
/dev/mapper/xxxxxx  4.9T  349G  4.6T   7% /voulme                       ...
/dev/mapper/xxxxxx  4.9T  408G  4.5T   9% /voulme
/dev/mapper/xxxxxx  4.9T  326G  4.6T   7% /voulme
/dev/mapper/xxxxxx  4.9T  257G  4.7T   6% /voulme
/dev/mapper/xxxxxx  4.9T  174G  4.8T   4% /voulme
/dev/mapper/xxxxxx  4.9T  203G  4.7T   5% /voulme
replication level is 100 , and a lot of free space can be used. 

But  difference shows in mount node:
#df -h    
Filesystem                 Size  Used Avail Use% Mounted on
SeaweedFS                  1.3T  1.2T   32G  98% /mountpoint
totle size just 1.3T?, how does this shows?

**Comment by chrislusf** [comment]
created_volume_count x 30GB = 1.3TB

**Comment by accumulatepig** [comment]
so the total size based on the created volume count,   it means the current total size is not  include all the remaining space in volume servers ？

**Comment by chrislusf** [comment]
correct.
