### ISSUE TITLE
Cassandra cluster support

### ISSUE THREAD

**Issue by meirhazon1** [chrislusf/seaweedfs#791]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**

**System Setup**
List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by chrislusf** [comment]
yes. Just use "weed scaffold -config=filer" to generate the yaml file.

The format is correct. Just change to "enabled = true".

**Comment by chrisluuber** [comment]
Add some more details on https://github.com/chrislusf/seaweedfs/wiki/Hadoop-Compatible-File-System
