### ISSUE TITLE
Can you provide some examples of FilerClient.java and FilerGrpcClient.java?

### ISSUE THREAD

**Issue by DPnice** [chrislusf/seaweedfs#792]
Can you provide some examples of FilerClient.java and FilerGrpcClient.java?

**Comment by chrislusf** [comment]
The FilerClient.java and FilerGrpcClient.java are in basic forms and need to be simplified.

The current usage can be found in SeaweedFileSystemStore.java

**Comment by DPnice** [comment]
thanks
