### ISSUE TITLE
Creating a secondary directory

### ISSUE THREAD

**Issue by DPnice** [chrislusf/seaweedfs#794]
https://github.com/chrislusf/seaweedfs/blob/21315f709de9520ae8dc8cd7a8998802ee89af72/other/java/client/src/main/java/seaweedfs/client/FilerClient.java#L40

Can't create a first-level directory
`if ("/".equals(path)) {
            return true;
        }`

**Comment by chrislusf** [comment]
Why it is a bug?

**Comment by DPnice** [comment]
Can't create a first-level directory

**Comment by chrislusf** [comment]
When you need to do that? What's the problem it is causing?

**Comment by chrislusf** [comment]
sorry, mis-read the description!
