### ISSUE TITLE
volume allocation issue

### ISSUE THREAD

**Issue by eatgrape** [chrislusf/seaweedfs#795]
by default, there will be concurrently 7 writable volumes allocated.
but the issue is that I have 10 volume nodes, there are 2 writable volumes allocated on one node although some other nodes have no writable volume.
that means it doesn't guarantee that one node serves only one volume when there are enough nodes, so I fear that even 7 writable volumes are allocated on one node in some extreme case in despite of other free nodes.

**Comment by chrislusf** [comment]
see https://github.com/chrislusf/seaweedfs/wiki/Master-Server-API#pre-allocate-volumes
