### ISSUE TITLE
the Problem of Chinese messy code

### ISSUE THREAD

**Issue by DPnice** [chrislusf/seaweedfs#802]
I use webui to upload a Chinese document, but the document is messy code. What should I do?

**Comment by ijunaid8989** [comment]
How you solved it? was that an issue?

**Comment by DPnice** [comment]
> How you solved it? was that an issue?

It should be related to the encoding set by the file.
I set the encoding format.

`HttpPost post = new HttpPost(targetUrl);
            post.setEntity(MultipartEntityBuilder.create()
                    .setMode(HttpMultipartMode.BROWSER_COMPATIBLE)
                    .setCharset(UTF_8)
                    .addBinaryBody("upload", inputStream)
                    .build());`
