### ISSUE TITLE
filer上传文件大小不对应

### ISSUE THREAD

**Issue by DPnice** [chrislusf/seaweedfs#803]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**

上传一个txt文件，命令

    $ curl -F "filename=@words.txt" "http://cdh1:8888/path/words2.txt"

上传之后的显示大小和实际大小不符，为什么会这样？

**Screenshots**

![在这里插入图片描述](https://img-blog.csdnimg.cn/20181223233257348.png)
文件大小为:18140544B

![在这里插入图片描述](https://img-blog.csdnimg.cn/2018122323344197.png)
上传之后变成了113kb

**Additional context**

    但是文件内容应该和源文件一致

**Comment by chrislusf** [comment]
This is already fixed. It was reporting compressed size.

**Comment by chrislusf** [comment]
fixed in https://github.com/chrislusf/seaweedfs/commit/be946c9e54db3297a68715d1789598d004b71e60
