### ISSUE TITLE
Benchmark ... "compression" aspect unclear.

### ISSUE THREAD

**Issue by tomi-engel** [chrislusf/seaweedfs#804]
**Describe the bug (feature?)**

When running a benchmark (weed 1.15) the storage result is clearly "compressed" data. But the documentation claims:

```
[root@korora-01 v_1_15]# ./weed help benchmark
Usage: weed benchmark -server=localhost:9333 -c=10 -n=100000

  benchmark on an empty SeaweedFS file system.

  Two tests during benchmark:
  1) write lots of small files to the system
  2) read the files out

  The file content is mostly zero, but no compression is done.
..
```

So either 

- the code is not creating "uncompressible" data
- the help text is ambiguous about the meaning of "no compression is done".

**System Setup**
I start a master:

```
./weed master -volumeSizeLimitMB=10 -defaultReplication=000 -ip 192.168.1.31 -mdir /var/zones/seaweed-m01/data
```

a volume

```
./weed volume -mserver=192.168.1.31:9333 -max=150 -port=8080 -dataCenter=dc1 -rack=rackA -ip 192.168.1.31 -dir /var/zones/seaweed-v01/data
```

and then run the benchmark

```
./weed benchmark -master="192.168.1.31:9333" -c=16 -size=1024000 -n=10000
```

Which runs as expected.

**Expected behavior**

If I want to benchmark the system read/write IO performance I want to have "no compression is done" feature .. otherwise I would be testing the CPUs compression/decompression speed.

With the above settings I would expect ... 10000 * 1 MB = 10 GB of data in the storage.

But I see:

```
[root@korora-01 data]# ls -la
total 10720
drwxr-xr-x. 2 root root    4096 Dec 27 17:24 .
drwxr-xr-x. 3 root root      18 Dec 21 01:03 ..
-rw-r--r--. 1 root root 1545048 Dec 27 17:26 benchmark_1.dat
-rw-r--r--. 1 root root   22912 Dec 27 17:26 benchmark_1.idx
-rw-r--r--. 1 root root 1521288 Dec 27 17:26 benchmark_2.dat
-rw-r--r--. 1 root root   22560 Dec 27 17:26 benchmark_2.idx
-rw-r--r--. 1 root root 1493424 Dec 27 17:26 benchmark_3.dat
-rw-r--r--. 1 root root   22144 Dec 27 17:26 benchmark_3.idx
-rw-r--r--. 1 root root 1600376 Dec 27 17:26 benchmark_4.dat
-rw-r--r--. 1 root root   23728 Dec 27 17:26 benchmark_4.idx
-rw-r--r--. 1 root root 1559296 Dec 27 17:26 benchmark_5.dat
-rw-r--r--. 1 root root   23120 Dec 27 17:26 benchmark_5.idx
-rw-r--r--. 1 root root 1503064 Dec 27 17:26 benchmark_6.dat
-rw-r--r--. 1 root root   22288 Dec 27 17:26 benchmark_6.idx
-rw-r--r--. 1 root root 1567888 Dec 27 17:26 benchmark_7.dat
-rw-r--r--. 1 root root   23248 Dec 27 17:26 benchmark_7.idx
[root@korora-01 data]# du -sk .
10720	.
```

only about 10 MB of stored data.

Since all 10000 files have been written (according to the ID log file) the files are compressed .. which can be confirmed by checking the data:

```
[root@korora-01 v_1_15]# ./weed export -limit 10 -dir /var/zones/seaweed-v01/data -volumeId 1 -collection benchmark
key	name	size	gzip	mime	modified	ttl	deleted
1,0f2f6dae19	.	1031	true		2018-12-27T17:24:56		false
1,19196d8240	.	1031	true		2018-12-27T17:24:56		false
1,2a375165dd	.	1031	true		2018-12-27T17:24:56		false
1,23806f4708	.	1031	true		2018-12-27T17:24:56		false
1,2d37824cd4	.	1031	true		2018-12-27T17:24:56		false
1,386297bd30	.	1029	true		2018-12-27T17:24:56		false
..
```

**Additional context**

Perhaps it makes sense to allow both options for the benchmark ... compressed and uncompressed storage ... in order to allow testing both behaviors. But if CPU compression should be the test target then the test data needs to represent the "final" test data way better than "all zero" or "all random".

So in the current form it seems to me more plausible to have "no compression is done" apply to the volume servers storage behavior.

I would assume that this should be achievable if the data uploaded was marked as "gzip" content.

**Comment by chrislusf** [comment]
This is due to some smarter gzip detection. https://github.com/chrislusf/seaweedfs/commit/c043fd17cb8f9753e284c41a627a269ad951b37d

Need a way to optionally skip this.

**Comment by tomi-engel** [comment]
So then maybe a "quick hack" could be to use some info that allows the benchmakr data to "fail early" in the gzippable test.

E.g. a MIME type ala

```
image/benchmark.fakeRaw
```

to meet the test

```
"if strings.HasPrefix(mtype, "image/")
..
```

**Comment by chrislusf** [comment]
Actually found a bug in the previous diff, which think files without file name extensions are gzippable. Fixed it now.

**Comment by tomi-engel** [comment]
Correct! I did not see that one.
But in that case the benchmark would still run down to the test:

```
isMostlyText := util.IsText(data)
```

.. which might get smarter in future releases and at some point change the behavior again.

Maybe a modification of the benchmark line:

```
fp := &operation.FilePart{Reader: &FakeReader{id: uint64(id), size: fileSize}, FileSize: fileSize}
```

with either a well defined `FileName` or `MimeType` might be useful as well.

Faking a `FileName` might be an interesting addition since it seems to me like this would enable benchmarking the "filer" subsystem too.
As I have never written a line of Go I an not sure what the proper creating of a "FileName" from the `id: uint64(id)` would look like.

Faking the `MimeType: "image/benchmark.noCompression" ` seem like the easier code part ... and it would serve the purpose of explicitly documenting the "idea" behind the data set.

But maybe both could useful modifications?

**Comment by chrislusf** [comment]
fixed accordingly: https://github.com/chrislusf/seaweedfs/commit/2a19511ba848913402b77c2f120ef583b7530a79

btw: golang is easy to code.
