### ISSUE TITLE
"weed mount " changes the mounted dir mod to 777

### ISSUE THREAD

**Issue by ledao** [chrislusf/seaweedfs#806]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**
Not sure.

**System Setup**
List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ledao** [comment]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

Describe the bug
Not sure.
The mounted dir mod is changed to 777.

System Setup
mkdir data
weed server -dir data/ -filer
mkdir mnt
weed mount -dir mnt


Expected behavior
The mnt dir mod should be the same as before.

Screenshots
If applicable, add screenshots to help explain your problem.


Additional context
Add any other context about the problem here.

**Comment by chrislusf** [comment]
which version?
