### ISSUE TITLE
Failed upload file through web UI on linux

### ISSUE THREAD

**Issue by Hacky-DH** [chrislusf/seaweedfs#807]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**
The weed server is on linux 3.10.0-327.28.3
I upload any files through http://<ipaddr>:8888/ from windows
BUT failed. 
The server occurs 500 err, the log is following
```
I1229 10:24:18  7401 needle_parse_multipart.go:38] Reading Content [ERROR] unexpected EOF
E1229 10:24:18  7401 filer_server_handlers_write.go:148] failing to connect to volume server /: Post http://localhost:8080/7,2007acb6c90819: unexpected EOF, POST
2018/12/29 10:24:18 http: superfluous response.WriteHeader call from github.com/chrislusf/seaweedfs/weed/server.writeJson (common.go:49)
I1229 10:24:18  7401 common.go:72] error writing JSON map[error:Post http://localhost:8080/7,2007acb6c90819: unexpected EOF] status 500: http: request method or response status code does not allow body
```

**System Setup**
```
weed version 1.16 linux amd64
weed server -dir data/ -filer
```

**Expected behavior**
upload files to server

**Comment by chrislusf** [comment]
What's the command line to upload?

**Comment by Hacky-DH** [comment]
I click the upload button on http://ipaddr:8888/ web page to upload

**Comment by chrislusf** [comment]
can not reproduce. maybe related to the javascript or browser

**Comment by Hacky-DH** [comment]
I use Google Chrome 70.0.3538.110
But through a http proxy
I could't find the reason of EOF error yet

**Comment by chrislusf** [comment]
seems the document type matters. ".jpg" is not good. ".docx" is fine.
