### ISSUE TITLE
按volumeId删除的接口没有grpc实现

### ISSUE THREAD

**Issue by dongyuandai** [chrislusf/seaweedfs#808]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**
在weedfs0.99，删除了接口/admin/volume/delete，但是没有对应的grpc的实现。这个接口对我们很重要，能提供实现吗？谢谢！
                                commits on oct 15,2018  66a353d
                      "remove volume server /admin/volume/delete"

**System Setup**
List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by chrislusf** [comment]
Please describe your use cases.

**Comment by dongyuandai** [comment]
谢谢，我们是在循环覆盖的时候利用到这个接口，按volumeId删除。
此外，如果想在python代码中调用这个grpc接口，该怎么做呢？能否提供一段demo代码，谢谢！
