### ISSUE TITLE
What is the difference between this and IPFS?

### ISSUE THREAD

**Issue by DaniellMesquita** [chrislusf/seaweedfs#810]

**Comment by ijunaid8989** [comment]
This doesn't sound like an issue. It depends on how/what/why are you going to use any of these.

For starter, you can read this https://www.usenix.org/legacy/event/osdi10/tech/full_papers/Beaver.pdf to get clarified about Seaweedfs.

**Comment by chrislusf** [comment]
different use cases. 

SeaweedFS is on solving the storage metadata efficiency. 

IPFS is more on locating, sharing, and securing data.
