### ISSUE TITLE
upload batch file from memory

### ISSUE THREAD

**Issue by Curchan** [chrislusf/seaweedfs#812]
i wanna upload batch of file  from memory. 
does master provide assign batch of fileid API ? 
master's assign API  param 'count' look like no use.

---------------------------------------------------------------
curl "http://192.168.227.128:9333/dir/assign?count=100"
 {"fid":"6,0886591bb5","url":"127.0.0.1:8081","publicUrl":"127.0.0.1:8081","count":100}

curl "http://192.168.227.128:9333/dir/assign?count=0"
 {"fid":"1,6c5a04f21f","url":"127.0.0.1:8081","publicUrl":"127.0.0.1:8081","count":1}

**Comment by chrislusf** [comment]
No.

**Comment by chrislusf** [comment]
The count is for reserving a few file ids, not for batch assignments.

**Comment by Curchan** [comment]
i fill in 2 and 3 .  master return same result, just one file id.

**Comment by chrislusf** [comment]
see https://github.com/chrislusf/seaweedfs/wiki/Use-Cases#saving-image-with-different-sizes
