### ISSUE TITLE
My weed volume start error :unknown port,by docker

### ISSUE THREAD

**Issue by Aliyzz** [chrislusf/seaweedfs#813]
>Master command : docker run -d -p 8033:9333 --name weed-master chrislusf/seaweedfs master
result: success
>Volume command: docker run -p 8034:8080 -p 18080:18080 --name weed-volume chrislusf/seaweedfs volume -max=5 -mserver=“weed-master:8033” -port=8080
result: fail
SendHeartbeat to “weed-master:8033”: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp: address tcp/8033”: unknown port"

Why??

**Comment by chrislusf** [comment]
This is a basic docker question.

because "weed-master" is an internal-to-docker address and port 8033 is an external-to-docker address.

**Comment by Aliyzz** [comment]
use [docker run -p 8034:8080 -p 18080:18080 --name weed-volume chrislusf/seaweedfs volume -max=5 -mserver=“real IP:8033” -port=8080]，the same result.
