### ISSUE TITLE
Read failed! There are same offset value for 2 different fids in the same .idx file.

### ISSUE THREAD

**Issue by MaYX123** [chrislusf/seaweedfs#818]
Hi Chirs, I did 10 million small files uploading test by version 1.14 concurrently, the result was nice without finding any failed. However, while read these files, 2 files failed. We check the issue as follows,

1. For file with key 0180bb62, unmatching cookie was reported,
`request /1175,0180bb620c1f97b8 with cookie:c1f97b8 expected:d9eaa9e9 from 192.168.100.11:41038 agent curl/7.29.0`
2. From *_1175.idx for volume 1175(each small file size is 100k), we found that there are same offset value (44 0C 24 3B) for key 0180bb62 (the error one) and key 018138bb as follows,
```
   00 00 00 00 01 80 BB 62 44 0C 24 3B 00 01 86 C4   # *_1175.idx line M
	。。。
   00 00 00 00 01 81 38 BB 44 0C 24 3B 00 01 86 C4   # *_1175.idx line N
```
3. In *_1175.dat for volume 1175, the offset 440C243B map to a file with cookie d9eaa9e9. So we can visit the file by /1175,0180bb62d9eaa9e9 or /1175,018138bbd9eaa9e9 but not /1175,0180bb620c1f97b8.
4. After running "weed export" for volume 1175, there was not any record for 1175,0180bb62 while there was 1175,018138bb record.
5. After running "weed fix" for volume 1175, a new *_1175.idx was generated, only line M and line N changed,
```
   00 00 00 00 01 81 38 BB 44 0C 24 3B 00 01 86 C4    # fixed *_1175.idx line M, replaced by 018138bb	。。。
   00 00 00 00 01 80 E8 B2 44 8C CA 15 00 01 86 C4    # fixed *_1175.idx line N, a new file key
```
6. Another read failed file has the same problem in volume 1217 (each small file size is 500k),
```
   00 00 00 00 01 80 BB 60 0B 45 47 BE 00 07 A1 44  # *_1217.idx line K
   。。。
   00 00 00 00 01 81 38 A5 0B 45 47 BE 00 07 A1 44  # *_1217.idx line L
```
We have some questions,

1. "weed fix" is to fix the .idx only by .dat, so we think the file 0180bb62 had lost while writing, but log or HTTP did't report the problem or we just missed the error report.
2. These file keys are similar, 0180bb62 vs 018138bb, 0180bb60 vs 018138a5, is it possible the goroutine disordered at that moment?
3. During writing, there is sync.Mutex in func (v *Volume) writeNeedle(n *Needle), I think it is impossible that there are two same offset for different fid in one .idx, is it right?

**Comment by chrislusf** [comment]
This seems also related to https://github.com/chrislusf/seaweedfs/pull/836
