### ISSUE TITLE
Update from 1.15 to 1.20, broke the filer

### ISSUE THREAD

**Issue by ijunaid8989** [chrislusf/seaweedfs#820]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**
We have been running on seaweedfs 1.15, and I updated it to v1.20
1. First I got a few errors which I will display in the screenshot below, which go away after few restarts.
2. From 9:53:52 to 10:15:23, the new version was deployed. and Filer was working for only saving files. It was saving them but didn't open the jpeg in the browser as well as through HTTP request. but Files are present there with full length.

**System Setup**
Ubuntu-1804-bionic-64-minimal.
Filer was started as 

`/opt/go/bin/weed -v=0 server -filer=true -ip=1xx.xxx.xxx.31 -dir=/storage/new_master -volume.max=3000 -volume.images.fix.orientation=false -pulseSeconds=5`

**Expected behavior**
It should start saving jpegs and also serving them, all old files were opening in browsers as well as through HTTP. but newer files were not opening (I repeat, Files only. not directories.)

**Screenshots**
![image](https://user-images.githubusercontent.com/13561999/50812119-43026100-1333-11e9-8910-d837f2ea9ba3.png)
![image](https://user-images.githubusercontent.com/13561999/50812246-ce7bf200-1333-11e9-8b3c-f2db7720da04.png)

**Additional context**
filer.toml file looks like this

```
[memory]
# local in memory, mostly for testing purpose
enabled = false

[leveldb]
# local on disk, mostly for simple single-machine setup, fairly scalable
enabled = true
dir = "/storage/new_master/filer"					# directory to store level db files
```

**Comment by chrislusf** [comment]
There are nothing related to this.

Please check whether the port 18080 is blocked.

**Comment by ijunaid8989** [comment]
Port was not blocked. I just updated the version.

as it was giving old files correctly but not the newer ones.

**Comment by ijunaid8989** [comment]
Time was meant to be not the exact time but time period between the recorded jpegs were not opening.

Also, I am saying: It was accepting new requests but, the saved files were failed to open.

**Comment by chrislusf** [comment]
The screenshot seems to show filer is failing to get a new file id from the master, via port 9333.

**Comment by chrislusf** [comment]
Could you please show the timing? I am not sure whether it is just a startup issue and how to reproduce this.
