### ISSUE TITLE
when master changed,weed mount cannot be write

### ISSUE THREAD

**Issue by accumulatepig** [chrislusf/seaweedfs#822]
weed version:version 1.15 linux amd64
主节点发生切换之后，weed mount客户端写文件就异常，日志一直报No free volumes left， 得把整个集群重启遍才行(master、volume重启了，但似乎在filer重启才恢复)，已经出现两次了，我自己尝试手工切换主节点又没复现，不清楚问题点在哪
1.weed mount log:
E0103 00:16:56 27334 filehandle.go:194] flush /xxx.jpg: filerGrpcAddr
ess assign volume: rpc error: code = Unknown desc = assign volume: rpc error: code = Unknown desc = No free volumes left!
2. weed master log:
I0103 00:13:25  2957 master_server.go:96] event: &{typ:leaderChange source:0xc0003d2a20 value: prevValue:xx1:9333}
I0103 00:13:31  2957 master_grpc_server.go:22] unregister disconnected volume server xx2:9080
I0103 00:13:31  2957 topology_event_handling.go:56] Removing Volume 71 from the dead volume server xx2:9080
I0103 00:13:31  2957 volume_layout.go:241] Volume 71 has 1 replica, less than required 2
I0103 00:13:31  2957 topology_event_handling.go:56] Removing Volume 41 from the dead volume server xx2:9080
I0103 00:13:31  2957 volume_layout.go:241] Volume 41 has 1 replica, less than required 2
I0103 00:13:31  2957 topology_event_handling.go:56] Removing Volume 58 from the dead volume server xx2:9080
......

3.上述volume server xx2上
I0103 00:13:31  9238 volume_grpc_client_to_master.go:75] Volume Server found a new master newLeader: xx3:9333 instead of xx1:9333
I0103 00:13:31  9238 volume_grpc_client_to_master.go:53] Heartbeat to: xx3:9333

4. df -h in weed mount client
df -h   (used space always shows 0 ,not show the actual usage before restart cluster)
Filesystem                 Size  Used Avail Use% Mounted on
SeaweedFS                  2.0T     0  2.0T   0% /seaweedfs

5.weed filer not found the issue log ,like reconnect the new master 。 But when i shutdown the master server by myself for test , the filer will show related logs。 is the filer not feel the master changed?

**Comment by chrislusf** [comment]
should be restarting "filer". What's the command line you use to start filer?

**Comment by accumulatepig** [comment]
filer start command like this:   
 ./weed -log_dir=/logs -v=3 filer -ip=filer_node1 -port=9081 -defaultReplicaPlacement=100 -dirListLimit=500000 -master=master_ip1:9333,master_ip2:9333,master_ip3:9333,master_ip4:9333,master_ip5:9333,master_ip6:9333,master_ip7:9333 -dataCenter=DC1

 ./weed -log_dir=/logs -v=3 filer -ip=filer_node2 -port=9081 -defaultReplicaPlacement=100 -dirListLimit=500000 -master=master_ip1:9333,master_ip2:9333,master_ip3:9333,master_ip4:9333,master_ip5:9333,master_ip6:9333,master_ip7:9333 -dataCenter=DC2

 ./weed -log_dir=/logs -v=3 filer -ip=filer_node3 -port=9081 -defaultReplicaPlacement=100 -dirListLimit=500000 -master=master_ip1:9333,master_ip2:9333,master_ip3:9333,master_ip4:9333,master_ip5:9333,master_ip6:9333,master_ip7:9333 -dataCenter=DC3

but when i try to change master by myself ,everything seems ok 。 but sometimes wrong ihappened in running time, make the flush data fail , and data lost

**Comment by chrislusf** [comment]
I think when the physical network cable is disconnected, the connection
could be slow to time out the connection.

**Comment by accumulatepig** [comment]
you mean filter maybe time out to connection to new leader? but filer log shows nothing about connection

**Comment by accumulatepig** [comment]
issue happend again weed mount log:
I0111 10:36:38  5699 dir.go:126] create: directory:"/" entry:<name:"test.log" attributes:<mtime:1547174198 file_mode:488 crtime:1547174198 re
plication:"100" > >
I0111 10:36:39  5699 dirty_page.go:170] assign volume failure count:1 replication:"100" : rpc error: code = Unknown desc = assign volume: rpc error: c
ode = Unknown desc = Cannot grow volume group! No matching data node found!
DC2:Not matching preferred data center:DC1
DC32:Not matching preferred data center:DC1
DC1:Free:0 < Expected:1
E0111 10:36:39  5699 filehandle.go:194] flush //test.log: filerGrpcAddress assign volume: rpc error: code = Unknown desc = assign volume: rpc
 error: code = Unknown desc = Cannot grow volume group! No matching data node found!
DC2:Not matching preferred data center:DC1
DC2:Not matching preferred data center:DC1
DC1:Free:0 < Expected:1

#df -h
Filesystem                 Size  Used Avail Use% Mounted on
SeaweedFS                  2.0T     0  2.0T   0% /weed

when restart filer ,everything will be ok
#df -h
Filesystem                 Size  Used Avail Use% Mounted on
SeaweedFS                  2.0T     1.2T  0.8T  60% /weed

**Comment by chrislusf** [comment]
Need to see the logs on the masters.

**Comment by accumulatepig** [comment]
I will collect the master log , does the filer and master use the keep-alive connection ?  
Is there a mechanism to guarantee the current connection exception or abnormally then to rediscover the master node?

**Comment by accumulatepig** [comment]
shutdown the leaderA , filter connect to new leaderB , then start the A ,filter also connect to  A ;   then shutdown B , start B like this...     I found filter will  connect to pre leader  and current leader

**Comment by chrislusf** [comment]
> shutdown the leaderA , filter connect to new leaderB , then start the A ,filter also connect to A ; then shutdown B , start B like this... I found filter will connect to pre leader and current leader ,not only connect the current leader

Tested this case. This is fixed now.
