### ISSUE TITLE
brain split happened when network interrupts between dc

### ISSUE THREAD

**Issue by accumulatepig** [chrislusf/seaweedfs#825]
weed vesion:1.15
1.  weed master: deployed in 3 DC  , 3 nodes in dc1 + 2 in  dc2 +in  2 dc3 ,
2. volumer server :  3 nodes in dc1 + 3 in dc2 + 3 in dc3
3. when the network between dc3 and dc2  interrupt ,  dc3 and dc1 also interrupt  ,but network between 
    dc1 and dc2  is ok , so dc3 is a network isolated island 。
4.  the original leader in dc1 , but when network issue happened ,  the second leader selected in dc3  and dc3's volumer server connect to the dc3 new leader.    Forming two clusters , dc1 and dc2 is a cluster  ,dc3 is a cluster
5. when the network issue  between dc3 and dc1、dc2  solved ,  also two leader in whole cluster util restart the dc3's leader.

**Comment by chrislusf** [comment]
what's the command line to start the 7 master servers?

**Comment by accumulatepig** [comment]
7 master start commad like this :
weed -log_dir=/logs -v=2 master -defaultReplication=100 -ip=node_ip -port=9333 -mdir=/eaweedfs/metadata -volumeSizeLimitMB=10000 -peers=dc1_ip1:9333,dc1_ip2:9333,dc1_ip3:9333,dc2_ip1:9333,dc2_ip2:9333,dc3_ip1:9333,dc3_ip2:9333

**Comment by chrislusf** [comment]
what kind of network interruption? It'll be good if this can be reproduced. basically the isolated dc3 elected one leader from the 2 masters, even though the quorum is 4.

**Comment by accumulatepig** [comment]
dc3 cannot reach other dc  beacuse of  network provider's line  interruption, but dc3 internal network is ok。 totally 7 nodes ,  the isolated dc3 elected one leader from the 2 dc3's masters , not reach half of 7 nodes.  i think it can be reproduced by iptables to interrupt the network between dc3 and other dc

**Comment by accumulatepig** [comment]
1.  dc3 elected master(the second master:dc3_masterIP1):
I0110 00:42:54 10646 master_server.go:96] event: &{typ:leaderChange source:0xc0000d85a0 value: prevValue:dc1_masterIP1:9333}
I0110 00:45:03 10646 node.go:223] topo adds child DC3
I0110 00:45:03 10646 node.go:223] topo:DC3 adds child rack01
I0110 00:45:03 10646 node.go:223] topo:DC3:rack01 adds child dc3_volumer1:9080
I0110 00:45:03 10646 master_grpc_server.go:66] added volume server dc3_volumer1:9080
I0110 00:45:03 10646 node.go:223] topo:DC3 adds child rack02
I0110 00:45:03 10646 node.go:223] topo:DC3:rack02 adds child dc3_volumer2:9080
I0110 00:45:03 10646 master_grpc_server.go:66] added volume server dc3_volumer2:9080
I0110 00:45:03 10646 node.go:223] topo:DC3 adds child rack03
I0110 00:45:03 10646 node.go:223] topo:DC3:rack03 adds child dc3_volumer3:9080
I0110 00:45:03 10646 master_grpc_server.go:66] added volume server dc3_volumer3:9080
I0110 01:49:28 10646 master_server.go:96] event: &{typ:leaderChange source:0xc0000d85a0 value::dc3_masterIP1:9333 prevValue:}
I0110 01:49:28 10646 master_server.go:98] [ dc3_masterIP1:9333 ] dc3_masterIP1:9333 becomes leader.
I0110 01:49:44 10646 master_grpc_server.go:142] + client filerdc3_filerIP1:53304
I0110 01:49:44 10646 master_grpc_server.go:142] + client filerdc3_filerIP2:40560
I0110 01:49:44 10646 master_grpc_server.go:142] + client filerdc3_filerIP3:43422
I0110 01:58:06 10646 topology_vacuum.go:119] Start vacuum on demand with threshold: 0.300000
I0110 01:58:06 10646 topology_vacuum.go:151] check vacuum on collection: volume:104
I0110 01:58:06 10646 topology_vacuum.go:151] check vacuum on collection: volume:219
......

2. dc3 another master node:
I0110 00:42:54  2805 master_server.go:96] event: &{typ:leaderChange source:0xc0000d4c60 value: prevValue:dc1_masterIP1:9333}
I0110 01:49:39  2805 master_server.go:96] event: &{typ:leaderChange source:0xc0000d4c60 value: prevValue:dc3_masterIP1:9333}

3. dc1 original master(dc1_masterIP1):
I0110 00:43:15   843 master_grpc_server.go:168] - client filerdc3_filerIP1:58366: rpc error: code = Canceled desc = context canceled
I0110 00:43:15   843 master_grpc_server.go:168] - client filerfilerdc3_filerIP:44388: rpc error: code = Canceled desc = context canceled
I0110 00:43:15   843 master_grpc_server.go:152] - client filerdc3_filerIP1:58366
I0110 00:43:15   843 master_grpc_server.go:168] - client filerfilerdc3_filerIP3:44508: rpc error: code = Canceled desc = context canceled
I0110 00:43:15   843 master_grpc_server.go:152] - client filerfilerdc3_filerIP:44388
I0110 00:43:15   843 master_grpc_server.go:152] - client filerfilerdc3_filerIP3:44508
I0110 00:43:17   843 master_grpc_server.go:22] unregister disconnected volume server dc3_volumer1:9080
I0110 00:43:17   843 master_grpc_server.go:22] unregister disconnected volume server dc3_volumer2:9080
I0110 00:43:17   843 topology_event_handling.go:56] Removing Volume 92 from the dead volume server dc3_volumer1:9080
I0110 00:43:17   843 topology_event_handling.go:56] Removing Volume 210 from the dead volume server dc3_volumer2:9080
I0110 00:43:17   843 volume_layout.go:241] Volume 92 has 1 replica, less than required 2
I0110 00:43:17   843 topology_event_handling.go:56] Removing Volume 197 from the dead volume server dc3_volumer1:9080
I0110 00:43:17   843 volume_layout.go:241] Volume 197 has 1 replica, less than required 2
I0110 00:43:17   843 volume_layout.go:217] Volume 197 becomes unwritable
I0110 00:43:17   843 topology_event_handling.go:56] Removing Volume 41 from the dead volume server dc3_volumer1:9080
I0110 00:43:17   843 master_grpc_server.go:22] unregister disconnected volume server dc3_volumer3:9080
I0110 00:43:17   843 topology_event_handling.go:56] Removing Volume 34 from the dead volume server dc3_volumer3:9080
......

**Comment by ingardm** [comment]
Maybe using this tried and true raft implementation would be a solution? https://github.com/etcd-io/etcd/tree/master/raft

**Comment by chrislusf** [comment]
How to reproduce it and prove either way?

**Comment by chrislusf** [comment]
thanks! this seems a timeout issue where node-0 needs to actively detect stream gRPC disconnections.

**Comment by chrislusf** [comment]
@PapaYofen please check whether this https://github.com/chrislusf/seaweedfs/commit/1d103e3ed54d0e5cf17dbc489ba412ce96c88a20 fix the problem.

**Comment by PapaYofen** [comment]
> @PapaYofen please check whether this [1d103e3](https://github.com/chrislusf/seaweedfs/commit/1d103e3ed54d0e5cf17dbc489ba412ce96c88a20) fix the problem.

It only reduces the append entry request time to follower, but can't solve split-brain problem. 
**Valid solution may be**: 
1. remove go keyword in `go t.RaftServer.Do(NewMaxVolumeIdCommand(next))`
2. do not wait for heartbeat to append entry to followers, but immediately trigger the append entry process
3. step down leader to follower, if number of active followers not up to quorum size, [like ectd raft](https://github.com/etcd-io/etcd/issues/3866)

2 and 3 need update raft which i do not understand thoroughly, maybe **_etcd raft is a better choice_** solving this split-brain issue already

**Comment by chrislusf** [comment]
I think it is fixed. Let me know if otherwise.

**Comment by accumulatepig** [comment]
version:1.23  (seems split-brain issue already)
                          Dc1 Dc2 Dc3
3 master nodes: m1  m2  m3
3 volume nodes: v1  v2  v3
1 filer node:        f1
current leader: m1

master m3 log:Now block dc3 and make it to be an isolated network environment, v3 disconnect from m1 and connect to m3 , v1 and v2 also connect to m1。m1 and m3 ,both nodes are leader?
I0122 17:00:25 37332 master_server.go:68] Volume Size Limit is 10000 MB
I0122 17:00:25 37332 master.go:80] Start Seaweed Master 1.23 at 0.0.0.0:9333
I0122 17:00:25 37332 master.go:109] Start Seaweed Master 1.23 grpc server at 0.0.0.0:19333
I0122 17:00:25 37332 raft_server.go:47] Starting RaftServer with v3:9333
I0122 17:00:27 37332 raft_server.go:88] current cluster leader: 
I0122 19:41:22 37332 master_server.go:96] event: &{typ:leaderChange source:0xc0000c66c0 value: prevValue:m1:9333}
I0122 19:42:16 37332 node.go:223] topo adds child DC3
I0122 19:42:16 37332 node.go:223] topo:DC3 adds child rack01
I0122 19:42:16 37332 node.go:223] topo:DC3:rack01 adds child v3:9080
I0122 19:42:16 37332 master_grpc_server.go:67] added volume server v3:9080

master m3 log：dc3 network is back to normal , m3 to be the all cluster leader 
I0122 19:46:20 37332 master_server.go:96] event: &{typ:leaderChange source:0xc0000c66c0 value:m3:9333 prevValue:}
I0122 19:46:20 37332 master_server.go:98] [ m3:9333 ] m3:9333 becomes leader.
I0122 19:46:20 37332 master_grpc_server.go:143] + client filerf1:8309
I0122 19:46:35 37332 node.go:223] topo adds child DC2
I0122 19:46:35 37332 node.go:223] topo:DC2 adds child rack01
I0122 19:46:35 37332 node.go:223] topo:DC2:rack01 adds child v2:9080
I0122 19:46:35 37332 master_grpc_server.go:67] added volume server v2:9080
I0122 19:46:35 37332 node.go:223] topo adds child DC1
I0122 19:46:35 37332 node.go:223] topo:DC1 adds child rack01
I0122 19:46:35 37332 node.go:223] topo:DC1:rack01 adds child v1:9080
I0122 19:46:35 37332 master_grpc_server.go:67] added volume server v1:9080

filer f1 netstat:   filer also connect to preleader and current leader
#netstat -anp|grep 9333
tcp        0      0 f1:8309          m3:19333         ESTABLISHED 40087/./weed        
tcp        0      0 f1:45036         m1:19333         ESTABLISHED 40087/./weed

**Comment by PapaYofen** [comment]
sudo iptables -I INPUT -s node-1-ip -j DROP

sudo iptables -I INPUT -s node-2-ip -j DROP

**Comment by PapaYofen** [comment]
https://github.com/PapaYofen/raft/commit/ecfccfc4498cd65d892f40adb4e7598224284347
+
https://github.com/PapaYofen/seaweedfs/blob/5737965eaa0e65073f7f33738fef0c4557de0bb1/weed/topology/topology.go#L94

maybe this two commits can fix split-brain problem

**Comment by accumulatepig** [comment]
> [PapaYofen/raft@ecfccfc](https://github.com/PapaYofen/raft/commit/ecfccfc4498cd65d892f40adb4e7598224284347)
> +
> https://github.com/PapaYofen/seaweedfs/blob/5737965eaa0e65073f7f33738fef0c4557de0bb1/weed/topology/topology.go#L94
> 
> maybe this two commits can fix split-brain problem

I tried ,but also two leaders.
step:
masterNodes :  node1 node2 node3
1. node1 current leader
2. block network node1 to node2 and node3  , but node2 and node3 communicate normally
3. node2 alse becomes the leader node

**Comment by PapaYofen** [comment]
let me know the reproduce step please

**Comment by accumulatepig** [comment]
> let me know the detailed reproduce step please
> And the latest commit of [seaweedfs](https://github.com/PapaYofen/seaweedfs/commit/a528bf1a544c0950a993904a9edc2e7305bacfda) and [raft](https://github.com/PapaYofen/raft/commit/478bfd9d0df758646923b44069e2164a5d31dcf0) can be used for test again.

@PapaYofen @chrislusf  the latest commits  seems work fine ,  the leader will be elected from more than half of nodes cluster ,   the leader from less than half of nodes cluster will become candidate , There will be always one leader node

**Comment by PapaYofen** [comment]
if chirs approves this solution, i will pull a merge request

**Comment by accumulatepig** [comment]
> if chirs approves this solution, i will pull a merge request

@chrislusf  how about this?

**Comment by chrislusf** [comment]
@accumulatepig  I am not sure what are the exact versions of code from the seaweedfs and raft repos you have tested.

Besides, I have changed the raft code from http to grpc recently, so the change does not apply.

**Comment by PapaYofen** [comment]
@chrislusf 

**About raft:**
1. tested raft commit is https://github.com/PapaYofen/raft/commit/478bfd9d0df758646923b44069e2164a5d31dcf0, based on https://github.com/chrislusf/raft/commit/5f7ddd8f479583daf05879d3d3b174aa202c8fb7
2. i can cherry-pick the tested commit to [the latest raft](https://github.com/chrislusf/raft/commit/cc54ba4a4ef32c5ac0fcc61fc7cbbf901410d127).  

**About seaweedfs:**
to fix the brain-split problem, it only needs to change func _NextVolumeId_  from
```golang
func (t *Topology) NextVolumeId() storage.VolumeId {
	vid := t.GetMaxVolumeId()
	next := vid.Next()
	go t.RaftServer.Do(NewMaxVolumeIdCommand(next))
	return next
}
```
to 
```golang
func (t *Topology) NextVolumeId() (storage.VolumeId, error) {
	vid := t.GetMaxVolumeId()
	next := vid.Next()
	if _, err := t.RaftServer.Do(NewMaxVolumeIdCommand(next)); err != nil {
		return 0, err
	}
	return next, nil
}
```

**Comment by chrislusf** [comment]
This commit https://github.com/chrislusf/seaweedfs/commit/7a493bbefa8aafe08ce9a7035c6fd0cf2e206e6c may be the real fix. Setting up the test env is too much work, I have not checked it yet.

**Comment by PapaYofen** [comment]
> This commit [7a493bb](https://github.com/chrislusf/seaweedfs/commit/7a493bbefa8aafe08ce9a7035c6fd0cf2e206e6c) may be the real fix. Setting up the test env is too much work, I have not checked it yet.

i dont think this commit fix brain split issue, due to raft not support auto-changing role from leader to candidate after brain split.
@accumulatepig have your test this commit before?

**Comment by accumulatepig** [comment]
> > This commit [7a493bb](https://github.com/chrislusf/seaweedfs/commit/7a493bbefa8aafe08ce9a7035c6fd0cf2e206e6c) may be the real fix. Setting up the test env is too much work, I have not checked it yet.
> 
> i dont think this commit fix brain split issue, due to raft not support auto-changing role from leader to candidate after brain split.
> @accumulatepig have your test this commit before?

yes ,I tried commit 7a493bb ,but it doesn't work .
@PapaYofen your lastest commit work fine

**Comment by chrislusf** [comment]
@accumulatepig thanks for testing and confirming
@PapaYofen thanks for your contribution. Please send PR to both repos.

**Comment by PapaYofen** [comment]
raft pr has also been sent

**Comment by accumulatepig** [comment]
@chrislusf @PapaYofen 
I tried weed 1.25  and fix the spilt brain issue, but maybe found another issue in special circumstances:
DC1: 3 master nodes , 3 volumes nodes
DC2: 2 master nodes, 3 volumes nodes
DC3: 2 master nodes, 3 volumes nodes
leader nodes in DC3 at first,when only  DC3's master nodes cannot reach DC2 and DC1's master nodes, the leader nodes elected from DC1 and DC3's leader became candidate , but all volume nodes still connect the DC3's preleader ,not switch to the current leader in DC1。This scenario only occurs when a network problem happened between the master nodes。 if the whole DC3(contain master、volume、filer） has a network problem with DC1 and DC2 , everything goes well.

**Comment by PapaYofen** [comment]
thanks for your test, i have found the root cause
