### ISSUE TITLE
don't you want change "glog" package to github.com/golang/glog?

### ISSUE THREAD

**Issue by suilongfei** [chrislusf/seaweedfs#826]
don't you want change "glog" package to github.com/golang/glog?

**Comment by chrislusf** [comment]
it was changed from github.com/golang/glog

**Comment by suilongfei** [comment]
but,we will get l "flag redefined:log_dir" error when we use this package and another package with golang/glog

shall we fix this?

**Comment by chrislusf** [comment]
Ok. Please send a PR.
