### ISSUE TITLE
Data Backup error

### ISSUE THREAD

**Issue by shou55** [chrislusf/seaweedfs#833]
./weed  backup -server xxx:xxx -dir . -volumeId=66
I0115 11:39:53 44873 volume_loading.go:69] volumeDataIntegrityChecking failed verifyNeedleIntegrity 66.idx failed: CRC error! Data On Disk Corrupted
I0115 11:39:53 44873 volume_loading.go:73] loading index 66.idx to memory readonly true
I0115 11:39:53 44873 volume_sync.go:132] Fetch needle {1952383 116470430 167350} from 10.10.20.161:12602: Appending volume 66 error: 66.dat is read-only
I0115 11:39:53 44873 volume_sync.go:132] Fetch needle {1952383 116470430 167350} from 10.10.20.161:12602: Appending volume 66 error: 66.dat is read-only
I0115 11:39:53 44873 volume_sync.go:132] Fetch needle {1952383 116470430 167350} from 10.10.20.161:12602: Appending volume 66 error: 66.dat is read-only
Error synchronizing volume 66: Appending volume 66 error: 66.dat is read-only

The first backup can be successful, and it must fail if it is executed again.

**Comment by shou55** [comment]
i find [483](https://github.com/chrislusf/seaweedfs/issues/483)

**Comment by chrislusf** [comment]
What's the version?

**Comment by chrislusf** [comment]
The error is "66.dat is read-only". Change your file permission.

**Comment by shou55** [comment]
use 777 permission or use root also get this error, version 0.76 linux amd64

**Comment by chrislusf** [comment]
I see. The version is too old. I can not remember what was changed. Please test it with latest version if possible.
