### ISSUE TITLE
weed mount raises error

### ISSUE THREAD

**Issue by john-dev** [chrislusf/seaweedfs#837]
Hello,

i am trying to mount a remount server.
A master, a volume and a filer are up and running - all ports are reachable.
OSXFuse is installed.
Seaweed version: version 1.18 darwin amd64

When trying to mount, i get the following error:
$ ./weed mount -filer=myserver.com:8889 -dir=/tmp/weed
This is SeaweedFS version 1.18 darwin amd64
F0116 11:30:02 14267 mount_std.go:72] exit status 255
goroutine 1 [running]:
github.com/chrislusf/seaweedfs/weed/glog.stacks(0xc00009d100, 0xc0000aa500, 0x36, 0x40)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:767 +0xb1
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).output(0x2e48a00, 0xc000000003, 0xc000150000, 0x2dd42ca, 0xc, 0x48, 0x0)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:718 +0x303
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).printDepth(0x2e48a00, 0x3, 0x1, 0xc001547e20, 0x1, 0x1)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:647 +0x12b
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).print(...)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:638
github.com/chrislusf/seaweedfs/weed/glog.Fatal(...)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:1129
github.com/chrislusf/seaweedfs/weed/command.runMount(0x2e37b00, 0xc0000c6030, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/command/mount_std.go:72 +0x47d
main.main()
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/weed.go:67 +0x31b

Any ideas?

**Comment by john-dev** [comment]
I have the exact same problem with linux, Ubuntu 18.04.1 LTS

**Comment by john-dev** [comment]
i managed to avoid that error by editing /etc/fuse.conf to allow user_shares.
The problem remains on OS-X!

**Comment by chrislusf** [comment]
What's the"df" command output? How the previous mount was stopped? Did you umount?

**Comment by john-dev** [comment]
df is empty since it doesn't mount it at all.
There was no previous mount - it never worked!

**Comment by chrislusf** [comment]
What's "i am trying to mount a remount server.", you mean remote?

No clue. I develop on Mac and didn't see this. Try to upgrade osxfuse.

**Comment by john-dev** [comment]
Yes, remote - sorry. But it is not working with a local server as well.
Upgrading OSXFuse was the first thing i tried.

Okay, thanks!

**Comment by chrislusf** [comment]
This is similar https://github.com/osxfuse/osxfuse/issues/446

Just google "code 255 osxfuse"

**Comment by john-dev** [comment]
Allright, i'll try to shutdown unneeded kernel extensions.
Thanks

**Comment by john-dev** [comment]
In case someone has the same problem as me.

I managed to get it working:
The Fuse kernel extension wasn't fully loaded.
I unloaded some unneeded kernen extensions (intel haxm, virtualbox etc.) and loaded osxfuse manually - using: sudo kextload com.github.osxfuse.filesystems.osxfuse
