### ISSUE TITLE
volume start error

### ISSUE THREAD

**Issue by zhangrenfu1** [chrislusf/seaweedfs#840]
I was maked the master and volume  started on one server;
but when started the volume ,notifyed 

0111 03:26:09  3035 volume_grpc_client_to_master.go:32] heartbeat error: fail to dial localhost:9333 : context deadline exceeded

go  version ,1.11.4
weed version,1.21
what's wrong with the config

**Comment by chrislusf** [comment]
the port 9333 should be open

**Comment by zhangrenfu1** [comment]
i have opened in the firewall,
![image](https://user-images.githubusercontent.com/7300414/51369958-68ac1900-1b30-11e9-9104-9ed8c6499508.png)

**Comment by zhangrenfu1** [comment]
可以用中文交流吗

**Comment by chrislusf** [comment]
please follow the issue creation template and give basic information.
