### ISSUE TITLE
master leader server panic when add other master server

### ISSUE THREAD

**Issue by taotaoo** [chrislusf/seaweedfs#845]
first master：
`nohup ./weed master -port=7333 -mdir=./mastertest -defaultReplication=001 > mastertest.log`
add other master:
`nohup ./weed master -port=7334 -mdir=./mastertest1 -peers=localhost:7333,localhost:7334.localhost:7335 -defaultReplication=001 > mastertest1.log &`

then first master server down.
```
I0123 15:01:11 31256 file_util.go:19] Folder ./mastertest Permission: -rwxrwxr-x
I0123 15:01:11 31256 master_server.go:68] Volume Size Limit is 30000 MB
I0123 15:01:11 31256 master.go:80] Start Seaweed Master 1.23 at 0.0.0.0:7333
I0123 15:01:11 31256 master.go:109] Start Seaweed Master 1.23 grpc server at 0.0.0.0:17333
I0123 15:01:11 31256 raft_server.go:47] Starting RaftServer with localhost:7333
I0123 15:01:11 31256 raft_server.go:51] Peers Change: [] => []
I0123 15:01:13 31256 raft_server.go:75] Initializing new cluster
I0123 15:01:13 31256 raft_server.go:88] current cluster leader: localhost:7333
I0123 15:01:13 31256 master_server.go:102] [ localhost:7333 ] I am the leader!
panic: assertion failed: leader.elected.at.same.term.0


goroutine 57 [running]:
github.com/chrislusf/raft._assert(...)
        /home/travis/gopath/src/github.com/chrislusf/raft/util.go:60
github.com/chrislusf/raft.(*server).processAppendEntriesRequest(0xc0000c25a0, 0xc0004980a0, 0xc0004980a0, 0x0)
        /home/travis/gopath/src/github.com/chrislusf/raft/server.go:948 +0xea5
github.com/chrislusf/raft.(*server).leaderLoop(0xc0000c25a0)
        /home/travis/gopath/src/github.com/chrislusf/raft/server.go:849 +0x3b5
github.com/chrislusf/raft.(*server).loop(0xc0000c25a0)
        /home/travis/gopath/src/github.com/chrislusf/raft/server.go:609 +0x1be
github.com/chrislusf/raft.(*server).Start.func1(0xc0000c25a0)
        /home/travis/gopath/src/github.com/chrislusf/raft/server.go:470 +0x5a
created by github.com/chrislusf/raft.(*server).Start
        /home/travis/gopath/src/github.com/chrislusf/raft/server.go:468 +0x2ab
```

**Comment by chrislusf** [comment]
The first master also need to have the full peer list.

**Comment by taotaoo** [comment]
> The first master also need to have the full peer list.

how can I add master without downtime?

**Comment by OneB1t** [comment]
Hello i was testing cluster setup and i have same problem


11/25/2019 1:13:51 PMpanic: assertion failed: leader.elected.at.same.term.0
11/25/2019 1:13:51 PM
11/25/2019 1:13:51 PM
11/25/2019 1:13:51 PMgoroutine 81 [running]:
11/25/2019 1:13:51 PMgithub.com/chrislusf/raft._assert(...)
11/25/2019 1:13:51 PM	/home/travis/gopath/pkg/mod/github.com/chrislusf/raft@v0.0.0-20190225081310-10d6e2182d92/util.go:60
11/25/2019 1:13:51 PMgithub.com/chrislusf/raft.(*server).processAppendEntriesRequest(0xc0003b4fc0, 0xc0009660f0, 0xc0009660f0, 0x0)
11/25/2019 1:13:51 PM	/home/travis/gopath/pkg/mod/github.com/chrislusf/raft@v0.0.0-20190225081310-10d6e2182d92/server.go:981 +0x9a3
11/25/2019 1:13:51 PMgithub.com/chrislusf/raft.(*server).leaderLoop(0xc0003b4fc0)
11/25/2019 1:13:51 PM	/home/travis/gopath/pkg/mod/github.com/chrislusf/raft@v0.0.0-20190225081310-10d6e2182d92/server.go:882 +0x430
11/25/2019 1:13:51 PMgithub.com/chrislusf/raft.(*server).loop(0xc0003b4fc0)
11/25/2019 1:13:51 PM	/home/travis/gopath/pkg/mod/github.com/chrislusf/raft@v0.0.0-20190225081310-10d6e2182d92/server.go:609 +0x1fd
11/25/2019 1:13:51 PMgithub.com/chrislusf/raft.(*server).Start.func1(0xc0003b4fc0)
11/25/2019 1:13:51 PM	/home/travis/gopath/pkg/mod/github.com/chrislusf/raft@v0.0.0-20190225081310-10d6e2182d92/server.go:470 +0x64
11/25/2019 1:13:51 PMcreated by github.com/chrislusf/raft.(*server).Start
11/25/2019 1:13:51 PM	/home/travis/gopath/pkg/mod/github.com/chrislusf/raft@v0.0.0-20190225081310-10d6e2182d92/server.go:468 +0x1a8

this is my docker compose

version: '2'
services:
  seaweedfs-cronjob:
    image: chrislusf/seaweedfs:1.45
    environment:
      CRON_SCHEDULE: '*/2 * * * * *'
      WEED_MASTER: localhost:9333
    stdin_open: true
    network_mode: host
    tty: true
    command:
    - cronjob
    labels:
      io.rancher.container.pull_image: always
  seaweedfs-master-1:
    image: chrislusf/seaweedfs:1.45
    stdin_open: true
    network_mode: host
    volumes:
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    tty: true
    command:
    - master
    - -defaultReplication=002
    - -port=9333
    - -peers=localhost:9334,localhost:9335
    - -ip=172.27.2.110
    - -mdir=/data/storage4
    labels:
      io.rancher.container.pull_image: always
  seaweedfs-master-2:
    image: chrislusf/seaweedfs:1.45
    stdin_open: true
    network_mode: host
    tty: true
    command:
    - master
    - -defaultReplication=002
    - -port=9334
    - -peers=localhost:9333,localhost:9335
    - -ip=172.27.2.110
    - -mdir=/data/storage4
    labels:
      io.rancher.container.pull_image: always
  seaweedfs-master-3:
    image: chrislusf/seaweedfs:1.45
    stdin_open: true
    network_mode: host
    volumes:
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    tty: true
    command:
    - master
    - -defaultReplication=002
    - -port=9335
    - -peers=localhost:9333,localhost:9334
    - -ip=172.27.2.110
    - -mdir=/data/storage4
    labels:
      io.rancher.container.pull_image: always
  seaweedfs-filer:
    image: chrislusf/seaweedfs:1.45
    stdin_open: true
    network_mode: host
    tty: true
    command:
    - filer
    - -master=localhost:9333,localhost:9334,localhost:9335
    - -ip=172.27.2.110
    - -defaultReplicaPlacement=002
    labels:
      io.rancher.container.pull_image: always
  seaweedfs-volume2:
    image: chrislusf/seaweedfs:1.45
    stdin_open: true
    network_mode: host
    tty: true
    command:
    - volume
    - -max=20
    - -mserver=localhost:9333,localhost:9334,localhost:9335
    - -port=8081
    labels:
      io.rancher.container.pull_image: always
  seaweedfs-volume3:
    image: chrislusf/seaweedfs:1.45
    stdin_open: true
    network_mode: host
    tty: true
    command:
    - volume
    - -max=20
    - -mserver=localhost:9333,localhost:9334,localhost:9335
    - -port=8082
    labels:
      io.rancher.container.pull_image: always
  seaweedfs-cronjob-3:
    image: chrislusf/seaweedfs:1.45
    environment:
      CRON_SCHEDULE: '*/2 * * * * *'
      WEED_MASTER: localhost:9335
    stdin_open: true
    network_mode: host
    tty: true
    command:
    - cronjob
    labels:
      io.rancher.container.pull_image: always
  seaweedfs-volume1:
    image: chrislusf/seaweedfs:1.45
    stdin_open: true
    network_mode: host
    tty: true
    command:
    - volume
    - -max=20
    - -mserver=localhost:9333,localhost:9334,localhost:9335
    - -port=8080
    labels:
      io.rancher.container.pull_image: always
  seaweedfs-cronjob-2:
    image: chrislusf/seaweedfs:1.45
    environment:
      CRON_SCHEDULE: '*/2 * * * * *'
      WEED_MASTER: localhost:9334
    stdin_open: true
    network_mode: host
    tty: true
    command:
    - cronjob
    labels:
      io.rancher.container.pull_image: always

**Comment by zzzzoy** [comment]
> Hello i was testing cluster setup and i have same problem
> 
> ```
> 11/25/2019 1:13:51 PMpanic: assertion failed: leader.elected.at.same.term.0
> 11/25/2019 1:13:51 PM
> 11/25/2019 1:13:51 PM
> 11/25/2019 1:13:51 PMgoroutine 81 [running]:
> 11/25/2019 1:13:51 PMgithub.com/chrislusf/raft._assert(...)
> 11/25/2019 1:13:51 PM	/home/travis/gopath/pkg/mod/github.com/chrislusf/raft@v0.0.0-20190225081310-10d6e2182d92/util.go:60
> 11/25/2019 1:13:51 PMgithub.com/chrislusf/raft.(*server).processAppendEntriesRequest(0xc0003b4fc0, 0xc0009660f0, 0xc0009660f0, 0x0)
> 11/25/2019 1:13:51 PM	/home/travis/gopath/pkg/mod/github.com/chrislusf/raft@v0.0.0-20190225081310-10d6e2182d92/server.go:981 +0x9a3
> 11/25/2019 1:13:51 PMgithub.com/chrislusf/raft.(*server).leaderLoop(0xc0003b4fc0)
> 11/25/2019 1:13:51 PM	/home/travis/gopath/pkg/mod/github.com/chrislusf/raft@v0.0.0-20190225081310-10d6e2182d92/server.go:882 +0x430
> 11/25/2019 1:13:51 PMgithub.com/chrislusf/raft.(*server).loop(0xc0003b4fc0)
> 11/25/2019 1:13:51 PM	/home/travis/gopath/pkg/mod/github.com/chrislusf/raft@v0.0.0-20190225081310-10d6e2182d92/server.go:609 +0x1fd
> 11/25/2019 1:13:51 PMgithub.com/chrislusf/raft.(*server).Start.func1(0xc0003b4fc0)
> 11/25/2019 1:13:51 PM	/home/travis/gopath/pkg/mod/github.com/chrislusf/raft@v0.0.0-20190225081310-10d6e2182d92/server.go:470 +0x64
> 11/25/2019 1:13:51 PMcreated by github.com/chrislusf/raft.(*server).Start
> 11/25/2019 1:13:51 PM	/home/travis/gopath/pkg/mod/github.com/chrislusf/raft@v0.0.0-20190225081310-10d6e2182d92/server.go:468 +0x1a8
> ```
> 
> this is my docker compose
> 
> ```
> version: '2'
> services:
>   seaweedfs-cronjob:
>     image: chrislusf/seaweedfs:1.45
>     environment:
>       CRON_SCHEDULE: '*/2 * * * * *'
>       WEED_MASTER: localhost:9333
>     stdin_open: true
>     network_mode: host
>     tty: true
>     command:
>     - cronjob
>     labels:
>       io.rancher.container.pull_image: always
>   seaweedfs-master-1:
>     image: chrislusf/seaweedfs:1.45
>     stdin_open: true
>     network_mode: host
>     volumes:
>     - /etc/timezone:/etc/timezone:ro
>     - /etc/localtime:/etc/localtime:ro
>     tty: true
>     command:
>     - master
>     - -defaultReplication=002
>     - -port=9333
>     - -peers=localhost:9334,localhost:9335
>     - -ip=172.27.2.110
>     - -mdir=/data/storage4
>     labels:
>       io.rancher.container.pull_image: always
>   seaweedfs-master-2:
>     image: chrislusf/seaweedfs:1.45
>     stdin_open: true
>     network_mode: host
>     tty: true
>     command:
>     - master
>     - -defaultReplication=002
>     - -port=9334
>     - -peers=localhost:9333,localhost:9335
>     - -ip=172.27.2.110
>     - -mdir=/data/storage4
>     labels:
>       io.rancher.container.pull_image: always
>   seaweedfs-master-3:
>     image: chrislusf/seaweedfs:1.45
>     stdin_open: true
>     network_mode: host
>     volumes:
>     - /etc/timezone:/etc/timezone:ro
>     - /etc/localtime:/etc/localtime:ro
>     tty: true
>     command:
>     - master
>     - -defaultReplication=002
>     - -port=9335
>     - -peers=localhost:9333,localhost:9334
>     - -ip=172.27.2.110
>     - -mdir=/data/storage4
>     labels:
>       io.rancher.container.pull_image: always
>   seaweedfs-filer:
>     image: chrislusf/seaweedfs:1.45
>     stdin_open: true
>     network_mode: host
>     tty: true
>     command:
>     - filer
>     - -master=localhost:9333,localhost:9334,localhost:9335
>     - -ip=172.27.2.110
>     - -defaultReplicaPlacement=002
>     labels:
>       io.rancher.container.pull_image: always
>   seaweedfs-volume2:
>     image: chrislusf/seaweedfs:1.45
>     stdin_open: true
>     network_mode: host
>     tty: true
>     command:
>     - volume
>     - -max=20
>     - -mserver=localhost:9333,localhost:9334,localhost:9335
>     - -port=8081
>     labels:
>       io.rancher.container.pull_image: always
>   seaweedfs-volume3:
>     image: chrislusf/seaweedfs:1.45
>     stdin_open: true
>     network_mode: host
>     tty: true
>     command:
>     - volume
>     - -max=20
>     - -mserver=localhost:9333,localhost:9334,localhost:9335
>     - -port=8082
>     labels:
>       io.rancher.container.pull_image: always
>   seaweedfs-cronjob-3:
>     image: chrislusf/seaweedfs:1.45
>     environment:
>       CRON_SCHEDULE: '*/2 * * * * *'
>       WEED_MASTER: localhost:9335
>     stdin_open: true
>     network_mode: host
>     tty: true
>     command:
>     - cronjob
>     labels:
>       io.rancher.container.pull_image: always
>   seaweedfs-volume1:
>     image: chrislusf/seaweedfs:1.45
>     stdin_open: true
>     network_mode: host
>     tty: true
>     command:
>     - volume
>     - -max=20
>     - -mserver=localhost:9333,localhost:9334,localhost:9335
>     - -port=8080
>     labels:
>       io.rancher.container.pull_image: always
>   seaweedfs-cronjob-2:
>     image: chrislusf/seaweedfs:1.45
>     environment:
>       CRON_SCHEDULE: '*/2 * * * * *'
>       WEED_MASTER: localhost:9334
>     stdin_open: true
>     network_mode: host
>     tty: true
>     command:
>     - cronjob
>     labels:
>       io.rancher.container.pull_image: always
> ```
> 
> When i include all other masters to peers it will tell me that odd number of masters required
> 
> run commands:
> 
> master -defaultReplication=002 -port=9333 -peers=localhost:9334,localhost:9335 -mdir=/data/storage4
> master -defaultReplication=002 -port=9334 -peers=localhost:9333,localhost:9335 -mdir=/data/storage4
> master -defaultReplication=002 -port=9335 -peers=localhost:9333,localhost:9334-mdir=/data/storage4

you might need to add some parameter when start master '-ip.bind="0.0.0.0" -ip=localhost'

**Comment by chrislusf** [comment]
> > The first master also need to have the full peer list.
> 
> how can I add master without downtime?

This feature was removed. Master nodes are like zookeeper nodes.

**Comment by chrislusf** [comment]
@zzzzoy Thanks for the answer! Yes. The master needs to specify the "-ip" option.
