### ISSUE TITLE
Question about the size in upload's response

### ISSUE THREAD

**Issue by anako18** [chrislusf/seaweedfs#849]
So after
`> curl -F file=@/home/docs/mypdf.pdf http://127.0.0.1:8080/3,01637037d6`
I get the size of already compressed file, therefore I can't check if the file was uploaded completely without lost bytes. Maybe it makes sense to have initial size in response along with compressed one, or  at least choose a compression level (like for replication)

**Comment by chrislusf** [comment]
Recent versions reports original size.
