### ISSUE TITLE
Fail to start multi masters due to leader election problem

### ISSUE THREAD

**Issue by XinhuiTian** [chrislusf/seaweedfs#851]
Hi chrislusf, I tried to start three masters on the same machine with the commands:

```
nohup ~/weed -logdir $MDIR -alsologtostderr=false \
    master -volumePreallocate -maxCpu 0 -mdir $MDIR -ip $IP -port 9333 \
    -peers=$IP:9333,$IP:9334,$IP:9335 -defaultReplication=010 &

nohup ~/weed -logdir $MDIR -alsologtostderr=false \
    master -volumePreallocate -maxCpu 0 -mdir $MDIR -ip $IP -port 9334 \
    -peers=$IP:9333,$IP:9334,$IP:9335 -defaultReplication=010 &

nohup ~/weed -logdir $MDIR -alsologtostderr=false \
    master -volumePreallocate -maxCpu 0 -mdir $MDIR -ip $IP -port 9335 \
    -peers=$IP:9333,$IP:9334,$IP:9335 -defaultReplication=010 &
```
But I got a `panic: assertion failed: leader.elected.at.same.term.0`, and the full log is as below:

```
panic: assertion failed: leader.elected.at.same.term.0

goroutine 102 [running]:
github.com/chrislusf/raft._assert(...)
        /home/travis/gopath/src/github.com/chrislusf/raft/util.go:60
github.com/chrislusf/raft.(*server).processAppendEntriesRequest(0xc000158d80, 0xc0003820a0, 0xc0003820a0, 0x0)
        /home/travis/gopath/src/github.com/chrislusf/raft/server.go:948 +0xea5
github.com/chrislusf/raft.(*server).leaderLoop(0xc000158d80)
        /home/travis/gopath/src/github.com/chrislusf/raft/server.go:849 +0x3b5
github.com/chrislusf/raft.(*server).loop(0xc000158d80)
        /home/travis/gopath/src/github.com/chrislusf/raft/server.go:609 +0x1be
github.com/chrislusf/raft.(*server).Start.func1(0xc000158d80)
        /home/travis/gopath/src/github.com/chrislusf/raft/server.go:470 +0x5a
created by github.com/chrislusf/raft.(*server).Start
        /home/travis/gopath/src/github.com/chrislusf/raft/server.go:468 +0x2ab
```
After viewing related codes, I find that each master sends a DefaultJoinCommand command to its raft server when it starts up. In the follower loop, when a raft server receives a JoinCommand and if the `log.currentIndex() == 0`, it becomes leader directly. 

I wonder if this could be a problem? Since all the servers has their log.currentIndex() equals to 0 when the system starts up.

I also have rerun this test, and found that the problem occurs randomly, and if I set to sleep 1 second after each master starts up, it can be avoided. I also notice that there is a random timeout before each raft server performs the JoinCommand, but it seems not work for this problem. The weed version is 1.24.

**Comment by chrislusf** [comment]
We can use a random timeout seeded by ip+port

**Comment by lqhl** [comment]
@chrislusf the fixes are reverted and this issue still exists.
