### ISSUE TITLE
[help] Embedded api : any documentation

### ISSUE THREAD

**Issue by sapiens-sapide** [chrislusf/seaweedfs#852]
Is there any tutorial, wiki or documentation explaining how to use seaweedfs embeded in an application ?  
I like to explore how to bring encryption-on-the-fly ontop of FUSE interface.

**Comment by chrislusf** [comment]
no doc.

start reading from https://github.com/chrislusf/seaweedfs/tree/master/weed/filesys

let me know if more questions.

**Comment by sapiens-sapide** [comment]
thanks for your reply and the bootstrap. I'll look there.
