### ISSUE TITLE
I can't delete photos

### ISSUE THREAD

**Issue by prtha112** [chrislusf/seaweedfs#857]
I can't delete photos

**First time**
```
curl -X DELETE http://********:8080/4,07545dad5c6733
{"size":76956}
```
**And this second time**
```
curl -X DELETE http://********:8080/4,07545dad5c6733
{"size":76956}
```

Which the second half should be 0
(Other some id can be 0)

**Comment by chrislusf** [comment]
Follow the issue template to add more info.

**Comment by chrislusf** [comment]
can not help without details. please follow issue template with more context.
