### ISSUE TITLE
Failover-Master-Server in Kubernetes. 

### ISSUE THREAD

**Issue by prasus** [chrislusf/seaweedfs#860]
**Describe the bug**

I have got a single master cluster in kubernetes which works perfectly fine. I am thinking of configuring failover master service and wondering if that's supported/possible on kubernetes.

While the provided [example](https://github.com/chrislusf/seaweedfs/wiki/Failover-Master-Server) works well for setup's based on single server (running master services on different ports in localhost), it will fail on multi-pod deployment's as we can't correctly specify `-peers` argument, I tried using the pod dns address, but it fails to form a single cluster as seen in the command output's given below. 😞 

**System Setup**
master configured as `StatefulSet` with `--replicas=3` and using the start command 

`/usr/bin/weed master -port 9333 -mdir /seaweeddata -peers localhost:9333,test-seaweedfs-master-1:9333,test-seaweedfs-master-2:9333`

cluster status from Pod's. 

```bash
kubectl  exec -it test-seaweed-master-0 -- curl localhost:9333/cluster/status?pretty=true
{
  "IsLeader": true,
  "Leader": "localhost:9333",
  "Peers": [
    "test-seaweed-seaweedfs-master-1:9333",
    "test-seaweed-seaweedfs-master-2:9333"
  ]
}

kubectl  exec -it test-seaweed-master-1 -- curl localhost:9333/cluster/status?pretty=true
{
  "IsLeader": true,
  "Leader": "localhost:9333",
  "Peers": [
    "test-seaweed-seaweedfs-master-1:9333",
    "test-seaweed-seaweedfs-master-2:9333"
  ]
}

kubectl  exec -it test-seaweed-master-2 -- curl localhost:9333/cluster/status?pretty=true
{
  "IsLeader": true,
  "Leader": "localhost:9333",
  "Peers": [
    "test-seaweed-seaweedfs-master-1:9333",
    "test-seaweed-seaweedfs-master-2:9333"
  ]
}
```
Cheers,
Prasad

**Comment by chrislusf** [comment]
Try to add "-ip=xxxxx" for "weed master"

**Comment by chrislusf** [comment]
any updates?
