### ISSUE TITLE
why I can't find my files in mysql

### ISSUE THREAD

**Issue by live-xy** [chrislusf/seaweedfs#866]
I have running a master server and volume server ,   and I add a filer to it .
when I visit ip:8888 and upload file, it can shows in mysql correctly .
but I upload files by  master/dir/assign , and it uploads successfully , but I can't find anything in mysql database
could you help me , thx

**Comment by chrislusf** [comment]
mysql is one of the filer store.

"upload files by master/dir/assign and upload to volume server directly" does not go through filer.
