### ISSUE TITLE
can not access cluster/status v1.25 

### ISSUE THREAD

**Issue by yxb3130** [chrislusf/seaweedfs#870]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**
curl "http://localhost:9333/cluster/status?pretty=y"
404 page not found

but 1.24 works

**Comment by chrislusf** [comment]
this is removed since all cluster operations are moved to grpc.

**Comment by rdsuncn** [comment]
客户端还在使用这个特性，像 java 客户端

**Comment by chrislusf** [comment]
Is there any logic depends on this or just for checking? Please show me some code.
