### ISSUE TITLE
weed server  mode can’t set the master directory

### ISSUE THREAD

**Issue by ckhker** [chrislusf/seaweedfs#872]
weed server -master.port=9333 -volume.port=8080 -dir="data" -filer=true

-dir does not work for master.
Still saved to the temporary folder . the default "C:\\Users\\Administrator\\AppData\\Local\\Temp"
Single open weed master -mdir="xxx" useful

os:win10

**Comment by chrislusf** [comment]
Please show the output or screenshot.

**Comment by ckhker** [comment]
i check code
command/server.go  line:188
`
			myMasterAddress, peers := checkPeers(*masterIp, *mport, *masterPeers)
			raftServer := weed_server.NewRaftServer(security.LoadClientTLS(viper.Sub("grpc"), "master"),
				peers, myMasterAddress, *metaFolder, ms.Topo, *mpulse)`

*metaFolder error, shloud be *masterMetaFolder

**Comment by chrislusf** [comment]
thanks a lot for debugging !!!
