### ISSUE TITLE
how can i fix #868?

### ISSUE THREAD

**Issue by 9527code** [chrislusf/seaweedfs#876]
Because #868 filer server stored data is wrong, still can not list the files in the directory, how can I correct the filer data(leveldb)? I have compiled the latest weed

**Comment by 9527code** [comment]
I already have about 70 million files stored in the filter. I don't know how to fix the error data in filer database. I really need to list the files in the directory, but I can't use them now.

**Comment by chrislusf** [comment]
sorry for the confusion. the files were not saved into the system correctly. the fix only solves that problem. 

you will need to copy the files again.

**Comment by 9527code** [comment]
i want know how to make  dirhash, i can export to mysql and then modify .@chrislusf

**Comment by 9527code** [comment]
i found dir_rename.go , maybe i can use this change "test\123" to "test/123"?

**Comment by chrislusf** [comment]
filer.proto has listed the filer grpc APIs. It was failing due to the last step to CreateEntry(CreateEntryRequest)

To do this, you will need to have the FileChunk information, which is not saved.

**Comment by 9527code** [comment]
i upload a new file in localhost:8888/path/txt/0/, it's working ,i can list all files, including old files uploaded previously. i don;t know why

**Comment by chrislusf** [comment]
new files should always work with the fix. From the error log, the old files were not saved into the filer store (mysql?).

**Comment by 9527code** [comment]
NO,
Before you fix this problem, I'm using the curl-F "Filename=@123.txt" http://localhost:8888/path/txt/0/
http://localhost:8888/path/txt/0/123.txt is working! but visit http://localhost:8888/path/txt/0/ can't list files, it's 404. and i already have about 70 million files post to filer.  can't list files.  not use filer.copy ! so i think maybe i can fix filer data.

**Comment by chrislusf** [comment]
well. I guess you will need to do some debug to see where it went wrong and how to fix it.

The related files are under https://github.com/chrislusf/seaweedfs/tree/master/weed/filer2/abstract_sql

The hashing is just MD5 of the current directory full path:
https://github.com/chrislusf/seaweedfs/blob/master/weed/filer2/abstract_sql/hashing.go

The SQL for mysql to list directory entries are:
```
store.SqlListExclusive = "SELECT NAME, meta FROM filemeta WHERE dirhash=? AND name>? AND directory=? ORDER BY NAME ASC LIMIT ?"
store.SqlListInclusive = "SELECT NAME, meta FROM filemeta WHERE dirhash=? AND name>=? AND directory=? ORDER BY NAME ASC LIMIT ?"
```

**Comment by chrislusf** [comment]
```
# CREATE TABLE IF NOT EXISTS filemeta (
#   dirhash     BIGINT        COMMENT 'first 64 bits of MD5 hash value of directory field',
#   name        VARCHAR(1000) COMMENT 'directory or file name',
#   directory   VARCHAR(4096) COMMENT 'full path to parent directory',
#   meta        BLOB,
#   PRIMARY KEY (dirhash, name)
# ) DEFAULT CHARSET=utf8;

```

**Comment by 9527code** [comment]
post log.txt  to http://localhost:8888/path/txt/0/
test use mysql data:
dirhash  name      directory    meta                                                                                              
--------------------  --------  -----------  -----------------------------------------
-6550421018326639705  0         /path\txt                                                                                                      
-4225287773105936522  txt       /path                                                                                                                                                                                                                                                 447631134298880677  l ogs.txt  /path/txt/0                                                                                                    
 7378810950367401542  path      /                    

i need fix "/path\txt" to "/path/txt " 
dirhash  -8103326890376618209


but i use leveldb, i never use this db,i don;t know how to fix it

**Comment by 9527code** [comment]
I tried uploading a file "1.txt" with the latest version.
![Lily_Screenshot_1552341133](https://user-images.githubusercontent.com/48319403/54160732-488f3b00-448b-11e9-8be9-e71f5123c04c.png)
maybe i only need delete directory indexof "\"
But still don't know how to do it in leverdb

**Comment by chrislusf** [comment]
sorry, I forgot you are using leveldb, which is different. It does not use "dirhash".

not sure how to help you. all the leveldb code is in this file
https://github.com/chrislusf/seaweedfs/blob/master/weed/filer2/leveldb/leveldb_store.go
