### ISSUE TITLE
[Feature] Ability to specify fuse options when using `weed mount` ( Can't mount as non-root user )

### ISSUE THREAD

**Issue by zicklag** [chrislusf/seaweedfs#877]
Hi, I was testing mounting seaweedfs as a non-root user on Ubuntu 16.04 and I ran into the following error.

```
mount helper error: fusermount: option allow_other only allowed if 'user_allow_other' is set in /etc/fuse.conf
```

As far as I understand it, I could mount the filesystem if it wasn't for the fact that the weed mount command has the FUSE `allow_other` option on by default, and I am unable to override it. It would be nice if the `weed mount` command would allow setting fuse options so that it is configurable.

**Comment by accumulatepig** [comment]
add user_allow_other to /etc/fuse.conf

**Comment by zicklag** [comment]
The `allow_other` option is an option to the FUSE mount command ( like `fusermount` ). It lets other users access the mountpoint, but I don't want to allow other users to access the mount as it is one of FUSE's security measures. With other FUSE filesystems I have been able to run the mount without the `other_users` option so that there is no need for the user to have extra permissions added to `fuse.conf`.

For my use-case I'm actually wanting to be able to mount as a normal user on the system with no special permissions.

**Comment by zicklag** [comment]
Thank you! :smiley:

**Comment by zako91** [comment]
I recently had the same problem, you could use a workaround with linux capabilities to do that:
setcap cap_net_raw,cap_net_admin,cap_dac_override+eip /usr/local/bin/weed

**Comment by chrislusf** [comment]
@zako91 Thanks! Could you add this to the "common problems" https://github.com/seaweedfs/seaweedfs/wiki/FUSE-Mount#common-problems
