### ISSUE TITLE
v1.26 cluster/status page not found

### ISSUE THREAD

**Issue by Yumfriez** [chrislusf/seaweedfs#879]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**
I'm working with seaweed using the 
https://github.com/ChihoSin/weed-client (from the provided list of clients).
The problem is there is no result for "cluster/status" endpoint, so the client doesn't work because of this.
This is the same issue as https://github.com/chrislusf/seaweedfs/issues/870, but it is still reproduced on the version 1.26.

**System Setup**
v1.26 is deployed in the Docker

**Screenshots**
Containers created by provided docker-compose.yml:
![image](https://user-images.githubusercontent.com/31598109/54127428-cebf6900-441a-11e9-8c9a-ed079be77cd0.png)
Curl result:
![image](https://user-images.githubusercontent.com/31598109/54127500-f8789000-441a-11e9-8f2e-59b2d928477b.png)

**Comment by chrislusf** [comment]
please show the weed version. the docker image has some delay. it always picks up the last release. not the current one.

rebuilding the docker image as of now.
