### ISSUE TITLE
idx file not removed when i invocation the Volume.Destroy() function

### ISSUE THREAD

**Issue by SnowPigeons** [chrislusf/seaweedfs#880]
Hi, chrislusf :
when i impliment a function of reduce the replication count of a volume, i try to invocation the Volume.Destroy() function, the .dat file is removed, but .idx file is not.

After i repair the Destroy() like below, the bug disappear.

`	if v.nm != nil {
		err = v.nm.Destroy()
	} else {
		os.Remove(v.FileName() + ".idx")
	}`

i don't find the reason of the v.nm is nil,  and what is your suggestion abuout this ?

**Comment by chrislusf** [comment]
what's the version of your code?
