### ISSUE TITLE
upload file ,but the return filesize is not true 

### ISSUE THREAD

**Issue by daimanman** [chrislusf/seaweedfs#881]
[BUG Demo](http://r.photo.store.qq.com/psb?/V139FU3O3CL8jb/6uOZ8u0vmdKWaqBrrxlK6NRc0ZR3v0tkWRE.zlWhPnY!/r/dL8AAAAAAAAA)

when I upload my file with " curl -F file=@./01.pdf http://192.168.1.191:9333/submit 
" ,  I find the return filesize is 5763949, but the true size is 6758384.  why is it so？

**Comment by chrislusf** [comment]
Your SeaweedFS version is old.
