### ISSUE TITLE
proposal: add Go SDK pubsub

### ISSUE THREAD

**Issue by jba** [chrislusf/seaweedfs#882]
I work on the [Go Cloud Development Kit](https://gocloud.dev) team at Google. We have a [pubsub API](https://godoc.org/gocloud.dev/pubsub) that we'd like to integrate with SeaweedFS. It would immediately give SeaweedFS support for Azure Service Bus and Rabbit MQ. (We also support Amazon SQS and Google Cloud PubSub, which you already have.) 

Can we send you a PR?

**Comment by chrisluuber** [comment]
PR is very welcome!

**Comment by chrislusf** [comment]
PR is very welcome!

**Comment by chrisluuber** [comment]
It will be ideal if there are change notification from the cloud side. Not sure whether this is easily available for google cloud.
