### ISSUE TITLE
[setup for noobs] how do i set up multiple masters/volumes?

### ISSUE THREAD

**Issue by jyjyj** [chrislusf/seaweedfs#883]
Hi,

I'm facing an issue (maybe not really able to figure this out) trying to set up a seaweed instance on my VM: if I understand correctly from https://github.com/chrislusf/seaweedfs/wiki/Failover-Master-Server, it is helpful to set up multiple master servers to ensure no single point of failure. Is this possible or required to do with a single VM?

Also, what is the recommended workflow for setting up a master and volume instance if doing multiple cases? I'm quite new to this, but I seem to need to open multiple terminal windows in Ubuntu to launch multiple masters/volumes, and trying to write it in a script to launch gives me the following errors:

Master startup error: listen tcp 0.0.0.0:9333: bind: address already in use
(similar for the volume)

and this error which keeps showing in an infinite loop:
SendHeartbeat to IP:9333: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp: lookup IP: no such host"

If I set up a master with port 9333 and a volume with port 8080 once, does this run forever unless I force close the port? Is there a way to close the seaweed instance?

Furthermore, does this mean that if I deploy a seaweed server in some VM on my system, that I do not need to initialise anything upon VM startup as the server will always be there?

Apologies for the many questions, thanks for any help!

**Comment by chrislusf** [comment]
single master is fine.

you are asking questions about VM. You do not need VM. Just one "weed" binary file is good for you to setup master and multiple volume servers. Or you just use "weed server"

**Comment by jyjyj** [comment]
Noted about the single master, thanks.

If I want backup in the case as you mentioned in the documentation, should I create many instance of single master-volume on multiple machine then?

Separately, what is the recommended procedure for shutting down and restarting an instance? As I have not seen the docs on how to kill the service other than something like the "kill" command in ubuntu.

Thanks!

**Comment by chrislusf** [comment]
"backup" and "replication" are different. Not sure what you need.

"kill" is good.
