### ISSUE TITLE
query for uploaded file exists

### ISSUE THREAD

**Issue by jyjyj** [chrislusf/seaweedfs#884]
I understand you can assign file IDs when uploading individually, but is there an equivalent for uploading batch files via "upload"? Or is there a way to get such a list if it is assigned automatically, then changing it later?

And when trying to retrieve the file/s, is there a query for file existence before fetching? Thanks!

**Comment by chrislusf** [comment]
yes. no.
see https://github.com/chrislusf/seaweedfs/wiki/Use-Cases#saving-image-with-different-sizes
see https://github.com/chrislusf/seaweedfs/wiki/Master-Server-API#assign-a-file-key

yes. HTTP HEAD.

Please read the docs.
