### ISSUE TITLE
[filer failed to connect] initialising

### ISSUE THREAD

**Issue by jyjyj** [chrislusf/seaweedfs#886]
Hi,

Am getting this error:
filer failed to connect with master localhost:9333: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:19333: connect: connection refused"

when initialising a simple server (master + volume) instance with filer, using this command:
weed server -dir=$PATH_TO_DIR -ip=$IP -ip.bind=$IP -filer=true -filer.port=$FILER_PORT -master.port=$MASTER_PORT -volume.port=$VOLUME_PORT -volume.max=$NUM_VOLUMES_MAX

no issues without the -filer parts

**Comment by flomo29** [comment]
@chrislusf Why do you close this issue? I have the same problem with the masters:
master failed to connect with master localhost:9333: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp [::1]:19333: connect: connection refused"

Can you tell me where the problem is?

**Comment by chrislusf** [comment]
use the latest version with the fix

**Comment by flomo29** [comment]
I have the latest version with your latest commit. iptables is clean and say ACCEPT to everything. But i have the same error. One looks like there is another problem:

master_grpc_server.go:252] topo leader: Raft Server not initialized!
This error comes very often.

**Comment by chrislusf** [comment]
please show your command line and logs

**Comment by flomo29** [comment]
sudo ./weed master -ip="192.168.178.32" -mdir="/mnt/data/vol_master" -peers="192.168.178.32:9333,192.168.178.23:9334,192.168.178.23:9333"

I0916 21:47:06 16682 config.go:28] Reading : Config File "security" Not Found in "[/mnt/data/go/src/github.com/chrislusf/seaweedfs/weed /home/florian/.seaweedfs /etc/seaweedfs]"
I0916 21:47:06 16682 config.go:28] Reading : Config File "master" Not Found in "[/mnt/data/go/src/github.com/chrislusf/seaweedfs/weed /home/florian/.seaweedfs /etc/seaweedfs]"
I0916 21:47:06 16682 file_util.go:19] Folder /mnt/data/vol_master Permission: -rwxr-xr-x
I0916 21:47:06 16682 master_server.go:93] Volume Size Limit is 30000 MB
I0916 21:47:06 16682 master_server.go:180] adminScripts:
I0916 21:47:06 16682 master.go:109] Start Seaweed Master 30GB 1.43 at 0.0.0.0:9333
I0916 21:47:06 16682 raft_server.go:44] Starting RaftServer with 192.168.178.32:9333
I0916 21:47:06 16682 raft_server.go:48] Peers Change: [] => [192.168.178.32:9333 192.168.178.23:9334 192.168.178.23:9333]
I0916 21:47:06 16682 raft_server.go:84] current cluster leader: 
I0916 21:47:06 16682 master.go:133] Start Seaweed Master 30GB 1.43 grpc server at 0.0.0.0:19333
I0916 21:47:06 16682 masterclient.go:73] master failed to keep connected to 192.168.178.23:9333: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 192.168.178.23:19333: connect: connection refused"
I0916 21:47:06 16682 masterclient.go:118] master failed to connect with master 192.168.178.23:9333: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 192.168.178.23:19333: connect: connection refused"
I0916 21:47:06 16682 masterclient.go:73] master failed to keep connected to 192.168.178.23:9334: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 192.168.178.23:19334: connect: connection refused"
I0916 21:47:06 16682 masterclient.go:118] master failed to connect with master 192.168.178.23:9334: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 192.168.178.23:19334: connect: connection refused"
E0916 21:47:06 16682 master_grpc_server.go:252] topo leader: Raft Server not initialized!
I0916 21:47:06 16682 masterclient.go:90] master failed to receive from 192.168.178.32:9333: rpc error: code = Unknown desc = raft.Server: Not current leader
I0916 21:47:06 16682 masterclient.go:118] master failed to connect with master 192.168.178.32:9333: rpc error: code = Unknown desc = raft.Server: Not current leader
I0916 21:47:07 16682 masterclient.go:73] master failed to keep connected to 192.168.178.23:9333: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 192.168.178.23:19333: connect: connection refused"
I0916 21:47:07 16682 masterclient.go:118] master failed to connect with master 192.168.178.23:9333: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 192.168.178.23:19333: connect: connection refused"
I0916 21:47:07 16682 masterclient.go:73] master failed to keep connected to 192.168.178.23:9334: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 192.168.178.23:19334: connect: connection refused"
I0916 21:47:07 16682 masterclient.go:118] master failed to connect with master 192.168.178.23:9334: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 192.168.178.23:19334: connect: connection refused"
E0916 21:47:07 16682 master_grpc_server.go:252] topo leader: Raft Server not initialized!
I0916 21:47:07 16682 masterclient.go:90] master failed to receive from 192.168.178.32:9333: rpc error: code = Unknown desc = raft.Server: Not current leader
I0916 21:47:07 16682 masterclient.go:118] master failed to connect with master 192.168.178.32:9333: rpc error: code = Unknown desc = raft.Server: Not current leader
I0916 21:47:08 16682 masterclient.go:73] master failed to keep connected to 192.168.178.23:9333: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 192.168.178.23:19333: connect: connection refused"
I0916 21:47:08 16682 masterclient.go:118] master failed to connect with master 192.168.178.23:9333: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 192.168.178.23:19333: connect: connection refused"
I0916 21:47:08 16682 masterclient.go:73] master failed to keep connected to 192.168.178.23:9334: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 192.168.178.23:19334: connect: connection refused"
I0916 21:47:08 16682 masterclient.go:118] master failed to connect with master 192.168.178.23:9334: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 192.168.178.23:19334: connect: connection refused"
E0916 21:47:08 16682 master_grpc_server.go:252] topo leader: Raft Server not initialized!
I0916 21:47:08 16682 masterclient.go:90] master failed to receive from 192.168.178.32:9333: rpc error: code = Unknown desc = raft.Server: Not current leader
I0916 21:47:08 16682 masterclient.go:118] master failed to connect with master 192.168.178.32:9333: rpc error: code = Unknown desc = raft.Server: Not current leader
I0916 21:47:09 16682 masterclient.go:73] master failed to keep connected to 192.168.178.23:9333: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 192.168.178.23:19333: connect: connection refused"
I0916 21:47:09 16682 masterclient.go:118] master failed to connect with master 192.168.178.23:9333: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 192.168.178.23:19333: connect: connection refused"
I0916 21:47:09 16682 masterclient.go:73] master failed to keep connected to 192.168.178.23:9334: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 192.168.178.23:19334: connect: connection refused"
I0916 21:47:09 16682 masterclient.go:118] master failed to connect with master 192.168.178.23:9334: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 192.168.178.23:19334: connect: connection refused"
E0916 21:47:09 16682 master_grpc_server.go:252] topo leader: Raft Server not initialized!
I0916 21:47:09 16682 masterclient.go:90] master failed to receive from 192.168.178.32:9333: rpc error: code = Unknown desc = raft.Server: Not current leader
I0916 21:47:09 16682 masterclient.go:118] master failed to connect with master 192.168.178.32:9333: rpc error: code = Unknown desc = raft.Server: Not current leader
I0916 21:47:10 16682 masterclient.go:73] master failed to keep connected to 192.168.178.23:9333: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 192.168.178.23:19333: connect: connection refused"
I0916 21:47:10 16682 masterclient.go:118] master failed to connect with master 192.168.178.23:9333: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 192.168.178.23:19333: connect: connection refused"
I0916 21:47:10 16682 masterclient.go:73] master failed to keep connected to 192.168.178.23:9334: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 192.168.178.23:19334: connect: connection refused"
I0916 21:47:10 16682 masterclient.go:118] master failed to connect with master 192.168.178.23:9334: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 192.168.178.23:19334: connect: connection refused"
E0916 21:47:10 16682 master_grpc_server.go:252] topo leader: Raft Server not initialized!
I0916 21:47:10 16682 masterclient.go:90] master failed to receive from 192.168.178.32:9333: rpc error: code = Unknown desc = raft.Server: Not current leader
I0916 21:47:10 16682 masterclient.go:118] master failed to connect with master 192.168.178.32:9333: rpc error: code = Unknown desc = raft.Server: Not current leader
I0916 21:47:11 16682 masterclient.go:73] master failed to keep connected to 192.168.178.23:9333: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 192.168.178.23:19333: connect: connection refused"
I0916 21:47:11 16682 masterclient.go:118] master failed to connect with master 192.168.178.23:9333: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 192.168.178.23:19333: connect: connection refused"
I0916 21:47:11 16682 masterclient.go:73] master failed to keep connected to 192.168.178.23:9334: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 192.168.178.23:19334: connect: connection refused"
I0916 21:47:11 16682 masterclient.go:118] master failed to connect with master 192.168.178.23:9334: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 192.168.178.23:19334: connect: connection refused"
E0916 21:47:11 16682 master_grpc_server.go:252] topo leader: Raft Server not initialized!
I0916 21:47:11 16682 masterclient.go:90] master failed to receive from 192.168.178.32:9333: rpc error: code = Unknown desc = raft.Server: Not current leader
I0916 21:47:11 16682 masterclient.go:118] master failed to connect with master 192.168.178.32:9333: rpc error: code = Unknown desc = raft.Server: Not current leader
I0916 21:47:12 16682 masterclient.go:73] master failed to keep connected to 192.168.178.23:9333: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 192.168.178.23:19333: connect: connection refused"
I0916 21:47:12 16682 masterclient.go:118] master failed to connect with master 192.168.178.23:9333: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 192.168.178.23:19333: connect: connection refused"
I0916 21:47:12 16682 masterclient.go:73] master failed to keep connected to 192.168.178.23:9334: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 192.168.178.23:19334: connect: connection refused"
I0916 21:47:12 16682 masterclient.go:118] master failed to connect with master 192.168.178.23:9334: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 192.168.178.23:19334: connect: connection refused"
E0916 21:47:12 16682 master_grpc_server.go:252] topo leader: Raft Server not initialized!
I0916 21:47:12 16682 masterclient.go:90] master failed to receive from 192.168.178.32:9333: rpc error: code = Unknown desc = raft.Server: Not current leader
I0916 21:47:12 16682 masterclient.go:118] master failed to connect with master 192.168.178.32:9333: rpc error: code = Unknown desc = raft.Server: Not current leader

**Comment by chrislusf** [comment]
your server 192.168.178.32 can not talk to 192.168.178.23. check your network.

**Comment by flomo29** [comment]
no. both server can talk to other. with the ping command and testet with seaweedfs volumes the server and the master on the other. this problem is only with multiple master. But i got this error too:

./weed master -port="9333" -ip="192.168.178.23" -mdir="/mnt/data/vol_master2" -peers="192.168.178.23:9333,192.168.178.23:9334,192.168.178.32:9333"
I0916 19:08:17  2808 config.go:28] Reading : Config File "security" Not Found in "[/root/go_weed/src/github.com/chrislusf/seaweedfs/weed /root/.seaweedfs /etc/seaweedfs]"
I0916 19:08:17  2808 config.go:28] Reading : Config File "master" Not Found in "[/root/go_weed/src/github.com/chrislusf/seaweedfs/weed /root/.seaweedfs /etc/seaweedfs]"
I0916 19:08:17  2808 file_util.go:19] Folder /mnt/data/vol_master2 Permission: -rwxr-xr-x
I0916 19:08:17  2808 master_server.go:93] Volume Size Limit is 30000 MB
I0916 19:08:17  2808 master_server.go:180] adminScripts:
I0916 19:08:17  2808 master.go:109] Start Seaweed Master 30GB 1.43 at 0.0.0.0:9333
I0916 19:08:17  2808 raft_server.go:44] Starting RaftServer with 192.168.178.23:9333
I0916 19:08:17  2808 raft_server.go:48] Peers Change: [] => [192.168.178.23:9333 192.168.178.23:9334 192.168.178.32:9333]
I0916 19:08:17  2808 raft_server.go:71] Initializing new cluster
I0916 19:08:17  2808 raft_server.go:84] current cluster leader: 192.168.178.23:9333
I0916 19:08:17  2808 master_server.go:134] [ 192.168.178.23:9333 ] I am the leader!
I0916 19:08:17  2808 master.go:133] Start Seaweed Master 30GB 1.43 grpc server at 0.0.0.0:19333
I0916 19:08:17  2808 master_grpc_server.go:196] + client master192.168.178.23:46862
I0916 19:08:20  2808 master_server.go:131] state change: &{typ:stateChange source:0x2802370 value:follower prevValue:leader}
E0916 19:08:22  2808 master_grpc_server.go:252] topo leader: Raft Server not initialized!
I0916 19:08:22  2808 master_grpc_server.go:206] - client master192.168.178.23:46862
I0916 19:08:22  2808 masterclient.go:90] master failed to receive from 192.168.178.23:9333: rpc error: code = Unknown desc = raft.Server: Not current leader
I0916 19:08:22  2808 masterclient.go:118] master failed to connect with master 192.168.178.23:9333: rpc error: code = Unknown desc = raft.Server: Not current leader
I0916 19:08:22  2808 masterclient.go:73] master failed to keep connected to 192.168.178.23:9334: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 192.168.178.23:19334: connect: connection refused"
I0916 19:08:22  2808 masterclient.go:118] master failed to connect with master 192.168.178.23:9334: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 192.168.178.23:19334: connect: connection refused"
I0916 19:08:22  2808 masterclient.go:73] master failed to keep connected to 192.168.178.32:9333: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 192.168.178.32:19333: connect: connection refused"
I0916 19:08:22  2808 masterclient.go:118] master failed to connect with master 192.168.178.32:9333: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 192.168.178.32:19333: connect: connection refused"
E0916 19:08:23  2808 master_grpc_server.go:252] topo leader: Raft Server not initialized!

As you can see. The master wants to talk to himself but got refused.

**Comment by flomo29** [comment]
the interessting stuff is: i got two servers .23 and 32. and on the first i have 2 masters and the 3. ion 32. when start with .23:9333 and the start the others. everything works fine. i can stop master and start again. no problem. but when i kill the leader the other masters print the messages you saw in the last posts und no one of the other masters wants to be the new master. it would be cool, that if a master cannot connect to other the he will be the new leader automaticly until he can connect to the others again.

**Comment by chrislusf** [comment]
The second log shows the master on grpc 192.168.178.23:19333 wants to talk to 192.168.178.23:19334 and 192.168.178.32:19333, but got refused.

**Comment by chrislusf** [comment]
> if a master cannot connect to other the he will be the new leader automaticly until he can connect to the others again.

That's called a split-brain problem and needs to be avoided.

**Comment by flomo29** [comment]
but the question is: why one master cannot connect to the other master on the same server with only a different port when both masters are active?

**Comment by chrislusf** [comment]
can not tell. check your network. It is just a simple network call.

**Comment by flomo29** [comment]
but why do we should have multiple masters when the leader goes down and nobody wants to be the next leader because of split-brain avoidance?

**Comment by chrislusf** [comment]
if the 2 remaining masters can not communicate and decided to act as leaders, there would be more trouble down the road.

**Comment by flomo29** [comment]
okay. i try to solve that problem the other way.
Buy the way. SeaweedFS is a very cool piece of software. i like that architecture and the feature. it would be cool if the s3 gateway can be so good that one can use S3QL.

**Comment by chrislusf** [comment]
"S3QL" are you referring to S3 select
https://aws.amazon.com/about-aws/whats-new/2018/09/amazon-s3-announces-new-features-for-s3-select/

or s3ql https://github.com/s3ql/s3ql ?

**Comment by flomo29** [comment]
The second one.

**Comment by chrislusf** [comment]
welcome to use it with s3ql. I haven't tested it. But it should work.
