### ISSUE TITLE
return file-uploading timestamp when uploading succeed

### ISSUE THREAD

**Issue by PapaYofen** [chrislusf/seaweedfs#888]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Expected behavior**
Right now when uploading a file succeeds, neither http header nor response body carries about uploading timestamp (Last-Modified), which is an important metadata for file in 3rd application.

Could timestamp be added in response body or header?

**Comment by chrisluuber** [comment]
when uploading to filer or volume server?

what kind of 3rd application? for caching?

**Comment by PapaYofen** [comment]
> when uploading to filer or volume server?  

volume server

> what kind of 3rd application? for caching?  

we implement a storage gateway, backend different storage systems, and customized object key is composed of many parts, including timestamp.

**Comment by chrisluuber** [comment]
The "Last-Modified" means the content modification time, not necessarily uploading time.

The uploader already knows the upload time.

**Comment by PapaYofen** [comment]
what about create_time instead of last-modified?

**Comment by chrislusf** [comment]
Why asking for the creation time when creating the file?

**Comment by PapaYofen** [comment]
to exactly tell client the expired timestamp when ttl is set

**Comment by chrislusf** [comment]
Better not to change for this. The TTL does not need to be so precise.

**Comment by PapaYofen** [comment]
all right. i will close isssue
