### ISSUE TITLE
volumes contain multiple duplicate files

### ISSUE THREAD

**Issue by jyjyj** [chrislusf/seaweedfs#892]
Hi, when I POST a file to the filer server, I noticed that repeated POSTs of the same file do show up in the volumes. Is this because I'm not doing POST by file key? I am currently doing this based on the filer port and the actual file name for easier reading.

And if I want to continue using this way for easy reading, should I then do my own checks for file existence? Was wondering about the speed of this check.

Thanks for any advice!

**Comment by chrislusf** [comment]
There are no built-in dedup. You can do your own dedup checking by sending HTTP HEAD for the ETag in the header.

**Comment by chrislusf** [comment]
I found http HEAD to filer is not returning ETag. Added.
