### ISSUE TITLE
read and write performance

### ISSUE THREAD

**Issue by PapaYofen** [chrislusf/seaweedfs#894]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**
There are two questions confusing me.
#### 1st
experiments on 3 machines seperated logically 3 different racks, each runs a master and a volume server,  and the 3 machines have the same specifications, including disk, cpu, memory.
- benchmarking with replication=000, read ops=1035, write ops=1039
- benchmarking with replication=010, read ops=597, write ops=387

**_Expectedly read ops of replication=000 should be better  than  replication=010._**
Detailed benchmark results refer to [here](https://note.youdao.com/web/#/file/recent/markdown/WEB47b7a52980ba916c06d706c0bfdcc3e3/)

#### 2nd
benchmark from repo readme shows that random read performance is better than sequential write. 
why?

**Expected behavior**
- more replicas, better read ops
- sequential write ops should be better than random read

**Comment by chrislusf** [comment]
Do not run "weed benchmark" from any of the 3 machines.
