### ISSUE TITLE
Merge Data !

### ISSUE THREAD

**Issue by shahzaibcb** [chrislusf/seaweedfs#897]
Hi,

We currently have 2 x thumbs servers named thumbs1.domain.com and thumbs2.domain.com. thumbs1 have 27 max volume set and thumbs2 have 100 max volume set because it has large storage. Thumbs1 volume space is filled up and thumbs only upload to thumbs2 server now.

Recently we have decided to move thumbs1 data to thumbs2 server to dump thumbs1 server in order to save cost. Should we simply follow the mentioned below steps for data movement:

- Migrate volume directory `/var/www/html/vol1` to thumbs2 current volume directory `/var/www/html/vol2`
- Change DNS entry for thumbs1.domain.com to resolve from thumbs2.domain.com

Is that all we need ? do we need to start another weed daemon or the current weedfs daemon with max 100 vol will just work fine ? Is there any chance that old max volume was 27 and new maxvolume 100 can create some problems when all data is on same node ?

**Comment by chrislusf** [comment]
If no volume replica, that is good.
