### ISSUE TITLE
HA: Seaweed UI shows blank topology on slaves 

### ISSUE THREAD

**Issue by HuxyUK** [chrislusf/seaweedfs#898]
**Describe the bug**
When using a HA cluster, the UI on the slaves show an empty topology. I found this behaviour confusing and think it would be better if all UIs showed the same topology regardless of roles. I was using a load-balancer at the time and it had me scratching my head

**System Setup**
```
weed master -port=9334 -ip=127.0.0.1 -ip.bind="0.0.0.0" -peers=127.0.0.1:9334,127.0.0.1:9335,127.0.0.1:9336
weed master -port=9335 -ip=127.0.0.1 -ip.bind="0.0.0.0" -peers=127.0.0.1:9334,127.0.0.1:9335,127.0.0.1:9336
weed master -port=9336 -ip=127.0.0.1 -ip.bind="0.0.0.0" -peers=127.0.0.1:9334,127.0.0.1:9335,127.0.0.1:9336
weed volume -dir="." -max=5 -mserver="127.0.0.1:9334" -port=8080
```

**Expected behaviour**
I would like to see the topology (if possible) shown on all master UI

**Screenshots**
![image](https://user-images.githubusercontent.com/3058486/54829781-13ff5880-4caf-11e9-83e5-915b139a4519.png)
![image](https://user-images.githubusercontent.com/3058486/54829806-21b4de00-4caf-11e9-833e-fb07e3b0afbc.png)

**Comment by zicklag** [comment]
Whoa, I didn't know there was a WebUI, how do you get to it?

**Comment by HuxyUK** [comment]
@zicklag 
1. For the servers just head to their port: http://hostname:9333
2. For storage volumes you need to add to /ui/index.html: http://hostname:8080/ui/index.html

**Comment by chrislusf** [comment]
Will a redirect work?

**Comment by HuxyUK** [comment]
I don't mind if they auto redirect to the leader's web pages. The thing to note though is that I access the page outside of the internal network via a reverse proxy, so it would need to proxy the request and not redirect the connecting client as I don't have access to the private range on the overlay network. 

![image](https://user-images.githubusercontent.com/3058486/54909176-7cce1700-4ee1-11e9-861b-5965f0778a74.png)
