### ISSUE TITLE
Seaweedfs Master crashes

### ISSUE THREAD

**Issue by ijunaid8989** [chrislusf/seaweedfs#899]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**
Everything was working fine for the past few months, nothing has changed but seaweedfs master has started to crash and restart.

**System Setup**
Ubuntu 18.04.
Weed v 1.15

the command to start weed master filer:
```
/opt/go/bin/weed -v=0 server -filer=true -ip=159.xx.xxx.31 -dir=/storage/new_master -volume.max=3000 -volume.images.fix.orientation=false -pulseSeconds=5
```

**Expected behaviour**
It should not crash and work properly.

The error comes across on vacuum 

**Screenshots**
![image](https://user-images.githubusercontent.com/13561999/54899592-10a7df00-4ef2-11e9-8708-9bc2cbfaaa45.png)

**Additional context**

To secure seaweedfs, we have added firewall rules, in which right now we have,

1. Master Filer 8888 Server A
2. Master Port  9333 Server A
3. Master Volume 8080 Server A
4. Volume Port 8080 (on another server) Server B.

All these ports are allowed for each other servers over the internet to make a connection and read or write.

This is an FYI.

**Comment by ijunaid8989** [comment]
Follow up:

I have updated the weed version to the latest one.

If the problem will still exist, I will update.

**Comment by chrislusf** [comment]
@ijunaid8989 could you please include the line numbers in the screenshot?

**Comment by chrislusf** [comment]
btw: There are also gRpc ports to secure.

For security, please check https://github.com/chrislusf/seaweedfs/wiki/Security-Overview

**Comment by ijunaid8989** [comment]
It's working fine now. so Am closing the issue.
