### ISSUE TITLE
root project import: /Users/zhoubin/gorepo/pkg/dep/sources/https---github.com-Azure-azure--storage--blob--go is not within any GOPATH/src

### ISSUE THREAD

**Issue by ipanocloud** [chrislusf/seaweedfs#901]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**

**System Setup**
List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by chrislusf** [comment]
This is a basic go build question.

```
go get -u github.com/chrislusf/seaweedfs/weed
```
