### ISSUE TITLE
upload file in Filer just shows the name as "file" (Gzip)

### ISSUE THREAD

**Issue by jyjyj** [chrislusf/seaweedfs#903]
Uploaded a bunch of files to Filer, and all i see in the directory is "file" instead of the individual files, which is a Gzip that can't be read. I have checked the file/directory names etc. and they seem to be fine. Also checked the directory (in case there's some limit on directory string length and/or depth).

Any suggestions? Using Ubuntu if that matters, thanks!

**Comment by chrislusf** [comment]
Please follow issue template. Maybe show some screenshots.

**Comment by jyjyj** [comment]
Managed to fix it by converting the curl command to a python request, was previously going through the python-seaweed libraries suggested. Seems like they do not support the correct format for reading images. Managed to fix it with (example):

"
import requests

files = {
    'file': ('report.js', open('report.js', 'rb')),
}

response = requests.post('http://localhost:8888/javascript/', files=files)
"

for anyone else facing this issue in python. Thanks!
