### ISSUE TITLE
launch upon OS startup doesn't work

### ISSUE THREAD

**Issue by jyjyj** [chrislusf/seaweedfs#905]
Hi, I have a seaweed server running in a VM. For deployment/relocation and convenience purposes, I would like the server to automatically start up when the VM is booted up. To do so, I have written a simple bash script in Ubuntu and used a cron-job (crontab -e) to run this script. However, the server does not start up automatically. I have checked the logs of my cronjob, and everything else in my startup script does print successfully. Any issues in Ubuntu, or how should I be doing this? Thanks.

**Comment by chrislusf** [comment]
please follow issue template and provide details.

**Comment by jyjyj** [comment]
I don't think I need a screenshot for this, but basically I have a startup script initialise.sh with the following lines:

"
echo "initialise"
weed server -dir=$PATH_TO_DIR -ip=$IP -ip.bind=$IP -filer=true -filer.port=$FILER_PORT -master.port=$MASTER_PORT -volume.port=$VOLUME_PORT -volume.max=$NUM_VOLUMES_MAX
echo "end"
"

When I run this script in the terminal normally, the server loads up, with the master/volumes/filer. But when I wrote a cron job:

@reboot /directory/initialise.sh > /directory/seaweed.log

Inside /directory/seaweed.log, all I get is:

initialise
end

And the seaweed servers have not been set up. Not sure if there's any issue with launching this on restart/start-up?

Thanks!

**Comment by jyjyj** [comment]
got it, thanks! I previously ran with "weed .....", but it seems to not recognize this environment variable upon startup. Running it with the absolute path to the weed executable worked.

Separately, I noticed that adding -ip.bind=... doesn't work in the crontab but works in the terminal. After taking it out, seems to be ok
