### ISSUE TITLE
uploaded file URL too long?

### ISSUE THREAD

**Issue by jyjyj** [chrislusf/seaweedfs#906]
Hi, is there a limit on the URL length when uploading on filer? I tried with a shorter length and my upload works normally, but when I tried with a longer length (have 4 nested directories), the uploaded file is named correctly but has 0Bytes size. In the curl request "curl -F file=@report.js "http://localhost:8888/javascript/"", the return object does not have a "size" parameter.

With a shorter length, this is ok with the proper size parameter.

**Comment by chrislusf** [comment]
There are no limit on URL length. Your underlying filer store may be related. Please follow the issue template and have reproducible commands.

**Comment by chrislusf** [comment]
This could be related. https://github.com/chrislusf/seaweedfs/commit/2a52e70a41cd1a196a43fe196960d9ed9d25f43d
