### ISSUE TITLE
[Feature] Automatic Re-replilcation of Volumes on Interval

### ISSUE THREAD

**Issue by zicklag** [chrislusf/seaweedfs#907]
What do you think about having a configurable interval that you could set for automatically running `volume.fix.replication`? If it is a non-destructive operation that can be safely run automatically, it would be nice not to have to manually run it.

If a replica fails to write for some reason, like network connectivity, it should then be able to automatically recover from it.

**Comment by chrislusf** [comment]
I was thinking some cron job should be good, instead of adding more features.

**Comment by zicklag** [comment]
What about building it into the official Docker image, then? As a user I wouldn't want to have to create a custom container or setup a cron job on the Docker host.

**Comment by zicklag** [comment]
I can add an option that you can pass in to the Docker entrypoint to run a cron job that runs the repair periodically if you were good with that.

**Comment by chrislusf** [comment]
there could be some race condition if multiple instances are deployed.

**Comment by zicklag** [comment]
Yeah, you would have to deploy only one of the cron services. It wouldn't run by default, just if you pass in an entrypoint flag like `cron` instead of `master` or `volume`.

**Comment by chrislusf** [comment]
That should work. Please help here. Thanks!

**Comment by zicklag** [comment]
Rodger that. :wink:
