### ISSUE TITLE
guarantee random distribution of uploaded files across all volume servers

### ISSUE THREAD

**Issue by gregjhogan** [chrislusf/seaweedfs#909]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**
when volumes are added to a collection, they are not always equally distributed across all volume servers, causing unequal load and data distribution

example:
```
# start empty
aws s3 mb s3://test --endpoint-url http://seaweed-s3:8333 --no-sign-request
# grow (screen shot below of result)
curl 'http://seaweed-master:9333/vol/grow?collection=test&count=3'
# grow (screen shot below of result)
curl 'http://seaweed-master:9333/vol/grow?collection=test&count=6'
```

**System Setup**
`master`, `filer`, `s3` running together on one server and `volume` running on 7 other servers

**Expected behavior**
anyone who wants to maximize IOPS needs data distributed randomly and equally across all volume servers

**Screenshots**
after grow from 0 -> 3
![image](https://user-images.githubusercontent.com/4112046/55295860-fc1e8780-53c6-11e9-9cae-5005c9cab7ea.png)

after grow from 3 -> 6
![image](https://user-images.githubusercontent.com/4112046/55295887-4869c780-53c7-11e9-8fe3-9fcf12ee68a2.png)

**Additional context**
n/a

**Comment by gregjhogan** [comment]
There are other ways to make this happen, too, for example using `filer.copy` if you start with no volumes

**Comment by gregjhogan** [comment]
There are other ways to make this happen, too, like using `filer.copy`

start empty:
![image](https://user-images.githubusercontent.com/4112046/55296046-2f621600-53c9-11e9-84d6-3cb0669e6d3f.png)

run `filer.copy` and volumes are unevenly distributed:
```
./weed filer.copy -master=seaweed-master:9333 -collection=test /path/to/folder/ http://seaed-filer:8888/buckets/test/folder/
```
![image](https://user-images.githubusercontent.com/4112046/55296056-5ae50080-53c9-11e9-8e3c-e1fa9c300930.png)

**Comment by chrislusf** [comment]
The volumes are randomly created based on capacity. But when the number of
volumes are low, it looks like uneven. To remedy this, you can manually
create the volumes.

**Comment by gregjhogan** [comment]
You see the issue, right? I started empty, manually created volumes (as you suggested), they are not distributed equally, and the data will therefore be unequally be distributed and random reads to the cluster will not be distributed equally, so my IOPS will be diminished significantly (above 5/7 of the data ends up on one volume server).  How do I guarantee data gets distributed equally to maximize IOPS?  I copied in 500 GB and I still had significant skew toward one volume server (in both cases when I manually grow volumes initially and when I don't manually grow initially)

**Comment by chrislusf** [comment]
Allocate more volumes. 7 volumes are too small to show statistically even
distribution.

**Comment by gregjhogan** [comment]
It just isn't ideal because when whatever I allocate fills up, only a few more volumes are created, which are highly likely to be unbalanced, so I have to constantly monitor it to keep writing balanced across all volume servers (to keep random reads equally distributed).

Is there a downside to keeping the number of writable volumes on each volume server as close to balanced as possible? (when adding volumes always randomly pick from set of volume servers with free space available and with least number of writable volumes)

If there is a down side, how about a new option on the master that specifies the minimum number of writable volumes you always want available on each volume server?

I could pre-allocate all volumes on all volume servers as a solution to my problem, but in the situation where I add another volume server in the future I don't want a disproportionate number of writes going to that new volume server (because what I really want is to always have equally balanced writes across all volume servers, and I will then re-shuffle the data so that it is equally and randomly distributed across both old and new volume servers to maximize random read performance again)

**Comment by chrislusf** [comment]
This is a hard problem and I do not have an easy answer. It's hard to evenly distribute both storage and network, unless all servers are started up at the beginning. Also, the volume growth strategies are different for a couple of collections, or a lot of collections.

> when adding volumes always randomly pick from set of volume servers with free space available and with least number of writable volumes

This is already the case.

**Comment by gregjhogan** [comment]
Are you opposed to a new option on the master that specifies a minimum number of writable volumes per collection that all volume servers should always have (unless they run out of space)?  Then if you never `/vol/grow`, writing will stay very close to balanced across all volume servers that are up and running.

**Comment by chrislusf** [comment]
For large number of volume servers, a minimum number of volumes could be too much for other cases. For example, one collection per user.

Need to have different strategies for different use cases. Need to think about how to code or template it.

**Comment by gregjhogan** [comment]
Agreed, I was thinking it would need to be optional and default to 0 (no change in behavior)

**Comment by chrislusf** [comment]
I think where you want to achieve is to ensure all servers have N number of writeable volumes. This should be achievable by periodically run a new weed shell command to check and allocate new volumes.

**Comment by chrislusf** [comment]
added "volume.balance" command in "weed shell". see https://github.com/chrislusf/seaweedfs/commit/3ff92037ccd56307441fd5155df60d3aaff3db66
