### ISSUE TITLE
怎么样把weed mount 添加到 /etc/fstab 实现重启后自动挂载啊

### ISSUE THREAD

**Issue by nqzhang** [chrislusf/seaweedfs#912]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**

**System Setup**
List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".

**Expected behavior**

**Screenshots**

**Additional context**

怎么样把weed mount 添加到 /etc/fstab 实现重启后自动挂载啊 ,不然的话每次都要手动挂载啊

**Comment by chrislusf** [comment]
just use a cron job
