### ISSUE TITLE
allocating all available volumes fails

### ISSUE THREAD

**Issue by gregjhogan** [chrislusf/seaweedfs#913]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**
I tried to allocate all available volumes (which was 6,400 volumes) and it allocated all but 42 of the volumes and then threw an error (then I was able to allocate the last 42 volumes successfully)
```
$ curl "http://seaweed-master:9333/vol/grow?collection=test&count=6400"
{"error":"Failed to assign 6625: rpc error: code = Unknown desc = No more free space left"}
$ curl "http://seaweed-master:9333/vol/grow?collection=test&count=6400"
{"error":"Only 42 volumes left! Not enough for 6400"}
$ curl "http://seaweed-master:9333/vol/grow?collection=test&count=42"
{"count":42}
```
(sorry, didn't get screen shots)

after deleting all volumes and running again, I got got a different error and strangely I see 6,400 volumes allocated but it says 397 volumes free (which should be 0 volumes free)
```
$ curl "http://seaweed-master:9333/vol/grow?collection=test&count=6400"
{"error":"Failed to assign 6669: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 192.168.X.XXX:18080: connect: connection refused\""}
```
and strangely it say 397 volumes are free
![image](https://user-images.githubusercontent.com/4112046/55459751-1b730b80-55a5-11e9-9bd8-7121623f067b.png)
even though the volume servers show a total of 6400 volumes
![image](https://user-images.githubusercontent.com/4112046/55459802-3c3b6100-55a5-11e9-9249-359442fc9d19.png)

**System Setup**
`master` `filer` and `s3` on one machine and `volume` on 4 separate machines

**Expected behavior**
allocating all available volumes should succeed and counts should make sense

**Screenshots**
n/a

**Additional context**
n/a

**Comment by gregjhogan** [comment]
I tried restarting all docker containers on all hosts and then the "Free" count on the master changed to 50.  I then restarted all docker containers on all hosts a second time and the "Free" count on the master changed to 250.

**Comment by chrislusf** [comment]
The allocation runs based on volumes reported by volume servers. So there are delays. And it is a randomized allocation. So it is non-deterministic in nature.

I am interested to see why the "Free" count can change. Maybe you can run this to show the difference.
```
echo `volume.list` | weed shell -master="...,...,..."
```

**Comment by gregjhogan** [comment]
Here is the output
[volume.list.txt](https://github.com/chrislusf/seaweedfs/files/3045897/volume.list.txt)

**Comment by chrislusf** [comment]
added a possible fix to atomically count the volume. not quite sure this can fix it though.

**Comment by chrislusf** [comment]
the system is not designed to allocate so many volumes in one shot.

The problem you are trying to address is balancing the volumes, similar to  https://github.com/chrislusf/seaweedfs/issues/913. There is a command "volume.balance" to address it.
