### ISSUE TITLE
filer.copy复制文件到volume出错

### ISSUE THREAD

**Issue by thatseason** [chrislusf/seaweedfs#915]
./weed filer.copy /files/ http://127.0.0.1:8888/xxx/

upload data 44776s.jpg to http://127.0.0.1:8888/xxx/44/44776/44776.jpg: update fh: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:18888: connect: cannot assign requested address"

大约有三千万个文件，每次停止的地方都不一样

**Comment by chrislusf** [comment]
added a possible fix, but not sure. Please help to check.

btw: it's better to use flat directories, not deep directories.

**Comment by thatseason** [comment]
测试过，功能正常，谢谢！

**Comment by thatseason** [comment]
运行了4个小时左右，又出现和一开始同样的错误。

**Comment by chrislusf** [comment]
added another fix. I think there could be some leaking. maybe get back to this tomorrow.

**Comment by thatseason** [comment]
是的，还是会出错。
另外，性能好像也有问题，我在复制文件的时候，磁盘IO和CPU使用率都没有到瓶颈，单机网络，复制三千万个文件（平均4KB）用了16个小时左右。

**Comment by chrislusf** [comment]
Added options to parallelize the copying process. It should be much faster now.

Please show the errors.

**Comment by thatseason** [comment]
昨天晚上更新后测试170万文件没有出错，但是速度依旧很慢，今天早上看到你更新了gzip部分，也许性能和这部分有关（我没有测试），因为我在复制稍大点的文件（大约400KB，类型html,txt,xml）时，速度非常慢。

**Comment by chrislusf** [comment]
"very slow" doesn't show where's the bottleneck. Show some CPU and network
stats.

**Comment by chrislusf** [comment]
added code to optimize gzip for best speed.

**Comment by chrislusf** [comment]
Going to close this one if no more updates.
