### ISSUE TITLE
rpc error: code = Unavailable desc = all SubConns are in TransientFailure

### ISSUE THREAD

**Issue by ijunaid8989** [chrislusf/seaweedfs#918]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**
```
error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 46.4.221.254:18080: i/o timeout"
Mar 12 08:02:57 Ubuntu-1804-bionic-64-minimal seaweedfs[855]: I0312 08:02:56   855 topology_vacuum.go:151] check vacuum on collection: volume:3000
Mar 12 08:02:57 Ubuntu-1804-bionic-64-minimal seaweedfs[855]: I0312 08:02:56   855 topology_vacuum.go:151] check vacuum on collection: volume:3983
Mar 12 08:02:57 Ubuntu-1804-bionic-64-minimal seaweedfs[855]: I0312 08:02:56   855 topology_vacuum.go:30] Checking vacuuming 3983 on 46.4.221.254:8080: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 46.4.221.254:18080: i/o timeout"
Mar 12 08:02:57 Ubuntu-1804-bionic-64-minimal seaweedfs[855]: I0312 08:02:56   855 topology_vacuum.go:151] check vacuum on collection: volume:4580
Mar 12 08:02:57 Ubuntu-1804-bionic-64-minimal seaweedfs[855]: I0312 08:02:56   855 topology_vacuum.go:30] Checking vacuuming 4580 on 46.4.221.254:8080: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 46.4.221.254:18080: i/o timeout"
```

```

Apr 08 10:18:56 Ubuntu-1804-bionic-64-minimal seaweedfs[24068]: I0408 10:18:56 24068 volume_server_handlers_read.go:71] read /988,20be23d7e2cb02ff error: File Entry Not Found. offset 2950061488, Needle id 2776134163513633160 expected size 121397911 Memory 546629
Apr 08 10:18:57 Ubuntu-1804-bionic-64-minimal seaweedfs[24068]: I0408 10:18:57 24068 volume_server_handlers_read.go:71] read /1356,3a41113ab7ce983d error: File Entry Not Found. offset 2961880, Needle id 2910950754801121579 expected size 2254586614 Memory 2521494
Apr 08 10:18:57 Ubuntu-1804-bionic-64-minimal seaweedfs[24068]: I0408 10:18:57 24068 volume_server_handlers_read.go:71] read /1356,3a41113ab7ce983d error: File Entry Not Found. offset 2961880, Needle id 2910950754801121579 expected size 2254586614 Memory 2521494
Apr 08 10:19:05 Ubuntu-1804-bionic-64-minimal seaweedfs[24068]: I0408 10:19:05 24068 volume_server_handlers_read.go:71] read /1404,1171f85450c1bb26 error: not found
Apr 08 10:19:57 Ubuntu-1804-bionic-64-minimal seaweedfs[24068]: I0408 10:19:57 24068 volume_server_handlers_read.go:71] read /1356,3a41113ab7ce983d error: File Entry Not Found. offset 2961880, Needle id 2910950754801121579 expected size 2254586614 Memory 2521494
Apr 08 10:19:57 Ubuntu-1804-bionic-64-minimal seaweedfs[24068]: I0408 10:19:57 24068 volume_server_handlers_read.go:71] read /1356,3a41113ab7ce983d error: File Entry Not Found. offset 2961880, Needle id 2910950754801121579 expected size 2254586614 Memory 2521494
Apr 08 10:19:57 Ubuntu-1804-bionic-64-minimal seaweedfs[24068]: I0408 10:19:57 24068 volume_server_handlers_read.go:71] read /988,20be23d7e2cb02ff error: File Entry Not Found. offset 2950061488, Needle id 2776134163513633160 expected size 121397911 Memory 546629
Apr 08 10:20:07 Ubuntu-1804-bionic-64-minimal seaweedfs[24068]: I0408 10:20:07 24068 volume_server_handlers_read.go:71] read /1404,1171f85450c1bb26 error: not found
```
**System Setup**
Ubuntu-1804-bionic-64-minimal
Master Command.
```
/opt/go/bin/weed -v=0 server -filer=true -ip=159.69.136.31 -dir=/storage/new_master -volume.max=3000 -volume.images.fix.orientation=false -pulseSeconds=5
```
Volume Command
```
/opt/go/bin/weed -v=0 volume -mserver=159.69.136.31:9333 -ip=46.4.221.254 -dir=/storage -max=3000 -images.fix.orientation=false -pulseSeconds=1
```

**Expected behavior**
There should be no I/O Time out while dialling up TCP to another volume server from the master filer

**Additional context**

We are saving files to seaweedfs with 2 methods, both are the same.

just one method save it with a directory structure, and always there is a new and different file.

Other, send 1 request per camera to save the thumbnail of a camera, 
this time file is different but the name is always the same.

`thumbnail.jpg`.

And we are getting most of the request timeouts for this file.

You can say within 30 timeouts..

The first method gets 5 and others get 25 request timeout.

I am not sure where the issue is: But my hunch is that time IO Timeouts are causing problem or the same file name also causing the problem?

**Comment by chrislusf** [comment]
The master 159.69.136.31 is failing to connect to 46.4.221.254, port 18080. This is needed for gRPC which is added in recent SeaweedFS versions.

**Comment by chrislusf** [comment]
Not sure about your timeout setting. Updating the same picture will need to do a deletion of the old content also. The additional http call would cause more timeouts.

It looks you are using a version dated to 2018-10-18 20:47

In a commit in 2018-11-20 11:35, https://github.com/chrislusf/seaweedfs/commit/b318167cd3411b49e142610e11f70cc073ee8382 it batches the deletion and run it in background jobs. It should reduce your timeouts.

**Comment by ijunaid8989** [comment]
We are on v1.28 https://github.com/chrislusf/seaweedfs/releases/tag/1.28

for master and 3 volumes, the same version.

As well as the gRPC ports are open to each and another server.

telnet does make a connection on port 18080

```
root@Ubuntu-1804-bionic-64-minimal:~# telnet 46.4.221.254 18080
Trying 46.4.221.254...
Connected to 46.4.221.254.
```

**Comment by chrislusf** [comment]
your log output does not match the git version.

**Comment by ijunaid8989** [comment]
that's strange

![image](https://user-images.githubusercontent.com/13561999/55932137-c472d380-5c41-11e9-9999-11e845488c83.png)

**Comment by chrislusf** [comment]
what about the volume servers?

**Comment by ijunaid8989** [comment]
Volume 46.4.221.254
![image](https://user-images.githubusercontent.com/13561999/55932262-609cda80-5c42-11e9-9feb-09c3abfe7321.png)

Volume 88.99.70.249

![image](https://user-images.githubusercontent.com/13561999/55932282-83c78a00-5c42-11e9-86ab-b783557534da.png)

**Comment by chrislusf** [comment]
1.29 added reusing cached grpc connections.

btw: next release reduces leveldb memory requirements. maybe it is useful to you also.

**Comment by ijunaid8989** [comment]
Okay I will update now.

**Comment by chrislusf** [comment]
FYI: this commit could be related to this issue also: https://github.com/chrislusf/seaweedfs/commit/e11e127d91c3a6e1f4b13243a9c7cd1980159dd9

**Comment by ijunaid8989** [comment]
I have just updated Seaweedfs version now.

I will update about it after some time.

PS: now when you run command `weed version` it outputs
```
version 30GB 1.30 Linux amd64
```

that 30GB seems suspicious?

**Comment by chrislusf** [comment]
https://github.com/chrislusf/seaweedfs/wiki/FAQ#how-to-configure-volumes-larger-than-30gb

**Comment by ijunaid8989** [comment]
We are still getting the same timeout and most of them on thumbnail.jpg update.

In past, we were using the same method, without deleting the old files and just post to it again and again.

But now Each request only giving us timeouts..

Are the newer versions not capable of handling almost 800 to 1k POST requests to filer in 2 to 3 seconds?

**Comment by chrislusf** [comment]
Is there any way to reproduce this?

**Comment by chrislusf** [comment]
Added some stress test code https://github.com/chrislusf/seaweedfs/compare/2e03f3adef08...26aaccca088e and here are some numbers.

This test traffic goes through filer only. If this is your way and you use shared filer store(redis/mysql/porestgres/cassandra), you can improve throughput and reduce timeout by adding more filer instances.

You can also use "weed filer.copy", which will send data to volume servers directly and update the metadata in filer. This is much more performant.

```
bench_filer_upload$ bench_filer_upload -n 102400 -size 204800
data len 204800
1009.72 files/s, 195.95 MB/s
988.37 files/s, 192.07 MB/s
853.97 files/s, 165.99 MB/s
715.98 files/s, 138.00 MB/s
662.00 files/s, 128.00 MB/s
781.65 files/s, 151.93 MB/s
931.04 files/s, 181.81 MB/s
989.53 files/s, 192.30 MB/s
929.86 files/s, 179.97 MB/s
992.07 files/s, 192.01 MB/s

```

**Comment by ijunaid8989** [comment]
We are using leveldb embedded filer as mentioned above in very first post.
```
/opt/go/bin/weed -v=0 server -filer=true -ip=159.69.136.31 -dir=/storage/new_master -volume.max=3000 -volume.images.fix.orientation=false -pulseSeconds=5
```

We are using leveldb filer.

filer.toml file.
```
[memory]
# local in memory, mostly for testing purpose
enabled = false

[leveldb]
# local on disk, mostly for simple single-machine setup, fairly scalable
enabled = true
dir = "/storage/new_master/filer"					# directory to store level db files
```

**Comment by chrislusf** [comment]
almost same perf numbers.

```
bench_filer_upload$ bench_filer_upload -n 102400 -size 204800
data len 204800
960.05 files/s, 186.01 MB/s
980.01 files/s, 190.00 MB/s
995.99 files/s, 194.00 MB/s
891.53 files/s, 173.52 MB/s
878.45 files/s, 170.48 MB/s
976.79 files/s, 188.99 MB/s
916.87 files/s, 178.95 MB/s
953.69 files/s, 185.94 MB/s
776.52 files/s, 149.72 MB/s
930.50 files/s, 181.32 MB/s
923.57 files/s, 179.92 MB/s
930.22 files/s, 181.65 MB/s
1018.48 files/s, 197.65 MB/s
871.53 files/s, 169.13 MB/s
922.67 files/s, 178.52 MB/s
889.85 files/s, 171.97 MB/s
782.99 files/s, 151.42 MB/s

```

**Comment by ijunaid8989** [comment]
I don't know how you are reproducing it but so far, In new versions, there are some changes are making these timeouts. our data and configuration are the same as in past.

Suppose there are 700 cameras in total.

1. there are 700 concurrent requests after 1 minute to thumbnail.jpg (ALL give timeouts). In past it was all fine we were just posting at same pictures and everything was fine.
2. the same 700 cameras are sending 1 request per second/minute/10minutes. so almost 500 requests are concurrent per second. (each second) and others are in between 1 to 10 minutes.

Point 2 gives lower timeouts approx 30 to 50 each time.

Point 1 gives only timeouts.

**Comment by chrislusf** [comment]
possibly related to compaction. Added "weed volume -compactionMBps=xxx" option to pace the compaction.

**Comment by ijunaid8989** [comment]
Thanks Chris. Much appreciated.
