### ISSUE TITLE
[Question] File Availability Upon Replica Failure

### ISSUE THREAD

**Issue by zicklag** [chrislusf/seaweedfs#919]
# Scenario

## Goal

Highly available distributed filesystem such that any one server can fail without losing the availability of of the filesystem.

[[Full Editable Diagram]](https://www.draw.io/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=SeaweedFS%20Architecture.xml#R7Vvbjts2EP0aA%2BlDDF19edybExRJG8BFmzwtaGkssUuJLkVftl%2FfoUTZkiiv7dSxN%2FZ6gUQcUaQ058zRkCI77l2y%2BiDILP7MQ2AdxwpXHfe%2B4zh9p4%2F%2FKsNzYfAGXmGIBA0Lk70xjOm%2FoI2Wts5pCFmtouScSTqrGwOephDImo0IwZf1alPO6r3OSASGYRwQZlr%2FoqGMtdXuDTcnPgKNYt31oHzgCQmeIsHnqe6v47jT%2FFecTkjZln7QLCYhX1ZM7kPHvROcy%2BIoWd0BU64t3VZcN9pydn3fAlK5zwUDe1BcsiBsDuU99xhefDvBg0gdfOCEddybjmqrOIUNrs9%2BRDewZ%2BX4BaGMTNCHCDzNpKCTuYRQ%2BZ8yyJ4zCQkWljEIVYWkz5UW183xFNp6waopskxhTtIc%2BWTGQELe8xQ7zltUnckYml1mkqqn1j2Jsk0BCaFp9c67ZiWNk3wuuYEtszvOuMiLrnd%2FY498rIgPzJ%2BgPJOq50Bjia%2BNhUiQkCIwjTpTnkodAraHZcJolGKBwVTdQDYjAU2jT3np3rf0FZVb0Axzb2OZMN2XSQTNjQUICauKSRPjA%2FAEpFDu1Gcd3y8uKYNYc3a5iYh%2BX9viSjD42kZ0EEbrljdExAPNxS1EtizbIOZvBQFsA5I84CDUj04mGWfIvBsRlG5V1nXJqXuqFbctUNXgDEkW551aDRAdE6Lhg%2FozwVVoUNSdG22WfLaBXLVlbYp%2FqHP37xVFGhwc2aPBw3CNugFxCxG2o96zaqjbtgn7mgpV2N0j4e5sw915w%2F0H4u47Z8bd3Ya7u4covzHheEzoD87MhLaUpIF3HTJ0QJj%2FTMes34014IrLy9ROWQ4n0DFizq2%2FYW2%2FxdOWb3ra847i6KHh6DGQJUA4Gpsx95lgNiUKHd4Zj7XI0Fl6nhoWlkrwNfDq%2B%2BrvhXRqptpIVpEad3SjYOZ0ZyAyTDfR54%2BYdj49ZimZZbHKoG8RCqn7wfwO2BeeUUm5ijNReHMdf58a5xMahup%2Bd8Xrul4jTzMVwMp%2FLUqxH5N0XJhk0uSxur5BHtdpiVJtE8CIpIv6iKeNULrHL5zivWy4W2Pue7tXb4BPpxlIg4%2Fr296ToqX0XL4W9Idn1QLbTLf30YJ93s1vWnB8LbCtdjJdtBaYI4ML1QKnf14tMFPxfbTAftOC82iBc31aUHZzfVrguifVAqdnOPqOZBlJQ0HMeB9RlkvBWPJ8jvf%2B9hXqAkKIgSohfIxIAo8ZCATo0kShCJArE4X%2BtYhCc%2BLg1KJgztAcKgqvbRLhOkShf4WiYE5yXagoNGcQTiwKrjlVc6govLbZhOsQheH1iYJrznZdqCg0MwWnf1pRMOdsXphKKEXB%2FMJ%2FyqhfUCHnhD2qJSSPeg3JhcW8u4U0Fx3z5qzWhcZ8MxE4dcx73xPzJhhvMX%2FcmHevMOa%2FZ5qwFwxgMjVpFRIYTINXGvO%2B36t51B0MDTjt3sDEs%2FcCdAfEfMs0oeBqbeWvfJKvHW3G%2FQK9kkB3SlddATOm8mwVOS0DgFc1JAjYPP%2FccWnicIXTha45XfgOiwlfgF7F%2FItBNfSi7OxePFblmTaVUAfo9Zw%2FW8FexlTCGBFXfS6RejVNsZoC1GDCaOTi70iiMhzWkPDKrwEVGgxaaOAcZR2YZ44dTPHWMZphdDDUWKHc0urBKmQ19zUSu0EAQWDgimcmA9%2FLV18fI0Pz7LpjyyFPVa2ttiV2x%2FHsPqlwq2dDKlBcCxVbQiZ%2FBmd7nvV9zi6nDv%2Bns3%2BOT5U%2FUEaanzCdtgWlbQAcZzzimbnJC%2BORP%2FO8BKuPi9m%2Bc89GTObBE1zcmgXvCvMN7%2Bf4PPkj84nmZOSJhcD8bHmQEJx3iuJCheAKP0mWq%2FkqRIIwgrEuciFjHvGUsIeNtTECqDALVlR%2BrRx%2FU1W6Cip0s3j%2BWi9%2B0zX%2FBimfNV5kLjmaNv1%2B4vlGk92jC3XbL2sBPiWfiwDWeOucShIRwc7h595wHiACbd%2BDi9hXz9pRW0vLx%2B39M%2BfFjEPJ84qpUAklDjSAnKF5T8qZCcmjSe1NbaqK3qrKC0VBv6ttq1zGeTHmmFEbl9Bpp9zVWlSwQgpZ61bVpuVdfiVSJ4rx6J6jgqh%2Bxksi1L5YLoIYk3hBJFeXkETl7ukkU%2F%2F9sr19dHLhqi3zMaV84XNtG89W%2BLvZMv37XDKalm%2Bl2outKXTGKHqn0u0ed2fVzVvG29ZpH6iEvUnP7x0rT24MVNrm7Z2W1%2BPw8FEhFje7zAsV2%2Bzkdx%2F%2BAw%3D%3D)

![SeaweedFS Architecture](https://user-images.githubusercontent.com/25393315/55753121-30212a80-5a0f-11e9-8b3a-b6fb637f695b.png)

## Explanation

Given the above layout for the SeaweedFS services, I have one problem: when a node that has a volume server on it goes down, the filesystem becomes read-only because of the under-replicated volumes. The cron job that runs the re-replication of the volumes on a schedule will automatically fix the under-replicated volumes, but there will still be a time period where the filesystem is un-writable until the cron-job runs and all of the volumes have been re-replicated.

Is it necessary to make the volumes read-only when they are under-replicated, or could there be a way to configure them not to become read-only when there are missing replicas?

**Comment by chrislusf** [comment]
Have more volumes spread on more servers, so if one server goes down, there are other volumes writable. And do not try to "update" the entries. Just write a new entry.

**Comment by zicklag** [comment]
1. So if I have a majority of replicas for a volume, the volume will still be writable?
2. I'm just using filesystem mount so will the filer handle not using "update" for the entries? ( I don't know much about the HTTP API for Seaweed works ).

**Comment by chrislusf** [comment]
1. No
2. yes. Filer will act the right way.

**Comment by zicklag** [comment]
Ah! I finally get it. So if the number of available volume servers is greater than the target number of replicas, then there won't be any write issues. When it needs to write a new file or update an existing one, it will create a new entry and replicate it on the available servers. So with a replication mode of 001 and three volume servers, I can lose up to one server and still maintain availability. 

That's great, thanks!

**Comment by zicklag** [comment]
I would like to put this info in the Wiki, is there anywhere specific that you want me to put it?
