### ISSUE TITLE
How can i upload more file in one request?

### ISSUE THREAD

**Issue by Kiltalaw** [chrislusf/seaweedfs#920]
i could not find the api document about how to upload more file in one request.
so it means i have to repeat post request to seaweedfs filer but it is terrible that i have to sovle the multi-thread situation which cause by the network congestion or I have to write the shell to upload files to the seaweedfs filer?

**Comment by chrislusf** [comment]
no such API.

reuse the http connection.

**Comment by Kiltalaw** [comment]
I am not sure if it is necessary to add it on in next version.
it's not friendly to while i have to upload files because i have to write shell or handle the network exceptioin.

**Comment by chrislusf** [comment]
There are "weed upload" and "weed filer.copy" if you just want to upload.
