### ISSUE TITLE
filer.copy显示客户端连接失败

### ISSUE THREAD

**Issue by LHFData** [chrislusf/seaweedfs#921]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**
I0409 13:19:42  6720 masterclient.go:95] client failed to connect with master localhost:9333: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:19333: connect: connection refused"
**System Setup**
the SeaWeedFS was deployed ,using official docker-compose.yml

**Screenshots**
the command i used as follow:
./weed filer.copy {filename} http://{remote-fileraddress}:8888/testdir/

**Additional context**
i couldn't find what cause the problem, the network? or the configuration of seaweedfs' docker-compose.yml?or the command ?

**Comment by chrislusf** [comment]
docker's network. seems you are running in docker but not familiar with docker.

try to run it without docker first.
