### ISSUE TITLE
size of sub directories  under weed mount  directory shows 0

### ISSUE THREAD

**Issue by accumulatepig** [chrislusf/seaweedfs#923]
weed version: 1.26

run df -h command under weed mount  directory:
drwxrwxr-x 1 root root 0 Aug 14  2018 testdir01
drwxr-xr-x 1 root root 0 Mar 14 09:30 testdir02
-rwxrwx--- 1 root root 22827 Mar 21 11:48 test.txt

directory size shows 0 , but  file size is ok

**Comment by chrislusf** [comment]
It's costly to get the subfolder size, especially if the directory size is
big. It's better not to support this.

**Comment by chrislusf** [comment]
Correction: the directoryis stored in filer store, a key value store,
different from what the df is expo.

**Comment by chrislusf** [comment]
Is the command "df -h" or "ls -l"?

**Comment by chrislusf** [comment]
not plan to fix this.
