### ISSUE TITLE
!!!! volume id  109  location not found!!!!!

### ISSUE THREAD

**Issue by JoelvSilly** [chrislusf/seaweedfs#929]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**
A clear and concise description of what the bug is:
I got the issue saying "volume id xx location not found" when running weed bechmark for performance testing.

**System Setup**
I got 3 servers to install weed as screenshot showing.
Wee version 0.76.

**Expected behavior**
Running a benchmark script in 5 different client server as below: 
sh start_benchmark.sh 3 2000 20 3.1_55 100
sh start_benchmark.sh 3 2000 20 3.1_56 100
sh start_benchmark.sh 3 2000 20 3.1_61 100
sh start_benchmark.sh 3 2000 20 3.1_62 100
sh start_benchmark.sh 3 2000 20 3.1_63 100

start_benchmark.sh:
`#! /bin/bash

bench_num=$1
file_num=$2
file_size=$3
log_name=$4
conc=$5
-- 单台测试机器 测试benchname;文件数量；文件大小(M);日志名;并发数
size=$[$file_size*1024*1000]
##read and write
nohup weed benchmark -server="10.12.6.134:9333" -n=$file_num -size=$size -collection="benchmark_$bench_num" -c=$conc  > benchmark_$log_name.log &`

**Screenshots**
![image](https://user-images.githubusercontent.com/38069572/56121507-d8e90000-5fa2-11e9-816a-3e057454a93c.png)
![image](https://user-images.githubusercontent.com/38069572/56121562-f1f1b100-5fa2-11e9-98ea-545badfa149a.png)
![image](https://user-images.githubusercontent.com/38069572/56121583-fc13af80-5fa2-11e9-96f4-eff7fbcd97b9.png)

**Additional context**
The thing I want to do is to test the performance when uploading 10K files of 20M.

**Comment by JoelvSilly** [comment]
Plus:
1. I pre-assigned 70 volume ids for benchmark testing, and totally 58 volume ids appeared in the log with the same issue above.
2. The bandwidth is 1000Mbps max for my servers.
3. The cpu load of one master server is over 100 when running benchmark.
![image](https://user-images.githubusercontent.com/38069572/56122372-dbe4f000-5fa4-11e9-9f70-f308c8ef30ca.png)

Question:
So what should I do to avoid the issue if I want to upload 20M files ? Reduce the concurrent？
Thanks for the response in advance.

**Comment by chrislusf** [comment]
master server should not be that busy.

concurrency seems high.

**Comment by JoelvSilly** [comment]
> master server should not be that busy. Need to find out why.
> 
> better use a late SeaweedFS version. You are only using blob store. No need to still use 0.76.

Each server showed in the sceenshot is installed with 1 master and 8 volume server. 

And I found several logs as below:
weed3 10.12.6.136 which the load is high:
```
I0415 17:02:27  5388 topology_event_handling.go:52] Removing Volume 126 from the dead volume server 10.12.6.136:8105
I0415 17:02:27  5388 volume_layout.go:227] Volume 126 has 0 replica, less than required 2
I0415 17:02:27  5388 topology_event_handling.go:52] Removing Volume 78 from the dead volume server 10.12.6.136:8105
I0415 17:02:27  5388 volume_layout.go:227] Volume 78 has 0 replica, less than required 2
```

weed3 one volume server(10.12.6.136:8105):
```
I0415 17:01:36  2711 store.go:35] Resetting master nodes: nodes:[10.12.6.135:9333 10.12.6.136:9333 10.12.6.134:9333], leader:
I0415 17:01:37  2711 volume_grpc_client.go:52] Heartbeat to 10.12.6.136:9333
I0415 17:02:27  2711 volume_grpc_client.go:95] Volume Server heart beat stops with <nil>
I0415 17:02:27  2711 store.go:35] Resetting master nodes: nodes:[10.12.6.136:9333 10.12.6.134:9333 10.12.6.135:9333], leader:
I0415 17:02:27  2711 volume_grpc_client.go:52] Heartbeat to 10.12.6.134:9333
```

**Comment by chrislusf** [comment]
1. use a late SeaweedFS version
2. in -mserver, specify the full list of masters.

**Comment by JoelvSilly** [comment]
>     1. use a late SeaweedFS version
> 
>     2. in -mserver, specify the full list of masters.

Well, No.1 might be a quick way to fix that but I still want to figure it out.

I specified the full list of masters in each starting command of volumes:
`weed volume -dataCenter=dc1 -rack=rack1 -ip=10.12.6.134 -idleTimeout=150 -max=80 -dir=/data1/seaweedfs/vdata1 -mserver=10.12.6.134:9333,10.12.6.135:9333,10.12.6.136:9333 -port=8101`

However there is an error below showing in all volume logs after restart all volumes and masters:
I0416 14:11:55 23079 volume_grpc_client.go:25] heartbeat error: No master found: No master node available!

**Comment by chrislusf** [comment]
Not sure why keep debugging for an old version.
