### ISSUE TITLE
http://localhost:8080/ui/index.html shows 0 bytes for all volumes.

### ISSUE THREAD

**Issue by ijunaid8989** [chrislusf/seaweedfs#935]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**
I have started filer with version 1.31 and Added almost 300+ files to it, but port 8080 showing - stats for anything in filer/volumes.

**System Setup**
Ubuntu 18.04
command:
```
weed -v=0 server -filer=true -dir=storage -pulseSeconds=1 -volume.images.fix.orientation=false
```

**Expected behavior**
http://localhost:8080/ui/index.html..
It should show some files are present in volumes.

**Screenshots**
![image](https://user-images.githubusercontent.com/13561999/56492382-1569ae00-6505-11e9-91aa-71b0af142076.png)

![image](https://user-images.githubusercontent.com/13561999/56492389-1dc1e900-6505-11e9-93f1-4698940a14ea.png)

**Comment by chrislusf** [comment]
This affects the UI, but not the functionality. If using `echo "volume.list" | weed shell`, the volume stats still shows up fine.
