### ISSUE TITLE
filer problem

### ISSUE THREAD

**Issue by gaojunjie03** [chrislusf/seaweedfs#937]
i upload a file which is already exist in seaweedfs. but it looks like the seaweedfs filer cannot be covered by the new file ?  my seaweedfs version is 1.28.
i want to be covered by the new file，how can i do that?

**Comment by chrislusf** [comment]
can not.

**Comment by gaojunjie03** [comment]
but the 1.11 version can do that , i use this version before

**Comment by chrislusf** [comment]
can you use Chinese to explain the question?
