### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by xiangshibo** [chrislusf/seaweedfs#939]
When I execute this command 【./weed volume -dataCenter="report" -port="8081" -dir="/opt/data1/files" -mserver="172.18.100.134:9330" max="16"】,the following error occurred.What should I do, thank you.
![image](https://user-images.githubusercontent.com/11767971/56653143-9a98c280-66bf-11e9-9a11-318e6082b962.png)
The master command line is【./weed master -mdir="/home/seaweedfs/ids" -port="9330" -ip="172.18.100.134】

**Comment by chrislusf** [comment]
related to https://stackoverflow.com/questions/28670232/atomic-addint64-causes-invalid-memory-address-or-nil-pointer-dereference

**Comment by xiangshibo** [comment]
I chose the wrong version. The error was solved after the replacement. Thank you for your answer.

**Comment by chrislusf** [comment]
Could you please be more specific? what are the differences?

**Comment by xiangshibo** [comment]
I used a 32-bit weed on a 64-bit machine. The master process can be started, but an exception occurs when executing .\weed volume. I think it's more obvious to mark each release.
