### ISSUE TITLE
timeout如何设置？

### ISSUE THREAD

**Issue by gaojunjie03** [chrislusf/seaweedfs#940]
{
    "error": "Post http://192.168.4.140:9090/6,0302ff237371: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"
}

**Comment by chrislusf** [comment]
-idleTimeout

**Comment by yunbj** [comment]
@chrislusf 

I tested uploading file on slow network.
I set limit-rate for curl using 30m file.
Without limit rate, uploading the file was succeeded.
But, the error occurs after 5s with limit rate though I set idleTimeout 30s.
Within 5 seconds, all tests were succeeded.

During investigation, timeout of http client was changed to 5 seconds by 39c745588111cebef0475f2453ee0715e0153c49 commit.
Was there a reason to change timeout?

**Comment by chrislusf** [comment]
@yunbj do you upload to master or volume server?

**Comment by yunbj** [comment]
I uploaded files through filer.

**Comment by chrislusf** [comment]
@yunbj thanks for reporting! I fixed it in https://github.com/chrislusf/seaweedfs/commit/20d90dea5a04c815319c375e5c69e9bdecbca633
