### ISSUE TITLE
no response after run some days using docker-compose

### ISSUE THREAD

**Issue by joveth** [chrislusf/seaweedfs#941]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**
I'm using docker-compose to publish server
But after some days.The seaweedfs container can not get a fid using like:
`    
    127.0.0.1:9333/dir/assign
`
But 127.0.0.1:9333 shows a page seems that the server is ok, and also 127.0.0.1:8777 can show images.

When restart the container.It recovery.

Maybe it not wrong with  seaweedfs. but i don't have any ideas.

Thanks

**System Setup**

    filemaster:
        image: chrislusf/seaweedfs
        privileged: true
        ports:
          - "9333:9333"
          - "8777:8777"
        volumes:
          - "$PWD/imgdata/mdata:/data"
        command: server  -master.port=9333  -volume.port=8777 -volume.publicUrl=127.0.0.1:8777  -volume.max=100 -dir=/data
        network_mode: "bridge"

**Comment by chrislusf** [comment]
SeaweedFS does not do anything special. Please check the container related issue.
