### ISSUE TITLE
volume_server_handlers_read.go:71] read /2,89f636320a error: already deleted after `fs.meta.load` 

### ISSUE THREAD

**Issue by ijunaid8989** [chrislusf/seaweedfs#943]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**
Few files are not being opened after weed shell fs.meta.load

**System Setup**
Ubuntu 18.04
Weed v. version 30GB 1.31 linux amd64
Started seaweedfs filer with this command
```
./weed -v=0 server -filer=true -dir=storage -pulseSeconds=1 -volume.images.fix.orientation=false
```

Add new files to filer using REST API at port 8888.

the storage directory contains:
```
1.dat  2.dat  3.dat  4.dat  5.dat  6.dat  7.dat   filer  snapshot
1.idx  2.idx  3.idx  4.idx  5.idx  6.idx  7.idx  conf        log  
```
All files are being served from port 8888 and accessible.

Now go to `weed shell` and run `fs.meta.save`, this created a new file in the root of the folder as 

```
localhost-8888-20190425-104730.meta
```

Now delete the filer directory from 

```
1.dat  2.dat  3.dat  4.dat  5.dat  6.dat  7.dat  snapshot
1.idx  2.idx  3.idx  4.idx  5.idx  6.idx  7.idx  conf        log  
```

and stop start seaweedfs.

No files are on port `8888` 

Now again go to `weed shell` and run command `fs.meta.load "localhost-8888-20190425-104730.meta"`

It will load all files such as 

```
load /bamed-kiznw
load /bamed-kiznw/snapshots
load /bamed-kiznw/snapshots/thumbnail.jpg
load /bamho-xwtim
load /bamho-xwtim/snapshots
load /bamho-xwtim/snapshots/oldest-1556166444.jpg
load /bamho-xwtim/snapshots/recordings
load /bamho-xwtim/snapshots/recordings/2019
load /bamho-xwtim/snapshots/recordings/2019/04
load /bamho-xwtim/snapshots/recordings/2019/04/25
load /bamho-xwtim/snapshots/recordings/2019/04/25/04
load /bamho-xwtim/snapshots/recordings/2019/04/25/04/27_24_000.jpg
load /bamho-xwtim/snapshots/recordings/2019/04/25/04/27_29_000.jpg
load /bamho-xwtim/snapshots/recordings/2019/04/25/04/27_34_000.jpg
load /bamho-xwtim/snapshots/recordings/2019/04/25/04/27_39_000.jpg
load /bamho-xwtim/snapshots/recordings/2019/04/25/04/27_44_000.jpg
load /bamho-xwtim/snapshots/recordings/2019/04/25/04/27_49_000.jpg
load /bamho-xwtim/snapshots/recordings/2019/04/25/04/27_54_000.jpg
load /bamho-xwtim/snapshots/recordings/2019/04/25/04/27_59_000.jpg
load /bamho-xwtim/snapshots/recordings/2019/04/25/04/28_04_000.jpg
load /bamho-xwtim/snapshots/recordings/2019/04/25/04/28_09_000.jpg
load /bamho-xwtim/snapshots/recordings/2019/04/25/04/28_14_000.jpg
load /bamho-xwtim/snapshots/recordings/2019/04/25/04/28_19_000.jpg
.......more logs.......
load /water-neiow
load /water-neiow/snapshots
load /water-neiow/snapshots/thumbnail.jpg
load /waxie-jolxd
load /waxie-jolxd/snapshots
load /waxie-jolxd/snapshots/thumbnail.jpg

total 279 directories, 246 files
localhost-8888-20190425-094508.meta is loaded to http://localhost:8888/
```

Now again start-stop, seaweedfs.

as it's clear from `fs.meta.load`

![image](https://user-images.githubusercontent.com/13561999/56714963-b8156d00-674f-11e9-9fab-7ee9c2677ecd.png)
It's loaded `/bamho-xwtim/snapshots/recordings/2019/04/25/04/27_29_000.jpg`

it's also available in meta info on port 8888
![image](https://user-images.githubusercontent.com/13561999/56715011-dbd8b300-674f-11e9-8e77-da2729055c34.png)

But on access to this file.

![image](https://user-images.githubusercontent.com/13561999/56715050-f27f0a00-674f-11e9-9f74-62c1fbef94b1.png)

![image](https://user-images.githubusercontent.com/13561999/56715078-0fb3d880-6750-11e9-8b0b-9369b2903141.png)

No operation was performed on Filer API port 8888.. to delete this file(almost 10 files are being shown as deleted.)

as filer directory contains all meta values, but on deleting that directory, few files are also missing.

After doing many start-stops to seaweedfs the log from `already deleted` changed to

![image](https://user-images.githubusercontent.com/13561999/56715272-a2547780-6750-11e9-840c-4a160176c99f.png)

there were total of 108 files were being added 

![image](https://user-images.githubusercontent.com/13561999/56715324-c87a1780-6750-11e9-8109-ae74e481e277.png)

on `fs.meta.load` meta values are back but few files are missing now. 

**Expected behavior**
It should not give 404 or already delete as actual file or file data is not saved on filer store.

**Additional context**
This issue is to demonstrate what I described over slack.

**Comment by chrislusf** [comment]
I can not reproduce locally.

There are no deletion happening, while the file in the volume .dat and .idx files are changed. Can you check why the .dat and .idx files are changed when you fs.meta.save and fs.meta.load?

**Comment by ijunaid8989** [comment]
what could be the possibility of the changes in .dat or .idx?
1. We are not deleting anything.
2. Auto Vacuum forcing to delete those files??

Try it this way.

after deleting the filer store directory. and before doing fs.meta.load, keep seaweedfs filer keep running. 

I think that's the moment when master filer made some changes. I am trying to replicate it again, I will post again with screenshots.

**Comment by chrislusf** [comment]
If there are some updates to existing uploaded files, e.g., upload a new version of a picture, the picture's metadata will point to a new file id, and deleting the old file id. So using the previous fs.meta.save meta files will point to the old deleted file id.

**Comment by ijunaid8989** [comment]
Okay, this is what I came to.

We recorded almost 15 minutes for a camera, and these are all different jpegs with time series, which cannot be re-recorded. And cannot be deleted. After recording for 15 minutes I stopped the server which was recording the jpegs (getting from the camera and send it to Seaweedfs).

Now nothing is being added and nothing is getting replaced/deleted.

I repeat the above process again. During all this seaweedfs is running. after all meta.save meta.load, 

I have lost 14 images.

That's all I can tell. More than that I have no idea what I am doing wrong which is making it lose images. I am going to update seaweedfs any way now.

**Comment by chrislusf** [comment]
If possible, you can run fs.meta.save again if found files are missing and send me the 2 meta files. I can code something to find out the difference.

**Comment by chrislusf** [comment]
added a simple tool to see the content of meta file: https://github.com/chrislusf/seaweedfs/commit/6aad558972459f048835a85d721e48488e6c604e

**Comment by chrislusf** [comment]
closing. reopen if more findings.
