### ISSUE TITLE
Image file data lost at version 0.91 after

### ISSUE THREAD

**Issue by cooper-lyt** [chrislusf/seaweedfs#944]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**
When I save images (JPGs,BMP,JPEG) after , download it , image can't view , may be lost some data.  this bug in version 0.91  - 1.32,  is work fine less then 0.90  ver.

**System Setup**
weed server -master.port=9333 -volume.port=9080 -dir="/data" -volume.publicUrl="127.0.0.1:9080"

**Expected behavior**
view image

**Screenshots**

**Additional context**

**Comment by chrislusf** [comment]
can not reproduce anything with current issue description.

**Comment by cooper-lyt** [comment]
i upload image:
<img width="568" alt="WeChat453269459bfa7c296aa6447ed5199e90" src="https://user-images.githubusercontent.com/4219608/56759912-9b6b4a80-67cc-11e9-9c65-ecc7ede90cd0.png">


download it 
<img width="569" alt="WeChat652cc91d0db9440a7b713d5cff728b96" src="https://user-images.githubusercontent.com/4219608/56759683-1bdd7b80-67cc-11e9-85eb-d02d6e410394.png">

view in chrome
<img width="1040" alt="WeChat891d505aadac532cc9013762aaa88270" src="https://user-images.githubusercontent.com/4219608/56759645-fea8ad00-67cb-11e9-9c12-fcf1484954c5.png">

**Comment by chrislusf** [comment]
Can not reproduce. Here are my steps:

```
weed$ weed filer.copy  ~/Desktop/Sunflower_from_Silesia2.jpg http://localhost:8888/
uploaded Sunflower_from_Silesia2.jpg to http://localhost:8456/4,0163f6d9ebc0
copied Sunflower_from_Silesia2.jpg => http://localhost:8888/Sunflower_from_Silesia2.jpg
weed$ wget http://localhost:8888/Sunflower_from_Silesia2.jpg
--2019-04-25 13:09:18--  http://localhost:8888/Sunflower_from_Silesia2.jpg
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:8888... failed: Connection refused.
Connecting to localhost (localhost)|127.0.0.1|:8888... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2803917 (2.7M) [image/jpeg]
Saving to: ‘Sunflower_from_Silesia2.jpg’

Sunflower_from_Silesia2.jpg                           100%[========================================================================================================================>]   2.67M  --.-KB/s    in 0.01s

2019-04-25 13:09:18 (209 MB/s) - ‘Sunflower_from_Silesia2.jpg’ saved [2803917/2803917]

weed$ ls -al Sunflower_from_Silesia2.jpg
-rw-r--r--  1 chris  staff  2803917 Apr 25 13:08 Sunflower_from_Silesia2.jpg
weed$ ls -al ~/Desktop/Sunflower_from_Silesia2.jpg
-rw-r--r--@ 1 chris  staff  2803917 Apr 25 13:08 /Users/chris/Desktop/Sunflower_from_Silesia2.jpg
weed$ wget http://localhost:8456/4,0163f6d9ebc0
--2019-04-25 13:09:44--  http://localhost:8456/4,0163f6d9ebc0
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:8456... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2803917 (2.7M) [image/jpeg]
Saving to: ‘4,0163f6d9ebc0’

4,0163f6d9ebc0                                        100%[========================================================================================================================>]   2.67M  --.-KB/s    in 0.01s

2019-04-25 13:09:44 (201 MB/s) - ‘4,0163f6d9ebc0’ saved [2803917/2803917]

weed$ ls -al 4,0163f6d9ebc0
-rw-r--r--  1 chris  staff  2803917 Apr 25 13:08 4,0163f6d9ebc0
```

**Comment by chrislusf** [comment]
please show your steps, and maybe attach the image you used to test.

**Comment by yourchanges** [comment]
check your upload method, It can be download but not be shown in chrome
mostly cased by wrong content-type header.

Chris Lu <notifications@github.com> 于2019年4月26日周五 上午5:01写道：

**Comment by cooper-lyt** [comment]
I found that the problem , 
 In my APP  use XMLHttpRequest PUT the file is not work. 
but I use CURL PUT the file ,  is work final! 
why , i miss something?

I already add request header   Content-Type image/jpeg

**Comment by cooper-lyt** [comment]
I print the request head:
My APP:
` host:localhost:6699
 content-type:image/jpeg
 connection:keep-alive
 content-length:2260715
 accept-encoding:gzip, deflate, br
 user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
 accept-language:zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7
 referer:http://localhost:4200/business-file/I2.15
 origin:http://localhost:4200
 accept:application/json`

CURL PUT :
` host:localhost:6699
 content-length:2260496
 user-agent:curl/7.56.1
 accept:*/*
 expect:100-continue`

**Comment by chrislusf** [comment]
please share your code in order to reproduce it.

**Comment by chrislusf** [comment]
will close this if no activities. @cooper-lyt

**Comment by cooper-lyt** [comment]
can you temporarily retain this! 
I'm on a case right now, I Will test this as soon as I finish.
I staying at 0.90

**Comment by chrislusf** [comment]
no idea how "/ng2-file-upload" works. 

can you create a reproducible test case?

**Comment by chrislusf** [comment]
similar to this. Please use POST instead of PUT.
