### ISSUE TITLE
FR: Add support for Consul KV as Filer database

### ISSUE THREAD

**Issue by digger18** [chrislusf/seaweedfs#945]
Since Consul is very popular for clusters and it is pretty easy to setup a highly available Consul cluster, I would really like to see support for it's key value store in Seaweed as a Filer database.

**Comment by chrislusf** [comment]
there are simply too many kv stores. do you want to work on this?

**Comment by chrislusf** [comment]
my impression is that consul kv store is mainly for consistency, not for high performance.
