### ISSUE TITLE
master节点自动分配

### ISSUE THREAD

**Issue by ooocici** [chrislusf/seaweedfs#947]
作者,你好!

请问master节点是否会根据volumes空间进行分配存储?
目前遇到旧集群节点空间已满, 新增硬盘后,master节点还是会分发至无空间硬盘.
目前采用指定datacenter方式规避该问题(还是有概率分配至无空间硬盘)，我该如何解决这个问题呢？

谢谢作者。

**Comment by chrislusf** [comment]
What're your volume server command line options?

**Comment by ooocici** [comment]
Master： 
./weed master -mdir="data" -ip="192.168.0.243" -defaultReplication="100" 

Volume：
volume -dir=/data -max=100 -mserver="192.168.0.243:9333" -index=leveldb -dataCenter=dc1 -rack=rack1 -ip=192.168.0.244

DataCenter 为4个， 分别为：dc1、dc2、dc3、dc4
Rack 为4个， 分别为： rc1、rc2、rc3、rc4

**Comment by chrislusf** [comment]
you can pre-allocate volumes.

https://github.com/chrislusf/seaweedfs/wiki/Master-Server-API#pre-allocate-volumes

**Comment by ooocici** [comment]
i'll try it soon, thank you very much!!
