### ISSUE TITLE
Unable to build with 128BitNeedleId

### ISSUE THREAD

**Issue by Smarrito** [chrislusf/seaweedfs#949]
Hey.

Im currently trying out what I'd be able to do with seaweed and up until now everything's looking pretty fine.

In my projects I'm usually working with UUID's, so I tried to build with the 128BitNeedleId tag.

Sadly, the build is failing because of invalid operations ins /storage/needle_map/compact_map.go

My build, ran with:

CGO_ENABLED=0 GOOS=linux go build -x -tags 128BitNeedleId -o /home/sergio/work/git/seaweedfs/weed github.com/chrislusf/seaweedfs/weed

`WORK=/tmp/go-build022534110`
`mkdir -p $WORK/b492/`
`cat >$WORK/b492/importcfg << 'EOF' # internal`
`# import config`

`packagefile github.com/chrislusf/seaweedfs/weed/storage/types=/home/sergio/.cache/go-build/bb/bbc307a316153e153aaa115c0d11a82efee3f5855f241fa22b51dc77865c2072-d`

`packagefile github.com/google/btree=/home/sergio/go/pkg/linux_amd64/github.com/google/btree.a`

`packagefile sort=/usr/lib/go-1.10/pkg/linux_amd64/sort.a`

`packagefile sync=/usr/lib/go-1.10/pkg/linux_amd64/sync.a`
`EOF`

`cd /home/sergio/go/src/github.com/chrislusf/seaweedfs/weed/storage/needle_map`

`/usr/lib/go-1.10/pkg/tool/linux_amd64/compile -o $WORK/b492/_pkg_.a -trimpath $WORK/b492 -p github.com/chrislusf/seaweedfs/weed/storage/needle_map -complete -buildid l12Sk0Lo9qUWdsK2kE8r/l12Sk0Lo9qUWdsK2kE8r -goversion go1.10.4 -D "" -importcfg $WORK/b492/importcfg -pack -c=4 ./btree_map.go ./compact_map.go ./needle_value.go ./needle_value_map.go`

`# github.com/chrislusf/seaweedfs/weed/storage/needle_map`

`storage/needle_map/compact_map.go:57:32: invalid operation: key - cs.start (operator - not defined on string)`

`storage/needle_map/compact_map.go:128:32: invalid operation: key - cs.start (operator - not defined on string)`

`storage/needle_map/compact_map.go:146:32: invalid operation: key - cs.start (operator - not defined on string)`

`storage/needle_map/compact_map.go:185:14: invalid operation: key - cm.list[x].start (operator - not defined on string)`

`storage/needle_map/compact_map.go:282:29: invalid operation: nv.Key - cs.start (operator - not defined on string)`

Sadly, I'm simply not experienced enough with go, so sorry, if this is rather easy to fix. I'll keep on trying and I'll further dig into the code. If I find a solution myself, I'll comment and close. 

Thanks for any help in advanced, much appreciated!

**Comment by chrislusf** [comment]
@Smarrito your build process is correct. It's just the 128bit version is not compiling any more.

The UUID as part of the file id seems good. But I think this is not really anyway better, because you will still need to store a UUID to volume id mapping somewhere. 

So it is very likely the 128 bit version will be discontinued.
