### ISSUE TITLE
Question about the volume

### ISSUE THREAD

**Issue by xiangshibo** [chrislusf/seaweedfs#953]
I mounted two volumes and set the maximum volume for each to be 15, for a total of 30. But I found that there are actually only 7 volumes after startup. What are the other volumes?What settings do I need to make? Now that the other volumes already have data, I am worried that after the 7 volumes are full, they will not work. Thank you
![image](https://user-images.githubusercontent.com/11767971/57289648-57dadf80-70ee-11e9-8387-e6cea562f074.png)

**Comment by ijunaid8989** [comment]
Don't worry they will get created as your existing volumes will fill up, It creates volumes with a frequency of 7.
After 7 volumes are full, they will work and new 7 will be created along.

**Comment by chrislusf** [comment]
@xiangshibo You can also increase the number of volumes this way: https://github.com/chrislusf/seaweedfs/wiki/Optimization#increase-concurrent-writes

**Comment by xiangshibo** [comment]
Thank you everyone
