### ISSUE TITLE
请问filer有没有API可以将目录重命名

### ISSUE THREAD

**Issue by gao2009ss** [chrislusf/seaweedfs#954]
请问filer有没有API可以将目录重命名？

如
http://127.0.0.1:8888/file/test/
重命名为
http://127.0.0.1:8888/file/test2/

找了一圈没看到有这种API

**Comment by ijunaid8989** [comment]
檢查此鏈接

https://groups.google.com/forum/#!searchin/seaweedfs/move%7Csort:date/seaweedfs/DrKRoGsRcIY/DxO94B5oedEJ

**Comment by chrislusf** [comment]
Actually rename via HTTP is removed, and this feature is only available in gRPC now. 

You can invoke it directly via FUSE, or code a little to invoke the gRPC.

```
service SeaweedFiler {
    ...
    rpc AtomicRenameEntry (AtomicRenameEntryRequest) returns (AtomicRenameEntryResponse) {
    }
    ...
}

```

**Comment by gao2009ss** [comment]
用gRPC调感觉太麻烦了,以后还会不会将http目录重命名功能加上?

**Comment by chrislusf** [comment]
Also you can "weed mount" the filer, and rename anything there.

**Comment by chrislusf** [comment]
@gao2009ss http API is too cumbersome. How about using `weed shell`?
