### ISSUE TITLE
Documentation - Volume Replication Recovery 

### ISSUE THREAD

**Issue by solganik** [chrislusf/seaweedfs#956]
Hi, I have been considering using seaweed in some project i`m starting (best alternative for S3 i found sofar :)), and i have  several questions regards how seaweed handles Volume server failure.

1) What happens if Volume Server fails ? can i still perform writes or "volumes" will be "read-only" ?
2) Is there any rebalancing mechanism in case of adding/removing/failing a node ? i.e. rebalancing the data across remaining nodes ? 
3) What happens when failed nodes returns, how it "catches up" data it missed (assuming volumes are still writable during "failure time" ?

**Comment by solganik** [comment]
Also i looked at the code  especially at store_replicate.go at ReplicatedWrite method, and from what i understand if one of replicas failed, request is considered as failed correct ?

**Comment by sashas-anyvision** [comment]
One more observation that i made is that if "Master volume" node looses communication with slave volume node is sets volume status to "unavailable" and avoids further writes to the volume 
Is this correct or am i missing something ?

**Comment by solganik** [comment]
One more observation that i made is that if "Master volume" node looses communication with slave volume node is sets volume status to "unavailable" and avoids further writes to the volume 
Is this correct or am i missing something ?

**Comment by chrislusf** [comment]
> What happens if Volume Server fails ? can i still perform writes or "volumes" will be "read-only" ?
Is there any rebalancing mechanism in case of adding/removing/failing a node ? i.e. rebalancing the data across remaining nodes ?
What happens when failed nodes returns, how it "catches up" data it missed (assuming volumes are still writable during "failure time" ?

These are good questions and should be included in the wiki.

If the volume server fails, the write request should restart again, request a new file id from the master.

Rebalancing feature is in `weed shell` by `volume.balance` command.

Volumes are readonly if volume peers are down.

**Comment by chrislusf** [comment]
If one replica write fails, the whole write request fails. A new file id would usually go to a different set of volumes.

If the volume server disconnects from the master, no writes can go to the volume server.

**Comment by sashas-anyvision** [comment]
> > What happens if Volume Server fails ? can i still perform writes or "volumes" will be "read-only" ?
> > Is there any rebalancing mechanism in case of adding/removing/failing a node ? i.e. rebalancing the data across remaining nodes ?
> > What happens when failed nodes returns, how it "catches up" data it missed (assuming volumes are still writable during "failure time" ?
> 
> These are good questions and should be included in the wiki.
> 
> If the volume server fails, the write request should restart again, request a new file id from the master.
> 
> Rebalancing feature is in `weed shell` by `volume.balance` command.
> 
> Volumes are readonly if volume peers are down.

So there is no automatic rebalancing in case of volume server failure ?

**Comment by chrislusf** [comment]
Usually you don't want to instantly rebalance as soon as one node is down.
You can schedule some periodic cron jobs for that.

**Comment by zicklag** [comment]
@sashas-anyvision You can checkout how the Docker container is setup to run the re-balance on a schedule: https://github.com/chrislusf/seaweedfs/pull/922/files.
