### ISSUE TITLE
下载的文件和上传的文件内容不一致

### ISSUE THREAD

**Issue by baopin** [chrislusf/seaweedfs#957]
**操作步骤**
#向/dir/assign发送HTTP POST
curl -X POST http://192.168.6.132:9333/dir/assign
{"fid":"5,0265e692d2","url":"127.0.0.1:9080","publicUrl":"127.0.0.1:9080","count":1}

#上传一张图片
curl -X PUT -F file=@/opt/seaweedfs/test/1.jpg http://127.0.0.1:9080/5,0265e692d2
{"size":178154,"eTag":"04d77997"}

#在浏览器打开图片
http://192.168.6.132:9080/5,0265e692d2.jpg

**预期结果**
5,0265e692d2.jpg和1.jgp内容一致

**实际结果**
5,0265e692d2.jpg打不开，说格式不支持，和原始图片对比发现多了响应字段，内容如下：
------------------------------37bd2155d34b
Content-Disposition: form-data; name="file"; filename="1.jpg"
Content-Type: image/jpeg

**Comment by chrislusf** [comment]
use POST instead of PUT

**Comment by baopin** [comment]
谢谢！
