### ISSUE TITLE
how to start filer

### ISSUE THREAD

**Issue by linqinghai** [chrislusf/seaweedfs#960]
I use this command to start filer:
 docker run -d -p 8888:8888 --name fs-filer --restart=always -v /data/weedfs/filer:/data -e WEED_IP=$smartIp --add-host=mysql:$smartIp registry.cn-hangzhou.aliyuncs.com/joywise-iedu/seaweedfs:1.33 filer -master="$smartIp:9333" -port=8888

Cause an error:
I0515 06:09:16     1 filer_server.go:103] Reading : Config File "security" Not Found in "[/ /root/.seaweedfs /etc/seaweedfs]"
I0515 06:09:16     1 filer_server.go:103] Reading /etc/seaweedfs/filer.toml: While parsing config: (14, 11): keys cannot contain new lines
I0515 06:09:16     1 filer_server.go:103] Reading : Config File "notification" Not Found in "[/ /root/.seaweedfs /etc/seaweedfs]"
I0515 06:09:16     1 leveldb_store.go:37] filer store dir: ./filerdb
I0515 06:09:16     1 file_util.go:19] Folder ./filerdb Permission: -rwxr-xr-x
I0515 06:09:16     1 configuration.go:26] Configure filer for leveldb
I0515 06:09:16     1 filer.go:131] Start Seaweed Filer 30GB 1.33 at 10.10.23.22:8888
F0515 06:09:16     1 filer.go:137] Filer listener error: listen tcp 10.10.23.22:8888: bind: cannot assign requested address
goroutine 1 [running]:
github.com/chrislusf/seaweedfs/weed/glog.stacks(0xc0005a2a00, 0xc0004180e0, 0x7c, 0xd3)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:767 +0xb1
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).output(0x262fac0, 0xc000000003, 0xc0001bd960, 0x25ab9c1, 0x8, 0x89, 0x0)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:718 +0x2d9
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).printf(0x262fac0, 0x3, 0x16b6085, 0x18, 0xc000465de8, 0x1, 0x1)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:656 +0x14e
github.com/chrislusf/seaweedfs/weed/glog.Fatalf(...)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:1149
github.com/chrislusf/seaweedfs/weed/command.(*FilerOptions).startFiler(0x262f700)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/command/filer.go:137 +0x50c
github.com/chrislusf/seaweedfs/weed/command.runFiler(0x261bd60, 0xc00003a230, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/command/filer.go:82 +0x4b
main.main()
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/weed.go:67 +0x2fe

**Comment by chrislusf** [comment]
can you please try to change this line
https://github.com/chrislusf/seaweedfs/blob/master/docker/entrypoint.sh#L32

to just `ARGS=""`

**Comment by linqinghai** [comment]
it work, thanks
