### ISSUE TITLE
how to analyze meta

### ISSUE THREAD

**Issue by linqinghai** [chrislusf/seaweedfs#961]
how to convert this field to txt?

**Comment by linqinghai** [comment]
import mysql.connector

# mysql1.py
config = {
    'host': '10.10.23.22',
    'user': 'root',
    'password': 'root',
    'port': 3306,
    'database': 'base-platform',
    'charset': 'utf8'
}
try:
    cnn = mysql.connector.connect(**config)
except mysql.connector.Error as e:
    print('connect fails!{}'.format(e))
cursor = cnn.cursor()
try:
    sql_query = 'select name, meta from filemeta ;'
    cursor.execute(sql_query)
    for name, meta in cursor:
        print (name, meta)
except mysql.connector.Error as e:
    print('query error!{}'.format(e))
finally:
    cursor.close()
    cnn.close()


(u'123123213213.jpg', bytearray(b'\x1a+\n\x0f11,547d8f024f77\x18\x97\xe2\n \xe9\xc4\xa6\xa0\xac\xc0\xb2\xcf\x15*\n"1b4e82dc"" \x10\xfa\xf9\xee\xe6\x05\x18\xb0\x030\xb8\xf1\xee\xe6\x05:\nimage/jpegB\x03000'))

**Comment by chrislusf** [comment]
It's encoded by protobuf as `Entry` defined in `filer.proto`.

**Comment by linqinghai** [comment]
got it, thanks
