### ISSUE TITLE
启动volume，一直报“Raft Server not initialized”

### ISSUE THREAD

**Issue by baopin** [chrislusf/seaweedfs#963]
**操作步骤**
vim /etc/hosts
192.168.6.132 dc1node1
192.168.6.133 dc2node1

#启动master
/opt/seaweedfs/bin/weed master -ip=192.168.6.132 -ip.bind=192.168.6.132 -port=9333 -mdir=/opt/seaweedfs/data/dc1node1 -peers=dc1node1:9333,dc2node1:9333

#启动volume
/opt/seaweedfs/bin/weed volume -dataCenter="dc1" -rack="rack1" -ip=192.168.6.132 -port=8080 -dir="/opt/seaweedfs/data/dc1node2" -mserver=192.168.6.132:9333

**预期结果**
volume能正常启动

**实际结果r**
一直会报“heartbeat error: rpc error: code = Unknown desc = Raft Server not initialized!”

**其他**
在执行第一条指令(/opt/seaweedfs/bin/weed master)，-peers后面不能写ip:port，而且至少要两个domain:port，这个是什么原因？另外想问一下有没有搭建seaweedfs分布式环境的文档？

**Comment by chrislusf** [comment]
#启动master
/opt/seaweedfs/bin/weed master -ip=192.168.6.132 -ip.bind=192.168.6.132 -port=9333 -mdir=/opt/seaweedfs/data/dc1node1

#启动volume
/opt/seaweedfs/bin/weed volume -dataCenter="dc1" -rack="rack1" -ip=192.168.6.132 -port=8080 -dir="/opt/seaweedfs/data/dc1node2" -mserver=192.168.6.132:9333


`-peers` is for other similar master servers. With only one master, you do not need to set `-peers`.

docs are all here https://github.com/chrislusf/seaweedfs/wiki

**Comment by baopin** [comment]
谢谢！
