### ISSUE TITLE
filer 运行一段时间后挂了

### ISSUE THREAD

**Issue by nqzhang** [chrislusf/seaweedfs#964]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**

**System Setup**
List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".

**Expected behavior**

**Screenshots**

**Additional context**

filer 运行一段时间后挂了

weed版本是1.28
系统centos7
错误是在使用rsync大量导入数据的时候发生的

filer 运行命令
weed -logdir=./log -v=2 filer  -master=8.8.8.8:19333 -port=18888 -ip=8.8.8.8 &

在日志里面看不到报错。。。。。。。。，只能看见这样的。。。。。
[root@gluster2 log]# tail -n 50 weed.gluster2.root.log.INFO.20190515-211048.24474 
I0516 03:00:41 24474 filer_grpc_server_rename.go:87] moving entry /site/uploads/avatar/000/19/65/.80_avatar_min.jpg.b1GHFy => /site/uploads/avatar/000/19/65/80_avatar_min.jpg
I0516 03:00:41 24474 filer_grpc_server_rename.go:87] moving entry /site/uploads/avatar/000/19/65/.80_avatar_real.jpg.54ZZog => /site/uploads/avatar/000/19/65/80_avatar_real.jpg
I0516 03:00:41 24474 filer_grpc_server_rename.go:87] moving entry /site/uploads/avatar/000/19/65/.81_avatar_max.jpg.x6ANAY => /site/uploads/avatar/000/19/65/81_avatar_max.jpg
I0516 03:00:42 24474 filer_grpc_server_rename.go:87] moving entry /site/uploads/avatar/000/19/65/.81_avatar_mid.jpg.D08NgH => /site/uploads/avatar/000/19/65/81_avatar_mid.jpg
I0516 03:00:42 24474 filer_grpc_server_rename.go:87] moving entry /site/uploads/avatar/000/19/65/.81_avatar_min.jpg.b5jNsq => /site/uploads/avatar/000/19/65/81_avatar_min.jpg
I0516 03:00:42 24474 filer_grpc_server_rename.go:87] moving entry /site/uploads/avatar/000/19/65/.81_avatar_real.jpg.rTWlba => /site/uploads/avatar/000/19/65/81_avatar_real.jpg
I0516 03:00:42 24474 filer_grpc_server_rename.go:87] moving entry /site/uploads/avatar/000/19/65/.82_avatar_max.jpg.vI6wrU => /site/uploads/avatar/000/19/65/82_avatar_max.jpg
I0516 03:00:42 24474 filer_grpc_server_rename.go:87] moving entry /site/uploads/avatar/000/19/65/.82_avatar_mid.jpg.94pFgF => /site/uploads/avatar/000/19/65/82_avatar_mid.jpg
I0516 03:00:42 24474 filer_grpc_server_rename.go:87] moving entry /site/uploads/avatar/000/19/65/.82_avatar_min.jpg.7IhU4q => /site/uploads/avatar/000/19/65/82_avatar_min.jpg
I0516 03:00:43 24474 filer_grpc_server_rename.go:87] moving entry /site/uploads/avatar/000/19/65/.82_avatar_real.jpg.P52Hmd => /site/uploads/avatar/000/19/65/82_avatar_real.jpg
I0516 03:00:43 24474 filer_grpc_server_rename.go:87] moving entry /site/uploads/avatar/000/19/65/.83_avatar_max.jpg.V1LD9Z => /site/uploads/avatar/000/19/65/83_avatar_max.jpg
I0516 03:00:43 24474 filer_grpc_server_rename.go:87] moving entry /site/uploads/avatar/000/19/65/.83_avatar_mid.jpg.nn6arN => /site/uploads/avatar/000/19/65/83_avatar_mid.jpg
I0516 03:00:43 24474 filer_deletion.go:46] timed deletion fileIds len=39
I0516 03:00:43 24474 filer_grpc_server_rename.go:87] moving entry /site/uploads/avatar/000/19/65/.83_avatar_min.jpg.R1DmdB => /site/uploads/avatar/000/19/65/83_avatar_min.jpg
I0516 03:00:43 24474 filer_grpc_server_rename.go:87] moving entry /site/uploads/avatar/000/19/65/.83_avatar_real.jpg.JewWup => /site/uploads/avatar/000/19/65/83_avatar_real.jpg
I0516 03:00:43 24474 filer_grpc_server_rename.go:87] moving entry /site/uploads/avatar/000/19/65/.84_avatar_max.jpg.hvB3ge => /site/uploads/avatar/000/19/65/84_avatar_max.jpg
I0516 03:00:43 24474 filer_grpc_server_rename.go:87] moving entry /site/uploads/avatar/000/19/65/.84_avatar_mid.jpg.Hmd7y3 => /site/uploads/avatar/000/19/65/84_avatar_mid.jpg
I0516 03:00:43 24474 filer_grpc_server_rename.go:87] moving entry /site/uploads/avatar/000/19/65/.84_avatar_min.jpg.Xpp0lT => /site/uploads/avatar/000/19/65/84_avatar_min.jpg
I0516 03:00:44 24474 filer_grpc_server_rename.go:87] moving entry /site/uploads/avatar/000/19/65/.84_avatar_real.jpg.F4P1EJ => /site/uploads/avatar/000/19/65/84_avatar_real.jpg
I0516 03:00:44 24474 filer_grpc_server_rename.go:87] moving entry /site/uploads/avatar/000/19/65/.85_avatar_max.jpg.JdUHwA => /site/uploads/avatar/000/19/65/85_avatar_max.jpg
I0516 03:00:44 24474 filer_grpc_server_rename.go:87] moving entry /site/uploads/avatar/000/19/65/.85_avatar_mid.jpg.Jf0G1r => /site/uploads/avatar/000/19/65/85_avatar_mid.jpg
I0516 03:00:44 24474 filer_grpc_server_rename.go:87] moving entry /site/uploads/avatar/000/19/65/.85_avatar_min.jpg.Fq7j7j => /site/uploads/avatar/000/19/65/85_avatar_min.jpg
I0516 03:00:44 24474 filer_grpc_server_rename.go:87] moving entry /site/uploads/avatar/000/19/65/.85_avatar_real.jpg.D4GcJc => /site/uploads/avatar/000/19/65/85_avatar_real.jpg
I0516 03:00:44 24474 filer_grpc_server_rename.go:87] moving entry /site/uploads/avatar/000/19/65/.86_avatar_max.jpg.rdTTR5 => /site/uploads/avatar/000/19/65/86_avatar_max.jpg
I0516 03:00:44 24474 filer_grpc_server_rename.go:87] moving entry /site/uploads/avatar/000/19/65/.86_avatar_mid.jpg.VFRizZ => /site/uploads/avatar/000/19/65/86_avatar_mid.jpg
I0516 03:00:45 24474 filer_grpc_server_rename.go:87] moving entry /site/uploads/avatar/000/19/65/.86_avatar_min.jpg.xtHuMT => /site/uploads/avatar/000/19/65/86_avatar_min.jpg
I0516 03:00:45 24474 filer_grpc_server_rename.go:87] moving entry /site/uploads/avatar/000/19/65/.86_avatar_real.jpg.PDrMtO => /site/uploads/avatar/000/19/65/86_avatar_real.jpg
I0516 03:00:45 24474 filer_grpc_server_rename.go:87] moving entry /site/uploads/avatar/000/19/65/.87_avatar_max.jpg.x9EZEJ => /site/uploads/avatar/000/19/65/87_avatar_max.jpg
I0516 03:00:45 24474 filer_grpc_server_rename.go:87] moving entry /site/uploads/avatar/000/19/65/.87_avatar_mid.jpg.361SlF => /site/uploads/avatar/000/19/65/87_avatar_mid.jpg
I0516 03:00:45 24474 filer_grpc_server_rename.go:87] moving entry /site/uploads/avatar/000/19/65/.87_avatar_min.jpg.NsNMwB => /site/uploads/avatar/000/19/65/87_avatar_min.jpg
I0516 03:00:45 24474 filer_grpc_server_rename.go:87] moving entry /site/uploads/avatar/000/19/65/.87_avatar_real.jpg.PHRAcy => /site/uploads/avatar/000/19/65/87_avatar_real.jpg
I0516 03:00:45 24474 filer_grpc_server_rename.go:87] moving entry /site/uploads/avatar/000/19/65/.88_avatar_max.jpg.T8fjlv => /site/uploads/avatar/000/19/65/88_avatar_max.jpg
I0516 03:00:45 24474 filer_grpc_server_rename.go:87] moving entry /site/uploads/avatar/000/19/65/.88_avatar_mid.jpg.1RJGWs => /site/uploads/avatar/000/19/65/88_avatar_mid.jpg
I0516 03:00:46 24474 filer_grpc_server_rename.go:87] moving entry /site/uploads/avatar/000/19/65/.88_avatar_min.jpg.zswh2q => /site/uploads/avatar/000/19/65/88_avatar_min.jpg
I0516 03:00:46 24474 filer_grpc_server_rename.go:87] moving entry /site/uploads/avatar/000/19/65/.88_avatar_real.jpg.HnBBBp => /site/uploads/avatar/000/19/65/88_avatar_real.jpg
I0516 03:00:46 24474 filer_grpc_server_rename.go:87] moving entry /site/uploads/avatar/000/19/65/.89_avatar_max.jpg.9GeBFo => /site/uploads/avatar/000/19/65/89_avatar_max.jpg
I0516 03:00:46 24474 filer_grpc_server_rename.go:87] moving entry /site/uploads/avatar/000/19/65/.89_avatar_mid.jpg.jhMwfo => /site/uploads/avatar/000/19/65/89_avatar_mid.jpg
I0516 03:00:46 24474 filer_grpc_server_rename.go:87] moving entry /site/uploads/avatar/000/19/65/.89_avatar_min.jpg.xEl5ko => /site/uploads/avatar/000/19/65/89_avatar_min.jpg
I0516 03:00:46 24474 filer_grpc_server_rename.go:87] moving entry /site/uploads/avatar/000/19/65/.89_avatar_real.jpg.RtTfQo => /site/uploads/avatar/000/19/65/89_avatar_real.jpg
I0516 03:00:46 24474 filer_grpc_server_rename.go:87] moving entry /site/uploads/avatar/000/19/65/.90_avatar_max.jpg.Fl69Op => /site/uploads/avatar/000/19/65/90_avatar_max.jpg
I0516 03:00:46 24474 filer_grpc_server_rename.go:87] moving entry /site/uploads/avatar/000/19/65/.90_avatar_mid.jpg.DPkWjr => /site/uploads/avatar/000/19/65/90_avatar_mid.jpg
I0516 03:00:47 24474 filer_grpc_server_rename.go:87] moving entry /site/uploads/avatar/000/19/65/.90_avatar_min.jpg.p70ult => /site/uploads/avatar/000/19/65/90_avatar_min.jpg
I0516 03:00:47 24474 filer_grpc_server_rename.go:87] moving entry /site/uploads/avatar/000/19/65/.90_avatar_real.jpg.j0x2Rv => /site/uploads/avatar/000/19/65/90_avatar_real.jpg
I0516 03:00:47 24474 filer_grpc_server_rename.go:87] moving entry /site/uploads/avatar/000/19/65/.91_avatar_max.jpg.5fkoTy => /site/uploads/avatar/000/19/65/91_avatar_max.jpg
I0516 03:00:47 24474 filer_grpc_server_rename.go:87] moving entry /site/uploads/avatar/000/19/65/.91_avatar_mid.jpg.DeAmoC => /site/uploads/avatar/000/19/65/91_avatar_mid.jpg
I0516 03:00:47 24474 filer_grpc_server_rename.go:87] moving entry /site/uploads/avatar/000/19/65/.91_avatar_min.jpg.NuekqG => /site/uploads/avatar/000/19/65/91_avatar_min.jpg
I0516 03:00:47 24474 filer_grpc_server_rename.go:87] moving entry /site/uploads/avatar/000/19/65/.91_avatar_real.jpg.V6HiYK => /site/uploads/avatar/000/19/65/91_avatar_real.jpg
I0516 03:00:47 24474 filer_grpc_server_rename.go:87] moving entry /site/uploads/avatar/000/19/65/.92_avatar_max.jpg.ZoPm1P => /site/uploads/avatar/000/19/65/92_avatar_max.jpg
I0516 03:00:47 24474 filer_grpc_server_rename.go:87] moving entry /site/uploads/avatar/000/19/65/.92_avatar_mid.jpg.JQMPyV => /site/uploads/avatar/000/19/65/92_avatar_mid.jpg
I0516 03:00:48 24474 filer_grpc_server_rename.go:87] moving entry /site/uploads/avatar/000/19/65/.92_avatar_min.jpg.JXWgz1 => /site/uploads/avatar/000/19/65/92_avatar_min.jpg

rsync的报错
rsync: recv_generator: mkdir "/web/site/uploads/avatar/000/29" failed: No such file or directory (2)
*** Skipping any contents from this failed directory ***
site/uploads/avatar/000/30/
rsync: recv_generator: mkdir "/web/site/uploads/avatar/000/30" failed: No such file or directory (2)
*** Skipping any contents from this failed directory ***
site/uploads/avatar/000/31/
rsync: recv_generator: mkdir "/web/site/uploads/avatar/000/31" failed: No such file or directory (2)
*** Skipping any contents from this failed directory ***
site/uploads/avatar/000/32/
rsync: recv_generator: mkdir "/web/site/uploads/avatar/000/32" failed: No such file or directory (2)
*** Skipping any contents from this failed directory ***
site/uploads/avatar/003/
rsync: recv_generator: mkdir "/web/site/uploads/avatar/003" failed: No such file or directory (2)
*** Skipping any contents from this failed directory ***

**Comment by chrislusf** [comment]
need more details. what's the filer store, used `weed mount` or not, crash logs, what's the rsync command.

to move data, you can use `weed filer.copy` command

**Comment by nqzhang** [comment]
file store 是indexdb默认的
挂载命令
weed mount -filer=8.8.8.8:18888  -dir=/web -filer.path=/ -collection=web &
使用weed copy复制
weed filer.copy -master=8.8.8.8:19333  -collection=web /smb192820/* http://127.0.0.1:18888/

weed copy的错误
copy file error: upload data Python.h to http://127.0.0.1:18888/mil.xuehua.us/include/python3.6m/Python.h: update fh: rpc error: code = Unknown desc = /mil.xuehua.us/include/python3.6m is a file

copy file error: upload data Python-ast.h to http://127.0.0.1:18888/web/include/python3.6m/Python-ast.h: update fh: rpc error: code = Unknown desc = /web/include/python3.6m is a file

uploaded accu.h to http://148.251.47.67:18085/44,02bd946da281a6f0
copied accu.h => http://127.0.0.1:18888/web/include/python3.6m/accu.h
copy file error: upload data accu.h to http://127.0.0.1:18888/web/include/python3.6m/accu.h: update fh: rpc error: code = Unknown desc = /web/include/python3.6m is a file


filer日志
tail -n  50 weed.gluster2.root.log.INFO.20190516-111030.16969 
I0516 11:46:13 16969 filer_deletion.go:40] deleting fileIds len=4096
I0516 11:46:15 16969 filer_deletion.go:46] timed deletion fileIds len=1627
I0516 11:46:19 16969 filer_deletion.go:40] deleting fileIds len=4096
I0516 11:46:20 16969 filer_deletion.go:46] timed deletion fileIds len=1331
I0516 11:46:23 16969 filer_deletion.go:40] deleting fileIds len=4096
I0516 11:46:25 16969 filer_deletion.go:46] timed deletion fileIds len=1378
I0516 11:46:28 16969 filer_deletion.go:40] deleting fileIds len=4096
I0516 11:46:30 16969 filer_deletion.go:46] timed deletion fileIds len=1702
I0516 11:46:33 16969 filer_deletion.go:40] deleting fileIds len=4096
I0516 11:46:35 16969 filer_deletion.go:46] timed deletion fileIds len=1498
I0516 11:46:38 16969 filer_deletion.go:40] deleting fileIds len=4096
I0516 11:46:40 16969 filer_deletion.go:46] timed deletion fileIds len=1636
I0516 11:46:43 16969 filer_deletion.go:40] deleting fileIds len=4096
I0516 11:46:45 16969 filer_deletion.go:46] timed deletion fileIds len=1870
I0516 11:46:48 16969 filer_deletion.go:40] deleting fileIds len=4096
I0516 11:46:50 16969 filer_deletion.go:46] timed deletion fileIds len=1777
I0516 11:46:53 16969 filer_deletion.go:40] deleting fileIds len=4096
I0516 11:46:55 16969 filer_deletion.go:46] timed deletion fileIds len=1731
I0516 11:46:58 16969 filer_deletion.go:40] deleting fileIds len=4096
I0516 11:47:00 16969 filer_deletion.go:46] timed deletion fileIds len=1742
I0516 11:47:03 16969 filer_deletion.go:40] deleting fileIds len=4096
I0516 11:47:05 16969 filer_deletion.go:46] timed deletion fileIds len=1293
I0516 11:47:08 16969 filer_deletion.go:40] deleting fileIds len=4096
I0516 11:47:10 16969 filer_deletion.go:46] timed deletion fileIds len=1777
I0516 11:47:13 16969 filer_deletion.go:40] deleting fileIds len=4096
I0516 11:47:17 16969 filer_deletion.go:40] deleting fileIds len=4096
I0516 11:47:20 16969 filer_deletion.go:46] timed deletion fileIds len=3617
I0516 11:47:23 16969 filer_deletion.go:40] deleting fileIds len=4096
I0516 11:47:25 16969 filer_deletion.go:46] timed deletion fileIds len=1831
I0516 11:47:28 16969 filer_deletion.go:40] deleting fileIds len=4096
I0516 11:47:30 16969 filer_deletion.go:46] timed deletion fileIds len=1628
I0516 11:47:33 16969 filer_deletion.go:40] deleting fileIds len=4096
I0516 11:47:35 16969 filer_deletion.go:46] timed deletion fileIds len=1646
I0516 11:47:38 16969 filer_deletion.go:40] deleting fileIds len=4096
I0516 11:47:40 16969 filer_deletion.go:46] timed deletion fileIds len=1798
I0516 11:47:43 16969 filer_deletion.go:40] deleting fileIds len=4096
I0516 11:47:45 16969 filer_deletion.go:46] timed deletion fileIds len=1521
I0516 11:47:48 16969 filer_deletion.go:40] deleting fileIds len=4096
I0516 11:47:50 16969 filer_deletion.go:46] timed deletion fileIds len=1649
I0516 11:47:55 16969 filer_deletion.go:46] timed deletion fileIds len=3938
I0516 11:48:00 16969 filer_deletion.go:46] timed deletion fileIds len=2842
I0516 11:48:05 16969 filer_deletion.go:46] timed deletion fileIds len=2425
I0516 11:48:10 16969 filer_deletion.go:46] timed deletion fileIds len=2577
I0516 11:48:15 16969 filer_deletion.go:46] timed deletion fileIds len=2358
I0516 11:48:20 16969 filer_deletion.go:46] timed deletion fileIds len=2714
I0516 11:48:25 16969 filer_deletion.go:46] timed deletion fileIds len=2664
I0516 11:48:30 16969 filer_deletion.go:46] timed deletion fileIds len=2601
I0516 11:48:35 16969 filer_deletion.go:46] timed deletion fileIds len=2758
I0516 11:48:40 16969 filer_deletion.go:46] timed deletion fileIds len=3496
I0516 11:48:45 16969 filer_deletion.go:46] timed deletion fileIds len=1570

现在是filer进程直接没有了
![QQ截图20190516134357](https://user-images.githubusercontent.com/12559853/57829264-f9de8400-77e0-11e9-8082-65bbb5936fe7.png)

**Comment by nqzhang** [comment]
复制的时候iowait是挺高的 在20%以上 这样会导致filer进程退出吗...

**Comment by chrislusf** [comment]
filer process has pid 16969. stil there.

**Comment by chrislusf** [comment]
check what's special about file /web/include/python3.6m

**Comment by nqzhang** [comment]
是的 的确是一个软链接
![image](https://user-images.githubusercontent.com/12559853/57832104-66f61780-77e9-11e9-9ea2-a8bd7940d95d.png)

**Comment by nqzhang** [comment]
我可能看错了 就是web挂载是出问题了的
但是可能看的时候以为filer进程不在了..... 没看清
我现在把所有版本都升级到1.33 并且把filer清空了 重新在用weed copy拷数据
过段时间如果有问题的话看看能不能提供更加详细的错误日志........
