### ISSUE TITLE
replicate 001，两个备份Volume 大小不一致，该如何修复

### ISSUE THREAD

**Issue by tjx222** [chrislusf/seaweedfs#965]
volume 信息如下
-volume-|  id | --name ---| ---------size --------   |  files 
volume1 |  9  | tal_storage  | 31510382928 Bytes | 32215  
volume2 |  9  | tal_storage  | 29507514235 Bytes  | 5690

同一个volume id下文件数量不一致， 该如何修复呢？

另外，文件在volume2中不存在，下载时master 依然返回了volume2 的地址，是否是一个bug.

**Comment by chrislusf** [comment]
> volume 信息如下
-volume-| id | --name ---| ---------size -------- | files
volume1 | 9 | tal_storage | 31510382928 Bytes | 32215
volume2 | 9 | tal_storage | 29507514235 Bytes | 5690

how did you get these info? can you use this: `echo "volume.list" | weed shell`

**Comment by tjx222** [comment]
是直接访问 http://localhost:9332/ui/index.html 查看的，
版本是0.99 ， weed shell 还不支持这些命令。

**Comment by chrislusf** [comment]
please take a screenshot

**Comment by tjx222** [comment]
![image](https://github.com/tjx222/tmser/blob/master/1.png?raw=true)
![image](https://github.com/tjx222/tmser/blob/master/2.png?raw=true)

**Comment by chrislusf** [comment]
In your case, just copy the larger 9.dat and 9.idx files to overwrite the smaller ones.

**Comment by tjx222** [comment]
不是只有这一个的，也不知道是否后面还会产生这种不一致情况，weed shell 是否有命令可以批量修复，或者其他批量处理方法吗。

**Comment by chrislusf** [comment]
your volume 9 replicas have 5690 vs 32215 files respectively, but size are close. Something wrong. 

How do you write files? what kind of file? have many updates?  Any network problem? Any thing special?

**Comment by tjx222** [comment]
我已经把其他所有volume 比较了下，只有这一个volume有问题。
和其他卷一样，这些文件是批量上传的，其中volume 9 里面存储的是文本文件大小不超过20k.
批量上传api , 如下。
@RequestLine("POST /{fid}")
@Headers("Content-Type: multipart/form-data")

ps:
   已经将volume 9 同步了，重启后已经可以调用了。谢谢。
