### ISSUE TITLE
weed filer.copy big file success, but the mounted dir returns "ls: reading directory .: Input/output error" when ls the copied big file

### ISSUE THREAD

**Issue by ledao** [chrislusf/seaweedfs#966]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs
Hi, we got a problem when filer.copy super big file to filer. 

**Describe the bug**
1. weed filer.copy big_300G_file.tgz http::/localhost:8888/big_dir/, this step is ok.
2. go to the local mounted dir big_dir_local ( /big_dir in  sweed), when type "ls", i/o error occors.

**System Setup**
List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
nohup weed -v=2 master -mdir=$master_mdir -port=$master_port -ip='$master_ip' -defaultReplication='000' > /dev/null 2>&1 &
nohup weed -logdir=$logdir  volume -dir=$volume_dir -ip='$volume_ip' -port=$volume_port -max=$volume_max_per_machine -mserver='$master_ip:$master_port' -index=leveldb -dataCenter='asr_dc' -rack='rack1' > /dev/null 2>&1 &
nohup weed  filer -port=$filer_port -ip='localhost' -master='$master_ip:$master_port' -collection='$collection' -dataCenter='$data_center'  -defaultReplicaPlacement='000'> /dev/null 2>&1 &
nohup weed  mount -filer='localhost:$filer_port' -dir=$mpoint -filer.path=/$filer_path  -collection='$collection' -dataCenter='$data_center' > /dev/null 2>&1 &

notes:
1. we use mariadb 10.1.9 to store the meta data.
2. we have 8 computers, each computer have 40 volumes.
3. weed version 1.33.

**Expected behavior**
as usual, ls the mounted dir could display the file list.

**Screenshots**
weed.copy success.
![image](https://user-images.githubusercontent.com/6221224/57897450-5eecb500-7887-11e9-8221-eec2d55ae7ae.png)
ls error:
![image](https://user-images.githubusercontent.com/6221224/57897653-6fe9f600-7888-11e9-8b7c-960a255bccf7.png)

**Additional context**

**Comment by chrislusf** [comment]
what's your mariadb database schema? can you export your mariadb data to reproduce this?

**Comment by ledao** [comment]
| Table    | Create Table                                                                                                                                                                                                                                                                                                                                       |
+----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| filemeta | CREATE TABLE `filemeta` (
  `dirhash` bigint(20) NOT NULL COMMENT 'first 64 bits of MD5 hash value of directory field',
  `name` varchar(1000) NOT NULL,
  `directory` varchar(4096) DEFAULT NULL COMMENT 'full path to parent directory',
  `meta` blob,
  PRIMARY KEY (`dirhash`,`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC |

**Comment by chrislusf** [comment]
schema seems fine. could you export data for this table?

**Comment by chrislusf** [comment]
Or you can try to run `echo "fs.meta.save" | weed shell ` and share the generated meta data file.

**Comment by chrislusf** [comment]
Is there any execution timeout?

**Comment by ledao** [comment]
there is none exception.
i download some filemeta form db, this may help.

**Comment by ledao** [comment]
filemeta.zip
http://note.youdao.com/noteshare?id=863bc3194110f76dfeef575035ed7626

**Comment by chrislusf** [comment]
It seems either the shared file is wrongly exported, or the data in the database is truncated somehow.

```
mysql> select dirhash, name, directory, length(meta) from filemeta;
+----------------------+-------------------------------------------------------------+-----------------------------------------------+--------------+
| dirhash              | name                                                        | directory                                     | length(meta) |
+----------------------+-------------------------------------------------------------+-----------------------------------------------+--------------+
| -2856740567714572279 | 3125.log                                                    | /buy_data/数据堂-3125普通话语音数据           |           94 |
| -2856740567714572279 | 3125小时语音助手普通话实网采集语音数据.zip                  | /buy_data/数据堂-3125普通话语音数据           |        65535 |
| -2856740567714572279 | format_MDTtang3125.py                                       | /buy_data/数据堂-3125普通话语音数据           |           94 |
| -2856740567714572279 | uzip.log                                                    | /buy_data/数据堂-3125普通话语音数据           |           94 |
+----------------------+-------------------------------------------------------------+-----------------------------------------------+--------------+
4 rows in set (0.00 sec)
```

**Comment by ledao** [comment]
MariaDB [test]> CREATE TABLE IF NOT EXISTS filemeta (
    ->   dirhash     BIGINT        COMMENT 'first 64 bits of MD5 hash value of directory field',
    ->   name        VARCHAR(1000) COMMENT 'directory or file name',
    ->   directory   VARCHAR(4096) COMMENT 'full path to parent directory',
    ->   meta        BLOB,
    ->   PRIMARY KEY (dirhash, name)
    -> ) DEFAULT CHARSET=utf8;
ERROR 1709 (HY000): Index column size too large. The maximum column size is 767 bytes.

---------------------------------------------------

is this problem?

**Comment by chrislusf** [comment]
please show the sql result in your system:
```
select dirhash, name, directory, length(meta) 
from filemeta 
where dirhash=-2856740567714572279
```

**Comment by chrislusf** [comment]
I got it. BLOB is only 64KB. Need to use LONGBLOB or MEDIUMBLOB for meta field.

**Comment by chrislusf** [comment]
Added a fix for the mysql DDL.

Sorry for your data, besides changing the meta column data type, you would need to re-upload the file.

**Comment by ledao** [comment]
all of my data? the small file works well?

**Comment by chrislusf** [comment]
Only files that meta content is cut off.
```
select dirhash, name, directory
from filemeta 
where length(meta)=65535
```

**Comment by ledao** [comment]
ok, thank you for your help. 
sweedfs is great.
