### ISSUE TITLE
Filer don't honor collection option

### ISSUE THREAD

**Issue by bash99** [chrislusf/seaweedfs#968]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**
start filer with a named collection, but it won't use the name

**System Setup**
```
weed server -filer -filer.collection=xs3
```

**Expected behavior**
```
weed filer.copy -master=localhost:9333 nohup.out http://localhost:8888/tmp/
curl -s localhost:9333/dir/status\?pretty=yes | grep collection
```
I think I'll got a xs3 collection, but the default collection "" showed
```
root@pve1:~# curl -s localhost:9333/dir/status\?pretty=yes | grep collection
        "collection": "",
```

BTW, if add collection in filer.copy, it works

**Comment by chrislusf** [comment]
This is expected. 

`weed filer.copy` does not go through filer when uploading the actual data file. So  `weed filer.copy` collection is not managed by filer.

**Comment by chrislusf** [comment]
On second thought, "filer.copy" should check filer configurations before copying the data. Leaving this open until fixed.
