### ISSUE TITLE
请问seaweedfs可以直接查看文件的内容吗?还有就是用java客户端上传文件时可以分配目录吗?

### ISSUE THREAD

**Issue by ICannerxy** [chrislusf/seaweedfs#970]
官方wiki已经翻过一遍了,貌似没有找到合适的方法,java客户端库的源码也看过一遍,也是没有合适的方法..如果有知道该怎么处理的,请告知我,谢谢.

**Comment by chrislusf** [comment]
use http to see the file content.

not sure what java client you use. but most likely it only upload to master+volume server. you can upload directly to filer, with basic http POST.
