### ISSUE TITLE
 when stress testing, the filer core down at delete_content.go

### ISSUE THREAD

**Issue by stlpmo-jn** [chrislusf/seaweedfs#972]
when stress testing, the filer core down

core dump :
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc0 pc=0x467035]

goroutine 5039907 [running]:
panic(0x1203a00, 0x22083c0)
        /usr/local/seaweedfs/go/src/runtime/panic.go:556 +0x2cb fp=0xc00146fdc0 sp=0xc00146fd30 pc=0x43704b
runtime.panicmem()
        /usr/local/seaweedfs/go/src/runtime/panic.go:82 +0x5e fp=0xc00146fde0 sp=0xc00146fdc0 pc=0x43608e
runtime.sigpanic()
        /usr/local/seaweedfs/go/src/runtime/signal_unix.go:390 +0x182 fp=0xc00146fe30 sp=0xc00146fde0 pc=0x44d032
runtime.memmove(0xc00012ca00, 0x0, 0x140)
        /usr/local/seaweedfs/go/src/runtime/memmove_amd64.s:329 +0x3c5 fp=0xc00146fe38 sp=0xc00146fe30 pc=0x467035
runtime.growslice(0x134ad40, 0x0, 0x28, 0x28, 0x50, 0x28, 0x2c, 0xc00004e780)
        /usr/local/seaweedfs/go/src/runtime/slice.go:206 +0x1f1 fp=0xc00146fea0 sp=0xc00146fe38 pc=0x44e5c1
github.com/chrislusf/seaweedfs/weed/operation.DeleteFilesWithLookupVolumeId.func1(0xc000a4a220, 0x15c5ae0, 0xc00000e180, 0xc0014dec70, 0xc0014d3a00, 0xc0002103a0, 0x13, 0xc000ff3600, 0x28, 0x2c)
        /home/seaweedfs/gopath/src/github.com/chrislusf/seaweedfs/weed/operation/delete_content.go:98 +0x34b fp=0xc00146ff90 sp=0xc00146fea0 pc=0x99bc6b
runtime.goexit()
        /usr/local/seaweedfs/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc00146ff98 sp=0xc00146ff90 pc=0x465b91
created by github.com/chrislusf/seaweedfs/weed/operation.DeleteFilesWithLookupVolumeId
        /home/seaweedfs/gopath/src/github.com/chrislusf/seaweedfs/weed/operation/delete_content.go:92 +0xa78

mybe the slice.append() is not thread-safe, in other word it can't support concurrent,

the forllowing code mybe resolve it: (function : DeleteFilesWithLookupVolumeId())
```
	var wg sync.WaitGroup
	resultChan := make(chan []*volume_server_pb.DeleteResult, len(server_to_fileIds))
	for server, fidList := range server_to_fileIds {
		wg.Add(1)
		go func(server string, fidList []string) {
			defer wg.Done()
			glog.V(6).Infof("server:%s file-list:%s", server, fidList)
			if deleteResults, deleteErr := DeleteFilesAtOneVolumeServer(server, grpcDialOption, fidList); deleteErr != nil {
				err = deleteErr
			} else {
				resultChan <- deleteResults
			}
		}(server, fidList)
	}

	go func() {
		wg.Wait()
		close(resultChan)
	}()

	for result := range resultChan {
		ret = append(ret, result...)
	}
```

**Comment by stlpmo-jn** [comment]
frequency : occasional

**Comment by chrislusf** [comment]
Thanks! Could you please help to create a PR and test the fix?

**Comment by stlpmo-jn** [comment]
okey, after stress testing passed, i will make a PR
