### ISSUE TITLE
some question about benchmark

### ISSUE THREAD

**Issue by ICannerxy** [chrislusf/seaweedfs#973]
作者老哥,又来找您解惑了,关于性能测试的问题.我搭了三台服务器做性能测试,
我在主节点执行的命令是'./weed benchmark -c 10 -n 10000 -collection 10000_benchmark2 -master 192.168.1.35:9333 -size 307200 -list ./weedfs/benchmark_10000.txt'. 
下面是测试结果.
------------ Writing Benchmark ----------
Completed 977 of 10000 requests, 9.8% 976.9/s 286.2MB/s

Concurrency Level:      10
Time taken for tests:   9.340 seconds
Complete requests:      10000
Failed requests:        0
Total transferred:      3072313634 bytes
Requests per second:    1070.62 [#/sec]
Transfer rate:          321218.23 [Kbytes/sec]

Connection Times (ms)
              min      avg        max      std
Total:        1.0      9.3       147.0      11.7

Percentage of the requests served within a certain time (ms)
   50%      3.0 ms
   66%      5.2 ms
   75%     16.4 ms
   80%     19.9 ms
   90%     27.9 ms
   95%     33.1 ms
   98%     37.2 ms
   99%     39.3 ms
  100%    147.0 ms
------------ Randomly Reading Benchmark ----------
Concurrency Level:      10
Time taken for tests:   7.750 seconds
Complete requests:      10000
Failed requests:        0
Total transferred:      3072313957 bytes
Requests per second:    1290.30 [#/sec]
Transfer rate:          387128.98 [Kbytes/sec]

Connection Times (ms)
              min      avg        max      std
Total:        0.3      7.6       123.2      10.2

Percentage of the requests served within a certain time (ms)
   50%      1.7 ms
   66%      3.2 ms
   75%     17.6 ms
   80%     20.8 ms
   90%     24.4 ms
   95%     26.8 ms
   98%     29.2 ms
   99%     30.3 ms
  100%    123.2 ms
========================================
但是我用java代码测试性能,也是开了10个线程上传10000个300KB文件,测试每秒可以写入588个文件..执行您给的测试接口时每秒可以达到1290个请求.
接下来我用单机做了测试,也是执行了同样的命令'./weed benchmark -c 10 -n 10000 -collection 10000_benchmark2 -master 192.168.1.35:9333 -size 307200 -list ./weedfs/benchmark_10000.txt'
执行后的结果令我吃惊.下面是执行结果.
------------ Writing Benchmark ----------
Completed 1614 of 10000 requests, 16.1% 1613.9/s 472.9MB/s
............

Concurrency Level:      10
Time taken for tests:   6.116 seconds
Complete requests:      10000
Failed requests:        0
Total transferred:      3072316431 bytes
Requests per second:    1635.14 [#/sec]
Transfer rate:          490593.43 [Kbytes/sec]

Connection Times (ms)
              min      avg        max      std
Total:        1.2      6.1       122.4      7.0

Percentage of the requests served within a certain time (ms)
   50%      4.6 ms
   66%      5.5 ms
   75%      6.1 ms
   80%      6.6 ms
   90%      8.2 ms
   95%     10.8 ms
   98%     37.6 ms
   99%     46.0 ms
  100%    122.4 ms

------------ Randomly Reading Benchmark ----------
Completed 1201 of 10000 requests, 12.0% 1200.8/s 351.8MB/s
.........

Concurrency Level:      10
Time taken for tests:   6.214 seconds
Complete requests:      10000
Failed requests:        0
Total transferred:      3072318099 bytes
Requests per second:    1609.37 [#/sec]
Transfer rate:          482862.08 [Kbytes/sec]

Connection Times (ms)
              min      avg        max      std
Total:        0.3      6.1       144.9      6.2

Percentage of the requests served within a certain time (ms)
   50%      6.8 ms
   66%      7.7 ms
   75%      8.2 ms
   80%      8.4 ms
   90%      8.9 ms
   95%      9.5 ms
   98%     10.8 ms
   99%     13.4 ms
  100%    144.9 ms
=======================================
结论是单机的速读写度竟然要远远大于集群的速度,同样的,我用java代码也测试了一下,也是上传10000个300KB文件,总共花费时间是26.6秒,算下来每秒上传375个文件(前面集群是每秒上传588个文件).
请问下为什么会造成这种现象.

**Comment by chrislusf** [comment]
seems the bottleneck in your case is the network.

**Comment by ICannerxy** [comment]
我用的是本地网络呀..从java客户端上来说,3台seaweedfs,每秒写入588个300KB文件,单台seaweedfs,每秒写入375文件.这看上去似乎是合理的.但是我用./weed benchmark测试,结果就超出预期了.不应该是集群的读写更快吗?

**Comment by chrislusf** [comment]
If you have unlimited network and unlimted CPU/memory, yes, the cluster will be faster.

**Comment by ICannerxy** [comment]
我可以这样理解吗,在有限的网络和cpu/内存里,单机的读写更快...那集群的意义在哪里呢..请问您有粉丝群吗,我想进去学习一下.

**Comment by chrislusf** [comment]
my wechat id: chrislusf

**Comment by LuuucasChen** [comment]
> 我可以这样理解吗,在有限的网络和cpu/内存里,单机的读写更快...那集群的意义在哪里呢..请问您有粉丝群吗,我想进去学习一下.

您好，请问如何在java客户端里测试集群，可以交流一下吗
