### ISSUE TITLE
是否能添加WINDOW下的MOUNT?

### ISSUE THREAD

**Issue by 9527code** [chrislusf/seaweedfs#975]
找到一些可以用的类库
https://godoc.org/github.com/keybase/client/go/kbfs/dokan
https://github.com/dokan-dev/dokany/wiki/FUSE

**Comment by chrislusf** [comment]
unlikely due to the high maintenance cost

**Comment by 9527code** [comment]
使用WebDAV方式挂载一个盘符,读写文件跟用http api 的方式哪个高效一点?
或者说WebDAV本质上还是调用的HTTP API "http://localhost:8888/"

**Comment by 9527code** [comment]
@chrislusf

**Comment by chrislusf** [comment]
webdav is not stable.

webdav depends on http api.
