### ISSUE TITLE
weed mount不能读取已有文件

### ISSUE THREAD

**Issue by greatle** [chrislusf/seaweedfs#978]
linux版本3.10.0-327.el7.x86_64，CentOS Linux release 7.2.1511；seaweedfs版本1.35; fuse版本fuse-2.9.2-11.el7.x86_64
1. 运行master、volume、filer
2. 通过filer上传一些文件
3. 运行weed mount，在mount的文件夹中可以看到第2步上传的文件，但不能读取文件内容，也不能chmod修改权限，都是报“Permission denied”错误；如果在操作系统中拷贝、移动文件到mount目录中，则可以读取等操作

**Comment by chrislusf** [comment]
Try to sudo chmod

**Comment by greatle** [comment]
用sudo也不行。
mount的时候是root用户，读取也是root用户。只要是直接通过filer方式上传的文件都不能读取，只能看到文件名

**Comment by chrislusf** [comment]
I can not reproduce this.

**Comment by chrislusf** [comment]
closing this unless reproducing steps are added.

**Comment by artificerpi** [comment]
@chrislusf Any way to mount volume with umask? As rexray/s3fs docker plugin supports mount with umark 000, so files can be modified by non-root user. While I am using [docker-plugin_seaweedfs](https://github.com/katharostech/docker-plugin_seaweedfs/issues/1), I don't find an command option to do this.

**Comment by chrislusf** [comment]
@artificerpi added
