### ISSUE TITLE
provide a method to set volume ip dynamically.

### ISSUE THREAD

**Issue by di3663** [chrislusf/seaweedfs#979]
Hi, i'm testing seaweedfs to find out whether it's better than mfs what i used currently because tring to replace all servers with golang.

**Describe the bug**
volume server will not update its ip when reconnect.

**temporary method**
+126 weed/command/volume.go

+47 weed/server/volume_grpc_client_to_master.go

after set ip from those position, master seems get ip correctly.

**why i need this**
mfs master server will just take chunk server's connect ip, so do not even need to set mfs chunk server's ip when start mfs chunk server.  But using weed, i need to set weed volume's ip.

if volume servers are connected to public master server, master server need to know public ips of volume servers or upload will fail.

**Comment by chrislusf** [comment]
not clear the line numbers are based on which version of the code.

**Comment by di3663** [comment]
master

````
vi +126 weed/command/volume.go
	*v.ip = util.GetIp()

vi +47 weed/server/volume_grpc_client_to_master.go
				vs.store.Ip = util.GetIp()
```

**Comment by chrislusf** [comment]
we just need a default value for the volume server ip address. What's your implementation of `util.GetIp()`?

**Comment by di3663** [comment]
Get public ip itself.Beacuse volume server has a dynamically public ip., when ip changes, volume server will reconnect master and send real public ip.

**Comment by di3663** [comment]
as i said, it's not a good solution, but works. 
weed master server does not use volume connect ip, after reconnection, upload will fail if volume has not sent it's public ip.

**Comment by chrislusf** [comment]
send a PR please.

**Comment by di3663** [comment]
Maybe let master use client connect ip then, GetIp() used a private server api.
