### ISSUE TITLE
The service could not start properly

### ISSUE THREAD

**Issue by ooocici** [chrislusf/seaweedfs#980]
![image](https://user-images.githubusercontent.com/15642865/59575005-25a89e80-90ec-11e9-880b-dfcc50a8f03e.png)

Service cannot start due to power failure in machine room
Loading leveldb /data1/*. LDB error: resource permanently unavailable

How to fix it..

help me ..pls.  ╭(╯^╰)╮

**Comment by chrislusf** [comment]
remove the /data1/xxx.ldb folders and try to start again.

**Comment by ooocici** [comment]
I tried, it doesn't solve the problem.

**Comment by ooocici** [comment]
Remove invalid files below 10KB, and the service can start normally o(╥﹏╥)o
