### ISSUE TITLE
when the space can free

### ISSUE THREAD

**Issue by xiaoweihong** [chrislusf/seaweedfs#981]
I can upload image by seaweedfs api,can delete image by api,but the disk space can't free.I also use http://localhost:9333/vol/vacuum ,but don't work.

**Comment by chrislusf** [comment]
What's the command you used?

**Comment by xiaoweihong** [comment]
curl -X DELETE localhost:9301/3,1bf1939d2cb05e ,like this

**Comment by chrislusf** [comment]
add garbage thresh hold when http://localhost:9333/vol/vacuum
