### ISSUE TITLE
Issue on deleting file and volume size keeps on increasing.

### ISSUE THREAD

**Issue by anikumar1991** [chrislusf/seaweedfs#982]
Storage Space Issue.

Whenever delete a file from seaweed volume and it keeps on increasing the disk size(1.dat). How to fix this issue?
 
1.After Uploading file to (1.dat) Volume Size is  569570632
2.After deleting the same file from (1.dat) Volume Size  is 569570656

**Comment by chrislusf** [comment]
This is by design.

see https://github.com/chrislusf/seaweedfs/wiki/Master-Server-API#force-garbage-collection
