### ISSUE TITLE
文件存储会丢失

### ISSUE THREAD

**Issue by jenner-luo** [chrislusf/seaweedfs#984]
我上传了一个zip文件，过了两个多月，我去下载的时候发现下载到一个空数据，也没有报错，请问是不是数据被当成垃圾回收了，我的TTL设置的是2年，请问是不是不支持这类文件的存储，其它类型的文件数据没有出现过这个问题

**Comment by chrislusf** [comment]
zip has no difference with other files. maybe some error when uploading the zip file. Need to have some reproducible steps.

**Comment by jenner-luo** [comment]
问题是：zip文件刚上传的时候是完好的，下载是正常的。但过了一段时间(几天或者2月)之后再下截，文件变成空文件，请求不报错只返回空对象。

**Comment by chrislusf** [comment]
不大可能。没有任何对zip的特殊处理。有没有发生对这个文件的删除操作？

**Comment by linqinghai** [comment]
我也遇到过，redis中都还有原来保存的信息，只是文件就是空的

**Comment by chrislusf** [comment]
This could be related to https://github.com/chrislusf/seaweedfs/issues/986
