### ISSUE TITLE
volume和shell连接master出问题

### ISSUE THREAD

**Issue by kakazuo** [chrislusf/seaweedfs#989]
![image](https://user-images.githubusercontent.com/5010445/59973061-87757680-95cc-11e9-8668-c41d38a49083.png)
![image](https://user-images.githubusercontent.com/5010445/59973079-bdb2f600-95cc-11e9-9f76-66d9d57ca486.png)

如第一张，volume和shell连接master都有这个问题，第二张是master启动的日志

**Comment by chrislusf** [comment]
use ip 10.10.10.154 instead of localhost to talk to the master.

**Comment by kakazuo** [comment]
请帮忙看一下第二张图片，选择leader应该是出了问题

**Comment by chrislusf** [comment]
1. use ip 10.10.10.154 instead of localhost to talk to the master.
2. what's the problem?
