### ISSUE TITLE
通过内网地址访问不到文件

### ISSUE THREAD

**Issue by kakazuo** [chrislusf/seaweedfs#990]
@chrislusf 你好，
我的服务器有一个公网地址，一个内网地址，
通过公网我可以访问到文件，但是通过内网我访问不到这个文件，当时这个文件是通过公网地址来存贮的
您能帮忙看一下可能的原因是什么吗

**Comment by chrislusf** [comment]
can not help without details.

**Comment by kakazuo** [comment]
![image](https://user-images.githubusercontent.com/5010445/60037390-f85b8200-96e3-11e9-8b2f-38ee45093a5f.png)
这是访问时候的日志

**Comment by kakazuo** [comment]
![image](https://user-images.githubusercontent.com/5010445/60037715-e5957d00-96e4-11e9-9a32-4278c8046e2c.png)
curl一直停在那里，其他的应用都可以正常的返回

**Comment by chrislusf** [comment]
the log shows no errors.

The system does not know intranet or internet. There are no difference.
