### ISSUE TITLE
Filer High CPU

### ISSUE THREAD

**Issue by momosnn** [chrislusf/seaweedfs#996]
Hi Chris, thanks for all the effort you've put into creating seaweefs.

I'm having an issue with the Filer during a long run. I'm attempting to load 100 million compressed BLOBs (~30-40K each) into a single Volume server via the Filer API.

I have 16 concurrent client processes which are sending a combined load of about 10,000 BLOB's per minute (165/second). So the load is pretty low.

Everything runs fine for several hours with low CPU. I see CPU usage on the Filer of about 10%. Sometimes it spikes to 20-30% but not for long. But after the first 6 hours with 10 million BLOBs the CPU sits on a constant 110-140% under top (depending on how many clients I have running). 

When I pause the clients the Filer CPU immediately drops to 0%. I'm not seeing much CPU used by the Volume process even when the Filer is under full load.

If I debug the client and step through a single upload, I can see on the server the CPU spikes to >10%. And then quickly maxes out if I just let it run.

Is the CPU load I'm seeing normal? This is the first time I've used Filer, usually just Volume server. Filer is not really usable with such high CPU.

For my Filer keys I'm using real wold URLs. So the keys are pretty long with quite a few paths. And the keys will have lots of "files" per "directory". Will this slow things down?

Is there anything you can suggest that might be the problem? Do longer keys or many files require a lot more CPU? My BLOB's are VERY compressed already using a non-standard algorithm, is seaweedfs trying to re-compress these?

I don't really know how to debug GO and I'm not a linux expert so I'm not sure how much more info I can provide.

**System Setup**
All nodes running FreeBSD 11,2-RELEASE. Disks are ZFS RAIDz2 (non production). Low-spec modern hardware, dual core.

2 Volume servers but Filer collection is on one Volume server only. 

Filer is running on same node as the Volume server that contains the target collection. Almost no CPU usage for the Volume server.

Master server running on other node, no CPU load.

Clients are running from a Windows box using a custom C# client. Basic REST commands.

**Expected behavior**
Long run expected to continue to use modest CPU as number of files grow.

**Comment by chrislusf** [comment]
thanks for the details! please show the version, the command lines, and maybe the filer.toml file you used.

If you are using the latest version, you can also collect metrics following https://github.com/chrislusf/seaweedfs/wiki/System-Metrics

**Comment by momosnn** [comment]
Sorry. Thanks so much for the fast reply. I'll look into using the metrics. It's currently running a single client at 3.7 uploads/second and CPU sits at 93-105%.

At first I had v1.36 but then upgraded "1.38 freebsd amd64" during the run. And still high CPU on resume.

I forgot to mention also that I pre-allocated 164 30GB volumes (using the "rack=NODE_B" param to bind them to a single Volume node) before the run.

I'm starting each service individually using its own startup script. I've renamed the "weed" binary for each service. They all run as "seaweed" user. Volume data is stored on local HDD (new Iron Wolf sata disks).

Filer and NODE_B Volume share same public IP.


NODE_A (master)
/usr/local/seaweedfs/bin/weed-master master -mdir="/node_a/assets/seaweedfs/seq/" -ip=10.10.10.60 -port=9333 -ip.bind=10.10.10.60 -whiteList={PRIV_LAN_IPS},127.0.0.1 -pulseSeconds=15 -volumePreallocate=false -volumeSizeLimitMB=30000


NODE_B (volume-2)
/usr/local/seaweedfs/bin/weed-volume volume -dir=/node_b/assets/weed/volumes -dataCenter=DEV1 -rack=NODE_B -max=256 -images.fix.orientation=false -ip=node_b.local-domain.com -port=9339 -port.public=8080 -mserver=10.10.10.60:9333 -pulseSeconds=15 -whiteList={PRIV_LAN_IPS},127.0.0.1 -index=leveldb


NODE_B (filer)
/usr/local/seaweedfs/bin/weed-filer filer -collection=global_blobs -dataCenter=DEV1 -maxMB=32 -ip=10.10.10.70 -port=8888 -port.readonly=8090 -master=10.10.10.60:9333 -dirListLimit=100000 -disableDirListing=false

**Comment by chrislusf** [comment]
Looks like you did not configure the filer.toml file and only used the default.

Please check 
https://github.com/chrislusf/seaweedfs/wiki/Filer-Setup

And choosing a filer store:
https://github.com/chrislusf/seaweedfs/wiki/Directories-and-Files#filer-store

**Comment by momosnn** [comment]
Is there something wrong with using leveldb as the Filer store? Are you saying I should use leveldb2 instead?

**Comment by momosnn** [comment]
Okay so I do have a "filer.toml" (Filer won't start without finding one). I have attached it as .txt but there's nothing much other than the default.

[leveldb]
# local on disk, mostly for simple single-machine setup, fairly scalable
enabled = true
dir = "/assets/weedfs/filer"



[filer.toml.txt](https://github.com/chrislusf/seaweedfs/files/3342229/filer.toml.txt)

**Comment by momosnn** [comment]
So I decided to test the "leveldb2" store and I've been dumping metadata using "weed shell" for the past 9 hours. And it's only 5% through (going by the size of the dump/backup file - but maybe it compresses 
to much less than the source data directory). 

So if that's correct it's only dumping at around 26 file entries per second and still using 130% CPU.

Would you expect to see faster than this?

I also move the Filer metadata to an NVMe drive, which may have helped a little but still same CPU.

Is there a way to quiet the text trace output, I assume this slows the dump a little.

**Comment by momosnn** [comment]
Also if I try to use leveldb2 - changing by filer.toml to

> [leveldb]
enabled = false
dir = "/ssd_temp/filer"

> [leveldb2]
enabled = true
dir = "/assets/weedfs/filer" 


I get failed Filer startup with message...

> Supported filer stores are:
    cassandra
    leveldb
    memory
    mysql
    postgres
    redis_cluster
    redis


The output from ./weed version is "version 30GB 1.38 freebsd amd64" - so I assume I'm running the correct version. Is there any change that this change wasn't included in the FreeBSD build?

**Comment by chrislusf** [comment]
The slow export seems confirming the leveldb store is slow for the meta operations.

please wait for the 1.39 release, which is being built as of now.

**Comment by chrislusf** [comment]
Maybe you can share the filer metadata to debug.

**Comment by momosnn** [comment]
Thanks Chris. I'll try 1.39 first and report back.

**Comment by momosnn** [comment]
Hi. Are you planning to release the builds for 1.39? 
Thanks.

**Comment by chrislusf** [comment]
Will close if no more updates.

**Comment by chrislusf** [comment]
Latest version is 1.41

**Comment by momosnn** [comment]
Hey Chris, I've still only managed to load in 1.5TB of data so far. 

I can confirm that the leveldb2 metadatastore consumes a LOT less CPU. The issue was still present in v1.39 (but with 40% CPU instead of 130%). I was also seeing long delays of about 12 seconds fore each request during one of my runs (when I performed a lot of overwrites on the same set of files). So looks like there was some kind of contention issue.

v1.40 seems to have fixed the high CPU problem so I think you can close this issue. You fixed another bug with the file listings and hashes also. Thanks for all your effort.

I've had some problems trying to get my clients to push through with maximum throughput. I'm assuming it's not SeaweedFS's fault but probably my disks or the database. I'll report back if I find anything.

Thanks again.

**Comment by momosnn** [comment]
Just quickly, is there any way with Filer to list only the directories under a path rather than files and directories? Otherwise I have to iterate through thousands of pages just to find a few sub directories.

Could you also add to the wiki the command to rename a directory? I've seen it mentioned in a few places but have never seed the actual API endpoint.

**Comment by chrislusf** [comment]
The long delays should be from compaction. They can be reduced by using `weed volume -index=leveldb`

> Just quickly, is there any way with Filer to list only the directories under a path rather than files and directories?

Not, as of now.

> Could you also add to the wiki the command to rename a directory?

Not implemented yet. It was there before, but later removed. See https://github.com/chrislusf/seaweedfs/issues/954
