### ISSUE TITLE
Introduced bug in ParseServerToGrpcAddress

### ISSUE THREAD

**Issue by momosnn** [chrislusf/seaweedfs#998]
Hi Chris, I think there's an issue in the new release with the Volume to Master heartbeat. It seems to be prepending a "1" character in the port number. So it's attempting to call master IP port "19333" instead of "9333".

Think it's something to do with this change line 96 in ParseServerToGrpcAddress(). 

port, parseErr := strconv.ParseUint(hostnameAndPort[1], 10, 64)
port, parseErr := strconv.ParseUint(server[colonIndex+1:], 10, 64)

**Comment by momosnn** [comment]
Heartbeat seems to work locally. So is master server listening on more than port "9339" ?

**Comment by momosnn** [comment]
Think I only noticed because of firewall rules.

**Comment by chrislusf** [comment]
this is expected.

**Comment by momosnn** [comment]
It's expected to not work?? I can no longer start volume servers from other nodes.

Are you saying that Master server now requires port "9333" AND port "19333" ?

**Comment by chrislusf** [comment]
working as expected. requiring both 9333 and 19333.

**Comment by chrislusf** [comment]
Here you can see the full list of ports

https://github.com/chrislusf/seaweedfs/blob/master/docker/Dockerfile
